### ISSUE TITLE
Exporting collections with multi-part file 

### ISSUE THREAD

**Issue by hannesgeodan** [a85/POSTMan-Chrome-Extension#6342] opened 2019-04-23 08:10 UTC
**Describe the bug**
Exporting collections with file-uploads produces empty values for the given file-location.

**To Reproduce**
1. Create a POST request with Body 'form-data' and key 'fileX', type 'file' and set value to a file on your disk
2. Click on 'save' to save the request in a collection (create a new collection for clarity)
3. Right-click on the new collection and click 'export'.
4. Choose a version: all versions produce this unexpected result
5. Open the exported json and find the 'fileX' part. Assert that the selected file does not show up.

**Expected behavior**
I expect that the selected filepath is exported. The unexpected: In the exports (all version/formats) I see an empty path field. The name (fileX) and the type (file) show up, but not the location. See this example for v2.0.1:

	"formdata": [
		{
			"key": "fileX",
			"type": "file",
			"src": ""
		}
	]

We would expect something like this:

	"formdata": [
		{
			"key": "fileX",
			"type": "file",
			"src": "/home/me/directory/file_to_be_uploaded.txt"
		}
	]

or 

	"formdata": [
		{
			"key": "fileX",
			"type": "file",
			"src": "file_to_be_uploaded.txt"
		}
	]

**App information (please complete the following information):**
 - App Type Native app
 - Postman Version tested on: 7.0.9, but also the version before that, export version 2.0.1
 - OS: tested on Ubuntu

**Additional context**
We found this unexpected behaviour while using the paid Postman Workspace. I reproduced the issue on my local workspace as well. We use the exports to run Newman. This is not possible for file uploads in the current situation.

**Comment by saswatds** [comment] 2019-04-23 08:23
@hannesgeodan the issue is that we have not been storing file path's in the app due to security and interoperability reasons.
We are almost there at providing a better way to solve this problem.

You can follow this master thread #4320 , which aims to solve the problems of file path storage in the app completely.

We regret the inconvenience caused.
Kindly follow the above-mentioned thread for updates.

Thank you!

**Comment by hannesgeodan** [comment] 2019-04-23 08:45
Thankyou @saswatds,
After reading (parts of) #4320 I'm not convinced this will work soon. 
Do we have other options as a paying customer?
Kind regards,
Hannes

**Comment by shamasis** [comment] 2019-04-23 10:44
Look out for the canary releases within next month and a half. Closing issue as duplicate.

**Closed as completed by shamasis** 2019-04-23 10:44 UTC
Labels: feature, duplicate, product/runtime
