### ISSUE TITLE
Black screen on standalone app in Virtualbox Ubuntu 16.04 VM with accelerate3d enabled

### ISSUE THREAD

**Issue by edwardmlyte** [a85/POSTMan-Chrome-Extension#2979] opened 2017-04-27 13:56 UTC
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Stnadalone linux app
 3. OS details: ubuntu 16.04
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Always been there
 6. Expected behaviour: Postman opens
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
From terminal execution of Postman:

`~ () $ /opt/Postman/Postman 
[2926:0427/145308:ERROR:texture_manager.cc(2971)] [.DisplayCompositor-0x1ff337883500]GL ERROR :GL_INVALID_ENUM : glTexImage2D: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.CompositorWorker-0x1ff337882e00]GL ERROR :GL_INVALID_ENUM : GLES2DecoderImpl::DoBindTexImage2DCHROMIUM: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.CompositorWorker-0x1ff337882e00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
OpenGL Warning: You called glBindTexture with a target of 0xde1, but the texture you wanted was target 0x8513 [1D: de0 2D: de1 3D: 806f cube: 8513]
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2295)] [.CompositorWorker-0x1ff337882e00]GL ERROR :GL_INVALID_OPERATION : ScopedTextureBinder::ctor: was unhandled
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.CompositorWorker-0x1ff337882e00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2295)] [.CompositorWorker-0x1ff337882e00]GL ERROR :GL_INVALID_OPERATION : ScopedTextureBinder::ctor: was unhandled
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.CompositorWorker-0x1ff337882e00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.CompositorWorker-0x1ff337882e00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.CompositorWorker-0x1ff337882e00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.CompositorWorker-0x1ff337882e00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.CompositorWorker-0x1ff337882e00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:texture_manager.cc(2971)] [.RenderCompositor-0x18a860b56700]GL ERROR :GL_INVALID_ENUM : glTexImage2D: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_ENUM : GLES2DecoderImpl::DoBindTexImage2DCHROMIUM: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2295)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_OPERATION : ScopedTextureBinder::ctor: was unhandled
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145308:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145309:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145309:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145309:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145309:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145309:ERROR:gles2_cmd_decoder.cc(2291)] [.RenderWorker-0x18a860b58a00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
[2926:0427/145310:ERROR:gles2_cmd_decoder.cc(2291)] [.CompositorWorker-0x1ff337882e00]GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
OpenGL Warning: You called glBindTexture with a target of 0xde1, but the texture you wanted was target 0x8513 [1D: de0 2D: de1 3D: 806f cube: 8513]`

In  virtualbox VM, enable accelerate3d. Start VM, open postman.

**Comment by Flaxscrip** [comment] 2017-04-28 13:13
Same issue with brand new Ubuntu 16.04 installation on Windows 10 VirtualBox Host.

**Comment by thinkbigthings** [comment] 2017-04-30 09:32
Same setup, same issue here.

**Comment by mwaltersva** [comment] 2017-05-16 20:41
+1 Windows 10 host, Ubuntu 16.04 in virtualbox

Edit: The "chrome app" works just fine under the same circumstances

**Comment by dschwinn** [comment] 2017-06-01 13:15
I'm having the same issue.  I think it started after I installed Guest Additions.

Confirmed: removing Virtual Box Guest Additions resolved the issue

**Comment by chriswhite199** [comment] 2017-06-08 13:50
Somewhat a workaround in the short term - execute Postman with the `--disable-gpu` flag.

Update your `/usr/share/applications/Postman.desktop` file to include this flag:

    Exec="/opt/Postman/Postman" --disable-gpu %f

After the initial load, you'll probably need to Alt-Tab away and back again to get the screen to refresh, but this no longer trashes my entire UI session when running Postman in VB with enable 3d accel.

**Comment by ScottMorris** [comment] 2017-11-08 20:00
I'm trying to run Postman on Linux Mint 18.2 and am getting a black screen when I launch the application.  I've tried launching it with `--disable-gpu` with no prevail.  It looks like an [electron issue](https://github.com/electron/electron/issues/4380) relating to this one is still open, however my notebook as an Intel HD graphics GPU.

Have anyone found any other workarounds?

My environment is,
* OS: Linux Mint 18.2
* Guest HW: VMWare Player 12.5.7 build-5813279
* Host: Windows 10 x64

Here is what I get when I launch Postman,
![launching postman - linux mint 18 2](https://user-images.githubusercontent.com/404967/32571674-43224e94-c496-11e7-8d85-b13f9834878b.png)

**Comment by SamvelRaja** [comment] 2018-06-29 13:48
Closing this in-favor of https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621 workaround.

**Closed as completed by SamvelRaja** 2018-06-29 13:48 UTC
Labels: bug
