### ISSUE TITLE
Option need to NOT show http verb in tab title

### ISSUE THREAD

**Issue by piltdown64** [a85/POSTMan-Chrome-Extension#5476] opened 2018-11-05 09:38 UTC
I was auto-updated to 6.4.4 and found that the http verb now takes pride of place in the tab title to the practical exclusion of everything else so that I pretty much have to guess which tab I want.  Please make a point of having UI changes such as this be able to be switched on/off via settings.

![screen shot 2018-11-05 at 09 32 43](https://user-images.githubusercontent.com/5835423/47990094-8dbaef00-e0de-11e8-9a03-991e16c79990.png)

**Comment by numaanashraf** [comment] 2018-11-05 20:23
Duplicate of #5310

**Closed as completed by numaanashraf** 2018-11-05 20:23 UTC
