### ISSUE TITLE
Parameter not parsing correctly - Broken since after v4.4.3

### ISSUE THREAD

**Issue by eholley** [a85/POSTMan-Chrome-Extension#2427] opened 2016-10-20 15:56 UTC
1. Postman Version: 4.8.0
2. App (Chrome app or Mac app): Mac
3. OS details: 10.12 Sierra
4. Is the Interceptor on and enabled in the app: Doesn't matter
5. Did you encounter this recently, or has this bug always been there: Bug since after 4.4.3
6. Expected behaviour: Expect to receive a json packet.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   
   GET
   http://cbd46b77.cdn.cms.movetv.com/cms/publish3/asset/info/:asset_id_or_guid.json
   09:47:03.625
   Request Headers:
   cache-control:"no-cache"
   Postman-Token:"51ae24c0-98b9-4135-9649-1932aa648354"
   User-Agent:"PostmanRuntime/3.0.1"
   Accept:"_/_"
   Host:"cbd46b77.cdn.cms.movetv.com"
   cookie:"__cfduid=d265c8fc819f490ad7c91e05d735d77a61463775140"
   accept-encoding:"gzip, deflate"
   Response Headers:
   content-length:"32"
   server:"IPoAC/1.1.49"
   access-control-allow-headers:"Content-Type, If-Modified-Since, If-None-Match"
   access-control-allow-methods:"GET, HEAD"
   access-control-allow-origin:"*"
   access-control-max-age:"604800"
   app-cache:"HIT"
   app-cache-hits:"2"
   app-cache-host:"cg5-acache004"
   xid-deliver:"313586475"
   xid-fetch:"313586476"
   date:"Thu, 20 Oct 2016 15:47:03 GMT"
   connection:"keep-alive"
   Response Body:
   No such asset: :asset_id_or_guid
   404
   233 ms
8. Screenshots (if applicable)

There is a disconnect when parsing URL parameters. In v4.4.3, this URL: 
    {{cms_host}}/cms/publish3/asset/info/:asset_id_or_guid.json
converts to:
    http://cbd46b77.cdn.cms.movetv.com/cms/publish3/asset/info/10345046.json

In versions after 4.4.3, the same URL converts to:
    http://cbd46b77.cdn.cms.movetv.com/cms/publish3/asset/info/:asset_id_or_guid.json
As the console log shows, the "asset_id_or_guid" parameter is not substituted.

However, in all versions, the Code Generator parses it correctly:
    GET /cms/publish3/asset/info/10345046.json HTTP/1.1
    Host: cbd46b77.cdn.cms.movetv.com
    Cache-Control: no-cache
    Postman-Token: 1a440917-9f3e-077e-27b6-3c44009add0e

**Comment by sdnts** [comment] 2016-10-21 09:36
@eholley I was able to reproduce this, we'll get on a fix. I discovered that this happens only in case the variable name is succeeded by a special character. (`.` in your case)
Till then, you can do one of two things:
1. Use environment variables. They behave in a similar fashion, and are much more versatile (can be used anywhere, bodies, test scripts, etc.)
2. Append the `.json` to the value field itself, so it resolves correctly.

**Comment by curtisgibby** [comment] 2017-03-21 23:17
Any update on this? I'm having the same problem with `/noun/:id.json` type URL formats. Thanks for the workaround, but if you could get it working "right", that would be much appreciated!

**Comment by eholley** [comment] 2017-04-12 19:21
The bug is still present in 4.10.7. Which, is very frustrating because I can't upgrade passed 4.4.3. The workaround is messy and is inconvenient in scripts. Using environment variables is not an option. 

@madebysid "this happens only in case the variable name is succeeded by a special character. (. in your case)"

**The bug isn't due to the dot character. The bug is in the "Send" behavior. The "Code" button works correctly.**

Scenario:
- URL = "{{cms_host}}/cms/publish3/asset/info/:asset_id_or_guid.json"
- cms_host = "cbd46b77.cdn.cms.movetv.com"
- asset_id_or_guid = "10345046"

Pressing Send button sends out this wrong request:
- URL http://cbd46b77.cdn.cms.movetv.com/cms/publish3/asset/info/:asset_id_or_guid.json

Pressing the Code button yields the correct request for every language type (HTTP shown here):
- GET /cms/publish3/asset/info/10345046.json HTTP/1.1
- Host: cbd46b77.cdn.cms.movetv.com
- Cache-Control: no-cache
- Postman-Token: 304d9c84-39ea-bd05-b357-364c4db30604

**Looks like the Send button function is not calling the same translation code that the Code button calls.**

**Comment by ravimisra** [comment] 2018-02-28 07:18
A similar issue is with "/" char.
If the URL is of the format:
https://:api_host/admin/product.json
converted to:
https:/example.com/admin/product.json
instead of:
https://example.com/admin/product.json
though can be easily resolved by prefixing a "/" in the parameter value, but as @curtisgibby mentioned, if you could get it working "right", that would be much appreciated!

**Comment by Kanmuri** [comment] 2018-03-31 18:55
I have the same issue with path variables that used to work. The variable is in the format ":client.cfc" (e.g. when the variable is set to "someClient", it should render as "someClient.cfc").

From my understanding of how environment variables work, they will not work for my use case, as the value does not vary per environment.

I am currently using the workaround of putting the suffix in the variable (e.g. changing the variable to ":clientcfc" and the variable set to "someClient.cfc"), but I would greatly appreciate this being fixed.

**Comment by timdmackey** [comment] 2018-11-29 09:57
As I have explained in response to [Issue #1428](https://github.com/postmanlabs/postman-docs/issues/1428#issuecomment-442773070), the recommendation of using environment, global, or collection variables does not cover certain situations where path variables would be necessary.

**Comment by itsjavi** [comment] 2018-12-03 19:46
any update on this?

what about using the variable delimiter for name start and name end, so Postman won't have to do presumptions?

e.g.

**current situation**
`/foo/:bar` (works)
`/foo/:bar.baz` (does not work)

**proposal**

`/foo/:bar:` (works)
`/foo/:bar:.baz` (works)
`/foo/:bar.xyz:` (works, variable name is `bar.xyz`)
`/foo/:bar.xyz:.baz` (works, variable name is `bar.xyz`)
`/foo/:bar.xyz::abc:.baz` (works, variable name is `bar.xyz`, there is another variable called `abc`)

**Comment by itsjavi** [comment] 2018-12-03 19:52
for now, a workaround would be to use the path extension as another param:

e.g. `https:/example.com/foo/123.json` -> `https:/example.com/foo/:id:ext`

`https:/example.com/admin/product.json` -> `https:/example.com/admin/product.json`

**Comment by jmurowaniecki** [comment] 2019-01-18 15:46
Hello there!

Somebody can tell me if it's possible to use multiple **optional** uri segments like `/user(/:id|:username)` (or, like itsjavi proposed `/user/:id::username:`) ?

I'm planning to use **:id** or **:username** - both are optional since when nothing is informed the response are the user logged.

Now I'm using this way:

```json
"name": "user(/:id|:username)",
"item": [
    {
        "name": "/user",
        "request": {
            "method": "GET",
            "header": [],
            "body": {
                "mode": "raw",
                "raw": ""
            },
            "url": {
                "raw": "/user",
                "path": [
                    "user"
                ]
            },
            "description": "request logged user data."
        },
        "response": []
    },
    {
        "name": "/user/:id",
        "protocolProfileBehavior": {
            "disableBodyPruning": true
        },
        "request": {
            "method": "GET",
            "header": [
                {
                    "key": "Content-Type",
                    "name": "Content-Type",
                    "type": "text",
                    "value": "application/x-www-form-urlencoded"
                }
            ],
            "body": {
                "mode": "file",
                "file": {}
            },
            "url": {
                "raw": "/user/:id",
                "path": [
                    "user",
                    ":id"
                ],
                "variable": [
                    {
                        "description": "User ID.",
                        "key": "id",
                        "value": "42"
                    }
                ]
            },
            "description": "request using id."
        },
        "response": []
    },
    {
        "name": "/user/:username",
        "protocolProfileBehavior": {
            "disableBodyPruning": true
        },
        "request": {
            "method": "GET",
            "header": [
                {
                    "key": "Content-Type",
                    "name": "Content-Type",
                    "type": "text",
                    "value": "application/x-www-form-urlencoded"
                }
            ],
            "body": {
                "mode": "file",
                "file": {}
            },
            "url": {
                "raw": "/user/:username",
                "path": [
                    "user",
                    ":username"
                ],
                "variable": [
                    {
                        "key": "username",
                        "value": "douglasadams",
                        "description": "Username duh."
                    }
                ]
            },
            "description": "request using username."
        },
        "response": []
    }
]
```

But the idea is replace by
```json
"name": "/user",
"item": [
    {
        "name": "/user(/:id|:username)",
        "request": {
            "method": "GET",
            "header": [
                {
                    "key": "Content-Type",
                    "name": "Content-Type",
                    "type": "text",
                    "value": "application/x-www-form-urlencoded"
                }
            ],
            "body": {
                "mode": "raw",
                "raw": ""
            },
            "url": {
                "raw": "/user(/:id|:username)",
                "path": [
                    "user",
                    [":id", ":username"]
                ],
                "variable": [
                    {
                        "description": "User ID.",
                        "key": "id",
                        "value": "42"
                    },
                    {
                        "key": "username",
                        "value": "douglasadams",
                        "description": "Username duh."
                    }
                ]
            },
            "description": "request logged user data."
        },
        "response": []
    }
]
```

What do you think? It might be possible?

Or maybe are easier to still using duplicate item and change the uri with proper descriptions :thinking: ??

**Comment by ghost** [comment] 2019-03-06 22:29
Wow, this is still broken, three years later.  Luckily, it only impacts **every single API endpoint** in our application.

**Comment by Kanmuri** [comment] 2019-03-30 20:28
As a follow-up to my previous comment, I have an additional example scenario.
I have a path that includes "/:clientName/:clientName.cfc".
Before this regression, I could use just one variable "clientName", now I have to use two variables, "clientName" and "clientNameCfc", because the second instance now has to have the ".cf" in it.

And to echo somewhat what @timdmackey said, this is an instance where global, environment, or collection variables would not work. This needs to be easily changeable per request on the request itself, hence the use of path variables.

I'm not necessarily attached to the exact current syntax of path variables as they are now, I just want something that works like path variables used to work (so that I can do stuff like ":clientName.cfc" and the :clientName part gets replaced with the value in :clientName) and can be easily adjusted at a finer grain than the collection level. I need to be able to adjust it per individual request in a collection, and that is what the path variables allow for.

**Comment by codenirvana** [comment] 2019-06-13 11:56
This is fixed in the latest version of the Postman App (v7.2.0).

**Closed as completed by codenirvana** 2019-06-13 11:56 UTC
Labels: bug, product/runtime

**Comment by antdking** [comment] 2019-09-30 14:41
This is broken again, as of v7.8.0, Running on Linux.

Unknown if this is broken in previous versions too:

![image](https://user-images.githubusercontent.com/2099618/65889146-a4260500-e398-11e9-84ac-8cf1f1056b7d.png)

**Comment by rober710** [comment] 2019-11-06 23:08
Same here for me, broken in 7.10.0 running on Linux.

**Comment by Glideh** [comment] 2019-12-20 12:18
Same issue in 7.13.0 (linux 4.15.0-72-generic / x64)

**Comment by Alamei** [comment] 2020-02-06 20:55
I'm experiencing the same behavior on 7.17.0 (Win10 x64). Should this issue be re-opened, or should a new issue be created?

**Comment by szogoon** [comment] 2020-03-13 10:20
What is the status of this?
