### ISSUE TITLE
how to get the saved response in Testscript

### ISSUE THREAD

**Issue by mohamedmubarish-s-19801** [a85/POSTMan-Chrome-Extension#2557] opened 2016-12-15 10:45 UTC
Hi,
I am using Postman for RestApi Testing. I am trying to compare JSON response structure with the old JSON response to identify any breakage. For that I need the saved response (previously saved response) to compare with the current response. how to get the saved response into testscript, so that I can use that old saved response to check the structure change? or any other way is appreciable?

Thanks in Advance!

**Comment by mohamedmubarish-s-19801** [comment] 2016-12-16 05:22
Hi,
 Any update or solution on this. This is of higher importance for us. Any quick response is much appreciable.

**Comment by vegetableman** [comment] 2016-12-16 07:05
@SMohamedMubarish You could use environment variables to save the response and then compare with the current one. Check out the docs for the api : https://www.getpostman.com/docs/sandbox

**Comment by mohamedmubarish-s-19801** [comment] 2016-12-16 11:17
@vegetableman Thank you!
 I know that solution, but i want a solution other than maintaining the old response in Environment or global variable.
In our case, we have 1000s of restapi call and its difficult to maintain and manage all the old responses as environment variable. It would be better, if I am able to maintain with the testscript or  restapi call?
Any other solution is appreciable!

**Comment by vegetableman** [comment] 2016-12-16 12:42
@SMohamedMubarish Thanks for sharing your use-case 👍 . We will take this up as a feature request and will keep you posted on this thread ^_^.

**Comment by shamasis** [comment] 2016-12-27 23:03
closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/1262

**Closed as completed by shamasis** 2016-12-27 23:03 UTC
Labels: feature

**Comment by rishulmatta** [comment] 2018-06-07 07:09
Has this feature been developed? Can we use the saved example in the test scripts?
