### ISSUE TITLE
I think the redirection should be reflected in the PostMan Console like Chrome Network Panel, so it can be discovered easily. It shows only one rather two for now.

### ISSUE THREAD

**Issue by gaohuia** [a85/POSTMan-Chrome-Extension#5522] opened 2018-11-13 03:54 UTC
_Originally posted by @gaohuia in https://github.com/postmanlabs/postman-app-support/issue_comments#issuecomment-438124787_

**Comment by numaanashraf** [comment] 2018-11-14 00:09
Duplicate of #4474

**Closed as completed by numaanashraf** 2018-11-14 00:09 UTC
