### ISSUE TITLE
Spamming Duplicate creates orphaned requests, shown only in docs page

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5463] opened 2018-10-31 20:40 UTC
**Docs page:**
https://documenter.getpostman.com/view/5392110/RzZ3N3Uc#5ea6b10c-997d-4791-949e-f61c92635e12

**Issue:**
On the left-hand nav sidebar, the two requests not in folders do not appear in my Postman app:
`GET Example request Copy Copy`
`GET Example request Copy Copy Copy`

<img width="267" alt="screen shot 2018-10-31 at 1 13 03 pm" src="https://user-images.githubusercontent.com/43283131/47815896-d35a6f00-dd0e-11e8-899c-88740cfb1587.png">

Strange (maybe relevant?) note, is that when I duplicate the Collection in question (using CMD+D), the request count changes from 74, to 72:

<img width="265" alt="screen shot 2018-10-31 at 1 17 14 pm" src="https://user-images.githubusercontent.com/43283131/47816326-1406b800-dd10-11e8-8fca-b875d37b3989.png">

The published docs page for the duplicated collection shows no orphaned requests:
https://documenter.getpostman.com/view/5392110/RzZ3N3ri

**Steps to reproduce:**
- Create a new Collection, and add a single request to it. Select the request, then press `CMD+D` over and over as quickly as your can (I did ~8 presses / second) . Make about ~20 duplicates.
- Create a folder in the Collection you made, and drag all requests you see into the folder.
- Click `View in web` on the Documentation tab for the Collection to see which requests are not in the folder you created. These are the orphaned requests which do not show in the app.

**Comment by numaanashraf** [comment] 2019-04-11 04:44
Duplicate of #5074

**Closed as completed by numaanashraf** 2019-04-11 04:44 UTC
Labels: bug, postman-data
