### ISSUE TITLE
Feature request: make it very clear when working with a PROD environment

### ISSUE THREAD

**Issue by nibras85** [a85/POSTMan-Chrome-Extension#1098] opened 2015-06-01 17:45 UTC
This is more of a feature request than an issue. 

It would be really nice if POSTMan warned me when I'm working with a PROD environment. 

![image](https://cloud.githubusercontent.com/assets/11825028/7919105/fc22dcca-0863-11e5-881f-694c0c1fc87d.png)

![image](https://cloud.githubusercontent.com/assets/11825028/7919145/44c188aa-0864-11e5-8dbf-e41704aef908.png)

Another tool I use (LinqPad) enables me to do this.

![image](https://cloud.githubusercontent.com/assets/11825028/7919133/2b5b5058-0864-11e5-8f73-9cbfd794f8c7.png)

![image](https://cloud.githubusercontent.com/assets/11825028/7919157/5cefe5de-0864-11e5-92c7-a8cb431998b8.png)

Even if its a color or text that grabs my attention and prevents me from mistakenly targeting PROD.

**Comment by a85** [comment] 2016-12-21 16:52
Closing as duplicate of #903

**Comment by a85** [comment] 2016-12-21 16:52
Should be solved when we introduce colors for environments.

**Closed as completed by a85** 2016-12-21 16:52 UTC
Labels: feature
