### ISSUE TITLE
Show the collection name in the request tab

### ISSUE THREAD

**Issue by clairestreb** [a85/POSTMan-Chrome-Extension#7857] opened 2019-12-30 22:55 UTC
If all collections are collapsed, I do not know which collection my request belongs to.

It should be simple to show the collection name in the request's tab

**Comment by vkaegis** [comment] 2020-02-17 07:51
Duplicate of #8006.

Will be tracking all issues related to collection references / navigation there, so closing this for now.

**Closed as completed by vkaegis** 2020-02-17 07:51 UTC
Labels: feature, product/runtime
