### ISSUE TITLE
pm.* API for network information

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#9904] opened 2021-05-04 07:32 UTC
**Is your feature request related to a problem? Please describe.**
Since Aug 2020 it is possible to view inside Postman some network details. 

https://blog.postman.com/see-network-info-for-postman-api-requests/

This information is also logged. 

![image](https://user-images.githubusercontent.com/1197635/116972590-85e26280-acbb-11eb-862e-fbdd8ab5a254.png)

**Describe the solution you'd like**
Network information available through the pm.* API. 

**Describe alternatives you've considered**
This information can only be inspected manually.

**Comment by praveendvd** [comment] 2021-05-05 23:13
https://github.com/postmanlabs/postman-app-support/issues/9689#issue-823455580

An feature request is already in progress @DannyDainton  @vdespa  ❣️

**Comment by DannyDainton** [comment] 2021-05-06 11:35
Closing as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9689

**Closed as completed by DannyDainton** 2021-05-06 11:35 UTC
Labels: feature, duplicate, product/runtime, sandbox
