### ISSUE TITLE
Assertions don't print actual value if failed

### ISSUE THREAD

**Issue by Ernesto-Maserati-CH** [a85/POSTMan-Chrome-Extension#2554] opened 2016-12-14 13:04 UTC
The test section snippets look like this:

`tests["Status` code is 200"] = responseCode.code === `200;`

If the assertion fails then I only see that it failed, but I don't see in the test result what the actual value has been. Of course I can find this out by looking at the information elsewhere.

To me these test snippets are very rudementary test assertions. That has been done better long time ago by JUnit for instance.

`assertEquals("Status` code", 200, `responseCode.code)`

If it fails it prints automatically not just the expected value but also the actual value.

As nice as Postman looks, I sometimes wonder if the creators of it use it for themselves at all, since a lot of things are missing to ease pain in using it effectively, without repeating yourself for instance.

I would have built into Postman a feature to include your own JavaScript libraries. I guess there must be one for test assertions. Also I would suggest to improve these very rudementary test assertions which don't print the actual value automatically.

My Postman version is 4.9.1, Windows App.

**Comment by vegetableman** [comment] 2016-12-16 07:23
Thanks @Ernesto-Maserati-CH for reporting this issue 👍 .  @shamasis Your thoughts on this?.

**Comment by vegetableman** [comment] 2016-12-16 07:37
Thanks @Ernesto-Maserati-CH for reporting this issue 👍 .

The features mentioned are being work on and would be available early next year. For now, as a workaround for BDD, you could refer this article: http://blog.getpostman.com/2015/09/29/writing-a-behaviour-driven-api-testing-environment-within-postman/

**Comment by Ernesto-Maserati-CH** [comment] 2016-12-16 16:41
Ok, thanks for working on it!

**Comment by shamasis** [comment] 2016-12-27 23:04
duplicate of https://github.com/postmanlabs/postman-app-support/issues/1196

**Closed as completed by shamasis** 2016-12-27 23:04 UTC
Labels: feature
