### ISSUE TITLE
Runner for socket.io doesn't work

### ISSUE THREAD

**Issue by pzur1** [a85/POSTMan-Chrome-Extension#12201] opened 2023-07-30 19:35 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We may add http requests (collection) to runner, but we cannot add socket io collection/ request.

### Steps To Reproduce

1.Write simple socketio request( collection)
2.Open Runner
3.Try add SocketIO to runner

### Screenshots or Videos

![Zrzut ekranu 2023-07-30 213443](https://github.com/postmanlabs/postman-app-support/assets/49210844/7b45bea6-39a0-4997-963d-a24320ff04a8)
![Zrzut ekranu 2023-07-30 213409](https://github.com/postmanlabs/postman-app-support/assets/49210844/fcb26015-3068-49fb-b093-5906643c85d6)

### Operating System

Windows 10

### Postman Version

10.16.3

### Postman Platform

Postman App

### User Account Type

Signed In User

```[tasklist]
### Tasks
```

**Comment by codenirvana** [comment] 2023-08-09 11:56
Duplicate of #12194

**Closed as completed by codenirvana** 2023-08-09 11:56 UTC
Labels: feature, collection-runner, protocol/websocket, product/api-client
