### ISSUE TITLE
Indentation Bug

### ISSUE THREAD

**Issue by Rockthor1106** [a85/POSTMan-Chrome-Extension#13233] opened 2024-10-31 16:14 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Today I updated vs code to the latest version (1.95.0). However, when I performed a request the response is not indented correctly. I tried to reload vs code and also y pc, but it does not fixed that bug. You can see the bug in the following screenshot. I also want to mention that I decided to downgrade the vs code version to the previous one (1.94.2) where the extension is working correctly.
![Captura de pantalla 2024-10-31 111028](https://github.com/user-attachments/assets/8be0ee45-c0bc-4f31-8bc1-b591225b5333)

### Steps To Reproduce

1. Open the extension
2. Select a request
3. Perform the request
4. Check for the response 
5. That's it

### Operating System

Windows

### Postman Version

1.3.0

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by mctunes** [comment] 2024-11-04 22:45
I see this behaviour too with VS Code 1.95.1 and Postman 1.4.1:

![image](https://github.com/user-attachments/assets/feb0a438-50b3-4e5e-8625-1afabd858743)

Just like the OP, downgrading VS Code to 1.94.2 resolved the issue.

**Comment by pankajk07** [comment] 2024-11-06 06:09
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/13230

**Closed as completed by pankajk07** 2024-11-06 06:09 UTC
