### ISSUE TITLE
Native App - Unable to access team workspace - Something went wrong 

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6505] opened 2019-05-15 08:37 UTC
**Describe the bug**
Clicking on a specific team workspace in-app throws the error Something Went Wrong. 

![image002](https://user-images.githubusercontent.com/47351631/57761586-1b1a7400-76fe-11e9-8c6f-78e4c3cf7d67.png)

**To Reproduce**
1. Open the native app
2. Toggle from Personal to Team workspace
3. Select a team workspace from `WORKSPACES YOU CAN JOIN` 
![a](https://user-images.githubusercontent.com/47351631/57763445-a9dcc000-7701-11e9-9523-ad3143c4e24b.png)
4. See error.

**Expected behavior**
Be able to view the workspace and join it. 

**App information (please complete the following information):**
 - App version: 7.0.9
 - OS: 

**Additional context**
- The user is able to access the workspace in the dashboard and see all the collections. 
- The issue happens for **only one specific workspace**. The issue cannot be reproduced with the other team workspace available in the team.
- The user is able to see notifications related to the team workspace in question.
-  Quitting and restarting the app + Sign out / sign back in doesn't help.

**Comment by preethammavin** [comment] 2019-05-15 09:18
@cyrielle-hada can you attach the logs for the user in the internal ticket please

**Comment by doverby0122** [comment] 2019-05-15 19:03
Any ETA on when this could be resolved? Thx - Dustin

**Comment by sujayvenaik** [comment] 2019-05-16 10:21
@doverby0122 
Can you send us the screenshots from 
1. view -> Developer -> Show DevTolls (Shared)
2. view -> Developer -> Show DevTolls (Current View)
as soon as you try to switch to that workspace.

Also just wanted to confirm one thing, the crash happens on the complete and becomes in the unusable state, right?

**Comment by doverby0122** [comment] 2019-05-16 16:12
@sujayvenaik Here are the screenshots from the above instructions, when I try to switch to the work space. 

1. ![Show Dev Tools Dev-Shared](https://user-images.githubusercontent.com/47822082/57869650-7d917400-77d3-11e9-8791-f89ace9d708d.png)

2. ![Show Dev Tools Dev-Current](https://user-images.githubusercontent.com/47822082/57869651-7d917400-77d3-11e9-9c9c-f2085b6caaad.png)

And yes, the crash happens as soon as I switch to the team. But I can still see the above things. These should show the error from when I switch plus the window that appears for each step.

**Comment by sujayvenaik** [comment] 2019-05-16 16:14
@doverby0122 The dev tools that you have opened can we have screenshots by switching to the console tab.

**Comment by doverby0122** [comment] 2019-05-16 16:17
@sujayvenaik Sorry, new user here. So, screenshots of the same thing after I select "View" ->"Show Postman Console", correct?

**Comment by sujayvenaik** [comment] 2019-05-16 16:22
No. Can you check the gif below? Its dev tools -> console. Can we have the screenshots for those.
![devTools](https://user-images.githubusercontent.com/11532114/57870504-d806f080-7824-11e9-8a8e-21a58524bb56.gif)

**Comment by sujayvenaik** [comment] 2019-05-16 16:33
@doverby0122 ^

**Comment by doverby0122** [comment] 2019-05-16 16:59
Right - here are the below @sujayvenaik 
![Show Dev Tools Console Shared](https://user-images.githubusercontent.com/47822082/57872685-38247500-77da-11e9-81d7-9a9ff405dca3.png)
![Show Dev Tools-Console Current](https://user-images.githubusercontent.com/47822082/57872688-38247500-77da-11e9-95a4-faa5767183fd.png)

**Comment by doverby0122** [comment] 2019-05-16 17:01
@sujayvenaik So also one thing to note that upon restarting the app I was force updated to 7.1.0. 

So one thing to note: I can now switch to the group within. However, the only thing that NOW crashes is when I toggle the 'Collections' tab.

**Comment by sujayvenaik** [comment] 2019-05-16 17:06
Hey @doverby0122 
Can you do a screen recording of the issue you are facing with the new v7.1.0 app and send? Also, keep the postman window and the dev tools console open side by side so we can trace your actions and get the error message.

Do scroll the complete dev tools console if it is not fitting in one frame so we can see all logs from top to bottom.

**Comment by doverby0122** [comment] 2019-05-16 17:41
@sujayvenaik I have it, but the file is large and I'm hitting a 10MB file size limit. Is there a way I can get this to you another way?

**Comment by sujayvenaik** [comment] 2019-05-16 17:42
@doverby0122 You can zip and mail it at help@getpostman.com

**Comment by doverby0122** [comment] 2019-05-16 17:44
@sujayvenaik  Done.

**Comment by doverby0122** [comment] 2019-05-16 18:22
@sujayvenaik Actually, maybe not, sorry. I'm trying e-mail and getting kicked back because of a file size limit on our end. Can I share via OneDrive with the same e-mail address as above?

**Comment by preethammavin** [comment] 2019-05-16 18:26
@doverby0122 yes please, send the link to help@getpostman.com.

**Comment by doverby0122** [comment] 2019-05-16 18:35
@preethammavin Sent - and this link: https://ingramcontent-my.sharepoint.com/:u:/p/dustin_overby/EUDW6tBWUbpEjB1bYrc8GyEBHf3CjxTZxqxCzMmdIrmoMA

Should have it, if you miss the e-mail.

**Comment by preethammavin** [comment] 2019-05-16 18:45
@doverby0122 I am unable to open it, would you give access to help@getpostman.com.

**Comment by doverby0122** [comment] 2019-05-16 18:51
@preethammavin I did give access, here let me try another way...

Try this link: https://ingramcontent-my.sharepoint.com/:f:/p/dustin_overby/Etl7b3ayXEhFuykunYvZuSsBYopTGa3iQoUmWpyt4ZgE2Q

This should open a folder and you should see the attachment.

**Comment by preethammavin** [comment] 2019-05-16 19:16
@doverby0122 sorry to re request again, can you give access to preetham@getpostman.com? I am unable to fetch the code required to verify the access.

**Comment by doverby0122** [comment] 2019-05-16 19:27
@preethammavin Sent over again to that e-mail

**Comment by preethammavin** [comment] 2019-05-16 20:02
@doverby0122 got it thanks

**Comment by kamalaknn** [comment] 2019-05-17 05:21
@doverby0122 Thanks for sending us the information.

We were able to pinpoint the root cause of this issue. We will keep this thread updated on the status of the fix.

In the meantime, you mentioned that since 7.1.0 you were able to switch to the workspace but not switch to the collections tab. I'm hoping that unblocks your major workflow. Please let us know if that helps to continue working till we push out a fix.

**Comment by sujayvenaik** [comment] 2019-05-20 17:32
hey @doverby0122 
We have pushed out a fix for this in v7.1.1
Please update to the latest version and let us know if the issue is fixed for you.

**Comment by doverby0122** [comment] 2019-05-21 12:30
@sujayvenaik Success! Thank you!

**Closed as completed** 2019-05-21 15:00 UTC
Labels: bug, sync
