### ISSUE TITLE
+ sign to create new request disappears when there is no more space for request tabs

### ISSUE THREAD

**Issue by JebediahSpringfield** [a85/POSTMan-Chrome-Extension#3194] opened 2017-06-21 15:28 UTC
## App Details:

```
Postman for Windows
Version 5.0.0
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Think it's always been there.

 2. Expected behaviour:
+ sign visible all the time since there is no other way to create requests with the awkward postman gui approach.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Create enough request tabs to fill the tabs area. + signs disappears.

**Comment by SamvelRaja** [comment] 2017-06-22 09:55
@JebediahSpringfield  you just need to keep the cursor in tab header and scroll using your mouse wheel. 
![scroll-up-down](https://user-images.githubusercontent.com/5114052/27428210-02f16610-575f-11e7-9529-78a60b460538.gif)

**Comment by JebediahSpringfield** [comment] 2017-06-22 12:07
Thanks Samvel, however,  what's the point of making us search for a functionality that should be readily available? When I use a tool I'm concerned about productivity and this kind of needless scrolling and clicking really annoys me.  On Jun 22, 2017 5:55 AM, SamvelRaja <notifications@github.com> wrote:@JebediahSpringfield  you just need to keep the cursor and scroll using your mouse wheel.

**Comment by prashantagarwal** [comment] 2018-08-08 07:03
Duplicate of #4869

**Closed as completed by prashantagarwal** 2018-08-08 07:03 UTC
Labels: bug, tabs
