### ISSUE TITLE
Auth Header not in Generated Code

### ISSUE THREAD

**Issue by mdunn-bluefox** [a85/POSTMan-Chrome-Extension#8580] opened 2020-06-03 02:18 UTC
Version 7.25.2
OS X 19.5.0 / x64

Selected the generate code button and everything displays except the auth header.
This was working but suddenly stopped in the past 7 days.

**Comment by shreys7** [comment] 2020-06-03 05:46
Duplicate of #8550

**Closed as completed by shreys7** 2020-06-03 05:46 UTC
