### ISSUE TITLE
POSTMAN desktop app is getting crashed after the latest update.

### ISSUE THREAD

**Issue by bharatup** [a85/POSTMan-Chrome-Extension#5772] opened 2019-01-14 14:18 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

POSTMAN desktop app is getting crashed after the latest update.

**Describe the bug**
After updating postman to latest version 6.7.1 the POSTMAN desktop app is just loading asking to reach out to support. PFB the screenshots
![postman1](https://user-images.githubusercontent.com/33952951/51116017-d9e98480-182f-11e9-8a4e-2e6dbf3af3bb.PNG)

![postman2](https://user-images.githubusercontent.com/33952951/51116027-e1109280-182f-11e9-8e10-eeec5622fcb8.PNG)

**To Reproduce**
1. Update the build from  6.0.1 to 6.7.1 .'
2. Click on desktop app icon
3. App will keep on loading and will throw an error
4. See error in above screenshot

**App information (please complete the following information):**
 - App Type [ Chrome App, Native App]
 - Postman Version [6.7.1]
 - OS: [windows 10]

**Additional context**

**Comment by pbassut** [comment] 2019-01-14 17:18
I'm getting an issue here as well but it's regarding authentication. It's saying the app is having trouble connecting to their authentication service.

**Comment by numaanashraf** [comment] 2019-04-05 09:24
Duplicate of #5591

**Closed as completed by numaanashraf** 2019-04-05 09:24 UTC
Labels: bug, updates
