### ISSUE TITLE
Requests could not complete, seeing "socket hang up" errors

### ISSUE THREAD

**Issue by GuilhermeMLS** [a85/POSTMan-Chrome-Extension#7297] opened 2019-09-10 13:26 UTC
With macOS Mojave, Postman used to stop working sometimes showing the error “Could not get any response” in all requests, however, if I sent lots of identical requests, it came back to working.

Now, with macOS Catalina, Postman has the same error, but isn’t coming back even when I send lots of requests.

![Captura de Tela 2019-09-10 às 09 57 02](https://user-images.githubusercontent.com/17656975/64617754-61829580-d3b5-11e9-8d27-03f5c3944ae9.png)

This error doesn't seem to be happening on Linux.

**Comment by CharlieReitzel** [comment] 2019-09-11 18:43
I'm seeing this on Windows after a recent update.  It was working fine ....  Note, I know the server application is working fine, because requests sent with curl always come back immediately.  Postman seems to work for 1 or 2 requests before it hangs.  But, after that, a restart of Postman is necessary to get another 1 or 2 requests.   I.e. it has stopped being useful.

**Comment by kamalaknn** [comment] 2019-09-12 04:23
@GuilhermeMLS Thanks for reporting this issue.

Unfortunately, we are not able to reproduce this issue on macOS Catalina against endpoints we are testing with. If you could give us the following information, it will help us debug the issue better.

1. Are you seeing failures only for this particular endpoint or all endpoints (e.g. postman-echo.com, google.com)
2. If yes, can you share and endpoint against which we can test

**Comment by GuilhermeMLS** [comment] 2019-09-12 16:48
> @GuilhermeMLS Thanks for reporting this issue.
> 
> Unfortunately, we are not able to reproduce this issue on macOS Catalina against endpoints we are testing with. If you could give us the following information, it will help us debug the issue better.
> 
> 1. Are you seeing failures only for this particular endpoint or all endpoints (e.g. postman-echo.com, google.com)
> 2. If yes, can you share and endpoint against which we can test

Sure! 

1. All endpoints
2. I'm testing against local endpoints, from an API that I'm developing (PHP + Laravel).

However, when I test with Insomnia/cURL, the endpoints are working properly, so I think it's something with Postman.

I mentioned macOS because my co-workers aren't seeing this issue using Ubuntu with the same endpoints.

**Comment by codenirvana** [comment] 2019-09-13 05:47
> 1. All endpoints

@GuilhermeMLS are you getting the same error i.e, `socket hang up` for `http://postman-echo.com/get`?

Can share the curl verbose (`curl -v http://...`) logs for the failing request (your local endpoint)?

**Comment by codenirvana** [comment] 2020-03-11 05:45
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-03-11 05:45 UTC
Labels: bug, blocked/need-info, product/runtime
