### ISSUE TITLE
Postman logo is missing

### ISSUE THREAD

**Issue by lkbn** [a85/POSTMan-Chrome-Extension#7224] opened 2019-08-29 10:07 UTC
The Postman logo is missing in the taskbar of Windows 10.
Postman version = 7.5.0

**Comment by kamalaknn** [comment] 2019-08-29 10:42
@lbn2019 Thanks for your feedback. This looks like a duplicate of #6897 

I'm closing this issue, please follow the original issue for updates.

Duplicate of #6897

**Closed as completed by kamalaknn** 2019-08-29 10:42 UTC

**Comment by lkbn** [comment] 2019-08-29 10:51
Thanks
