### ISSUE TITLE
Duplicating Tabs does not carry information

### ISSUE THREAD

**Issue by grab-a-byte** [a85/POSTMan-Chrome-Extension#9579] opened 2021-02-09 09:25 UTC
**Describe the Issue**

> Right click and duplicate tab does not actually duplicate the tab and just opens a new window

- Open Postman for Windows 8.0.4 
- Add in headers/URL etc
- Right click and click duplicate Tab
- URL not moved over unlike previous versions. 

**Screenshots or Videos**
https://user-images.githubusercontent.com/30392071/107342900-b352b200-6ab8-11eb-9046-5d15bfaf5b8b.mp4

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 

**Environment Information**

 - Platform Type: [e.g. Native Desktop App, Postman On The Web, Web Dashboard]
 - Postman Version: 8.0.4
 - Operating System: Windows 10 Pro - Build 19042.789

**Comment by DannyDainton** [comment] 2021-02-09 09:31
Closing this as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9493

**Closed as completed by DannyDainton** 2021-02-09 09:31 UTC
Labels: duplicate
