### ISSUE TITLE
Current Tab is overwritten when clicking on a saved Request

### ISSUE THREAD

**Issue by cawoodm** [a85/POSTMan-Chrome-Extension#2739] opened 2017-02-22 09:22 UTC
Sometimes, when opening a saved Request it overwrites the current request tab instead of opening a new tab. It seems to always replace the currently selected tab. I'm sure it's supposed to make a new tab and does this sometimes correctly.

 1. v4.10.2
 2. Chrome app
 3. Windows 7
 4. Interceptor is off

**Comment by vegetableman** [comment] 2017-02-22 13:31
@cawoodm If the current tab is not having any unsaved changes, any request, you open, would replace the existing request, unless, you check the option `Always open requests in new tab` on the `Settings` dialog which will take care of your use-case.

**Comment by cawoodm** [comment] 2017-02-22 19:29
That's crazy. Please change this absurd behaviour. Respectfully.

**Comment by cawoodm** [comment] 2017-02-22 19:33
I don't see how the current behaviour can be useful, certainly not as a default setting. Are there many users who click through a bunch of requests and want them all to open in the same tab?? I know I never changed the setting so maybe "open in new tab" should be the default?

**Comment by vegetableman** [comment] 2017-02-22 19:56
@cawoodm Hence, the toggle option ^_^. We can't please everyone, but we can give options.

**Comment by Zero3** [comment] 2017-02-22 22:08
@vegetableman My personal opinion/experience with this issue:

This default behaviour has caused me great frustration multiple times, and has caused me to lose carefully crafted requests in the writing. These were not saved anywhere, and I was not able to find any functionality for re-opening the closed tabs. So Postman threw away my work just because I wanted to open a saved request in a new tab to look something up. I think this is a poor default behaviour, and my immediate thoughts were also something like "ouch, this is a nasty bug". I'm surprised it is the intended behaviour.

On a side-note, I actually looked for a setting to turn this off immediately after my last incident, but I did not manage to find it. I guess I will have to go back and have another look.

**Comment by SORC3r3r** [comment] 2017-02-23 10:28
At first I had issues with this behaviour too and I tried using the 'always open requests in new tab'.
This led to a high number of open tabs and an annoying search for the right one, so you open it again in a new tab and the number of open tabs increases.
At least I turned the 'always open requests in new tab' off again.
In my experience postman never discarded one of my open unsaved tabs. It just overwrites the tab if there are no unsaved changes.
![1](https://cloud.githubusercontent.com/assets/22958825/23255235/1a8fc94e-f9bb-11e6-93b0-81488d9a6e66.PNG)

**Comment by vegetableman** [comment] 2017-02-23 16:59
@Zero3 @SORC3r3r @cawoodm  Thanks guys for the valuable feedback 👍 . We are planning to up the ante to ensure data in the tabs are not lost. For instance, let's say you have an _unsaved tab with a response_, any request that would be opened from the sidebar would instead open in a new tab. Do note, the tab needs to have a response for it to be considered non-overwritable. Thoughts?

**Comment by SORC3r3r** [comment] 2017-02-24 07:58
Sounds good, makes sense.
How about saving the responses in the history or create a seperate 'response history' with request and response details including time stamp?

**Comment by Zero3** [comment] 2017-03-06 23:54
@vegetableman sounds like an improvement!

**Comment by cawoodm** [comment] 2017-03-20 10:18
@vegetableman, this isn't rocket science: the default behaviour is unheard of. Imagine you start writing a new document in MS Word and then, when you open an existing document, it overwrites the new (unsaved) document you were working on. That's what Postman does today and it's killing me - I can't see the benefit. Never, EVER overwrite someone's unsaved work without prompting. It's not important whether the current, unsaved, tab has a response or not: don't overwrite it.

That said there is definitely a BUG here. I have "always open requests in a new tab" switched ON and I just lost my work when, after crafting an unsaved request, I clicked on an existing saved request and it loaded in the tab I was working in. My request is gone and several minutes work lost.

**Comment by gaode103** [comment] 2017-05-31 14:46
This is very, very annoy to me. Looks like we (user and dev) have totally different understanding of what is a 'new tab'.  To me a new tab is a tab that needs to be created and not that already listed in the window. ESPECIALLY not a tab that already dirty, either from an empty tab that you put some stuff in, or an opened tab that you modified something.

Behavior I would expect would be:
Scenario 1:
Given:
1. 'Always open requests in new tab' (option) is off.
2. There is no tab open.

When:
1. Click an existing request.

Then:
1. A new tab created with exiting request.

Scenario 2:
Given:
1. option is off.
2. There is a tab open and not dirty (either a totally blank tab or from an existing request).

When:
1. Click an existing request.

Then:
1. The request should open in current opened tab.

Scenario 3:
Given:
1. option is off
2. There is a tab open but dirty (modified either from a blank tab or from an existing request)

When:
1. Click an existing request.

Then:
1. A new tab created with existing request.

Scenario 4:
Given:
1. option is on
2. There is no tab open

When:
1. Click an existing request

Then:
1. A new tab created with existing request.

Scenario 5:
Given:
1. option is on
2. There is a tab open and not dirty (either a totally blank tab or from an existing request).

When:
1. Click an existing request.

Then:
1. A new tab created with exiting request.

Scenario 6:
Given:
1. option is on
2. There is a tab open but dirty (modified either from a blank tab or from an existing request)

When:
1. Click an existing request.

Then:
1. A new tab created with exiting request.

An even better option:
If current tab is dirty, always open in a new tab.
If current tab is not dirty, click to open in current tab, ctrl+click to open in new tab.

**Baseline: under no circumstance should overwrite an dirty tab.**

Hope that helps.

**Comment by a85** [comment] 2017-12-11 14:56
This behavior has been fixed now in the latest versions of the app.

**Closed as completed by a85** 2017-12-11 14:56 UTC
Labels: support

**Comment by scottf** [comment] 2020-10-19 15:36
This behavior is back, with the default being not to open requests in new tabs. This wasn't the behavior when I used this product about 6 months ago, I go the latest for a new gig a couple days ago. I won't pile on the trolling of this behavior as you already know it's not a great idea.

**Comment by scottf** [comment] 2020-10-19 15:37
> This behavior has been fixed now in the latest versions of the app.

What does this "fix" entail. The default behavior is overwrite. I downloaded the latest mac version about 3 days ago.
