### ISSUE TITLE
Invisible suggestion ruins URL

### ISSUE THREAD

**Issue by racouster** [a85/POSTMan-Chrome-Extension#12148] opened 2023-07-05 14:00 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When switching between tabs in the request editor (e.g. from Body to Pre-Request Script) the value of the URL changes to the first item in the suggestion box (which is not visible when clicking).

### Steps To Reproduce

1. Open a new request tab.
2. Click on the url.
3. Leave it blank or choose the first suggestion.
4. Delete some of the suggestion so that the URL is shorter than the suggestions.
5. Push `Escape`, Clicking away to dismiss the suggestion box does not produce this bug.
6. Click on `Pre-request Script` in the editor just below the URL.
7. The URL changes to the invisible selection.
![Screenshot 2023-07-05 154628](https://github.com/postmanlabs/postman-app-support/assets/12576433/817f55e1-0a89-4212-b02c-8766a15a0bd0)
![Screenshot 2023-07-05 155708](https://github.com/postmanlabs/postman-app-support/assets/12576433/43fbe6af-ddff-4a75-b0ba-db31151d2416)

### Screenshots or Videos

Screenshots show the URL before clicking on Pre-request Script and after.

### Operating System

Windows 11

### Postman Version

10.15.6

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Secondary screen in use, but it doesn't seem to make any difference without the screen plugged in.

**Comment by codenirvana** [comment] 2023-07-05 14:07
@racouster Thanks for reporting this issue. I can reproduce this issue locally, we'll fix this as soon as possible.

Duplicate of #12125

**Comment by dev-sharma-08** [comment] 2023-07-05 17:39
We have fixed this bug in the latest web version 10.15.10 and desktop app version 10.15.7.
Please update your app to the latest version, and feel free to open this again if the issue persists.

**Closed as completed by dev-sharma-08** 2023-07-05 17:39 UTC
Labels: bug, product/runtime
