### ISSUE TITLE
Warning: Unable to verify the first certificate

### ISSUE THREAD

**Issue by Zikkq** [a85/POSTMan-Chrome-Extension#10705] opened 2022-02-26 14:22 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I've created corresponding question on strackoverflow and asked at the community. But investigating problem further i was suggesting that it could be a bug or I've just missing something. Any help will be appreciated so please follow [this link](https://stackoverflow.com/questions/71264975/warning-unable-to-verify-the-first-certificate) to get more details so I don't repeat myself

### Steps To Reproduce

1. Run API on the .NET 6.0.2.
2. Try to hit simple GET endpoint via Postman.
3. Get consistent response and warning.

### Screenshots or Videos

Screenshots attached to the question on the [same link](https://stackoverflow.com/questions/71264975/warning-unable-to-verify-the-first-certificate)

### Environment Information

```markdown
- Operating System: Windows 11
- Platform Type: .NET 6.0.2
- Postman Version: 9.13.2 but the problem occurs even in the web version with desktop agent
```

**Comment by DannyDainton** [comment] 2022-03-18 11:44
Hey @Zikkq 

With the steps that you have provided, we will be unable to reproduce this issue you're facing on our side. 

Could you expand on the details and provide steps that we can use to triage the issue, please?

Do you still see the same warning with this setting disabled -  https://github.com/postmanlabs/postman-app-support/issues/6354#issuecomment-937741986

**Comment by Zikkq** [comment] 2022-03-20 18:59
Hi @DannyDainton 
Yes. I see warning even when SSL verification disabled also I tried to add localgost development certificate to CA certificates and this didn't help too. I don't know what kind of information or steps I can send to you in addition. I've just created simple API using .NET 6.0.2 and hitting localhost endpoints as usual. Here's [link](https://github.com/Zikkq/skinet) to my repo you can clone it and try to hit any endpoint. The most embarasing here that respones return correct data as I would expected but warning surely tells that something not okay.

**Comment by Zikkq** [comment] 2022-03-20 19:01
Hello! I’ve just added new comment on this issue

  
>Пятница, 18 марта 2022, 14:44 +03:00 от Danny Dainton ***@***.***>:
> 
> 
>Hey  @Zikkq
>With the steps that you have provided, we will be unable to reproduce this issue you're facing on our side.
>Could you expand on the details and provide steps that we can use to triage the issue, please?
>Do you still see the same warning with this setting disabled -  #6354 (comment)
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you were mentioned. Message ID:  <postmanlabs/postman-app-support/issues/10705/1072332729 @ github . com> 
 
 
С уважением,
Дмитрий Андреев
***@***.***

**Comment by DannyDainton** [comment] 2022-04-28 10:59
I'm going to close this issue as a duplicate and link it to https://github.com/postmanlabs/postman-app-support/issues/6354

**Closed as completed by DannyDainton** 2022-04-28 10:59 UTC
Labels: duplicate, client-certificates, need-more-info
