### ISSUE TITLE
Swagger 2.0 import: accept YAML

### ISSUE THREAD

**Issue by dolmen** [a85/POSTMan-Chrome-Extension#1444] opened 2015-09-18 12:17 UTC
It is much more convenient to write Swagger specs in YAML than in JSON.

Swagger 2.0 specs serialized as YAML are not currently accepted for import by Postman 3.0.16.

**Comment by czardoz** [comment] 2015-09-18 12:33
Edit: Closed the issue accidentally, have reopened

**Comment by czardoz** [comment] 2015-09-18 12:36
Hi @dolmen, 

Yes, this will definitely be a part of one of the upcoming releases :)

**Comment by spark85** [comment] 2016-03-18 21:10
has this feature been implement in v 4.0.5 for mac?

**Comment by wichert** [comment] 2016-05-30 12:15
This does not work for me with Postman 4.2.2.

**Comment by abhijitkane** [comment] 2016-05-30 23:06
@wichert Can you include a sample YAML file that you're not able to import?

**Comment by wichert** [comment] 2016-06-01 07:08
@abhijitkane This is the YAML file I used: https://dl.dropboxusercontent.com/u/448540/swagger.yaml

**Comment by priyanka92feb** [comment] 2016-06-15 14:07
Hi, 

I am unable to import yaml file to postman as well. Attaching the file.
[input.zip](https://github.com/postmanlabs/postman-app-support/files/316249/input.zip)

Could someone let me know what is it thats going wrong? Please help.

**Comment by abhijitkane** [comment] 2016-06-15 20:27
@wichert Two lines (725 and 731) spanned 2 lines. You can view the correct file at https://gist.github.com/abhijitkane/ae76f3cbb61565350a90ca83a89c1e97

@pritianka What format are you trying to import? A Swagger file must have a root `swagger` property, whose value is `2.0`

**Comment by a85** [comment] 2018-12-07 13:59
Closing as duplicate of #843

**Closed as completed by a85** 2018-12-07 13:59 UTC
Labels: feature
