### ISSUE TITLE
Search in environment quick view

### ISSUE THREAD

**Issue by ColdCerealAtWork** [a85/POSTMan-Chrome-Extension#8300] opened 2020-04-08 22:18 UTC
**Is your feature request related to a problem? Please describe.**
Using the faker api is great for random data creation in many fields and using that data across requests, but doing so leaves my environments full of a long list of variables, to the point where it becomes frustrating looking for a specific variable to copy or modify.

**Describe the solution you'd like**
If there was a search option directly in the quick look view for environments it would speed up development and make life easier.

**Describe alternatives you've considered**
I love the search option built into postman, but it would be helpful if I could open or at least view and live edit the request or environment at that location from the search results. 

**Additional context**

**Comment by vvs11** [comment] 2020-04-11 15:06
duplicate of #6562

**Closed as completed by vvs11** 2020-04-11 15:06 UTC
Labels: product/runtime
