### ISSUE TITLE
Headers like `application/vnd.retailer.v3+json` in the request should be used to highlight the request as JSON

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#6615] opened 2019-05-29 16:00 UTC
While importing a request, if there's a header like `application/vnd.retailer.v3+json` instead of `application/json`, Postman does not automatically treat the body as JSON, but as text.

Furthermore, manually selecting JSON from the raw mode dropdown changes the Content-Type to `application/json`.

Intended behavior:
Any header of the form `application/*+json` should be treated as JSON for purposes for formatting the request body.

**Comment by shamasis** [comment] 2019-05-30 05:25
We would disconnect the raw body type drop down and value of content type. The magic of setting any `*json` may be tricky. 

cc @ankitjaggi @codenirvana - this is a duplicate of form-data header change and storage of extra body intent.

**Comment by codenirvana** [comment] 2019-09-17 08:05
Duplicate of #5127

This behavior is now fixed in the latest version of the Postman app (v7.7.2).

**Closed as completed by codenirvana** 2019-09-17 08:05 UTC
Labels: feature, product/runtime
