### ISSUE TITLE
Tables are not displayed correctly in Postman documentation

### ISSUE THREAD

**Issue by dcalliste** [a85/POSTMan-Chrome-Extension#7859] opened 2019-12-31 12:37 UTC
**Describe the bug**
Since a few weeks tables in documentation done with Postman are not displayed correctly:
- Button to see table in fullscreen is missing
- Full table is displayed by default instead of a preview for big tables
- Tables in folder description overlap the right panel in documentation

**To Reproduce**
1. Go to Postman
2. Create new collection
3. Create a folder
4. Edit folder description by adding big table (example in file attache)
5. Publish documentation for this collection
6. See errors in published documentation in browser

**Expected behavior**
- Tables do not overlap on the right panel
- For big table, a preview is displayed and a button is available to see the full table in fullscreen

**Screenshots**
<img width="1418" alt="Screenshot 2019-12-31 at 13 30 34" src="https://user-images.githubusercontent.com/41050836/71621919-961f9480-2bd2-11ea-861c-b656e5909699.png">
<img width="883" alt="Screenshot 2019-12-31 at 13 38 00" src="https://user-images.githubusercontent.com/41050836/71621933-c8c98d00-2bd2-11ea-9656-32c1f67840d6.png">

**App information (please complete the following information):**
 - Chrome (Version 79.0.3945.88) and Safari (Version 13.0.4)
 - macOS High Sierra 10.13.2

**Additional context**
Example of table in markdown to add to folder description to reproduce defect:
[table.example.markdown.rtf.zip](https://github.com/postmanlabs/postman-app-support/files/4012688/table.example.markdown.rtf.zip)

**Comment by mrz1836** [comment] 2020-01-01 03:49
Unless I'm doing something wrong...

Centering a table is not working as well:

```
| package | language | header  |
|----|:---:|----|
| pkg | Go | some text |
| pkg | JavaScript | some text |
```

The middle column should be centered, yet it's still left aligned.

**Comment by Raja-Simha** [comment] 2020-01-02 08:28
@dcalliste we are investigating this issue.

**Comment by dcalliste** [comment] 2020-02-04 13:42
hello @Raja-Simha, I would like to know if you have an update to share on this issue? Thank you

**Comment by Cazaimi** [comment] 2020-02-04 16:10
@dcalliste, we have identified the cause behind this issue. We're working on the fix and plan on getting it out in the next two weeks. Stay tuned to this thread for updates. :)

**Comment by dcalliste** [comment] 2020-03-18 16:59
> @dcalliste, we have identified the cause behind this issue. We're working on the fix and plan on getting it out in the next two weeks. Stay tuned to this thread for updates. :)

It seems fix has been release, thank you!

**Comment by Cazaimi** [comment] 2020-03-20 12:27
@dcalliste, the fix is out for this. Please reach out to us via this thread if you still face problems. 🙂

@Raja-Simha , this can be marked as closed.

**Closed as completed** 2020-04-14 10:41 UTC
Labels: bug, product/documentation
