### ISSUE TITLE
scrolling in version 7.28

### ISSUE THREAD

**Issue by sajadsholi** [a85/POSTMan-Chrome-Extension#8781] opened 2020-07-15 07:17 UTC
- App Type Postman desktop
 - Postman Version 7.28

Why has the scrolling experience changed in this version? 

for example It's so annoying when you can't scroll the response from the top of request .

please instead of removing this feature, make a setting option to decide have that or not

**Comment by coditva** [comment] 2020-07-15 07:42
As I mentioned in [this comment](https://github.com/postmanlabs/postman-app-support/issues/8780#issuecomment-658598977), we've removed the top-level scroll from the top-level. You can always switch to a 2-pane layout where you can view the request and response side-by-side.


![87516577-42225c00-c69b-11ea-8496-7ffdc7fe4899](https://user-images.githubusercontent.com/8445768/87517601-b1e51680-c69c-11ea-9e30-03be37e70385.gif)

Duplicate of https://github.com/postmanlabs/postman-app-support/issues/8780

**Closed as completed** 2020-07-15 07:43 UTC
Labels: user-interface, product/runtime

**Comment by vkaegis** [comment] 2020-07-20 14:10
Hey @sajad2176 , out of curiosity, what resolution are you using Postman at?

**Comment by coditva** [comment] 2020-08-25 06:35
Hey @sajad2176, with the new release (version 7.31.0), you will be able to easily switch to working on request or response with just a scroll, similar to how you're used to! 🎉

Simply press and hold the Alt (or ⌥ on MacOS) key and scroll the request or response to resize it. You can also use Win+Alt (or ⌘ + ⌥ on MacOS) while scrolling (in case you have the Alt key bound to something else).

![Screen Recording 2020-08-25 at 11 04 25](https://user-images.githubusercontent.com/8445768/91130971-206cb980-e6ca-11ea-8489-2d836061ec87.gif)

You can also find the reference to this in the Shortcuts:

![image](https://user-images.githubusercontent.com/8445768/91130983-26629a80-e6ca-11ea-964c-f1b790123429.png)

We hope this would be easier and faster than dragging. We ask you to give it a try and let us know if we could solve your problem. Please do reach out with any concerns you have about this. ⌨️ 📜
