### ISSUE TITLE
Saved Responses -> Examples

### ISSUE THREAD

**Issue by meywd** [a85/POSTMan-Chrome-Extension#3116] opened 2017-06-05 10:28 UTC
1. Postman Version: 4.11.0
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows 10 64bit
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: latest version only
 6. Expected behaviour: The send button is shown to send to requests
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**How to use saved responses after 4.11 the same way as before the update?**

before the update it was easy to send saved requests by clicking the Send button, now the send button doesn't show while browsing the saved examples.

**Comment by numaanashraf** [comment] 2017-06-05 11:00
Thanks for getting in touch @meywd. We made some changes to the saved responses feature as we transition to our new examples feature. @bhawna2109 can share more details on this.

**Comment by bhawna2109** [comment] 2017-06-05 15:03
Hi @meywd 

The examples feature was built to account for the fact that each saved response has a request associated with it, which _can_ be different from your saved request. Thus, while you're viewing your example (which is a request&response pair), the request part of it is different from your saved request, which is why there is no send button. You'll have to explicitly go back to the request in order to send it.

That said, I understand that there's an additional step involved in sending your saved request. We'll be improving this feature over time, and adding keyboard navigation for the same is on our list!

Let us know if anything is unclear or if you have any more questions.

**Comment by meywd** [comment] 2017-06-12 10:15
@numaanashraf  @bhawna2109 Thank you for your response, I understand that it has changed, but it's really annoying now to send a saved request, so it would be great if you can add the send button again.

**Comment by Candidate48** [comment] 2017-06-13 01:19
hello there, 
one of 4.11.0 update Features confuse me! that is "Save variations of request & response with Examples".I save the response for write my Tests .but in 4.11.0 Examples I can not see the response and write Tests at the same time!

Obviously, in example, request&response is pair which is great. it seem to have a conflict with my needs.

**Comment by numaanashraf** [comment] 2018-11-13 23:50
Duplicate of #3694

**Closed as completed by numaanashraf** 2018-11-13 23:50 UTC
Labels: feature, examples
