### ISSUE TITLE
Hide white space special characters in the body and response in Postman 8

### ISSUE THREAD

**Issue by milindrao** [a85/POSTMan-Chrome-Extension#9632] opened 2021-02-18 15:17 UTC
I updated to Postman 8 and I find the white space characters (dots for spaces and arrows for tabs) in the body and response very distracting.  I can't find a way to disable it.  Am I missing something in the settings?

**Comment by DannyDainton** [comment] 2021-03-05 12:03
Closing as this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9531

**Closed as completed by DannyDainton** 2021-03-05 12:03 UTC
Labels: user-interface, product/client-foundation
