### ISSUE TITLE
Postman Not getting launched in windows 10 

### ISSUE THREAD

**Issue by shyam2794** [a85/POSTMan-Chrome-Extension#4239] opened 2018-02-24 19:17 UTC
## App Details:
The app is not launching , so unable to get the app details .
``` 
windows 10 
```

## Issue Report:
  The the launch page prevails all the time . The app doesnt start . 
 4. Screenshots (if applicable)
![postman](https://user-images.githubusercontent.com/30238125/36634082-5367bcf6-19c5-11e8-9cad-975aea7854f0.PNG)

**Comment by sivcan** [comment] 2018-02-24 19:24
@shyam2794 - Are you on the latest version of the app ?
If not then [Download Postman](getpostman.com/apps) and try opening the app ?

If you're on the latest version and experiencing this issue then we'll be needing logs from you.

Steps :
1. Launch the Postman App.
2. In the Menu Bar click on View > Developer > View Dev Tools (Shared)
**Note**: Need you to launch the dev tools for the 'Shared' view
3. View > Developer > View Dev Tools (Current View)

Share the console logs as log files for both the dev tool windows.

**Comment by shyam2794** [comment] 2018-02-24 19:35
@sivcan  Thanks for the response . 
 1. yes i am downloading the latest version i think so . The one in this URL for windows 
(https://www.getpostman.com/apps) . Am not sure whether this is the latest . 

2.Am getting the following error . 

requester.js:283536 Uncaught DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Object.getUnsyncedChanges (file:///C:/Users/ADMIN/AppData/Local/Postman/app-5.5.3/resources/app.asar/js/requester.js:283536:20)
    at child.loadUnsyncedChanges (file:///C:/Users/ADMIN/AppData/Local/Postman/app-5.5.3/resources/app.asar/js/requester.js:274618:18)
    at child.initialize (file:///C:/Users/ADMIN/AppData/Local/Postman/app-5.5.3/resources/app.asar/js/requester.js:274524:10)
    at child.Backbone.Model (file:///C:/Users/ADMIN/AppData/Local/Postman/app-5.5.3/resources/app.asar/js/requester.js:81570:21)
    at new child (file:///C:/Users/ADMIN/AppData/Local/Postman/app-5.5.3/resources/app.asar/js/requester.js:83049:41)
    at initializeSync (file:///C:/Users/ADMIN/AppData/Local/Postman/app-5.5.3/resources/app.asar/js/requester.js:471571:23)
    at file:///C:/Users/ADMIN/AppData/Local/Postman/app-5.5.3/resources/app.asar/js/requester.js:471684:7
    at Object.onTransactionComplete (file:///C:/Users/ADMIN/AppData/Local/Postman/app-5.5.3/resources/app.asar/js/requester.js:283001:5)
    at file:///C:/Users/ADMIN/AppData/Local/Postman/app-5.5.3/resources/app.asar/js/requester.js:283129:22

**Comment by sivcan** [comment] 2018-02-24 20:02
@shyam2794 - Ohh, were you logged in previously ?
Has all your data been synced previously ?
Can you head over to the Postman Dashboard and check if all your data is there ?

Let me know.

**Comment by shyam2794** [comment] 2018-02-24 20:08
@sivcan  i am not able to view the dashboard . This is the first time am using postman . will send the screenshot of my dashboard . 
![dashboard](https://user-images.githubusercontent.com/30238125/36634610-1acbb3ea-19cd-11e8-89ab-7b3c54e1d020.PNG)

**Comment by sivcan** [comment] 2018-02-24 20:10
@shyam2794 Okay never mind, can you tell me how you reached this state ?

**Comment by shyam2794** [comment] 2018-02-24 20:13
@sivcan  i have updated the previous comment . You can find the screenshot of the dashboard .

**Comment by sivcan** [comment] 2018-02-24 20:15
@shyam2794 - Okay
So couple of questions that'll help us to triage this issue faster

1. Were you previously using postman or is this the first time you installed it ? 
2. Do you have an account and were logged in or not ? (If you had Postman installed previously) 
3. Are you sure you're on the latest version ? Can you head over to the site and download it fresh [Download Postman](https://www.getpostman.com/apps) and install it ? 

If you are on the latest version, did you download it via the site and still facing the issue ?
or 
Did you press the 'Update' button that came up as a new postman version is available ?

**Comment by sivcan** [comment] 2018-02-24 20:20
@shyam2794 - Okay you updated the comment that you're using postman for the first time. 
When was the last time you downloaded it from our site ?

Was it like the first time you downloaded and it just never booted up ?

**Comment by shyam2794** [comment] 2018-02-24 20:22
@sivcan  I have cleared all the files related to postman and tried reinstalling it again . It works fine . The app is updated to the latest version 6.0.7 . 
Thanks for your help .  

I suspect the reason for the bug is i tried to use the postman chrome as the app didnt start in my windows machine and logged in the web app .  I signed out from the web app ,removed it from the chrome apps . And re-installed the native app . And it works fine now .

**Comment by LennyLip** [comment] 2018-06-29 11:00
postman 6.1.4. win 8, + blinked cursor
![postman](https://user-images.githubusercontent.com/955994/42089160-c5bb4ca0-7ba4-11e8-9270-0542b45acedd.png)

**Comment by sweepy84** [comment] 2018-07-02 23:47
Getting the same issue with version 6.1.4 on Windows 10. Getting the below errors about an access token.

If i'm not logged in why wouldnt it ask me to? I just get the never ending loading animation. Tried re-installing no dice.

Looks like a clear bug

> Initializing the global config
vendor-shared.js:84989 Initializing settings
vendor-shared.js:79325 Booting waterline models
vendor-shared.js:137973 Object "Successful ORM initialization"
shared.js:353 Migration bailed out due to: EXCEEDED_ATTEMPT
(anonymous) @ shared.js:353
shared.js:5601 create socket bailed sync disabled
vendor-shared.js:97210 User not logged in or there is no access token
vendor-shared.js:96937 Uncaught (in promise) User not logged in or there is no access token
vendor-shared.js:97210 User not logged in or there is no access token
vendor-shared.js:96937 Uncaught (in promise) User not logged in or there is no access token

**Comment by thecuriousdev** [comment] 2018-07-04 05:24
Hey @sweepy84 thanks for reporting this issue, I'll look into this, Please help me with these questions,
1. Is it a fresh install or you updated the app from an older version (if so which version of the app)?
2. How you encountered this bug? (When tried to signin, add a new account, etc)
3. Did the issue got resolved in anyway (if so how?), or you are still facing the issue?

**Comment by sweepy84** [comment] 2018-07-05 02:49
@thecuriousdev  

1. It was an update
2. Same as the original issue post, i just see that screen, never ends loading.
3 . I didn't want to lose settings/cache etc so after some testing i deleted a few files from "C:\Users\Peter\AppData\Roaming\Postman" argh but dont rememebr which i think its was the "Partition" folder and a handful from the root of that folder like "Preferences" and "settings.json"

This allowed me to see the login screen again, i logged in and all was fine.

**Comment by thecuriousdev** [comment] 2018-07-05 06:35
@sweepy84 can you confirm whether all of your data is synced to Postman servers? (You can verify this by going to our dashboard, http://app.getpostman.com/)

If so you can delete `C:\Users\Peter\AppData\Roaming\Postman` and relaunch the application.

**Comment by SamvelRaja** [comment] 2018-07-17 08:51
Closing this for now.
⚠️  Also, We do not recommend deleting files from the app storage. It can lead to unexpected behaviors.

**Closed as completed by SamvelRaja** 2018-07-17 08:51 UTC
Labels: bug

**Comment by MiguelAtTweddle** [comment] 2018-09-13 12:24
thecuriousdev's answer did actually work! Thnx

**Comment by chuckwade** [comment] 2019-04-09 17:46
I had a similar issue with Windows 10 and Postman 7.0.7.  The app would never open.  I deleted everything from C:\Users{user name}\AppData\Roaming\Postman and C:\Users{user name}\AppData\Local\Postman

Then I ran the 64-bit installer again (run as administrator) and it is now working.

**Comment by naveed1234567** [comment] 2019-04-14 17:30
![Screenshot_2](https://user-images.githubusercontent.com/49415120/56096687-e94a9d80-5f04-11e9-9c84-c058a52ed8c4.png)
After downloading Postman i'm getting this error plz help me out to solve this error

**Comment by SamvelRaja** [comment] 2019-04-15 06:51
@naveed1234567 could you follow the step specified here?  https://github.com/postmanlabs/postman-app-support/issues/5681#issuecomment-449251511
