### ISSUE TITLE
Postman implicitly encodes the '{}' symbols 

### ISSUE THREAD

**Issue by gingerdin** [a85/POSTMan-Chrome-Extension#6120] opened 2019-03-21 10:44 UTC
**Describe the bug**
According the documentation https://learning.getpostman.com/docs/postman/sending_api_requests/requests/
"Note: Parameters you enter in the URL bar or in the data editor will not automatically be URL-encoded".
At the same time, when using the GET request with the '{}' symbols
`http://localhost/api/PolicySpecification?query={policySpecifications{productCd}}` when intercepting the request by the 
Fiddler, I got
`http://localhost/api/PolicySpecification?query=%7BpolicySpecifications%7BproductCd%7D%7D`
Note: no 'EncodeURIComponent' has been used

**To Reproduce**
1. Go to Postman
2. Create new GET request with the url, containing '{}'
3. Send
4. Intercept the request 
5. The intercepted request will be encoded

**Expected behavior**
The executed URL will be the same as it is seen in the URL window in Postman

**Screenshots**
![postman-error](https://user-images.githubusercontent.com/2117420/54747234-61ac9000-4bdf-11e9-8efd-27b3b27d14ce.png)

**App information (please complete the following information):**
 - Native App Windows (the same for macOS)
 - Postman Version 6.7.4 (the same for macOS)
 - OS: Windows (the same for macOS)

**Comment by codenirvana** [comment] 2019-12-17 13:59
Duplicate of #4171

**Closed as completed by codenirvana** 2019-12-17 13:59 UTC
Labels: encode-decode, duplicate, product/runtime

**Comment by vikiCoder** [comment] 2020-03-09 09:40
@gingerdin this is fixed in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). We don't automatically encode `{}` anymore according to WHATWG URL standards. You can see more details about the fix at #8154
