### ISSUE TITLE
Unable to Backup Postman data to Gitlab Instance w/ Custom Domain

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6177] opened 2019-03-29 01:36 UTC
**Describe the bug**
When attempting to leverage the GItlab Integration for an instance with a Custom Domain, the following error is thrown:

`An error occurred while verifying GitLab user. Try again after some time`

**To Reproduce**
1. Add Gitlab Integration to a workspace
2. See error during addition flow

**Expected behavior**
Successful addition / implementation of the integration/backup.

**Screenshots**
Pending end-user provisioning.

**App information (please complete the following information):**
 - App Type: Native App | Web Dashboard
 - Postman Version 7.0.6

**Additional context**
Team Domain: `lively-space-3252`
[Filed by Postman]

**Comment by preethammavin** [comment] 2019-04-08 07:12
Closing this as we are unable to reproduce this, feel free to reopen if it occurs again.

**Closed as completed by preethammavin** 2019-04-08 07:12 UTC
Labels: bug, product/dashboard, product/integrations
