### ISSUE TITLE
Unable to send form-data with key as empty string

### ISSUE THREAD

**Issue by f3rgames** [a85/POSTMan-Chrome-Extension#6537] opened 2019-05-17 12:04 UTC
**Describe the bug**
I am doing a Post with a File in the header. I have to save the file in the working directory, but when I do the post, the file is not at the Request.Files
This is a recently problem. A few weeks ago it did not happen.

**To Reproduce**
I have 2 headers. 
- Authorization: ...
- Content-Type: multipart/form-data

And the Body:
- form-data:  With a txt file selected.

**Expected behavior**
A few weeks ago, the file was at the Request.Files array

**Screenshots**
![image](https://user-images.githubusercontent.com/50740230/57926359-55754400-78ab-11e9-8686-4a5ba455119f.png)

![image](https://user-images.githubusercontent.com/50740230/57926778-77bb9180-78ac-11e9-9061-0b7d4b387519.png)

The Request.Files.Count is 0.

**App information (please complete the following information):**
 - App Type: WebAPI 2 from VS2017
 - Postman Version: v7.1.0
 - OS: Windows 10 - 64bits

**Comment by saswatds** [comment] 2019-05-17 14:56
Hi @f3rgames, Thanks for reporting this.
As we can see that you are sending form-data with empty key. We have been able to reproduce this bug and identified the root cause of this. Will be releasing the fix soon. 

Meanwhile as a short-term fix if your server doesn't care about a key for the file, you can add some dummy key and it should work.

I hope this helps

**Comment by f3rgames** [comment] 2019-05-21 07:18
Hi @saswatds, thanks for your replay,

I have used a dummy key like you said, and it work.
The problem was that i though that the key was the combo "File".

**Comment by codenirvana** [comment] 2019-05-21 07:52
@f3rgames This is fixed in our Canary channel (version 7.1.1-canary03) https://www.getpostman.com/downloads/canary

Let me know if the issue persists, will update once the issue is fixed in our stable channel.

**Comment by codenirvana** [comment] 2019-06-13 11:50
@f3rgames Fixed in Postman v7.2.0

**Closed as completed by codenirvana** 2019-06-13 11:50 UTC
Labels: bug, product/runtime
