### ISSUE TITLE
Collection Runner unable to identify the Data File Type for JSON file.

### ISSUE THREAD

**Issue by built-by-vjallada** [a85/POSTMan-Chrome-Extension#4353] opened 2018-03-19 04:03 UTC
## App Details:

```
Postman for Windows
Version 6.0.10
win32 6.1.7600 / x64
```

## Issue Report:

1. Open Postman.
2. Click on [Runner].
3. Under Data, select the File (Select the json File.)
4. Check the Data File Type is set to "Undetermined".

![image](https://user-images.githubusercontent.com/22824009/37577514-a12b3012-2b86-11e8-9145-aec0d74521c0.png)

**Comment by sivcan** [comment] 2018-03-19 06:10
@sekhar-selenium - The collection runner does support JSON (not sure why you want to check undetermined over here as the option)
-> https://www.youtube.com/watch?v=NuQD2Xmg3x8&feature=youtu.be

**Comment by built-by-vjallada** [comment] 2018-03-19 06:36
@sivcan , I'm not sure why there is a comment saying the collection runner does not support JSON file, but as a part of the Postman Documentation on the Working with the Files, it stated that as a part of the collection runner, anyone can work on Collection runner using the .csv or .json files.
Here is the link to support the above comment:
https://www.getpostman.com/docs/v6/postman/collection_runs/working_with_data_files

**Comment by sivcan** [comment] 2018-03-19 07:04
@sekhar-selenium - Where is there a comment that collection runner does not support JSON files ?
It totally does.
Kindly take a look at the video link I shared in my first comment.

**Comment by DannyDainton** [comment] 2018-08-22 21:26
@sivcan I think you have not understood the issue that was originally reported, no one is saying it's not supported. When you add a .csv file to the runner it picks up the data type and auto sets it correctly, if a json file is added, it always reverts to 'undetermined' and you need to manually select 'json' from the drop down list.

Your video is showing this working on a Mac but the issue was reported on a Windows machine. 

![json_file_windows](https://user-images.githubusercontent.com/17089546/44518490-3eaa1400-a6c2-11e8-9dcc-c301c9f85581.gif)

**Comment by steckdev** [comment] 2018-10-26 15:40
Can we either re-open this issue or create another issue for this  behavior. Please update this ticket properly. Unless there is a known work around for this.

**Comment by sivcan** [comment] 2018-10-27 08:16
I was able to reproduce this on Windows, reopening this.

**Comment by numaanashraf** [comment] 2019-04-01 07:32
Duplicate of #4591

**Closed as completed by numaanashraf** 2019-04-01 07:32 UTC
Labels: bug, collection-runner

**Comment by kiwinz2015** [comment] 2019-06-16 22:02
Still able to reproduce. Is this issue fix underway?
Cheers
