### ISSUE TITLE
Add body form data via pre-request scripts is not effective

### ISSUE THREAD

**Issue by alimlong** [a85/POSTMan-Chrome-Extension#9000] opened 2020-08-30 11:01 UTC
**Describe the bug**
Add body form data via pre-scriptis is not effective

**To Reproduce**
1. Create a new POST request.
2. Add some x-www-form-urlencoded format data in body.
3. Edit pre-request script, add a extra data to pm.request.body.
4. Send request.
5. Check request in pm console.

**Expected behavior**
All body data will send by request.

**Screenshots**
![image](https://user-images.githubusercontent.com/60846979/91657288-683c7800-eaf2-11ea-97f1-35ee82299eef.png)
![image](https://user-images.githubusercontent.com/60846979/91657363-f153af00-eaf2-11ea-8df8-71dc01a1fb67.png)
![image](https://user-images.githubusercontent.com/60846979/91657386-1b0cd600-eaf3-11ea-9fe1-1b2f7e010406.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version v7.31.1
 - OS: Windows 10

**Additional context**

**Comment by codenirvana** [comment] 2020-08-31 06:38
@alimlong Request body can't be mutated via pre-request script at the moment, please follow #4808 for updates on this feature request.

Closing as duplicate of #4808

**Closed as completed by codenirvana** 2020-08-31 06:38 UTC
Labels: duplicate, product/runtime
