### ISSUE TITLE
Failure to make API requests due to (accidental) trailing newlines in header values

### ISSUE THREAD

**Issue by umnagendra** [a85/POSTMan-Chrome-Extension#8004] opened 2020-02-06 14:18 UTC
**Describe the bug**
If there is a trailing newline character at the end of a request header value, postman fails to even initiate the API request.

Users see a **"Could not get any response"** error with no indication that there is a problem with a request header value.

**To Reproduce**
1. Create a new request
2. Add a request header (say `Authorization`) whose value has a trailing newline (copy the value from elsewhere with the newline and paste it)
3. Click **Send**
4. Users see a **"Could not get any response"** error

**Expected behavior**
Ideally, postman should trim any trailing newlines / whitespaces from header values. Often, header values (such as API keys, bearer tokens etc.) are copy-pasted, and might inadvertantly introduce trailing newlines / whitespaces.

Secondly, it is very hard to determine that _**this**_ is the problem.
The error message (**"Could not get any response"**) and suggestions that follow don't offer a hint that this could be a problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/990210/73944238-3f675200-4918-11ea-940b-963eab27a79e.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.17.0
 - OS: macOS Catalina v10.15.3

**Comment by ritwijsinha** [comment] 2020-02-07 05:05
Duplicate of #4339

**Closed as completed by ritwijsinha** 2020-02-07 05:05 UTC
Labels: duplicate, product/runtime
