### ISSUE TITLE
Builder/UI waits indefinitely on request when a Contextify/VM error is thrown for large responses

### ISSUE THREAD

**Issue by JamesMGreene** [a85/POSTMan-Chrome-Extension#4156] opened 2018-02-07 17:07 UTC
## App Details:

```
Postman for Windows
Version 5.5.2
win32 10.0.10586 / x64
```

## Issue Report:

 **1. Did you encounter this recently, or has this bug always been there:**

Not sure.  This is the first time I've been dealing with responses this large.

 **2. Expected behaviour:**

The Postman Builder/UI should update to display the response after it receiving it.

Failing that, the Builder/UI should at least update to reflect that an internal Postman error occurred rather than misleading me into believing that there is something wrong with my service.

 **3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):**

   ![image](https://user-images.githubusercontent.com/417751/35928793-a6bc0b30-0bf3-11e8-88cb-c537719121ca.png)

Full stack text:

```
Error: Script execution timed out.
    at ContextifyScript.Script.runInContext (vm.js:37:29)
    at Object.exports.runInContext (vm.js:69:17)
    at PostmanSandbox.emitter._dispatch (C:\Users\myUsername\AppData\Local\Postman\app-5.5.2\resources\app.asar\node_modules\uvm\lib\uvm\bridge.js:112:16)
    at PostmanSandbox.dispatch (C:\Users\myUsername\AppData\Local\Postman\app-5.5.2\resources\app.asar\node_modules\uvm\lib\uvm\index.js:103:30)
    at PostmanSandbox.execute (C:\Users\myUsername\AppData\Local\Postman\app-5.5.2\resources\app.asar\node_modules\postman-sandbox\lib\index.js:106:14)
    at PostmanCollectionRun.<anonymous> (C:\Users\myUsername\AppData\Local\Postman\app-5.5.2\resources\app.asar\node_modules\postman-runtime\lib\runner\extensions\event.command.js:289:27)
    at C:\Users\myUsername\AppData\Local\Postman\app-5.5.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1121:9
    at replenish (C:\Users\myUsername\AppData\Local\Postman\app-5.5.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:998:17)
    at C:\Users\myUsername\AppData\Local\Postman\app-5.5.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1002:9
    at _asyncMap (C:\Users\myUsername\AppData\Local\Postman\app-5.5.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1119:5)
```

 **4. Screenshots (if applicable)**

The Postman Builder/UI waits indefinitely (granted, my request timeout is set to `0` (Infinity)):

   ![image](https://user-images.githubusercontent.com/417751/35929154-6f5f0844-0bf4-11e8-89b1-9ff05acf4ddd.png)

In reality, the successful response received after ~3 seconds in the Postman Console:

   ![image](https://user-images.githubusercontent.com/417751/35929362-f2d0dab8-0bf4-11e8-8ccb-32fb6e608ccd.png)

The response size (after unzipping) is only ~8.35 MB of JSON, so it's not even close to being outrageously large.  A few commentators on another somewhat unrelated issue (#2479) thread mentioned troubles if a response was over ~15 MB but this is merely half of that size!

I also switched the response to CSV to see if it was specific to the response being JSON (e.g. and being parsed for pretty view) but I still received an identical error.

**5. Steps to reproduce the problem:**

Make an HTTP `GET` or `POST` request to a resource that returning a large amount of data...?

**Comment by JamesMGreene** [comment] 2018-02-07 19:35
P.S. I also tried removing my "Tests" (post-request scripts) but doing so made no noticeable difference.

**Comment by a85** [comment] 2018-02-19 20:30
Thanks for reporting @JamesMGreene. Looking into this.

**Comment by kamalaknn** [comment] 2018-07-05 08:12
I'm closing this as a duplicate of #4751

We're tracking similar issues related to Postman handling large responses. Please follow the original thread for updates.

**Closed as completed by kamalaknn** 2018-07-05 08:12 UTC
Labels: bug
