### ISSUE TITLE
POST sent twice after duplicate request and drag to another folder

### ISSUE THREAD

**Issue by guneyozsan** [a85/POSTMan-Chrome-Extension#8061] opened 2020-02-14 10:08 UTC
**Describe the bug**
POST request is sent twice (Ctrl+L or Send button same).
It happens after I duplicate by Ctrl+D a request in folder and drag it to another folder.

**To Reproduce**
1. Create a folder with POST request in it.
2. Create another empty folder.
3. Duplicate the request with Ctrl+D. (Optionally rename it with Ctrl+E for exact steps).
4. Drag and drop it into the new folder.
5. Send request (Ctrl+L or Send button, same result).
6. Listen to it with debugger and you will see it is sent twice.

**Expected behavior**
Request should have been sent once.
It works fine if I create a new POST request.

**App information (please complete the following information):**
 - App Type: PHP endpoint running on localhost.
 - Postman Version 7.18.0
 - OS: Windows 10 Home Single Language 10.0.18362

**Comment by harryi3t** [comment] 2020-02-17 05:45
@guneyozsan Could you share a screen recording showing this bug? I wasn't able to reproduce this.

**Comment by codenirvana** [comment] 2020-05-29 20:40
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-05-29 20:40 UTC
Labels: bug, product/runtime, blocked/need-repro
