### ISSUE TITLE
Python Requests examples contain errors

### ISSUE THREAD

**Issue by xuthus** [a85/POSTMan-Chrome-Extension#7433] opened 2019-10-04 09:52 UTC
**Describe the bug**
Code generated for Python Requests examples contains some errors:
* using `undefined` contant instead of `None`
* duplicate using `allow_redirects=false` in `requests.request()` call (also note, `false` must be `False`)

**To Reproduce**
1. Create new simple GET request
2. Select Publish Docs for the collection
3. Open documentation for the collection
4. Select "Python Requests" in Language field at the top right corner of the page

**Expected behavior**
```python
import requests
url = 'http://localhost:8080/api/interview-admin/findIndicatorScales'
payload = {}
headers = {
  'Content-Type': 'application/json'
}
response = requests.request('GET', url, headers = headers, data = payload, allow_redirects=False, timeout=None)
print(response.text)
```

**But instead**

response = requests.request('GET', url, headers = headers, data = payload, __allow_redirects=False__, timeout=**undefined**, **allow_redirects=false**)

**Comment by Cazaimi** [comment] 2019-10-16 09:24
Duplicate of #6152

**Comment by godfrzero** [comment] 2019-10-16 11:39
Closing as a duplicate of #6152, please follow the original issue for updates.

**Closed as completed by godfrzero** 2019-10-16 11:39 UTC
Labels: bug, product/documentation
