### ISSUE TITLE
cookies not saved in Version 6.1.3

### ISSUE THREAD

**Issue by stavsap** [a85/POSTMan-Chrome-Extension#4612] opened 2018-05-29 09:56 UTC
Postman for Windows
Version 6.1.3

after last update, cookies are not saved, cant have simple login session based on cookies in postman native application.

**Comment by harryi3t** [comment] 2018-05-29 12:25
duplicate of https://github.com/postmanlabs/postman-app-support/issues/4581

**Closed as completed by harryi3t** 2018-05-29 12:25 UTC
