### ISSUE TITLE
after update, it no work anymore

### ISSUE THREAD

**Issue by emimarz** [a85/POSTMan-Chrome-Extension#7824] opened 2019-12-19 13:36 UTC
after update to the Version 7.13.0
all my collections stop working
even if I create a new request using an url accessible because I enter via browser not work
it's odd because if I copy the code from the app it work with curl

**Screenshots**
![Captura de pantalla de 2019-12-19 10-33-57](https://user-images.githubusercontent.com/10280713/71177710-56a88e00-224b-11ea-8b61-3c8ae61190b9.png)

**App information (please complete the following information):**
 - App Type desktop ubuntu 
 - Postman Version 7.13.0
 - OS: ubuntu 18.04

in the console the error is the follow
GET http://www.google.com.uy/
Error: getaddrinfo ENOTFOUND www.google.com.uy www.google.com.uy:80

that is the latest version of ubuntu package manager

**Comment by codenirvana** [comment] 2019-12-19 13:49
@emimarz That's odd 😕, Can you check if this is because of proxy configuration (global or system) or something set in `/etc/hosts`?

**Comment by emimarz** [comment] 2019-12-21 02:36
nop, nothing in /etc/hosts and I don't have proxy configured 
I solve this downloading version 7.14, using the same configuration works
but this problem still happen on 7.13 v0v

**Comment by codenirvana** [comment] 2020-03-11 06:00
This looks like an issue with the Linux upgrade flow.
Is this issue persists after upgrading to the latest version of the app?

**Comment by shamasis** [comment] 2020-03-17 21:05
Were we able to get more info on why this is happening. Else thinking of closing this issue until more reports around same behaviour occurs.

PS: Upgrade flows may have resulted in incomplete upgrade of underlying modules and could have been generating errors in console and dev tools. If possible, can you look under the hood and send us the logs?

**Comment by DannyDainton** [comment] 2020-08-15 08:30
Hey @emimarz 

Are you still facing this issue on the latest version?

**Comment by codenirvana** [comment] 2022-01-04 11:21
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2022-01-04 11:21 UTC
Labels: bug, need-more-info, product/runtime
