### ISSUE TITLE
PostMan unable to handle large responses

### ISSUE THREAD

**Issue by kthulsidoss** [a85/POSTMan-Chrome-Extension#5733] opened 2019-01-08 06:02 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

The issue is with postman handling large responses ~14 MB , the postman UI reports back it  cant find the server 

**To Reproduce**
The request is of multi -part form request with file handle , we are supplying input file and the responses that is expected is >=14 MB , the UI shows unable to find the server.

**Expected behavior**
The server sends back a file response
**Screenshots**

**App information (please complete the following information):**
 -  Native App]
 - Postman Version [e.g. 6.2.3]
 - OS: [e.g. windows 2016 server]

**Additional context**

**Comment by kthulsidoss** [comment] 2019-01-08 06:04
![postman_error](https://user-images.githubusercontent.com/42998906/50812582-57e1f300-1339-11e9-9c90-78ebc22abfe8.JPG)

**Comment by kthulsidoss** [comment] 2019-01-08 06:04
sorry by mistake closed it

**Comment by codenirvana** [comment] 2019-01-08 06:13
Duplicate of #4751
Please follow that issue for updates.

**Closed as completed by codenirvana** 2019-01-08 06:13 UTC
Labels: duplicate
