### ISSUE TITLE
CTRL-W Should close a TAB on windows not the whole Postman App

### ISSUE THREAD

**Issue by askpatrickw** [a85/POSTMan-Chrome-Extension#1572] opened 2015-11-18 22:18 UTC
On Windows in every app I can think of (including chrome) CTRL-W closes the tab or document you are working on, not the entire application.

If you can't get the tabs in Postman to act like proper tabs, then I'd prefer you at least prevent CTRL-W from doing anything if you can. Lost some work today. :-(

**Comment by abhijitkane** [comment] 2015-11-19 08:32
This is a Chrome restriction. We can intercept the Ctrl/Cmd + W event, but can't stop it from closing the window. Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1378

**Closed as completed by abhijitkane** 2015-11-19 08:32 UTC
