### ISSUE TITLE
App Icon not available

### ISSUE THREAD

**Issue by ayarrus** [a85/POSTMan-Chrome-Extension#6897] opened 2019-07-10 18:37 UTC
**Describe the bug**
The main icon is not available.

**To Reproduce**
1. Open Postman Ver 7.3.3 (last)

**Expected behavior**
The main icon is not visible.

**Screenshots**
![sdasdasdsad](https://user-images.githubusercontent.com/10744797/60995262-8e201f80-a328-11e9-981b-1e5c46b85a61.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.3.3
 - OS: Microsoft Windows [Versión 10.0.17763.379]

**Comment by carlos-toscano** [comment] 2019-07-10 21:42
I have the same problem in the same version.
![Captura](https://user-images.githubusercontent.com/18338854/61007160-54034d80-a329-11e9-9b3f-19257c5c9f2c.JPG)

**Comment by aaronmbos** [comment] 2019-07-11 12:35
The Postman icon is also not being displayed in the taskbar for me.  I am running the same version of Postman (7.3.3) natively on Windows 10 version 1809.  This seemed to just start happening when Postman updated to 7.3.3.

![postman](https://user-images.githubusercontent.com/24758740/61051296-5065da00-a3ae-11e9-9c5a-6e5ef3020f69.png)

**Comment by ayarrus** [comment] 2019-07-11 12:49
Problem: The main app **change install directory** but **not update the shorcut**.
Fix: **Delete old shorcut, and create new shorcut.**

![ssss](https://user-images.githubusercontent.com/10744797/61052095-0cc89b80-a3c1-11e9-98ae-2d2b82c71362.png)

**Comment by fifteenzhang** [comment] 2019-07-24 07:01
Same Problem With 7.3.4

**Comment by wiggisser** [comment] 2019-07-25 11:08
The icon is not even showing up if I start postman.exe directly from "%userprofile%\AppData\Local\Postman" or "%userprofile%\AppData\Local\Postman\app-7.3.4" directories. 

This is quite annoying because I currently have another (also updated via squirrel) app behaving the same way. Might therefore be a squirrel issue ...

**Comment by fifteenzhang** [comment] 2019-07-26 07:51
It happens with automatic upgrade.And I download the app install package and reinstall it.The icon appears.

**Comment by KSib** [comment] 2019-08-01 14:26
This happens with me every time the automatic upgrade happens. Instead of getting the icon from Update.exe, it keeps trying to look in a directory that doesn't exist. Finally got tired enough of it to post after a few months of it happening.

**Comment by reduckted** [comment] 2019-08-06 00:47
I'm seeing this too on v7.3.6. Seems to be the same as #4814 which was fixed previously.

My shortcut was pointing to the `7.2.2 folder`, but I only have `7.3.4` and `7.3.6` folders.
![image](https://user-images.githubusercontent.com/10321525/62503397-54fba200-b837-11e9-9b78-3d420325cacc.png)

**Comment by harryi3t** [comment] 2019-08-12 09:19
Thanks for reporting this. We were able to reproduce this on our end and are working towards getting this fixed as soon as possible.

**Root Cause**:
Postman internally uses `squirrel` for creating windows distributables. It looks like in the latest version of squirrel, there was a change where the executable (which is referenced in the shortcuts for the icon) was moved to one level up. But, this is created only on a fresh install, not on updates. So when the users update their Postman app, the icon is left broken. The issue is still open but the contributor has suggested a [workaround](https://github.com/Squirrel/Squirrel.Windows/issues/1075#issuecomment-311488107) to manually move the executable. We are currently exploring the suggested workaround doing further testing.

Relevant Issue On Squirrel Project: https://github.com/Squirrel/Squirrel.Windows/issues/1075

__As a workaround, users can do a fresh install of Postman. The data will be retained.__

**Comment by vaibhavghevde** [comment] 2019-08-30 13:51
![image](https://user-images.githubusercontent.com/52920073/64025852-3ef1b080-cb5b-11e9-8427-26ce38c418f9.png)
I have the same problem on windows 10

**Comment by harryi3t** [comment] 2019-09-17 06:18
This is fixed in Postman v7.7.2
Any broken shortcut icons (on desktop and in the start menu) should be fixed once you update to this latest version.

@vaibhavghevde For the pinned icon on the taskbar, please unpin and then pin the application again.

**Closed as completed by harryi3t** 2019-09-17 06:18 UTC
Labels: bug

**Comment by harryi3t** [comment] 2019-09-17 10:46
@uvarvu Moving to this thread since the issue you are facing is regarding broken Postman icon.

The fix we made in v7.7.2 should fix the icons on the desktop and on the start menu under Postman directory. If you had a pinned icon on the taskbar which is broken, please unpin and pin it again.

If the issue still persists, try the following steps:
 - Find the shortcut that has a broken icon. Is it the desktop shortcut or the one in the start menu? Open the broken shortcut in the File Explorer. Share a screenshot of this.
 - Right-click on the shortcut and click on `Properties`
 - In the `Shortcuts` tab click on `Change Icon`. If the icon path is broken it would show a warning. In that case, share the screenshot of the same. If not, it would open up another window with the icon path. In this case, the broken icon might be cached so try restarting your PC.
![image](https://user-images.githubusercontent.com/5207331/65034829-691ddd80-d965-11e9-93e3-5e70698105c8.png)

**Comment by uvarvu** [comment] 2019-09-18 10:34
Those icons are okay it's the ones under "apps & features" and "programs and features" that are broken

![Annotation 2019-09-18 113224](https://user-images.githubusercontent.com/8590819/65141287-37118780-da08-11e9-98d6-07da755388e4.png)

**Comment by harryi3t** [comment] 2019-09-18 10:50
@uvarvu It's a separate issue which we are tracking here https://github.com/postmanlabs/postman-app-support/issues/5468
