### ISSUE TITLE
Postman Runner giving 404 Bad Request for Proper Request

### ISSUE THREAD

**Issue by rajikuchana** [a85/POSTMan-Chrome-Extension#4622] opened 2018-05-30 10:55 UTC
Receiving 404 Bad Request for Valid Request Body in Postman Runner but if i run normal postman window it is working fine.Please help me why this is not working properly.

**Steps to reproduce the behavior:**

Create Collection
Add rest api request using post method
Added input parameters with variable like {{storecode}}
Add Code in Tests tab to check string from the response
Open postman Runner
Select Collection
Select Environment
Select csv file
select Iterations
Click on Start Test

**Expected behavior**

It should provide proper response for valid request but displaying Bad Request

**Screenshots**
PFA

![postman_error](https://user-images.githubusercontent.com/25505499/40716273-07362542-6426-11e8-957a-b349b344ce52.png)

**App information** 

App Type : Native App
Postman Version 6.1.3
OS: Windows 7 64 bit

**Comment by kamalaknn** [comment] 2018-05-30 11:45
Hey @rajikuchana 

Can you make sure that if you are using an environment variable in your request, you have that environment selected before running the collection in runner?

Also, you use the `Postman Console`(View -> Show PostmanConsole) to inspect the actual request that was sent.

**Comment by saswatds** [comment] 2019-09-17 13:51
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by saswatds** 2019-09-17 13:51 UTC
Labels: bug, product/runtime
