### ISSUE TITLE
Runner does not retrieve the latest file data when request contains File type data in body

### ISSUE THREAD

**Issue by jackyzhujiale** [a85/POSTMan-Chrome-Extension#9228] opened 2020-11-03 10:11 UTC
**Describe the bug**
So I have some request, sending File type key value in body. I may update the file, then the API will carry the latest file data to server. However if I run this api in Runner, the api does not read the latest file data, but stuck with the first version.

This bug is introduced between version 7.29.0-7.34.0 (inclusive). It behaves correctly in 7.28.0, but behaves wrong in 7.34.0

**To Reproduce**
1. Create a post API, with "form-data" format body, pass a key-value pair with "File" type value.
2. Put this API under a collection
3. Open Runner window and try run this collection 
4. Now modify the File passed in step 1, but keep file name and location not changed.
5. Retry that collection in the same runner window.
6. Expected that server will received a different File, but in fact server received the same File in 2 call

**Expected behavior**
Expected that server will received a different File, but in fact server received the same File in 2 call

**Screenshots**
Here's the screenshot of my API with a File type value
![Screen Shot 2020-11-03 at 18 09 32](https://user-images.githubusercontent.com/52772762/97972681-d9a0eb80-1dff-11eb-880b-94d99c9add3d.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.34.0
 - OS: [e.g. macOS Catalina 10.15.6]

**Additional context**
1. This bug is introduced between version 7.29.0-7.34.0 (inclusive). It behaves correctly in 7.28.0, but behaves wrong in 7.34.0
2. Click to execute that API in main window behaves correctly (Will send the latest file data). Seems the bug only happens to Runner

**Comment by timbochamp** [comment] 2021-06-14 13:30
This should be fixed in the latest version of the app, as well as on Postman for Web. Please feel free to reopen if the issue is persisting at the same time!

**Closed as completed by timbochamp** 2021-06-14 13:30 UTC
Labels: bug, collection-runner, product/runtime
