### ISSUE TITLE
OS X App - Could not get any response

### ISSUE THREAD

**Issue by KwangzSan** [a85/POSTMan-Chrome-Extension#3865] opened 2017-11-28 01:46 UTC
I just switch from chrome app to os x app and then I got the "Could not get any response" error showing up.
Chrome app still working fine.

## App Details:

```
Postman for Mac
Version 5.3.2
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: 
I just use os x app for the first time.

 2. Expected behaviour:
:)

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Error: Parse Error
Request Headers:
cache-control:"no-cache"
postman-token:"f9dd3a16-27bd-42b6-b2ee-5d75fa524660"

 4. Screenshots (if applicable)
https://drive.google.com/open?id=1fAUbqGc0uuYrPZHAcH_80Q5gEm-Tb28s
https://drive.google.com/open?id=1oUp80i2MV3KhWRHmJTUGVLkqWYp17B3Y
https://drive.google.com/open?id=1bhPukcyBOZ8NW3hByxl8jqOK7f0HP2QR

**Comment by sdnts** [comment] 2017-11-28 12:05
@KwangzSan Can you provide a little more info about the request itself? (URL, scripts etc. if possible)? It'll help me get to the bottom of this faster.

**Comment by KwangzSan** [comment] 2017-12-05 00:15
@madebysid I made a script for you to test. 
http://luckymeow.com/api/test/server/status

**Comment by numaanashraf** [comment] 2018-06-29 13:35
@KwangzSan Thanks a lot for the sample endpoint. We were able to replicate this and it seems to be a bug. We are looking into the root cause and working on a possible fix.

**Comment by numaanashraf** [comment] 2019-03-21 14:30
No longer reproducible on Postman v7.0. Closing this issue for now, please don't hesitate to re-open if you are still facing this issue on Postman v7.0.

<img width="1015" alt="Screenshot 2019-03-21 at 7 58 22 PM" src="https://user-images.githubusercontent.com/3295568/54759284-c2ee5680-4c13-11e9-96dd-614443449a05.png">

**Closed as completed by numaanashraf** 2019-03-21 14:30 UTC
Labels: bug
