### ISSUE TITLE
Collection Export with preselected directory error

### ISSUE THREAD

**Issue by PVGrad** [a85/POSTMan-Chrome-Extension#4217] opened 2018-02-20 13:34 UTC
## App Details:

```
Postman for Mac
Version 5.5.3
OS X 17.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **always**
 2. Expected behaviour: Export should save every time it runs
 3. Console logs: 
```
requester.js:255798 Could not read FileList correctly
requester.js:282877 Filesystem Error: Error: ENOENT: no such file or directory, open '/~/Team.postman_collection.json'
```
 4. Screenshots: [Issue screencast in GIF format](https://imgur.com/a/GAp9S)

Steps to reproduce the problem:
1. press "Export" on collection,
2. press "Export" on opened window,
3. select destination folder from "recent"
4. press "Save" and then "Overwrite"
5. Notification about successful "Save" appears
6. repeat steps 1 and 2
7. destination folder is already holds needed directory
8. press "Save" and then "Overwrite"
9. no dialog about file Overwrite and no file saving

**Comment by preethammavin** [comment] 2018-06-28 08:34
@PVGrad The issue is fixed on our latest build on the native apps, can you update and verify if the issue persists.

**Closed as completed** 2018-06-29 12:54 UTC
Labels: bug
