### ISSUE TITLE
x-amz-server-side​-encryption header for AWS Signature not recognised

### ISSUE THREAD

**Issue by benschmi** [a85/POSTMan-Chrome-Extension#5528] opened 2018-11-14 09:48 UTC
**Describe the bug**
When using the authentication method "AWS signature" und adding the valid header "x-amz-server-side​-encryption:AES256", a PUT and POST returns the following error (taken from Postman console):

`Error: Header name must be a valid HTTP Token ["x-amz-server-side​-encryption"]`

**To Reproduce**
1. Use AWS signature for authentication and use correct AccessKey and SecretKey
2. Add x-amz-server-side​-encryption:AES256 to header for a PUT or POST on a S3 object
3. Press Send
4. See error in console "Error: Header name must be a valid HTTP Token ["x-amz-server-side​-encryption"]"

**Expected behavior**
Executed POST or PUT call with x-amz-server-side​-encryption:AES256 included in the header and a correct calculated authorization signature

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.5.2
 - OS: macOS 10.14.1

**Comment by ddanf** [comment] 2019-06-11 19:24
also encountering this, however, if I change the case of the header (X-Amz-Server-Side-Encryption) it works fine...

**Comment by vikiCoder** [comment] 2019-06-12 12:13
Hi @benschmi,

It looks like you have copy-pasted `["x-amz-server-side​-encryption"]` header from somewhere because it contains some non-ASCII characters which are not allowed to be sent in HTTP headers. I confirmed it by copy-pasting the same header text you posted in the terminal and it looks like below screenshot in the terminal (note the non-ASCII characters after `x-amz-server-side` in the screenshot).

<img width="508" alt="Screenshot 2019-06-12 at 5 33 25 PM" src="https://user-images.githubusercontent.com/16588032/59349989-9f313d00-8d38-11e9-92dc-076e6732d374.png">

This certainly is a bug but it is not related to AWS authentication. Until we fix it, you can type the header manually instead of copying it from somewhere and it should work.

**Comment by codenirvana** [comment] 2019-06-13 07:23
@benschmi As mentioned in https://github.com/postmanlabs/postman-app-support/issues/5528#issuecomment-501246256 this is because of non-ASCII characters present in the header name.

@ddanf Header names are case-insensitive and as we can see the actual issue is not related to that.

We are planning to highlight these invalid characters or whitespaces instead of filtering/removing automatically.
Closing this issue because we are tracking a similar issue here: #4485

**Closed as completed by codenirvana** 2019-06-13 07:23 UTC
Labels: bug, encode-decode, product/runtime
