### ISSUE TITLE
Search and Replace inside the Tests tab

### ISSUE THREAD

**Issue by gototester** [a85/POSTMan-Chrome-Extension#3423] opened 2017-08-22 08:36 UTC
Postman for Windows
Version 5.1.3
win32 10.0.15063 / x64

This seem to be an intermittent bug, which is a bit of a pain,  But it does happen more often than not.
When I do a search and replace (Ctrl + H) on the Tests tab.  Then go and edit the text in the tests tab the page scrolls up and I can’t see the tests anymore.

I found If I do the search and replace I need then I select a different test step and go back to the original test step, then it doesn’t scroll when I try to edit it.

Attached is an example.  
![postman search and replace bug](https://user-images.githubusercontent.com/31238264/29555935-13b2fcd8-871c-11e7-9e53-9e073bf0da19.gif)

**Comment by sdnts** [comment] 2017-08-22 11:48
@gototester I wasn't able to reproduce this. If I understand correctly, after the replace operation, you're just trying to type into the test area, right?

I understand that this doesn't happen every time with you, yes?
Is this only happening for one specific request, or all requests? If there are steps you've found that always causes this to happen, can you post them here? It will help me debug this faster. Thanks.

**Comment by gototester** [comment] 2017-08-22 12:23
@madebysid yes, when I press the space bar to add a space in front of the single quote,  the page shoots down.

yes it is all requests not specific ones.  I was refactoring a load of my tests and noticed this happened a lot.

And that is correct it doesn’t happen every time unfortunately.

Cheers.

**Comment by sdnts** [comment] 2017-08-22 13:37
@gototester I think this is related to the focus being shifted after the replace operation happens.
On Windows, if you press the spacebar in a scrollable view, the view scrolls down automatically. This is default OS behavior, and can be observed in browsers as well. What I suspect is happening is, the focus shifts outside, and you pressing the spacebar scrolls the view down.

To confirm this, can you try pressing some other key? The scroll should not happen then if my hunch is correct.

In any case, this is definitely a bug, and I'm marking it so. Thanks for reporting this!

**Comment by gototester** [comment] 2017-08-23 08:00
@madebysid Just tried it and If i press any other key nothing happens and soon as I press the spacebar the page scrolls up as shown in my original screen capture.

**Comment by sdnts** [comment] 2017-08-23 12:35
@gototester I was able to replicate. This looks like a focus issue, I'll get this fixed in a coming version :)

**Comment by gototester** [comment] 2017-08-26 18:27
Nice one :)

**Comment by a85** [comment] 2017-12-11 15:50
@madebysid Is this fixed?

**Closed as completed** 2018-05-14 09:44 UTC
Labels: bug
