### ISSUE TITLE
Collection runner does not identify the JSON format when selecting Data file

### ISSUE THREAD

**Issue by cbarrerah-sogeti** [a85/POSTMan-Chrome-Extension#4591] opened 2018-05-23 07:09 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When selecting a JSON file as "Data" for the collection runner, it does not recognize the format, neither autodetects the number of items

**To Reproduce**
1. Go to Collection runner with any collection
2. Click on File button to select a json file(example.json) that contains:

> [
	{
		"labelA": "valueA1",
		"labelB": "valueB1"
	},
	{
		"labelA": "valueA2",
		"labelB": "valueB2"
	}
]

3. click on Open to use it for Collection Runner
4. Observe as the "Data File Type" says Undetermined, and the iterations remain at 0

**Expected behavior**
When selecting a valid json, the format is recognized and the iterations selects the number of items in the main array detected by default.
This is the current behaviour with csv files, that are corectly identified .

**Screenshots**
![image](https://user-images.githubusercontent.com/24520879/40408683-aa62abbe-5e68-11e8-9059-e6aabd6f2816.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]: Native App
 - Postman Version [e.g. 6.0.1]
Postman helps you develop APIs faster
Postman for Windows
Version 6.0.10
win32 10.0.15063 / x64

**Additional context**
When manually selecting the JSON format, when going to preview, it correctly identifies the items in the JSON but you still have to fill the iterations field manually.

**Comment by sivcan** [comment] 2018-05-23 07:18
@cbarrerah-sogeti - Cannot reproduce this issue.
I copied the JSON that you provided here and you can see the screenshots.

Can you check creating a new file with another editor?
Maybe some additional characters are added.

![image](https://user-images.githubusercontent.com/12631777/40409176-a03b57c0-5e87-11e8-8cbe-a2d37e87a5ac.png)


![image](https://user-images.githubusercontent.com/12631777/40409063-444eddce-5e87-11e8-9a00-aa9535b0ac9f.png)

**Comment by cbarrerah-sogeti** [comment] 2018-05-23 07:22
Can you try with the file i used?
[example.zip](https://github.com/postmanlabs/postman-app-support/files/2029884/example.zip)

**Comment by sivcan** [comment] 2018-05-23 07:26
@cbarrerah-sogeti Downloaded the file that you gave and it works fine. 
The iterations count is being updated.

![image](https://user-images.githubusercontent.com/12631777/40409423-8297f006-5e88-11e8-919e-f295b3ea65ca.png)

![image](https://user-images.githubusercontent.com/12631777/40409430-868b5fcc-5e88-11e8-8a92-5606a3b61b78.png)

**Comment by cbarrerah-sogeti** [comment] 2018-05-23 07:26
May have something to do with localization or locale identification of values? I'm on es-ES locale if it helps

**Comment by cbarrerah-sogeti** [comment] 2018-05-23 07:27
is there any configuration that i may have inadvertedly changed?
I have to manually change this values tens of time a day, and it is getting rather frustrating.
Let me know if you need any debugging actions on my side.

**Comment by sivcan** [comment] 2018-05-23 07:30
@cbarrerah-sogeti Weird. There's no configuration around this. 
Can you test it out on the canary build ? 
https://www.getpostman.com/canary

Canary builds of the Postman app can run alongside the main app so it won't affect your current app / settings.

**Comment by cbarrerah-sogeti** [comment] 2018-05-23 07:32
downloading right away, will update in 10-15 minutes.
Thanks :)

**Comment by cbarrerah-sogeti** [comment] 2018-05-23 07:44
Same thing with same file :(

**Comment by cbarrerah-sogeti** [comment] 2018-05-23 07:56
Hi, 
did a simple test with an example csv and generated the json in (http://www.convertcsv.com/csv-to-json.htm) so i was not the one creating the json (and consequently could not introduce extra chars)
This is the canary version just installed.

Attaching csv and json generated.
[csvtojson.zip](https://github.com/postmanlabs/postman-app-support/files/2030016/csvtojson.zip)

her you can see the results in gif format.
![csv recognized but not json](https://user-images.githubusercontent.com/24520879/40411021-85c3103a-5e6f-11e8-82b3-2ecc71026d20.gif)

**Comment by sivcan** [comment] 2018-05-23 08:06
@cbarrerah-sogeti - Ahh, I tried the **convertedcsv.json** also. It works fine. 
Can you test with this file?

[data.json.zip](https://github.com/postmanlabs/postman-app-support/files/2030047/data.json.zip)

**Comment by cbarrerah-sogeti** [comment] 2018-05-23 08:12
Does not work either.
I'm on windows, and i noticed that you sent a mac generated file
i tried changing the EOL for all three formats (Win,Mac, Linux) and all presented the same result.

**Comment by sivcan** [comment] 2018-05-23 09:03
@cbarrerah-sogeti Can you confirm by right clicking the file > Properties > General 
The **Type of file** should be JSON

**Comment by sivcan** [comment] 2018-05-23 09:07
@cbarrerah-sogeti I was able to reproduce this on windows.
I'll look into this and get back to you.

**Comment by cbarrerah-sogeti** [comment] 2018-05-23 10:58
Confirmed, it's recognized as a JSON type:
![image](https://user-images.githubusercontent.com/24520879/40420501-eed46a74-5e88-11e8-9e22-1155905d6a33.png)

**Comment by tnjohansson** [comment] 2018-06-29 10:41
Hi, is there a workaround for this issue? I'm on Windows and I'm having the same issue.

**Comment by sivcan** [comment] 2018-06-29 12:36
@tnjohansson We're looking into this issue.
For now, you can simply select 'application/JSON' type from the dropdown and it should work as expected.
Apologies for the inconvenience caused.

**Comment by pritamdharme** [comment] 2019-03-14 10:57
Hi Guys,
![json iterator issue](https://user-images.githubusercontent.com/45936318/54351685-070eb380-4676-11e9-8d5c-99bf0c8034fd.jpg)
Facing the same issue with workaround could you please  look into it.

Reagrds,
Pritam

**Comment by lucielavickova** [comment] 2019-05-05 10:17
hey guys, same issue here... it's quite annoying to select the number of iterations and file type every time :/

**Comment by shamasis** [comment] 2019-05-05 18:44
@lucietriskova - this is a closed issue. It would be great if you file a new feature request explaining your use case. Maybe you could tell us a bit more about when and how do you need it

**Comment by kiwinz2015** [comment] 2019-06-16 22:05
Still able to reproduce.
FYI: I'm using a JSON file (UTF-8)

**Comment by ankurdengla** [comment] 2019-06-18 11:50
The fix for this issue is now available in the latest Canary app - [Postman Canary 7.3.0-canary01](https://www.getpostman.com/downloads/canary). Please check it out and let us know if the issue still persists.

**Comment by kiwinz2015** [comment] 2019-06-18 22:29
> The fix for this issue is now available in the latest Canary app - [Postman Canary 7.3.0-canary01](https://www.getpostman.com/downloads/canary). Please check it out and let us know if the issue still persists.

Hey, it's looking better now in **7.3.0-canary01**, which is not just detecting the Data File Type but also the iteration number. 
Now, I noticed that in the Preview mode all JSON objects are not recognized as shown below:

![2019-06-19_10-14-28](https://user-images.githubusercontent.com/51891425/59723856-ed37ca80-927b-11e9-8c61-1222559312d2.png)

![2019-06-19_10-14-00](https://user-images.githubusercontent.com/51891425/59723869-f45ed880-927b-11e9-9d56-80e69a2eb4c2.png)

Console
![2019-06-19_10-23-36](https://user-images.githubusercontent.com/51891425/59724190-202e8e00-927d-11e9-86ae-765866f53564.png)


Hope this helps.
Cheers!

**Comment by shamasis** [comment] 2019-07-08 15:38
Hey ... this was fixed as part of v7.3 of app.

**Closed as completed by shamasis** 2019-07-08 15:38 UTC
Labels: bug, collection-runner, data-file/json
