### ISSUE TITLE
New Request > Headers tab: After click in default header the tab is going wild and unusable

### ISSUE THREAD

**Issue by aureole82** [a85/POSTMan-Chrome-Extension#9271] opened 2020-11-13 14:11 UTC
![Postman has a really bad UI](https://user-images.githubusercontent.com/4819891/99080791-13bd7a80-25c2-11eb-90ac-b1890dffd276.gif)
Occured in Postman v7.35.0

**Comment by DannyDainton** [comment] 2020-11-13 14:44
Duplicate of: https://github.com/postmanlabs/postman-app-support/issues/9251

**Closed as completed** 2020-11-13 14:44 UTC
Labels: duplicate
