### ISSUE TITLE
Black screen issue with latest version of postman

### ISSUE THREAD

**Issue by eminks** [a85/POSTMan-Chrome-Extension#7767] opened 2019-12-10 07:50 UTC
**Describe the bug**
With the latest update when I open the app get a black screen

**To Reproduce**
Open application 

**Expected behavior**
Any ui element

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/1908412/70505732-c5923280-1b39-11ea-98c7-7364b9050a17.png)

![Screenshot_2](https://user-images.githubusercontent.com/1908412/70505975-5ec14900-1b3a-11ea-865f-aa5b15ac58cb.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.13.0
 - OS: windows 7 32-bit

**Comment by kamalaknn** [comment] 2019-12-10 08:18
Hey @eminks 

Thanks for reporting the issue. This looks like a duplicate of #4764. I'm closing this as a duplicate. Could you share some more information **on the original thread** about

1. When do you see this issue? Does it happen always? 
2. The size of data you are working with, the number of history or requests, the size of the response you are working with?

**Closed as completed by kamalaknn** 2019-12-10 08:18 UTC
