### ISSUE TITLE
Optional query parameters no longer show in documenter

### ISSUE THREAD

**Issue by tlegluhe** [a85/POSTMan-Chrome-Extension#8475] opened 2020-05-13 09:08 UTC
Optional query parameters no longer show in documenter. We can see the names and descriptions of parameters that are checked (and showing in the URL), but others aren't showing. I believe they did in a previous version of the generated documentation. 
This is a problem because I would like my API users to know what options they can call my routes with without showing them all in the URL (it is messy and sometimes params can't combine).

**Screenshots**
This is an example of a request definition I'm doing in the postman app.
![image](https://user-images.githubusercontent.com/37486794/81792511-71d0ae80-9508-11ea-9fe0-efe0b66d30b9.png)

I'd like to see all query params (even unchecked) in the generated documentation. But I get this incomplete documentation
![image](https://user-images.githubusercontent.com/37486794/81793836-2f0fd600-950a-11ea-868b-459d35b1552f.png)

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version 7.24.0
 - OS: Linux

If I'm mistaken in the usage of postman documentation, please guide me and close this issue ! Thanks for the hard work

**Comment by rainabba** [comment] 2020-07-29 23:23
I'm seeing the same right now. My pre-publish view shows optional params in a lighter color font. When I view from the published link, they aren't showing at all (not even in HTML, hidden by CSS or such).

**Comment by Raja-Simha** [comment] 2020-11-19 10:15
Duplicate of #7301

**Closed as completed by Raja-Simha** 2020-11-19 10:15 UTC
Labels: feature, product/documentation
