### ISSUE TITLE
Proxy Socks

### ISSUE THREAD

**Issue by ilicilho** [a85/POSTMan-Chrome-Extension#13184] opened 2024-10-07 13:59 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Is not a problem but a implementation of facility 

### Describe the solution you'd like

Postman suport Socks Proxy.

**Comment by parthverma1** [comment] 2024-10-21 18:10
Thank you for your feature request! It appears that this is a duplicate of an existing issue we are tracking at https://github.com/postmanlabs/postman-app-support/issues/1321. Please feel free to add any further comments or details there.

As such, we will be closing this issue.

**Closed as completed by parthverma1** 2024-10-21 18:10 UTC
Labels: feature
