### ISSUE TITLE
App initialization takes too long

### ISSUE THREAD

**Issue by CharanmeetSingh** [a85/POSTMan-Chrome-Extension#4981] opened 2018-08-07 07:49 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
App is being freezing for about 20-30 minutes and then later it starts normally each time I open it.

**To Reproduce**
1. Simply open app from your PC.
2. Or open app from command prompt user/appdata/local/postman/app6.2.3/postman.exe

**Expected behavior**
App gets freeze on initializing and then loader continues to spin with flashing every second.
Later app gets start after 20-30 minutes.

![capture](https://user-images.githubusercontent.com/29355004/43763633-df098f6a-9a48-11e8-856a-e6d79f9501dd.PNG)

**App information (please complete the following information):**
 - Postman Version 6.2.3 64 bit
 - OS: Windows 8.1 64 bit

**Comment by sivcan** [comment] 2018-08-07 11:35
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4703

**Closed as completed by sivcan** 2018-08-07 11:35 UTC
