### ISSUE TITLE
Exporting to cURL does not handle quotation marks correctly

### ISSUE THREAD

**Issue by johnhamelink** [a85/POSTMan-Chrome-Extension#3482] opened 2017-09-04 13:53 UTC
## App Details:
```
Postman for Mac
Version 5.2.0
OSX 10.12.4
```

## Issue Report:
> 1. Did you encounter this recently, or has this bug always been there:

This is the first time I've encountered this error

> 2. Expected behaviour:

When you export to cURL, the headers should exactly match what what Postman has been running.

>  3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

```
 ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs. 

================================================================
sails.io.js:142 🌏 sync service connectivity initiated
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 connected to sync service.
file:///Applications/Postman.app/Contents/Resources/app/html/mode-auto.js Failed to load resource: net::ERR_FILE_NOT_FOUND
```

 4. Screenshots (if applicable)

<img width="731" alt="screen shot 2017-09-04 at 14 31 00" src="https://user-images.githubusercontent.com/101739/30029259-73bdf42a-9180-11e7-8cda-23814366a931.png">

When exporting a request to cURL, the exporter needlessly escapes quotation marks.

**Comment by petermarcoen** [comment] 2017-09-22 12:57
This issue cause my OAuth 1.0 request to not work with Curl while it did work for Postman

**Comment by q42jaap** [comment] 2017-10-19 13:36
This is also happening for NodeJS Native, NodeJS request types of code snippet.

**Comment by harryi3t** [comment] 2017-12-18 09:38
@johnhamelink @petermarcoen @q42jaap 
I have confirmed the bug and we are looking into it. Since there is an already open issue for this here https://github.com/postmanlabs/postman-app-support/issues/2947, I am marking this as duplicate and closing it.

Please subscribe to the original issue for updates.

**Closed as completed by harryi3t** 2017-12-18 09:38 UTC
