### ISSUE TITLE
Download dialog box does not automatically resize on macOS

### ISSUE THREAD

**Issue by BenJuan26** [a85/POSTMan-Chrome-Extension#5867] opened 2019-01-31 18:39 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
In the `Download` dialog box on macOS, clicking the down/up arrow to switch between simple and advanced finder views does not resize the window. Clicking the button a second time greys out the button, so the user can't go back and forth. Furthermore, the entire dialog cannot be dragged at all when it is in this 'in-between' state.

**To Reproduce**
1. Send any request that returns content
2. Click on 'Download'
3. Note that the dialog can currently be dragged around by the title bar
4. Click the down arrow
5. See that the screen is not expanded to show the advanced finder view (although it can be resized manually)
6. See that the dialog now cannot be dragged by the title bar (although it can be dragged at the very top once the cursor turn into the double-sided resize arrow)
7. Click the up arrow
8. See that it is greyed out
9. Click on 'Cancel'
10. Click on 'Download' again
11. See that the advanced finder view is now shown, and the problem is now the same but in reverse

**Expected behavior**
In macOS, when that down 'expand' arrow is clicked, the window is supposed to resize you can navigate folders, create a new folder, etc. The opposite is also true: if the advanced view is currently selected, clicking the up arrow should contract the window into the simplified view.

**Screenshots**
<img width="349" alt="image" src="https://user-images.githubusercontent.com/4079548/52076500-cd1d9e00-255c-11e9-9390-d9e6d47a997a.png">
<img width="349" alt="image" src="https://user-images.githubusercontent.com/4079548/52076516-d575d900-255c-11e9-9697-fbf92ddf4099.png">
<img width="842" alt="image" src="https://user-images.githubusercontent.com/4079548/52076593-00602d00-255d-11e9-8a16-5ba01a01dfb0.png">
<img width="843" alt="image" src="https://user-images.githubusercontent.com/4079548/52076624-0f46df80-255d-11e9-96ea-5d5c98841773.png">

**App information (please complete the following information):**
 - Native App
 - Postman 6.7.1
 - macOS Mojave 10.14.2

**Comment by numaanashraf** [comment] 2019-02-03 06:12
@BenJuan26 Thanks for reporting this. We are tracking this together with a related issue at #5381. Please follow that for updates. Closing this as duplicate.

Duplicate of #5381

**Closed as completed by numaanashraf** 2019-02-03 06:12 UTC
