### ISSUE TITLE
Mac app have problem with url encode for chinese

### ISSUE THREAD

**Issue by jappre** [a85/POSTMan-Chrome-Extension#2252] opened 2016-08-11 09:16 UTC
1. Postman Version: 4.5.1
2. App (Chrome app or Mac app): Mac app
3. OS details: OS X 10.11.6
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: in the version 4.0, it`s ok,but this always been there since 4.5.1, AND, the latest chrome app is also ok.
6. Expected behavior: it should be encode the chinese, but don`t.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by SunChJ** [comment] 2016-08-11 09:29
I have the same problem, and it influenced my work. fix it soon plz

**Comment by shamasis** [comment] 2016-08-11 17:57
yes. we are on it.

**Comment by numaanashraf** [comment] 2016-08-17 11:55
duplicate of #2263. closing this since that issue is a superset of this.

**Closed as completed by numaanashraf** 2016-08-17 11:55 UTC
