### ISSUE TITLE
Memory Leak? Slowdown and leading to Hang in App.

### ISSUE THREAD

**Issue by MrBenGriffin** [a85/POSTMan-Chrome-Extension#3649] opened 2017-10-18 09:42 UTC
## App Details:

```
Postman for Mac
Version 5.3.0
OS X 15.6.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: 
I'm new to Postman
 2. Expected behaviour: 
Fast switching between examples, instead of increasingly larger delays.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
They didn't seem to help much - I gathered 800 MB of data while the delay was happening - and it recorded lots of GC activity.

 4. Screenshots (if applicable)
![hang](https://user-images.githubusercontent.com/1785064/31711102-fc5bd5fa-b3ee-11e7-9a85-e55656330ce8.png)
Hangs here, for as much as a minute or more.

Not really sure - it's something about creating lots of examples with documentation seems to slow the app to a hang. The problem reliably shows up  After going through making edits to each endpoint, and editing each example (maybe 40 different examples across 20 requests)

**Comment by prashantagarwal** [comment] 2017-10-18 10:29
@MrBenGriffin Thanks for reporting this. We will be investigating this issue.

**Comment by MrBenGriffin** [comment] 2017-10-18 10:31
@prashantagarwal, it may have been fixed in today's update (Version 5.3.1), to be honest.

**Comment by sdnts** [comment] 2017-10-18 11:15
@MrBenGriffin Out of curiosity, how large are these responses? 2 examples per request should not slow down the app as much.

**Comment by MrBenGriffin** [comment] 2017-10-18 12:37
Not that many - about 15 or 20 examples, and each of them are small.  I know it's another thing, but also it would be good to be able to delete cookies - especially private cookies - from examples.

**Comment by prashantagarwal** [comment] 2017-10-27 04:27
@MrBenGriffin We were able to identify the cause for it. We have released a fix for this in 5.3.2 . Feel free to reopen the issue if you are still facing this issue.

**Closed as completed by prashantagarwal** 2017-10-27 04:27 UTC
Labels: pending-close
