### ISSUE TITLE
Using Beautify function to format body as json will change the value of key

### ISSUE THREAD

**Issue by QuSoyol** [a85/POSTMan-Chrome-Extension#8396] opened 2020-04-27 05:58 UTC
**Describe the bug**
Using Beautify function to format body as json will change the value of key

**To Reproduce**
1. Paste the data on body
2. Click on 'Beautify'
3. Check the value of key which the type is number

**Expected behavior**
The value of key which the type is number shouldn't be changed

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type : Chrome App
 - Postman Version : 7.23.0
 - OS: Postman for Windows win32 10.0.18362 / x64

**Additional context**
example data like this :
{"id":1254251321528160258}

**Comment by kamalaknn** [comment] 2020-04-27 06:18
Hey @QuSoyol 

Thanks for reporting this issue. It looks like this is related to other issues where the content of the JSON body is modified when beautifying. The root cause is how Postman formats the JSON. We use Javascript method - `JSON.stringify` to format JSON and  Javascript has limitations on the numbers it can handle. 

Employing other ways to format JSON would fix this issue. I'm closing this as a duplicate of #5658. Please subscribe to the original thread for updates on the fix.

**Closed as completed by kamalaknn** 2020-04-27 06:18 UTC
