### ISSUE TITLE
Postman Requests Hang when Interceptor is enabled

### ISSUE THREAD

**Issue by greensombrero** [a85/POSTMan-Chrome-Extension#3164] opened 2017-06-14 17:30 UTC
## App Details:

```
Postman for Chrome
Version 5.0.0
OS X / x86-64
Chrome 58.0.3029.110
```

## Issue Report:
I recently started trying to use the interceptor with Postman and now when the interceptor is enabled in Postman every request hangs.  If I disable the interceptor in Postman all is well.

Things I've tried:

1. Enabling/disabling the interceptor extension
2. Rebooting my computer
3. Uninstall and reinstalling the interceptor extension

Any ideas what else I should try?  I really want to disable auto following redirects and my understanding is this requires I have the interceptor turned on.

**Comment by greensombrero** [comment] 2017-06-14 17:32
Also I'm running Postman Interceptor Version  0.2.22

**Comment by kamalaknn** [comment] 2017-06-15 09:44
Hey @greensombrero 

Thanks for reporting this. We'll take a look at it once and get back to you.

**Comment by ivaaaan** [comment] 2017-06-16 07:42
the same problem. +1

**Comment by chiedo** [comment] 2017-06-22 17:38
Same problem even after disabling interceptor

**Comment by sdnts** [comment] 2017-06-23 09:45
@greensombrero If you're only looking to disable redirects, I'd recommend our [native apps](http://getpostman.com/apps), which have this functionality built-in.

@ivaaaan @chiedo I'm unable to reproduce this with a request to `postman-echo.com/get`. Is this only happening for some endpoints? If so, could you add an example here?

**Comment by chiedo** [comment] 2017-06-23 11:28
Hi @madebysid 

I can't GET request any endpoint. Not even google.com.

Thanks for the quick response

**Comment by sdnts** [comment] 2017-07-10 10:54
@chiedo We recently pushed a fix for the interceptor which should address this. Can you try force updating the interceptor and try again?
You can force update by visiting `chrome://extensions/` and clicking on `Update Extensions.`

**Comment by chiedo** [comment] 2017-07-10 12:33
Still no luck. Thanks for trying @madebysid

**Comment by abhijitkane** [comment] 2019-11-30 08:25
@chiedo Closing this. We've deprecated the Chrome app, and the native apps (https://www.getpostman.com/downloads/) let you control the redirect behavior without the interceptor extension.

Other features including request/cookie syncing with the Interceptor are coming soon.

**Closed as completed by abhijitkane** 2019-11-30 08:25 UTC
Labels: bug, platform/chrome, Interceptor
