### ISSUE TITLE
Getting Error: tunneling socket could not be established, statusCode=407 error

### ISSUE THREAD

**Issue by santoshclicks** [a85/POSTMan-Chrome-Extension#8931] opened 2020-08-13 14:25 UTC
I have started getting below error
Error: tunneling socket could not be established, statusCode=407
Earlier it used to work, I work before company proxy I have made proxy settings and which was working earlier for. The same setting is working for my collegue now as well.

**Comment by DannyDainton** [comment] 2020-08-13 15:01
Duplicate of #8783

**Closed as completed by DannyDainton** 2020-08-13 15:01 UTC
Labels: duplicate
