### ISSUE TITLE
syncing?

### ISSUE THREAD

**Issue by eugene-sotirescu** [a85/POSTMan-Chrome-Extension#1526] opened 2015-10-27 02:08 UTC
i am in postman, i go to Manage Profile then to Collections, double click on the collection i'm interested in, everything is there.
i go back to postman and sync. but the "local" collection is not synced, even though it says "In Sync" it's missing several items.
what am i doing wrong?

**Comment by sobtiankit** [comment] 2015-10-27 03:30
Hi 

For some reason the app seems to have reached an inconsistent state. There are 3 things that you can do here, in this order:
1. Hover over the collection in the left sidebar, click on the 3 dots, click on share and then Resync.
2. If it doesn't work, click on Settings in the toolbar at the top right, click on Sync and then Force Sync.
3. Last, but before make sure all your requests are displayed on the website (Manage Profile > Collections). Then sign out and sign back in, it will restore the app state from the server.

Hope it helps

**Comment by srilaxmi215** [comment] 2016-10-06 17:42
Postman app is not syncing and doesnt import any of my collections from web
Sync is stuck  at "Connecting"
Need help to see my collections in the app

**Comment by sdnts** [comment] 2016-10-07 06:14
@srilaxmi215 Do you see any errors in the DevTools console (Cmd/Ctrl + Alt + I) ? If yes, could you post a screenshot here?
In any case, a logout + restart + login should resolve the issue.

**Comment by srilaxmi215** [comment] 2016-10-13 18:21
Hi

Issue did not get resolved for me

Is there a way we can make postman honor network proxy settings
I have already applied proxy settings on postman

Thanks
Sri

**Comment by a85** [comment] 2017-04-08 20:00
Closing as duplicate of #1658

**Closed as completed by a85** 2017-04-08 20:00 UTC
Labels: support, sync
