### ISSUE TITLE
Published copy missing first letter of URL when using variable

### ISSUE THREAD

**Issue by datazen** [a85/POSTMan-Chrome-Extension#6376] opened 2019-04-27 16:27 UTC
Using latest version 7.0.9

Set a custom variable for API URL and when publish the docs, the first letter of the URL is missing.

![grabilla 000032](https://user-images.githubusercontent.com/3129247/56852312-c39b9c00-68e7-11e9-96f9-56a669152bed.png)

![grabilla 996288](https://user-images.githubusercontent.com/3129247/56852313-c72f2300-68e7-11e9-91c8-2a2384873d21.png)

**Comment by dhineshwiz** [comment] 2019-04-29 16:58
Hey @datazen I couldn't reproduce this issue, Can you recheck with variable values, and if it still persists, please do send us the published url, it will help us in debugging

**Comment by Raja-Simha** [comment] 2019-05-17 04:47
We haven't been able to reproduce this issue and haven't received any additional information. I am closing this issue. @datazen, please reopen with further information if the issue still persists.

**Closed as completed by Raja-Simha** 2019-05-17 04:47 UTC
Labels: bug, product/documentation
