### ISSUE TITLE
Can't copy and paste if the password isn't visible

### ISSUE THREAD

**Issue by Duduxs** [a85/POSTMan-Chrome-Extension#9969] opened 2021-05-24 16:29 UTC
**Issue**

When I try to copy a basic authorization password, and for example I try to paste it elsewhere, the current value is not pasted. Unless I click on the "Show Password" checkbox and try to copy, however copying the password with the checkbox unchecked is the same as nothing.

**Steps to Reproduce**

1 - Enter the Postman
2 - Create any http request
3 - Add Basic Auth type authorization
4 - Enter any password with the "Show password" checkbox disabled
5 - Now try to copy your password and put it somewhere else

**Environment Information**

 - Platform Type: Desktop
 - Postman Version: 8.5.1
 - Operating System: Ubuntu 20 LTS

**Comment by DannyDainton** [comment] 2022-05-05 10:59
Hey @Duduxs 

I'm going to close this issue for now - This appears to be working as intended. 

Do you have an example, in a different application, of copying a masked password and this showing unmasked when pasted?

**Closed as completed by DannyDainton** 2022-05-05 10:59 UTC
Labels: Auth, user-interface, product/runtime
