### ISSUE TITLE
Mismatch of collection order between app/runner and documenter/monitor.

### ISSUE THREAD

**Issue by AndySoHotRightNow** [a85/POSTMan-Chrome-Extension#3867] opened 2017-11-28 09:45 UTC
## App Details:

Version 5.3.2 (5.3.2) for Mac

## Issue Report:
 
There is a discrepancy between the order of folders/requests of my collection on the app/runner and on the documenter/monitor despite the app indicator claiming everything is "in Sync".

Here are the screenshots to clarify:

_Order of items is "admins", "guests1", "categories", "dashboard"... etc._

**App**

![App](https://user-images.githubusercontent.com/17130123/33312589-4c38e574-d463-11e7-94b7-c4ba04511066.png)

**Runner**

![Runner](https://user-images.githubusercontent.com/17130123/33312624-60030b48-d463-11e7-9de2-44a0aaaeb24d.png)

_Order of items is "categories", "dashboard", "guests1", "institutions"... etc._

**Documenter**

![Documenter](https://user-images.githubusercontent.com/17130123/33312668-7ea38960-d463-11e7-92c3-9ba7233d99c1.png)

**Monitor**

![Monitor](https://user-images.githubusercontent.com/17130123/33312691-8b73f210-d463-11e7-866b-fc155173cd2b.png)

**Comment by sdnts** [comment] 2017-11-28 12:08
@AndySoHotRightNow The order reflected in the Documenter and Monitoring is the order actually stored on our servers. Can you try a force sync? You can do this by pressing the Sync icon again.

If that doesn't help, can you head over to https://app.getpostman.com/library/collections and check if all your requests are there? If so, signing out + signing in should solve your issue.

**Comment by AndySoHotRightNow** [comment] 2017-11-28 13:59
Thanks.

Force syncing didn't change a thing but the second suggestion (to log-out and back in) did solve the issue.

At this point what I would suggest Postman to do is investigate why the Sync indicator reflects an incorrect sync status.

From my point of view the problem is solved.

Just a heads up, the link [https://app.getpostman.com/library/collections]() leads to a 404, I think you meant [https://app.getpostman.com/dashboard/collections](). Thanks again.

**Comment by a85** [comment] 2017-12-13 22:39
@AndySoHotRightNow Glad the issue is fixed. Closing this.

**Closed as completed by a85** 2017-12-13 22:39 UTC
Labels: support, sync
