### ISSUE TITLE
Postman Pro API Collection Names With Trailing Space

### ISSUE THREAD

**Issue by jcald1** [a85/POSTMan-Chrome-Extension#7981] opened 2020-02-01 02:06 UTC
The following collection comes back to the Postman Pro API client application with trailing space in the name.  However, there is no trailing space in the UI client or web.

{
      id: '64084678-a735-4b2e-9292-163bccfe6eca',
      name: 'BW Media Platform API ',
      owner: '7337586',
      uid: '7337586-64084678-a735-4b2e-9292-163bccfe6eca'
    }

**Comment by shamasis** [comment] 2020-03-16 21:35
Can you export the collection and send us after removing any sensitive data? @jcald1 ... also can you try Postman Canary (postman.com/canary) to check if your collection in UI has some invisible character that’s for some reason translating to newline in our APIs?

**Comment by jcald1** [comment] 2020-03-28 01:19
@shamasis , attached.  I don't see an extra space or character in Postman Canary.
[BW Media Platform API.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/4396474/BW.Media.Platform.API.postman_collection.json.zip)

**Comment by DannyDainton** [comment] 2020-08-28 10:21
Hey @jcald1 

Is this still an issue for you on the latest version on the app?

**Comment by Mechanicalkeyboard** [comment] 2020-09-14 14:05
Closing this issue for now, if the issue is still present, please feel free to reopen

**Closed as completed by Mechanicalkeyboard** 2020-09-14 14:05 UTC
Labels: bug, product/runtime
