### ISSUE TITLE
Can no longer reorder requests w/in a folder

### ISSUE THREAD

**Issue by brandonh-msft** [a85/POSTMan-Chrome-Extension#3291] opened 2017-07-20 17:40 UTC
## App Details:

```
Postman for Windows
Version 5.1.1
win32 10.0.16232 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Just encountered after recent update(s). When you attempt to reorder w/in a subfolder, the item is placed at the top level (collection root) no matter where you drop it.
 2. Expected behaviour:
I should be able to reorder requests w/in a subfolder in a collection. This was possible before 5.1.1

**Comment by SamvelRaja** [comment] 2017-07-21 00:50
@brandonh-msft are you seeing any error in the console?  
Can you provide me exact steps to reproduce the issue?

**Comment by brandonh-msft** [comment] 2017-07-24 18:35
repro steps are pretty self-explanatory

1. Create a collection
1. put one request in the collection
1. create a folder w/in the collection
1. put one request in the folder
1. try to move the item from step 2 in to the folder.
1. try to reorder the requests w/in the folder

**Comment by oooarthur** [comment] 2017-07-25 09:33
Seeing this too in 5.1.2 Also can't reorder existing tests in a folder

**Comment by oooarthur** [comment] 2017-07-25 09:45
Workaround seems to be to duplicate the "offending" request. You can reorder that ok, and then delete the original

**Comment by SamvelRaja** [comment] 2017-07-25 10:49
@brandonh-msft, @oooarthur I tried reproducing the same from my end but it works from my end.

Attaching a gif to represent the steps i followed. let me know if i need to test any specific flow i missed.
![reorde_request](https://user-images.githubusercontent.com/5114052/28568854-fa18d52c-7154-11e7-8aaa-690e3f66753f.gif)


If you guys sees any errors in the console kindle send it at help[at]getpostman.com
you can find them in View -> Show DevTools

**Comment by brandonh-msft** [comment] 2017-07-25 18:37
what happens if you add more requests and keep trying? mine all have much more than two in them (5+)

**Comment by ludocode** [comment] 2017-07-30 15:04
Can confirm, this bug is happening here also, starting with 5.1.2. I cannot re-order requests within folders, neither on Arch Linux nor on Mac OS X with version 5.1.2.

The [workaround suggested above](https://github.com/postmanlabs/postman-app-support/issues/3291#issuecomment-317686516) does not work here. It seems a copied request can only be moved once, and even then, its new position is not sync'd with other users, and is lost if you log out and back in again. Nothing is printed to the Dev Tools console.

I was able to work around this by downgrading one of my machines to 5.0.2. It is able to re-order within folders just fine, and the results are immediately reflected on other machines running 5.1.2 logged into the same account, so it's definitely the 5.1.2 UI that is broken.

**Comment by ValentinOdier** [comment] 2017-07-31 07:11
Hi, same here . I have 1 folder with many folders in it. When i'm at the bottom of the tree i can't reorder my requests. Sometimes i get it working sometimes not. If a copy my folder it usually unlock the situation.

------ 
Postman for Chrome
Version 5.1.2
linux / x86-64
Chrome not on.

**Comment by josslamberti** [comment] 2017-08-01 09:40
I'm pretty sure the issue has been introduced (or reintroduced if it existed earlier) in 5.1.2.
It's not 100% reproducible and sometimes, the duplicating workaround works, but other times it doesn't.
This is on the Chrome extension.
I have not updated the standalone app and I have no such issue there.

**Comment by dannyhajj** [comment] 2017-08-01 10:10
I had a similar issue, but maybe this can offer more details.

I have a large collection with many subfolders, and one of those folders has a subfolder on its own (Gonna call it a sub-subfolder). Ordering items, in subfolders, is possible. But ordering items, in the sub-subfolder, is not possible.

While trying to order one of those items, I was not able to position it in a different location inside the sub-subfolder. However, when I tried to position it as the last item in the sub-subfolder, the item got placed in the top level of my collection outside all folders and subfolders (just as what happened with OP).

Trying to move it back into the sub-subfolder is not possible. I had to re-save it again in order to move it back.

Edit: @SamvelRaja I created a new collection and cannot reproduce the issue in that new collection. However, the problem remains in my older collection and is always reproducible even after restarting Postman.

Ubuntu 17.04
Postman for Linux 5.1.2
linux 4.10.0-28-generic / x64

**Comment by josslamberti** [comment] 2017-08-01 10:17
I don't use subfolders so is this issue only happening on the lowest level of a given collection?

**Comment by miguelhughes** [comment] 2017-08-01 12:06
I'm have this as well. apparently started yesterday when upgraded to 5.1.2
it happens on team/shared collections, in folders with just 4 tests, or in folders with 12 or more tests. On collections only owned by me, I can reorder fine. I hope this helps.

The test gets grayed out when dragging but the orange line that indicates the new position doesn't show up within the same folder. Nevertheless, I can drag it out of the folder and into another folder, and it's added at the bottom of the destination collection.
Keep up the good work! love postman.

**Comment by sdnts** [comment] 2017-08-02 13:13
Guys, we're taking a deeper look into this. I'll keep you guys updated here.

@dannyhajj Weird that it happens only for older collections. subfolders and sub-subfolders shouldn't be behaving differently at all.

**Comment by mjkraner** [comment] 2017-08-03 14:58
I'm having this same issue, I am doing a lot of copying of tests and after I copy I can't move the copied one.  Also have had issues where I can't move tests into folders.  However, I have had some tests that I have copied and can move with no issues. Very frustrating!

**Comment by josslamberti** [comment] 2017-08-03 15:00
I can confirm that the issue is reproducible with 5.1.3.
I'm so glad I've not updated the standalone app yet.

**Comment by miguelhughes** [comment] 2017-08-03 16:53
I’ve updated to 5.1.3 and its working somewhat better. the ui feedback of
moving a test is still missing (no orange rulers), but if I drop it in
another place, it moves.

sometimes it goes back to previous behavior and won’t move them, I noticed
it happens when I have the collection runner open.

**Comment by elmojo** [comment] 2017-08-03 20:19
I have 5.1.3 and am also experiencing this issue as well.  Seems to have been introduced with 5.1.2 which allowed nested folders.

Sometimes the issue causes the UI to do nothing when trying to reorder, other times it moves the request to the parent collection, ejecting it from the folder.

**Comment by SamvelRaja** [comment] 2017-08-22 06:09
Hey all, 
We pushed out *Canary app(5.2.0-canary02)* with fixes for reordering problem you all facing, can you  guys help in testing the same from your end?

Just download and install the app according to your os.
*NOTE:*  Backup the data in current app using Settings -> Data -> Export  for additional security.

https://dl.pstmn.io/download/channel/canary/osx_64
https://dl.pstmn.io/download/channel/canary/windows_32
https://dl.pstmn.io/download/channel/canary/windows_64
https://dl.pstmn.io/download/channel/canary/linux_32
https://dl.pstmn.io/download/channel/canary/linux_64

**Comment by ghost** [comment] 2017-08-22 08:29
On first glance, using Canary 5.2.0 solves the reordering problem for me. 
Thanks a lot!

**Comment by anladwig** [comment] 2017-08-23 20:41
I can also confirm that reordering requests now works in Postman v5.2.0-canary02. Thanks!

**Comment by BrianKilby** [comment] 2017-08-24 15:42
Also seeing this issue for a while now.

**Comment by sdnts** [comment] 2017-08-25 08:29
@BrianKilby Can you try this on the canary build?

**Comment by beneberle** [comment] 2017-08-25 21:48
I was seeing the reorder bug with a particular shared collection and Postman Canary 5.2.0 solved it for me as well. Thanks!

**Comment by reynard2007** [comment] 2017-08-31 03:08
The Canary build fixed it for me already. Thanks!

**Comment by SamvelRaja** [comment] 2017-08-31 04:39
@ All,
We just released the 5.2.0 which includes the fix for this problem. Can you guys confirm the fix from your end by updating to the latest.

**Comment by josslamberti** [comment] 2017-08-31 06:14
I tested 5.2.0 all day yesterday and the issue is no longer reproducible. 
Thanks!

**Comment by sdnts** [comment] 2017-08-31 07:07
Awesome, closing this!

**Closed as completed by sdnts** 2017-08-31 07:07 UTC
Labels: bug

**Comment by josslamberti** [comment] 2017-09-05 16:16
This issue is not completely gone, I'm afraid. I've reproduced it twice in 2 days.
Small difference, the dragged request gets sent to another folder (so far an adjacent one) of the same collection rather than being sent to the root of the collection (I only use folders, not subfolders, so far).
It seems the issue is related with an ongoing syncing issue because I get a number of sync issues to fix after that.
When you drag a request between another 2, the orange line that identifies where it's going to go flicks between 2 very close by positions. When I dropped the request to the lower of the 2, the issue disappeared.

**Comment by SamvelRaja** [comment] 2017-09-07 05:54
@josslamberti  It will be very much useful if you can provide me a screencast 😄 
I am having a hard time in reproducing the issue you are facing.

**Comment by josslamberti** [comment] 2017-09-07 12:14
As soon as I can reproduce it, I'll provide a recording.

**Comment by josslamberti** [comment] 2017-09-19 08:36
@SamvelRaja I have reproduced the issue and have a recording of it. How do you want me to share it privately with you?

**Comment by SamvelRaja** [comment] 2017-09-19 10:11
@josslamberti kindly post it here.

**Comment by SamvelRaja** [comment] 2017-09-19 11:13
@josslamberti Received your screencast thanks for it 👍

**Comment by dannyhajj** [comment] 2017-09-22 08:27
Very sorry for the late reply, but I just wanted to let you know that my problem went away on its own before even updating to v5.2.0-canary02 (I was still on 5.1.2).
I had thought I'd open the DevTools and see if there are any logs that would show up while rearranging the requests. But nothing showed up, and everything was working fine. I never had any problems since.
Not sure if I had done anything else myself that may have fixed my issue.

**Comment by josslamberti** [comment] 2017-10-30 08:44
I've been reproducing the issue more and more over the last few days. It's starting to really impact my output.
Since I'm the only one apparently still reporting it, could there be an issue with my repository? Should I do a backup, delete everything and import everything again? Do you think this may help?
Thanks in advance.

**Comment by SamvelRaja** [comment] 2017-10-30 09:01
@josslamberti  The data you provided is proper as far I went through it. If your data is already synced with the postman server, you can go ahead, log out and log in back should get the fresh sets of data from the sync server.
By which we are ensuring that the corrupted local data is removed.

**Comment by josslamberti** [comment] 2017-10-30 09:20
Sync is off so I'll be doing it via a manual back up.

**Comment by josslamberti** [comment] 2017-11-03 10:56
So far, since I have cleared my repository and reimported (instead of replacing), the issue has not occurred yet. 

EDIT: It has now.

**Comment by josslamberti** [comment] 2017-12-15 07:53
@SamvelRaja, this is still very much an issue for me, even after saving a back-up, deleting all my collections and importing my back-up.
It looks like the issue is linked to creating duplicates.

**Comment by josslamberti** [comment] 2018-01-04 13:27
If anyone is still looking at reproducing this issue, it seems to occur more with a large repository and after having opened a large number of tabs.

**Comment by mbejda** [comment] 2021-08-10 13:01
The issue is still there even in the most latest 8.X.X. I can re-order but the order doesn't save. :(

**Comment by giridharvc7** [comment] 2021-08-10 13:27
@mbejda This feature is released, not completely sure why you are facing this issue -  can you drop a mail to help@postman.com ? 
@postman-support
