### ISSUE TITLE
Right click does not work

### ISSUE THREAD

**Issue by scottburnsmb** [a85/POSTMan-Chrome-Extension#2966] opened 2017-04-20 18:23 UTC
1. Postman Version: Version 4.10.7
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: On
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: Can right click to set variables
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Try to right click on a value in a response to set a variable.

**Comment by kachinger** [comment] 2017-05-23 23:41
We are facing the issue with below conditions:
· Using Windows 7 Pro edition (64 bit Dell laptop).
· We tried installing 64 and 32 bit versions.
· Right click works everywhere else in the system, it also works on the Windows frame that holds Postman app but not in the app itself.
· We tried to uninstall Postman, laptop was naturally rebooted multiple times.

**Comment by SamvelRaja** [comment] 2017-09-07 06:27
We are unable to reproduce this issue in our latest 5.3 version of the app. Kindly provide a screencast if the problem still persists.
Closing this for now, kindly feel free to open if you face it again 😄

**Closed as completed by SamvelRaja** 2017-09-07 06:27 UTC
Labels: bug
