### ISSUE TITLE
GRPC Connection Failed to Load Server Reflection

### ISSUE THREAD

**Issue by Bedagya-Joshi** [a85/POSTMan-Chrome-Extension#12999] opened 2024-07-10 15:22 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The newest patch of Postman v11.3.1 on Windows OS has encountered some bugs when trying to load server reflection using GRPC. When downgrading to version 11.2.34 it works fine and after the upgrade the server reflection can not be loaded due to the following error. 
"Could not load server reflection.
Details: no such Type or Enum '.Channel.ControlsEntry' in Type .Channel"

### Steps To Reproduce

Could not load server reflection.
Details: no such Type or Enum '.Channel.ControlsEntry' in Type .Channel

### Operating System

Windows

### Postman Version

11.3.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ronork** [comment] 2024-07-10 15:28
This issue is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/12997

**Closed as completed by ronork** 2024-07-10 15:28 UTC

**Comment by ronork** [comment] 2024-07-12 06:32
Hey, @Bedagya-Joshi  thank you for reporting the issue. 
We have resolved this issue in the latest release of the Postman app (v11.3.2). Please update your app to verify if everything is now working correctly.
