### ISSUE TITLE
Headers with same name are not chained

### ISSUE THREAD

**Issue by rofthedeep** [a85/POSTMan-Chrome-Extension#7314] opened 2019-09-12 16:03 UTC
**Describe the bug**
The behaviour from Postmans API Call and the CURL request is different.

**To Reproduce**
1. Go to Headers tab and create Headers with same name
![Bildschirmfoto 2019-09-12 um 17 55 57](https://user-images.githubusercontent.com/2420176/64800327-b32e4a00-d586-11e9-9ce1-3cd10e8a9634.png)
2. Click on Send
3. In the header of the request you can find only the last value of "User-Interest"
![Bildschirmfoto 2019-09-12 um 17 56 15](https://user-images.githubusercontent.com/2420176/64800475-f7214f00-d586-11e9-81af-e70c7ceb6ccd.png)
4. Click on "Code" and get the CURL request value. Trigger the curl request on command Line
![Bildschirmfoto 2019-09-12 um 17 55 57](https://user-images.githubusercontent.com/2420176/64800734-6139f400-d587-11e9-9d96-aed8b68c924c.png)
5. You get all "User-Interest" Headers chained
![Bildschirmfoto 2019-09-12 um 17 56 15](https://user-images.githubusercontent.com/2420176/64800746-65fea800-d587-11e9-9702-ded3fbdda5d5.png)

**Expected behavior**
All User-Interest Headers chained, like with the CURL Request.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [Version 7.6.0 (7.6.0)]
 - OS: [e.g. macOS Mojave 10.14.6]

**Comment by vikiCoder** [comment] 2019-09-17 12:45
Hi @rofthedeep 

Can you please send the same request to `https://postman-echo.com/get` and show the response you get? 

According to my understanding, postman-echo should show comma-separated values for `User-Interest` header which is correct. I believe the culprit here is the generated `cURL` request which should have multiple headers added separately instead of combining them into the single header with comma(`,`).

**Comment by rofthedeep** [comment] 2019-09-26 11:28
Hi @vikiCoder 
this is the response I get:

`{
    "args": {},
    "headers": {
        "x-forwarded-proto": "https",
        "host": "postman-echo.com",
        "accept": "*/*",
        "accept-encoding": "gzip, deflate",
        "authorization": "Basic Y29tZWNvOnByZXZpZXc=",
        "cache-control": "no-cache",
        "cookie": "sails.sid=s%3AE3eBmWRqX5BPQEIRAHZAL602OglhLplj.WZ1YkEaBqdbruK%2FHudHKnCp6ZE%2Be%2Fxaj0ul42l33ZKY",
        "postman-token": "cc70efb6-cf3b-42fd-b819-16aff03b6a20",
        "user-agent": "PostmanRuntime/7.17.1",
        "user-interest": "2ea64cef-c28f-4849-a9c9-2839a7ff16d4, 7c979f38-b380-48cb-b923-c32a42e79dab, 41a74c70-323b-4f05-a93f-640875427d9a",
        "x-forwarded-port": "443"
    },
    "url": "https://postman-echo.com/get"
}`

**Comment by DannyDainton** [comment] 2020-08-28 11:05
Hey @rofthedeep 

Is this something that's still causing an issue of could we close this issue now?

**Comment by Mechanicalkeyboard** [comment] 2020-09-04 16:13
I was unable to reproduce the issue. If this comes up again, please feel free to reopen!

**Closed as completed by Mechanicalkeyboard** 2020-09-04 16:13 UTC
Labels: bug, code-generator, product/ops
