### ISSUE TITLE
Digest Auth in MD5-sess does not work

### ISSUE THREAD

**Issue by kota65535** [a85/POSTMan-Chrome-Extension#2941] opened 2017-04-12 13:23 UTC
1. Postman Version: v4.10.7
 2. App (Chrome app or Mac app): Linux app
 3. OS details: Cent OS 7
 4. Is the Interceptor on and enabled in the app: There is no interceptor but proxy setting icon... 
 5. Did you encounter this recently, or has this bug always been there: always
 6. Expected behaviour: 

I've tested using [this page ](https://httpbin.org/).
This address below can be accessed by user: `aaa` and password: `bbb`.
https://httpbin.org/digest-auth/auth/aaa/bbb/MD5-sess

### Steps to Reproduce

1. In Authorization tab, type blow:
Type: `Digest Auth`
Username: `aaa`
Realm: `{{echo_digest_realm}}`
Password: `bbb`
Nonce: `{{echo_digest_nonce}}`
Algorithm: `MD5-sess`
qop: `auth`

2. Hit the "Update Request" button.
3. Send  GET request to `https://httpbin.org/digest-auth/auth/aaa/bbb/MD5-sess`.
4. 401 UNAUTHORIZED will be returned.

I also realized that `nc` and `cnonce` in generated Authorization header are always blank. As far as I know, MD5-sess uses this value to calculate hash. I think this is the cause of the problem.

I found this closed issue #932 , which seems to be related to this problem.

**Comment by medjai** [comment] 2017-06-12 04:10
@czardoz Will this be fixed in the windows client too? I can also confirm that using {{echo_digest_realm}} and {{echo_digest_nonce}} does not work

**Comment by nushydude** [comment] 2017-06-21 05:54
I too can reproduce this issue on 5.0.1 Chrome app.

**Comment by medjai** [comment] 2017-06-28 23:30
@numaanashraf When can we expect this to be fixed? This is a major roadblock for me. I am using Postman to work with our devices here at work and test API implementation but our devices ONLY support digest authentication. It has been months since this issue was reported

**Comment by medjai** [comment] 2017-08-20 01:12
@kunagpal This has been assigned and re-assigned many times with no resolution for months. Can we expect this to be fixed soon?

MD5 and MD5-session both don't work!

**Comment by harryi3t** [comment] 2017-09-20 12:07
@medjai MD5 does work
![image](https://user-images.githubusercontent.com/5207331/30642481-b411024c-9e28-11e7-9f68-de2765355fd1.png)
Let me know if you have issues with MD5. (Also in next release we are supporting auto-detection of nonce and realm from the server response, so the user would have to fill the username and password only and it will just work)

@kota65535  About MD5-sess, from what I tested [httpbin](https://httpbin.org/) does not even support MD5-sess
This can be verified by looking at the response headers when you call this end-point
![image](https://user-images.githubusercontent.com/5207331/30642552-f4d5aeb8-9e28-11e7-8c73-e7cf66539e11.png)

IMO they are doing the partial matching of the URL. So anything after (/MD5-xxxxx) work hit the `/MD5` endpoint
![image](https://user-images.githubusercontent.com/5207331/30642681-6fcb6f2c-9e29-11e7-8776-64c3baa98b58.png)

I have checked the code and found that [the logic is there](https://github.com/postmanlabs/postman-runtime/blob/develop/lib/authorizer/digest.js#L156) to handle `MD5-sess` algorithm. So that should also work, but I don't have an endpoint to verify this.
![image](https://user-images.githubusercontent.com/5207331/30642869-2213d76e-9e2a-11e7-8793-5244712030e0.png)

~The [passport-http](https://www.npmjs.com/package/passport-http) module also does not support MD5-sess :(~
I would really appreciate if anyone can help me point to endpoint on which I can test MD5-sess

### Update
[passport-http](https://www.npmjs.com/package/passport-http) does support MD5-sess
I will test using it, and if there is a  bug it will be fixed soon.

**Comment by harryi3t** [comment] 2017-09-22 10:57
### Update:

I can confirm that `MD5-sess` does not work. Tested with `passport-http`
expected to be fixed in Postman 5.3

**Comment by medjai** [comment] 2017-09-22 13:59
Harendra and All,

Am i testing this incorrectly? I should expect this 401 error initially but
the Realm and Nonce should be sent again from that 401 reply and I should
be authenticated and see my intended response. Is this not the case?

[image: Inline image 1]

**Comment by harryi3t** [comment] 2017-09-25 06:53
@medjai 
I see what's happening. 
Right now Postman does not support any interactivity in the auths.
By `interactivity` I mean, from the response to the first request, making the second request and so on (like the browsers).
Right now Users have to fill the details manually.
For digest auth, it means you need to fill the `realm` and `nonce` manually.

But the good news is, we are shipping Postman 5.3 (around the 1st week, Oct) with this interactive mode.
That means from 5.3 onwards making one request will suffice.

**Comment by medjai** [comment] 2017-09-25 21:17
Thank you for the clarification! This is exactly what I've been looking
for!

**Comment by medjai** [comment] 2017-10-05 15:07
Harendra,

Do you have any timeline on Postman 5.3 release? Would you let me know if
this has been delayed?

**Comment by harryi3t** [comment] 2017-10-06 17:35
@kota65535 @medjai 
Postman 5.3 is released 🎉  I need at-least one confirmation that this has fixed the issue. 
Can you guys please check it

**Comment by medjai** [comment] 2017-10-06 22:24
Harendra,

I see that this does work now but sometimes it fails and I have to send the
command again not sure why

**Comment by harryi3t** [comment] 2017-10-07 07:41
@medjai I will be more than happy to assist you in resolving the issue.
Could you provide me with some more details around when it fails?
1. Please open the `postman console` (view -> Show postman console) and clear any logs, if present.
2. Send the request (having digest auth)
3. take a screenshot of postman console
4. expand all the logs and each section and copy the content
5. Send this info either here in the comment or if you prefer you can send an email to me `harendra[at]getpostman[dot]com`
we also have a slack community channel `https://www.getpostman.com/slack-invite`

Note: You can obfuscate the confidential information.

Sample Data (with incorrect credentials):

![image](https://user-images.githubusercontent.com/5207331/31305804-7d0ea7c4-ab5f-11e7-84c6-c4e3ac462f59.png)

#### Request 1
```
Request Headers:
cache-control:"no-cache"
postman-token:"7aeca5bf-d427-441e-8a25-741be0dcb35d"
user-agent:"PostmanRuntime/6.4.0"
accept:"*/*"
host:"postman-echo.com"
cookie:"sails.sid=s%3A7gzzlN1D6N3wgANJsxW9CPPscNLyb6a3.GPJ2LhdTqUXbizLmVVXFV0tmIkk4nASabXL1aeJjsyc"
accept-encoding:"gzip, deflate"
Response Headers:
server:"nginx/1.10.2"
date:"Sat, 07 Oct 2017 07:30:14 GMT"
transfer-encoding:"chunked"
connection:"keep-alive"
access-control-allow-origin:""
access-control-allow-credentials:""
access-control-allow-methods:""
access-control-allow-headers:""
access-control-expose-headers:""
www-authenticate:"Digest realm="Users", nonce="46W85Y6C4Tqg60AHzk9reefedCBOTPtO", qop="auth""
set-cookie:"sails.sid=s%3Advm-wlwPxQpgcCCHWdD_MgZPSXdiKyN0.DQi%2BRTIopYZS3EctlUDqVAWkKCzS6L7HV53DEnhvmHw; Path=/; HttpOnly"
Response Body:
Unauthorized
```

#### Request 2
```
Request Headers:
cache-control:"no-cache"
postman-token:"7aeca5bf-d427-441e-8a25-741be0dcb35d"
user-agent:"PostmanRuntime/6.4.0"
accept:"*/*"
host:"postman-echo.com"
cookie:"sails.sid=s%3A7gzzlN1D6N3wgANJsxW9CPPscNLyb6a3.GPJ2LhdTqUXbizLmVVXFV0tmIkk4nASabXL1aeJjsyc; sails.sid=s%3Advm-wlwPxQpgcCCHWdD_MgZPSXdiKyN0.DQi%2BRTIopYZS3EctlUDqVAWkKCzS6L7HV53DEnhvmHw"
accept-encoding:"gzip, deflate"
authorization:"Digest username="postma", realm="Users", nonce="46W85Y6C4Tqg60AHzk9reefedCBOTPtO", uri="/digest-auth", algorithm="MD5", qop=auth, nc=00000001, cnonce="LJFQgdmI", response="1ec44e3e24689df0cfb1c791504582ee""
Response Headers:
server:"nginx/1.10.2"
date:"Sat, 07 Oct 2017 07:30:15 GMT"
transfer-encoding:"chunked"
connection:"keep-alive"
access-control-allow-origin:""
access-control-allow-credentials:""
access-control-allow-methods:""
access-control-allow-headers:""
access-control-expose-headers:""
www-authenticate:"Digest realm="Users", nonce="hgZwfOlRjnhNw4YdARByCwQURey6Ol0o", qop="auth""
set-cookie:"sails.sid=s%3AMSTj8SedIxdEJmLFl14qbyKTAnFjy_8h.hfsh0dzrcCIKM7YiQAPOUY9tfEtttUdelQbfMgxxFqU; Path=/; HttpOnly"
Response Body:
Unauthorized
```

And so on for Request 3 and 4

**Comment by medjai** [comment] 2017-10-09 13:36
@harryi3t I wanted to break this up into two issues but I am using a product that utilizes Digest Auth and ServerPush to reply back to the API call (continually pushes live information about the product). 

When utilizing Digest Auth MD5 with local variables it seems to fail the first time even though "Yes, disable retrying the request" is turned off.

Second issue is that Postman doesn't seem to support server push. (These are unrelated so I'll open up a different issue for this)

Video: [REDACTED]

**Comment by medjai** [comment] 2017-10-09 13:50
I forgot to attach the console log. Please see

![image](https://user-images.githubusercontent.com/16169426/31341365-46afeb88-acd7-11e7-809c-0412f42cdb8f.png)

**Comment by harryi3t** [comment] 2017-10-09 14:02
@medjai Thanks for the video and the screenshot. But unfortunately, they don't show what's happening behind the scenes. I need the logs for all the requests that are being sent.

To avoid too many back and forth comments here, would you mind joining our slack community channel where I can directly help you out?
Here's the link to join - https://www.getpostman.com/slack-invite

**Comment by medjai** [comment] 2017-10-11 15:25
works as expected had to remove the echo variables.

**Comment by medjai** [comment] 2017-10-11 15:26
@harryi3t  @shamasis can you please close this?

**Closed as completed** 2017-10-11 15:38 UTC
Labels: bug, Auth
