### ISSUE TITLE
Members in the team not receiving Monitoring summary emails

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6085] opened 2019-03-15 07:51 UTC
**Describe the bug**
Members in the team not receiving Monitoring summary emails

**Expected behavior**
Team members should receive summary emails for monitors created by their teammates.

**Comment by godfrzero** [comment] 2019-04-09 02:12
We've pushed out a fix for this issue. Team members will now receive summary mailers once they've opted in, even if they themselves haven't run any monitors during the relevant (daily, weekly) period.

**Comment by godfrzero** [comment] 2019-04-24 07:43
We've received a report of a case where the email delivery is not behaving as expected and a teammate is not receiving a summary mailer. We're investigating and we'll post an update here when it's available.

**Comment by AnkitMasand** [comment] 2019-04-24 10:36
We have identified the root cause of the issue. The fix will be rolled out as soon as the development and testing are done. Will update the status here once we are ready with the fix.

**Comment by AnkitMasand** [comment] 2019-05-01 16:07
We have verified and released our fix for this issue.
Team members will now receive summary mailers once they've opted in, even if they themselves haven't run any monitors during the relevant (daily, weekly) period.

**Closed as completed** 2019-05-01 16:07 UTC
Labels: bug, product/automation-testing
