### ISSUE TITLE
Strange behavior when in environments

### ISSUE THREAD

**Issue by ivaaaan** [a85/POSTMan-Chrome-Extension#4354] opened 2018-03-19 09:41 UTC
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 17.5.0 / x64
```

## Issue Report:
I'm working with my team in PostMan Premium, and before the update to 6.0 this problem was no there. But now, we have for example 6 environments. When I edit one of the environment, that environment also updates for all team members. Why? In 5.0 version we had Environment templates, where they now?

So expected behavior:
When I edit some variables in the environment, the same environment should not be updated for other team members.

**Comment by kamalaknn** [comment] 2018-03-19 11:17
Him @ivaaaan 

Starting with `Postman 6.0` we've made environments editable by everyone it is shared with. You should be able to create new environments that are not shared that don't update across the team. 

I'm closing this issue as this is not a bug. You can also go through [discussions on our community forum](https://community.getpostman.com/search?q=environments) for ways to solve your use case.

**Closed as completed by kamalaknn** 2018-03-19 11:17 UTC
