### ISSUE TITLE
Right click > Copy doesn't work

### ISSUE THREAD

**Issue by DerekSansom** [a85/POSTMan-Chrome-Extension#4108] opened 2018-01-25 14:59 UTC
## App Details:

Postman for Linux
Version 5.3.2
linux 4.10.0-42-generic / x64

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
ALways
 2. Expected behaviour:
Select some text in response field > right click > copy, paste to a text file, expect it to paste the copied text
But it doesn't, it pastes whatever was copied before.
Ctrl C does work as expected

  3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by lucasyvas** [comment] 2018-01-30 18:22
Also having this issue on Linux (Ubuntu 17.10)

Edit: Postman 5.5.2

**Comment by viking225** [comment] 2018-02-02 15:58
Also having this issue on Ubuntu (16.04 LTS).

Postman version: 5.5.0

**Comment by akaars** [comment] 2018-02-05 13:19
Reproducible for me. I see the similar issue was fixed for Mac, but we, Linux users, still need a fix :)

**Comment by akaars** [comment] 2018-02-05 13:23
Temporary workaround was to switch themes (Light to Dark, Dark to Light) - now the copy-paste works. Don't know for how long...

**Comment by prashantagarwal** [comment] 2018-02-08 12:56
Hey guys, we will get this issue investigated and release the possible fix.

**Comment by BrixSat** [comment] 2018-05-14 09:31
Ubuntu 18.04 does not work either! only by using ctrl + insert and shift insert.

**Comment by harryi3t** [comment] 2018-05-14 12:29
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3691
Please subscribe to the original issue for further updates

**Closed as completed by harryi3t** 2018-05-14 12:29 UTC

**Comment by kletkeman** [comment] 2018-06-08 21:46
MacOS -- this horrible behavior is pure torture ... I want to be able to copy any text from any panel and past anywhere else in the POSTMAN interface, and the behaviour is totally random. Sometimes it works and sometimes it does not.

**Comment by oyvigri** [comment] 2018-08-10 07:57
This is still not fixed?

**Comment by sudhirkhanger** [comment] 2019-04-03 05:51
This is not fixed. Right click copy-paste options, Unix's selection to copy, etc. don't work. Could someone please open this issue?

**Comment by abhijitkane** [comment] 2019-04-03 05:57
@sudhirkhanger Can you add a comment on https://github.com/postmanlabs/postman-app-support/issues/3691 and mention your app version?

**Comment by khwilo** [comment] 2019-07-26 07:36
I also have the issue. The workaround for me is to copy all the response to the clipboard by clicking the icon on the top right corner next to search icon of the response output: 
![postman-copy-issue](https://user-images.githubusercontent.com/5740429/61934347-c2cee080-af90-11e9-9282-01d37ce8b647.PNG)

I then paste the copied items to another editor. Then from there, I copy the values I want from the editor to POSTMAN.

**Comment by mhlenux** [comment] 2019-08-05 10:34
Same problem, Windows 10

**Comment by ravisanwal** [comment] 2019-09-10 18:52
Same problem. My observation is that there is a delay of some sort. If you wait long enough after focus, it works.

**Comment by neg3ntropy** [comment] 2019-09-17 09:37
This never worked well and it is mostly broken now. Terrible experience.
