### ISSUE TITLE
Can't copy all output in console for7.17.0

### ISSUE THREAD

**Issue by TianLiuAu** [a85/POSTMan-Chrome-Extension#8082] opened 2020-02-19 02:58 UTC
**Describe the bug**
I can't copy whole output in Console after run any collections

**To Reproduce**
1. Click Runner, Postman Console on any workspace.
2. Select a collection, Environment, Data , then Start Run in Runner
3. In the Postman Console, should see some output of the collection
4. Click Edit-Select All, then Copy
5. Open Notepad, and ctrl+v
6. Only see a few lines of the whole output

**Expected behavior**
In Notepad, should see all output lines pasted

**App information (please complete the following information):**
 - App Type : Postman for Windows
 - Postman Version: Version 7.17.0
 - OS: win32 10.0.17763 / x64

**Additional context**
My colleagues met the same issue as I did, and for postman version 6, there's no such issue.

**Comment by ritwijsinha** [comment] 2020-03-02 06:10
Duplicate of #7685

**Closed as completed by ritwijsinha** 2020-03-02 06:10 UTC
Labels: duplicate, product/runtime
