### ISSUE TITLE
Consolidation of HTML, JSON reports when running different folders with different iterations

### ISSUE THREAD

**Issue by raghav19** [a85/POSTMan-Chrome-Extension#5012] opened 2018-08-13 05:39 UTC
**Use Case:** 

1. POST call REST API for multiple iterations. 
2. GET call REST API after all iterations of POST call is completed
3. Validate the list retrieved.

**Current Solutions tried:**
**-  Solution 1**
      Create a separate folder in collection and put GET call
      2) Run 1 iteration of POST and GET call for that 1 iteration
      3)  Validate
      Issue: Actual use case not solved      

**-  Solution 2**
      1) Create a separate collection for the GET request   
       2)  Call the collection in newman CLI after the POST request
      Issue: Separate HTML reports are generated, need it consolidated

**Actual Solution Required:**
1. Create POST request in a folder in a collection and set iteration count for that folder
2. Create GET request in a folder in a collection and set iteration count for that folder
3. Run collection as a whole where postman/newman would pick the iteration count assigned at per folder level and run the test in Postman & Newman.
4. Single HTML, JSON report will get generated

**Provide either of the 2 solutions**
1. Controlling the iteration for data source at per folder level[Most preferred]
2.  Consolidated HTML,JSON reports when running through newman 

If there is any better solutions for this, please let me know.

**Comment by sivcan** [comment] 2018-08-13 10:14
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4996

On solving https://github.com/postmanlabs/postman-app-support/issues/4996, this use-case will be solved too.

**Closed as completed by sivcan** 2018-08-13 10:14 UTC
Labels: feature, collection-runner
