### ISSUE TITLE
Can we have sock5 proxy in the app? Thanks!

### ISSUE THREAD

**Issue by tanglin0123** [a85/POSTMan-Chrome-Extension#4821] opened 2018-07-13 03:26 UTC
Hi,

Can we have sock5 proxy in Postman app? 
Although I can change the system proxy to workaround, I don't want to always change it as it is shared by other apps.

Thanks!

## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by SamvelRaja** [comment] 2018-07-13 05:35
Duplicate of #1321

**Closed as completed by SamvelRaja** 2018-07-13 05:35 UTC
