### ISSUE TITLE
Roaming profile completely breaks postman (windows 7)

### ISSUE THREAD

**Issue by darrenshrwd** [a85/POSTMan-Chrome-Extension#4889] opened 2018-07-26 01:26 UTC
**To Reproduce**
1. Have two laptops on the same network that share your roaming profile.
2. Try and install on one then the other (done cleanly as detailed below)

**Expected behavior**
The second laptop does not open the app from shortcut, when I ran it from the command prompt within the [user]\AppData\Local\Postman\app-6.1.4\ I got "Shared window not present".

**App information**
 - Native App
 - Postman Version: 6.1.4
 - OS: Windows 7 Enterprise

**Additional Context**
Setting a new laptop seemed to break postman on my current laptop, gave up trying to repair, uninstalled on both, cleared out local and roaming profile (I abandoned my collections).

I could not get the 64bit installer to work on either (few issues including this one). So I cleared out everything again, and tried the 32bit installer, it worked on 'current' laptop, so I then tried it several times on the the new laptop, clearly out the local folder each time.

...Have an idea...

**Comment by darrenshrwd** [comment] 2018-07-26 01:43
...I decided to completely shut down my old machine and try again on the new, it then got further, however had all the following issues on the chrome console:
![capture](https://user-images.githubusercontent.com/417178/43236551-0edc239e-90c9-11e8-8541-b819e2631cd2.PNG)

**Comment by darrenshrwd** [comment] 2018-07-26 01:47
...I then started up the old machine and tried opening Postman on that (leaving other one open), did not open.

Then I shut down the new laptop...tried to open it on the old laptop, broken.

Exactly the same errors as above.

**Comment by darrenshrwd** [comment] 2018-07-26 01:54
**Workaround:** If you are moving to a new laptop that will be connected to the same domain you will have to delete your roaming profile folder ([user]\AppData\Roaming\Postman\ ) from the network before using on another machine. (You can **NOT** successfully alternate between machines and keep your profile).

**Comment by SamvelRaja** [comment] 2018-07-31 08:52
Duplicate of #4669

**Closed as completed by SamvelRaja** 2018-07-31 08:52 UTC
Labels: bug

**Comment by darrenshrwd** [comment] 2018-08-01 03:07
I can't see how this is a duplicate
