### ISSUE TITLE
Slecting (by dragging cursor) url from json response body will open new request tab

### ISSUE THREAD

**Issue by rasentry** [a85/POSTMan-Chrome-Extension#7104] opened 2019-08-13 11:15 UTC
**Describe the bug**
Selecting by dragging cursor, right or left click on url in json response body,
all actions do the same - open a new request tab.

**Expected behavior**
Ability to copy url from response.

**App information (please complete the following information):**
Postman for Windows
Version 7.5.0
win32 10.0.18362 / x64

**Comment by ankurdengla** [comment] 2019-08-14 08:35
Closing as it is duplicate of https://github.com/postmanlabs/postman-app-support/issues/6984

**Closed as completed by ankurdengla** 2019-08-14 08:35 UTC
