### ISSUE TITLE
Not able to send null value from csv file

### ISSUE THREAD

**Issue by vebs60719** [a85/POSTMan-Chrome-Extension#4078] opened 2018-01-18 05:58 UTC
## App Details:

Postman for Windows
Version 5.5.0
OS Windows X 

## Issue Report:

After sending null value for optional variables from csv, Postman is not able to understand null value.
For Example : "VariablaName" = "{{VariableName}}"
Same csv is working correctly from Chrome Extension.

Screenshot From Postman Windows version : 
![image](https://user-images.githubusercontent.com/35371204/35082522-a1cf8c5c-fc1a-11e7-9ccf-a29a14d14b56.png)

Screenshot From Postman Chrome Extension : 
![image](https://user-images.githubusercontent.com/35371204/35082558-d5d6d046-fc1a-11e7-9372-a82d18056737.png)

[new.txt](https://github.com/postmanlabs/postman-app-support/files/1641748/new.txt)

Steps to reproduce the problem : 

1. Create post request with variables such as ( I have attached csv file with txt extension, you can change extension to csv again )

{
  "data":{
    "type": "TypeName",
    "Variable": "{{Variable}}",
    ""Variable1": "Variable1",
    "Variable2": "{{Variable2}}",
    "Variable3": "{{Variable3}}"
  }
}

2. Create one Collection and place post request inside collection.

3. Create csv file with columns 'Variable', 'Variable2', 'Variable3' and values under respective columns.

4. Click Run Collection -> Select Environment, Select Data as csv file.

5. Click Run button.

**Comment by sdnts** [comment] 2018-01-18 12:08
Hi @vebs60719, thanks for reporting this. We'll be taking a look at bugs related to CSV parsing in the app soon, I'll make sure we fix this as well. I'll let you know here when I do.

**Comment by tflintio** [comment] 2018-07-24 21:10
Is there a work-around for this issue?

**Comment by vebs60719** [comment] 2018-07-25 04:12
work-around for this issue, it is working from Postman Browser App.

**Comment by sivcan** [comment] 2018-08-01 10:07
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/2970

**Closed as completed by sivcan** 2018-08-01 10:07 UTC
Labels: bug
