### ISSUE TITLE
Content Length Header doesn't update automatically on updating the body

### ISSUE THREAD

**Issue by MrDHat** [a85/POSTMan-Chrome-Extension#7396] opened 2019-09-26 19:02 UTC
**Describe the bug**
On updating the content for the request, the `Content-Length` header does not get updated automatically in the mac app

**To Reproduce**
1. Send a POST request
2. Update the request body
3. Send the request again
4. It'll fail

**Expected behavior**
It should update the `Content-Length` header automatically.

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]: Native
 - Postman Version [e.g. 6.0.1]: Version 7.7.3 (7.7.3)
 - OS: [e.g. macOS High Sierra 10.13.2]: MacOS Mojave 10.14.6 (18G95)

**Comment by saswatds** [comment] 2019-09-26 19:55
Hi @MrDHat, I am not able to reproduce this issue on the said version of app. 
<img width="959" alt="Screenshot 2019-09-27 at 1 23 15 AM" src="https://user-images.githubusercontent.com/8796447/65720372-75244080-e0c5-11e9-8e25-b86d8683b249.png">
<img width="970" alt="Screenshot 2019-09-27 at 1 23 30 AM" src="https://user-images.githubusercontent.com/8796447/65720373-75bcd700-e0c5-11e9-867e-70deaabaa512.png">
These are the two request's that I have sent, and as you can see the content-length does change from `4` to `8` 

Can you use the same `https://postman-echo.com/post` endpoint and verify that content-length is the issue?

**Comment by chainhead** [comment] 2019-10-01 15:00
@saswatds in your screenshot, are they _response_ headers? I have raised a similar issue/feature request - https://github.com/postmanlabs/postman-app-support/issues/7413

**Comment by saswatds** [comment] 2019-10-01 15:24
Hi @chainhead They are the request headers being sent by postman. The echo server echo's back whatever the client sends.

**Comment by saswatds** [comment] 2019-11-28 07:48
We have not been able to reproduce this issue on our end and no other users have reported the same happening. Closing this issue now. Feel free to re-open if you provide us more details on how to reproduce.

**Closed as completed by saswatds** 2019-11-28 07:48 UTC
Labels: product/runtime, blocked/need-repro
