### ISSUE TITLE
Currently Not able to use special characters in Request tests tab and its displaying error

### ISSUE THREAD

**Issue by vishnuprakash9845** [a85/POSTMan-Chrome-Extension#11080] opened 2022-07-13 07:38 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

So I am getting the response like this.

![image](https://user-images.githubusercontent.com/24207575/178676735-0e880e07-370d-481c-b982-27e1f27c0176.png)

 I want the value underlined and set to global variable. I can use below json path to get it.

![image](https://user-images.githubusercontent.com/24207575/178676936-ac175c88-f5ac-45fe-8d31-25797cabf1b0.png)

But in postman If I try same json path, its giving error. Any way to avoid it or any workaround is there.

### Describe the solution you'd like

So in the in Request tests tab, if there are options to allow wild card it would really help

### Describe alternatives you've considered

I tried googling and approached Manual API Testers to find the solution for this issue, hard luck couldn't get it.

**Comment by DannyDainton** [comment] 2022-07-13 08:48
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/11081

**Closed as completed** 2022-07-13 08:48 UTC
Labels: feature
