### ISSUE TITLE
Should be able to arrange the Collections by moving up and down in Postman- REST Client (Packaged App)

### ISSUE THREAD

**Issue by parsiamyt** [a85/POSTMan-Chrome-Extension#1018] opened 2015-04-21 10:54 UTC
Using the Postman- REST Client (Packaged App), liked all the features and it is helping me in overall project but can't arrange my Collections. Should be able to move up and down, hide the collections.

Thanks.

**Comment by a85** [comment] 2015-07-17 23:52
Closing as a duplicate of #363

**Closed as completed by a85** 2015-07-17 23:52 UTC
Labels: feature
