### ISSUE TITLE
cURL import without space parameter

### ISSUE THREAD

**Issue by senpl** [a85/POSTMan-Chrome-Extension#3279] opened 2017-07-17 12:52 UTC
## App Details:
Postman for Linux
Version 5.0.2
linux 4.4.0-59-generic / x64

## Issue Report:
 1. Problem was present in previous and current version
 2. Expected behaviour: Import -> Paste Raw Text -> curl -H"data=example1&data2=example2" http://URL/example.cgi 
to be imported, it work with space after -H curl -H "data=example1&data2=example2" http://URL/example.cgi
 3. not required
 4. not applicable

Steps to reproduce the problem
1. Click Import 
2. Click "Paste Raw Text"
3. Paste 

> curl -H"data=example1&data2=example2" http://URL/example.cgi 

into field (this is valid curl command, so it should not be that hard to be imported, or at least error message should be more descriptive).
4. Press import (error appears to be imported, it work with space after -H curl -H "data=example1&data2=example2" http://URL/example.cgi). Same fix is needed for -d parameter(and probably all supported).

**Comment by prashantagarwal** [comment] 2017-07-19 06:58
@senpl Thanks for reporting this. We are looking into the issue.

**Comment by SamvelRaja** [comment] 2018-06-29 13:31
Duplicate of #3135

**Closed as completed by SamvelRaja** 2018-06-29 13:31 UTC
Labels: bug
