### ISSUE TITLE
Postman Response not being displayed

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1041] opened 2015-05-04 17:11 UTC
I am sending a POST to a method and when Postman gets the response, it displays the generic 'Could not get any response' message. I used Soap UI to capture the response and here's what is actually being returned below. I would hope that Postman would show a raw response, even if malformed, instead of showing there was no response at all. Any ideas on why Postman is reacting this way?

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<response>
  <status code="201">Save was successful.</status>
  <messages />
  <timestamp>1430759238165</timestamp>
  <content>
    <wfprocessscheduler-list>
      <wfprocessscheduler href="http://localhost:8080/PM/REST/entity/wfprocessscheduler/pk/14307592381510000" entityrefid="14307592381510000">
        <wfappointment-list>
          <wfappointment href="http://localhost:8080/PM/REST/entity/wfappointment/pk/14307592381560000" entityrefid="14307592381560000" />
          <wfappointment href="http://localhost:8080/PM/REST/entity/wfappointment/pk/14307592381590000" entityrefid="14307592381590000" />
        </wfappointment-list>
      </wfprocessscheduler>
      <wfprocessscheduler href="http://localhost:8080/PM/REST/entity/wfprocessscheduler/pk/14307592381610000" entityrefid="14307592381610000" />
    </wfprocessscheduler-list>
  </content>
</response>
```

**Comment by abhijitkane** [comment] 2015-05-05 07:20
@spoolie031  What version of Postman are you using?

**Comment by ghost** [comment] 2015-05-05 12:37
2.0.25

On Tue, May 5, 2015 at 2:20 AM, Abhijit Kane notifications@github.com
wrote:

> @spoolie031 https://github.com/spoolie031 What version of Postman are
> you using?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/a85/POSTMan-Chrome-Extension/issues/1041#issuecomment-98980864
> .

## 

[image: CallidusCloud Connections] 
http://calliduscloudconnections.com/register/?RefID=cc-signature-banner&utm_source=callidus&utm_medium=signature&utm_campaign=c32015
*CallidusCloud HQ *has moved. 
Our new address is: 
4140 Dublin Blvd, Suite 400, Dublin, CA 94568

**Comment by abhijitkane** [comment] 2015-05-05 12:39
You can enable the DevTools for Postman - http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/, and right click > Inspect Element > Network. Are you seeing the response body?

If yes, check for error messages in the Console tab (also in DevTools)

**Comment by ghost** [comment] 2015-05-05 13:09
The response is not being shown, but here's what's appearing in the console:

actual 'dpi' of a screen. In media query expression:
(-webkit-min-device-pixel-ratio: 1.25), (min-resolution: 120dpi)
extensions::platformApp:17 window.onbeforeunload is not available in
packaged apps.(anonymous function) @ extensions::platformApp:17
requester.js:1137 Checking for update notifications...
requester.js:836 Initialize interceptor
requester.js:22077 ThemeSettingsTab: Purchase is available
requester.js:1146 Stored version: 2.0.25, currentVersion: 2.0.25
extensions::webView:97 <webview>: contentWindow is not available at this
time. It will become available when the page has finished
loading.(anonymous function) @ extensions::webView:97
requester.js:23642 8:6:6.75 - Uncaught TypeError: Cannot read property
'postMessage' of undefinedBackbone.Model.extend.errorForce @
requester.js:23642
requester.js:26606 Uncaught TypeError: Cannot read property 'postMessage'
of undefined
http://fhbjgbiflinjbdggehcddcbncdddomop/socket.io/1/?__sails_io_sdk_version…io_sdk_platform=browser&__sails_io_sdk_language=javascript&t=1430831196658
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://fhbjgbiflinjbdggehcddcbncdddomop/socket.io/1/?__sails_io_sdk_version…io_sdk_platform=browser&__sails_io_sdk_language=javascript&t=1430831196661
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
requester.js:12864 Purchase saved
requester.js:12647 Error message sent to server
requester.js:16169 Submit request event handler already registered

On Tue, May 5, 2015 at 7:39 AM, Abhijit Kane notifications@github.com
wrote:

> You can enable the DevTools for Postman -
> http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/,
> and right click > Inspect Element > Network. Are you seeing the response
> body?
> 
> If yes, check for error messages in the Console tab (also in DevTools)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/a85/POSTMan-Chrome-Extension/issues/1041#issuecomment-99067389
> .

## 

[image: CallidusCloud Connections] 
http://calliduscloudconnections.com/register/?RefID=cc-signature-banner&utm_source=callidus&utm_medium=signature&utm_campaign=c32015
*CallidusCloud HQ *has moved. 
Our new address is: 
4140 Dublin Blvd, Suite 400, Dublin, CA 94568

**Comment by abhijitkane** [comment] 2015-05-05 13:19
If the response is not visible in the Network tab, Postman isn't receiving the response. Can you check the curl preview of the request (Preview button > Curl) and see if that's returning the response?

**Comment by ghost** [comment] 2015-05-05 14:52
Here's the curl request, no response . How does Postman track what
responses are intended for it, anything to do with the PostmanSessionId?

curl -X POST -H "AddaSessionId: 7r5rh5p0onf9thkfr779i3n4un" -H
"Content-Type: application/xml" -H "Cache-Control: no-cache" -H
"Postman-Token: 742d4ec3-49c0-462b-fcc4-47855eb0e34d" -d
'<wfprocessscheduler-list>
<wfprocessscheduler>
  <transmissionseq>10000000000009917</transmissionseq>
  <transactionseq>1</transactionseq>
  <agentproducerid>12345</agentproducerid>
  <status>NEW</status>
  <source>ESB</source>
  <transactiontype>LC</transactiontype>
  <registrationdate>04/05/2015 13:03:03</registrationdate>
  <wfappointment-list>
    <wfappointment>
      <transmissionseq>10000000000009917</transmissionseq>
      <transactionseq>1</transactionseq>
      <state>TX</state>
      <isTermination>0</isTermination>
      <status>NEW</status>
    </wfappointment>
    <wfappointment>
      <transmissionseq>10000000000009917</transmissionseq>
      <transactionseq>1</transactionseq>
      <state>NY</state>
      <isTermination>0</isTermination>
      <status>NEW</status>
    </wfappointment>
  </wfappointment-list>
</wfprocessscheduler>
<wfprocessscheduler>
  <transmissionseq>10000000000009917</transmissionseq>
  <transactionseq>2</transactionseq>
  <agentproducerid>123456</agentproducerid>
  <status>NEW</status>
  <source>ESB</source>
  <transactiontype>LC</transactiontype>
  <registrationdate>04/05/2015 14:03:03</registrationdate>
</wfprocessscheduler>
</wfprocessscheduler-list>'
http://localhost:8080/PM/REST/entity/wfprocessscheduler

On Tue, May 5, 2015 at 8:19 AM, Abhijit Kane notifications@github.com
wrote:

> If the response is not visible in the Network tab, Postman isn't receiving
> the response. Can you check the curl preview of the request (Preview button
> 
> > Curl) and see if that's returning the response?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/a85/POSTMan-Chrome-Extension/issues/1041#issuecomment-99075822
> .

## 

[image: CallidusCloud Connections] 
http://calliduscloudconnections.com/register/?RefID=cc-signature-banner&utm_source=callidus&utm_medium=signature&utm_campaign=c32015
*CallidusCloud HQ *has moved. 
Our new address is: 
4140 Dublin Blvd, Suite 400, Dublin, CA 94568

**Comment by ghost** [comment] 2015-05-05 14:53
Sorry, Postman-Token not SessionId

On Tue, May 5, 2015 at 9:52 AM, Brent Koch bkoch@calliduscloud.com wrote:

> Here's the curl request, no response . How does Postman track what
> responses are intended for it, anything to do with the PostmanSessionId?
> 
> curl -X POST -H "AddaSessionId: 7r5rh5p0onf9thkfr779i3n4un" -H "Content-Type: application/xml" -H "Cache-Control: no-cache" -H "Postman-Token: 742d4ec3-49c0-462b-fcc4-47855eb0e34d" -d '<wfprocessscheduler-list>
> <wfprocessscheduler>
>   <transmissionseq>10000000000009917</transmissionseq>
>   <transactionseq>1</transactionseq>
>   <agentproducerid>12345</agentproducerid>
>   <status>NEW</status>
>   <source>ESB</source>
>   <transactiontype>LC</transactiontype>
>   <registrationdate>04/05/2015 13:03:03</registrationdate>
>   <wfappointment-list>
>     <wfappointment>
>       <transmissionseq>10000000000009917</transmissionseq>
>       <transactionseq>1</transactionseq>
>       <state>TX</state>
>       <isTermination>0</isTermination>
>       <status>NEW</status>
>     </wfappointment>
>     <wfappointment>
>       <transmissionseq>10000000000009917</transmissionseq>
>       <transactionseq>1</transactionseq>
>       <state>NY</state>
>       <isTermination>0</isTermination>
>       <status>NEW</status>
>     </wfappointment>
>   </wfappointment-list>
> </wfprocessscheduler>
> <wfprocessscheduler>
>   <transmissionseq>10000000000009917</transmissionseq>
>   <transactionseq>2</transactionseq>
>   <agentproducerid>123456</agentproducerid>
>   <status>NEW</status>
>   <source>ESB</source>
>   <transactiontype>LC</transactiontype>
>   <registrationdate>04/05/2015 14:03:03</registrationdate>
> </wfprocessscheduler>
> </wfprocessscheduler-list>' http://localhost:8080/PM/REST/entity/wfprocessscheduler
> 
> On Tue, May 5, 2015 at 8:19 AM, Abhijit Kane notifications@github.com
> wrote:
> 
> > If the response is not visible in the Network tab, Postman isn't
> > receiving the response. Can you check the curl preview of the request
> > (Preview button > Curl) and see if that's returning the response?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/a85/POSTMan-Chrome-Extension/issues/1041#issuecomment-99075822
> > .

## 

[image: CallidusCloud Connections] 
http://calliduscloudconnections.com/register/?RefID=cc-signature-banner&utm_source=callidus&utm_medium=signature&utm_campaign=c32015
*CallidusCloud HQ *has moved. 
Our new address is: 
4140 Dublin Blvd, Suite 400, Dublin, CA 94568

**Comment by abhijitkane** [comment] 2015-05-05 17:08
If the curl request is not returning a response, then the problem is with the request itself. Can you try exporting the request from Soap UI in some format, preferably curl?

The responses for any requests that are made to Postman are sent back to Postman. It works like any other browser in this regard.

**Comment by ghost** [comment] 2015-05-05 18:03
The curl request was posted a few emails back. It does require a
AddaSessionId inserted into the header of all requests after logging in.
Exporting it in JSON format here. The first is where it logs in, the second
is where it inserts a Customer which works fine. It's the final call that
Postman isn't recognizing the response. I can capture the response from
Soap UI as initially posted.

I makes me wonder if the format of the response is somehow being parsed
incorrectly, probably from the format I am returning in the response.

I do appreciate your assistance with this, this has been frustrating.

On Tue, May 5, 2015 at 12:08 PM, Abhijit Kane notifications@github.com
wrote:

> If the curl request is not returning a response, then the problem is with
> the request itself. Can you try exporting the request from Soap UI in some
> format, preferably curl?
> 
> The responses for any requests that are made to Postman are sent back to
> Postman. It works like any other browser in this regard.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/a85/POSTMan-Chrome-Extension/issues/1041#issuecomment-99143331
> .

## 

[image: CallidusCloud Connections] 
http://calliduscloudconnections.com/register/?RefID=cc-signature-banner&utm_source=callidus&utm_medium=signature&utm_campaign=c32015
*CallidusCloud HQ *has moved. 
Our new address is: 
4140 Dublin Blvd, Suite 400, Dublin, CA 94568

**Comment by apmoronez** [comment] 2015-10-23 13:57
I am having the same issue with Postman.  When I post to a particular resource on a server with Postman, and that server returns a 400 code, Postman displays the generic "Could not get any response" page.  However, if I curl the same resource, I get the response (sent along with the 400:

<pre>
> curl -k -v -H'Authorization: Bearer &lt;redacted>' 'https://api.athenahealth.com/preview1/195900/appointmenttypes' -XPOST -dduration=30 -dname=Test -dpatient=false -dshortname=GMZ1
* About to connect() to api.athenahealth.com port 443 (#0)
*   Trying 107.21.253.153... connected
* Connected to api.athenahealth.com (107.21.253.153) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* warning: ignoring value of ssl.verifyhost
* skipping SSL peer certificate verification
* SSL connection using TLS_DHE_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
*       subject: CN=api.athenahealth.com,O="Athenahealth, Inc.",L=Watertown,ST=Massachusetts,C=US
*       start date: Apr 24 00:00:00 2015 GMT
*       expire date: Jun 09 12:00:00 2017 GMT
*       common name: api.athenahealth.com
*       issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> POST /preview1/195900/appointmenttypes HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: api.athenahealth.com
> Accept: */*
> Authorization: Bearer &lt;redacted>
> Content-Length: 50
> Content-Type: application/x-www-form-urlencoded
> 
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Date: Fri, 23 Oct 2015 13:54:02 GMT
< nnCoection: close
< Pragma: No-cache
< Server: Apache
< Vary: Accept-Encoding
< X-Mashery-Message-ID: c86aaa6c-8ef2-46e8-8dcb-627e21a6ee0a
< X-Mashery-Responder: prod-j-worker-us-east-1e-120.mashery.com
< transfer-encoding: chunked
< Connection: keep-alive
< 
* Connection #0 to host api.athenahealth.com left intact
* Closing connection #0
{"error":"An appointment type with that name or shortname already exists"}
</pre>

Curl is detecting the 400, but still returning the response (the JSON with the error detail).  Postman just displays the "Could not receive a response" page and doesn't attempt to retrieve a response.  How can I get Postman to display a response, even when there is a 5XX/4XX error and it thinks there isn't one?

**Comment by ghost** [comment] 2016-03-30 12:26
I am also now getting this problem, a few weeks ago I was seeing the response message along with the code, but now it just says 400 Bad request. When I watch the request using fiddler  I can see "HTTP/1.1 400  Invalid Transaction Type" where "Invalid Transaction Type" is the message I am expecting to see and was seeing up to a week or so ago in Postman.

Thanks
Richard

**Comment by abhijitkane** [comment] 2017-08-14 22:35
@richcbaker This should be fixed now. Feel free to reopen if you see this again.

**Closed as completed by abhijitkane** 2017-08-14 22:35 UTC
Labels: support
