### ISSUE TITLE
Change shorcut behavior

### ISSUE THREAD

**Issue by will-fsanches** [a85/POSTMan-Chrome-Extension#5646] opened 2018-12-13 20:32 UTC
When I press the shortcut for inserting the question mark (?), AltGr+W, postman closes the tab I'm wornking at. Please change this behaviour so I can use the shortcut.

**Comment by sujayvenaik** [comment] 2018-12-14 11:38
Duplicate of #2096

**Closed as completed by sujayvenaik** 2018-12-14 11:38 UTC
