### ISSUE TITLE
Dynamics 365 CE 9.0 API Testing Error at Postman version 6.7.2

### ISSUE THREAD

**Issue by VenkattaPidikiti** [a85/POSTMan-Chrome-Extension#5874] opened 2019-02-01 13:52 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
error for Dynamics 365 CE 9.0 API while testing from Postman version 6.7.2 and 6.7.3. But we don't have any issues with 6.7.1 and earlier versions.

**To Reproduce**
1. Go to Postman
2. Click on GetNew access token
3. Enter ADFS credentials
![postman6 7 2 version oautherror](https://user-images.githubusercontent.com/11817148/52126816-62e92400-2656-11e9-8ee2-905b8642e8c0.jpg)

**Expected behavior**
Genarate Access token

**Screenshots**
![postman6 7 2 version oautherror](https://user-images.githubusercontent.com/11817148/52126816-62e92400-2656-11e9-8ee2-905b8642e8c0.jpg)

**App information (please complete the following information):**
 - App Type :Postman
 - Postman Version 6.7,2 and 6.7.3
 - OS: Windows 10

**Additional context**

**Comment by numaanashraf** [comment] 2019-02-03 05:53
@VenkattaPidikiti We are tracking this issue at https://github.com/postmanlabs/postman-app-support/issues/5819#issuecomment-457625628. Please follow that issue for updates.

**Comment by numaanashraf** [comment] 2019-02-03 05:53
Duplicate of #5819

**Closed as completed by numaanashraf** 2019-02-03 05:53 UTC
Labels: duplicate

**Comment by VenkattaPidikiti** [comment] 2019-02-03 11:48
Hello,
I understood you have made a duplicate as per 5819 for self-signed certificates. Please note I have disabled SSL Certifications verification from settings at 6.7.1 and 6.7.2 and 6.7.3 as well

Venkatta
