### ISSUE TITLE
Allow collection generation from GraphQL schema

### ISSUE THREAD

**Issue by sankalp0o** [a85/POSTMan-Chrome-Extension#7024] opened 2019-07-30 10:12 UTC
Splitting from #6712 , some users have requested a feature to be able to generate collections from GraphQL. If you also have this need, please add some details below so we're better able to understand your use case.

Filed by Postman

**Comment by nik-lampe** [comment] 2019-10-05 07:46
Actually I'm wondering that nobody else is commenting on this...

I love using Postman, I prefer it to all the other API tools that I have tried. And now that it supports GraphQL I'd like to use it for my GraphQL APIs as well.

But in it's current state I can't use it efficiently. 
Other Tools like Insomnia, Altair or graphiql all support this without setting anything up. You just enter the endpoint of your API and click "refresh schema" and it loads the schema and assists you with autocompletion and hinting if your input is wrong.

I just digged a little through the source code of the Insomnia client and it seems to do this with the graphql/utilities module (https://graphql.org/graphql-js/utilities/). With the introspectionQuery and the buildClientSchema.

I'm aware that it might not be so simple to integrate this into postman, but  maybe this helps to push into the right direction?

https://github.com/getinsomnia/insomnia/blob/57bf6c2df28c34c57f2b5626e1b9fc07d59b6005/packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js#L246

**Comment by umeshp7** [comment] 2020-01-17 12:26
As of 7.15 we have added support for collection generation from GraphQL schema. You can either use a `GraphQL SDL` or the `introspection query result JSON` and import it as a collection. This can also be done using the ‘Generate Collection’ button inside the API tab for GraphQL schemas.

Feel free to get back to us with suggestions and concerns regarding the same.

**Comment by kgonyon** [comment] 2020-01-21 23:21
I have started using the `Generate Collection` with our new graphql api and the only issue I have found is the queries generated don't include fields that are not scalar types. For example we have a schema that includes 
``` 
type Ticket {
  agentReferences: [ReferenceModel]
  articles: [Article]
  createDate: String
  createdBy: ReferenceModel
  deleted: Boolean
  description: String
  files: [ReferenceModel]
  individualReferences: [ReferenceModel]
  lastModifiedBy: ReferenceModel
  lastModifiedDate: String
  leadReferences: [ReferenceModel]
  status: TicketStatus
  ticketAgent: ReferenceModel
  ticketId: ID!
  ticketInbox: ReferenceModel
  title: String
}

type Query {
  getTickets(category: TicketCategory, length: Int): [Ticket]
  ...
}
...
```
but the generated query only includes 
```
query getTickets ($category: TicketCategory, $length: Int) {
    getTickets (category: $category, length: $length) {
        createDate
        deleted
        description
        lastModifiedDate
        status
        ticketId
        title
    }
}
```

Basically only fields that are scalar types. I am not sure if this is the intended behavior or not, but it would be nice it if default to pull in all possible fields.

**Comment by umeshp7** [comment] 2020-01-22 20:04
@kgonyon Awesome to hear that you have started using the feature. 
We are aware of this problem and we are working on getting configurable options while importing a schema. 
In this case, this issue will be solved by the `depth` option. By default, we have kept the depth to which the query be generated to `1` (which is only the scalar types). A depth of `2`, will fetch all of the immediate types along with the scalar, and going further will go in-depth of all those types as well. In the future, you will be able to choose a depth that suits your needs while importing the specification. 
We already support this in our open-source module. To know more, you can go on to https://github.com/postmanlabs/graphql-to-postman and, while we are working on getting these configurations on the UI, you could use this module to generate postman collections and share your thoughts.
Hope this helps! 
Happy to answer any more queries.

**Comment by kgonyon** [comment] 2020-01-24 21:29
Thank you for the response. We have a node package that generates our schema so I was able to integrate this with that package and import into our workspace. This worked great! The only other issue I feel we have is the query variables. The default values are usually not useful, but I am not sure how this could be dealt with. Maybe only updating a collection so the queries change, but the variables stay the same?

**Comment by umeshp7** [comment] 2020-10-01 05:59
@kgonyon We don't have support for updating collection already imported, it is either replaced or a copy is created as of now. Feel free to open a new issue for this specific feature. 

Closing this issue for now.

**Closed as completed by umeshp7** 2020-10-01 05:59 UTC
Labels: feature, importer, protocol/graphql
