### ISSUE TITLE
line-height issues in editor

### ISSUE THREAD

**Issue by arnavsaxena17** [a85/POSTMan-Chrome-Extension#8092] opened 2020-02-21 06:51 UTC
Hi, 

I'm using the native app on Mac OS Sierra 10.12.6.
I am unable to change the line height in the editors and its stuck at the fixed height and is making reading difficult. 
Edit: I'm using Postman Version 7.18.0 (7.18.0)
Screenshot attached.

Could someone help?
![Screen Shot 2020-02-21 at 12 17 05 PM](https://user-images.githubusercontent.com/16238974/75011061-b0744100-54a4-11ea-9f1c-60f0d2f830d6.png)

**Comment by kamalaknn** [comment] 2020-03-18 16:57
Duplicate of #6760

**Closed as completed by kamalaknn** 2020-03-18 16:57 UTC
Labels: bug
