### ISSUE TITLE
Can no longer click on HATEOS links in latest version

### ISSUE THREAD

**Issue by michael-arneson** [a85/POSTMan-Chrome-Extension#7090] opened 2019-08-09 13:30 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by michael-arneson** [comment] 2019-08-09 13:41
In native postman 7.2.2 The option existed to click on a HATEOS link in http response and this would open a new tab based on the HATEOS url. However this option is no longer present in the native app postman 7.3.6. It does make using postman more tedious because if I have to follow the link i have to open a new tab and manually create the new link. 

Highlighting link

![image](https://user-images.githubusercontent.com/53943087/62782936-e27e0280-ba80-11e9-85d6-9015bc9fa6f5.png)


After clicking on link, new tab is opened based on HATEOS link.
![image](https://user-images.githubusercontent.com/53943087/62782890-c4180700-ba80-11e9-826f-f2aec3ec5f9c.png)

In Postman 7.3.6, this option is no longer available. The link is not highlighted and it can't be clicked.
![image](https://user-images.githubusercontent.com/53943087/62783039-26710780-ba81-11e9-9556-a7ec34183607.png)

**Comment by kamalaknn** [comment] 2019-08-09 14:17
Hi @michael-arneson 

Thanks for reporting this issue. This looks like a duplicate of #6832 

I'm closing this issue. Please follow the original thread for updates.

**Closed as completed by kamalaknn** 2019-08-09 14:17 UTC
Labels: bug
