### ISSUE TITLE
Run Requests Directly From Postman Documentation

### ISSUE THREAD

**Issue by staticvoidmaine** [a85/POSTMan-Chrome-Extension#3325] opened 2017-07-31 13:24 UTC
```
Postman for Linux
Version 5.1.2
linux 4.11.9-1-ARCH / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always been there?
 2. Expected behaviour: Instead of being provided with scripts to copy/paste in order to run requests from documentation, be able to run requests directly within documentation
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 4. Screenshots (if applicable): N/A

Hi there,

Currently, a command/code snippet is generated for the viewer of the documentation to copy/paste and run within their chosen environment. It would be more useful if the user was able to fire off a request via ajax in the right sidebar instead of be provided with a command or code snippet.

So, the feature request would be to replace (or provide the user with an option to replace) the command/code snippet sidebar with something along the lines of a "Run request" button that runs the request and then displays the request/response for the user.

Thanks,

Rylan

**Comment by sdnts** [comment] 2017-08-01 09:09
Hi @rylancates! Unfortunately, this isn't on our roadmap as of now. However, you should be able to use the `Run In Postman` button for something similar. When someone clicks on the `Run In Postman` button from the collection documentation, the collection will be imported into their app, and they can fire requests from the app, like you said.

I'm still adding this as a feature request, though. Our [roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers) would be the best place to follow for updates :)

**Comment by staticvoidmaine** [comment] 2017-08-01 13:15
That's okay, example requests are suitable for now. Thank you for considering this request all the same.

Just for the sake of context - this use case is for sharing documentation with organizations who have a heavily locked down environment where installing postman and 'run in postman' is not an option for them, but still allowing them to have a rich experience in the documentation like you get in swagger docs.

**Comment by Raja-Simha** [comment] 2019-07-23 14:46
Duplicate of #3719

**Closed as completed by Raja-Simha** 2019-07-23 14:46 UTC
Labels: feature, product/documentation
