### ISSUE TITLE
Cant import collection

### ISSUE THREAD

**Issue by dmytrokovalevskyi** [a85/POSTMan-Chrome-Extension#12597] opened 2024-01-24 15:00 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Impossible to import collection

### Steps To Reproduce

1. Import collection in any way (drag n drop etc.)

### Operating System

Windows

### Postman Version

10.22.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by dmytrokovalevskyi** [comment] 2024-01-24 15:02
trying to import json file 2,8 MB

**Comment by romacvccorp** [comment] 2024-01-24 16:30
Same issue here... Trying to import a 3,0MB json file collection

**Comment by jamespotz** [comment] 2024-01-24 16:48
Same here... 2.2MB json collection

**Comment by kascote** [comment] 2024-01-24 17:16
I found this on the logs, may be related ?
```
[26345][1706115782577][requester][error]["ReleaseListStore~getReleases: apiId or apiVersionId is missing"]
[26345][1706115787394][requester][error]["ImportContainerV2~addEventsForSelectedFiles: Could not send analytic events."]
[26345][1706115787851][requester][error]["ReleaseListStore~getReleases: apiId or apiVersionId is missing"]
[26345][1706115788393][requester][error]["CollectionInterfaceV2~createCollection - Error: ",{"error":{"message":"Request body size limit exceeded."},"status":413,"headers":{}}]
```

is uploading the collections and the endpoint has a payload limit ?

**Comment by VShingala** [comment] 2024-01-24 19:15
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/12595.

**Closed as completed by VShingala** 2024-01-24 19:15 UTC
