### ISSUE TITLE
Postman hangs and become unresponsive while showing sign in option

### ISSUE THREAD

**Issue by maknahar** [a85/POSTMan-Chrome-Extension#7306] opened 2019-09-11 18:17 UTC
**Describe the bug**
Postman shows dialog box saying you have been logged out and giving the option to log in or sign out. However, both buttons are non-clickable. If I leave postman open for some time, it starts taking all the CPU. Postman does not become responsive even if I leave it for 10 minutes.

**To Reproduce**
Just open the app in macOS Mojave.

**Expected behavior**
The app opens and does not consume all the CPU for no reason.

**Screenshots**
<img width="1438" alt="Screenshot 2019-09-11 at 11 43 17 PM" src="https://user-images.githubusercontent.com/9051383/64723356-03a59900-d4ee-11e9-99c0-95b1aa2075ec.png">

<img width="799" alt="Screenshot 2019-09-11 at 11 44 12 PM" src="https://user-images.githubusercontent.com/9051383/64723421-1fa93a80-d4ee-11e9-9c9e-3c56eff95a8f.png">
 

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : Version 7.6.0 (7.6.0)
 - OS: macOS Mojave 10.14.6 (18G95)

**Additional context**
There was no issue until yesterday. Did not update the postman either. A minor update could have been downloaded automatically. Tried uninstalling and installing the app but no help.

**Comment by preethammavin** [comment] 2019-09-16 08:48
@maknahar can you write to us at help@getpostman.com so that we can take a closer look at it?

**Comment by maknahar** [comment] 2019-09-16 12:01
Sure.

**Comment by kamalaknn** [comment] 2019-10-16 08:36
Hey @maknahar 

I'm closing this issue since we are not able to see similar issues and we do not have enough information to reproduce this issue. Please do get back to us if you are seeing this issue again.

**Closed as completed by kamalaknn** 2019-10-16 08:36 UTC
Labels: bug, performance, product/login

**Comment by mattroberts297** [comment] 2019-10-24 15:55
![Screenshot 2019-10-24 at 16 53 52](https://user-images.githubusercontent.com/705501/67503076-eb916f80-f67e-11e9-9f0c-44229a3f9834.png)

I see a similar problem. 

OS: macOS Mojave 10.14.5
Postman Version: 7.8.0
App Type: Native

Happy to discuss over email.

**Comment by kamalaknn** [comment] 2019-10-25 03:33
@mattroberts297 Can you share the steps you took before the app came to this state, and logs from `View -> Developer -> Show logs in Finder` to help@getpostman.com?

Please include the GitHub issue number - 7306 in the email.

Thanks

**Comment by maknahar** [comment] 2019-12-23 18:27
Old issue but for anybody else facing this issue, Delete the local postman data. It should be available at `~/Library/ApplicationSupport/Postman/` in Mac. However, this will remove all your local postman data and you will need to sign in again to sync the data back. Do not use this option if you don't have your local data synced.
