### ISSUE TITLE
Allow Each Collection's Documentation to Have Own Branding

### ISSUE THREAD

**Issue by staticvoidmaine** [a85/POSTMan-Chrome-Extension#3324] opened 2017-07-31 13:11 UTC
## App Details:
```
Postman for Linux
Version 5.1.2
linux 4.11.9-1-ARCH / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Not a bug but rather a feature request
 2. Expected behaviour: Each documented collection can accept branding
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 4. Screenshots (if applicable): N/A

Hi there,

In working with the documentation and seeing the initial capability for documentation to accept branding, we're hoping for the following progression:
* Documentation inherits branding from postman organization => documentation inherits branding from collection so as to contain its own branding for a customer-by-customer personalized look.

Thanks,

Rylan

**Comment by sdnts** [comment] 2017-08-01 09:03
Hi @rylancates, when you say `branding`, I'm guessing you mean changing the documentation colors and the logo (on the top left).

Changing the logo is possible on a team level, meaning the logo will change for all docs published from a team. As of now, collection specific styling isn't possible, but I'll add this as a feature request.

You can follow our [roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers) for news :)

**Comment by staticvoidmaine** [comment] 2017-08-01 13:10
Yep, you nailed it. Thanks!

**Comment by Raja-Simha** [comment] 2019-07-23 14:48
Duplicate of #3632

**Closed as completed by Raja-Simha** 2019-07-23 14:48 UTC
Labels: feature, product/documentation
