### ISSUE TITLE
Changing content type of post body overwrites "Content-type" header

### ISSUE THREAD

**Issue by Umkus** [a85/POSTMan-Chrome-Extension#4335] opened 2018-03-14 08:53 UTC
## App Details:
```
Postman for Mac
Version 6.0.9
OS X 16.7.0 / x64
```

## Issue Report:
 1. Changing type of the Raw post body in the dropdown overwrites `Content-Type` header
 2. Expected behaviour: Dropdown for the `Raw` body type is used for syntax highlighting 
 3. I have to choose between syntax highlighting and correct headers 
 4. Demo: https://gfycat.com/PerfumedCorruptGosling

**Comment by sivcan** [comment] 2018-03-28 08:52
Hi @Umkus - Thanks for reporting this. We'll look into it and get back to you.

**Comment by hpawe01** [comment] 2018-05-09 08:52
Hello, I have the same problem. I work with [JSON API](http://jsonapi.org/format/) and need the `Content-Type` header to be `application/vnd.api+json`. As this is a type of JSON I want the normal JSON syntax highlighting in the "Body"-Tab. But as @Umkus describes, I cannot have both.

This is very annoying and at first I was wondering, why my request wouldn't go through until I found this (imo buggy) behavior.

Expected behavior: Do not change already existing headers.

**Comment by prashantagarwal** [comment] 2018-06-29 09:51
Duplicate of #2366

**Closed as completed by prashantagarwal** 2018-06-29 09:51 UTC
Labels: bug
