### ISSUE TITLE
[Bug] Postman does not save Postman Variables if the value is 0

### ISSUE THREAD

**Issue by PFarrell89** [a85/POSTMan-Chrome-Extension#2598] opened 2016-12-28 15:51 UTC
1. **Postman Version:** Version 4.9.3
 2. **App (Chrome app or Mac app):** Windows App
 3. **OS details:** Windows 10 64 Bit
 5. **Did you encounter this recently, or has this bug always been there:** This was definitely working in the past as our regression tests are now throwing errors in Postman.
 6. **Expected behaviour:** Postman should save Postman Variables regardless of the value returned.

1. Perform a request that returns a field name with a value of 0.
```
{
    fieldName: 0
}
```
2. Write a test in Postman to save this value as an Environment Variable

```
var response = JSON.parse(responseBody);
postman.setEnvironmentVariable("fieldName", response.fieldName);
```

3. Once the request is sent, notice that the variable is not created. Using console.log(response.fieldName) will return the value 0.

I don't suppose this is related to issue #2596
<!--

**Comment by St3ffn** [comment] 2017-01-03 13:44
+1 
same problem on Linux Client

**Comment by vegetableman** [comment] 2017-01-04 08:08
@St3ffn @PFarrell89 Thanks for reporting this issue 👍 . The issue has been identified. Will keep you guys posted.

**Comment by Dmytro-Komaryst** [comment] 2017-01-04 16:10
+1
same problem if value = "" or []
Any empty value

**Comment by PFarrell89** [comment] 2017-01-10 00:01
Also confirmed issue on v4.9.3 on the Chrome App.

**Comment by deardooley** [comment] 2017-01-13 11:04
Confirmed for `null` values as well.

**Comment by vegetableman** [comment] 2017-01-17 12:02
@PFarrell89 The `0` bug has been fixed internally and will be part of the next release. As for null and [], support for them is being worked on and will be part of a future release.

**Comment by St3ffn** [comment] 2017-01-17 14:36
@vegetableman ty

**Comment by PFarrell89** [comment] 2017-02-15 09:10
@vegetableman Do you know when the next release due to be released to the public?

**Comment by SamvelRaja** [comment] 2017-02-15 10:17
@PFarrell89 at present you can switch to our Canary app which has the fix.
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64

**Comment by vegetableman** [comment] 2017-02-16 11:04
@PFarrell89 The current release `4.10` supports `0` and empty strings.
@Dmytro-Komaryst,  Would be great if you could create an issue for `[]` and `null` to allow better tracking ^_^.

**Closed as completed by vegetableman** 2017-02-16 11:04 UTC
Labels: bug

**Comment by Paychokxxx** [comment] 2018-03-13 22:02
Postman Version: Version 6.0.9
App (Chrome app or Mac app): Windows App
OS details: Windows 10 64 Bit

in pre-script, if I try to set 0 to variable

let steps_to_add = 0;
pm.environment.set("steps_to_add", steps_to_add);

in quick look 0 will be displayed but really 
environment variable will have empty space

**Comment by Dmytro-Komaryst** [comment] 2018-03-14 09:05
Hello, I can't reproduce the problem with 0 :

Postman Version: Version 6.0.9
App (Chrome app or Mac app): Windows App
OS details: Windows 10 64 Bit

 Pre-request Script:
let steps_to_add = 0;
pm.environment.set("steps_to_add", steps_to_add);

Tests:
console.log(pm.environment.get("steps_to_add")) // Postman console: 0
console.log(pm.environment.get("steps_to_add") === 0); //Postman console: true
