### ISSUE TITLE
Reusable requests

### ISSUE THREAD

**Issue by dhoyt** [a85/POSTMan-Chrome-Extension#1072] opened 2015-05-20 13:52 UTC
Hello ...

I have well over 100 POSTMAN regression test collections that all start with the following endpoints

Create Session
Create User

In these endpoints I am getting/setting various environment variables that will be used later on in the subsequent endpoints in the collection that is being run.

The problem that I ran into was the format of a variable that is set in "Create Session", that is used in "Create User", has been changed. Now I need to go thru all 100+ POSTMAN collections and make the appropriate changes.

Has anyone ever requested the need or want of an "include/insert" notion implemented ? It would be really great to create those 2 endpoints in a collection and then be able to "include/insert" them into other POSTMAN collections so that I would only need to make the change in just those 2 files and the changes will then be realized in all the other collections.

Thanks for listening !

**Comment by dhoyt** [comment] 2015-05-26 17:36
Yes ? No ? Maybe ?

**Comment by a85** [comment] 2015-05-26 17:36
@dhoyt Yes. That's coming soon as part of a revamp of the collection structure and execution flow that we are planning.

**Comment by dhoyt** [comment] 2015-05-26 17:41
Thanks for the response and great news !!! Have a ballpark time (no pressure ;-) of when we might see this ?

**Comment by dhoyt** [comment] 2015-05-28 17:31
Just saw the new release this morning and updated right away. Love the new updates to the GUI. Is there a "What's New" that I can read to see what is in this release ? I have to ask ... Is what I was asking for in this release ?

Thanks D Hoyt

**Comment by a85** [comment] 2015-05-28 17:33
@dhoyt Yep. Check it out here: http://blog.getpostman.com/2015/05/28/postman-3-0-a-whole-new-experience/

**Comment by skyboyer** [comment] 2017-12-07 10:46
probably should be merged with #1535

**Comment by a85** [comment] 2019-05-05 22:11
Closing as duplicate of #1535. See latest comment there!

**Closed as completed by a85** 2019-05-05 22:11 UTC
Labels: feature, external-scripts
