### ISSUE TITLE
OAuth2 Authentication: option for automatic refreshing of the token after expiration

### ISSUE THREAD

**Issue by pavlee** [a85/POSTMan-Chrome-Extension#9150] opened 2020-10-10 19:25 UTC
I'm using Postman Canary version 7.32.0-canary04.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my token expires and I have to fetch a new one manually. It takes quite a few clicks to get there.

**Current flow with saved Auth configuration**

1. Send the request and discover that the token is expired after receiving response with 401 status
2. Click on "Authorization" tab
3. Click "Get New Access Token"
4. The dialog pops up with a button "Proceed"
5. After closing the dialog clicks "Use Token"
6. Finally clicks "Update" button and attempts sending the request again

**Describe the solution you'd like**
It would be nice if there existed a feature, some kind of a checkbox in Auth configuration, so that when the checkbox is checked, Postman will always check before sending a request if a currently used token is expired. If it is expired it will automatically authenticate and fetch a new token before actually sending the request.

**Comment by coditva** [comment] 2020-10-12 07:09
Hey! Thanks for writing in. We've noted your request and we're tracking it as a feature request. Will post on this thread when we have updates. Stay tuned.

Related: https://github.com/postmanlabs/postman-app-support/issues/2452

**Comment by giridharvc7** [comment] 2021-04-20 08:17
Duplicate of #2452 
Closing this issue to track it in a single place

**Closed as completed by giridharvc7** 2021-04-20 08:17 UTC
Labels: feature, OAuth2, product/runtime
