### ISSUE TITLE
empty (RQL) parameters gets truncated on request

### ISSUE THREAD

**Issue by Hibbem** [a85/POSTMan-Chrome-Extension#3900] opened 2017-12-04 15:57 UTC
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **always in the new native app**
 2. Expected behaviour: **send the request that I entered**
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): **Nothing special to see, only sync logs**

To reproduce:
Make a GET request with empty (rql) parameters. For example: `https://data.acme.com/v1/movies/?id=123&select(data.movies.ratings)`

The `?id` part is submitted correctly, but the `select(data.movies.ratings)` is truncated.

This was working fine on the Chrome app, so I am using the chrome app again for now.

**Comment by prashantagarwal** [comment] 2017-12-05 14:10
@Reyske Can you provide a screenshot of Postman console when you make this request.

**Comment by Hibbem** [comment] 2017-12-05 14:33
![image](https://user-images.githubusercontent.com/6367525/33612360-8d3fe536-d9d1-11e7-8e01-d9d66d30d832.png)

Here you go

**Comment by wwaaijer** [comment] 2017-12-05 14:51
![image](https://user-images.githubusercontent.com/6366926/33613032-c41ec5ac-d9d3-11e7-811b-a3932606aba1.png)

I have reproduced the problem. While the Chrome app did support this. Haven't upgraded for this reason.

**Comment by Hibbem** [comment] 2017-12-14 13:26
Any updates here? As wwaaijer indicated, I can see the parameters are double url encoded

**Comment by SamvelRaja** [comment] 2018-06-29 10:02
As Postman is a very generic tool and for URL encoding we are following the [RFC 3986
](https://www.ietf.org/rfc/rfc3986.txt) and encoding algorithm specified in [what-wg format](https://url.spec.whatwg.org/#parsers) based on that we created a library [postman-url-encoder](https://github.com/postmanlabs/postman-url-encoder), which is been used in our request sending engine - [Postman-runtime](https://github.com/postmanlabs/postman-runtime) 

Closing this as it is the expected behavior.

**Closed as completed by SamvelRaja** 2018-06-29 10:02 UTC
Labels: bug, encode-decode

**Comment by Hibbem** [comment] 2018-07-03 13:00
Ok, thanks for the quick reply.

**Comment by wwaaijer** [comment] 2018-07-10 11:25
I get what is going on under the hood. Bud now the kind of requests one can send with Postman are limited. And since you mention yourself Postman is a very generic tool. Not covering these use cases makes it less of a generic tool.

Before it was possible to send the `(` and `)` character without it automatically being encoded in the background. Now there is no way to send these characters anymore with Postman. It would have been nice to at least have the option the disable the automatic encoding. A checkbox in the `request-urlparams-editor` for example.

Too bad we had to switch to another tool for these kind of requests.
