### ISSUE TITLE
WebSocket with TLS client certificate

### ISSUE THREAD

**Issue by iliyan85** [a85/POSTMan-Chrome-Extension#12628] opened 2024-02-07 11:21 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

At the moment HTTPS API calls in Postman work fine with TLS Client certificate, but WSS collections for the same domain with the same TLS settings cannot establish the connection.

### Describe the solution you'd like

Establishing wss connections with TLS Client Certificate.

**Comment by appurva21** [comment] 2024-02-07 11:43
Duplicate of #11865

**Closed as completed by appurva21** 2024-02-07 11:43 UTC
Labels: feature, protocol/websocket, product/api-client
