### ISSUE TITLE
Incorrectly says SSL Error: Certificate has expired

### ISSUE THREAD

**Issue by dgobaud** [a85/POSTMan-Chrome-Extension#10341] opened 2021-10-04 19:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

incorrectly gives SSL expired error for https://api.facilitafx.com/ but it is not expired

Expires: Thursday, December 9, 2021 at 2:03:12 AM Eastern Standard Time

### Steps To Reproduce

make request to https://api.facilitafx.com

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/240811/135914565-3fa2ff2e-98fe-4284-80a1-3c182373df6d.png)

### Environment Information

```markdown
- Operating System: OSX
- Platform Type: Native App
- Postman Version: Version 8.11.1 (8.11.1)
```

**Comment by xk0der** [comment] 2021-10-04 23:18
@dgobaud I checked and found that the site is using LetsEncrypt generated cert. LetsEncrypt's root cert had expired on 30th Sep causing the issue.

Upgrading to [8.12.4](https://www.postman.com/downloads/) should fix the issue.
Refer: https://github.com/postmanlabs/postman-app-support/issues/10338#issuecomment-932330968

Closing this as duplicate of #10338

**Closed as completed by xk0der** 2021-10-04 23:18 UTC
Labels: duplicate
