### ISSUE TITLE
Open in New Tab does not always work

### ISSUE THREAD

**Issue by bdiaz-gapsi** [a85/POSTMan-Chrome-Extension#9549] opened 2021-02-04 18:59 UTC
When you right-click on a request in order to open it in a new tab, nothing happens.

**Comment by DannyDainton** [comment] 2021-02-04 19:05
Closing as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9493

**Closed as completed** 2021-02-04 19:05 UTC
Labels: duplicate
