### ISSUE TITLE
Initial request became edited after edit of its duplicate in Postman 6.0.7 for Win

### ISSUE THREAD

**Issue by serg1409** [a85/POSTMan-Chrome-Extension#4273] opened 2018-03-03 15:07 UTC
## App Details: Postman for Win x64
Version 6.0.7 

## Issue Report:
1. Initial request (body and tests) became edited after edit of its duplicate
2. It didn't happen in Postman 5. I had to go back to Postman 5.5.3

Steps to reproduce the problem
1. Make a duplicate of a saved collection request in Postman 6.0.7 for Win
2. Start edit the new request
3. Initial request (body and tests) became edited along with the new one

**Comment by IrynaRus** [comment] 2018-03-06 23:19
Please prioritise this bug as it's creating a mess in my tests. 
All tests from the same collection usually have the same structure and just some parts are different, so the easiest way to create them is to duplicate and edit, but I ended up editing original test instead of a copy and ruined the work I've done before.
Thank you.

**Comment by sdnts** [comment] 2018-03-07 06:35
@serg1409 @IrynaRus I've verified that this is now fixed with v6.0.9.

Just to confirm, you guys are duplicating the request from the sidebar, correct? Do note that duplicating an open tab will open the same request in two tabs, so changing any one of them WILL change the original.

I'm closing this for now, but please let me know if you still see this and I'll reopen.

**Closed as completed by sdnts** 2018-03-07 06:35 UTC

**Comment by IrynaRus** [comment] 2018-03-07 22:59
@madebysid Updated to the latest version and the issue is fixed. Thank you!
And Yes, I was duplicating from the sidebar.

**Comment by sdnts** [comment] 2018-03-09 06:50
@IrynaRus Awesome, that's great to hear :)
