### ISSUE TITLE
support more protocols such as websocket or mqtt?

### ISSUE THREAD

**Issue by Txiaozhe** [a85/POSTMan-Chrome-Extension#7366] opened 2019-09-20 09:11 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Is there any plan to support more protocols in postman such as websocket or mqtt or anymore?

**Comment by codenirvana** [comment] 2019-09-25 10:43
Duplicate of #4009

**Closed as completed by codenirvana** 2019-09-25 10:43 UTC
Labels: duplicate, product/runtime, http2 + sse

**Comment by shamasis** [comment] 2021-05-20 14:15
Postman v8.5 onwards have added support to connect to WebSocket APIs and send/receive messages https://github.com/postmanlabs/postman-app-support/issues/4009#issuecomment-845136513

**Comment by philCryoport** [comment] 2022-05-17 16:38
The request for MQTT support is apparently covered by https://github.com/postmanlabs/postman-app-support/issues/9490

Please vote for it!

**Comment by Txiaozhe** [comment] 2022-08-31 12:42
Thanks:)
