### ISSUE TITLE
How to avoid - Too many error (xx% scanned?

### ISSUE THREAD

**Issue by BhanuDash007** [a85/POSTMan-Chrome-Extension#5198] opened 2018-09-18 12:28 UTC
Hi, I am getting Too many error - xx% scanned error . I checked the syntax in other JS editor seem to be all syntax correct even post man script is running fine . How to remove that error ?

**Comment by numaanashraf** [comment] 2018-09-18 12:31
Duplicate of #3385. Please use the original thread to continue this discussion.

**Closed as completed by numaanashraf** 2018-09-18 12:31 UTC
