### ISSUE TITLE
Cannot send multiple set-cookie headers 

### ISSUE THREAD

**Issue by klubi** [a85/POSTMan-Chrome-Extension#3168] opened 2017-06-15 13:35 UTC
## App Info
```
Postman for Mac
Version 5.0.0
OS X 10.12.5 (16F73)
```

## Issue Report
I noticed that when I create a request and add two headers with same key, then only second one is sent, fist one is omitted.
While for most headers this is a valid behavior for `Set-Cookie` it should send all entries.

**Comment by kamalaknn** [comment] 2017-06-16 10:13
Hey @klubi,

Thanks for reporting this.

It looks like the request headers for duplicates are actually being sent over the network. Except that the Postman Console shows only the last header(which is a bug - we will get this fixed). Could you verify this?

Also you can try `cookie` header with `foo=bar; bar=baz;` to set multiple cookies?

**Comment by quicksketch** [comment] 2017-07-18 18:12
> I noticed that when I create a request and add two headers with same key, then only second one is sent, fist one is omitted.

This may be a duplicate of #3172.

And confirmed this is a big problem for the `Set-Cookie` header, for which some applications set many cookies, each with a separate header.

**Comment by sdnts** [comment] 2017-07-19 13:53
Hi @quicksketch I verified that the headers are actually being sent to the server, but the Console (or the Runner for that matter) only list it once. I'm closing this as duplicate of #3172 as you said, since these appear to be the same issue. Please let me know if you feel otherwise.

**Closed as completed by sdnts** 2017-07-19 13:53 UTC
