### ISSUE TITLE
could not delete cookie with the browser way

### ISSUE THREAD

**Issue by shuperry** [a85/POSTMan-Chrome-Extension#2187] opened 2016-07-21 02:07 UTC
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Mac Postman App
3. OS details: os x El Captian

I write some api with node, when I visit with my chrome browser at same url, my backend app excuted `ctx.cookies.set('jwt', null)` to delete cookie, this works in chrome and the cookie is removed, but in Postman app, cookie still there.

**Comment by abhijitkane** [comment] 2016-07-21 04:47
@shuperry Does manually deleting the cookie from the 'Manage Cookies' section work?

**Comment by shuperry** [comment] 2016-07-21 06:02
@abhijitkane Yeah, delete domain and cookie from `Manage Cookies` works.

**Comment by odziem** [comment] 2016-08-17 00:46
This is still the case on 4.6.1. My understanding is that Postman doesn't set cookies with an empty string value or with an expiry in the past. This breaks a common pattern used to "unset" a cookie.

**Comment by sdnts** [comment] 2018-03-20 13:05
I believe this ties in with [this](https://github.com/postmanlabs/postman-app-support/issues/3312) issue, and as such will be accomplished together. I'm marking this as a feature request.

**Comment by codenirvana** [comment] 2019-04-10 02:43
~Duplicate of #3312~

Originally posted at https://github.com/koajs/koa/issues/777

**Closed as completed by codenirvana** 2019-04-10 02:43 UTC
Labels: feature, cookies
