### ISSUE TITLE
Team doesn't reflect in Canary

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6597] opened 2019-05-27 09:23 UTC
**Describe the bug**
Wanted to use GraphQL feature hence checking the same in Canary but unable to see the "team" in Canary though it looks all good in the Postman app(associated with the team)

**To Reproduce**
1. Go to Canary
2. Click on Login 
3. After logging in, unable to see the team

**Expected behavior**
User should be associated with the team in Canary

**App information (please complete the following information):**
 - App Type [Canary]
 - Postman Version [7.1.1]

**Comment by preethammavin** [comment] 2019-05-28 06:25
@ash007-postman can you check with the user if the issue persists, also would be good if the user was able to share a screen recording of the same.

**Comment by galvesribeiro** [comment] 2019-05-28 10:14
@preethammavin yes, the error persist. 

Just to clarify the real issue. We're using the enterprise login. After we get redirected to the identity provider, login, and return back, this is the screen we have:

![image](https://user-images.githubusercontent.com/4714040/58470443-1bf8d000-8118-11e9-8cce-c805ad15f486.png)

Obviously my account is on the team. I'm the account owner and I'm using it on the release build.

That doesn't happen on the released app. Only on canary.

**Comment by galvesribeiro** [comment] 2019-05-29 02:15
Please close the issue. The problem is not a bug. Just that Saml integration should be better documented. The support email has fixed the issue. 

Thank you

**Closed as completed** 2019-05-29 03:21 UTC
Labels: bug, product/login
