### ISSUE TITLE
Postman GitHub Integration does not show all repository branches

### ISSUE THREAD

**Issue by dreamiurg** [a85/POSTMan-Chrome-Extension#8284] opened 2020-04-03 17:22 UTC
**Describe the bug**
After adding new GitHub Sync API schema integration and setting up personal access token and a webhook on our GitHub repo I don't see the branch we need to sync API schema with in the integration settings dropdown box.

The repository has ~100 active branches. The branch in question is present on GitHub. In fact we don't even see the `master` branch in the dropdown. 

**To Reproduce**
1. Create a reasonably large repo with 50k commits and 100+ branches. Work on it for several years.
2. Go to Workspace -> Integrations -> GitHub -> Add "Sync API Schema" integration
3. Set up GitHub personal access token and webhook as required per Postman manual
4. In the integration settings click "Add API version", and look for the branch.

**Expected behavior**
All branches available in GitHub repo should be available in the integration

**Screenshots**
https://www.dropbox.com/s/hvi4j1kfiecceoo/Screenshot%202020-04-03%2010.18.59.png?dl=0

**App information (please complete the following information):**
 - App Type: Web
 - Postman Version: 7.21.1

**Comment by cyrielle-hada** [comment] 2020-05-08 12:29
@dreamiurg according to the official documentation of the Github API, [requests that return multiple items will be paginated to 30 items by default](https://developer.github.com/v3/#pagination). This means that whenever there are more than 30 branches in a repository, all the branches will not be listed due to pagination in Github API. 

We are working on implementing a fix for increasing the number of branches when setting up the GitHub integration with Postman for an API version.

**Comment by abhijitkane** [comment] 2020-07-23 07:57
This should be fixed now. @dreamiurg @cyrielle-hada Feel free to reopen if you continue to see this.

**Closed as completed by abhijitkane** 2020-07-23 07:57 UTC
Labels: bug, product/mocks, product/integrations

**Comment by wardboumans** [comment] 2021-04-20 20:29
I'm facing the same issue when adding the github integration via 'Connect to repo' on an API. We have ~400 repos. Im using the website not the desktop client.

**Comment by ObidulKadir** [comment] 2023-08-15 03:47
I am also facing the same issue, did not get any branch while integrating. Its shows "No Branch Found"

**Comment by Purvi-30** [comment] 2023-10-11 09:51
I am also facing the same issue, I understand you are requesting for a video, but does steps to reproduce help?
There are 2 ways to reproduce this 
A) 1. Click on Import
2. Select GitHub option
3. Authorize it
4. Select Organization in the Import from GitHub pop-up (It by default shows your user ID as organization)
5. Repository - Error No repositories found under selected organization.

B) 1. Click on Home
2. Select Integrations
3. Browse all Integrations
4. Click Backup a Collection option Add Integration button
5. Enter PAT
6. Authenticate PAT
7. Enter Nickname
8. Choose Workspace
9. Choose Collection
10. Choose Repository is disabled as no repositories are being shown to select.
