### ISSUE TITLE
OAuth Client Credentials - Do not send client_id in body when selected 'send as Basic auth header'

### ISSUE THREAD

**Issue by cuzic4n** [a85/POSTMan-Chrome-Extension#4488] opened 2018-04-24 23:26 UTC
<img width="532" alt="screen shot 2018-04-26 at 9 37 59 am" src="https://user-images.githubusercontent.com/204951/39319597-68c68ae6-4936-11e8-9cc0-28c612454f35.png">
<img width="828" alt="screen shot 2018-04-26 at 9 37 34 am" src="https://user-images.githubusercontent.com/204951/39319598-68e03978-4936-11e8-8fdf-d3ab42d96072.png">

The Send as Basic Auth Header option keeps client_id in the body and breaks some OAuth implementations that are more strict. The spec says you may have it but if you are choosing the drop down you likely should not include it. Anyways the result is you don't get the access token back for my IDaaS provider. 

In the OAuth 2.0 - Get new access token button - Grant Type Client Credentials - Fill in everything and choose Client Authentication - Send as Basic Auth Header
endpoint => /oauth2/v1/token
clientid: <stuff>
secret: <stuff>
scope: <stuff>
Client Authentication: drop down where you choose Send as Basic Auth header

Postman for Mac
Version 6.0.10
OS X 17.5.0 / x64

I tested this against my Oauth 2.0 server with Postman App for Chrome.. with same config values and it works because that app does not add client_id to the body in this same scenario.

**Comment by harryi3t** [comment] 2018-05-04 11:36
@cuzic4n 
Looks like the server is not spec-compliant

According to the [RFC-6749#4.1.3](https://tools.ietf.org/html/rfc6749#section-4.1.3)

>  <h3> 4.1.3.  Access Token Request </h3>
>      <b>client_id</b>
>
>          REQUIRED, if the client is not authenticating with the
>          authorization server as described in Section 3.2.1.
>  <b>If the client type is confidential or the client was issued client
>    credentials</b> (or assigned other authentication requirements), the
>    client MUST authenticate with the authorization server as described
>    in Section 3.2.1.

Since in this case, the client is not confidential it MUST not authenticate with the authorization server as described in Section 3.2.1, meaning it MUST include a `client_id` field

Also, In [section 3.2.1](https://tools.ietf.org/html/rfc6749#section-3.2.1) it says
 

> A client MAY use the "client_id" request parameter to identify itself
>    when sending requests to the token endpoint.  In the
>    "authorization_code" "grant_type" request to the token endpoint, an
>    unauthenticated client MUST send its "client_id" to prevent itself
>    from inadvertently accepting a code intended for a client with a
>    different "client_id".  This protects the client from substitution of
>    the authentication code.  (It provides no additional security for the
>    protected resource.)

No-where it suggests not to use it. If an implementation is breaking on a field which the spec says can be added for security, then I guess the implementation itself is not very correct.

**Comment by cuzic4n** [comment] 2018-05-04 17:16
Thanks for your reply and bringing up the RFC spec. 
I am not sure we can say that it "Looks like the server is not spec-compliant"... IMO

Postman Chrome App does not behave this way and it was implemented to the same RFC. The way the spec is written it's not clear that you can claim if sending the creds in the HTTP Basic Auth header AND including the client_id in the body constitutes a violation. aka non spec-compliant.

What you refer to in your reply as a MUST is for an authorization_code flow not a client credentials flow which is the focus here. And the Client MAY use it based on section 3.2.1..  but then ask yourself about the POSTman drop down window for that MAY use decision.

2 options for the Client Authentication in the drop down

1. Send as Basic Auth Header
>>> If I choose this option that means the clientid:secret base64 encoded goes in the http Authorization header.. no need to put it in the body.. no purpose for it.. no need for it.. extra data in the payload for nothing in return..

2. Send client credentials in body
>>> If I choose this option that means the clientid and secret go in the body not the header

So why would I choose Send as Basic Auth Header and still put clientid in the body of the payload. No benefit and not required. 

Also the spec states 
`Including the client credentials in the request-body using the two
   parameters is NOT RECOMMENDED and SHOULD be limited to clients unable
   to directly utilize the HTTP Basic authentication scheme (or other
   password-based HTTP authentication schemes)`

So HTTP Basic authentication should be preferred w/o any clientID w/n the body. 

Specs are open for interpretation for sure. But ultimately, clientid should not be sent in the body when there is zero benefit server side for it when using the recommended HTTP Authorization header option.

**Comment by harryi3t** [comment] 2018-05-06 15:20
@cuzic4n Sorry, I thought this was about grant type `authorization code`.
You are right, for grant type `client credentials`, the client_id should not be sent.
I will take another look at the RFC and fix this bug.
Thank you again for reporting this bug.

**Comment by cuzic4n** [comment] 2018-05-06 16:02
Absolutely. Thanks for all your support & efforts. Postman is awesome!

**Comment by harryi3t** [comment] 2018-07-10 11:07
Hi @cuzic4n,
Sorry for the delay. I looked at the RFC again and now can confirm the bug.
We are working on the fix and will update the thread once it's released.
Thank you for using Postman :)

**Comment by harryi3t** [comment] 2018-07-23 05:54
@cuzic4n  We have released a fix for this on our canary apps. 
Can you please verify it?
You can get the canary app from https://www.getpostman.com/canary

**Comment by cuzic4n** [comment] 2018-07-23 14:59
Just tested it and it works

**Comment by Moily** [comment] 2018-07-24 09:33
Confirmed as working, so thanks for delivering this fix.  May I propose some improvements to the auth flow?  

As it stands expired tokens are left hanging around and need to be deleted manually via the 'Manage Tokens' screen. It would be slicker if the auth tokens were managed by Postman for their lifespan, where they are automatically requested where no valid token is currently assigned to the request, and they are removed automatically once expired.

**Comment by harryi3t** [comment] 2018-07-24 18:11
@cuzic4n @Moily Thanks for confirming the fix 👍 

> As it stands expired tokens are left hanging around and need to be deleted manually via the 'Manage Tokens' screen. It would be slicker if the auth tokens were managed by Postman for their lifespan, where they are automatically requested where no valid token is currently assigned to the request, and they are removed automatically once expired.

@Moily This is being tracked here as a feature request https://github.com/postmanlabs/postman-app-support/issues/2452

**Comment by harryi3t** [comment] 2018-08-02 05:34
@cuzic4n @Moily This is fixed in the latest version of Postman 6.2.3

**Closed as completed by harryi3t** 2018-08-02 05:34 UTC
Labels: bug, Auth

**Comment by yanxiaodi** [comment] 2018-08-08 04:34
Unfortunately, if Postman doesn't send the client_id in the body when using Password Credentials , it cannot get the accessToken from Microsoft AD. The error:
`The request body must contain the following parameter: 'client_id'.`
 
Could we provide an option to allow users decide it? Thanks.

**Comment by harryi3t** [comment] 2018-08-08 08:55
@yanxiaodi There is an option already for this. Just choose `Send client credentials in body` from the `Client Authentication` dropdown.

![postman 2018-08-08 14-23-07](https://user-images.githubusercontent.com/5207331/43827084-99e461de-9b16-11e8-97f1-b69a78ea70b8.png)

We have only removed `client_id` from body when the first option `Send as basic auth header` is selected

**Comment by yanxiaodi** [comment] 2018-08-08 10:19
@harryi3t Great! Thank you very much.

**Comment by yanxiaodi** [comment] 2018-08-08 21:16
@harryi3t Can we add the custom params when requesting the token? It seems like that the `resource` param is mandatory for the Microsoft AD OAuth 2.0:

`The request body must contain the following parameter: 'resource'`

Should I open a new issue for it? Thanks.

**Comment by harryi3t** [comment] 2018-08-09 13:08
@yanxiaodi There's already an open feature request for this here https://github.com/postmanlabs/postman-app-support/issues/2523

Also, a user suggested a workaround (if you are not using client-credentials) on that thread https://github.com/postmanlabs/postman-app-support/issues/2523#issuecomment-339526853

**Comment by yanbinzhang-chevron** [comment] 2020-10-29 22:58
@harryi3t , I think this issue is still there. I am using the latest Postman v7.34.0. Just regular authorization code flow:
![image](https://user-images.githubusercontent.com/73672919/97640724-64a07100-1a0f-11eb-974e-f637ac9dd7d2.png)
Here is the error in the console:
![image](https://user-images.githubusercontent.com/73672919/97641099-222b6400-1a10-11eb-8260-08c0838d172d.png)
The client_id is still in the body, which is rejected by the server. 
When looking at the earlier post, this bug was fixed in 2018. Am I getting something wrong, or this bug is actually crept back?

**Comment by dylantack** [comment] 2022-01-26 20:13
Yes, it seems to have regressed. Theres another open issue: #8731
