### ISSUE TITLE
Adding Required field and data type of param's really helps in documenting the Api's

### ISSUE THREAD

**Issue by lokeshreddyp** [a85/POSTMan-Chrome-Extension#8430] opened 2020-05-04 16:18 UTC
**Is your feature request related to a problem? Please describe.**
Yes, It would be great to have `Required` and `field type` for params because it will really help a developer a lot in understanding what's the data type is and is this param mandatory while sending an API request.

Currently, we have `Key, Value, Description` but adding `Required field which is a boolean ` and `DataType of param which may be an integer, boolean, etc` 

**Describe the solution you'd like**
A dropdown menu for Required Field with yes, no as options
The dataType of param with values like integer, boolean, etc

**Describe alternatives you've considered**
For now, I'm adding those two details in the description but it doesn't give much readability visually

**Comment by Raja-Simha** [comment] 2020-05-06 13:23
@lokeshreddyp appreciate your feedback. This is on our short term roadmap and will be working on this soon.

**Comment by Raja-Simha** [comment] 2020-11-19 10:00
Duplicate of #7890

**Closed as completed by Raja-Simha** 2020-11-19 10:00 UTC
Labels: feature, product/documentation
