### ISSUE TITLE
Bug Report : Title of original request gets changed when title of duplicate is changed.

### ISSUE THREAD

**Issue by aakashkhatter1296** [a85/POSTMan-Chrome-Extension#4281] opened 2018-03-05 21:01 UTC
## App Details:

```
Postman for Mac
Version 6.0.8
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Encountered this recently
 2. Expected behaviour: When changing the title in a duplicate request tab, the title of the original request should not change
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![postman_bug_screen_grab](https://user-images.githubusercontent.com/10905662/36999350-d7b5adca-20e5-11e8-93f3-2aecac2e00aa.gif)

Steps to reproduce the problem:

1. Create a request, add its title and description and save it
2. Duplicate the tab
3. Edit the title in the duplicated tab. On editing the title in the duplicated tab, the title in the original tab also gets changed. Happens with multiple duplicate tabs as well.

**Comment by kamalaknn** [comment] 2018-03-06 04:50
Hi @aakashkhatter1296 

I think there is some confusion with the terminology here. The action taken here is `Duplicate Tab` which copies the state of the current tab into a new tab, which is actually the same request in the new tab. 

If you want to duplicate the request, you can use the `Duplicate` option for the request from the sidebar.

I'm closing this issue as this not a bug, but an intended feature. Feel free to continue the discussion.

**Closed as completed by kamalaknn** 2018-03-06 04:50 UTC
