### ISSUE TITLE
Basic Auth only working the first time

### ISSUE THREAD

**Issue by hardcodet** [a85/POSTMan-Chrome-Extension#7471] opened 2019-10-12 23:28 UTC
It appears as if Postman only sent the configured basic auth header on the first request - the API I invoke returns for all subsequent requests a 401. As soon as I restart Postman, I can again send 1 call, and then am back to getting the 401s. Tried that a couple of times with consistent behavior.

If I invoke the same API endpoint programmatically with the same credentials, all calls go through.

![image](https://user-images.githubusercontent.com/873009/66708878-267ad580-ed58-11e9-8854-64a045f131e8.png)

**Describe the bug**

**To Reproduce**
1. Add basic auth as in screenshot
2. Press `Send` to invoke the endpoint - works
3. Press `Send` again - fails
4. Restart Postman
5. Repeat steps 2 - 4

** App information **

Postman v7.9.0, Win 10 x64

**Comment by vikiCoder** [comment] 2020-03-05 06:49
Hi @hardcodet,

I tried to reproduce your issue in the latest version of the Postman app but had no success 😞. Can you please update to the latest version of the [Postman App (v7.19.1)](https://www.postman.com/downloads/) and see if the problem is still there?

You are saying that the request works once and then it only works again when the app is restarted. So my hunch is that it could be a problem because of the persistent connection between the Postman app and your server. You can try adding `Connection: close` header in your request and see if it solves the problem. It is just a wild guess but worth trying 🙂.

Also, can you provide information about the endpoint you are trying to call if it is not private? It might help me reproduce the problem.

**Comment by vvs11** [comment] 2020-03-13 05:59
@hardcodet Could you provide us with the required information so that we can proceed with the issue?

**Comment by codenirvana** [comment] 2020-05-29 20:31
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-05-29 20:31 UTC
Labels: blocked/need-info, product/runtime, blocked/need-repro
