### ISSUE TITLE
Add javascript method to ignore/skip current request

### ISSUE THREAD

**Issue by vnskliarova** [a85/POSTMan-Chrome-Extension#10439] opened 2021-11-12 19:34 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

In my project we are supposed to test API on 3 different environments (more are coming). Right now we have 3 different collections, because for some of the calls we expect a different responses in different envs. I'm currently trying to unify these collections into 1, because it's becoming very cumbersome to maintain. I know you added a great UI feature to disable requests in the runner, but it's not applicable for newman runs on Bamboo.

### Describe the solution you'd like

It would be great to have a command like "postman.skipRequest()" so that it's possible to add a prerequest script like 
```
if(some_condition) {
    postman.skipRequest();
}
```

### Describe alternatives you've considered

I've found the setNextRequest() solution, but it can become a problem when multiple people are maintaining the collection. Because it's supposed to be put in the previous call from the one that I want to skip, If someone shuffles calls around, or adds more calls between the request with the script and the one that we want to skip, it can create more problems.

### Additional context

I'm sorry if there's a similar feature request out there, I could not find anything. And thank you so much for the work you do!

**Comment by ldileonardo** [comment] 2023-01-25 03:07
We need this... so many articles of workarounds (which we have implemented).
Something like this would speed up the testing as we are currently still redirecting the API to the echo request and reporting its skipped using custom logic.
If we can skip the request it would execute much faster.

**Comment by coditva** [comment] 2023-01-30 06:27
Duplicate of #8929. Moving the discussion there.

**Closed as completed by coditva** 2023-01-30 06:27 UTC
Labels: feature, product/runtime, sandbox
