### ISSUE TITLE
Blank white page is displayed after installing Postman Version 4.10.5

### ISSUE THREAD

**Issue by shrutiSS** [a85/POSTMan-Chrome-Extension#2868] opened 2017-03-30 16:06 UTC
1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by pairote** [comment] 2017-03-31 05:32
@shrutiSS 
I am experiencing the same issue. Here is the details of my system environment:
1. Postman Version: 4.10.5
2. App: Mac app
3. OS details: MacOS Sierra 10.12.3
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: I just encounter this today.
6. Expected behaviour: The content in `<div class="requester-tab-contents">` shouldn't be empty.
7. Console logs: See the attached image.
8: Screenshots: See the attached image.

![screen shot 2017-03-31 at 12 30 00 pm](https://cloud.githubusercontent.com/assets/1981588/24537619/db09f0be-160d-11e7-80ea-c4ee5167abe5.png)
![screen shot 2017-03-31 at 12 27 44 pm](https://cloud.githubusercontent.com/assets/1981588/24537620/db531a6e-160d-11e7-9b2b-4b15b67e05fd.png)

**Comment by SamvelRaja** [comment] 2017-03-31 05:59
@shrutiSS @pairote Thanks for bringing this to our notice, we do traced out the issue.
You can still continue using postman by opening a new tab ? Can you guys provide me little more info on that?

**Comment by pairote** [comment] 2017-03-31 06:19
@SamvelRaja 
Negative. Opening a new tab still shows a white blank page.

Is it because of ES6 thing? Because I saw more console log about "Array.from is not a function" when javascript execution is at `_toConsumableArray(arr)` in requester.js#108753.

**Comment by prashantagarwal** [comment] 2017-03-31 08:29
Hey @pairote the app you are using is a Chrome app and the error occurred because of your chrome version(<45). Can you confirm the same? 
We would recommend you to switch to our Native app (http://getpostman.com/apps)

**Comment by pairote** [comment] 2017-03-31 08:58
Hey @prashantagarwal,

Thanks! You are right. My Google Chrome version is < 45. After I downloaded and installed the latest version, the problem is gone.

Anyway, should Postman checks the browser version if it satisfy minimum requirements? or perhaps includes polyfill that works as far down as ES5?

Thank you again for your help.

**Comment by prashantagarwal** [comment] 2017-03-31 09:19
Yeah ideally it should have been transpiled to ES5 using Babel but somehow it was not being done in one the packages we were using. We will get this fixed in upcoming releases.

**Comment by shrutiSS** [comment] 2017-03-31 13:52
@prashantagarwal Thank you folks for notifying this issue and answering in quick time. I still have to download the version of chrome mentioned on my office desk and check if its working or not. 
@pairote Are you working postman api tool  for automation testing?

**Comment by pairote** [comment] 2017-04-02 04:37
@shrutiSS Yes, I am doing automate testing for my api, and Postman is one of my favorite tools to get the job done.

**Comment by prashantagarwal** [comment] 2017-04-08 20:45
This issue has been fixed in 4.10.6. Please update you Postman app.

**Closed as completed by prashantagarwal** 2017-04-08 20:45 UTC
