### ISSUE TITLE
Auto Save before hitting a URL

### ISSUE THREAD

**Issue by hsjoshi28** [a85/POSTMan-Chrome-Extension#10782] opened 2022-03-24 01:48 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Not exactly, but an auto-save after some time or maybe before hitting the send button auto-save

### Describe the solution you'd like

It should prompt for Auto-save before hitting the URL and before exporting too.
It should save it in some default collection, or else in some defined collection.
OR-- The "Send" button can by default save in collections and then hit the backend.

### Describe alternatives you've considered

The "Send" button should be default save in collection and then send.

**Comment by giridharvc7** [comment] 2022-03-25 05:26
Duplicate of #8195

**Closed as completed by giridharvc7** 2022-03-25 05:26 UTC
Labels: feature
