### ISSUE TITLE
Need to have option to skip the requests in the collection based upon certain test

### ISSUE THREAD

**Issue by sarfaraz49** [a85/POSTMan-Chrome-Extension#1403] opened 2015-09-02 10:07 UTC
There is no option to skip the underlying requests in a collection based upon some user defined conditional checks. There should be some option to skip the requests if there are some failure or some condition is not met in the collection.

**Comment by abhijitkane** [comment] 2015-09-02 10:09
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/1172

**Closed as completed by abhijitkane** 2015-09-02 10:09 UTC
