### ISSUE TITLE
Collection runner crashes postman when stop run is pressed during a run

### ISSUE THREAD

**Issue by Connor-Graves** [a85/POSTMan-Chrome-Extension#8917] opened 2020-08-11 21:50 UTC
**Describe the bug**
App crashes upon stopping a run in the collection runner.  I am not quite sure if it has to do with the size of the request but I have been running pretty large requests.  The only way I can exit a run is if I first pause the run, then stop the run.  Then it stops as expected.   If I click stop run without pausing while it is running requests all of postman quits.

**To Reproduce**
1.  Trigger a run with many rapid requests, maybe 100+ with no delay between the requests
2.  Press stop run.
3. Postman should crash
4. Try same run again
5. This time pause the run first
6. Then after it has paused, press stop run
7. Postman stops the run as expected.

**Expected behavior**
The app should just stop the run not crash.

**App information (please complete the following information):**
Using native app v7.30.1 on windows 10

**Additional context**
I am running many repeated requests quickly,  This has only started happening recently. I make heavy use of environment and collection variables and the console log.

**Comment by mohitranka** [comment] 2020-08-16 19:14
@connorgraves99 I am unable to reproduce this issue locally. Is it possible to share a collection on which this behaviour can be reproduced?

**Comment by sjkaiv** [comment] 2020-08-17 08:15
Issue reproducible in following case also:
1. Run a collection
2. Stop Run in between
3. Close the Collection Runner window
4. Click Runner button in main window
App crashes
Version - v7.30.1
OS - Windows

**Comment by DannyDainton** [comment] 2020-08-27 06:33
Hey @sjkaiv, 

This sounds very similar to https://github.com/postmanlabs/postman-app-support/issues/8972 where we have been able to replicate the runner crashing.

I'm going to close this issue and we will post any updated information on that thread.

Thanks for reporting. 🏆

**Closed as completed by DannyDainton** 2020-08-27 06:33 UTC
Labels: collection-runner, need-more-info, product/runtime
