### ISSUE TITLE
Postman for the web - Collection runner won't open the selected collection

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#8798] opened 2020-07-19 14:47 UTC
**Describe the bug**
It seems that the collection runner has some issues in the current "Postman for the web" version.

**To Reproduce**
1. Go to a workspace that is not the default workspace
2. Click on a collection and from the context menu select "Run"
3. A new tab will open with the collection runner.
4. The collection I selected to run will not be displayed. I collection runner will start in the Default workspace.

**Expected behavior**
"Postman for the web" should work like the Postman App and open the collection that I wanted to run.

**App information (please complete the following information):**
 - App Type: Postman for the web
 - OS: macOS

**Comment by coditva** [comment] 2020-07-20 04:45
@vdespa Thanks for writing in and testing out the Beta! This is something that we're working on currently. I'll post any updates on this thread. 😄

**Comment by DannyDainton** [comment] 2022-05-04 16:36
Hey @vdespa 

I'm unable to reproduce this issue in the latest version of the platform. If you're still able to recreate the problem we can look at reopening the issue but I'm closing this one for now.

**Closed as completed by DannyDainton** 2022-05-04 16:36 UTC
Labels: collection-runner, product/runtime
