### ISSUE TITLE
Additional `/` getting prefixes for absolute path in form-data in v7.1.0

### ISSUE THREAD

**Issue by Dach0** [a85/POSTMan-Chrome-Extension#6545] opened 2019-05-19 13:45 UTC
Uploading files doesn't seem to work correctly. First of all, I cannot upload multiple files with different keys, it only sends last one. If anything else is clicked or changed after Choose File button non of the files will be sent. I have the following example that used to work a week or two ago...

![Capture](https://user-images.githubusercontent.com/40193265/57982869-3e6d5800-7a4b-11e9-8e02-838b02faa51e.PNG)

and now, if I die and dump this request I have the following issue:

1. if cover_image file is last selected
![Capture1](https://user-images.githubusercontent.com/40193265/57982918-ec790200-7a4b-11e9-928d-89554a66a747.PNG)

2. if vehicle_images[] is last selected the first one is missing 
![Capture3](https://user-images.githubusercontent.com/40193265/57982938-39f56f00-7a4c-11e9-81fc-fc10bcce759b.PNG)

and if I edit any other filed after choosing files, in this example for instance if I change price_discounted both files are missing.

![Capture4](https://user-images.githubusercontent.com/40193265/57982965-922c7100-7a4c-11e9-8a65-802ecd4ee9b2.PNG)

Used to work with Postman 6.7.3 and now I'm using

 - Lumen [5.8.4]
 - Postman Version [7.1.0]
 - OS: [Win10 64bit]

**Comment by saswatds** [comment] 2019-05-19 14:27
Hi @Dach0, we are following this issue in this thread https://github.com/postmanlabs/postman-app-support/issues/6516 . We have found the root cause of this issue, as the patch has been applied. I will out real soon in production. 

I have also provided a temporary resolution to this problem in this comment https://github.com/postmanlabs/postman-app-support/issues/6534#issuecomment-493658383 

I will also like to re-iterate that this is a high magnitude and high impact issue for us and we are releasing the fix ASAP. 

Thanks

**Comment by Dach0** [comment] 2019-05-19 15:10
And I saw that little note when selecting files saying "This file resides outside working directory...". I thought it might be something connected. Thanks @saswatds on quick answer and pointing out workaround. When I put files in working directory it's working as it should, but still I'm expecting new release as you've said cause this is temporary.
Thanks again.

**Comment by saswatds** [comment] 2019-05-20 15:13
Hi @Dach0, The patch has been released as part of Postman App v7.1.1
I will be closing this issue as I am tracking this issue here https://github.com/postmanlabs/postman-app-support/issues/6516. 

If you are still facing this issue feel free to comment on the above-mentioned issue.

Thanks

**Closed as completed by saswatds** 2019-05-20 15:13 UTC
Labels: bug, product/runtime

**Comment by bardiaborhani** [comment] 2019-05-20 21:44
Hi @saswatds  I have v7.1.1 but am still having this issue

**Comment by saswatds** [comment] 2019-05-20 21:51
@bardiaborhani The issue here was that in windows os, additional `/` was getting added to absolute. Are you facing the same issue. If this is not the case then can you create a new issue to help us understand your problem better and triage it accordingly?

**Comment by bardiaborhani** [comment] 2019-05-20 21:56
@saswatds I was able to fix the issue by placing the files I want sent by Postman in Postman's default directory "C:\Users\[user_name]\Postman\files"
