### ISSUE TITLE
Closing app switches to desktop space on dual monitor setup

### ISSUE THREAD

**Issue by wolfadactyl** [a85/POSTMan-Chrome-Extension#6061] opened 2019-03-12 21:39 UTC
**Describe the bug**
When postman is open a primary monitor (either in fullscreen or not) and there are other apps open in fullscreen on a secondary monitor it will slide those apps out of the way and show the bare desktop on the secondary monitor when you quit postman.

**To Reproduce**
1. Open postman app on primary monitor
2. Open any other app on secondary monitor
3. Make other app fullscreen
4. Quit postman app
5. Observe fullscreen app on secondary monitor switching to bare desktop view

**Expected behavior**
Secondary monitor desktop state should be unaffected

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - 7.0.5 (although this was affecting other versions, don't remember which ones)
 - OS: macOS Mojave 10.14.3

**Comment by mccannt** [comment] 2020-08-14 22:37
@wolfadactyl Is this still happening in the most recent version of the app?

**Comment by mccannt** [comment] 2020-09-04 16:50
Closing this issue, not able to reproduce. 
If this is still an issue, please let us know.

**Closed as completed by mccannt** 2020-09-04 16:50 UTC
Labels: bug, platform/macOS, window-management
