### ISSUE TITLE
"GET", "SEND" and "SAVE" button align to the left of the panel

### ISSUE THREAD

**Issue by Neeerav** [a85/POSTMan-Chrome-Extension#2597] opened 2016-12-28 09:31 UTC
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 7
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Encountered it recently
 6. Expected behaviour: The buttons should be aligned to the right
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/7372817/21518717/655cbe8e-cd0e-11e6-8ed2-58b9c418d914.png)

Try to switch between multiple tabs in the Postman window.

**Comment by SamvelRaja** [comment] 2016-12-28 10:03
@Neeerav Thanks for bringing this to our notice. We shall take keep you updated on this progress over here.

**Comment by sdnts** [comment] 2016-12-28 10:17
Hi @Neeerav, can you reliably reproduce this? If so, can you let me know what triggers this?

**Comment by Neeerav** [comment] 2016-12-28 12:22
I cannot reproduce this issue consistently. I am trying to understand what exactly is causing this issue. I will update on the same thread in case I find it out.

**Comment by sdnts** [comment] 2017-08-23 09:20
@Neeerav I'm closing this since this isn't reproducible :(
Please reopen if you manage to replicate it again!

**Closed as completed by sdnts** 2017-08-23 09:20 UTC
