### ISSUE TITLE
Data Loss - data removed after being prompted to sign in

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7479] opened 2019-10-15 13:15 UTC
Filed by Product Support 

**Describe the bug**

**To Reproduce**
1 - Sign in to the application and uncheck `Keep me signed in` from the sign-in modal.
<img width="419" alt="Screen Shot 2019-10-16 at 12 39 57" src="https://user-images.githubusercontent.com/47351631/66915990-34f41600-f012-11e9-8ea6-8f3e2ee36c96.png">
2 - Create a few collections and environments
3 - After 12 hours of inactivity, the application prompts the revoked session modal. The user has the option to either Sign in or Sign out. 
<img width="472" alt="Screen Shot 2019-09-09 at 15 09 55" src="https://user-images.githubusercontent.com/47351631/66834750-29dbb000-ef56-11e9-9d58-ebfef86440e8.png">
4 - Sign in to the application results in a data loss. 

**Expected behavior**
The data should be synced and populate to the app

**Comment by preethammavin** [comment] 2019-10-18 16:52
I am unable to reproduce the issue, can you add a bit more details? What sort of data loss do you see , is it on every app version?

**Comment by Raj-postman** [comment] 2019-10-21 10:34
@preethammavin The issue is usually seen on the 7.x version, which leads to loss of collections/environments. My only suspect is that the data wasn't synced after some point. Linked an issue on the same lines.

**Comment by kamalaknn** [comment] 2019-10-21 16:53
@Raj-postman Is this the same as #7475?

**Comment by Raj-postman** [comment] 2019-10-22 05:41
@kamalaknn Not entirely, here the issue was seen on the version above 7.x and the data loss is usually reported after users receive "Session timeout" popup asking for reauthentication.

**Comment by kaiwie** [comment] 2019-10-23 06:46
Today i had the same issue. Starting, Postman and ask for login. Entire Data is gone :( 
Postman for Windows
Version 7.9.0

**Comment by cyrielle-hada** [comment] 2019-10-23 09:04
@kaiwie, would it be possible to submit a ticket from [this page](https://www.getpostman.com/support)? Also, could you provide a high-level list of steps that we might be able to take to reproduce the behavior locally? That will help us track down what’s happening and figure out the best way forward.

**Comment by kamalaknn** [comment] 2019-10-24 04:42
@cyrielle-hada Could we get access to application logs for cases where this has happened?

**Comment by kaiwie** [comment] 2019-10-24 07:23
@cyrielle-hada of course. @kamalaknn Tell me which logs are of interest and I'll add them.

**Comment by cyrielle-hada** [comment] 2019-10-24 08:21
@kaiwie To find your app logs, navigate to `View > Developer > View Logs in Finder/Explorer`
<img width="757" alt="Screen Shot 2019-10-24 at 09 05 59" src="https://user-images.githubusercontent.com/47351631/67466727-794d6a80-f63f-11e9-964d-1dca9b08be3e.png">

**Comment by ArjunSingh-PM** [comment] 2020-01-22 05:20
We have not been able to gather logs from the user as the user had cleared their local directory. Presently, we can not proceed further to identify the root issue and resolve the issue. 

Closing the issue due to lack of information.

**Closed as completed by ArjunSingh-PM** 2020-01-22 05:20 UTC
Labels: bug, sync, product/login
