### ISSUE TITLE
Postman update fails because of missing permissions

### ISSUE THREAD

**Issue by komape** [a85/POSTMan-Chrome-Extension#9910] opened 2021-05-06 08:12 UTC
**Describe the Issue**

I cannot update my Postman. It always reports that the update failed. I took a look into the DevTools and the error says: `EACCES: permission denied, open '/opt/Postman/Postman-1620288011421.tar.gz'`. This file doesn't exist. I guess Postman need sudo to update. If so, Postman should ask then for the permission.

**Steps to Reproduce**

1. Click on 'Help' -> 'Check for Updates'
2. Click on 'Update'

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/25869589/117263696-d213db00-ae52-11eb-92d3-7a78c2236ece.png)

**Environment Information**

 - Platform Type: Postman for Linux
 - Postman Version: Version 7.25.0
 - Operating System: linux 5.11.0-16-generic / x64

**Additional Context**

**Comment by DannyDainton** [comment] 2021-05-06 11:33
Hey @komape 

That looks you're trying to grab an older version of the client - Currently, we're on version 8 which brings in a bunch of new functional and UI changes.

As you're using Linux, you could get that version using snap - https://snapcraft.io/postman

More details can be found on this thread - https://github.com/postmanlabs/postman-app-support/issues/9573#issuecomment-804808932

**Comment by komape** [comment] 2021-05-06 15:36
Maybe Postman should do this by itself... Or is it not able to handle major version updates?

**Comment by komape** [comment] 2021-05-06 15:37
Besides that there is a newer version, the problem is independent from that. It's not like Postman doesn't find a version to install, Postman is not allowed to do so. That's the problem

**Comment by komape** [comment] 2021-05-20 17:05
the same error occurres with version 8

**Comment by wigglytuff-tu** [comment] 2021-07-23 13:44
@komape did u find a solution to it? I am facing the same problem

**Comment by komape** [comment] 2021-07-28 12:54
@wigglytuff-tu I reinstalled it. So far it has not been fixed :/

**Comment by madodig** [comment] 2021-09-24 11:04
The problem is that Postman is installed in the location where users have no write permissions (ex: /opt/Postman). So when users run Postman, auto upgrader is unable to download the new release (to ex: /opt/Postman/Postman-1632470662491.tar.gz).

Postman upgrader process should be improved so that it asks you for password in such case, once new version is available (if you want to perform the upgrade). If user has root privileges it should successfully perform the upgrade.

In the meantime, you have two options:
1) Install Postman to your home directory (ex: /home/user/Postman or /home/user/apps/Postman). Downside to this approach is that Postman will be accessible only to you; if there are other users using the computer, they will have to install their own Postman instances in their home directories.
2) If you have root privileges, you can perform the upgrade by running Postman as root. Close Postman if running, open the terminal and run
`sudo /opt/Postman/app/postman --no-sandbox`
(NOTE: Running as root without --no-sandbox is not supported; see https://crbug.com/638180)
If you have never run Postman as root previously, you will be greeted with the welcome page which you can just skip and go straight to the app to perform the upgrade.
You can monitor the progress in the terminal.
After the new release is downloaded, Postman will ask you to restart to perform the upgrade. Don't restart, but close the Postman and re-run it from the terminal by repeating the previous command. If you just do the restart from the app, Postman will be re-run with your user and upgrade will not be successful.
Once the upgrade is done, close the Postman and run it as usually.

**Comment by inertnet** [comment] 2021-09-28 09:55
@madodig Your solution worked for me with a minor tweak:
`sudo /opt/Postman/app/Postman --no-sandbox` instead of `sudo /opt/Postman/app/postman --no-sandbox`
And indeed you have to start this twice from the terminal.

**Comment by RaisinTen** [comment] 2022-02-21 09:05
Why do you want to keep Postman inside the `/opt` directory? Is it because we mention it in https://learning.postman.com/docs/getting-started/installation-and-updates/#installing-postman-on-linux (we have sent a PR to update the path in https://github.com/postmanlabs/postman-docs/pull/3890)?

**Comment by twitharshil** [comment] 2022-02-23 06:11
Hey Everyone, 

The doc modification PR mentioned above ^ is merged. Closing the ticket as we don't recommend extracting the application directory inside the directory that doesn't have write permissions. Also, we don't recommend users run postman with sudo. [Ref](https://learning.postman.com/docs/getting-started/installation-and-updates/#:~:text=Avoid%20starting%20Postman%20using%20the%20sudo%20command%2C%20as%20it%20will%20create%20permission%20issues%20on%20the%20files%20created%20by%20Postman)
> Avoid starting Postman using the sudo command, as it will create permission issues on the files created by Postman.

**Closed as completed by twitharshil** 2022-02-23 06:11 UTC
Labels: bug, platform/linux, product/desktop-foundation, version/8, component/auto-updates, version/7

**Comment by BayoKwendo** [comment] 2022-12-08 12:52
> @madodig Your solution worked for me with a minor tweak: `sudo /opt/Postman/app/Postman --no-sandbox` instead of `sudo /opt/Postman/app/postman --no-sandbox` And indeed you have to start this twice from the terminal.

I am facing the same problem but when I running the command ***sudo /opt/Postman/app/Postman --no-sandbox***  this what i get

```

The disableGPU setting is set to undefined
Not disabling GPU
[139728:1208/154831.938781:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[139728:1208/154831.938917:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
No protocol specified
[139728:1208/154831.972521:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
No protocol specified
[139728:1208/154831.976942:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
No protocol specified
[139728:1208/154831.980915:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
Main~createDefaultWorkingDir - Error while creating default working dir Error: default working directory already exists
    at /opt/Postman/app/resources/app/services/workingDirManager.js:22:23
    at FSReqCallback.oncomplete (node:fs:196:5)
No protocol specified
[139728:1208/154831.986946:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
No protocol specified
[139728:1208/154831.991756:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
No protocol specified
[139728:1208/154831.996749:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
1670503711997 main info "Booting Postman 10.5.2, linux-5.4.0-91-generic on x64"
No protocol specified
1670503711998 main info "EventBus~initialize - Success"
[139728:1208/154832.002196:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
1670503712002 main info "Proxy configuration has not been setup"
1670503712003 main info "CloudProxyManager~init - Success"
1670503712010 main info "UpdateHandler~init - Success"
1670503712013 main info "LeaderSelection: Initialized successfully"
No protocol specified
1670503712015 main info "VersionDependencyService: Initialized successfully"
[139728:1208/154832.017437:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
1670503712024 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
No protocol specified
error reading fileError: ENOENT: no such file or directory, open '/root/.config/Postman/proxy/postman-proxy-ca.crt'
1670503712026 main info "Generated root certificate for linux"
[139728:1208/154832.028044:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
[139728:1208/154832.028069:FATAL:gpu_data_manager_impl_private.cc(417)] GPU process isn't usable. Goodbye.
[1]    139727 trace trap  sudo /opt/Postman/app/postman --no-sandbox
➜  ~ 
```

**Comment by frankiedrake** [comment] 2023-01-25 08:04
I've spent 30 minutes and about a thousand nerve fibers moving postman directory around `/opt`, `/home` etc while I just noticed that the owner of a postman directory was `root`! Just changed it to my user and it's done
