### ISSUE TITLE
SSL certs with SAN leads to Parse Error

### ISSUE THREAD

**Issue by davecanderson** [a85/POSTMan-Chrome-Extension#4515] opened 2018-05-02 00:54 UTC
## App Details:
```
Postman for Windows
Version 6.0.10
win32 6.1.7601 / x64
```
## Issue Report:
I have an API served from different subdomains bound to the same website using the same wildcard SSL certificate. On our production instance Postman calls to all but one of our subdomains fail with ``Could not get any response``.  

The succeeding call is to the subdomain which is the [ServiceStack Proxy](http://docs.servicestack.net/proxy-feature) for calls to the authentication of other domains. This should be transparent to the client making the request.

The Postman Console shows ``Parse Error`` for the failing call and omits several of the Request Header values. It does not appear possible to find the cause of the parse error.

![auth-call-fails-console](https://user-images.githubusercontent.com/2754325/39500098-77f792d0-4df5-11e8-854f-0b544c45b613.png)

All the calls are processed by the same code and API requests outside Postman succeed. Using the JavaScript code supplied by Postman in the DevTools successfully processes both requests.

![auth-call-fails-devtools](https://user-images.githubusercontent.com/2754325/39500099-782f4748-4df5-11e8-8ba8-534a1bb88cc7.png)

This problem effects several instances of Postman used on different machines so does not appear to be network related.

**Comment by dhineshwiz** [comment] 2018-05-02 12:27
hey @davecanderson . Thanks for reporting this issue, I am assigning as bug, we will fix it soon

**Comment by davecanderson** [comment] 2018-07-25 00:11
We have switched to Let's Encrypt on all our environments now and this problem is making Postman almost unusable.

I think this issue is related to the fact our SSL certificate uses Subject Alternative Name (SAN) entries for the other domains. The api domain where the request succeeds is the Common Name for the cert. 

We intend to switch to a wildcard certificate which would probably avoid this issue but https://certifytheweb.com/ does not yet support our DNS provider to allow the required DNS validation from Let's Encrypt.

Is there any estimate on if/when a fix for this issue might be available?

**Comment by numaanashraf** [comment] 2018-07-25 06:11
@davecanderson Could you try turning off SSL verification via Settings > General and check whether this solves the issue for you?

**Comment by davecanderson** [comment] 2018-08-02 23:57
I've had SSL verification turned off for a long while since we use self signed certs for development. I'll try some different cert values and see if I can isolate the issue. It seemed to start when we began having multiple values in our Subject Alternative Name field in the cert i.e.

```
DNS Name=api.staging.tekreader.com
DNS Name=c2d.staging.tekreader.com
DNS Name=comcover.staging.tekreader.com
DNS Name=egloo.staging.tekreader.com
DNS Name=wsaa.staging.tekreader.com
```
This was necessary as a result of [Chrome 58 no longer accepts certificates that fallback to common name (ERR_CERT_COMMON_NAME_INVALID)](https://bugs.chromium.org/p/chromium/issues/detail?id=700595&desc=2)

**Comment by numaanashraf** [comment] 2019-01-09 12:19
Duplicate of #3609

**Closed as completed by numaanashraf** 2019-01-09 12:19 UTC
Labels: bug, Certificate, request-sending
