### ISSUE TITLE
Not able to view the environment details by clicking on eye icon

### ISSUE THREAD

**Issue by renjithrnair** [a85/POSTMan-Chrome-Extension#9960] opened 2021-05-21 07:20 UTC
Describe the Issue

The eye icon in the top right corner of the postman application which is next to the environment file dropdown menu should be clickable and we should be able to see the environment variables and their values if an environment is selected. But I'm not able to view the environment variables and their values.

Steps to Reproduce

1.Open the postman workspace
2.Select an environment file from the dropdown in the top right corner
2. Click on the eye icon next to the dropdown tab

Screenshots or Videos
<img width="566" alt="Capture" src="https://user-images.githubusercontent.com/28842267/119098019-054d9100-ba33-11eb-9fbd-3b7f66016eee.PNG">

Environment Information

Platform Type: Desktop
Postman Version: v8.5.0
Operating System: Windows

Additional Context
In the paid version of the application, this issue is not present.

**Comment by timbochamp** [comment] 2021-05-21 17:33
This looks like a duplicate of #9750 if you could report your finding there please, @renjithrnair ? I'm curious if the total number of requests, collections, console activity in runs is causing a performance issue if you could clarify that? I suggested some workarounds in the original issue and the steps to sending logs along to us which would also be helpful!

**Closed as completed by timbochamp** 2021-05-21 17:33 UTC

**Comment by renjithrnair** [comment] 2021-06-08 05:05
This issue got resolved with v8.6.0 update. @timbochamp
