### ISSUE TITLE
Multiple scrollbars in UI

### ISSUE THREAD

**Issue by abdulkareemgs** [a85/POSTMan-Chrome-Extension#2238] opened 2016-08-09 10:51 UTC
1. Postman ver 4.4.3
2. Chrome app 
3. OS details:Win 32
4. Is the Interceptor on and enabled in the app:No
5. Did you encounter this recently, or has this bug always been there:Dont Know
6. Expected behaviour:Single Scroll Bar
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

![screen shot 2016-08-09 at 4 12 51 pm](https://cloud.githubusercontent.com/assets/10112879/17513885/452f0458-5e4d-11e6-8029-9e2c71aa5458.png)

**Comment by a85** [comment] 2016-09-07 21:21
A 3-pane layout is coming to Postman soon.

**Comment by excentris** [comment] 2016-10-24 07:23
@a85 Nice to hear. Can you give an indication of how soon?

**Comment by maxgalbu** [comment] 2016-12-16 11:00
Would be nice to have it, really :)

**Comment by excentris** [comment] 2016-12-16 11:01
This has become less of an issue with the new experimental 3-pane layout...

**Comment by vegetableman** [comment] 2016-12-16 11:02
This issue has been fixed for quite a while ^_^. Closing this. @abdulkareemnalband Feel free to reopen if the issue still exists.

**Closed as completed by vegetableman** 2016-12-16 11:02 UTC

**Comment by maxgalbu** [comment] 2016-12-16 11:09
How can I enable this experimental panel layout? Is it "two panel layout" in the options?

**Comment by Sarastro72** [comment] 2017-04-27 11:19
I beg to differ, the issue is still very much alive for me. I am running 4.10.7 on os-x 10.12.3. Makes it difficult to read the last few lines of the payload. :(

![screen shot 2017-04-27 at 13 19 21](https://cloud.githubusercontent.com/assets/3330155/25481157/321aa198-2b4c-11e7-8009-52db6054b003.png)

**Comment by raja031191** [comment] 2017-04-27 11:44
@maxgalbu @Sarastro72 You can try our Two pane view (cmd/ctrl+alt+v)  or  View -> Toggle two pane view
![screen shot 2017-04-27 at 5 13 50 pm](https://cloud.githubusercontent.com/assets/22856573/25481898/f0bfe548-2b6c-11e7-8086-be278f515d20.png)

**Comment by SamvelRaja** [comment] 2017-04-27 11:46
@maxgalbu @Sarastro72 You can try our Two pane view (cmd/ctrl+alt+v) or View -> Toggle two pane view
![screen shot 2017-04-27 at 5 13 50 pm](https://cloud.githubusercontent.com/assets/5114052/25481958/47367b94-2b6d-11e7-96a1-483478d27615.png)

**Comment by Sarastro72** [comment] 2017-05-08 07:10
@SamvelRaja Thanks, I tried it and I don't really like it. The adressbar becomes too small in this view, I can't see the URL.

I'm just pointing out that the bug isn't fixed. There is an experimental beta feature that doesn't have the bug. That's not the same thing as it being fixed IMHO.

**Comment by pepkin88** [comment] 2018-03-25 15:51
Yes. There is a simple solution to this problem, which doesn't require creating a completely new layout. Lowering the results pane's height is enough for the outer scrollbar to disappear. I suggest to just stretch it until the edge of a window, but not beyond it.

**Comment by pepkin88** [comment] 2018-03-25 15:52
> pepkin88 unassigned bhawna2109 a minute ago

What? I didn't unassign anyone. What's going on?

**Comment by pepkin88** [comment] 2018-03-25 16:22
@SamvelRaja Your screenshot shows nicely the issues with the two-panel view:
![unused space issue](https://i.paste.pics/d5c22c7d917965a1cf03b555197d8d3f.png)

I admit, for some requests this view might be better, e.g. for requests with big payloads.
But for GETs with long, parameterized URLs and no payload, the single panel view seems to be better.

So it would be nice to have an option to wrap/trim the results pane to the container, without overflowing. In my opinion such option should be set by default, but that's a secondary issue.
