### ISSUE TITLE
Duplicating folders deletes the body in the copied folder request

### ISSUE THREAD

**Issue by miralpopat** [a85/POSTMan-Chrome-Extension#3539] opened 2017-09-18 11:13 UTC
## App Details:

```
Postman for Windows
Version 5.2.0
win32 6.3.9600 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: recently
 2. Expected behaviour: should keep the request as after copying the folders
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

1. Duplicate the folder with request in it.
2. Check the request body, it goes empty, headers remains all good

**Comment by abhijitkane** [comment] 2017-09-18 11:18
@miralpopat Not able to reproduce this. Can you attach a screencast/gif of the bug?

**Comment by abhijitkane** [comment] 2017-09-18 12:02
@miralpopat Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/3484. This has been fixed internally - we'll push out a public fix soon.

**Closed as completed** 2017-09-20 07:42 UTC
