### ISSUE TITLE
unable to use {{variable name}} in access token name field

### ISSUE THREAD

**Issue by rotorboy** [a85/POSTMan-Chrome-Extension#6114] opened 2019-03-21 06:44 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
The docs clear and unequivocally state that variable substitution is available in ALL text fields, however entering {{variable_name}} in the token name field simply creates the string "{{variable_name}}

**To Reproduce**
1. Go to 'token name' field and enter any variable eg {{$timestamp}}
2. click "request token"; name will have {{$timestamp}} as string

**Comment by codenirvana** [comment] 2019-03-21 07:26
@rotorboy In which authorization method you are facing this issue?
I tested with Bearer Token and OAuth 2.0 fields and its working fine (attached screenshot).

Can you provide more information regarding the issue you are facing?

<img width="987" alt="Screenshot 2019-03-21 at 12 47 23 PM" src="https://user-images.githubusercontent.com/4865836/54737843-bf3cde80-4bd7-11e9-8a88-a7eb1ec23609.png">

**Comment by rotorboy** [comment] 2019-03-21 07:44
I’m trying to use time stamp in the token name field in the token request dialog box, in the “edit collection” feature (e.g. Im trying to get a new token for the collection, and use the time stamp as part of the token “name” string...

-Avi

**Comment by rotorboy** [comment] 2019-03-21 07:44
Sorry, the type is OAUTH2...

**Comment by vikiCoder** [comment] 2019-07-29 08:47
Closing this as a duplicate of following issue:
https://github.com/postmanlabs/postman-app-support/issues/3525

**Closed as completed by vikiCoder** 2019-07-29 08:47 UTC
Labels: Auth, OAuth2, product/runtime
