### ISSUE TITLE
Requesting archived data does not complete and provide a download link

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7189] opened 2019-08-25 23:53 UTC
**Describe the bug**
The user started "data export" on 29th July and the dashboard still doesn't show a download link. Clicking on "Request" again shows an error stating that an existing export is already running.

**Expected behaviour**
Existing export should finish and provide a link to download the data.

**Screen Recording attached**
[screencast-saloon.postman.co-2019.08.24-23_01_26.webm.zip](https://github.com/postmanlabs/postman-app-support/files/3538850/screencast-saloon.postman.co-2019.08.24-23_01_26.webm.zip)
**Screenshot**
<img width="1298" alt="Screen Shot 2019-08-26 at 11 59 13 AM" src="https://user-images.githubusercontent.com/21366/63657713-fb184780-c7f8-11e9-95b6-40eb88e3c7b9.png">

**App information (please complete the following information):**
 - App Type: Native App

**Additional context**
Logged on behalf of a user.
User details are available in the internal ticket.

**Comment by cyrielle-hada** [comment] 2019-08-28 17:09
@xk0der It looks like it is a duplicate of this issue [#7046](https://github.com/postmanlabs/postman-app-support/issues/7046). Closing this one!

**Closed as completed by cyrielle-hada** 2019-08-28 17:09 UTC
