### ISSUE TITLE
Cannot set multiple cookies using pm.cookies.jar()

### ISSUE THREAD

**Issue by tguedes-connectwise** [a85/POSTMan-Chrome-Extension#7541] opened 2019-10-25 20:30 UTC
**Describe the bug**
I am attempting to set multiple cookies but only the first one is actually being set. The other set calls aren't even called.

**To Reproduce**
Using the Postman test scripting environment
1. Add the following code:
```
var jar = pm.cookies.jar();
jar.set(pm.environment.get("site"), "cookie1", "xxx");
jar.set(pm.environment.get("site"), "cookie2", "yyy");
console.log(jar.get("cookie1"));
console.log(jar.get("cookie2"));
```

Output:
`xxx`

Only the first cookie will be outputted.

I've even added the callback function to see if there is an error setting the token: 
```
jar.set(pm.environment.get("site"), "cookie1", "xxx", function(error, cookie) {
   console.log("cookie1");
   console.log(cookie);
});
jar.set(pm.environment.get("site"), "cookie2", "yyy", function(error, cookie) {
   console.log("cookie2");
   console.log(cookie);
});
```

Output:
```
cookie1
xxx
```

The console logs in the second callback function are never called. So it seems like the runner is just completely ignoring the second set call.

**App information (please complete the following information):**
 - App Type: Native Type
 - Postman Version: 7.10.0
 - OS: Windows 10

**Comment by shamasis** [comment] 2020-03-11 13:43
Hi. Can you check your Postman Console logs to see what error you are getting? I am testing this in our latest app 7.20.0 (did not get chance to test in 7.10) and was unable to reproduce.

1. I went and added `example.com` for programmatic whitelisted access
2. I added environment variable `site` to value `example.com`
3. Made call to a random domain with the following script

```
var jar = pm.cookies.jar();
jar.set(pm.environment.get("site"), "cookie1", "xxx", function(error, cookie) {
   console.log("cookie1");
   console.log(cookie);
});
jar.set(pm.environment.get("site"), "cookie2", "yyy", function(error, cookie) {
   console.log("cookie2");
   console.log(cookie);
});
```

- Note that cookie is only callback based API 
- I see the result in console

![Screenshot 2020-03-11 at 19 10 46](https://user-images.githubusercontent.com/232373/76423048-357bb780-63cc-11ea-9bd3-9df90b2583ab.png)

Perhaps there's something specific in your case that this is not working for. Can you attach a non-sensitive scaled down version of environment and collection as a zip for us to try. You may use `httpbin.org` APIs to demonstrate the same.

**Comment by codenirvana** [comment] 2020-05-03 20:59
@tguedes-connectwise This is happening because the domain is not added to the programmatic cookie access whitelist. To help debug such issues we recently added a warning log in the console when programmatic cookie access is denied.

Closing this issue... please feel free to reopen if the issue persists.

**Closed as completed by codenirvana** 2020-05-03 20:59 UTC
Labels: bug, cookies, product/runtime, sandbox, blocked/need-repro

**Comment by chusri** [comment] 2023-06-09 09:55
for someone who are looking for the solution of this prob:

**PLEASE SET SECOND COOKIE IN CALLBACK**

```
var jar = pm.cookies.jar();
jar.set(pm.environment.get("site"), "cookie1", "xxx", (error) => {
  jar.set(pm.environment.get("site"), "cookie2", "yyy")
});
```
