### ISSUE TITLE
Change postman request data type to data from data-raw

### ISSUE THREAD

**Issue by JAELatDHI** [a85/POSTMan-Chrome-Extension#10020] opened 2021-06-11 13:00 UTC
I am trying to export files from a server called IUCLID. 

To do this I must set the request body type as --data. 

This is apparently not possible in Postman, according to a message I received from their support. 

Please add this feature!

**Comment by DannyDainton** [comment] 2021-06-11 13:01
Hey @JAELatDHI 

Are you able to provide an example of the request you're trying to make, please?

**Comment by JAELatDHI** [comment] 2021-06-11 13:05
This is the code atm:
curl --location --request POST '######/iuclid6-ext/api/ext/v1/raw/Reference_Substance/#####/export' \
--header 'accept: application/vnd.iuclid6.ext+json;type=iuclid6.Iuclid6Job' \
--header 'IUCLID6-USER: SuperUser' \
--header 'IUCLID6-PASS: ####' \
--header 'Content-Type: application/vnd.iuclid6.ext+json; type=iuclid6.FullExport' \
**_--data-raw '{}'_** 

**_--data-raw '{}'_** should be **_--data '{}'_**, Postman cannot recognize this syntax however.

**Comment by DannyDainton** [comment] 2021-06-11 13:20
That's currently working correctly if you were to manually change that from `--data-raw` to `--data` though right?

**Comment by JAELatDHI** [comment] 2021-06-11 13:23
No, then it highlights --data as red in code snippets and ignores it:

![image](https://user-images.githubusercontent.com/85746288/121692996-f9e90500-cac8-11eb-9b2a-00a450ed215e.png)

**Comment by DannyDainton** [comment] 2021-06-11 13:27
Are you trying to import that code into the app to make a new request or exporting that to another place to use?

If you could expand a little on your use case here that would help offer a better solution. 😄

**Comment by JAELatDHI** [comment] 2021-06-11 13:39
Sorry of course I honestly didn't expect this post to get noticed. 

I am creating a POST request to create an Export job in the server, which I then download using a GET request.

**Comment by JAELatDHI** [comment] 2021-06-11 13:47
Here is all the code that I am running at the moment to run it

[XportCodeforSupport.pdf](https://github.com/postmanlabs/postman-app-support/files/6638826/XportCodeforSupport.pdf)

**Comment by DannyDainton** [comment] 2021-06-11 13:52
I'm a bit confused - Is the POST request being actioned via Postman or you're crafting the request and then using the code feature to run in from the command line with curl?

Is the GET request getting run with Postman?

**Comment by JAELatDHI** [comment] 2021-06-11 13:58
No I programmed or crafted it in Postman (I am using environment variables). Everything is running through Postman. I am just using "Code Snippet" to compare my code with the documentation code.

**Comment by webholik** [comment] 2022-02-04 10:55
@JAELatDHI  The only difference between the `--data` and `--data-raw` is that with the former option you can specify a filename from where curl will fetch the data to be sent. You can do the same in Postman by selecting the body type as `binary` and selecting the file you want to send. You can also set the `Content-Type` header to match the content type of the file. If you can tell why exactly is the `--data` option necessary for  your use case, we can take further action.

**Comment by JAELatDHI** [comment] 2022-02-04 12:08
The exact use case is related to downloading a file using a GET request, which is a .i6z file type. (Which is proprietary to the IUCLID Database, some info on the DB here: https://iuclid6.echa.europa.eu/project-iuclid-6 )

I have since gone around the issues by writing the scripts in python, however it would be nice to also be able to do this in postman. Here is a snippet of what the code looks like in python:

Post request to create the download:
```
  url = f'http://iuclid7:8080/iuclid6-ext/api/ext/v1/raw/{doc_type}/{key}/export'
            headers = {
                'iuclid6-user': 'SuperUser',
                'iuclid6-pass': '######',
                'accept': 'application/vnd.iuclid6.ext+json; type=iuclid6.Iuclid6Job',
                'Content-Type': 'application/vnd.iuclid6.ext+json; type=iuclid6.FullExport'

response = requests.post(url, headers=headers, data='{}')
```
               
Get request to download it: 
````
download_url = f'http://iuclid7:8080/iuclid6-ext/api/ext/v1/system/job/{job_id}/result'
                download_headers = {
					'iuclid6-user': 'SuperUser',
					'iuclid6-pass': '#####',
					'accept': 'application/vnd.iuclid6.archive',
					'Accept-Encoding': 'gzip, deflate',}

                download_response = requests.get(download_url, headers=download_headers)
```

(Python 3.9.9, requests library)

**Comment by webholik** [comment] 2022-03-25 06:04
Hey @JAELatDHI, According to curl docs, for the data you are sending with the request i.e. `{}` there is no difference between using `--data-raw` or `--data`.
> --data-raw \<data\>
>   (HTTP) This posts data similarly to -d, --data but without the
>    special interpretation of the @ character.

 Since your request body doesn't contain the `@` character, the resulting request *should* be exactly the same. The fact that this is not happening hints that the problem is either with `curl` or `IUCLID` server, and not with the generated snippet.  I am closing this for now, but feel free to open it up again if you feel I'm missing something here.

**Closed as completed by webholik** 2022-03-25 06:04 UTC
Labels: bug, product/codegen, product/api-design

**Comment by Nyceane** [comment] 2022-07-19 23:12
> Hey @JAELatDHI, According to curl docs, for the data you are sending with the request i.e. `{}` there is no difference between using `--data-raw` or `--data`.
> 
> > --data-raw <data>
> > (HTTP) This posts data similarly to -d, --data but without the
> > special interpretation of the @ character.
> 
> Since your request body doesn't contain the `@` character, the resulting request _should_ be exactly the same. The fact that this is not happening hints that the problem is either with `curl` or `IUCLID` server, and not with the generated snippet. I am closing this for now, but feel free to open it up again if you feel I'm missing something here.

This does not work, I am facing a lot of problems where --data-raw isn't being consumed where --data is.  So please give us an option of removing '-raw' part of '--data-raw'.  Currently I have to manually remove it and run it under terminal which is very exhausting.

**Comment by domrycz** [comment] 2022-09-05 09:52
I have exactly the same issue. The PUT request using curl and **--data** works but exactly the same request via postman (and thus with **--data-raw** or **--data-urlencode**) is not working. It is not possible to change it to use --data

**Comment by idiked** [comment] 2022-09-08 13:15
There was a same problem, 
in Postman request with **--data-raw** did not work, but same request with **--data** in curl was sent without errors.

Fixed it with enabling all auto-generated headers in Postman
