### ISSUE TITLE
Encoding of URL query string is incorrect

### ISSUE THREAD

**Issue by sndwow** [a85/POSTMan-Chrome-Extension#3734] opened 2017-11-04 01:33 UTC
## App Details:
```
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64
```

## Issue Report:

For example url : http://abc?plate_no=粤123456
Using fiddler will display：http://abc?plate_no=�123445

**Comment by SamvelRaja** [comment] 2017-11-06 12:54
Thanks for bringing this to our notice, we shall look at the issue and update the progress in the same thread again.

**Comment by scplay** [comment] 2018-04-24 02:11
same issue here, when chinese parameters in GET, the uri encode does not work corretly. My service return 400 bad request

**Comment by abhijitkane** [comment] 2019-01-04 09:13
Related to https://github.com/postmanlabs/postman-app-support/issues/3688

**Comment by shamasis** [comment] 2019-06-17 15:58
Closing as very very close duplicate of https://github.com/postmanlabs/postman-app-support/issues/4555

**Closed as completed by shamasis** 2019-06-17 15:58 UTC
Labels: bug, encode-decode, product/runtime
