### ISSUE TITLE
Dashboard: viewing all team environments results in an error

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6875] opened 2019-07-08 19:10 UTC
**Describe the bug**

[Reported by Postman Support, on behalf of original user]

User attempts to load https://go.postman.co/team/elements?type=environment to view all team environments, but the page doesn't load any environments, and the following error shows in browser console:

"/api/environments?team=412119&uid=true undefined" for raven.js:51

Please see internal notes.

**To Reproduce**
1. User loads: https://go.postman.co/team/elements?type=environment
2. Banner and other UI elements render, but no environments load
3. Browser console contains following error: "/api/environments?team=412119&uid=true undefined" for raven.js:51

**Expected behavior**
 - Page loads successfully
 - Error message is shown as an alert on the page (as we do for other errors), instead of only in the browser console.

**App information (please complete the following information):**
 - App Type: Web dashboard (Chrome)
 - Postman Version: 7.2.2
 - OS: macOS

**Additional context**
See internal notes

**Comment by sankalp0o** [comment] 2019-07-09 17:36
Not reproducible. Must be something wrong with that account. @ankitjaggi @ankit-m Could you guys take a look at this?

**Comment by sankalp0o** [comment] 2019-12-24 06:45
Thanks for reporting this JP. We ere unable to reproduce this and we think this was a one-off case of the server timing out and unlikely to recur. I'm closing this but feel free to reopen if you see more cases like this coming up.

**Closed as completed by sankalp0o** 2019-12-24 06:45 UTC
Labels: bug
