### ISSUE TITLE
Environment variable not being injected properly into request URL

### ISSUE THREAD

**Issue by robert-krikey** [a85/POSTMan-Chrome-Extension#5435] opened 2018-10-27 03:44 UTC
**Describe the bug**
When I try to make a request that interpolates an environment-level variable, the injected value is blank.

**To Reproduce**
1. Create an environment
2. Create a variable in the environment called `foo`
3. Try to make a request to `http://{{foo}}`

**Expected behavior**
I expect the value of `foo` to be injected into the URL.

**Screenshots**
![image](https://user-images.githubusercontent.com/43487745/47599297-e2d96100-d978-11e8-83f7-3bf9daef5aeb.png)

Interestingly, in the screenshot above you can see that the tooltip is displaying the correct value, but somehow it's not making it into the actual URL of the request.

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 6.4.4
 - OS: macOS Mojave 10.14 (18A391)

**Additional context**

**Comment by bhargavkaranam** [comment] 2018-10-27 06:33
Hi @robert-krikey,
This is an expected behaviour. Postman uses the current value of the environment variable during execution. Here, since your current value is empty, Postman is considering the empty value during request execution. You can read more about initial and current values in Postman from [here](https://www.getpostman.com/docs/v6/postman/environments_and_globals/sessions)

Closing this issue for now. If you have any more queries regarding this, you can use our [Community page](community.getpostman.com).

**Closed as completed by bhargavkaranam** 2018-10-27 06:33 UTC
