### ISSUE TITLE
Postman on Windows display white blank window

### ISSUE THREAD

**Issue by gluons** [a85/POSTMan-Chrome-Extension#2256] opened 2016-08-12 11:21 UTC
1. Postman Version: Latest 4.5.1 (64 bits)
2. App: Windows
3. OS details: Windows 10 Pro (64 bits) version 1607 build 14393.51
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: I installed Postman first time.
6. Expected behaviour: Display app screen
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   ![postman2](https://cloud.githubusercontent.com/assets/4688092/17620781/e885fdba-60b8-11e6-82d6-199794cd096c.png)
   
   Nothing show in console.
   
   ![postman3](https://cloud.githubusercontent.com/assets/4688092/17620823/347bb390-60b9-11e6-979d-0a9e70f11805.png)
8. Screenshots (if applicable)
   ![postman](https://cloud.githubusercontent.com/assets/4688092/17620780/e87f52da-60b8-11e6-8ce4-e98e7ae81771.png)

I've tried to reinstall many time but it's still blank.

**Comment by SamvelRaja** [comment] 2016-08-12 15:38
@gluons 
Could you please open the app directly through the cmd and send us the logs from there?
`c:\Users\<User>\AppData\Local\Postman\app.4.5.1\Postman.exe`

**Comment by gluons** [comment] 2016-08-13 09:27
@SamvelRaja Not work :worried:

![postman](https://cloud.githubusercontent.com/assets/4688092/17642471/badff4aa-6172-11e6-9998-9098927d3c86.png)

**Comment by SamvelRaja** [comment] 2016-08-13 09:31
@gluons  you would have got some logs in your cmd. could you please get that for us?

**Comment by gluons** [comment] 2016-08-13 09:43
@SamvelRaja Did you mean `View -> Toggle Dev Tools`? It's empty. I've no idea. 😟 

![postman](https://cloud.githubusercontent.com/assets/4688092/17642551/cef43710-6174-11e6-8c6c-28e7ab41a07d.png)

![postman-2](https://cloud.githubusercontent.com/assets/4688092/17642552/cff5a982-6174-11e6-9dd7-56f113ee2be6.png)

**Comment by SamvelRaja** [comment] 2016-08-13 09:56
@gluons  Sorry to bug you again and again. we are just asking the command prompt screen shot. 
I would like you to launch the app through your command prompt and need to give the logs appears on the command prompt. Like this
![screenshot 1](https://cloud.githubusercontent.com/assets/5114052/17642616/36e7afb0-616a-11e6-956f-35103a95733c.png)

**Comment by gluons** [comment] 2016-08-13 10:10
OK. Here's from my cmd.

```
C:\Users\saran\AppData\Local\Postman\app-4.5.1>Postman.exe

C:\Users\saran\AppData\Local\Postman\app-4.5.1>
Reading C:\Users\saran\AppData\Roaming\Google\Chrome\Default\Extensions\fmkadmapgofadopljbjfkapdkoienihi\0.14.11_0\manifest.json failed.
Error: ENOENT: no such file or directory, open 'C:\Users\saran\AppData\Roaming\Google\Chrome\Default\Extensions\fmkadmapgofadopljbjfkapdkoienihi\0.14.11_0\manifest.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:426:29)
    at getManifestFromPath (C:\Users\saran\AppData\Local\Postman\app-4.5.1\resources\electron.asar\browser\chrome-extension.js:33:26)
    at Function.BrowserWindow.addDevToolsExtension (C:\Users\saran\AppData\Local\Postman\app-4.5.1\resources\electron.asar\browser\chrome-extension.js:353:22)
    at Object.attachDevToolsExtensions (C:\Users\saran\AppData\Local\Postman\app-4.5.1\resources\app.asar\background-modules\windowManager.js:111:21)
    at Object.newRequesterWindow (C:\Users\saran\AppData\Local\Postman\app-4.5.1\resources\app.asar\background-modules\windowManager.js:149:11)
    at EventEmitter.<anonymous> (C:\Users\saran\AppData\Local\Postman\app-4.5.1\resources\app.asar\main.js:402:28)
Couldn't add React DevTools. Expecting ReactDevTools at C:\Users\saran\AppData\Roaming\Google\Chrome\Default\Extensions\fmkadmapgofadopljbjfkapdkoienihi\0.14.11_0
Couldn't add Devtron DevTools
Window loaded (id: 1). Primary Window id:  1
```

~~_no need to blur anymore_~~ :grinning:

**Comment by SamvelRaja** [comment] 2016-08-13 10:16
@gluons  thank you so much.. We will look into it and get back to you in some time.

**Comment by SamvelRaja** [comment] 2016-08-15 15:35
Hey, @gluons we tried reproducing the same from our end and it is working properly, could you please open dev-tools on the blank window and give us the value of `window.location.pathname` ?

**Comment by gluons** [comment] 2016-08-15 15:42
![default](https://cloud.githubusercontent.com/assets/4688092/17669874/979adb90-6339-11e6-874f-d28c328c0236.PNG)

**Comment by SamvelRaja** [comment] 2016-08-16 07:35
@gluons could you please uninstall the app and delete the `c:\Users\<User>\AppData\Local\Postman` folder. 
Then, download and install the latest `4.6.1` version. 
Also, kindly let us know if you face any problem while installing which would be much helpful for us to debug.

**Comment by gluons** [comment] 2016-08-17 02:05
I've uninstalled and deleted `c:\Users\<User>\AppData\Local\Postman` before reinstall new but still not work. still blank 😟 

```
C:\Users\saran\AppData\Local\Postman\app-4.6.1>Postman.exe

C:\Users\saran\AppData\Local\Postman\app-4.6.1>
Failed to load window state: requester
Reading C:\Users\saran\AppData\Roaming\Google\Chrome\Default\Extensions\fmkadmapgofadopljbjfkapdkoienihi\0.14.11_0\manifest.json failed.
Error: ENOENT: no such file or directory, open 'C:\Users\saran\AppData\Roaming\Google\Chrome\Default\Extensions\fmkadmapgofadopljbjfkapdkoienihi\0.14.11_0\manifest.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:167:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:500:29)
    at getManifestFromPath (C:\Users\saran\AppData\Local\Postman\app-4.6.1\resources\electron.asar\browser\chrome-extension.js:33:26)
    at Function.BrowserWindow.addDevToolsExtension (C:\Users\saran\AppData\Local\Postman\app-4.6.1\resources\electron.asar\browser\chrome-extension.js:363:22)
    at Object.attachDevToolsExtensions (C:\Users\saran\AppData\Local\Postman\app-4.6.1\resources\app.asar\background-modules\windowManager.js:108:21)
    at loadWindowState (C:\Users\saran\AppData\Local\Postman\app-4.6.1\resources\app.asar\background-modules\windowManager.js:200:12)
    at Storage.get (C:\Users\saran\AppData\Local\Postman\app-4.6.1\resources\app.asar\background-modules\windowManager.js:144:16)
React Devtools Error:  ENOENT: no such file or directory, open 'C:\Users\saran\AppData\Roaming\Google\Chrome\Default\Extensions\fmkadmapgofadopljbjfkapdkoienihi\0.14.11_0\manifest.json' , Path:  C:\Users\saran\AppData\Roaming\Google\Chrome\Default\Extensions\fmkadmapgofadopljbjfkapdkoienihi\0.14.11_0
Devtron DevTools Error:  Cannot find module 'devtron'
Window loaded (id: 1). Primary Window id:  1
```

_I've tried on other laptop with Windows 10. It not work too._

**Comment by SamvelRaja** [comment] 2016-08-18 10:32
@gluons  Thank you so much for your patience, 
Seems like an process environment issue. 
can you type `set process.env.NODE_ENV` in your command line and ensure it is not **development** ?

_If that is the case, then kindly make sure it is not *development*._

**Comment by SamvelRaja** [comment] 2016-08-18 10:46
@gluons  Thank you so much for your patience, 
Seems like a process environment issue. can you make sure your NODE_ENV is **not development** system wise
you can find it under   _System properties -> Advanced -> Environment Variables_

<img width="818" alt="screen shot 2016-08-18 at 4 12 12 pm" src="https://cloud.githubusercontent.com/assets/5114052/17771080/eb845322-655e-11e6-89b0-47ef4b2dc5fc.png">

**Comment by Jeff-Lewis** [comment] 2016-08-18 19:00
Removing NODE_ENV=development works. Are you guys going to remove this dependency in the distributed app?

In the meantime, for those that keep NODE_ENV=development set on their machines, you can update your shortcut to Postman to clear NODE_ENV just when Postman runs.

```
cmd.exe /c "set NODE_ENV= & C:\Users\<your win account>\AppData\Local\Postman\Update.exe --processStart Postman.exe"
```

**Comment by numaanashraf** [comment] 2016-08-18 19:24
@Jeff-Lewis Yup. We are removing this dependency on `NODE_ENV` in version `4.6.2` which should be available within a day or two.

**Comment by SamvelRaja** [comment] 2016-08-18 21:27
@Jeff-Lewis  @gluons we released our `4.6.2` version which had the fix for removing the `process.env.NODE_ENV` dependency.
Kindly make sure this from your end.

**Comment by gluons** [comment] 2016-08-19 02:43
@SamvelRaja OK, It work!

I'm using `NODE_ENV` as dev. I can't remove it. You save me. Thank you very much. 😃 

<img width="954" alt="default" src="https://cloud.githubusercontent.com/assets/4688092/17797188/3de68fc6-65f1-11e6-8d20-69c998aa9fd2.PNG">

**Comment by SamvelRaja** [comment] 2016-08-19 05:49
@gluons Thank you so much for your patience while debugging the root cause 👍

**Comment by Arijit1234** [comment] 2017-09-22 00:01
Hi , 
I just installed postman last week. It was working when I installed but stopped working from second day. The post will load the UI when I start it but within 2 min, it turn into a white screen. I am using Windows 10, i7, 16 GB ram.
![image](https://user-images.githubusercontent.com/32181945/30723802-f72b21c0-9f7c-11e7-961d-9f54be0b39a8.png)
![image](https://user-images.githubusercontent.com/32181945/30723815-08bfbd38-9f7d-11e7-9e61-537cf0b48036.png)

regards, 
Arijit

**Comment by KevinvdBurg** [comment] 2017-10-27 07:30
I still got a whitescreen on the native app. The chrome app is fine. I'm using Windows 10 (fall creators update), Intel Core i7-2760QM 2.40GHz. 16gb ram, 64bit. 

Native:
![Native](https://user-images.githubusercontent.com/4567644/32092539-56ee7980-baf9-11e7-928e-eed2f94aaf00.PNG)

Chrome:
![Chrome](https://user-images.githubusercontent.com/4567644/32092551-6049b8aa-baf9-11e7-86fd-e60bca64c34d.PNG)

**Comment by SamvelRaja** [comment] 2017-10-27 07:41
@KevinvdBurg  By any chance, you are running ia32bit version on your 64bit OS?

**Comment by nkpaladugu** [comment] 2017-10-29 05:11
I have same issue on windows 7 32 bit, installed postman v5.3.2.. On opening, its just turned into a white screen.

**Comment by KevinvdBurg** [comment] 2017-11-03 08:07
@SamvelRaja no I downloaded the 64bit version

**Comment by KevinvdBurg** [comment] 2017-11-29 09:17
Almost a month has past and this issue is still not fixed.  I had contact with the support team but it keeps telling to starts postman from the Command Line (what I did). 
![2017-11-17 08_54_35-command prompt](https://user-images.githubusercontent.com/4567644/33367316-60823bda-d4ee-11e7-90b6-910730b58ce1.png)

What I found is that if I click and drag on the postman screen it exactly drags something. No clue what this means.
![2017-11-17 08_56_30-postman](https://user-images.githubusercontent.com/4567644/33367323-6a3a5e5a-d4ee-11e7-81d8-c2853765cda6.png)

**Comment by razikallayi** [comment] 2018-01-29 07:36
Same blank screen issue for me too.
Postman version: 5.5.2
Windows 10 64bit Os

![image](https://user-images.githubusercontent.com/11429908/35498623-144c908a-04f5-11e8-89be-bc1eb0300381.png)
![image](https://user-images.githubusercontent.com/11429908/35498670-43283706-04f5-11e8-84aa-84b5e25581f4.png)


The problem is with windows app. I have tried reinstalling the windows app. 
But chrome app is working almost fine with the deprecation message and with reduced features.

**Comment by KevinvdBurg** [comment] 2018-01-29 11:13
I can confirm that the app still shows a blank screen. The issue at the postman issue tracker is therefore still open.

**Comment by erdemkose** [comment] 2018-05-07 11:32
I also had the same issue with the native windows app.

My laptop has two graphics cards:
- nVidia Quadro 2000M (Default)
- Intel HD Graphics

When I switch to Intel, Postman works; otherwise it is just a blank window.

![image](https://user-images.githubusercontent.com/4168527/39699742-22ac93d6-5203-11e8-8c2d-69d4dac72cde.png)

**Comment by davutg** [comment] 2018-05-19 20:59
Postman is an indispensable tool for me, but I'm in trouble with updates.
This occured for me again after another update today.I'll think twice for further updates. I previously migrated from Chrome extension edition and it was also hard for me. This time I just clicked update and lost it again. 

Windows 8.1 64 bit,
Downloaded the latest version, 6.1.2
Updated shortcut's "Start In" directory manually because it was searching for 4.x previous version.

Black/Gray or White screen appears , many postman.exe processes seen in task manager and i7 CPU had some hard time without a result.  For further updates I'll consider re-installation instead of update.

**Comment by teebu** [comment] 2018-05-21 22:15
just updated postman, Windows 8.1, 64 bit. the standalone version.

![image](https://user-images.githubusercontent.com/5531844/40332675-b56a83c0-5d09-11e8-832d-68f9cf7eec0b.png)

Blank screen. I can somewhat interact with the menus. 

The Chrome App works.

**Comment by orck-adrouin** [comment] 2018-05-22 16:59
I has the same issue as @teebu on Windows 2012r2 64 bits.  I was able to work around the issue by setting compatibility mode on postman.exe to Windows7.

**Comment by dmarkowicz96** [comment] 2018-05-23 07:09
Same problem here. 'Troubleshoot compatibility' has resolved issue. (Windows 8.1 PRO)

**Comment by gustafl** [comment] 2018-05-27 17:50
I'm on Windows 8.1, and just encountered this problem too after updating to version 6.1.3.  Uninstalled, removed the Postman folder in `AppData`, downloaded the latest version again, but still the same. Running it from the console gives no clue:

    C:\Users\Gustaf\AppData\Local\Postman\app-6.1.3>
    ORM initialization successful
    App events bus { name: 'booted', namespace: 'shared' }
    App updater event { name: 'checkForElectronVersionUpdated',
    namespace: 'appUpdate' }
    App events bus { name: 'booted', namespace: 'requester' }

Thanks to @dmarkowicz96 for the compatibility tip. Running `Postman.exe` in Windows 7 compatibility mode solved it for me.

**Comment by samizzo** [comment] 2018-05-29 05:52
I'm seeing this too. This is all I see in my console when I start postman:

```
C:\Users\izzo\AppData\Local\Postman\app-6.1.3>
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App updater event { name: 'checkForElectronVersionUpdated',
  namespace: 'appUpdate' }
App events bus { name: 'booted', namespace: 'requester' }
```

**Comment by eMarv** [comment] 2018-05-30 14:42
@dmarkowicz96 's solution worked. Thanks! I am also on the same version of Windows.

For those who don't know, you can do this by:

1. Finding your Postman.exe file, which for me was in C:\Users\<username>\AppData\Local\Postman\app-6.1.3
   a. replace <username> with your actual username
2. Right click on Postman.exe 
3. Click on Troubleshoot Compatitility
4. Follow the instructions in the prompts

**Comment by oomaks** [comment] 2018-06-01 07:19
I'm developing an electron app and have the same 'blank screen' problem as Postman 6.13. Have any one know why this happens. Why @dmarkowicz96 and @erdemkose 's solution works?

**Comment by iamthevoid** [comment] 2018-06-06 10:58
@eMarv A lot of thanks and lot of love !!! )) You saved my day

**Comment by eatinasandwich** [comment] 2018-06-11 16:19
Was having this issue on Windows Server 2012 R2. Troubleshoot compatiblity worked for me too but I had to do it a second time this morning for some reason. Would be nice to have a better fix for this so it doesn't randomly occur.

**Comment by DaDude** [comment] 2018-06-28 12:15
My guess is it's related to old graphics drivers or hardware.
My console on an old i5-3330 with intel hd graphics 2500 (which doesn't get driver updates anymore afaik) get's flooded with gles-Errors like this:
`[14360:0628/140113.099:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-000
00045D444E370]RENDER WARNING: texture bound to texture unit 0 is not renderable.
 It maybe non-power-of-2 and have incompatible texture filtering.`
I think compatibility mode disables some graphics features so it will work fine.
Don't know if this help narrowing it down but i got this with several electron apps (e.g. Mattermost) on this old computer.
Also, the app is "usable" except for being blank. You can still see the cursor change when you hover the (invisible) new button on the top.

**Comment by SamvelRaja** [comment] 2018-06-28 14:52
All, I would recommend you guys to try the solution provided [here ](https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621)to resolve this. We figured out that on certain GPU's the app is not rendering.

**Closed as completed** 2018-06-29 06:48 UTC
Labels: bug

**Comment by Rostanxd** [comment] 2018-07-08 17:31
@dmarkowicz96 ty so much!!... 'Troubleshoot compatibility' , it worked for me. I have Windows 8.1.

**Comment by monGanti** [comment] 2018-09-20 20:05
same here 'Troubleshoot compatibility' works, i installed 6.3.0 version on windows 8.1 and i got the blank screen. Following the instructions here helped.

**Comment by AnsurM** [comment] 2019-01-22 22:31
What I did to solve my issue is as follows:

Went to:

"C:\Users\Ansur\AppData\Local\Postman\app-6.7.1" (that is where my postman.exe is installed, not update.exe).

Right click, open Properties>Compatibility tab> 
Tick "Disable Display Scaling on High DPI Settings" 
and 
Tick "Run this program as administrator",

And I got my display back and app working fully.

Thanks!

**Comment by jzapantis** [comment] 2019-05-07 06:12
Im using Windows 8.1 PRO, and Postman 7.0.9 - had a blank screen.

@eMarv @dmarkowicz96 @orck-adrouin 
Thanks the solution worked for me. Weird - I hope running it in Windows 7 doesnt lead to loss of features or issues updating, but happy to have it running on my machine. 

Thanks!

**Comment by kapakym** [comment] 2022-03-17 20:26
Hello. White screen
![image](https://user-images.githubusercontent.com/50634455/158889461-2b34ed0f-379d-48b9-bd8d-45584c0b8e78.png)

**Comment by giridharvc7** [comment] 2022-03-17 20:38
@kapakym Would you be willing to get on a call with us? Would really help us debug the issue deeper

**Comment by SimonK1323** [comment] 2022-03-17 21:33
![image](https://user-images.githubusercontent.com/77468460/158898625-b0d8d42f-ef3f-4f27-aa8b-38bdc1239345.png)
same here...cant even close the window :(

**Comment by numaanashraf** [comment] 2022-03-17 22:12
@SimonK1323 @kapakym We've identified the issue and we are tracking it at this issue - https://github.com/postmanlabs/postman-app-support/issues/10763#issuecomment-1071616594

Please follow the other thread for updates.
