### ISSUE TITLE
'An error occurred while running this request. Open DevTools for more info.' while running Collection Runner

### ISSUE THREAD

**Issue by AlexaTkachenko** [a85/POSTMan-Chrome-Extension#7667] opened 2019-11-18 21:09 UTC
**Describe the bug**
The Postman Runner doesn't run the Collection of requests. The Collection contains 285 requests. But only 20 of them were run due to error 'An error occurred while running this request. Open DevTools for more info.'
GET 
**Error:** read ECONNRESET
**Request Headers**
**Content-Type:** ""
**Authorization:** ""
**Request Body**
Type: "function PostmanQueryParam (options) {
        // this constructor is intended to inherit and as such the super constructor is required to be executed
        QueryParam.super_.apply(this, arguments);

        this.update(options);
    }"
_postman_listAllowsMultipleValues: true
_postman_listIndexKey: "key"
members: [0]
reference: {}

**Steps to reproduce the behavior:**
1. Create a big collection (more than 100 requests)
2. Open the Runner module
3. Choose a particular collection and environment
4. Click on 'Start Run' button
5. Look at the result

**Expected behavior**
All requests from the collection should be run

**Screenshots**

![Postman Console 2019-11-18 23 04 03](https://user-images.githubusercontent.com/17069390/69093789-e34b0b00-0a57-11ea-99d0-e59dd207388e.png)
![Collection Runner 2019-11-18 23 06 02](https://user-images.githubusercontent.com/17069390/69093923-23aa8900-0a58-11ea-99d8-41fe358bb404.png)

**App information (please complete the following information):**
 - App Type Postman for Windows
 - Postman Version 7.11.0
 - OS: win32 10.0.18362 / x64 Windows 10 Pro

**Comment by appurva21** [comment] 2019-11-19 12:00
Hey @AlexaTkachenko,

I couldn't reproduce the mentioned issue by following the steps suggested by you.
It would very helpful if you could share the collection that caused this issue or any other insights that might help us in reproducing the issue.

Thanks!!

**Comment by AlexaTkachenko** [comment] 2019-11-19 15:22
Hey @appurva21,

Thanks for your feedback, unfortunately, I can not share collection and environment that caused this issue due to the security point of view.  My collection contains 285 requests, and I have the Postman Plan.

Best regards,
Alexandra.

**Comment by AlexaTkachenko** [comment] 2019-11-19 15:24
And I have reached the monthly usage limits of my plan.
![Postman 2019-11-19 17 23 14](https://user-images.githubusercontent.com/17069390/69159951-5f456180-0af1-11ea-90f5-de5a207067ed.png)

**Comment by saswatds** [comment] 2019-11-28 08:02
@AlexaTkachenko It seems that there was some error when parsing the query parameters in your request  or your pre-request script errored out while updating the query parameters. 

Without any more details from your end we are completely shooting in the dark. It will be really helpful if you can provide some hints. Maybe with all secret values replaced.

**Comment by saswatds** [comment] 2020-03-09 22:40
Closing this issue as we are not able reproduce. Feel free to reopen issue if you can provide detailed steps to reproduce.

**Closed as completed by saswatds** 2020-03-09 22:40 UTC
Labels: bug, collection-runner, product/runtime
