### ISSUE TITLE
Collections Pane improvements

### ISSUE THREAD

**Issue by transome** [a85/POSTMan-Chrome-Extension#3625] opened 2017-10-11 20:14 UTC
It would be nice to have a collapse all button, and be able to have more than one level of hierarchy.

**Comment by prashantagarwal** [comment] 2017-10-12 07:32
@transome Are referring to the sidebar ?

**Comment by transome** [comment] 2017-10-12 14:00
Yes, the collections pane on the left side.

**Comment by mbuquet** [comment] 2017-10-12 15:13
I agree, I would love to have a "Collapse all collections/folders" button. I have a lot of collections and each with a lot of folders.

**Comment by prashantagarwal** [comment] 2017-10-16 07:33
@transome @mbuquet Cool, thanks for the suggestion.

**Comment by a85** [comment] 2017-12-23 19:09
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2657

**Closed as completed** 2017-12-23 19:09 UTC
Labels: sidebar

**Comment by DataTeamITInternal** [comment] 2018-03-21 01:45
The issue remains:

No way to Collapse "FOLDERS" in the collections pane.

You closed as duplicate however that ticket solved "TABS" not "FOLDERS"

Thanks
