### ISSUE TITLE
Visualize not working well in dark mode

### ISSUE THREAD

**Issue by sanghvian** [a85/POSTMan-Chrome-Extension#9726] opened 2021-03-14 11:05 UTC
**Describe the Issue**
Visualization of response not working in dark mode

**Steps to Reproduce**
Enable dark mode and try to visualize response hit at this example endpoint - postman-student-expert.glitch.me

**Screenshots or Videos**
![Screenshot from 2021-03-14 15-24-45](https://user-images.githubusercontent.com/69717009/111066020-e8508b00-84e2-11eb-945c-6b4924962dc5.png)

**Environment Information**

 - Platform Type: Linux
 - Postman Version: 7.36.5
 - Operating System: Ubuntu 20.0.4

**Additional Context**
I wish to contribute to this software so can you **please assign this issue to me**?

**Comment by DannyDainton** [comment] 2021-03-14 11:09
Closing as this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9505

**Closed as completed** 2021-03-14 11:10 UTC
Labels: duplicate
