### ISSUE TITLE
Application freezing on launch with black screen on Xubuntu 16.04

### ISSUE THREAD

**Issue by ScarellaDev** [a85/POSTMan-Chrome-Extension#5448] opened 2018-10-30 10:52 UTC
**Describe the bug**
Everytime I launch the application, it freezes and displays a black screen and I can't do anything.

To avoid that, I have to open the DevTools (Current view) which pauses the excecution before "potential out-of-memory crash".  The paused execution occurs 2 to 3 times and after that I'm good to go.

**To Reproduce**
1. Start the application

**Expected behavior**
No black screen.

**Screenshots**
I made an imgur album : [https://imgur.com/a/H9WLnmZ](https://imgur.com/a/H9WLnmZ)

**App information:**
- Postman for Linux
- Version 6.4.4
- linux 4.4.0-67-generic / x64
- My OS: Xubuntu 16.04

**Comment by numaanashraf** [comment] 2018-11-02 11:42
@ScarellaDev could you share your system specs, including CPU and RAM?

**Comment by ScarellaDev** [comment] 2018-11-05 10:49
@numaanashraf 

Here there are:
- **CPU:** Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
- **RAM:** 2x 8GB @ 1.6GHz

**Comment by ScarellaDev** [comment] 2018-11-09 15:31
I tried opening Postman alone, right after restarting my computer and it crashes too while I can have Webstorm & Chrome opened with 39 tabs pinned all day long without any problem.

**Comment by kamalaknn** [comment] 2019-11-06 09:02
Duplicate of #7078 

I'm closing this issue in favor of #7078 because the latter has more details and error logs.

**Closed as completed by kamalaknn** 2019-11-06 09:02 UTC
Labels: bug, performance, platform/linux
