### ISSUE TITLE
Add checkboxes to enable/disable parameters

### ISSUE THREAD

**Issue by maedox** [a85/POSTMan-Chrome-Extension#2519] opened 2016-12-05 09:32 UTC
For headers and form data there is a checkbox per line to enable/disable it. I would like to request the same feature for URL parameters.

 1. Postman Version: 

> 4.9.0
> linux / x86-64
> Chrome 55.0.2883.75

 2. Chrome App
 3. OS details: Ubuntu 16.10

**Comment by vivek201** [comment] 2017-03-09 06:23
Yeah, this would be really helpful.

**Comment by IllyaMoskvin** [comment] 2017-04-06 23:10
Dupe of #785, I think.

**Comment by a85** [comment] 2017-04-07 21:03
Closing as duplicate of #785

**Closed as completed** 2017-04-07 21:03 UTC
Labels: feature
