### ISSUE TITLE
Missing Collapse Arrow in Postman Extension

### ISSUE THREAD

**Issue by ClaytonFish** [a85/POSTMan-Chrome-Extension#13268] opened 2024-11-14 17:20 UTC
Type: <b>Bug</b>

I've re-installed various versions of this extension to see if the issue will get fixed with a different version of the extension, but every version has the same problem. 

Create a request and inside of the body of the request you set the payload type to "raw" then set the blue text dropdown to "JSON". Add some Json data to the window with 2 or 3 levels of key-value pairs. I used to be able to hover over the left side of the screen and it would show a drop down arrow for me to collapse levels of data that were huge. However this seems to have dissapeared. 

Also, the Beautify button in the top right also seems to have stopped working. It usually formats the data nicely, but now it doesn't do anything. It'll show the white dot indicating that something changed, but the payload itself doesn't look like it was formatted, or changed in any way.

Extension version: 1.2.1
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.14GB free)|
|Process Argv|--folder-uri vscode-remote://attached-container%2B7b22636f6e7461696e65724e616d65223a222f646570656e64656e63696573222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d/usr/dependencies --crash-reporter-id b9ebf363-4582-46ed-bc61-a4d5468dc4fc|
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|Container dependencies-dependencies (dependencies) @ desktop-linux|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 0)|
|Memory (System)|15.59GB (12.93GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container cloud-functions-cloud_functions (cloud-functions) @ desktop-linux|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 0)|
|Memory (System)|15.59GB (12.93GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31181874

```

</details>

**Comment by amaldinesh7** [comment] 2024-11-18 06:48
Duplicate of #13230

**Closed as completed by amaldinesh7** 2024-11-18 06:48 UTC
Labels: bug, vscode
