### ISSUE TITLE
Variable value is not imported

### ISSUE THREAD

**Issue by sebastien-savalle** [a85/POSTMan-Chrome-Extension#3318] opened 2017-07-28 08:17 UTC
When importing a collection which was recently exported, the variable value is no more imported. 

I have noticed that the json model has been changed. 
Previous model 
```
{
  "id": "project",
  "value": "postmanlabs"
}
```
New model
```
{
  "key": "project",
  "value": "postmanlabs"
}
```

The import of collection using older model is still working as expected and values are correctly fulfilled 

## App Details:

```
Postman for Windows
Version 5.1.2
win32 10.0.15063 / x64
```

## Issue Report:

 1. Create a collection and a request containing variables with values
 2. Export your collection
 3. Import the exported collection (or the attached one)
[Bug Export Duplicate  #Variables.postman_collection.zip](https://github.com/postmanlabs/postman-app-support/files/1182428/Bug.Export.Duplicate.Variables.postman_collection.zip)

 4. The request will be imported without values

Import of a collection with json variable using "key"
![image](https://user-images.githubusercontent.com/9685252/28708460-9d5b4d18-737c-11e7-9569-0d0dc409c514.png)

Import of a collection with json variable using "id"
![image](https://user-images.githubusercontent.com/9685252/28708500-c814e12c-737c-11e7-93ff-225ac75b9d6c.png)

**Comment by sdnts** [comment] 2017-07-31 12:02
Hi @ellavas, I think this is a duplicate of #3266. Can you take a look at that issue and confirm?
I'm closing this, but please let me know if your issue is different :)

**Closed as completed by sdnts** 2017-07-31 12:02 UTC
