### ISSUE TITLE
Environment does not work with Graphql requests (beta functionality)

### ISSUE THREAD

**Issue by HumidBrains** [a85/POSTMan-Chrome-Extension#13018] opened 2024-07-18 16:52 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

For some reason I cannot use the new graphql ui for making authenticated requests. It works making http requests, but I'd like to use the graphql explorer which isn't possible as the access token set in my environment doesn't seem to be used.

### Steps To Reproduce

1. Setup an environment, use it for http request to confirm that it works.
2. Try to make a graphql request with the beta UI for graphql. Result...`{
    "errors": [
        {
            "message": "",
            "extensions": {
                "code": "ACCESS_DENIED"
            }
        }
    ]
}`

### Operating System

macOS

### Postman Version

 11.4.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ronork** [comment] 2024-07-19 07:07
Hey  @HumidBrains, we were unable to reproduce the issue. Could you please provide more details on the authorization method you are using and where it is being set ? Additionally, could you confirm if the access token is being correctly updated in your environment and if there are any specific configurations in your setup that might affect the GraphQL request?

**Comment by HumidBrains** [comment] 2024-07-19 07:46
Hey @ronork my bad! I had misunderstood how to set the access token variable in the header. I simply thought that since I'd set the variables in the environment and it worked for the http requests, those variables would get picked up also on the graphql requests. But I had to set the headers again. Is that maybe related to the fact that there is no option to inherit from parent like in the http requests? Anyway, all good and sorry about the rookie mistake.

**Comment by ronork** [comment] 2024-07-19 07:53
No problem at all, glad to hear it's resolved! Closing this issue now.

**Closed as completed by ronork** 2024-07-19 07:53 UTC
Labels: protocol/graphql, product/api-client
