### ISSUE TITLE
file import via API

### ISSUE THREAD

**Issue by jarogers** [a85/POSTMan-Chrome-Extension#10385] opened 2021-10-21 00:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When attempting to import an exported file using the "Import exported data" documentation shown here:
https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a

the request fails with an 'invalidParamsError' indicating that the 'input' parameter is missing from the multi-form data...

Neither the documentation above nor the sample request shown here: https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-902c2d6e-eb59-49ec-8f6f-6bb1fa96f597
make any mention of this parameter.

Further when changing the 'file' parameter to 'input', a 'malformedRequestError' is returned indicating that the input must be a valid zip file.

Zipping the exported json and supplying that to the input parameter yields a 504 Gateway Time-out.

### Steps To Reproduce

Open new request
set headers for X-API-Key, X-Workspace-Id, Content-Type to multipart/form-data
create two body parameters with keys type, and file. where type is text with a value of file, and file is a file with a value of a json file exported from postman (say global variables for example)
send request
observe returned errors

### Environment Information

```markdown
- Operating System: MacOS 11.6
- Platform Type: Application and Web
- Postman Version: 9.1.1
```

**Comment by DannyDainton** [comment] 2022-06-30 10:48
Hey @jarogers 

I'm not really following what/where the issue is - Would you be able to expand on the information more and provide a copy of the failing file so that we can see this failing from our side, please?

I'm going to close this for now but if this is still an issue in the latest version of the platform we can reopen it again.

**Closed as completed** 2022-06-30 12:43 UTC
Labels: product/runtime
