### ISSUE TITLE
Postman python3 http.clent code generation problem

### ISSUE THREAD

**Issue by cirrusa** [a85/POSTMan-Chrome-Extension#6810] opened 2019-07-01 07:25 UTC
**Describe the bug**
When I generated the python3 http.clent code, the dot was replaced with a comma.

**To Reproduce**
When you click code to generate the code

**Screenshots**
![TIM截图20190701151754](https://user-images.githubusercontent.com/7261963/60417885-1b21f500-9c14-11e9-92ba-c6fde13b712e.jpg)

**App information (please complete the following information):**
- Postman for Windows
- Version 7.2.2
- win32 10.0.18362 / x64

**Comment by abhijitkane** [comment] 2019-07-08 05:27
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/5837

**Closed as completed by abhijitkane** 2019-07-08 05:27 UTC
