### ISSUE TITLE
Collection Variables not being decoded in code view.

### ISSUE THREAD

**Issue by dbkaynor** [a85/POSTMan-Chrome-Extension#4176] opened 2018-02-12 20:24 UTC
If variables are defined in the Manage enviroment tool the Code display will show the the replaced values. If the variable are defined as collection variables then they are not.

Postman v5.5.2 
Windows 10 64 bit

Body             <username>{{ServerUsername}}</username>
            <password>{{ServerPassword}}</password>
        </auth>
    </general>
    <request>
        <category>fundingmethod</category>
        <function>pull</function>
        <param> 
            <account>{{Account}}</account>

![manage enviroment tool](https://user-images.githubusercontent.com/1424275/36117684-6c456bd6-0fef-11e8-9a02-8554c4959852.JPG)

**Comment by numaanashraf** [comment] 2018-02-19 21:55
@dbkaynor Thanks for reporting this. Could you provide more information regarding this issue?

**Comment by dbkaynor** [comment] 2018-02-20 23:37
If I select an environment and then define variables in it they are substituted. For example, I have an environment called xsign and in it, a variable called {{TrackCode}} which is equal to AUS-AUB. 
The Builder window has a line 
<trackcode xsd:type="xsd:string">{{TrackCode}}</trackcode>.  
When I click on the Code link I see  
<trackcode xsd:type="xsd:string">AUS-AUB</trackcode>  which is expected. 

I set builder to No Environment and now I see {{TrackCode}} again.
Click on Collections ... edit/Variables and put in a key TrackCode and set it to something.  Click update and then click code again. {{TrackCode}} will be displayed and not whatever was entered. I have not tested Globals to see if the problem exits there.

**Comment by sivcan** [comment] 2018-03-21 07:36
Hi @dbkaynor - I can confirm that the issue no longer exists in the [latest postman app](https://www.getpostman.com/apps).
Kindly update to the same.

**Comment by dbkaynor** [comment] 2018-03-21 16:31
I just installed Postman-win64-6.0.10-Setup.exe and after doing so I still have the same problem. I created a collection "Bug test". In the collection is one test called "Test". Under the Bug test collection, I selected Edit/Variables and added three Keys,  NewAccount (12345), NewPassword (abcdef), and State (California). I then clicked Update and created a test with {{NewAccount}}, {{NewPassword}}, and {{State}} in it. When I click on the Code button the variables are not substituted in the Generate Code Snippets window. If I create and select an environment and define the variables in it they are substituted correctly.

Please view the attached files for more information.

![bugtest1](https://user-images.githubusercontent.com/1424275/37722523-78bdf402-2ce9-11e8-994b-1969cc356aa6.JPG)

![bugtest2](https://user-images.githubusercontent.com/1424275/37722650-cae7b434-2ce9-11e8-89c6-a9b954910f26.JPG)

![bugtest3](https://user-images.githubusercontent.com/1424275/37722943-6496b300-2cea-11e8-8647-e4da9499e72a.JPG)

**Comment by harryi3t** [comment] 2018-04-03 06:02
@dbkaynor I was able to reproduce this. Marking this as a bug.

**Comment by dbkaynor** [comment] 2018-06-26 19:04
I am using version 6.1.3 When is the fix for this problem going to be released? I makes my development difficult and a fix would be appreciated.

**Comment by kamalaknn** [comment] 2019-01-13 04:42
I just tried this out on the latest version 6.7.1 and it seems to be working.

I'm closing this issue. Please let us know if you're still seeing this issue.

**Closed as completed by kamalaknn** 2019-01-13 04:42 UTC
Labels: bug, code-generator
