### ISSUE TITLE
Allow body in GET requests

### ISSUE THREAD

**Issue by bashok001** [a85/POSTMan-Chrome-Extension#1481] opened 2015-10-06 01:56 UTC
With advent of elasticsearch REST API, there is a need for body in GET requests too. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html

They expect the query to be like:
 curl -XGET {endpoint}/_search -d '{
     "query" : {
         "term" : { "user": "kimchy" }
     }
 }'

Please add this functionality.

**Comment by abhijitkane** [comment] 2015-10-06 07:21
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1112 and https://github.com/postmanlabs/postman-app-support/issues/996

**Closed as completed by abhijitkane** 2015-10-06 07:21 UTC

**Comment by abhijitkane** [comment] 2016-02-01 15:55
@bashok001 
With v2.0 of Elasticsearch, you can send a POST request instead (Last line of https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-request-body.html)

**Comment by bashok001** [comment] 2016-02-01 18:48
Thanks @abhijitkane !
