### ISSUE TITLE
Bug with case sensitivity when inviting new users to postman pro

### ISSUE THREAD

**Issue by AquaHippie808** [a85/POSTMan-Chrome-Extension#7338] opened 2019-09-17 20:28 UTC
Bug with case sensitivity when inviting new users to postman pro

**Comment by asi-postman** [comment] 2019-09-17 20:38
**Describe the bug**
Bug with case sensitivity when inviting new users to postman pro

**To Reproduce**
A current user uses the postman app to recommend a use postman pro user using lower case.
Example: usera@example.com

An admin also invites the same user with an email address that is in a different case.
Example: userA@example.com

The result is that the invite from the admin will not work because there is a pending referral with the same email but a different case.

**Expected behavior**
Error prompt or modal detailing the error

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/52974659/65077710-365cf080-d937-11e9-9b91-d05f835a6e1a.png)

**Comment by abhijitkane** [comment] 2019-09-18 05:30
@asi-postman Can you explain the current behavior you're seeing? Is the admin unable to see the invite?

Even if you send an invite with the same email (in the same case), there will be no error message because we treat emails the same irrespective of case. We might have to re-look at this - some providers might respect case, some might not.

**Comment by JSSAggie** [comment] 2019-09-18 19:34
In the screen shot above another postman pro user invited that user by email with a lower case email address.

In the bottom section I am showing a user that was invited via the API.  We have a slack bot connected to the postman APIs that our company uses to request a postman pro license.

When the new user that was invited tries to accept the invitation it causes errors.  I don't know the specific error because I did not witness the error myself as it was reported to me.

To resolve the issue I deleted/rejected both invites and used the slack bot/api to invite the person again and everything worked.

This is not the first time we have seen this issue so I thought I would report it.

**Comment by debjeetsarkar** [comment] 2019-11-05 08:09
Hey @JSSAggie, I tried reproducing the mentioned scenario but didn't face any issue with both the flows:

* Approving the request to join the team.
* Using the email invitation to join the team. 

Are there any specific intermittent steps that you were performing and is not mentioned above?

Also, would you mind opening a ticket at help@getpostman.com if you're still facing the issue? :)

**Comment by DannyDainton** [comment] 2020-08-29 07:12
Hey @JSSAggie 

Is this still an issue for you in the latest version of the app - If not, could we look to close this issue out, please?

**Comment by DannyDainton** [comment] 2020-09-04 07:45
Closing out this issue - We can look to open it up again if the issue persists.

**Closed as completed by DannyDainton** 2020-09-04 07:45 UTC
Labels: bug, team-management
