### ISSUE TITLE
Postman native app keeps failing to open while logging in via SSO

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5509] opened 2018-11-09 05:54 UTC
Hello, I tried to use AD FS as our SSO login. We followed the instructions to set up on both Postman and our AD. When I tried to use the login URL, https://identity.getpostman.com/sso/adfs/$$$$$$$$$$$$$$/init, I received a 500 error. However, we figured out that we had imported an incorrect x.509 certificate. After correcting the x.509 certificate, we managed to login to Postman from our browsers. However, when tried to do the same from the Postman application, we are stuck to the attached screenshot after we attempted to login via SSO. 

![image](https://user-images.githubusercontent.com/40994626/48245640-e279a500-e411-11e8-98e8-0a974d57e769.png)

![image](https://user-images.githubusercontent.com/40994626/48390060-38a65b00-e726-11e8-967c-80c809702d85.png)

**Comment by elssar** [comment] 2018-11-12 07:22
@Ramya-From-Postman I'm having trouble reproducing this. It would help if you can provide the app version and platform you are using.

**Comment by abhijitkane** [comment] 2018-11-13 18:15
@elssar  v6.4.4 on Windows

**Comment by elssar** [comment] 2019-07-15 08:18
This looks like a case of a firewall or a proxy blocking the app from connecting to the IdP.

**Comment by elssar** [comment] 2019-07-24 08:05
Closing as this is a network problem.

**Closed as completed by elssar** 2019-07-24 08:05 UTC
Labels: bug, sso, launch
