### ISSUE TITLE
Run Collection - returns server error 500

### ISSUE THREAD

**Issue by GitHubHelps** [a85/POSTMan-Chrome-Extension#5615] opened 2018-12-06 13:31 UTC
**Describe the bug**
I have create POST method to upload file/image through Body - form-data - file. If i run the request like a singe request is totally OK, because we DON'T put image/file (see picture 2), but if I run the same request through collection runner I got server error 500 and all other test are terminated! (see picture 1)

**To Reproduce**
1. Go to postman and run POST method with Body - form-data - file.
2. Don't load file/image
3. Run the request
4. We got "400 Bad Request" (this is correct!)
5. Run the same request through Collection runner
6. The error now is "500 server error" and all other test are terminated!

**Expected behavior**
The error is "400 Bad Request" just like we push single request (picture 2)

**Screenshots**
![image](https://user-images.githubusercontent.com/45661012/49586872-0aa1e880-f96b-11e8-9195-b30dc0ce6bf7.png)
![image](https://user-images.githubusercontent.com/45661012/49586898-1d1c2200-f96b-11e8-8772-e24a9b81e68e.png)

**App information (please complete the following information):**
 - Postman app
 - Postman Version 6.5.3
 - OS: Windows 10 Enterprise

**Comment by sivcan** [comment] 2018-12-06 18:10
Hi @GitHubHelps, the issue is that we do not store file path's in the app due to security reasons.
So, in the runner the file paths don't work for now.
But we'll be building upon a better way to solve this problem.

Here's more info explaining the issue of storing file paths in the app: https://github.com/postmanlabs/postman-app-support/issues/4824#issuecomment-409548624

You can follow the thread above and it refers #4320  ticket, which aims to solve the problems of file path storage in the app.

I regret the inconvenience caused.
I'll be closing this issue since we're tracking the file path issue already.
Kindly follow the above mentioned thread for updates.

Thank you!

**Closed as completed by sivcan** 2018-12-06 18:10 UTC
