### ISSUE TITLE
Severe Data Loss when Moving Folder into Another Folder

### ISSUE THREAD

**Issue by markusthegeek** [a85/POSTMan-Chrome-Extension#6448] opened 2019-05-08 17:09 UTC
**Describe the bug**
When moving a folder into another folder, sometimes the UI does not show the result immediately. When repeating the action, you can get into a state where the whole test suite shows up as empty. This happened twice to me yesterday.

**To Reproduce**
1. Have to collections with at two levels of folders
2. Make a duplicate of one of the sub folders containing test cases; see Trials - Samples - Cancel during Trial Copy below
3. Drag the copy folder to the other collection top folder and drop, see Instruments folder below
4. UI will take 5 seconds or so to update
5. If you repeatedly drag and drop now you can end up with an empty target collection

**Expected behavior**
Folder should appear within the target folder and the end of the target folder content.

**Screenshots**
![image](https://user-images.githubusercontent.com/1049733/57393967-1e9b8180-7179-11e9-9d18-3425dac1e8d1.png)

**App information (please complete the following information):**
 - Native App
 - 6.7.4
 - macOS Mojave 10.14.2

**Additional context**
Note that there is another bug that the folder will only be copied inside the target folder if that folder is closed; otherwise it will appear next to the target folder.

**Comment by abhijitkane** [comment] 2019-05-13 04:52
@markusthegeek I was able to reproduce the second issue (folder transfer is incorrect it the target folder is open), but not the first.

Would it be possible for you to attach a screen recording?

**Comment by markusthegeek** [comment] 2019-05-13 19:24
@abhijitkane, great idea, I was able to catch the bug during the recording, using a copy of my original target collection. I am following the same steps as laid out above. Note that my Postman is sometimes really slow although I did restart it just before these tests. So Postman Helper might use > 100% CPU and the sync button might not react. An indication is that it might take a while until that copy of the test folder was created. This might help you to reproduce this issue since the key seems to be that I am able to keep dragging and dropping the folder into the target collection folder multiple times.

[PostmanDataLossSmall.mov.zip](https://github.com/postmanlabs/postman-app-support/files/3174441/PostmanDataLossSmall.mov.zip)

**Comment by sujayvenaik** [comment] 2019-05-13 19:45
Hey @markusthegeek 
One reason for you able to drag-drop the collection multiple times is when this operation is made, it may judge it as 1. you are trying to reorder i.e. moving behind the folder which I guess would be happening in your case, 2. moving inside the folder and 3. moving it after the folder.

I tried reproducing the case where I moved folders in nested folders but could not reproduce the folder going away case. Is it happening for a specific folder case or happening for every move?

**Comment by markusthegeek** [comment] 2019-05-13 19:49
@sujayvenaik, I only had it happen recently with that specific case, but I also lost two folders in another transaction which I am no longer sure what was involved. So it could be related to having several folders inside each other, having a certain amount of test requests per collection, and having the system under load like I mentioned above. These all seem to be conditions I am hitting in that recent test collection. Do you have access to my test collections and could import them into your test system?

**Comment by sujayvenaik** [comment] 2019-05-15 07:41
Hey, @markusthegeek Can you help us by exporting the collection for which you are facing issues and mail it to help@getpostman.com?
Redact any sensitive information.

**Comment by markusthegeek** [comment] 2019-05-15 17:02
Hi @sujayvenaik, that was my idea as well :-) I replaced our passwords and sent the JSON exports of the two collections involved to support now, mentioned this bug and your email. Let me know if you want to do a shared screen session. gruss, Markus

**Comment by sujayvenaik** [comment] 2019-05-16 12:35
Hey @markusthegeek 
The collections you sent, I tried replicating the issue by following the screencast that you had sent.
But could not reproduce. Might be that the collection got malformed.

**Comment by markusthegeek** [comment] 2019-05-16 16:49
@sujayvenaik, I used the very same collections in my screen recording so the malforming happened after the bug hit ;-) I did notice that my Postman Helper used like 110% CPU and that when clicking the Sync button in the header nothing happened for like 5 seconds. So maybe you can disconnect yourself from the server or throttle your network connection to slow down your system? Or open like 50 Chrome tabs lol

But mostly it is probably the local load since you can still work offline?

In essence I think you need to somehow prevent your UI to do further drag and drops with folders or collections while another transaction is already started on that same item. is that possible?

**Comment by DannyDainton** [comment] 2020-06-26 12:46
Hey @markusthegeek 

Is this an issue that you're still facing with the latest native app version?

**Comment by mccannt** [comment] 2020-08-25 23:00
Closing this. If this is still an issue with the latest version of the application, please feel free to reopen.

**Closed as completed by mccannt** 2020-08-25 23:00 UTC
Labels: bug
