### ISSUE TITLE
Creating a new collection gets removed automatically if the App was in syncing state

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#5402] opened 2018-10-22 13:42 UTC
**Describe the bug**
When App is in syncing state, creating new collections or environments get removed automatically. This only happens only the first time after opening the App.

**To Reproduce**
1. have a team workspace shared with another member
2. quit your app in that team workspace (so that next time it will open in that workspace)
3. ask your team member to create some collections with multiple requests (the more, the better the chances of reproducing the issue)
4. open your app and create a new collection
5. After syncing is finished, not able to see other collections

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 6.4.4

**Additional context**

**Comment by kamalaknn** [comment] 2019-03-26 09:25
@harryi3t Duplicate of #5255

**Closed as completed by kamalaknn** 2019-03-26 09:25 UTC
Labels: bug, sync, postman-data
