### ISSUE TITLE
POSTMAN not returning correct content-length header for range request.

### ISSUE THREAD

**Issue by bhadkeYD** [a85/POSTMan-Chrome-Extension#4074] opened 2018-01-17 14:45 UTC
## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Yes
 2. Expected behaviour: content-length header should return proper value.
 3. Console logs (had some issue while getting logs)
 4. Screenshots (if applicable)
![postmanissue](https://user-images.githubusercontent.com/35532024/35048103-1c2405ae-fbc2-11e7-8f40-d4f7be93c1a9.png)

**Comment by numaanashraf** [comment] 2018-01-18 08:20
@bhadkeYD Thanks for writing in. Could you provide us version details of your OS, Postman App and (Chrome browser, if using the Chrome app)?

**Comment by bhadkeYD** [comment] 2018-01-18 08:23
Postman for Chrome
Version 5.4.0
win / x86-64
Chrome 63.0.3239.132

**Comment by prashantagarwal** [comment] 2018-03-20 17:51
@bhadkeYD Can you download native Postman app and try to reproduce this. We are soon deprecating Chrome apps.

**Comment by bhadkeYD** [comment] 2018-03-20 18:06
@prashantagarwal Have you checked whether problem is reproducible or not ? I'm able to reproduce on issue Postman App

**Comment by codenirvana** [comment] 2019-02-21 11:56
@bhadkeYD This looks like an issue with the requesting server.
The server is responsible to respect the range provided by the client and send the partial response.

Example: You can test a range request on `http://i.imgur.com/z4d4kWk.jpg`
![screenshot 2019-02-21 at 5 14 54 pm](https://user-images.githubusercontent.com/4865836/53166925-90ddda80-35fc-11e9-92c4-5fe853178943.png)

Closing this issue, Please feel free to re-open if the issue persists.

**Closed as completed by codenirvana** 2019-02-21 11:56 UTC
Labels: bug

**Comment by bhadkeYD** [comment] 2019-02-22 12:16
I did checked at that time, issue was not with server but the way content-length is returned incorrectly.
I have verified with new postman build that content-length is returning properly somehow I think this may been fixed with other code push
