### ISSUE TITLE
Window turns black in i3-wm

### ISSUE THREAD

**Issue by xhalo32** [a85/POSTMan-Chrome-Extension#4913] opened 2018-07-28 17:41 UTC
**Describe the bug**
The window except for the menu bar turns black

**To Reproduce**
1. Open postman
2. Click on `Pre-request Script` (or any other "tab" except for Authorization)
3. Move your mouse to another i3 workspace
4. Move your mouse back to postman

**Expected behavior**
I expect for the window to not turn completely black

**Screenshots**
- Opened postman
![image](https://user-images.githubusercontent.com/15152190/43359143-7897cbb0-92a6-11e8-96b7-64109b419172.png)
- Clicked on `Pre-request Script`
![image](https://user-images.githubusercontent.com/15152190/43359155-8df4cf26-92a6-11e8-821c-9cb27847cf73.png)
- After doing something like changing workspaces and changing back
![image](https://user-images.githubusercontent.com/15152190/43359158-9746eba4-92a6-11e8-851a-61d2aed6119a.png)

**App information**
 - Native App
 - Postman Version 6.1.4
 - OS: 4.17.4-1-ARCH x86_64 GNU/Linux
```
Postman for Linux
Version 6.1.4
linux 4.17.4-1-ARCH / x64
```

**Additional context**
The bug happens upon switching to any "tab" other than `Authorization`.

If I switch back to `Authorization`, the bug doesn't happen.

I'm running `i3 version 4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors`

**Comment by numaanashraf** [comment] 2018-08-02 15:15
Duplicate of #4764

**Closed as completed by numaanashraf** 2018-08-02 15:15 UTC
Labels: bug
