### ISSUE TITLE
Collection Runner not using data file variables and not setting token environment variable

### ISSUE THREAD

**Issue by msmithmis** [a85/POSTMan-Chrome-Extension#2804] opened 2017-03-14 04:12 UTC
1. Postman Version: Version 4.10.3  win / x86-64
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows10
 4. Is the Interceptor on and enabled in the app: yes
 5. Did you encounter this recently, or has this bug always been there: I've only started using collection runner recently, but the problem has always been there for that time.
 6. Expected behaviour: Collection Runner should run tests the same as when running them individually.  First test should get token via OAuth and set the token to environment variable, and the other tests should use that token.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:
All the tests pass when I run them individually, but when I run them from collection runner, I get 401 UnAuthorized.  The first test creates the token and assigns it to an environment variable. `postman.setEnvironmentVariable("token_user", jsonData.access_token);`  
It seems that the rest of the api calls are not getting the new token and are failing.   It almost appears like the tests are not getting the values from the CSV data file also.  (It previews fine).  The tests seem to be running off the saved environment variables only and not the ones imported in the CSV.  Then, when the iteration runs, the new values from token are not overriding the enviro variables. (Note:JSON data file has same issue).

![image](https://cloud.githubusercontent.com/assets/13390776/23885309/64011862-082f-11e7-8275-fda515d0a2f9.png)

**Comment by sdnts** [comment] 2017-03-16 11:00
@msmithmis Thanks for reporting this. Unfortunately, I was unable to reproduce this.
There's only one issue I can think if that might be causing your problem. The Runner on the Chrome app does not reflect changes in a collection in real time. If you added the `setEnvironmentVariable` line later, it might not be reflected. Closing and opening the runner again should fix this.

However, if it does not, would it be possible for you to open up the Chrome DevTools ([this](http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/) should help), switch over to the Network tab and see if the requests being sent are correct (by that I mean if the expected headers are sent, the URL is correctly resolved etc.)

Have you also tried the [native apps](https://getpostman.com/apps)? It has a redesigned Runner that will allow you to see the request URL and body as it is sent so you can investigate this easier. Since Google will discontinue Chrome apps this July, I'd recommend shifting anyway.

Do let me know what you find.

**Comment by SamvelRaja** [comment] 2017-09-06 12:32
Since there is no activity in this issue, we are closing this now, feel free to reopen it if needed.

**Closed as completed by SamvelRaja** 2017-09-06 12:32 UTC

**Comment by apoorvaagrawal86** [comment] 2018-01-19 07:43
Postman Version: Postman v5.5.0
    App (Chrome app or Mac app): Native app for Windows
    OS details: Windows10
    Is the Interceptor on and enabled in the app: NA
    Did you encounter this recently, or has this bug always been there: I've only started using collection runner recently, but the problem has always been there for that time.
    Expected behaviour: Collection Runner should run tests the same as when running them individually. 
    Console logs NA
    Screenshots (if applicable)




Hello, 

I am facing a similar issue while using postman collection runner,
In my case, the scripts fail in the 3rd iteration giving 401 unauthorized error.
I am using the native app for postman.
I have specified the environment variables for the authorization headers and the URL.

Please find the screenshot below - 

![image](https://user-images.githubusercontent.com/34733289/35139725-6ad49c82-fd1a-11e7-86cc-10b02d8c1d78.png)

Let me know in case you need any more information.
