### ISSUE TITLE
Export collection containing gRPC Requests

### ISSUE THREAD

**Issue by adimoi** [a85/POSTMan-Chrome-Extension#11579] opened 2022-12-21 13:16 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

The inability to export the collection containing the gRPC requests prevents me for saving the collection into the code repository.

### Describe the solution you'd like

The solution should be identical with the one implemented for the REST API Collection, which is right-click on the collection and then select the Export option.
![Export REST API Collection](https://user-images.githubusercontent.com/11740004/208913665-a406a7d2-d9b2-494e-b154-6fb0a02ccf45.png)

**Comment by chisty-care** [comment] 2022-12-22 16:50
Yup! it will be really helpful if we can export the grpc collection.

**Comment by appurva21** [comment] 2023-01-04 08:08
@adimoi @chisty-care Thanks for writing in! 

Can you share your workflows with the exported collection on this [thread](https://github.com/postmanlabs/postman-app-support/issues/11252)?

------
Closing this as a duplicate of #11252

**Closed as completed by appurva21** 2023-01-04 08:08 UTC
Labels: feature, protocol/grpc, product/api-client
