### ISSUE TITLE
Requests are not loaded when there are large number of heavy requests saved

### ISSUE THREAD

**Issue by TheAllThing** [a85/POSTMan-Chrome-Extension#4297] opened 2018-03-07 18:06 UTC
```
Postman for Windows
Version 6.0.9
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently, after updating to build 6.0.9
 2. Expected behavior: When opening the PM app, all collections should have their requests under the respective folders.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): NA
 4. Screenshots (if applicable)

1. Close PM.
2. Open PM. Upon opening, all folders under all collections show the "This folder is empty" message. Leaving the app open for an extended period of time does not help.
3. Log out of PM.
4. Log in. After logging in, the app quickly syncs and all requests are available.

<!--

**Comment by thecuriousdev** [comment] 2018-03-08 12:05
@TheAllThing thanks for reporting this issue. Please help me with this, What was the sync status during that time? (you can find it in the top bar of the app)

**Comment by TheAllThing** [comment] 2018-03-08 16:27
Hi @thecuriousdev, the status showed that it was syncing (blue) for a minute, then it changed to orange. When logging out/in, it shows that it is syncing, but the requests do actually return after awhile. Our team workspace has a lot of collections/requests.

**Comment by thecuriousdev** [comment] 2018-03-09 05:58
The status SYNCING means the app is syncing with the server to keep all your data up to date, and it may take some time depends on how much data you have. Once the status changed to IN-SYNC you can access all of your data. So I think in your case, nothing is unusual, it's the expected behavior. Hence I am closing the ticket, for now. But feel free to continue the discussion.

**Comment by TheAllThing** [comment] 2018-03-09 16:10
@thecuriousdev, we are not on the same page. This cannot be expected behavior. Every time the app is closed, the next time it is opened, all requests are missing, and all folders under every collection show "this folder is empty." We can wait all day and nothing will change. The only way to resolve this is to log out of the desktop application, and upon logging back in, it successfully syncs and requests are populated.

**Comment by TheAllThing** [comment] 2018-03-13 01:18
@thecuriousdev , if you could let me know what I have to do to get this more attention, I'd appreciate it. This was closed prematurely, and there is no clear direction for where I need to go from here. Do I need to open a brand new ticket for the same issue?

**Comment by kamalaknn** [comment] 2018-03-13 03:24
Hi @TheAllThing,

Sorry for the initial misunderstanding. This looks like the view is partially rendering the data. We will definitely investigate this, but we need your help. Please give us these additional data so we can triage this better.

1. Are you seeing the collections as empty every time you restart the app?
2. Are requests missing for all the collections or only a few of them?
3. Do you see any errors in the DevTools `View -> Developer -> Show DevTools(Shared)` and `View -> Developer -> Show DevTools(Current View)`

Additional details that might help us,

1. Export the logs in both the developer tools(Right Click -> Save As). Please send these to hel[at]getpostman.com as this might include some of your sensitive data.
2. A screencast reproducing this issue.

Thanks

**Comment by TheAllThing** [comment] 2018-03-14 18:28
Hello @kamalaknn. Thanks for the response.

1. Are you seeing the collections as empty every time you restart the app?
   1. Yes.
1. Are requests missing for all the collections or only a few of them?
   1. All requests are missing.
1. Do you see any errors in the DevTools View -> Developer -> Show DevTools(Shared) and View -> Developer -> Show DevTools(Current View)
   1. There are several. One in particular looks suspect (below). I'll send the logs to the email address mentioned above.
      1. Could not find on CollectionStore. Missing or invalid parameter.

Can you confirm that the email is hel[at]getpostman.com, or is it supposed to be help[at]getpostman.com?

**Comment by kamalaknn** [comment] 2018-03-15 07:03
@TheAllThing 

My bad, our support email is `help[at]getpostman.com`. Please forward the logs to this email.

**Comment by TheAllThing** [comment] 2018-03-15 16:45
Thanks, @kamalaknn . I just sent them.

**Comment by kamalaknn** [comment] 2018-03-19 06:38
Hi @TheAllThing,

We've identified the root cause of the issue. The Postman App is having trouble loading the collections when there are a large number of requests(with heavy pre-request/test scripts). 

We're working on a fix to load the requests in batches that will solve this. We'll push out a fix for this in the next release.

@TheAllThing I'm editing the title of the issue for anyone facing similar issues.

**Comment by TheAllThing** [comment] 2018-03-20 02:55
Hello @kamalaknn.

A quick update. I have unsubscribed from all of our workspaces and only have a single collection with 1 request in my personal workspace. When I close the app and open again, that single personal workspace will not load the request. I still need to log out/in to resolve this. It certainly doesn't look like it has anything to do with large numbers of requests when the behavior is the same in this situation. Obviously, I'm not qualified to make that call, but wanted to let you know what I found. If you need any further detail, let me know.

**Comment by TheAllThing** [comment] 2018-04-03 01:22
Hi @kamalaknn ,

I may have found a resolution to my syncing issues. I had been logging in via my Google account, using 2 factor authentication. With the consistent problems I've been facing, I decided to try using a new, dedicated user account, and bypass logging in via my Google account. After creating a new user account using my work email, I am able to close/open the app without it having sync issues. Syncing is extremely fast too. From what I can see with these new results, it looks like the root cause was not the large workspaces, but logging in via Google.

I will be using the new user account now. How does this affect collections/workspaces I built using the old account? We would like to delete the old user, but are concerned it would give us trouble with any resources created by that account.

Could you please assist us with this so we can take these next steps with confidence?

**Comment by kamalaknn** [comment] 2018-04-05 14:03
Hi @TheAllThing 

Sorry, the delayed response. We've been working a fix for this.

**The short answer**
We have pushed a fix to our [Canary Channel](http://getpostman.com/canary). With the fix, you should be able to use your existing account with Postman. You do not have to create a new account. This was not an issue with Google login.

**The long answer**
The root cause of the issue is that when there a lot of requests stored in the Postman app, loading all the requests when the app starts had exceeded the electronjs platform's limit. We've now moved to an approach where we load the requests in batches. This has fixed issues with initial loading.

When you left all the team workspaces, we hadn't internally unsubscribed you from all the collections. That's is why you were still subscribed to a lot of requests after leaving the workspaces.

When you created a new app, you were never subscribed to these collections in the first place. That's why the new account loaded perfectly.

We are also working on a fix for this from Sync perspective. After that's done, requests from collections you are no longer part of will not be stored in the app. That'll reduce the actual number of stored requests in your app and make the app a lot faster.

Thanks for understanding.

**Comment by TheAllThing** [comment] 2018-04-05 15:28
Thanks for the explanation, @kamalaknn. That makes sense.

 I just loaded the Canary build and it's already loading everything exactly as one would expect! Thank you! I'll relay this to the rest of the team and get back to you with any details if we see anything out of the ordinary.

I'll keep my eye open for the next stable release with these fixes rolled up into it.

Thanks again!

**Comment by kamalaknn** [comment] 2018-04-05 17:18
Great!

That’s good to hear. We’ll be pushing the fix to the stable channel in the next release. 

I’m closing this ticket. You can continue using the canary channel until the next stable release.


Thanks

**Closed as completed by kamalaknn** 2018-04-05 17:18 UTC
Labels: bug, sync, pending-close
