### ISSUE TITLE
Can't send requests in version 3.0.2

### ISSUE THREAD

**Issue by pmckeown** [a85/POSTMan-Chrome-Extension#1200] opened 2015-06-30 23:21 UTC
The latest version of postman (which was auto-upgraded this morning) doesn't send HTTP requests which I click send.

I get the following JS errors when I start up postman and then a dialog saying "Lack of Javascript Support" pops up.  The 2 are clearly related and probably the root cause of the basic function of this tool not working anymore.

![image](https://cloud.githubusercontent.com/assets/574865/8444238/b70cd80c-1fe2-11e5-8de8-12f864caa10b.png)

This was such a great tool until this unwanted upgrade from v2 of the packaged app.  Thankfully my browser still has the embedded version 0.8 installed!

**Comment by a85** [comment] 2015-06-30 23:23
Can you go to chrome://flags and reset them? Probably some setting that was changed. The latest version has been pushed to users and things have been working fine so far.

**Comment by pmckeown** [comment] 2015-06-30 23:29
That's not it - the only one I had changed was "Enable debugging for packed apps" to allow me to get the above screenshot.

**Comment by a85** [comment] 2015-06-30 23:31
Can you send one to http://dump.getpostman.com and check if it's not the server? Also try toggling off the interceptor if it's enabled. I am not seeing this error in my Postman copy so not sure. None of the errors in the console are related to Javascript being disabled.

**Comment by pmckeown** [comment] 2015-07-01 00:27
Attempting a GET to http://dump.getpostman.com/status is showing the same behaviour - nothing whatsoever is happening other than .  

The JS errors in the console must be related to this. I'm assuming that some resource is not loading correctly.

**Comment by a85** [comment] 2015-07-01 00:48
Looking into this. Another user reported this: https://github.com/postmanlabs/postman-app-support/issues/1162. There is a workaround listed.

**Comment by pmckeown** [comment] 2015-07-01 03:59
That's a different issue, I am able to dismiss the dialog.

**Comment by abhijitkane** [comment] 2015-07-01 07:14
@pmckeown What version of Chrome are you using? We tested this version of the app on Windows with the latest version of Chrome.

**Comment by pmckeown** [comment] 2015-07-01 20:42
The latest version:

31.0.1650.57 m

On Windows XP

**Comment by abhijitkane** [comment] 2015-07-01 21:52
We'll continue to investigate and update this thread. The earlier issue relating to the Send button not working was due to Javascript being disabled in Chrome. 

That setting doesn't affect the main Postman context, but affects the sandbox where the pre-request scripts are run. Javascript should enabled for all sites in chrome://settings.

**Comment by pmckeown** [comment] 2015-07-01 22:09
Is there anywhere to download POSTMAN V2?  I'd rather roll back while issues like this are resolved.

**Comment by pmckeown** [comment] 2015-07-01 22:18
Sorry, I just realised I had version 3.0.2 install, not 3.0.1

**Comment by abhijitkane** [comment] 2015-07-02 05:37
You can download v2 from here - https://chrome.google.com/webstore/detail/postman-v2-deprecated/nppbmnmcgngfmnlmaejnanlldjdffchl

Note that Sync will not work in this version.

**Comment by pmckeown** [comment] 2015-07-02 05:54
Thanks for that, at least I can continue to use this great tool while the kinks are worked out of v3

**Comment by jezeniel** [comment] 2015-07-10 00:02
:+1: for this. I am encountering the same bug with postman 3.0.2

**Comment by mikefadhl** [comment] 2015-07-10 00:43
How can I roll back to 3.0.1?

**Comment by abhijitkane** [comment] 2015-07-10 04:44
@jezenielzapanta @mikefadhl Have you tried resetting the settings at chrome://flags, and ensuring that Javascript is enabled for all sites?

**Comment by jezeniel** [comment] 2015-07-10 14:06
@abhijitkane yes, i tried resetting the flags and enabled everything. it is just working yesterday.

**Comment by ruslanix** [comment] 2015-07-16 09:58
Same problem with version 3.0.4
I can dismiss "Lack of javascript support", but "Send" button doesn't work.
I've reset all chrome://flags and Javascript enabled for all Sites in chrome://settings->Advanced Settings->Content->Java script

Ubuntu: 12.04
Postman: 3.0.4

Chromium    33.0.1750.152 (Developer Build 256984) Ubuntu 12.04
OS  Linux 
Blink   537.36 (@169182)
JavaScript  V8 3.23.17.23
Flash   11.2 r202
User Agent  Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/33.0.1750.152 Chrome/33.0.1750.152 Safari/537.36
Command Line     /usr/lib/chromium-browser/chromium-browser --enable-pinch --flag-switches-begin --debug-packed-apps --flag-switches-end
Executable Path /usr/lib/chromium-browser/chromium-browser
Variations  24dca50e-837c4893
ca65a9fe-bf3100d4
246fb659-e1cc0f14
f296190c-75cb33fc
4442aae2-a90023b1
ed1d377-e1cc0f14
75f0f0a0-a5822863
e2b18481-6bdfffe7
e7e71889-4ad60575

**Comment by abhijitkane** [comment] 2015-07-16 11:27
This might be due to a race condition in the way jQuery is loaded. We'll push a fix for this soon.

**Comment by abhijitkane** [comment] 2015-07-23 10:00
@ruslanix Can you confirm if you're still seeing this in 3.0.5?

**Comment by ruslanix** [comment] 2015-07-24 09:49
@abhijitkane For some reason my current 3.0.4 postman didn't want to update, so I just removed this extension from Chrome and now trying to install again (install new version). But when I press "Add to Chrome" button on extension page, chrome extension file download interrupted with error: "Fail: no file". So, currently can't say anything, trying to figure this out.

**Comment by ruslanix** [comment] 2015-07-28 17:04
@abhijitkane I've updated postman to 3.05 and still have this error.

![screenshot from 2015-07-28 21 02 34](https://cloud.githubusercontent.com/assets/5372723/8937896/e75f1614-3563-11e5-8b22-8175a6d7e244.png)

**Comment by abhijitkane** [comment] 2015-07-28 17:13
@ruslanix Do you see a `Reference error: $ is not defined` error in the console - http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/?

**Comment by ruslanix** [comment] 2015-07-29 12:10
@abhijitkane yes!
![screenshot from 2015-07-29 16 08 41](https://cloud.githubusercontent.com/assets/5372723/8957011/ec678678-3603-11e5-91f7-3fc056c452e7.png)

**Comment by abhijitkane** [comment] 2015-07-29 13:36
@numaanashraf @shamasis Can you take a look at this? This is the jQuery race condition in the tester sandbox - Backbone is loading but $ is not defined

**Comment by ruslanix** [comment] 2015-08-06 12:20
@abhijitkane 
Hi, after upgrading Chrome to version:
Version 37.0.2062.120 Ubuntu 12.04 (281580)

Postman works fine and this error not reproduced

**Closed as completed** 2015-12-29 10:58 UTC
Labels: bug
