### ISSUE TITLE
Even without the version upgrade, system shows message that the "Update failed, view details"

### ISSUE THREAD

**Issue by Pricilla09** [a85/POSTMan-Chrome-Extension#9696] opened 2021-03-08 07:23 UTC
**Describe the Issue**

Suddenly it shows error during upgrade and when we try to fix it manually it says the version is up-to date.

I am already using the latest version - Version 8.0.6, also my auto update is disabled. But sometimes I am seeing the error that the upgrade is failed. 

**Steps to Reproduce**

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/71498483/110287767-040aeb80-8022-11eb-8450-71cf561595dd.png)

![image](https://user-images.githubusercontent.com/71498483/110287800-0ec58080-8022-11eb-8259-163d26e3c20b.png)

![image](https://user-images.githubusercontent.com/71498483/110287812-1422cb00-8022-11eb-9546-a16a81a85354.png)

**Environment Information**

 - Platform Type: Desktop application
 - Postman Version: Version 8.0.6
 - Operating System: Win 10

**Comment by DannyDainton** [comment] 2021-03-08 07:40
Is fully quiting the app and restarting it again still showing the same?

Also, the auto update applies to only _major_ versions (v7 > v8) and not minor or patch versions (V8.0.1 > V8.0.2).

**Comment by twitharshil** [comment] 2021-03-08 07:47
Hey @Pricilla09 

Could you send over the logs to help@postman.com so we can take a look at what's going on, please?
You can find the logs at View -> Developer -> View logs in Finder/Explorer.

Feel free to reference the GH Issue number in the subject line of the email.

**Comment by Pricilla09** [comment] 2021-03-08 07:49
This issue is sporadic Danny :-( I might not see if I am restating the app now, but may be again in few days this comes back!!

**Comment by nasco-a** [comment] 2021-03-08 11:24
Hi @Pricilla09 
Thank you for sending the logs - we will keep you posted once we have an update.

**Comment by xk0der** [comment] 2021-03-31 10:15
Hey @Pricilla09 just a quick note about the label changes you may see here 👋 
This GitHub issues stays open, just closing the support-automation here, we have your ticket logged internally and will continue to follow-up there too.

**Comment by Pricilla09** [comment] 2021-04-04 23:51
Thank you @xk0der :-) I faced the issue today as well!!

![image](https://user-images.githubusercontent.com/71498483/113524811-c333d180-95e3-11eb-8226-149c9ab66108.png)

![image](https://user-images.githubusercontent.com/71498483/113524813-c8911c00-95e3-11eb-9665-714bebf2ea90.png)

![image](https://user-images.githubusercontent.com/71498483/113524815-cb8c0c80-95e3-11eb-85a2-861f31fc3b23.png)

**Comment by twitharshil** [comment] 2021-07-07 07:04
@Pricilla09 Thanks for sharing the application logs with us, could you also share the SquirrelSetup log file available at the local application directory? This will help in further narrowing down the root cause of the problem.

![Squirrel](https://user-images.githubusercontent.com/25850676/124714390-53edb680-df1f-11eb-8241-fa859dd43808.PNG)

**Comment by chrisdeso** [comment] 2022-02-14 22:31
@Pricilla09 We're closing this issue for now – if you're still facing issues, let us know by reopening this or by filing a [support ticket](support.postman.com).

**Closed as completed by chrisdeso** 2022-02-14 22:31 UTC
Labels: support, staff/done
