### ISSUE TITLE
App icon consistency on macOS Big Sur - square (iOS-like) icons

### ISSUE THREAD

**Issue by heyaco** [a85/POSTMan-Chrome-Extension#9819] opened 2021-04-10 23:05 UTC
Please update your app icon for macOS. As of Big Sur the system standard has shifted to a more iOS-like UI with square icons.

**Comment by xk0der** [comment] 2021-04-12 01:16
Duplicate of #9560

**Closed as completed by xk0der** 2021-04-12 01:16 UTC
