### ISSUE TITLE
[Bug] The test results under the 'Tests' tab in the response window are now displayed alphabetically.

### ISSUE THREAD

**Issue by PFarrell89** [a85/POSTMan-Chrome-Extension#2864] opened 2017-03-30 12:38 UTC
1. **Postman Version: 4.10.5**
 2. **Windows Native Client**
 3. OS details: **Windows 10 x64 Bit**
 4. Is the Interceptor on and enabled in the app: **N/A**
 5. Did you encounter this recently, or has this bug always been there: **This appears to be a new issue.**
 6. Expected behaviour: **The tests that were created against the endpoint should match the order displayed in the Tests tab for the response.**
Screenshots:

![image](https://cloud.githubusercontent.com/assets/8641826/24504178/1b3f8548-154d-11e7-99c8-115265ef3c63.png)

![image](https://cloud.githubusercontent.com/assets/8641826/24504169/15ba3866-154d-11e7-8a80-8555f1eb4489.png)

Notice how the first test that should be shown as passing/failing should be the "Status Code is 200 (OK)" as this is the first test that is written. 

The Test Results are displayed in alphabetical order.
I believe this was introduced as part of the new update.

**Comment by kamalaknn** [comment] 2017-03-30 13:06
Hi @PFarrell89, 

Thanks for reporting this issue. This is an unintended outcome of our recent changes.

We have a fix ready for this. Will be rolled out as part of our next release.

I will update here when the release goes out.

**Comment by kamalaknn** [comment] 2017-04-10 09:55
Hey @PFarrell89, the latest version of the app now displays the test results in the order you've defined them. Please update to it.

Closing this issue for now. Feel free to re open if you continue to see this.

**Closed as completed by kamalaknn** 2017-04-10 09:55 UTC

**Comment by PFarrell89** [comment] 2017-04-10 09:57
@kamalaknn Thanks. Confirmed fixed :)

**Comment by a85** [comment] 2017-04-10 20:44
@abhijitkane Why are we removing the labels? Will be helpful in regression testing later.
