### ISSUE TITLE
Postman 7.12.0 black screen on MacOS 10.15.1 

### ISSUE THREAD

**Issue by pz2147** [a85/POSTMan-Chrome-Extension#7729] opened 2019-12-03 05:45 UTC
Describe the bug
After updating to 7.2.2 version, Post man screen turns black in few minutes once the app is started

To Reproduce

Open the post man app
Keep for a minute
Full screen of the app turns black and nothing can be done
Expected behavior
Post man screen should show the menu items and work as normal

App information (please complete the following information):

Postman Version : 7.12.0
OS: macOS Catalina
Version 10.15.1

**Comment by kamalaknn** [comment] 2019-12-03 08:32
Hey @pz2147 

This looks like a duplicate of #7078

Could you update the original thread with information like, number of requests, size of your requests and responses etc?

**Closed as completed by kamalaknn** 2019-12-03 08:32 UTC
