### ISSUE TITLE
Duplicated request doesn't use the same environment variable

### ISSUE THREAD

**Issue by Zsolti1989** [a85/POSTMan-Chrome-Extension#7921] opened 2020-01-16 10:20 UTC
**Describe the bug**
If you duplicate a request which uses an environment variable, the duplicated request doesn't use the same variable.

**To Reproduce**
1. Have multiple environment variables
2. Duplicate a request which uses an environment variable in the URL
3. Check the environment variable in the duplicated request

**Expected behavior**
They should use the same variable

**Screenshots**
![Postman](https://user-images.githubusercontent.com/49157917/72516507-12aca700-3852-11ea-8542-65e97733fbcc.gif)

**App information (please complete the following information):**
 - App Type: Desktop
 - Postman Version Version 7.14.0 (7.14.0)
 - OS: macOS Mojave 10.14.6

**Comment by vikiCoder** [comment] 2020-03-20 06:21
Hi @Zsolti1989,

I see that the request you are duplicating has unsaved changes in the open tab. Please note that duplicating a request only duplicates the saved state of the particular request. Unsaved changes in the request tab are not duplicated. So the saved request (`Get Auth Token` in your case) must be having the URL as `{{MAPI_URL}}/token/new` and then you might have updated the URL to `{{MAUTH_URL}}/token/new` and forgot to save the request. So the duplicated request still has the URL `{{MAPI_URL}}/token/new`.

If the unsaved changes are intentional and you want to duplicate the request with those unsaved changes, you can right-click on the request tab and select `Duplicate Tab` option. This will open a new tab with all the data in the current tab (even unsaved data).

I am closing the issue since this is the expected behavior. Feel free to reopen this if I misunderstood your problem.

**Closed as completed by vikiCoder** 2020-03-20 06:21 UTC
Labels: bug, support, product/runtime
