### ISSUE TITLE
Can't add Cookies when specifying domain with schema and/or port

### ISSUE THREAD

**Issue by porfirion** [a85/POSTMan-Chrome-Extension#7231] opened 2019-08-30 10:46 UTC
**Describe the bug**
Can't add cookies for request ("cookies-management-cookies__actions--add" button doesn't work) when adding domain with schema (http/https) or with port.

**To Reproduce**
1. Create new request
2. Click on 'Cookies' link
3. In opened window type host name into 'Type a domain name' input with schema, for example "https://google.com" or "google.com:8080" (not just "google.com")
4. Click "Add" button
5. Click "+ Add Cookie"

**Expected behavior**
Input for cookie text should appear

**App information (please complete the following information):**
 - App Type: Postman for Linux (linux 4.15.0-58-generic / x64)
 - Postman Version: v7.6.0
 - OS: Linux Mint 18.3 Cinnamon 64-bit

**Additional context**
I've used cookies previously, but several month ago I've tried to add some cookies and button was not working. I thought that button totally broken. Now, while writing this issue I discovered, that it works when no schema is specified. Chome dev tools in Application->Cookies shows domains with schema and port and I assumed that it is correct way of specifying domain.
Also - cookies are distinct for different port on same domain - so I really need to specify schema and port for cookies.

**Comment by codenirvana** [comment] 2019-09-01 19:53
Duplicate of #6931 #3518

@porfirion As mentioned in the previous issues, Cookie scope is limited to the hostname and not bound to port or protocol information.
RFC: https://tools.ietf.org/html/rfc6265#section-8.5
Refer: https://github.com/postmanlabs/postman-app-support/issues/3518#issuecomment-401298505

> cookies are distinct for different port on same domain

Can you share an example for this?

> Chome dev tools shows domains with schema and port

The protocol information is just to filter out `secure` cookies and the same behavior is present in Postman as well.

**Closed as completed** 2019-09-18 23:07 UTC
Labels: bug, cookies, user-interface, blocked/need-info, product/runtime
