### ISSUE TITLE
Not able to view Release Notes - Version 7.3.2

### ISSUE THREAD

**Issue by suraj-purohit** [a85/POSTMan-Chrome-Extension#6892] opened 2019-07-10 14:14 UTC
**Describe the bug**
Not able to view Release Notes - Version 7.3.2 - In App

**To Reproduce**
1. Go to 'Top Right Corner of the App'
2. Click on 'Settings -> Release Notes'
4. See error -> "Something Went Wrong"

**Expected behavior**
When you click on the Release Notes button - You should be able to see Release Notes related to update version.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
<img width="1280" alt="Screenshot 2019-07-10 at 7 10 58 PM" src="https://user-images.githubusercontent.com/51916047/60975932-62ae2c80-a34a-11e9-9429-71ec5146390f.png">

App information:
Native App
Postman Version 7.3.2
macOS Mojave 10.14.5

**Comment by ACadieux** [comment] 2019-07-11 13:36
I got the same problem. I just upgraded to 7.3.3 and bug still present.

**Comment by shamasis** [comment] 2019-07-11 22:05
Yep. Looks like we have a release note delivery misbehaviour in cases where we are doing gradual rollout. Will get this addressed in coming releases.

**Comment by DannyDainton** [comment] 2022-04-11 16:27
Hey @suraj-purohit 

It's going to be difficult to recreate this issue given the version that it was reported in 😢 , As we're now 2 Major versions ahead, I'm going to close this issue.

If the problem is encountered again in the latest versions, we can look to open this up again.

**Closed as completed by DannyDainton** 2022-04-11 16:27 UTC
Labels: distribution
