### ISSUE TITLE
Restore button is not shown up for some of the collection under activity feed.

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5178] opened 2018-09-14 09:07 UTC
**Describe the bug**
We are noticing that there are few collections on which we don't see an option restore them back to the previous date & the information of who modified the collection & what changes have been done. However, the same is working on some of the collections. Please look into the issue

**Expected behavior**
Restore option should be available for all the collections along with the details of changes made & who modified the collection.

**Screenshots**
Collections with no restore option:
![image](https://user-images.githubusercontent.com/40994626/45540636-8e47af80-b82a-11e8-9f2f-d45c46e31ba6.png)

![image](https://user-images.githubusercontent.com/40994626/45540758-e088d080-b82a-11e8-8975-4316474e31a2.png)

Collections with restore option:
![image](https://user-images.githubusercontent.com/40994626/45540864-2776c600-b82b-11e8-8fcd-19a83af3fbbc.png)

![image](https://user-images.githubusercontent.com/40994626/45540986-69a00780-b82b-11e8-818f-2f80f3f82236.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.2.4

**Comment by smennesson** [comment] 2018-09-14 09:24
Hi @ankitjaggi, I'm the one having reported the problem. Don't hesitate in the case you need additional details.
Kind regards,
Stéphane

**Comment by deeg** [comment] 2018-10-19 18:08
@numaanashraf, is there any update on this? Is this only a paid feature?

I'm currently looking into buying postman for my team and having this type of version control over our documentation would be necessary. I am also not seeing it work on my shared collections with my team.

**Comment by preethammavin** [comment] 2019-05-27 09:05
@deeg yes, its a feature as part of paid plan . We have made several updates, @smennesson can you check if its still an issue on your end.

**Comment by smennesson** [comment] 2019-05-28 11:29
Hello @preethammavin, sorry the problem was too long ago for me to be able to reproduce today. I'm not anymore working for the company having the Postman account reproducing the issue.

**Comment by preethammavin** [comment] 2019-05-28 13:33
Closing the issue for now, feel free to reopen it if not so.

**Closed as completed by preethammavin** 2019-05-28 13:33 UTC
Labels: bug
