### ISSUE TITLE
Postman returns an error when there is a renegotiation of certificate

### ISSUE THREAD

**Issue by tegomass** [a85/POSTMan-Chrome-Extension#5841] opened 2019-01-28 15:52 UTC
**Describe the bug**
When 2 requests are sent too quickly, Postman returns an error on the 2nd request due to the renegotiation on certificate set on the server.

The test has been done also on a web browser using fetch and xhr functions. Plus with node.js request module. And the issue doesn't happen on them.

This bug happens on Postman and also on Newman.

**To Reproduce**
1. Setup an https server (node.js/express) with certificates and renegotiation on the certificate.
2. Send a request to the server url
3. Send another request on the server url 
4. Error 400 is returned by Postman on the 2nd request (if the 2nd request is sent too quickly)

**Expected behavior**
Postman should return a 200 status. If I set an timeout of 2 secondes between the requests, all tests are 200.
It looks like Postman close the request prematurely and returns a generic 400 error.

**Screenshots**
![1](https://user-images.githubusercontent.com/25712863/51847460-04e9d300-231c-11e9-8b3a-78913e409f8c.jpg)

**App information (please complete the following information):**
 - App Type : Native App + Newman with node.js
 - Postman v6.7.2
 - OS: Windows

**Additional context**
The renegotiate code on the server (express) look like this : 

App route :
![2](https://user-images.githubusercontent.com/25712863/51847696-86416580-231c-11e9-9d02-397da4ba6e58.jpg)

bin/www : 
![3](https://user-images.githubusercontent.com/25712863/51847913-efc17400-231c-11e9-835a-48ecf9504dc2.jpg)

**Comment by codenirvana** [comment] 2019-09-18 23:12
@tegomass Can you update your app and confirm if that fixes your issue?

If the issue still persists, is it possible to share a scaled-down collection with the sample express server which we can use to reproduce this issue internally?

**Comment by tegomass** [comment] 2019-09-23 09:06
Hi, 
The issue still happens on Postman client and newman 4.5.4.
I'll update the issue with an example ready-to-run, soon. 
Thanks

**Comment by coditva** [comment] 2019-10-31 08:54
@tegomass I was able to reproduce the issue. The problem seems to be that the `renegotiate` function calls the callback with error only if the renegotiation was successful. You must add a listener to `error` event on the socket to handle this case as:
```js
...
    socket.on('error', (err) => {
        // handle error
    });

    let result = socket.renegotiate(options, (err) => {
...
```

The error on renegotiation is:
```
Error [ERR_TLS_SESSION_ATTACK]: TLS session renegotiation attack detected
```

I tried this request with `curl` with the `--verbose` flag and found that this request is failing the second time for `curl` too. `curl` detects that the renegotiation failed, closes the connection on this socket, and creates another connection and re-sends the request.

<details>
	<summary>curl logs</summary>

```
* TLSv1.2 (IN), TLS handshake, Hello request (0):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (OUT), TLS alert, unexpected_message (522):
* LibreSSL SSL_read: error:14004064:SSL routines:CONNECT_CR_SRVR_HELLO:app data in handshake, errno 0
* Connection died, retrying a fresh connect
* Closing connection 0
* Issue another request to this URL: 'https://localhost:4433/'
* Hostname localhost was found in DNS cache
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 4433 (#1)
```
</details>

Apart from this, I found out that renegotiation is completely removed from TLS versions later than `v1.3` included, because of the possibility of [TLS renegotiation attack](http://www.educatedguesswork.org/2009/11/understanding_the_tls_renegoti.html).

Anyway, if you want to still use renegotiation with Postman, you can send a `Connection: close` header with the renegotiation request as a workaround.

Hope this helps! :)

**Comment by tegomass** [comment] 2019-10-31 10:05
Hi coditva,

I'll check that.

Whether it works or not, big thanks to you !

**Comment by coditva** [comment] 2019-11-05 07:41
We identified that this issue is with the server and not with Postman. The server errors on renegotiation and Postman is correct to show a 400 code since the request failed. If the server wants to implement multiple renegotiations, they can add
```js
const tls = require('tls');
tls.CLIENT_RENEG_LIMIT = 5; // or any other value
```
to the top of their server code. Postman is ready to handle this case, thus closing this issue.

Ref: https://nodejs.org/api/tls.html#tls_client_initiated_renegotiation_attack_mitigation

**Closed as completed by coditva** 2019-11-05 07:41 UTC
Labels: bug, request-sending, tls, product/runtime
