### ISSUE TITLE
Unable to create documentation or generate tests using Postbot

### ISSUE THREAD

**Issue by SAM2904** [a85/POSTMan-Chrome-Extension#12907] opened 2024-05-31 09:54 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when i try to generate documentation or test using postbot it fails.
It's happening when the response use to be status code 200, or the response is 1.
Not sure if there is a pattern or not.

Hey @kylerRenneker , hope you are doing well!
I have an issue with the updated postman version. Can you please help me how can I fix it?

### Steps To Reproduce

Open a new POST/GET method.
Execute
Go to documentation, use postbot to generate the documentation, you will get the documentation, BTW, i love them!
Go to tests, use postbot to generate the tests, you will get the tests.

### Screenshots or Videos

![Postbot Error not generate](https://github.com/postmanlabs/postman-app-support/assets/51758881/ceff5899-2984-4457-ae87-575fd14b0516)
![Postbot Error Screenshot](https://github.com/postmanlabs/postman-app-support/assets/51758881/ca0c98e2-0437-4100-b9b0-54b2f2e96570)
![postbot response generate in chat6](https://github.com/postmanlabs/postman-app-support/assets/51758881/8e14ef87-b162-4a0f-bc0f-91b6b34e1c7e)

### Operating System

Windows

### Postman Version

Postman v11.1.14

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

UI version
11.1.14-ui-240521-0853

Architecture
x64

OS platform
Windows 11 win32 10.0.22631

My plan:
Basic (Monthly) Team Plan

**Comment by abhijitkane** [comment] 2024-06-11 11:32
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/12906

**Closed as not planned by abhijitkane** 2024-06-11 11:32 UTC
