### ISSUE TITLE
Postman APIs Validation Generate [object Object] for Parameters Description after Review Issue

### ISSUE THREAD

**Issue by fanadol** [a85/POSTMan-Chrome-Extension#9102] opened 2020-09-29 10:52 UTC
**Describe the bug**
Postman APIs generate [object Object] for parameter description from OpenAPI 3.0 yaml after "Review Issue".

**To Reproduce**
1. Create postman APIs
2. Define some OpenAPI 3.0 format in "Define" tab
3. Move to "Develop" tab and Add documentation -> Create new documentation
4. Click "Click to Validate" button under "Validation" column.
5. At this point the postman collection will work as intended, the parameters will have its description
6. Add / Change some endpoint in "Define" tab
7. Move to "Develop" tab and click validate again under "Validation" column, you will see "Resolve Issue" button. Click it.
8. Resolve the issue
9. Check the collection parameters again, it's description will change to [object Object]

**Expected behavior**
The description should not change to [object Object].

**Screenshots**
<img width="902" alt="Screen Shot 2020-09-29 at 17 47 51" src="https://user-images.githubusercontent.com/25933748/94549242-1cf5c080-027c-11eb-9676-e600eece95ff.png">

<img width="345" alt="Screen Shot 2020-09-29 at 17 48 56" src="https://user-images.githubusercontent.com/25933748/94549252-1f581a80-027c-11eb-88a7-c1d04fa6b54d.png">

**App information (please complete the following information):**
 - App Type [Native App for Mac]
 - Postman Version [Version 7.33.1 (7.33.1)]
 - OS: [macOS Catalina 10.15.6]

**Additional context**

**Comment by VShingala** [comment] 2020-09-29 12:46
@fanadol Thanks for reporting the issue. We have identified the problem and will be fixing it with upcoming releases.

**Comment by fanadol** [comment] 2020-09-30 04:09
Hi @VShingala thank you for your quick reply, could you tell me the release date for the patch ? The feature is really great, and our team love to explore this feature more.

Cheers

**Comment by VShingala** [comment] 2020-09-30 11:27
@fanadol Thanks.! I can't promise an exact date but It should be fixed by end of next month.

**Comment by abhinaba-ghosh** [comment] 2020-11-04 06:17
Hi @fanadol, the issue is fixed. Feel free to re-open the ticket if you find the issue still exists.

**Closed as completed by abhinaba-ghosh** 2020-11-04 06:17 UTC
Labels: bug, product/importers
