### ISSUE TITLE
Postman adding "=" at the end of variables in certain conditions

### ISSUE THREAD

**Issue by turbokat** [a85/POSTMan-Chrome-Extension#4136] opened 2018-01-31 19:39 UTC
## App Details:

```
Postman for Mac
Version v5.5.2
OS X 16.4.0 / x64
```

## Issue Summary: 
the postman seems to be adding an "=" at the end of variables, which makes it difficult if not impossible to use them in URLs. e.g. http://my.server.instance/my.request?param={{postman-variable}} with **postman-variable** having the value say **foo** results in the URL http://my.server.instance/my.request?param=foo= (with the = at the end that I did not add). 

Now this appears to be happening in certain conditions e.g. with nested variables e.g. **{{value={{another-variable}}&param=123}}** or when the URL contains 2 or more variables e.g. **paramOne={{param-one}}&paramTwo={{param-two}}**. The only case that works consistently is URLs with only one variable in them.

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **encountered recently with update - last couple of weeks**
 2. Expected behaviour: **variables should not be adding anything - they should be replaced as-is**
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

URL request - 
<img width="252" alt="screen shot 2018-01-31 at 11 38 32 am" src="https://user-images.githubusercontent.com/20780493/35643486-51f242e0-067b-11e8-8952-2fca78badcdb.png">

global variable
<img width="230" alt="screen shot 2018-01-31 at 11 22 52 am" src="https://user-images.githubusercontent.com/20780493/35643263-9d19d284-067a-11e8-825f-2a081ea301e4.png">

what is seen by the request processor
<img width="341" alt="screen shot 2018-01-31 at 11 22 41 am" src="https://user-images.githubusercontent.com/20780493/35643250-972667b6-067a-11e8-8f8d-4908efa5f7b2.png">

**Comment by jochenhager** [comment] 2018-02-06 01:12
I have the same problem. Postman just became unusable for me. It turns this request:
http://192.168.1.1:8080/ContentServer/ContentServer.dll?get&pVersion=0046&contRep=T2
into this: ("=" after the get parameter, which should not be there).
http://192.168.1.1:8080/ContentServer/ContentServer.dll?get=&pVersion=0046&contRep=T2
which causes my target server to respond with "invalid request".

**Comment by sdnts** [comment] 2018-02-20 07:38
Hi @jochenhager, we're aware of this. This happens because the app treats the value of a URL parameter like the ones you've quoted as an empty string, and so adds the additional `=` character. We're working on fully supporting types for all variables, and that should solve this issue.

For the time being, can you separate the `myParam` variable name and the `{{my-email}}`? Your URL would look like: `/gender/percentage?myParam={{my-email}}`. This should make the app usable again.

@jochenhager I'm guessing the URL param `get` is supposed to be a boolean on your server. Can you try explicitly passing `get=true` to get around it for the time being as well?

**Comment by sdnts** [comment] 2018-02-20 07:41
I'm closing this as a duplicate of #3181, please follow that thread for updates :)

**Closed as completed by sdnts** 2018-02-20 07:41 UTC

**Comment by jochenhager** [comment] 2018-02-20 13:48
Hi Siddhant,

No the parameter is not boolean. The name is the value and handled as a flag in the server specification. 

Therefore, your workarounds unfortunately do not work.

Please update me as soon as you have a fix available.

Best Regards,
 Jochen

Managing Partner
Solution Exchange LLC
West Chester, PA, USA
Jochen.Hager@solutionXchg.com
Office: +1 (484) 356-1264
Mobile: +1 (484) 716-1210

On Feb 20, 2018, at 2:38 AM, Siddhant Sinha <notifications@github.com> wrote:

Hi @jochenhager <https://github.com/jochenhager>, we're aware of this. This happens because the app treats the value of a URL parameter like the ones you've quoted as an empty string, and so adds the additional = character. We're working on fully supporting types for all variables, and that should solve this issue.

For the time being, can you separate the myParam variable name and the {{my-email}}? Your URL would look like: /gender/percentage?myParam={{my-email}}. This should make the app usable again.

@jochenhager <https://github.com/jochenhager> I'm guessing the URL param get is supposed to be a boolean on your server. Can you try explicitly passing get=true to get around it for the time being as well?
