### ISSUE TITLE
Duplicate Environments after import

### ISSUE THREAD

**Issue by pvegh** [a85/POSTMan-Chrome-Extension#11684] opened 2023-02-02 09:47 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When importing a folder to keep everything up to date, the collection is correctly replaced.
But the environments are duplicated every time, there is no dialog asking for replacement.
So I end up with many outdated environments with no chance see which is new/correct.

There should be a dialog asking if they should be replaced. Maybe skip the dialog if data is identical.

### Steps To Reproduce

Select collections tab and use the Import button

### Operating System

macos

### Postman Version

10.8.0

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by DannyDainton** [comment] 2023-02-08 10:07
Hey @pvegh 

This looks like a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9561

**Comment by VaishnaviChallaPostman** [comment] 2023-03-06 07:02
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/9561

**Closed as completed by VaishnaviChallaPostman** 2023-03-06 07:02 UTC
Labels: product/runtime
