### ISSUE TITLE
Auto-complete GraphQL json payload

### ISSUE THREAD

**Issue by steebchen** [a85/POSTMan-Chrome-Extension#10657] opened 2022-02-12 15:24 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Currently, the JSON payload input field in a GraphQL request does not make use of auto-completion.

![image](https://user-images.githubusercontent.com/5013932/153716930-6f527512-fa5f-4f9b-8e01-7cdf60121cd6.png)

### Describe the solution you'd like

It would be great if Postman could auto-complete the JSON payload. It should be possible from the schema and some GraphQL playgrounds also do that which is super useful.

**Comment by giridharvc7** [comment] 2022-02-15 11:11
Duplicate of #6719

**Closed as completed by giridharvc7** 2022-02-15 11:11 UTC
Labels: feature
