### ISSUE TITLE
Duplicated request remains linked to original

### ISSUE THREAD

**Issue by heath3n** [a85/POSTMan-Chrome-Extension#4938] opened 2018-08-01 03:15 UTC
**Describe the bug**
Changing properties of a duplicated request affects the original request.

**To Reproduce**
1. Create a request and duplicate it.
1. Change the title of the duplicated request and note that the title of the original changes too. Changing the request URL does not change the URL of the original but nevertheless puts it into an unsaved state. Some weirdness ensues when trying to delete the request.

**Expected behavior**
A shallow copy of the original request should be created.

**App information (please complete the following information):**
 - Native App
 - v6.1.4
 - Windows 8.1 x64

**Comment by sujayvenaik** [comment] 2018-08-01 12:25
Hey @heath3n 

Did you duplicate the request from the sidebar where all requests are listed or did you duplicate the request when it was opened in the tab, and duplicated from the context menu ?

**Comment by heath3n** [comment] 2018-08-01 18:32
I duplicated it from the tab context menu. The sidebar appears to work as expected.

**Comment by sujayvenaik** [comment] 2018-08-02 05:52
@heath3n 
From the tab context menu, this is the expected behavior.
It basically creates a clone (duplicate) of the request but points to the same request.

We are working on making it more clear to the users about the difference when you duplicate from the sidebar and the tab context menu.

**Comment by heath3n** [comment] 2018-08-02 06:41
Huh...it seems like a rather arbitrary decision to have an option in one area of the screen do one thing and the same option elsewhere do another. IMO it would be clearer to just have a "Duplicate" and "Linked Duplicate" or whatever you choose to call it.

Thank you for clearing that up though; this ticket can be closed if you don't intend to leave it open as a reminder to improve clarity.

**Comment by sujayvenaik** [comment] 2018-08-02 07:29
@heath3n 

Sure.

Closing it now. We already have this noted on our road map.

**Comment by jolsen71** [comment] 2018-09-19 13:15
This issue caused me some grief as well; I was expecting the tab's "duplicate" to do what the sidebar's "duplicate" does, so after I made a duplicate via the tab menu, I changed all values I wanted to change and saved it--only to later realize I destroyed the original values. 

I'm not sure I see the value in having two or more tabs open to the same request, since it doesn't seem like you can drag the tabs out to a new window or view more than one tab at once, but I am very admittedly very, very new to Postman.

I'd suggest making "duplicate" behavior consistent, so it does the same thing on a request no matter what context. Perhaps "Clone View" might be a better name for "Duplicate" in tab context, or "Create Copy" would be a better name in the sidebar. 

This will be a confusing issue for all new users and something should be done to make it more obvious of what the menu item is going to do so mitigate the potential for frustrating new users.

Thanks for listening :)

**Comment by cnanney** [comment] 2019-08-12 17:11
This is very poor UX and just caused me some grief - was just about to open a ticket for it. Why would some duplicate tabs stay linked to parent and not others, based on which "Duplicate" button you click?

**Comment by alexanderankin** [comment] 2020-10-13 18:58
October of 2020 this is still an issue - the word CONFLICT appears on the original tab, but the new tab still overwrites - duplicate tab is still associated with the json entry in the configuration.

**Comment by DannyDainton** [comment] 2022-07-04 14:25
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/7350

**Closed as completed by DannyDainton** 2022-07-04 14:25 UTC
Labels: feature, tabs, duplicate
