### ISSUE TITLE
Missing secure cookies in v6.1.3

### ISSUE THREAD

**Issue by MatveyNeyman** [a85/POSTMan-Chrome-Extension#4621] opened 2018-05-30 10:25 UTC
Bug description:
Unable to find cookies with 'secure=true' attribute in the 'manage cookies' modal.

To Reproduce:
1. Make some request to server that returns some 'secure=true' and 'secure=false' cookies
2. Verify that all cookies are presented in 'cookies' tab of response
3. Open 'manage cookies' window
4. See that only 'secure=false' cookies are here

Expected behavior:
All cookies are presented

App information:
 - Native App
 - Postman Version 6.1.3
 - OS: macOS Sierra 10.12.6

**Comment by harryi3t** [comment] 2018-05-30 12:04
duplicate of https://github.com/postmanlabs/postman-app-support/issues/4581

**Closed as completed by harryi3t** 2018-05-30 12:04 UTC
