### ISSUE TITLE
mac v7.1.1 crash 

### ISSUE THREAD

**Issue by hvritual** [a85/POSTMan-Chrome-Extension#6558] opened 2019-05-21 05:36 UTC
after auto update v7.1.1,  run app is normal, but post api request eg.(https://www.baidu.com) ,it's crash and not any output log(maybe I can't find), 
normal api before update also can't request, dut to crash.

runtime environment: mac mojave 10.14.4

**Comment by numaanashraf** [comment] 2019-05-21 06:24
@hvritual We are having trouble reproducing this at our end. It'll help a lot if you could send us the application logs found in `View > Developer > View logs`. Please send these logs to `help@getpostman.com` with the subject "Logs for GH#6558"

**Comment by numaanashraf** [comment] 2019-05-22 10:24
Thanks for the logs @hvritual. I've added a screenshot of the crash I noticed in the logs here. We'll get this addressed in upcoming releases.

<img width="803" alt="Screenshot 2019-05-22 at 3 53 58 PM" src="https://user-images.githubusercontent.com/3295568/58167565-d8324080-7ca9-11e9-889c-23cf4eb6bf72.png">

**Comment by hvritual** [comment] 2019-05-23 05:56
This problem should be related to request url escape ,like http://www.baidu.com escape %20http://www.baidu.com, and application will crash

**Comment by tanistra** [comment] 2019-06-07 11:20
the same problem but with ` or ' character before url

**Comment by codenirvana** [comment] 2019-06-11 10:41
Duplicate of #6533

**Closed as completed by codenirvana** 2019-06-11 10:41 UTC
Labels: bug, product/runtime
