### ISSUE TITLE
Add Workspace name and/or Collection name to Titlebar text in desktop GUI

### ISSUE THREAD

**Issue by kevenwebb** [a85/POSTMan-Chrome-Extension#9793] opened 2021-04-04 20:55 UTC
I use Chrometa for automatic time-tracking (on Windows), and it records the name of the executable program and the dialog Titlebar text to summarize time spent using a particular application.

- For Postman, the Titlebar only shows "Postman" where other tools might show "Visual Studio 2019 - c:\projects\projectname\Widget.cs".

I would like to see Postman desktop app update the Titlebar text with at least the Workspace name.
- Ideally, it would also include the Collection name or other related tasks.
- This would be helpful to anyone using Chrometa or other time-tracking apps that use a similar technique.

I see that this happens now in the browser experience.

**Comment by numaanashraf** [comment] 2021-04-13 12:43
Duplicate of #6291

**Closed as completed by numaanashraf** 2021-04-13 12:43 UTC
Labels: user-interface, duplicate, product/client-foundation
