### ISSUE TITLE
Open requests in new tab

### ISSUE THREAD

**Issue by ohadmuch** [a85/POSTMan-Chrome-Extension#1945] opened 2016-03-29 21:58 UTC
First of all, you have a great app keep up with the good work.
When i open an existing request in a collection it's opened on the current focused tab , overriding the last request I used.
It will be more efficient if each request will be opened in new tab.
Thanks

**Comment by gogonutsss** [comment] 2016-04-08 21:03
Any news on thisss?

**Comment by tribou** [comment] 2016-04-18 13:22
I thought this option had been implemented previously, but it's now gone in the latest version.  Are there plans to bring it back?  The current functionality of editing multiple routes in the same tab is extremely error-prone causing the wrong routes to be changed.

**Comment by mdaloia** [comment] 2016-05-05 18:43
I have lost unsaved opened tabs that I was using because of this annoying usability issue because it replaces the tab without any warning and you can undo it.

**Comment by BlueInt32** [comment] 2016-05-13 06:16
+1 The tabs and requests being edited in postman currently do not behave like tabs in any other application that make use of tabs (IDE, internet browsers, ...), but we can see it's being improved. 
Anyway we are so used to the "hard" link between the tab and its content that it makes postman quite disconcerting. It comes from the fact that a new tab is opened only if the current tab has unsaved changes, else it changes the current tab data.
A request should be opened in a tab just like a file would be opened in an IDE  :
- clicking a request automatically opens a new tab or switches to the tab that's already editing it. This should never modify an other request's tab data.
- this should be impossible to have 2+ tabs editing the same request

**Comment by aditikul** [comment] 2016-08-01 12:28
@BlueInt32 @mdaloia @tribou @gogonutsss @ohadmuch You can open a request in a new tab with Cmd/Ctrl+Shift+Click when you select a request in the sidebar. You can also open the same request in multiple tabs now. This should help. We allow opening the same request in multiple tabs to give people freedom to add modifiers/compare etc while working.

**Comment by mdaloia** [comment] 2016-08-01 12:45
@aditikul thanks for pointing that out but I (personally) think that it isn't a complete solution because:
- No chance to configure opening in a new tab by default (I need to remember to press a combination of keys each time).
- It still doesn't warn you when you have an unsaved open tab that you will lose the info (when you modify a saved request and select another saved request it opens in a new tab).

**Comment by aditikul** [comment] 2016-08-01 12:50
@mdaloia Noted. For the second point, let me check on that. The app should definitely warn you and prevent you from losing unsaved changes. Thanks for pointing it out.

**Comment by BlueInt32** [comment] 2016-08-23 09:55
@aditikul you said "You can also open the same request in multiple tabs now. This should help." but I personnally think this in particular represents an UX anti-pattern. Would you agree if notepad++ or VSCode or any text editor you use let you open the same file in multiple tabs ? I don't think so, because then you would have desynchronizations very fast.

**Comment by a85** [comment] 2016-11-09 06:34
@BlueInt32 Options and better behavior coming up in 4.9.

**Comment by SamvelRaja** [comment] 2016-12-02 13:59
Here All, Opening request in new tab has been landed in 4.9.0, we provided the explicit settings to enable this feature in the app, as _Settings -> General -> Always opens requests in new tab_ 😄

**Comment by amirabiri-odoro** [comment] 2017-01-14 15:57
The new behaviour is still not what I was looking for.

I think there are 2 or 3 different ways that folks conceptualise tabs when they don't represent "hard" things such as a file. I think XCode suffers from the same problem.

I think in general there are two basic tab behaviours:
 - Tab is "hard" linked to object being opened, and opening said object again will simply switch to the tab where the file is opened. This is like files in an IDE and the tab is essentially not something you think about - you think about open files.
 - Tab is something of its own and not linked to the object opened in it. Whatever happens - opening a new or already opened object - you stay within the same tab. This is like browser tabs. If you open a new tab and click on a bookmark of a site already open in another tab - it would make no sense to switch to that other tab.

I think the problem is that some folks think about postman saved requests as IDE files, and some folks think about the postman tabs more like the browser tabs. I for example belong to the later group and the current behaviour drives me mental.

This is due to the fact that I use the saved requests more like "templates", i.e I open let's say "get book" which is `GET .../books/1`, but I actually want to `GET` book 32. And then I want to open another tab and `GET` book 783. You can quickly see why the current behaviour would drive me mental - the app keeps switching me to other tabs in a way that I'm no expecting. I want to stay within the same tab and decide what to do in it like I would with a browser tab.

Of course for people who use the saved requests like files in an IDE it would be complete opposite - they would *never* want to change the contents of the current tab, they want each saved request to always be open in a single tab, and if it is clicked again then just switch to that tab - like files in an IDE. Any kind of reusing same tab again, regardless of circumstances - would drive them mental.

Current behaviour is mishmash of both due to an attempt to merge both approaches, and it drives everyone mental. There should be a preference for clearly switching between either "files in an IDE" or "browser tabs" behaviour, and stick to that.

(The new "always open in a new tab" switch is basically "files in an IDE", now we are missing the "browser tabs" mode).

**Comment by amirabiri** [comment] 2017-01-14 16:01
The new behaviour is still not what I was looking for.

I think there are 2 or 3 different ways that folks conceptualise tabs when they don't represent "hard" things such as a file. I think XCode suffers from the same problem.

I think in general there are two basic tab behaviours:
 - Tab is "hard" linked to object being opened, and opening said object again will simply switch to the tab where the file is opened. This is like files in an IDE and the tab is essentially not something you think about - you think about open files.
 - Tab is something of its own and not linked to the object opened in it. Whatever happens - opening a new or already opened object - you stay within the same tab. This is like browser tabs. If you open a new tab and click on a bookmark of a site already open in another tab - it would make no sense to switch to that other tab.

I think the problem is that some folks think about postman saved requests as IDE files, and some folks think about the postman tabs more like the browser tabs. I for example belong to the later group and the current behaviour drives me mental.

This is due to the fact that I use the saved requests more like "templates", i.e I open let's say "get book" which is `GET .../books/1`, but I actually want to `GET` book 32. And then I want to open another tab and `GET` book 783. You can quickly see why the current behaviour would drive me mental - the app keeps switching me to other tabs in a way that I'm no expecting. I want to stay within the same tab and decide what to do in it like I would with a browser tab.

Of course for people who use the saved requests like files in an IDE it would be complete opposite - they would *never* want to change the contents of the current tab, they want each saved request to always be open in a single tab, and if it is clicked again then just switch to that tab - like files in an IDE. Any kind of reusing same tab again, regardless of circumstances - would drive them mental.

Current behaviour is mishmash of both due to an attempt to merge both approaches, and it drives everyone mental. There should be a preference for clearly switching between either "files in an IDE" or "browser tabs" behaviour, and stick to that.

(The new "always open in a new tab" switch is basically "files in an IDE", now we are missing the "browser tabs" mode).

**Comment by a85** [comment] 2017-01-14 16:17
@amirabiri You are right about the issue. There are several ways people try to think about tabs but the current behavior is the most stable so far and we haven't seen any issue from users post 4.9.

Double clicking the request will always open a request in a new tab even if it is open previously - as many times as you want. Have you tried that?

**Comment by amirabiri** [comment] 2017-01-14 16:36
@a85 The new behaviour is exactly the opposite of what I want... I'm a "browser tabs" guy. I want to **always** stay in my current tab, regardless of circumstances. Never open in a new tab or switch to an already open one.

**Comment by a85** [comment] 2017-01-14 16:43
@amirabiri Ok. If I understand that properly, you want to create a new tab and load things in the tab regardless of what has happened in the tab previously?

**Comment by amirabiri-odoro** [comment] 2017-01-14 16:44
@a85 Exactly. I think of my tabs like browser tabs, and I think of my saved requests like bookmarks.

**Comment by amirabiri** [comment] 2017-01-14 16:45
@a85 Exactly. I think of my tabs like browser tabs, and I think of my saved requests like bookmarks.

**Comment by a85** [comment] 2017-01-14 16:58
@amirabiri I agree on how you can think of them as browser tabs but Postman is not a browser. Your saved requests have a co-relation with the content that loads in the tab unlike a web browser - which just loads that URL and doesn't care about what you do in it. In Postman, if you want to use requests as templates, just double clicking will ensure that you don't lose your work/responses in the current tab and you have your pre-filled request as a starting point for the new request. 

As a tab's content is related to the saved request, let's say we trust users to know that they remember to open a new tab when they don't want to lose their changes or remove whatever is displayed there. If they do lost stuff in the tab, then it's their fault - which is how browser tabs work.

The solution probably is yet-another-mode for people who don't want to use the double-click option, are ok with losing changes and are always going to use Postman in that mode. 

We have been shuttling back and forth on this topic because everybody cites their mode of thinking as the correct one. Point taken though.

**Comment by amirabiri** [comment] 2017-01-14 17:06
@a85 Citing one's mode of thinking as correct is counter-productive. We should identify the N different modes of thinking and cater to them, not force some users into other users' mode of thinking.

As for your point about the link between the tab and its content, you are right in that it does pose an issue. The indicator and warning about unsaved changes is indeed helpful. However I think that in "browser tabs" mode, the default behaviour should gravitate more towards always "save as" + a warning about loosing content with a "don't show this warning again" checkbox. Or something along those lines.

**Comment by a85** [comment] 2017-01-14 17:20
@amirabiri Yeah I agree. I was referring to our existing solutions where we thought we could go with one solution. We changed the behavior and added an option in 4.9. There will always be multiple modes of thinking and as a rule Postman never forces anyone in a particular way. That's the reason Collections can be used as saved request templates, API descriptions, test suites, workflows or just bookmarks. :)

My primary worry is a user losing their changes to saved requests. Again, we could create modes upon modes (always open in the current tab + ignore warnings). It puts extra cognitive load for every interaction (this time I want to override, this time I don't want to override).

**Comment by BlueInt32** [comment] 2017-01-14 23:02
This is a very interesting discussion about how postman should behave, I'd personnally never thought there could be people thinking about postman requests just as browser bookmarks.
In my opinion the current behavior is mildly contenting everyone but in the end the danger is that nobody can map postman's behavior to any "mainstream" tab management system (browser bookmark VS IDE file). I think Postman should just make a clear choice and stick to it. Or propose a setting as @amirabiri suggested.
I have a strong opinion about the subject (I'd chose IDE mode) because a postman request contains way more that a browser's bookmark (i.e. name, folder, url). It contains many things, especially code. In a parallel universe if Chrome would let you edit your favorite webpage's HTML, they surely wouldn't let you lose all your changes by just clicking once on another bookmark !
As of today if I understand it well, postman requests are loading like browser's bookmarks (in the same tab) as long as the requests are not modified. But whenever a request is "dirtied", it sticks in the tab like a file. This means the mode actually changes dynamically without the user being notified ; this is a bit puzzling. 

Thus I agree there should be a dedicated setting.

**Comment by amirabiri** [comment] 2017-01-15 13:43
@BlueInt32 You are right in everything you say, but there is one significant detail here - although postman saved requests are potentially quite complex beasts, some of us use only a small subset of the features thus for us they are closer to bookmarks.

So for example in my personal collection I have a few typical CRUD APIs that I'm developing. So I have a `GET` a `POST` and a `PUT` usually per API. When I use the `GET`s for example, the ID is almost never the same. And when I am working on some issue, I potentially want to open 2-3 tabs each with the same `GET` saved request but change the ID in each one because these are the 2-3 entities I'm currently monitoring. Additionally I may open 2-3 `PUT`s for updating some objects. I will tweak the URL and the bodies but again all based on same template. Oh and throw a `POST` or 2 into the mix...

All this time the saved requests save me a lot of time and effort because I usually have a few headers that must be set, from content type to authentication. The prepared bodies in the `PUT`s and the `POST`s also save me time, but I also almost always want to tweak the values. Yet I almost never want to save my changes - it makes almost no sense in 99% of cases, unless I'm changing the "template" (But a warning about loosing changes or at least an indicator is still useful for me in those cases were I may want to save something to the template before closing).

As you can see I don't use the Pre-req, tests, code etc (I'm sure these are cool useful features, but it's just not what I use Postman for).

And whatever happens, if I am in one tab and I want to reuse it for a different "bookmark" the last thing I want is that when I click on something else in my collection to be thrown to one of the other open tabs - and then worse - have the contents of **that** tab replaced when I click again on something else in my collection.

I think there are a few ways to help users with a workflow like mine, and "browser tabs" mode is just one of them. Another approach could have been actually supporting templates perhaps. Or maybe have two types of saved requests somehow and let that dictate the tab behaviour - i.e "bookmark" type and "file" type (obviously with better names). The "bookmark" can then have the features cut down perhaps if that helps in any way. Just ideas anyway.

**Comment by mdaloia** [comment] 2017-01-15 18:03
With all the respect and appreciation of this really good tool I will give my impressions.

I think that the root of the problems is that the Collections panel has 2 behaviors/purposes:

1. It is a list of saved request / bookmarks / templates / whatever-you-want-to-call-it
2. It is used like an Opened tabs manager (when you click on a saved request it tries opens a new tab or focus to an open instance of it).

I have made a summary (see tables below) of all the current options (`Click`, `Double-Click`, `Cmd/Ctrl+Shift+Click`, `Always open requests in new tab` option) and different scenarios with the current and (_what I think is)_ the expected behavior.

I think that the current behavior it is not consistent and also there are some behavioral bugs in the current tabs management (shown as **[BUG]** in the tables).

#### `Always open requests in new tab` option = **ON**

Tabs opened                  | Tab focus                  | I want to open a ...             | Click<br/>(Current behavior)                           | Double-Click<br/>(Current behavior)                           | Cmd/Ctrl+Shift+Click<br/>(Current behavior)                           | Click<br/>(Expected behavior)                           | Double-Click<br/>(Expected behavior)                           | Cmd/Ctrl+Shift+Click<br/>(Expected behavior)                          
--- | --- | --- | --- | --- | --- | --- | --- | ---
New Tab (blank) | New Tab (blank) | Saved request | Replaces the blank tab | Replaces the blank tab and opens a second tab **[BUG]** | Opens a second tab with the saved request | Replaces the blank tab | Replaces the blank tab | Opens a second tab with the saved request
New Tab (dirty) | New Tab (dirty) | Saved request | Replaces the unsaved tab losing all the work without any warning **[BUG]** | Replaces the unsaved tab losing all the work without any warning and opens a second tab **[BUG]** | Opens a second tab with the saved request | Opens a second tab with the saved request | Opens a second tab with the saved request | Opens a second tab with the saved request
Saved request A (dirty or not) | Saved request A (dirty or not) | Saved request A | Nothing happens | Opens a second tab with the saved request A | Opens a second tab with the saved request A | Nothing happens | Opens a second tab with the saved request A | Opens a second tab with the saved request A
Saved request A (dirty or not) | Saved request A (dirty or not) | Saved request B | Opens a second tab with the saved request B | Opens a second and a third tab with the saved request B **[BUG]** | Opens a second tab with the saved request B | Opens a second tab with the saved request B | Opens a second tab with the saved request B | Opens a second tab with the saved request B
Saved request A (dirty or not)<br/>New Tab (blank or dirty) | New Tab (blank or dirty) | Saved request A | Changes focus to the already opened saved request A | Briefly changes the focus to the already opened saved request A **[BUG]** and later opens a third tab with the saved request A | Opens a third tab with the saved request A | Changes focus to the already opened saved request A | Opens a third tab with the saved request A | Opens a third tab with the saved request A
Saved request A (dirty or not)<br/>New Tab (blank or dirty) | New Tab (blank or dirty) | Saved request B | Opens a third tab with the saved request B | Opens a third and a fourth tab with the saved request B **[BUG]** | Opens a third tab with the saved request B | Opens a third tab with the saved request B | Opens a third tab with the saved request B | Opens a third tab with the saved request B


#### `Always open requests in new tab` option = **OFF**

Tabs opened                  | Tab focus                  | I want to open a ...             | Click<br/>(Current behavior)                           | Double-Click<br/>(Current behavior)                           | Cmd/Ctrl+Shift+Click<br/>(Current behavior)                           | Click<br/>(Expected behavior)                           | Double-Click<br/>(Expected behavior)                           | Cmd/Ctrl+Shift+Click<br/>(Expected behavior)                          
--- | --- | --- | --- | --- | --- | --- | --- | ---
New Tab (blank) | New Tab (blank) | Saved request | Replaces the blank tab | Replaces the blank tab and opens a second tab **[BUG]** | Opens a second tab with the saved request | Replaces the blank tab | Replaces the blank tab | Opens a second tab with the saved request
New Tab (dirty) | New Tab (dirty) | Saved request | Replaces the unsaved tab losing all the work without any warning **[BUG]** | Replaces the unsaved tab losing all the work without any warning and opens a second tab **[BUG]** | Opens a second tab with the saved request | Warns that you will lose the data if you continue | Opens a second tab with the saved request | Opens a second tab with the saved request
Saved request A (not dirty) | Saved request A (not dirty) | Saved request A | Nothing happens | Opens a second tab with the saved request A | Opens a second tab with the saved request A | Nothing happens | Nothing happens | Opens a second tab with the saved request A
Saved request A (dirty) | Saved request A (dirty) | Saved request A | Nothing happens | Opens a second tab with the saved request A | Opens a second tab with the saved request A | Nothing happens | Opens a second tab with the saved request A | Opens a second tab with the saved request A
Saved request A (not dirty) | Saved request A (not dirty) | Saved request B | Replace the saved request A with the saved request B | Replace the saved request A with the saved request B and opens a second tab with the saved request B **[BUG]** | Opens a second tab with the saved request B | Replace the saved request A with the saved request B | Replace the saved request A with the saved request B | Opens a second tab with the saved request B
Saved request A (dirty) | Saved request A (dirty) | Saved request B | Opens a second tab with the saved request B | Opens a second and a third tab with the saved request B **[BUG]** | Opens a second tab with the saved request B | Opens a second tab with the saved request B | Opens a second tab with the saved request B | Opens a second tab with the saved request B
Saved request A (not dirty)<br/>New Tab (blank or dirty) | New Tab (blank or dirty) | Saved request A | Changes focus to the already opened saved request A | Briefly changes the focus to the already opened saved request A **[BUG]** and later opens a third tab with the saved request A | Opens a third tab with the saved request A | Changes focus to the already opened saved request A | Changes focus to the already opened saved request A | Opens a third tab with the saved request A
Saved request A (dirty)<br/>New Tab (blank) | New Tab (blank) | Saved request A | Changes focus to the already opened saved request A | Briefly changes the focus to the already opened saved request A **[BUG]** and later opens a third tab with the saved request A | Opens a third tab with the saved request A | Changes focus to the already opened saved request A | Replaces the blank tab | Opens a third tab with the saved request A
Saved request A (dirty)<br/>New Tab (dirty) | New Tab (dirty) | Saved request A | Changes focus to the already opened saved request A | Briefly changes the focus to the already opened saved request A **[BUG]** and later opens a third tab with the saved request A | Opens a third tab with the saved request A | Changes focus to the already opened saved request A | Opens a third tab with the saved request A | Opens a third tab with the saved request A
Saved request A (not dirty)<br/>New Tab (blank) | New Tab (blank) | Saved request B | Replace the blank tab with the saved request B | Replace the blank tab with the saved request B and opens a third tab with the saved request B **[BUG]** | Opens a third tab with the saved request B | Replace the blank tab with the saved request B | Replace the blank tab with the saved request B | Opens a third tab with the saved request B
Saved request A (not dirty)<br/>New Tab (dirty) | New Tab (dirty) | Saved request B | Replaces the unsaved tab losing all the work without any warning **[BUG]** | Replaces the unsaved tab losing all the work without any warning and opens a third tab with the saved request B **[BUG]** | Opens a third tab with the saved request B | Opens a third tab with the saved request B | Opens a third tab with the saved request B | Opens a third tab with the saved request B
Saved request A (dirty)<br/>New Tab (blank) | New Tab (blank) | Saved request B | Replace the blank tab with the saved request B | Replace the blank tab with the saved request B and opens a third tab with the saved request B **[BUG]** | Opens a third tab with the saved request B | Replace the blank tab with the saved request B | Replace the blank tab with the saved request B | Opens a third tab with the saved request B
Saved request A (dirty)<br/>New Tab (dirty) | New Tab (dirty) | Saved request B | Replaces the unsaved tab losing all the work without any warning **[BUG]** | Replaces the unsaved tab losing all the work without any warning and opens a third tab with the saved request B **[BUG]** | Opens a third tab with the saved request B | Opens a third tab with the saved request B | Opens a third tab with the saved request B | Opens a third tab with the saved request B


As you can see when the `Always open requests in new tab` option is `OFF` the complexity is increased.

In order to have a more consistent and greatly simplified behavior you could:
- Get rid of the `Always open requests in new tab` option and asume it like it is always `ON`
- Get rid of the `Double-Click` event

**Some notes:**
- Personally I would go with having a "browser like" tab management but with the difference (this is the "files like" part) that if the current focused tab is dirty (does not matter if it is already saved in a collection or not) and you want to replace it I would be warned that I will lose data.
- As a general rule **you wouldn't let the users to lose information if the tab is dirty** (if the user is super confident of what he always does you can provide a configuration option that don't ask them to confirm it).
- All of this is also happens with the `History` list.

**Comment by a85** [comment] 2017-02-04 01:22
@mdaloia Thank you so much for the table! Helps a lot. We are cleaning up all these flows with the general principle of not to lose any user data by default.

**Comment by a85** [comment] 2017-03-10 15:57
@madebysid @vegetableman Can we review the table once again?

**Comment by sdnts** [comment] 2017-03-17 13:03
@a85 For sure

**Comment by a85** [comment] 2017-12-11 13:51
Most of these changes have been implemented. The app also has a setting to always open a request in a new tab. Closing this issue now!

**Closed as completed by a85** 2017-12-11 13:51 UTC
Labels: tabs
