### ISSUE TITLE
TypeError: Cannot read property XXXXX" of undefined

### ISSUE THREAD

**Issue by leonardocsobral** [a85/POSTMan-Chrome-Extension#5105] opened 2018-08-28 20:36 UTC
**Describe the bug**
If we want to validate if some object is undefined. Postman cannot handle it.

**To Reproduce**
1. Open application
2. create a test similar to this one:
`let jsonData = pm.response.json();
let resultDetails = jsonData.resultDetails;
let result = jsonData.result;

if (resultDetails.acquirerTxId2 !== undefined){
    pm.test("acquirerTxId2 should not be Null", function(){
   pm.expect(resultDetails.acquirerTxId2).to.not.be.null;
});
    } else {
        pm.test("acquirerTxId2 should not be undefined", function(){
   pm.expect(resultDetails.acquirerTxId2).to.not.be.undefined;
});
    }
`

**Expected behavior**
The application should understand that an object is undefined.

**Screenshots**
![image](https://user-images.githubusercontent.com/10927062/44749393-bb852580-aae8-11e8-9c08-8518a548f893.png)

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version 6.2.5
 - OS:Ubuntu 18.04

**Additional context**

**Comment by kamalaknn** [comment] 2018-08-30 09:34
@leonardocsobral 

The error you are seeing is telling you that you are trying to access a property on an `undefined` value. You can still check if a property is `undefined` or not in Postman.

**The point to note here is that `resultDetails` is also `udnefined` and that is why `resultDetails.acquirerTxId2` is not allowed. Not because `acquirerTxId2` is `undefined`.**

You can easily workaround this be first checking if `resultDetails` exists.

```js
pm.test("resultDetails should be ok", function(){
  pm.expect(resultDetails).to.be.ok;
});

pm.test("acquirerTxId2 should be ok", function(){
  pm.expect(resultDetails.acquirerTxId2).to.be.ok;
});
```
I'm closing this because this is not a bug with Postman.

**Closed as completed by kamalaknn** 2018-08-30 09:34 UTC
