### ISSUE TITLE
Postman console - copy-paste bug

### ISSUE THREAD

**Issue by Anwartest** [a85/POSTMan-Chrome-Extension#7786] opened 2019-12-12 09:41 UTC
Hello!
I am sorry - my so-so english. (i am free write - russian language)
I am find new bug in the Postman Console window.

when postman have more 30 rows string text (very many, no a little) - i do Select All (Ctrl+A) and Copy (Ctrl+C). Then i paste text in notepade - and i see not all copy and pasted. On postman console - if i go page down on last row - and Select All and Copy - only then - it correctly Copy and Paste - all text in console to Notepad. Please fix bug.

you find this bug - when very more row text on Console window - and Console window is small (not Full size screen) when little Screen size)

Thank You All.
Your user.

**Comment by ritwijsinha** [comment] 2019-12-12 10:36
Duplicate of #7685

**Closed as completed** 2019-12-12 10:36 UTC
Labels: duplicate, product/runtime
