### ISSUE TITLE
POSTman killing CPU

### ISSUE THREAD

**Issue by Redsandro** [a85/POSTMan-Chrome-Extension#1996] opened 2016-04-14 12:21 UTC
Somewhere along the way this POSTman new version started to idle using ~55% of my CPU. (Just about one core + overhead I guess.) Not always, but often. This is making my laptop very hot and draining my battery. Killing the app and using an alternative is my current workaround. But I'm not a fan. :sunglasses: 

POSTman 4.1.3 (but I reckon it happens for multiple versions now)
Google Chrome Version 49.0.2623.112 (64-bit)
Linux Mint 17.3 (AKA Ubuntu 14.04.3 LTS)

**Comment by numaanashraf** [comment] 2016-04-14 12:37
@Redsandro That's odd. Does CPU usage spike only when you perform specific actions or is it always idling at 55%?

**Comment by Redsandro** [comment] 2016-04-14 13:27
Not always. Only on the first start when I do nothing. I have a script that starts a bunch of apps including POSTman for developing projects.

`exec chromium-browser --app-id=fhbjgbiflinjbdggehcddcbncdddomop`

I just noticed that I can restart POSTman after closing it, and then it doesn't idle at 55%. Perhaps it has something to do with the sync function of request data, or the way it's started.

**Comment by Redsandro** [comment] 2016-04-14 20:35
Something I noticed today.

![image](https://cloud.githubusercontent.com/assets/1702193/14542237/3bf21706-028e-11e6-8daf-b4c63d67ca98.png)

The first entry looks like the browser, but it starts at the same time as Postman. When I end the process, both Postman (and the killed process) alleviate the CPU. At the same time I get a chrome popup "GoogleDrive has crashed. Click here to restart."

It's important to notice that starting Postman starts the second chromium-browse thread, which in turn causes the normal Chrome browser to also use more CPU. Killing Postman or the CPU eating process causes everything to settle down.

**Comment by numaanashraf** [comment] 2016-04-15 08:44
@Redsandro Could you check Chrome's task manager and let us know how much resource Postman is consuming?

![chrometaskmanager](https://cloud.githubusercontent.com/assets/3295568/14556128/2e43d082-0314-11e6-84fa-60ed68737333.gif)

**Comment by Redsandro** [comment] 2016-04-15 09:26
Yeah I tried that before. `shift` + `escape`. But it doesn't show up in there. There are extensions, tabs, GPU, browser, but no POSTman background page. I'm probably missing a step.

**Comment by Redsandro** [comment] 2016-04-15 09:30
Update:

I noticed that although my default browser is Google Chrome Version 49.0.2623.112, the Postman app is running on Chromium Version 49.0.2623.108. Can I change this somewhere?

**Comment by czardoz** [comment] 2016-04-15 12:37
@Redsandro how do you have multiple versions of Chrome on your system? 

I'm guessing one is Chromium Browser and another is Google Chrome. Is that correct?

**Comment by Redsandro** [comment] 2016-04-15 12:48
Yes. I have Chrome and Chromium. I use Chrome, but I guess when I installed Postman I installed it from Chromium.

**Comment by czardoz** [comment] 2016-04-15 13:28
Do you see high CPU usage with Google Chrome too?

**Comment by Redsandro** [comment] 2016-04-15 14:09
Yes, I see high usage among all three processes, and they all stop if I kill either the Postman app, or the Chrome/ium instance that does the Google Cloud syncing.

Also, I need to figure out how to run/install Postman from Chrome rather than Chromium.

**Comment by numaanashraf** [comment] 2016-04-15 14:24
You can install Postman on Chrome by visiting this URL: https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop

(You'll have to open the URL in Chrome)

**Comment by czardoz** [comment] 2016-04-15 14:33
To add to that, once you install Postman on Chrome, do the following:
1. Open Chrome browser
2. Enter `chrome://extensions` in the URL bar, and hit enter
3. Click on "Postman"
4. Hit `Shift+Esc` to bring up the Chrome's Task Manager
5. Take a screenshot and post it here

This will help us to check Postman's resource usage :-)

**Comment by Redsandro** [comment] 2016-04-18 11:38
It only seems to happen the first time I start Postman after I've rebooted.

I've been busy. I know rebooting only takes a minute. You know this thing where you're working on a project and you only put your laptop in sleep mode otherwise you have to open all the programs and sessions you've been using again. Some call it lazy, others call it clever. I will get back to this. :smiley:

**Comment by czardoz** [comment] 2016-04-18 11:47
Sure!

I'm pretty sure this has nothing to do with Postman though. Linux has had notorious problems with suspend/hibernate for a long time (My own laptop cannot resume if suspended for a long time). It's a functionality that comes from the Kernel in conjunction with a number of device drivers. Postman has no control over these unfortunately.

**Comment by Redsandro** [comment] 2016-04-23 12:56
![image](https://cloud.githubusercontent.com/assets/1702193/14761476/0fb88d10-0963-11e6-8848-e11b0ca7ed06.png)

![image](https://cloud.githubusercontent.com/assets/1702193/14761489/5ed3f812-0963-11e6-9df3-117e869c6bd6.png)

Perhaps it has nothing to do with Postman per se, but it happens exclusively when I start Postman for the first time after a reboot. Could it have something to do with the browser syncing Postman data?

**Comment by mikehedman** [comment] 2017-02-10 07:38
I have noticed this for quite some time.  Postman is very often the most active app running on my Mac (even when I haven't touched it for hours).

![image](https://cloud.githubusercontent.com/assets/1550290/22818212/ccb2d3dc-ef20-11e6-9c32-f0c8190bfa4f.png)

That screenshot is pretty common for me.  I used Postman for a few minutes earlier in the day, but hours later it's still chugging along at 10-15% of my CPU.

**Comment by renatomariscal** [comment] 2017-03-21 17:44
It just happened to me, I noticed that Mac was heating since I wake it up; After 1 hour decided to check the system monitor. A "Google Chrome Helper" was consuming 110% of CPU, killed it and Postman crashed.

**Comment by adnansinanovic** [comment] 2017-06-09 15:38
![image](https://user-images.githubusercontent.com/27208956/26982863-12ea9bce-4d3a-11e7-9b03-b9d3e3dace84.png)

Occurs very often.

**Comment by PKPublicCode** [comment] 2018-02-24 00:07
Postman for Windows, Version 6.0.6, win32 10.0.16299 / ia32
98% CPU usage. 100% reproducibility. Impossible to use app at all.
Steps.
Install postman.
Launch postman
Actual result: 6 child postman processes kills CPU.
Expected result: Possible to use application

**Comment by s1mar** [comment] 2018-02-24 06:37
@pavelkruglov I second that, after launching the postman application, the child processes, consume all the cpu and basically kill it. 

machine spec:
------------------
System Information
------------------
      Time of this report: 2/24/2018, 12:08:21
             Machine name: LAPTOP-CEVMV80B
               Machine Id: {598DBB0E-BDFE-4E14-A348-8FF56201642D}
         Operating System: Windows 10 Home 64-bit (10.0, Build 16299) (16299.rs3_release.170928-1534)
                 Language: English (Regional Setting: English)
      System Manufacturer: Razer
             System Model: Blade Stealth
                     BIOS: 1.1
                Processor: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 CPUs), ~2.9GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16282MB RAM
                Page File: 8120MB used, 11105MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 192 DPI (200 percent)
       System DPI Setting: 240 DPI (250 percent)
          DWM DPI Scaling: Enabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.16299.0015 64bit Unicode

**Comment by GermaineG** [comment] 2018-02-24 11:52
Can completely confirm @pavelkruglov with the x64 version on Windows 10. Freshly installed today, v6.0.6.,
6 postman processes and 99% CPU usage after launch.

**Comment by s1mar** [comment] 2018-02-24 11:55
I have reverted to the chrome app version of postman for now, it works

**Comment by smushy129** [comment] 2018-02-24 17:05
Any fix for this? Just installed the latest version of postman on getpostman.com and I'm getting 100% CPU usage and fans spinning like wind turbines because the laptop is heating up. I'm not even doing anything, just starting the app.

![screen shot 2018-02-24 at 12 02 41 pm](https://user-images.githubusercontent.com/19790133/36632927-de476710-195a-11e8-9aa3-bc70b3cb2f8c.png)

**Comment by s1mar** [comment] 2018-02-24 17:08
@kingsleyliao The chrome web app version works without such a glitch, you can use that in the meanwhile

**Comment by numaanashraf** [comment] 2018-02-24 18:10
@pavelkruglov @s1mar @kingsleyliao @GermaineG Thanks for reporting this. We can confirm there is a performance issue in Postman 6.0.x version which affects users without an account or while the application is trying to connect to our sync service. We are working on rolling out a fix for this as soon as possible.

**Comment by numaanashraf** [comment] 2018-02-24 19:12
@pavelkruglov @s1mar @kingsleyliao @GermaineG We've rolled out the fix in the latest version on our Canary channel (v6.0.7-canary01) - https://www.getpostman.com/canary. Would it be possible to download the Canary app and let us know if the issue is resolved at your end?

**Comment by markatwork8823** [comment] 2018-02-25 00:17
@numaanashraf This worked for me! CPU was killing my VM and POSTs were taking ages but all good now!

Thank you

**Comment by PKPublicCode** [comment] 2018-02-25 11:53
I don't know if canary had a CPU problem. But I can confirm that issue with 100% CPU is not repro on my PC with Canary downloaded by your link

**Closed as completed** 2018-05-14 08:07 UTC
Labels: performance

**Comment by jgfet** [comment] 2019-06-18 12:50
I had the exact same issue today. When I tried to install Postman-win64-7.2.0-Setup.exe on a VM with Windows Server 2016 and Java 
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
it sent my VM into meltdown.
Had to kill VM a couple of times and reboot it.
I noticed after the install that Java was behaving erratically and 2 or 3 Java process were consuming 100% CPU.
After I uninstalled Postman, my VM returned to it's usual stable self.
Shame because I'd found it useful before on a Mac. Don't know what's happened - but this version of the product is useless now.

Right... Subsequently saw this [post](http://mahedee.net/how-to-install-postman-a-rest-client/).
It inferred you need Chrome installed first. When I did that sanity resumed.

**Comment by angrimer** [comment] 2019-08-19 14:43
I had this experience as well (since last week), driving me mad! CPU 50%+ when Postman is supposed to idle!

I'm on Postman 7.5.0 on Windows 10 (19H1) with plenty of collections.
I tried uninstalling, reinstalling both 32 and 64 bit versions without success.

HOWEVER, I FOUND A SOLUTION THAT WORKS FOR ME AT LEAST! :-)

The uninstall does not remove the local appdata cache and something in this Postman cache must have gone corrupt or an version upgrade not handling the old cache very well?! After deleting the directories below and reinstalling Postman again, everything went back to normal, Postman using 0% CPU when idling, hurray! And that is after logging in again and having restored all my collections from the cloud account.

C:\Users\username\AppData\Local\Postman
C:\Users\username\AppData\Roaming\Postman

Hope this might help somebody.

**Comment by dtate22** [comment] 2020-05-19 19:55
Still having this problem.
- Trying the solution above 
- Verified / Validated 5/19/2020 @ 3:52 pm

**Comment by arlemi** [comment] 2020-05-20 08:47
@dtate22 See #7294

**Comment by th3third** [comment] 2020-09-08 19:34
Confirmed that https://github.com/postmanlabs/postman-app-support/issues/1996#issuecomment-522606835 worked for me after I was seeing 20-40% constant CPU usage and noticeably slow UI interaction. Reinstalling didn't help until those folders were deleted.

I had this issue running the Windows 10 desktop 64-bit 7.32.0 version.

**Comment by contentfree** [comment] 2020-11-20 00:59
Postman.app (Version 7.34.0) is having a large enough impact on my 16" Macbook Pro that it wasn't even able to keep the battery charged (battery drain while plugged in). It was just sitting in the background having a massive energy impact. Fans running on high all day. 

I just quit it, relaunched it, put it in the background and waited a minute to settle down. Here's the processes as reported by Activity Monitor:

![image](https://user-images.githubusercontent.com/10958/99742633-c0976c00-2a88-11eb-81b3-7af54aa6dce5.png)

And here's the Energy Impact:

![image](https://user-images.githubusercontent.com/10958/99742572-a65d8e00-2a88-11eb-9346-a866ecfc0511.png)

This is a major issue.
