### ISSUE TITLE
Postman tries to auto-update when installed system-wide

### ISSUE THREAD

**Issue by bodograumann** [a85/POSTMan-Chrome-Extension#9465] opened 2021-01-26 14:20 UTC
**Describe the Issue**

Since version 8, postman tries to auto-update and fails, because it is installed system-wide on arch.

**Steps to Reproduce**

Install postman with:
```
git clone https://aur.archlinux.org/postman-bin.git
cd postman-bin
makepkg -sif
```

Then start postman.

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/1223583/105855973-f3119800-5fe8-11eb-9274-a2dcb95bb03a.png)

![image](https://user-images.githubusercontent.com/1223583/105856901-040ed900-5fea-11eb-8f0d-ed3e75f35bc2.png)

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: [8.0.1-1 from AUR](https://aur.archlinux.org/packages/postman-bin/)
 - Operating System: Arch Linux

**Additional Context**

If the auto-update can be disabled during installation this could be done in the AUR package.
Otherwise there should be at least an option to manually auto-updates even for minor versions.

**Comment by jviotti** [comment] 2022-02-08 11:56
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9910

**Closed as completed by jviotti** 2022-02-08 11:56 UTC
Labels: bug, platform/linux, product/desktop-foundation, version/8, component/auto-updates
