### ISSUE TITLE
POST method will automatically add 'undefined' param, in x-www-form-urlencoded format

### ISSUE THREAD

**Issue by pecliu** [a85/POSTMan-Chrome-Extension#5666] opened 2018-12-19 09:15 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
An 'undefined' param will be added, when use x-www-form-urlencoded POST method

**To Reproduce**
1. create a new api
2. change method to POST
3. add x-www-form-urlencoded key
4. send data
5. an ‘undefined’ param will be added to body

**Expected behavior**
No more 'undefined' param

**Screenshots**
![image](https://user-images.githubusercontent.com/8316744/50210499-45ffd680-03b1-11e9-913a-3b951fe3126e.png)

![image](https://user-images.githubusercontent.com/8316744/50210444-1bae1900-03b1-11e9-854f-e52ed642452f.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.6.1
 - OS: macOS High Sierra 10.13.2

**Additional context**

**Comment by numaanashraf** [comment] 2018-12-19 15:27
Duplicate of #5585

**Closed as completed by numaanashraf** 2018-12-19 15:27 UTC
Labels: duplicate
