### ISSUE TITLE
Dark Theme Response Bodies

### ISSUE THREAD

**Issue by benhamill** [a85/POSTMan-Chrome-Extension#2224] opened 2016-08-03 16:28 UTC
1. Postman Version: 4.5.0
2. App: Mac App
3. OS details: OS X 10.10.5 (14F27)
4. Is the Interceptor on and enabled in the app: I don't know.
5. Did you encounter this recently, or has this bug always been there: Showed up after updating today.
6. Expected behaviour: The dark theme should use light text on a dark background.
# Repro Steps
1. Switch to the dark theme.
2. Make a request that will end up with a response body, ideally one that doesn't have syntax highlighting.
3. See that the text is black on a dark background.

**Comment by abhijitkane** [comment] 2016-08-03 20:19
@benhamill This is happening due to specific Content-Type headers in the response. We'll push a fix for this soon. Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2221

**Closed as completed by abhijitkane** 2016-08-03 20:19 UTC
Labels: bug

**Comment by benhamill** [comment] 2016-08-04 02:15
The content type in the response for me was `application/hal+json`.

And the symptom was very different than that described in #2221. Can you go into a bit more detail about how they're related?
