### ISSUE TITLE
After upgrading, "Archived" collections notification still shown until logout + login

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6777] opened 2019-06-24 16:46 UTC
**Describe the bug**
For _some_ teams who have upgraded to Postman Pro after their shared Collections are archived, users still see notifications for Archived collections until they've logged out of the app, and logged back in. Note that the Collections _are_ restored successfully during the upgrade process -- only the notification persists.

This may be confusing, because the web dashboard page for un-archiving Collections is not accessible for paid teams, and there is no other messaging to suggest login + logout as a potential resolution.

**To Reproduce**
1. Team has shared Collections archived
2. Team upgrades to Pro (assuming this affects enterprise as well)
3. Collections _are_ un-archived successfully, per upgrade flow.
4. In the app, team is still shown notification about archived Collections.
5. Logging out, then logging back in removes the notification

**Expected behavior**
Upgrading to Pro (or Enterprise) more reliably dismisses any notifications associated with free teams, without requiring login + logout

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.2.2
 - OS: Linux (possibly others)

**Additional context**

**Comment by sankalp0o** [comment] 2019-12-09 08:54
This issue is actually the same as/caused by #6027, therefore closing this one.

**Closed as completed by sankalp0o** 2019-12-09 08:54 UTC
Labels: bug, notifications
