### ISSUE TITLE
Inputting Hebrew characters in the "value" field of params gives errors connecting

### ISSUE THREAD

**Issue by arielbeje** [a85/POSTMan-Chrome-Extension#7155] opened 2019-08-20 22:12 UTC
**Describe the bug**
When Hebrew characters are entered as a value for a path variable, Postman claims `There was an error connecting`

**To Reproduce**
1. Make a new GET request
2. Make a path variable in the URL
3. Put Hebrew characters in its value (say אבג)
4. Run request
5. See error

**Expected behavior**
The request will work like any other, but with Hebrew characters in the URL.

**Screenshots**
Hebrew value:
![Postman_2019-08-21_01-05-55](https://user-images.githubusercontent.com/19347259/63388283-9dc36700-c3b0-11e9-859d-c3ad99bb2ac9.png)
English value:
![Postman_2019-08-21_01-06-42](https://user-images.githubusercontent.com/19347259/63388295-a451de80-c3b0-11e9-9ee1-5edbd8762235.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.5.0
 - OS: Windows 10 Enterprise 1903 x64 (OS build 18362.295)

**Comment by vikiCoder** [comment] 2019-09-11 08:47
Hi @arielbeje 

The issue is related to character encoding. Currently, we are not automatically encoding such characters in the URL path. You can manually encode it by right-clicking on the field and selecting `EncodeURIComponent` option as shown in below GIF.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16588032/64682057-6b33f800-d49e-11e9-88f0-11f48895d2a5.gif)

Closing this issue because all URL encoding issues are being tracked here: #4555

**Closed as completed by vikiCoder** 2019-09-11 08:47 UTC
Labels: bug, encode-decode, product/runtime

**Comment by vikiCoder** [comment] 2020-03-09 09:35
@arielbeje this is fixed in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). We now automatically encode path variables in a URL. You can see more details about the fix at #8154
