### ISSUE TITLE
OAuth 2.0 Token Request failing

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7930] opened 2020-01-17 18:44 UTC
Filed on the behalf of a user. 

**Describe the bug**

Requesting a new auth token or manage existing auth tokens throws a Something went wrong error.

**To Reproduce**
1. Go to the Authorization tab > Get New Access Token 
2. Fill all fields
3. Click Request Token

<img width="676" alt="Screen Shot 2020-01-17 at 18 39 57" src="https://user-images.githubusercontent.com/47351631/72637257-ca2be100-3958-11ea-9c9b-0ef1bb47e387.png">

Or, 

1. In the Authorization tab, go to Available tokens
2. In the drop-down, select Manage tokens.
3. See Something went wrong error.

**Expected behavior**
Create the token

**App information (please complete the following information):**
 - Postman Version 7.16

**Additional context**
You can access logs internally and screen record.

**Comment by vikiCoder** [comment] 2020-03-17 12:40
It is fixed in the Postman canary and the fix will be out in the next Postman release (v7.21) as well. Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/8054

**Closed as completed by vikiCoder** 2020-03-17 12:40 UTC
Labels: bug, duplicate, product/runtime
