### ISSUE TITLE
Unable to start the app.

### ISSUE THREAD

**Issue by Madhu031090** [a85/POSTMan-Chrome-Extension#5850] opened 2019-01-29 21:25 UTC
Description:
The app is just loading forever.
Developer tools, I am seeing the following error message.
 "the server responded with a status of 403 (Forbidden)"

1. Download 6.7.2 version of Postman Desktop app
2. Run the .exe file
3. Postman app install is successful
4. App Loads and nothing other than "exit" works

**App information (please complete the following information):**
 - App Type [native app]
 - Postman Version [e.g. 6.7.2
 - OS: [Windows 10, OS 14393.2724, 64 Bit

**Additional context**

**Comment by numaanashraf** [comment] 2019-02-03 10:10
@Madhu031090 Could you provide a screenshot of the 403 error?

**Comment by salhidev** [comment] 2019-02-05 15:16
I'm encountering the same thing on Windows 7, 64 Bit
The app is just loading forever. Uninstalled and re-installed but problem persists
This is my main.log 
```
[48012][1549378135664][main][info]["Booting Postman 6.7.3, win32-6.1.7601 on x64"]
[48012][1549378135670][main][info]["EventBus\\x7einitialize - Success"]
[48012][1549378135677][main][info]["UpdateHandler\\x7einit - Success"]
[48012][1549378135678][main][info]["RuntimeExecutionService\\x7einitialized: Success"]
[48012][1549378135680][main][info]["ProtocolHandler\\x7einit - Success with status: true]"]
[48012][1549378135691][main][info]["PluginHost - Booted for 1th time"]
[48012][1549378135990][main][info]["Bootstrap-models\\x7ebootstrap - Success"]
[48012][1549378140818][main][info]["Main\\x7eAppEvents - Received booted event for process shared"]
[48012][1549378145131][main][info]["UpdateHandler\\x7eapp-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[48012][1549378145133][main][info]["Main\\x7eAppEvents - Received booted event for process requester"]
```

**Comment by salhidev** [comment] 2019-02-05 15:41
I fixed the problem by adding a system variable "POSTMAN_DISABLE_GPU" and set it to "true".
re-open the app and it works, this documentation helped me :
https://learning.getpostman.com/docs/postman/launching_postman/installation_and_updates/

**Comment by numaanashraf** [comment] 2019-02-18 14:53
@salhidev Thanks for letting us know. We are closing this as a duplicate of #4594.

**Closed as completed by numaanashraf** 2019-02-18 14:54 UTC
Labels: duplicate
