### ISSUE TITLE
Default tab setting

### ISSUE THREAD

**Issue by rmnrdi** [a85/POSTMan-Chrome-Extension#9351] opened 2020-12-08 15:19 UTC
As a user, it would be nice to have a "default" tab setting so that when you switch between endpoints, you don't have to navigate to the tab you need.

For example,
**Use case:** I'm going through endpoints and making changes to the tests. I currently have to select the endpoint, then navigate to the test tab for every endpoint because the default tab that loads is "Params".

**Describe the solution you'd like**
I'd like to have a switch somewhere where I can choose the default tab I end up in when navigating endpoints.
Imagine the below doodads are radio buttons.
- [ ] Params 

- [ ] Authorization

- [ ] Headers

- [ ] Body

- [ ] Pre-request Script

**- [O] Tests**

- [ ] Settings

With the "Test" radio button set, whenever I navigate to an endpoint in that collection, it automatically takes me to the test tab. I spend 90% of the time in Tests or Pre-Request Script tabs and it's a pain point to navigate there when I open an endpoint.

Thanks!

**Comment by appurva21** [comment] 2020-12-11 11:46
Duplicate of [#2086](https://github.com/postmanlabs/postman-app-support/issues/2086)

**Closed as completed by appurva21** 2020-12-11 11:46 UTC
Labels: feature, duplicate, product/runtime
