### ISSUE TITLE
'Render non-printable characters' defaults to true

### ISSUE THREAD

**Issue by asherber** [a85/POSTMan-Chrome-Extension#9685] opened 2021-03-04 19:31 UTC
**Describe the Issue**

In Postman v7, there was an editor setting 'Render non-printable characters' which defaulted to false. In v8, this setting defaults to true, but there is no longer a toggle to turn it off.

**Steps to Reproduce**

Type a raw body into a request, or perform any request that returns text/XML/HTML. Glyphs for spaces and tabs are visible in the editor.

**Environment Information**

 - Platform Type: Desktop
 - Postman Version: 8.0.6
 - Operating System: Windows 10

**Additional Context**

Interestingly, as per https://community.postman.com/t/hide-white-space-symbols-in-postman/20718, you can turn off display of whitespace chars by going into preferences and resetting editor preferences -- although this resets all editor preferences, which may not be desirable, and the setting does not persist between Postman sessions.

**Comment by DannyDainton** [comment] 2021-03-05 12:06
Closing this as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9531

**Closed as completed by DannyDainton** 2021-03-05 12:06 UTC
Labels: duplicate
