### ISSUE TITLE
Search arrows for next and previous are backwards

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#6202] opened 2019-04-01 22:24 UTC
**Describe the bug**
Clicking on the `<` (left arrow) takes you to the next search result, and clicking on the `>` (right arrow) takes you to the previous search result.

**To Reproduce**
1. Get a JSON response from an API in the Body section
2. Search for something that appears more than once
3. Click left arrow and you'll "go to next" in the list
4. Click right arrow and you'll "go to previous" in the list

**Expected behavior**
Left arrow should "go to previous", and right arrow should "go to next".

**Screenshots**
In the screenshots below, I am only clicking the "left" arrow, and it is taking me down the list, not up.

![Screen Shot 2019-04-02 at 11 20 38 AM](https://user-images.githubusercontent.com/2616473/55363405-6f480b00-5539-11e9-89d6-b6708c2bdf85.png)

![Screen Shot 2019-04-02 at 11 20 51 AM](https://user-images.githubusercontent.com/2616473/55363413-753dec00-5539-11e9-9c89-fd2ee8ae3d59.png)

![Screen Shot 2019-04-02 at 11 21 02 AM](https://user-images.githubusercontent.com/2616473/55363416-796a0980-5539-11e9-9b16-7662475e96f0.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version7.0.7
 - OS: MacOS Mojave

**Comment by numaanashraf** [comment] 2019-04-02 07:15
Duplicate of #5226

**Closed as completed by numaanashraf** 2019-04-02 07:15 UTC
