### ISSUE TITLE
GitLab Integration not working

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#5335] opened 2018-10-10 10:41 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Set up the Postman- GitLab integration [https://learning.getpostman.com/docs/postman_pro/integrations/gitlab/?_ga=2.46685799.1391770307.1538974094-148920403.1535954785](url) but don't see any pushes on GitLab repo.

**Expected behavior**
Seemless push into GitLab repo

**Other information**
Using GitLab ([gitlab.com](url)) free account

**Comment by emilianobonassi** [comment] 2018-10-25 09:04
any updates?

**Comment by ankit-m** [comment] 2018-10-25 09:13
@emilianobonassi We are working on this. I will post updates on this thread. Apologies for the delay in response.

**Comment by kartikjain26** [comment] 2018-10-31 08:43
@emilianobonassi  This issue could not be reproduced at our end. However I would advise you to initialise your repository while creating a new project by clicking on the checkbox at bottom on project setup screen. We saw that if project was not initialised, the integration failed to backup that collection.
<img width="978" alt="screen shot 2018-10-31 at 2 09 32 pm" src="https://user-images.githubusercontent.com/26088676/47775901-0a348300-dd17-11e8-9723-00a9e26e9558.png">

**Comment by kartikjain26** [comment] 2018-10-31 10:37
@emilianobonassi  Let us know if you consistently face this issue and steps leading to reproduce this.

**Comment by emilianobonassi** [comment] 2018-11-29 08:32
@kartikjain26 repeating your steps not work for our account.

We reset the repository and configured again the integration but none is pushed on gitlab side.

Consider the issue close, we will try to backup collections in another way.

**Comment by ankitjaggi** [comment] 2018-11-29 08:57
@emilianobonassi Is it possible that the user whose token was used to create the integration does not have enough permissions to push to the specified branch? If that's case, Gitlab won't allow any changes to be pushed to the branch.

**Comment by emilianobonassi** [comment] 2018-12-05 10:08
@ankitjaggi he has the admin rights.

**Comment by lpantea** [comment] 2019-04-17 11:25
I have a similar issue and I was wondering if anyone managed to see the files posted. I've successfully added the integration entry but there is nothing posted to the private Gitlab.

**Comment by kartikjain26** [comment] 2019-04-17 12:54
Hey, can you follow these steps while creating integrations- https://learning.getpostman.com/docs/postman_pro/integrations/gitlab/
Also make sure you initialise your gitlab repo with an initial commit (opt for Initialise repo with readme file), and you give access-token permissions for reading/writing to that repo.

**Comment by Ivanello** [comment] 2019-05-08 11:35
Try to remove **Protected** from branch which You want to use with Postman integration (by default master is Protected)
It works for me, I think its good to add to doc because GitHub need fewer preparations.

So, it is necessary to meet the conditions:
1. Valid User (access to repo)
2. Valid token in Gitlab (allow to write to repo via API)
3. Repo is initiated (Initial commit to repo is present)
4. Branch used to integration is **Unprotected** 

https://docs.gitlab.com/ee/user/project/protected_branches.html

**Comment by Hanzelka** [comment] 2019-05-14 13:14
I have the same issue. I am using custom domain Gitlab. Integration on PM side is successful without any errors, but no JSON file is pushed to repo. I tried several times with no succes.

1) I am valid user with developer permission
2) I have created valid token (allow to write to repo via API)
3) Repo is initiated (many commits and MR in past)
4) Branch for integration is Unprotected

**Comment by kartikjain26** [comment] 2019-05-27 09:15
@Hanzelka  can you try to build a new repo and configure a new integration for this following these steps:
https://learning.getpostman.com/docs/postman_pro/integrations/gitlab/
Also make sure you initialise your gitlab repo with an initial commit (opt for Initialise repo with readme file), and you give access-token permissions for reading/writing to that repo.

**Comment by harishbarma** [comment] 2019-07-23 14:36
@kartikjain26 I have gitlab on  a custom domain. I followed all the steps mentioned in above post but it is not backing up the collections.  I created new access tokens with api and read user access
I tried several types with 
1. exsinting repository with with amster
2. existing repository with separate branch (mentioned branch name while configuring)
3. Create separate public project 
4. created separate project and selected branch name as master.
it still doesn't work

**Comment by harishbarma** [comment] 2019-09-02 08:37
Hi @kartikjain26  any news on what might be wrong ?

**Comment by somyata** [comment] 2019-12-27 14:17
Hi Friends- I am still not able to integrate Postman with Gitlab..Did anyone had a good luck with this?

**Comment by DannyDainton** [comment] 2020-08-29 09:07
Hey @kartikjain26 

Is this still an issue with the latest version?

**Comment by DannyDainton** [comment] 2020-09-04 07:41
Closing out this issue, we can reopen this is the issue still persists.

**Closed as completed by DannyDainton** 2020-09-04 07:41 UTC
Labels: bug, product/integrations

**Comment by shashankawasthi88** [comment] 2020-10-27 04:59
@somyata @harishbarma @Hanzelka @emilianobonassi - For the GitLab Integration on a custom domain, there might be a firewall issue which is blocking the Integration from running successfully. With the latest release, we are running the GitLab, GitHub, and Webhook Integration through a static IP. Once the IP is whitelisted in your network's firewall, the Integration should run as expected. Please follow the link to know about the details of the IP address - https://learning.postman.com/docs/integrations/intro-integrations/
