### ISSUE TITLE
Usage of "Shared Requests" not getting updated after deleting shared collections

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6857] opened 2019-07-04 07:13 UTC
**Describe the bug**
Usage of "Shared Requests" are not getting updated after deleting shared collections

**To Reproduce**
1) Go to ' Team Workspace'
2) Delete all collections
The usage limit doesn't reset.

**Expected behavior**
Once you clear all Team collections, the usage for "Shared Requests" should get updated.

**Screenshots**
![11](https://user-images.githubusercontent.com/47771757/60646468-0da97c80-9e59-11e9-96d4-ed0221528c1c.png)
![22](https://user-images.githubusercontent.com/47771757/60646472-113d0380-9e59-11e9-9ba4-e6be2fa54244.png)

**App information :**
 - App Type - Native App]
 - Postman Version - 7.2
 - OS: MacOS

**Comment by preethammavin** [comment] 2019-07-05 16:00
@Kurmavathar the shared collection count is updated with throttle of 15 seconds. I am unable to reproduce this for any other scenario, closing the issue for now. Do let me know if there is a specific case you want me to look at.

**Closed as completed by preethammavin** 2019-07-05 16:00 UTC
