### ISSUE TITLE
Issue using 'auth' to update collection

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6532] opened 2019-05-17 07:44 UTC
**Describe the bug**
 While 'auth' is used instead of 'Auth' to update the collection, receives an error.

**To Reproduce**
1. Use 'auth' inside the tests to run collection
2. Error: malformedRequestError

**Expected behavior**
To be able to receive the same response when 'Auth' is used i.e ignoring the case sensitivite

**Screenshots**
![AuthIssue](https://user-images.githubusercontent.com/47771757/57911346-2d82e200-78a5-11e9-967e-4d3d55b265f2.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.0.9

**Additional context**
When 'Auth' is used: 
![Authused](https://user-images.githubusercontent.com/47771757/57911483-85214d80-78a5-11e9-903c-c6e02339183e.png)

**Comment by Raj-postman** [comment] 2019-06-27 15:52
@ankitjaggi Let me know if there are any further details required to check on it

**Comment by ash007-postman** [comment] 2019-09-09 10:34
@ankitjaggi Another user facing the same issue, have tagged the ticket.

**Comment by DannyDainton** [comment] 2020-08-27 11:42
@Raj-postman Is this still a problem?

**Comment by Raj-postman** [comment] 2020-08-28 06:38
@DannyDainton I guess yes - with "auth": Error

![image](https://user-images.githubusercontent.com/47771757/91529375-cd437280-e926-11ea-9551-a8c70843c9a9.png)

Changing to "Auth": Works fine

![image](https://user-images.githubusercontent.com/47771757/91529432-eb10d780-e926-11ea-9828-e0670d940574.png)

Could you give it a try and see if it's true?

**Comment by DannyDainton** [comment] 2020-08-28 06:46
Thanks for checking that - just to expand on what the issue is, am I correct in saying this is just something that you have seen on the Postman API?

Does the same happen on the POST call when creating a new collection?

Is it just the `Auth` that's doing this and not case-insensitive?

As that's a collection JSON file, does a GET request for a collection with `Auth` set return the same or the exported file from the app?

**Comment by Raj-postman** [comment] 2020-08-28 12:55
Yes, the same error during the creation of a collection.

auth:
![image](https://user-images.githubusercontent.com/47771757/91561989-106b0900-e95a-11ea-88b5-884aab18f7c3.png)

Auth:
![image](https://user-images.githubusercontent.com/47771757/91562100-44462e80-e95a-11ea-9f70-93b80a31a273.png)

If I remember this right - there was a user who faced this issue for one of his APIs as well and changing it to "Auth" resolved the issue for him. Guess its only auth (not sure)

**Comment by DannyDainton** [comment] 2020-09-02 10:43
I'm not sure what the actual behaviour should be here - @ankitjaggi Is this something that you could help with? 🙏

**Comment by DannyDainton** [comment] 2020-09-10 06:28
Hey @Raj-postman 

I'm not sure where to go with this issue - Do we know if any other users have reported this?

**Comment by Raj-postman** [comment] 2020-09-10 07:39
No @DannyDainton. 

Apart from those two cases, I haven't seen recent reports on this. I will keep this thread posted if we receive any.

**Comment by DannyDainton** [comment] 2020-09-18 11:03
@Raj-postman I'm going to close this one for now and if we get any more reports of this happening we can open it up again.

**Closed as completed by DannyDainton** 2020-09-18 11:03 UTC
Labels: bug, product/postman-api
