### ISSUE TITLE
Postman Collection Runner stop bug on unavailable server

### ISSUE THREAD

**Issue by cimpresovec** [a85/POSTMan-Chrome-Extension#7505] opened 2019-10-21 13:31 UTC
**Bug description**
When running a collection that includes a request to an unavailable server the request fails (with a ECONNREFUSED error in the runner) and stops the whole collection. Inspecting the console output the error is in parsing the response. The response doesn't have a responseTime value since it was refused, crashing/stopping the runner.

```Javascript
Uncaught TypeError: Cannot read property 'responseTime' of null
    at RuntimeRunner.onEndRequest (runner.js:44821)
    at invokeCallbackSafely (runner.js:45276)
    at EventEmitter.ipcRenderer.on.rawArgs (runner.js:45302)
    at EventEmitter.emit (events.js:182)
```

**To Reproduce**
1. Create a collection with 3 requests. Number 1 and 3 can be the same an should be working (e.g. GET www.google.com). Number 2 should be to an unavailable server (e.g. GET 127.0.0.1 with a random port)
2. Run the collection with the runner
3. The collections stops after request number 2. The error is visible in the console.

**Expected behavior**
Expected behavior would be to log that request as failed and continue uninterrupted.

**App information (please complete the following information):**
 - Native App
 - Postman Version v7.9.0
 - OS: Windows 10 version 1803

**Comment by coditva** [comment] 2019-10-21 13:48
@cimpresovec Thanks for reporting! I was able to reproduce this. Will fix and update this issue.

**Comment by coditva** [comment] 2019-10-22 10:08
Closing because it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/3845

**Closed as completed by coditva** 2019-10-22 10:08 UTC
Labels: bug, product/runtime
