### ISSUE TITLE
Multipart form-data content type is incorrectly encoded in Postman

### ISSUE THREAD

**Issue by NinnOgTonic** [a85/POSTMan-Chrome-Extension#2690] opened 2017-02-09 14:59 UTC
1. Postman Version:4.9.2 OS X / x86-64 Chrome 56.0.2924.87
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: macOS Sierra
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Probably always
 6. Expected behaviour: Use correct multipart/form-data header when posting form-data
 7. Console logs: Not relevant
 8. Screenshots: See related issue

Hello, I've just discussed this issue over at flask, but it appears that postman is incorrectly encoding multipart form-data, as such I was hoping you would look to patch this so we are able to properly debug flask apps:

https://github.com/pallets/flask/issues/2177#issuecomment-278663324

**Comment by vegetableman** [comment] 2017-02-13 11:49
@NinnOgTonic The issue happens when switching from `x-www-form-urlencoded` to `form-data`, retaining the previous `Content-Type` header and it's value `application/x-www-form-urlencoded`, as such, the app does not add any `Content-Type` for `form-data`.

**Comment by vegetableman** [comment] 2017-02-13 11:58
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2636

**Closed as completed by vegetableman** 2017-02-13 11:58 UTC
Labels: bug
