### ISSUE TITLE
Postman is soooo slow on 16gb ram and ssd hard drive and cpu core i5!!!!

### ISSUE THREAD

**Issue by sinahosseini76** [a85/POSTMan-Chrome-Extension#7404] opened 2019-09-27 14:23 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by kamalaknn** [comment] 2019-11-04 02:01
Hey @sinahosseini76 

I'm closing this as a duplicate of # 7294. Please follow the original thread for updates.

**Closed as completed by kamalaknn** 2019-11-04 02:01 UTC
Labels: bug

**Comment by sinahosseini76** [comment] 2021-05-08 12:53
thanks
