### ISSUE TITLE
Postman Windows App Setup Fails

### ISSUE THREAD

**Issue by Anyqax** [a85/POSTMan-Chrome-Extension#2806] opened 2017-03-15 11:14 UTC
1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Microsoft Windows 8.1 Pro
 4. Is the Interceptor on and enabled in the app: /
 5. Did you encounter this recently, or has this bug always been there: always
 6. Expected behaviour: Postman app is sucessfully installed
 7. Console logs: /
 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/3055796/23945726/e727479a-0977-11e7-8813-6d3cffdb180a.png)

Steps to reproduce the problem:
- Download windows-x64 or x32 installer
- Start setup

Setup immediately fails with message "Installation has failed" (see screenshot), the setup log is unfortunately empty. Wether setup is started with or without privilege elevation makes no difference.

Is there anything I can try or anywhere I can check for further details?

**Comment by sdnts** [comment] 2017-03-16 11:42
@Anyqax An empty log does make it hard to debug. Can you also check `C:\Users\<username>\AppData\Local\Postman\SquirrelSetup.log` and see if you find anything there?

Can you also make sure you're not running a 64-bit setup on a 32-bit machine?

**Comment by Anyqax** [comment] 2017-03-21 09:08
There is no SquirrelSetup.log or similar in C:\Users\xxx\AppData\Local\Postman.
I'm on a 64-bit system (i7), tried both 64-bit and 32-bit, no success.

**Comment by pmneve** [comment] 2017-03-29 18:34
Have been having similar issue since September (#2352) except that I don't even get the error message.  No logs at all.  Both 32 and 64 bit (on 64 bit system).   The directories in AppData\Local\Postman are there but no logs

**Comment by prashantagarwal** [comment] 2017-09-06 06:21
@pmneve we are already tracking this in #2352 . Closing this as duplicate.

**Closed as completed by prashantagarwal** 2017-09-06 06:21 UTC

**Comment by sauladalibor** [comment] 2018-08-27 05:33
Hey Guys I had the same issue, the quickest way to fix this is to run it in windows 7 compatibility mode.  So run the installer in that mode, and once installed, set the application exe to run in the same mode. You can easily find how to run a program in compatibility mode on google.  :+1:

**Comment by jsk999** [comment] 2019-01-02 05:34
![image](https://user-images.githubusercontent.com/46309537/50581195-4f0ba000-0ea7-11e9-9aae-a5bfbe7c3f97.png)


This error is due to AppLocker in our environment. It is basically extracting files to C:\Users\User\AppData\Local\Postman folder and then tries to run the program from that location. If you move it (the whole Postman folder) to a location that is excluded from AppLocker then run it, it should work. If it works that means it is confirmed the problem is due to AppLocker. You can also check Event viewer for Applocker logs.
