### ISSUE TITLE
HTML void elements don't have children

### ISSUE THREAD

**Issue by jkrrv** [a85/POSTMan-Chrome-Extension#1371] opened 2015-08-24 22:07 UTC
Per the [html5 spec](http://dev.w3.org/html5/spec-author-view/syntax.html#syntax-start-tag), start tags for [void elements](http://www.w3.org/html/wg/drafts/html/master/single-page.html#void-elements) do not need to have a corresponding closing tag.  

Thus, responses that currently appear as this:

```
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="minimum-scale=1.0, maximum-scale=1.0">
            <title>page title</title>
...
```

should be indented as: 

```
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="minimum-scale=1.0, maximum-scale=1.0">
    <title>page title</title>
...
```

Considering that this behavior may or may not be desirable depending on whether the response is actually html5, I would propose making this an option in the settings. 

Possibly related to #1166 and #236.

**Comment by abhijitkane** [comment] 2015-12-29 18:33
@jkrrv This was an issue with our HTML indenting library. We've fixed this, and will be pushing it out in the next release. Thanks for reporting this.
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/1589

**Closed as completed by abhijitkane** 2015-12-29 18:33 UTC
Labels: bug
