### ISSUE TITLE
Scrollspy inside the documentation 

### ISSUE THREAD

**Issue by cafferata** [a85/POSTMan-Chrome-Extension#3622] opened 2017-10-11 17:27 UTC
## App Details:

```
Postman Documentation Web
```

## Feature request

It would help end users when a scroll spy is added to online documentation. This makes it better to know which folder they are currently in. In our case, we have the versions as main directories. From there you can find the same call multiple times. For example, when you use the browser search option you don't know if you are looking at V1.0 or V2.0. By using the Scrollspy we can make this more clear.

![Scrollspy](http://blog.bigbasti.com/uploads/scrollspy_2.gif)
_https://v4-alpha.getbootstrap.com/components/scrollspy/#example-in-navbar_

**Comment by numaanashraf** [comment] 2017-10-12 06:31
Thanks for the suggestion @cafferata

**Comment by Raja-Simha** [comment] 2019-07-22 13:31
Duplicate of #3931. Closing this one.

**Closed as completed by Raja-Simha** 2019-07-22 13:31 UTC
Labels: feature, product/documentation
