### ISSUE TITLE
Sessions keep timing out and signing back in sometimes (often) fails.

### ISSUE THREAD

**Issue by blairg23** [a85/POSTMan-Chrome-Extension#5010] opened 2018-08-13 05:11 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I'm getting a permanent sign in screen at the moment, haven't even gotten a chance to log in yet.

Previously, I was getting signed out in the middle of requests and then forced to sign in again.

**To Reproduce**
1. Use the app for a while
2. Get session timed out.

**Expected behavior**
Session does not sign out, but rather warns that session is going to time out unless I hit okay.

**Screenshots**
![image](https://user-images.githubusercontent.com/6225764/44013703-5f773a6e-9e84-11e8-9c59-b3dad6da218c.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Latest (can't see because sign in screen is still going)
 - OS: Ubuntu 17.10 LTS

**Additional context**
Tried to uninstall / reinstall, still getting sign in screen w/o ability to go further.

**Comment by sivcan** [comment] 2018-08-13 07:19
@blairg23 Duplicate of https://github.com/postmanlabs/postman-app-support/issues/5011

**Closed as completed by sivcan** 2018-08-13 07:19 UTC
