### ISSUE TITLE
Could not get any response (Error: Invalid URI)

### ISSUE THREAD

**Issue by kalemdzievski** [a85/POSTMan-Chrome-Extension#5027] opened 2018-08-14 13:37 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Postman cannot resolve environment variable in request's URL, for requests that are created in folder.
Example env variable is set in the environment as host: https://x.com
Every created in folder request returns error "Could not get any response. There was an error connecting to %7B%7Bhost%7D%7D/v1/status.". Console says: Error: Invalid URI "http:///%7B%7Bhost%7D%7D/v1/status"

**Steps to reproduce the behavior:**
1. Create environment
2. Add variable "host" in the created environment
3. Create request in folder with URL: {{host}}/v1/status
3. Try to send the request.
4. See the error in the response

**Screenshots**
![screenshot from 2018-08-14 15-34-01](https://user-images.githubusercontent.com/4439047/44094842-86d3b1b0-9fd7-11e8-8e36-9cf328181a5b.png)

**App information**
 - Native App
 - Postman Version 6.2.4
 - OS: Ubuntu

**Additional context**
This started happening after I updated postman to version 6.2.4.

**Comment by sujayvenaik** [comment] 2018-08-14 13:43
Hey @kalemdzievski 

I was not able to reproduce the bug and this seems to work fine when i tried reproducing it.

Can you check once if you selected the environment from the environment selector drop-down after creating the environment ?

**Comment by kalemdzievski** [comment] 2018-08-14 13:58
@sujayvenaik 

yes the environment is selected. Here is an exported collection example:
[Postman Issue #5027.postman_collection.zip](https://github.com/postmanlabs/postman-app-support/files/2287203/Postman.Issue.5027.postman_collection.zip)

**Comment by kalemdzievski** [comment] 2018-08-14 14:10
@sujayvenaik 

i found out that the following code is causing the issue:
`"event": [
						{
							"listen": "prerequest",
							"script": {
								"id": "f6b64b63-e595-4cc0-95ab-0aaef4ea2d36",
								"type": "text/javascript",
								"exec": [
									""
								]
							}
						}
					]`
But the "Pre-request script" tab is empty for this request. If i delete this code from the postman collection, the request works fine.

**Comment by kalemdzievski** [comment] 2018-08-14 14:36
Also please note that, the request is copied from existing collection. It is just edited (name, host, request path) for privacy reasons.

**Comment by sujayvenaik** [comment] 2018-08-14 14:40
Hey @kalemdzievski 

I imported the collection and ran the request worked fine.
Ideally this should not happen if the pre-request scripts you have entered do not have any error.

Closing this issue for now, if you face such a situation again then you can reopen this issue.

**Comment by kalemdzievski** [comment] 2018-08-15 07:59
@sujayvenaik 

the issue is still happening. I found out that if i create new collection add request, without setting any pre-request script, everything works fine. As soon as i add for example global variable, the issue occurs.

I recorded a video of the issue happening:
[Screencast 2018-08-15 09:54:59.zip](https://github.com/postmanlabs/postman-app-support/files/2289565/Screencast.2018-08-15.09.54.59.zip)

Please reopen the issue.

**Comment by harryi3t** [comment] 2018-08-22 13:54
@kalemdzievski Thanks for the inputs. 
Could you also share any errors on the DevTools
You can open from `View -> Developer -> Show DevTools (current view)`

Also, have you unzipped the app in `/opt/postman/....`? We have seen people having permission issues in this directory.
If yes, can you try downloading a fresh app and then unzipping to your home directory or desktop and then test it again?

**Comment by kalemdzievski** [comment] 2018-08-27 07:58
@harryi3t sorry for the late response.

I tried unzipping the app in my home directory and it workings fine now.

Thank you very much for your help!

**Closed as completed** 2018-10-30 20:02 UTC
Labels: bug

**Comment by pdh-24** [comment] 2025-05-17 03:03
It's still an issue to me. The variable for base_url works just fine on desktop app, but it doesn't when the request is run thru the postman web.
