### ISSUE TITLE
Diactitics on variable names cause error when replacing URL value

### ISSUE THREAD

**Issue by rober710** [a85/POSTMan-Chrome-Extension#3765] opened 2017-11-09 17:03 UTC
When I create a request with path parameters, which have diacritics in their names, like this:
`http://127.0.0.1:8000/api/applications/product-evaluations/:idAplicación`, Postman cannot parse the variable name correctly, taking it as `idAplicaci`:
![image](https://user-images.githubusercontent.com/25037552/32618176-f60f7d66-c544-11e7-872a-35aa12ce4fff.png)
Thus, the request is sent like this:
`PATCH /api/applications/product-evaluations/:idAplicaciÃ³n HTTP/1.1`
or `PATCH /api/applications/product-evaluations/13ón HTTP/1.1`

The parameter name should be parsed as 'idAplicación' and its name replaced with the value '13', so that it is sent as `PATCH /api/applications/product-evaluations/13 HTTP/1.1`

## App Details:
```
Postman for Linux
Version 5.3.2
Fedora 25 / x64, kernel 4.13.8-100.fc25.x86_64
```

**Comment by sdnts** [comment] 2017-11-14 15:17
@rober710 Thanks for reporting this. I was able to reproduce this. We will look into this!

**Comment by abhijitkane** [comment] 2019-01-04 09:27
@kamalaknn If the app has updated the runtime version after Sep, can you check if this is still an issue?

**Comment by kamalaknn** [comment] 2019-01-04 09:59
@abhijitkane This issues seems to exist. I think this is because the App uses a different logic to parse path variables.

**Comment by codenirvana** [comment] 2019-06-13 11:58
This is fixed in the latest version of the Postman App (v7.2.0).

**Closed as completed by codenirvana** 2019-06-13 11:58 UTC
Labels: bug, product/runtime
