### ISSUE TITLE
[Auth] AccessToken not properly recognized(remains blank) after successfully issued

### ISSUE THREAD

**Issue by ryan1st** [a85/POSTMan-Chrome-Extension#4021] opened 2018-01-04 07:19 UTC
## App Details:
```
Postman for Mac
Version 5.5.0
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: ```First tried and first met today.```

 2. Expected behavior: 
```
In Auth tab, when I request access token, 
Access token field is supposed to be filled with newly issued one 
but it remains blank.
No matter how many tokens I create, their 'Access Token' field is empty 
and I need to copy the value from 'accessToken' field and paste 
every time I need to change the token.
```

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

```POST /oauth/token
content-type: application/x-www-form-urlencoded
authorization: Basic TGp6QzNRMGZpdkE0aUJFNDVicWg3eUhjS0QxQk11Wkk2OmpWU2t6ZXZrcE9MeVlueW4zLTZwSWxmMTkzV0JHZ2VRYkxBTw==
user-agent: PostmanRuntime/7.1.1
accept: */*
host: localhost:3000
accept-encoding: gzip, deflate
content-length: 114
grant_type=passwordusername=user1@test.compassword=testscope=testclient_id=LjzC3Q0fivA4iBE45bqh7yHcKD1BMuZI6
HTTP/1.1 200
status: 200
x-powered-by: Express
content-type: application/json; charset=utf-8
instance: namu-auth
content-length: 254
etag: W/"fe-UC7HIp9TpcWgMFOwdOxiGbctXm8"
date: Thu, 04 Jan 2018 07:02:53 GMT
connection: keep-alive
{"accessToken":"edbb0434e16b51275deff4937cb87e7f465f8289","accessTokenExpiresAt":"2018-02-03T07:02:53.187Z","refreshToken":"98b0b14a93ee9fbecd78aa13dc7fb5ca1122edb3","refreshTokenExpiresAt":"2018-02-04T07:02:53.187Z","user":{"id":1,"isGroupAdmin":false}}
```

 4. Screenshots 

Screenshot1
![screenshot_1](https://user-images.githubusercontent.com/4222863/34553232-b7f7dcf2-f169-11e7-905e-202917433aa5.png)

Screenshot2
![screenshot_2](https://user-images.githubusercontent.com/4222863/34553233-b8223bc8-f169-11e7-9a67-a40807661b3f.png)

5. Steps to reproduce the problem
   1. in Auth tab, select type 'Oauth 2.0' / Add auth data to 'Request Headers'
   2. Click "Get New Access Token" button at the bottom.
   3. Fill in the fields as in the [screenshot1]
   4. Click 'Request Token' button
   5. The access token is successfully issued but the field is empty. (Screenshot2)

**Comment by SamvelRaja** [comment] 2018-01-04 11:48
@ryan1st Thanks for bringing this to our notice,
Since there are lots of possible ways the access token can be returned by the servers. We are looking for a more generic solution for handling this case.

We shall update the thread once we implemented the same. Until, we recommend you to manually copy the accessToken received.

**Comment by kamalaknn** [comment] 2018-01-04 12:22
@ryan1st The root cause is that Postman is looking for `access_token` in the response (which is the specification for a standard OAuth2 implementation). 

You can circumvent this for now, by using copy-pasting the `accessToken` into the `Access Token` input box. 

We'll add more contextual information inside the App.

**Comment by ryan1st** [comment] 2018-01-08 01:17
@kamalaknn I understand. I wish there were some option I can specify the key name for the access token. Anyway, for now I'll add another `access_token` key for the access token. 
Thank you!

**Comment by kamalaknn** [comment] 2018-01-08 04:10
@ryan1st Adding a key name to extract the token has been on our minds. The configuration being global to all requests in the App and first user experience have to be considered too. We'll look into this when we do the next wave of OAuth 2.0 improvements 😄

**Comment by grantkemp** [comment] 2018-02-20 16:04
Hi - I am trying to do the same thing - but Can't get past the request token step - it redirects to oauth page and just goes back to requeset token screen. I have tried to use it with Google accounts and their implementation - but no joy..  
Do you have an eta when the fixes are coming? 

I get this message when clicking on the app 
![image](https://user-images.githubusercontent.com/751115/36435237-06c06958-1659-11e8-82f2-7760203371ba.png)

**Comment by harryi3t** [comment] 2018-02-21 13:58
@grantkemp This thread is about supporting non-spec-complaint auth servers.
The error that you see is not coz of the issue being discussed here.  Google sends the token as `access_token` only. 
Please update to the latest version of Postman and it should work for you

**Comment by callmeaatrey** [comment] 2018-03-15 11:06
Hey @ryan1st ,

Sorry for the delayed response.

In the latest version 6.0.x we've added a UI Improvement that gives the information regarding the spec-compliance of the received token right in the Manage Tokens dialog. This will prevent similar confusions where the access token is not recognised.

I'm closing the issue for now. Feel free to open if it still persists after updating to the new version.

**Closed as completed by callmeaatrey** 2018-03-15 11:06 UTC
Labels: Auth

**Comment by ryan1st** [comment] 2018-03-15 11:41
Thanks for the hard work !

**Comment by Abe-Telo** [comment] 2022-12-14 17:38
Hi, How can I change what postman is looking for as the variable **accsess_token**? I want it to look for **Access** instead.
Adding **Access** into the Access Token Field like the way it was explained will probably not do me well. I was thinking to add something like this {{Access}} But I don't know how to get the data from Authentication in the field. Please shed light to anything you can help me with. Thank you.

![image](https://user-images.githubusercontent.com/29134216/207667346-ed05a9e8-7afb-4102-8c23-b2428387fbec.png)
![image](https://user-images.githubusercontent.com/29134216/207667386-08aba3ac-9fdf-41af-b1cc-92a02bf5ba54.png)
