### ISSUE TITLE
Can't update HttpOnly cookie to non-HttpOnly

### ISSUE THREAD

**Issue by akaczinski** [a85/POSTMan-Chrome-Extension#7051] opened 2019-08-02 18:45 UTC
**Describe the bug**
Before this version of PostmanCanary, if you went to a page that, for example had a cookie on login:
set-cookie: 'foo=bar; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/test'

and later, after using a logout link, the server responds to postman with:
set-cookie: 'foo=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/test'

It used to wipe the cookie from Postman.

Now when following that same route, with the latest version of Canary, Postman does not wipe the cookie from it's cache and continues using it in subsequent tests. This becomes a problem because we cannot programatically (yet) control our cookies in automated testing.

**To Reproduce**

I threw together a NodeJS server to replicate this behavior.

```
require('net').createServer(function (socket) {
    socket.on('data', function (chunk) {
      chunk = chunk.toString();
      socket.write('HTTP/1.1 200 OK\r\n');
      if (chunk.indexOf(' /login') !== -1) {
        socket.write('set-cookie: LOGIN_COOKIE=yummy; Version=1; Path=/somePath; HttpOnly\r\n');
      } else if (chunk.indexOf(' /logout') !== -1) {
        socket.write('set-cookie: LOGIN_COOKIE=""; X-SID=117466745; Path=/somePath; \r\n');
      } 
      socket.write('\r\n');
      socket.write('ok');
      socket.end();
    });
  }).listen(3000);
```
1. Request localhost:3000/login
2. Note the cookie LOGIN_COOKIE=yummy has saved correctly
3. Request localhost:3000/logout
4. Note the LOGIN_COOKIE is still yummy

**Expected behavior**
If a server responds with a set-cookie= 'login_cookie=""', it should wipe the previous cookie if it was saved there already.

**App information (please complete the following information):**
 - PostmanCanary
 - Postman Version v7.3.5-canary04
 - OS: Windows 10

**Comment by codenirvana** [comment] 2019-08-03 06:05
@akaczinski Thanks for reporting this issue. We have made some improvements in our cookie management flow to add support for programmatic cookie access (Yes, its available in canary-04) and this looks like a side effect of that.

I will try reproducing this issue and check why it's happening.

To know more about programmatic cookie access: https://github.com/postmanlabs/postman-app-support/issues/3312#issuecomment-516965288

Edit: This is because of the underlying platform (Electron v3.1.8) upgrade.

**Comment by akaczinski** [comment] 2019-08-05 16:07
> @akaczinski Thanks for reporting this issue. We have made some improvements in our cookie management flow to add support for programmatic cookie access (Yes, its available in canary-04) and this looks like a side effect of that.
> 
> I will try reproducing this issue and check why it's happening.
> 
> To know more about programmatic cookie access: [#3312 (comment)](https://github.com/postmanlabs/postman-app-support/issues/3312#issuecomment-516965288)
> 
> Edit: This is because of the underlying platform (Electron v3.1.8) upgrade.

happy to help! and thank you for looking into this.

I'm strangely excited about the programmatic cookie access! It's been an area where I've often felt trapped in Postman, so thank you very much. I'll definitely be giving it some work.

**Comment by codenirvana** [comment] 2019-11-04 06:23
@akaczinski This issue is fixed in the latest version of the Postman app `v7.10.0`.

**Closed as completed by codenirvana** 2019-11-04 06:23 UTC
Labels: bug, cookies, product/runtime
