### ISSUE TITLE
Better anchor support in documentations

### ISSUE THREAD

**Issue by jooleeanh** [a85/POSTMan-Chrome-Extension#6859] opened 2019-07-04 14:18 UTC
**Is your feature request related to a problem? Please describe.**
I put in each of my endpoint's description what is returned. However, many of my endpoints return the same type of data (models, e.g. user, product). I therefore have lots of duplicates, which is hard to maintain.

**Describe the solution you'd like**
I was thinking of listing all the models that can be returned in the Collection's description, and have each endpoint reference to the specific models they return. For that, I would need to be able to create anchors. However, currently, the only way to create an anchor is to create a h1 tag, which is very visual.
I would like either:
- automatically create `id`s for h2, and h3 tags
- have custom html tags with ids to not be stripped 

**Describe alternatives you've considered**
I've tried putting `<div id="myanchor"></div>`, but the id is stripped.

**Additional context**

**Comment by Raja-Simha** [comment] 2019-07-23 15:02
Duplicate of #5706

**Closed as completed by Raja-Simha** 2019-07-23 15:02 UTC
Labels: feature, product/documentation
