### ISSUE TITLE
Option to replace a collection instead of create a copy has been lost

### ISSUE THREAD

**Issue by byrdman** [a85/POSTMan-Chrome-Extension#9037] opened 2020-09-08 19:04 UTC
**Describe the bug**
With the latest update 7.32.0 when importing a collection you no longer get the option to replace or create a copy if a collection already exists.

**To Reproduce**
1. Go into Postman
2. Import collection x
3. Import it a second time (now you have X and X (copy)

**Expected behavior**
Previously you were given an option to replace an existing collection or to create a copy

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
Native App version 7.32.0.  Not sure what version I was on, 2 updates installed today.
Windows 10

**Additional context**
Very annoying, we track our collections in our source control system so they follow along with code changes.  So, we frequently import.  This along with the regenerating of ids is about to become a deal breaker for using Postman.

**Comment by grimsa** [comment] 2020-09-17 16:09
Just came here to report this issue, but found it already reported. We have the same use case - exporting/importing collections in source control.

After the regenerating IDs issue becoming more severe since 7.23 (see https://github.com/postmanlabs/postman-app-support/issues/2906) and now this, it is starting to feel that Postman is pushing users to adopt some different workflow.

If that is the case and "export-commit-import" workflow is not going to be supported, it would be nice to hear that, so that instead of waiting we could take some action.

**Comment by abhijitkane** [comment] 2020-09-22 10:36
@byrdman @grimsa This was a regression, unfortunately. We'll be including a fix for this in the subsequent release.

**Comment by chughmayank** [comment] 2020-12-09 10:01
hi @byrdman , @grimsa 

The issue has been fixed in Postman Native app version 7.36.0. Thanks for waiting for the fix 👍🏼 

Cheers!

**Closed as completed by chughmayank** 2020-12-09 10:01 UTC
Labels: bug, product/importers
