### ISSUE TITLE
Give an option to the user to mark a query parameter as optional

### ISSUE THREAD

**Issue by Yash-Singh1** [a85/POSTMan-Chrome-Extension#8846] opened 2020-07-28 17:39 UTC
**Is your feature request related to a problem? Please describe.**
It is not a problem but next to the option where you can put in a description for any query parameter there could be an option to mark it as optional and maybe even display that in the API Documentations that are generated.

**Describe the solution you'd like**
I want there to be an option for the user to make a query parameter optional.

**Describe alternatives you've considered**
There are alternatives where you could change the description of the request.

**Additional context**
![Screenshot from 2020-07-28 10-38-10](https://user-images.githubusercontent.com/53054099/88701181-8c093a00-d0be-11ea-9180-1236ec5de982.png)

**Comment by Raja-Simha** [comment] 2020-11-19 09:59
Duplicate of #7890

**Closed as completed by Raja-Simha** 2020-11-19 09:59 UTC
Labels: feature, product/documentation
