### ISSUE TITLE
No collections visible in Runner

### ISSUE THREAD

**Issue by Gans79** [a85/POSTMan-Chrome-Extension#2293] opened 2016-08-25 05:09 UTC
1. Postman Version: 4.6.2
2. App (Chrome app or Mac app): chrome
3. OS details: win86-32
4. Is the Interceptor on and enabled in the app: yes
5. Did you encounter this recently, or has this bug always been there: recently
6. Expected behaviour: 
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

when i click on runner i dont see any of my collections it is blank , earlier last week i was seeing all my collection

**Comment by sdnts** [comment] 2016-08-25 05:14
Hey @Gans79 Can you see your collections in the main Postman window? If yes, can you try relaunching the runner?

**Comment by Gans79** [comment] 2016-08-25 05:28
Yes i do see it in the main window and able to run individual APIs, But dont see them in runner , tried restarting the computer also on another windows machine still no go .

**Comment by numaanashraf** [comment] 2016-08-25 11:48
@Gans79 Could you open DevTools on the Runner window and let us know if there are any errors in the Console? http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/

**Comment by Gans79** [comment] 2016-08-26 00:32
Yes i see errors , see attached 
![chrome-error](https://cloud.githubusercontent.com/assets/21234415/17990344/2c3136c8-6b78-11e6-86f1-cddbce1f4ea0.jpg)

**Comment by Gans79** [comment] 2016-08-26 00:40
I got the problem .there was one collection added without a proper name ( guess postman named it as null ) 
After deleting it started appearing :)

**Comment by sdnts** [comment] 2016-08-26 07:11
@Gans79 You are indeed right. It looks like a collection naming problem.
This shouldn't have happened though. Can you elaborate what exactly you did so we can prevent this in the future? Thanks!

**Comment by Gans79** [comment] 2016-08-26 07:29
Sorry not sure how i added that collection. But bottom line is postman allows adding a collection without a name which should be handled .

**Comment by sdnts** [comment] 2016-08-26 07:32
Yes, which is what is weird, because we already have a check for that in place. You shouldn't have been able to create a collection with an empty name in the first place :P

Closing this, do let us know if you manage to reproduce this!

**Closed as completed by sdnts** 2016-08-26 07:32 UTC

**Comment by Gans79** [comment] 2016-08-26 08:06
Sure . Must say the tool is really awesome !! Kudos to your team :)
