### ISSUE TITLE
Postman for Linux Version 6.1.2 forgets scaling

### ISSUE THREAD

**Issue by oliverm2112** [a85/POSTMan-Chrome-Extension#4595] opened 2018-05-24 00:43 UTC
**Describe the bug**
Postman for Linux Version 6.1.2 forgets scaling between app launches

**To Reproduce**
1. Open app
2. Scale up or down using CTRL+ or CTRL-
3. Exit app
4. Re-open app; scaling back to default

**Expected behavior**
Remember scaling between sessions, per previous versions

**App information**
 - App Type: Native App for Linux
 - Version 6.1.2
 - Linux Mint 18.2

**Additional context**
Workaround: launch with `./Postman --force-device-scale-factor=1.3`

**Comment by sivcan** [comment] 2018-05-24 06:06
@oliverm2112 We're aware of this issue and have fixed this internally.
I'll update the thread once it has been released.

**Comment by sivcan** [comment] 2018-05-24 06:07
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4586

**Closed as completed by sivcan** 2018-05-24 06:07 UTC
