### ISSUE TITLE
Can't submit a form inside preview window

### ISSUE THREAD

**Issue by panuckov-nick** [a85/POSTMan-Chrome-Extension#5926] opened 2019-02-14 09:50 UTC
While testing implementation of an authorization server that is supporting OAuth 2.0 Implicit flow found that I can't pass through login for due to an error.

By request to the authorization server from Postman happening redirect to login page where user credentials should be used, but when I click "Login" button nothing happening, but in dev console I see error "Blocked form submission to '' because the form's frame is sandboxed and the 'allow-forms' permission is not set" this IFrame is added by Postman over HTML form on the page so I can't do nothing myself to change attributes responsible for enabling form submission.

**Steps to reproduce**
1) Navigate to any HTML page with the form on it that will be submitted by POST request
2) Fill the form with valid values and click "Submit" button

**Expected behavior**
The form is submitted successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/15320216/52777890-7f6d5f00-304d-11e9-8725-bb1e449628a8.png)
![image](https://user-images.githubusercontent.com/15320216/52778460-bdb74e00-304e-11e9-8a28-5c406949c3d1.png)

**App information (please complete the following information):**
 Windows App Postman v6.7.3

**Comment by numaanashraf** [comment] 2019-02-18 13:06
Thanks for the feedback @panuckov-nick. We are tracking this at #2646. Please follow that issue for updates.

**Comment by numaanashraf** [comment] 2019-02-18 13:06
Duplicate of #2646

**Closed as completed by numaanashraf** 2019-02-18 13:06 UTC
Labels: duplicate
