### ISSUE TITLE
Saving a request ending in a query (?something) appends an `=` to the end.

### ISSUE THREAD

**Issue by jxmot** [a85/POSTMan-Chrome-Extension#4203] opened 2018-02-16 08:39 UTC
## App Details:
```
Postman for Windows
Version 5.5.3
win32 10.0.16299 / x64
```

## Issue Report:
 1. Recently started testing an API that I want to use
 2. Expecting the API to return JSON formatted data, however the request fails.
 3. Console logs: Please see screenshot.
 4. Screenshots
<br>

**Console Showing Issue:**

![image](https://user-images.githubusercontent.com/20270843/36298318-2e87a2a2-12bd-11e8-92c5-7364501d3a8f.png)

## Issue Explanation

For API calls ending with a query such as - `?something` :

1. When the request is saved Postman will append an `=` to the end of the query. 
2. It becomes  `?something=`. It would seem that some APIs (_like the one seen in the screenshot_) will fail.

## Issue Reproduction

Start by opening the Postman console to able to see the issue.

1. Create a request that ends in `?something`.
2. Send it and observe the console. The request ends in `?something` as expected.
3. Save the request in a collection.
4. Open the saved request in a new tab. Observe that there is no `=` visible in the URL box.
5. Send it and observer the console. There is now a `=` appended to the end.

## Other Observations

1. Editing the request by removing and re-adding the `?something` does not remove the `=`.
2. The only work around is to copy and past from the failing request into a new request tab.
3. I did some research on queries and it seems that `?something` is considered a valid query.

## Desired Fix

Allow for what was described above. Perhaps a setting in Postman could be used to select whether or not a `=` is appended to the query at the end of the request. Or it would be really nice if it was an option that could be set within request when it is saved. Then that option would stay in place until manually reset before saving the request again.

Thanks!

**Comment by sivcan** [comment] 2018-02-16 08:48
Duplicate of issue https://github.com/postmanlabs/postman-app-support/issues/3991

Closing this.

**Closed as completed by sivcan** 2018-02-16 08:48 UTC

**Comment by jxmot** [comment] 2018-02-16 09:03
Sorry, I tried looking before I created it! But I'm happy to know it's being worked on!

**Comment by sivcan** [comment] 2018-02-16 09:03
@jxmot - No problem :)
