### ISSUE TITLE
Tab - close without prompt (settings option)

### ISSUE THREAD

**Issue by maciekdragan** [a85/POSTMan-Chrome-Extension#2195] opened 2016-07-23 13:48 UTC
It would be very convinient to close tab without prompt to "save it".
It could be option in settings.

**Comment by KRA2008** [comment] 2016-07-23 17:08
+1

**Comment by aditikul** [comment] 2016-07-28 05:49
@maciekdragan Unfortunately this was leading to some people losing their work when they close a tab. You can jump quickly through this modal by using the shortcuts space for "Don't Save" enter for "Save" and escape for cancel. Hope this helps.

**Comment by maciekdragan** [comment] 2016-07-28 08:35
@aditikul you are right. So maybe you can add this feature as an option in setting (for people knowing what they are dooing)? Or as a checkbox "don't as me again" in dialog box? I have many situations where I must close i.e. 10 tabs without saving it.

**Comment by KRA2008** [comment] 2016-07-30 22:34
I just started using the standalone Postman after using the Postman in-tab extension for a few years and the first thing I noticed was how annoying it was to close all those tabs. I don't think closing them would be quite as annoying if it just wouldn't open so many of them! It seems like it opens a new tab every time you do anything... my workaround right now is just to close the whole app and restart. This kills the tabs.

**Comment by stevemcmillen** [comment] 2017-01-05 18:19
Now I've noticed the app re-opened tabs at startup.  So that workaround no longer works.  You have to open a new window and close the previous one.

POSTMan used to have a settings checkbox that allowed you to tell it to close tab w/o prompting for save (much like the "dont ask me again" option suggested above).  It was convenient.  Now its gone.  I wish this option would just be brought back.  I mostly use postman for troubleshooting and often have to change values in the request but I almost never want to save those to the API definition.

This is really close to the top of my postman wish list (only topped by ability to save global functions )

@postman-admin, please add option to close w/o prompt for savings.  Or maybe if user is pressing Shift or command while closing don't prompt (thought I prefer the default always to be close w/o prompt)

Also, It would be nice if the Chrome app had a right click option to "Close all tabs" like the Mac app has.

**Comment by aiden56** [comment] 2017-02-15 09:32
+1 for "Close all tabs".

**Comment by dvkwong** [comment] 2017-02-16 21:00
Another +1 for 'Close all tabs' for people who know what they are doing. At the same time can we get the option to not reopen tabs on opening postman.

**Comment by sdnts** [comment] 2017-02-17 01:59
Guys, `Close All Tabs` as well as `Close All Other Tabs` is available on our native apps. It is unlikely that it'll come to the Chrome app, since the platform does not allow for context sensitive context menus. I'd recommend shifting to the native apps anyway, since all Chrome Apps will stop updating this July and will be discontinued later this year. (in regard to Google's [announcement](https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html))

**Comment by stevemcmillen** [comment] 2017-02-17 18:40
@madebysid,  understood.  I use the native app and have seen the "close all" option.  But what I was asking for is " close all *w/o prompt for saving*".  Make sense?

But i agree, the thread became a "+1 for close all tabs" which is NOT what I meant.

Actually, what I REALLY want is the "don't prompt to save changes" preference that was there long long ago.  I almost exclusively use the POSTMan for adhoc testing and debugging and I almost never want to save changes I make to the API.

**Comment by sdnts** [comment] 2017-02-22 13:53
@stevemcmillen Ah, understood. Tagging this a feature request. @a85

**Comment by jutley-hiya** [comment] 2017-03-02 18:01
I would really like this feature as well. Most of my collections remain static, and I intentionally make one-off modifications, knowing that I don't want the changes to be saved. If I could turn off this dialog, I'd certainly lose some work I wanted, but I'm positive that I'd get way more time back than having to tediously close and confirm each individual tab.

**Comment by ianjosephthompson** [comment] 2017-08-25 22:05
++ Please add a setting to disable the prompt to save when closing.  Very frustrating for me when I open and close dozens of tabs a day and very rarely need to save any of them.

**Comment by stevemcmillen** [comment] 2017-08-26 18:50
Many ages ago this was the default.  Sadly it was taken out and never returned :(  

I understand the need for caution but my hope is that it would be a pref (default to prompt but power users can go in and change).  I can't see why this would be very hard.

**Comment by bhawna2109** [comment] 2017-08-28 07:25
Hi guys, we understand the issue here and how this can be an impediment. To handle the use case when users do NOT want to save anything in Postman, we will be adding a 'Force close all tabs' option in this menu - 
![image](https://user-images.githubusercontent.com/14976346/29762863-39248d2a-8bee-11e7-900f-339d1ddac3c1.png)
Ofcourse, if you hit this option, you'll be asked to confirm your choice once, but this will close all tabs without popping up a confirmation modal for each tab. Thoughts?

At Postman, we treat 'users should not lose their work' as a first principle. This is why we had introduced a confirmation step when closing unsaved tabs, but as @stevemcmillen mentioned, we understand that people can have different use cases (for example using Postman only for troubleshooting), and it's important to support those as well :)

**Comment by dvkwong** [comment] 2017-08-28 07:53
How about a startup option in settings similar to chrome:

* open without tabs (does not prompt to save any open tabs)
* continue where you left off (prompts to save on closing tabs)

Although I can live with 'Force close all tabs' :) thanks

**Comment by stevemcmillen** [comment] 2017-08-30 23:18
There already is a method to close all tabs so I guess this only takes out the prompt on each one.    For me a better solution would be to allow a way to force close w/o a prompt by holding option key or something.  It would also be nice if this worked when opening new tabs (replace current tab instead of open new one).  Even better for my use cases is an option in prefs that says don’t ever prompt to save changes - just close any tab w/o prompt.  In this mode, opening a tab would always go to a new window but I suspect there are mixed opinions on this.— SteveOn Aug 28, 2017, at 12:25 AM, Bhawna Agarwal <notifications@github.com> wrote:Hi guys, we understand the issue here and how this can be an impediment. To handle the use case when users do NOT want to save anything in Postman, we will be adding a 'Force close all tabs' option in this menu -

Ofcourse, if you hit this option, you'll be asked to confirm your choice once, but this will close all tabs without popping up a confirmation modal for each tab. Thoughts?At Postman, we treat 'users should not lose their work' as a first principle. This is why we had introduced a confirmation step when closing unsaved tabs, but as @stevemcmillen mentioned, we understand that people can have different use cases (for example using Postman only for troubleshooting), and it's important to support those as well :)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/postmanlabs/postman-app-support","title":"postmanlabs/postman-app-support","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/postmanlabs/postman-app-support" class="">https://github.com/postmanlabs/postman-app-support</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bhawna2109 in #2195: Hi guys, we understand the issue here and how this can be an impediment. To handle the use case when users do NOT want to save anything in Postman, we will be adding a 'Force close all tabs' option in this menu - \r\n![image](<a href="https://user-images.githubusercontent.com/14976346/29762863-39248d2a-8bee-11e7-900f-339d1ddac3c1.png" class="">https://user-images.githubusercontent.com/14976346/29762863-39248d2a-8bee-11e7-900f-339d1ddac3c1.png</a>)\r\nOfcourse, if you hit this option, you'll be asked to confirm your choice once, but this will close all tabs without popping up a confirmation modal for each tab. Thoughts?\r\n\r\nAt Postman, we treat 'users should not lose their work' as a first principle. This is why we had introduced a confirmation step when closing unsaved tabs, but as @stevemcmillen mentioned, we understand that people can have different use cases (for example using Postman only for troubleshooting), and it's important to support those as well :)\r\n"}],"action":{"name":"View Issue","url":"<a href="https://github.com/postmanlabs/postman-app-support/issues/2195#issuecomment-325280305" class="">https://github.com/postmanlabs/postman-app-support/issues/2195#issuecomment-325280305</a>"}}}

**Comment by PaulvdDool** [comment] 2017-08-31 07:51
Ideally, I would like to have a settings option to disable or enable the prompt.
A force close function wouldn't allow me to quickly close 3 out of 5 tabs. The biggest annoyance from that would be that I would lose the tab with the authorization token and I would have to get the token again. But I guess I could just pick a call from the history tab.

**Comment by bhawna2109** [comment] 2017-08-31 11:47
@PaulvdDool @stevemcmillen Postman also allows opening multiple windows. Thus, if you decide to have a workflow when you do not want to save, you can open a new window and work there. Having a settings option locks the user inside modes and this is something we want to particularly avoid because there can be several configurations. From a users perspective, modes also introduce a cognitive load on the user because then the user has to remember which mode is active and be cautious of his/her actions.

**Comment by eightyeighteyes** [comment] 2017-09-15 15:40
I really really want an option to disable this prompt when a tab is closed.  I often work with a lot of temporary requests that I don't mind throwing away.  When I do accidentally close one, it's pretty easy to recover through the request history.

I just tried 'Close all tabs' and it prompted me for every open tab.  Closing one window appears to close EVERY Postman window (which seems like a different bug?).  I don't want to 'force close all tabs'... I just don't want to ever be bugged when I'm trying to close a tab.

None of these workarounds work for me.  I want an option!

**Comment by maciekdragan** [comment] 2017-09-15 16:16
If people want to lose their work by closing tabs without prompt, why not allow them to do so? Give them an option in settings, they're programmers, IT guys, they know what they are doing ;)

Nevertheless, I believe that the best solution already exists. It's implemented in Chrome browser:
ctrl + w  [close tab]
ctrl + shift + T  [restore tab]

Postman could save tab data before closing them, and restore if user want to do so.

**Comment by bhawna2109** [comment] 2017-09-18 08:02
@eightyeighteyes @maciekdragan Thanks for all the inputs. Improving this behavior is part of our next release - please stay tuned for updates on this!

**Comment by bhawna2109** [comment] 2017-10-09 07:12
Hi guys, ability to force close all tabs is now supported in our latest version [(V 5.3.0)](https://www.getpostman.com/apps#changelog). 🎉 Clicking on the three dots next to the '+' icon brings up a dropdown with options to manage the tabs you're currently working with.

The last option in the dropdown - 'Force close all tabs' - will close all the tabs without prompting to save each time - 
![image](https://user-images.githubusercontent.com/14976346/31327774-eca078a2-acee-11e7-8a7d-52a290bef376.png)

Additionally, you can use CMD/CTRL + ALT + W shortcut to force close the currently active tab. Holding down the ALT key and clicking on the 'x' icon also closes a tab without bring up the save modal.

**Comment by eightyeighteyes** [comment] 2017-10-10 14:37
Thanks for the update, @bhawna2109 !!! Unfortunately, the ctrl+alt+w shortcut does not work for me on Windows 10 (alt-click to close works, and everything works for me in macOS Sierra).

**Comment by bhawna2109** [comment] 2017-11-14 11:46
@eightyeighteyes sorry we missed this. I just tried it on my windows machine and it works for me. Could you recheck once and let us know if you're still facing this issue?

**Comment by eightyeighteyes** [comment] 2017-11-16 17:01
Thanks @bhawna2109 ... I uninstalled and reinstalled Postman and the feature behaves as expected.

**Comment by mlambley** [comment] 2018-01-18 04:26
https://github.com/postmanlabs/postman-app-support/issues/3386 is a duplicate of this. If you haven't already, I suggest having a look and seeing the grief encountered by many users at what I thought was a technical/workload limitation of the devs.

I'm following the discussion in this ticket and I can see that instead, it is a design decision. The original reasoning, that people are accidentally losing their work, was rebutted by a very reasonable suggestion that a "Don't show this again" tickbox be included, which can also be toggled in settings.

The argument against this has me somewhat confused. That allowing the user to set modes which apply to all open Postman windows will increase the cognitive load on the users and you want to avoid that. I'm sorry but what? You've included an irritating dialog box and refuse to allow users to remove it because you're concerned that it might overload your users' cognitive ability?

Thank you for implementing Ctrl+Alt+W, and showing that there are no technical limitations which prevent this feature from being implemented. Now, please, go one step further and make the design decision to include a very common UI feature, and allow your users to decide whether or not they wish to make use of it.

I would like to click the X or click my middle mouse button and see a tab disappear. It's not an unreasonable request, and I have the cognitive ability to remember that I've configured it to do so.

**Comment by brgrz** [comment] 2018-02-28 19:46
This is so annoying. We're developers, we know when to explicitly save when we actually want to.

![image](https://user-images.githubusercontent.com/193816/36809532-78ccec22-1cc8-11e8-9c06-9ec3ab4d87fd.png)

**Comment by cozzbp** [comment] 2018-03-15 20:09
+1

**Comment by kyeotic** [comment] 2018-05-03 15:37
The idea that we are losing work is wrong. If you close a tab you wanted to use you can re-open it from the History menu.

Or you could add an "undo close tab".

But _come on_, this is a hugely popular ask. Why is there so much resistance to this?

**Comment by ghost** [comment] 2018-06-04 12:27
+1. Postman is supposed to speed up the development, right? Add a setting for "do not ask to save" on tab close already! Make it false by default if you are worried about users losing work.

**Comment by paulop** [comment] 2018-06-12 22:01
Hello, in some notebooks hotkey "?" is Alt+w 
All times is closing a tab.
Can you fix that?

**Comment by HeXetic** [comment] 2018-08-14 14:33
Given that Postman _automatically_ remembers all previous requests, with no option to disable this functionality, it's really ludicrous to prompt us _every single time_ if we want to save a tab before closing it.

With the history behaviour, I treat Postman like I treat my browser. I manually save certain requests which are critical to me; anything else, I dig through the history to find again. I challenge the Postman developers to find a browser that will prompt to "add this to your bookmarks" before closing a tab.

**Comment by vkaegis** [comment] 2018-09-24 08:00
Quick update guys, it's taken a long while, but we're actively working on enabling this workflow. In addition the app will also remember previously closed tabs, so even if you closed something you needed by mistake, you will be able to restore it.

No ETA on this just yet, but stay tuned for more updates!

**Comment by a85** [comment] 2018-11-16 20:39
This is coming up in the next version! I tried this out on our internal channel and it works beautifully. Pretty excited about it.

**Comment by a85** [comment] 2018-12-09 16:19
Rolling out now with version 6.6!

**Closed as completed by a85** 2018-12-09 16:19 UTC
Labels: feature, tabs, buffers

**Comment by eugeneYWang** [comment] 2020-07-09 20:36
@a85 um...here comes another question then, how do I get the save prompt back?

**Comment by kamalaknn** [comment] 2020-07-10 05:22
Hey @eugeneYWang 

You can enable the setting to prompt for confirmation any time on the Settings view. You will find this under `Settings Icon` -> `General` tab, under `Request` section.

![Screenshot 2020-07-10 at 10 49 26 AM](https://user-images.githubusercontent.com/8401064/87119370-6b0db000-c29b-11ea-84d8-fa73bb842a5b.png)
