### ISSUE TITLE
GUI: POST, SEND and SAVE buttons overlapped  

### ISSUE THREAD

**Issue by sweetw0r** [a85/POSTMan-Chrome-Extension#2186] opened 2016-07-20 20:52 UTC
1. Postman Version: Version 4.4.2 (4.4.2
2. App (Chrome app or Mac app): Mac
3. OS details: OS X 10.11.4
4. Is the Interceptor on and enabled in the app: n/a
5. Did you encounter this recently, or has this bug always been there:
6. Expected behavior: Should not overlap
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable):
   <img width="1440" alt="screen shot 2016-07-20 at 1 43 25 pm" src="https://cloud.githubusercontent.com/assets/12688470/17002637/1dd37a82-4e81-11e6-961d-761cd6540691.png">

1. Open 5-7 tabs with set of calls
2. Work for some time switching and editing variables 
3. Start closing these tabs

**Comment by sdnts** [comment] 2016-08-02 11:49
Hey @sweetw0r, if you can reliably reproduce this, can you attach a screenshot of the Console logs (View->Toggle Dev Tools for the Mac app) along with it?
I'm not able to reproduce this, so it would also help if you could tell us if you were doing something specific when this happened.
Thanks.

**Comment by SamvelRaja** [comment] 2016-09-23 13:26
@sweetw0r closing this until reproduced 😄

**Closed as completed by SamvelRaja** 2016-09-23 13:26 UTC

**Comment by mroche89** [comment] 2017-08-23 01:05
I get this too. I am unable to reliably reproduce but it happens very regularly. Running on Windows 7. I am required to resize the application window to fix an individual tab. If the bug occurs on multiple tabs, I need to resize the window each time.

Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 59.0.3071.115
