### ISSUE TITLE
Postman Native app - Cannot signin with Google account enabled with Google Advanced Protection

### ISSUE THREAD

**Issue by belaie** [a85/POSTMan-Chrome-Extension#5015] opened 2018-08-13 08:36 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Cannot sigin with Google account enable with Google Advanced Protection,  It only works with Google Chrome Browsers, and Postman just stops there!.

**Describe alternatives you've considered**
No alternatives, 

**Additional context**
N/A

**Comment by belaie** [comment] 2018-08-13 10:01
This works only in Google Chrome extension, which is depricated oosn,  but it does not work in the Native app.

**Comment by numaanashraf** [comment] 2018-08-13 15:13
@belaie Thanks for writing in. This is currently not supported in Postman Native apps due to an underlying technical limitation. We are tracking this issue at #3697.

**Comment by numaanashraf** [comment] 2018-08-13 15:13
Duplicate of #3697

**Closed as completed by numaanashraf** 2018-08-13 15:13 UTC
