### ISSUE TITLE
No option to pass data file (csv/text) in postman collection so monitor can pick it

### ISSUE THREAD

**Issue by ManikandanRajendran** [a85/POSTMan-Chrome-Extension#5171] opened 2018-09-13 15:08 UTC
There is no option provided to feed data using external file (csv/text) in postman monitor. only we have few options like to select the collection and environment.

It would be great if it is included like how we are able to feed data from external when hitting API's through nodejs.

as we created API collections all depends on external data source we are unable to use postman monitors option to track the performance of our API's.

Below are options available in monitors,

![image](https://user-images.githubusercontent.com/17049131/45497206-da481500-b794-11e8-83bd-71643d613e4b.png)

Thanks,
Mani

**Comment by mohandacx** [comment] 2018-09-14 05:49
+1

Would be really helpful if we are able to pass data in the Monitors.

**Comment by anudeepmedicharla** [comment] 2018-10-09 03:44
@sankalp0o A few users also requested this feature during the workshop.

**Comment by numaanashraf** [comment] 2019-02-27 07:37
Duplicate of #3174

**Closed as completed by numaanashraf** 2019-02-27 07:37 UTC
Labels: feature, product/automation-testing
