### ISSUE TITLE
Encoding ✓ incorrectly in code view

### ISSUE THREAD

**Issue by recurse-id** [a85/POSTMan-Chrome-Extension#8596] opened 2020-06-05 18:12 UTC
**Describe the bug**
versions tested: 7.24 and 7.25

When ✓ is a value in one of the url parameters. If you go to the code view you will see that the check mark is encoded as %u2713

**To Reproduce**

Add ✓ as a value to a url parameter. 
Click the code button. 
You'll see the ✓ encoded as %u2713
**Expected behavior**
✓ should be encoded as %E2%9C%93

**Comment by cyrielle-hada** [comment] 2020-06-08 13:06
@recurse-id I didn't seem to be able to reproduce your issue in Postman version 7.25.3 using the code generator. The checkmark seems to be encoded correctly as `%E2%9C%93`.

![Screenshot 2020-06-08 at 13 59 54](https://user-images.githubusercontent.com/47351631/84033159-56828300-a990-11ea-9a25-0b7632b995ed.png)

![Screenshot 2020-06-08 at 13 59 11](https://user-images.githubusercontent.com/47351631/84033165-597d7380-a990-11ea-8b64-b218a33b41ca.png)

Would you please try to replicate the issue in [the latest release](https://www.postman.com/downloads/)?

**Comment by recurse-id** [comment] 2020-06-12 13:36
Oh yes, it's not a problem for all languages. Please check for it where the filter language is Python.

**Comment by DannyDainton** [comment] 2022-06-30 09:04
I'm unable to recreate this issue in the latest version of the platform. The encoding for Python seems to be the expected value.

Closing this for now but if you're still facing an issue we can look at reopening and investigating further.

**Closed as completed by DannyDainton** 2022-06-30 09:04 UTC
Labels: support
