### ISSUE TITLE
Interceptor debug sessions do not show URLs for captured cookies in the Cookies tab

### ISSUE THREAD

**Issue by figchutney** [a85/POSTMan-Chrome-Extension#10901] opened 2022-05-10 16:23 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

#### Context

When capturing cookies using the interceptor method, Postman displays an `Interceptor debug session` tab in the UI. Under this tab, there's the option to view either `Requests` or `Cookies` captured during the interceptor session, along with extra details about each.

#### Expected

When cookies are captured via Chrome using the interceptor, **the expected behaviour** is:

- the `Cookies` tab changes to show the number of cookies captured in brackets (e.g. `Cookies (3)`)
- under the `Cookies` tab, the URLs the cookies were captured from show up in table format (with the option to then click on each URL and view details about the cookies that have been captured).

#### Actual

In `9.18.1` (and I _think_ some earlier versions also), when cookies are captured via Chrome using the interceptor, **the following happens**:

- the `Cookies` tab changes to show the number of cookies captured in brackets (e.g. `Cookies (3)`), as expected
- under the `Cookies` tab, the outlines of a table for the URLs of the cookies that were captured show up, **however no text is shown - each row is simply blank** (see video). Running the mouse over the table slightly greys each row in the table, but no text shows up, and clicking anywhere in the table has no effect

#### Notes

- It _is_ possible to get the URLs to show up eventually by closing the interceptor session, at which point they become visible in the `Cookies` tab.
- The problem persists in both light and dark mode.

### Steps To Reproduce

- start a new `Capture requests` session
- choose the `Via interceptor` option
- ensure the `Capture Cookies` box is checked, and the interceptor is showing as `CONNECTED`
- click the `START CAPTURE` button
- make a request in Chrome that you know will result in cookies being captured
- observe the `Cookies` section in the `Interceptor debug session` tab shows an empty table with no URLs, despite the tab updating to `Cookies (n)` where `n` is the number of cookies that were captured

### Screenshots or Videos

https://user-images.githubusercontent.com/52138939/167676382-ae4106c0-5169-48e7-be62-a54f18d9d5f5.mov

### Operating System

macOS 11.6.1 Intel

### Postman Version

9.18.1

### Postman Platform

Postman App

**Comment by shashankawasthi88** [comment] 2022-05-11 06:38
@figchutney thanks for raising this. We are fixing this and would update the thread once the issue is fixed.

**Comment by shashankawasthi88** [comment] 2022-05-16 07:25
@figchutney this should be fixed on the latest version of the application. Feel free to reopen the thread if you still face the issue.

**Closed as completed by shashankawasthi88** 2022-05-16 07:25 UTC
Labels: bug, product/capture-proxy
