### ISSUE TITLE
Incorrect character escaping within Strings of Swift generated code

### ISSUE THREAD

**Issue by moored** [a85/POSTMan-Chrome-Extension#2933] opened 2017-04-10 19:41 UTC
When generating Swift code it is incorrectly escaping double quotes with two backslashes. It should only use one backslash.

Example:

Current code generation
``` Swift
let headers = [
  "x-docusign-authentication": "{\\"Username\\":\\"test@user.com\\",\\"Password\\":\\"secretpassword\\",\\"IntegratorKey\\": \\"special_integrator_key\\"}",
  "content-type": "application/json",
  "cache-control": "no-cache",
]
```

Correct code generation
``` Swift
let headers = [
  "x-docusign-authentication": "{\"Username\":\"test@user.com\",\"Password\":\"secretpassword\",\"IntegratorKey\": \"special_integrator_key\"}",
  "content-type": "application/json",
  "cache-control": "no-cache",
]
```

Version Info
 
1. Postman Version:  4.10.7
 2. App (Chrome app or Mac app): Mac App
 3. OS details: macOS Sierra 10.12.4 (16E195)
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: First time using feature
 6. Expected behaviour:
 
Steps to reproduce the problem

1. Create new request whose method is GET
2. Select code
3. Select Swift(NSURL)

**Comment by SamvelRaja** [comment] 2017-04-11 06:22
Thanks for bringing this to our notice we shall let you know the progress in the same thread.

**Comment by abhijitkane** [comment] 2019-04-19 03:30
<img width="502" alt="Screen Shot 2019-04-19 at 09 00 33" src="https://user-images.githubusercontent.com/681190/56403966-9e70b300-6281-11e9-897c-efb43242026f.png">

@moored Unable to reproduce this any more. Closing.

**Closed as completed by abhijitkane** 2019-04-19 03:30 UTC
Labels: bug, code-generator

**Comment by tomaculum** [comment] 2019-06-27 11:31
Ran into an related issue in Version 7.2.2 (7.2.2):

``` swift
import Foundation

let headers = [
  "Content-Type": "text/xml",
  "SoapAction": "urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1#GetAddonInfos"
]

let postData = NSData(data: "<?xml version="1.0" encoding="utf-8"?><s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:GetAddonInfosxmlns:u="urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1" /></s:Body></s:Envelope>".data(using: String.Encoding.utf8)!)

let request = NSMutableURLRequest(url: NSURL(string: "http://fritz.box:49000/igdupnp/control/WANCommonIFC1")! as URL,
                                        cachePolicy: .useProtocolCachePolicy,
                                    timeoutInterval: 10.0)
request.httpMethod = "POST"
request.allHTTPHeaderFields = headers
request.httpBody = postData as Data

let session = URLSession.shared
let dataTask = session.dataTask(with: request as URLRequest, completionHandler: { (data, response, error) -> Void in
  if (error != nil) {
    print(error)
  } else {
    let httpResponse = response as? HTTPURLResponse
    print(httpResponse)
  }
})

dataTask.resume()

```

the `postData` xml content is not escaped at all and should be:

``` swift
let postData = NSData(data: "<?xml version=\"1.0\" encoding=\"utf-8\"?><s:Envelope s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Body><u:GetAddonInfosxmlns:u=\"urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1\" /></s:Body></s:Envelope>".data(using: String.Encoding.utf8)!)
```

**Comment by abhijitkane** [comment] 2019-07-15 09:05
@tomaculum Can you try this is Postman 7.2+, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

In the new code, I see the following Swift code for a sample request with POST data:

```
import Foundation

var semaphore = DispatchSemaphore (value: 0)

let parameters = "<a b=\"c\">Hello</a>"
let postData = parameters.data(using: .utf8)

var request = URLRequest(url: URL(string: "https://httpbin.org/post")!, timeoutInterval: 0)
request.addValue("application/xml", forHTTPHeaderField: "Content-Type")

request.httpMethod = "POST"
request.httpBody = postData

let task = URLSession.shared.dataTask(with: request) { data, response, error in 
	guard let data = data else {
		print(String(describing: error))
		return
	}
	print(String(data: data, encoding: .utf8)!)
	semaphore.signal()
}

task.resume()
semaphore.wait()

```

**Comment by tomaculum** [comment] 2019-07-15 09:20
With this experimental codegen mode enabled the xml content escaping works correctly, thanks!
