### ISSUE TITLE
Pre-Request Script Has No Access to Inherited Authorization

### ISSUE THREAD

**Issue by d42ohpaz** [a85/POSTMan-Chrome-Extension#5219] opened 2018-09-20 16:26 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When setting the authorization on an endpoint, the `pm.request` object has an `auth` object describing the authorization. For example:

![screen shot 2018-09-20 at 10 28 44 am](https://user-images.githubusercontent.com/2528463/45825332-03e6cc00-bcc0-11e8-9f45-379077ecaaf3.png)

However, whenever the Authorization is set to `Inherit auth from parent`, the `pm.request` object does not have the `auth` object. 

**To Reproduce**
1. Create Endpoint that uses `Inherit auth from parent`
2. Add `console.log(pm.request.auth)` to `Pre-request Script`
3. Hit Send

**Expected behavior**
Expect an object defining the `Inherit auth from parent` option being chosen

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version v6.3.0
 - OS: macOS High Sierra 10.13.5 (17F77)

**Additional context**

**Comment by codenirvana** [comment] 2018-12-14 06:23
Duplicate of #4396

**Closed as completed** 2019-05-13 10:14 UTC
Labels: bug, duplicate, product/runtime
