### ISSUE TITLE
Add changing font feature

### ISSUE THREAD

**Issue by BruceAn1978** [a85/POSTMan-Chrome-Extension#7470] opened 2019-10-12 03:04 UTC
The default font family and size is not friendly to Chinese, the font size is smaller and is not clearly for Chinese, so it's hard to read clearly.

The best solution is change default font family to microsoft yahei and font size 12px, this is simple for the feature.

Hope postman gets better and better!

**Comment by numaanashraf** [comment] 2019-10-14 07:10
Thanks for the suggestion @BruceAn1978. We are tracking this at #4142.

**Comment by numaanashraf** [comment] 2019-10-14 07:11
Duplicate of #4142

**Closed as completed by numaanashraf** 2019-10-14 07:11 UTC
Labels: duplicate
