### ISSUE TITLE
Feature Request: Search and Replace URLs in API Requests

### ISSUE THREAD

**Issue by idevtech** [a85/POSTMan-Chrome-Extension#3406] opened 2017-08-17 21:02 UTC
Postman for Windows
Version 5.1.3
win32 10.0.15063 / x64

When a collection is duplicated it would be useful to be able to search and replace the URLs for the API requests. For example, I have ~50 requests in a collection and when it is duplicated manually replacing the domain portion of each URL is time consuming.

**Comment by bhawna2109** [comment] 2017-08-18 04:48
Thanks for explaining your use case @idevtech. This is actually on our roadmap :) Stay tuned for updates on this!

**Comment by a85** [comment] 2017-12-24 22:01
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1429

**Closed as completed by a85** 2017-12-24 22:01 UTC
Labels: feature
