### ISSUE TITLE
Selecting multiple subfolders of Collection for run from Collection Runner

### ISSUE THREAD

**Issue by Anjana-Entropik** [a85/POSTMan-Chrome-Extension#6360] opened 2019-04-25 08:36 UTC
We have several different Collections and each one of it as sub-folders for categorization. Currently through Postman Collection Runner, we setup entire Collection with sub-folders to run it only runs the very first folder and leaves the rest. 
Having a mechanism for selecting multiple folders within the Collection or picking up all sub-folders of collection when collection is run will resolve the problem
Please plan to address our concern

**Comment by hrocho** [comment] 2019-05-10 07:38
+1

**Comment by saswatds** [comment] 2019-05-21 19:49
Duplicate of #2392

**Comment by saswatds** [comment] 2019-06-17 10:50
The feature has been released as part of Postman Client App v7.2.0 🎉 
Closing this issue now.

**Closed as completed by saswatds** 2019-06-17 10:50 UTC
Labels: feature, collection-runner, product/runtime
