### ISSUE TITLE
"pm.response.to.not.have" causing subsequent "pm.response.to.have" to fail

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#5390] opened 2018-10-19 13:47 UTC
**Describe the bug**
Having "pm.response.to.not.have" before a "pm.response.to.have" will cause the latter one to fail as it is now expecting the header to be missing.

**To Reproduce**
1. Test the response to NOT have a header
2. Add tests afterwards expecting headers to be present (regardless of being in separate or same test function)
3. Run the request and all subsequent tests will fail

**Expected behavior**
pm.response.to.have should succeed if the header is actually present regardless of not method previously used.

**Screenshots**
![image](https://user-images.githubusercontent.com/43671684/47222093-d6b83700-d3ad-11e8-9055-d44e791d4e03.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.4.4
 - OS: Windows 10 Pro

**Comment by kunagpal** [comment] 2018-10-19 13:49
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3592

**Closed as completed by kunagpal** 2018-10-19 13:49 UTC
Labels: duplicate
