### ISSUE TITLE
After installing update postman app does not load

### ISSUE THREAD

**Issue by kyledavelaar** [a85/POSTMan-Chrome-Extension#5598] opened 2018-11-30 19:19 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I updated postman yesterday and now when I open the app, the app never loads.  The spinners just keep spinning. 

**To Reproduce**
see above

**Expected behavior**
The app should load so I can use it. 

**Screenshots**
<img width="1643" alt="screen shot 2018-11-30 at 11 19 06 am" src="https://user-images.githubusercontent.com/22839320/49310071-1d5f7d80-f492-11e8-8fa5-f16726448bcb.png">

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.1.4
 - OS: macOS High Sierra 10.12.6

**Additional context**

**Comment by mfaheemakhtar** [comment] 2018-12-01 14:42
Not sure if I'm facing the same problem but when I started the Postman today, it got stuck on the loading screen. I have recently installed some updates for Ubuntu 16.04 so the Postman may have got updated.

I tried running Postman from the terminal and saw that there was a permission error, I ran the Postman command with sudo and it worked.

**Comment by kamalaknn** [comment] 2019-03-18 09:55
Are you still seeing this in the latest version of Postman?

If yes can you send the logs to help us debug this. You can find the logs in View -> Developer -> View logs in Finder

After removing any sensitive information in them you can send them to `help@getpostman.com`

**Comment by mfaheemakhtar** [comment] 2019-03-18 11:00
Yes, still facing the issue. Sent the last two logs (without sudo and sudo) of main.log to the email. 

I've Ubuntu 18.04.2.

Update:

I got a reply from support with instructions to fix the issue. I deleted the Postman config (created a backup first) and then restored my settings and data from my backup. And it is working fine.

**Comment by numaanashraf** [comment] 2019-04-05 09:21
Duplicate of #4642

**Closed as completed** 2019-04-05 09:22 UTC
Labels: bug, updates
