### ISSUE TITLE
OAuth 2.0 Not Showing Saved Cookies in Windows Native

### ISSUE THREAD

**Issue by wolfordj** [a85/POSTMan-Chrome-Extension#2817] opened 2017-03-16 21:43 UTC
1. Postman Version:
4.10.3

 2. App (Chrome app or Mac app):
Windows Native

 3. OS details:
Windows 10

 4. Is the Interceptor on and enabled in the app:
N/A

 5. Did you encounter this recently, or has this bug always been there:
Recently downloaded native Windows version and it is always present

 6. Expected behaviour:
Use OAuth 2.0 Crendential manager to log into GitHub and provide OAuth permissions and sucessfully request a token. I would expect to see the session cookie stored in the `Cookies` manager but it lists no cookies. However, on subsequent requests to request tokens from GitHub the session cookie is still being sent. This means that there is no way to log out and request an access token for a different account.

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
No content is displayed in the Console

 8. Screenshots (if applicable)

Request a OAuth 2.0 token from GitHub, you will be prompted to log in as expected. Open cookies and notice there are no cookies listed. Request a 2nd token and you will NOT be prompted to log in which means cookies are being sent. This means I cannot login with a different account.

**Comment by a85** [comment] 2017-03-17 03:52
We are working on finer control over OAuth 2 modals. Don't think session cookies in the app are related to OAuth 2 based cookies in the auth flows.

**Comment by aggieben** [comment] 2017-03-28 16:45
So is there no workaround?  How are we supposed to test different users on APIs?

**Comment by kryptx** [comment] 2017-09-01 20:17
This is the issue preventing us from using postman more. 

We need to be able to authenticate arbitrary users against an OAuth 2 provider. The first time an access token is requested, it prompts for a username and password. For _some_ providers, each subsequent time, the previous credentials are re-used in some form.

Whatever that form is, it's definitely stored in a cookie. You can see them being sent by opening the inspector for postman and looking at request cookies, and if you just aggressively delete every cookie it'll prompt you again (ready your MFA devices before trying this one). So, there are cookies associated with that domain but they're not associated with our postman request, which makes sense because they weren't set for that request; they were set when we authenticated.

The problem is that they're kept after this flow is complete, with no option to clear them, so they just linger inside postman waiting to do their dirty deed when you unwittingly ask for another token.

Someone should check me on this, but I don't believe a session cookie from an OAuth 2 provider is a necessary part of any of the standard flows. It's just a convenience to their users. All Postman needs to do is provide a method for clearing cookies associated with the provider shown. The next iteration could also potentially notify or highlight something the moment it detects that they were set.

**Comment by kamalaknn** [comment] 2017-09-06 10:03
duplicate of https://github.com/postmanlabs/postman-app-support/issues/2049

**Closed as completed by kamalaknn** 2017-09-06 10:03 UTC
Labels: Auth
