### ISSUE TITLE
Pretty response of json not formatting like ealier

### ISSUE THREAD

**Issue by johnsonfash** [a85/POSTMan-Chrome-Extension#13280] opened 2024-11-20 05:49 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The pretty formatting for postman vscode extension is not working like ealier, it formats pretty well on the desktop but not the vs code extension.

### Steps To Reproduce

1. Open a new get request tab
2. Backend response is json
3. Click on pretty response
4. Click send
5. Response is not well formatted for (pretty) unlike the desktop version

### Screenshots or Videos

<img width="1710" alt="Screenshot 2024-11-20 at 6 46 58 AM" src="https://github.com/user-attachments/assets/180d4128-b3f7-409d-818e-5a069b340562">
<img width="1710" alt="Screenshot 2024-11-20 at 6 46 51 AM" src="https://github.com/user-attachments/assets/f97547fc-e011-4519-afb5-9ccd74b70d27">

### Operating System

macOS

### Postman Version

Postman VS Code Extension Version: 1.4.1

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by npgenx** [comment] 2024-11-20 22:02
This appear to be an issue with VSCode.   https://github.com/postmanlabs/postman-app-support/issues/13230.

Alledgedly scheduled for the Nov release.  Current workarounds are: 

1. Rolling back to [VSCode 1.94.2](https://code.visualstudio.com/updates/v1_94) 
2. Launch VS Code via Terminal with `code --disable-features=PlzDedicatedWorker`

**Comment by amaldinesh7** [comment] 2024-11-22 06:25
Closing as a duplicate of #13230.

**Closed as completed by amaldinesh7** 2024-11-22 06:25 UTC
Labels: vscode
