### ISSUE TITLE
Runner to show number of skipped tests

### ISSUE THREAD

**Issue by nils-work** [a85/POSTMan-Chrome-Extension#8512] opened 2020-05-20 02:24 UTC
**Is your feature request related to a problem? Please describe.**
I can't see a quick summary of the number of skipped tests in a run.

**Describe the solution you'd like**
Show some details for skipped tests in the same way as for Passed and Failed counts with the filter option on the left side to quickly review them.

**Describe alternatives you've considered**
Scroll through the long list of tests searching for any skipped lines marked with grey strike-through.

**Additional context**
Screenshot attached for basic suggestion.

![image](https://user-images.githubusercontent.com/60594671/82397879-c9d15d00-9a94-11ea-9500-bc1f3fd0f13e.png)

**Comment by malvikach** [comment] 2022-05-12 06:35
Duplicate of [this](https://github.com/postmanlabs/postman-app-support/issues/9590)

P.S: Original issue has been fixed

**Closed as completed by malvikach** 2022-05-12 06:35 UTC
Labels: feature, collection-runner, user-interface, product/runtime
