### ISSUE TITLE
After upgrading to Postman 7.0.9 it would not start on Windows Server 2012R2 64 bit 

### ISSUE THREAD

**Issue by mharrow-Diligent** [a85/POSTMan-Chrome-Extension#6426] opened 2019-05-06 22:21 UTC
**Describe the bug**
After upgrading postman to v 7.0.9 on my Server 2012 R2 64 bit it would not start. When I try to start it it load the loading window and then an error comes up as per bellow:

![image](https://user-images.githubusercontent.com/24662274/57258671-2ee82980-70b1-11e9-9501-d4c1957c6d5c.png)

And then it sits with loading screen forever: 
![image](https://user-images.githubusercontent.com/24662274/57258704-49220780-70b1-11e9-8d1d-97e9fe5bde30.png)

Server info:
![image](https://user-images.githubusercontent.com/24662274/57258854-c2b9f580-70b1-11e9-8def-7ee776b78eec.png)

I have **POSTMAN_DISABLE_GPU** system variable set to "**true**"  but it seems not to make any difference.

I have tried to completely uninstall and reinstall postman with no luck, running it as administrator does not make any difference either.

Thanks in advance.

**Comment by chrisdeso** [comment] 2019-05-07 07:46
Hey @marykanz – would you be able to send us some logs so that we can investigate further on our end? The logs can be retrieved by navigating to the app's menu bar `> View > Developer > View Logs in Finder` – compress/zip those files and send them over to us (help@getpostman.com).

A workaround would be clearing the app's cache. Deleting the following folders and restarting the app should do the trick:

- `C:\Users\<user>\AppData\Roaming\Postman​`
- `​C:\Users\<user>\AppData\Local\Postman`

Note that removing the directories above will wipe any locally-saved data. I'm not sure if you're leveraging our [sync feature](https://learning.getpostman.com/docs/postman/launching_postman/syncing/) but it backs up your saved collections/environments but requires that you have been logged in and are able to connect to the service. 

We can confirm whether or not you're using the feature if you submit a ticket via our help center or message me on the community forum – both would require that you use the email address associated with your postman account (if you have one).

- ### **Postman Community** – https://community.getpostman.com (@chris)
- **Help Center** – https://www.getpostman.com/support

**Comment by numaanashraf** [comment] 2019-05-22 12:15
Duplicate of #5591

**Closed as completed by numaanashraf** 2019-05-22 12:15 UTC
