### ISSUE TITLE
Body is not displayed for Content-Type →image/svg+xml; charset=utf-8

### ISSUE THREAD

**Issue by buennerbernd** [a85/POSTMan-Chrome-Extension#2077] opened 2016-05-20 14:06 UTC
Please include the following:
1. Postman Version: 4.2.1
2. App (Chrome app or Mac app): Chrome 50.0.2661.102
3. OS details: win / x86-32
4. Is the Interceptor on and enabled in the app: no

I have a get-request that returns an SVG.

Response headers displayed in postman:

Content-Length →7733
Content-Type →image/svg+xml; charset=utf-8

The body is not displayed. There is only a broken icon. Also Copy to clipboard and Save response don't work.
When I do the call in Chrome, the Image is displayed well.
My expectation is that the body was displayed as text. Additionally the rendering of the image in an extra tab would be great.

Expected body:

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 704"><rect x="0" y="0" width="1280" height="704" r="0" rx="0" ry="0" fill="#FAFAFA" stroke="#FAFAFA"></rect><path d=" M 0 32 H 1280 M 0 64 H 1280 M 0 96 H 1280 M 0 128 H 1280 M 0 160 H 1280 M 0 192 H 1280 M 0 224 H 1280 M 0 256 H 1280 M 0 288 H 1280 M 0 320 H 1280 M 0 352 H 1280 M 0 384 H 1280 M 0 416 H 1280 M 0 448 H 1280 M 0 480 H 1280 M 0 512 H 1280 M 0 544 H 1280 M 0 576 H 1280 M 0 608 H 1280 M 0 640 H 1280 M 0 672 H 1280 M 32 0 V 704 M 64 0 V 704 M 96 0 V 704 M 128 0 V 704 M 160 0 V 704 M 192 0 V 704 M 224 0 V 704 M 256 0 V 704 M 288 0 V 704 M 320 0 V 704 M 352 0 V 704 M 384 0 V 704 M 416 0 V 704 M 448 0 V 704 M 480 0 V 704 M 512 0 V 704 M 544 0 V 704 M 576 0 V 704 M 608 0 V 704 M 640 0 V 704 M 672 0 V 704 M 704 0 V 704 M 736 0 V 704 M 768 0 V 704 M 800 0 V 704 M 832 0 V 704 M 864 0 V 704 M 896 0 V 704 M 928 0 V 704 M 960 0 V 704 M 992 0 V 704 M 1024 0 V 704 M 1056 0 V 704 M 1088 0 V 704 M 1120 0 V 704 M 1152 0 V 704 M 1184 0 V 704 M 1216 0 V 704 M 1248 0 V 704" stroke-dasharray="4" stroke-dashoffset="6" stroke="#CCCCCC"/><polygon points="640,648 632,640 624,632 616,608 608,584 600,560 600,536 608,528 616,528 624,520 624,504 624,504 632,496 632,496 624,488 616,416 608,280 608,208 600,200 584,200 584,200 576,192 568,192 560,200 552,200 552,200 544,192 464,192 456,200 216,200 216,200 208,192 184,192 176,200 168,208 160,216 152,280 144,288 136,296 128,312 128,312 120,320 120,328 128,336 136,360 144,368 160,376 176,384 184,392 192,416 200,440 200,488 208,496 216,496 224,504 232,560 232,568 224,576 192,576 192,576 184,568 176,568 168,576 152,584 144,584 136,592 136,632 128,664 120,672 48,672 40,664 32,584 32,224 40,216 96,208 104,200 104,200 112,192 112,168 104,160 104,96 112,88 128,80 152,80 392,88 400,96 408,104 408,104 416,112 416,88 424,80 456,72 480,64 488,56 704,48 848,40 992,32 1192,32 1200,40 1208,104 1216,176 1216,208 1208,224 1208,224 1200,232 1200,240 1208,248 1216,256 1224,304 1232,368 1232,536 1224,544 1216,552 1208,560 1200,568 1192,576 1176,576 1176,576 1168,568 1096,568 1088,576 1080,576 1056,568 1048,560 1032,552 1032,552 1024,544 1000,544 992,552 984,624 976,632 904,632 904,632 896,624 768,624 760,632 696,640 688,648 " style="fill:#E0E0E0;fill-rule:evenodd" />
<polygon points="1032,56 1000,56 1000,64 1032,64 " style="fill:#61B081;fill-rule:evenodd" />
<polygon points="760,608 760,608 768,600 904,600 912,608 960,608 968,544 976,536 984,528 984,528 992,520 1024,520 1032,528 1056,536 1064,544 1176,552 1184,552 1192,544 1208,536 1208,480 1200,480 1192,488 1192,488 1184,496 1144,496 1136,488 1120,480 1120,480 1112,472 1112,424 1120,416 1128,408 1136,400 1136,400 1144,392 1176,392 1184,400 1200,408 1208,408 1208,376 1200,304 1192,264 1184,256 1184,256 1176,248 1176,224 1184,216 1192,200 1192,176 1184,104 1176,56 1080,56 1080,64 1088,72 1096,80 1104,96 1112,128 1120,160 1128,160 1128,160 1136,152 1152,152 1160,160 1160,160 1168,168 1168,184 1160,192 1152,200 1152,200 1144,208 1136,208 1128,200 1120,192 1112,168 1104,168 1096,176 1088,184 1072,192 1056,200 1048,208 1032,216 1024,224 1008,232 1000,240 1000,240 992,248 992,248 984,240 976,232 968,224 960,200 952,184 952,184 944,176 944,80 952,72 952,64 856,64 712,72 496,80 496,88 488,96 464,96 440,104 432,128 424,136 424,136 416,144 408,144 400,136 392,128 384,112 152,104 136,104 128,112 128,152 136,200 144,200 152,192 160,184 176,176 176,176 184,168 216,168 224,176 448,176 448,176 456,168 544,168 552,176 560,176 560,176 568,168 584,168 592,176 616,184 624,192 632,280 640,408 648,440 656,440 664,432 672,424 680,416 688,408 688,408 696,400 704,400 712,408 720,416 720,416 728,424 728,472 720,480 712,488 712,488 704,496 680,496 672,488 664,480 656,472 648,472 648,480 648,480 656,488 656,504 648,512 640,528 632,536 624,544 624,552 632,576 640,600 648,624 680,624 688,616 " style="fill:#61B081;fill-rule:evenodd" />
<polygon points="1032,200 1040,192 1056,184 1072,176 1080,168 1088,160 1096,152 1096,136 1088,96 1080,88 1072,80 1040,80 968,88 968,176 976,192 984,216 1008,216 1016,208 " style="fill:#61B081;fill-rule:evenodd" />
<polygon points="1120,160 1112,160 1112,168 1120,168 " style="fill:#61B081;fill-rule:evenodd" />
<polygon points="136,208 128,208 128,216 136,216 " style="fill:#61B081;fill-rule:evenodd" />
<polygon points="144,560 160,552 160,552 168,544 184,544 192,552 200,552 200,520 192,512 184,504 176,448 168,424 160,408 152,400 144,392 128,384 120,376 112,360 104,336 104,336 96,328 96,320 104,312 112,288 120,280 128,272 128,216 120,216 112,224 104,232 56,240 56,584 64,648 104,648 112,624 120,576 128,568 " style="fill:#61B081;fill-rule:evenodd" />
<polygon points="1176,416 1144,416 1136,424 1136,472 1184,472 1184,424 " style="fill:#61B081;fill-rule:evenodd" />
<polygon points="704,472 704,432 688,432 680,440 672,448 672,472 " style="fill:#61B081;fill-rule:evenodd" />
<polygon points="1000,56 1016,56 1016,64 1000,64 " style="fill:#C3FECE;fill-rule:evenodd" />
<polygon points="1024,56 1032,56 1032,64 1024,64 " style="fill:#C3FECE;fill-rule:evenodd" />
<polygon points="896,120 888,112 864,112 864,104 856,96 824,96 784,88 784,80 808.0,66.66666666666666 856,64 952,64 952,72 944,112 928,120 912,128 896,128 " style="fill:#C3FECE;fill-rule:evenodd" />
<polygon points="136,200 128,144 128,112 136,104 152,104 384,112 392,128 400,136 400,136 408,144 416,144 424,136 432,128 434.6666666666667,120.0 448,112 464,104 496,96 512,88 528.0,78.81481481481481 552.0,77.92592592592592 552.0,77.92592592592592 560,88 560,88 568.0,77.33333333333334 592.0,76.44444444444444 592.0,76.44444444444444 600,88 608,88 616.0,75.55555555555556 712,72 752.0,69.77777777777777 752,80 744,80 736,88 736,88 744,96 744,104 728,112 720,120 712,128 704,136 700.0,144.0 672,144 664,128 664,112 656,104 648,104 640,112 624,120 600,128 584,128 576,136 576,136 584,144 600,144 608,136 616,136 616,176 600.0,178.66666666666666 600.0,178.66666666666666 592,168 568,168 560,176 552,176 552,176 544,168 456,168 448,176 224,176 184,168 184,152 176,144 168,144 160,152 160,168 152,192 144,200 " style="fill:#C3FECE;fill-rule:evenodd" />
<polygon points="1056,208 1056,200 1072,192 1088,184 1096,184 1104,176 1104,168 1112,160 1112,160 1118.0,152.0 1114.0,136.0 1112,128 1100.0,88.0 1104,80 1096,72 1088,72 1080,64 1080,56 1176,56 1184.888888888889,112.0 1188.4444444444443,144.0 1176,152 1168,160 1160,160 1160,160 1152,152 1136,152 1128,160 1120,168 1117.3333333333333,184.0 1104,192 1088,200 1072,208 " style="fill:#C3FECE;fill-rule:evenodd" />
<polygon points="128,208 136,208 136,216 128,216 " style="fill:#C3FECE;fill-rule:evenodd" />
<polygon points="64,648 56,584 56,328 56,328 64,320 64,320 56,312 56,264 64,256 80,248 104,240 128,240 128,272 120,280 112,288 104,312 104,312 96,320 96,328 104,336 104,368 112,376 120,376 120,384 128,392 144,392 152,400 160,408 168,424 176,448 184,504 192,512 200,520 200,552 192,552 192,552 184,544 168,544 160,552 144,560 128,568 120,576 112,624 106.66666666666667,640.0 80,648 " style="fill:#C3FECE;fill-rule:evenodd" />
<polygon points="112,456 112,456 120,448 120,440 112,432 96,432 88,440 88,464 96,472 104,472 112,464 " style="fill:#61B081;fill-rule:evenodd" />
<polygon points="824,112 776,112 696,184 696,240 872,256 904,256 912,248 912,192 " style="fill:#E0E0E0;fill-rule:evenodd" />
<polygon points="616,168 616,136 640,112 656,112 672,128 672,168 656,184 640,184 " style="fill:#E0E0E0;fill-rule:evenodd" />
<polygon points="840,336 816,312 816,296 848,280 848,272 672,240 672,184 768,88 824,88 936,184 936,248 912,280 872,280 864,272 864,272 856,280 880,296 880,312 856,336 " style="fill:#E0E0E0;fill-rule:evenodd" />

**Comment by abhijitkane** [comment] 2016-05-20 14:07
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/2001

**Closed as completed by abhijitkane** 2016-05-20 14:07 UTC
