### ISSUE TITLE
Monitors misbehaving - Nothing in the API, Half missing on overview page

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6017] opened 2019-03-05 10:33 UTC
**Describe the bug**
Today something strange is going on with monitors, they have run as expected and all the Slack integrations have been displayed, going to each monitor directly or calling API for it is also all good, BUT:

- "Monitors" tab for the Workspace is only showing half of the monitors (all the ones started at 9AM UK time), the others (started 8AM UK time) are missing.
- Monitors API is returning empty array, as if there are NO monitors at all.

**Expected behavior**
All monitors should be displayed in the Monitors tab and monitors API should give us info on all available monitors.

**Screenshots**
![monitors api](https://user-images.githubusercontent.com/43671684/53799261-e639b600-3f31-11e9-9e9a-a882ee7f0da9.png)
![monitors tab](https://user-images.githubusercontent.com/43671684/53799262-e6d24c80-3f31-11e9-9c74-3407c2f0717f.png)
![caling specific monitor api](https://user-images.githubusercontent.com/43671684/53799260-e639b600-3f31-11e9-8d29-9fa16c4287bc.png)

**App information (please complete the following information):**
 N/A (Monitors)

**Comment by DarrylGwinnett** [comment] 2019-03-05 20:25
I raised a support ticket for this earlier today, and I've just had word a fix should be deployed to production within a few hours.

**Comment by VicKetchup** [comment] 2019-03-06 12:31
The API is still returning empty array :(

**Comment by DarrylGwinnett** [comment] 2019-03-06 12:52
> The API is still returning empty array :(

We just found this as well. Oddly, not empty for me. I see about a quarter of the monitors I should see. My colleague sees the other 75%, but not the ones I can see. But it's all fine on the dashboard. Very strange.

I've raised it with support.

**Comment by preethammavin** [comment] 2019-03-06 19:24
We have pushed a fix to solve it, can you check if the issue is resolved?

**Comment by VicKetchup** [comment] 2019-03-06 19:55
> We have pushed a fix to solve it, can you check if the issue is resolved?

Unfortunately no, still no monitors are showing in the response.

**Comment by godfrzero** [comment] 2019-03-06 20:08
The issue with the API and the previous issue with the UI are two different problems. The UI issue has been fixed and all monitors which are supposed to show up do show up in the Dashboard. The API issue is a bit more nuanced and I'll need some more time to push out a proper fix for it.

**Comment by VicKetchup** [comment] 2019-03-07 17:36
Not sure if the API issue is related to this, however when creating Slack integrations, not all monitors are shown (I am missing only a few, however my colleague can't see any, even if he creates a monitor himself).

**Comment by godfrzero** [comment] 2019-03-08 04:21
We've had an internal discussion and finalized how we're going to approach the fix. I'll post an update here again once the fix is out.

**Comment by VicKetchup** [comment] 2019-03-13 09:13
@godfrzero Are there any updates on the fix?

**Comment by DarrylGwinnett** [comment] 2019-03-15 21:44
Is there any ETA on a fix for this?

We rely on this to be able to integrate Postman monitor results in our dashboards, sadly this failing for over a week without an update is likely to cause my company to have to migrate away from Postman for our API monitoring.

**Comment by godfrzero** [comment] 2019-03-16 05:18
The API should be fixed in production within the coming week.

**Comment by godfrzero** [comment] 2019-03-25 14:03
Just FYI, the fixes are being reviewed and we're working on pushing them out.

**Comment by VicKetchup** [comment] 2019-04-05 10:13
Issue seems to be resolved on our side, been working fine for couple of days now.

**Closed as completed** 2019-04-22 02:29 UTC
Labels: bug, product/postman-api
