### ISSUE TITLE
Make the src parameter dynamic for uploading files from references stored in a csv data-file

### ISSUE THREAD

**Issue by amanautomation** [a85/POSTMan-Chrome-Extension#4521] opened 2018-05-03 18:50 UTC
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 16.4.0 / x64
newman 3.9.3
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Hi,

I wanted to check if there is a way to make the src parameter dynamic while uploading files as part of an API.

**Use case:** 
I have 5 files say (a.pdf, b.pdf, c.pdf, d.pdf and e.pdf) and I have to upload these files in 5 different iterations. The csv data file for iteration is in format:

**Test#,FileName,FilePath,ExpectedResponse** 
1, a.pdf, folder1/folderA/, 200
2, b.pdf, folder1/folderB/,400
3, c.pdf, folder1/folderC/, 200
4, d.pdf, folder1/folderD/,400
5, e.pdf, folder1/folderE/,400

I tried to use the following in my newman collection json file:

"formdata": [
                                                {
                                                        "key": "fileName",
                                                        "value": "",
                                                        "description": "",
                                                        "type": "file",
                                                        "src": "data.FilePath+\"/\"+data.FileName"
                                                }
                                        ]

But the same is not working and I gets error as "ReferenceError in test-script". I am not able to test the same using Postman UI as I need to make the src value a variable which I am not able to do in UI.

Thanks for your help.

**Comment by vikiCoder** [comment] 2019-08-23 09:34
Closing this as a duplicate of the following issue:
https://github.com/postmanlabs/postman-app-support/issues/5147

**Closed as completed by vikiCoder** 2019-08-23 09:34 UTC
Labels: feature, duplicate, product/runtime
