### ISSUE TITLE
Multilingual @ not doable

### ISSUE THREAD

**Issue by Crackroach** [a85/POSTMan-Chrome-Extension#3051] opened 2017-05-20 02:57 UTC
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app):
 3. OS details: Window 10
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour: I use a French Canadian keyboard and when i type @ (alt-car + 2) the app sometimes freezes but it never enter the @ symbol
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by Crackroach** [comment] 2017-05-20 03:00
I think i found out why. There is a keybind related to alt+ctrl+2 (Switch to builder) which is the same than alt-car+2. There is no way to change the binding so there is no way for me to fix the problem

**Comment by kamalaknn** [comment] 2017-05-22 13:36
Hi @Crackroach 

Thanks for sending in your feedback. This issue appears to be a duplicate of #2707. 

We haven't figured out a cleaner way to solve this yet. We will update the parent issue as soon as we have a fix for this.

**Closed as completed by kamalaknn** 2017-05-22 13:36 UTC
