### ISSUE TITLE
Postman spontaneously deleting starred collection folders

### ISSUE THREAD

**Issue by AmandaGBolton** [a85/POSTMan-Chrome-Extension#8683] opened 2020-06-19 13:19 UTC
**Describe the bug**
Yesterday and again today, while working in the Postman app, my starred collection folders in the current directory spontaneously disappeared. They do not appear in the app, in the web service, or in the trash on the web service. I have tried quitting and restarting, signing out and in again, but they are still gone. I was working on some code for a call at the latest time, not doing anything related to deleting collections. My app has also recently experienced trouble syncing, but I don't see why that issue would target specifically the starred folders. The non-starred folder collections remain untouched.

Update: I just reimported the two collection folders that disappeared (minus the uncommitted changes). One just spontaneously disappeared again even though it wasn't starred and I wasn't even doing anything in the program at the time (it was open while I used other applications). It might be an issue of old vs new folders. The starred ones are more recently imported vs. the not-starred folders.

**To Reproduce**
Unknown

**Expected behavior**
I expect my folders to not disappear without cause.

**App information (please complete the following information):**
Postman for Mac
Version 7.26.1
OS X 19.5.0 / x64

**Comment by vvs11** [comment] 2020-06-19 15:27
@AmandaGBolton could you write to us at help@getpostman.com? we will be able to provide better support to you

**Comment by bibAtWork** [comment] 2020-06-22 14:04
Same problem here, occurs when importing a postman_dump.

**Steps to Reproduce:**
1. Import a random postman dump file
2. Wait until postman sync has finished

**Expected Behavior**
Successful import should be durable and persistent.

**Actual Behavior**
Postman dump is imported successfully and is getting deleted during the postman device sync.

**App information (please complete the following information):**
Postman for Windows
Version 7.26.1
Windows 10 Enterprise Version 1809 64-Bit

**Notes:**
- Postman dump can not be attached due to sensitive data
- Error does not occur in earlier Postman versions like e.g. 7.23.1

**Comment by cyrielle-hada** [comment] 2020-06-24 10:11
@bibAtWork I wanted to check-in with you and see if you're still experiencing the behavior and if so, would you also be able to [raise a support ticket](https://go.pstmn.io/help-center-signin-newrequest) and send your logs as well as a screen record that shows how to replicate the behavior? To find the logs, please navigate to View > Developer > View Logs in Finder/Explorer.

<img width="1461" alt="85529025-8d999b00-b604-11ea-842b-0a34314c34c6" src="https://user-images.githubusercontent.com/47351631/85537061-8aee7400-b60b-11ea-973b-fd48dc09540d.png">

**Comment by ankit-m** [comment] 2020-06-25 04:17
We have pushed out a fix for this. Please reopen the issue if this is still happening for you.

**Closed as completed by ankit-m** 2020-06-25 04:17 UTC
Labels: support
