### ISSUE TITLE
Incorrect redirect following for HTTP 301 

### ISSUE THREAD

**Issue by VeselovAndrey** [a85/POSTMan-Chrome-Extension#4558] opened 2018-05-16 04:18 UTC
Postman don't use original request verb (POST, GET etc) and body when following redirect.

1) Enable "Automatically follow redirects" in Postman settings
2) Try to access resource 
* Accepts POST only (or any http verb except GET)
* Server supports HTTPS only and responds HTTP 301 for HTTP requests (to redirect them to HTTPS). For example it can be AppService hosted on Azure ( http://*.azurewebsites.net/ ) with "HTTPS Only" option enabled.
3) Postman will use new HTTPS URL but sends GET request
4) As result you will get "The requested resource does not support http method 'GET'" error for POST request.

 - Postman Version 6.0.10
 - OS: Windows 10

**Comment by sivcan** [comment] 2018-05-16 12:44
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4001

**Closed as completed by sivcan** 2018-05-16 12:44 UTC
