### ISSUE TITLE
Token manager feature request

### ISSUE THREAD

**Issue by aviweiss** [a85/POSTMan-Chrome-Extension#4911] opened 2018-07-28 14:15 UTC
The “use key” does not properly set the key to be used. It must also be selected and visible in key window.

It would be nice to have templatable “sprintf” auto-key key names for each collections: so for dev box: “dev: %t” would generate the key name “dev: 10:03” and “live: %d %t” would create “live: 2018-07-25 13:14”. This would help in knowing which key is current, though ideally would be nice to have expired keys “auto delete”.

**Comment by prashantagarwal** [comment] 2018-07-31 09:41
@aviweiss Can you add some screenshots.

**Comment by aviweiss** [comment] 2018-07-31 12:25
Not sure how to add those here, or what kind of screenshot you are looking for.

**Comment by aviweiss** [comment] 2018-07-31 17:49
<img width="866" alt="pm1" src="https://user-images.githubusercontent.com/940588/43477084-42d71264-94c8-11e8-84ff-c5f604d19b9b.png">
<img width="758" alt="pm2" src="https://user-images.githubusercontent.com/940588/43477085-42e61520-94c8-11e8-9c4f-183540c20e3d.png">
<img width="572" alt="pm3" src="https://user-images.githubusercontent.com/940588/43477086-42f60aa2-94c8-11e8-9701-c33df901e1d2.png">

first picture shows the key being obtained, the second that even though "use key" was selected, the key was not applied, and any requests made fail. The third shows the key having been selected from list now appears in input line and is available for use.

**Comment by vikiCoder** [comment] 2019-07-29 08:16
Closing this issue as a duplicate of the following issue:
https://github.com/postmanlabs/postman-app-support/issues/5823

**Closed as completed by vikiCoder** 2019-07-29 08:16 UTC
Labels: feature, Auth, OAuth2
