### ISSUE TITLE
Publish Collection with multiple sets of Environment Variables

### ISSUE THREAD

**Issue by deanlyoung** [a85/POSTMan-Chrome-Extension#8614] opened 2020-06-09 23:29 UTC
**Is your feature request related to a problem? Please describe.**
I would like to publish multiple Environment Variables to the public docs page. Right now I can only select one via the dropdown.

<img width="1046" alt="79293263-1dde9580-7e88-11ea-8c9e-333a1114cd5f" src="https://user-images.githubusercontent.com/2523456/84210551-d894a980-aa6d-11ea-94da-1d21a322254c.png">

**Describe the solution you'd like**
A multi-select list so that a user can choose the pre-defined Environment Variables we provide.

![Screen Shot 2020-06-09 at 4 26 32 PM](https://user-images.githubusercontent.com/2523456/84210666-1c87ae80-aa6e-11ea-9a2f-9226cb1a68e2.png)

**Describe alternatives you've considered**
We provide json files for these, but users may prefer to see the example live in the docs. It is also valuable to see the placeholders (i.e. empty variables).

**Comment by Raja-Simha** [comment] 2020-06-10 06:46
@deanlyoung can you explain how publishing multiple environments help your documentation consumers? We would like to understand this use-case better

**Comment by Raja-Simha** [comment] 2020-06-11 18:42
Duplicate of #4818

**Closed as completed by Raja-Simha** 2020-06-11 18:42 UTC
Labels: feature, product/documentation

**Comment by mbraidy** [comment] 2021-01-20 13:52
This can serve both the documentation and the sandbox at the same time.
A client can choose one environment to see our server API request url and chose another environment to see the sandbox request.

**Comment by raghuchinnannan** [comment] 2022-07-28 12:25
@Raja-Simha In our case, we have different host for each of our data center located in EU & US. We don't want to publish separate API documentation as all the endpoints are same except for change in host. Environments would be ideal for us, as users can either choose US / EU and get on with their life.

**Comment by sharapov-outsource** [comment] 2023-01-17 02:38
@postman-support do you forget about this? Any update on this? Would be very helpful for us.
