### ISSUE TITLE
How to upload a json file to create a POST request?

### ISSUE THREAD

**Issue by sasasa42** [a85/POSTMan-Chrome-Extension#3259] opened 2017-07-11 10:42 UTC
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by kamalaknn** [comment] 2017-07-11 11:03
Hey @sintoanto 

You can select the request method as `POST` and then find various options to upload a file under the `Body` section. You can then select the file you want to upload based on the type of request body you choose.

I'm closing this issue as this is not a bug with the Postman App itself. Feel free to continue the discussion here.

**Closed as completed by kamalaknn** 2017-07-11 11:03 UTC

**Comment by sasasa42** [comment] 2017-07-12 02:16
Hi @kamalaknn 
But, this does not work. I chose the file in the body section. After sending the request, what I am getting is just a piece of some info. PFA the screenshot.
<img width="964" alt="screen shot 2017-07-12 at 10 13 28 am" src="https://user-images.githubusercontent.com/30074470/28098784-debda506-66ea-11e7-81de-85f1b5629fde.png">
