### ISSUE TITLE
Stuck in white screen

### ISSUE THREAD

**Issue by dajneem23** [a85/POSTMan-Chrome-Extension#10800] opened 2022-03-29 18:29 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

i'm stuck in white screen when open postman
![image](https://user-images.githubusercontent.com/56623206/160680565-9dca1941-9ff4-42e1-867e-186fb8c02026.png)

### Steps To Reproduce

1. open postman
2. get stuck

### Operating System

windows

### Postman Version

9.15.1

### Postman Platform

Postman App

**Comment by DannyDainton** [comment] 2022-03-29 18:32
Hey @dajneem23 

This looks like a duplicate of this #10763. 

Could you follow the steps detailed here and let us know if the app works for you? 

https://github.com/postmanlabs/postman-app-support/issues/10763#issuecomment-1071909372

**Comment by dajneem23** [comment] 2022-03-29 18:34
> Hey @dajneem23
> 
> This looks like a duplicate of this #10763.
> 
> Could you follow the steps detailed here and let us know if the app works for you?
> 
> [#10763 (comment)](https://github.com/postmanlabs/postman-app-support/issues/10763#issuecomment-1071909372)

thanks you, i'll check this

**Comment by DannyDainton** [comment] 2022-04-01 16:36
Hey @dajneem23 - Did that solve the issue for you?

**Comment by dajneem23** [comment] 2022-04-01 16:45
@DannyDainton  yes it did, sorry i forgot to close issue, thanks you very much

**Closed as completed** 2022-04-01 16:45 UTC
Labels: bug, platform/windows, duplicate, product/desktop-foundation, version/9, component/gray-screen
