### ISSUE TITLE
Need to have option to reset selected environment/global variables in collection runner

### ISSUE THREAD

**Issue by sarfaraz49** [a85/POSTMan-Chrome-Extension#1402] opened 2015-09-02 10:03 UTC
There is no option to reset or delete the environment/global variables while running collection runner.
Variables can be set only in the requests inside the collection runner. This approach is not useful when we need to reset few variables before running the collection running. Right now the only option is to manually edit the variables via postman GUI.

**Comment by abhijitkane** [comment] 2015-09-02 10:09
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/1193

**Closed as completed by abhijitkane** 2015-09-02 10:09 UTC
