### ISSUE TITLE
The pre-request written in editor is not the one executed.

### ISSUE THREAD

**Issue by meetDeveloper** [a85/POSTMan-Chrome-Extension#5775] opened 2019-01-15 09:15 UTC
I wrote a pre-request script and saved it and then when I tested, the executed script was not the current script but the earlier script. Maybe the action when I saved script was not trigger so the earlier script is running.

**Comment by numaanashraf** [comment] 2019-01-16 04:15
@meetDeveloper Would it be possible to share a screen recording of this issue? We are having trouble replicating this.

**Comment by kamalaknn** [comment] 2019-01-16 04:23
@numaanashraf I saw this when it happened. This looks like an issue from the ace editor, where the internal state of the editor was updated but not propagated correctly outside. I verified that there is nothing wrong with the temporary cache on the tab storage. The tab storage wasn't aware of the change.

Closing and reopening the tab fixed the issue. It was hard to reproduce the same issue after that.

**Comment by sujayvenaik** [comment] 2019-04-09 07:19
@meetDeveloper Can you still reproduce this on the latest version? As far as I remember this was the case where the change handler from the underlying AceEditor was not getting called but closing and opening it again seemed to have fixed it for you.

**Comment by meetDeveloper** [comment] 2019-04-10 06:17
@sujayvenaik I was not able to reproduce it in that version also, don't know how it happened at that time.

**Comment by pankajk07** [comment] 2020-05-10 07:55
Fixed as part of v7.24

**Closed as completed by pankajk07** 2020-05-10 07:55 UTC
Labels: bug, code-editor
