### ISSUE TITLE
Collection browser in description edit mode behaves strangely

### ISSUE THREAD

**Issue by sankalp0o** [a85/POSTMan-Chrome-Extension#5257] opened 2018-09-26 12:13 UTC
If I'm editing the collection description from the collection browser and I open another collection in the browser, only the title changes.

1. Open Collection A in collection browser
2. Edit collection description
3. Try to open Collection B in collection browser

Expected behavior:
Since I'm intending to navigate away, the app should alert me to save/discard changes.

App information:
 macOS, native App v6.3.0

**Comment by numaanashraf** [comment] 2019-01-15 14:32
Duplicate of #5276

**Closed as completed by numaanashraf** 2019-01-15 14:32 UTC
Labels: bug, user-interface, duplicate
