### ISSUE TITLE
"Description" column on environment variables

### ISSUE THREAD

**Issue by danhowelldev** [a85/POSTMan-Chrome-Extension#8801] opened 2020-07-20 07:51 UTC
I couldn't see this raised anywhere - sorry if I missed it!

### Problem
I use postman environments to store various ID's needed for testing my endpoints. Sometimes I have multiple ID's that I switch between, with the same variable name. The IDs are mongo DB ids, so not easily memorable, and in order to remember which is which, I have taken to putting a description in the "Initial Value" field.

For example, my environment window could look like this:

```
Variable	Initial Value			Current Value
id		Description of the ID		5ccaxxxxxxxxxxxxxxxx295e
id		Description of another ID	5ccaxxxxxxxxxxxxxxxx295f
...
```

I "check" the one that I want to test with, and "uncheck" all the others.

### Possible Solution
What I'd really like is a "Description" column on the environment variables, where I can add these notes, so that I don't have to use the "Initial Value" field. If I ever want to export the environment, I have to "Persist" the values to the initial value field, but then I don't know what they represent.

Maybe there is another solution out there someone can suggest.

Thanks in advance 🙏

**Comment by DannyDainton** [comment] 2020-07-20 08:24
@Raja-Simha duplicate of https://github.com/postmanlabs/postman-app-support/issues/6714 ?

**Comment by Raja-Simha** [comment] 2020-07-20 08:39
Yes
Duplicate of #6714

**Closed as completed by Raja-Simha** 2020-07-20 08:39 UTC
Labels: feature, product/documentation, Environments, product/runtime
