### ISSUE TITLE
AWS auth sets default content-type as application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by govindrai** [a85/POSTMan-Chrome-Extension#4127] opened 2018-01-29 23:24 UTC
## App Details:
Postman for Mac
Version 5.5.2
OS X 10.13.1 / x64

Hi guys. Hope it's another good day at Postman Labs! We are using Postman's AWS Signature feature for signing requests. The problem is Postman sets the default content-type as application/x-www-form-urlencoded. Why? It's causing requests to fail and return "Unsupported Media Type" from AWS.

Also, this is another pleading request for Collection level headers as I need to send a common header in all requests.

**Comment by rbatta** [comment] 2018-02-22 03:41
I also encountered this on Postman Mac standalone v 5.5.3, OSX 10.12.6.  Annoyingly I couldn't get rid of that `content-type` header, which was the root cause. Couldn't edit, couldn't delete. I couldn't use cURL either w/ the given output because AWS complained that the signatures didn't match.

@govindrai here's what I did to get it working. My workaround was to find the link Chrome app version (thank you Google), make the same request with the same information, then once it fails, go to the Headers (4) part and delete the contents of `content-type` where the `application/x-www-form-urlencoded` was listed. Hit `Send` and boom! Things worked again.  Screenshot of what it looks like for me using the Chrome extension/app version attached below.

![image](https://user-images.githubusercontent.com/3965984/36519151-c6ab1480-173e-11e8-9f3a-f1c311294a03.png)

To the Postman Labs folks, can you please fix this for the Standalone version? Otherwise it's gonna be the deprecated Chrome app. :\

**Comment by govindrai** [comment] 2018-02-22 15:10
@rbatta No need to use the chrome app. Although you can't delete the content-type header auto-generated by postman, you can just add another content-type header below the auto-generated headers and when you hit send it will override the default postman header. It's not very clear that this is even possible or why that's even a thing, but the functionality is there. 😄 


Regardless, I stopped using this approach a while ago and opted to sign my requests through a simple custom-built node proxy as I was finding myself repetitively going into one of my hundreds of postman requests to update the headers one by one in order to override the content-type. 

If you have only a couple, this approach will work for the time being, but I hope they can get around to fixing this and providing collection level headers. Thanks for replying!

**Comment by numaanashraf** [comment] 2018-08-10 12:11
This is a confirmed bug. Seems to be caused by https://github.com/mhart/aws4/blob/master/aws4.js#L116.

**Comment by codenirvana** [comment] 2019-03-28 21:45
We've released a fix for this on our Canary (`version: 7.1.0-canary01`) channel https://www.getpostman.com/canary

Please try it out in the Canary version and let us know if you continue to face the issue.
Will update the thread once we release the fix on our stable channel.

**Comment by codenirvana** [comment] 2019-04-24 06:45
This has been fixed in the latest Postman app.

**Closed as completed by codenirvana** 2019-04-24 06:45 UTC
Labels: bug, Auth, auth/aws, product/runtime
