### ISSUE TITLE
Allow comments in Request Body

### ISSUE THREAD

**Issue by blackathol** [a85/POSTMan-Chrome-Extension#10919] opened 2022-05-17 23:09 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

No

### Describe the solution you'd like

In a request Body, particularly for 'raw' / 'JSON' format content, please allow comments. For example: 

{
    "field_name": "field_value",
    // This is a comment that is ignored in the request 
    "field_name2": "field_value2",
    "field_name3": "field_value3",
    "field_name4": "field_value4",
}

### Describe alternatives you've considered

There is no alternative.

**Comment by dhwaneetbhatt** [comment] 2022-05-18 07:03
The Postman does allow comments in the request body but sends the payload as-is to your server. The app does not show an invalid JSON or give linting errors after adding comments.

But the JSON spec does not allow comments in the body so maybe your server is rejecting the payload?

**Comment by josuamanuel** [comment] 2022-10-14 11:44
I think this would be a nice feature. @dhwaneetbhatt it is not true that the payload is sent as-is to the server. There is a preprocessing that for example resolve variables before sending to the server. 

`{
	"test": {{env}}
}`

is sent as:

`{
	"test": dev
}`

The behaviour could be added in the settings as:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/39583890/195838977-4825685d-64c5-4f7e-a30a-60e4876392a6.png">

**Comment by Sotatek-SonLai** [comment] 2022-11-09 05:43
Select collection, in the tab pre-request Script, you can paste bellow code:
`if (pm?.request?.body?.options?.raw?.language === 'json') {
    const rawData = pm.request.body.toString();
    const strippedData = rawData.replace(
        /\\"|"(?:\\"|[^"])*"|(\/\/.*|\/\*[\s\S]*?\*\/)/g,
        (m, g) => g ? "" : m
    );
    pm.request.body.update(JSON.stringify(JSON.parse(strippedData)));
}`

![image](https://user-images.githubusercontent.com/93107445/200748386-f36094e1-89eb-49fe-b6ae-ae29c1acbefc.png)

**Comment by johnson298** [comment] 2022-11-09 05:45
- Select your collection
- In the tab `Pre-request Script`, you can paste bellow code:
`
if (pm?.request?.body?.options?.raw?.language === 'json') {
    const rawData = pm.request.body.toString();
    const strippedData = rawData.replace(
        /\\"|"(?:\\"|[^"])*"|(\/\/.*|\/\*[\s\S]*?\*\/)/g,
        (m, g) => g ? "" : m
    );
    pm.request.body.update(JSON.stringify(JSON.parse(strippedData)));
}
`

![image](https://user-images.githubusercontent.com/51223025/200748654-dc7888f3-c86b-4fe1-a15c-a28177af1e1c.png)

**Comment by johnson298** [comment] 2022-11-09 05:47
- Select your collection
- In the tab `Pre-request Script`, you can paste bellow code:
`
if (pm?.request?.body?.options?.raw?.language === 'json') {
    const rawData = pm.request.body.toString();
    const strippedData = rawData.replace(
        /\\"|"(?:\\"|[^"])*"|(\/\/.*|\/\*[\s\S]*?\*\/)/g,
        (m, g) => g ? "" : m
    );
    pm.request.body.update(JSON.stringify(JSON.parse(strippedData)));
}
`
![image](https://user-images.githubusercontent.com/51223025/200748998-c4dd6eb9-1597-420e-bad5-01db7def3442.png)

**Comment by codenirvana** [comment] 2023-02-20 05:21
Duplicate of #3358

**Closed as completed by codenirvana** 2023-02-20 05:21 UTC
Labels: feature, product/runtime, request-body-format, comments
