### ISSUE TITLE
Postman could not start - default workspace missing

### ISSUE THREAD

**Issue by liniukesi** [a85/POSTMan-Chrome-Extension#5208] opened 2018-09-19 09:52 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
postman could not work,always stay at start page

**To Reproduce**
double click on app and wait...

**Expected behavior**
app start successfully.

**Screenshots**
1.get these messasges from console view :
![image](https://user-images.githubusercontent.com/5425209/45745765-259a7180-bc34-11e8-9720-7a03d40a6f9e.png)

2.app always stay at start page:
![image](https://user-images.githubusercontent.com/5425209/45745961-9a6dab80-bc34-11e8-8d05-184420627426.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version [6.3.0]
 - OS: window 10 professional

**Comment by liniukesi** [comment] 2018-09-26 02:06
Is anyone working on it?

**Comment by numaanashraf** [comment] 2019-03-18 11:29
Duplicate of #4883

**Closed as completed by numaanashraf** 2019-03-18 11:29 UTC
Labels: bug, launch
