### ISSUE TITLE
JSON response body - Pretty View showing escape characters

### ISSUE THREAD

**Issue by mds1256** [a85/POSTMan-Chrome-Extension#7017] opened 2019-07-29 14:19 UTC
**Describe the bug**
It seems Postman now shows escaping slashes when returning a json response containing forward slashes, e.g. `01/01/2019` now shows up as `01\/01\/2019`

**To Reproduce**
1. Call an endpoint that returns forward slashes in a JSON response and you will see this.

**Expected behavior**
The pretty display setting should show without any escaping slashes.

**App information (please complete the following information):**
Native App
Postman v7.3.4
Windows 10
Also happening on Mac

**Comment by jonnyijapan** [comment] 2019-07-30 08:48
I think you meant to add backslashes? I think the github UI however mangles it unless we put it in a code block or something.

    e.g. 01/01/2019 now shows up as 01\/01\/2019


Btw I also realized this issue. Not sure when it started happening, but I think it's semi-recently.

**Comment by mds1256** [comment] 2019-07-30 09:20
@jonnyijapan Yeah sorry, forgot to add the code block but your example is what is happening.

At least it isn't just me, I would say in the past 2 months, as the last time I updated postman was around 2 months ago and then again yesterday and now I have this issue.

**Comment by ErSoul** [comment] 2019-07-30 10:15
In my case, it started happening two days ago. It sucks, because now I can't navegate easily through the links the responses returns. Instead I have to backslashes one by one, before going to another request.

**Comment by jonnyijapan** [comment] 2019-07-31 00:42
Also I suspect that the escaping of forward slashes within string values in JSON by itself is a mistake, and according to the [RFC](https://www.ietf.org/rfc/rfc4627.txt) is not needed;

```
2.5.  Strings

   The representation of strings is similar to conventions used in the C
   family of programming languages.  A string begins and ends with
   quotation marks.  All Unicode characters may be placed within the
   quotation marks except for the characters that must be escaped:
   quotation mark, reverse solidus, and the control characters (U+0000
   through U+001F).
```

**Comment by COB-SM** [comment] 2019-07-31 19:35
@mds1256 It looks like this has been fixed in the Canary build...

**Comment by kamalaknn** [comment] 2019-08-02 11:29
Hey @jonnyijapan @ErSoul @mds1256 

This is a regression introduced in the 7.3 version of Postman App. as @COB-SM mentioned we have pushed a fix for this on the [Canary Channel](https://www.getpostman.com/downloads/canary).

We will be pushing this to the stable channel soon. We are tracking this as part of #6899

I'm closing this as a duplicate. Please follow the original thread for updates.

**Closed as completed by kamalaknn** 2019-08-02 11:29 UTC

**Comment by maidi-yang** [comment] 2019-12-02 02:40
![image](https://user-images.githubusercontent.com/22462895/69926592-ffd35280-14ef-11ea-830a-fa4e0b18aedc.png)
How can I solve this problem?

**Comment by kamalaknn** [comment] 2019-12-02 05:41
@maidi-yang Could you let us know the version of Postman you are using? Could you also attach a screenshot of the raw response you see under the `raw` tab?
