### ISSUE TITLE
Including call type in tab hides tab name when multiple calls open

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#5324] opened 2018-10-08 14:08 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Since the new update to 6.4.2, the type of call (e.g. `GET`, `POST`, etc.) are included in the tab. This is great, however when several tabs are open and the tabs shrink, now pretty much all you can see is the method and the first couple letters of the name, making it incredibly difficult to see which tab is which. Before the method was included, there was enough visible text to determine which tab is which, however now I have to go into each tab to see which one it is.

**To Reproduce**
Open up a lot of tabs (20+) causing all tabs to shrink down to the smallest size.

**Expected behavior**
I would expect to be able to see the name of the call. Perhaps hide the method when the tabs shrink below a certain size, because I do like the idea of having it on there, just not when the tab is tiny and it takes up the entire tab.

**Screenshots**
<img width="1058" alt="screen shot 2018-10-08 at 9 54 33 am" src="https://user-images.githubusercontent.com/16259311/46613642-b781f580-cae1-11e8-8c28-df52083da801.png">

**App information (please complete the following information):**
Postman for Mac
Version 6.4.2
OS X 18.0.0 / x64

**Additional context**

**Comment by sujayvenaik** [comment] 2018-10-09 05:30
Duplicate of #5310

**Closed as completed by sujayvenaik** 2018-10-09 05:30 UTC
