### ISSUE TITLE
Crashing while using Runner

### ISSUE THREAD

**Issue by Exvitermini** [a85/POSTMan-Chrome-Extension#6778] opened 2019-06-24 16:58 UTC
**Describe the bug**
I have a set of tests that I run in the Runner every day multiple times. The tests have not changed. Since the update to version 7.2.0, the runner window will go black and freeze. When I close the runner window, it will crash Postman as a whole. There has been two updates since (7.2.1, and 7.2.2) but those of those versions also exhibit the same issue.

**To Reproduce**
1. Open Runner window
2. Choose the folder of tests and environment and/or other options
3. Normally I run tests with "Keep variable values" enabled
4. Couple of minutes after the tests start running, the Runner window goes black

**Expected behavior**
Finish running the tests and show the results

**Screenshots**
Please see attached screenshots
![Screen Shot 2019-06-24 at 10 40 22](https://user-images.githubusercontent.com/4072314/60037332-e4c60200-9676-11e9-86f5-8ebdc97a93e7.png)

![Screen Shot 2019-06-24 at 10 41 02](https://user-images.githubusercontent.com/4072314/60037351-f0b1c400-9676-11e9-99e1-b31fab859802.png)

![Screen Shot 2019-06-24 at 10 41 55](https://user-images.githubusercontent.com/4072314/60037369-f5767800-9676-11e9-80a7-ff48ef9e04fb.png)

![Screen Shot 2019-06-24 at 10 42 29](https://user-images.githubusercontent.com/4072314/60037377-f9a29580-9676-11e9-9ebd-f7f31207df02.png)

**App information (please complete the following information):**
 - Postman Version 7.2.2
 - OS: Mojave version 10.14.4

**Additional context**

**Comment by shamasis** [comment] 2019-06-24 18:42
Hmm this is bad. Is this happening for any collection you run or there’s something specific to it? Either there’s a memory related issue or something underlying is crashing. I tried to reproduce this by running a simple collection as hosted here https://docs.api.getpostman.com/?version=latest and could not.

Any way you can share a non sensitive scaled down collection with open APIs that exhibit this behaviour? Else, you can email us the collection at help@getpostman.com and we will investigate there.

**Comment by Exvitermini** [comment] 2019-07-05 15:52
Hi,
Very sorry for the delayed response. It seems like it's not tied to a collection. It looks like the runner window it self is crashing. I think it happens while it tries to load the "Recent Runs" on the right side of the Runner window. Please see the screen recording. I hope this helps.
Video is 2:22 in length. https://youtu.be/HMauSSDJC_0
Thank you

**Comment by saswatds** [comment] 2019-07-05 16:26
@Exvitermini I believe that the running turning black and crash during loading of Recent Runs are two distinct issues. 
I have been trying to replicate the crashing and have kind of succeeded in doing so but never reached a state of window turning black. My findings point towards the runner running out of permitted memory.

I would like to know a little bit more on the nature of collection that results in the black screen.
Think like, but not limited to
* Is there a usage of environment variables, if so how are they being used (is data being accumulated in a variable)?
* Are there only tests in the scripts or does it include other kinds of logic?
* Have you opted-in for saving the responses?

Regarding the runner window hanging while it's loading, I shall try to find the root cause for it meanwhile and if you could help me these few facts it would be great
* What is estimated number of collections in your workspace?
* Do you have any examples stored for your request?

**Comment by Exvitermini** [comment] 2019-07-05 20:30
@saswatds thanks for getting back to me.
The collection I run on a daily basis has 161 requests in it and is synced with a team. 
It uses both environment and global variables and the most of the requests set/replace environment variables. All together it has about 130 variables. 
The script each request run are mostly tests and has some minor logic to check if elements and values are correct.
Normally I run 1 iteration while "Keep variable values" enabled only. I do not save responses.
In the workspace I have 3 collections. Biggest collection has 161 requests, next has 53 requests and last one has 10.
I'm very sorry but I cannot send you my collections or examples of requests as it's all sensitive stuff.
I hope i've answered your questions above.
Please let me know if you need more info.

**Comment by saswatds** [comment] 2019-07-08 05:46
Thanks @Exvitermini, this will it for now. I will keep this thread updated once there is some finding.

**Comment by saswatds** [comment] 2020-02-12 07:31
We have pushed all of our performance fixed to the stable version 7.18.0. The runner should be snappier and not crash. Can you update to the latest version and check if this issue is fixed for you?

**Comment by saswatds** [comment] 2020-03-11 05:22
Closing this issue now as other users have reported that the issue is fixed for them. Feel free to reopen if the issue still persists for you.

**Closed as completed by saswatds** 2020-03-11 05:22 UTC
Labels: bug, performance, collection-runner, product/runtime
