### ISSUE TITLE
Crash on Windows 10 Pro & macOS with certain URLs Postman v7.1.1

### ISSUE THREAD

**Issue by harold-b** [a85/POSTMan-Chrome-Extension#6571] opened 2019-05-21 23:43 UTC
**Describe the bug**
Postman crashes on macOS and Windows when hitting "Send" with certain URLs on **v7.1.1**
The URLs which caused this were URLs which started with special characters (**!**, **'** or **"**) followed by http/https.

**To Reproduce**
1. Create a new request and paste the following in the URL entry box.
```
!https://google.com
```
2. Press "Send".

**Expected behavior**
Perform an HTTP request as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/11462418/58137327-e1ff6980-7bff-11e9-8e9e-85e8762f6016.png)

**App information (please complete the following information):**
 - Postman Versionv 7.1.1
 - OS: Windows 10 Pro 1803, macOS 10.14

**Comment by numaanashraf** [comment] 2019-05-22 10:37
Thanks for reporting this. I was able to replicate this. I'm attaching a screenshot of the cause of the crash from the logs here and we'll get this resolved in the upcoming releases.

<img width="794" alt="Screenshot 2019-05-22 at 4 05 18 PM" src="https://user-images.githubusercontent.com/3295568/58168299-8b4f6980-7cab-11e9-85a9-d789860a0853.png">

**Comment by codenirvana** [comment] 2019-06-11 10:41
Duplicate of #6533

**Closed as completed by codenirvana** 2019-06-11 10:41 UTC
Labels: bug, product/runtime
