### ISSUE TITLE
Generating Postman collection from imported OpenAPI 3.0 definion does not generate authorization config 

### ISSUE THREAD

**Issue by volphy** [a85/POSTMan-Chrome-Extension#8663] opened 2020-06-15 14:25 UTC
**Describe the bug**
I have tried to import a valid OpenAPI 3.0 compliant API definition and generate a Postman collection to test this API. 
My API included API Key specification as defined in OpenAPI:
https://swagger.io/docs/specification/authentication/api-keys/

API key was defined to be used by all operations:
```
[...]
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
[...]
security:
  - ApiKeyAuth: []
```

Generated collection did not include any authorization configuration.

**To Reproduce**
1. Go to 'APIs'
2. Click on 'New API'
3. Enter API details: Name and Version
4. Choose Schema type: OpenAPI 3.0
5. Choose Schema format: YAML
6. Import API schema
7. Go to newly imported API
8. Click on 'Generate Collection'
9. Name your collection
10. Choose 'Test the API'
11. Click on 'Generate Collection'
12. Switch to Collections
13. Choose newly generated collection
14. Choose 'Edit collection'
15.  Check 'Authorization' type configured
16. Instead of 'API Key' I can see 'No Auth'

**Expected behaviour**
I would assume that 'API Key' with sample values should be configured as authorization type.

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.26.0. 
- OS: MS Windows 10 Version 1809 (OS Build 17763.1282)

**Additional context**
N/A

**Comment by shanecp** [comment] 2020-07-12 12:15
Leaving code to reproduce this issue. This is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/7427

Can confirm this is a bug. Example to reproduce the issue is below. Both AccessToken and APIToken should be added, but it doesn't.

Also the root level security components are not added to the internal routes as required by the spec.

```
openapi: 3.0.2
info:
    title: 'Open API v3'
    version: 1.0.0.20200712
servers:
    -
        url: 'http://example.com'
        description: desc
components:
    securitySchemes:
        SecurityApiKey:
            type: apiKey
            description: 'Application API Key'
            name: x-api-key
            in: header
            schema:
                type: string
                example: '{{x-api-key}}'
        SecurityAccessToken:
            type: apiKey
            description: 'User access token'
            name: x-access-token
            in: header
            schema:
                type: string
                example: '{{x-access-token}}'
paths:
    /api/v1/guests:
        get:
            responses:
                '200':
                    description: Success
            security:
                - SecurityAccessToken: []
                - SecurityApiKey: []
security:
    - SecurityApiKey: []
```

**Comment by DannyDainton** [comment] 2020-08-24 14:30
Duplicate of #7427

**Closed as completed by DannyDainton** 2020-08-24 14:30 UTC
Labels: importer, duplicate
