### ISSUE TITLE
Consider `charset` parameter in `Content-Type` header for server-sent events

### ISSUE THREAD

**Issue by yeonho84lee** [a85/POSTMan-Chrome-Extension#11773] opened 2023-02-28 06:44 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I read [Introducing support for server-sent events in Postman](https://blog.postman.com/support-for-server-sent-events/) with excitement. But I can not use the endpoint written in python [FastAPI](https://github.com/tiangolo/fastapi) framework.

Most web frameworks, including FastAPI (version 0.92.0), can include charset parameter in the Content-Type header.
The response header of the FastAPI endpoint have the charset parameter.

In the response HTTP headers, look for the `Content-Type` header, and in particular for the `charset` parameter, e.g.
```
Content-Type: text/event-stream; charset=utf-8
```

See the curl command using my local endpoint and the HTTP Response:

```shell
curl -v '127.0.0.1:8000/stream'
*   Trying 127.0.0.1:8000...
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET /stream HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Tue, 28 Feb 2023 06:37:56 GMT
< server: uvicorn
< cache-control: no-cache
< connection: keep-alive
< x-accel-buffering: no
< content-type: text/event-stream; charset=utf-8   <- This is inserted by FastAPI EventSourceResponse
< Transfer-Encoding: chunked
< 
id: 1
event: notification
data: message_content

id: 2
event: notification
data: message_content
...
```

### Steps To Reproduce

You can use the following `fastapi` endpoint written in Python.
- https://github.com/harshitsinghai77/server-sent-events-using-fastapi-and-reactjs#server-side

### Operating System

Any

### Postman Version

10.10.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by appurva21** [comment] 2023-02-28 06:53
@yeonho84lee Thanks for writing in! We'll get this fixed soon. You can follow this [thread](https://github.com/postmanlabs/postman-app-support/issues/11753) for further updates.

---

Closing this as duplicate of #11753

**Closed as completed by appurva21** 2023-02-28 06:53 UTC
Labels: bug, product/api-client

**Comment by appurva21** [comment] 2023-03-20 11:10
Hey @yeonho84lee! This issue is now fixed in the latest version of the Postman app (v10.12.0).
