### ISSUE TITLE
Request Editor switches to Another request when coming back from Example Editor

### ISSUE THREAD

**Issue by sumit0k** [a85/POSTMan-Chrome-Extension#5023] opened 2018-08-14 06:01 UTC
**Describe the bug**
When I edit any example for a request, and then click the back to request link in top left, I am shown details of another request with sidebar still highlighting correct request. 

**To Reproduce**
1. Go to 'any request'
2. Click 'Examples'
3. Change details of Example
4. Click on 'back to request link in left top'

**Expected behavior**
The request for which examples have been edited should be shown.

**Screen Record**
https://drive.google.com/file/d/1uSUq4jwMp0Z56teMYn-nD-_kazflfDzo/view?usp=sharing

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.2.4
 - OS: macOS High Sierra 10.13.6

**Additional context**
These request with examples have been duplicated from a single request.

**Comment by sujayvenaik** [comment] 2018-08-14 06:27
Hey @sumitkumar1209 

I was not able to replicate this issue.
Was there a specific use case where you faced this ?

Do let us know, so we can dig more as to why this happened.

**Comment by sumit0k** [comment] 2018-08-14 06:36
Yes, it is not happening frequently or always reproducible. May be screen record attached in Original post can help.

**Comment by sujayvenaik** [comment] 2018-08-14 07:43
@sumitkumar1209 
Tried that, but could not reproduce accurately.

If you find this is not happening now, you can close this issue and open it any time later you face it again.

**Closed as completed** 2018-08-14 14:45 UTC
Labels: bug
