### ISSUE TITLE
Support for Windows Authentication

### ISSUE THREAD

**Issue by gsteinbacher** [a85/POSTMan-Chrome-Extension#2292] opened 2016-08-24 20:13 UTC
We have our IIS setup to only allow Windows Authentication.  When I execute my Rest API call from a browser the request works just fine.  When I run the same request through Postman I get a 401 - Unauthrorized.  Is there a way to allow Postman to support Windows Authentication?

**Comment by RobbyDeLaet** [comment] 2016-09-15 09:39
+1

**Comment by swisscoder** [comment] 2016-09-27 15:34
+1 
=> as the chrome app will not live forever this becomes more important! Please build it into the Windows App.

**Comment by shamasis** [comment] 2017-02-14 13:55
@gsteinbacher you mean NTLM auth right?

**Comment by giuliocaccin** [comment] 2017-02-21 17:36
Is this a duplicate of #1137 ?

**Comment by chrisknoll** [comment] 2017-06-14 22:14
Looks like we're seeing momentum, does that latest PR mean that we'll be seeing this supported in the near future?

**Comment by AlessandroLazzari1985** [comment] 2017-07-10 16:55
+1

**Comment by muehan** [comment] 2017-09-20 12:52
+1
there is a useful workaround here: https://stackoverflow.com/a/40544245/4383425

**Comment by harryi3t** [comment] 2017-09-27 11:15
We are adding NTLM support in Postman 5.3
Please refer the original issue https://github.com/postmanlabs/postman-app-support/issues/1137 for updates
Marking this as duplicate and closing.

**Closed as completed by harryi3t** 2017-09-27 11:15 UTC
Labels: feature, Auth
