### ISSUE TITLE
Let raw-json support jsonc

### ISSUE THREAD

**Issue by minefujiko9293** [a85/POSTMan-Chrome-Extension#11741] opened 2023-02-20 03:19 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When the request data is raw-json and json contains comments, these comments are automatically filtered before sending the request.

We can add a new option to let users choose whether to filter.

Because sometimes when testing, especially the query interface, some parameters will be frequently enabled and disabled to detect the results.

### Describe the solution you'd like

I hope that when raw-json is like this:
`
{
  "test1":"test1",
  //"test2":"test2"
}
`
By automatically filtering out the content of comments, the backend receives such data:
`
{
  "test1":"test1"
}
`

### Additional context

![image](https://user-images.githubusercontent.com/23348616/220001933-a4cc2045-2de2-422d-ad67-e93f1d60c03b.png)

**Comment by codenirvana** [comment] 2023-02-20 05:21
Duplicate of #3358

Workaround: https://github.com/postmanlabs/postman-app-support/issues/3358#issuecomment-826875807

**Closed as completed by codenirvana** 2023-02-20 05:21 UTC
Labels: feature
