### ISSUE TITLE
Runner screen goes blank - Postman 7.5.0 on Windows 10  

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7169] opened 2019-08-21 22:52 UTC
**Describe the bug**
When running a particular collection with around 19 requests and test-data file with around 500-1000 items, the iterations display goes blank or only a first couple of iterations are visible.

For the user, this occurs pretty much every time for one particular collection. Other collections with fewer requests work fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Invoke Runner for a collection with 19+ requests
2. Use a data file with 500-100 items
3. Start run
4. Once run is complete the request/iterations view goes blank
(Unfortunately, I was unable to reproduce this on a Windows 10 VM)

**Expected behaviour**
User should be able to view the iterations and requests

**Screenshots**
Blank Iterations View
![blank-runner](https://user-images.githubusercontent.com/21366/63473320-23d2d100-c4c9-11e9-9faa-df9e6db10edb.png)

Console Logs
![consolelog](https://user-images.githubusercontent.com/21366/63473203-b626a500-c4c8-11e9-93d5-3b9f05428b42.png)
I could not verify if this Internet-disconnected error was a real thing or a red herring.
Awaiting app logs from the user.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.5.0
 - OS: Windows 10

**Additional context**
Filed on behalf of a user

**Comment by Nmirontsev** [comment] 2019-08-28 20:41
I have the same issue. It is reproducible for any collection that has more then 2 iterations in it. Despite number of requests in collection. 
My last run was with 6-requests collection with 9 iterations. After scrolling to iteration 3 in "Run Results" screen goes blank. It is very annoying and makes using "Runner" useless. I hope issue will be addressed.
App info and OS is the same as for reporter.

**Comment by saswatds** [comment] 2020-02-12 07:37
We have pushed all of our performance fixed to the stable version 7.18.0. The runner should be snappier and not crash. Can you update to the latest version and check if this issue is fixed for you?

**Comment by saswatds** [comment] 2020-03-11 05:18
Closing this issue now as other users have reported that the issue is fixed for them and the runner no longer turns black.

**Closed as completed by saswatds** 2020-03-11 05:18 UTC
Labels: bug, performance, collection-runner, product/runtime
