### ISSUE TITLE
No Sandbox to run live request within document generated by postman

### ISSUE THREAD

**Issue by farzanmasood123** [a85/POSTMan-Chrome-Extension#6392] opened 2019-04-30 10:31 UTC
**Is your feature request related to a problem? Please describe.**
Its been a while now I am using Postman to generate beautiful API documentations. I faced a really bad problem when my team lead asked for a document that can get param values from the reader and they can execute it, just like try it out option in swagger or fields provided in APIDocs. For me Postman is the best tool as I have a good grip on it but even unwanted I have to shift to other API Documentation tools because if the try it out feature lagging in Postman

**Describe the solution you'd like**
"Run in Postman" button is not enough as the reader of API Documentation do not want to leave the page and open postman app just to execute a request he is reading about. Please provide a sandbox in Postman Documentation or a try it out button so the reader can give his desired fields and execute the request

**Describe alternatives you've considered**
Other than providing a sandbox you can also get a button to execute the specific request instead of importing and executing whole of the collection

**Additional context**
Please refer to the image I have attached of the swagger editor. You will have a precise idea
![Screenshot (7)](https://user-images.githubusercontent.com/50138463/56956221-f1d5e180-6b5c-11e9-901e-8bdf1fb89592.png)

**Comment by Raja-Simha** [comment] 2019-07-23 14:35
Duplicate of #3719

**Closed as completed by Raja-Simha** 2019-07-23 14:35 UTC
Labels: feature, product/documentation
