### ISSUE TITLE
Postman crashes when sending request with environment not selected

### ISSUE THREAD

**Issue by zzxcqa** [a85/POSTMan-Chrome-Extension#5825] opened 2019-01-24 19:26 UTC
Postman crashes when clicking on "Send" for a request that has a pre-request script using environment variables, but without any environment selected.

To reproduce:

1. Create a request with pre-request script referring to environment variables.
2. Do not select any environment
3. Click on "Send"
4. Postman crashes

I would expect Postman to show some sort of error message instead of just crashing. I do not recall if this behavior is new or existed in an older version. I just happened to run into it now.

App information:
* Windows 10
* Native App - v6.7.2

**Comment by SamvelRaja** [comment] 2019-01-25 04:00
@zzxcqa  Could send us logs from `%appdata%/Postman/logs/main.log` 
and,
I would like you to open the app using cmd from `%localappdata%/Postman\app-6.7.2\Postman.exe` and send the log in cmd when it is crashing.

This will help us in identifying the issue.

**Comment by zzxcqa** [comment] 2019-01-25 20:05
@SamvelRaja here is the log when launching Postman from cmd:

> 1548446143158 main info ["Booting Postman 6.7.2, win32-10.0.15063 on x64"]
1548446143159 main info ["EventBus\\x7einitialize - Success"]
1548446143164 main info ["UpdateHandler\\x7einit - Success"]
1548446143165 main info ["RuntimeExecutionService\\x7einitialized: Success"]
1548446143165 main info ["ProtocolHandler\\x7einit - Success with status: true]"]
1548446143275 main info ["PluginHost - Booted for 1th time"]
1548446143484 main info ["Bootstrap-models\\x7ebootstrap - Success"]
1548446143971 pluginHost info ["Booting Plugin Host for Postman 6.7.2, win32-10.0.15063 on x64"]
1548446143974 pluginHost info ["PluginsHost - Host: Booted"]
1548446143980 pluginHost info ["PluginInstallationService-_shouldReInstallPlugin",{"installedVersion":"0.0.9","currentVersion":"0.0.9"}]
1548446143980 pluginHost info ["PluginsHost: Synced all plugins",[{"pluginId":"postman.openApi","version":"0.0.9","status":"skipped"}]]
1548446145720 main info ["Main\\x7eAppEvents - Received booted event for process shared"]
1548446147927 main info ["UpdateHandler\\x7eapp-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
1548446147929 main info ["Main\\x7eAppEvents - Received booted event for process requester"]
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:179:11)
    at new Buffer (buffer.js:154:17)
    at Object.createType3Message (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\httpntlm\ntlm.js:172:19)
    at Object.post (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\authorizer\ntlm.js:140:44)
    at Object.module.exports (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\runner\request-helpers-postsend.js:31:21)
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:241:31
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1135:9
    at replenish (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1011:17)
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1016:9
    at _asyncMap (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1133:5)
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1219:16
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1046:16
    at Object.<anonymous> (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:240:20)
    at Object.<anonymous> (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:74:12)
    at Object.applyEachSeries (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:245:23)
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\runner\extensions\http-request.command.js:182:31
    at complete (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\requester\requester.js:109:24)
    at Request._callback (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\requester\requester.js:178:13)
    at Request.self.callback (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-request\request.js:247:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-request\request.js:1230:10)
Main~handleUncaughtError - Uncaught errors TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:179:11)
    at new Buffer (buffer.js:154:17)
    at Object.createType3Message (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\httpntlm\ntlm.js:172:19)
    at Object.post (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\authorizer\ntlm.js:140:44)
    at Object.module.exports (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\runner\request-helpers-postsend.js:31:21)
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:241:31
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1135:9
    at replenish (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1011:17)
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1016:9
    at _asyncMap (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1133:5)
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1219:16
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:1046:16
    at Object.<anonymous> (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:240:20)
    at Object.<anonymous> (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:74:12)
    at Object.applyEachSeries (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\node_modules\async\dist\async.js:245:23)
    at C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\runner\extensions\http-request.command.js:182:31
    at complete (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\requester\requester.js:109:24)
    at Request._callback (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\requester\requester.js:178:13)
    at Request.self.callback (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-request\request.js:247:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-request\request.js:1230:10)
1548446161527 main error ["Main\\x7ehandleUncaughtError - Uncaught errors",{"name":"TypeError","message":"First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.","stack":"TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.\n    at Function.Buffer.from (buffer.js:179:11)\n    at new Buffer (buffer.js:154:17)\n    at Object.createType3Message (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\httpntlm\\ntlm.js:172:19)\n    at Object.post (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\authorizer\\ntlm.js:140:44)\n    at Object.module.exports (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\runner\\request-helpers-postsend.js:31:21)\n    at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:241:31\n    at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1135:9\n    at replenish (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1011:17)\n    at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1016:9\n    at _asyncMap (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1133:5)\n    at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1219:16\n    at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1046:16\n    at Object.<anonymous> (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:240:20)\n    at Object.<anonymous> (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:74:12)\n    at Object.applyEachSeries (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:245:23)\n
  at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\runner\\extensions\\http-request.command.js:182:31\n    at complete (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:109:24)\n    at Request._callback (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:178:13)\n    at Request.self.callback (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-request\\request.js:247:22)\n    at emitTwo (events.js:125:13)\n
    at Request.emit (events.js:213:7)\n    at Request.<anonymous> (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-request\\request.js:1230:10)"}]

And main.log file:

> [17348][1548446552782][main][info]["Booting Postman 6.7.2, win32-10.0.15063 on x64"]
[17348][1548446552786][main][info]["EventBus\\x7einitialize - Success"]
[17348][1548446552791][main][info]["UpdateHandler\\x7einit - Success"]
[17348][1548446552792][main][info]["RuntimeExecutionService\\x7einitialized: Success"]
[17348][1548446552793][main][info]["ProtocolHandler\\x7einit - Success with status: true]"]
[17348][1548446552900][main][info]["PluginHost - Booted for 1th time"]
[17348][1548446553098][main][info]["Bootstrap-models\\x7ebootstrap - Success"]
[17348][1548446555176][main][info]["Main\\x7eAppEvents - Received booted event for process shared"]
[17348][1548446557386][main][info]["Main\\x7eAppEvents - Received booted event for process console"]
[17348][1548446557563][main][info]["UpdateHandler\\x7eapp-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[17348][1548446557565][main][info]["Main\\x7eAppEvents - Received booted event for process requester"]
[17348][1548446569916][main][error]["Main\\x7ehandleUncaughtError - Uncaught errors",{"name":"TypeError","message":"First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.","stack":"TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.\n    at Function.Buffer.from (buffer.js:179:11)\n    at new Buffer (buffer.js:154:17)\n    at Object.createType3Message (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\httpntlm\\ntlm.js:172:19)\n    at Object.post (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\authorizer\\ntlm.js:140:44)\n    at Object.module.exports (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\runner\\request-helpers-postsend.js:31:21)\n    at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:241:31\n    at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1135:9\n    at replenish (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1011:17)\n    at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1016:9\n    at _asyncMap (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1133:5)\n    at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1219:16\n    at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1046:16\n    at Object.<anonymous> (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:240:20)\n    at Object.<anonymous> (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:74:12)\n    at Object.applyEachSeries (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:245:23)\n    at C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\runner\\extensions\\http-request.command.js:182:31\n    at complete (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:109:24)\n    at Request._callback (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:178:13)\n    at Request.self.callback (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-request\\request.js:247:22)\n    at emitTwo (events.js:125:13)\n    at Request.emit (events.js:213:7)\n    at Request.<anonymous> (C:\\Users\\zzxcqa\\AppData\\Local\\Postman\\app-6.7.2\\resources\\app.asar\\node_modules\\postman-request\\request.js:1230:10)"}]

**Comment by zzxcqa** [comment] 2019-01-25 20:09
@SamvelRaja I noticed something else as well when trying to reproduce this issue. "No Environment" should be selected before sending any request after Postman starts. If an environment was selected and a request sent, even though I change to "No Environment", the previously selected Environment seems to be used when sending requests

This possibly belongs as a separate bug report - Postman does not seem to be using the correct environment selected (or maybe just not clearing the environment properly).

**Comment by codenirvana** [comment] 2019-04-05 05:55
@zzxcqa Are you facing this issue while using NTLM auth?
The logs look similar to the one reported in #5768 & #6231

**Comment by shamasis** [comment] 2019-05-14 07:39
@zzxcqa we are suspecting that NTLM auth is an issue because of the following lines in stack trace

```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
at Function.Buffer.from (buffer.js:179:11)
at new Buffer (buffer.js:154:17)
at Object.createType3Message (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\httpntlm\ntlm.js:172:19)
at Object.post (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\authorizer\ntlm.js:140:44)
at Object.module.exports (C:\Users\zzxcqa\AppData\Local\Postman\app-6.7.2\resources\app.asar\node_modules\postman-runtime\lib\runner\request-helpers-postsend.js:31:21)
```

Can you confirm whether you have NTLM auth selected and what happens if you remove that auth?

**Comment by BorntraegerMarc** [comment] 2019-06-12 06:47
For me postman also crashes when a variable IS selected:

```
~/Library/Application Support/Postman/logs$ cat main.log 
[34770][1560321936980][main][info]["Booting Postman 7.1.1, darwin-18.6.0 on x64"]
[34770][1560321936984][main][info]["EventBus~initialize - Success"]
[34770][1560321936986][main][info]["UpdateHandler~init - Success"]
[34770][1560321936987][main][info]["RuntimeExecutionService~initialized: Success"]
[34770][1560321936990][main][info]["ProtocolHandler~init - Success with status: true]"]
[34770][1560321936999][main][info]["PluginHost~bootHost: Booted - 1"]
[34770][1560321937325][main][info]["Bootstrap-models~bootstrap - Success"]
[34770][1560321939726][main][info]["Main~AppEvents - Received booted event for process shared"]
[34770][1560321942289][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[34770][1560321942290][main][info]["Main~AppEvents - Received booted event for process requester"]
[34770][1560321971957][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read property 'toLowerCase' of null","stack":"TypeError: Cannot read property 'toLowerCase' of null\n    at Object.getRequestOptions (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/core.js:304:59)\n    at Requester.request (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:178:31)\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:117:37\n    at Function.create (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:336:16)\n    at RequesterPool.create (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester-pool.js:60:22)\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:105:32\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16\n    at replenish (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)\n    at iterateeCallback (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:995:17)\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:969:16\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1137:13\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/runner/request-helpers-presend.js:315:20\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16\n    at next (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:5329:29)\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:969:16\n    at Function.session.resolveProxy (/Applications/Postman.app/Contents/Resources/app/utils/getSystemProxy.js:32:16)"}]
```

**Comment by BorntraegerMarc** [comment] 2019-06-12 06:57
Also possible duplicate of https://github.com/postmanlabs/postman-app-support/issues/6533

**Comment by codenirvana** [comment] 2019-06-13 07:12
Closing as duplicate of #5768

**Closed as completed by codenirvana** 2019-06-13 07:12 UTC
Labels: bug, Auth, request-sending, product/runtime
