### ISSUE TITLE
runner with json object not working

### ISSUE THREAD

**Issue by Opticsponge** [a85/POSTMan-Chrome-Extension#2882] opened 2017-04-03 01:46 UTC
1. Postman Version:  4.10.5 
 2. App (Chrome app or Mac app): mac
 3. OS details:
 4. Is the Interceptor on and enabled in the app:no
 5. Did you encounter this recently, or has this bug always been there: not sure
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

set up collection post entry with 
header with Content-Type:application/json
body as raw json ( application/json)

file.json
[
{"parent1":  { "child" { "name": "value" }}},
{"parent2":  { "child" { "name": "value" }}}
]

set up runner to try and get data to pull and send and it won't work no matter what combo I try

if I set a console.log(data) in pre-req it dumps data

Trying hack to get pre-req to didn't work
postman.setEnvironmentVariable("req", JSON.stringify(data));

In console I see
Request Body:
mode:"raw"
raw:"[object Object]"

**Comment by kamalaknn** [comment] 2017-04-03 07:39
Hi @Opticsponge,

We are trying to reproduce this issue.

> set up runner to try and get data to pull and send and it won't work 

Could you explain what you are seeing or you can open Dev Tools (View -> Show Dev Tools) in the runner and take a screenshot after running the collection?

Also I could see that the example JSON you gave is broken. Might be unrelated to the issue, but here is the updated one: 

```json
[
{"parent1": { "child": { "name": "value" }}},
{"parent2": { "child": { "name": "value" }}}
]
``` 

If you could create a sample collection where you see this and share it (Click "Export" in the drop down menu next to the collection) it will be super helpful for us to reproduce. You could mask sensitive data in it though.

Thanks

**Comment by Opticsponge** [comment] 2017-04-03 15:15
whoops my stub json skills seem to be lacking, good news is somehow retrying hack in pre-req worked this morning. 

postman.setEnvironmentVariable("request", JSON.stringify(data));

not putting in stringify in pre-req and attempting to send object data we get
Request Body:
mode:"raw"
raw:"[object Object]"


If this is the proper way to do it documentation would be great for others behind me

**Comment by kamalaknn** [comment] 2017-04-04 07:51
Could you explain a bit on what you are trying to achieve, expected behaviour and actual behaviour and steps to reproduce?

It will help us in isolating any issues.

**Comment by jgroom33** [comment] 2017-04-13 23:01
This seems to have the same issue:
https://www.getpostman.com/collections/937511b736db36d34c78

The behavior appears to exist when the imported array contains a child object that is meant to be the body.

import.json:

```
[{
    "foobar":"not intended for posting",
    "body": {
      "bool": true,
      "properties": {
        "foo": "bar"
      }
    }
  }
]
```

**Comment by coditva** [comment] 2019-08-16 08:19
The problem here seems to be that the request body is not in the correct JSON form but is a Javascript object. There are two solutions to this problem:

1. Use pre-request script to `JSON.stringify` the request data as @Opticsponge does or,
2. Use `JSON.stringify`-ed value in the data file:
```javascript
[
  {
    "body": "{ \"parent1\": { \"child\": \"value\" } }"
  },
  {
    "body": "{ \"parent2\": { \"child\": \"value\" } }"
  }
]
```
and set the variable as:
```javascript
pm.environment.set('request', data.body);
```

<hr>

The problem in @jgroom33's collection seems to be that the `JSON.stringify`-ed environment variable `body` is overridden by the data variable `body` which contains non-stringified data. This can be resolved by changing the environment variable name and using that in the request body.

Ref: https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#variable-scopes

**Closed as completed** 2019-08-16 08:39 UTC
Labels: support, collection-runner, product/runtime
