### ISSUE TITLE
Duplicate "My Workspace" - Can't create requests, folders and collections - user not in workspace error

### ISSUE THREAD

**Issue by adrian-kurzeja** [a85/POSTMan-Chrome-Extension#4862] opened 2018-07-20 11:54 UTC
I wanted check how mock server works... now i can't do nothing (cant save/create)... I don't want to loose my collection.

Everything was working untill:
-I tried to mock server... 
-it requested me to login so 
-I logged with my google account
-choosed to make mock server private
-clicked next
-it started to load I canceled it
-Now I can' save and create tabs.... 
-It seems that the problem is with google account, saw one month ago almost the same bug

please repair ;/

**Comment by numaanashraf** [comment] 2018-07-20 15:36
@adrian-kurzeja, Could you open the DevTools (View > Developer > Show DevTools (Current View)) & (View > Developer > Show DevTools (Shared)), try saving or creating tabs and let us know if you see any errors there?

**Comment by Postman-Gabriel** [comment] 2018-07-20 21:31
My user on Windows 10 x64 is experiencing the same issue. He can't save any requests.

**Comment by adrian-kurzeja** [comment] 2018-07-21 17:31
@numaanashraf Yes i can change tabs here.... but now I have another problem.... i cant change enviromental variables, cant change enviroments, cant create enviroments.

I can't do nothing! I had to change REST API client.... i can't work on Postman.... just after login everything "freezed" in way, i can't add/edit/delete requests. Can't add/edit/delete collections. Can't  add/edit/delete enviroments and variables.

I am scared to logout becouse it says my all request will be deleted and saved on account... but... it seems it won't be saved... 

You should do something like if i had some collections before logout... when i logout the collections i had stays on computer... now i can lose everything i created, just becouse i was curious of features... that don't work...

Please repair so maybe i'll back to postman, but now there is no way to work on it. I cant even change url from staging to developement. ;/

**Comment by adrian-kurzeja** [comment] 2018-07-21 17:31
@numaanashraf Btw. It is on Xubuntu 17.04

**Comment by Postman-Gabriel** [comment] 2018-07-23 20:33
![](https://postman.zendesk.com/attachments/token/92SVzJkJ4IjSi2VMHyajjKfpq/?name=Screen+Shot+2018-07-22+at+11.56.47.png)

![](https://postman.zendesk.com/attachments/token/h5AqbmGY3W968i2z9n9NmQ2gg/?name=Screen+Shot+2018-07-22+at+12.02.26.png)

additional screenshots about the bug

**Comment by prashantagarwal** [comment] 2018-07-24 03:41
@gabriel-bronfman-postman If its possible can you try this out on our canary apps and see if it is working there ? You can download it from https://www.getpostman.com/canary

**Comment by Postman-Gabriel** [comment] 2018-07-25 18:30
Hi @prashantagarwal, we figured out a "workaround", if you remove the  ~/.config/Postman/ file and restart, it apparently launches without error.

**Comment by Darko-git** [comment] 2018-09-25 21:50
Hi, I had a similar issue on Win 10 (cannot save anything), I could not find any configuration files but I was getting permission errors in console.

Turns out I had 2 (two) workspaces under "My Workspace", both named... "My Workspace". I imagine one is local and the other one is shared?
In any case, when I switched to the other workspace, I was able to save a request.

![image](https://user-images.githubusercontent.com/5216705/46045307-2cacfe00-c0d2-11e8-8b29-73bd7012dfbf.png)

I don't know where this other workspace came from, but I do use Postman on two different machines.

**Comment by nayyaung** [comment] 2018-09-28 08:32
> 
> 
> Hi, I had a similar issue on Win 10 (cannot save anything), I could not find any configuration files but I was getting permission errors in console.
> 
> Turns out I had 2 (two) workspaces under "My Workspace", both named... "My Workspace". I imagine one is local and the other one is shared?
> In any case, when I switched to the other workspace, I was able to save a request.
> 
> ![image](https://user-images.githubusercontent.com/5216705/46045307-2cacfe00-c0d2-11e8-8b29-73bd7012dfbf.png)
> 
> I don't know where this other workspace came from, but I do use Postman on two different machines.

Thanks. It solved the same issue for me.

**Comment by neekfenwick** [comment] 2018-10-16 03:05
Hopefully the same behaviour here, wanted to add my experience.  I'm on Fedora 28 and have exactly the same duplicate "My Workspace" as @Darko-git screenshotted earlier, and the same 'cannot save or make env changes' as described above on my primary My Workspace.  I used Postman heavily a couple of years ago and can see my 20+ collections in the primary read-only My Workspace.  Switching to the second My Workspace gives me an empty collection I can edit.  However after creating a collection and a couple of requests, the new requests have "CONFLICT" in their tab header with a tooltip saying "This request has been modified since you last opened this tab" which is very weird.

I think I must have been logged onto Postman as a different user previously.  If I click the '...' next to My Workspace and click View Details, I get this exception in the dev tools Console for the current view:

Uncaught (in promise) Error: You are not permitted to perform the action.
    at SyncRemoteFetcherService._dispatchCallback (vendor-shared.js:90859)
    at EventEmitter.emit (vendor-shared.js:46902)
    at _dispatch (vendor-shared.js:106631)
    at EventEmitter.<anonymous> (vendor-shared.js:106641)
    at emitTwo (events.js:125)
    at EventEmitter.emit (events.js:213)

I can click View Details on the second workspace just fine (which I have renamed to "New Workspace" to avoid confusion).

If I go into Application->IndexedDB in the dev tools, I can see postman/collections and see lots of saved collections, but they are all for the old "My Workspace" which is locked.  They show an "owner" of "108005" but I don't know what this relates to.  Under postman-app/users there is a single key "currentUser" with id "5456861" so I imagine the read-only behaviour of the My Workspace collections is because the userid doesn't match the id of the current user.

Is there an official way of bringing My Workspace under the control of my new 'currentUser'?  Should I just start editing the IndexedDB content to update the userid to 5456861?

On a side note, I thought the problem may be having several versions of Postman installed, this info might help people with multiple installs.  I've manually downloaded a tarball release in /opt/postman, and also have a desktop shortcut offered by Gnome3 called Postman.  If I run postman through the desktop shortcut I get Settings->About "Postman for Chrome 5.5.3" and if I run /opt/postman/Postman I get "Postman for Linux 6.4.2".   Both show the same set of Collections and duplicate Workspace.

Since I'm on Fedora with Gnome 3 I checked ~/.local/share/applications and grepped for postman, found chrome-fhbjgbiflinjbdggehcddcbncdddomop-Default.desktop which shows the launch command:

Exec=/usr/lib64/chromium-browser/chromium-browser.sh --user-data-dir=/home/neek/.chromium-profiles/sender --profile-directory=Default --app-id=fhbjgbiflinjbdggehcddcbncdddomop

So it's in a long-disused profile of mine called 'sender', I can run the command line without the --app-id and see Postman as an Extension installed in that browser profile.  Removing it also removed the .desktop launcher.  However this has not cleared up the permissions problem at all, all the same duplicate workspace and user shennanigans are still going on.

**Comment by BeatriceThalo** [comment] 2018-10-19 14:57
Yeah similar. I had 14 unsaved requests open, not signed into Postman Ubuntu 16. I'm moving machines to Ubuntu 18, so made a free (not google) account on the new machine. Then on the old machine with my request tabs open I signed in, and tried to save my requests but the save request dialog's save button remained grayed out and any attempts to create a collection did not create any collection objects. The Current View dev console has the error

> vendor-shared.js:119656 Error in pipeline for creating collection or the session Error: permissionsHandler: User '2740527' is not part of workspace '29ba1c6f-43ab-4e23-8a6c-27c39a57a069'
>     at __WEBPACK_IMPORTED_MODULE_0__modules_controllers_WorkspaceController__.a.get.then.workspace (vendor-shared.js:259925)

Indeed, I have two workspaces named "My Workspace", one with my requests and an empty one which allows creating collections no problem. My question is that the suggested workaround file to remove is a directory, should the whole thing be removed?

**Comment by awalakaushik** [comment] 2018-11-15 21:35
Hi, In my case, I have a folder inside of a collection. I don't have any requests in it. When I try to delete it, postman says, "**Unable to delete this folder**". Can somebody help?

**Comment by DrYSG** [comment] 2019-04-30 19:24
I am having the same issue with win10. When I try to save a request to a collection:

```
vendor-shared.js:553414 PermissionHandler:  Object {request: Object, context: Object, err: Error: EntityPermissionHandler: User does not have permission to perform this action
    at __WEBPAC…}context: Objecterr: Error: EntityPermissionHandler: User does not have permission to perform this action
    at __WEBPACK_IMPORTED_MODULE_2__services_AccessControl_AccessControlService__.a.can.then.isAllowed (file:///C:/Users/ysg4206/AppData/Local/Postman/app-7.0.9/resources/app.asar/js/vendor-shared.js:369683:33)
    at <anonymous>message: "EntityPermissionHandler: User does not have permission to perform this action"stack: "Error: EntityPermissionHandler: User does not have permission to perform this action↵    at __WEBPACK_IMPORTED_MODULE_2__services_AccessControl_AccessControlService__.a.can.then.isAllowed (file:///C:/Users/ysg4206/AppData/Local/Postman/app-7.0.9/resources/app.asar/js/vendor-shared.js:369683:33)↵    at <anonymous>"__proto__: Objectrequest: Objectdata: Objectrequest: Objecttarget: Object__proto__: Objectevents: Array(0)meta: Objectname: "create_deep"namespace: "request"__proto__: Object__proto__: Object
```

**Comment by DrYSG** [comment] 2019-04-30 19:25
I tried running Postman as admin and it has the same error.

**Comment by sankalp0o** [comment] 2019-08-20 09:28
Looks like this issue is also happening because of the extra "My Workspace" created when signing up for the first time because the process is interrupted for some reason. @kamalaknn what's the recommendation in this case?

**Comment by kamalaknn** [comment] 2019-08-21 04:52
@sankalp0o The quickest way to unblock affected users is to sign out and sign in again.

We did push a few improvements to the sign-in flows that communicate to the user that some action is being run in the background to prevent user interruptions. 

External unexpected interruptions are the ones that can lead to these issues now.

**Comment by mccannt** [comment] 2020-05-28 12:16
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.

**Closed as completed by mccannt** 2020-05-28 12:16 UTC
Labels: bug, postman-data
