### ISSUE TITLE
Display more authentication information in generated documentation

### ISSUE THREAD

**Issue by cascer1** [a85/POSTMan-Chrome-Extension#3766] opened 2017-11-09 18:18 UTC
## App Details:
```
Postman for Windows
Version 5.3.2
win32 10.0.16299 / x64
```

## Issue Report:
This is not a bug.

Currently, when I create a request with authentication information (such as a bearer token) in Postman, the documentation simply displays a little padlock icon next to the request. However, this does not inform the visitor what kind of authentication is requested. 

Instead, I would like to see additional authentication information, such as the expected headers, or where to obtain a key.

**Comment by sdnts** [comment] 2017-11-14 15:19
@cascer1 Thanks for the feature request! I can definitely understand the use case behind this.
We will look into this :)

**Comment by Raja-Simha** [comment] 2019-07-23 13:56
Duplicate of #4244

**Closed as completed by Raja-Simha** 2019-07-23 13:56 UTC
Labels: feature, product/documentation, Auth
