### ISSUE TITLE
Feature Request: Description for Environment Variables

### ISSUE THREAD

**Issue by sumit0k** [a85/POSTMan-Chrome-Extension#4949] opened 2018-08-02 06:31 UTC
**Is your feature request related to a problem? Please describe.**
I wanted to have a clear detailed description of what each environment holds and what each environment variable does, much like how there is description available for collections and request parameters or request form values

**Describe the solution you'd like**
Another column while listing environment variable, to be able to describe what is the role of that variable. 
Description tab for Environment as a whole similar to Collections

**Describe alternatives you've considered**
None, has to rely on guessing from environment name and variables name and then running and seeing the updated value

**Additional context**
None

**Comment by sivcan** [comment] 2018-08-02 10:25
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4030

**Closed as completed by sivcan** 2018-08-02 10:25 UTC
