### ISSUE TITLE
How to make postman communicate with web-socket

### ISSUE THREAD

**Issue by MostafaSenousy** [a85/POSTMan-Chrome-Extension#5285] opened 2018-10-01 13:12 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment] 2018-10-03 09:34
Duplicate of #4009

**Closed as completed by numaanashraf** 2018-10-03 09:34 UTC

**Comment by shamasis** [comment] 2021-05-20 14:09
Postman v8.5.0 onwards supports WebSockets for connecting and viewing messages. https://github.com/postmanlabs/postman-app-support/issues/4009#issuecomment-845136513
