### ISSUE TITLE
GET and POST request to localhost produce error

### ISSUE THREAD

**Issue by eap0120** [a85/POSTMan-Chrome-Extension#3441] opened 2017-08-24 14:35 UTC
## App Details:

```
Postman for Windows
Version 5.1.3
win32 10.0.10240 / x64```

1) issue Postman GET request to http://localhost:8080/getScan/808296.  This issue just started showing up recently.  Previous versions of Postman did not have this problem.
2) expect that web service will response back with valid JSON response
3) Get an error back that stats as follows:

Could not get any response
There was an error connecting to http://localhost:8080/getScan/808296.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Client certificates are required for this server:
Fix this by adding client certificates in Settings > Certificates
Request timeout:
Change request timeout in Settings > General

4) Console logs show the following:

Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:c:\jenkins\workspace\electron-win-x64\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:
Request Headers:
cache-control:"no-cache"
Postman-Token:"4582c4b0-dc93-4941-aa3e-81c49e2ebb4f"
Content-Type:"application/json"


## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)


<!--
Some guidelines: 

1. Please file Newman-related issues at https://github.com/postmanlabs/newman/issues

2. If it’s a Cloud-related issue, or you want to include personal information like your username / collection names, mail us at help@getpostman.com

3. If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://getpostman.com/docs.
-->

**Comment by sdnts** [comment] 2017-08-25 05:05
@eap0120 This error usually happens when you try to access your server on the wrong port. Are you trying to access an HTTPS server over HTTP?
I wasn't able tor reproduce. I'm closing this because this looks like a problem with server setup rather than Postman itself. Please reopen if you feel otherwise.

**Comment by eap0120** [comment] 2017-08-25 13:08
I'm running over http and this is still an issue

**Comment by sdnts** [comment] 2017-08-28 08:36
@eap0120 Is your local server running over HTTPS? If so, you'll need to access it over HTTPS. I think it is, since your errors show SSL errors

**Comment by eap0120** [comment] 2017-08-28 13:52
Unfortunately that is not the case.  I'm running under http as evidenced by the following server log debug statement:

2017-08-25 10:39:12.312  INFO 30896 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2017-08-25 10:39:12.321  INFO 30896 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2017-08-25 10:39:12.321  INFO 30896 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.16
2017-08-25 10:39:12.608  INFO 30896 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext

**Comment by eap0120** [comment] 2017-08-28 15:05
Also, I can run the following curl command generated by Postman and get a JSON response back

curl -X GET \
>   http://localhost:8080/scan/304083338296 \
>   -H 'cache-control: no-cache' \
>   -H 'content-type: application/json' \
>   -H 'postman-token: 2e5f9e71-4190-76a4-d10f-27f5c2f94098'

**Comment by klr8** [comment] 2018-04-06 09:10
Also had this problem with Postman v6.0.10 on Windows 7.
As suggested, setting no_proxy resolved the problem.

**Comment by jbourdonLFNY** [comment] 2018-04-06 20:15
@eap0120 I have the same issue, using HTTPS on port 8443 (Tomcat) and curl is indeed working fine for me as well.

**Comment by numaanashraf** [comment] 2018-07-18 09:25
@eap0120 Are you still facing this issue?

**Comment by numaanashraf** [comment] 2018-12-07 07:47
Closing this due to inactivity

**Closed as completed by numaanashraf** 2018-12-07 07:47 UTC
Labels: bug

**Comment by VonTalavang** [comment] 2019-02-03 08:08
I cant request using post
