### ISSUE TITLE
In postman ,Facing tunneling issue after adding the custom proxy configuration

### ISSUE THREAD

**Issue by Venkat43210** [a85/POSTMan-Chrome-Extension#9132] opened 2020-10-06 07:11 UTC
Facing the issue "could not send request " and "Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8888"

Steps to recreate
1. In postman settings,adding the custom proxy configuration with localhost and portnumber
2.Clicking on send button after providing the valid GET HTTPS Request.
3.I am intercepting the postman local host proxy withe Jmeter Https recording purpose

Actual result: 
Facing the issue  "could not send request " and  "Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8888""

Expected result:Response should be success with 200 code.

![image](https://user-images.githubusercontent.com/71552626/95169190-1ca37b00-07d0-11eb-94bd-5d40544bf0cd.png)
![image](https://user-images.githubusercontent.com/71552626/95169230-2f1db480-07d0-11eb-95c4-6526a74124b2.png)

**Comment by codenirvana** [comment] 2020-10-22 17:46
@Venkat43210 This issue will be fixed in the next app release.

Closing as duplicate of #8783

**Closed as completed by codenirvana** 2020-10-22 17:46 UTC
Labels: Proxy, product/runtime
