### ISSUE TITLE
Unable to view Response body and other 

### ISSUE THREAD

**Issue by dbkaynor** [a85/POSTMan-Chrome-Extension#4317] opened 2018-03-09 21:10 UTC
This used to work but now when I click on a failing test and Response Body in runner I get a message as follows: "Data unavailable (Only data from about the top 10 historical runs is stored)
All of the item in runner show the same results. 

![dataunavailable](https://user-images.githubusercontent.com/1424275/37229957-ae0d8a8a-239a-11e8-82e5-5a7ecb2ea619.JPG)

**Comment by sivcan** [comment] 2018-03-10 04:33
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4296

**Closed as completed by sivcan** 2018-03-10 04:33 UTC
