### ISSUE TITLE
Favicon support for postman API documentation feature

### ISSUE THREAD

**Issue by ewilde** [a85/POSTMan-Chrome-Extension#3014] opened 2017-05-11 12:21 UTC
On the [team edit page](https://app.getpostman.com/dashboard/teams/edit) where you can customize the domain, team logo and name.

Allow customers to specify a 'favicon' for the documentation api site

**Comment by shamasis** [comment] 2017-05-11 14:55
Marking this as a feature request.

**Comment by a85** [comment] 2017-12-25 00:47
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2719. Will be out in public docs soon!

**Closed as completed by a85** 2017-12-25 00:47 UTC
Labels: feature

**Comment by mjaverto** [comment] 2018-04-12 12:54
@a85 is this live? I also have a pro account and am not seeing where I can upload this?
