### ISSUE TITLE
Run Example Request in Postman

### ISSUE THREAD

**Issue by science695** [a85/POSTMan-Chrome-Extension#5481] opened 2018-11-05 18:31 UTC
I have been saving examples for a request in postman, and I ran into a situation where I wanted to update and re-run the example api request.

Could you add the ability to run/re-run a saved example request?

I'm using:
Postman for Linux
Version 6.2.4

But I'm pretty sure this isn't a bug, but a feature would be a big help.

Thanks!

**Comment by numaanashraf** [comment] 2018-11-13 23:48
Duplicate of #3694

**Closed as completed by numaanashraf** 2018-11-13 23:48 UTC
Labels: feature, examples
