### ISSUE TITLE
Tests - require/import external module of sandBox and define mechanisme to implement a global functionnal test for collection and use/call this function in a specific test api for example.

### ISSUE THREAD

**Issue by aabou** [a85/POSTMan-Chrome-Extension#7721] opened 2019-11-29 13:14 UTC

**Comment by saswatds** [comment] 2019-12-03 16:23
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1180

**Closed as completed by saswatds** 2019-12-03 16:23 UTC
