### ISSUE TITLE
NTLM auth fails with unified "WWW-Authenticate" header from ASP.NET

### ISSUE THREAD

**Issue by johnradke** [a85/POSTMan-Chrome-Extension#4711] opened 2018-06-15 15:25 UTC
**Describe the bug**
*NOTE: This might be related to issue #4355 since it involves `WWW-Authenticate` header(s)*

Postman fails to start the NTLM negotiation process when the server returns a 401 with auth headers in a **unified** format as follows:
```
WWW-Authenticate: NTLM,Basic realm=""
```
But it works fine when they are **separated**:
```
WWW-Authenticate: NTLM
WWW-Authenticate: Basic realm=""
```

**To Reproduce**
In my ASP.NET WebAPI (version 5.2.3.0) app startup code, I set the auth schemes as follows:
```csharp
var listener = (HttpListener)appBuilder.Properties["System.Net.HttpListener"];
listener.AuthenticationSchemes = AuthenticationSchemes.Anonymous | AuthenticationSchemes.Ntlm | AuthenticationSchemes.Basic;
```
(In my use case, some endpoints can be called anonymously, but others require NTLM or Basic auth.)

When I then use Postman (with Authorization set to NTLM Authentication) to call an endpoint which requires auth, the server responds with the single, unified `WWW-Authenticate` header (see first example above), and Postman fails to issue the subsequent NTLM requests.

However, if I remove the `AuthenticationSchemes.Anonymous` flag from the list of auth schemes and call the same endpoint, the server responds with the two separate `WWW-Authenticate` headers (see second example above), and Postman authenticates just fine.

Removing the `AuthenticationSchemes.Basic` flag also works, since in that case it responds with a single `WWW-Authenticate: NTLM` header whether or not Anonymous is allowed.

**Expected behavior**
Postman parses a single `WWW-Authenticate` header which specifies multiple comma-separated schemes.

**Screenshots**
N/A

**App information (please complete the following information):**
Postman for Windows
Version 6.1.3
win32 6.1.7601 / x64

**Additional context**
I'm not sure why ASP.NET builds headers differently depending on whether Anonymous is allowed or not. When Anonymous is allowed, it is executing my custom `System.Web.Http.AuthorizeAttribute` implementation (which is applied to that specific controller) which then returns false from my overridden `IsAuthorized(HttpActionContext actionContext)`, which then obviously results in a 401 result with the **unified** headers. When Anonymous is NOT allowed at the server level, then it doesn't even get that far-- since the request has no `Authorization` header it can logically be summarily rejected, which somehow results in a 401 result with the **separated** headers.

**Workaround**
Current workaround is to run Fiddler with **Rules** > **Automatically Authenticate** enabled

**Comment by harryi3t** [comment] 2018-07-02 07:41
> NOTE: This might be related to issue #4355 since it involves WWW-Authenticate header(s)

@johnradke Yes, this is actually a duplicate of https://github.com/postmanlabs/postman-app-support/issues/4355 
Please subscribe to the original issue for any updates.

**Comment by dco123** [comment] 2021-08-10 07:54
I'm getting this issue using 8.10.0. I don't think it was ever a duplicate of #4355 as that was explicitly about nonunified WWW-Authenticate headers. Can you please reopen this and investigate it?

If an api responds with this:

HTTP/1.1 401 Unauthorized
Content-Length: 0
Server: Microsoft-HTTPAPI/2.0
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
Date: Tue, 10 Aug 2021 07:38:46 GMT
Proxy-Support: Session-Based-Authentication

Postman responds to this 401 by retrying the request and providing NTLM credentials.

If the api responds with this:

HTTP/1.1 401 Unauthorized
Content-Length: 42
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
WWW-Authenticate: Negotiate,NTLM
Date: Mon, 09 Aug 2021 09:52:18 GMT
Proxy-Support: Session-Based-Authentication

Postman does not attempt to use NTLM authentication, and the request will fail.

**Comment by codenirvana** [comment] 2021-08-20 08:48
@dco123 we've pushed a fix for this in `v8.11.0`. Can you update your app and confirm if this fixes your issue?

**Comment by timbochamp** [comment] 2021-08-23 01:02
We had to pause the v8.11 release, but should have it ready soon. This should be addressed on Postman for Web in the meantime!

**Comment by dco123** [comment] 2021-08-25 14:05
@codenirvana @timbochamp confirmed it's fixed in 8,11. Thanks!

**Closed as completed** 2021-08-25 16:37 UTC
Labels: bug, Auth, product/runtime
