### ISSUE TITLE
Windows Application - Menu not showing labels.

### ISSUE THREAD

**Issue by luislaurentino1969** [a85/POSTMan-Chrome-Extension#12755] opened 2024-04-01 11:35 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The main menu does not show the options label.

### Steps To Reproduce

1. Open the hamburger menu.
 

### Screenshots or Videos

![Postman Main menu](https://github.com/postmanlabs/postman-app-support/assets/47584093/30bf92f2-c4bc-4b3f-996b-2cc22d6db9c9)

### Operating System

Windows

### Postman Version

10.24

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by dsanders11** [comment] 2024-06-12 00:38
Duplicate of #12620

**Closed as not planned by dsanders11** 2024-06-12 00:38 UTC
