### ISSUE TITLE
Feature Request: Allow the "Snippits" panel within the Test tab to be hidden

### ISSUE THREAD

**Issue by jeronimusus** [a85/POSTMan-Chrome-Extension#2592] opened 2016-12-25 13:49 UTC
Make it possible to hide the **Snippits** panel within the **Test** tab.

The **Snippits** is very handy but it does take up valuable real estate when I am just using my laptop. thanks!

**Comment by kunagpal** [comment] 2016-12-29 08:18
Duplicate of #2176

**Closed as completed** 2017-01-06 06:17 UTC
