### ISSUE TITLE
Postman stops sending requests when sending a token.

### ISSUE THREAD

**Issue by apokall** [a85/POSTMan-Chrome-Extension#6993] opened 2019-07-25 08:09 UTC
**Describe the bug**
One day, with time, the postman stopped sending requests normally, but only those that require verification for authorization. When I send Bearer Token with the request, the request does not get to the server at all. It only costs me to disable the transfer of the token, then immediately begins to get a request to the server.
I use the common repository of rekvestov. My team has the same requests, but I don’t. Both on production and on my local.

**To Reproduce**
1. Go to my requests
2. Click on send
3. Scroll down

**Expected behavior**
Waited for a response from the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/12546313/61857062-14616780-aecc-11e9-8191-c32b1f11de12.png)

![image](https://user-images.githubusercontent.com/12546313/61857146-3955da80-aecc-11e9-9061-d4ca4ba6c93c.png)

**App information (please complete the following information):**
 - Postman Version:
Postman for Linux
Version 7.0.7
linux 4.15.0-54-generic / x64
 - OS: Ubuntu 16.04

**Other information**
After the appearance of this problem, I reinstalled the postman - but the effect was not bad.

**Comment by preethammavin** [comment] 2019-08-04 15:16
@apokall can check if the behaviour persists with our latest version, 7.3.5. as I am unable to reproduce this on my end.

**Comment by techpeace** [comment] 2019-09-26 06:54
I'm able to reproduce on 7.8.0:

![Screen Recording 2019-09-26 at 01 52 AM](https://user-images.githubusercontent.com/2220/65665181-8c4d2a80-e000-11e9-8a81-1a9af76cfbfc.gif)

**Comment by vikiCoder** [comment] 2020-03-13 06:11
@techpeace, @apokall  Can you please show the error from Postman console when the request fails? I suspect the token might contain some invalid characters (like newline) which are not allowed to be sent as request header and causing the request to fail.

**Comment by mccannt** [comment] 2020-08-27 14:28
@techpeace @apokall Can you confirm this is still an issue for you in the most recent version of the app? 
If so can you provide the requested information as outlined above?

**Comment by mccannt** [comment] 2020-09-04 17:16
Closing this issue out. If it is still a problem, please let us know.

**Closed as completed by mccannt** 2020-09-04 17:16 UTC
Labels: bug, product/runtime
