### ISSUE TITLE
Error importing Kubernetes OpenAPI document

### ISSUE THREAD

**Issue by BryanHunt** [a85/POSTMan-Chrome-Extension#9926] opened 2021-05-11 15:10 UTC
**Describe the Issue**
Importing the OpenAPI document from our kubernetes cluster failed with: There was an unexpected error.  Please try again.

**Steps to Reproduce**
1. Download the OpenAPI document from a Kubernetes cluster.
2. Import the file

**Environment Information**

 - Platform Type: Mac
 - Postman Version: 8.3.0
 - Operating System: Mac OS 11.3

**Additional Context**
After restarting Postman, I do see the Kubernetes API.

**Comment by abhijitkane** [comment] 2021-05-14 09:34
@BryanHunt Can you post the file here, or email it to help@postman.com quoting this issue? The issue might be due to the file size, or certain OpenAPI constructs that we might not fully support yet.

**Comment by dhwaneetbhatt** [comment] 2023-01-30 05:50
@BryanHunt I tried importing a Kubernetes OpenAPI v2 file, and it works fine on the latest version. Could you please post the file here or email it to [help@postman.com](mailto:help@postman.com) quoting this issue?

**Environment Information**
- Platform Type: Mac
- Postman Version: 10.8.5
- Operating System: Mac OS Monterey 12.6

**Comment by dhwaneetbhatt** [comment] 2023-02-13 08:28
Hello @BryanHunt, I am closing this issue as we cannot reproduce this in the latest version of Postman. Feel free to reopen if the issue persists by attaching or emailing screenshots and OAS files.

**Closed as not planned by dhwaneetbhatt** 2023-02-13 08:28 UTC
Labels: bug, OpenAPI, product/api-design
