### ISSUE TITLE
As a postman flow user, I want to add a global variable

### ISSUE THREAD

**Issue by wangfeifan945** [a85/POSTMan-Chrome-Extension#11971] opened 2023-04-30 04:58 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Now flow contain create and get variable.
But this variable is trigger by run. So for 2 level or more levels for, will not work.

For example with below case.

Step1 - get list contain 2 objects
Step2 - based on Step1, we run the request and get 3 objects.
Step3 - Create a template with some data that comes from the step1 list, and some that come from step2 list.

**Expected Result -**  All 2 *3 = 6 data be print
**Actual Result - ** only 2 data be print and flow is not able to end.

Based on my research, the "Template" blocks also trigger when 2 inputs are got updated.
So, result for this is - template is have to wait for first level for get update and not able to print all 2*3 = 6 records

Solution - For flows we need a global variable or temporary variables. the one support we get variable real time value.
And 

### Describe the solution you'd like

Now flow contain create and get variable.
But this variable is trigger by run. So for 2 level or more levels for, will not work.

For example with below case.

Step1 - get list contain 2 objects
Step2 - based on Step1, we run the request and get 3 objects.

Step3 - Create a template with some data that comes from the step1 list, and some that come from step2 list.

**Expected Result -**  All 2 *3 = 6 data be print
**Actual Result -** only 2 data be print and flow is not able to end.

Based on my research, the "Template" blocks also trigger when 2 inputs are got updated.
So, result for this is - template is not able to print all 2*3 = 6 records

Solution - For flows we need a global variable or temporary variables. the one support we get variable real time value.
And 

### Describe alternatives you've considered

Solution - For flows we need a global variable or temporary variables. the one support we get variable real time value.
And

**Comment by rabbah** [comment] 2023-11-02 16:09
👋 hi @wangfeifan945 can you share a flow that explains this problem you're describing? From what I can understand you should be able to do this but I might be missing something from your description. If you have a flow you can share that would be great.

**Comment by rabbah** [comment] 2024-04-20 02:34
Duplicate of #12109.

**Closed as completed by rabbah** 2024-04-20 02:34 UTC
Labels: feature, Flows
