### ISSUE TITLE
Authorize Button is disabled on Authorize OAUTH 2.0 Github Application

### ISSUE THREAD

**Issue by krpraveen01** [a85/POSTMan-Chrome-Extension#7698] opened 2019-11-26 02:27 UTC
Hi,

I got 7.12 version and I tried to request token on OAUTH 2.0 Authorization. I have entered all the required information of github OAUTH 2.0 urls and params and then clicked on Request Token button. The new window of Authorize Application is opened with warning :

Please note that GitHub no longer supports your web browser.
We recommend upgrading to the latest Google Chrome or Firefox.

and the Authorize button is disabled.

Can you help me to fix this issue.

Steps to reproduce:

Create a request
select Authorization tab -> OAuth 2.0
click on Get New Access Token
Fill the required params on the form
click on Request TOken

Issue: The Authorize button is disabled

Thanks,
Raj

**Comment by kamalaknn** [comment] 2019-12-27 11:53
Hey @krpraveen01 

This looks like a duplicate of #7700. I'm closing this as a duplicate. Please subscribe to the original issue for updates.

**Closed as completed by kamalaknn** 2019-12-27 11:53 UTC
Labels: bug, OAuth2
