### ISSUE TITLE
Collection Runner Crashing because of memory 

### ISSUE THREAD

**Issue by Anapier22** [a85/POSTMan-Chrome-Extension#10453] opened 2021-11-19 16:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I have 2 requests in my collection. One is to get an array of URLs for headshot images of athletes. The 2nd request is to call the URL's that I stored from the first request. This ends up to be a total of about 2000+ requests. The collection runner in postman crashes before completion and only makes it to about 1000 requests. I have also tried running in Newman via the command prompt and as a library in addition to increasing the memory with `set NODE_OPTIONS=--max_old_space_size=60000` with no luck. 

I have attached a screenshot of the error messages I receive after trying to run newman as a library

How can I get my collection to run without crashing? Is this seriously a memory issue that cannot be resolved by the postman team? I read in a few places that Shamasis mentioned working on an option to exclude report summary info, but wouldn't that just eliminate the entire purpose of postman?  The links where Shamasis spoke on this subject are below.

https://issueexplorer.com/issue/postmanlabs/newman/2789
https://github.com/postmanlabs/newman/issues/2229

I need some help in resolving this or if not possible ( I find hard to believe) I will need to switch to a new tool :/

### Steps To Reproduce

I am only seeing this when running my collection that loops through approx 2000 requests

### Screenshots or Videos

<img width="1108" alt="Screenshot 2021-11-19 at 16 50 40" src="https://user-images.githubusercontent.com/17089546/142660818-7bebdb51-5261-418e-8626-7a9f6fa6d62b.png">

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.1.5
```

**Comment by kamalaknn** [comment] 2022-05-05 05:20
Duplicate of #10410

**Closed as completed by kamalaknn** 2022-05-05 05:20 UTC
Labels: performance, collection-runner, product/runtime
