### ISSUE TITLE
Hard crash when making requests starting with special characters

### ISSUE THREAD

**Issue by devuberoi** [a85/POSTMan-Chrome-Extension#6671] opened 2019-06-06 16:08 UTC
**Description:**
Postman app crashes when trying to make a request with special characters at the beginning of a URL.

**Steps to reproduce the behavior:**
1. Type in URL starting with special character e.g. `"https://www.google.com`
2. Click on 'Send'
3. Wait for crash

**Expected behavior:**
The app should not crash instead display an error.

**App information:**
 - App Type: Native App
 - Postman Version 7.1.1 (7.1.1)
 - OS: macOS Sierra 10.12.6

**Additional context:**
Stumbled upon this as an accident while copy-pasting a URL. Might be related to [#6664](https://github.com/postmanlabs/postman-app-support/issues/6664)

**Comment by codenirvana** [comment] 2019-06-07 07:46
@devuberoi Thanks for reporting this, we've already fixed this in our internal library and will be fixed in our next stable release.

Closing as duplicate of #6533

**Closed as completed by codenirvana** 2019-06-07 07:46 UTC
Labels: duplicate, product/runtime
