### ISSUE TITLE
when i publish collection, page reload every 1 second

### ISSUE THREAD

**Issue by marcopoloIR** [a85/POSTMan-Chrome-Extension#6916] opened 2019-07-13 04:12 UTC
i can't understand what problem is,
when i create simple collection with a simple request,
then i publish it, it creates, but destination URL  load repeatly!
this is my published URL:

https://documenter.getpostman.com/view/6887187/SVSHr9i8?messageSource=AUGURY_INSPECTED_APPLICATION&messageId=cd507b46cf581&serialize=0&messageType=9&content=[object%20Object]&version=latest

**Comment by marcopoloIR** [comment] 2019-07-15 04:50
postman published collection, at least for me, has conflict with AUGURY (angular extension), when i disable it, everything is OK.

**Comment by kaustavdm** [comment] 2019-07-15 07:59
Seems to be a serialization issue. This is affecting all published documentation.

**Comment by kaustavdm** [comment] 2019-07-15 09:00
So far, we reproduced this with certain browser extensions enabled. Grammarly on Chrome and ExpressVPN on Firefox, both on macOS, trigger the reload. Grammarly does when clicking the language dropdown. ExpressVPN triggers reload automatically.

@marcopoloIR can you confirm if you have either of these extensions enabled in your browser? If not, can you try disabling extensions one by one and tell us which one stops this behaviour?

**Comment by godfrzero** [comment] 2019-07-15 09:56
We've isolated the problem and are testing out a fix now. I'll post an update here once we've verified the fix & pushed it to production.

**Comment by godfrzero** [comment] 2019-07-15 11:55
@marcopoloIR This issue should be fixed now, could you let us know if it's still a problem?

**Closed as completed** 2019-07-16 04:38 UTC
Labels: bug, product/documentation
