### ISSUE TITLE
Collection Runner Opens with Blank screen

### ISSUE THREAD

**Issue by sneela787** [a85/POSTMan-Chrome-Extension#6324] opened 2019-04-19 12:55 UTC
**Describe the bug**
Currently I am using v7.0.8. 

**To Reproduce**
1. Click on "Runner"
2. Select the collection
3. Select the datafile
4. Changes to black screen

Sometimes it is happening without selecting any files. As soon as I open runner its immediately changing to Black screen. I restarted the application multiple times and still the same thing happens.

**Expected behavior**
It should show Runner UI and should be able to run the collections as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/48291331/56425072-c7447880-6280-11e9-8340-e54086e70db1.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by shamasis** [comment] 2019-04-19 15:30
What OS are you running it on? Linux/Windows? I am not sure where to start debugging this without being able to reproduce locally. I have a hunch though. If you are on Windows, can you try setting an environment variable as described in https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621 and let me know? 

If that does not work, can you check if you have errors in DevTools console and if so, post a sanitised copy of the same?

**Comment by sneela787** [comment] 2019-04-19 15:38
@shamasis I am currently using Windows 10. I tried setting the environment and it ran successfully, but it did show me black screen even if I select the environment for the second time. I don't see any logs in DevTools Console.

**Comment by sneela787** [comment] 2019-04-19 18:29
@shamasis I don't know if the below error is related.. But this is what I see
![image](https://user-images.githubusercontent.com/48291331/56438019-84e66000-62af-11e9-81a2-4d62797e070a.png)

**Comment by shamasis** [comment] 2019-04-19 21:35
You’re right. The errors in dev tools aren’t related. This leads me to further believe that the issue is around GPU acceleration. While I talk to the rest of the team to see if there’s any more info I can ask to better understand the cause, can you double check that the environment variable is set and retry by restarting the app? I’m hoping that the GPU environment variable would be the right fix since the symptoms match that as a cause. 

@numaanashraf, @kamalaknn - thoughts? Any way we can check from inside the app whether it is receiving the GPU disabling flag and that GPU acceleration is actually disabled.

**Comment by navidmatin** [comment] 2019-04-22 18:17
I'm having the same issue, Windows 10 (dual boot on MacBook hardware), Postman `v7.0.9`.
I noticed that this issue happens if I click on anything or not, the app loads and after 10-20 seconds goes to a black screen.
![2019-04-22_14-02-26](https://user-images.githubusercontent.com/4390676/56516767-5d8acf80-6509-11e9-88d2-459ad42582c9.gif)

**Comment by navidmatin** [comment] 2019-04-22 18:38
**Update**
Deleting the Postman related `AppData` folders fixed the issue (It appears that they do not get deleted by a simple uninstall). So I assume it was some type of cache corruption.

**Comment by romanmar** [comment] 2019-04-24 17:30
Switched back to version 6.7.4.  Version 7 has been a complete disappointment, constant crashes, crazy slowness, and now this issue appeared.

**Comment by SofiaCarGo** [comment] 2019-06-11 17:14
I was presenting the same issue in windows 10 and new version 7.1, I´m tried everything!! but this works!! 
Delete cache and cookies and sign out.
Go to View tab > Developer > Show DevTools (Current View) > Application Tab > Clear Storage 
1. Uncheck all boxes but keep check it "cache storage" 
2. Clear site data
3. Closed window
4. sign out - deleting local data
5. Log in again -  sometimes is necessary to restart your password
6. try to run your collections 💃 

These steps works for me, try it! maybe them work for you.
- Sofia 👍

**Comment by sneela787** [comment] 2019-07-18 12:40
@shamasis Any update on this bug? We are still experiencing the issue.

**Comment by saswatds** [comment] 2019-10-03 11:08
Hi everyone, in the latest canary version of app 7.9.0-canary01 we have made some performance improvements in the Collection Runner. It should now load much faster and with proper loading state. Have also been able to reduce the memory foot-print of the runner window by quite a lot so the runner resulting in the back-screen should also be mitigated to an extent.

You can download the canary app from https://www.getpostman.com/downloads/canary

Also this issue seems like a duplicate of https://github.com/postmanlabs/postman-app-support/issues/4128. I will closing this issue in favour of the other and keep that thread updated with all future updates. 

Thanks

**Closed as completed by saswatds** 2019-10-03 11:08 UTC
Labels: bug, collection-runner, product/runtime
