### ISSUE TITLE
Postman black in full screen

### ISSUE THREAD

**Issue by Axzc** [a85/POSTMan-Chrome-Extension#7784] opened 2019-12-12 02:49 UTC
**Describe the bug**
Ijust opened postman,did nothing,I encountered this problem in V7.9.0.but I still have the problem when upgrading to 7.13.0

**To Reproduce**
1. Open the Postman application.
2. Wait a few seconds

**Screenshots**
![screenshots](https://user-images.githubusercontent.com/25051943/70678718-d673ad00-1ccd-11ea-9bc1-701ce1e72f99.png)

**App information (please complete the following information):**
 - Postman Version [7.13.0]
 - OS:  Ubuntu 18.04.1 LTS

**Comment by kamalaknn** [comment] 2019-12-12 06:45
@Axzc 

Thanks for reporting the issue. Could you send the logs from `View -> Developer -> Show logs in Explorer` to `help@getpostman.com` so we can take a deeper look at this issue.

I'm closing this issue as a duplicate of #4764. Please subscribe to the linked issue for updates.

**Closed as completed by kamalaknn** 2019-12-12 06:45 UTC
