### ISSUE TITLE
Generating a collection from OpenAPI file that uses $ref doesn't work

### ISSUE THREAD

**Issue by simundev** [a85/POSTMan-Chrome-Extension#8212] opened 2020-03-21 00:36 UTC
**Describe the bug**

The OpenAPI specification supports using the `$ref` keyword in several places, including in paths, but this is not supported by Postman. Loading such a file will succeed (Create New Api), but the next step, Generate Collection, will not produce any results for those endpoints which are described in referenced files.

**To Reproduce**

Use this approach to define your endpoints:

```
paths:

  /users:
    $ref: 'endpoints/users.yaml'

  '/users/{user-id}':
    $ref: 'endpoints/users-by-id.yaml'
```

Then Create New Api from that file. And then click Generate Collection to create a collection from the API definition. A collection will be created, but requests will be created only for those endpoints that are described inline. Those that are described in other files (like the two above) will not be parsed.

**Expected behavior**
A collection is generated with all endpoints and methods.

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.20.1
 - macOS Catalina 10.15.2

**Comment by umeshp7** [comment] 2020-05-12 04:01
@simundev Thank you for reporting this. 
We do support multi-file schemas for OpenAPI but not currently through the 'Generate Collection' button in the API tab.
To import multifile schemas as a `collection` please use the `IMPORT` button on the top left corner of the Postman app and choose the option `Folder` to upload the entire folder containing this multi-file schema. It will be converted into a collection. 

We are working to bring the multifile support on the 'Generate Collection' flow as well. 

Please let us know if you face any other problem.

**Comment by VShingala** [comment] 2020-09-29 15:21
@simundev We are closing this issue as it's a duplicate of issue https://github.com/postmanlabs/postman-app-support/issues/7794. You can communicate further on that thread.

**Closed as completed by VShingala** 2020-09-29 15:21 UTC
Labels: importer, product/importers
