### ISSUE TITLE
Postman can't connect to https://localhost on MacOS

### ISSUE THREAD

**Issue by tevariou** [a85/POSTMan-Chrome-Extension#6087] opened 2019-03-15 23:52 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Postman couldn't get any response from local server although certificate and key files have been added in Postman Settings > Certificates.

**To Reproduce**
1. Send any request to https://localhost
2. Postman outputs `Error: unable to verify the first certificate`

**Expected behavior**
No TLS handshake error

**Screenshots**
n/a

**App information (please complete the following information):**
 - Postman native app 7.0.6 on MacOS Mojave 10.14.3

**Additional context**
Disabling SSL certificate verification in the settings restores connection. 
No issue on Postman chrome app or Insomnia (with SSL certificates validation enabled).

**Comment by shamasis** [comment] 2019-03-19 05:53
Your SSL certificate that’s been installed in localhoat seems to have had been added to root certificate list in OS and that’s my guess why it’s working fine on Chrome. Postman does not share root certificate from OS yet. 

In our next release, we are working towards the ability to allow adding Root CA in Postman App.

**Comment by shamasis** [comment] 2019-03-19 05:55
Duplicate of 
https://github.com/postmanlabs/postman-app-support/issues/3290

**Closed as completed by shamasis** 2019-03-19 05:55 UTC
Labels: feature, Certificate, duplicate, product/runtime

**Comment by temitopealabi** [comment] 2020-03-08 11:57
was able to import my self signed certificate into postman settings
in Postman 
click Settings  at right top bar gear icon >  Click Certificates then click on import icon

thanks Postman
