### ISSUE TITLE
Support for swagger v3.0.0/OpenAPI

### ISSUE THREAD

**Issue by dancrumb** [a85/POSTMan-Chrome-Extension#3390] opened 2017-08-15 19:16 UTC
## App Details:

```
Postman for Chrome
Version 5.1.3
OS X / x86-64
Chrome 60.0.3112.90
```

## Feature Request

Currently, Swagger import is limited to v1 and v2 of the swagger schema.

With the release of swagger v3.0.0, AKA OpenAPI, is support for this on the roadmap?

**Comment by prashantagarwal** [comment] 2017-08-16 09:58
@dancrumb Thanks. We will review this request and get back to you with an update on this.

**Comment by wowi42** [comment] 2017-09-25 07:52
Some news?

**Comment by OwlLaboratory** [comment] 2017-11-09 17:20
It would be very usefull ! :)

**Comment by ghost** [comment] 2017-11-17 09:16
We're upgrading stuff to use swagger.core.v3 which gives us OpenApi v3. Support for this in Postman would be very useful!

**Comment by DylanC** [comment] 2017-11-17 14:04
Also interested in this feature.  Ready API has supported this feature for some time already.

**Comment by rlcomte** [comment] 2017-11-24 12:45
As we are using Postman for API testing, and we want to upgrade our Swagger API specs to 3.0, it is a must-have.

**Comment by arthurgrig** [comment] 2017-11-30 19:08
This is a must have.

**Comment by dvh** [comment] 2017-12-21 15:20
+1

**Comment by lyneca** [comment] 2017-12-28 07:41
+1

**Comment by chadbr** [comment] 2018-01-05 16:56
any updates here? an ETA?

**Comment by a85** [comment] 2018-01-05 16:58
Commented here on our approach towards this: https://github.com/postmanlabs/postman-app-support/issues/1669

**Comment by Sergi0** [comment] 2018-01-23 14:11
Swagger just announced Swagger Inspector, so openapi 3 support looks like a crucial feature now

**Comment by pabloharrys** [comment] 2018-01-26 19:45
+1

**Comment by Frank591** [comment] 2018-01-31 16:13
Any plans about OpenAPI3 support?

**Comment by dmitry-mukhin** [comment] 2018-02-07 14:06
just subscribing to this epic thread :p

**Comment by alexmreis** [comment] 2018-02-14 07:23
+1

**Comment by darkturo** [comment] 2018-02-27 13:30
Hmm this has been labeled as a feature but I see that is not planned for the next 12 months (https://trello.com/c/4WUkp8Ob/18-track-current-issues-and-log-new-ones-on-github-also-submit-new-feature-requests-here). Actually, it seems it has been lost in the backlog :-/ ...

**Comment by ekkinox** [comment] 2018-03-08 15:49
+1, with both YAML and JSON support

**Comment by sirdawidd** [comment] 2018-03-08 15:53
+1

**Comment by hobbes38111** [comment] 2018-03-09 11:56
+1

**Comment by realB12** [comment] 2018-03-12 11:11
I really do not understand why Swagger and now new OpenAPI-Specs have not been considered to be at the base of all the data architecture here. When adding Swagger just as an afterthought I am not convinced to invest into Postman any further because I do not want to be locked into a proprietary product that takes in all the Swagger-stuff but does not give back in return!

**Comment by youcef-laribi** [comment] 2018-03-16 00:42
+1

**Comment by Kalki5** [comment] 2018-03-23 09:01
+1

**Comment by zoul** [comment] 2018-03-23 10:26
PLEASE, when you are just adding a +1 comment, do realize you are spamming some twenty people with a useless e-mail. (Just as I am doing now – sorry!) There’s an upvote button on the original post for this precise reason. Use it. ❤️

**Comment by Broutard** [comment] 2018-03-30 08:40
+1

**Comment by itsjavi** [comment] 2018-04-14 14:33
@a85 we use Postman at my company with a team license and we use Open API 3.0 too, which is automatically generated from our API. We have in the other hand to maintain Postman manually every time we have new endpoints or changes in our API...

Please understand that being able to import Swagger/Open API (an specification being supported by big companies like Google, Microsoft) is an invaluable and essential resource.

I don't say you have to support the whole specification, but at least being able (in the beginning) to import the basics (path, method, request headers, request body) would be very helpful and incredibly time saving.

If OpenApi/Swagger support is such a problem and has such low priority... we will have to consider to not renew the license anymore.

**Comment by a-akimov** [comment] 2018-06-01 12:37
Agree with the comments above. Supporting only Swagger 2.0 doesn't help Postman get more traction from those companies who build their API lifecycle around OpenAPI 3.0. And OpenAPI 3.0 is becoming a de-facto standard for defining and describing web APIs. 

Please, support OpenAPI 3.0 in Postman.

**Comment by dinamic** [comment] 2018-06-19 11:17
Guys, it's been almost a year since this issue was posted. Should this have been properly handled, you could have had an implementation half a year ago.

Please, raise the priority of this feature request!

**Comment by philsturgeon** [comment] 2018-06-20 13:27
Seeing as this process is import only (that's not ideal but lets save that for another place) the import process could very easily be based around [swagger2openapi](https://github.com/Mermade/swagger2openapi), which will convert OpenAPI v2 to v3. 

If you build your code to support v3 only and convert up from v2, you'll have everything covered. Honestly Swagger 1.x is so out of date there's not much supporting it, and if folks need to convert there are other ways to get that done, like [APImatic Transformer](https://apimatic.io/transformer).

**Comment by stianlagstad** [comment] 2018-06-28 14:45
@philsturgeon My problem (and many others here) is that I have an openapi v3 specification file that I want to import to Postman. I have not found any good tools to convert from openapi v3 -> openapi v2 / swagger.

[APImatic Transformer](https://apimatic.io/transformer) did not work the last time I tried it, but I do see that it is able to convert from openapi v3 -> swagger v2 now. Importing the result of that into Postman works as well :) The requests are named after the description of the endpoints in the original v3 spec file and not the endpoint path which I would prefer, but it's a lot better than nothing.

**Comment by dinamic** [comment] 2018-06-28 14:58
Thanks for the workaround, @philsturgeon! I had no clue a tool like APImatic Transformer existed.

It is a workaround, thou.

I would love it if Postman, as a modern tool for testing APIs, embrace a modern standard for documenting APIs. Feels like the right thing do expect, right?

**Comment by derrickmehaffy** [comment] 2018-07-17 11:45
+1 from me on openAPI Spec 3.0.0

**Comment by robations** [comment] 2018-07-17 12:17
@derrickmehaffy Better to use the thumbs up on the original post instead of adding +1 comments, which spams everyone with notifications.

**Comment by a-akimov** [comment] 2018-07-17 20:56
@robations sorry, I disagreee. This is a huge problem for everyone who wants to migrate to OpenAPI 3.0 (which is already a year being live now) and benefit from Postman at the same time, So, leaving a comment here shouldn't be considered as spam at all - this is the only possibility for us to show how important it is.

**Comment by philsturgeon** [comment] 2018-07-18 04:25
@a-akimov comments with constructive content is helpful, but comments with only +1 is spam. You can always thumb the PR to show support. Please let’s not keep spamming people. This thread might be here for a while and we don’t want folks to have to mute it.

**Comment by thecb4** [comment] 2018-07-28 23:36
As someone new to Swagger/OAS and attempting to use current tooling, I would like to have Postman support OAS 3. Otherwise, Postman is not an option for me.

**Comment by and0x000** [comment] 2018-07-30 16:10
You can try to convert your openapi 3 spec via [api-spec-converter](https://github.com/LucyBot-Inc/api-spec-converter) to swagger 2 which then in turn is accepted by postman. Needs some more tooling, native support of openapi 3 spec would obviously be the neater choice, but it works for me.

**Comment by kibertoad** [comment] 2018-07-30 16:13
@and0x000 While there is a number of possible workarounds, it is somewhat troubling that a product with commercial support hasn't issued any official statement regarding plans to support OpenAPI 3.0.

**Comment by piersmacdonald** [comment] 2018-08-02 17:00
Add me to the train of wanting OpenAPI 3.0 support.

While we're at it, it would be great to import API functionality too so we can programmatically update our POSTMAN collection. Our API builds auto generate swagger3 specs, it would be great to have a CI step which updates POSTMAN so other developers on our account can start testing against our API immediately.

**Comment by derrickmehaffy** [comment] 2018-08-02 21:32
@and0x000 The problem being that the 2.0.0 spec doesn't properly support bearer JWT authentication (added in 3.0.0)

@robations That is the point of +1 to bring up this issue again.

@kibertoad I completely agree with you.

**Comment by ianlintner** [comment] 2018-08-09 17:25
+1

**Comment by gnarr** [comment] 2018-08-17 11:09
+1

**Comment by mrpwhiteSPS** [comment] 2018-08-20 20:28
+1

**Comment by EricLanduyt** [comment] 2018-08-20 20:32
+1

**Comment by bkatznelson** [comment] 2018-08-20 20:40
+1

**Comment by bmarka** [comment] 2018-09-14 10:03
A must have indeed, don't fall behind 🥇

**Comment by rhuanbarreto** [comment] 2018-09-24 10:55
Please let's upvote the trello card on https://trello.com/c/JEgGQfvh
Then they can prioritize this!

**Comment by stellis** [comment] 2018-10-29 15:04
@rhuanbarreto That's a good suggestion. However, it looks like "improvements to tab management" (whatever that means) has 2 votes and is "short-term," while OAS 3 support has 81 votes and is "mid-term." It's been mid-term since May of last year, so I guess mid-term = never.

This is a disappointing way to handle requests for the latest version of the most popular API spec format. There doesn't even seem to be acknowledgement that it's useful and will be worked on at all.

**Comment by philsturgeon** [comment] 2018-10-29 19:34
It really seems like this issue is not going to happen. For some reason OpenAPI support is just not a priority. 

Adding good OpenAPI import (and sync - ongoing reimporting to keep things up to date) could really open up a lot of use-cases. At [WeWork we are OpenAPI-first](https://engineering.wework.com/our-api-specification-workflow-9337448d6ee6), and we mirror back to Postman so folks have the best of OpenAPI without having to manually also keep their Postman collections up to date.

You could do so many awesome things, like taking the request/response schemas to build examples automatically, to save users having to copy and paste examples into the GUI. 

Please bump this up as a priority folks.

**Comment by diegoventuri7** [comment] 2018-11-13 11:14
+1

**Comment by qrayven** [comment] 2018-11-13 15:46
+1

**Comment by jpuck** [comment] 2018-11-14 19:10
@vkaegis I'm curious, what is the `ADP` label for? Should I get excited this issue is getting some traction?

**Comment by rdkls** [comment] 2018-11-15 00:26
I just set up docker image to solve by converting v3 => v2

`docker run --rm -v $PWD:/tmp -e OPENAPI_FILE=swagger.yml rdkls/openapi2swagger > swagger.openapiv2.yml`

Also includes free bitcoin miner!
(j/k but pls check dockerfiles before running ...)

(thanks juan-lb on github, and  LucyBot-Inc/api-spec-converter)

**Comment by stellis** [comment] 2018-11-15 00:31
@rdkls Thanks for sharing this, but it's not going to solve the problem for some of us.

v3 has features that can't be converted back down to v2 losslessly. One example is [anyOf](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/).

I recently tried a v3-to-Postman converter and the results were a disaster. There were response headers moved into the request parameters, among many other inaccuracies.

There are tons of libraries Postman could use if they wanted to support v3. It's baffling and user-unfriendly that they haven't already.

**Comment by a85** [comment] 2018-11-24 02:36
Everyone, We are testing out OpenAPI 3 support in our Canary builds (getpostman.com/canary). It might not be perfect but help us test it out! We are also building a plug-in model that will help us update OpenAPI and schema support independently of releasing a new version of the app. The development of the plug-in system is what has resulted in seemingly no visible progress on this but we see that as an essential part to support OpenAPI and other schema formats in Postman. Eventually, it got pretty taxing for the team to support the variety of importers/exporters in line with our development process.

**Comment by philsturgeon** [comment] 2018-11-24 03:37
Amazing! Thank you so much. 

Totally understandable that building an entire add on system slowed you down. If a similar situation pops up maybe you could post a link to an issue for “Add-on System” and folks could follow that progress, then folks know what you’re up to and don’t feel like they’re being ignored. :)

I’ll check it out soon. Thanks again!

**Comment by luketlancaster** [comment] 2018-11-26 17:20
Just tried the import OpenAPI 3 situation, and it worked really well! Our docs are only so good (and I'm personally only the tiniest bit knowledgeable about all of this 😬), as we're getting things converted over, but it's a great start. Thanks for working on it!

**Comment by a85** [comment] 2018-11-26 21:40
@philsturgeon Thanks! I agree with the suggestion. We are getting better at managing the tracker in general but it's hard for to deal with the volume of comments + issues (all great feedback of course). The team will update other threads too. Lots coming up in 2019.

**Comment by markmooibroek** [comment] 2018-11-27 10:00
Good to hear this is actively worked on! Tested the function with the Canary build, but got an undefined error. Maybe you can improve things with my json file. Good luck!

[open_api_3_test.json.txt](https://github.com/postmanlabs/postman-app-support/files/2619286/open_api_3_test.json.txt)

**Comment by SamvelRaja** [comment] 2018-11-27 12:34
@markmooibroek  Thanks for providing the Test file.
 We could reproduce the issue. We shall update this thread once it gets fixed from our end.

**Comment by derrickmehaffy** [comment] 2018-11-27 15:02
@SamvelRaja I am also getting an undefined error, I do have a bit of redocs x-data stuff in mine as well, your welcome to use it as a test case also: (Warning it is quite large and it is very possible that it could be user error 😛 ) https://github.com/canonn-science/CAPIv2-Strapi/blob/development/public/openapi.yaml

**Comment by SamvelRaja** [comment] 2018-11-28 09:27
@derrickmehaffy  Thanks for providing the test case JSON.

**Comment by patthiel** [comment] 2018-11-28 16:27
@SamvelRaja I experienced the same error as @markmooibroek  while attempting to import our OpenAPI 3 spec. In case you need another 10000+ line spec to reproduce from 😄: 

https://developers.linode.com/api/v4/openapi.yaml

**Comment by abhijitkane** [comment] 2018-11-30 11:40
@patthiel @derrickmehaffy - Your specs should import in the latest version of Postman Canary - `6.6.0-canary02`
@markmooibroek - Your spec should import as well. We're tracking an issue where example URLs for requests with path variables in the URL aren't being imported correctly, and we expect a fix to be out in a few days. -  https://github.com/postmanlabs/postman-collection/issues/740

**Comment by jcstanaway** [comment] 2018-11-30 14:30
6,6,0-canary02 appears to have an issue with forward references.  I had a $ref to an element defined later in the file and the import failed with an error that it couldn't find that referenced element.  I moved things around so that the element was before the reference and the import succeeded.

I can't post the spec due to proprietary reasons, but if needed I can try to mock something up.

**Comment by abhijitkane** [comment] 2018-12-03 05:37
@ccs018 Odd - we look through all components before constructing the requests. An example OAS spec would help.

**Comment by jcstanaway** [comment] 2018-12-03 14:39
I'll try to put a sample spec, but might take a couple days before I can do that.  Note that this was within the components section - an element in the components $ref'ed to something later within the components.

**Comment by abhijitkane** [comment] 2018-12-03 17:25
@ccs018 I'm able to import the JSON at https://gist.github.com/abhijitkane/9ca56ec40bc2668107b85ce92d4f402a with the properly generated response. The Pet schema is referenced in, but defined after Pets.

**Comment by Ryandaydev** [comment] 2018-12-04 18:49
Checked canary build against a working OpenAPI spec, and it imported successfully and requests worked.

**Comment by zmes50416** [comment] 2018-12-05 09:57
Tried the canary03 version, import working really well! 
But I got one issue that server template variable is not parsing correctly.

According to openAPI 3 document [here](https://swagger.io/docs/specification/api-host-and-base-path/), It does support server templating. 
Can Postman parse it as the Environment variable? 
Ex: 
```
server:
  - url: http://{host}:{port}
    variables:
      - host:
      - port:
```
request should be parsed as` http://{{host}}:{{port}}/what/every/your/api`
instead it is been parsing as `http://{host}:{port}/what/every/your/api`

For now I am manually modifying it. It is workable in short term, but an auto parsing when importing will be a lot helpful!

Neverthelast, thank you guys for support OpenAPI, It really help me a lot.

**Comment by mm-matthias** [comment] 2018-12-07 08:57
Are OpenAPI files with $refs to other files supported yet? I've got something looking like:

api.yaml:
```yaml
paths:
  /somepath/:
    get:
      operationId: someoperation
      summary: bla
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: 'models.yml#/components/schemas/some-model'
```

And the models.yml contains the corresponding schema.

When I add api.yaml in Postman's "Import files" section, the importer will complains 

`Error while importing Open API 3.0: ref models.yml#/components/schemas/some-model not found.`

When I try to use the "import folder" option (all my .yml files are in that folder), nothing happens.

Is this scenario supposed to work?

EDIT: Hmm, it does seem to work with a different file that referencs other .yamls. So the message is probably misleading, I guess there is some exception down the line when processing one of the files and this exception is not carried upwards to the message?!

**Comment by mm-matthias** [comment] 2018-12-07 10:38
Do you have any plans to add generation/editing of request bodies with OpenAPI 3.0? Having only the urls and query params doesn't really address our needs as all the meat is in the request body.

**Comment by philsturgeon** [comment] 2018-12-07 16:18
Entirely agree that request bodies and example requests / responses should be built up using the OpenAPI Schema provided for that request/response.

**Comment by abhijitkane** [comment] 2018-12-08 12:20
@mm-matthias Could you share a sample spec? Right now, the importer generates a sample request body/example response body based on the schema (for form-data, urlencoded, and raw-JSON formats only). Are you using an XML schema?

**Comment by danfowler** [comment] 2018-12-12 04:44
https://swagger.io/docs/specification/authentication/

> After you have defined the security schemes in the securitySchemes section, you can apply them to the whole API or individual operations by adding the security section on the root level or operation level, respectively.

I've defined and applied a security scheme at the root level only, so I would expect each endpoint of the imported collection have an Authorization of type "Inherit auth from parent".  Instead, after importing a new collection from my OpenAPI file, each endpoint's Authorization is set to Basic Auth.  This is inconvenient, because I then have to manually set each endpoint to inherit its authorization.  

I think setting the root level OpenAPI authorization as the Collection authorization (currently, it's "No Auth") and defaulting the endpoint Authorization type to "inherit auth from parent" would be ideal as that is the expected behavior of OpenAPI.

**Comment by abhijitkane** [comment] 2018-12-12 13:53
@mm-matthias @philsturgeon We've open-sourced the converter at https://github.com/postmanlabs/openapi-to-postman. The current Postman Canary uses 0.0.7.

We've added basic support for generating XML request/response bodies too - this should show up in the next Canary release.

@danfowler Agreed - will work on this.

**Comment by a85** [comment] 2018-12-12 18:23
Thank you for your patience everyone. Closing this issue now. If you have comments/suggestions/bug reports for the feature please file it in the repo that @abhijitkane linked to. We'll be soon rolling out the ability to update plug-ins without having to update the app and improvements to converters will ship much faster.

**Closed as completed by a85** 2018-12-12 18:23 UTC
Labels: feature, Plugin
