### ISSUE TITLE
List of variables appears behind of the window

### ISSUE THREAD

**Issue by patrickjmeurer** [a85/POSTMan-Chrome-Extension#8842] opened 2020-07-27 17:55 UTC
**Describe the bug**
I'm trying to add a environment variable to my collection and the list of variables appears behind the window

**To Reproduce**
1. Click in the tree dots in a collection
2. Click in Edit
3. Select "Authorization"
4. Select any type and try to write a variable, on my case, i type `{{access_token`
5. See de error.

**Expected behavior**
The list of variables appears above the collection window

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/8931135/88574681-0f705000-d019-11ea-8774-a35cf5a2960c.png)

**App information:**
 - App Type: Desktop
 - Postman Version: 7.29.1
 - OS: Windows 10 2004

**Comment by DannyDainton** [comment] 2020-07-27 19:40
Duplicate of 

https://github.com/postmanlabs/postman-app-support/issues/8819

**Closed as completed** 2020-07-30 10:59 UTC
Labels: bug, product/runtime
