### ISSUE TITLE
How to change Postman's SSL Certificate?

### ISSUE THREAD

**Issue by gartmeier** [a85/POSTMan-Chrome-Extension#4328] opened 2018-03-13 12:08 UTC
I'd like to use Postman's proxy to monitor requests from my iOS simulator. I configured the HTTP and HTTPs proxy in my network settings and everything works fine for HTTP, but unfortunately, the certificate delivered by postman over HTTPS isn't trusted and expired in 2015.

To be able to use the proxy from the iOS simulator I'd need a CA root certificate to be delivered by Postman. CA root certificates can be easily generated on macOS and are the only ones you can mark as trusted in the iOS simulator.

Is it possible to change the SSL certificate delivered by Postman?

**Comment by sivcan** [comment] 2018-03-21 11:36
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3290

**Closed as completed by sivcan** 2018-03-21 11:36 UTC

**Comment by bayan9** [comment] 2018-12-26 08:40
charlesproxy supports this, but i wish it was possible with postman
