### ISSUE TITLE
Postman Icon not visible on Windows

### ISSUE THREAD

**Issue by jiangtianyou** [a85/POSTMan-Chrome-Extension#7103] opened 2019-08-13 10:39 UTC
**Describe the bug**
Postman Icon not visible on Windows
![image](https://user-images.githubusercontent.com/5664308/62935311-60cc0300-bdf9-11e9-840a-3cba16db3d02.png)

**To Reproduce**

**Expected behavior**
expected show postman icon

**App information (please complete the following information):**
 - App Type 
Windows Desktop app
 - Postman Version 
![image](https://user-images.githubusercontent.com/5664308/62935364-848f4900-bdf9-11e9-9339-c2fef6ebf15d.png)

 - OS: widnows10

**Comment by djbios** [comment] 2019-08-13 14:23
Same thing

**Comment by kamalaknn** [comment] 2019-08-14 08:37
Hi @jiangtianyou 

Thanks for reporting this issue. This is a regression introduced in Postman 7.3. We were able to reproduce this and we are working on a fix for this.

This is a duplicate of #6897. I'm closing this issue. Please follow the original issue for updates.

**Closed as completed by kamalaknn** 2019-08-14 08:37 UTC
