### ISSUE TITLE
Postman crash after sending a request

### ISSUE THREAD

**Issue by xsauce** [a85/POSTMan-Chrome-Extension#6686] opened 2019-06-10 06:30 UTC
**Describe the bug**
Postman crash after sending a request which url contains a invisible character. And I find some error message in ~/Library/Application Support/Postman/logs/main.log:

[26250][1560136290743][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read property 'toLowerCase' of null","stack":"TypeError: Cannot read property 'toLowerCase' of null\n    at Object.getRequestOptions (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/core.js:304:59)\n    at Requester.request (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:178:31)\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:117:37\n    at Function.create (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:336:16)\n    at RequesterPool.create (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester-pool.js:60:22)\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:105:32\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16\n    at replenish (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)\n    at iterateeCallback (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:995:17)\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:969:16\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1137:13\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/runner/request-helpers-presend.js:315:20\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16\n    at next (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:5329:29)\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:969:16\n    at Function.session.resolveProxy (/Applications/Postman.app/Contents/Resources/app/utils/getSystemProxy.js:32:16)"}]

**To Reproduce**
1. Add Request In a collection
2. Copy "https://httpbin.org/get" into the URL input box
3. Enter Send

**Expected behavior**
I think postman should be trim all the invisible characters in a url

**Screenshots**
URL:
![image](https://user-images.githubusercontent.com/1265474/59176583-242b2380-8b8c-11e9-9eab-198d32cfedc9.png)
Postman Screenshot after Copying the url which contains a invisible character
![image](https://user-images.githubusercontent.com/1265474/59176444-a6671800-8b8b-11e9-9ebb-eac2eb42cdc4.png)

**App information (please complete the following information):**
 - Native App
 - Postman 7.1.1
 - macOS Mojave 10.14.5

**Comment by shamasis** [comment] 2019-06-11 05:01
Thanks for reporting. We have identified this bug and would fix it in our next release.

**Comment by codenirvana** [comment] 2019-06-11 10:40
Duplicate of #6533

**Closed as completed by codenirvana** 2019-06-11 10:40 UTC
Labels: bug, product/runtime
