### ISSUE TITLE
Error: self signed certificate in certificate chain in version 6.7.2

### ISSUE THREAD

**Issue by esheafer** [a85/POSTMan-Chrome-Extension#5856] opened 2019-01-30 23:25 UTC
## App Details:

```
Postman for Windows
Version 6.7.2
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: It just started after updating to Postman 6.7.2.
 2. Expected behaviour: In version 6.7.1 I could hit our OATH2 token service and get an authorization token with no issues. Now in version 6.7.2 I keep getting this "Error: self signed certificate in certificate chain". I rolled back to version 6.7.1 and I can get tokens again and I don't see that issue. 
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable) console logs for version 6.7.1 and 6.7.2 are attached.

Steps to reproduce the problem
1. Setup up a post to a secure service
2. Go To Authorization tab, choose type OAuth 2.0, choose Add authorization data to Request Headers
3. Click on Get New Access Token button
  3a. Choose Grant Type: Client Credentials
  3b. put in url to token service
  3c. put in client id
  3d. put in client secret
  3e. put in scope we are requesting access too
  3f. choose Client Authentication of Send client credentials in body
4. Click Request Token 
![v6 7 1](https://user-images.githubusercontent.com/14790885/52019815-df87d100-24a3-11e9-9150-e98657a5b966.JPG)
![v6 7 2](https://user-images.githubusercontent.com/14790885/52019817-e0b8fe00-24a3-11e9-85db-3f0a07bbe4dc.JPG)

**Comment by codenirvana** [comment] 2019-01-30 23:51
Duplicate of #5819

@esheafer  Please follow #5819 for updates on this issue.

**Closed as completed by codenirvana** 2019-01-30 23:51 UTC

**Comment by esheafer** [comment] 2019-01-31 16:13
@codenirvana thanks!
