### ISSUE TITLE
Windows desktop app crashes after response

### ISSUE THREAD

**Issue by tradeli** [a85/POSTMan-Chrome-Extension#6080] opened 2019-03-14 17:57 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Just after sending a POST request with a huge (a few thousands lines) of JSON payload, and expecting to receive a few hundred thousand lines response as return, the app crashes without any message.

**To Reproduce**
1. Create a POST request with a huge JSON payload
2. Click on 'Send'
3. [Expect a huge response back]
4. After a long time, the app just crashes

**Expected behavior**
The response of the server should be rendered on the appropriate screen.

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.0.6
 - OS: Windows 10.0.17134 on x64

**Additional context**
**The main log file has this error when the app crashes:**
```
[11132][1552584666411][main][error]["Main~handleUncaughtError - Uncaught errors",
{
        "name": "Error",
        "message": "\"toString()\" failed",
        "stack": "Error: \"toString()\" failed
        at Buffer.toString (buffer.js:607:17)
        at Request._callback (C:\\Users\\thullyo.castilho\\AppData\\Local\\Postman\\app-7.0.6\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:145:25) 
        at Request.self.callback (C:\\Users\\thullyo.castilho\\AppData\\Local\\Postman\\app-7.0.6\\resources\\app.asar\\node_modules\\postman-request\\request.js:247:22)
        at emitTwo (events.js:125:13)
        at Request.emit (events.js:213:7)
        at Request.<anonymous> (C:\\Users\\thullyo.castilho\\AppData\\Local\\Postman\\app-7.0.6\\resources\\app.asar\\node_modules\\postman-request\\request.js:1230:10)
        at emitOne (events.js:115:13)
        at Request.emit (events.js:210:7)
        at IncomingMessage.<anonymous> (C:\\Users\\thullyo.castilho\\AppData\\Local\\Postman\\app-7.0.6\\resources\\app.asar\\node_modules\\postman-request\\request.js:1152:12)
        at Object.onceWrapper (events.js:314:30)
        at emitNone (events.js:110:20)
        at IncomingMessage.emit (events.js:207:7)
        at endReadableNT (_stream_readable.js:1045:12)  
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)"
    }]
```

**Comment by codenirvana** [comment] 2019-03-25 11:05
@tradeli This looks like a duplicate of #4751
Any idea about the size of the JSON payload?

**Comment by tradeli** [comment] 2019-03-25 16:02
It is variable, but around 15MB.

**Comment by codenirvana** [comment] 2019-06-17 11:22
As mentioned in https://github.com/postmanlabs/postman-app-support/issues/4751#issuecomment-501420752, you can try out improvements in the Canary channel here: https://www.getpostman.com/downloads/canary

Closing as duplicate of #4751

**Closed as completed by codenirvana** 2019-06-17 11:22 UTC
Labels: bug, product/runtime
