### ISSUE TITLE
call one request to other request(as a reusable function )  

### ISSUE THREAD

**Issue by avinashkandukuri** [a85/POSTMan-Chrome-Extension#4792] opened 2018-07-07 18:15 UTC
Hi, 

I am trying to call one request to other as a (reusable function)
for instance, a sample scenario 
I have a collection with a list of requests 
     Authentication 
     Signon
     homePageDetails
     Make payment
     Delete a payment
     
**In the first Scenario**
 Authentication -> Signon ->  homePageDetails this is possible by using the 
Authentication -> postman.setNextRequest("SignOn") -> postman.setNextRequest("homePageDetails");;

**In the Second scenario,** 
I am trying to make a call inside the call if I run the 
homePageDetails request it should first execute Authentication, SignOn then HomePageDetails

Now I am trying as an Ajax calls inside the PreRequestScript but the line of code is repetitive, so I am want to make it as a reusable function for both Authentication and SignOn  

**my Thoughts on this**
pm.Sendrequest("Authentication");  pm.Sendrequest("SignOn"); this both functions used in the preReqeuest Script of  homePageDetails, MakeApayment or Delete a payment.

**Comment by harryi3t** [comment] 2018-07-09 07:49
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4024

**Closed as completed by harryi3t** 2018-07-09 07:49 UTC
