### ISSUE TITLE
JSON broken in pretty mode and valid in raw mode

### ISSUE THREAD

**Issue by LonerKO** [a85/POSTMan-Chrome-Extension#7388] opened 2019-09-25 14:11 UTC
RAW MODE
`{"jsonrpc":"2.0","result":{"s_registrant":{"r_type":"person","r_name":"СУПЕР ТЕСТ","r_chief":null,"r_phone":"+375257701847","r_email":"petrushko@test.by","r_unp":null,"address_country":"BY","address_city":"Минск","address_region":"Минская","address_index":"220028","address_street":"Либавороменская","address_building":"20005","address_office":"20005","passport_ser":"AB","passport_nmbr":"2117911","passport_org":"sdf","passport_date":"23.10.2010","passport_personalnmbr":"3242342W234WE6","egr_num":null,"egr_org":null,"egr_resh":null,"egr_date":null,"whois_privacy_protect":"True","contract_info":{"applicant_position":"Позиция1","applicant_name":"Имя1","number":"0XX0XX0YY","order":"06.06.2000","validity":"06.06.2021"}},"s_ns":null,"s_state":{"domain":"12.test-reg-dom.by","status":"OK","crDate":"2019-05-30T13:18:02Z","exDate":"2020-05-30T13:18:13Z","pendingExDate":null}},"id":1}
`
https://prnt.sc/pau35w

PRETTY MODE
`{"jsonrpc":"2.0","result":{"s_registrant":{"r_type":"person","r_name":"СУПЕР
ТЕСТ","r_chief":null,"r_phone":"+375257701847","r_email":"petrushko@test.by","r_unp":null,"address_country":"BY","address_city":"Минск","address_region":"Минская","address_index":"220028","address_street":"Либавороменская","address_building":"20005","address_office":"20005","passport_ser":"AB","passport_nmbr":"2117911","passport_org":"sdf","passport_date":"23.10.2010","passport_personalnmbr":"3242342W234WE6","egr_num":null,"egr_org":null,"egr_resh":null,"egr_date":null,"whois_privacy_protect":"True","contract_info":{"applicant_position":"Позиция1","applicant_name":"Имя1","number":"0XX0XX0YY","order":"06.06.2000","validity":"06.06.2021"}},"s_ns":null,"s_state":{"domain":"12.test-reg-dom.by","status":"OK","crDate":"2019-05-30T13:18:02Z","exDate":"2020-05-30T13:18:13Z","pendingExDate":null}},"id":1}`

https://prnt.sc/pau3d2

Bug with ""

**Comment by timothyj-splunk** [comment] 2019-09-28 02:07
This broke in the latest version.  I can't use postman effectively for demonstrations or development with all but small JSONs.

**Comment by kamalaknn** [comment] 2019-10-09 04:16
Hey @timothyj-splunk @LonerKO 

Thanks for reporting this issue. I tried reproducing this issue by creating a mock server that returns the JSON you have provided(https://6113ac09-2d1b-4a7b-9dc9-9e888e3de159.mock.pstmn.io/get). I don't see any issues and the formatting is applied correctly. 

Also, I don't see any difference between the two JSON texts you have provided.

If you are seeing the JSON not prettified, can you ensure that the response contains a valid and correct `Content Type` header?

If you could provide steps to reproduce and clearly define the expected and actual experience it will help us identify the issue better.

Can you provide a reproduction

**Comment by timothyj-splunk** [comment] 2019-10-10 18:02
Thank you!  I can no longer reproduce it. It was definitely there (after update) and it's definitely gone.  I may have restarted postman.

**Comment by kamalaknn** [comment] 2019-10-13 11:07
@timothyj-splunk Thanks for the clarification. I'm closing this issue since there is not seen again the issue does not have enough information for us to identify any problems. Feel free to let us know if you encounter this again.

**Closed as completed by kamalaknn** 2019-10-13 11:07 UTC
Labels: bug
