### ISSUE TITLE
allow_redirects is added twice in example POST request in Postman Echo docs/ POST Raw Text section

### ISSUE THREAD

**Issue by karinakozarova** [a85/POSTMan-Chrome-Extension#5919] opened 2019-02-13 12:44 UTC
**Describe the bug**
allow_redirects is added twice in example POST request in Postman Echo docs/ POST Raw Text section

**To Reproduce**
1. Go to https://docs.postman-echo.com/, 
2. Scroll to the POST Raw Text section
3. look at the example, the parameter allow_redirects is added twice

**Expected behavior**
`response = requests.request('POST', url, headers = headers, data = payload, allow_redirects=False, timeout=undefined, allow_redirects=false)` should become `response = requests.request('POST', url, headers = headers, data = payload, allow_redirects=False, timeout=undefined)`

**App information (please complete the following information):**
Postman Echo docs hosted at https://docs.postman-echo.com/

**Comment by Cazaimi** [comment] 2019-07-18 10:44
Beginning investigation.

**Comment by seelaman** [comment] 2019-09-09 17:52
duplicate of #6152

**Comment by Cazaimi** [comment] 2019-12-09 06:05
@Raja-Simha , this is solved and can be marked as closed.

**Closed as completed** 2020-02-18 06:33 UTC
Labels: bug, product/documentation
