### ISSUE TITLE
I can't log in - the website and the application is just spinning

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5794] opened 2019-01-18 09:14 UTC
Unable to access the postman app & web dashboard as the page keeps spinning. Find below are the screenshot of related logs.

![image](https://user-images.githubusercontent.com/40994626/51377575-45359e00-1b31-11e9-9d5d-29d9de69df6d.png)

![image](https://user-images.githubusercontent.com/40994626/51377606-5383ba00-1b31-11e9-88ef-f8b03c3e3399.png)

![image](https://user-images.githubusercontent.com/40994626/51377657-7b731d80-1b31-11e9-9049-a83fdacaa5eb.png)

![image](https://user-images.githubusercontent.com/40994626/51377741-a52c4480-1b31-11e9-95a1-31d074801d4f.png)

**Comment by numaanashraf** [comment] 2019-02-21 18:37
Closing this as this seems to have been caused by an service incident and is resolved now.

**Closed as completed by numaanashraf** 2019-02-21 18:37 UTC
Labels: bug, service-incident, authentication-service
