### ISSUE TITLE
Copy to Clipboard with Pretty JSON response failing

### ISSUE THREAD

**Issue by bkmetzler** [a85/POSTMan-Chrome-Extension#3691] opened 2017-10-30 04:24 UTC
## App Details:
Postman for Linux
Version 5.3.2
linux 4.4.0-97-generic / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Issue was not present in Postman-linux-x64-5.1.3.tar.gz
Next version I installed, that shows the issue, is Postman-linux-x64-5.3.2.tar.gz

 2. Expected behaviour:
Being able to copy data from JSON output to clipboard.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
N/A, as not Chrome based install.  If debug instructions provided, I can provide output.

 4. Screenshots (if applicable)
N/A

 5. How to reproduce:
HTTP GET Body Response with "Pretty" and "JSON" selected does not allow for copying characters to clipboard.
Tried copying via CTRL+C and Mouse Right Click -> Copy.  Both ways do not copy the data selected to clipboard.

 6. Troubleshooting steps:
   When selecting "Raw", with the same HTTP GET, both CTRL+C and Mouse Right Click -> Copy both work.

**Comment by prashantagarwal** [comment] 2017-11-02 16:00
@bkmetzler Are you still facing this issue. I was unable to reproduce it on MacOS. I will try to reproduce this on Linux.

**Comment by bkmetzler** [comment] 2017-11-03 14:59
I'm still able to reproduce it.

**Comment by Jas0nch** [comment] 2017-11-10 07:26
I can also reproduce this issue in windows native app(not chrome app).
Here's my issue report.

## App Details:

```
Postman for Windows (native apps not app in chrome app store)
Version: Postman v5.3.2
Windows 10 Enterprise 
```

## Issue Report:
 1. Bugs description:
I have used native app instead of chrome app because of notification in chrome app.
But when I was using formatted json by VS Code as a body of one request, I found unexpected responses like this:
a. 
{
    "Message": "The request is invalid.",
    "ModelState": {
        "settings.IsPeergroupKey": [
            "Unexpected end when reading JSON. Path 'IsPeergroupKey', line 2, position 1071.",
            "Unexpected end when deserializing object. Path 'IsPeergroupKey', line 2, position 1071."
        ]
    }
}
b.
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML>
    <HEAD>
        <TITLE>Bad Request</TITLE>
        <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii">
    </HEAD>
    <BODY>
        <h2>Bad Request - Invalid Verb</h2>
        <hr>
        <p>HTTP Error 400. The request verb is invalid.</p>
    </BODY>
</HTML>
```
When I use unformatted json, it will get the right response. 
So I manually formated json and it also give me unexpected response.
I tried in chrome app and it works well no matter how I formatted my json.

 2. Expected behaviour:
I can use formatted json in my post body, so I can easily change my body.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 N/A

**Comment by blakethepatton** [comment] 2017-11-21 00:17
I can confirm that this isn't working from the pretty view on linux for the desktop app. The dev console(ctrl+shift+i) shows no errors. In Preview mode, I'm unable to even get the right click context menu to show up. Copy pasting seems to work fine in raw though.

**Comment by TheWeirdDev** [comment] 2017-11-25 18:36
I'm having the same issue.
```
Postman for Linux
Version 5.3.2
linux 4.13.12-1-ARCH
```

**Comment by loganhuskins** [comment] 2018-01-05 16:57
Same here. I seem to remember not having this issue always though? Unsure when it started.

```
Postman For Mac
Version 5.5.0
macOS 10.13.2
```

**Comment by shairozan** [comment] 2018-01-06 05:25
Same issue here

```
Postman for Linux
Version 5.5.0
Ubuntu 16.04
```

**Comment by jmoniatte** [comment] 2018-01-29 19:42
Same issue here too
```
Postman for Linux
Version 5.5.0
linux 4.9.0-5-amd64 / x64
```

**Comment by dougmcmillan** [comment] 2018-02-02 09:51
Have reproduced too in 5.5.2 and previously in 5.3.2

Postman for Linux
Version 5.5.2
linux 4.4.0-109-generic / x64

Xubuntu 16.04

Dragging to a new window works, but middle click does not.
Raw is okay but pretty formatting is much more useful of course.

**Comment by ghost** [comment] 2018-02-09 15:48
When will this issue be fixed?

**Comment by jtlindsey** [comment] 2018-02-09 18:09
Same problem
```
Postman for Linux
v5.5.2
Ubuntu 16.04
```

One workaround is using the copy to clipboard UI button on the right, next to the search icon:
![image](https://user-images.githubusercontent.com/7409277/36042685-b9825730-0d9a-11e8-8d0b-2ba63c81e699.png)

Or switch to Raw view and copy

**Comment by sdnts** [comment] 2018-02-23 12:29
Guys, I'm still unable to reproduce this on Mac or on Linux with v5.5.3. I drag selected parts of the pretty JSON response (and the entire thing too), and they were copied to the clipboard with Cmd/Ctrl+C as well as the context menu (prettified). This leaves me very confused.

This is a shot in the dark, but does this only happen to you guys with specific servers? One reason I can think this might happen is the response itself might have newline characters or something.

Can you guys try this on `https://postman-echo.com/get` and let me know what you see?

**Comment by jtlindsey** [comment] 2018-02-23 12:59
@madebysid Do you mean a `GET` request to `https://postman-echo.com/get`? I get no response at all with a `GET` request to `https://postman-echo.com/get` or `https://postman-echo.com`. 

Even running some of the built in request in the `Postman Echo` collection like `GET` DigestAuth Request don't work.

No response with `ping postman-echo.com`

Is postman-echo down?

**Update**: Never-mind, I forgot to change my proxy before doing the test. `GET` request to `https://postman-echo.com/get` yields similar problem. Copy only works in raw view unless using the copy button or CTRL+C. But right click copy does not work.

**Comment by jtlindsey** [comment] 2018-02-23 13:03
Here is a animation showing the lack of copy working on my system and the latest Postman.
![nw1](https://user-images.githubusercontent.com/7409277/36595355-deaa7ac6-186f-11e8-897f-1b597a647729.gif)

**Comment by sdnts** [comment] 2018-02-26 13:02
@jtlindsey Thanks for testing it out on `postman-echo.com`. I tried this on an Ubuntu VM, and I was able to see the behavior you're talking about. The context menu does not seem to work, but Ctrl+C works just fine. I'll get on this!

**Comment by jmoniatte** [comment] 2018-02-26 16:45
@madebysid Thanks for looking into this.

Just tested, and you are right, copying using the context menu does not work, but Ctrl+C does indeed work.

```
Postman for Linux
Version 5.5.0
linux 4.9.0-6-amd64 / x64
```

**Comment by testmonger** [comment] 2018-03-14 14:57
Postman Version 6.0.9 , Macbook Pro o/s ver 10.13.3
None of these work: cmd+c, Edit\Copy, right click Copy
trying to paste into another postman request, or Excel, or VisualStudio.

**Comment by fynnlyte** [comment] 2018-03-28 13:14
```
Postman for Linux
Version 6.0.10
linux 4.13.0-37-generic / x64 (Ubuntu 17.10)
```
cmd + c works for pretty and raw; right-click + copy works for raw but not for pretty.

**Comment by h5tark** [comment] 2018-04-01 13:26
```
Postman for Linux
Version 6.0.10
Distributor ID:	Ubuntu
Description: Ubuntu 16.04.4 LTS
Release: 16.04
Codename: xenial
Linux: 4.13.0-37-generic
```
Ctrl + C works for pretty and raw; right-click + copy works for raw but not for pretty too.

**Comment by mattrixman** [comment] 2018-05-08 22:47
I thought I'd add that wherever `right click, Copy -> CLIPBOARD` is broken, `highlight -> PRIMARY` is also broken.

Typically the `PRIMARY` buffer is where highlighted text goes, and then is pasted from via a middle-click.  It's a separate buffer from `CLIPBOARD`, but the only difference is that it has it's own read/write hooks.

More on this: https://unix.stackexchange.com/questions/139191/whats-the-difference-between-primary-selection-and-clipboard-buffer

**Comment by harryi3t** [comment] 2018-05-15 04:48
Hi everyone,
We have fixed this issue internally and this should be available in the next release 🎉

**Comment by barotashish** [comment] 2018-05-18 10:59
Today I installed Postman on my Ubuntu Linux -- 18.04 

I am not able to copy from output. 
![screenshot from 2018-05-18 16-28-29](https://user-images.githubusercontent.com/21197417/40231389-a11ea53e-5ab8-11e8-8aae-5b5cc17124ad.png)

**Comment by barotashish** [comment] 2018-05-18 11:01
Postman Version - 
cat version 
v1.6.16

My Ubuntu Linux version - 
cat /etc/*rele*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"

==Architecture - 
uname -m
x86_64

**Comment by barotashish** [comment] 2018-05-18 11:02
![screenshot from 2018-05-18 16-32-15](https://user-images.githubusercontent.com/21197417/40231516-10c2c122-5ab9-11e8-8782-960895322bfd.png)

**Comment by harryi3t** [comment] 2018-05-19 03:31
@barotashish The latest version is 6.1.2, it's released yesterday (after your last comment). Can you update to that and try again?

**Comment by juanfestrada** [comment] 2018-05-24 03:23
I getting the same error, I am not able to copy from output, in my HP Envy Windows 10 Home Single, Release 1803

My Postman version is: `You are up to date! Postman v6.1.2 is the latest version.`

**Comment by kennycason** [comment] 2018-05-31 23:09
Mac Sierra 10.12.6
Postman 6.1.3 (also with 6.1.2)
Can also not copy any text from postman. In the "Code" section, "copy to clipboard" also does not work.

**Comment by kennycason** [comment] 2018-06-01 16:03
I just made an interesting discovery. The text does copy, but only within the context of Chrome. I can copy the postman text and then paste it anywhere within Chrome (e.g. a GH gist or jsfiddle). However, when I paste to other apps such as Atom or Slack, it fails. 

In fact, I can't copy any text from Chrome either.

**Comment by kennycason** [comment] 2018-06-01 16:24
I upgraded Chrome and now it works again.

**Comment by harryi3t** [comment] 2018-06-02 15:59
@kennycason If I got it correctly, you are saying upgrading chrome fixed the issue in postman native app? That's weird, postman native app is built on election which should have it's own chrome version.
Any chance you remember the previous chrome version you were using?

**Comment by kletkeman** [comment] 2018-06-08 21:47
The native app does not work on Mac ... copy/paste with the menu is random and deeply frustrating.

**Comment by numaanashraf** [comment] 2018-12-24 11:44
Fixed in latest version of Postman (v6.6+)

**Closed as completed by numaanashraf** 2018-12-24 11:44 UTC
Labels: bug, user-interface

**Comment by sudhirkhanger** [comment] 2019-04-03 10:02
Right-click copy/paste and unix's selection to copy and three-click paste doesn't work on Postman Version 6.7.1

**Comment by mmerbes** [comment] 2019-07-22 19:22
Rick-click copy does not work with Windows Postman v7.3.1. It does not work in Pretty or Raw for JSON responses. Very annoying.

**Comment by SupaMario123** [comment] 2019-07-24 11:03
Having the same issue. 

Postman for Mac
Version 7.3.4

I dont have the Problem always. Sometimes copy paste works. Very strange.
