### ISSUE TITLE
Greater max horizontal size for sidebar

### ISSUE THREAD

**Issue by luismoramedina** [a85/POSTMan-Chrome-Extension#10633] opened 2022-02-04 12:35 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

In the postman api client, now, you can drag the line between left sidebar and the main content to do greater the left side bar, but it has a limit (¿1/4 of the screen?). This limit makes difficult to find requests in folders when the request name is long...

### Describe the solution you'd like

A greater limit will be perfect

### Describe alternatives you've considered

A secret option to set the max limit for those users that need it

**Comment by DannyDainton** [comment] 2022-02-04 12:50
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/10566

**Closed as completed by DannyDainton** 2022-02-04 12:50 UTC
Labels: feature, duplicate
