### ISSUE TITLE
If a subfolder is moved out of its parent, it cannot be moved back in

### ISSUE THREAD

**Issue by JessePelton** [a85/POSTMan-Chrome-Extension#7374] opened 2019-09-23 18:27 UTC
**Description**
If a subfolder is moved out of its parent, it cannot be moved back in.

**Steps To Reproduce**
1. Create a new collection.
2. Create a folder named "Parent".
3. Create a child of "Parent" named "Child".
4. Drag Child out of Parent.
Then realize that you didn't really intend to do that...
5. Attempt to drag Child back into Parent.

**Expected behavior**
Child moves inside Parent when dropped there.

**Actual behavior**
Child remains a sibling of Parent. At most, the folder order in the collection is updated.

**App information**
 - native
 - version 7.7.3
 - Windows 10 Enterprise version 1903 build 18362.356

**Comment by Ghusar** [comment] 2019-09-23 19:01
@JessePelton I am trying to reproduce this issue but not able to.

![Hnet-image](https://user-images.githubusercontent.com/15612246/65455123-3479bc80-de64-11e9-8b82-6d12f1b2f607.gif)

**Comment by JessePelton** [comment] 2019-09-23 19:16
Are there some logs or something that I can send to help chase down the problem? It's 100% reproducible on my machine, and I have no way of knowing how to get it to go away. "Works for me" unfortunately doesn't make it work for me.

**Comment by preethammavin** [comment] 2019-09-24 03:34
@JessePelton can you write to us at help@getpostman.com from you registered email id, along with logs which you will find in view-> developer -> logs. If you can zip it and send it across would be help us debug the situation better.  

If possible a screen recording would also help.

**Comment by JessePelton** [comment] 2019-09-24 13:10
Zipped screen recording attached.
[Postman 2019-09-24 07-27-30.zip](https://github.com/postmanlabs/postman-app-support/files/3647333/Postman.2019-09-24.07-27-30.zip)

**Comment by saswatds** [comment] 2020-03-13 06:29
Hi @JessePelton We are still not able to reproduce this issue on our end. Can check the latest version of postman app, confirm that it's still happening.

**Comment by JessePelton** [comment] 2020-03-13 12:04
The problem still occurs.

Your query prompted me to try again to find a pattern for success and failure, and I've gotten closer. A child folder can reliably be moved out of the parent (becoming a sib) and then moved back into a parent only if the parent is closed (not expanded) for the second move.

**Sometimes passes, mostly fails**

1. Create and open a new collection.
2. Create a folder named "Parent".
3. Create a child of "Parent" named "Child".
4. Open Parent.
5. Drag Child out of Parent to the root of the collection, making it a sib of Parent.
6. Leave Parent open.
7. Attempt to drag Child back into Parent.

**Consistently passes**

1. Create and open a new collection.
2. Create a folder named "Parent".
3. Create a child of "Parent" named "Child".
4. Open Parent.
5. Drag Child out of Parent to the root of the collection, making it a sib of Parent.
6. Close Parent.
7. Attempt to drag Child back into Parent.

The only differences between the two cases are step 6 and the result. If Parent is closed in step 6, the result is always a successful move. If it's open, the move fails most of the time.

**Comment by saswatds** [comment] 2020-03-14 16:00
@JessePelton Thanks a lot for the steps. I was able to reproduce this issue. We will make sure this scenario is fixed.

**Comment by DannyDainton** [comment] 2020-08-24 08:38
Closing this issue as it has now been resolved in version: 7.23

Please feel free to reopen with the steps to reproduce if the issue persists.

**Closed as completed by DannyDainton** 2020-08-24 08:38 UTC
Labels: bug, product/runtime
