### ISSUE TITLE
Cannot open Postman extension for Vs Code 

### ISSUE THREAD

**Issue by LiviuSilion1414** [a85/POSTMan-Chrome-Extension#12321] opened 2023-09-15 12:31 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I was trying to open the Postman extension for Vs Code when this error message appeared:

Error loading webview: 
Error: Could not register service worker: InvalidStateError: 
Failed to register a ServiceWorker: The document is in an invalid state..

### Steps To Reproduce

After installing Postman extension, I used for a few days regularly then suddenly it stopped working.

### Screenshots or Videos

https://github.com/postmanlabs/postman-app-support/assets/65337043/83c14315-ab07-4003-8699-cb53606361f1

### Operating System

Windows 11 Home Version: 10.0.22621 Build: 22621

### Postman Version

Postman Vs Code Extension  Version: 0.8.0

### Postman Platform

Other

### User Account Type

Signed In User

### Additional Context?

EDIT: After reloading Vs Code several times, the problem seems to be solved.

**Comment by pankajk07** [comment] 2023-09-15 12:51
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/12306

**Closed as completed by pankajk07** 2023-09-15 12:51 UTC
Labels: duplicate, vscode
