### ISSUE TITLE
UI doesn't scale on ubuntu

### ISSUE THREAD

**Issue by gszeszko** [a85/POSTMan-Chrome-Extension#1237] opened 2015-07-10 12:48 UTC
It appears that UI doesn't scale properly on ubuntu.  Changing Preferences -> Settings -> UI Size has no effect.  The GUI graphics are stack in a huge mode.
![screenshot from 2015-07-10 07 47 59](https://cloud.githubusercontent.com/assets/1662654/8618906/0bff9236-26d8-11e5-88f7-5e0904ed15ad.png)

**Comment by ppc52776** [comment] 2015-07-10 17:24
I have the same problem, too.

**Comment by alexmherrmann** [comment] 2015-07-10 21:40
Works for me... but
I have to fiddle with the "scale for menu and title bars" a little bit when I switch between 1080P and 4K mode (and vice versa) on my laptop, and usually shut down chrome _completely_ before It returns to normal.
![selection_060](https://cloud.githubusercontent.com/assets/9485711/8629601/d0aea7b6-2719-11e5-86a9-640eca5789be.png)

**Comment by abhijitkane** [comment] 2015-07-11 09:04
@czardoz Can you try to reproduce this?

**Comment by czardoz** [comment] 2015-07-11 09:23
I was not able to reproduce this. Here's what I get with all the screen sizes (for all the sizes, the app window was maximized).

Smallest:
![smallest](https://cloud.githubusercontent.com/assets/3726484/8633239/3de18214-27dc-11e5-9661-ba60e7109615.png)

Smaller:
![smaller](https://cloud.githubusercontent.com/assets/3726484/8633242/48f4da02-27dc-11e5-802b-e09adda52433.png)

Default:
![default](https://cloud.githubusercontent.com/assets/3726484/8633244/52848ee6-27dc-11e5-8a46-cfc97c55e89b.png)

Bigger:
![bigger](https://cloud.githubusercontent.com/assets/3726484/8633246/5c17bbea-27dc-11e5-93b8-9b6c4659645f.png)

I'm using Google Chrome, `43.0.2357.132 (64-bit)`.

**Comment by ghost** [comment] 2015-08-30 00:46
I'm seeing the same problem, Windows 10.
Chrome version Version 44.0.2403.125 m (64-bit)

Smallest (Rebooting the app each time):
![image](https://cloud.githubusercontent.com/assets/1232245/9565180/7948030e-4e75-11e5-90af-d3a8d6ee9a5e.png)

Smaller:
![image](https://cloud.githubusercontent.com/assets/1232245/9565183/99f97efc-4e75-11e5-91c7-9b703b970ac2.png)

Default:
![image](https://cloud.githubusercontent.com/assets/1232245/9565189/b3fc1274-4e75-11e5-9321-32d30ea87bc0.png)

Bigger:
![image](https://cloud.githubusercontent.com/assets/1232245/9565193/cec28070-4e75-11e5-8a91-664fdcd86a5e.png)

**Comment by numaanashraf** [comment] 2016-03-23 09:05
@gszeszko Fixed in versions 4.0 and above

**Closed as completed by numaanashraf** 2016-03-23 09:05 UTC
Labels: bug
