### ISSUE TITLE
Application doesn't Open 6.7.3 - Windows 10

### ISSUE THREAD

**Issue by addzep** [a85/POSTMan-Chrome-Extension#5936] opened 2019-02-18 06:02 UTC
**Describe the bug**
Postman installs within 5 seconds, with and without "Run as Administrator" option, I tried many times the application doesn't open as well as it doesn't show any error. I tried reinstalling many times, I find the folder in AppData/Local/Postman, so it seems that it installs successfully,but doesn't create Start folder or desktop icon etc . Further, I also tried to install Canary version also, but the application doesn't open.
There are no logs in AppData/Roaming/Postman/logs.

**To Reproduce**
1. Download 64-bit version of Postman  (Windows)
2. Install
3. Doesn't open

**Expected behavior**
Should start Postman, like earlier. 

**App information (please complete the following information):**
 - App Type: Native App 
 - Postman Version 6.7.3, 6.7.2, Canary (latest)
 - OS: Windows 10 Pro - 64-bit - 1803

**Comment by numaanashraf** [comment] 2019-02-18 12:29
Thanks for reporting this @addzep. We are tracking this at a related issue #5681. Please follow that issue for updates.

**Comment by numaanashraf** [comment] 2019-02-18 12:29
Duplicate of #5681

**Closed as completed by numaanashraf** 2019-02-18 12:29 UTC
Labels: duplicate
