### ISSUE TITLE
IntelliSense mechanism would be useful while coding

### ISSUE THREAD

**Issue by abala1980** [a85/POSTMan-Chrome-Extension#6725] opened 2019-06-17 13:14 UTC
As a newbie native Postman User I would like to have IntelliSense mechanism while I am typing the code snippet in order to learn available functions more quickly and use features effectively.

Currently I can find the predefined code snippet and choose it but it is a way less effective way of programming in Postman than it could be especially for newbies which do not know yet the available options or syntax.

I would like to get some tips from the Postman which function or variable I am able to use in current context to simply speed up my work and learning.

**Comment by numaanashraf** [comment] 2019-06-17 14:09
Thanks @abala1980. We are tracking this issue at #3919 - we'll be posting updates there.

**Comment by numaanashraf** [comment] 2019-06-17 14:09
Duplicate of #3919

**Closed as completed by numaanashraf** 2019-06-17 14:09 UTC

**Comment by abala1980** [comment] 2019-06-17 20:59
Thank you I knew it is a greate idea worth to be considered and implemented. Keeping fingers crossed over. Good luck @numaanashraf !
