### ISSUE TITLE
When attempting to save a request to a collection, there is no way for the user to know which collection is the original or the forked version.

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#5863] opened 2019-01-31 11:59 UTC
**Describe the bug**
When attempting to save a request to a collection, there is no way for the user to know which collection is the original or the forked version.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a collection "Regression"
2. Create a fork from that collection
![image](https://user-images.githubusercontent.com/9334128/52052381-10bcdb80-254e-11e9-9a92-be8a03f4b4db.png)
3. Create a new request
4. Attempt to Save the request
5. At the bottom of the "Save Request" window, you will see two collections called "Regression"
6. Notice the user has no way of knowing which is the original and which is the forked collection.
![image](https://user-images.githubusercontent.com/9334128/52052480-714c1880-254e-11e9-9f19-935e06af47e6.png)

**Expected behavior**
It should show the fork name similar to the Collection window on the left-hand side

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: Version 6.7.2
 - OS: Windows 10

**Additional context**

**Comment by SamvelRaja** [comment] 2019-02-01 06:27
Duplicate of #5760

**Closed as completed by SamvelRaja** 2019-02-01 06:27 UTC
