### ISSUE TITLE
URL Param not being replaced

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#4983] opened 2018-08-07 10:24 UTC
I have a URL that looks like https://www.example.com/:page.html and the params list recognizes the "page" parameter and asks for a value for it, but when I send the request, it doesn't replace :page with the value that was set.

I'm on Postman v6.2.3. This was not an issue on the previous version I had (which was probably a few versions back, but I don't remember which it was).

**Comment by codenirvana** [comment] 2018-08-07 10:43
Duplicate of #2427

**Closed as completed** 2018-08-08 06:48 UTC
