### ISSUE TITLE
Getting Black Window When StartUp ( Version 7.2.0)

### ISSUE THREAD

**Issue by rammesaran** [a85/POSTMan-Chrome-Extension#6866] opened 2019-07-07 11:05 UTC
**Describe the bug**

I Have installed the recent version ( 7.2.0) - Once it gets installed i am getting blank Screen Noting is seen.

**To Reproduce**
1. Install the recent version ( 7.2.0) or ( 7.2.2)
2. After installation is completed - launch Postman.

**Expected behavior**
App Gets Launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/45402258/60767355-85371000-a0d4-11e9-88a3-20e4eae2999d.png)

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [e.g. 7.2.0]
 - OS: [e.g. Windows 8]

**Additional context**
 I Also tried to uninstall and reinstall for more than 2 times.

**Comment by preethammavin** [comment] 2019-07-09 17:09
@rammesaran can you try the steps detailed in the following thread https://github.com/postmanlabs/postman-app-support/issues/4594

and let us know if it solves the issue

**Comment by kamalaknn** [comment] 2019-11-11 05:56
Duplicate of #7078 

@rammesaran I'm closing this as a duplicate. Please follow the original issue for more updates.

**Closed as completed by kamalaknn** 2019-11-11 05:56 UTC
Labels: installation
