### ISSUE TITLE
Team Administrators unable to invite users

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5849] opened 2019-01-29 19:54 UTC
**Describe the bug**
Team administrators are unable to invite users via the web dashboard

**To Reproduce**
1. Go to the [Teams page](https://go.postman.co/team) 
2. Click on `Invite Users`
3. Enter an email address

**Expected behavior**
Administrators should be able to invite team members via the self-serve flow.

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/51936235-569e6600-23cd-11e9-8352-4b868acf804f.png)

**Additional context**
[Filed by Postman]

**Comment by preethammavin** [comment] 2019-03-04 23:41
@chrisdeso can you write to us at help@getpostman.com with team details, as I am unable to reproduce this issue.

**Comment by abhijitkane** [comment] 2019-03-06 23:03
@preethammavin User-reported bugs need to be on github and open till they're verified fixed by the OP. Most bugs won't be reproducible till the underlying conditions are known, and we'll internally move all user-facing bugs to github. Reopening for further investigation.

**Comment by abhijitkane** [comment] 2019-03-06 23:04
@chrisdeso Can you add more details (user/team ID) to the linked JIRA ticket?

**Comment by preethammavin** [comment] 2019-04-08 09:06
@abhijitpostman @chrisdeso closing the issue , as we were unable to reproduce and the issues linked with the github issue do not have information to triage it.

**Closed as completed by preethammavin** 2019-04-08 09:06 UTC
Labels: bug, product/dashboard
