### ISSUE TITLE
Data lost in Postman for Linux Version 6.0.10

### ISSUE THREAD

**Issue by TheDavidJohnson** [a85/POSTMan-Chrome-Extension#5001] opened 2018-08-09 21:04 UTC
## App Details:
```
Postman for Linux
Version 6.0.10
linux 4.15.0-30-generic / x64
```

## Issue Report:

A few days ago I launched Postman for Linux for the first time in a few months. I clicked the button to update, but didn't install anything. My data was there in the app, but I had to set aside the project and closed the app.

Today, I opened Postman again and all my data is gone. I've looked through other support requests and can't seem to figure out where to look for lost data.

From the console log:

```
requester.js:41967 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41967
requester.js:560528 Check that entitites shown here should only be personal entites
componentWillMount @ requester.js:560528
requester.js:370141 error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (file:///opt/Postman/resources/app/js/requester.js:75519:26)
    at EventEmitter.102.EventEmitter.emit (file:///opt/Postman/resources/app/js/common.js:17109:17)
    at _dispatch (file:///opt/Postman/resources/app/js/common.js:24502:14)
    at EventEmitter.<anonymous> (file:///opt/Postman/resources/app/js/common.js:24512:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
requester.js:41967 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41967
requester.js:41967 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41967
```

**Comment by SamvelRaja** [comment] 2018-08-10 04:33
@TheDavidJohnson  
Few clarifications to help you better and fast.
1. Did you update the app from 5.x version?
2. When you opened 6.0.10 you had the data before?
3. Postman store data in ~./config folder, if that is removed in anytime, the data would be lost.
4. Also, recommend you to share the logs from View -> Developer -> Show Devetools (Shared)
     - Share the console logs and also
     - In devtools -> Applications -> IndexedDb -> Is there any tables inside **postman** database.

**Comment by TheDavidJohnson** [comment] 2018-08-10 11:30
Thanks, @SamvelRaja 

> 
    1. Did you update the app from 5.x version?
    2. When you opened 6.0.10 you had the data before?
    3. Postman store data in ~./config folder, if that is removed in anytime, the data would be lost.
    4. Also, recommend you to share the logs from View -> Developer -> Show Devetools (Shared)
        - Share the console logs and also
        - In devtools -> Applications -> IndexedDb -> Is there any tables inside postman database.


1. No. Version 6.0.10 was the first and only installed version.
2. Yes. The data was there just a few days ago, even though I hadn't opened the software for several months.
3. Excellent. I made several backups of that folder yesterday when I discovered the problem. The folder has always been intact, however.
4. Logs are below

```
shared.js:265253 Initializing the global config
shared.js:327942 Initializing settings
shared.js:265537 Booting waterline models
shared.js:265603 Object "Successful ORM initialization"
shared.js:347825 Migration bailed out due to: FRESH_INSTALL
(anonymous) @ shared.js:347825
shared.js:338609 create socket bailed sync disabled
```

Here's what I see under View -> Developer -> Show Devtools (Shared) -> Application -> IndexedDB

![image](https://user-images.githubusercontent.com/1313680/43955665-39d82686-9c6f-11e8-96ea-b1178fc7e490.png)

I  very much appreciate any help or advice you're able to provide! Thanks again!

**Comment by TheDavidJohnson** [comment] 2018-08-13 12:21
@SamvelRaja After digging around further and reading additional support requests here, I looked in these tables: 

- collections
- folders
- requests

They are all empty.

**Comment by TheDavidJohnson** [comment] 2018-08-15 17:02
Sorry to be a pest, but do you have any thoughts about this, @SamvelRaja ?

**Comment by SamvelRaja** [comment] 2018-08-20 10:15
@TheDavidJohnson  
Sorry for late reply and I have been trying to reproduce it.
We won't do any kind of data migration in the current version. 
Could you try replacing one of your back of ~./config/Postman folder?

**Comment by TheDavidJohnson** [comment] 2018-08-23 16:56
@SamvelRaja Apologies for any confusion: the backups of the ~./config/Postman folder were created after the issue arose, about the time I opened this ticket. I'll try restoring one, but since it is substantially identical to what's in the "live" folder, I don't expect any difference.

Is there somewhere in the file system that I should be looking?

Thanks

**Comment by TheDavidJohnson** [comment] 2018-08-23 18:53
In case this is useful for troubleshooting, I attempted an upgrade to the latest version of Postman for Linux (6.2.5 from the [downloads page](https://www.getpostman.com/apps) ) today. After the upgrade, the app failed to launch properly, and here's what I saw in the logs:

```
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App events bus { data: 
   { adapterMethodName: 'find',
     cause: 
      { adapterMethodName: 'find',
        modelIdentity: 'workspacesession',
        name: 'AdapterError',
        raw: [Object] },
     isOperational: true,
     modelIdentity: 'workspacesession',
     raw: 
      { _e: {},
        _stack: 'OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing\n    at Transaction.create (file:///opt/Postman/app/resources/app/js/vendor-shared.js:122645:31)\n    at tempTransaction (file:///opt/Postman/app/resources/app/js/vendor-shared.js:121601:23)\n    at Table.getTransaction (file:///opt/Postman/app/resources/app/js/vendor-shared.js:122097:17)\n    at Table.getIDBObjectStore (file:///opt/Postman/app/resources/app/js/vendor-shared.js:122106:25)\n    at Collection._read (file:///opt/Postman/app/resources/app/js/vendor-shared.js:123244:31)\n    at Collection.each (file:///opt/Postman/app/resources/app/js/vendor-shared.js:123275:29)\n    at Object.find (file:///opt/Postman/app/resources/app/js/vendor-shared.js:184463:10)\n    at _getPopulatedRecords (file:///opt/Postman/app/resources/app/js/vendor-shared.js:111297:21)\n    at helpFind (file:///opt/Postman/app/resources/app/js/vendor-shared.js:111734:6)\n    at _afterPotentiallyRunningBeforeLC (file:///opt/Postman/app/resources/app/js/vendor-shared.js:178343:9)\n    at _maybeRunBeforeLC (file:///opt/Postman/app/resources/app/js/vendor-shared.js:178317:16)\n    at Deferred._.extend._WLModel [as _handleExec] (file:///opt/Postman/app/resources/app/js/vendor-shared.js:178319:9)\n    at Deferred.exec (file:///opt/Postman/app/resources/app/js/vendor-shared.js:149698:10)\n    at promisified (file:///opt/Postman/app/resources/app/js/vendor-shared.js:154502:16)',
        inner: [Object],
        message: 'UpgradeError Dexie specification of currently installed DB version is missing',
        name: 'OpenFailedError' } },
  name: 'booted',
  namespace: 'requester' }
App updater event { name: 'checkForElectronUpdate', namespace: 'app-update' }
```
I still have backups of the version I had been running (version 6.0.10) as well as the data folders [mentioned previously](#issuecomment-415490897) in the event that the info above might help me find the data I lost. Thanks!

**Comment by SamvelRaja** [comment] 2018-09-11 08:40
Related to https://github.com/postmanlabs/postman-app-support/issues/4897

**Comment by kamalaknn** [comment] 2019-04-02 05:31
@TheDavidJohnson This looks like a duplicate of #4476 

Closing this. Please follow the linked thread for updates.

**Closed as completed by kamalaknn** 2019-04-02 05:31 UTC
Labels: bug, launch
