### ISSUE TITLE
Postman_ExecutionStub.exe Digital Signature Missing  (Postman-win64-8.12.0-full)

### ISSUE THREAD

**Issue by aconcato** [a85/POSTMan-Chrome-Extension#10272] opened 2021-09-02 11:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman_ExecutionStub.exe Digital Signature Missing 

Applocker is blocking the app to run

### Steps To Reproduce

Run the application

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/32514373/131832343-42c99f99-d5d8-4d5c-8e04-361ecbe7ae70.png)

### Environment Information

```markdown
- Operating System: Windows
- Platform Type: Native App
- Postman Version: 8.12.0
```

**Comment by twitharshil** [comment] 2022-01-06 13:46
@aconcato Thanks for reporting !! The issue is fixed in recent versions of the Postman application. Closing the GitHub ticket. In case you face the issue again, feel free to re-open the ticket

**Closed as completed by twitharshil** 2022-01-06 13:46 UTC
Labels: bug, updates, product/client-foundation
