### ISSUE TITLE
Postman snaps are out of date.

### ISSUE THREAD

**Issue by arpitbatra123** [a85/POSTMan-Chrome-Extension#6888] opened 2019-07-10 08:46 UTC
All Versions of Postman snaps on https://snapcraft.io/postman are out of date.

![Screenshot 2019-07-10 at 2 06 21 PM](https://user-images.githubusercontent.com/21967563/60954745-24e6df00-a31d-11e9-8478-0c81011a5b33.png)

**Comment by Spurlos** [comment] 2019-07-22 15:31
Jumping on to bump up this issue. Please try to update your snap repos adequately. This is an official distribution channel from you, not a Beta of internal, so please treat it nice, or close it and delete, as it's not fulfilling its job on distributing latest versions to those who prefer Snap packages.

**Comment by seantcanavan** [comment] 2019-08-19 22:20
**Describe the bug**
Ubuntu software's version of Postman is 6.7.1. This is incompatible with the breaking changes added to syncing in 7.0.0.

Also, the message regarding the breaking change and requiring the user to update to 7.0.0 contains instructions that are impossible as there is no "Update" section in the anywhere in the settings pane in the 6.7.1 version deployed to the Ubuntu Software center.

**To Reproduce**
Steps to reproduce the behavior:
1. Install Postman from the Ubuntu Software center
2. Try to follow the "Upgrade" directions header at the top of the app
3. Fail and be sad
4. Be unable to sync your data from Postman 7.0.0+ on your macOS machine

**Expected behavior**
The version on the Ubuntu software center should be kept up to date or it should be pulled. Leaving it on the software store out of date is only going to confuse newbies who are switching over to Linux from macOS or Windows and have 7.0.0+ installed there.

**App information (please complete the following information):**
 - Native App
 - 6.7.1
 - OS: Ubuntu 18.04.1

**Additional context**
Thank you for supporting Postman on Linux!

**Comment by mike-echo-oscar-whiskey** [comment] 2019-09-06 06:43
Any news on this?

**Comment by harryi3t** [comment] 2019-09-11 15:09
@youfoundkris Please use the `candidate` channel for now to get the latest updates.
We will update the thread on our plans to roll out the latest updates on the stable channel.

**Comment by harryi3t** [comment] 2019-10-04 07:03
For teams on Postman v6 to get the latest update, they must first migrate their team to  Postman v7
Here's the documentation on how/why to do the migration: https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/migrating_to_v7/

That being said, since not all teams have migrated to Postman v7, we have not yet rolled out Postman v7 on the `latest/stable` channel.
We are working on an alternative to creating a new release track for Postman v6 named `v6`, so that we can move the non-migrated teams to `v6/stable` channel and roll out the latest updates the `latest/stable` channel.

We have already requested snap to create this release track
Request Ticket: https://forum.snapcraft.io/t/track-request-v6-for-postman/13425/4

For the time being the latest updates are available on the `latest/candidate` channel.

**Comment by seantcanavan** [comment] 2019-10-08 15:46
So `latest/stable` will turn into `v6/stable`? Which channel will change to `latest/stable` after that? Will the change be automatic or require uninstalling / reinstalling from the updated channel?

**Comment by numaanashraf** [comment] 2019-10-14 10:01
@seantcanavan `latest/stable` will have the Postman v7.x version after we perform this migration. For users who would like to stay in Postman v6.x (which is a very small number) can switch to `v6/stable` manually after the migration.

**Comment by harryi3t** [comment] 2019-10-23 07:04
We have released Postman v7 on the "latest/stable" channel. All users will get this update automatically.
You can force the update by running
```shell
sudo snap refresh postman
```

### How this might affect you
- You don't have to do anything if any of the following is true
  - you have not installed Postman from Snap
  - you haven't signed-in to Postman
  - your Postman account does not belong to a team
  - your team has already migrated to Postman v7

- If you are an admin of your team and see the following modal, you would have to Migrate your team to Postman v7 to use the latest update. 
![image](https://user-images.githubusercontent.com/5207331/67275740-df6fab80-f4e0-11e9-82cc-30aaa162a28b.png)
- If you are not an admin, you can either ask your admin to migrate the team or you can go back to Postman v6.
![image](https://user-images.githubusercontent.com/5207331/67276036-78062b80-f4e1-11e9-9677-944a2ba9b54a.png)
Clicking on the `Download v6` would take you to the documentation page describing how to switch the channel to `v6/stable` to get Postman v6

**Closed as completed** 2019-10-23 09:10 UTC
Labels: bug, distribution

**Comment by Aleks-Ya** [comment] 2021-02-28 06:30
The same problem with v7 and v8:
Direct downloading from Postman web-site - v8.0.6
Snap version ("latest/stable") - 7.36.5 ("snap refresh" was done)
Could you publish new releases to Snap without long delays?

**Comment by nshiell** [comment] 2021-04-30 16:15
Snap was out of date, I just installed the tar.gz as a workaround
