### ISSUE TITLE
Per request proxy setting

### ISSUE THREAD

**Issue by centfox** [a85/POSTMan-Chrome-Extension#11309] opened 2022-09-30 07:15 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

In Postman, there is a global setting to enable proxy. But we need a proxy only for specific endpoints to run test scripts.

### Describe the solution you'd like

Please provide a feature to enable proxy for individual requests.

**Comment by DannyDainton** [comment] 2022-09-30 07:28
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/11265

**Closed as completed by DannyDainton** 2022-09-30 07:28 UTC
Labels: feature
