### ISSUE TITLE
Hope that environment variables can be associated with collections

### ISSUE THREAD

**Issue by xutl** [a85/POSTMan-Chrome-Extension#3654] opened 2017-10-19 03:17 UTC
I hope that the environment variable can be associated with the set, so that you can set a custom environment variable for each collection, in the development environment, pre-environment, and online environment can easily switch a unified URL constant

**Comment by xutl** [comment] 2017-10-19 03:18
It is possible to set an environment that belongs only to the collection

**Comment by deepakpathania-zz** [comment] 2017-10-19 08:28
Duplicate of #2876. 
Follow #3205 for the roadmap. 
Read about managing environments here https://www.getpostman.com/docs/postman/environments_and_globals/manage_environments

**Comment by cauvery-guda-eb** [comment] 2017-11-01 19:46
Looking forward for this change, badly need this.

**Comment by prashantagarwal** [comment] 2017-12-10 06:12
Closing this as duplicate of #2876

**Closed as completed by prashantagarwal** 2017-12-10 06:12 UTC
Labels: pending-close
