### ISSUE TITLE
Second Instance of Postman Desktop loads forever(It seems)

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2953] opened 2017-04-18 10:00 UTC
1. Postman Version: **v4.10.7**
 2. App (Chrome app or Mac app): **Desktop App**
 3. OS details: **Windows 10**
 4. Is the Interceptor on and enabled in the app: **Yes**
 5. Did you encounter this recently, or has this bug always been there: **This is the first time I have tried this.**
 6. Expected behaviour: **I expect second instance become ready for use or warn me(showing an error) that postman cannot run more than one instance simultaneously.**
![postman2](https://cloud.githubusercontent.com/assets/7044707/25125263/70cfb42e-2443-11e7-973d-d06c1f9b14ee.png)

 8. Screenshots: **Attached**

Steps to reproduce the problem:**Run first instance of Postman desktop. After complete loading run the second one.**

**Comment by ghost** [comment] 2017-04-18 10:16
I should mention that running an instance of chrome app simultaneously with desktop app has no problem, works fine.

**Comment by SamvelRaja** [comment] 2017-09-06 09:50
duplicate of #/2177

**Closed as completed by SamvelRaja** 2017-09-06 09:50 UTC
Labels: bug
