### ISSUE TITLE
Postman 7.3.4 color of JSON response is wrong

### ISSUE THREAD

**Issue by evser** [a85/POSTMan-Chrome-Extension#7026] opened 2019-07-30 13:36 UTC
After updating to 7.3.4 I see that colors in response have changed.
Re-installing of the application does not help. I have cleaned ../AppData/Postman as well.

Please refer to the screenshot below for the details:
![image](https://user-images.githubusercontent.com/11527468/62133805-1ec69b80-b2e8-11e9-973e-7a7bbbb94b2f.png)

**Comment by saswatds** [comment] 2019-07-30 20:38
Hi @evser We have updated only the response viewer to Monaco editor internally for gaining performance advantage. The change in color of the editor is because of the new-editor and is intended. Will be propagating it to all other editors in the app in the upcoming releases.

Closing this issue now as this is not a bug.

**Closed as completed by saswatds** 2019-07-30 20:38 UTC

**Comment by evser** [comment] 2019-07-31 08:03
@saswatds but these colors are horrible! :( I can not believe that **colors** impact performance...

**Comment by saswatds** [comment] 2019-08-01 04:44
Hi @evser the colors do not impact performance, the underlying editor stack was the problem. When we changed the editor, as a side-effect the color also changed.

Perception of color being horrible is very subjective when some people love it and some people hate it. We can never make a color scheme that everyone loves. 
In the future, we may have the ability to let the users select their own scheme but no promises.

Thanks for your feedback.

**Comment by evser** [comment] 2019-08-01 08:16
So, as you said it is a side effect... I mean that I am with Postman _**since it was created**_, but this color-change makes me disappointed... The worst update since the beginning, sorry.
