### ISSUE TITLE
Invalid handling of double quotes in CSV since 7.2.2 update

### ISSUE THREAD

**Issue by 1BigDug** [a85/POSTMan-Chrome-Extension#6830] opened 2019-07-02 13:58 UTC
When trying to use collection runner with a file that has embedded double quotes, Postman reports an error Invalid Closing Quote: got """ at line 3 instead of delimiter...

To resolve the error, you have to replace the correctly escaped double quote format (2 double quotes in a row) with backslash quote (\"). This is not valid CSV format that can be used anywhere else, so you have to manually update your CSV files with a text editor to convert them to "Postman CSV" format.

**Comment by codenirvana** [comment] 2019-07-02 15:08
@1BigDug Thanks for reporting this. We are aware of this issue and tracking it here: #6764

As mentioned in https://github.com/postmanlabs/postman-app-support/issues/6764#issuecomment-506313128, this issue is fixed in our [Canary channel](https://www.getpostman.com/downloads/canary) and will be fixed in our stable channel (v7.3.0) very soon!

Closing as duplicate of #6764

**Closed as completed by codenirvana** 2019-07-02 15:08 UTC
Labels: data-file/csv, duplicate, product/runtime
