### ISSUE TITLE
Cursor mismatch in text editor

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#4477] opened 2018-04-20 09:20 UTC
originally reported via tweet - https://twitter.com/desidalek/status/987252394324086784

**Comment by parth115** [comment] 2018-04-20 09:31
Postman : 6.0.10-1
Kernel : 4.14.34-1
i3wm : 4.15.0.1

Running on Manjaro Linux, postman installed from aur https://aur.archlinux.org/packages/postman/

Infinality patched fontconfig https://aur.archlinux.org/packages/fontconfig-infinality-ultimate

**Comment by prashantagarwal** [comment] 2018-06-29 11:21
Duplicate of #2985

**Closed as completed by prashantagarwal** 2018-06-29 11:21 UTC
Labels: bug
