### ISSUE TITLE
Collection Runner - Multi Iteration Scroll Issue

### ISSUE THREAD

**Issue by DannyDainton** [a85/POSTMan-Chrome-Extension#6980] opened 2019-07-23 09:57 UTC
**Describe the bug**
Running more than a single iteration via the Collection Runner causes the scrolling action, in the Results section, to _jump up_ to the first iteration.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Collection Runner
2. You can use the `Postman Echo` Collection for the run
3. Select more than a single iteration (3 will be fine)
4. Start the Collection run
5. In the Result Section, scroll down to the last Iteration or use the numbered Iteration icons on the right side of the screen.

**Expected behaviour**

Be able to scroll or view any part of the Results without being automatically sent to the top of the screen.

**Screenshots**

![Multi_Iteration_Scroll](https://user-images.githubusercontent.com/17089546/61701582-5658a500-ad36-11e9-90e5-a789a2c82daa.gif)

**App information:**
 - App Type Native App
 - Postman Version 7.3.4
 - OS: macOS Mojave 10.14.5 (18F203

**Additional context**

This was first raised on the Postman Community site:

https://community.getpostman.com/t/collection-runner-results-screen-scroll-bug/6570

**Comment by youqingz** [comment] 2019-07-24 06:20
Same issue here.
Windows 10 64 bit
Postman Version 7.3.4

**Comment by 8Peter8** [comment] 2019-07-25 17:47
Exactly the same issue here on Postman V7.3.4 under Win10. It would be good if it was possible to go down to a previous release until the problem is fixed as this problem causes significant impact to Collection Runner.

**Comment by unisev** [comment] 2019-07-26 15:44
Same issue, I really like a rollback or something to unblock me.

PostMan v7.3.5
Windows 7 - 32 bits

**Comment by kaustavdm** [comment] 2019-07-30 08:50
Also, reported on the [community forum](https://community.getpostman.com/t/collection-runner-multi-iteration-scrolling-issue/6861).

**Comment by unisev** [comment] 2019-08-06 13:40
In my case, it happends only after an empty response (0 byte)

**Comment by saswatds** [comment] 2019-08-17 09:25
Hello everyone, we have been able to reproduce this issue and are trying to find out the root-cause for this problem. Fix will be underway soon.

**Comment by ravitejapendyala** [comment] 2019-08-20 08:21
Hi this issue is very frustrating,  hard to debug the iteration payload as the scroll option is not working. Will this be fixed in the next update?

**Comment by DannyDainton** [comment] 2019-08-20 10:04
As a workaround, you could use Newman and run the Collection, Environment, any other files through that from the command line.

There are different cli options and reporters available to present the data in any way you would like. 

https://github.com/postmanlabs/newman

**Comment by Dangerunicorn** [comment] 2019-08-20 21:03
I am also running into this issue and it's making it difficult for me to troubleshoot the failed tests in iterations 3+. Windows 10. Postman v7.5.0

**Comment by codenirvana** [comment] 2019-09-02 11:19
Hey, Everyone 👋
We've pushed a fix for this on `7.6.0`. Please update your app and confirm if that fixes your issue?

**Comment by Dangerunicorn** [comment] 2019-09-05 21:05
Issue is fixed on my end!

**Closed as completed** 2019-09-06 04:12 UTC
Labels: bug, collection-runner, product/runtime

**Comment by juanmoyano1** [comment] 2019-09-09 14:27
Issue is fixed on `7.6.0`
