### ISSUE TITLE
Call stack size exceeded when generating collection from GraphQL schema

### ISSUE THREAD

**Issue by bachi76** [a85/POSTMan-Chrome-Extension#11028] opened 2022-06-21 18:28 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The issue described in https://github.com/postmanlabs/postman-app-support/issues/10266 (Closed) appeared again. Kindly refer to 10266 for details how to reproduce.

Here's the used GraphQL schema: [schema.zip](https://github.com/postmanlabs/postman-app-support/files/8951667/schema.zip)
(generated by Pimcore Datahub)

 

### Steps To Reproduce

Add API
Define using the attached schema
Generate Collection From Schema
Test the API -> Generate Collection

### Screenshots or Videos

![Auswahl_335](https://user-images.githubusercontent.com/1873207/174871965-214b89c2-6166-46e7-9bb1-f81c5fa2de7d.png)

### Operating System

Linux

### Postman Version

9.19.0

### Postman Platform

Postman App

**Comment by timbochamp** [comment] 2022-06-23 17:57
Going to group this as a duplicate of #10717 where I believe the fix should address both. We can re-open if that's not the case

**Closed as completed by timbochamp** 2022-06-23 17:57 UTC
