### ISSUE TITLE
Load external JS in pre-request script

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#2189] opened 2016-07-21 15:30 UTC
I am new to postman testing. I am currently trying to load an external script that I wrote to pull some db data as part of pre-request script. The script is:

var express = require('express');
var app = express();
app.get('/', function (req, res) {  
    var sql = require("mssql");
    // config for your database
    var config = {
        user: 'xxxx',
        password: 'xxxx',
        server: 'xxx.xx.xx.xx', 
        database: 'xxxxxxxx', 
        port: xxxx
    };
    // connect to your database
    sql.connect(config, function (err) {
        if (err) console.log(err);
        // create Request object
        var request = new sql.Request();
        // query to the database and get the records
        request.query('SELECT \* FROM xxxxx', function (err, recordset) {
            if (err) console.log(err)
            // send records as a response
            res.send(recordset);  
        });
    });
});
var server = app.listen(5000, function () {
    console.log('Server is running..');
});

I have tried to add this through $.getScript ('myScript') way and through adding the script as an environment variable but its throwing an error. Any help will be much appreciated!

Version/App Information:
-->
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Chrome
3. OS details: Windows 7 professional
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Its not a default feature
6. Expected behaviour: Import the external JS scripts successfully
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

Error: Cannot find module 'express'
    at s (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/request-snippet-generator.js:1:156)
    at s (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/request-snippet-generator.js:1:122)
    at eval (eval at loadCustomFile (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/tester/Evaluator.js:238:39), <anonymous>:1:27)
    at eval (eval at loadCustomFile (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/tester/Evaluator.js:238:39), <anonymous>:40:3)
    at r.loadCustomFile (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/tester/Evaluator.js:238:34)
    at chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/tester/Evaluator.js:215:25

STEPS:
1. Add the above script as a pre-request script
2. In the Test tab do:
   $.getScript('Path_to_myscript');
## 
1. Add the script as a global environment variable
2. In the Test tab do:
   eval(postman.getGlobalVariable('Path_to_myscript'));

**Comment by abhijitkane** [comment] 2016-07-21 19:12
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/1180

**Closed as completed by abhijitkane** 2016-07-21 19:12 UTC
