### ISSUE TITLE
Disabling the cookie jar for 1 requests, disables it for subsequent requests

### ISSUE THREAD

**Issue by jtonneyck** [a85/POSTMan-Chrome-Extension#8293] opened 2020-04-07 23:05 UTC
**Describe the bug**
Switching"Disable cookie jar" to ON for a request should disable the cookie jar for that request only. However, in the runner all subsequent requests also seem to have the cookies disabled. The bug isn't triggered when the requests are executed manually. It seems to be a problem of the runner.

**To Reproduce**
1. Create new collection.
2. Create  a request to an endpoint that has a set-cookie in the response header.
3. Create another request to some other endpoint on the same domain.
4. Create another request to some other endpoint on the same domain. Disable the cookie jar for this request in settings.
5. Create another request to some other endpoint on the same domain. This should have the cookie jar enabled.
6. Run the collection and save the response. You'll see that the cookie for the request made in step 5 is not set.

**Expected behavior**
I'm expecting that switching"Disable cookie jar" to on only disables cookies for that particular request, but in the runner it disables cookies for all subsequent requests.

**App information (please complete the following information):**
 - App Native App
 - Postman Version  v7.21.2 and v7.21.1
- OS: macOs Catalina and windows 10 (latest updates).

I've created a collection that demonstrates the bug: https://www.getpostman.com/collections/93ebb73ec3928df0fe96

**Comment by vikiCoder** [comment] 2020-04-08 05:28
Duplicate of: https://github.com/postmanlabs/newman/issues/2292

**Closed as completed** 2020-05-26 08:40 UTC
Labels: bug, product/runtime

**Comment by codenirvana** [comment] 2020-05-26 08:43
@Piepongwong This issue is fixed in the latest version of the Postman app.
