### ISSUE TITLE
Authorization header not cleared on selecting "No auth"

### ISSUE THREAD

**Issue by r0ssing** [a85/POSTMan-Chrome-Extension#2911] opened 2017-04-06 13:35 UTC
Hello,

If I choose another method than "No auth", e.g. Basic Auth, in Postman and presses "Send" and then  change back to "No auth", I notice that Postman has not removed the authorization header in the "Headers" section (ie. there is still a header with "Authorization" and various values, depending on what value was selected. Sometimes the value for "Authorization" even becomes "application/json"?!). 

 1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Win server, x63
 4. Is the Interceptor on and enabled in the app: disabled
 5. Did you encounter this recently, or has this bug always been there: ?
 6. Expected behaviour: Postman should remove the authorization header when No auth is selected

Steps to reproduce the Postman problem:

1. Create a GET request that doesn't require auth. and hit SEND
2. Change auth type to Basic Auth and hit SEND
3. Change auth to No auth and hit SEND
4. Observe the "Authorization" header under the tab Headers

I believe the issue has some connection with Collection Runner and newman also failing to use the correct authorization when "No auth" has been selected. (I have created a separate issue on the newman github page).

Best regards,
Emil

**Comment by kamalaknn** [comment] 2017-08-28 09:30
Closing this as a duplicate of #2045. Please follow the parent thread for updates.

Thanks.

**Closed as completed by kamalaknn** 2017-08-28 09:30 UTC
Labels: bug
