### ISSUE TITLE
Postman 4.3.3- Moving requests around-----does not work---need urgent solution

### ISSUE THREAD

**Issue by rbawachkar610** [a85/POSTMan-Chrome-Extension#2142] opened 2016-06-21 10:59 UTC
Moving requests around

You can transfer requests to any other folder or collection in the sidebar. Just drag-and-drop the request to a collection, or any of its child folders. 

**This functionality does not work. I am not able to transfer requests anywhere.
needs urgent solution ....pls**

**Comment by rbawachkar610** [comment] 2016-06-21 11:03
Is there something like, 32bit machine problem ?
it was working previously....but suddenly it stops working to transfer

**Comment by rbawachkar610** [comment] 2016-06-21 11:09
is there any setting for this ? 
is this Postman's version issue ?

**Comment by abhijitkane** [comment] 2016-06-21 11:11
@rbawachkar610 This seems to occur after you drag-and-drop a file into the app (for importing). A restart of the app should fix this. We're working on fixing the root cause of the problem.

**Comment by rbawachkar610** [comment] 2016-06-21 11:59
ah....yes restarting the app is workaround.
Thanks

**Comment by abhijitkane** [comment] 2016-06-21 13:12
@rbawachkar610 You can also resize the app window a tiny amount. We've figured out a permanent fix - this will go out in the next release.

**Comment by abhijitkane** [comment] 2016-07-06 10:54
@rbawachkar610 This has been fixed in v4.4.2 of the app (Chrome only). Can you update (https://www.getpostman.com/docs/updating) and check?

**Closed as completed** 2016-07-11 07:36 UTC
