### ISSUE TITLE
Postman Standalone app prevents switching focus to Chrome in OSX Yosemite

### ISSUE THREAD

**Issue by ryanoboril** [a85/POSTMan-Chrome-Extension#1009] opened 2015-04-14 18:34 UTC
I decided to use the standalone version of Postman so that it would be easier to switch (command-tab) between a Chrome tab and the Postman app.  However, when I have Postman running, if i try to command-tab from any other application to Chrome, it switches to Postman.  The only way to bring Chrome back up is to minimize Postman.  This is very disruptive of my workflow and I don't know why Postman seems to "hide" Chrome but that's what's happening for me.  I have the latest versions of Chrome and Postman running on OSX Yosemite v10.10.2.  Is there anything that can be done about this?  Is anyone else bothered by this (does anyone still use command-tab to switch apps in OSX?)

**Comment by deepredsky** [comment] 2015-04-17 15:41
I am also facing the same problem. To bring focus back to Chrome, i have to additionally press Cmd + ~ or miniminize Postman like you do. Hopefully this will be fixed soon

+1

**Comment by petemod** [comment] 2015-06-26 03:55
+1
This issue is not Yosemite specific, I can confirm it occurs on OSX Lion 10.7 as well.

**Comment by sobtiankit** [comment] 2015-06-26 04:21
I agree with the annoyance, however, this is a limitation of the Chrome App platform and something we have no control over. All chrome packaged apps behave this way.

**Comment by a85** [comment] 2015-07-16 23:07
Would request users to post here so that the Chrome team can escalate the severity of the issue: https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=window%20switching%20cr%3DPlatform-Apps&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=504650

**Comment by a85** [comment] 2015-07-20 21:23
This seems to be a deep problem with the Chrome app platform. Details here: https://code.google.com/p/chromium/issues/detail?id=308382

**Comment by a85** [comment] 2015-12-11 22:47
We have a Mac app out now people that solves these issues once and for all. Get it here: https://www.getpostman.com/apps

**Closed as completed** 2015-12-29 10:52 UTC
Labels: platform/chrome

**Comment by arunrdd** [comment] 2016-11-09 15:38
I was surprised to see the issue even after installing the postman mac app. I use Cmd-Space to lookup and launch applications and it suggests the installed chrome postman app first. I had to delete the chrome app to make it disappear from mac quick lookup suggestions.

**Comment by sdnts** [comment] 2016-11-09 15:48
@arunkreddy OSX's Spotlight works based on how much you use an app (among other factors). We do not have control over where (the order) the app appears. I'm thinking you have been using the Chrome App a lot more, so it ranks higher.

**Comment by arunrdd** [comment] 2016-11-10 11:52
@madebysid just thought sharing this might save some time for anyone facing the same issue, not expecting any solution from you guys :)

**Comment by LaZyLiOn-arch** [comment] 2018-10-04 07:32
Just uninstall postman and download other file for postman and install it on mac. This works for me
