### ISSUE TITLE
Large numbers in CSV rounded in Runner

### ISSUE THREAD

**Issue by manhActivePOS** [a85/POSTMan-Chrome-Extension#6798] opened 2019-06-27 23:07 UTC
**Description**

_Regression Issue_ When importing a .csv file for use in Runner, large numbers are being rounded and are no longer being preserved.  This is a script that I run weekly and this issue has appeared this week (I believe after 7.2.2 code drop... see [GitHub #3178] - Updated internal CSV parser to fix bugs with data files parsing in runner).  It appears to be a JS limitation as anything greater than Number.MAX_SAFE_INTEGER is being rounded.

**To Reproduce**
1.  Create request containing a variable for runner use {{PK}}
2.  Create .csv file with number values for said variable {{PK}} greater than 9007199254740991.
3.  Launch Runner

4.  Select created request
5.  Import created .csv
6.  Attempt to run or select "Preview"

**Expected behavior**
Numbers will remain preserved and not be rounded

**Screenshots**
![2019-06-27 19_05_14-Postman](https://user-images.githubusercontent.com/52300573/60306590-ba8e7180-990e-11e9-9cc7-91cf55af6f4b.png)
![2019-06-27 19_04_02-Collection Runner](https://user-images.githubusercontent.com/52300573/60306591-bbbf9e80-990e-11e9-8bfc-7ac95dc5030a.png)
![2019-06-27 19_08_18-_C__Users_jscherer_Desktop_ejCleanup csv - Notepad++](https://user-images.githubusercontent.com/52300573/60306658-080ade80-990f-11e9-906a-6ea1b0a72f37.png)

**App information**
 - App Type: Native App
 - Postman Version: 7.2.2
 - OS:  Windows 10

**Additional context**
This was working with previous versions.   [GitHub #3178] may be a good place to start.

**Comment by vikiCoder** [comment] 2019-06-28 08:00
Hi @manhActivePOS 

You are right, we convert numbers without quotes in CSV file into JavaScript Number while parsing the CSV file in the Postman App. As a result, some numbers are changed because of the limitations related to how big number can be stored in JavaScript (learn more about it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#Properties)).

If you want to keep very large numbers or numbers with leading zeros as it is, you can specify them as a string in CSV file by wrapping the number in double quotes like below:
```
index,specialNumber
1,"000001"
2,"9223372036854775807"
```

Number wrapped in quotes like this will be parsed as a string instead of JavaScript Number, so it will solve your problem.

**Comment by shamasis** [comment] 2019-06-30 14:41
Closing this as a close duplicate of https://github.com/postmanlabs/postman-app-support/issues/6746

When we add options to auto convert numbers to string, it would be easier to achieve what @vikiCoder suggested.

**Closed as completed by shamasis** 2019-06-30 14:41 UTC
Labels: feature, bug, data-file/csv, duplicate, product/runtime
