### ISSUE TITLE
Response json formatter

### ISSUE THREAD

**Issue by Scorpio-nan** [a85/POSTMan-Chrome-Extension#13307] opened 2024-12-01 11:34 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

response body json formatter.

### Describe the solution you'd like

the response body, when pretty = json, is not work pritter;
![json-formatter](https://github.com/user-attachments/assets/d60fd271-e9ec-4b86-8fa9-9856b79c78d2)

**Comment by Perdolique** [comment] 2024-12-02 10:47
Probably duplicate of #13230

**Comment by pankajk07** [comment] 2024-12-05 04:26
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/13230

**Closed as completed by pankajk07** 2024-12-05 04:26 UTC
Labels: bug, vscode
