### ISSUE TITLE
Postman v5.5.0 cannot send HEAD request

### ISSUE THREAD

**Issue by kalinchih** [a85/POSTMan-Chrome-Extension#4003] opened 2017-12-25 07:00 UTC
## App Details:

```
Postman for Windows
Version 5.5.0
win32 6.1.7601 / x64
```

## Issue Report:
Cannot send HEAD request. 
Always display Loading...

**Comment by sdnts** [comment] 2017-12-26 11:36
@kalinchih, I'm unable to reproduce this. Can you check your server logs to make sure the request is received there and handled correctly? I'm closing this, but please let me know if this needs to be reopened.

**Closed as completed by sdnts** 2017-12-26 11:36 UTC
Labels: support

**Comment by kalinchih** [comment] 2017-12-27 13:23
@madebysid  , thanks for your reply.
When I use chrome extension, the head method works. Server also has the access log.

But the latest PC version does not work on head method. (Before I update, head works. After update, the head method doesn’t work).

**Comment by kalinchih** [comment] 2017-12-29 01:48
@madebysid ,

I find a workaround to fix this issue.
The steps are:

1. uninstall Postman PC
2. delete {user}/AppData/Local/Postman folder
3. delete {user}/AppData/Roaming/Postman
4. reinstall Postman PC 5.5.0


So I think there is a bug in the upgrade scripts.

thanks,
Kalin

**Comment by freeranger** [comment] 2018-02-22 12:41
I get this problem too - PC version hangs as described, chrome extension does not
@madebysid can you re-open and fix for the next version?

**Comment by nordvall** [comment] 2018-02-28 13:11
I also got this problem with a saved GET request that I've using for about a month. When I later implemented HEAD on the server side and flipped the request metod to HEAD in Postman, the request just hang forever.
Issuing HEAD requests from other clients to the same URL worked fine. 

My simple workaround was to start a new request tab in Postman. Then it worked immediately. 
Sounds like some local cache corruption to me, since also @kalinchih got it working by clearing the cache folders.

**Comment by freeranger** [comment] 2018-02-28 13:16
I did the uninstall/delete folders/reinstall thing and it has worked fine ever since.
