### ISSUE TITLE
Import from (file->import) do not work.

### ISSUE THREAD

**Issue by Lincimary** [a85/POSTMan-Chrome-Extension#9621] opened 2021-02-17 06:54 UTC
**Describe the Issue**
When I import a file to my application from File<import works for the first time and then does nothing over the second attempt.
The short-cut key (cmd+o) also did not work. 

**Steps to Reproduce**
1.Open the postman app
2.Try to import file from File<import without not using the import button.
3.Pop-up for import files open for the first time, close and try re-opening from File<import does not work

** Attaching the screen record for reference**

https://user-images.githubusercontent.com/76947097/108166107-b6354e80-7119-11eb-861c-d2b228a96c64.mp4

**Environment Information**
 - Platform Type: Native Desktop App
 - Postman Version: 8.0.5
 - Operating System: Mac OS

**Comment by DannyDainton** [comment] 2021-02-17 07:14
Closing as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9528

**Closed as completed** 2021-02-17 07:14 UTC
Labels: duplicate
