### ISSUE TITLE
Add Breadcrumb like navigation to Documentation in Postman Desktop Version

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#8050] opened 2020-02-12 14:21 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the navigation for a request needs to be checked from the folder hierarchy.

**Describe the solution you'd like**
I think it would be nice to have breadcrumb-like navigation in the Documentation part for Postman Desktop. Right now it is allowed to have a hierarchical documentation structure, where common information about a group of requests is written either in the collection or in a sub-folder containing the requests. What is not possible is, a way to easily navigate through these hierarchical documentation structures. This can could be achieved by introducing a small breadcrumb on top where the Documentation is shown.

For example, in the image below, I have tried to visualize how this would look. Using the breadcrumb we could easily go to the hierarchical documentation of "MyRequest" written in SubFolder1 or SubFolder2 and even to the documentation describing the entire collection.

![Breadcrumb](https://user-images.githubusercontent.com/47771757/74257306-a58a1580-4d1a-11ea-91d9-8eba3f6edd44.png)

**Additional context**
_Community request_

**Comment by Raja-Simha** [comment] 2020-02-13 09:50
Very valid concern @Raj-postman We will see how we can fit this into our roadmap

**Comment by vkaegis** [comment] 2020-02-17 08:39
Duplicate of #8006, tracking all requests around collection references/breadcrumbs there, so closing this.

**Closed as completed by vkaegis** 2020-02-17 08:39 UTC
Labels: feature, product/documentation
