### ISSUE TITLE
There was an error in evaluating the Pre-request Script:  TypeError: btoa is not a function

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#3120] opened 2017-06-06 10:03 UTC
1. Postman Version:  4.10.7
 2. App (Chrome app or Mac app): Mac app
 3. OS details: OS X 16.6.0 / x64
 4. Is the Interceptor on and enabled in the app: n/a
 5. Did you encounter this recently, or has this bug always been there: i got this issue since last update
 6. Expected behaviour: as version before.  it was working.
 8. Screenshots (if applicable)

![image](https://cloud.githubusercontent.com/assets/20908050/26823963/d27163fc-4aaf-11e7-9a2e-f404767fd311.png)

I'm getting the error in the Subject while using the btoa method in the pre-request script.

It was working since the version before my last update!!

**Comment by numaanashraf** [comment] 2017-06-06 10:21
@gornialberto Could you send us a screenshot of the error?

**Comment by sdnts** [comment] 2017-06-12 11:31
Hi @gornialberto We were unable to reproduce this on v5.0.0. I've attached a screenshot showing that this works on the native Mac app.
I'm closing this, but please reopen if you're still seeing this.

![screenshot 2017-06-12 17 04 24](https://user-images.githubusercontent.com/7689783/27032188-37aaa874-4f91-11e7-839d-18da18df8b34.png)

**Closed as completed by sdnts** 2017-06-12 11:31 UTC

**Comment by sainejob** [comment] 2017-07-11 23:34
I'm seeing this in: 
Postman for Chrome
Version 5.0.2
OS X / x86-64
Chrome 59.0.3071.115

![screen shot 2017-07-11 at 4 34 11 pm](https://user-images.githubusercontent.com/377227/28095359-ce7ae210-6656-11e7-8cf5-b81894b53694.png)


It works fine in Postman for Mac:

Repro Steps: 
1) Go to: https://documenter.getpostman.com/view/2374336/broken-pre-request-script/6fYUinS
2) Click '> Run in Postman' > 'Open With... Postman for Chrome' 
3) Click 'Send'
You should see the error above in the screenshot

**Comment by sainejob** [comment] 2017-07-12 17:25
@madebysid - Should I open a new ticket?  I have no way to re-open this.

**Comment by sdnts** [comment] 2017-07-17 07:39
Hi @sainejob You don't need to require cryptoJS to use it, it is already available as a global. [Docs](https://www.getpostman.com/docs/postman/scripts/postman_sandbox)

If you still can't get it to work, I'll reopen this.

**Comment by SeunJay** [comment] 2019-05-29 00:01
![image](https://user-images.githubusercontent.com/47621880/58519849-2fa24600-81ad-11e9-8e49-2f9efda57fe2.png)

**Comment by SeunJay** [comment] 2019-05-29 00:04
Hi...i am trying to make a post request using Postman but i have been getting the error shown below. How do i fix this bug? Thanks in anticipation.

![image](https://user-images.githubusercontent.com/47621880/58519988-a6d7da00-81ad-11e9-95fa-a7d347fe7861.png)

**Comment by benbendemo** [comment] 2019-08-02 06:42
Postman Version: 7.3.5
App (Chrome extension or Native app):Native app
OS: MacOS Mojave 10.14.5 (18F132)

<img width="795" alt="image" src="https://user-images.githubusercontent.com/4705587/62349750-38a7ee80-b533-11e9-9a8e-6546ba50c7b7.png">

<img width="844" alt="image" src="https://user-images.githubusercontent.com/4705587/62349766-48273780-b533-11e9-905c-489121b190c3.png">

I've tried all kinds of crypto-js method in postman, it returns "TypeError: crypto.createHmac is not a function " all the time, could you help to figure this?

**Comment by benbendemo** [comment] 2019-08-02 06:43
@madebysid @numaanashraf

**Comment by saswatds** [comment] 2019-08-02 07:18
Hi @benbendemo 
The crypto library available inside sandbox is https://code.google.com/archive/p/crypto-js/

Can you try `var res = CryptoJS.HmacSHA1("Message", "Secret Passphrase");` instead ?

**Comment by benbendemo** [comment] 2019-08-06 08:11
it works, thank you very much. @saswatds
