### ISSUE TITLE
Custom domain: document URL returns status 500, can't publish anything else to it

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6530] opened 2019-05-16 22:14 UTC
**Describe the bug**
User receives the following error when attempting to publish to a custom domain:

`Someone else on your team has already published a documentation with this domain. Ask them to un-publish their documentation before publishing yours.`

There is currently a Collection published to the custom domain, but attempting to access it by direct URL returns a status 500 error. Collection _may_ have been owned by a previous team member.

**To Reproduce**
1. Attempt to publish to affected custom domain
2. Receive error noted above
3. Attempt to access Collection still published to custom domain
4. Receive status 500 error

**Expected behavior**
- Error message points to the Collection currently published at the domain in question

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.1.0
 - OS: Windows

**Additional context**
_Suggested improvements:_
Allow team admins (or other role) to unlink published Collections from a custom domain by, without needing to un-published the specific Collection in question. i.e., option to purge a custom domain.

**Comment by Cazaimi** [comment] 2019-08-26 04:52
@JP-from-Postman , This was resolved internally. @Raja-Simha , please mark this as closed.

**Comment by mjang** [comment] 2019-08-27 18:26
What was the resolution? I do not see any option to unpublish a collection created by a different "team admin"

**Comment by Cazaimi** [comment] 2019-08-30 11:40
@mjang , please refer https://github.com/postmanlabs/postman-app-support/issues/6421. If that still does not solve your problem, please post the documentation's public URL on this thread, or (re)open the corresponding support ticket [here](https://www.getpostman.com/support)

**Comment by Raja-Simha** [comment] 2020-02-18 05:42
Duplicate of #6421

**Closed as completed by Raja-Simha** 2020-02-18 05:42 UTC
Labels: bug, product/documentation
