### ISSUE TITLE
Allow to hide only sidebar tabs, not all of sidebar

### ISSUE THREAD

**Issue by andersjj** [a85/POSTMan-Chrome-Extension#9551] opened 2021-02-04 22:25 UTC
right now when toggling the sidebar, the sidebar tabs as well as the tab content is toggled.

It would be valuable to be able to toggle the sidebar tabs as well as the content independently.   I use Postman collections a lot and it would be nice to hide the sidebar tabs, but still be able to view the tab content, in my case, the collections that have been setup.

Granted, the tabs only occupy a relatively small amount of space, but based on how the UI was before, seems like a step backwards.

Would be great to be able to toggle the sidebar tabs themselves, and the tab content separately.  then if you want to switch between collections and some other tab, you'd need to unhide the tabs, select a different tab and then re-hide the tabs with the appropriate content visible.

**Comment by DannyDainton** [comment] 2021-02-04 23:09
Closing as this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9498

**Closed as completed by DannyDainton** 2021-02-04 23:09 UTC
Labels: duplicate
