### ISSUE TITLE
JSON stringify does not create compatible query parameter with new URL processor

### ISSUE THREAD

**Issue by svangils** [a85/POSTMan-Chrome-Extension#8874] opened 2020-08-03 09:06 UTC
**Describe the bug**
We have a legacy postman collection that communicates with AWS SQS service. We send a JSON message body as query parameter that is composed in a pre-request Script. This message body should be JSON and offcourse be url encoded. This worked with the 'old' url processor.

The output of the JSON.stringify() method is like this `{"Message":"{\"event\":{}"}}`. But the '\' doesn't get encoded like before. 

With the old url processor, the url would look something like this: 
`https://sqs.eu-west-1.amazonaws.com?Action=SendMessage&MessageBody=%7B%22Message%22:%22%7B%5C%22event%5C%22:%7B%7D%22%7D%7D`

With the new processor it looks like this:
`https://sqs.eu-west-1.amazonaws.com/240842184392/dd_dev_smd_fi_bingel.fifo?Action=SendMessage&MessageBody={%22Message%22:%22{\%22event\%22:{}%22}}`

**Expected behavior**
A JSON stringified query parameter should be encoded correctly. Is there a way to do this with the new url processor or not?

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 2.29.1
 - OS: Mac OS Catalina (10.15.5)

**Comment by codenirvana** [comment] 2020-08-03 09:12
@svangils Please refer https://github.com/postmanlabs/postman-app-support/issues/8808#issuecomment-662212275 for more details.

**Comment by codenirvana** [comment] 2020-08-03 18:32
Duplicate of #8808

**Closed as completed by codenirvana** 2020-08-03 18:32 UTC
Labels: duplicate, product/runtime
