### ISSUE TITLE
API example not syncing request body to cloud

### ISSUE THREAD

**Issue by realjay007** [a85/POSTMan-Chrome-Extension#4550] opened 2018-05-11 09:07 UTC
I ran a request in a collection by changing some request body values and removing some fields. I then went ahead to save it as an example using the "Save response" button.
However when viewing on the web, I noticed that the example request body does not match that in the postman program. It used the values from the main request.

Postman example request body

![postman](https://user-images.githubusercontent.com/22660815/39916589-ca7ceb04-5502-11e8-8d4c-f87ede69a4e3.png)

Example request body on postman web docs

![postman2](https://user-images.githubusercontent.com/22660815/39916615-e2f085ba-5502-11e8-8917-268cca854521.png)

**Comment by ankit-m** [comment] 2018-05-11 12:07
Hey @realjay007,

I am able to reproduce this issue and investigating it. I will update this thread once we have a fix.

**Comment by ghost** [comment] 2018-07-10 19:29
+1 Still the same. Requests not syncing with docs sometimes

**Comment by VDI-Tech-Guy** [comment] 2018-08-29 12:24
+1 having the same issue as well,  noticed its coming from when i upload POST the body sometimes isn't being transferred from the source over to the Cloud and thus not making it over to other synchronized desktops.   

Post seems to not sync body data
Patch does sync body data

My current workspace has a mix of ones that do work and do not, i will say that the ones that are having the issue were copied/pasted then changed that seem to have the body transfer issues, and POSTs that were added new seem to work fine.

To explain better, what i would do is create a statement get/post/patch --> Duplicate --> rename and replace the body/part of the address and those cloned entries seem to have issues with syncing body.

**Comment by jzombie** [comment] 2019-02-27 23:13
I am experiencing this same issue, and it's nearly a year old.

Has anyone made a React app that can replace Postman, by any chance?  Seems like a good weekend project, to just implement the basic features, such as full syncing.

**Comment by sujayvenaik** [comment] 2019-04-09 09:05
Hey @darkladder @realjay007 @VDI-Tech-Guy @mrsamirmh 
Can you update to the latest app v7 and check if this issue still persists?
If yes, could you share a screen recording with us so we could debug it better at our end?

This is my original req
![image](https://user-images.githubusercontent.com/11532114/55787571-31685b00-5ad4-11e9-97cd-0d55425f7e25.png)

Example: 
![image](https://user-images.githubusercontent.com/11532114/55787649-64125380-5ad4-11e9-9485-2e86f841065e.png)

Web documentation:
![image](https://user-images.githubusercontent.com/11532114/55787691-78565080-5ad4-11e9-9e77-e6feb5b09e4a.png)

Let me know if i am missing something.

**Comment by sujayvenaik** [comment] 2019-04-23 05:29
Closing this issue due to inactivity. Please feel free to ping here and reopen the thread if anyone finds this on the latest version of the app. Will be glad to help.

**Closed as completed by sujayvenaik** 2019-04-23 05:29 UTC
Labels: bug, sync

**Comment by ntbrierly** [comment] 2019-11-14 17:21
I've been experiencing this on 7.11.  I've tried to reproduce with combinations of Exporting, Importing, etc.  Finally I just turned Syncing off, which was a painful process.
