### ISSUE TITLE
Docs incorrectly state the RAML is supported import format

### ISSUE THREAD

**Issue by jawn** [a85/POSTMan-Chrome-Extension#4190] opened 2018-02-14 13:38 UTC
On https://www.getpostman.com/docs/postman/collections/data_formats, the documentation claims that RAML is a supported input format.

This works with the github RAML example on that page, which starts with #%RAML 0.8.

However, files with #%RAML 1.0 are refused. This is the official version.

The documentation should mention which versions are supported.

Issue to add support for RAML 1.0 version: #1906 

![image](https://user-images.githubusercontent.com/1705112/36206830-0fec130c-1194-11e8-98bb-b7563bed5702.png)

**Comment by harryi3t** [comment] 2018-02-17 09:27
@jawn Thanks for reporting. We will fix the docs.  Support for RAML 1.0 is on the way :)

**Comment by jawn** [comment] 2018-02-26 09:40
Can you clarify support for RAML 1.0 is on the way?
Is this still tracked via #1906?

**Comment by harryi3t** [comment] 2018-02-26 11:21
It's work in progress and yes it's tracked via https://github.com/postmanlabs/postman-app-support/issues/1906

**Comment by numaanashraf** [comment] 2018-08-10 14:03
Duplicate of #1906

**Closed as completed by numaanashraf** 2018-08-10 14:03 UTC
Labels: postman-docs

**Comment by mprice-mule** [comment] 2019-06-08 04:49
Can someone confirm if (or when) Postman will fully support RAML 1.0?
