### ISSUE TITLE
Runner not resolving variable names in Run Results display

### ISSUE THREAD

**Issue by Super-Net-Ops** [a85/POSTMan-Chrome-Extension#8166] opened 2020-03-10 13:05 UTC
**Describe the bug**
In the runner, variable names are not resolved in the Run Results display. 

**To Reproduce**
1. Go to Runner
2. Run a collection containing a request that uses a variable in the URL.
3. For each iteration, variable name will be displayed instead of the value.

**Expected behavior**
Value should be shown instead of var name.

**Screenshots**
![image](https://user-images.githubusercontent.com/60976012/76314733-bdb76b00-62ad-11ea-81a2-4d63233174fb.png)

**App information (please complete the following information):**
 - App Type: native app
 - Postman Version: 7.19.1
 - OS: Windows 10 Enterprise

**Additional context**
Bug was introduced in 7.19.1.

**Comment by saswatds** [comment] 2020-03-24 05:24
Hi @Super-Net-Ops the request row is now shown before the `pre-request scipts` executes which is the most accurate representation. (The request name and request url are supposed to show the authored version and not resolved) 
In that moment of time the URL has still not been resolved as it is possible that the pre-request could modify the variables. 
We have tried fixing all inconsistency in representation of different phases in runner to prevent bugs and performance issue resulting from accumulation and delayed representation of state.
The actual URL that was sent will now be shown in the actual request dropdown
![Screenshot from 2020-03-24 10-53-05](https://user-images.githubusercontent.com/8796447/77391069-cafc4b80-6dbd-11ea-8d30-93324c085904.png)

Closing this issue now as this is the intended behaviour.

**Closed as completed by saswatds** 2020-03-24 05:24 UTC
Labels: product/runtime
