### ISSUE TITLE
 Python requests contains syntax errors in Postman API documentation 

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6152] opened 2019-03-26 06:27 UTC
**Describe the bug**
 Python requests contains syntax errors in Postman documentation (https://docs.api.getpostman.com)

**To Reproduce**
1. Go to https://docs.api.getpostman.com
2. Click on Collections- Get request
3. Select language as "Python Requests
4. Example Request has wrong syntax as below:
    a. allow_redirects is declared twice 
    b. The second declaration has incorrect syntax 'false'. It should have a capital F 
    c. The timeout is undefined.
response = requests.request('POST', url, headers = headers, data = payload, allow_redirects=False, timeout=undefined, allow_redirects=false)

**Expected behavior**
allow_redirects should show once and timeout should be corrected

![Screenshot 2019-03-26 at 11 24 52 AM](https://user-images.githubusercontent.com/41741228/54974462-22ed5000-4fba-11e9-9103-f12de1d7abf7.png)

**Comment by alexprest** [comment] 2019-05-02 17:54
Also when the request is "x-www-form-urlencoded" the encoding of the payload is incorrect:
"/" don't get encoded

**Comment by ashutosh2307** [comment] 2019-06-27 06:42
Have same issue.
If I remove this from request **allow_redirects=False, timeout=undefined, allow_redirects=false**  its works fine. But cant edit in api documentation.

**Comment by sulmanbashir** [comment] 2019-08-13 13:13
Hello,

We meet the same issue with postman documentation. Please can you tell me when this bug should be resolve ? 

Thanks for your reply.
Sulman

**Comment by seelaman** [comment] 2019-09-09 17:38
same issue here, I was planning to use this as our reference documentation but the resulting code is not copy-pastable by our clients so I can't really publish this...

Is there a way to edit the generated documentation before publishing it?

also the files dict (this is for a form-data request) has syntax errors:


import requests
url = 'http://localhost:8080/match
payload = {}
`# incorrect line`
files = {('source': open('/home/seelaman/Workspace/trueface/github/trueface-sdk/master/trueface/tests/fixtures/manuel.jpeg','rb'),('target': open('/home/seelaman/Workspace/trueface/github/trueface-sdk/master/trueface/tests/fixtures/SF.png','rb')}
`# correction that works, removed the "(" before source and target.`
files = {'source': open('/home/seelaman/Workspace/trueface/github/trueface-sdk/master/trueface/tests/fixtures/manuel.jpeg','rb'),'target': open('/home/seelaman/Workspace/trueface/github/trueface-sdk/master/trueface/tests/fixtures/SF.png','rb')}

headers = {}
response = requests.request('POST', url, headers = headers, data = payload, files = files, allow_redirects=False, timeout=undefined, allow_redirects=false)
print(response.text)

**Comment by Cazaimi** [comment] 2019-09-12 19:43
@seelaman , we’re currently working on fixing this and should be out shortly. Stay tuned! :)

**Comment by greyraven** [comment] 2019-09-30 15:31
@Cazaimi #DEFINE "Shortly". This bug has been around since March. My boss wants to pull the plug on Postman. Please address "Shortly..." we are "Staying tuned" as you have asked.

**Comment by godfrzero** [comment] 2019-10-01 01:52
@greyraven The bug you're seeing here is actually caused by a 3rd party code generator we're using. Since we don't have control of that generator, we've been stuck with a few bugs in the module. What we're doing right now, and what @Cazaimi is working on, is moving to a new in-house code generator. While this will allow us to fix bugs and add features quickly in the future, it does mean that the initial switch will take time: we don't want to rush this out and end up breaking even more things.

That being said, the current release is in the final stages and it should be out within the next week.

**Comment by Cazaimi** [comment] 2019-10-01 18:57
@greyraven , I'm sorry to hear that and I thank you for the patience. As @godfrzero mentioned, the release should be out within the next week.

**Comment by stcalica** [comment] 2019-10-15 18:07
@Cazaimi Any updates? I have a user waiting on this bug to be fixed.

**Comment by Cazaimi** [comment] 2019-10-16 07:02
@stcalica , this fix should be out on the Web dashboard on the 17th, with the fix on public documentation following a couple of days later.

**Comment by Cazaimi** [comment] 2019-12-09 06:05
@stcalica , the fix is out on the public documentation. Please check it out and let us know. :)

@Raja-Simha, this can be marked as closed.

**Closed as completed** 2020-02-03 06:58 UTC
Labels: bug, product/documentation, product/ops
