### ISSUE TITLE
Documentation Markdown for tables not rendered in Web doc (but correct in Postman app)

### ISSUE THREAD

**Issue by massenz** [a85/POSTMan-Chrome-Extension#4639] opened 2018-06-04 00:00 UTC
**Describe the bug**
It seems that Postman documentation "understands" the table markdown (see attached screenshots) in the app itself; however, in the generated web documentation, this is not rendered correctly.

**To Reproduce**
1. Go to any collection
2. Click on 'Edit'
3. Enter a valid Markdown for a table, such as:
```
Project   |  Sample
--------- | -----------------------
Version   |   0.4.1
Created   |   2018-05-15
Updated   |   2018-05-15
Author    |   M. Massenzio (marco@alertavert.com)
```
4. `Update` and confirm the markdown is valid and the table is generated correctly in the preview
5. Click `View in Web`
6. The generated HTML is just the textual representation, no table rendered.

**Expected behavior**
The generated Web documentation should render correctly tables.

**Screenshots**
Attached

**App information (please complete the following information):**
 - App Type: native
 - Postman Version: 6.1.3
 - OS: Ubuntu 18.04

![View in Postman App](https://user-images.githubusercontent.com/1153951/40892711-7c775fca-674f-11e8-9632-148796d42740.png)

![View in Web](https://user-images.githubusercontent.com/1153951/40892720-8babb630-674f-11e8-96d0-744e25c8e7e4.png)

**Comment by thecuriousdev** [comment] 2018-06-04 10:09
@massenz thanks for reporting this issue. It's bug, I am able to reproduce this. We'll fix this issue in the upcoming release.

**Comment by godfrzero** [comment] 2018-07-03 09:11
@massenz In the meantime, you can get the table rendering correctly by making sure that any block elements (like tables) are surrounded by an empty line. So instead of:

```
Sample API
Project   |  Sample
--------- | -----------------------
Version   |   0.4.1
Created   |   2018-05-15
Updated   |   2018-05-15
Author    |   M. Massenzio (marco@alertavert.com)
```

You could try:
```
Sample API

Project   |  Sample
--------- | -----------------------
Version   |   0.4.1
Created   |   2018-05-15
Updated   |   2018-05-15
Author    |   M. Massenzio (marco@alertavert.com)
```

**Comment by massenz** [comment] 2018-07-03 19:13
I don't see how that would fix the issue.
This is the original markdown:
```
# Sample - API

Project   |  Sample
--------- | -----------------------
Version   |   0.4.1
Created   |   2018-05-15
Updated   |   2018-05-15
Author    |   M. Massenzio (marco@alertavert.com)

Ipse lorem ubuis derat non quorot: sed API non est sputandum.
```
as you can see there are empty lines around the table markdown: as mentioned, this renders fine in Postman itself, but incorrectly in the web presentation.

**Comment by stantond** [comment] 2018-07-06 14:21
@godfrzero unfortunately that doesn't fix this.

```
# Response
<br>

|Response Code|Explanation|
|---|---|
|200 OK Response|AuthToken: string|
|400 Response|No credentials in request body|
|401 Unauthorized Response|Missing, incorrectly formatted or invalid combination of username and password|

```

In Postman app:

![screen shot 2018-07-06 at 15 18 59](https://user-images.githubusercontent.com/3207366/42383789-358fb300-8130-11e8-891f-e794b6615f00.png)

Website:

![screen shot 2018-07-06 at 15 18 50](https://user-images.githubusercontent.com/3207366/42383802-4716999a-8130-11e8-9349-4b812f33863a.png)

**Comment by ethanjcohen** [comment] 2018-07-31 15:23
Any update on this? Tables are a very important feature for documentation.

**Comment by ethanjcohen** [comment] 2018-07-31 15:29
Looks like if I put spaces before and after it renders ok - there's just a lot of space between multiple tables but that works 👍

**Comment by stantond** [comment] 2018-11-08 09:44
This is still broken. Why was the work cancelled?

@ethanjcohen still can't get this working. Where exactly did you put these spaces?

**Comment by chrisdeso** [comment] 2018-11-14 02:51
@ankit-m Friendly bump!

**Comment by godfrzero** [comment] 2018-11-17 01:34
Note: https://github.com/postmanlabs/postman-app-support/issues/3955
Block elements in markdown need to have an empty line before & after. #3955 tracks the correct, expected behavior.

@stantond I tried using the snippet you've posted and it's rendering correctly in both the public and private docs. What do you have in the markdown _after_ the table? Is it broken in both the private and public docs for you?

**Comment by preethammavin** [comment] 2019-03-04 20:35
Closing the thread in reference of #3955

**Closed as completed by preethammavin** 2019-03-04 20:35 UTC
Labels: bug, product/dashboard
