### ISSUE TITLE
Editing the value of a variable via the environment quick look also edits the value of other variables

### ISSUE THREAD

**Issue by antonrabe** [a85/POSTMan-Chrome-Extension#6406] opened 2019-05-02 06:20 UTC
**Describe the bug**
Editing the value of a variable via the environment quick look also edits the value of other variables. 

**To Reproduce**
1. Select an environment with existing variables and values
2. Click on the environment quick look
3. Edit the value of a variable.
4. Press Enter

**Expected behavior**
Only the value of the select variable should be edited.

**Screenshots**
![image](https://user-images.githubusercontent.com/27763721/57058791-62f3d100-6ce4-11e9-896e-63ed8dc5756e.png)

I edited locationCode1 from LON to JFK and pressed enter, and the value of the bookingSourceCode was also edited.
![image](https://user-images.githubusercontent.com/27763721/57058806-71da8380-6ce4-11e9-9453-7f320a09ada5.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Version 7.0.9
 - OS: Windows 10 Enterprise

**Additional context**
--

**Comment by grg-akshay** [comment] 2019-05-02 07:14
@antonrabe  Thank you for raising this issue.
Do you have any variables that are disabled? We are already tracking an [issue](https://github.com/postmanlabs/postman-app-support/issues/6362) where this happens.

**Comment by antonrabe** [comment] 2019-05-02 08:24
@grg-akshay Yes. I have two variables that are disabled.

**Comment by numaanashraf** [comment] 2019-05-03 04:59
Duplicate of #6362

**Closed as completed by numaanashraf** 2019-05-03 04:59 UTC
