### ISSUE TITLE
Team and Personal Workspaces get mixed up on first time login.

### ISSUE THREAD

**Issue by Cazaimi** [a85/POSTMan-Chrome-Extension#5379] opened 2018-10-17 12:04 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Description**
On loging in/signing up in the app (after the associated user data has been deleted/is not present), the personal and team are both displayed in the Team Workspace modal.

**To Reproduce**
You must have a couple of team workspaces and personal workspaces.
1. Sign-in/up
2. Create some team and personal workspaces.
3. Delete user data
4. Log-in again
5. As you see the Syncing logo turning, click on the workspace modal and Team workspaces after that.
6. You will see your personal and team workspaces both present under the Team Workspaces modal.

**Expected behavior**
Ideally, only team workspaces should be displayed under the team workspace modal. 

**Screenshots**
![bug](https://user-images.githubusercontent.com/13660453/47084966-ca5b9f00-d232-11e8-97d4-43cbfe9bdcb0.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Version 6.4.2 (6.4.2)
 - OS: MacOs Mojave Version 10.14

**Comment by kamalaknn** [comment] 2018-10-17 16:06
Duplicate of #4948

**Closed as completed by kamalaknn** 2018-10-17 16:06 UTC
Labels: bug, sync
