### ISSUE TITLE
Weird design issue happening infrequently

### ISSUE THREAD

**Issue by stianlagstad** [a85/POSTMan-Chrome-Extension#2457] opened 2016-11-07 08:09 UTC
1. Postman Version: 4.8.1
 2. App (Chrome app or Mac app): linux 4.4.0-45-generic / x64
 3. OS details: Ubuntu 16.10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: I've seen this a few times before
 6. Expected behaviour: 
 7. Console logs: NA
 8. Screenshots (if applicable): 
![postman-design-issue](https://cloud.githubusercontent.com/assets/4340859/20050450/b502d94a-a4c9-11e6-818f-497709ba2309.png)

Sometimes multiple requests that I open gets stacked on top of each other. When this happens I can't remove them. The only way out of it is to restart the application. I don't know how to reproduce this. It happens maybe about once a week. Has anyone else seen it?

**Comment by numaanashraf** [comment] 2016-11-07 08:13
Thanks for reporting this issue @stianlagstad. We are trying to replicate this at our end. Would it be possible to open Postman's DevTools and give us a screenshot of the console error the next time this happens? Steps to open the DevTools are detailed [here](https://www.getpostman.com/docs/errors).

**Comment by abtiddle** [comment] 2016-11-07 17:50
+1 

Version 4.8.1 (4.8.1)
Mac App
1. Click a request with Saved Responses
2. Click the downward triangle to display list of Saved Responses
3. Click one of the saved responses
   Error: xml.js:22 Uncaught Error Uncaught TypeError: Cannot read property 'split' of undefined file:///Applications/Postman.app/Contents/Resources/app/js/requester.js 79322 25 TypeError: Cannot read property 'split' of undefined(…)
4. Click a different request with Saved Responses
   Error: xml.js:22 Uncaught Error Uncaught TypeError: Cannot read property 'remove' of undefined file:///Applications/Postman.app/Contents/Resources/app/js/common.js 17411 28 TypeError: Cannot read property 'remove' of undefined(…)
5. Click Send button
   Error: xml.js:22 Uncaught Error Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings. file:///Applications/Postman.app/Contents/Resources/app/js/common.js 1029 6 Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.(…)

And request not ever sent.
1. In the tab, click the X to close.
   Error: xml.js:22 Uncaught Error Uncaught TypeError: Cannot read property 'removeEventListener' of null file:///Applications/Postman.app/Contents/Resources/app/js/requester.js 54377 23 TypeError: Cannot read property 'removeEventListener' of null(…)

And multiple request lines now display.
![2016-11-08-saved-responses-display-iossue](https://cloud.githubusercontent.com/assets/9487008/20068983/963dded2-a4cf-11e6-9575-f22cd8d59fe1.png)

![2016-11-08-saved-responses-display-iossue-02](https://cloud.githubusercontent.com/assets/9487008/20069068/e6f6f4f8-a4cf-11e6-90c6-9b74fa139f16.png)

**Comment by sdnts** [comment] 2016-11-08 10:40
@abtiddle We've reproduced the issue you pointed out, and will include a fix in the coming releases.
@stianlagstad Was your issue also caused by these series of steps?

**Comment by stianlagstad** [comment] 2016-11-10 08:18
I've not been able to reproduce the issue, @madebysid, but I'm sure it was _not_ caused by the same series of steps as with @abtiddle. I'll comment here if I discover how it happens.

**Comment by SamvelRaja** [comment] 2016-11-16 07:25
@abtiddle @stianlagstad We pushed a fix for this in our 4.8.3 version of the app, can you guys check the same from your end?

**Comment by SamvelRaja** [comment] 2016-11-22 07:54
@stianlagstad  @abtiddle  Closing this right now. Feel free to reopen if you guys get this again.

**Closed as completed by SamvelRaja** 2016-11-22 07:54 UTC
