### ISSUE TITLE
Unable to use ordinary user startup program！

### ISSUE THREAD

**Issue by adinlead** [a85/POSTMan-Chrome-Extension#6430] opened 2019-05-07 09:55 UTC
Can use root start it！ 
System:Deepin 15.10（Linux）
Error Info：
`
adinlead@adonis:~$ /usr/local/src/Postman/Postman 
1557222814070 main info "Booting Postman 7.0.9, linux-4.15.0-30deepin-generic on x64"
1557222814071 main info "EventBus~initialize - Success"
1557222814079 main info "UpdateHandler~init - Success"
1557222814080 main info "RuntimeExecutionService~initialized: Success"
1557222814082 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1557222814089 main info "ProtocolHandler~init - Success with status: false]"
1557222814098 main info "PluginHost~bootHost: Booted - 1"
1557222814254 main info "Bootstrap-models~bootstrap - Success"
1557222814364 pluginHost info "Booting Plugin Host for Postman 7.0.9, linux-4.15.0-30deepin-generic on x64"
1557222814367 pluginHost info "PluginsHost: Booted"
1557222814370 pluginHost info "not exist",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/adinlead/.config/Postman/plugins/postman.openApi/version.json","name":"Error","message":"ENOENT: no such file or directory, open '/home/adinlead/.config/Postman/plugins/postman.openApi/version.json'","stack":"Error: ENOENT: no such file or directory, open '/home/adinlead/.config/Postman/plugins/postman.openApi/version.json'"}
1557222814370 pluginHost info "PluginInstallationService~installOrUpdatePlugins Installing plugin",{"version":"0.0.10","pluginId":"postman.openApi","isInstalled":false}
1557222814371 pluginHost info "PluginInstallationService~installFromLocal",{"pluginZipPath":"/usr/local/src/Postman/app/resources/app/plugins/postman.openApi.zip","pluginsDir":"/home/adinlead/.config/Postman/plugins","currVersionDirPath":"/home/adinlead/.config/Postman/plugins/postman.openApi/0.0.10","tempDir":"/tmp","result":{"pluginId":"postman.openApi","version":"0.0.10","status":null}}
1557222814371 pluginHost info "PluginInstallationService~installFromLocal extracting"
1557222814372 pluginHost info "not exist",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/adinlead/.config/Postman/plugins/postman.sample/version.json","name":"Error","message":"ENOENT: no such file or directory, open '/home/adinlead/.config/Postman/plugins/postman.sample/version.json'","stack":"Error: ENOENT: no such file or directory, open '/home/adinlead/.config/Postman/plugins/postman.sample/version.json'"}
1557222814372 pluginHost info "PluginInstallationService~installOrUpdatePlugins Installing plugin",{"version":"0.0.1","pluginId":"postman.sample","isInstalled":false}
1557222814372 pluginHost info "PluginInstallationService~installFromLocal",{"pluginZipPath":"/usr/local/src/Postman/app/resources/app/plugins/postman.sample.zip","pluginsDir":"/home/adinlead/.config/Postman/plugins","currVersionDirPath":"/home/adinlead/.config/Postman/plugins/postman.sample/0.0.1","tempDir":"/tmp","result":{"pluginId":"postman.sample","version":"0.0.1","status":null}}
1557222814372 pluginHost info "PluginInstallationService~installFromLocal extracting"
1557222814497 pluginHost info "PluginInstallationService~installFromLocal extracted",{"pluginId":"postman.openApi","version":"0.0.10","status":null}
1557222814497 pluginHost info "PluginInstallationService~installFromLocal moving",{"extractedPluginPath":"/tmp/postman.openApi"}
1557222814497 pluginHost info "PluginInstallationService~installFromLocal extracted",{"pluginId":"postman.sample","version":"0.0.1","status":null}
1557222814498 pluginHost info "PluginInstallationService~installFromLocal moving",{"extractedPluginPath":"/tmp/postman.sample"}
1557222814498 pluginHost warn "PluginInstallationService~installFromLocal Caught an error",{"errno":-18,"code":"EXDEV","syscall":"rename","path":"/tmp/postman.openApi","dest":"/home/adinlead/.config/Postman/plugins/postman.openApi/0.0.10","name":"Error","message":"EXDEV: cross-device link not permitted, rename '/tmp/postman.openApi' -> '/home/adinlead/.config/Postman/plugins/postman.openApi/0.0.10'","stack":"Error: EXDEV: cross-device link not permitted, rename '/tmp/postman.openApi' -> '/home/adinlead/.config/Postman/plugins/postman.openApi/0.0.10'"},{"pluginId":"postman.openApi","version":"0.0.10","status":"failed","error":{}}
1557222814498 pluginHost info "PluginInstallationService~installFromLocal Completed installing plugin",{"pluginId":"postman.openApi","version":"0.0.10","status":"failed","error":{}}
1557222814498 pluginHost warn "PluginInstallationService~installFromLocal Caught an error",{"errno":-18,"code":"EXDEV","syscall":"rename","path":"/tmp/postman.sample","dest":"/home/adinlead/.config/Postman/plugins/postman.sample/0.0.1","name":"Error","message":"EXDEV: cross-device link not permitted, rename '/tmp/postman.sample' -> '/home/adinlead/.config/Postman/plugins/postman.sample/0.0.1'","stack":"Error: EXDEV: cross-device link not permitted, rename '/tmp/postman.sample' -> '/home/adinlead/.config/Postman/plugins/postman.sample/0.0.1'"},{"pluginId":"postman.sample","version":"0.0.1","status":"failed","error":{}}
1557222814498 pluginHost info "PluginInstallationService~installFromLocal Completed installing plugin",{"pluginId":"postman.sample","version":"0.0.1","status":"failed","error":{}}
1557222814499 pluginHost info "PluginsHost~installOrUpdatePlugins: Synced all plugins",[{"pluginId":"postman.openApi","version":"0.0.10","status":"failed","error":{}},{"pluginId":"postman.sample","version":"0.0.1","status":"failed","error":{}}]
1557222815643 main info "Main~AppEvents - Received booted event for process shared"
1557222815647 main error "Main~AppEvents - Shared window boot failed",{"_e":{"message":"","name":"Error","stack":"Error\n    at getErrorWithStack (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:204598:12)\n    at new DexieError (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:204727:19)\n    at mapError (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:204757:14)\n    at handleRejection (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:205241:14)\n    at IDBOpenDBRequest.<anonymous> (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:208448:9)\n    at IDBOpenDBRequest.<anonymous> (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:205454:23)"},"_stack":"VersionError: The requested version (40) is less than the existing version (120).\n    at mapError (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:204757:14)\n    at handleRejection (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:205241:14)\n    at IDBOpenDBRequest.<anonymous> (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:208448:9)\n    at IDBOpenDBRequest.<anonymous> (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:205454:23)","inner":{"message":"The requested version (40) is less than the existing version (120).","name":"VersionError"},"message":"The requested version (40) is less than the existing version (120).","name":"VersionError","stack":"VersionError: The requested version (40) is less than the existing version (120).\n    at mapError (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:204757:14)\n    at handleRejection (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:205241:14)\n    at IDBOpenDBRequest.<anonymous> (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:208448:9)\n    at IDBOpenDBRequest.<anonymous> (file:///usr/local/src/Postman/app/resources/app/js/vendor-shared.js:205454:23)"}

`

**Comment by numaanashraf** [comment] 2019-05-22 12:22
Duplicate of #5591

**Closed as completed by numaanashraf** 2019-05-22 12:22 UTC
