### ISSUE TITLE
Curl command generated from postman is not correct

### ISSUE THREAD

**Issue by neeraj15599** [a85/POSTMan-Chrome-Extension#5842] opened 2019-01-28 16:47 UTC

**Comment by numaanashraf** [comment] 2019-02-03 07:13
@neeraj15599 Please provide more information regarding the issue in this format.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by numaanashraf** [comment] 2019-02-18 14:52
Closing due to insufficient information. Please reopen with clear steps to reproduce this issue.

**Closed as completed by numaanashraf** 2019-02-18 14:52 UTC
