### ISSUE TITLE
Postman app screen goes black

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#5410] opened 2018-10-23 11:28 UTC
**Describe the bug**
Postman is usually unusable as it goes completely black when switching between windows. Sometimes, it also freezes the window when doing something like double-clicking on a text field. 

**To Reproduce**
1. Open app
2. Switch between any other open window on screen
3. Try going back tot he Postman app, it throws a blank screen
4. Error: 
- More detailed information is also not avilable as nothing gets written to stdout, nothing in system logs.
- Devtools can't be opened- each of the four options does nothing and below error is thrown at stderr.

[23051:1022/144724.926169:ERROR:CONSOLE(1)] "Uncaught ReferenceError: WorkspaceDiff is not defined", source: chrome-devtools://devtools/bundled/devtools_compatibility.js (1) 

[23051:1022/144724.929758:ERROR:CONSOLE(3)] "Uncaught TypeError: Cannot set property 'showContextMenuAtPoint' of undefined", source: /usr/lib/electron- postman/resources/electron.asar/renderer/inspector.js (3)

**Expected behavior**
App doesn't throw a blank screen at any point of time.

**Screenshots**
![app blank screen](https://user-images.githubusercontent.com/12132423/47357590-c2917400-d6e4-11e8-8aa4-fae73ba7bb4c.png)

Video - [https://drive.google.com/open?id=1fG1NmTlZhuCjNSMkArMclV7OimC37mu0](url)

**App information**
System: Manjaro Linux (rolling release) 
postman 6.2.4-1 
electron 2.0.11-1

**Comment by m4rcinkowski** [comment] 2018-10-25 09:39
Thanks for addressing the issue. If you ever need additional help with debugging it remotely, just mention me and I'll do my best.

**Comment by harsh-reality** [comment] 2018-10-25 11:14
Certainly, @szoper. Either me or someone from our team will reach out for help if needed while debugging this!

**Comment by gnunes76** [comment] 2018-10-25 21:32
Hi people. Thank you for addressing this issue. I hope this is corrected soon. Thank you all.

**Comment by bhanuvrat** [comment] 2018-11-16 03:36
happening with archlinux too.

**Comment by m3dbedb** [comment] 2019-01-21 08:24
The issue is still here with postman 6.7.1 for windows 32

**Comment by m4rcinkowski** [comment] 2019-01-21 10:52
Since a couple of weeks ago (more than a month, I think) I'm testing a different package providing postman and **haven't experienced the issue yet**.  
As Manjaro is based on ArchLinux, I use AUR packages both now and before. You might want to analyze the differences in PKGBUILD files to see what the core reason is.

**Wrong package** (the one that showed the issue), postman 6.2.4: https://aur.archlinux.org/packages/postman/
**Right package** (no issues yet), postman 6.7.1: https://aur.archlinux.org/packages/postman-bin/

**Comment by m3dbedb** [comment] 2019-02-12 08:55
The issue has been reproduced in postman 7.0.9 for windows 32 bit under windows 7 32. (I use  --disable-gpu parameter, but it does not help)

**Comment by numaanashraf** [comment] 2019-05-20 03:51
@szoper Thanks for letting us know. Closing this for now as the original issue reported has been resolved.

**Closed as completed** 2019-05-20 03:51 UTC
Labels: bug, platform/linux
