### ISSUE TITLE
On export collection, content-type added automatically with wrong value

### ISSUE THREAD

**Issue by neriya197** [a85/POSTMan-Chrome-Extension#8256] opened 2020-03-29 18:51 UTC
**Description**
On export collection, content-type added automatically with wrong value

**Steps to reproduce**

[SanityTests.zip](https://github.com/postmanlabs/postman-app-support/files/4399569/SanityTests.zip)

1. import the attach collection.
2. focus on startup request
3. see in headers only 2 headers.
4. export it.
5. see that:
					{
						"key": "Content-Type",
						"value": "{{Retailer}}"
					}
was added to startup request.

**Expected behavior**
headers will be exported properly. 

 - Type: Native App
 - Postman Version: v7.21.1
 - OS: Win 10

**Comment by umeshp7** [comment] 2020-03-30 08:52
Duplicate of #5702

**Closed as completed by umeshp7** 2020-03-30 08:52 UTC
Labels: importer, product/importers

**Comment by neriya197** [comment] 2020-03-30 11:40
> Duplicate of #5702

why it's duplicate? I review the second bug. it's similar to me but not the same.
in the second one he create this header, I didnt create it at all, and when I export it, it's added...

**Comment by neriya197** [comment] 2020-03-30 11:42
see my comment in my issue, it's not a duplicate issue. the second one is
different

נריה הלל Neriya Hillel
מהנדס תוכנה Software application engineer
052-4206989
רבבה ת.ד. 227 Revava mailbox




‫בתאריך יום ב׳, 30 במרץ 2020 ב-11:53 מאת ‪Umesh Pathak‬‏ <‪
notifications@github.com‬‏>:‬
