### ISSUE TITLE
Request to collapse or hide the left-hand bar

### ISSUE THREAD

**Issue by bgrabar** [a85/POSTMan-Chrome-Extension#9538] opened 2021-02-03 17:01 UTC
Can you add a way to collapse or even hide the left-hand bar that contains tiles for Collections, APIs, Environments, etc?

The left-hand bar and collections pane together take up more real estate than I'd like. I don't want to fully collapse the collections pane as I access it often. 

In the screenshot below, I've reduced the collections pane as much as possible without collapsing it, but the combined width of the pane and left bar still take up too much space for me.
 
![image](https://user-images.githubusercontent.com/2104449/106781190-cb3cb880-6616-11eb-8f02-5731fb1acac4.png)

**Comment by DannyDainton** [comment] 2021-02-03 17:10
Closing this as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9498

**Closed as completed by DannyDainton** 2021-02-03 17:10 UTC
Labels: duplicate
