### ISSUE TITLE
Variables Autocomplete menu available in request body

### ISSUE THREAD

**Issue by norcino** [a85/POSTMan-Chrome-Extension#5290] opened 2018-10-02 11:39 UTC
Currently when typing {{ in the request URL box, or in the Headers section, I see a nice and helpful dialogue which allow me to view the available variables I can use.

I would like the same feature to be available for the request Body area.

While setting up the body for a POST request (for example), I would like PostMan to intercept the {{ and show me a dialogue which would allow me to pick one of the available variables.

**Comment by gekonwi** [comment] 2018-11-29 03:45
I would like the variables in the request body to behave just like the variables in the URL box - what @norcino said + mouse-over popups which shows the initial / current value and the scope.

**Comment by nouknouk** [comment] 2019-10-09 09:04
highly interrested too ; this would be very helpful and time saving to have auto-completion in the request body, both for writing & reviewing actual values.

**Comment by kamalaknn** [comment] 2020-05-11 16:08
Duplicate of #3517

**Closed as completed by kamalaknn** 2020-05-11 16:08 UTC
Labels: feature, code-editor
