### ISSUE TITLE
Postman fails to send request when token ends with a newline character

### ISSUE THREAD

**Issue by djbios** [a85/POSTMan-Chrome-Extension#7106] opened 2019-08-13 15:34 UTC
**Describe the bug**
Postman don't send request with variable in Bearer authorization, on some tokens

**To Reproduce**
1. Version v7.5.0
2. Set variable with some bearer token 
I've used
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEiLCJqdGkiOiI1NjhiNjg4MS0wMTczLTRkM2YtOTVmMy1iYTRlOTMyYTE1NTQiLCJpYXQiOiIwOC8xMy8yMDE5IDEzOjAzOjUzICswMDowMCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIkF1dGhTZXNzaW9uSWQiOiIwZmU4ZTZiYi02ZDRmLTRlODMtYWU2NC1hYmMzNGNlYjFlZWYiLCJuYmYiOjE1NjU3MDE0MzMsImV4cCI6MTY1MjEwMTQzMywiaXNzIjoiUmVuSW5zLkF1dGgiLCJhdWQiOiJSZW5JbnMuSGVhbHRoIn0.oozmmvzKx-vhRqxsUUgzqriysZ8McgcxetFDjbrlJg8
```
3. Use variable in request
![image](https://user-images.githubusercontent.com/11632032/62954698-83a9e780-bdf8-11e9-9ec8-1fef2f32d699.png)
![image](https://user-images.githubusercontent.com/11632032/62954853-c2d83880-bdf8-11e9-9656-ed6c713a6136.png)
![image](https://user-images.githubusercontent.com/11632032/62954942-e7341500-bdf8-11e9-8cd7-5fad06c3a34e.png)

**Expected behavior**
Request works.

**Screenshots**

**App information (please complete the following information):**
 - Postman Version v7.5.0
 - OS: Windows 10

**Additional**
If I past token in authorization without variable, it works fine.
I've checked with Wireshark, there is no request on server in described case.

**Comment by coditva** [comment] 2019-08-14 06:32
@djbios Hi!
I tried sending a request with the token you provided and it went through (with and without environment variable) on Windows 10.

One way I _was_ able to reproduce this was by adding a newline character at the end of the token. Can you verify if this is the case? Try removing and re-adding the `token` variable and tell me if this persists.

**Comment by djbios** [comment] 2019-08-15 12:47
Yes, newline was the issue, thanks. But I guess it's still an unexpected behaviaour.

**Comment by coditva** [comment] 2019-08-16 09:06
@djbios You're absolutely right. Tracking this as `Postman fails to send request when token ends with a newline character`.

Similar: https://github.com/postmanlabs/postman-app-support/issues/4485

**Comment by shamasis** [comment] 2019-09-18 22:32
Duplicate of: https://github.com/postmanlabs/postman-app-support/issues/7106 We are working towards improving the response area error messages so that this can be bubbled up better.

**Closed as completed by shamasis** 2019-09-18 22:32 UTC
Labels: bug, duplicate, product/runtime
