### ISSUE TITLE
desktop app freezes and UI becomes unresponsive  

### ISSUE THREAD

**Issue by RichieMerchant** [a85/POSTMan-Chrome-Extension#8522] opened 2020-05-21 13:32 UTC
**Describe the bug**
The application fails to respond to any click. The whole app is unresponsive

**To Reproduce**
1. Open the desktop app
2. Run a request
3. Leave the app to go idle (length of time is not known, it varies 1 hour, 1 day)
4. Tab back to desktop app and you are unable to interact with the UI

**Expected behavior**
Should be able to interact with the UI or see an error message

**Screenshots**

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.22.1
 - OS: macOS High Sierra 10.13.6

**Additional context**

**Comment by kamalaknn** [comment] 2020-05-23 11:55
@RichieMerchant thanks for reporting this. This looks like a duplicate of #8135. 

We have rolled out some improvements on the [canary channel](https://www.postman.com/downloads/canary/), that should address this particular issue. We will keep the main issue updated when the fix is rolled out to the stable channels.

**Closed as completed by kamalaknn** 2020-05-23 11:55 UTC
