### ISSUE TITLE
tunneling socket could not be established, statusCode=407

### ISSUE THREAD

**Issue by srajamohan** [a85/POSTMan-Chrome-Extension#8862] opened 2020-07-30 03:06 UTC
**Describe the bug**
I am facing proxy tunnel problem. I tried by setting proxy configuration manually but still it didn't work. In the logs I can see
Error: tunneling socket could not be established, statusCode=407
Proxy
authenticate: true
disabled: false
host: "proxy-host"
match: {…}
password: "password"
port: 8080
tunnel: false
username: "username"

**To Reproduce**

**Expected behavior**
After we enable the proxy request should be processed successfully

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]
Postman for Mac
Version 7.29.1
OS X 19.6.0 / x64
macOs Catalina: version 10.15.6

**Additional context**

**Comment by arlemi** [comment] 2020-07-30 10:46
Duplicate of #8783

**Closed as completed by arlemi** 2020-07-30 10:46 UTC
