### ISSUE TITLE
Published documentation is not syncing

### ISSUE THREAD

**Issue by imikemiller** [a85/POSTMan-Chrome-Extension#7317] opened 2019-09-13 15:31 UTC
**Describe the bug**
I am regularly updating my API documentation and distributing the link to share to my team. The shared collection JSON always updates as expected.

I have just checked the published web page version of the documentation and there has been no change to the CURRENT version since 21st June 2019.

**Expected behavior**
When the Postman application syncs my local changes I expect these changes to show in the documentation published on the web. 

**App information (please complete the following information):**
Postman for Linux
Version 6.7.1
linux 4.15.0-62-generic / x64

**Comment by godfrzero** [comment] 2019-09-17 13:49
@imikemiller Could you post the link to the concerned published documentation here? If you've already opened up an internal support ticket, please send the ID of the published collection on the internal support ticket. The documentation doesn't exist as a separate logical entity from the collection, so this bug shouldn't be possible.

**Comment by godfrzero** [comment] 2019-09-23 00:13
@imikemiller One more question: How are you sharing the collection JSON? Are you using a link that starts with "https://www.getpostman.com/collections/"?

**Comment by imikemiller** [comment] 2019-09-23 07:13
@godfrzero yes that is right - the importable JSON from the share link starting   "https://www.getpostman.com/collections/" was correct. The API page was not. I updated to version 7.6 and the issue resolved itself.

**Comment by godfrzero** [comment] 2019-09-23 07:19
Alright, closing this ticket then. The actual bug was most likely caused by local app changes not being synced to our servers. The documentation is generated from the JSON present on our servers, while the the JSON share link creates a different snapshot (which is why that was up to date).

**Closed as completed by godfrzero** 2019-09-23 07:19 UTC
Labels: bug, product/documentation

**Comment by imikemiller** [comment] 2019-09-23 07:23
i am not sure I am buying that as the shared collection link was not local so clearly my local changes had sync'd with the servers or my team mates would have got really outdated collection when they imported. Issue only came to light when I shared the documentation page with some business people (who didnt have Postman and couldnt use the import) and they started questioning where API's were etc. It was then I noticed the change log was so stale. I dumped web browser cache and checked with my team and was pretty clear the web page was showing different content to the share link

**Comment by godfrzero** [comment] 2019-09-23 07:27
@imikemiller I meant that the link snapshot and the synced changes are handled separately. One is a point-in-time snapshot, the other is realtime. The point-in-time snapshot is the one you've shared with your teammates and it was displaying the updated JSON. The realtime sync flow was the one storing the outdated JSON.

**Comment by godfrzero** [comment] 2019-09-23 07:30
The issues related to incomplete or non-functional sync is being tracked separately: #7119 #6166

**Comment by imikemiller** [comment] 2019-09-23 07:31
Ah ok yep that certainly makes sense.

**Comment by SanthoshGunaShekar** [comment] 2019-09-26 12:41
@Raja-Simha @Cazaimi... I have a similiar issue. Myself and my teammate share a workspace and once I create a collection and share the collection to him, the list of api's are not showing the latest one. They always show the old and not updated one, beacuse of this issue we are not able to sync our work and it is affecting us a lot. Could you please let me know how this can be solved or is there any work around to fix this?

Thanks for your help.

**Comment by contentfree** [comment] 2020-11-24 04:31
Using the postman.co website and changes to my API are not synced to the published documentation. How do I force a documentation collection to be updated / synced with my API? I've edited it today but the documentation still says "current" is from four days ago. Do I really have to delete and recreate the documentation collection every time I update the spec?

**Comment by godfrzero** [comment] 2020-11-24 07:26
@contentfree You shouldn't have to delete & recreate. Would it be possible to post a link to the public doc here so I can take a look?

**Comment by contentfree** [comment] 2020-11-25 03:11
https://documenter.getpostman.com/view/2541692/TVes8SV2 (it's out of sync
with the API spec in my Postman account – I don't know of any way to force
it to update besides deleting and recreating)

**Comment by godfrzero** [comment] 2020-11-25 06:14
@contentfree Thanks for the link. We had made some changes yesterday which should've addressed this. If you're still seeing this issue, could you try the following:

1. Make modifications to the collection description, check if the updates are reflected within a couple minutes
2. Make modifications to a request within the collection, check if the updates are reflected within a couple minutes

If you're continue to see this problem, please contact us at help@postman.com and we can get into the details.
