### ISSUE TITLE
Postman indicates "could not get response", but wireshark captures show otherwise

### ISSUE THREAD

**Issue by thesaxonedone** [a85/POSTMan-Chrome-Extension#6377] opened 2019-04-27 22:17 UTC
**Describe the bug**
Postman indicates "could not get response" when POSTing a multipart form, but wireshark captures show the server responding with a properly formed HTTP 400.

**To Reproduce**
I don't really have a way to reproduce it as it appears to be sporadic.

**Expected behavior**
If a properly formed HTTP response is received on the wire, Postman should indicate as such

**Screenshots**

**App information (please complete the following information):**
 - App Type, Native App
 - Postman Version 7.09
 - OS: Windows 10

**Additional context**
The only thing I can think of that might be contributing to this is the fact that the app logic is intentionally interrupting the postman request.   The multipart form is submitted with a large 3 GB file, and the appserver is intentionally responding with a 400 **while the request is in flight** because the file is too large.    

If you would like my pcap files, I can provide

**Comment by shamasis** [comment] 2019-04-29 05:21
This will be tricky to debug. If you’re seeing “could not get a response” - indicates that the flow completed internally. I can think of two things that could be the cause. Code error in parsing request or response and secondly SSL certificate issues. Could you open Postman Console and see if there are any error logged?

**Comment by thesaxonedone** [comment] 2019-04-29 05:23
I can confirm that SSL/TLS is not the problem as the traffic is unencrypted.   I will get back to you on the console output

**Comment by thesaxonedone** [comment] 2019-04-29 05:45
The failing requests alternate between the following errors in console(I have also included a screenshot of the failing request). 
Error: write ECONNABORTED or Error: read ECONNRESET

![image](https://user-images.githubusercontent.com/31674706/56878087-161faa00-6a07-11e9-8560-a5a6b3e0746a.png)




What's odd though is that the wireshark capture clearly shows the HTTP request being issued by postman, clearly shows a series of data packets are exchanged, and clearly shows the 400 response being sent (backend will respond with 400 due to size of client request, or extraneous form value).  Here is the same request issued later and working this time.   Again, it seems sporadic.

![image](https://user-images.githubusercontent.com/31674706/56878103-29327a00-6a07-11e9-84c8-b8eb462c5776.png)
![image](https://user-images.githubusercontent.com/31674706/56878113-351e3c00-6a07-11e9-82e4-bb8f9c2e3555.png)

If a pcap file would be useful, let me know.

**Comment by hubeflo** [comment] 2019-04-30 14:44
@thesaxonedone
Did you check the value for "Request timeout in ms" in Postman under Settings->General?

Error "Could not get response" is what Postman will display in case the request timeout occurs.

**Comment by thesaxonedone** [comment] 2019-05-01 03:25
Timeout is set sufficiently high.

**Comment by thesaxonedone** [comment] 2019-06-30 16:52
As an added datapoint, I believe I have further diagnosed this as unpredictable behavior when the server responds to an in-flight HTTP request.   In other words, for example, if the client is trying to POST a 4 GB file, and the server responds with an HTTP 413 (or anything really, but we'll just use a 413 as an example), while the client is still transmitting data, Postman's behavior is unpredictable.   Sometimes it will appropriately show the HTTP response, other times it will erronesouly show a "Could not get any response" message.    

Here is another library where a similar discussion was had:
https://github.com/akka/akka-http/issues/119

Here is the RFC governing that a client should listen for error responses while request is ongoing https://tools.ietf.org/html/rfc7230#section-6.5
```
 A client sending a message body SHOULD monitor the network connection
   for an error response while it is transmitting the request.  If the
   client sees a response that indicates the server does not wish to
   receive the message body and is closing the connection, the client
   SHOULD immediately cease transmitting the body and close its side of
   the connection.
```

**Comment by codenirvana** [comment] 2019-06-30 17:50
@thesaxonedone Thanks for providing the additional details and the RFC reference.

I tried reproducing this locally with our request sending library and it does terminate the ongoing request if the server ends the connection prematurely.

<img width="1081" alt="Screenshot 2019-06-30 at 11 06 17 PM" src="https://user-images.githubusercontent.com/4865836/60400101-fa628c80-9b8c-11e9-806d-eb43bb5a5155.png">

As you can see in the screenshot above, the actual content-length is `2097152347` but the server closed the collection and at the same time, the ongoing request is terminated.
> Note: 4 chunks are received even after the closing log, that's because `socket.end()` is async. No more chunks are received after request termination.

**Comment by thesaxonedone** [comment] 2019-06-30 17:58
I am unable to understand if you are acknowledging that this is a problem, or if you're saying this is expected behavior?   I am getting the impression that you mean the latter.

If a properly formed 400 or 413 (or really any HTTP response) is being sent back by the server, Postman should not be indicating an ECONNRESET or ECONNABORTED, when the reason for the ended connection was **not** a TCP RST but rather a valid HTTP response.

I am making the assumption that your test was just cancelling the TCP connection on the server side which would result in a TCP RST packet being sent on the wire to the client, at which point the client would cancel the connection (as you said) and you would get the behavior you described (and would be expected).   

However, the issue is that when the server responds to an inflight request with valid content in the form of an HTTP 400 or 413 or whatever (as opposed to a TCP RST), and then sends a TCP FIN packet, Postman will seemingly randomly decide to either A) appropriately display the HTTP response,  B) erroneously indicate that it couldn't get a response.

**Comment by codenirvana** [comment] 2019-06-30 18:10
@thesaxonedone I acknowledge that its an issue but I am not able to reproduce this locally (https://github.com/postmanlabs/postman-app-support/issues/6377#issuecomment-507054543).

Can you share your steps to reproduce this? Maybe provide a sample local server which can be used to reproduce the similar behavior at our end.

**Comment by thesaxonedone** [comment] 2019-06-30 18:12
I will see if I can get something going for you.   Thanks for the followup

**Comment by thesaxonedone** [comment] 2019-06-30 21:57
I do not readily have access to a server on which to do this, but I have created a github repository with code that will run a nodeJS application that will demonstrate the issue.   I have included what I believe to be relatively straightforward instructions for running this and demo-ing the issue

https://github.com/thesaxonedone/postman_issue6337_demo

**Comment by codenirvana** [comment] 2019-07-01 23:29
@thesaxonedone Thanks for providing the sample server. However, Its working fine for me, no "Could not get any response" 😕 

Can you try upgrading to the latest version of the Postman App and check if the issue persists?

**Comment by thesaxonedone** [comment] 2019-07-02 00:18
How many times did you attempt the POST?    It usually takes a few tries for it to happen (it seems to happen as frequently as every other request and as infrequently as every ten requests, depending on who knows what).

For reference, I am running Postman 7.2.2, which appears to be the latest version?   Clicking "Check For Updates" results in an "Up To Date" message

**Comment by codenirvana** [comment] 2019-07-02 03:29
@thesaxonedone I tried around 20-25 request manually and then ran 150 iterations using the collection runner without any issue.

**Comment by thesaxonedone** [comment] 2019-07-02 03:57
@codenirvana maybe its some oddity with the OS network stack?   I'm running both Node and Postman on windows.   Yourself?

**Comment by thesaxonedone** [comment] 2019-07-02 04:23
@codenirvana Nevermind, I spun up a VM and got it to happen using both Postman Linux and Windows clients going to the referenced NodeJS app running on both Windows and Linux NodeJS instances.    

Would it be helpful for me to demo it to you, since you seem unable to repro?

**Comment by codenirvana** [comment] 2019-07-02 04:49
@thesaxonedone I can confirm this is happening on Windows. I was testing on macOS previously.

Need to check what's causing this issue but it will be very tricky as its happening and the very low-level request sending layer.

Will update once I found the root cause of this issue.

**Comment by thesaxonedone** [comment] 2019-07-02 05:02
Here is a possible theory:
Race condition between TCP FIN packet and unacknowledged receive buffer, though I don't know if its an OS level problem or a Postman problem.   That being said, I don't think I'm the first one in the world to deal with trying to gracefully terminate requests that are too large, so I imagine there is an accepted way to deal with this.  Some of the previous articles I linked discuss this possibility with respect to other issues.

Example flow of what I think is going on.
1.  Client initiates a request to upload file and starts sending data
2.  Server accepts data until request is too large (or until it determines request is malformed).
3.  Server issues a 413 (or 400 or whatever) and then closes underlying TCP connection by sending a FIN packet.
4.  This FIN packet has to transit the internet and takes some non-zero amount of time to arrive at the client.   Client meanwhile is still happily transmitting data.
6.   The client's traffic that arrives at the server after the server's issuance of the FIN packet, results in the server sending a TCP RST because its no longer an open connection
7.    Client is taking a non-zero amount of time to fill its receive buffer which may at this point contain the HTTP 400/413
8.    If the TCP RST arrives back at the client before the receive buffer is processed, I'm guessing there is logic in either Postman, or the underlying OS that disregards any pending data in the receive buffer.
9.   If this receive buffer contains the unprocessed HTTP 400/413, then the client's perceived behavior is an interrupted request (i.e. TCP RST) to which the server never responded (at HTTP/Layer7 level).

I'm hoping its simpler than this, but given the sporadic nature of the problem, this was the only logical conclusion I could come up with that made sense

**Comment by m3dbedb** [comment] 2019-09-13 11:54
I also have the issue in postman 7.6.0 under windows 7 32 bit.  One request to the same server works, another does not. Later I noticed I request unexisting page, and normally server redirects browser to default page.  At the end of workout I have found URL mistake, fixed it, but Postman still gives could not get response. After several attempts useng another web browser app, postman get back to work.

**Comment by vikiCoder** [comment] 2019-12-02 04:29
I was able to reproduce this issue in both, macOS and Windows. But it doesn't seem to be a problem specific to Postman App. I see the same behaviour (randomly failing request when sent multiple times) while sending the request using cURL, but Wireshark shows the response. See the below GIF in which I am sending the request 3 times using cURL, of which the first request fails. But the Wireshark shows the response for all 3 requests.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16588032/69930345-07432d80-14e9-11ea-9b5c-31e065fa5249.gif)

However, the possible theory given by @thesaxonedone seems to be correct. Because when I run the server locally and send the request to it, I never saw the failing response in Postman. To reproduce the problem, I had to run the server on a different machine connected through LAN and send the request from my PC. This introduces a little more delay between sent packets, causing the race condition @thesaxonedone  mentioned to occur more frequently.

Since it is not the Postman App specific problem, I am closing this issue.

**Closed as completed by vikiCoder** 2019-12-02 04:29 UTC
Labels: bug, request-sending, product/runtime

**Comment by thesaxonedone** [comment] 2019-12-02 04:40
@vikiCoder    My comments indicate seeing the failure in both cases (running locally, and running app on a VM on LAN).   However, I would assert that the race condition is MORE likely when running locally because there is less time for the OS to clear the receive buffer before seeing the TCP RST.   I dont know if this changes anything with respect to your troubleshooting, but thought I would point it out.
