### ISSUE TITLE
Uploaded files (form-data/binary) don't reflect in code snippets

### ISSUE THREAD

**Issue by AymanEG** [a85/POSTMan-Chrome-Extension#2469] opened 2016-11-15 05:56 UTC
Hello there , Thanks for great work at your APP
And as a pay back for the great APP , I like to report a bug :

Edit [More details] 
I try to upload a file (test.png) from my desktop to my Wordpress Media library through the client (Body -> binary -> choose file) , the call was success returning 201 created , when i try to generate the code , no indication for the image path !

The code generator fail to generate the data binary "file" field

![untitled](https://cloud.githubusercontent.com/assets/23207050/20294701/d1df940a-ab08-11e6-9a4a-6f7045f31f05.png)

Version/App Information:

* Postman Version: Windows APP
* OS details: win 10 x64

**Comment by SamvelRaja** [comment] 2016-11-15 06:33
@AymanEG Thanks for bringing this to out notice, we shall keep you updated on the progress of this here.

**Comment by AymanEG** [comment] 2016-11-15 07:27
Thanks for your fast response, I confirm also same issue on chrome app

for who seeks the answer , a complete example is like the following in php curl: 

```
<?php

$curl = curl_init();

$data = file_get_contents('C:\test.png');

curl_setopt_array($curl, array(
  CURLOPT_URL => "http://woo.dev/wp-json/wp/v2/media",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_HTTPHEADER => array(
    "authorization: Basic XxxxxxxxxxxXXx=",
    "cache-control: no-cache",
    "content-disposition: attachment; filename=test.png",
    "content-type: image/png",
  ),
  CURLOPT_POSTFIELDS => $data,
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

**Comment by chandanpasunoori** [comment] 2016-11-25 04:31
request and response are correct when I click send, but when I generate whole json body is not available in  code, like java, nodejs, httpie, etc but it was in only cURL but not in shell curl.

I restarted postman several time but still same behaviour

**Comment by DaFrik** [comment] 2016-11-29 03:46
got the same issue, 

my env:
- in a POST request, with Headers and Body, 
- Body type is "raw" and  "JSON (application/json)" is selected
- typed my correctly formatted JSON
- click on the "Code" to generate code
- Selected "HTTP" I can see my post body JSON value
- then selected "Java > Unirest" , I CANNOT see my post body JSON value
- tried selected "NodeJS > Unirest", ALSO CANNOT  see my post body JSON value
- then tried "C# (RestSharp)" , ALSO CANNOT  see my post body JSON value

**Comment by rtrigoso** [comment] 2017-10-24 15:46
Just to post more information:

The request body shows on Postman Console, under the RAW request tab, but it doesn't show under the PRETTY request tab.

**Comment by abhijitkane** [comment] 2019-04-19 03:20
There seem to be two distinct issues here:

1. Files being uploaded through the form-data or binary mode don't show up in the generated snippet. This is a known issue - we're working on a better way to handle files in Postman, and we'll be able to support this in the code snippets once the file path is available. 

2. JSON in the body doesn't show up in some of the snippets. I'm not able to reproduce this with version 7.x of Postman anymore.

**Comment by SaiRamPothuganti** [comment] 2019-06-28 14:04
is this issue resolved  ?

**Comment by abhijitkane** [comment] 2019-07-15 08:54
@SaiRamPothuganti What issue are you referring to? As mentioned in the previous comment, file handling is something we'll take up as a feature request in a future release.

The JSON body issue is not reproducible with Postman v7+.

**Comment by SaiRamPothuganti** [comment] 2019-07-15 14:17
Hi abhijit,

the issue, we are sending files in binary, and in code auto-generation, we are not able to see it

**Comment by yogevglucome** [comment] 2019-10-16 14:45
Anyone has a workaround for this one?

**Comment by vyomanaut** [comment] 2019-10-18 07:15
any updates on how to fix this ? same issue with restsharp generated code on postman

**Comment by shreys7** [comment] 2020-01-02 12:08
In Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'New Code Generation Mode' flag enabled in Postman's global settings
This particular bug is fixed in the new code generation mode. It supports file upload via multipart/form-data.
![Screenshot 2020-01-02 at 5 33 47 PM](https://user-images.githubusercontent.com/20665864/71666378-92cd0a00-2d86-11ea-94c8-7afadfa48562.png)

**Closed as completed** 2020-05-04 07:32 UTC
Labels: feature, code-generator
