### ISSUE TITLE
Fork name in GET collections API call

### ISSUE THREAD

**Issue by SVDL-begame** [a85/POSTMan-Chrome-Extension#7435] opened 2019-10-04 11:30 UTC
**Is your feature request related to a problem? Please describe.**
We are using Postman collections for our functional tests. Using the Postman API together with Newman CLI to run the tests in our Bitbucket pipelines. I've written a script that runs during the BitBucket Pipeline to see if there is a Postman collection specifically for the branch the Pipeline is running for. Right now I'm check the collection name to see if there is a specific one but preferable I would like to get it through the fork name which is not returned by the GET collections API call! 

**Describe the solution you'd like**
Please add the FORK name to the result when getting collections. Example:
`{
    "collections": [
        {
            "id": "0749b3ac-73d3-4330-b177-##########",
            "name": "Collection name",
            "owner": "1312####",
            "uid": "1312462-0749b3ac-73d3-4330-b177-###########"
"fork": "Fork name"
        }
    ]
}`

**Describe alternatives you've considered**
I have a workaround in place now but it requires us to change the collection name of the fork. Not ideal because when merging the changes of the fork it also wants to change the name of the collection. So we need to change the name twice and this is prune to errors!

**Additional context**
See screenshot from Postman for requested info object.
<img width="431" alt="Screenshot 2019-10-04 at 13 24 41" src="https://user-images.githubusercontent.com/56157621/66204278-cb3b4a00-e6aa-11e9-88a4-eb8d64377b2e.png">

**Comment by Wotuu** [comment] 2019-10-28 14:57
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/6540. I'm running into your exact issue and hope that this gets added soon.

**Comment by ankit-m** [comment] 2020-01-22 07:27
API now returns a `fork` object for forked collections.

**Closed as completed by ankit-m** 2020-01-22 07:27 UTC
Labels: feature, product/postman-api, version-control, fork+merge

**Comment by Wotuu** [comment] 2020-01-28 09:47
Awesome! Thank you so much, I'll get to work on integrating this right away.
