### ISSUE TITLE
Can you create a folder that supports multiple levels?

### ISSUE THREAD

**Issue by tonycody** [a85/POSTMan-Chrome-Extension#2926] opened 2017-04-08 02:31 UTC
Can you create a folder that supports multiple levels?
like this?sample:

- company name 1
	- project name 1
		- module name 1
		- module name 2
	- project name 2
		- module name 1
		- module name 2
	- project name 3
		- module name 1
- company name 2
	- project name 1
		- module name 1
		- module name 2
	- project name 2
		- module name 1
		- module name 2
	- project name 3
		- module name 1

**Comment by a85** [comment] 2017-04-08 20:30
Duplicate of #907

**Closed as completed by a85** 2017-04-08 20:30 UTC
Labels: feature
