### ISSUE TITLE
"Unable to import as APIs when offline. These files will be imported as collections instead. Connect to the internet to import as APIs." - but I am connected

### ISSUE THREAD

**Issue by IanKemp** [a85/POSTMan-Chrome-Extension#9146] opened 2020-10-08 16:11 UTC
**Describe the bug**
When I attempt to import from a Swagger JSON link, I receive the message in the title.

I am connected to the internet, as I can successfully execute requests to internet resources from within Postman.

I do not have a proxy set, nor do I need one.

**To Reproduce**
1. Click the "Import" button on the toolbar
2. Select the "Link" tab
3. Input a URL to a valid Swagger JSON schema document
4. Press "Continue" button
5. See message

**Expected behavior**
Not sure. I don't understand what this message is trying to tell me, or whether I should be concerned, or if there is something I can or should be doing (since the "advice" it gives me is clearly wrong and therefore useless).

**Screenshots**
![image](https://user-images.githubusercontent.com/1726434/95484513-76e73c00-0988-11eb-819f-eac702fc70d0.png)

**App information**
Postman for Windows
Version 7.34.0
win32 10.0.19041 / x64

**Comment by abhinaba-ghosh** [comment] 2020-10-08 19:58
Hi @IanKemp I am not able to replicate this issue in the mentioned system setup. Can you double-check the internet connectivity and the sync status?

**Comment by ociteau** [comment] 2020-10-13 07:53
Hi @IanKemp , I have had the same issue. It was solved by creating a postman account.

**Comment by IanKemp** [comment] 2020-10-13 09:26
@ociteau thank you for confirming - I do not have a Postman account either.

@abhinaba-ghosh based on the above feedback, the error message is obviously incorrect - it has nothing to do with being offline.

**Comment by abhinaba-ghosh** [comment] 2020-10-13 09:28
@IanKemp Thanks for the confirmation.

**Comment by IanKemp** [comment] 2020-10-13 09:31
Why are you closing this? That error message needs to be fixed.

**Comment by abhinaba-ghosh** [comment] 2020-10-13 09:50
Yes, we are tracking this internally. Further updates will be posted here.

**Comment by d-schmidt** [comment] 2020-10-16 07:47
@abhinaba-ghosh I'm getting this "error" when I try to reimport my integration test collection. It is not even API, it never was. It is a collection and has been exported as v2.1 collection for newman to execute.
It no longer offers to overwrite the existing collection and drag-and-drop is broken. Nothing happens when I drop the file.

**Comment by kpittman-securus** [comment] 2020-10-30 14:59
I am getting this same error even after signing in, but I think it may have something to do with our corporate firewall.

**Comment by dylang-usask** [comment] 2020-11-05 19:06
Hello!  I, too, had this error come up.  When I go to import a collection, it fails to import with the message, "Unable to import as APIs when offline. These files will be imported as collections instead. Connect to the internet to import as APIs."  

If the issue is that I need a Postman account to import a Postman 2.1 JSON file, then the dialogue text should reflect that.  Also, the actual collection imports fine, which is additionally confusing.  Why is there an alert there at all?

**Comment by abhinaba-ghosh** [comment] 2020-11-06 05:27
Hi all, we are actively working on this to display a better alert. It is expected to release later this month.

**Comment by remborg** [comment] 2020-11-09 13:37
Hang on, so you need a postman account now to be able to import scripts such as curl commands? Is that right?

**Comment by abhinaba-ghosh** [comment] 2020-11-24 07:04
Hi all, this is fixed in `v7.36`  🎉 

We have changed the display message to:

<img width="705" alt="Screenshot 2020-11-24 at 12 33 15 PM" src="https://user-images.githubusercontent.com/23141842/100059594-56e4dc80-2e51-11eb-9010-c0f2f73e9350.png">

**Closed as completed by abhinaba-ghosh** 2020-11-24 07:04 UTC
Labels: bug

**Comment by xccjk** [comment] 2020-12-22 07:40
I also have the same problem here, because I did not log in.

**Comment by xccjk** [comment] 2020-12-22 07:41
I also have the same problem here, because I did not log in.
