### ISSUE TITLE
Shortcuts conflicting with keyboard layouts

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [a85/POSTMan-Chrome-Extension#2707] opened 2017-02-15 14:49 UTC
1. Postman Version: 4.10.0
 2. App (Chrome app or Mac app): Postman for Chrome - Chrome 58.0.3007.0
 3. OS details: win / x86-64
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Today
 6. Expected behaviour: Being able to use AltGr+2 to insert the @ sign. I use pt-PT keyboard
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

The usage of Altgr doesn't work application wide... in URL field, request body...

**Comment by Telaran** [comment] 2017-02-17 07:40
The Issue are the new Shortcuts.
They use several Shortcuts with "CTRL + Alt +" which is equivalent to "AltGr". As seen on the Wikipedia Page (https://en.wikipedia.org/wiki/QWERTZ) they now made several conflicting shortcuts depend on the Layout someone use.

My suggestion: 
Fast: Remove all "CTRL+ALT" Shortcuts and replace them by something Like CTRL+Shift.
Long Term: Make them editable

**Comment by isaklafleur** [comment] 2017-02-24 08:25
I have the same issue with swedish keyboard layout. When I switch to US keyboard layout then it works...

to get @ on Swedish keyboard is AltGr + 2

**Comment by Daszczu** [comment] 2017-03-02 08:54
I've got the same issue. My keyboard is Polish and only 'ALT + E' doesn't work, so I cannot type 'ę'.

**Comment by Telaran** [comment] 2017-04-03 09:15
Any Update or Roadmap on this Issue?
Currently I'm stuck on 4.9.3 and it seems there are some other issues with 4.10.5 (as far I've seen by a co-worker => Folder/Call Edit missing as an example)

**Comment by dracon** [comment] 2017-04-12 08:48
Pitty, is there any hope that we can change the shortcut settings? Norwegian keyborad has the same setup as the swedish. AltGr+2 = @

**Comment by Telaran** [comment] 2017-05-23 06:26
While your write in your May-News Newsletter about "_Increase your productivity with keyboard shortcuts_", you still haven't addressed the issue. It's more annoying due the missing possibility to disable the update-check on the application startup.

Why not at least offer a "disable shortcuts" toggle. This isn't ideal, but for many of us it would at least give the opportunity to use a newer version with some nice improvements/features.

**Comment by matthiasjost** [comment] 2017-05-31 11:50
Also for Swiss-German keyboard: AltGr+2 = @. I have the same issue. That's an annoying problem.

**Comment by matthiasjost** [comment] 2017-06-01 15:21
@numaanashraf Could you fix this for the next version? It is still there in: 4.11.0. I think this is a bug that could be fixed.

**Comment by fvilers** [comment] 2017-06-04 07:43
Also with belgian french keyboard.

**Comment by Daszczu** [comment] 2017-06-08 07:50
The bug is still present. In Polish I can't type 'ę' alt + e, and typing 'ć' alt + c opens 'Console' view but writes the letter.

**Comment by Jiia** [comment] 2017-06-09 20:03
This bug is driving me nuts...

**Comment by sdnts** [comment] 2017-06-12 11:55
Guys, can you try updating to 5.0.0 and check if this is fixed for you now? You should be able to type the `@` symbol now.

**Comment by fvilers** [comment] 2017-06-12 11:57
Works now, thanks!

**Comment by matthiasjost** [comment] 2017-06-12 12:01
I can confirm, it works. Thank you.

**Comment by Telaran** [comment] 2017-06-12 13:13
At least @ is now fixed for Swiss-Layout (Co Worker had it on 4.11.3 and I've confirmed on 5.0)
Several other "special ones" are covered too. 

Only € (Alt-Gr-E) is not recognized correctly and open the "Manager Environment"-Dialog.

**Comment by foldvari** [comment] 2017-08-04 14:40
CTRL+ALT+V still conflicts with AltGr+V (@) on the Hungarian keyboard. Would it be possible to stop using CTRL+ALT combination or make the shortcuts configurable?

**Comment by kmute90** [comment] 2017-11-12 17:08
+1 for conflict on Hungarian keyboard :(

**Comment by a85** [comment] 2018-06-30 22:50
@preethammavin @vkaegis A quick fix here would be to let people define mappings from their keyboard to what Postman sees as Ctrl/Alt/Option keys. We can do configurable shortcuts later.

**Comment by SeinopSys** [comment] 2018-07-29 13:51
I have a Hungarian keyboard as well and this is making entering e-mail addresses into requests a major pain. I hope this gets fixed soon.

**Comment by Magador** [comment] 2018-10-10 07:51
Postman v6.4.2
Windows 7 (6.1.7601) x64
`AltGr` + `e` triggers `Ctrl` + `Alt` + `e` instead of write `é` in an US-International keyboard layout

Since many AltGr-modified keys are to write characters, an idea would be to not trigger the shortcuts when the user is focusing a input field, allowing them to write the character.

**Comment by makuc** [comment] 2018-11-10 00:16
Could you at least let us be able to disable shortcuts or (better yet) disable only a certain shortcut if you have to make the whole thing hard-coded?

**Comment by makuc** [comment] 2018-11-10 00:17
It's been more than a year since you've been made aware of this issue (Alt Gr screwing with us), so the least you could do would post us an update...

**Comment by vbob** [comment] 2019-01-14 11:40
AltGr + W is the shortcut for Question Mark ('?') on Brazilian Portuguese ABNT2 Keyboard. 

On Postman, it closes the current tab, making it impossible for me to type '?'.

**Comment by numaanashraf** [comment] 2019-01-23 14:36
We are working on a configuration to disable all keyboard shortcuts till we have a long-term solution for this. We will update here when this configuration is available on our stable or canary apps.

**Comment by drake1979** [comment] 2019-01-24 10:41
> We are working on a configuration to disable all keyboard shortcuts till we have a long-term solution for this. We will update here when this configuration is available on our stable or canary apps.

Some serious architecture issues there if this is such a big problem for you 👎
I would like to hope that this is the only quality issue with your product, but it's kind of hard.

Thanks for your efforts anyway!

**Comment by vbob** [comment] 2019-03-06 16:47
At the stable release or newer 6.7.4 is possible to disable shortcut keys by going to:

Wrench Icon -> Settings -> Shortcuts -> Shortcuts Toggle

**Comment by vkaegis** [comment] 2019-03-23 10:57
Hey guys, as @vbob mentioned, we now have an option to disable shortcuts. This should unblock you while we work on making shortcuts configurable.

**Comment by mccannt** [comment] 2020-05-29 14:34
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.

**Closed as completed by mccannt** 2020-05-29 14:34 UTC
Labels: bug, shortcuts
