### ISSUE TITLE
Replace tv4 JSON schema validator with Ajv

### ISSUE THREAD

**Issue by hiredgun** [a85/POSTMan-Chrome-Extension#2788] opened 2017-03-07 13:00 UTC
Is there any particular reason why tv4 is used as the JSON-schema validator? Its performance seems horrible comparing with [Ajv](https://github.com/epoberezkin/Ajv)  - according to [json-schema-benchmark](https://github.com/ebdrup/json-schema-benchmark). Can tv4 be replaced with [Ajv](https://github.com/epoberezkin/ajv) which is way faster and regularly updated? At the moment Ajv supports even JSON-Schema draft-06.

**Comment by jon49** [comment] 2017-06-15 17:08
As another reason not to use `tv4` is that it is not case sensitive. Which is not compliant with the standard. It appears that `tv4` isn't being supported anymore either. So, it would be nice to have the Postman team support `tv4` and continue to enhance it or drop it for a better supported library. I was really excited to be able to use Postman to do acceptance testing but now that I know the choice of Json Schema library was poor I'll have to find a different testing environment.

**Comment by kunagpal** [comment] 2018-08-12 13:40
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/3199

**Closed as completed by kunagpal** 2018-08-12 13:40 UTC
Labels: feature, duplicate
