### ISSUE TITLE
Can't install on Windows 10, problem with paths

### ISSUE THREAD

**Issue by d3lboy** [a85/POSTMan-Chrome-Extension#6019] opened 2019-03-05 18:00 UTC
[postman.txt](https://github.com/postmanlabs/postman-app-support/files/2932181/postman.txt)
It's not possible to install Postman version Postman-win64-6.7.4-Setup (older versions also) on Windows 10. 

It can be that is something with file system paths. Look at the logs .
Sometimes is written: "C:\Users\dalib\AppData\Local\Postman\packages\RELEASES" (correct)
Sometimes: "C:\Users\daLocal\Postman\app-6.7.4". It looks like that substring "lib\" is removed from the  correct path.

**Comment by numaanashraf** [comment] 2019-03-18 09:48
@d3lboy Thanks for your issue. This seems like a duplicate of #5301. I'm closing this issue as we are tracking the root cause and the fix at #5301.

**Closed as completed by numaanashraf** 2019-03-18 09:48 UTC
Labels: bug, installation
