### ISSUE TITLE
After updating, Postman 6.2.5 won't start

### ISSUE THREAD

**Issue by ccrookston** [a85/POSTMan-Chrome-Extension#5106] opened 2018-08-28 21:40 UTC
I had been using Postman for many months with no problems.  Everytime I opened it, it prompted me to upgrade, and I never did. Then today for some reason, I went ahead and did the upgrade.  I am now REALLY regretting that.

OS: Windows 8.
Using the Windows app, not the Chrome extension.

When I open the app, I get the yellow Postman window, but then nothing ever happens after that.  It just flickers forever.  I have followed these steps multiple times:

1) Uninstalled the app
2) Deleted C:\Users\[user]\AppData\Roaming\Postman
3) Deleted C:\Users\Developer\AppData\Local\Postman
4) Re-installed version 6.2.5

Same results.  I also started it via a command prompt:

![image](https://user-images.githubusercontent.com/2073514/44752529-46662000-aae9-11e8-907e-16ca933983a2.png)

It got that far, and then just stalled while the Postman window sat there and flickered.

![postman](https://user-images.githubusercontent.com/2073514/44752560-5e3da400-aae9-11e8-9115-5a9999f21486.PNG)

I REALLY hope I can get this fixed.  I've read a lot of threads, and it looks like this has been a problem for a long time.  I wasn't able to find a solution in any of the threads.

**Comment by sivcan** [comment] 2018-08-29 07:57
@ccrookston Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4703

**Closed as completed** 2018-08-29 07:58 UTC
