### ISSUE TITLE
Unable to run requests from a specific folder using ./node_modules/newman/bin/newman.js

### ISSUE THREAD

**Issue by petrussorin** [a85/POSTMan-Chrome-Extension#3933] opened 2017-12-08 12:06 UTC
1. Installed the newman using the following commands.

npm init (created a package.json)
npm install --save newman (installed newman and added to package.json)
 
2. I'm running the tests in the following way:

./node_modules/newman/bin/newman.js run 
3. Adding --folder option I'm getting each time same result...that the folder doesn't :

NOTE: using "newman run" (version 3.8.3)  instead of "./node_modules/newman/bin/newman.js run " (version 3.9.0) will work fine.

**Comment by kunagpal** [comment] 2017-12-08 12:28
Closing as a duplicate of https://github.com/postmanlabs/newman/issues/1324

**Closed as completed by kunagpal** 2017-12-08 12:28 UTC
Labels: bug

**Comment by deepakpathania-zz** [comment] 2017-12-08 13:55
Hey @petrussorin, thanks for reporting it, this has been fixed and released in [3.9.1](https://github.com/postmanlabs/newman/releases/tag/v3.9.1). Go ahead and try it and feel free to reach out in case you have any other queries. :smile:

**Comment by petrussorin** [comment] 2017-12-08 13:58
Thanks guys
