### ISSUE TITLE
Focus URL textfield on new tab.

### ISSUE THREAD

**Issue by vdegenne** [a85/POSTMan-Chrome-Extension#7932] opened 2020-01-18 14:46 UTC
**Is your feature request related to a problem? Please describe.**
When creating a new tab `ctrl+t` the URL textfield is not focus.

**Comment by numaanashraf** [comment] 2020-01-20 04:37
Hey! Thanks for reporting this. We are tracking this at #4282.

**Comment by numaanashraf** [comment] 2020-01-20 04:37
Duplicate of #4282

**Closed as completed by numaanashraf** 2020-01-20 04:37 UTC
