### ISSUE TITLE
Option to add additional params for "Get new access token"

### ISSUE THREAD

**Issue by kschulst** [a85/POSTMan-Chrome-Extension#5057] opened 2018-08-21 11:43 UTC
We're using Auth0. The Auth0 token endpoint requires an additional "audience" parameter in order to exchange an access token. Would it be possible for Postman to include optional additional "key=value" inputs that would be included in the token requests?

The only way to use Postman to retrieve access tokens from Auth0 today is if you configure a default audience in Auth0 - but this will not work for "multi-audience" configurations (like we have).

A more detailed description of the issue can be found here:
https://community.auth0.com/t/get-new-access-token-in-postman/7169/4

**Comment by giridharvc7** [comment] 2021-04-14 10:08
Duplicate of #2934 
Closing this feature request to track in a single place

**Closed as completed by giridharvc7** 2021-04-14 10:08 UTC
Labels: feature, Auth, product/runtime
