### ISSUE TITLE
Continually receiving "You seem to be offline..." message

### ISSUE THREAD

**Issue by matt-ball** [a85/POSTMan-Chrome-Extension#5611] opened 2018-12-05 21:11 UTC
**Describe the bug**
During normal use of the app, the "You seem to be offline. Any changes made while offline might not sync properly with other members of this workspace." message will appear.

Users on the same network are not experiencing the same problem.

**To Reproduce**
No specific steps other than launching the app

**Expected behavior**
No sync issues

**App information (please complete the following information):**
6.5.3-darwin-x64

**Additional context**
[-1544043260405.log](https://github.com/postmanlabs/postman-app-support/files/2650650/-1544043260405.log)

Zendesk #26234

**Comment by wspencer** [comment] 2018-12-10 15:02
+1.  I get this message on and off throughout the day.  It disappears after a few seconds.  No disruption in functionality is apparent.  However, it's very distracting / annoying because the UI "twitches" every time this message appears or disappears.  I've noticed it only in the last couple of months.  I don't think this was happening six months ago.

I'm on Windows 10, but I don't know what version of Postman - the Help menu doesn't have an 'about' option.  I assume I'm up to date on the Postman version, but I can't confirm.

**Comment by qmcree** [comment] 2018-12-10 17:55
Yes, I experience the exact same problem, and it is quite distracting. It started within the past few months. I am running the latest version of Postman for Mac.

This issue was created on my behalf by Postman Support.

**Comment by JPhillipBrooks** [comment] 2019-01-03 17:54
I'm experiencing the same problem.  I noticed it start happening after I created a Team and added a coworker to the team.  She also noticed it started happening as soon as she joined the Team Workspace.

If I can help by gathering Console logs, please let me know.

**Comment by qmcree** [comment] 2019-01-03 20:40
I can also confirm that this issue began after I created a Team and added members to it.

**Comment by MatthewRyanRead** [comment] 2019-01-08 21:56
It's not related specifically to team creation, just being part of a team at all.  I've seen the same as wspencer where it's only been the last 2 months or so.

**Comment by thetreythomas** [comment] 2019-01-09 00:57
I'm seeing this everyday now as well. I'm also using a workspace and collection that is part of a Team.

Windows 10
Postman v6.6.1

**Comment by thertzelle** [comment] 2019-02-01 18:54
Is this issue going to be resolved for the desktop application? Moving the UI to a button or some less obstructive location would be fantastic. All day long the UI shifts up and down.

**Comment by numaanashraf** [comment] 2019-03-26 06:47
We've made some improvements to our syncing system that should address this. Let us know if you are still facing this issue. Closing this issue for now.

**Closed as completed by numaanashraf** 2019-03-26 06:47 UTC
Labels: bug, sync

**Comment by qmcree** [comment] 2019-04-04 18:47
@numaanashraf I am still experiencing this issue. Running Postman for Mac v6.7.4.

**Comment by sujayvenaik** [comment] 2019-04-04 18:48
Hey, @qmcree Can you update to the latest version v7.0.7 and check?

**Comment by JPhillipBrooks** [comment] 2019-04-10 20:13
For my co-worker and I, it used to happen every few minutes. We've upgraded to v7.0.7 an so far I've only seen it happen a couple times over the course of several days. Windows 10 x64.

**Comment by qmcree** [comment] 2019-04-10 20:54
@sujayvenaik We haven’t had any issues since upgrading to Postman v7. Thanks!

**Comment by wspencer** [comment] 2019-04-11 13:18
I'm still experiencing this problem. Windows 10.  Postman 6.7.4, and it tells me this is the latest version.  What gives?  How do I get v7?

**Comment by JPhillipBrooks** [comment] 2019-04-11 13:29
> I'm still experiencing this problem. Windows 10. Postman 6.7.4, and it tells me this is the latest version. What gives? How do I get v7?

Go out to the website and manually download it: https://www.getpostman.com/downloads/

Edit: Looks like you can also go into Settings/Update and enable "Automatically download major updates" but I don't recall if that setting existed prior to v7.

**Comment by timmeade** [comment] 2019-04-24 14:39
I just updated to 7.0.9 and i'm still getting the error.  Not as frequently . but it is still there.

**Comment by qmcree** [comment] 2019-04-24 18:02
Ditto to @TimMeade. It's not near as frequent, but it still happens sometimes.

**Comment by lookingcloudy** [comment] 2019-04-25 16:17
I just upgraded to Version 7.0.9 (OSX version) and I'm getting this every time I start Postman.

**Comment by Niels-Abel** [comment] 2019-06-24 05:28
I can confirm the bug for v7.2.2 (Windows).

**Comment by TzviGK** [comment] 2019-08-29 08:58
Experiencing this in version 7.5.0 (Windows)

**Comment by emetcalfputnam** [comment] 2019-09-08 13:21
Experiencing this on version 7.6.0 (Linux)

**Comment by arueckauer** [comment] 2019-10-14 14:03
Getting this way too often on v7.9.0 (Windows). Restarting app and/or computer does not help. Any workaround? Or any news on this @numaanashraf ?

**Comment by TomYeoman** [comment] 2019-10-21 11:12
I'm on 7.9.0 i'm apparently offline whilst writing this and browsing the web..

**Comment by lanegoolsby** [comment] 2019-12-27 18:53
For the other googlers, I had this problem today. What happened was all of my variables somehow were lost/reset/disappeared into the aether. I figured this out by looking at a Fiddler session and saw all my variables (urls and whatnot) were 'undefined'. I blew away the collection and re-imported it, that fixed it. 

I'm not sure what caused the vars to get wiped. Things worked fine the day before then were borked in the morning. Postman was open when I closed my laptop so maybe something when the system was waking back up? ¯\\_(ツ)_/¯

I'm on Win10, Postman 7.14.0 for those interested.

**Comment by MG-CDS** [comment] 2020-01-08 21:03
This is still an issue. My OS is Windows 8.1 64-bit, and I'm using the desktop version of Postman v7.14.0. I get the "_You seem to be offline. Any changes made while offline might not sync properly with other members of this workspace._" message several times per day. While this message is displayed, I am unable to access any of my Workspaces. This issue usually lasts no more that 5-10 seconds, but sometimes it lasts for minutes.
@numaanashraf, Please re-open and resolve this issue.

**Comment by TheVivekGowda** [comment] 2020-01-12 07:50
I have multiple postman accounts and getting same message 'You seem to be offline' error everywhere. I got this message earlier also, but its was fine after some 10-15 seconds. But this time after few hours also issue persists.

Using latest version: 
![image](https://user-images.githubusercontent.com/19553091/72215833-a0c91a80-353e-11ea-9344-c782a6550cb0.png)

**Comment by WZewdie** [comment] 2020-03-29 20:59
Is this resolve? I have 7.21.1 with the same issue.

**Comment by letanloc1998** [comment] 2020-04-15 07:09
Hey, I have got same error

**Comment by theholiday** [comment] 2020-04-15 10:54
The same.

**Comment by netbull** [comment] 2020-04-15 11:22
I'm on Mac and after creating a team the app thinks I am offline and I could not see the newly created team nor the workspace...

The Postman version is 7.22.1

**Comment by arlemi** [comment] 2020-04-15 11:24
@theholiday @netbull Your issues may be related to an ongoing incident with the app and dashboard, please check our status page and try again once the incident is resolved! Thanks for your patience in the meantime. https://status.postman.com/

**Comment by netbull** [comment] 2020-04-15 11:30
@arlemi Yes, it could be... thanks for the link, I did not saw it earlier...

**Comment by ivobarbosa** [comment] 2021-04-15 10:36
Yes is off now!

**Comment by urmichm** [comment] 2021-04-18 20:42
version 8.2.3 is offline :(

**Comment by FloatingSunfish** [comment] 2021-04-19 03:18
Still happening on 8.2.3, isn't resolving by itself, restarting my machine did not resolve the issue, and neither did uninstalling it and deleting all Postman folders.
I cannot get any work done and it is extremely frustrating!

**Comment by JoseFMP** [comment] 2021-04-19 03:21
8.2.3 and still happening. Linux. This totally bricks Postman. Cannot use it at all although internet connection is detected as off, it should be possible to just use your workspaces that were already synced.

But the real bug is that internet connection works but Postman says you're offline.

**Comment by FloatingSunfish** [comment] 2021-04-19 03:28
Petition to reopen this issue because it's still happening on the latest version, and unlike the original issue, it is not resolving by itself.
Luckily, I found the below workaround:

**_WORKAROUND:_**
Click the Gear icon and select "Scratch Pad."
You should now be able to use Postman even though it thinks you're offline.

**Comment by rhumborl** [comment] 2021-04-23 18:38
wow yes same issue. I was surprised nothing at work had been synced up to my account since I installed it there at the start of this year. Also I get an annoying update available every time I launch postman, even with latest installed. Thought maybe installing the latest 8.2.3 would help but now its bricked without the Scratchpad workaround from @FloatingSunfish 
Awful

**Comment by urmichm** [comment] 2021-04-27 21:09
I have found a great workaround here lol
https://www.thunderclient.io/

**Comment by chucknelson** [comment] 2021-06-11 17:18
I have this issue working within my company's network - it's like whatever specific host is trying to be contacted is...blocked? Anyone know where the request for workspaces / syncing is going to (what host)?

Postman 8.x has made this much more frustrating, as you can't keep working in your workspaces if Postman can't reach the sync server. 7.x would at least let you keep working and tell you sync wasn't working.

**Comment by SeppiHDamgaard** [comment] 2023-06-15 10:53
Still having this issue. Just keeps popping up every few minutes, then regains connection a few seconds later.
![image](https://github.com/postmanlabs/postman-app-support/assets/134580256/9a6eff4d-3ee7-4061-982f-42cd85aa92f9)

**Comment by Tavisca-Sachin-Panchal** [comment] 2023-07-01 05:01
facing same issue on latest version () as well 10.15.4

**Comment by nexstar-rodrigosalles** [comment] 2024-01-24 10:58
Facing the same distracting pop-up issue on mac, Postman 10.21.14

**Comment by califool** [comment] 2024-06-25 21:30
this is happening to me..... 

running:
Version 11.2.13
UI Version: 11.2.13-ui-240620-0532
Desktop Platform Version: 11.2.0 (11.2.0)

**Comment by SeppiHDamgaard** [comment] 2024-06-26 05:34
Mine stopped doing it when I disabled my VPN.

**Comment by dvaschenko** [comment] 2024-12-26 10:17
Used to have the issue, but it seems that getting to this page fixed it)))
