### ISSUE TITLE
Postman hangs if you have too much previous data

### ISSUE THREAD

**Issue by thkang2** [a85/POSTMan-Chrome-Extension#2081] opened 2016-05-25 17:57 UTC
- Please notice that scrollbar on the right is very thin (many autocomplete data)
- Postman just hangs on startup for a few seconds, If you go to location bar and try to type anything and autocomplete is triggered. I'm not on SSD
- This may be because
  - autocomplete + sync with postman server on startup is heavy load
  - or there is just too much data to autocomplete
- there should be a way to remove all thise autocomplete mess. Those URIs on autocomplete popup, I don't even use them anymore. I tried removing all chrome privacy detail and won't help, autocomplete data is still there.

Please include the following:
1. Postman Version:latest
2. App (Chrome app or Mac app): chrome
3. OS details: win7
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: always
6. Expected behaviour:
   - postman shouldn't hang
   - or there should be a way to remove all these previous connection autocompletes
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   - can't it hangs
8. Screenshots (if applicable)

**Comment by thkang2** [comment] 2016-05-25 18:00
how to reproduce: goto location bar, type `h`, wait minutes++ for postman trying to autocomplete 1000+ addresses that starts with `h` (https?:// .. everything)

**Comment by abhijitkane** [comment] 2016-07-17 08:40
@thkang2 

Can you check the console for the value of these properties - pm.urlCache.getUrls().length and pm.history.length? (https://www.getpostman.com/docs/errors)

These are all the URLs that are offered as autocomplete suggestions.

Possible duplicate of https://github.com/postmanlabs/postman-app-support/issues/2153

**Closed as completed** 2017-09-24 17:25 UTC
Labels: bug
