### ISSUE TITLE
Our business process needs to add parameters dynamically before request

### ISSUE THREAD

**Issue by xiaomaolver** [a85/POSTMan-Chrome-Extension#9011] opened 2020-09-02 03:53 UTC
Our business process needs to add parameters dynamically before request.
At present, there is no way to realize this function.

Here is the demo
![image](https://user-images.githubusercontent.com/47557223/91930117-9b5d5200-ed12-11ea-87ec-99b5741725dd.png)
![image](https://user-images.githubusercontent.com/47557223/91930244-ed9e7300-ed12-11ea-942d-f8a1256859d3.png)

**Comment by DannyDainton** [comment] 2020-09-02 05:15
Hey @xiaomaolver 

Request body can't be mutated via pre-request script at the moment, please follow #4808 for updates on this feature request.

Closing as duplicate of #4808

**Closed as completed by DannyDainton** 2020-09-02 05:15 UTC
Labels: duplicate, product/runtime
