### ISSUE TITLE
求助，pm在请求数据的时候直接闪退

### ISSUE THREAD

**Issue by jangshmily** [a85/POSTMan-Chrome-Extension#7275] opened 2019-09-06 02:11 UTC
这里是日记：
["Main~handleUncaughtError - Uncaught errors",{"name":"URIError","message":"URI malformed","stack":"URIError: URI malformed\n    at decodeURIComponent (<anonymous>)\n    at Function.ensureEncoded (C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\node_modules\\postman-collection\\lib\\util.js:62:35)\n    at PostmanCookie.update (C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\node_modules\\postman-collection\\lib\\collection\\cookie.js:205:38)\n    at new PostmanCookie (C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\node_modules\\postman-collection\\lib\\collection\\cookie.js:115:25)\n    at toPostmanCookie (C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:51:16)\n    at C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:389:38\n    at C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\lodash\\lodash.js:13806:16\n    at arrayEach (C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\lodash\\lodash.js:516:11)\n    at Function.transform (C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\lodash\\lodash.js:13805:43)\n    at C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:388:37\n    at C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\node_modules\\tough-cookie\\lib\\cookie.js:1110:5\n    at forEachWithCallback (C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\services\\CookieStore.js:674:7)\n    at next (C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\services\\CookieStore.js:82:16)\n    at _cache (C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\services\\CookieStore.js:668:9)\n    at persistentStore.get (C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\services\\CookieStore.js:466:7)\n    at Function.store.get (C:\\Users\\Administrator\\AppData\\Local\\Postman\\app-7.6.0\\resources\\app.asar\\services\\CookieStore.js:260:7)"}]

**Comment by codenirvana** [comment] 2019-09-06 04:16
Duplicate of #7268

@jangshmily Can you share more details about the request on the original thread?

**Closed as completed by codenirvana** 2019-09-06 04:16 UTC
Labels: duplicate, product/runtime

**Comment by jangshmily** [comment] 2019-09-06 06:08
Thank you！Version 7.6，I think it's the use of personal workspace，now  The old version 6.5 worked fine.

**Comment by codenirvana** [comment] 2019-09-17 07:07
@jangshmily This is fixed in the latest version of the Postman App (v7.7.2).
Can you update your app and confirm if that fixes your issue?
