### ISSUE TITLE
Add an "Export" button for the environment

### ISSUE THREAD

**Issue by Zinnurka** [a85/POSTMan-Chrome-Extension#9680] opened 2021-03-03 05:42 UTC
Please add an "Export" button for the environment  (Postman Windows v8.0.6)

![image](https://user-images.githubusercontent.com/32505382/109758014-c4509800-7c0c-11eb-9f86-234c21790d15.png)

**Comment by DannyDainton** [comment] 2021-03-03 06:36
Closing as this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9608

**Closed as completed by DannyDainton** 2021-03-03 06:36 UTC
Labels: duplicate
