### ISSUE TITLE
OAuth2 token credentials per saved request

### ISSUE THREAD

**Issue by brentco** [a85/POSTMan-Chrome-Extension#3903] opened 2017-12-05 08:35 UTC
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.10586 / x64
```

## Issue Report:
When I have request A saved in my collection, with a certain set of credentials for OAuth2, and I have a request B saved with a different set of credentials, when I try to request a new token for either, it will take the credentials that were last entered, no matter which request. 
I personally find this very unusable, because I may have different OAuth2 requirements for different requests (such as different scopes or credentials).

I would prefer if the credentials were saved on a per-request level (instead of global/per environment?)

**Comment by prashantagarwal** [comment] 2017-12-05 14:02
@brentco Thanks for reporting this. We will have a look at this.

**Comment by brentco** [comment] 2017-12-07 22:13
I'm assuming this goes for all forms of supported authentication. Thanks for the response!

**Comment by kamalaknn** [comment] 2017-12-08 05:40
@brentco Thank you for your feedback.

We have a few improvements planned for OAuth 2.0 token flows. We would want to make OAuth 2.0 credentials attached to the request just like other Authorization methods.

We are working a few other interesting features for now. We'll pick this up after this.

**Comment by bertramn** [comment] 2018-01-23 12:53
I agree with @brentco every time you switch a request or collection and fiddle with the settings, the prior settings are lost. This is particularly annoying when for some services one will need to add fancy hacks like #4051. :+1: for persisting the authorization context per collection with ability to override it per api call.

**Comment by guitar-freq** [comment] 2019-07-26 15:19
Hello, has there been any movement on this? It's quite annoying and inefficient to have to repopulate the "Get New Access Token" configuration every time. This is especially true for short lived tokens and instances where we have multiple collections requiring Oauth2.
Thanks.

**Comment by vikiCoder** [comment] 2019-07-31 07:17
Closing this as a duplicate of the following issue:
https://github.com/postmanlabs/postman-app-support/issues/4636

**Closed as completed by vikiCoder** 2019-07-31 07:17 UTC
Labels: feature, Auth, configurations, duplicate
