### ISSUE TITLE
NTLM unable to complete authentication

### ISSUE THREAD

**Issue by MADiep** [a85/POSTMan-Chrome-Extension#4355] opened 2018-03-19 16:07 UTC
## App Details:
```
Postman for Windows
Version 6.0.10
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: It has been there for a while.
 2. Expected behaviour: NTLM authentication should be successful when providing correct credentials, but appears to be failing when parsing the type 2 message. Suspicion is that the NTLM authenticator is assuming only one WWW-AUTHENTICATE header exists when there could be more than one, which is what is happening in my case (see https://github.com/postmanlabs/postman-runtime/blob/e6c7590e8542cbbce4addb0f21be814725d2168c/lib/authorizer/ntlm.js#L134). Based on analysis of the code, it appears to be taking only the last matching header (which happens to not be the NTLM header).
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
Request Headers:
cache-control:"no-cache"
postman-token:"1749bcc1-395d-4058-ba4e-240d757c5d78"
user-agent:"PostmanRuntime/7.1.1"
accept:"*/*"
host:"XXX"
cookie:"XXX"
accept-encoding:"gzip, deflate"
authorization:"NTLM XXX"

Response Headers:
content-type:"text/html"
server:"Microsoft-IIS/7.5"
www-authenticate:
0:"NTLM XXX"
1:"Negotiate"
x-powered-by:"ASP.NET"
date:"Mon, 19 Mar 2018 15:08:54 GMT"
content-length:"1293"

runtime~ntlm.auth: there was an error validating auth: ntlm: server did not correctly process authentication request
```
 4. Screenshots (if applicable): N/A

**Comment by sdnts** [comment] 2018-03-20 12:12
Hi @MADiep, thanks for reporting this. You're absolutely correct, this is an issue. We will look into this!

**Comment by harryi3t** [comment] 2018-07-02 16:01
@MADiep You are right, in the response to the TYPE-1 message where the client (Postman) has already picked an authenticate scheme (from NTLM & Kerberos) we were assuming that the server will only send one header now.
We checked an IIS server's implementation for reference. 

Since I could not find any reference which restricts this behavior, I have marked this as a bug and will update the thread once we have a fix for this.

**Comment by wstoettinger** [comment] 2018-09-18 10:22
is there any workaround until this is fixed? e.g. tweak the repsonse headers and set only one www-authenticate header before the response is processed?

**Comment by harryi3t** [comment] 2018-09-19 07:17
@wstoettinger Yes, if the server only sends one header for `www-authenticate` then it should work.
You can try our test endpoint for NTLM using the collection I have shared below
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/3a317ed4211384d8bfe9)
![postman_console_and_postman](https://user-images.githubusercontent.com/5207331/45736964-26b6a900-bc0a-11e8-8a80-60a048b1a6bd.png)

**Comment by wstoettinger** [comment] 2018-09-19 08:28
@harryi3t thanks for your quick reply. unfortunately the server sends two headers (as opposed to one comma separated) and it doesn't work out of the box. that's why I even searched for the issue and ended up here. 

My idea for a workaround would be to somehow intercept the response header, merge the two www-authenticate to one and then continue with the processing.

**Comment by rscadrde** [comment] 2018-10-22 20:36
You can use https://github.com/quaddy-services/escape-from-intranet
in your app you specify "localhost" as proxy and escape-from-intranet forwards to the corporate proxy adding the credentials.

**Comment by HrDahl** [comment] 2019-01-17 15:28
Is there any updates to this issue? I see same issue as @wstoettinger 
Here are the response header from the server I try to call:

Response Headers:
Cache-Control:"private"
Content-Type:"text/html; charset=utf-8"
Server:"Microsoft-IIS/10.0"
**WWW-Authenticate:
0:"Negotiate"
1:"NTLM"**
X-Powered-By:"ASP.NET"
Date:"Thu, 17 Jan 2019 15:21:33 GMT"
Content-Length:"6165"

**Comment by jmzagorski** [comment] 2019-01-18 13:30
I have multiple proxies at work, and for some reason one was not working (a request could not be sent), but when I changed it to our other proxy by turning off **User System Proxy** and instead select **Global Proxy Configuration** I was able to get a response from my dotnet core 2.0 app using windows authentication. Under authorization i selected NTLM Authorization [Beta] and filled in username and password using postman v6.7.1. Here is the response:

```
Transfer-Encoding →chunked
Content-Type →application/json; charset=utf-8
Server →Kestrel
Persistent-Auth →true
X-Powered-By →ASP.NET
Date →Fri, 18 Jan 2019 13:20:43 GMT
Cache-Control →proxy-revalidate
Connection →Keep-Alive
```
Not sure if this could help anyone.

**Comment by omarw** [comment] 2019-05-07 15:51
Any updates on this issue?

**Comment by FedeCanet** [comment] 2019-05-08 19:59
I'm interested too. Is there anything new to share?

**Comment by falconkirtaran** [comment] 2019-05-11 00:07
For what it's worth, I got here trying to debug why it sent NTLM but the Windows box on the other end claimed the password was bad in event logs.  It looks like it's sending Net-NTLMv1, not Net-NTLMv2; perhaps the feature should be re-labelled.  It's a shame that postman shares no supported auth mechanisms with windows integrated authentication in IIS using .net core.

**Comment by Dangerunicorn** [comment] 2019-09-30 15:19
I am encountering this same issue as well. My tests with NTLM were running fine until September 19th. Now they fail with 401 error. I am also seeing this in the console:

WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM

I am unable to use Postman with this error as 95%+ of our test suite uses NTLM.

**Comment by sthornton** [comment] 2019-11-03 19:31
Same as everyone else. 401 unauthorized consistently. Show stopper for me. Just wasted 3 hours of my life. On to a product that I know works.

**Comment by omarw** [comment] 2019-11-10 21:45
Any updates?

**Comment by coditva** [comment] 2019-11-15 14:58
@omarw Hey we've identified the issue and we're already working on a fix! Will update here once the change ships. :)

**Comment by vikiCoder** [comment] 2019-12-20 11:38
Hi everyone,

This issue is fixed in the latest release of Postman App (v7.14.0). Please update your Postman app to the latest version and let us know if you are still facing any issues regarding this.

**Closed as completed by vikiCoder** 2019-12-20 11:38 UTC
Labels: bug, Auth, product/runtime

**Comment by omarw** [comment] 2019-12-26 13:54
Latest update still doesn't work for me. I get 401 Unauthorized

**Comment by coditva** [comment] 2019-12-27 07:44
@omarw can you send us the logs you see in Postman Console? It would help us understand your case better.

The steps you took to send the request would help us reproduce the issue too.

**Comment by omarw** [comment] 2019-12-27 14:09
GET /DeploymentConfigurationApi/api/customer/customersview HTTP/1.1
Content-Type: application/json
User-Agent: PostmanRuntime/7.21.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 86284af5-09af-4d93-9870-0370d2f38aec
Host: hfdtdevsvc01-1
Accept-Encoding: gzip, deflate
Connection: keep-alive
Authorization: NTLM TlRMTVNTUAADAAAAGAAYAHgAAAAYABgAkAAAACAAIABIAAAAEAAQAGgAAAAAAAAAeAAAAAAAAACoAAAABYKIogUBKAoAAAAPSQBOAFMALgBJAE4AUwBVAFIASQBUAFkALgBOAEUAVAB3AGgAZQBhAHQAbABvAG0AwGi21gndO+kAAAAAAAAAAAAAAAAAAAAATm62x/LGgFZl3fPYbFb+OSfeM0L++EeI
HTTP/1.1 401 Unauthorized
Content-Type: text/html
Server: Microsoft-IIS/10.0
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
X-UA-Compatible: IE=edge
Date: Fri, 27 Dec 2019 14:05:54 GMT
Content-Length: 1293
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
<div class="content-container"><fieldset>
<h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
<h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
</fieldset></div>
</div>
</body>
</html>

![image](https://user-images.githubusercontent.com/6384312/71520153-a3fab000-2888-11ea-8e81-958112d064c4.png)

**Comment by coditva** [comment] 2019-12-30 06:50
@omarw This does not seem to be an issue with Postman itself. Can you try this request with `curl` to see if the credentials are indeed correct?

```bash
curl --ntlm -u username:password -Lv http://URL
```

**Comment by omarw** [comment] 2019-12-30 17:57
It worked with curl
![image](https://user-images.githubusercontent.com/6384312/71593889-b7657f80-2b03-11ea-9fe6-3e12bb268ad8.png)

With curl it automatically sent the request twice.

**Comment by omarw** [comment] 2020-02-03 13:43
These are the headers
![image](https://user-images.githubusercontent.com/6384312/73657935-457fd900-4661-11ea-887d-cab24d20f9fb.png)

**Comment by coditva** [comment] 2020-02-07 13:06
@omarw What is the domain that you're setting for the request? In `curl` I see that it is `ins`, whereas in the Postman App it seems to be `ins.insurity.net`. Can you verify this and try the request with the same domain name?

Thanks.

**Comment by omarw** [comment] 2020-02-07 16:20
@coditva Both domains are the same. ins.insurity.net is the fqdn. I tried with both in postman and it fails. Anything else I should check?

**Comment by coditva** [comment] 2020-02-11 10:34
@omarw I think the issue seems to be that the server supports only `NTLMv2` while Postman does not implement it yet. Can you verify if this is the case?

I've opened a feature request for it here: https://github.com/postmanlabs/postman-app-support/issues/8038

**Comment by omarw** [comment] 2020-02-14 13:34
@coditva I think that's it. Thanks

**Comment by dco123** [comment] 2021-08-09 10:24
Sorry to drag this up again but this isn't working for me, using 8.10.0. When the api responds with this:

HTTP/1.1 401 Unauthorized
Content-Length: 42
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
WWW-Authenticate: Negotiate,NTLM
Date: Mon, 09 Aug 2021 09:52:18 GMT
Proxy-Support: Session-Based-Authentication

Postman doesn't attempt a follow up request with credentials.

When the api responds with this:

HTTP/1.1 401 Unauthorized
Content-Length: 0
Server: Microsoft-HTTPAPI/2.0
WWW-Authenticate: NTLM
Date: Mon, 09 Aug 2021 10:14:22 GMT
Proxy-Support: Session-Based-Authentication

It does make subsequent requests using NTLM authentication, and is able to successfully call the api. The differences are the WWW-Authenticate and Content-Length / Content-Type headers (the first example above included an error message in the response content, whereas the second one didn't)

Any idea why it's not working? If the issue with the WWW-Authenticate header is supposed to be fixed, could the response content be having an impact?

**Comment by dco123** [comment] 2021-08-10 07:58
We've found that authenticate works ok when there are separate WWW-Authenticate headers in the response, e.g:

WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM

It doesn't work when they're unified, e,g:

WWW-Authenticate: Negotiate,NTLM

Which is exactly the issue described in #4711 which was closed as a duplicate of this issue (incorrectly IMO). Can someone please take another look at that?
