### ISSUE TITLE
Beautify functionality is not working

### ISSUE THREAD

**Issue by sujitblues** [a85/POSTMan-Chrome-Extension#6133] opened 2019-03-22 12:32 UTC
Hello,
I am using window native app for postman version  Postman v7.0.6.I am trying to beautify my input json using beautify button but it's not working.I have attached my screenshot below.Please look into this and what are the short-cut to beautify the json input text?

![beautify](https://user-images.githubusercontent.com/37321410/54822940-3fdd0700-4ccc-11e9-934a-2ce747ccf10c.png)

**Comment by sujayvenaik** [comment] 2019-03-22 12:40
Hey @sujitblues 
I tried with a certain nested JSON structure which seemed to work.
Can you send us this exact JSON which you are trying to beautify so we replicate this better?

**Comment by sujitblues** [comment] 2019-04-11 12:37
Hello @sujayvenaik 
Please see below json example where we can't able to beautify .

-----------------
Example 1
-----------
{
"token": "{{token}}",
  "username":{{groupid}},
"menu_timestamp": "{{menu_timestamp}}",
            "profile_timestamp": "{{profile_timestamp}}",
            "device_type":"{{device_type}}"
}
---------------------------------------------------------------------------
Example 2
-------------
{
         "token": "{{token}}",
        "group_id": {{groupid}}, 
        "group_desc": "The quick brown fox jumps over the lazy dog The quick brown fox jumps over the lazy dog The quick brown fox jumps over the lazy dog The quick brown.",
        "group_categories": [1],
        "group_members": "",
              "profile_timestamp": "{{profile_timestamp}}",
        "menu_timestamp": "{{menu_timestamp}}",
        "device_type":"{{device_type}}"
}

Example 3:
{
"token":"{{token}}",
  "profile_timestamp": "{{profile_timestamp}}",
             "menu_timestamp": "{{menu_timestamp}}",
   "group_id": {{groupid}}, 
              "categories_data": [
                   {
                        "label": "Sport"
                   },
                    {
                        "label": "Sport 1"
                   }
              ],
"Mobile": "Android",
  "req_mode": "app",
  "device_type":"{{device_type}}"

}


Sorry for delay response.Again I am not able to Beautify some json .Some times beautify is working sometimes not working.Above mentioned json,Beautify functionality is not working. Need any information please inform me

**Comment by kamalaknn** [comment] 2019-12-17 05:09
@sujitblues Thanks for the update. 

From your example, it looks like the part of your JSON `"group_id": {{groupid}},` which uses a variable for the value part of your JSON now violates the JSON syntax and prevents the body from formatted.

I'm marking this as a bug so we can take a deeper look at how we can enable formatting with this.

**Comment by kamalaknn** [comment] 2019-12-27 11:45
Hey @sujitblues 

This looks like a duplicate of #6581. I'm closing this is a duplicate. Please subscribe to the original one for updates.

**Closed as completed by kamalaknn** 2019-12-27 11:45 UTC
Labels: bug, code-editor
