### ISSUE TITLE
Add support to add file paths as environment Variables

### ISSUE THREAD

**Issue by p6345uk** [a85/POSTMan-Chrome-Extension#9336] opened 2020-12-02 11:36 UTC
Is it possible that you can add the option to specify the file path in Environment Variables as well as directly.

![image](https://user-images.githubusercontent.com/4558013/100866633-dfd2c800-3490-11eb-8609-8102edbee68b.png)

I have a number of test files these are environment specific and it would be hugely beneficial;

Alternatively is it possible for add an option to generate a dummy file e.g. $randomFile which creates a 1kb file 
https://learning.postman.com/docs/writing-scripts/script-references/variables-list/

**Comment by vikiCoder** [comment] 2020-12-07 12:36
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/5147

**Closed as completed by vikiCoder** 2020-12-07 12:36 UTC
Labels: feature, local-files, product/runtime
