### ISSUE TITLE
Requests ignoring localhost endpoint

### ISSUE THREAD

**Issue by benjamin-Keller** [a85/POSTMan-Chrome-Extension#10297] opened 2021-09-14 09:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

`GET` requests seem to just jump over our `localhost` environment endpoint, resulting in an immediate `404` status code.
`POST` requests seem to not have this issue as we've seen so far.

The `GET` request does work since after we tested the exact same endpoint in the browser it hit our breakpoint immediately.

### Steps To Reproduce

1. Open request (generated via `OpenAPI 3.0`).
2. Run request (it fails).
3. Remake the request (change it'll fix the bug).
4. Run request (if fails continue to step 5).
5. Run endpoint in browser (works).

### Screenshots or Videos

Postman:
![image](https://user-images.githubusercontent.com/42422504/133234976-19bcdf82-1d5e-4470-8666-8ba3b89f8c35.png)

Visual Studio:
![image](https://user-images.githubusercontent.com/42422504/133235341-65d51492-5a2a-4aa5-99aa-d1bee24d021a.png)
![image](https://user-images.githubusercontent.com/42422504/133235248-02ca27a9-4f8e-42e2-8bfa-f231167895a2.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Web API / Postman Desktop
- Postman Version: 8.12.2
```

**Comment by giridharvc7** [comment] 2023-01-19 12:23
@benjamin-Keller Can you share the Postman console log here, want to confirm if the `baseURL` is being parsed correctly. Something like this
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1040583/213442116-533f0e28-ec3d-4320-8d84-120e1b2f9ee7.png">

**Comment by benjamin-Keller** [comment] 2023-01-19 12:38
This is so long ago the issue was fixed by a postman reinstall

**Comment by ashuvyaspm45** [comment] 2023-04-27 05:54
@benjamin-Keller Hey thank you for the update. We will close this ticket now as the issue is resolved.

**Closed as completed** 2023-04-27 05:55 UTC
Labels: bug, product/runtime
