### ISSUE TITLE
Data export exports deleted collections.

### ISSUE THREAD

**Issue by anoiio** [a85/POSTMan-Chrome-Extension#6623] opened 2019-05-30 11:11 UTC
Data export exports deleted collections.

1. Have a collection and environments sets in postman.
2. Delete all the collections and environments.
3. Import same collections from the existing backup json file
4. Make some changes in the collections (optionally)
6. UI displays only one (imported) set of collections and environments 
5. Export data to backup json file.
6. Backup json file contains duplicate set of collections (one deleted in 2 + imported and edited in 3 and 4)
7. Environments also duplicated
8. When deleting all collections and environments again and importing file from 5, both sets of collections and environments visible in UI

Expected behavior
Only existing collections and environments are exported.

App information (please complete the following information):
 - App Type: Native App
 - Postman Version: 6.7.4
 - OS: Windows 10 Pro v1803

**Comment by numaanashraf** [comment] 2019-05-31 05:04
@anoiio Do you use multiple workspaces? And in step 2, any chance you might have done remove from workspace instead of delete workspace?

**Comment by anoiio** [comment] 2019-06-02 04:17
@numaanashraf I previously had two workplaces, but deleted one of them before I started the steps.
This deleted workplaces had different set of collections.
Step 2 I do from the 'Collections' tab and 'Manage Environments' window, one by one.

**Comment by timbochamp** [comment] 2021-02-25 22:31
I'm unable to reproduce this when using a couple collections, deleting them, and importing/exporting them by following the steps listed. I'm on the latest v8.0.6 app and on Postman for Web. I'm going to close this out but please feel free to reopen if you're still encountering this issue!

**Comment by DannyDainton** [comment] 2022-07-05 13:43
Hey @anoiio 

I'm going to close this issue due to inactivity. If this is still a problem you're facing on the latest version of the platform we can look to reopen this again.

**Closed as completed by DannyDainton** 2022-07-05 13:43 UTC
Labels: bug, exporter/postman-data
