### ISSUE TITLE
Accounts logged out on updating to 7.2.1

### ISSUE THREAD

**Issue by sankalp0o** [a85/POSTMan-Chrome-Extension#6745] opened 2019-06-19 07:07 UTC
I had multiple accounts signed in to Postman app (some 7.0+ version). I updated the app to 7.2.1 and all but one of the accounts were logged out.

**Comment by sujayvenaik** [comment] 2019-06-19 11:30
This issue is fixed in v7.2.2. Please update your app to the latest version.
In case you face any issues please log out and log in again.

Let us know if you still face any issues.

**Comment by ivanrodjr** [comment] 2019-06-19 13:45
I updated to 7.2.2 and now the issue is I cant change between users, when I try, it always returns to the same account I was.

**Comment by sujayvenaik** [comment] 2019-06-19 13:49
@ivanrodjr. Can you try logging out and logging in once with the user with which you are facing this incident? This will mostly fix the issue.
Let us know if you still face some issues.

**Comment by ivanrodjr** [comment] 2019-06-19 13:50
@sujayvenaik It worked, now I can change users without issues, thanks.

**Comment by sankalp0o** [comment] 2019-06-19 16:37
Issue looks fixed after updating to 7.2.2, all accounts restored as well.

**Comment by axelonet** [comment] 2019-06-20 03:43
It worked when I updated to 7.2.2.

**Comment by sujayvenaik** [comment] 2019-06-20 10:14
Closing this for now, if you face any other issues feel free to comment on this thread.

**Closed as completed by sujayvenaik** 2019-06-20 10:14 UTC
Labels: bug
