### ISSUE TITLE
Tab switch shortcut and customize shortcut

### ISSUE THREAD

**Issue by rajib-raiyat** [a85/POSTMan-Chrome-Extension#9076] opened 2020-09-20 05:02 UTC
Bring a future that I can **switch between tabs** with new shortcut and also need **shortcut customize option**.

**Shortcut for switch between tabs**

- To go left tab
> Alt + left arrow 

- To go right tab
> Alt + right arrow

**Comment by DannyDainton** [comment] 2020-09-20 06:59
Hey @rajib-raiyat 

You currently have 2 options to switch between tabs. These are the options for macOS.

To go to a specific tab:

```
Command + 0 > 9
```

To move left and right through the tabs:

```
Shift + Command + [ or ]
```

To show all the shortcuts, you can go to `Settings > Shortcuts` or using `Command + ?`

**Comment by rajib-raiyat** [comment] 2020-09-20 08:10
> Bring a future that I can **switch between tabs** with new shortcut and also need **shortcut customize option**.
> 
> **Shortcut for switch between tabs**
> 
>     * To go left tab
> 
> 
> > Alt + left arrow
> 
>     * To go right tab
> 
> 
> > Alt + right arrow

No I want this option. Mainly **shortcut customization options** in cross platform

**Comment by arlemi** [comment] 2023-02-13 11:04
Closing as duplicate of #2096

**Closed as completed by arlemi** 2023-02-13 11:04 UTC
Labels: feature, shortcuts, product/client-foundation
