### ISSUE TITLE
Duplicated tab override another ones

### ISSUE THREAD

**Issue by pazfelipe** [a85/POSTMan-Chrome-Extension#9663] opened 2021-02-25 12:13 UTC
**Describe the Issue**
When I try to save a duplicated tab, the original tab is override with duplicated tab's information, 

**Steps to Reproduce**
Create a tab, put some content in it and save it.
Duplicated it, put some content in the duplicated tab and save it. Both tabs will get same content, title, method.

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/19727571/109151774-5c500c80-7749-11eb-89b6-4adfb648ce3b.png)

Before save the duplicated tab.

![image](https://user-images.githubusercontent.com/19727571/109151837-71c53680-7749-11eb-95cf-ff0110441b43.png)

After save it.

**Environment Information**

 - Postman Version: Postman v8.0.1 - v8.0.6
 - Operating System: Windows 10

**Comment by DannyDainton** [comment] 2021-02-25 12:59
This is the intended behaviour when duplicating a tab - You would need to duplicate the request from the sidebar to get a different copy.

> Duplicating a tab does not mean creating a second request to the same endpoint—when you duplicate a tab any edits you make will affect the original request.

https://learning.postman.com/docs/getting-started/navigating-postman/#tabs

**Comment by DannyDainton** [comment] 2021-02-25 13:20
Closing this one as it appears to be working as intended.

**Closed as completed by DannyDainton** 2021-02-25 13:20 UTC
Labels: tabs
