### ISSUE TITLE
Error in methods after a Postman Update

### ISSUE THREAD

**Issue by Wolvie1975** [a85/POSTMan-Chrome-Extension#13005] opened 2024-07-12 15:03 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

There was an update to the desktop made recently (7/11/2024 or 7/12/2024) that has now introduced an error to  Pre-request Scripts section in methods that were working the previous day..

I have attached the error I am getting now. 

I am going to continue to figure out a solution on my end. But I will need some assistance on yours.

### Steps To Reproduce

Ran a method when running a debug

### Screenshots or Videos

![Screenshot ERROR 0712](https://github.com/user-attachments/assets/69553867-b0d9-44d4-91f0-db7286f26331)

### Operating System

Windows

### Postman Version

11.3.2

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

This code is used in a lot of our methods. So I might need some solution that we need to adjust moving forward with how the app now works.

var skip = pm.variables.get("skip");
if( !skip) {
    pm.variables.set("skip", 0);
}
var take = pm.variables.get("take");
if( !take) {
    pm.variables.set("take", 50000);
}

**Comment by codenirvana** [comment] 2024-07-12 15:38
@Wolvie1975 can you share a scaled-down collection that we can use to reproduce this issue?

Do you have a pre-request script at the collection level as well? I cannot reproduce this using the code snippet you shared above.

**Comment by appurva21** [comment] 2024-08-14 13:58
I'm closing this issue for now, but if you're still experiencing it in the latest version, please share the previously requested details so we can investigate further

**Closed as completed by appurva21** 2024-08-14 13:58 UTC
Labels: product/api-client
