### ISSUE TITLE
Generate Code Snippets Not Functioning with Parametrised Values in URI Address Bar 

### ISSUE THREAD

**Issue by mi-akram** [a85/POSTMan-Chrome-Extension#6175] opened 2019-03-28 15:22 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Generate Code snippets only seems to be working for requests that have hard coded locations in the address bar and not when using environment variables. I believe this could be due to the parameterised variables being used in the URI / address bar as when I hard code the base url and location the code snippets function as expected. Code snippets requests that include a hard coded address are persisted when selecting to generate a code snippet for a request that has a paramaterised value. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a basic request on postman
2. Click on the code link and select cURL from the available options
3. You will see the the cURL code snippet created
4. Exit the generate code snippet window and configure a new request in a new tab.
5. Click on Code - cURL should be preselected, which it is however the details of the code snippet are incorrect as it still persists with the details from request one.

**Expected behaviour**
I would expect the generate code snippets to output valid and correct code snippets for any of the syntax standard available from the dropdown and correctly reflect the request within the selected tab.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Chrome App
 - Postman Version: 7.0.6
 - OS: macOS Mojave 10.14.4

**Additional context**
Screen shot attached.

**Comment by mi-akram** [comment] 2019-03-28 15:23
<img width="1680" alt="Postman Bug" src="https://user-images.githubusercontent.com/20515286/55169852-663bf000-516d-11e9-84a7-aeca8270855b.png">

**Comment by mi-akram** [comment] 2019-03-28 16:14
Below screen shot shows generate code snippet window with not code snippet details when an parameterised environment variable is used.
<img width="1489" alt="Postman Bug 2" src="https://user-images.githubusercontent.com/20515286/55174125-c71af680-5174-11e9-8db4-463cf6509bae.png">

**Comment by sujayvenaik** [comment] 2019-03-29 05:11
Hey @mi-akram 
I tried reproducing this issue but could not. Attached a screen recording what I did.
Can you tell us where we went wrong and how can we replicate this behaviour?

![clientApp-codeGen-bug](https://user-images.githubusercontent.com/11532114/55210794-275e7680-520f-11e9-869f-9ce1a22d3a5d.gif)

**Comment by mi-akram** [comment] 2019-04-01 10:07
Can you try pushing your environment variables into environments as illustrated in this screen sht:
<img width="1680" alt="Screenshot 2019-04-01 at 11 06 27" src="https://user-images.githubusercontent.com/20515286/55320116-51fa3a80-546e-11e9-8bfa-343164812627.png">

**Comment by mi-akram** [comment] 2019-04-01 10:32
Hi sujayvenaik, I think I may have some information for you on this. If I create a global environment and use this in my request it works. However my env variables are set within environments as shown in the above screen shot. Can you also ensure that the specific environment is selected on the main window when to check if the code snippets work.

**Comment by sujayvenaik** [comment] 2019-04-01 10:43
Hey @mi-akram 
The above screenshot that I had posted, I have an environment there E1 which is the one I have selected. Also, using the quick look I show that the variables are there.

Can you provide us with a screen recording with the exact steps on how to reproduce it?
Also after selecting your environment and before pressing Code can you once click on the quick look (eye icon) to check that your environment is populated.

**Comment by mi-akram** [comment] 2019-04-01 11:21
Hi sujayvenaik see attached video screen recording:
[ScreenRec1.mov.zip](https://github.com/postmanlabs/postman-app-support/files/3029077/ScreenRec1.mov.zip)

**Comment by mi-akram** [comment] 2019-04-01 14:17
Hi sujayvenaik, 
I have been doing some further testing around this can can confirm that the `Generate code snippet` for other requests in other collections seem to work as expected. However,  I am unable to determine what is different and why it not functioning as expected with my Hello World collection. This has always worked and I believe I may have lost this functionality with one of the recent updates. In order to resolve I have even uninstalled the application, removed all references and caches for the application, removed the collection and re-importing but none seem to have an affect. I have also included another video for you to view. Any suggestions would be most appreciated.

[ScreenRec2.mov.zip](https://github.com/postmanlabs/postman-app-support/files/3029814/ScreenRec2.mov.zip)

**Comment by sujayvenaik** [comment] 2019-04-01 23:44
Hey @mi-akram 
Can you send us the logs from View -> Developer -> View logs in finder? Need to check if any errors are logged.

Also is it only that variable that is buggy or other variables are also not getting resolved?

**Comment by mi-akram** [comment] 2019-04-02 13:09
It just seems to be the {{hello-world-url}} variable. The others seems to be working fine. Please see a copy of the logs attached. The logs were initially cleared, and then the issue was reproduced.  I have had a look and van not seen anything obvious. I have also try to reset, delete and also create the variable again which has not had any effect.
[Logs.zip](https://github.com/postmanlabs/postman-app-support/files/3034045/Logs.zip)

**Comment by mi-akram** [comment] 2019-04-02 13:32
Hi sujayvenaik, 
I think I have fixed the problem. I resolved this. Deleting the variable and then creating a new one with the same name, typing out the current value for the variable and then tabbing across to the initial value. When tabbing across the field was automatically populated. I went back to check and now the code snippets were working. Awkwared but all is working now. Appreciate all your help and assistance with my ticket. Feel free to close.

**Comment by sujayvenaik** [comment] 2019-04-03 06:48
Hey @mi-akram 
Thanks for cooperating. Closing this issue for now, feel free to reopen if you face any other issues with this. Will be glad to help.

**Closed as completed by sujayvenaik** 2019-04-03 06:48 UTC
Labels: bug, code-generator

**Comment by iteratelance** [comment] 2019-11-30 09:54
I was able to reproduce this issue.  I discovered that the root cause is have a leading space in an environment variable.

For example GET `{{base_url}}/some/path`
For instance base_url=`^http://example.com`, where `^` is leading whitespace will cause code snippets for curl and other languages to break.

Solution, remove leading white space. base_url=`http://example.com`
