### ISSUE TITLE
Clicking on Mock Call Logs is redirecting to 401 request expired page. 

### ISSUE THREAD

**Issue by srinivasskc** [a85/POSTMan-Chrome-Extension#8867] opened 2020-07-31 12:14 UTC
**Describe the bug**
When I click on Mock Call Logs after creating a mock server for collection, it is redirecting to 401 request expired page. 

**To Reproduce**
1. Go to 'Collection'
2. Click on '> arrow and then Mocks'
3. Click on  'Add Mock'
4. Enter Mock Server Name as JSONMock with Version Tag=Current , Environment selected
5. Click on Create Mock
4. Then click on Mock Call Logs link

**Expected behavior**
It should open Mock Call logs interface

**Screenshots**
![image](https://user-images.githubusercontent.com/26836928/89033525-93497580-d354-11ea-849f-7f3ca5b4f0d1.png)

![image](https://user-images.githubusercontent.com/26836928/89033252-01da0380-d354-11ea-9675-7095c39bdb8c.png)

![image](https://user-images.githubusercontent.com/26836928/89033217-f2f35100-d353-11ea-8ea3-e7a849b947a0.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [v7.29.1]
 - OS: [Windows 10 - 64 Bit]

**Additional Context**
Note: I had logged into https://web.postman.co/ account also and then re-loaded the webpage

**Comment by Raj-postman** [comment] 2020-08-05 11:46
Hi @srinivasskc, I tried to replicate the entire flow and was unable to reproduce this.

![image](https://user-images.githubusercontent.com/47771757/89409073-16950d80-d73f-11ea-84bf-0669cc2a48ae.png)

Could you please try & see if you are still facing this issue and write to us at help@postman.com if the issue persists? Once received we will check on this further.

**Comment by srinivasskc** [comment] 2020-08-07 07:38
Hi @Raj-postman 
I am trying to access the mock call logs from Postman App (not from website)

I selected the Run -> Mocks -> 
![image](https://user-images.githubusercontent.com/26836928/89621086-5f1f0900-d8ae-11ea-9081-dfc2bc6447c5.png)

Then selected Add Mock
![image](https://user-images.githubusercontent.com/26836928/89621138-75c56000-d8ae-11ea-93bd-fa8117d5b8a3.png)

Then clicked on Mock Call Logs
![image](https://user-images.githubusercontent.com/26836928/89620966-2121e500-d8ae-11ea-9397-bc6a8364c24c.png)

It is displaying 401 error.
![image](https://user-images.githubusercontent.com/26836928/89621037-47e01b80-d8ae-11ea-9990-ad1185b73a32.png)

**Comment by Raj-postman** [comment] 2020-08-07 07:59
@srinivasskc Thank you! I did try the same steps via the app and that link redirected me to the web - Could you please [submit a ticket via this page here](https://support.getpostman.com/hc/en-us/requests/new) with the title`GH #8867` and we'll help you with the steps to grab some logs for us to check this further?

**Comment by srinivasskc** [comment] 2020-08-07 08:14
Thank you @Raj-postman. I have submitted the request https://support.postman.com/hc/en-us/requests/55209

**Comment by Raj-postman** [comment] 2020-08-20 04:11
@srinivasskc Marking this as close since the issue is now resolved via ticket. Feel free to reopen if the error repeats :)

**Closed as completed by Raj-postman** 2020-08-20 04:11 UTC
Labels: support, product/mocks
