### ISSUE TITLE
When adding email symbol @ to Team on Mac @ end email typing. 

### ISSUE THREAD

**Issue by Neogene** [a85/POSTMan-Chrome-Extension#8340] opened 2020-04-15 14:35 UTC
**Describe the bug**
When typing email address symbol @ when adding email to invite inside Team typing ends and

**To Reproduce**
1. Go to 'INVITE' top button
2. Type "info@"
3. Typing ends creating [info] avoiding to typing correct email eg: iinfo@test.it

**Expected behavior**
@ doesn't end email typing OPTION + @ symbol
<img width="687" alt="Schermata 2020-04-15 alle 16 22 15" src="https://user-images.githubusercontent.com/2322707/79348455-50929780-7f35-11ea-8821-ad4a1b2f2af4.png">

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version  7.22.1
 - OS: Mac OS 10.14.6 Mojave 

**Additional context**

**Comment by sankalp0o** [comment] 2020-04-18 06:55
Thanks for reaching out @Neogene ! I understand your problem but I'm not able to reproduce it. We'll do some more digging around to see what might be causing this. We'll get back to you if we need any more info from you to debug this.

**Comment by sankalp0o** [comment] 2020-04-20 07:51
@Neogene could you please attach a video so that we are able to better understand how you're running into this issue? We've tried multiple things but we're unable to reproduce this.

**Comment by avani-n** [comment] 2020-04-20 10:17
@Neogene Getting a GIF/Video will help tremendously. You can also send the relevant screenshots/gifs to help@postman.com with this github issue id mentioned in subject.

**Comment by sankalp0o** [comment] 2020-04-30 05:57
Hey @Neogene , 
We tried reproducing this issue but weren't able to. I'm closing this but if this problem persists, please do let us know!

**Closed as completed by sankalp0o** 2020-04-30 05:57 UTC
Labels: bug
