### ISSUE TITLE
Application is too slow and switching tabs becomes impossible

### ISSUE THREAD

**Issue by santosh-hegde** [a85/POSTMan-Chrome-Extension#7699] opened 2019-11-26 06:26 UTC
**Describe the bug**
I have 3 tabs open, which makes GET call to 3 different end points returns around 4MB data each.
Once the call completes, I can’t switch to any other tabs. All buttons become unresponsive.

**Expected behavior**
For 4MB of data, application should behave like this.

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version : 7.12.0 
 - OS:  macOS High Sierra 10.13.6

**Additional context**
On restart, it works fine.

**Comment by kamalaknn** [comment] 2019-12-02 07:20
@santosh-hegde  This looks like a duplicate of #4687 or #7294. 

I'm closing this as a duplicate. Could you update the relevant thread with your inputs?

**Closed as completed by kamalaknn** 2019-12-02 07:20 UTC
Labels: performance
