### ISSUE TITLE
Application Keeps Refreshing failing to open in Windows 8.1

### ISSUE THREAD

**Issue by mariojulian** [a85/POSTMan-Chrome-Extension#5801] opened 2019-01-21 16:59 UTC
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by SamvelRaja** [comment] 2019-01-22 03:48
@mariojulian  Could you give us more information on the issue?
Screen shot or a screen capture video would be useful.

**Comment by mariojulian** [comment] 2019-01-22 05:15
Hello,
The issue is resolved. The issue was related to the GPU. I had to set the
env variable POSTMAN_DISABLE_GPU to false.
Thanks for the support.
I will update the same in the forum.

**Comment by numaanashraf** [comment] 2019-01-22 05:33
Duplicate of #4594

**Closed as completed by numaanashraf** 2019-01-22 05:33 UTC
Labels: duplicate
