### ISSUE TITLE
Form-data with files upload is crashing the app in certain cases

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6752] opened 2019-06-19 13:22 UTC
**Describe the bug**
When sending a request that has a file attached, this user gets an error "Something went wrong" 

**Screenshots**
![image](https://user-images.githubusercontent.com/10200603/59768983-2d5b7500-929d-11e9-9dee-50859c295fe4.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version 7.2.0
 - OS: Windows

**Comment by saswatds** [comment] 2019-06-20 07:26
@labifrancis I have been able to replicate this issue. Will apply the fix ASAP

**Comment by saswatds** [comment] 2019-06-27 06:50
@labifrancis The fix for this has been applied on `7.3.0-canary04`. Can you confirm if the issue is resolved in canary?

**Comment by labifrancis** [comment] 2019-07-01 13:45
@saswat The user is getting this error "could not get any response"

**Comment by saswatds** [comment] 2019-07-01 14:07
`Could not get any response` error occurs usually when the server fails to respond. Can you confirm that `Something Went Wrong` crash is no longer happening?

**Comment by labifrancis** [comment] 2019-07-03 09:13
The user is not getting this error again `Something Went Wrong`

**Comment by saswatds** [comment] 2019-07-23 20:49
The latest version of app v7.3.4 has the fix for this. Closing issue

**Closed as completed by saswatds** 2019-07-23 20:49 UTC
Labels: bug, product/runtime
