### ISSUE TITLE
AWS SIGV4 signature mismatch with "binary" payload

### ISSUE THREAD

**Issue by webbnh** [a85/POSTMan-Chrome-Extension#3232] opened 2017-07-03 18:54 UTC
## App Details:
```
Postman for Mac
Version 5.0.2 (5.0.2)
OS X 10.10.5 (14F2411)
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:  I don't know -- I've only tried this feature recently, and it has yet to work for me.
 2. Expected behaviour:  a successful PUT operation.
 3. Console logs:
```
PUT https://b________4.execute-api.us-east-2.amazonaws.com/prod/upload/test.txt
02:27:50.624
Request Headers:
cache-control:"no-cache"
Postman-Token:"91170cd9-5bb4-460f-af52-49e88b72e0cb"
Content-Type:"application/octet-stream"
X-Amz-Date:"20170703T182750Z"
Authorization:"AWS4-HMAC-SHA256 Credential=A__________________A/20170703/us-east-2/execute-api/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=624495497a6d49da51395139ab82895e12a584a86cd49efc86da8be2cb5f6ec9"
User-Agent:"PostmanRuntime/6.1.6"
Accept:"*/*"
Host:"b________4.execute-api.us-east-2.amazonaws.com"
accept-encoding:"gzip, deflate"
Response Headers:
content-type:"application/json"
content-length:"691"
connection:"keep-alive"
date:"Mon, 03 Jul 2017 18:27:50 GMT"
x-amzn-requestid:"522a9601-601d-11e7-8788-d94a8b2cdb4c"
x-amzn-errortype:"InvalidSignatureException"
x-cache:"Error from cloudfront"
via:"1.1 cf50699455d063ab813aee70063811cf.cloudfront.net (CloudFront)"
x-amz-cf-id:"UxKWRtoqKo_Pixe2N1zSAhFSKadHLED1HcrruQxfjjjTaRpzpwbCjw=="
Response Body:
message:"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. The Canonical String for this request should have been 'PUT /prod/upload/test.txt content-type:application/octet-stream host:b________4.execute-api.us-east-2.amazonaws.com x-amz-date:20170703T182750Z content-type;host;x-amz-date b1708ee123c0114cfbc206db10518b418beab5b2224d6c10911fc3d55e026e17' The String-to-Sign should have been 'AWS4-HMAC-SHA256 20170703T182750Z 20170703/us-east-2/execute-api/aws4_request 42237e2030c6c1f1fbd3ee10a295763b003fa9aa98e98ef4c04940b1a1063544' "
Request Body:
content:
src:"/Users/scalesw/Documents/How to install Andriod on the HP TouchPad.rtf"
```

 4. Screenshots (if applicable) : N/A

I've got an AWS API Gateway set up, and I'm trying to upload a file via a `PUT` operation.  The upload worked fine until I turned on IAM-based authorization in AWS.  Now in Postman, after selecting "AWS Signature" for the Authorization Type and entering my AccessKey, SecretKey, AWS Region, and Service Name (leaving the Session Token blank), I get the signature mismatch reported above when I use a "binary" body and select a file.  If I select "raw" and just type some text in, the upload works, so I think it's something specific to using a payload from a file.  (Exporting the request as a cURL command didn't work, either.)

**Comment by sdnts** [comment] 2017-07-04 07:48
Hi @webbnh, thanks for reporting this. We'll look into this and I'll let you know what we find :)

**Comment by lukeinage** [comment] 2017-07-07 08:33
Can confirm the same issue, it happens every time when selecting a file.
Without a file the request is successful.

Postman for Mac
Version 5.0.2 (5.0.2)
OSX 10.12.5 (16F73)

**Comment by appsassociates-dev** [comment] 2017-08-02 15:41
is there any solution, I could still see the issue.

**Comment by sdnts** [comment] 2017-08-03 10:00
Guys, we'll be taking a better look at auth helpers in the near future, we'll take this up then. You can follow our [product roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers) for updates

**Comment by saikatmohajan** [comment] 2017-09-12 17:33
Any update on this issue. I am having the exactly issue. It appears that  there is no way to do a binary upload to the api gateway.

**Comment by jpete-ksc** [comment] 2017-09-21 18:36
Same exact issue for me. I have created api gateway methods for downloading and uploading files to S3. Downloading files using Postman and the api gateway GET method works just fine. However, uploading a binary file using the PUT method does not work when I select an attachment to upload:

    "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been....

As others have noted, the PUT method succeeds if i don't select an attachment and just enter the raw text instead.

**Comment by westover** [comment] 2017-10-08 06:15
Also appears to be a problem with raw input

**Comment by cyrilhamidechi** [comment] 2017-10-26 16:37
Hello @madebysid 

>Guys, we'll be taking a better look at auth helpers in the near future

Thanks a lot for your work and your response but it does not help...
Actually, this is not about "taking a better look at auth helpers".
It's about fixing the SIGv4 support for binary payload.

Is there any known workaround?

Again, great thank you for your work and help on this useful tool

Best,

Cyril

**Comment by harryi3t** [comment] 2017-11-20 08:42
@cyrilhamidechi @webbnh and all
I have confirmed this behaviour and marked it as a bug
I will update this thread as soon as we have this on our immediate roadmap.

**Comment by maddog666** [comment] 2018-02-05 06:12
Got the same error. 
How is that fix coming?

**Comment by waliaraman** [comment] 2018-02-22 00:29
Thanks guys for the great work. Love Postman. 
However, I just faced the same issue. Lost half a day trying to debug the issue. 
Any ETA on the fix. 

Raman

**Comment by JuergenSimon** [comment] 2018-02-27 11:25
Same here. Any news on the fix? Or at least a workaround?

**Comment by jamie--stewart** [comment] 2018-03-27 15:30
Hi, I'm also seeing this issue when trying to PUT a Swagger schema into an existing API Gateway:

PUT `https://apigateway.eu-west-1.amazonaws.com/restapis/<API_ID>?basepath=prepend&mode=merge`

The Swagger document is JSON in the body of the request. 

Any word on a workaround for this?

**Comment by mkain0** [comment] 2018-04-19 18:53
Anyone knows something about this update?

**Comment by sky-wang** [comment] 2018-04-25 03:13
Any update?

**Comment by VitorBrangioni** [comment] 2018-07-23 23:21
Same problem, any solution?

**Comment by binitshah** [comment] 2018-07-31 03:20
Hey guys, still facing this issue.

**Comment by numaanashraf** [comment] 2018-08-10 12:10
https://github.com/mhart/aws4/blob/master/aws4.js#L116

**Comment by mr-fixit** [comment] 2018-08-22 21:59
I had the this error, in my case I was using a pre-signed upload URL, and the error message from the server included

    <StringToSign>PUT
        application/octet-stream 1535007327
        /secureurl/foo/bar/baz/workaround.mp4
    </StringToSign>

I would have loved for the server to tell me what it was expecting, as it did for the OP.  But once I saw that the value of the Content-Type header was used when calculating the signature, I tried various values for 'Content-Type' until I stumbled on "". Yes, a empty string.

curl does this by default. Postman had to be told specifically to use "". If I didn't specify it in Postman, then it used 'application/octet-stream'. NSURLRequest (a macOS/iOS thing) also has to be told, otherwise a default value is injected.

I realize this info probably won't help the OP.  I hope it helps someone.

**Comment by AlexCatch** [comment] 2018-09-07 12:49
This is still an issue over a year since the first report.

**Comment by codenirvana** [comment] 2019-03-28 21:44
We've released a fix for this on our Canary (`version: 7.1.0-canary01`) channel https://www.getpostman.com/canary

Please try it out in the Canary version and let us know if you continue to face the issue.
Will update the thread once we release the fix on our stable channel.

**Comment by lubao** [comment] 2019-04-04 06:24
It works on Canary release. Thanks for fix the issue. :)

**Comment by codenirvana** [comment] 2019-04-23 17:29
This has been fixed in the latest Postman app.

**Closed as completed by codenirvana** 2019-04-23 17:29 UTC
Labels: bug, Auth, product/runtime

**Comment by YaromyrS** [comment] 2023-11-29 13:00
> I had the this error, in my case I was using a pre-signed upload URL, and the error message from the server included
> 
> ```
> <StringToSign>PUT
>     application/octet-stream 1535007327
>     /secureurl/foo/bar/baz/workaround.mp4
> </StringToSign>
> ```
> 
> I would have loved for the server to tell me what it was expecting, as it did for the OP. But once I saw that the value of the Content-Type header was used when calculating the signature, I tried various values for 'Content-Type' until I stumbled on "". Yes, a empty string.
> 
> curl does this by default. Postman had to be told specifically to use "". If I didn't specify it in Postman, then it used 'application/octet-stream'. NSURLRequest (a macOS/iOS thing) also has to be told, otherwise a default value is injected.
> 
> I realize this info probably won't help the OP. I hope it helps someone.

Thank you! You saved me from 2 more days of investigation
