### ISSUE TITLE
Changes in collection not sync to Monitor

### ISSUE THREAD

**Issue by drorwb** [a85/POSTMan-Chrome-Extension#9306] opened 2020-11-22 10:37 UTC
I created a monitor from collection in the app.
After edit the requests in the collection locally and even click the sync button the requests the monitor is running stay same as they were before my changes.
Only after change the collection name and than create again monitor it's sync.
Any solutions?

**Comment by DannyDainton** [comment] 2020-11-23 09:40
Hey @drorwb 

Could you include the version and OS that you're using, please?

Also, any screenshots or a recording which shows the issue will help us to investigate the problem.

**Comment by VicKetchup** [comment] 2020-11-23 11:10
Facing the same issue, started happening on Thursday. The changes done then are now in monitors however new changes are still taking their time. I am  on macOS Catalina (10.15.7) using Postman 7.34.0 (can't use 7.35 due to https://github.com/postmanlabs/postman-app-support/issues/9230)

**Comment by drorwb** [comment] 2020-11-23 12:53
> Hey @drorwb
> 
> Could you include the version and OS that you're using, please?
> 
> Also, any screenshots or a recording which shows the issue will help us to investigate the problem.

Version 7.36.0
win32 10.0.19041 / x64

**Comment by godfrzero** [comment] 2020-11-24 02:56
Hey @drorwb @VicKetchup,

When you're seeing this delay, could you open up https://go.postman.co and see if the changes are reflected in the same collection there?

**Comment by godfrzero** [comment] 2020-11-24 08:59
Nvm, we were able to recreate the issue. We're looking into the cause.

**Comment by godfrzero** [comment] 2020-11-24 10:33
@drorwb @VicKetchup Could you let me know if you're still seeing this problem?

**Comment by VicKetchup** [comment] 2020-11-24 11:39
@godfrzero we just merged some changes to a branch with the monitor and unfortunately monitor run didn't get the up-to-date code. I went to https://go.postman.co/ and saw the changes refrected there though.

**Comment by godfrzero** [comment] 2020-11-25 05:21
@VicKetchup Could you send us the monitor ID or collection ID at help@postman.com? The issue appears to be resolved based on what I can see internally, so I want to make sure it's not an intermittent issue with specific resources.

**Comment by VicKetchup** [comment] 2020-11-25 09:50
@godfrzero After trying this morning with a new change, everything seems to be good now :) Thanks for your help!

**Comment by godfrzero** [comment] 2020-11-30 08:06
Closing this ticket since the issue has been resolved.

**Closed as completed** 2020-11-30 08:06 UTC
Labels: bug, sync, product/automation-testing
