### ISSUE TITLE
Sign DLLs installed with postman.

### ISSUE THREAD

**Issue by Alslinet** [a85/POSTMan-Chrome-Extension#5771] opened 2019-01-14 08:27 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When doing whitelisting With Microsoft Application Control or Applocker, its useful to be able to allow code signed With a specific signature to run. This makes Your rules Version independant.

But in postmans case the DLL files used are not signed and therefore you have to resort to using hash based rules or folders (Folders is a bad idea when the files end up in the users profile)

**To Reproduce**
1. Enable Applocker With default rules and DLL enforcement
2. Try to run or update postman

**Expected behavior**
Applocker will Block postman

**Screenshots**
Not applicable

**App information (please complete the following information):**
Native app
Current version.

**Comment by harryi3t** [comment] 2019-05-08 09:39
@Alslinet 
Could you help me in setting the correct rules so that I can reproduce this?
I have tried enabling the `App locker` with DLL rules and have added the default rules.

![image](https://user-images.githubusercontent.com/5207331/57365684-2ff98380-71a3-11e9-84df-516263b03548.png)

I have also tried creating another standard account (non-admin), but in that also I was able to install and open Postman

**Comment by Alslinet** [comment] 2019-05-08 21:41
I think it happens when you install the app as a non admin maybe. Its been
a while since i had to deal with this.
Or maybe it was the updater that had issues.

ons. 8. mai 2019 kl. 11:40 skrev Harendra Singh <notifications@github.com>:

**Comment by harryi3t** [comment] 2019-06-20 09:20
Closing this since this is not happening anymore.

**Closed as completed by harryi3t** 2019-06-20 09:20 UTC
Labels: bug, platform/windows, updates
