### ISSUE TITLE
Unable to signin / signup to postman

### ISSUE THREAD

**Issue by rvnath** [a85/POSTMan-Chrome-Extension#1763] opened 2016-02-29 10:31 UTC
If I try to sign in to my account (or try to create a new account), postman shows up error label 

> Something went wrong. Please try again later.

As a result, unable to access my account.  Can this be more descriptive, or provide some helpful hints on what went wrong (assuming invalid credentials, or anything else to do with wrong input)?  Or is this a server side error, such as service is down..?

**Comment by abhijitkane** [comment] 2016-02-29 10:34
@rvnath The service seems to be up - we're seeing signups as well. Can you send an email to help@getpostman.com with your username / emailID?

**Comment by rvnath** [comment] 2016-02-29 17:51
It is working from my home location (direct internet connection).  Will chk again tomorrow from office (corporate proxy with authentication).

**Comment by hardikramwani** [comment] 2016-03-01 15:52
I am facing same issue, in other location working proper. Version 3.2.20 (packaged) OS: win
In below image after clicking on "Proceed to app.getpostman.com(unsafe)". It's able to login.
![connection](https://cloud.githubusercontent.com/assets/3940294/13432192/9e951138-dff2-11e5-9773-3a21b9ad2a2a.jpg)

But while i sign in, i got process bar and than offline status. API Collection is not sync.

![offline1](https://cloud.githubusercontent.com/assets/3940294/13432419/85562e22-dff3-11e5-9a75-a9b5216dbf45.jpg)

I have try lots of things, but not get any Success.

**Comment by abhijitkane** [comment] 2016-03-01 16:22
@hardikramwani This seems like an issue with your proxy. Can you try heading to https://app.getpostman.com/client-login?redirect=web&persistent=true in your browser? You should see the same "Your connection is not private" error. Click on the green padlock to view the certificate info - you should see that the certificate issuer etc. is invalid.

Are you able to browse facebook properly?

**Comment by hardikramwani** [comment] 2016-03-01 17:28
Yes it may me certificate issue, but how can i resolve it ? Below are some screen shots.

![cert_1](https://cloud.githubusercontent.com/assets/3940294/13435599/16997152-e001-11e5-9cae-8749b121c42a.jpg)
![cert_2](https://cloud.githubusercontent.com/assets/3940294/13435601/16c4bdc6-e001-11e5-8e2c-482c0dfa4fcf.jpg)
![cert_3](https://cloud.githubusercontent.com/assets/3940294/13435602/16c68232-e001-11e5-83cb-08d127f0b667.jpg)
![cert_4](https://cloud.githubusercontent.com/assets/3940294/13435603/16eb72d6-e001-11e5-94ea-ef4d7de95693.jpg)

certificate will be install automatically when install Postman APP right ?
I have reinstall chrome browser, deleted all history, tried all things. But not working.

**Comment by abhijitkane** [comment] 2016-12-22 21:01
@hardikramwani Feel free to re-open if you're still facing this issue.

**Closed as completed by abhijitkane** 2016-12-22 21:01 UTC
Labels: support

**Comment by oleksandrzelentsov** [comment] 2017-07-28 08:03
i cannot sign in now, it says
```Something went wrong. Please try again later.```

**Comment by JonasGao** [comment] 2017-07-28 08:23
@oleksandrzelentsov +1

**Comment by aligang** [comment] 2017-07-28 08:58
@**oleksandrzelentsov** +1

**Comment by MiaLinke** [comment] 2017-07-28 09:30
I also had same problem: 
I cannot login :( 
Something went wrong. Please try again later.

**Comment by oleksandrzelentsov** [comment] 2017-07-28 09:32
i think it is because they have some problem in their server


2017-07-28 11:30 GMT+02:00 Mia Linke <notifications@github.com>:

**Comment by MiaLinke** [comment] 2017-07-28 09:33
@oleksandrzelentsov  Thank you for information.
Where can we report this issue. I will mail to help@getpostman.com :)

**Comment by sdnts** [comment] 2017-07-28 09:38
Guys, we had an issue with our login service during deployment, it should be up very soon. You can track status [here](http://status.getpostman.com)

**Comment by oleksandrzelentsov** [comment] 2017-07-28 09:39
thanks for info

2017-07-28 11:38 GMT+02:00 Siddhant Sinha <notifications@github.com>:

**Comment by MiaLinke** [comment] 2017-07-28 09:54
@madebysid  Thank you for Info.

**Comment by oleksandrzelentsov** [comment] 2017-07-28 10:25
@madebysid hey it still doesn't work, define "pretty soon" plz, tasks are hanging time is passing

**Comment by oleksandrzelentsov** [comment] 2017-07-28 10:26
now it says
`Your session has expired. Please sign in again.`

**Comment by oleksandrzelentsov** [comment] 2017-07-28 10:27
and after that it says "Something went wrong" again

**Comment by oleksandrzelentsov** [comment] 2017-07-28 11:44
looks like it works now, thanks to everybody helping

**Comment by sdnts** [comment] 2017-07-28 11:52
Things are back to normal now. You should be able to login to the app as well as the website.

**Comment by ashlindias06** [comment] 2018-01-21 22:33
I am unable to log in, says following
![screen shot 2018-01-22 at 9 32 46 am](https://user-images.githubusercontent.com/26864072/35199786-46b5627a-ff57-11e7-8bd2-f8f9e7a9b035.png)

**Comment by kunagpal** [comment] 2018-01-21 22:40
@ashlindias06 We're currently working on resolving this, you can track the current status via [status.getpostman.com](http://status.getpostman.com).

**Comment by ashlindias06** [comment] 2018-01-22 01:00
Hey, @kunagpal looks like the issue is fixed. Thanks for the assistance

**Comment by Lixue0523** [comment] 2019-05-14 02:21
I can't login with such error.
![image](https://user-images.githubusercontent.com/50348856/57666290-125c6c00-7632-11e9-820e-91ff0842730b.png)
