### ISSUE TITLE
Server Reflection Fails with Netty Error

### ISSUE THREAD

**Issue by alina-revefi** [a85/POSTMan-Chrome-Extension#13002] opened 2024-07-10 23:43 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I try to use the reflection of a GRPC service that has reflection enabled, I get the following error.
```
Could not load server reflection.
Details: no such Type or Enum: <SOME TYPE>
```
I enabled server reflection on my service and verified that the endpoints are functional with grpc_cli and grpccurl. I have restarted Postman, the GRPC service, and my computer.
```
grpcurl -plaintext localhost:8000 describe
```
I noticed that following errors that appear in the logs of the GRPC service I am running
```
2024-07-10 15:49:18 Jul 10, 2024 10:49:18 PM io.grpc.netty.NettyServerTransport notifyTerminated
2024-07-10 15:49:18 INFO: Transport failed
2024-07-10 15:49:18 io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 1603010200010001fc0303b2cf3b2397ccd4975a52b2e570
2024-07-10 15:49:18     at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:109)
2024-07-10 15:49:18     at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:321)
2024-07-10 15:49:18     at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:247)
2024-07-10 15:49:18     at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
2024-07-10 15:49:18     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
2024-07-10 15:49:18     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
2024-07-10 15:49:18     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
2024-07-10 15:49:18     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2024-07-10 15:49:18     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-07-10 15:49:18     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2024-07-10 15:49:18     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2024-07-10 15:49:18     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2024-07-10 15:49:18     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-07-10 15:49:18     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2024-07-10 15:49:18     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
2024-07-10 15:49:18     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
2024-07-10 15:49:18     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
2024-07-10 15:49:18     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
2024-07-10 15:49:18     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
2024-07-10 15:49:18     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2024-07-10 15:49:18     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-07-10 15:49:18     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-07-10 15:49:18     at java.base/java.lang.Thread.run(Thread.java:833)
```
I was able to resolve the issue by downgrading to Postman 11.1.13.

### Steps To Reproduce

- Create proto
- Run a server with reflection enabled, this is written in java
- Create new GRPC request
- Use server reflection to generate the request

### Screenshots or Videos

<img width="567" alt="Screenshot 2024-07-10 at 4 41 24 PM" src="https://github.com/postmanlabs/postman-app-support/assets/123415837/230a9d7e-6500-4eb5-ba69-6a5757a2a02f">

### Operating System

macOS

### Postman Version

11.3.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by parthverma1** [comment] 2024-07-10 23:44
This issue is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/12997

**Closed as completed by parthverma1** 2024-07-10 23:44 UTC

**Comment by ronork** [comment] 2024-07-12 06:33
Hey, @alina-revefi thank you for reporting the issue. 
We have resolved this issue in the latest release of the Postman app (v11.3.2). Please update your app to verify if everything is now working correctly.
