### ISSUE TITLE
Ability to disable hotkeys

### ISSUE THREAD

**Issue by somadeaki** [a85/POSTMan-Chrome-Extension#3847] opened 2017-11-21 17:03 UTC
Please allow users to disable hotkeys entirely. It makes the app completely unusable for me, since with my keyboard layout, almost all special characters are associated with a hotkey. 

## App Details:
```
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64
```

## Issue Report:
 1. A recent update introduced new hotkeys
 2. I can't type any special characters anymore, since with my keyboard layout, the key combinations are associated with Postman hotkeys. This makes the app completely unusable. Examples of special characters that I can't type in the app: @ & |

## To reproduce

To reproduce the problem, set the keyboard layout to something other than US English (I use Hungarian), and try to type special characters.

**Comment by kamalaknn** [comment] 2017-11-22 11:03
Hi @somadeaki  

Thanks for reporting the issue. This is a duplicate of #3596.  Closing this, please follow the original issue for updates.

**Closed as completed by kamalaknn** 2017-11-22 11:03 UTC
