### ISSUE TITLE
Documentation bug with switching tabs

### ISSUE THREAD

**Issue by cschuchardt88** [a85/POSTMan-Chrome-Extension#12152] opened 2023-07-06 20:09 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If you have two tabs open when you are writing documentation. Than you copy and paste MarkDown from the documentation to the other tab, The tab you are coping from overwrites everything with the same content of the other tab when you switch to it. All previous documentation is lost. 

### Steps To Reproduce

1. Open two tabs of REST HTTP (already existing, one with documentation in it and the other not with documentation)
2. Have both tabs with documentation open.
3. On the tab that has documentation content in it, click "Edit" and copy the markdown using the "Beta" editor.
4. Now when you switch to other tab with no documentation content in it. Everything from the previous tab with content gets cloned(copied) to the tab you selected.

### Screenshots or Videos

First tab
![image](https://github.com/postmanlabs/postman-app-support/assets/8141309/0c2924bc-4631-48c8-be17-efdbcafbc49d)

Second Tab
![image](https://github.com/postmanlabs/postman-app-support/assets/8141309/5c7df3d7-793b-4aae-a1e0-416bb529c7a1)

Switching to 1st tab
![image](https://github.com/postmanlabs/postman-app-support/assets/8141309/bb903a3c-07db-4f9b-ac98-80990e859b24)

### Operating System

Windows

### Postman Version

10.15.8

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by azvyae** [comment] 2023-07-17 18:01
Apparently, it doesn't happen only on Beta editor, it happened in legacy markdown editor as well. By activating "editing" mode in legacy markdown editor then immediately change the tab will make the documentation replaced by the editor

**Comment by ekansh-001** [comment] 2023-10-11 07:29
Hello @cschuchardt88,

This issue is being fixed, I am not able to reproduce this on the latest release.
Request you to please check this once 🙇  
Let us know in case you need any other help from our side.

**Comment by ekansh-001** [comment] 2023-10-30 07:01
Hello @cschuchardt88 ,

Since the issue has already been resolved, I am closing off the issue.
Please feel free to open up the other issue on the board if you face any other problem 🙇

**Closed as completed by ekansh-001** 2023-10-30 07:01 UTC
Labels: bug, product/documentation, collections
