### ISSUE TITLE
Cookies are not being Saved in v6.1.3

### ISSUE THREAD

**Issue by Kaushal28** [a85/POSTMan-Chrome-Extension#4659] opened 2018-06-07 12:14 UTC
I've an API which allows login and the responses cookies. This Cookie is being displayed in 'Cookies' tab of the response, but it is not being saved in the cookies section. And also if I open new tab, it doesn't displays cookies which received previously. 

Platform which I'm using: Windows 10
Postman version: 6.1.3

**Comment by Routedworld** [comment] 2018-06-07 12:31
Seeing the same thing on MAC 6.1.3. Just downgraded to 6.0.10 to workaround.

**Comment by pratik97** [comment] 2018-06-07 13:11
I am also facing the same issue.

**Comment by harryi3t** [comment] 2018-06-07 14:53
The fix is already available in our [canary build](https://www.getpostman.com/canary) and will be available in our next production release (6.2.0).

Also, duplicate of https://github.com/postmanlabs/postman-app-support/issues/4581

**Closed as completed by harryi3t** 2018-06-07 14:53 UTC
