### ISSUE TITLE
Cannot install 7.5.0 on newly commissioned Win10 1903

### ISSUE THREAD

**Issue by lazarkanelov** [a85/POSTMan-Chrome-Extension#7132] opened 2019-08-18 17:44 UTC
Hello! I'm trying to install Postman 7.5.0 on my new dev VM running Win10 1903. Basically the setup starts and after a few seconds I'm getting "Installation has failed!"

![image](https://user-images.githubusercontent.com/6763761/63228242-df111680-c1f8-11e9-84a5-4ee32e48edcd.png)

1. Go to Postman download page
2. Download the latest version.
3. Run the setup.

That's the contents of the log file:

2019-08-18 20:24:34> Program: Starting Squirrel Updater: --install .
2019-08-18 20:24:34> Program: Starting install, writing to C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:24:34> Program: About to install to: C:\Users\LZK\AppData\Local\GitHubDesktop
2019-08-18 20:24:34> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\GitHubDesktop\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-08-18 20:24:34> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\GitHubDesktop\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-08-18 20:24:34> CheckForUpdateImpl: Reading RELEASES file from C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:24:34> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-08-18 20:24:35> ApplyReleasesImpl: Writing files to app directory: C:\Users\LZK\AppData\Local\GitHubDesktop\app-2.1.1
2019-08-18 20:24:35> LogHost: Rigging execution stub for lib/net45/GitHubDesktop_ExecutionStub.exe to C:\Users\LZK\AppData\Local\GitHubDesktop\GitHubDesktop.exe
2019-08-18 20:24:43> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\LZK\AppData\Local\GitHubDesktop\app-2.1.1\GitHubDesktop.exe]
2019-08-18 20:24:53> ApplyReleasesImpl: Starting fixPinnedExecutables
2019-08-18 20:24:53> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2019-08-18 20:24:53> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2019-08-18 20:24:53> ApplyReleasesImpl: Examining Pin: Microsoft SQL Server Management Studio 18.lnk
2019-08-18 20:24:53> ApplyReleasesImpl: Examining Pin: Visual Studio 2019.lnk
2019-08-18 20:24:53> ApplyReleasesImpl: Examining Pin: Visual Studio Code.lnk
2019-08-18 20:24:53> ApplyReleasesImpl: Examining Pin: Windows PowerShell.lnk
2019-08-18 20:24:53> ApplyReleasesImpl: Fixing up tray icons
2019-08-18 20:24:53> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2019-08-18 20:24:53> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2019-08-18 20:24:53> ApplyReleasesImpl: cleanDeadVersions: for version 2.1.1
2019-08-18 20:24:53> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.1.1
2019-08-18 20:26:33> Program: Starting Squirrel Updater: --install .
2019-08-18 20:26:33> Program: Starting install, writing to C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:26:33> Program: About to install to: C:\Users\LZK\AppData\Local\Postman
2019-08-18 20:26:33> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-08-18 20:26:33> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-08-18 20:26:33> CheckForUpdateImpl: Reading RELEASES file from C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:26:33> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-08-18 20:26:34> ApplyReleasesImpl: Writing files to app directory: C:\Users\LZK\AppData\Local\Postman\app-7.5.0
2019-08-18 20:26:37> LogHost: Rigging execution stub for Postman_ExecutionStub.exe to C:\Users\LZK\AppData\Local\Postman\Postman.exe
2019-08-18 20:26:40> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\LZK\AppData\Local\Postman\app-7.5.0\Postman.exe]
2019-08-18 20:27:27> Program: Starting Squirrel Updater: --install .
2019-08-18 20:27:27> Program: Starting install, writing to C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:27:28> Program: About to install to: C:\Users\LZK\AppData\Local\Postman
2019-08-18 20:27:28> Program: Install path C:\Users\LZK\AppData\Local\Postman already exists, burning it to the ground
2019-08-18 20:27:28> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-08-18 20:27:28> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-08-18 20:27:28> CheckForUpdateImpl: Reading RELEASES file from C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:27:28> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-08-18 20:27:29> ApplyReleasesImpl: Writing files to app directory: C:\Users\LZK\AppData\Local\Postman\app-7.5.0
2019-08-18 20:27:32> LogHost: Rigging execution stub for Postman_ExecutionStub.exe to C:\Users\LZK\AppData\Local\Postman\Postman.exe
2019-08-18 20:27:35> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\LZK\AppData\Local\Postman\app-7.5.0\Postman.exe]
2019-08-18 20:29:12> Program: Starting Squirrel Updater: --install .
2019-08-18 20:29:12> Program: Starting install, writing to C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:29:12> Program: About to install to: C:\Users\LZK\AppData\Local\Postman
2019-08-18 20:29:12> Program: Install path C:\Users\LZK\AppData\Local\Postman already exists, burning it to the ground
2019-08-18 20:29:13> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-08-18 20:29:13> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-08-18 20:29:13> CheckForUpdateImpl: Reading RELEASES file from C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:29:13> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-08-18 20:29:14> ApplyReleasesImpl: Writing files to app directory: C:\Users\LZK\AppData\Local\Postman\app-7.5.0
2019-08-18 20:29:16> LogHost: Rigging execution stub for Postman_ExecutionStub.exe to C:\Users\LZK\AppData\Local\Postman\Postman.exe
2019-08-18 20:29:19> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\LZK\AppData\Local\Postman\app-7.5.0\Postman.exe]
2019-08-18 20:30:26> Program: Starting Squirrel Updater: --install .
2019-08-18 20:30:26> Program: Starting install, writing to C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:30:26> Program: About to install to: C:\Users\LZK\AppData\Local\PostmanCanary
2019-08-18 20:30:26> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\PostmanCanary\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-08-18 20:30:26> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\PostmanCanary\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-08-18 20:30:26> CheckForUpdateImpl: Reading RELEASES file from C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:30:26> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-08-18 20:30:27> ApplyReleasesImpl: Writing files to app directory: C:\Users\LZK\AppData\Local\PostmanCanary\app-7.6.0-canary02
2019-08-18 20:30:30> LogHost: Rigging execution stub for PostmanCanary_ExecutionStub.exe to C:\Users\LZK\AppData\Local\PostmanCanary\PostmanCanary.exe
2019-08-18 20:30:33> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\LZK\AppData\Local\PostmanCanary\app-7.6.0-canary02\PostmanCanary.exe]
2019-08-18 20:33:58> Program: Starting Squirrel Updater: --install .
2019-08-18 20:33:58> Program: Starting install, writing to C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:33:58> Program: About to install to: C:\Users\LZK\AppData\Local\Postman
2019-08-18 20:33:58> Program: Install path C:\Users\LZK\AppData\Local\Postman already exists, burning it to the ground
2019-08-18 20:33:59> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-08-18 20:33:59> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-08-18 20:33:59> CheckForUpdateImpl: Reading RELEASES file from C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:33:59> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-08-18 20:33:59> ApplyReleasesImpl: Writing files to app directory: C:\Users\LZK\AppData\Local\Postman\app-7.5.0
2019-08-18 20:34:01> LogHost: Rigging execution stub for Postman_ExecutionStub.exe to C:\Users\LZK\AppData\Local\Postman\Postman.exe
2019-08-18 20:34:03> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\LZK\AppData\Local\Postman\app-7.5.0\Postman.exe]
2019-08-18 20:37:07> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
2019-08-18 20:37:07> Program: Starting install, writing to C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:37:08> Program: About to install to: C:\Users\LZK\AppData\Local\PostmanCanary
2019-08-18 20:37:08> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\PostmanCanary\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-08-18 20:37:08> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\PostmanCanary\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-08-18 20:37:08> CheckForUpdateImpl: Reading RELEASES file from C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:37:08> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-08-18 20:37:08> ApplyReleasesImpl: Writing files to app directory: C:\Users\LZK\AppData\Local\PostmanCanary\app-7.6.0-canary02
2019-08-18 20:37:11> LogHost: Rigging execution stub for PostmanCanary_ExecutionStub.exe to C:\Users\LZK\AppData\Local\PostmanCanary\PostmanCanary.exe
2019-08-18 20:37:14> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\LZK\AppData\Local\PostmanCanary\app-7.6.0-canary02\PostmanCanary.exe]
2019-08-18 20:40:28> Program: Starting Squirrel Updater: --install .
2019-08-18 20:40:28> Program: Starting install, writing to C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:40:29> Program: About to install to: C:\Users\LZK\AppData\Local\Postman
2019-08-18 20:40:29> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-08-18 20:40:29> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-08-18 20:40:29> CheckForUpdateImpl: Reading RELEASES file from C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:40:29> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-08-18 20:40:29> ApplyReleasesImpl: Writing files to app directory: C:\Users\LZK\AppData\Local\Postman\app-7.5.0
2019-08-18 20:40:31> LogHost: Rigging execution stub for Postman_ExecutionStub.exe to C:\Users\LZK\AppData\Local\Postman\Postman.exe
2019-08-18 20:40:34> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\LZK\AppData\Local\Postman\app-7.5.0\Postman.exe]
2019-08-18 20:42:53> Program: Starting Squirrel Updater: --install .
2019-08-18 20:42:53> Program: Starting install, writing to C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:42:53> Program: About to install to: C:\Users\LZK\AppData\Local\Postman
2019-08-18 20:42:53> Program: Install path C:\Users\LZK\AppData\Local\Postman already exists, burning it to the ground
2019-08-18 20:42:54> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-08-18 20:42:54> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\LZK\AppData\Local\Postman\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-08-18 20:42:54> CheckForUpdateImpl: Reading RELEASES file from C:\Users\LZK\AppData\Local\SquirrelTemp
2019-08-18 20:42:54> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-08-18 20:42:54> ApplyReleasesImpl: Writing files to app directory: C:\Users\LZK\AppData\Local\Postman\app-7.5.0
2019-08-18 20:42:57> LogHost: Rigging execution stub for Postman_ExecutionStub.exe to C:\Users\LZK\AppData\Local\Postman\Postman.exe
2019-08-18 20:42:59> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\LZK\AppData\Local\Postman\app-7.5.0\Postman.exe]

**Comment by numaanashraf** [comment] 2019-08-22 10:13
Duplicate of #5681

**Closed as completed by numaanashraf** 2019-08-22 10:13 UTC
