### ISSUE TITLE
Always reports 'Warning: Unable to verify the first certificate' with SSL Certification disabled

### ISSUE THREAD

**Issue by huavi02** [a85/POSTMan-Chrome-Extension#10214] opened 2021-08-12 12:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hi,

My Postman v8.10.0 on MacOS Big Sur v11.5.1. In Settings SSL certificate verification is off. It still always prompt error of 'Warning: Unable to verify the first certificate'.

Thx/David

### Steps To Reproduce

1. Open Postman
2. Use GET for any URL starting with https://..
3. Click Send

### Environment Information

```markdown
- Operating System: MacOS Big Sur 11.5.1
- Platform Type: Mac
- Postman Version: 8.10.0
```

**Comment by DannyDainton** [comment] 2022-04-28 11:03
Closing this out as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/6354

**Closed as completed by DannyDainton** 2022-04-28 11:03 UTC
Labels: support, duplicate, product/runtime
