### ISSUE TITLE
Large CSV file freezes Collection Runner, crashes app

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6824] opened 2019-07-02 00:01 UTC
**Describe the bug**
When starting a Collection run using a large CSV file (65k+ rows, 4 columns), the Runner window freezes. Clicking anywhere on the Runner window will get the UI to update with a couple run iterations, but after a few iterations it locks completely. Closing the Runner window then causes the app to crash.

**To Reproduce**
1. Create a Collection with a single request (doesn't matter if the CSV are included in the request using variables)
2. Create a large CSV file (65,000 rows x 4 columns)
3. Start a Collection run using the CSV file 
4. Click on the Runner window a few times to get it the UI to update with the first couple iterations.
5. See that UI eventually stops updating, and becomes non-responsive
6. Close Runner window, see app crash

**Expected behavior**
- Collection run succeeds
- Closing Runner window does not crash app

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.2.2
 - OS: macOS, Windows

**Additional context**
Note that on Canary 7.3.0, the same UI freezing occurs for the Runner window, but closing it does not crash the app.

**Comment by shamasis** [comment] 2019-07-02 05:04
Can you let me know of the size of the file on disk?

**Comment by JP-from-Postman** [comment] 2019-07-02 16:21
@shamasis CSV file size on disk: 3.4MB

**Comment by mccannt** [comment] 2020-09-03 22:55
@JP-from-Postman Are you still seeing this issue?

**Comment by hegerdes** [comment] 2020-09-22 23:55
I also encountered this bug. Had a much larger CSV file 100 MB with 2 columns.
But I don't even can start the Collection run. The App crashes while reading the CSV file.

**Comment by mccannt** [comment] 2020-09-23 12:52
Thanks for the feedback @hegerdes 
We are continually making changes to help with the stability and performance of the application. Hoping to have some changes rolled out in the coming month to hopefully help here.

**Comment by thoiboi** [comment] 2020-09-23 16:43
I too have been having this issue,  the CSV file is only one column with 250K rows making the file size about 2.2MB, it crashes at about row 16K

**Comment by guilherme-wirecard** [comment] 2020-10-20 13:35
I have the same problem, also a CSV file with one column with 400K rows and the Runner doesn't even start the screen was black, and the Runner freeze.

**Comment by mccannt** [comment] 2020-10-21 16:00
@thoiboi and @guilherme-wirecard Thanks for letting us know this. Can you try the same thing using this https://web.postman.co/build/ and let us know if it is still causing issues?

**Comment by Bendihossan** [comment] 2020-11-05 15:42
I'm also able to reproduce this issue with a large CSV (~100mb) using Postman as a Mac application (results in collection runner becoming a grey screen of death) and also on https://web.postman.co/build/ (tab crashes with Chrome "Error: 6").

**Comment by DannyDainton** [comment] 2022-04-27 13:53
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/10410

**Closed as completed by DannyDainton** 2022-04-27 13:53 UTC
Labels: performance, collection-runner, data-file/csv, duplicate, product/runtime
