### ISSUE TITLE
Postman Extension not working in latest Chrome Version 51.0.2704.79 m

### ISSUE THREAD

**Issue by mayurbhorkar** [a85/POSTMan-Chrome-Extension#2101] opened 2016-06-03 05:53 UTC
It seems after updating Chrome's latest Version 51.0.2704.79 m, Postman has stopped working.I Saw some javascript failure in "requester.js" file. Please find below details, 
1. Postman Version: Chrome Extension V 0.8.4.8
2. App (Chrome app or Mac app):  Chrome Version 51.0.2704.79 m
3. OS details: Windows 7
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: recently after updating google chrome to latest version
6. Expected behaviour:  Postman Extension should work the same way it was working on chrome's older versions
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable) :
   ![image](https://cloud.githubusercontent.com/assets/19625979/15770049/560ab8c0-297e-11e6-9048-3d3792eb26b9.png)

**Comment by gablegar** [comment] 2016-06-03 15:46
Could reproduce, Although this extension is no longer supported, at least a fix for this should be provided to export the collections at least. I'm losing all my information :( .

This is a duplicate of #1942

**Comment by numaanashraf** [comment] 2016-06-06 06:39
@mayurbhorkar @gablegar We had pushed a fix for this issue in v0.8.4.17. Could you try force updating by clicking on 'Update extensions now' in chrome://extensions?

![screen shot 2016-06-06 at 12 06 10 pm](https://cloud.githubusercontent.com/assets/3295568/15813798/7cdfd440-2bdf-11e6-9a84-cb0af2c22178.png)

**Comment by gms5683** [comment] 2016-06-08 01:37
@mayurbhorkar You how to solve this problem?
My Postman Version: Chrome Extension V 0.8.4.8
My Chrome Version 51.0.2704.84 m

**Comment by jvm99** [comment] 2016-06-08 12:33
I tried to do the "Update extensions now", but it didn't load v0.8.4.17.

**Comment by sethaugustus** [comment] 2016-06-09 18:31
I also lost all of my histories and Postman stopped working with Chrome v51.

**Here are some notes about reverting to v50:**
If you revert back to chrome v50, you’ll get all of your histories back and Postman will work again.  You’ll also need to disable auto-updates, which is not at all ideal...so write a note to yourself to re-enable auto updates after this is fixed or you find another app to replace Postman

**1.How to install an earlier version of Chrome:**
http://support.imonggo.com/help/kb/advance-questions/how-to-install-a-previous-version-of-chrome-in-mac
**2. Get an earlier version of chrome -- v50 works:**
http://google-chrome.en.uptodown.com/mac/old

**3. How to stop auto-updates in chrome:**
http://support.imonggo.com/help/kb/advance-questions/how-to-stop-google-chrome-from-auto-updates-for-mac
 google-chrome.en.uptodown.com
Google Chrome old versions - Mac
Download old versions of Google Chrome for Mac

**Comment by gablegar** [comment] 2016-06-09 19:29
The update didn't work, the wise thing to do is to get the earlier version of chrome back up your collections and pass to the postman chrome app.

**Comment by JuanManuelFigueroa** [comment] 2016-06-10 15:40
I have the same issue with chrome version Version 51.0.2704.84 (64-bit)

**Comment by njwangchuan** [comment] 2016-06-12 02:27
中国人民发来贺电,Postman dose not work any more with Chrome 51.0.2704.84.

**Comment by benstaker** [comment] 2016-06-12 17:14
I'm getting the same issue on Windows 10 64-bit, with Chrome 51.0.2704.84 m (64-bit).

I have tried using the "Update extensions now" action, but it doesn't update the version to v0.8.4.17.
![image](https://cloud.githubusercontent.com/assets/2591500/15992690/ea97b414-30c9-11e6-845f-5646cc4c230c.png)

**Comment by abhijitkane** [comment] 2016-06-13 08:33
@benstaker @njwangchuan @JuanManuelFigueroa @gablegar 

You seem to have been using an unofficial build of Postman - https://chrome.google.com/webstore/detail/postman-rest-client-short/mkhojklkhkdaghjjfdnphfphiaiohkef?hl=en.

Postman is available at https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en (the legacy app), and https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en (the currently supported app).

You'll need to contact the publisher of the unofficial extension for more on this. He seems to have forked the old Postman repository and published it as a separate item on the webstore.

**Comment by benstaker** [comment] 2016-06-13 08:35
@abhijitkane that seems to be the case, thank you for the investigation.

**Comment by njwangchuan** [comment] 2016-06-13 08:40
thanks a lot!

> 在 2016年6月13日，17:33，Abhijit Kane notifications@github.com 写道：
> 
> @benstaker https://github.com/benstaker @njwangchuan https://github.com/njwangchuan @JuanManuelFigueroa https://github.com/JuanManuelFigueroa @gablegar https://github.com/gablegar
> You seem to have been using an unofficial build of Postman - https://chrome.google.com/webstore/detail/postman-rest-client-short/mkhojklkhkdaghjjfdnphfphiaiohkef?hl=en https://chrome.google.com/webstore/detail/postman-rest-client-short/mkhojklkhkdaghjjfdnphfphiaiohkef?hl=en.
> 
> Postman is available at https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en (the legacy app), and https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en (the currently supported app).
> 
> You'll need to contact the published of the unofficial extension for more on this. He seems to have forked the old Postman repository and published it as a separate item on the webstore.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub https://github.com/postmanlabs/postman-app-support/issues/2101#issuecomment-225519331, or mute the thread https://github.com/notifications/unsubscribe/ADvLmCC4yfsZKXBqTy6f29viF8uw49Kvks5qLRXugaJpZM4ItOYw.

---

Chuan Wang
njwangchuan@gmail.com

**Comment by jmevel** [comment] 2016-06-16 03:50
You have to understand that this unofficial extension exists (and it's not the only one) because there is no way to display Postman icon in the menu bar beside other extensions like on this screenshot. (I installed another unofficial to have this icon back) 
![postman](https://cloud.githubusercontent.com/assets/2572775/16104946/4f7dec0e-33b8-11e6-856c-d3292b37f433.PNG)

**Closed as completed** 2016-07-17 08:43 UTC
