### ISSUE TITLE
Opens new tab after hover URL and click in body

### ISSUE THREAD

**Issue by wahidnory** [a85/POSTMan-Chrome-Extension#1282] opened 2015-07-23 12:40 UTC
Hi,

I've got an issue with the latest version of the postman app (3.0.5 (packaged)). When I've hovered over an url in the pretty view of the body, and then click somewhere inside the body. It opens a new tab for that url. Here is the example:
![e8d6bc5cf62c2ffabbe4167373e8211a](https://cloud.githubusercontent.com/assets/3277057/8850479/af804d4a-3148-11e5-867d-3c6b98a3a472.gif)

**Comment by RangerDan** [comment] 2015-07-23 16:13
Clicking on or near an XML tag in Pretty view opens a tab as well.  The tab has the same domain as the parent, but has a subfolder of the XML tag you clicked.

Could this be a feature to assist testing RESTful APIs?

**Comment by abhijitkane** [comment] 2015-07-23 16:55
Hm..only the link is supposed to be clickable. @numaanashraf Some ace-editor issue?

**Comment by bmmkoc** [comment] 2015-07-24 08:26
The problem is evident in XML responses as well - every part of an XML response that contains the forward slash character is turned into a clickable link, eg. any closing tag in the XML, such as `</accidentallink>`. It's highly annoying.

Using Postman 3.0.5 (packaged) on x86-64 (Fedora 22).

**Comment by davidw13** [comment] 2015-07-28 16:21
I'm seeing the original issue in JSON requests too. Additionally, in pretty view for HTML responses, if there is a link anywhere in the markup, any tag that encloses it will have it's closing tag be clickable for the first link in it's inner markup. Very annoying to either have to pay such close attention to where you click in the response or else have tabs randomly opening up and making requests that weren't actually desired.

**Comment by abhijitkane** [comment] 2015-07-30 12:35
This was an issue with the ace-editor plugin that we were using. We'll push a fix in the next release.

**Comment by numaanashraf** [comment] 2016-03-11 22:30
Fixed in 4.0

**Closed as completed by numaanashraf** 2016-03-11 22:30 UTC
Labels: bug
