### ISSUE TITLE
Allow user to assign colors to different request types

### ISSUE THREAD

**Issue by dempe** [a85/POSTMan-Chrome-Extension#10771] opened 2022-03-21 09:26 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Pretty much all database administration tools have the ability to color code certain DB connections for say, prod or staging.  This minimizes the chances that a user will submit an unintentional query.

It would be very nice if Postman offered similar functionality.  Ideally, at the request level, but the environment level would also be a huge help.  For example, this would minimize the chances that a user sends a PUT request when they meant to send a GET request.

### Describe the solution you'd like

Allow a user to color code different requests as they like.  The request in the URL bar would then have the background color the user selected.  For example, I would love for GET to be colored green, POST to be yellow, PUT to be orange, and DELETE to be red.

Of course other may want different colors, hence, I suggest allowing the user to select his or her own colors for each request.

**Comment by DannyDainton** [comment] 2022-03-25 17:29
Closing this as it looks like a duplicate of this issue https://github.com/postmanlabs/postman-app-support/issues/8260

**Closed as completed by DannyDainton** 2022-03-25 17:29 UTC
Labels: feature, duplicate
