### ISSUE TITLE
Run in Postman button not working | In Windows environment only

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#5209] opened 2018-09-19 11:19 UTC
**Describe the bug**
This bug (Java Script bug?) seems to be specific only to this collection. Here is the link to the web page: https://docs.newsletter2go.com/

**To Reproduce**
1. Go to 'https://docs.newsletter2go.com/'
2. Click on 'Run in Postman' button
3. Then Click on Open in 'Windows App'. Nothing happens after that- the same web page(https://docs.newsletter2go.com/) seems to be loading again in loop.
4. Attaching two screenshots with the JS errors below

**Expected behavior**
Successfully import collections and environments into the Postman application.

**Screenshots**
![exception- screenshot](https://user-images.githubusercontent.com/12132423/45749997-182cb980-bc2b-11e8-9aa0-4dc5b911e601.png)
![exceptions- screenshot](https://user-images.githubusercontent.com/12132423/45750001-1b27aa00-bc2b-11e8-8ae6-ca0cfc0d8d84.png)

**App information (please complete the following information):**
 - App Type Native App
 - OS: Windows

**Additional context**
This process is seemless in Mac OS. Also, tried running the Run Postman button across other collections like Echo for example (https://docs.postman-echo.com/)- there's no problem running this in both Mac and Windows as well. So this whole bug seems to be somehow related only to this one(hopefully) collection!

--
Harsha

**Comment by SamvelRaja** [comment] 2018-09-19 11:53
@godfrzero  On debugging we see that it's not redirecting to `postman://` protocol for the handover.

**Comment by godfrzero** [comment] 2018-09-21 02:11
This looks like a problem with URL length limitations in different browsers. Since the run in postman button uses the URL fragment to pass the encoded environment variables to the app, the total length of the URL can go beyond 2048 characters (which is where the problem seems to start).

We'll look for a way to avoid this issue, but in the meantime the best way to avoid this problem is to keep unnecessary information (descriptions, documentation) out of environment variables.

**Comment by steffenschebesta** [comment] 2018-10-08 12:46
@godfrzero any updates on this?
The "Run in Postman" button is still not working and purging the variables is not an option as the URLs break:
![image](https://user-images.githubusercontent.com/1621569/46609672-fbd4bc00-cb08-11e8-85b3-5778763a3c4c.png)

**Comment by godfrzero** [comment] 2018-10-15 08:58
You don't have to remove it completely, I was thinking more along the lines of replacing it with something shorter because I see that the current values are almost sentences.

As for the long-term fix for this issue, it's more complex than it may seem at first because the fix isn't just in the button. We'll have to expose a "public" url for environments, enable URL-based imports in the app (which means things won't be backward compatible), and then update the run in postman button to support this new URL.

**Comment by steffenschebesta** [comment] 2018-10-15 09:02
Tried using shorter descriptions but didn't help in the end since we are using the placeholders in the URLs. So it makes sense there to use e.g. `{{list_id}}` to clarify that this is the id that has to be used.

**Comment by steffenschebesta** [comment] 2018-10-15 09:08
@godfrzero is there at least another workaround? 
if the error happens, could you show a message explaining how else the user can import the collection?

**Comment by godfrzero** [comment] 2018-10-16 11:27
For now, I can try releasing a version of the run button which would remove the environment entirely if the URL ends up being too long. This would allow at least the collection to be imported. There's no way to reliably display an error since some browsers essentially nullify the URL action itself.

**Comment by steffenschebesta** [comment] 2018-11-21 12:33
@godfrzero any updates on this issue?

**Comment by staticvoidmaine** [comment] 2019-05-23 16:03
I believe this issue is blocking our customers from accessing their collections which we provide them via postman documentation.

Do you have any updates on a resolution?

Are there any workarounds which would allow our customers to open the collection in postman from their documentation page?

**Comment by stcalica** [comment] 2019-09-20 16:53
Issue reported by another user to support

**Comment by ShahinKohan** [comment] 2020-02-25 00:20
This is crazy, it is a bug and you should fix it. It's been open for a long long time. 

Reproduce the error

Use a Windows 10 Computer
Make sure Postman is running
Go to https://api.aims360.io
Click on the button Run in Postman
Nothing happens no errors

**Comment by ShahinKohan** [comment] 2020-03-02 22:14
This is crazy Postman should fix their code to comply with Windows RL length limits https://blogs.msdn.microsoft.com/ieinternals/2014/08/13/url-length-limits/

**Comment by ratpik** [comment] 2020-03-03 13:08
@ShahinKohan - We are actively working on fixing this issue. 

A workaround, for now, would be to reduce the URL length below 507 characters (if you are using Internet Explorer 11 on Windows) by reducing the length of values in the environment.

**Comment by ShahinKohan** [comment] 2020-03-03 18:19
Hi, we are using Chrome not Internet Explore. IE is not installed here.


Thank You,

**Comment by ratpik** [comment] 2020-03-04 09:25
@ShahinKohan - We are unable to reproduce this on Windows 10 and Chrome (Version 80). Can you confirm the version of the Postman app you are using?

**Comment by v-krishnakishore** [comment] 2020-03-05 14:34
> @ShahinKohan - We are unable to reproduce this on Windows 10 and Chrome (Version 80). Can you confirm the version of the Postman app you are using?

Hello @ratpik,

Please try now in chrome. It will not work. Previously, we have shortened the default values of the environment variables. Thus it worked.

**Comment by ratpik** [comment] 2020-03-10 11:49
@v-krishnakishore - We have released an intermittent patch fix that will allow you to import only the Collection if URL length crosses the limit on Windows (507 for IE and 2046 for Chrome/Firefox).

We are working on a fix for this that will allow you to import the environment irrespective of the URL length. We plan to roll out this fix to all users within the next couple of weeks. We will update this thread once we release it.

**Comment by v-krishnakishore** [comment] 2020-03-12 06:40
Thank you. I have tested the collection and it is working now. 

I look forward to the permanent fix so that it won't cause issues in the future if we add more variables to the environment with different length values.

**Comment by v-krishnakishore** [comment] 2020-03-18 06:55
Hello Postman Team,

Although the Run in Postman works, now it is not downloading the environment at all. We are not sure when this was broken. Can you please fix the issue ASAP.

As you can see there is an environment called ‘AIMS360 API Environment’ which used to download previously. But it is not downloading anymore now in both chrome and firefox on windows OS.

Please try on our API url https://api.aims360.io/?version=latest

**Comment by ratpik** [comment] 2020-03-18 09:24
Hello @v-krishnakishore,

We are working on a fix for this issue and we expect it to be resolved in about 3 weeks from now. 

The intermittent fix that we have released allows you to import the collection and environment if your URL length is less than 2046 characters. If it is more than that it will drop the environment and only import the collection. This behavior is for Windows with Chrome/Firefox.

You could choose to reduce the length of your URL and get it below 2046 by stripping out some parts of your  ‘AIMS360 API Environment’ until our fix is out.

**Comment by ratpik** [comment] 2020-03-27 13:44
Hi @v-krishnakishore,

We have released a fix for this issue. You will need to download or update to the **latest version of the Postman App (Above v7.21.0)** for this to work. The Postman Environment will get imported irrespective of the length across all OS (Windows/Mac/Linux) and Browser (Chrome/IE/Firefox/Safari) platforms.

**Closed as completed** 2020-03-30 06:26 UTC
Labels: bug, product/api-network

**Comment by iamprakashom** [comment] 2020-07-09 05:50
Previously it was working and it stopped working after automatic update to 7.21.0.
