### ISSUE TITLE
Obstructive equal-sign in query-string for parameter without value

### ISSUE THREAD

**Issue by brugr9** [a85/POSTMan-Chrome-Extension#4547] opened 2018-05-11 00:26 UTC
**Description**
For a wsdl request, the query-string contains a parameter with no value: https://mnt.jobat.be/ws/JobPost.asmx?wsdl
If using a parameter without value in Postman, an equal-sign is added to the query string when running the request in a **monitor on the web site**.

**To Reproduce**
1. Create a request.
2. Enter URL https://mnt.jobat.be/ws/JobPost.asmx?wsdl (creates a Parameter with key 'wsdl' and value left empty).
3. View the documentation on the web site.
4. Create a monitor.
5. Run the Monitor on the web site.

**Expected behavior**
If using a parameter without value, the equal-sign mustn't be added to the query string.

**Screenshots**
- In the **Request** the parameter wsdl **works**, https://pasteboard.co/HkBsPEU.png
- In the **Collection Runner** the parameter wsdl **works**, https://pasteboard.co/HkBsY7J.png
- In the **Documenter** unfortunately the parameter wsdl was automatically added a '=', https://pasteboard.co/HkBtssv.png
- In the **Monitor** unfortunately the URL with parameter wsdl was automatically added a '=', https://pasteboard.co/HkBt4Lb.png

**App information:**
 - App Type: Native App in combination with Documenter and/or Monitor
 - Postman Version: Postman for Linux, Version 6.0.10, linux 4.4.0-124-generic / x64
 - OS: Ubuntu 16.04 LTS, 64 Bit

**Comment by prashantagarwal** [comment] 2018-05-11 11:55
@brugr9 This is a duplicate of #3991 . I am closing this to track them all in one place.

**Closed as completed by prashantagarwal** 2018-05-11 11:55 UTC
