### ISSUE TITLE
Prevent removal of collection from last workspace

### ISSUE THREAD

**Issue by simasch** [a85/POSTMan-Chrome-Extension#4509] opened 2018-04-30 13:57 UTC
As it is not possible to have a collection without workspace why not prevent the removal of a collection from all workspaces?

**Comment by SamvelRaja** [comment] 2018-06-29 07:25
@simasch Thanks for raising your concern 😄  @vkaegis  @sankalp0o  any inputs?

**Comment by sankalp0o** [comment] 2018-06-29 08:36
@simasch A collection can still exist without being in a workspace. This collection would still be retrievable from the API and can be viewed on the dashboard. 
This state is present because multiple people might accidentally remove the collection from all workspace without realising this. However, I see what you mean and we are working on indicating the workspaces a collection is present in so that this does not happen.

**Comment by numaanashraf** [comment] 2019-01-09 12:15
The current implementation works as designed. Tracking this request as a feature/improvement.

**Comment by mccannt** [comment] 2020-07-22 12:52
Resolved in v7.29.0

**Closed as completed by mccannt** 2020-07-22 12:52 UTC
Labels: feature
