### ISSUE TITLE
Clicking "Collection Runner" tab whilst the runner is processing shouldn't cancel the run

### ISSUE THREAD

**Issue by RobWaterhouse95** [a85/POSTMan-Chrome-Extension#7664] opened 2019-11-18 16:48 UTC
**Is your feature request related to a problem? Please describe.**
I was recently processing several runners simultaneously.
Whilst trying to spin up another runner instance. I needed some information from the "Collection Runner" tab from the previous runs. 
Clicking on this button cancelled my runs, resulting in me not knowing where they got up to. I had to query databases to find out what requests had gone through so I would avoid sending the same request twice.

**Describe the solution you'd like**
Clicking on the "Collection Runner" tab should not cancel the current runner, rather expand the tab to simply display the information on there.

**Describe alternatives you've considered**
Clicking on the "Collection Runner" tab should prompt the user saying "Are you sure you want to cancel this runner session"

**Additional context**
N/A

**Comment by appurva21** [comment] 2020-02-11 07:02
Hi @RobWaterhouse95, we made have certain improvements in Collection Runner during our last few releases. Can you please update to the latest version of the app and check if this issue still persists for you.
To get the latest version either you can update the existing app or can download a new app from [here](https://www.postman.com/downloads/)

**Comment by appurva21** [comment] 2020-02-17 12:17
Hey @RobWaterhouse95,
Closing the issue as we are not able to reproduce it on the latest app version (`v.7.18.0`). Please feel free to reopen if the issue still persists.

**Closed as completed by appurva21** 2020-02-17 12:17 UTC
Labels: bug, collection-runner, user-interface, product/runtime
