### ISSUE TITLE
Delays with sync for large Collections + requests

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6368] opened 2019-04-26 00:11 UTC
[Filed by Postman Support, on behalf of user]

**Describe the bug**
Team has many, very large Collections (some with 600+ requests). Many of these requests contain very large request bodies (10,000+ lines of JSON).

When logging in for the first time in a given instance of the app, content fails to load and Dev Tools logs contains numerous socket disconnection errors. Quitting the app and restarting is required to see content sync successfully.

This appears similar to the following issue:
https://github.com/postmanlabs/postman-app-support/issues/4249

More details in internal notes.

**To Reproduce**

**Expected behavior**
Content loads successfully (even if it takes a while), regardless of quantity and size. Sync status bar maybe?

App does not require restart to load content on first-time sign-in.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.0.7
 - OS: macOS

**Additional context**

**Comment by kamalaknn** [comment] 2019-04-26 05:48
Hi @JP-from-Postman 

Can we get the logs from `View -> Developer -> View logs in Finder` when this happens? That will help us identify the root cause of the issue here.

**Comment by JP-from-Postman** [comment] 2019-04-26 16:57
@kamalaknn sorry about that, logs attached:
[-1556225409370.log](https://github.com/postmanlabs/postman-app-support/files/3122270/-1556225409370.log)

**Comment by sankalp0o** [comment] 2019-07-30 08:14
@kamalaknn Were we able to diagnose this issue?

**Comment by cyrielle-hada** [comment] 2020-01-14 12:04
Reporting here on the behalf of a team. 

**Describe the bug**
- This team's large collection (112 requests) is not syncing across instances once it is updated.
- It does sync but after a while (a couple of days). 
- Example of edits that are not updated on another instance: missing or incorrect Keys showing in the environment quick look, incorrect parameters in some requests, incorrect order of the Environment variables.
- This is an issue that comes and goes. Sometimes the changes are reflected sometimes they don't.

**App information** 
Native Postman App
Postman Version - 7.14 and 7.15

**Additional context**
- Logging out and back in doesn't help. 
- Everyone in the team has updated to at least to version 7.14
- There is no fork for this collection. 
- The syncing icon behaves as expected - it is orange color and while syncing it turns into blue.

**Logs** 
They ca be found internally.

**Comment by ankit-m** [comment] 2020-01-22 07:02
@cyrielle-hada I tried to reproduce this issue with a large collection (~500 requests with large descriptions and example - 40MB JSON). The collection did sync in about a minute. Same goes for importing a large collection.

Could you tell me more about the collection? Was there anything specific about this collection - like large descriptions, multiple saved examples, etc.

**Comment by cyrielle-hada** [comment] 2020-01-28 15:28
@ankit-m the syncing issues were occurring for a shared collection - when Params and Authorization sections would be edited. Sorry, I don't have more context for now. The issue doesn't seem to happen anymore, I will let you know if this re-occurs and will try to give more info.

**Comment by mccannt** [comment] 2020-09-03 22:36
@cyrielle-hada Is this still happening or can we close this out?

**Comment by cyrielle-hada** [comment] 2020-09-04 09:20
@mccannt closing this out!

**Closed as completed by cyrielle-hada** 2020-09-04 09:20 UTC
Labels: sync, performance, version-control
