### ISSUE TITLE
Body in requests is deleted after app restart

### ISSUE THREAD

**Issue by dyymmi** [a85/POSTMan-Chrome-Extension#2527] opened 2016-12-07 10:52 UTC
1. Postman Version: 4.9.1
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: Saving body in requests

Steps to reproduce the problem:
1. Open Postman
2. Save request with empty body
2. Add raw JSON body request to body
3. Save again
4. Close App and open again

Actual result:
Whole body is erased from request.
When using "Save as..." it works well.

**Comment by vegetableman** [comment] 2016-12-07 11:12
@dyymmi Thanks for reporting this issue 👍 . Will get back to you.

**Comment by vegetableman** [comment] 2016-12-08 04:34
@dyymmi The issue has been fixed internally and will be part of the next release ^_^.

**Comment by crowcoder** [comment] 2016-12-09 15:57
I assume this is fully fixed, but just in case I want to point out that Save As only works to a new collection. Save As to same collection still drops the request body on restart.

**Comment by vegetableman** [comment] 2016-12-16 06:34
@crowcoder @dyymmi The issue is fixed in the latest release ^_^.  Could you guys verify the same?

**Comment by dyymmi** [comment] 2016-12-16 07:53
@vegetableman Yes, i can confirm the fix. Thanks for quick reaction ;)

**Comment by vegetableman** [comment] 2016-12-16 07:57
Awesome 👍

**Closed as completed by vegetableman** 2016-12-16 07:57 UTC
Labels: pending-close
