### ISSUE TITLE
Collection test runner shows up black

### ISSUE THREAD

**Issue by tomershay** [a85/POSTMan-Chrome-Extension#4128] opened 2018-01-30 09:32 UTC
## App Details:
Postman for Mac
Version 5.6.0-canary01
OS X 17.2.0 / x64

## Issue Report:
I recently upgraded to Postman Canary from the previous Postman version, because I thought it might help resolve this issue, but it seems to happen in Canary as well (few weeks after using it).
From some reason, when clicking the "Runner" button and opening the collection runner, it loads the screen and then the runner's window goes black.
It happened in the previous version few months after using it. Now it happens in Canary about couple of weeks after using it.
Please note - the black screen shows only after the loading screen of the runner (which shows up properly, with both text and animations).
The dev tools console of the postman application doesn't show any errors when running the collections.

Screenshots:
![screen shot 2018-01-30 at 11 31 36](https://user-images.githubusercontent.com/18751488/35558626-3ae27c3e-05b1-11e8-907c-e13ab463f293.png)
![screen shot 2018-01-30 at 11 32 00](https://user-images.githubusercontent.com/18751488/35558625-3abf9e30-05b1-11e8-8b8f-7eb0f48e62d6.png)

Requesting your assistance. Thank you.

**Comment by numaanashraf** [comment] 2018-02-01 07:11
@sh-tomer Thanks for writing in. Looks like this is an issue in the underlying framework Postman is built on. We will include a fix for this as soon as it is available. In the meantime, you can try the workarounds mentioned here - https://github.com/electron/electron/issues/4380

**Comment by tomershay** [comment] 2018-02-01 14:37
@numaanashraf , thank you, but none of the workarounds there resolve the problem.
No matter what I do, still a black screen.
Any idea what may have caused this issue to suddenly appear? It worked a for a while, but then stopped working.

**Comment by SergeyTishchenko** [comment] 2018-02-16 10:27
The same issue for me 
![image](https://user-images.githubusercontent.com/22492720/36303387-119f7128-131d-11e8-8ba8-af72e47e58b7.png)

App Details:
Postman for Win
Version app-5.5.3
Windows 7 x64

**Comment by aprixon01112017** [comment] 2018-02-23 15:58
Same, 5.5.3 on WIndows 10

**Comment by jerrfi** [comment] 2018-02-28 19:42
+1

This is happening for me as well. Postman 5.5.3 on Windows 10. I do have an Nvidia GPU but the Electron thread indicates it is not limited to that GPU / maker.

This is significantly hampering development & testing of our APIs.

**Comment by LeslieMurphy** [comment] 2018-03-25 17:29
Postman has now become 100% unusable / unreliable for me.  I have nVidia K1200 and 3 monitors.

**Comment by DaveFUK** [comment] 2018-04-26 11:36
I'm running Window 7 32 bit at work. All of a sudden, i.e. one minute it worked next Postman is just giving me a black screen. Tried reinstall, all the suggested fixes, nothing works. Postman is now completely useless for me.

**Comment by reedzhao** [comment] 2018-04-26 21:24
It just happened to me.  Is there even not a work-around? Consider I paid $80 a year for the service.

Windows 10 64 bit
Latest postman update
Slack - which uses the same framework, works okay on the same computer.

![image](https://user-images.githubusercontent.com/16353524/39332726-53f739b8-4976-11e8-9e70-1d9a6794e82d.png)

**Comment by dani-easydevel** [comment] 2018-04-27 09:40
Hi,
Same to me. Black Screen.

Wednesday or Tuesday was working fine. Today no.
Could you fix this, or tell us what is happening?
Many thanks.

**Comment by ajayush** [comment] 2018-05-04 00:17
Go to C:\users\{user}\AppData\Local and delete the Postman folder.
Go to C:\users\{user}\AppData\Roaming and delete the Postman folder.
Re-install postman and it should be back up

**Comment by SergeyTishchenko** [comment] 2018-05-04 08:04
ajayush, thanks it helped!

**Comment by alovato88** [comment] 2018-06-05 16:18
I'm still seeing the problem on Mac and on the latest version of Postman. Goes to black screen within a minute of starting. I just reinstalled the app and it's still happening.

**Comment by prateeksarda** [comment] 2018-06-08 09:11
This is stopping us from even getting single activity done using Postman app.
Facing same problem on my Windows 10 machine.

**Comment by mdhornet90** [comment] 2018-06-15 05:23
This just started happening to me 5 minutes ago on Mac OS Sierra, Postman version 6.1.3

EDIT:
This continues to happen even after following the advice from #4634.

EDIT 2:
Same issue after uninstall/reinstall.

Update:
I was able to work around this by quickly opening the dev tools when a new window pops up. The cause of the black screen is the debugger "helpfully" pausing execution right before what it claims is a potential out of memory error. I have to continue from that breakpoint once or twice and then the app functions normally.

For what it's worth, I have a collection that has two requests each with a giant payload in the `POST` body.

**Comment by jacquesvoogt** [comment] 2018-06-25 07:04
I closed POSTMAN and reopened it again a couple of times to no avail.
Made a copy of the postman folders under local and roaming.
Tried deleting the cache to no avail
Deleted the Postman directory under Local and Roaming. Postman created a new one under Roaming still not working.
I then restored the postman folder under roaming from my backup. Still not working.

Then closed a few other apps to free up some memory.

Opened Postman and everything was working fine.

I think postman was trying to allocate more memory than I had available, which was a few hundred megs at the time.

**Comment by AleksandarSavic95** [comment] 2018-08-30 12:06
Another solution from user @harryi3t is to add an environment variable called `POSTMAN_DISABLE_GPU` and set its value to `true`. [Link to that comment on the main issue](https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621).

**Comment by tomershay** [comment] 2018-11-07 18:57
@numaanashraf, I thought I'd give the new Canary version a try, but it seems the issue occurs again in the latest version as well.

I thought I would add more information that may help to resolve this issue.
It seems that once I run the collection runner, the memory of the "PostmanCanary Helper" process starts to climb significantly. Once it reaches a few GBs (about 3-4GB), the screen goes black.

If I manage to start the developer tools for that screen before it goes black, I see the following error, which shows that the application was paused before an out of memory crash.
If I just resume from the developer tools, it seems that everything continues to work and no black screen appears.
I noticed that about a minute or two after the process I described above, the "PostmanCanary Helper" process frees up most of the memory and then it needs only 0.5GB.

Hope this can info will be helpful.

P.S, I'm running Mac with High Sierra 10.13.4.

<img width="996" alt="screen shot 2018-11-07 at 19 51 56" src="https://user-images.githubusercontent.com/18751488/48153712-3330b700-e2c7-11e8-9c71-fa92e76fddc6.png">

**Comment by harryi3t** [comment] 2018-11-09 06:05
@sh-tomer Thanks for your input. Could you let us know what version of Postman (Canary) you are using? Also, if you could give us the following information, that would really help us debug and fix this issue.
 - Total no. of requests sent in one collection-run (If not using [setNextRequest](https://www.getpostman.com/docs/v6/postman/scripts/branching_and_looping) it will be same as the no. of requests in the collection)
- On an average, how big is the response?
 - Are you using multiple iterations (if yes, how many?)
 - Are you running multiple collection-runs in parallel? 
 - Is this issue easily reproducible every time you use Runner?

**Comment by tomershay** [comment] 2018-11-09 19:39
Sure @harryi3t, happy to provide more information to help resolve this issue.
Answering with the same order as the questions.

- Version: 6.5.0-canary04 (6.5.0-canary04)
- 249 requests
- Estimating avg response at around 10-50KB. Please note though, that this issue occurs before actually running any tests using the collection. It happens when starting the collection runner.
- No, running only one collection.
- Yes, it happens every time.

Let me know if there is any more information I can provide. Thanks!

**Comment by paulosotu** [comment] 2018-12-12 05:22
Having exactly the same issue as @tomershay any updates on this one @harryi3t ?

**Comment by saswatds** [comment] 2019-10-03 10:51
Hi everyone, in the latest canary version of app `7.9.0-canary01` we have made some performance improvements in the Collection Runner. It should now load much faster and with proper loading state. Have also been able to reduce the memory foot-print of the runner window by quite a lot so the runner resulting in the back-screen should also be mitigated to an extent. This is not going to be the end, we have a series of performance updates planned over the next few releases.
Do check it out and share you thoughts.

You can download the canary app from https://www.getpostman.com/downloads/canary

Thanks

**Comment by tomershay** [comment] 2019-10-04 14:43
@saswatds, thanks for the update.
I upgraded to 7.9.0-canary01 but the issue still occurs, the collection runner still shows a black screen.
I can work around it by quickly running the DevTools, and once the exception occurs, click continue several times until the runner shows up.

Thank you for the efforts. Would love to see this fixed in the future.

**Comment by saswatds** [comment] 2019-10-04 17:29
Hi @tomershay, Is it possible that the workspace your are opening has a large number of collections? I tried optimising the follows and have updated the runner to load only collection information from the active workspace. If you do have lot of collections, can you split them to multiple workspaces and see if it helps?

**Comment by tomershay** [comment] 2019-10-04 17:33
@sanduhrs, the workspace contains only 2 containers (20 requests + 320 requests).

**Comment by tomershay** [comment] 2020-01-21 17:52
@sanduhrs, I'm happy to update that since upgrading to the last Canary version, this issue was resolved. Will keep you posted in case it will come back in the future. Thank you!
For reference, I'm currently using: version 7.16.0-canary01 (7.16.0-canary01), on a Macbook Pro 13'

**Comment by saswatds** [comment] 2020-02-12 07:16
Thanks @tomershay.  We have pushed all our runner performance change to the production channel on app version `7.18.0`. Closing this issue for now. Feel free to re-open if the issue persists.

**Closed as completed by saswatds** 2020-02-12 07:16 UTC
Labels: bug, performance, collection-runner, product/runtime
