### ISSUE TITLE
WebDAV methods

### ISSUE THREAD

**Issue by MovGP0** [a85/POSTMan-Chrome-Extension#1721] opened 2016-02-13 12:32 UTC
The WebDAV commands `COPY` and `DELETE` are available, but others are missing. This includes `PROPFIND`, `PROPWATCH`, `MKCOL`, `MOVE`, `LOCK` and `UNLOCK`, which are the minimal requirements for WebDAV implementations. 

There are even more [WebDAV methods](https://msdn.microsoft.com/en-us/library/aa142917%28v=exchg.65%29.aspx), so it might be useful to let the user type in a method that is not in the list.

**Comment by a85** [comment] 2016-06-19 18:45
Closing as duplicate of #1710

**Closed as completed by a85** 2016-06-19 18:45 UTC
Labels: feature
