### ISSUE TITLE
URL slashes are incorrect

### ISSUE THREAD

**Issue by DOLPHYNNNN** [a85/POSTMan-Chrome-Extension#6899] opened 2019-07-11 00:39 UTC
In Postman 7.3.1 with the new color formatting of responses the slashes in URL responses are now displaying both a backslash then a frontslash (\ /).  Using older versions of Postman shows the URL with just a single slash as expected but in the most recent versions the URLs have an extraneous slash displayed.  

To recreate:  Hit an endpoint which returns an URL.  Notice that the slashes in the URL appear incorrect.  

Expected Behavior = Postman displays the correct slashes as returned by the endpoint when displaying an URL and does not prepend an extraneous \ before them.

**Comment by DOLPHYNNNN** [comment] 2019-07-11 00:43
![BadSlashes](https://user-images.githubusercontent.com/52682172/61014029-3c809080-a33a-11e9-9773-79da2f7e7b87.png)
![GoodSlashes](https://user-images.githubusercontent.com/52682172/61014034-42767180-a33a-11e9-88dc-df783e4ed311.png)

**Comment by jpSimkins** [comment] 2019-07-11 01:59
I too have ran into this annoying issue. This is actually misrepresenting data and being problematic.

**Comment by T0mmyLee** [comment] 2019-07-11 09:04
Hope they will fix it soon!

**Comment by timatanu** [comment] 2019-07-30 23:01
This bug is extremely annoying and is exacerbated by the fact that Postman keeps on automatically updating my installation of V7.2.2 where the bug does not exist with version 7.3.x where it does. I used to be able to just click the link and follow it.

Also to add insult to injury I can't even just select and copy the escaped URL text to the clipboard so I can edit it myself. Whilst it selects it will not copy. I'm using Postman on RHEL 7.6. Although the issue does not seem to be limited to that platform as a colleague using Windows also has the same problem when using 7.3.x

I would add that this is turning Postman lovers into haters.

**Comment by ankurdengla** [comment] 2019-07-31 13:39
@DOLPHYNNNN @jpSimkins @T0mmyLee @timatanu The fix for this issue is out on our Canary build (PostmanCanary 7.3.5-canary04) which can be downloaded here - https://www.getpostman.com/downloads/canary . Do let us know if the issue still persists.

@timatanu The select and copy bug is being tracked here - https://github.com/postmanlabs/postman-app-support/issues/6876 . The fix for this is also available in the Canary version mentioned here.

Please do let us know if the issue still persists.

**Comment by kamalaknn** [comment] 2019-08-05 10:59
We have pushed this fix to the stable channel in Postman 7.3.6. Please update to the latest and give it a try.

**Closed as completed by kamalaknn** 2019-08-05 10:59 UTC
Labels: bug

**Comment by castillojuan1000** [comment] 2021-11-29 19:59
The issue still persist in version 9.2.0 and canary as well

**Comment by nirapavan** [comment] 2022-03-23 21:57
@kamalaknn - Is the escape characters issue resolved in Postman? Referring to the [DOLPHYNNNN] screenshots. Looks like it still persists in the latest release v9.15.2. Looks like this post is closed. Do we have any other post related to this issue?

**Comment by kamalaknn** [comment] 2022-03-24 07:53
Hey @nirapavan we are not able to reproduce the issue from our end. 

![Screenshot 2022-03-24 at 1 21 58 PM](https://user-images.githubusercontent.com/8401064/159868233-97d4c51a-fce6-4513-aa53-9e91d3627c62.png)
![Screenshot 2022-03-24 at 1 22 03 PM](https://user-images.githubusercontent.com/8401064/159868247-fc0c5e33-0a6a-4ca9-b477-b38ba4b482ee.png)

Could you share screenshots of your raw and pretty responses? It would help if you can share the API or a minimal reproduction that can help us debug the issue.

**Comment by nirapavan** [comment] 2022-03-24 11:09
![image](https://user-images.githubusercontent.com/102260882/159903916-20d33ae3-687c-435f-a6d6-29b8c32e67d1.png)
![image](https://user-images.githubusercontent.com/102260882/159903987-9674c7b4-9b10-4279-a1ac-53da4a07654f.png)

**Comment by kamalaknn** [comment] 2022-03-24 11:44
@nirapavan The issue raised by the original author on this thread is related to how `\/` slashes were not escaped correctly. I do not see this happening in your case.

I do see that you have `"` quotes within your strings in the JSON response, which is escaped as `\"`. Is this what you were referring to? if not, can you help me understand the issue you are seeing?

**Comment by nirapavan** [comment] 2022-03-24 12:39
I know it is a different post. But it is related to the escape character for the quotes. If you have any other related post, I can update there. The issue is with the quote with the escape character in the xml when rendered to the response. I saw other posts too, but saw them as closed with no resolution. Hope this helps.
