### ISSUE TITLE
[BUG] Minimize/Maximize Postman's window - Postman won't open!

### ISSUE THREAD

**Issue by milancheck** [a85/POSTMan-Chrome-Extension#3515] opened 2017-09-12 12:27 UTC
## App Details:
Postman for Windows
Version 5.2.0
win32 10.0.14393 / x64

## Issue Report:
 1. This bug always been there
 2. I don't know why, but anytime I want to connect my laptop on screen projector or on big screens with touch panel in our meeting rooms, I'm not able to open Postman and basically any interaction is not possible. I experience this weird behavior only on certain "display devices", since my daily driver Sasmung S34E790C doesn't seem to have this problem. To be honest, I don't know how to reproduce this issue, therefore any tips are appreciated.

**Comment by SamvelRaja** [comment] 2017-09-12 12:59
Thanks for bringing this to our notice. We are tracking this here, so this would be a possible duplicate of #2833

**Closed as completed by SamvelRaja** 2017-09-12 12:59 UTC
Labels: bug
