### ISSUE TITLE
Dash in Collection Variable value resolves as NaN in Uri

### ISSUE THREAD

**Issue by gsperk** [a85/POSTMan-Chrome-Extension#7547] opened 2019-10-28 03:13 UTC
**Describe the bug**
I'm starting to replace some environment variables with collection variables. 
But a dash in Collection Variable value resolves as NaN in the request Uri. The same value in an environment variable is sent correctly.

**To Reproduce**
1. Set a collection variable. e.g. pm.collectionVariables.set("reqUrlEntity1Id", JSON.parse(res.text()));
2. Use the collection variable in a request e.g. https://{{base_url}}/api/users/emails/{{reqUrlEntity1Id}}

As a collection variable, 8bded690-2244-4eb3-ac2f-09baba3a2d96  resolves to https://my_base_url/api/users/emails/NaN

If I use an environment variable I don't get this problem.

**Expected behavior**
Expecting the value to pass through as per environment variables.

https://my_base_url/api/users/emails/8bded690-2244-4eb3-ac2f-09baba3a2d96

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [v7.10.0]
 - OS: [Win 7 64bit]

**Comment by codenirvana** [comment] 2020-03-10 22:19
@gsperk Can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by shamasis** [comment] 2020-03-11 13:52
@gsperk ... just to add, we tried it locally and could not reproduce. We were using app version 7.20.0. I've attached a sample collection for you to import and try.

[Test #7547.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/4318598/Test.7547.postman_collection.json.zip)

**Comment by codenirvana** [comment] 2020-05-29 20:32
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-05-29 20:32 UTC
Labels: bug, product/runtime, blocked/need-repro
