### ISSUE TITLE
Postman is crashing when there's an SSL error during a Collection Runner execution

### ISSUE THREAD

**Issue by Warkdev** [a85/POSTMan-Chrome-Extension#7597] opened 2019-11-07 09:48 UTC
**Describe the bug**
When using Postman to generate requests towards an untrusted website (unknown root or unmatching certificate), a valid error message appears within the Postman editor.

When running the same request from the Collection Runner, this one will fail and the whole Postman application will crash.

**To Reproduce**
1. Create a request targeting a server with a name that doesn't match certificate CN or SAN.
2. Click on 'Send', see that the error appears properly in the editor.
3. Run that exact same request from the Collection Runner.
4. Notice that Postman app is crashing.
5. Notice this error message within the main.log:
`[7108][1573119516636][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Converting circular structure to JSON","stack":"TypeError: Converting circular structure to JSON\n    at JSON.stringify (<anonymous>)\n    at wrapError (MyDrive:\\Users\\MyUsername\\AppData\\Local\\Postman\\app-7.11.0\\resources\\app.asar\\services\\RuntimeBridge.js:41:24)\n    at Function.io (MyDrive:\\Users\\MyUsername\\AppData\\Local\\Postman\\app-7.11.0\\resources\\app.asar\\services\\RuntimeBridge.js:191:48)\n    at Requester.emit (events.js:182:13)\n    at Requester.EventEmitter.emit (domain.js:442:20)\n    at onEnd (MyDrive:\\Users\\MyUsername\\AppData\\Local\\Postman\\app-7.11.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:306:22)\n    at Request._callback (MyDrive:\\Users\\MyUsername\\AppData\\Local\\Postman\\app-7.11.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:439:24)\n    at self.callback (MyDrive:\\Users\\MyUsername\\AppData\\Local\\Postman\\app-7.11.0\\resources\\app.asar\\node_modules\\postman-request\\request.js:255:12)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:442:20)\n    at Request.onRequestError (MyDrive:\\Users\\MyUsername\\AppData\\Local\\Postman\\app-7.11.0\\resources\\app.asar\\node_modules\\postman-request\\request.js:1089:8)\n    at ClientRequest.emit (events.js:187:15)\n    at ClientRequest.EventEmitter.emit (domain.js:442:20)\n    at TLSSocket.socketErrorListener (_http_client.js:382:9)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at`

**Expected behavior**
The collection runner should throw an exception to the run indicating the error and continuing with the next request.

**Screenshots**
Can be produced if necessary.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.11.0
 - OS: Windows 7 32-bits

**Additional context**
Turning off SSL verification is precisely an option, however, knowing which of my servers are not using the right certificates configuration is also something that I'd like to validate and thus, disabling it is not really an option if I want to do it with Postman.

**Comment by appurva21** [comment] 2020-02-11 07:09
Hi @Warkdev,  we made have certain improvements in Collection Runner during our last few releases. Can you please update to the latest version of the app and check if this issue still persists for you.

To get the latest version either you can update the existing app or can download a new app from [here](https://www.postman.com/downloads/)

**Comment by appurva21** [comment] 2020-02-17 12:17
Hey @Warkdev, 
Closing the issue as we are not able to reproduce it on the latest app version (`v.7.18.0`). Please feel free to reopen if the issue still persists.

**Closed as completed by appurva21** 2020-02-17 12:17 UTC
Labels: bug, collection-runner, tls, product/runtime
