### ISSUE TITLE
Posting a file in multi-part formdata through code-gen doesn't send the file 

### ISSUE THREAD

**Issue by ShannonRichard** [a85/POSTMan-Chrome-Extension#2875] opened 2017-03-31 13:19 UTC
1. Postman Version:  4.10.5
 2. App (Chrome app or Mac app): Chrome App 
 3. OS details: Windows 10 (64bit)
 4. Is the Interceptor on and enabled in the app: I Think so, but I don't see any results
 5. Did you encounter this recently, or has this bug always been there: I don't know as I just started to use this feature
 6. Expected behaviour: uploading a file
![postman image 1](https://cloud.githubusercontent.com/assets/25206368/24551755/51e3fe34-15e9-11e7-89b8-03e6065778ad.PNG)
So I post a file I know I'm duplicating information here (testing)
![postman image 2](https://cloud.githubusercontent.com/assets/25206368/24551807/8ff791cc-15e9-11e7-9b4c-08fae6fbd957.PNG)
within my server api I don't recieve the file, if I use curl I do
when I view "code" in the http request this is what I see
![postman image 3](https://cloud.githubusercontent.com/assets/25206368/24551917/1ecd549a-15ea-11e7-9c92-5c0c4d3a841e.PNG)
but when I "code" in the curl request 
![postman image 4](https://cloud.githubusercontent.com/assets/25206368/24551932/2d1bf880-15ea-11e7-8c09-7894b6893374.PNG)
as you can see in the http request it doesn't contain my file, but the curl version does. I think this is the issue, because when I copy/paste the produced curl I get the connection within my app.

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
In step 6

**Comment by abhijitkane** [comment] 2019-04-19 03:28
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2469

**Closed as completed by abhijitkane** 2019-04-19 03:28 UTC
Labels: bug, code-generator
