### ISSUE TITLE
OAuth2.0 "Request Token" feature Broken

### ISSUE THREAD

**Issue by marshallr12** [a85/POSTMan-Chrome-Extension#6895] opened 2019-07-10 15:18 UTC
**Describe the bug**
After requesting a token using "Get New Access Token", the embedded browser shows an empty screen on callback. Following the same steps below in v7.2.2 works properly.

**To Reproduce**
1. Go to 'EDIT COLLECTION'
2. Click on 'Authorization tab'
3. Set "Type" dropdown to "OAuth2.0"
4. Click "Get New Access Token"
5. Fill in the form fields using

- Auth URL: https://[your_account].auth0.com/authorize
- Access Token Url: https://[your_account].auth0.com/oauth/token
- Callback URL: https://www.getpostman.com/oauth2/callback
- Client ID: (Auth0.com application client id)
- Client Secret: (Auth0.com application secret)

The Auth0 account is configured to automatically append the audience.

**Expected behavior**
In v7.2.2, after sending the token request, the token text will appear in the browser window along with a button to accept the token.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.3.3
 - OS: Windows 10

**Additional context**

**Comment by danielforster1** [comment] 2019-07-10 21:31
I am also having the same issue. I am getting a blank screen when clicking "Request Token"

**Comment by pratnala** [comment] 2019-07-11 00:15
Having the same issue. Been broken since v7.3.1. I am on Win 10 1903 x64.

**Comment by ankurdengla** [comment] 2019-07-11 08:00
@marshallr12 @danielforster1 @pratnala Thanks for reporting the issue. We are looking into this. It would be helpful to us if you could share the logs found in View -> Developer -> View logs in Explorer. Please mail the logs to help@getpostman.com

**Comment by ankurdengla** [comment] 2019-07-11 09:42
@marshallr12 @danielforster1  @pratnala 
**UPDATE** - We are still investigating the issue but we found a workaround meanwhile. Could you try changing the callback url from https://www.getpostman.com/oauth2/callback to https://app.getpostman.com/oauth2/callback ? You'll also need to add it in `Allowed Callback URLs` in you Auth0 app

**Comment by marshallr12** [comment] 2019-07-11 18:54
@ankurdengla1996 The new callback URL worked for me.

**Comment by pratnala** [comment] 2019-07-11 23:34
I can't confirm this as the external app is not under my control, so the call gets denied and fails. At least, it wasn't stuck under redirecting.

**Comment by ankurdengla** [comment] 2019-07-17 05:10
@marshallr12 @danielforster1 @pratnala The fix for this issue is now out on our Canary build (Postman Canary 7.3.4-canary01 - https://www.getpostman.com/downloads/canary)

**Comment by marshallr12** [comment] 2019-07-17 05:43
Great! Thank you.

**Closed as completed** 2019-07-22 07:11 UTC
Labels: bug, Auth, OAuth2, product/runtime

**Comment by toreskobba** [comment] 2019-07-31 10:44
Error is still in Version 7.3.5-canary03, let me know if you want the logs

**Comment by ankurdengla** [comment] 2019-07-31 10:53
Hey @toreskobba ! Could you elaborate a bit more about the kind of behaviour you're seeing when you click on "Request Token" ?
Also, could you tell us about the provider you're requesting the token from and the callback? This would help us in triaging the issue better as we are not able to reproduce the error with the current information available.

**Comment by toreskobba** [comment] 2019-07-31 11:01
Hi @ankurdengla1996 our bug is very much as described, when we do request token the browser window hangs with white screen (if we are not logged in we are sent to the login and then the browser hangs). We have our own oAuth server: 

Token Name: Token Name
Grant Type: Authorization Code
Callback URL: hostdesc://login
Auth URL: https://hostname/api/oauth/authorizations/new
Access token URL: https://hostname/api/oauth/accesstoken/
State: https://hostname/minside

Cliend Id and Secret is not shared but we have correct values there. Since this is our own oAuth server I see that the server gets the authorization grant request but never gets the request for the access token from the authorization code

**Comment by ankurdengla** [comment] 2019-08-01 06:39
Hey @toreskobba ! Could you send us the logs available in View -> Developer -> View Logs in Finder/Explorer to help@getpostman.com with the subject as "Logs for [Github issue]" from your current app version?

Also, could you try out our latest Canary build [PostmanCanary 7.3.5-canary04](https://www.getpostman.com/downloads/canary) ?  Do let us know if it fixes your issue.

**Comment by toreskobba** [comment] 2019-08-01 10:52
Still hangs on Postman v7.3.5-canary04, have sent logs

**Comment by ankurdengla** [comment] 2019-08-02 10:36
Since this issue is already closed, we are tracking OAuth2 related bugs in this thread - https://github.com/postmanlabs/postman-app-support/issues/7032

**Comment by toreskobba** [comment] 2019-08-02 14:31
@ankurdengla1996 I saw your email about trying the canary version but I am off for a week vacation now and did not manage to download and try. I gave the email and link to a colleague maybe they will try it. 

Thanks for fast replies.

**Comment by ankurdengla** [comment] 2019-08-09 10:59
Hey @toreskobba! We were able to reproduce the issue at our end and our working on a fix for it. Thanks for bringing the issue to our notice. 
Also, please follow https://github.com/postmanlabs/postman-app-support/issues/7032 for updates on the fix.
