### ISSUE TITLE
console.log no longer working under a function of a Collection Pre-request Script

### ISSUE THREAD

**Issue by Tiptup300** [a85/POSTMan-Chrome-Extension#11733] opened 2023-02-16 16:44 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the past I had logic within the Collection Pre-request Script which is used across our collections for passing variable data around. 

I had an optional parameter that allowed showing all the debug information in case of an issue. Just today on attempting to use it, I found that it's no longer working.

I have checked the Postman Console under View > Show Postman Console as well as the Console under View > Developer > Show Web Tools Console. 

I also have all log types selected under View > Show Postman Console. 

It is just not working at all anymore. If I do a console.log directly under the Pre-request script of a call, it works.

If I do a console.log directly under the Pre-request script of a collection, it also works, but not if I put it under a function.

### Steps To Reproduce

1. Create a new collection
2. Under that collection, choose Pre-request script and add this code:

```
testConsoleFunc = function() {
    console.log("NOT WORKING");

    return "working";
}
```

3. Under that collection add a call.
4. Under that call, under Pre-request script, add this code:

```
let func = testConsoleFunc();
console.log(func);
```

5. Run the call. 

Note that the console will only show "working" and not "NOT WORKING" 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/55206973/219430346-042c066d-16b5-4908-ac71-2468f2aa2e17.png)
![image](https://user-images.githubusercontent.com/55206973/219430492-3853acb7-50d3-462c-83c6-207c29c3c19a.png)
![image](https://user-images.githubusercontent.com/55206973/219430741-2617fe81-0aab-4c72-bb67-d77a364903e6.png)

![image](https://user-images.githubusercontent.com/55206973/219430819-d725c7e0-e51a-4cdf-a62b-97f09ba142fa.png)
Not filtering any log types

### Operating System

Windows

### Postman Version

v10.10.5

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by coditva** [comment] 2023-02-17 05:52
@Tiptup300 Thanks for reporting! I'm marking this as a duplicate of #11710. Will post updates there.

**Closed as completed by coditva** 2023-02-17 05:52 UTC
