### ISSUE TITLE
Beautify JSON In Raw JSON Requests

### ISSUE THREAD

**Issue by qwo** [a85/POSTMan-Chrome-Extension#1473] opened 2015-10-01 16:48 UTC
Related to #348 

The left off of the conversation was prettifying the json response. I use interceptor and postman stock and theres some large json payloads that need to be sorted through.

I often have jsbeautifier.org also pulled up because i copy paste the payload from there back into the prompt to prettify to read and edit the request.

It would be nice if there was a button or results were automatically beautified.

**Comment by harshil93** [comment] 2016-11-25 07:07
Ctrl + B seems to work

**Comment by sdnts** [comment] 2016-11-25 10:21
@stanzheng In the response, the Pretty view is exactly what you are looking for. This will beautify the response (indentation etc.)

Cmd/Ctrl + B works to beautify the raw request body section when it is valid, depending on the type of body (JSON / XML etc.)

Closing this :)

**Comment by avindra** [comment] 2017-04-07 17:57
CTRL+B does not seem to do anything. Nor is it documented in the shorcut list:

![image](https://cloud.githubusercontent.com/assets/126848/24812964/29831e1e-1b9a-11e7-95d6-c2a4eb8eff7f.png)

**Comment by vkadam** [comment] 2017-05-01 20:34
@avindra I agree it's not documented, but its working for me perfectly for raw request, when I have Content-Type = application/json selected in combo box, and my cursor is in text-area.

**Comment by reggi** [comment] 2017-09-18 15:58
⌘(CMD) + b

**Comment by jordanch** [comment] 2017-12-27 11:03
Re-open, this is still undocumented under shortcuts.

**Comment by vkras** [comment] 2018-02-16 15:29
It just stopped working completely after most recent update (Windows Client).
Please bring this very useful feature back (Ctrl + B)

**Comment by liesislukas** [comment] 2018-03-17 11:23
Cmd+B works for me, macOS native client Version 6.0.9 (6.0.9) but still **undocumented**

**Comment by yogimishra96** [comment] 2018-04-12 07:32
CTRL + B worked for me (Ubuntu 16.04 LTS ) 
Postman for Linux Version 5.5.0 Linux 4.4.0-116-generic / x64

*Remember 
1. your cursor should be inside text area otherwise it won't work.
2. select  JSON(application/text). huh obviously if you paste json their.

**Comment by gustavo-almeida** [comment] 2018-04-12 14:33
~Stopped working today after update to v6.0.10 (Windows client)~
Back to work on same version. Crazy

**Comment by pkgajulapalli** [comment] 2018-10-09 11:32
stopped working in mac after updating to 6.4.2

**Comment by J-A-M-E-5** [comment] 2018-10-10 00:51
Can confirm, this was driving me crazy as I always used this feature and it is now broken with latest OSX release 6.4.2

**Comment by shirshak55** [comment] 2018-10-14 14:45
not working :(


I was madly pressing cmd +b and nothing was happening. Above reply should be hidden :(

**Comment by numaanashraf** [comment] 2018-12-05 11:14
Apologies for the regression folks. I can confirm this has been fixed in the latest version of Postman (v6.5.3).

**Closed as completed by numaanashraf** 2018-12-05 11:14 UTC
Labels: bug, regression
