### ISSUE TITLE
Windows freezing after starting postman application

### ISSUE THREAD

**Issue by SheikSena** [a85/POSTMan-Chrome-Extension#9044] opened 2020-09-11 09:35 UTC
**Describe the bug**
Hello Team, Whenever I open the postman application in my windows machine the entire system is getting struck not able to open other applications as well. Can you please fix this issue. Thanks

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.32.0
 - OS: Windows 10

**Comment by RaisinTen** [comment] 2022-02-18 08:12
Hey @SheikSena is this still an issue?

**Comment by RaisinTen** [comment] 2022-02-18 08:22
Closing as I'm unable to reproduce this on my Windows 10. Please reopen if it's still relevant.

**Closed as completed by RaisinTen** 2022-02-18 08:22 UTC
Labels: bug, platform/windows, product/desktop-foundation, component/electron, version/7
