### ISSUE TITLE
I am unable to navigate to postman result 

### ISSUE THREAD

**Issue by npatelmob** [a85/POSTMan-Chrome-Extension#7129] opened 2019-08-16 12:36 UTC
**Describe the bug**
Having a test result for collection which I rerun 100 times , I am unable to navigate and open result after 30th 

**To Reproduce**
1. Generate report for around 50+ iteration for any collection 
2. Try to navigate too the last result and try to open it 

**Expected behavior**
It should navigate and open it properly 

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by saswatds** [comment] 2019-09-06 09:47
Hi @npatelmob we recently fixed some issue with scrolling in the runner in app version 7.6.0. Can you update to the latest version and confirm if the issue is fixed for you?

**Comment by saswatds** [comment] 2019-09-24 03:45
Hi, I will be closing this issue for now, because we were unable to reproduce this issue on our end and does not seem like any other user is facing the same problem. It might have been an intermittent thing. 

Feel free to re-open this issue, if your problem persists.

**Closed as completed by saswatds** 2019-09-24 03:45 UTC
Labels: performance, collection-runner, pending-close, product/runtime
