### ISSUE TITLE
problem with oauth credentials

### ISSUE THREAD

**Issue by czardoz** [a85/POSTMan-Chrome-Extension#2451] opened 2016-11-02 09:31 UTC
Originally reported by @MonneOnrust at: https://github.com/postmanlabs/postman-runtime/issues/137

---------------------

 1. Postman Version: N/A
 2. App (Chrome app or Mac app): N/A
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

I’m trying to get an OAuth2.0 access token for my web request, but I keep getting an error. 

The authorization server is an Azure Active Directory instance. There an application is set up as a web app with client credentials and the getpostman.com reply URL. 

I’ve tried different authURLs, but all with the same response. When I click Request Token, the error _‘Error getting access token from client_credentials’ flow. Could not send request’_ occurs. When I look in the development tools, I see a 400 Bad Request in the response with the following body:
_{"error":"invalid_request","error_description":"AADSTS90014: 'client_assertion' or 'client_secret' is required for the 'client_credentials' grant type.\r\nTrace ID: 52b99b1a-fc0c-401c-b2b1-3fac85dfe6cd\r\nCorrelation ID: 95d99f1e-fa0d-48c8-834e-4df2f1a9dd7b\r\nTimestamp: 2016-10-12 13:05:49Z","error_codes":[90014],"timestamp":"2016-10-12 13:05:49Z","trace_id":"52b99b1a-fc0c-401c-b2b1-3fac85dfe6cd","correlation_id":"95d99f1e-fa0d-48c8-834e-4df2f1a9dd7b"}_

These are my test settings, which you can also use if you want:
Auth URL (tried both): 
-	https://login.windows.net/common/oauth2/authorize?resource=https%3A%2F%2Ffacturatiefad-sys.royalfloraholland.com%2F
-	https://login.microsoftonline.com/7e58a9c5-ca4b-4ac7-b347-243188106279/oauth2/authorize?resource=https%3A%2F%2Ffacturatiefad-sys.royalfloraholland.com%2F 
Access token URL (tried both):
-	https://login.microsoftonline.com/common/oauth2/token
-	https://login.microsoftonline.com/7e58a9c5-ca4b-4ac7-b347-243188106279/oauth2/token 
Client ID:
df68d1a3-68e4-4965-816f-b9106a9d565b
Client Secret:
kESmQvsmtwWpacJ1mywse5jW2KIXYqhX0rTL4S7+0vk=

I’ve included pictures of the errors and developer tools.

![error](https://cloud.githubusercontent.com/assets/5955708/19898403/2649a34e-a05c-11e6-987e-c9ec565b3bd7.png)
![errordetails](https://cloud.githubusercontent.com/assets/5955708/19898402/26475b20-a05c-11e6-8312-4d6e3f77f37d.png)

**Comment by sdnts** [comment] 2016-11-02 10:11
@MonneOnrust I looked at the Office 365 API (which I assume you are using), and it looks like they want you to use the Authorization Flow, not the Client Credentials flow.
Can you try with the Authorization flow and check if this works?

**Comment by MonneOnrust** [comment] 2016-11-02 11:57
1.Postman Version: 4.8.1
2.App: Chrome App (Chrome 54.0.2840.71)
3.OS details: Windows 7 x86 (also reproduced on Windows 10 x64)
4.Is the Interceptor on and enabled in the app: Tried with interceptor on and off: same result
5.Did you encounter this recently, or has this bug always been there: I just tried this for the first time, though other have reported this to have happened earlier (~2 months)
6.Expected behaviour: Postman can fetch an access token normally
7.Console logs: added below
![console](https://cloud.githubusercontent.com/assets/5955708/19927849/ea01e266-a0fb-11e6-93dd-5316af1f179b.PNG)

8.Screenshots (if applicable)

**Comment by MonneOnrust** [comment] 2016-11-02 12:30
@madebysid I tried that. After typing in my password it gave me a white screen (see below). No console logging is done in Chrome Developer Tools, nor are there any network calls.

By the way, I used this video https://blogs.msdn.microsoft.com/devkeydet/2016/03/22/using-postman-with-azure-ad/ to setup the integration with Azure AD.

![badrequest](https://cloud.githubusercontent.com/assets/5955708/19928800/679a1028-a100-11e6-9243-7e4254f16c0c.PNG)

**Comment by sdnts** [comment] 2016-11-02 12:51
@MonneOnrust Ah so you see this white screen in the pop up window that opens up on clicking `Generate Token`? In that case, you'll have to open up the DevTools of the popup window.
It looks like the access token redirection isn't happening properly. 
Can you do that and check if there are any errors in there?

**Comment by MonneOnrust** [comment] 2016-11-02 13:28
Ah, thank you. That was a good tip. I resolved the issue. In the Developer Tools it said the resource was not found in Azure AD. I then realized I had the resource= part in the Auth URL wrong. Apparently you need to fill in the Sign-on URL from the application in Azure AD behind resource=. In my case, this was not the full URL of the app, but it was https://facturatiefad-sys. Once I filled this in, I could get the Authorization Code flow working. The Client Credentials flow still gives the same error, but the Authorization Code flow suffices for me.

Thank you very much for your help!

**Comment by sdnts** [comment] 2016-11-02 13:35
That's good to hear. The client credentials flow probably does not work because the Azure API was not built to support it.
Closing this.

**Closed as completed by sdnts** 2016-11-02 13:35 UTC
Labels: support
