### ISSUE TITLE
Large integer ID value in JSON object corrupted when beautified

### ISSUE THREAD

**Issue by rossknudsen** [a85/POSTMan-Chrome-Extension#6332] opened 2019-04-21 02:31 UTC
**Describe the bug**
When using the beautification feature for the body of a request, I discovered that the values of my JSON object were being altered.

**To Reproduce**
1. Create new Request
2. Go to Body tab
3. Select 'Raw' and 'JSON' for the types
4. Enter the following JSON value in the body content area: `{"id": 70023615234971703,"otherId": 70023615234971704}`
5. Observe that the ID values are both different above (last digit differs).
6. Click Beautify
7. Observe that the ID values are now the same and both equal to the first value.

**Expected behavior**
Beautification should not change the value of the ID fields.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/2489915/56464702-75981b80-6443-11e9-97a2-3c2912a3f3a5.gif)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.0.7
 - OS: Windows 10 64bit

**Discussion**

Our IDs are constructed using serial numbers and timestamps to ensure unique keys across devices, which is why they happen to be so large.  In playing with the numbers, I think it is just coincidence that both values take on the value of the first ID.

It seems that the values we are using are larger than the Javascript `Number.max_safe_integer` value.  This may make it difficult to 'fix' this issue.

**Comment by vikiCoder** [comment] 2019-09-17 13:57
Closing this as a duplicate of the following issue:
https://github.com/postmanlabs/postman-app-support/issues/5658

**Closed as completed by vikiCoder** 2019-09-17 13:57 UTC
Labels: bug
