### ISSUE TITLE
Upload file over 10 mb

### ISSUE THREAD

**Issue by JonathanNet** [a85/POSTMan-Chrome-Extension#6772] opened 2019-06-22 18:16 UTC
**Upload file over 10 mb fails**
I discovered that if I upload a image over 10 mb then my php doesnt recive the file from postman POST call, I post it as form-data.

**Comment by shamasis** [comment] 2019-06-22 18:44
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4375

Note that it’s been hit and miss for us in reliably reproducing this earlier. Maybe you could add more info to that issue.

**Comment by JonathanNet** [comment] 2019-06-22 18:54
It dosent do black screen as the issue you posted.

I use the last version of postman, and then I select a file under 10 mb, it works, but if the file is larger I dont get any infomation about $_FILES in the php

**Comment by shamasis** [comment] 2019-06-22 21:35
Ok. I have reopened the issue. We will try reproducing this at our end. Meanwhile, for us to be able to reproduce, kindly send us details of app version, OS and how much memory your system has. Also, are you uploading file as raw body or as part of form-data? As much information you send, it will help us that much to solve this faster.

**Comment by abhijitkane** [comment] 2019-06-23 04:43
@JonathanNet Also, can you check the `post_max_size` and `upload_max_filesize` directives in php.ini? You can override this limit in your php script too - https://stackoverflow.com/a/11381040/384155

**Comment by JonathanNet** [comment] 2019-06-24 16:48
> @JonathanNet Also, can you check the `post_max_size` and `upload_max_filesize` directives in php.ini? You can override this limit in your php script too - https://stackoverflow.com/a/11381040/384155

It is set for 200mb, so its not that, and I tested with Insomnia, and it works fine in that app, but I better like Postman :)

**Comment by JonathanNet** [comment] 2019-06-24 17:20
> Ok. I have reopened the issue. We will try reproducing this at our end. Meanwhile, for us to be able to reproduce, kindly send us details of app version, OS and how much memory your system has. Also, are you uploading file as raw body or as part of form-data? As much information you send, it will help us that much to solve this faster.

As I wrote, It is sent as form-data, I have 16gb memory, and I use App version:

Postman for Windows
Version 7.2.2
win32 10.0.18362 / x64

**Comment by a85** [comment] 2019-12-01 08:19
Closing as duplicate of #4375

**Closed as completed by a85** 2019-12-01 08:19 UTC
Labels: performance, large-request, duplicate, product/runtime
