### ISSUE TITLE
Collection run: missing total duration information

### ISSUE THREAD

**Issue by jooleeanh** [a85/POSTMan-Chrome-Extension#4023] opened 2018-01-04 14:56 UTC
## App Details:

```
Postman for Mac
Version 5.5.0
OS X 10.12.6
```

When doing a collection/folder run, the total duration of the run isn't visible anywhere. It is only available when exporting the run (`"totalTime"`). It is the same for 'delay' (albeit seemingly less important).

It would be nice to see the information in the following places:
-  Collection Runner > Run Results (perhaps next to the 'just now')
![image](https://user-images.githubusercontent.com/9873597/34568879-7c21c1f4-f167-11e7-89bc-8ca98363eaa2.png)
- Collection Runner - Recent Runs (perhaps next to the date)
![image](https://user-images.githubusercontent.com/9873597/34568944-9e20a2e8-f167-11e7-8358-d409da0a9c5e.png)

**Comment by numaanashraf** [comment] 2018-01-05 12:40
Thanks for the feedback @jooleeanh. I've passed this along to the team. 😄

**Comment by malvikach** [comment] 2022-09-21 14:47
closing this as its a duplicate of this issue: https://github.com/postmanlabs/postman-app-support/issues/2672

**Closed as completed by malvikach** 2022-09-21 14:47 UTC
Labels: feature, collection-runner, product/runtime
