### ISSUE TITLE
When selection a Collection or Folder in Builder window the details are no longer passed to the Runner

### ISSUE THREAD

**Issue by polydoreplasden** [a85/POSTMan-Chrome-Extension#3916] opened 2017-12-06 11:16 UTC
## App Details:

Postman helps you develop APIs faster
Postman for Windows
Version 5.4.1
win32 6.1.7601 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
This used to work ok but stopped working with the previous release.
 2. Expected behaviour:
When selecting a Collection or folder to run in the Builder window the details should get passed to Collection runner (i.e. be pre-filled when Runner window opens).
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Select a Folder to Run in the Runner:
![image](https://user-images.githubusercontent.com/33625396/33659059-be3921c0-da76-11e7-8abf-c63bc51bd844.png)
Click Run
![image](https://user-images.githubusercontent.com/33625396/33659108-de7c3fd0-da76-11e7-8958-0eba18169970.png)
The Runner opens but the selected Collection/Folder has not been pre-filled.

**Comment by sdnts** [comment] 2017-12-06 11:32
@polydoreplasden Looks like you're on a pretty old version of the app. I tried this with 5.4.0 (latest version as of now), and it seems to be working. Can you try updating and check if that resolves your issue?

**Comment by polydoreplasden** [comment] 2017-12-06 11:39
@madebysid sorry that app version was wrong - I've now put in the right version. We are running with the latest version.

**Comment by polydoreplasden** [comment] 2017-12-11 14:53
@a85   Hi, any reason this has been closed without resolution?

**Comment by a85** [comment] 2017-12-11 15:15
@polydoreplasden Wasn't sure from your comment that the issue is still valid.

**Comment by polydoreplasden** [comment] 2017-12-11 15:21
@a85 yes we are still seeing this issue.

I have just upgraded to 
Postman for Windows
Version 5.5.0
win32 6.1.7601 / x64

But this issue is still present.

**Comment by a85** [comment] 2017-12-11 15:52
Seems to be working fine for me. I'm on OS X

**Comment by harryi3t** [comment] 2018-02-17 09:59
Collection/Folder being pre-filled in the runner is fixed.
Environment being pre-filled is being tracked here https://github.com/postmanlabs/postman-app-support/issues/3887 (which is also fixed internally and should be available in the next release 🎉 )

**Comment by sanvipy** [comment] 2018-05-22 02:31
@harryi3t  @madebysid 
Hi,
This issue seems to have reborn on the latest update to Version

Running
Postman for Windows
Version 6.1.2
win32 6.1.7601 / x64

**Comment by harryi3t** [comment] 2018-05-22 03:00
@sanvipy Thanks for the bug report.
This is a known regression 🐛. We are already working on a fix.

**Comment by sivcan** [comment] 2018-05-24 04:30
@sanvipy We have a released a fix for this issue on our canary channel.
Can you try it out if it fixes the issue for you?
https://www.getpostman.com/canary

Canary builds can run alongside the main Postman app and won't affect your settings/data.

**Comment by sanvipy** [comment] 2018-05-25 09:10
Thanks @sivcan .. Looks good in the latest canary version

**Comment by sivcan** [comment] 2018-06-29 07:29
This has been fixed in v6.1.4
I advise all to update to the same.

**Closed as completed by sivcan** 2018-06-29 07:29 UTC
Labels: bug, pending-close, regression
