### ISSUE TITLE
Newman collection

### ISSUE THREAD

**Issue by Fr4ncis** [a85/POSTMan-Chrome-Extension#2011] opened 2016-04-21 15:49 UTC
The following collection
https://www.getpostman.com/collections/1d61540636161b64d1e7

works fine running in postman (e.g. try folder "featured") but in newman it seems to be temperamental when updating the collection, it stopped working. folder "featured cache" now seems to be working for comparison.

```
newman -e mapi_prod_v35.json -u https://www.getpostman.com/collections/1d61540636161b64d1e7 -f "featured"

Iteration 1 of 1
200 94ms /token/generate [GET] http://mapi.vouchercodes.co.uk/v3.5/token/generate
    ✔ Status code is 200
200 60ms /token/authorize [POST] http://mapi.vouchercodes.co.uk/v3.5/token/authorize
    ✔ Status code is 200
401 40ms /offer/getlist featured (random loc) [GET] http://mapi.vouchercodes.co.uk/v3.5/offer/getlist?list=featured&lat=52.6608&lng=-0.5869
    ✗ Status code is 200
401 56ms /offer/getlist featured (random loc) [GET] http://mapi.vouchercodes.co.uk/v3.5/offer/getlist?list=featured&lat=51.3485&lng=-1.4096
    ✗ Status code is 200
```

```
newman -e mapi_prod_v35.json -u https://www.getpostman.com/collections/1d61540636161b64d1e7 -f "featured cache"

Iteration 1 of 1
200 85ms /token/generate [GET] http://mapi.vouchercodes.co.uk/v3.5/token/generate
    ✔ Status code is 200
200 85ms /token/authorize [POST] http://mapi.vouchercodes.co.uk/v3.5/token/authorize
    ✔ Status code is 200
200 105ms /offer/getlist featured no loc [GET] http://mapi.vouchercodes.co.uk/v3.5/offer/getlist?list=featured
    ✔ Status code is 200
200 98ms /offer/getlist featured no loc [GET] http://mapi.vouchercodes.co.uk/v3.5/offer/getlist?list=featured
    ✔ Status code is 200
```

it is frustrating as we're relying on postman / newman for end-to-end tests (and we would like to ditch runscope) but we keep on finding bugs that block us :(

Sharing mapi_prod_v35.json via e-mail.

**Comment by czardoz** [comment] 2016-04-22 10:39
Thanks for sending the environment, Francesco! It helped me debug the issue faster :)

I've fixed the issue in Newman v2.0.9, you can update by running:

```
npm i -g newman@2.0.9
```

**Comment by abhijitkane** [comment] 2016-04-25 23:57
Fixed in Newman. Closing this.

**Closed as completed** 2016-04-26 07:13 UTC

**Comment by dbkaynor** [comment] 2019-01-10 17:02
I have a collection that works fine in runner but will not run with Newman. The issue is that the collection level variables do not seem to be exported so Newman cannot find them. I see there is a way to import an environment (-e, --environment [file|URL]) but I do not know how to export the environment.
