### ISSUE TITLE
The last column OF data loaded from CSV in runner seems end with "\r" and it caused fail everytime when it came to the end

### ISSUE THREAD

**Issue by S0im** [a85/POSTMan-Chrome-Extension#3178] opened 2017-06-19 11:20 UTC
Postman for Windows
Version 5.0.0
win10 / x64

 1.
 I`ve seen this before，but seems like someoneelse has already post it to you，here，

> https://github.com/postmanlabs/postman-app-support/issues/3115

，
and，at Version 5.0.0 ,it appears a little different . In the preview,we can see the  .csv datafiles always end with "\r",I guess you guys forgot to consider the “\r”.
**But it's goes well if you chose chrome app or youreplace the datafile with txt**~

 2. Launch runner.
Load data .csv file .
Preview loaded data.
Data of last row, last column is appended with "\r".
And start the test, it failes at the last one~
![image](https://user-images.githubusercontent.com/25290478/27282722-c12e7994-5523-11e7-850d-a8c95b81f148.png)

**Comment by sdnts** [comment] 2017-06-19 12:27
Hi @S0im, I'm unable to reproduce this.I made a CSV file that looks like:
```
test,name
1,2
3,4

```
(notice the extra line at the end), and it was parsed correctly. Can you see if there are any extra characters at the end of your file? These are usually not visible to an editor, so you won't see it in Sublime etc. This might be causing the parser to fail.

If possible, can you send over a CSV file that you're seeing this with, to help@getpostman.com? I'll take a look at it and see what is causing this.

**Comment by S0im** [comment] 2017-06-20 01:00
Hi @madebysid，I checked it again after you replayed me. Then I found it seemed like the Microsoft excel caused this issue. When I create a .csv file by using Microsoft excel ， it always end with a "\r"，whitch is not visible .But，if you create a txt，and change it to csv，there is no problem. So，thank U  that I find out the reason whitch  had confused me for a long time. I zip the csv I used and maybe you can have a look.
[example.zip](https://github.com/postmanlabs/postman-app-support/files/1086697/example.zip)

**Comment by sdnts** [comment] 2017-06-20 08:37
Ah, you can get rid of this by just removing the last line from the CSV. I'm closing this, since the CSV is behaving as expected. Please reopen if you feel otherwise :)

**Comment by SLinde** [comment] 2017-07-12 11:02
Reproduces for Postman v5.0.2 for Windows win10 / x64.
If create a txt, and change it to csv, nothing changes. 
As the result the last row data is always appended with '\r'. Otherwise an extra line at the end is parsed to additional column 'null' with '\r' value.

**Comment by dudeintown** [comment] 2017-07-18 13:39
Hi I am still getting the error as 500 server error while creating JSON file data . attaching CSV for reference..

**Comment by sdnts** [comment] 2017-07-19 14:02
@SLinde Do you also see the extra characters while previewing the file?

@dudeintown What do you mean you get a 500 when creating the data file?

Can you guys attach a sample CSV with which you see this, here?

**Comment by nehemiahjason9** [comment] 2017-09-12 21:26
![image](https://user-images.githubusercontent.com/31903889/30349034-148225c8-97d7-11e7-9040-e8da931e6e54.png)

**Comment by nehemiahjason9** [comment] 2017-09-12 21:27
I'm having the same problem sending the .csv file. How do i need to fix this?

**Comment by S0im** [comment] 2017-09-25 01:11
As I  said, you can open the .csv files with a txt editer，such as notepad++. Then delete the extra line break at the end line.At last, save it as .csv file. Now,reload it in the runner,preview ,the '\r' is gone.

**Comment by siddharthpalav** [comment] 2018-04-09 04:18
Hi,

Following the above instruction I was able to remove the "\r" but in preview mode my last data is seen without double quotes, still the code is running fine. Please check the below screenshot.

![image](https://user-images.githubusercontent.com/31617295/38479067-87f4c4d2-3bda-11e8-95c4-37608446cdd6.png)

Question here is, why password of last row is not shown in "double quotes" 

And I am also getting error as "testdata is not defined", where testdata is the name of my file. Please check the below two screenshots.

![image](https://user-images.githubusercontent.com/31617295/38479140-ddebfa4a-3bda-11e8-8ed5-f5114de32b7b.png)

![image](https://user-images.githubusercontent.com/31617295/38479147-e8064fee-3bda-11e8-9acc-1200dae22bd3.png)

testdata file

![image](https://user-images.githubusercontent.com/31617295/38479209-3584225a-3bdb-11e8-82ea-b645468caf42.png)

**Comment by vikiCoder** [comment] 2019-06-12 06:46
Hi everyone,

I would like to inform that we have made some changes related to CSV file parsing under the hoods in the Postman App. This issue is fixed as part of those changes. It is available on the [latest canary](https://www.getpostman.com/downloads/canary) version (Version 7.1.1-canary07) of the app. You can checkout [canary](https://www.getpostman.com/downloads/canary) and let us know if you are still facing this issue in it.

**Comment by vikiCoder** [comment] 2019-06-19 04:57
Fix for this is out in [latest Postman App](https://www.getpostman.com/downloads/) (v7.2.1) as well.

**Closed as completed** 2019-06-19 06:39 UTC
Labels: bug, collection-runner, data-file/csv, product/runtime

**Comment by yaredw** [comment] 2019-06-19 17:30
I'm now receiving this error when attempting to run a collection with a CSV that were both working fine yesterday (before the newest release):
```
Error while parsing data file: Error: Invalid Closing Quote: got """ at line 2 instead of delimiter, row delimiter, trimable character (if activated) or comment
```

**Comment by vikiCoder** [comment] 2019-06-20 06:52
@yaredw If you were using double quotes '"' inside an unquoted string in CSV file with previous version of the app then it will now work with the latest version. You have to wrap the string in double quotes and escape the quotes inside the string using backslash `\` for it to work with latest version of the app.

See this comment if you need an example: https://github.com/postmanlabs/postman-app-support/issues/5551#issuecomment-501153348
