### ISSUE TITLE
Large number of history requests cause Postman to crash

### ISSUE THREAD

**Issue by ravigajera** [a85/POSTMan-Chrome-Extension#1818] opened 2016-03-09 09:30 UTC
too many crash when working how can i install old version of postman

**Comment by mstaalesen** [comment] 2016-03-09 09:52
Agreed. It keeps crashing several times per hour now. 

Any instructions on how to get the debug-log or crash logs from Postman are welcome!

Postman v4.0.1

**Comment by abhijitkane** [comment] 2016-03-09 09:53
@ravigajera  @mstaalesen Can you try the following:
1. Clear all your history requests (trashcan icon in the history tab), and restart after a minute or two.
2. If it's still not resolved, check the Console for errors - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by mstaalesen** [comment] 2016-03-09 10:08
@abhijitkane 
1. I've reinstalled the app twice. Attempting to clear the history requests now.
2. Console for errors:
   Crash of postman also closes the developer tools window, so i'm not able to see any errors there. Or am I doing something wrong?

**Comment by abhijitkane** [comment] 2016-03-09 10:13
Is there any specific action in the UI that triggers the crash?

**Comment by mstaalesen** [comment] 2016-03-09 11:05
Not that I can tell.

From the top of my head it has happened during:
- Sending a request (crashed just as the response was shown)
- Editing parameters for a request
- Switching between tabs
- Opening a request in a collection

That's why I was hoping there was some way to start Postman with some extra debug-parameters that would be stored to a file. Perhaps I can enable Chrome-debugging?

**Comment by abhijitkane** [comment] 2016-03-09 11:09
The DevTools is the only way to debug the app. But, as you said, a crash of the app will close the DevTools window as well.
How many collections do you have saved?

**Comment by mstaalesen** [comment] 2016-03-09 11:10
12 collections at the moment. ~200 requests in total over the different collections.

**Comment by mstaalesen** [comment] 2016-03-09 11:22
Ok, I might have found a way to get some logging. I enabled google chrome debug logging:
`google-chrome --enable-logging --v=1`

This stores a file to `~/.config/google-chrome/chrome_debug.log` 

I was able to recreate a crash (by just clicking around for a while, opening a few requests in different tabs and clicking send ~20-30 times on one request). I think this might be related to the crash:

> [19598:19633:0309/121423:VERBOSE1:http_auth_controller.cc(256)] The server (..REMOVED..) requested auth 
> [19598:19633:0309/121423:VERBOSE1:mime_type_resource_handler.cc(269)] To buffer: https://analytics.getpostman.com/events
> [19598:19633:0309/121423:VERBOSE1:http_auth_controller.cc(256)] The server (..REMOVED..)  requested auth 
> [19598:19633:0309/121426:VERBOSE1:http_auth_controller.cc(256)] The server (..REMOVED..)  requested auth 
> [19687:19735:0309/121426:WARNING:x11_util.cc(1407)] X error received: serial 154, error_code 9 (BadDrawable), request_code 155, minor_code 3 (Unknown)
> [19687:19735:0309/121426:WARNING:x11_util.cc(1407)] X error received: serial 155, error_code 9 (BadDrawable), request_code 155, minor_code 7 (Unknown)
> [19598:19598:0309/121430:ERROR:CONSOLE(42)] "Uncaught TypeError: Cannot read property 'gain' of undefined", source: https://www.google.no/logos/2016/rockmore/rockmore16-4.js (42)
> [19598:19633:0309/121440:ERROR:connection_factory_impl.cc(367)] Failed to connect to MCS endpoint with error -102
> [19598:19633:0309/121443:VERBOSE1:invalidation-client-core.cc(99)] Registration state not in sync with server: Last known digest: { num_registrations: 0 registration_digest: "\3329\243\356^kK\r2U\277\357\225`\030\220\257\330\007\t"  }, Requested regs: SimpleRegistrationStore: 26 registrations
> [19598:19633:0309/121443:VERBOSE1:invalidation-client-core.cc(888)] Sending info message to server; request server summary = true
> [19598:19633:0309/121443:VERBOSE1:protocol-handler.cc(264)] Batching info message for client: { client_version: { version: { major_version: 3 minor_version: 20140204  } platform: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36" language: "C++" application_info: "chrome-sync"  } server_registration_summary_requested: true  }
> [19598:19598:0309/121444:VERBOSE1:mutable_profile_oauth2_token_service_delegate.cc(216)] MutablePO2TS::RefreshTokenIsAvailable

I'll see if I can find a better way of reproducing the problem.

**Comment by mstaalesen** [comment] 2016-03-09 12:10
Alright, I've pinpointed the problem. It's a memory leak somewhere in Postman.
To be able to reproduce this quickly. Open ~10 request tabs, and click Send a few times. Watch as the memory usage steadily increases untill the following message appears in the Command Line where Chrome was started with debug:

> #
> 
> # Fatal error in heap setup
> 
> # Allocation failed - process out of memory
> 
> #

---

Another crash:

> #
> 
> # Fatal error in heap setup
> 
> # Allocation failed - process out of memory
> 
> #
> 
> [23274:23274:0309/125951:ERROR:CONSOLE(42)] "Uncaught TypeError: Cannot read property 'gain' of undefined", source: https://www.google.no/logos/2016/rockmore/rockmore16-4.js (42)

Let me know if there is anything else I can do to help you with this.

**Comment by mstaalesen** [comment] 2016-03-09 12:15
Every "Send" click allocates ~300 MB memory.

**Comment by sdnts** [comment] 2016-10-18 11:19
We've made several improvements with regard to performance.
Can you still replicate this? Feel free to reopen if this is still an issue!

**Comment by mstaalesen** [comment] 2016-10-18 13:17
It's not as easy to reproduce as earlier, but yes - it still crashes. Really looking forward to moving away from the Chrome app!

**Comment by RangerDan** [comment] 2016-12-13 20:29
Still reporting crashes when I have numerous tabs open with large requests and responses.  The app will crash, and sending the same transaction again will cause it to crash again.  

Reducing the number of tabs prevents the crashes from happening for the rest of the day, but something is funny with how it handles many tabs.

Ver 4.9.0; linux / x86-64; Chrome 55.0.2883.75

**Comment by urishalit** [comment] 2017-03-01 05:57
This happened to me constantly
Version: 4.10.2 Chrome Version 54.0.2840.71 (64-bit). My OS is Ubuntu 16

I had something like 15 tabs open, after each crash it would resume all the tabs, and then after about 2-4 requests it would crash again. I am guessing somehow it got to an illegal state or something of the sort.

Seems like closing all the tabs has resolved the issue (or made it more scarce)

**Comment by ppragnya** [comment] 2017-03-02 12:05
Postman has been crashing a lot constantly on my system recently too.
Version  4.10.2 & Chrome Version 56.0.2924.87 (64-bit) . My OS is a 64-bit OS of Windows 7 Enterprise Edition .

Even if I have a few (i.e. 2-3) tabs open but 2 windows of the postman open, it still keeps crashing for me.
I am sure it has been working well with multiple windows & tabs opened before.  Has there been any recent updates to Postman that could be causing this performance issue ?

I have tried re-installing and clearing the history . But this didn't helped me either.

Checked the Google Chrome Task Manager to find this : 

![image](https://cloud.githubusercontent.com/assets/14329243/23505903/8c145fda-ff3d-11e6-8eed-ba6a4ebe049e.png)

**Comment by danielkucera** [comment] 2017-03-20 10:59
Postman for Chrome
Version 4.10.3
linux / x86-64
Chrome 56.0.2924.76

chromium-browser --version
Chromium 56.0.2924.76 Built on Ubuntu , running on Ubuntu 16.10

I'm getting this stack trace:

```
#
# Fatal process OOM in heap setup
#

Received signal 4 ILL_ILLOPN 7f5fc6ddde19
#0 0x7f5fe2c9000e base::debug::StackTrace::StackTrace()
#1 0x7f5fe2c90403 <unknown>
#2 0x7f5fe2fa5630 <unknown>
#3 0x7f5fc6ddde19 v8::base::OS::Abort()
#4 0x7f5fd8b9f03d <unknown>
#5 0x7f5fd8b9f23c <unknown>
#6 0x7f5fd9042f1f <unknown>
#7 0x7f5fd920bf36 <unknown>
#8 0x7f5fd8bc62e8 v8::Isolate::New()
#9 0x7f5fd98597dd gin::IsolateHolder::IsolateHolder()
#10 0x7f5fc3faf990 blink::V8PerIsolateData::V8PerIsolateData()
#11 0x7f5fc3fb0160 blink::V8PerIsolateData::initialize()
#12 0x7f5fc4abb04e blink::WorkerBackingThread::initialize()
#13 0x7f5fc4acb151 blink::WorkerThread::initializeOnWorkerThread()
#14 0x7f5fc4ac9f86 <unknown>
#15 0x7f5fe2c91543 base::debug::TaskAnnotator::RunTask()
#16 0x7f5fd1b30f4f blink::scheduler::TaskQueueManager::ProcessTaskFromWorkQueue()
#17 0x7f5fd1b31ab0 blink::scheduler::TaskQueueManager::DoWork()
#18 0x7f5fe2c91543 base::debug::TaskAnnotator::RunTask()
#19 0x7f5fe2cb7740 base::MessageLoop::RunTask()
#20 0x7f5fe2cb933d base::MessageLoop::DeferOrRunPendingTask()
#21 0x7f5fe2cba19d base::MessageLoop::DoWork()
#22 0x7f5fe2cba589 base::MessagePumpDefault::Run()
#23 0x7f5fe2cb6b22 base::MessageLoop::RunHandler()
#24 0x7f5fe2cdf4b8 base::RunLoop::Run()
#25 0x7f5fe2d08ce6 base::Thread::ThreadMain()
#26 0x7f5fe2d03e36 <unknown>
#27 0x7f5fe2f9b6ca start_thread
#28 0x7f5fcdba30af clone
  r8: 00007f5f7b7ce700  r9: 0000000000000028 r10: 0000000000000073 r11: 0000000000000000
 r12: 0000000000000000 r13: 0000000000000000 r14: 00007f5fb01d4f20 r15: 0000000000000000
  di: 00007f5f7b7c8b30  si: 0000000000000028  bp: 00007f5fd941d5a2  bx: 00007f5fb01d4f00
  dx: 00007f5fcde5e750  ax: 0000000000000028  cx: 0000000000000028  sp: 00007f5f7b7cb2d8
  ip: 00007f5fc6ddde19 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000006 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]

```

**Comment by philn5d** [comment] 2017-03-30 19:37
Runner is crashing constantly for me:

- Postman for Chrome
- Version 4.10.5
- win / x86-64
- Chrome 54.0.2840.87

I open Runner from Postman and Postman crashes after about 10 seconds. I was able to run a couple collections previously with this same setup. Nothing now. Looking for further clues about what is causing this - I saw the memory running up the same as @ppragnya but it went up over 1.2 GB before it died.

debugging source and breaking it's doing this, so probably explains the memory issue:
![image](https://cloud.githubusercontent.com/assets/4197796/24523732/a95068e6-1559-11e7-93e7-f22de2342f52.png)

Update : Cleared All History and it is working. I don't really want to load ALL history given I had the interceptor running, that's a lot of unnecessary requests to load for the purpose of running a colleciton.

**Comment by jahrichie** [comment] 2017-11-04 00:51
Ubuntu crashing on every request or click.  Please advise :-(

**Comment by rentman-theodore** [comment] 2017-11-06 14:55
@jahrichie Not sure if it is applicable in your case, but for me on Ubuntu 16.04, Postman crashes when it has a lot of tabs open. Closing the tabs fixes the crashes.

**Comment by charlieg-nuco** [comment] 2018-03-15 15:14
For me I think it's better when I'm using the app and not the chrome webapp. They look the same but the chrome app says that it's deprecated at the top.

**Comment by sivcan** [comment] 2018-03-16 19:57
Kindly update to the latest version of the postman native app -  [Download Postman 6](https://www.getpostman.com/apps) 
It has major performance improvements and new features.

If you're experiencing any issues regarding the crashes then feel free to reopen this issue.

**Closed as completed by sivcan** 2018-03-16 19:57 UTC
Labels: performance

**Comment by PTomasinski** [comment] 2018-10-03 13:43
zillions of tabs open -> that was the problem

**Comment by vfedorin** [comment] 2019-04-02 10:09
Hi. I'm using Postman Desktop for MacOS.
Runner became slower because I guess I have a lot of completed runs. How do I can remove ALL runs completely in bulk since I have several hundred runs? Thanks

**Comment by jacktang** [comment] 2019-06-03 12:21
I upgrade 7.7.1 yesterday, and now it crashes often.... I've clear all history records 
OS is macOS
