### ISSUE TITLE
Have oauth2 "token name" field honor variables

### ISSUE THREAD

**Issue by kkalmbach** [a85/POSTMan-Chrome-Extension#2063] opened 2016-05-12 19:45 UTC
Please include the following:
1. Postman Version:4.1.3
2. App (Chrome app or Mac app): Chrome
3. OS details: Mac
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there: always
6. Expected behaviour: when I use a variable name in the "token name" in the oauth2 authentication screen, it de-references the variable
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   ![image](https://cloud.githubusercontent.com/assets/1203135/15228081/860d0aa2-1847-11e6-9704-897cfac28327.png)

I use environments and oauth,  (and i usually have several valid oauth tokens for my varous environments).  I would like to be able to use variable names in the "token name" field.  In the screenshot, I used {{username}} for the token naem and I got a token names "{{username}}".

**Comment by vikiCoder** [comment] 2019-07-29 10:07
Closing this as a duplicate of the following issue:
https://github.com/postmanlabs/postman-app-support/issues/3525

**Closed as completed by vikiCoder** 2019-07-29 10:07 UTC
Labels: feature, Auth, OAuth2, product/runtime
