### ISSUE TITLE
[V11] Vault Shortcut on Windows Crashes the Application

### ISSUE THREAD

**Issue by Postmanaut-Adrian** [a85/POSTMan-Chrome-Extension#12915] opened 2024-06-04 16:47 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

On windows, the Vault shortcut utilizes the same shortcut as Plain Text Paste. 

As a result the application crashes.

### Steps To Reproduce

1. Copy any text content
2. Attempt to paste using CTRL+SHIFT+V on a body or text box that consumes plain text
3. The app will crash

### Operating System

Windows

### Postman Version

11.1.13

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Changing the shortcut keybinds via the Application > Settings > Shortcuts will resolve the issue for now and avoid further crashes.

**Comment by ravi-prasad07** [comment] 2024-06-13 06:23
@Postmanaut-Adrian Root cause investigation of this issue revealed that this is unrelated to Vault directly. The issue was with another component that the initialization of Vault relies upon, and thus, it appeared to be crashing when Vault was opened using the shortcut. Also, this issue has already been addressed in 11.1.x([PR](https://github.com/postman-eng/postman-app/pull/11634)) and no longer exists in the newer versions.

**Closed as completed by ravi-prasad07** 2024-06-13 06:23 UTC
Labels: product/trust
