### ISSUE TITLE
Handler for Request not found

### ISSUE THREAD

**Issue by MECLab-Michelle** [a85/POSTMan-Chrome-Extension#7209] opened 2019-08-28 00:21 UTC
**Describe the bug**
I have an existing POST request to an external api. No changes have been made to the request since June. I tried executing the request today, but I'm now receiving a 404 with the error 'Handler for Request not found.' 

**To Reproduce**
1. Click SEND for an existing api request in postman 
Body = form data with three variables
Headers = content type: application/x-www-form-urlencoded + 8 other temporary headers
2. See error: 

Handler for Request not found: 
Request.HttpMethod: GET
Request.HttpMethod: GET
Request.PathInfo: [api url goes here]
Request.QueryString: 
Request.RawUrl: [api url goes here]

**Expected behavior**
HTTP 200 response

**App information (please complete the following information):**
 - Postman Version [e.g. 7.5.0]
 - OS: [Windows 10 Enterprise]

**Additional context**
Able to send and receive a successful 200 OK response with the following in a simple python script. 

request = requests.post(api_url, data={'APIKey': api_key, 'SurveyId': survey_id, 'FromResultId': from_result_id})

Is this due to the addition of temporary headers?
Why does postman think this is a GET request?

**Comment by MECLab-Michelle** [comment] 2019-09-04 01:40
Hi there, 

Is there any update on this one? Do you need any more information. I'm still having the same issue and simply can't use postman to call this api. 

Cheers,

**Comment by codenirvana** [comment] 2019-09-11 03:29
@MECLab-Michelle Can you try disabling "Automatically follow redirects" option in settings and check what's the status code of the API response? Is it a 301 or 302?

Possible duplicate of #4001.

**Comment by preethammavin** [comment] 2019-09-20 07:49
@MECLab-Michelle please let us know if the above step solved your problem? Closing the issue for now, feel free to reopen and comment if it is not solved.

**Closed as completed by preethammavin** 2019-09-20 07:49 UTC
