### ISSUE TITLE
New version of postman forces response download instead of displaying result inline

### ISSUE THREAD

**Issue by hareesh-blippar** [a85/POSTMan-Chrome-Extension#2363] opened 2016-09-28 21:16 UTC
1. Version 4.7.2
2. Mac App
3. OSX El Capitan
4. Bug started after upgrading postman to 4.7.2.

Issue:
I send a POST request to an endpoint (Using the Send option. Not the Send and Download option.)
Earlier, the endpoint response would get shown inline inside the response window.

Now, upon sending the request, a download file window gets opened by postman and I'm forced to save the response as a file instead. The saved response file is base64 encoded making it impossible to see my response now (which is in without going through additional hoops.

Below is the console log message:
common.js:458 Resource interpreted as Document but transferred with MIME type multipart/form-data: "data:multipart/form-data;base64".

The problem is that you are interpreting my response as a document, which is partially incorrect, and forcing me to download it, instead of displaying the response inline.

**Comment by vegetableman** [comment] 2016-09-29 06:12
@hareesh-blippar Thanks for reporting this issue 👍 . Will get back to you.

**Comment by vegetableman** [comment] 2016-10-03 09:13
@hareesh-blippar The issue happens if the response headers from the server have a mime-type set `multipart/form-data; base64` but the response itself is a binary file.
Could you post a screenshot of the request/response headers on the `Postman Console` (`View` -> `Show Postman Console` or `Cmd + Opt + C`) for the request?.

**Comment by hareesh-blippar** [comment] 2016-10-05 00:09
@vegetableman - I'm attaching a screenshot with my headers here. If you hit the server along with a form-data parameter called `image_filename` which can be any image, you should be able to reproduce the results.

![postman_bug](https://cloud.githubusercontent.com/assets/14183519/19096908/441325fc-8a55-11e6-8914-532bb0b2ff89.png)

**Comment by vegetableman** [comment] 2016-10-05 08:39
@hareesh-blippar Thanks for sharing the screenshot 👍 . The issue has been identified. Will Keep you posted.

**Comment by vegetableman** [comment] 2016-10-15 04:44
@hareesh-blippar Can you try updating to the latest version (4.8) and check if this is fixed?

**Comment by vegetableman** [comment] 2016-10-27 07:36
Closing this. Feel free to reopen if you still see the issue.

**Closed as completed by vegetableman** 2016-10-27 07:36 UTC
Labels: bug

**Comment by vinogradoff** [comment] 2018-02-06 17:14
looks like regression in 5.5.2. Downloads even when just "Send" is used.

**Comment by derdrdirk** [comment] 2018-07-26 19:55
same in Version 6.2.1
