### ISSUE TITLE
bitbucket support

### ISSUE THREAD

**Issue by Cereal916** [a85/POSTMan-Chrome-Extension#7803] opened 2019-12-14 20:56 UTC
**Is your feature request related to a problem? Please describe.**
Bitbucket is the only thing we are allowed to use at work. Without proper version control developers at my work tend not to put much effort into maintaining a single collection.

**Describe the solution you'd like**
Integration with Bitbucket would help me make the argument to move to postman pro.

**Describe alternatives you've considered**
github and gitlab are good options, but not allowed in my work place. We have an on prem bitbucket instance that is used for all of our repositories.

**Comment by ankit-m** [comment] 2019-12-16 04:36
Duplicate of #4780

**Closed as completed by ankit-m** 2019-12-16 04:36 UTC
