### ISSUE TITLE
Cookies and Code button over flowing under Toggle Two-Pane View

### ISSUE THREAD

**Issue by CryptoGL** [a85/POSTMan-Chrome-Extension#7532] opened 2019-10-25 02:32 UTC
**Describe the bug**
Cookies and Code button over flowing under Toggle Two-Pane View

**To Reproduce**
1. Go to 'Main Window'
2. Click on 'Toggle Two-Pane View' in 'View'
3. Scroll down to 'Cookies' & 'Code'

**Screenshots**
![image](https://user-images.githubusercontent.com/22292685/67538784-b46c9e00-f712-11e9-8e2a-2c275a9574e5.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [v7.10.0]
 - OS: [Windows 10 Professional 18362.418]

**Comment by codenirvana** [comment] 2019-10-25 06:36
Duplicate of #7324

**Closed as completed by codenirvana** 2019-10-25 06:36 UTC
Labels: duplicate, product/runtime
