### ISSUE TITLE
the & character causes issues with soap requests

### ISSUE THREAD

**Issue by dbkaynor** [a85/POSTMan-Chrome-Extension#4706] opened 2018-06-14 20:38 UTC
When I include the & in a string and send it to my web server I receive a soap error. The request with the & character has been tested on other tools and the correct response is received. (This other tools are proprietary.)

[&Bug.txt](https://github.com/postmanlabs/postman-app-support/files/2103933/Bug.txt)

**Comment by sivcan** [comment] 2018-06-19 12:24
@dbkaynor 
1. What is the app version that you're using? Can you make sure you're on the latest version (v6.1.3 as of now)
2. Can you provide the steps to reproduce this issue?

**Comment by dbkaynor** [comment] 2018-06-19 15:31
Postman for Windows
Version 6.1.3
win32 10.0.16299 / x64

**Comment by codenirvana** [comment] 2019-05-13 12:28
@dbkaynor Can you try escaping the `&` (`&amp;`) or wrap the payload inside `<![CDATA[]]>`?

**Comment by codenirvana** [comment] 2019-07-25 11:24
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2019-07-25 11:24 UTC
Labels: bug, support, request-sending, blocked/need-info, product/runtime
