### ISSUE TITLE
IterationData is not getting reflected in local variable value

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#7800] opened 2019-12-13 16:56 UTC
**Describe the bug**

IterationData is not getting reflected in the below approach 

**To Reproduce**

**Steps to reproduce the behavior:**

- There is a environmental variable '**space**' with value 'initial'

- I have data file "data-copy" that have different values for space (have attached in zip)

- If modify local variable in pre request script then the local variable is not getting replaced automatically with next data iteration
![image](https://user-images.githubusercontent.com/45095911/70817166-ec19cd00-1dc8-11ea-949e-004f00966079.png)

- On executing the collection , i get previously modified value

**Test collection files**

[test.postman_environment.zip](https://github.com/postmanlabs/postman-app-support/files/3961820/test.postman_environment.zip)

- Use the above environment and collection file ( It is ready to be run ) 

- To execute use the command: 

`newman run "dsdgf.postman_collection.json" -e test.postman_environment.json -k -r cli,htmlextra --reporter-htmlextra-logs -d "data - Copy.csv"`

- observe the console output

**Observed behavior**

space is getting value from previous iteration

**Expected behavior**

The local variable value should be equal to iterationData value in each iteration irrespective to previous iteration state.

**Screenshots**

![image](https://user-images.githubusercontent.com/45095911/70817229-0eabe600-1dc9-11ea-8000-64e25ec401b2.png)

**App information (please complete the following information):**
 - Postman Version [ Postman v7.13.0]
 - OS: [Windows 10]

**Comment by saswatds** [comment] 2020-02-12 02:24
Hi @praveendvd this is intended behavior. To know more about the variable scopes you can check our learning center https://learning.postman.com/docs/postman/variables-and-environments/variables/#variable-scopes 

If you updated using the `variables` API then its changing the local scope and it will take priority over iterationData. 

I will be closing this issue for now as this does not seems to be a bug.

**Closed as completed by saswatds** 2020-02-12 02:24 UTC
Labels: product/runtime

**Comment by praveendvd** [comment] 2020-02-12 07:38
> Hi @praveendvd this is intended behavior. To know more about the variable scopes you can check our learning center https://learning.postman.com/docs/postman/variables-and-environments/variables/#variable-scopes
> 
> If you updated using the `variables` API then its changing the local scope and it will take priority over iterationData.
> 
> I will be closing this issue for now as this does not seems to be a bug.

Hi @saswatds  I think you have mis understood the issue . 

I know that local variable have more precedence than any other variable, but as per documentation local variables are temporary variable that get destroyed in each iteration .


In scenario were I have a variable a coming from a data file , if I set a = 1 only for iteration 1 . Then in iteration 2, I expect the local variable a to get destroyed and the value from data file to get reflected .

But here the value will be still  a=1 for all the iterations

**Comment by saswatds** [comment] 2020-02-18 06:40
@praveendvd 
Referring to the documentation, it says
> Local variables are temporary and only accessible in your request scripts. Local variable values are scoped to a **single request or collection run**, and are no longer available when the run is complete.

Their value gets destroyed at the end of *a run* and not end of the iteration.
