### ISSUE TITLE
CPU 100% unless you are logged in

### ISSUE THREAD

**Issue by VickyRonnen** [a85/POSTMan-Chrome-Extension#4238] opened 2018-02-24 17:15 UTC
## App Details:
Postman for Windows
Version v6.0.6
Windows 10 Professional x64
```

## Issue Report:
 1. Postman consumes 100% cpu after startup, unless you login.

##Steps to reproduce:
Start postman, but don't login
Look at taksmanagers and see  Postman consuming a whole CPU.

When you login, CPU goes down to a few percent.
Why should you be logged in at the first place?
Spyware??

**Comment by aenlr** [comment] 2018-02-24 17:34
Same on macOS:
- Fresh install
- Start Postman
- Don't login
- Postman and Postman helper processes all consume between 60 and 150% CPU according to Activity Monitor, with CPU usage showing no signs of going down

**Comment by numaanashraf** [comment] 2018-02-24 17:48
@VickyRonnen @anob3it Thanks for reporting this. We can confirm there is a performance issue in Postman 6.0.x version which affects users without an account or while the application is trying to connect to our sync service. We are working on rolling out a fix for this as soon as possible.

**Comment by numaanashraf** [comment] 2018-02-24 19:14
@VickyRonnen @anob3it We've rolled out the fix in the latest version on our Canary channel (v6.0.7-canary01) - https://www.getpostman.com/canary. Would it be possible to download the Canary app and let us know if the issue is resolved at your end?

**Comment by VickyRonnen** [comment] 2018-02-25 08:08
That resolves the issue, without being logged in cpu is low now.

 

Met vriendelijk groet,

Vicky Ronnen

 

Van: Numaan Ashraf [mailto:notifications@github.com] 
Verzonden: zaterdag 24 februari 2018 20:14
Aan: postmanlabs/postman-app-support <postman-app-support@noreply.github.com>
CC: VickyRonnen <v.ronnen@upcmail.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [postmanlabs/postman-app-support] CPU 100% unless you are logged in (#4238)

 

@VickyRonnen <https://github.com/vickyronnen>  @anob3it <https://github.com/anob3it>  We've rolled out the fix in the latest version on our Canary channel (v6.0.7-canary01) - https://www.getpostman.com/canary. Would it be possible to download the Canary app and let us know if the issue is resolved at your end?

**Comment by aenlr** [comment] 2018-02-25 18:25
@numaanashraf It resolves the issue on OS X as well.

**Closed as completed** 2018-02-26 14:30 UTC

**Comment by codessentials** [comment] 2019-02-07 06:44
I just downloaded and installed the canary version, but it has the same issue. :-(

**Comment by numaanashraf** [comment] 2019-02-07 06:46
@codessentials Could you help us with the OS & App version?

**Comment by RaynisDev** [comment] 2019-04-15 11:34
Same Issue here..

**Comment by msanguineti** [comment] 2019-09-13 12:39
Postman for Linux
Version 7.7.0
linux 4.19.0-6-amd64 / x64 (Debian 10)

@numaanashraf, postman is still eating up my CPU after @sivcan closed this more than 1.5 yrs ago :(

**Comment by kamalaknn** [comment] 2019-09-13 14:06
@msanguineti Are you seeing a constant high CPU usage or is it intermittent? Can you give us more information about your state, for e.g.

1. Are you signed in?
2. If yes, how many user accounts are you logged into?
3. Are you seeing this now in 7.7 or has this been the same in previous versions as well?

If you can share any screenshots, that would be great.

**Comment by msanguineti** [comment] 2019-09-13 23:20
> @msanguineti Are you seeing a constant high CPU usage or is it intermittent? Can you give us more information about your state, for e.g.

I couldn't reproduce the issue today. I will try again sometime during the weekend. But the problem was steady, I also killed the process (kill -9) and restarted and still the CPU kept on rising until it maxed out and stayed there. 

In any case:
 
>     1. Are you signed in?
NO
 
>     2. If yes, how many user accounts are you logged into?
>
>     3. Are you seeing this now in 7.7 or has this been the same in previous versions as well?
It happened after I've upgraded from 7.x to 7.7 yesterday.
 
> If you can share any screenshots, that would be great.

![shot_postman](https://user-images.githubusercontent.com/19243840/64899779-bfed9380-d695-11e9-96cc-5068a1d76f35.png)

mmmh I've just noticed the uptime of postman... still...
