### ISSUE TITLE
Not working in Google Chrome 51

### ISSUE THREAD

**Issue by VSerykh** [a85/POSTMan-Chrome-Extension#2109] opened 2016-06-07 14:23 UTC
Postman extension not working at all because of errors in console.
1. Postman - REST Client shortcut 0.8.4.8
   Google Chrome Version 51.0.2704.84 m (64-bit)
2. Google Chrome extension
3. Windows 8.1 Pro x64
4. Is the Interceptor on and enabled in the app: I don't know.
5. In Google Chrome 50 extension was working properly.
6. Expected behaviour: no errors in conlose.
7. Console logs:

requester.js:112 Uncaught TypeError: Cannot assign to read only property 'indexedDB' of object '#<Window>'(anonymous function) @ requester.js:112

**Comment by abhijitkane** [comment] 2016-06-07 14:24
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/2101

**Closed as completed by abhijitkane** 2016-06-07 14:24 UTC
