### ISSUE TITLE
Obtain OAuth 2.0 access token with custom callback URL

### ISSUE THREAD

**Issue by markbeij** [a85/POSTMan-Chrome-Extension#4643] opened 2018-06-04 13:49 UTC
**Describe the bug**
I cannot retrieve an oauth 2.0 access token using a custom callback URL

**To Reproduce**
1. Create a new resuest
2. Go to tab 'Authorization'
3. Set type to 'OAuth 2.0'
4. Click 'Get New Access Token'
5. Specify settings to obtain a token from an STS you have access to (Azure AD in my case). Select Grant Type 'Authorization Code'. Specify the Callback URL according to the setting in your STS (so do not leave this setting at 'https://getpostman.com/oauth2/callback').
6. After successfully logging in I end up with a blank popup screen, with title 'Working...'. No access token is obtained.

**Expected behavior**
I go to my login screen. After logging in, I return to Postman and have obtained an access token.

**App information (please complete the following information):**
 - App Type: Windows native
 - Postman Version: 6.1.3
 - OS: Windows 10 Pro 10.0.17134

**Comment by markbeij** [comment] 2018-06-08 07:02
I hope someone can reproduce this issue. If I can help, let me know.

**Comment by harryi3t** [comment] 2018-06-29 10:24
@markbeij This is duplicate of https://github.com/postmanlabs/postman-app-support/issues/4246 (closed)

Normally for OAuth-2 we open a browser window with the `auth url`, then there are series of redirection after which the page is redirected to the `callback url` that was registered along with a ` `code` that is used to exchange `access token`.

The problem with Azure AD is that one of redirected page is protected by NTLM auth. This is specified by the server using a custom header `www-authenticate: NTLM`. This header is well understood by browsers and they show a prompt to enter username and password.
Electron by default does not honour these auth headers. So redirection stops at that blank page.

**Comment by markbeij** [comment] 2018-06-29 11:09
@harryi3t 
Although similar I don't think this is a duplicate of #4246. I don't have this popup which might be a problem for Postman. Nor are we using NTLM I believe.
When I configure my app to accept callback url 'https://getpostman.com/oauth2/callback' and use that in Postman, I can get this to work. If I use my preferred callback url, I end up with this blank screen.

**Comment by harryi3t** [comment] 2018-06-29 19:34
@markbeij When you change the callback URL to your `preferred callback url` do you also change the same in the settings where your application is registered? (Setting page on the auth provider)

Can you give me more information about your auth provider? Is it publicly available for testing?

**Comment by harryi3t** [comment] 2018-08-01 09:37
@markbeij Closing due to inactivity. Feel free to reopen if this is still happening. Also, while re-opening please provide the extra information as requested in the comment above.

**Closed as completed by harryi3t** 2018-08-01 09:37 UTC
Labels: bug

**Comment by pkvsinha** [comment] 2019-03-05 09:30
I used "https://app.getpostman.com/oauth2/callback" as the callback url and it worked.

**Comment by harryi3t** [comment] 2019-03-05 10:51
@prashant-sinha You can use any callback url  (even http://localhost )as long as it is used to register on the auth provider.

**Comment by pkvsinha** [comment] 2019-03-06 04:37
> @prashant-sinha You can use any callback url (even http://localhost )as long as it is used to register on the auth provider.

I understand that any url can be used, but the thing is, 'https://getpostman.com/oauth2/callback' doesn't work. However, 'https://app.getpostman.com/oauth2/callback' works for some reason. That was the point. Thanks for your reply, btw.
