### ISSUE TITLE
how to capture https request via native postman

### ISSUE THREAD

**Issue by Iamxiaoxiong** [a85/POSTMan-Chrome-Extension#3013] opened 2017-05-11 08:11 UTC
1. Postman Version:4.10.7
@a85 @shamasis @ratpik @abhijitkane

**Comment by ghost** [comment] 2017-05-11 11:33
I am assuming you already know how to capture __HTTP__ requests using [postman's proxy](https://www.getpostman.com/docs/postman/sending_api_requests/capturing_http_requests)

Capturing __HTTPS__ requests is not possible using postman for websites using [HSTS policy](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)
![screen shot 2017-05-11 at 4 19 55 pm](https://cloud.githubusercontent.com/assets/28589861/25946976/fe60c27c-366a-11e7-93b1-1db848ba7bee.png)

**Comment by harryi3t** [comment] 2017-08-31 11:46
duplicate of https://github.com/postmanlabs/postman-app-support/issues/3013

**Comment by sryze** [comment] 2017-10-10 04:50
Isn't this issue #3013?

**Comment by sryze** [comment] 2017-10-10 04:51
Can Postman do HTTPs traffic capturing similar to other proxies that generate you a unique root certificate (or whatever it is, not sure) and you just install it on the device? Again, I'm not entirely sure how that works, but mitmproxy and Charles can do it. 

I would like to use Postman instead of those apps since it's easier and has a lot of other features (and the UI is much better) but right now it doesn't seem to be possible (unless you can get around untrusted HTTPS cert errors).

**Comment by harryi3t** [comment] 2017-10-10 07:09
@sryze Oh snap! Must have opened the same page in 2 diff tabs. 
Re-opening it.

Although this is not on our immediate roadmap, we will take a look at the feasibility of this feature.
@shamasis Thoughts?

**Comment by repac** [comment] 2017-12-12 17:35
Can I just add support for the idea of getting Postman Native working with HTTPS? We currently use HTTPS and access our in-house test environment via a reverse proxy, no HTTPS support means I can't test using Postman on our pseudo-Live environment.
Apologies to everyone who has alerts enabled for this thread, I'm new to GitHub and there doesn't appear to be a way to upvote an issue without spamming everyone.

**Comment by harryi3t** [comment] 2017-12-13 10:55
@repac Just click the thumbs up icon on the top comment :)
![image](https://user-images.githubusercontent.com/5207331/33935415-dceab04c-e021-11e7-8a21-fa6dcfa157c4.png)

**Comment by AndriiStepura** [comment] 2018-02-18 22:26
Does anybody know some workarounds for this?

**Comment by AndriiStepura** [comment] 2018-02-18 22:33
Any body know about some workarounds for this?

**Comment by mattrixman** [comment] 2018-02-26 20:29
@repac Also consider upvoting this guy's comment: http://disq.us/p/1o8hq5s
(no, I'm not that guy)

**Comment by ggajews** [comment] 2018-07-23 14:38
Is this feature on your roadmap already? Any updates?

**Comment by maudrid** [comment] 2018-11-15 10:32
Please add your votes here:
https://github.com/postmanlabs/postman-app-support/issues/1667

**Comment by sumithpdd** [comment] 2020-05-17 15:29
No fix for this issues. its 2020 now, HTTPS is mandatory

**Comment by maudrid** [comment] 2020-05-19 11:44
> No fix for this issues. its 2020 now, HTTPS is mandatory
In the meantime, I have a work-around. If you use chrome develper tools, you can copy a request to your clipboard in curl format. And use the postman import from text function to run it from postman.

**Comment by 1trackprojects1** [comment] 2020-06-01 09:47
> No fix for this issues. its 2020 now, HTTPS is mandatory
Exactly

**Comment by shashankawasthi88** [comment] 2021-03-09 06:25
Hi, @1trackprojects1 @maudrid @sumeetsarkar and others. We have started to explore enabling HTTPS request capturing. We would love to get onto a call to explore your exact use cases and any other issue around the proxy feature in general. If possible, can we hop onto a quick call to discuss the same. You can schedule a 1:1 one us through this link - https://calendly.com/shashank-awasthi/postman-proxy

**Comment by abhijitkane** [comment] 2021-04-26 12:22
Support for HSTS in Postman's proxy has been released with version 8.3.0. This is only available on Postman's native app, and not the version on the web.

Once you upgrade, check https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/#capture-https-traffic-with-postmans-built-in-proxy for installing the certificate Postman needs to read HTTPS requests.

**Closed as completed** 2021-04-26 12:23 UTC
Labels: feature, Proxy, Interceptor
