### ISSUE TITLE
Postman doesn't launch on ubuntu 19.10 on wayland, instead postman canary whether works fine

### ISSUE THREAD

**Issue by oscarlopez1616** [a85/POSTMan-Chrome-Extension#8196] opened 2020-03-19 08:58 UTC
**Describe the bug**
Postman doesn't launch on ubuntu 19.10 on wayland, instead postman canary whether works fine

**To Reproduce**
install postman from spancraft for example and open in ubuntu 19.10 over wayland. Postman doesn't start, instead postman canary yes works correctly.

**Expected behavior**
postman should open correctly

**App information (please complete the following information):**
 - Postman 7.2
 - Ubuntu 19.10 Wayland

**Comment by zsoltii** [comment] 2020-04-01 10:12
Same problem under Ubuntu 18.04

**App information**

    Postman Version 7.21.1 (latest from https://snapcraft.io/postman)
    Ubuntu 18.04 Wayland (I have Amd Radeon rx480 and I use hwe x.org drivers)

**Comment by michalfita** [comment] 2020-05-19 21:01
I've installed 7.24.0 today on Ubuntu 20.04 using Wayland and it doesn't start as well. Any attempt is silent.
I reported it on [snapcraft forum](https://forum.snapcraft.io/t/postman-7-24-0-on-ubuntu-20-04-dont-start/17601) too.

**Comment by twitharshil** [comment] 2022-02-18 06:56
We have sent a fix for this issue in later versions of the postman. Upgrading to the latest version should fix this for you 

Closing this ticket as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/10252

**Closed as completed by twitharshil** 2022-02-18 06:56 UTC
Labels: bug, platform/linux, product/desktop-foundation, component/electron, version/7
