### ISSUE TITLE
Feature Request (minor) - Editing the Request description 

### ISSUE THREAD

**Issue by ben-eichler-abcs** [a85/POSTMan-Chrome-Extension#4169] opened 2018-02-11 23:33 UTC
## App Details:
Postman for Windows
Version 5.5.2
win32 10.0.16299 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
The behaviour has been there as long as I have been using Postman, which is not long
 2. Expected behaviour:
When editing the description of a Request, the Request is flagged as having been edited, so that when the tab is closed if the user has not clicked Update, a warning will be presented to the user to save their changes.
 3. Console logs
Not applicable
 4. Screenshots (if applicable)
Image 1 - the Request does not have a description yet
![image](https://user-images.githubusercontent.com/31116939/36080085-93add208-0fef-11e8-8f1a-faf2ae136836.png)

Image 2 - I type a description of the Request. Note how far away the Update button is (I'm using a desktop with a 22" monitor)
![image](https://user-images.githubusercontent.com/31116939/36080135-70dc6f40-0ff0-11e8-9c61-bf95a1f6faac.png)

Image 3 - I close the Request tab and am not warned to save my changes. When I reopen it, the description is gone
![image](https://user-images.githubusercontent.com/31116939/36080085-93add208-0fef-11e8-8f1a-faf2ae136836.png)

**Comment by thecuriousdev** [comment] 2018-02-12 11:31
@ben-eichler-abcs thanks for suggesting this, we will keep you posted here.

**Comment by vkaegis** [comment] 2018-06-29 12:31
@ben-eichler-abcs Thanks for pointing this out! The behavior is as intended. As of now, Postman considers the request name and description as part of the meta of the request, and we treat the use case of editing name/descriptions to be different to that of actually working with the request (editing headers etc). We will be working on some improvements to make this more apparent. 

The issue of the update button being far away is a legitimate concern. Will look at some improvements there too. We're working on some major changes to how the tab interface is structured in the coming versions, so stay tuned!

**Comment by ben-eichler-abcs** [comment] 2018-07-01 21:51
@vkaegis Thanks for the post. I'll keep an eye out for this update ;)

**Comment by ZhangYiJiang** [comment] 2019-01-23 07:27
I just lost about fifteen minutes of work because of this. Thanks.

I'll also note that while editing everything else will trigger a warning if you then try to close the tab, editing the description does not, and while Ctrl + S saves everything, it doesn't save the description even if the description textbox is in focus. It's not even consistent with the module title, which *does* automatically save as expected if you try to close the tab.

**Comment by DannyDainton** [comment] 2022-07-06 11:52
The Postman UI has been changed in later versions and the description is now part of the right-side context menu. I'm going to close this out as it feels less relevant given those changes.

https://learning.postman.com/docs/publishing-your-api/authoring-your-documentation/

**Closed as completed by DannyDainton** 2022-07-06 11:52 UTC
Labels: feature, tabs
