### ISSUE TITLE
Unable to access Build once in Browse Mode

### ISSUE THREAD

**Issue by Izidi** [a85/POSTMan-Chrome-Extension#4248] opened 2018-02-27 10:32 UTC
## App Details:

```
Postman for Windows
Version 6.0.7
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always
 2. Expected behaviour: Should be able to access Build Mode
 3. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/2879895/36723688-e399b376-1ba8-11e8-90a7-5d3dac0051fc.png)
![image](https://user-images.githubusercontent.com/2879895/36723704-f0c78492-1ba8-11e8-8a98-6b995392a3ee.png)
![image](https://user-images.githubusercontent.com/2879895/36723727-ffa14df4-1ba8-11e8-86fe-4e47f0479389.png)

1. Click on Browse at the base of the page.
    a. I'm unable to see the Browse Page as it states that I'm offline.
2. Click Build using the menu at the base of the page. I'm then informed that I'm unable to access the Build pages. Note that clicking Join This Workspace also does not work.
3. Clicking Switch to the Build View Button Works as expected.

Additional Information:
 1. Postman is unable to connect to the Internet and does not seem to be syncing my account. It is continually stating that it is connecting.
![image](https://user-images.githubusercontent.com/2879895/36723929-801b59ca-1ba9-11e8-9bf3-15cefe56a07e.png)

**Comment by Izidi** [comment] 2018-02-27 10:42
https://github.com/postmanlabs/postman-app-support/issues/4249 is another bug which has been raised regarding the additional information added to my bug report. Unsure if the syncing issue is affecting the other issues that I am seeing.

**Comment by sivcan** [comment] 2018-02-27 10:45
@Izidi - Thanks for reporting this and sorry for the inconvenience. 
I can confirm that this is a known issue and you expect a fix for this soon in the next update.
I'll update you once we release it.

In the mean time, you can try using the workspace switcher on the top to switch to another workspace. 

Also, I guess you must have tried restarting the app ? 
If not then do so.
Also, try disconnecting from the internet and connecting again.

**Comment by Izidi** [comment] 2018-02-27 10:50
@sivcan Thanks for the quick response. This is still occurring on reloading the app. I actually only have a single Workspace and so was just looking to see the new update. 
With regards to the syncing issue, it does eventually state that it's syncing but I never saw it going back to being synced although I'm not actually making changes in any of my collections.

**Comment by sivcan** [comment] 2018-02-27 10:54
@Izidi Oh alright, so it says 'Syncing' now or 'Connecting' ?  

Also, can you go to the Menu bar and click  'View > Developer > Show DevTools (Shared)' 
And post the console logs here ? 
![image](https://user-images.githubusercontent.com/12631777/36724959-bf9d0ac2-1bda-11e8-9c25-b452cbda4e6a.png)

Thanks!

**Comment by Izidi** [comment] 2018-02-27 11:01
@sivcan sorry, I should have specified. It was saying Syncing. It actually now says In Sync. Below is the console logs as well as a screenshot of the warning and error as I can see it's hard to read the logs:

![image](https://user-images.githubusercontent.com/2879895/36725253-9bbba262-1bad-11e8-876a-8e48f0796019.png)

> Initializing the global config
> shared.js:325548 Initializing settings
> shared.js:262795 Booting waterline models
> shared.js:262861 Object "Successful ORM initialization"
> sails.io.js:142 🌏 sync service connectivity initiated
> shared.js:336133 authenticating socket for 475512 true
> shared.js:336149 sign in bailed. force connect.
> shared.js:131595 Successfully received bootstrap data Object
> shared.js:335639 Sync manager listening to bootstrapUser event Object
> (anonymous) @ shared.js:335639
> shared.js:336133 authenticating socket for 475512 true
> shared.js:336149 sign in bailed. force connect.
> sails.io.js:661 Uncaught (in promise) Error: already reconnecting socket. wait till connected event is fired
>     at SailsSocket.SailsIOClient.SailsSocket._reconnect (sails.io.js:661)
>     at SailsSocket.SailsIOClient.SailsSocket.reconnect (sails.io.js:442)
>     at shared.js:336097
> sails.io.js:759 socket replaying queued commands
> sails.io.js:142 🌏 connected to sync service.
> shared.js:336133 authenticating socket for 475512 true
> shared.js:336187 session create
> sails.io.js:142 🌏 connected to sync service.
> sails.io.js:759 socket replaying queued commands
> shared.js:336133 authenticating socket for 475512 true
> shared.js:336174 sign in bailed. in progress.
> shared.js:336133 authenticating socket for 475512 true
> shared.js:336187 session create
> shared.js:112542 Sync Request: /v2/session/create
> shared.js:112546 Sync Request: Object
> shared.js:112547 Sync Response: Object
> shared.js:336418 already bootstrapped for this user. skipping bootstrap.
> shared.js:112542 Sync Request: /v2/session/create
> shared.js:112546 Sync Request: Object
> shared.js:112547 Sync Response: Object
> shared.js:336418 already bootstrapped for this user. skipping bootstrap.
> shared.js:112542 Sync Request: /v2/monitor/proxy?workspace=<<id>>&collection=<<id>>
> shared.js:112546 Sync Request: Object
> shared.js:112547 Sync Response: Array[0]
> shared.js:112542 Sync Request: /v2/mock/proxy?workspace=<<id>>&collection=<<id>>
> shared.js:112546 Sync Request: Object
> shared.js:112547 Sync Response: Array[0]
> shared.js:112542 Sync Request: /v2/monitor/proxy?workspace=<<id>>&collection=<<id>>
> shared.js:112546 Sync Request: Object
> shared.js:112547 Sync Response: Array[0]
> shared.js:112542 Sync Request: /v2/session/sync?since_id=3281270561&sync_timestamp=1519639319&changeset=false
> shared.js:112546 Sync Request: Object
> shared.js:112547 Sync Response: Object
> shared.js:335883 CR DONE Object
> shared.js:336677 updated revision after /sync 3281270561
> shared.js:112542 Sync Request: /v2/session/sync?since_id=3281270561&sync_timestamp=1519639319&changeset=false
> shared.js:112546 Sync Request: Object
> shared.js:112547 Sync Response: Object
> shared.js:335883 CR DONE Object
> shared.js:336677 updated revision after /sync 3281270561

**Comment by sivcan** [comment] 2018-02-27 11:07
@Izidi - Thanks for sharing the logs, will go through them.
Also, since it says 'In Sync' for you now - I am sure you are able to switch to the workspace that you created and switched back to the Build View ?

**Comment by Izidi** [comment] 2018-02-27 11:10
@sivcan seems closer to opening but it's stuck on loading. If I attempt to view the Workspace Details, I get shown the following:
![image](https://user-images.githubusercontent.com/2879895/36725615-bea6bebe-1bae-11e8-8fcd-6c741cf03f43.png)

Note that I'm still unable to return back to the Build screen using the menu at the base of the page.

**Comment by Izidi** [comment] 2018-02-27 11:12
@sivcan I'm actually now stuck on the Loading page for the Workspace and have no way of getting back to the Build page without possibly restarting Postman. Hoping that it might load something soon. There's no additional logs shown in the console.
Update:
It seems to have disconnected me and then I could get back to the Build page. Might have timed out on loading the Workspace.

**Comment by sivcan** [comment] 2018-02-27 11:14
@Izidi - Yes so your switcher must be showing 'Loading...' and clicking on the workspace details must be showing this.
Try waiting for sometime, it loads all your data directly from the server.

**Comment by sivcan** [comment] 2018-02-27 11:14
@Izidi - A quick fix (might help you) - can you logout and login again to the postman app ? 
We're looking into this issue on our end.

**Comment by Izidi** [comment] 2018-02-27 11:19
@sivcan re-logging seems to have fixed the issues and I'm now able to see the Workspace after around 1 min of loading - note that this is occurring everytime I'm accessing the page.. I'm now able to switch back and forward between workspace and build tabs at the base of the page without issues.

**Comment by sivcan** [comment] 2018-02-27 11:25
@Izidi - Good to know that you're able to use the workspaces.
Yes, we are aware of these bugs and will be releasing a fix for it soon.
Will keep you updated.

Thanks for your co-operation and for reporting this issue.

**Comment by Izidi** [comment] 2018-03-02 12:02
@sivcan Issues all seem to be sorted now with the new version 6.0.8

**Comment by sivcan** [comment] 2018-03-02 18:58
@Izidi - Thank you for letting us know and I hope you liked the all new Postman 6.0!
 Closing this issue as it's resolved.

**Closed as completed by sivcan** 2018-03-02 18:58 UTC
Labels: bug
