### ISSUE TITLE
Postman 6.4.4 for Windows through RDP shows black screen

### ISSUE THREAD

**Issue by adidaslevy** [a85/POSTMan-Chrome-Extension#5469] opened 2018-11-01 15:37 UTC
Right after installing Postman 6.4.4 on a remote machine through RDP, postman opens, but I get black screen after the screen flickers. 

See Bug Description. 

**Expected behavior**
Postman is able to start, as at my local Windows machine

**Screenshots**
![image](https://user-images.githubusercontent.com/6115496/47861893-8bb21100-ddfc-11e8-8681-f512fb99949d.png)

![image](https://user-images.githubusercontent.com/6115496/47861921-a3899500-ddfc-11e8-90c2-0d65bec108d8.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 6.4.4 
 - OS: Windows Server 2012 sp...

**Comment by cw-kritipoddar** [comment] 2018-11-02 07:06
I am facing the same issue on my Windows 8.1 Pro with above specifications

**Comment by numaanashraf** [comment] 2018-11-02 11:44
@adidaslevy @cw-kritipoddar This looks like a GPU related issue. Please turn off GPU acceleration in Postman by following the steps here - https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates#troubleshooting-postman-updates and let us know if that resolves your issue.

**Comment by adidaslevy** [comment] 2018-11-02 11:58
Thanks! I'll give it a try

**Comment by adidaslevy** [comment] 2018-11-04 07:53
Thanks, 
Disabling hardware GPU acceleration w/a helped.

**Comment by numaanashraf** [comment] 2019-01-16 16:45
Duplicate of #4594

**Closed as completed by numaanashraf** 2019-01-16 16:45 UTC
Labels: bug, platform/windows, hardware-dependent

**Comment by Azleal** [comment] 2019-05-29 05:15
encountered the same situation and the solution works for me, thanks~
