### ISSUE TITLE
204 response with non-zero content-length takes too long to finish 

### ISSUE THREAD

**Issue by adachenski** [a85/POSTMan-Chrome-Extension#5818] opened 2019-01-23 18:56 UTC
**To Reproduce**
1. Send a valid DELETE request 

**Expected behavior**
1. Verify that the execution time is reasonable and the response and the status code is 204 

**Actual behavior**
Right after sending the request the app hangs
[App hangs JPG](https://drive.google.com/file/d/1APvQ_CoDqnY-kz9hgXC8iKBBGortnVao/view?usp=sharing)
Than it takes very long to execute(1 min)
[Long to execute JPG](https://drive.google.com/file/d/1_g8-LKAi6fGAfTPx-U1pXHpxgO38CoXM/view?usp=sharing)
Other Rest API client example(execution time 31ms)
[Other client JPG](https://drive.google.com/file/d/10TrZohKDBPnsuUWwCDxHl6KyNAd0MZMW/view?usp=sharing)

**Environment**
Postman Version: 6.7.1
OS: Windows 7, MAC OS 10.14

**Comment by numaanashraf** [comment] 2019-02-03 06:32
@adachenski Is there a publicly accessible endpoint we can use to replicate this issue?

**Comment by numaanashraf** [comment] 2019-02-03 06:33
@adachenski could you send us a screen grab of the response headers after this happens?

**Comment by adachenski** [comment] 2019-02-04 17:59
@numaanashraf there are no  publicly accessible endpoints for the calls that I'm testing
but I'm sending the response headers [JPG here](https://drive.google.com/file/d/1NtIBrKat_R-HX2eAD5bz36lGQ8oWrEOU/view?usp=sharing)

**Comment by numaanashraf** [comment] 2019-02-05 07:57
@adachenski This seems to be due to a non-zero Content-Length being sent by the server for 204. Postman would wait for the response from the server (as indicated by the content-length). The request will finally finish when the underlying connection is closed by the client or server. Refer related issue at https://github.com/postmanlabs/postman-app-support/issues/2418#issuecomment-460290091 for more details. I'll keep this issue open to discuss how we'ld like to handle such cases.

**Comment by vozersky** [comment] 2019-02-08 16:28
I've just encountered this as well. 

@numaanashraf This indeed seems to happen due to a non-zero Content-Length in reply Header, which in my case is true.

**Comment by shamasis** [comment] 2019-05-13 10:25
Closing this as duplicate of: https://github.com/postmanlabs/postman-app-support/issues/2418

**Closed as completed by shamasis** 2019-05-13 10:25 UTC
Labels: bug, duplicate, product/runtime
