### ISSUE TITLE
User Interface issue: Collection level options (three dots) is overlapping with the Documentation tab on the right.

### ISSUE THREAD

**Issue by Pricilla09** [a85/POSTMan-Chrome-Extension#9779] opened 2021-03-30 04:12 UTC
**Describe the Issue**
When a Collection level view is selected, the option button (three dots) is visible clearly, but when the Documentation is expanded, the options are now overlapped. 

**Steps to Reproduce**
1. Select any collection inside the workspace.
2. Select and expand the documentation on the right side panel. 

**Screenshots or Videos**

https://user-images.githubusercontent.com/71498483/112933119-cc3f2180-9151-11eb-8abf-00bae805848d.mp4

**Environment Information**

 - Platform Type: Desktop Application
 - Postman Version: Version 8.0.9
 - Operating System: Win 10

**Additional Context**
Issue happens in Application as well as web version.

**Comment by DannyDainton** [comment] 2021-03-30 15:55
Hey @Pricilla09 

Thanks for reporting - We are tracking this issue internally but it's always good to have something public to reference.

Appreciate you reporting this 🏆

**Comment by Pricilla09** [comment] 2021-03-31 05:36
@DannyDainton Great then, Thanks a lot Danny!!

**Comment by DannyDainton** [comment] 2022-06-30 11:31
Unable to reproduce this issue in the latest version of the platform. Going to close this out but we can reopen if you see the issue again.

**Closed as completed by DannyDainton** 2022-06-30 11:31 UTC
Labels: user-interface, product/client-foundation
