### ISSUE TITLE
Search for requests in documentation

### ISSUE THREAD

**Issue by jsooter** [a85/POSTMan-Chrome-Extension#9188] opened 2020-10-20 22:59 UTC
**Is your feature request related to a problem? Please describe.**
When the number of requests are high it can be difficult to find a specific request. Not all API's are as intuitive, or similar to systems of organization we use as common reference. This means that it can be extremely difficult for someone new to an API to find a request definition when they don't already know where it is likely to be. Now add nested folders and hundreds of endpoints and it can be very frustrating.

**Describe the solution you'd like**
Place a search box on the documentation page that would filter requests in the requests list on the left.
![Quickbooks-Payments-API-Collections](https://user-images.githubusercontent.com/17498322/96652158-332af580-12eb-11eb-97f1-69bdc65cec9b.png)

**Describe alternatives you've considered**
Using ctrl+F/cmd+F on the keyboard

The draw back to this is it will stop on every occurance of the word you search for. This could occur many times in the descriptive text as well as the request itself. It also can be slower on very large pages.

**Additional context**
In this example there are 35 occurences of the word "refund" but only 3 refund end points. Also, none of the folders titles mention refunds so the user would have to open each one by one or use keyboard shortcuts to find the end points.
<img width="1425" alt="Screen Shot 2020-10-20 at 3 48 54 PM" src="https://user-images.githubusercontent.com/17498322/96652494-dc71eb80-12eb-11eb-9777-14f2dcc32f89.png">

The examples above are used because they are public and available from the API Network.

**Comment by daveploger** [comment] 2020-10-22 12:24
Filtering the folders on the left side would be helpful.  But there may be better UI alternatives.  The Key purpose is to enable easy browsing of search results.
  
Suggestion: something more like Google search results.

**Comment by Raja-Simha** [comment] 2020-11-19 04:20
Duplicate of #3747

**Closed as completed by Raja-Simha** 2020-11-19 04:20 UTC
Labels: feature, product/documentation
