### ISSUE TITLE
v4.0.3: Extra headers not sent with OPTIONS

### ISSUE THREAD

**Issue by creynders** [a85/POSTMan-Chrome-Extension#1773] opened 2016-03-01 15:06 UTC
If I try to request OPTIONS with a `Access-Control-Request-Method: POST` header for instance the ACRM header isn't sent to the end-point with v4.0.3 (mac app) see:

```
OPTIONS /api/log.json HTTP/1.1
Host: [edited]
Cache-Control: no-cache
Origin: file://
Content-Type: application/json
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Postman/4.0.3 Chrome/47.0.2526.73 Electron/0.36.2 Safari/537.36
Postman-Token: 2ce23b8f-bdcb-1f9c-713f-ebc4055f89af
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US
```

This is not a problem using the chrome app (v3.2.17) though:

```
OPTIONS /api/log.json HTTP/1.1
Host: [edited]
Content-Length: 0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
Postman-Token: 51bc51db-bbc8-0279-6275-275dc4a7e969
Cache-Control: no-cache
Origin: chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo
Content-Type: text/plain;charset=UTF-8
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Access-Control-Request-Method: POST
```

**Comment by abhijitkane** [comment] 2016-04-26 12:49
@creynders This is a limitation of Chrome's XHR object - it doesn't allow this header to be set. We're working on moving away from XHR, but there's no timeframe on that yet.

**Comment by a85** [comment] 2016-06-19 19:01
You can get the Postman Canary build to help us test this out. Details here: http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/

Closing this as a duplicate of #1584

**Closed as completed by a85** 2016-06-19 19:01 UTC
Labels: bug
