### ISSUE TITLE
I'm losing my open tabs when I choose to sign in with another account and revert. 

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#4833] opened 2018-07-16 13:43 UTC
**Describe the bug**
When I choose to add another account but for some reason, I decide not to add and exit the process, I am losing all the open tabs that I had.

**To Reproduce**
1. Have a few unsaved tabs
2. Click on 'Add a new account'
3. In the sign in page, select 'cancel and take me to signed in account'.
4. You'll see the app starts fresh and you'll lose all the unsaved tabs.

**Expected behavior**
I want the app to retain the context that I had.

**Comment by SamvelRaja** [comment] 2018-07-17 04:26
@sujayvenaik  Verify this behavior and get this covered if not available in the current version.

**Comment by kamalaknn** [comment] 2018-07-18 19:36
@thecuriousdev It looks like Postman on exit from login a new window is opened instead of restoring the existing window. Can you confirm?

**Comment by thecuriousdev** [comment] 2018-07-19 06:10
@kamalaknn I am able to reproduce this issue. We're loosing the data when we switching the sessions, will look into this.

**Comment by numaanashraf** [comment] 2019-04-23 15:00
Fixed in Postman v7.0.8

**Closed as completed by numaanashraf** 2019-04-23 15:00 UTC
Labels: bug, tabs
