### ISSUE TITLE
version 5.0.2 - white blank screen on OS X 10.12

### ISSUE THREAD

**Issue by jumeracosta** [a85/POSTMan-Chrome-Extension#3243] opened 2017-07-06 10:13 UTC
## App Details:

```
Postman for Mac
Version 5.0.2
OS X 10.12
```

## Issue Report:
I've recently updated my Postman for Mac and then after the fresh update, my Postman app always show as a white blank screen after a few secs. I tried to reload, new tab, new window and I'm still getting the same issue.
<img width="1087" alt="postman_white_screen" src="https://user-images.githubusercontent.com/18678415/27906205-2f5d7394-6275-11e7-9457-a4d4f6525fa8.png">

**Comment by kamalaknn** [comment] 2017-07-06 10:36
Hey @jumeracosta 

This looks like a duplicate of #3229.

Could you open the app via command line and see if there are any error messages? (The app should be in `C:\Users\<User>\AppData\Local\Postman\app.4.10.2\Postman.exe`)

Do you see any error messages in the DevTools? (`View -> Show DevTools`)

I am closing this issue so we can track this in the parent issue. Feel free to reopen this if you feel this is not related to the linked issue.

**Closed as completed by kamalaknn** 2017-07-06 10:36 UTC

**Comment by jumeracosta** [comment] 2017-07-06 11:00
@kamalaknn thanks for your quick response. I think the issue #3229 is for Windows. 
Here's what I've got from the DevTools console. see screenshot below.
<img width="866" alt="devtools-postman" src="https://user-images.githubusercontent.com/18678415/27908114-e010b4b0-627c-11e7-9310-2eed94e9ef5e.png">

**Comment by kamalaknn** [comment] 2017-07-06 11:37
@jumeracosta Sorry for the mixup there.

Are you using the app from the `Downloads` folder or the Applications folder?

Could you open up the app via command line `/Applications/Postman.app/Contents/MacOS/Postman` or `<path/to/your/file/Postman.app/Contents/MacOS/Postman>` and share the logs you see?

**Comment by jumeracosta** [comment] 2017-07-06 11:47
@kamalaknn see the logs below.
$ /Applications/Postman.app/Contents/MacOS/Postman

<--- Last few GCs --->

   25480 ms: Mark-sweep 1399.5 (1491.7) -> 1399.5 (1491.7) MB, 140.5 / 7.5 ms [allocation failure] [GC in old space requested].
   25775 ms: Mark-sweep 1399.5 (1491.7) -> 1399.5 (1452.7) MB, 294.9 / 140.8 ms [last resort gc].
   25951 ms: Mark-sweep 1399.5 (1452.7) -> 1399.5 (1446.7) MB, 175.5 / 15.4 ms [last resort gc].
   26114 ms: Mark-sweep 1399.5 (1446.7) -> 1399.5 (1441.7) MB, 163.1 / 13.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x34d90fe14aa9 <String[7]: file://>
    1: /* anonymous */ [file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:~272947] [pc=0x16c13a59d46d](this=0x3e2b42067931 <an IDBRequest with map 0x28f5af34e51>,e=0x3cf9ea791d21 <an Event with map 0x108efd708b91>)

==== Details ================================================

[1]: /* anonymous */ [file:///Applications/Postman.app/Contents/Resources/app/js/reques...

**Comment by kamalaknn** [comment] 2017-07-06 13:13
This looks odd. 

Looks like the app is having trouble loading its data from IndexedDB. 

If you have Sync enabled and have synced all your data, you can try clearing the apps data directory and relaunching the app. The data directory should be `~/Library/Application\ Support/Postman`.

**Note: Clearing the data directory is not reversible. Make sure you do not have any unsynced data. You can login to https://app.getpostman.com to check your saved data.**

**Comment by jumeracosta** [comment] 2017-07-06 15:47
@kamalaknn that works fine for me! Thanks for the help :)..
