### ISSUE TITLE
Creating a monitor from within the app sometimes results in it not being assigned to any workspace

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4887] opened 2018-07-25 18:07 UTC
Not reproducible, app version 6.0.10

From a user:
I used the create monitor flow from inside the Postman app on a Mac. It was spinning setting up the monitor and it had a cancel button below it which I hit. We did this a couple of times and each time it resulted in a monitor, and I could delete all but one of them.

**Comment by numaanashraf** [comment] 2019-01-09 12:33
Closing this as we are not able to reproduce this on the current version of Postman (v6.6)

**Closed as completed by numaanashraf** 2019-01-09 12:33 UTC
Labels: bug
