### ISSUE TITLE
Sending a request with `If-None-Match` header resulting in 304 response fails with "Parse Error".

### ISSUE THREAD

**Issue by jsamr** [a85/POSTMan-Chrome-Extension#5353] opened 2018-10-12 13:11 UTC
**Describe the bug**
Sending a request with `If-None-Match` header resulting in 304 response fails with "Parse Error".

**To Reproduce**
1. Create a request to a valid endpoint supporting ETag caching
2. Add `If-None-Match` header
3. Click "send"
4. Server must respond 304
5. Postman claims it "Could not get any response"
6. Postman console shows a "Parse Error"

**Expected behavior**
A 304 response should be handled properly by Postman.

**Screenshots**

![image](https://user-images.githubusercontent.com/3646758/46871133-d8737f00-ce30-11e8-9254-8d32db50f942.png)
![image](https://user-images.githubusercontent.com/3646758/46871173-ee813f80-ce30-11e8-8cd5-2f39a4e2478a.png)

**App information (please complete the following information):**
 - App Type : Native (Linux, [aur](https://aur.archlinux.org/packages/postman-bin))
 - Postman Version : 6.4.2 and 6.3.0
 - OS: Manjaro Linux

**Additional context and tracks**

- I **could not** reproduce with chrome extension.
- I **could** reproduce with 6.3 version.
- I tried with quoting etag value without success.
- ~~Removing the `/` character result in a successful request~~ This is wrong : the reason it worked was that the response was not 304 anymore but 200.
- TLS certificates checks are disabled in Postman, but I could reproduce the issue with a bare HTTP connection.

**EDIT 1**: added relevant updates

**Comment by jsamr** [comment] 2018-10-12 13:17
As a side note, it just reveals another bug: `include-*` should not be included in request as they are grayed out in headers editor.

**Comment by numaanashraf** [comment] 2018-10-15 11:30
Thanks for writing in. Looks like Postman is not able to parse the response received. Could you retry the request with cURL and let us know whether you receive the response?

**Comment by jsamr** [comment] 2018-10-15 12:15
@numaanashraf Please take note that I disabled TLS checks in Postman, **but** I could reproduce with my server host in HTTP.
Bellow is my attempt (I obfuscated Bearer token). I made few other inferences:

- I can confirm it's a response parsing issue since **the request is logged server side**.
- I don't think it's related to `/` parsing in header anymore since **I could reproduce with slash-free ETag values**.
- I believe it's caused by empty body in `304` response, which I guess Postman tries to parse (I'll reword the title accordingly)

```bash
jsamr@localhost ~  $ curl -k -v -X GET \
                        https://localhost:8443/therapeutiques/340 \
                        -H 'Accept: application/json' \
                        -H 'If-None-Match: ztW/I2/Xjljawj7a+ktBKjfuToTItckV6G/Se/eZPTg=' \
                        -H 'cache-control: no-cache' \
                        -H 'Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / DHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: O=Docker Boilerplate; CN=*.vm
*  start date: May  4 17:14:40 2015 GMT
*  expire date: May  1 17:14:40 2025 GMT
*  issuer: O=Docker Boilerplate; CN=*.vm
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /therapeutiques/340 HTTP/1.1
> Host: localhost:8443
> User-Agent: curl/7.61.1
> Accept: application/json
> If-None-Match: ztW/I2/Xjljawj7a+ktBKjfuToTItckV6G/Se/eZPTg=
> cache-control: no-cache
> Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> 
< HTTP/1.1 304 Not Modified
< Date: Mon, 15 Oct 2018 12:02:41 GMT
< Server: Apache/2.4.25 (Debian)
< ETag: ztW/I2/Xjljawj7a+ktBKjfuToTItckV6G/Se/eZPTg=
< Cache-Control: max-age=0, must-revalidate, public
< Vary: Authorization
< 
* Excess found in a non pipelined read: excess = 4 url = /therapeutiques/340 (zero-length body)
* Connection #0 to host localhost left intact

```

**Comment by shamasis** [comment] 2019-05-13 11:27
Looks like an issue with body being less than content-length

```
* Excess found in a non pipelined read: excess = 4 url = /therapeutiques/340 (zero-length body)
* Connection #0 to host localhost left intact
```

**Comment by shamasis** [comment] 2019-05-13 11:28
Related to: https://github.com/postmanlabs/postman-app-support/issues/2418

**Comment by codenirvana** [comment] 2019-10-31 10:19
Closing as duplicate of #2418

@jsamr we are currently working on the original issue as mentioned in https://github.com/postmanlabs/postman-app-support/issues/5353#issuecomment-491784071

**Closed as completed by codenirvana** 2019-10-31 10:19 UTC
Labels: bug, request-sending, product/runtime
