### ISSUE TITLE
Slack Integration – Monitor Run Results ignoring "Notify for 3 failures and then first success" flag

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#4820] opened 2018-07-12 22:40 UTC
**Describe the bug**
The Slack integration ignores the `Notify for 3 failures and then first success` option that's been set in the [dashboard](https://app.getpostman.com/dashboard) and posts multiple successful runs instead of just the one (1) after a series of failures.

**To Reproduce**
1. Add the Slack integration to a workspace with a monitor
2. During setup, open `Advanced Settings` and select the `Notify for 3 failures and then first success` option
3. Watch Slack channel for multiple successful run messages when there should only be one that appears after failures.

**Expected behavior**
Notifications should only come in if there are failures in the monitor

**Screenshots**
![slack integration](https://i.imgur.com/Cgpq2f5.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Comment by bbartoni** [comment] 2018-07-17 06:45
Looks like the issue started occurring when you guys implemented the restart-logic to your scheduler. I'm observing that the success-notifications are sent to slack only when the monitor runs at a irregular time. Most of my monitors are set with a 30-min interval, and this issue appears if the monitor has lagged and restarted after 15mins. adding screenshot.
![screenshot from 2018-07-17 08-43-51](https://user-images.githubusercontent.com/24898010/42800884-c32cb3f0-899d-11e8-83bc-e86108aac98a.png)

**Comment by ankitjaggi** [comment] 2018-07-17 08:02
We're looking into a bug on our Monitoring service, which will prevent the duplicate runs you maybe seeing. I'll keep you updated on the same.

**Comment by godfrzero** [comment] 2018-07-19 13:14
Update: We've isolated the issue and we're working on a fix. I'll update here again once we've pushed the fix.

**Comment by godfrzero** [comment] 2018-07-28 03:28
Update: We've applied a fix and repeated runs/notifications should no longer be occurring.

@bbartoni Could you confirm?

**Comment by bbartoni** [comment] 2018-07-28 16:30
I can confirm that the issue has been resolved. I'll keep an eye if I see some other issue. Thanks for your help.

**Comment by bbartoni** [comment] 2018-07-31 18:24
There could be a latent bug related to this ticket. Seeing occurrences where postman-monitors fails to send the success-after-fail slack notification @godfrzero

**Comment by bbartoni** [comment] 2018-07-31 18:29
correction - the slack notification triggers after second successful run.

**Closed as completed** 2019-03-04 21:42 UTC
Labels: bug, product/automation-testing, product/dashboard
