### ISSUE TITLE
Google Login Fails - Insecure Browser | Add Open with Other Browser support

### ISSUE THREAD

**Issue by AkashM398** [a85/POSTMan-Chrome-Extension#7838] opened 2019-12-22 13:28 UTC
**Describe the bug**
Google Login doesn't work and says the postman browser is insecure to login.

**To Reproduce**
1. Open Pinterest Login 
2. Login with Google Account

**Expected behavior**
It should have logged in to the Pinterest page, but didn't happen instead it showed the error and couldn't able to move to the next step.

**Screenshots**

![GA](https://user-images.githubusercontent.com/38563661/71322325-6f839e80-24ec-11ea-8a4e-27e81680e632.png)

**Solution**
Add open with other browser feature, so could be able to open the app with different browsers as well.

**Additional context**
If this app is open source I would like to work on this issue.

**Comment by kamalaknn** [comment] 2019-12-23 04:23
Duplicate of #7700 

I'm closing this issue. Please subscribe to the original thread for updates.

**Closed as completed by kamalaknn** 2019-12-23 04:23 UTC
