### ISSUE TITLE
<What a about a console in your extension in VS-code>

### ISSUE THREAD

**Issue by MEMSTER94** [a85/POSTMan-Chrome-Extension#12252] opened 2023-08-22 10:02 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When I am using console.log can't see the console in VS-code

### Describe the solution you'd like

It would be nice to see your output when you are using VS-code

### Describe alternatives you've considered

You can use the debug console in VS-code

**Comment by pankajk07** [comment] 2023-08-22 11:02
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/12187

**Closed as completed by pankajk07** 2023-08-22 11:02 UTC
Labels: feature, vscode
