### ISSUE TITLE
Export Web Socket Collection

### ISSUE THREAD

**Issue by komape** [a85/POSTMan-Chrome-Extension#11731] opened 2023-02-15 15:26 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I need to export a collection that contains web socket connections to share it with customers. Right now, I can't share it which makes Postman useless for technical documentation of web sockets.

### Describe the solution you'd like

An export and import function for web socket collections.

**Comment by codenirvana** [comment] 2023-02-15 15:59
@komape sharing the collection in a [Postman workspace](https://www.postman.com/product/workspaces/) might help here.
For example, you can share your WebSocket APIs with everyone in a [public workspace](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/public-workspaces/).

Closing as duplicate of #11252

**Closed as completed by codenirvana** 2023-02-15 15:59 UTC
Labels: feature, protocol/websocket, product/api-client
