### ISSUE TITLE
Parameters with identical names are removed when disabled in GET requests.

### ISSUE THREAD

**Issue by gabrielmuresan** [a85/POSTMan-Chrome-Extension#3311] opened 2017-07-26 07:51 UTC
## Issue Description:
When trying to add a list of parameters and then disabling one of them starting from the first one, parameters disappear instead of getting disabled.

## App Details:
```
Postman for Mac
Version 5.1.2
OS X 16.6.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: __recently__
 2. Expected behaviour: __Parameter should remain visible, but disabled.__
 3. Console logs: __Not applicable__
 4. Screenshots: 
__Initial setup:__
![screen shot 2017-07-26 at 09 40 26](https://user-images.githubusercontent.com/6017306/28609834-7eda5fd8-71e6-11e7-8696-eb6d0e33def0.png)

__Result after 1 single click on the first checkmark of someList[] with value 1__
![screen shot 2017-07-26 at 09 43 46](https://user-images.githubusercontent.com/6017306/28609973-f96f8016-71e6-11e7-8680-599dd8feb1b8.png)

__Expected result:__
someList[] with value 1 should be grayed out, not removed.

 5. Steps:
     1. Open new tab and leave as GET request
     2. Write any url
     3. Open "parameters"
     4. Write parameter 1 named "someList[]" with any value, let's say "1"
     5. Write parameter 2 named "someList[]" with any value, let's say "2"
     6. Try to disable value parameter with value "1"
     7. **Error:** parameter disappears instead of being disabled

 6. Alternative steps:
     1. Open new tab and leave as GET request
     2. Write any url
     3. Open "parameters"
     4. Write parameter 1 named "someList[]" with any value, let's say "1" 
     5. Disable this parameter
     6. Create another parameter named "someList[]"
     7. **Error:** Impossible, the moment you type the last character, the previously disabled parameter disappears.

P.S. Error not present in POST body parameters.

**Comment by sdnts** [comment] 2017-07-26 09:36
Hi @gabrielmuresan, we were able to reproduce this, we'll get on a fix ASAP

**Comment by SamvelRaja** [comment] 2018-06-29 12:37
Duplicate of #4513

**Closed as completed by SamvelRaja** 2018-06-29 12:37 UTC
Labels: bug
