### ISSUE TITLE
Variable handling is not the same in request builder and runner

### ISSUE THREAD

**Issue by klemens-u** [a85/POSTMan-Chrome-Extension#6352] opened 2019-04-24 11:03 UTC
Situation:

Environment variable: `"status_code_default" = 200`

Collection Test (Collection -> Edit -> Tests):
```
statusCodeDefault = Number(pm.variables.get("status_code_default"));
pm.test("Status code is " + statusCodeDefault, function () {
    pm.response.to.have.status(statusCodeDefault);
});
```

So this adds a default test to every request checking if the status code = 200.

Now for a specific request we want to override the default value:
Request -> Pre-request Script: `pm.variables.set("status_code_default", 400);`

This way we can assert that the request expects code 400.

This works fine in the request builder.

Problem: it does not work for subsequent request in runner. The default value from the environment is not loaded before the next request. Therefore the last custom value leaks into the next request.
For example for the subsequent request I expect code 200 again, but in the runner it is still set to code 400.

Postman v7.0.9
Ubuntu 16.04

**Comment by m3dbedb** [comment] 2019-05-27 07:49
This should not work at all. By using pm.variables.set you address to collection variables, and they are not allowed to be modified while collection run. They are to be pre-defined and you may only read them.
pm.variables.set is not allowed.
[https://hghltd.yandex.net/yandbtm?lang=en&fmode=inject&tm=1558942838&tld=ru&la=1558537344&text=pm.variables.has&url=https%3A%2F%2Flearning.getpostman.com%2Fdocs%2Fpostman%2Fenvironments_and_globals%2Fvariables&l10n=ru&mime=html&sign=f2b52e5a32e22d9645e9a51fdadccdc0&keyno=0](url)
> Defining collection  variables 
> Collection  variables  can be defined by editing the collection details. Click ellipsis (...) next to the collection name, and select “Edit” to open the EDIT COLLECTION modal. Select the  Variables  tab to add and edit collection  variables . You can also define collection  variables  when creating the collection.

**Comment by klemens-u** [comment] 2019-05-27 08:28
@m3dbedb: what method would you propose for the described use case? 

Similar behaviour in both request builder and runner would be very desireable.

**Comment by m3dbedb** [comment] 2019-05-27 12:51
I use environmet variable to  store test stand settings, and globals for temporary data (I understand that it  sounds odd, but I keep environment parameters in environment variables, and it is consistent).

**Comment by klemens-u** [comment] 2019-05-27 12:55
@m3dbedb sorry, but what do you mean by that? How does that help with the example above for a default test case & default value?

**Comment by m3dbedb** [comment] 2019-05-27 12:56
@klemens-u, in my previous post edit I missed issue and passed wrong advice.

**Comment by klemens-u** [comment] 2019-05-27 13:29
@m3dbedb ok, no problem :-)

**Comment by shamasis** [comment] 2019-06-17 17:32
This is intended behaviour of Postman. I suggest that you unset that variable right after testing so that any of them set in previous scripts do not affect the next. Closing.

**Closed as completed by shamasis** 2019-06-17 17:32 UTC
Labels: bug, variables, wont-fix, product/runtime
