### ISSUE TITLE
Unable to use any variables (global, collection, env etc) for field description.

### ISSUE THREAD

**Issue by PU7510** [a85/POSTMan-Chrome-Extension#8068] opened 2020-02-14 20:24 UTC
Hi

I started writing description for my query string parameters within API requests and since a single API has multiple requests, I wanted to create the Global variables for the field description and then use it in the description column. For ex.: My API excepts a query string paramater named channelType. In the description column for this field I want to write that "Mandatory input. Supports value AA, AFF and WEB". However. since I would be creating atleast 10 different requests for happy and exception scenarios, I dont want to populate the same description in all 10 of those requests. So the idea was to define a global variable lets 'channel_type_desc' with value "Mandatory input. Supports value AA, AFF and WEB". If lets say, tomorrow, the API starts supporting a new channel type named CallCenter, then I would want to update the field description only in the global variable and it automatically reflects in each of the requests and my documentation is auto-refreshed with the new field description. 
However, this isnt working. The field description field isnt treating {{channel_type_desc}} as a variable and this is getting printed as is within the documentation.
Is there currently any fix / workaround available for this issue?

**Comment by Raja-Simha** [comment] 2020-02-18 07:32
Duplicate of #6795

**Closed as completed by Raja-Simha** 2020-02-18 07:32 UTC
Labels: product/documentation

**Comment by Raja-Simha** [comment] 2020-03-02 10:05
@PU7510 you can use environment and collection variables to resolve them within descriptions. Currently, we only show resolved variables in the web view of the collection. (Collection Browser -> View in Web). We do not resolve global variables.

Let me know if this helps and feel free to leave your comments.
