### ISSUE TITLE
Tab characters are removed from request body when syncing in cloud to another system

### ISSUE THREAD

**Issue by TheAllThing** [a85/POSTMan-Chrome-Extension#2289] opened 2016-08-23 22:45 UTC
I work in a cloud Postman environment. I have a tab delimited flat file that I am posting to an API.  When copying the tab delimited file to the request body, it retains the proper structure. However, when the collection is saved to cloud and is then synced to another system, it replaces the tabs with spaces on that new system. Not sure if corruption occurs when the collection syncs to the cloud or after it syncs to a new system for the first time.
1. Postman Version: 4.6.2
2. App (Chrome app or Mac app): Chrome
3. OS details: Multiple - Windows 7, 8, 10
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Recently, but may have always been there.
6. Expected behaviour: retain tab characters in the request body
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by abhijitkane** [comment] 2016-08-24 05:39
@TheAllThing I'm unable to reproduce this. Can you contact us at help@getpostman.com with your username/email, and the request you're seeing this issue with?

**Comment by numaanashraf** [comment] 2016-10-05 13:17
@TheAllThing This should be addressed in the latest version (v4.7.2+) of the app.

**Closed as completed** 2016-12-22 20:44 UTC
Labels: support
