### ISSUE TITLE
The + (plus) sign in the params list encodes to %20, not %2B

### ISSUE THREAD

**Issue by concordion2k** [a85/POSTMan-Chrome-Extension#2664] opened 2017-01-29 20:23 UTC
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Win 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: + sign should be encoded as %2B
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

1. Create a **GET** request
2. **Add** a parameter that includes a + sign, such as an international phone number
3. Click **CODE**
4. Select **cURL**
5. Observe that the + sign has been converted to %20

My company's use case: pass in an international phone number with a + sign as a parameter so we can return a filtered list of items that contain the specified phone number.

**Comment by mhertogs** [comment] 2017-01-30 22:47
This seems to be a duplicate of #2579  . You can follow the progress of this issue there.

**Comment by SamvelRaja** [comment] 2017-01-31 06:50
Closing as it is a duplicate of #2579

**Closed as completed** 2017-01-31 06:50 UTC
