### ISSUE TITLE
Importing a collection changes all request id's

### ISSUE THREAD

**Issue by ManiacDC** [a85/POSTMan-Chrome-Extension#8440] opened 2020-05-05 12:48 UTC
**Describe the bug**
After a recent Postman update (yesterday is when I first noticed it), when I import a collection, and then export it, all the request id's are changed in the export json collection. This happens upon import, as if I export the same collection twice (without re-importing), the request id's match; however, if I Import > export > import > export, the request id's will not match.

My group's workflow is to import the collection, make changes in Postman, and then export it and commit it. Changing the request id's will cause numerous conflicts during merges.

**To Reproduce**
1. Import a previously-exported collection v2.1
2. Export the collection to a different file
3. Compare the original file and the new file, note the id's are all different

**Expected behavior**
Prior to a recent Postman update, only the collection id (1 line) would change, which was easy enough to fix. The request id's would not change. The expected behavior is that the request id's do not change.

**App information (please complete the following information):**
 - Postman for Windows
 - Postman Version 7.23.0
 - OS: Windows 10 18362 x64

**Comment by arlemi** [comment] 2020-05-07 13:55
@ManiacDC Which collection format are you using? Collection v2 and v2.1 formats do not contain request IDs. (read more about [the differences between v1 and v2 here](https://blog.postman.com/travelogue-of-postman-collection-format-v2/)). 
If you are exporting your collections in the v1 format I would recommend that you switch to v2.1. 

If you are in v2 or v2.1 then you may be talking about pre-requests and tests IDs, in that case we have voluntarily changed the behaviour for these to be updated on import from Postman 7.23. Each entity that is imported is considered a new entity and therefore should have unique IDs.  
We've discussed the same workflow that you have in #4802 if you'd like more context.

We're working on ID-less export in the meantime, we'll update the following issue when we have more info about it #2906. 

I'll close this issue since this isn't a bug, let me know if there's anything you'd like more clarity on!

**Closed as completed by arlemi** 2020-05-07 13:55 UTC

**Comment by ManiacDC** [comment] 2020-05-07 14:11
Hi @arlemi , we are using v2.1. Sorry, I'm referring to pre-request and test ID's then.

It looks like there's no real solution until 2906, but I'll see if that postman-cli will do anything for us. Thank you.

**Comment by arlemi** [comment] 2020-05-07 14:59
@ManiacDC Based on your team size/number of requests you're working with you may want to have a look at [collaborating directly in Postman](https://learning.postman.com/docs/postman/collaboration/collaboration-intro/) which gives you version control directly in the app instead of going through git.

**Comment by ManiacDC** [comment] 2020-05-07 15:38
Thanks, I'm aware of that, but it's not an option for our workflow.

**Comment by murven** [comment] 2020-05-14 16:08
@arlemi Having two version control systems and the need for two separate PRs, reviews and approvals is definitely not a viable option in most teams.

**Comment by ManiacDC** [comment] 2020-05-14 16:11
Also, looked into postman-cli. We actually already have an assembler/disassembler that's more powerful than that tool, so it won't help us with this scenario either.

**Comment by arlemi** [comment] 2020-05-14 16:16
@murven We're also tracking feature requests on synchronising API/collections with other git repositories (other than GitHub), see #4780 or #8245. 

@ManiacDC If you have a custom tool, while we work on the ID-less export, you could add a step to remove all pre-request/test IDs before pushing to the repository.

**Comment by ManiacDC** [comment] 2020-05-14 17:12
@arlemi it's an idea we're probably going to implement. We'd have to strip it after running postman-collection module.

**Comment by arlemi** [comment] 2020-05-14 17:15
@ManiacDC Would love to see it showcased here if you end up implementing it: https://community.postman.com/c/content-showcase/7, also feel free to open a topic on the community forum if you'd like help with it, quite a few of us who'd de be happy to help. 😄

**Comment by murven** [comment] 2020-05-14 17:27
@arlemi  I tried setting the ID to empty string in JSON, but now Postman cannot import it anymore. Would it be necessary to completely remove it?

**Comment by arlemi** [comment] 2020-05-14 17:33
@murven Just tried with both empty string and removing it completely and import worked without issue. Admittedly I'm trying on a very simple collection but it shouldn't matter. Would you mind sharing your export (after removing any sensitive data)?

**Comment by murven** [comment] 2020-05-14 18:19
@arlemi thanks, but I am not allowed to share, I will try to reproduce with a smaller collection on a generic API later, but without knowing what is making it fail, I am just hitting in the dark, so I will just move on for now.

**Comment by arlemi** [comment] 2020-05-14 20:04
@murven @ManiacDC If you'd like you can reach out to me by email and we can set some time to look into it together: arlemi@postman.com.

**Comment by prakashn27** [comment] 2020-06-30 17:59
We too have the same issue. exports and import with the version 2.1 changes all the ids.

**Comment by obarat** [comment] 2020-09-29 18:57
This is obviously a scheme to make offline collection management painful so more people buy their premium offerings

**Comment by arlemi** [comment] 2020-09-30 09:48
@obarat You can follow improvements on that flow in #2906.
