### ISSUE TITLE
Could't import protobuf definition from wsl

### ISSUE THREAD

**Issue by shjyh** [a85/POSTMan-Chrome-Extension#10609] opened 2022-01-26 13:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

![1643202454(1)](https://user-images.githubusercontent.com/7910808/151168370-c52fae81-a2e8-41ae-afb3-ec0e3c7ba65d.png)

### Steps To Reproduce

1. import protobuf definition from local file
2. select file in wsl
![image](https://user-images.githubusercontent.com/7910808/151168606-d34de19e-927b-46f8-baa8-d0d0a9d98bac.png)

### Environment Information

```markdown
- Operating System: Windows 11 / wsl2 / Ubuntu21.04
- Platform Type: Native App
- Postman Version: 9.10.1
```

**Comment by jgdovin** [comment] 2022-02-23 20:27
I have seen a similar error when I had imports in my .proto file. Do you have any imports in the proto file? If you do you can change them to relative path and importing to postman should work.

**Comment by codenirvana** [comment] 2022-03-10 05:27
Duplicate of #10547, refer https://github.com/postmanlabs/postman-app-support/issues/10547#issuecomment-1062765631.

**Closed as completed by codenirvana** 2022-03-10 05:27 UTC
Labels: protocol/grpc
