### ISSUE TITLE
How to use data file to monitor a collection?

### ISSUE THREAD

**Issue by zankhanarana9** [a85/POSTMan-Chrome-Extension#5989] opened 2019-02-26 17:22 UTC
How do I use a data file to monitor my postman collection? I read in the Postman Documentation that it is not possible to use a data file as we use for collection run but we can access Google docs, google sheets etc. I don't understand how do we import these files?

**Comment by numaanashraf** [comment] 2019-02-27 07:37
Duplicate of #3174

**Closed as completed by numaanashraf** 2019-02-27 07:37 UTC
Labels: duplicate
