### ISSUE TITLE
[Import Collections] Always create a copy collections after imported instead of overwrite existed collections 

### ISSUE THREAD

**Issue by hainguyenh** [a85/POSTMan-Chrome-Extension#9128] opened 2020-10-06 01:30 UTC
Used on version v7.33.1 

I tried to import a collection, but it always creates a copy instead of overwriting

**To Reproduce**
1. I have a collection A in the Postman environment & local hard disk
2. Import the collection A again

**Actual results:**
On postman collections, I have 2 collections
- A
- A - copy

**Expected behavior**
A pop-up will display and ask the user to create a copy or overwrite

**Note**
I tried to use the import function via Setting > Data => Import data (description: Import a Postman data dump. This may overwrite existing data.) but the same issue.

If we have a setting for this....

**Comment by DannyDainton** [comment] 2020-10-06 15:22
Thanks for reporting this @hainguyenh - This is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9037

I'm going to close this issue, you can follow updates over on the other issue as and when we have them.

**Closed as completed by DannyDainton** 2020-10-06 15:22 UTC
Labels: duplicate
