### ISSUE TITLE
pm.request.url.getPath() does not take variable into account in Pre-RequestScript leading to an error result

### ISSUE THREAD

**Issue by ihipop** [a85/POSTMan-Chrome-Extension#6078] opened 2019-03-14 08:22 UTC
**Describe the bug**
`pm.request.url.getPath()` does not take variable into account in **Pre-RequestScript** ,leading to an error result
It just think that the start of  first `/` in URL is the request path.

**To Reproduce**
#### Case One：
- Set URL to `{{api}}param2/param3/4444`
- Set variable `{{api}}` to `https://example.com/openapi/`
- Run `console.log(pm.request.url.getPath())` in **Pre-RequestScript**  ，it returns that the request path is ` /param3/4444`
- Run `console.log(pm.request.url.getPath())` in **Tests**,it returns the correct one

#### Case Two： 
- Set URL to `{{api}}/param2/param3/4444`
- Set variable `{{api}}` to `https://example.com/openapi`
- Run `console.log(pm.request.url.getPath())` in **Pre-RequestScript**  ，it returns that the request path is `/param2/param3/4444`
- Run `console.log(pm.request.url.getPath())` in **Tests**,it returns the correct one

**Expected behavior**
#### Case Two：Shoud return `/openapi/param2/param3/4444`,too

**Screenshots**
None

**App information (please complete the following information):**
 - App Type: Native App,Postman for Linux
 - Postman Version: Version 6.2.4
 - OS: linux 4.15.0-29deepin-generic / x64, Debian alike OS, Linux Deepin

**Additional context**
https://github.com/postmanlabs/postman-app-support/issues/5767

**Comment by codenirvana** [comment] 2019-03-14 19:22
@ihipop That's expected behavior because in `pre-request` script the variables are not resolved.

For now, the only workaround is:
```javascript
const {Url} = require('postman-collection');

let url = new Url(pm.environment.get("url") + pm.request.url.getPath());

console.log(url.getPath())
```

In the future, an interpolation method (#5767) will help here.

**Comment by ihipop** [comment] 2019-03-15 03:48
@codenirvana  I write some Utility to extend `pm`
```javascript
pm.myUtility = {
    interpolateVariable: function (str) {
        return str.replace(/\{\{([^}]+)\}\}/g, function (match, $1) {
            // console.log(match)
            let result = match; //default to return the exactly the same matchd variable string
            if ($1) {
                let realone = pm.variables.get($1);
                if (realone) {
                    result = realone
                }
            }
            return result;
        });
    },
    getUrl: function () {
        let url = pm.request.url.getRaw();
        url = this.interpolateVariable(url)
        let {
            Url
        } = require('postman-collection')
        return new Url(url);
    },
    getUrlTest: function () {
        let url = pm.request.url.getRaw();
        url = this.interpolateVariable(url)
        // let {
        //     Url
        // } = require('postman-collection')
        //return new Url(url);
        return pm.request.url.parse(url);
    }
}
```
```pm.myUtility.getUrl().getPath()```  Work like a charm

~~but
`pm.myUtility.getUrlTest()` have a Exception throw out that  said:
 `pm.request.url.parse` is not a function~~

~~**The doc：**~~

![image](https://user-images.githubusercontent.com/423077/54407210-e6973580-4717-11e9-8cfe-5b884fb4843b.png)
![image](https://user-images.githubusercontent.com/423077/54407291-3d047400-4718-11e9-8318-43f90e5c5642.png)

~~Why？~~

**Comment by ihipop** [comment] 2019-03-15 03:56
I know，it's a prototype issue,`parse()`  is  static.
Hope #5767 will have some progress. Close this issue if you want.

**Comment by codenirvana** [comment] 2019-03-15 06:20
@ihipop Yes `parse` is a static function. The utility script looks fine for now but definitely not the actual solution you are looking for.

Closing this issue, please follow the variables interpolation thread for updates.

**Closed as completed by codenirvana** 2019-03-15 06:20 UTC
Labels: support

**Comment by ihipop** [comment] 2019-03-15 06:32
@codenirvana 
```javascript
apiPath = pm.myUtility.getUrl().getPath()
```
This works as excepted

`pm.myUtility.getUrl()`  return the  **fully variables  resolved**  `Url` object
then the `getPath()` of `Url` object will  Works like a charm.

The core issue is that  `pm.request.url` in  **Pre-RequestScript**  is not   **fully variables  resolved**  

Thanks for your hint in code.

The actual solution I'm  looking for  is that there is an official  interpolation method (#5767)  like `pm.myUtility.interpolateVariable() `  to be built in postman core

------

```javascript
pm.myUtility = {
    interpolateVariable: function (str) {
        return str.replace(/\{\{([^}]+)\}\}/g, function (match, $1) {
            // console.log(match)
            let result = match; //default to return the exactly the same matchd variable string
            if ($1) {
                let realone = pm.variables.get($1);
                if (realone) {
                    result = realone
                }
            }
            return result;
        });
    },
    getUrl: function () {
        let url = pm.request.url.getRaw();
        url = this.interpolateVariable(url)
        let {
            Url
        } = require('postman-collection')
        return new Url(url);
    }
}
```

**Comment by jankuzniak** [comment] 2019-03-27 14:05
@codenirvana thanks for the walkaround! Still voting for the official support for this one 👍

**Comment by codenirvana** [comment] 2019-04-03 09:15
@ihipop There's another workaround for this:
```javascript
const {Property, Url} = require('postman-collection');

let resolvedUrl = Property.replaceSubstitutions(pm.request.url.toJSON(), pm.variables.toObject()),
    newUrl = new Url(resolvedUrl);

console.log(newUrl.getPath())
```

**Comment by ihipop** [comment] 2019-04-03 13:01
> @ihipop There's another workaround for this:
> 
> ```js
> const {Property, Url} = require('postman-collection');
> 
> let resolvedUrl = Property.replaceSubstitutions(pm.request.url.toJSON(), pm.variables.toObject()),
>     newUrl = new Url(resolvedUrl);
> 
> console.log(newUrl.getPath())
> ```

Any doc about `Substitutor.box`?

**Comment by kirya-dev** [comment] 2020-08-25 10:56
You can just 
```JS
const pathInfo = pm.variables.replaceIn(pm.request.url.getPath());
```

**Comment by venkateshellaboina** [comment] 2020-08-26 12:10
If your Path also depends on variables 

Example Request : **{{baseUrl}}/info**,  where _baseUrl_ = `http://facebook.com/user`.  

After resolving variables, the URL will be `http://facebook.com/user/info`.

You can use this function to get the path:

```
function getUrlPath() {
    let url = pm.variables.replaceIn(pm.request.url).toString(); /

    if (url.includes("http://"))
        url = url.replace("http://", '');
    else
        url = url.replace("https://", '');

    let path;
    if (url.includes('?'))
        path = url.substring(url.indexOf('/'), url.indexOf('?'));
    else
        path = url.substring(url.indexOf('/'), url.length);

    return path;
}
```
output: /user/info

**Comment by Iceyyu123** [comment] 2021-04-06 16:30
if write path variable ':<path variable>' in the request, the ':<path variable>' is not resolved.
