### ISSUE TITLE
Regression Issue Introduced Between Postman v5.1.2 and Postman v5.1.3

### ISSUE THREAD

**Issue by dkedmondson** [a85/POSTMan-Chrome-Extension#3378] opened 2017-08-12 20:09 UTC
## App Details:

```
Postman for Windows
Version 5.1.3
win32 6.1.7601 / x64
```

## Issue Report:
 1. The Postman v5.1.2 "Run Collection" feature did not previously pass the variable name {{First_Name}} in a POST message's JSON Payload when the .csv file did not contain a value for the variable, it merely sent an empty value... 
 2. The Postman v5.1.3 "Run Collection" feature now passes the variable name {{First_Name}} in a POST message's JSON Payload when the .csv file does not contain a value for the variable...

POST Message Payload Sent:
{
    "Home_Campus_Code": "{{Home_Campus_Code}}",
    "Host_Campus_Code": "{{Host_Campus_Code}}",
    "Academic_Term": "{{Academic_Term}}",
    "Academic_Year": "{{Academic_Year}}",
    "Enrollment_Status": "{{Enrollment_Status}}",
    "Status_Change_Reason": "{{Status_Change_Reason}}",
    "Section_Resource_Number": "{{Section_Resource_Number}}",
    "Course_Subject_Area_Abbrev": "{{Course_Subject_Area_Abbrev}}",
    "Course_Catalog_Number": "{{Course_Catalog_Number}}",
    "Grade_Preference": "{{Grade_Preference}}",
    "Campus_User_Identifier": "{{Campus_User_Identifier}}",
    "Eppn": "{{Eppn}}",
    "Last_Name": "{{Last_Name}}",
    "First_Name": "{{First_Name}}",
    "Email": "{{Email}}"
}

Collection Run .CSV File:
testReason,requestID,transactionID,Home_Campus_Code,Host_Campus_Code,Academic_Term,Academic_Year,Enrollment_Status,Status_Change_Reason,Section_Resource_Number,Course_Subject_Area_Abbrev,Course_Catalog_Number,Grade_Preference,Campus_User_Identifier,Eppn,Last_Name,First_Name,Email,reponseCode
MissingFirstName,10000000-0000-0000-0000-000000000514,10000000-0000-0000-0000-000000000514,UCSD,UCSD,Fall,2016,Enrolled,Student Request Enrolled,A00,AIP,158,Pass/No Pass,xxx,xxx,Alexander,,xxx,400

POST Message Payload Received:
{
    "Home_Campus_Code": "UCSD",
    "Host_Campus_Code": "UCSD",
    "Academic_Term": "Fall",
    "Academic_Year": "2016",
    "Enrollment_Status": "Enrolled",
    "Status_Change_Reason": "Student Request Enrolled",
    "Section_Resource_Number": "A00",
    "Course_Subject_Area_Abbrev": "AIP",
    "Course_Catalog_Number": "158",
    "Grade_Preference": "Pass/No Pass",
    "Campus_User_Identifier": "xxx"
    "Eppn": "xxx",
    "Last_Name": "Alexander",
    "First_Name": "{{First_Name}}",
    "Email": "xxx"
}

**Comment by sivcan** [comment] 2018-08-01 10:32
@dkedmondson This is the expected behavior because replacing an unresolved variable with an empty string isn't quite right.

I'll be closing this issue.

**Closed as completed by sivcan** 2018-08-01 10:32 UTC
Labels: bug
