### ISSUE TITLE
Different custom logos for different collection documentations

### ISSUE THREAD

**Issue by wywarren** [a85/POSTMan-Chrome-Extension#8484] opened 2020-05-14 19:54 UTC
We currently develop APIs for different clients that don't necessarily use postman but need to have their documentation up for their developers and 3rd party developers but wish to have their own logo on the collection.

A proposed solution is to have an image/icon uploader for each published collection (perhaps only available to paid users) to have it override the team profile icon.

The alternative is to create a bunch of different accounts for every client and change the profile photo on each of them, but managing that would become cumbersome.

**Comment by chrisivens** [comment] 2020-06-15 16:29
Having a logo per team seems particularly short-sighted when many teams produce multiple products - often with their own logo/branding.

**Comment by Raja-Simha** [comment] 2020-12-14 12:37
Duplicate of #3632

**Closed as completed by Raja-Simha** 2020-12-14 12:37 UTC
Labels: feature, product/documentation
