### ISSUE TITLE
Requests in Collection Getting Re-Ordered

### ISSUE THREAD

**Issue by aviray48** [a85/POSTMan-Chrome-Extension#4992] opened 2018-08-08 17:48 UTC
**Requests in Collection Getting Re-Ordered**
- When duplicating a Collection the ordering of the Requests in the duplicated Collection is being changed.
- When duplicating a Requests in a Collection the entire collection is reordered.

**To Reproduce**
1. Right click on a Collection
2. Click Duplicate
3. Open the duplicated Collection
4. Note that the order is different from the original Collection
5. Right click on a Request
2. Click Duplicate
3. Note that the order of the Collection has changed

**Expected behavior**
The order  of the Collection would not change due to a duplication of Collection or a Request

**App information (please complete the following information):**
 - App Type [e.g. Native App]
 - Postman Version [e.g. 6.2.2]
 - OS: [Windows 7]

**Comment by kamalaknn** [comment] 2018-08-09 04:29
Hey @aviray48 

I've tried the steps you've provided, but couldn't reproduce this behavior. Are you seeing this for all collections consistently or is it particular to a specific collection?

Do you see any errors in your devtools? Can you attach the logs from `View -> Developer -> Show DevTools(Current View)` and `View -> Developer -> Show DevTools(Shared)`?

**Comment by aviray48** [comment] 2018-08-12 03:58
Dear Kamalakannan,

Thanks for responding. It seems the behavior is occurring on once per
folder, i.e. if I copy a Request or a folder once, it gets re-ordered, but
if I put the folder back in order and copy a Request or a folder a second
time, the order sticks. Now that I think about it, I wonder if the issue
has to do with import/export. I think the issue started when I exported my
requests from Canary, then imported them to "Regular". Is it possible that
on an export or import all the order information is lost or removed? Thanks
again for looking into this, and keep up the good work.

Sincerely,

Avi

**Comment by kamalaknn** [comment] 2018-08-12 09:01
Hi @aviray48 

I just tried exporting a collection from the latest Canary app and imported in the Stable channel. I see the order is **maintained correctly**. Are you consistently seeing this on any particular collection? Can you provide a screen capture or a reproduceable collection file? It will help us fast track triaging this issue?

**Comment by aviray48** [comment] 2018-08-13 13:55
Dear Kamalakannan,

For now, I cannot seem to reproduce the issue. Since it seems like this is
something that might only be with my computer, I don't want to trouble you
to continue looking at this. If I can track down what caused this, I will
reach back out to you. Once again, thank you for following up.

Avi

**Comment by kamalaknn** [comment] 2018-08-14 10:18
Hey @aviray48 

Sure, no problem.

I'm closing this issue for now. Feel free to reopen this issue if this happens again.

**Closed as completed by kamalaknn** 2018-08-14 10:18 UTC
Labels: bug

**Comment by aviray48** [comment] 2018-08-14 15:42
Sounds good, thanks. - Avi
