### ISSUE TITLE
Unable to import OpenAPI file with Postman v.10.14

### ISSUE THREAD

**Issue by vgarmash** [a85/POSTMan-Chrome-Extension#12066] opened 2023-06-01 21:04 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am trying to import the OpenAPI file, but Postman quietly does nothing. I tried to provide URL or file contents - both ways no result.

File contents:
[OpenAPI3.json.txt](https://github.com/postmanlabs/postman-app-support/files/11629748/OpenAPI3.json.txt)

### Steps To Reproduce

1. Open Postman workspace
2. Click Import button
3. Paste the following file contents: [OpenAPI3.json.txt](https://github.com/postmanlabs/postman-app-support/files/11629748/OpenAPI3.json.txt)

No collection being created, no erros being displayed.

### Operating System

Windows 11

### Postman Version

10.14.7

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by akshaydeo** [comment] 2023-06-02 04:13
Hi @vgarmash thanks for reporting this issue. When I tried to validate this schema using https://apitools.dev/swagger-parser/online/#, it gives a couple of validation errors. Could you fix them and retry importing. 

We will look into why it's silently failing the import. cc @VShingala

**Comment by VShingala** [comment] 2023-06-02 06:36
@vgarmash Just to confirm, Are you seeing this Import modal mentioning the API name, and which Import option to choose? Or there's no feedback at all after pasting?

Below is my import experience with the definition you shared.

https://github.com/postmanlabs/postman-app-support/assets/16756296/225f9607-582b-4dc2-8c9c-083b8bf627a3

**Comment by vgarmash** [comment] 2023-06-02 07:43
> @vgarmash Just to confirm, Are you seeing this Import modal mentioning the API name, and which Import option to choose? Or there's no feedback at all after pasting?
> 
> Below is my import experience with the definition you shared.
> 
>  Screen.Recording.2023-06-02.at.12.02.46.PM.mov

@VShingala Yes, you right the API is being created. Although the collection is not being created which is my main feature of the Postman that I use to manually test my APIs. My workflow is the following: 

1. I modify my API using String Data Rest and other Spring frameworks, 
2. generate OpenAPI spec using [Spring Doc ](https://springdoc.org/) and import it into Postman
3. Postman generates the Collection with all URLs I have in my spec
4. I configure pre-script for collection for authentication and start manually sending requests to my API server

Now the step 3 fails, and Postman don't give any warnings or errors so I can fix the specification file or something. I will try to fix those validation errors that @akshaydeo is talking about but I doubt that it is the reason of the issue. The operation with the validation error exists in my spec for months and Postman imported collection properly. In any case if there is a problem with the OpenAPI file then Postman should display the error properly.

**Comment by VShingala** [comment] 2023-06-02 09:02
@vgarmash Yeah, there is an issue with the way workspace collection is getting generated in some of the cases. I was able to reproduce the same. We'll start working on the fix for this and add update here once fixed.

Meanwhile, You can do following steps to get generated collection under `Collections` tab and continue with your workflow for time being.

1. As shown in video, Importing as API will create collection under the corresponding API.
2. You can go to collection under API that got imported and click on three dot menu on that collection.
3. Click on `Copy to collections` button. (this will create a collection under `Collections`, same as importing Postman collection only.)

<img width="564" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/16756296/eaeaeb4f-14c5-498f-b099-8e7ce7386d7e">

**Comment by vgarmash** [comment] 2023-06-05 20:02
> Hi @vgarmash thanks for reporting this issue. When I tried to validate this schema using https://apitools.dev/swagger-parser/online/#, it gives a couple of validation errors. Could you fix them and retry importing.

@akshaydeo 
I have fixed validation errors, but the Postman behaves the same. Here is the new version: 
[OpenAPI3-valid.json.txt](https://github.com/postmanlabs/postman-app-support/files/11657183/OpenAPI3-valid.json.txt)

@VShingala Your workaround works, I was able to create a collection using this method. By the way I noticed that the import only works if I paste the file contents. If I just provide a link as it worked in the past version of Postman, then import not happening at all.

**Comment by VShingala** [comment] 2023-06-06 05:53
@vgarmash Thanks for providing the new version with the fixes. We've confirmed that this definition will work with the fix we've done which will be available with the next Postman App release (v10.15).

Also, could you share more details how URL imports are not working for you? i.e. What's the behaviour like? I've mentioned the import of link mentioned by you below in my case.


https://github.com/postmanlabs/postman-app-support/assets/16756296/f67af579-ebd3-4f56-9360-97be24a1ec2c

**Comment by vgarmash** [comment] 2023-06-06 20:31
@VShingala Try to import this: https://[portal.heritage-cares.dev/api/v1/v3/api-docs](https://portal.heritage-cares.dev/api/v1/v3/api-docs)

**Comment by VShingala** [comment] 2023-06-07 05:13
@vgarmash Provided link also seems to be working fine on Windows 11 Postman App.


https://github.com/postmanlabs/postman-app-support/assets/16756296/b4a4d59e-e48c-4b3b-874d-4d7eb652ff32

**Comment by vgarmash** [comment] 2023-06-07 07:16
> @vgarmash Provided link also seems to be working fine on Windows 11 Postman App.
> 
>  Screen.Recording.2023-06-07.at.10.37.08.AM.mov

@VShingala 

Please define "working". Yes, somethings happening, the waiting indicator shows that something happening. Although nothing happens in 1, in 3 and even 5 minutes. The indicator just stays there forever. Please try again on empty Postman workspace.

For me "working" means that the waiting indicator disappears (or shows "work completed" state) and new collection is being created.

**Comment by VShingala** [comment] 2023-06-07 07:26
@vgarmash As already mentioned in the previous comment, this particular definition is having an issue with new postman versions and we'll be fixing it soon with the upcoming release.

By working I meant that import flow is able to detect the definition and import starts. Even as of now, selecting `Import as API` should create API and collection under and you can duplicate it to Workspace as suggested earlier.

> @vgarmash Yeah, there is an issue with the way workspace collection is getting generated in some of the cases. I was able to reproduce the same. We'll start working on the fix for this and add update here once fixed.

> Meanwhile, You can do following steps to get generated collection under Collections tab and continue with your workflow for time being.

**Comment by vgarmash** [comment] 2023-07-25 13:53
@VShingala Hello. I retested the import with Postman 10.16 - it works properly now. You can close the ticket.

**Comment by VShingala** [comment] 2023-07-25 14:01
@vgarmash Thanks for the confirmation of the fix! 🚀

**Closed as completed by VShingala** 2023-07-25 14:01 UTC
Labels: bug, product/importers
