### ISSUE TITLE
Postman hangs on launch: MacSierra OS High

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#4940] opened 2018-08-01 06:26 UTC
1. The issue we’re experiencing happens after installing Postman on a MacBook Pro A1707; the program seems to hang. We’ve already tried clearing the local app cache and reinstalling the program with no luck. We have also tried and older version of the software with the same result. 

2. Also ran the app via command line. Stuck on the loading view. ORM did initialize successfully. 

3. Tried again. Starting with clearing the cache. It did took me to the Sign up/Sign In page. Got stuck on the loading screen after Sign In.

**Comment by csm-noahjahn** [comment] 2018-08-07 20:33
Hello, do you have any update on this issue?

**Comment by numaanashraf** [comment] 2018-08-08 06:45
@csm-noahjahn Could you open Postman's DevTools via (Menu > View > Show DevTools (Current View)) at let us know if you see any errors there?

**Comment by csm-noahjahn** [comment] 2018-08-08 16:47
Hi @numaanashraf Attached are some of the screenshots of the result we get when launching Postman.

When opening Postman from Applications on MacOS, we receive the following result:
![image](https://user-images.githubusercontent.com/41996558/43851059-a89ed010-9b07-11e8-81b3-c579dee9915b.png)

When opening Postman from terminal we see the following result:
![image](https://user-images.githubusercontent.com/41996558/43851103-c0b66d48-9b07-11e8-8a18-8620f14dbd00.png)
And it just hangs at:
![image](https://user-images.githubusercontent.com/41996558/43851132-d3056eea-9b07-11e8-9194-dc4826ee10a8.png)

When opening Postman's DevTools via Show DevTools (Current View), we do not see any error:
![image](https://user-images.githubusercontent.com/41996558/43851169-ebf9830a-9b07-11e8-835a-4b00552924b4.png)

When opening Postman's DevTools via Show DevTools (Current Shell), we saw the following error:
![image](https://user-images.githubusercontent.com/41996558/43851553-fbc67206-9b08-11e8-8776-69c854e50db1.png)

Let me know of further action we might need to take. Thanks for the help!

**Comment by csm-noahjahn** [comment] 2018-08-16 13:41
Hello, 
Do you have an update on this issue? Is there any more information you need from me?
Thanks!

**Comment by csm-noahjahn** [comment] 2018-08-24 18:51
Hello,
Do you have an update on this issue? Is there any more information you need from me?
Thanks!

**Comment by csm-noahjahn** [comment] 2018-10-10 18:05
Hi,
Is there an update on this issue?
Thank you.

**Comment by csm-noahjahn** [comment] 2018-11-26 14:50
We recently reset the MacBook Pro we were experiencing this issue on and it seems to have resolved the issue.

**Comment by numaanashraf** [comment] 2019-03-18 11:33
@csm-noahjahn Thanks for letting us know. This seemed like a device specific issue and we are still unable to reproduce this. I'm closing this issue for now - don't hesitate to let us know if you are still facing this issue.

**Closed as completed by numaanashraf** 2019-03-18 11:33 UTC
Labels: bug, launch
