### ISSUE TITLE
[Feature Request] Add Root and Intermediary CA

### ISSUE THREAD

**Issue by kerednai** [a85/POSTMan-Chrome-Extension#3152] opened 2017-06-12 12:59 UTC
The native postman application should allow me to add a trusted root and intermediary CA.
I would like to be able to use postman to test an internal API which presents a cert signed by a local CA. In order to do this I need to add the local CA root and intermediary CA. The CA in this example is the company I work for. I know I can turn off SSL verification, but I don't want to do that. 
FYI - I also need to test mutual SSL and to do that I need SSL verification turned on.

Version info:
Postman for Windows
Version 5.0.0
win32 6.1.7601 / x64

**Comment by numaanashraf** [comment] 2017-06-12 15:05
Thanks for the suggestion @kerednai. We'll update here if and when we add this to our roadmap. You can view the current roadmap at https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers.

**Comment by linuxchata** [comment] 2019-02-15 07:34
Any updates on this issue?

**Comment by numaanashraf** [comment] 2019-02-16 13:32
@linuxchata @kerednai We are tracking this issue at #3290. Please follow that thread for updates.

**Comment by numaanashraf** [comment] 2019-02-16 13:32
Duplicate of #3290

**Closed as completed by numaanashraf** 2019-02-16 13:32 UTC
Labels: feature, Certificate, duplicate
