### ISSUE TITLE
Windows Store

### ISSUE THREAD

**Issue by vanillajonathan** [a85/POSTMan-Chrome-Extension#4573] opened 2018-05-19 10:22 UTC
Please put Postman in the Windows Store.

This would make it easy find, install and keep up-to-date with the latest updates.

As a UWP app it could also be installed on Windows 10 in S Mode.

**Comment by sivcan** [comment] 2018-05-21 07:44
@vanillajonathan - The app already has a built-in system to auto-update itself.
The installation process already involves no complications around it if you download and install it once.
Rest for future versions is handled by the auto-updater.

We'll look into the use cases for this.
Thanks for the Windows 10 S mode suggestion.

**Comment by vanillajonathan** [comment] 2018-05-21 08:05
With UWP the app is more secure since its sandboxed, it properly uninstalls without leaving anything remaining, the UI is scaleable across devices of different sizes such as phones, tablets, PC and TV. You can do in-app purchases and volume licensing, etc.

https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide

**Comment by a85** [comment] 2019-05-05 20:37
Closing as duplicate of #4072

**Closed as completed by a85** 2019-05-05 20:37 UTC
Labels: feature, installation
