### ISSUE TITLE
Unable to open request in a new tab

### ISSUE THREAD

**Issue by schadsey** [a85/POSTMan-Chrome-Extension#9742] opened 2021-03-17 15:00 UTC
Postman v8.0.7 on Linux

When a request is open in a tab, I can no longer open another copy of that request in a new tab. This was possible in previous versions (whatever the version was before the recent UI update). What I've observed:
* Clicking the request in the collection will always go to the tab for that request (expected)
* Right-click the request > Open in tab: new tab not opened. Tab containing the request is focused.
* Enable setting "Always open requests in new tab": clicking a request goes to the tab with that request, and does not open a new tab

**Comment by DannyDainton** [comment] 2021-03-17 15:44
Hey @schadsey 

Does right-clicking on the request tab in view, not give you the option to `Duplicate Tab`?

**Comment by schadsey** [comment] 2021-03-17 18:16
@DannyDainton : yes, `Duplicate Tab` is available and provides the functionality that I'm looking for, thanks. Previously I was using a right-click option on the request in the collection (my report didn't mention that), but I can start using this method.

**Comment by DannyDainton** [comment] 2021-03-17 18:18
That's great. Some items have moved around/changed in the new V8 UI update. 

Going to close this issue out as you have found the solution.

**Closed as completed by DannyDainton** 2021-03-17 18:18 UTC

**Comment by mtudor** [comment] 2021-03-20 14:38
Hi guys, apologies for posting on a closed issue but I'm not sure this is actually fixed (at least for my use case).

I see the same behaviour as @DannyDainton - i.e. right-clicking the request and choosing "Open In Tab" will open the request if it is not already open, otherwise it just focuses the existing tab.

Right-clicking the request tab header and choosing "Duplicate" does create a new instance of the tab BUT *the tab is duplicated in its current state, with any unsaved changes being duplicated also*.  That is what I would expect.

The functionality that is missing (as far as I can see) is that I cannot open the saved version of the tab, as I used to be able to using the "Open in *New* Tab" functionality in previous versions of Postman.  In fact, as far as I can see there is no way to get back to the saved version without closing ALL open instances of the request first.

Any thoughts, workarounds etc. welcomed :)

**Comment by Adri-LM** [comment] 2021-05-28 09:48
Hey, for me the problem isn't solved either.

Duplicating works great, but again it duplicates changes, so there's no way to open your original request without :
- starting **from** your current changes
or
- **loosing** all of your current changes (And if you already have 3-4 or more tabs open for the same request, it gets very frustrating)

Also, I don't really see the point of "Open in Tab" tbh as it seems to do exactly the same as just left clicking on the request, maybe I missed something?
