### ISSUE TITLE
OAuth 1.0 Header Auto Gen is broken

### ISSUE THREAD

**Issue by johnnykang** [a85/POSTMan-Chrome-Extension#4852] opened 2018-07-19 12:12 UTC
## App Details:

```
Postman for Mac
Version 6.1.4
OS X 17.7.0 / x64
```

## Issue Report:
1. this issue happens recently.
1. The OAuth 1.0 Header autogen value is broken.
1. 

```
"Authorization": "OAuth oauth_consumer_key=\\\"true\\\",oauth_token=\\\"true\\\",oauth_signature_method=\\\"HMAC-SHA1\\\",oauth_timestamp=\\\"1532002045\\\",oauth_nonce=\\\"JPLqLaXcexz\\\",oauth_version=\\\"1.0\\\",oauth_signature=\\\"HN1EDxQzoIDYtUihd9LrxNDRsNI%3D\\\"",
    "Cache-Control": "no-cache",
    "Postman-Token": "ac665bd9-a78a-4178-baf4-02bb025414e2"
```

the oauth_consumer_key and oauth_token has generated values of "true" although I have correctly put in the values in the OAuth ConsumerKey and Secret fields. 

## How to replicate
1. Select OAuth 1.0 as the Authorization type.
1. Put in any values in the Consumer Key, Consumer Secret, Access Token, Token Secret.
1. Put in any dummy URL in the url
1. Select Add authorization data to Request Headers
1. Click on Preview Request or Send
1. Inspect the Headers field - Authorization
1. The `oauth_consumer_key="true",oauth_token="true"` is wrong. It can't be the value of `true`.

**Comment by johnnykang** [comment] 2018-07-20 02:09
It looks like the New Request must be part of the collections to have the Authorization Header populated correctly. 

Close for now.

**Comment by johnnykang** [comment] 2018-07-23 21:59
It looks like if i sign out my current account from Postman, and use a new login, the above works fine !!!

what the ...

did the migration broke my workspace?

**Comment by harryi3t** [comment] 2018-08-01 09:12
@johnnykang Were you using hard-coded values or variables for the Oauth-1 parameters?
Also, after you signed-in did it ever happen again?

**Comment by johnnykang** [comment] 2018-08-01 09:17
hi, 

i tried both hard-coded values and variables. They all have the same issues as mentioned above. I signed out, and resigned in, same issues as well. 

i have to kill / close my account. Thus, I export all the configurations to a file, close my account, re-sign up , import all configurations, then everything back to normal working state again.

It is not longer happening because i have done the mentioned steps. 

I am pretty sure the configuration was a bit screwed up. But it is not longer an issue after I've took the above measurement.

I am happy to close this issue if it is too hard to find/fix.

**Comment by harryi3t** [comment] 2018-08-01 12:16
@johnnykang Thanks for the quick reply.
I am closing this issue, if this happens in future please reopen the issue with the steps to reproduce it.

**Comment by PkKingX11** [comment] 2018-08-16 13:11
This needs to be fixed it's so annoying, it's basically unusable...

**Comment by Hibbem** [comment] 2018-08-27 11:36
Signed out and in, same problem here..
How is it even possible that the unit tests did not cover this?

**Comment by dmestetskiy** [comment] 2018-10-03 15:34
I am having the same issue. It seems changing the value does nothing. postman keeps it oauth_consumer_key=\"true\". I have the latest release.

**Comment by eric-martin** [comment] 2018-10-03 20:34
Same issue here. Postman v6.3.0 on Windows. No account. 

This was working fine until this afternoon. Now all new oauth 1.x requests have the true/true problem.

**Comment by tejkweku** [comment] 2018-10-09 13:38
I have had this issue since downloading the Debian package from `getpostman.com`.
Specs: 

- Postman for Linux
- Version 6.3.0
- linux 4.9.0-8-amd64 / x64
- No account

I have cracked my head for more than two (2) weeks only to use a different REST client and find this bug around for OAuth 1.x request.

**Comment by eastwood** [comment] 2018-11-13 04:30
The same here, updated to latest mac version and still receiving this issue :(

**Comment by johnnykang** [comment] 2018-11-13 04:34
@harryi3t perhaps it is time to reopen this issue and investigate further?

**Comment by harryi3t** [comment] 2018-11-14 05:19
@johnnykang Sure
I was not able to reproduce this the last time. If possible, could someone post a screen recording? That would really help us debug and fix this issue.

**Comment by dmestetskiy** [comment] 2018-11-19 21:40
@harryi3t I don't have a video. but what I am experiencing is this:

1. Existing request from a collection.
2. Send said request, it fails with the old values(possibly worked before, not sure)
3. Update OAuth value with proper credentials and send it again. Looking at "Code", new OAuth values are not being used but the old request values are. 

It appears to be an issue with caching or something where changing the values of the request does nothing. Maybe because it is part of the collection?

Maybe someone else can expand on this.

**Comment by tejkweku** [comment] 2018-11-21 13:50
This is how the issue manifests on my system

![temp](https://user-images.githubusercontent.com/7029109/48845353-30889400-ed94-11e8-9254-cf5248905ade.gif)

Sorry for the poor quality. Github does not permit the upload of video files so I had to convert the video into a gif.

**Comment by harryi3t** [comment] 2018-11-22 11:47
@tej-kweku Can you also post the screenshots of the following:
1. After sending the request, open the headers tab
2. Open Postman Console, clear the logs, send the request, expand all the sections in the console

**Comment by tejkweku** [comment] 2018-11-22 13:07
> @tej-kweku Can you also post the screenshots of the following:
> 
> 1. After sending the request, open the headers tab
> 2. Open Postman Console, clear the logs, send the request, expand all the sections in the console

![postman_oauth_issue_reboot_1](https://user-images.githubusercontent.com/7029109/48904797-778b8d80-ee57-11e8-924e-12ad2aca8180.gif)

**Comment by imyaro** [comment] 2019-06-04 09:54
Any updates?

**Comment by vikiCoder** [comment] 2019-12-26 12:53
Hi everyone,

We are unable to reproduce this issue in the latest version of the Postman app (v7.14.0). Here are the steps I tried:

1. Open a new tab in the requester window
2. Select OAuth 1.0 as the Authorization type.
3. Put in any values in the Consumer Key, Consumer Secret, Access Token, Token Secret.
4. Put in any dummy URL in the url-bar
5. Select Add authorization data to Request Headers
6. Click on Preview Request: The Authorization header is as expected with all fields having proper value
7. Click on Send Request: Again, the Authorization header is as expected
8. Save the request to a collection.
9. Close the request tab and restart the Postman app.
10. Open the saved request and send the request again: Still, the Authorization header is as expected
11. Repeat steps 1 to 10 for Windows, Ubuntu and macOS

However,  we have seen this kind of issues emerging because of the dependencies not being installed properly while updating the Postman app. We have fixed that issue, so I have a feeling that this issue might be fixed along with that.

A lot of time has passed since this issue was created so please let us know if anyone is still facing this issue in the latest version of the Postman app(v7.14.0).

**Closed as completed** 2020-01-07 09:13 UTC
Labels: bug, Auth, product/runtime, blocked/need-repro

**Comment by Himesan12** [comment] 2024-11-18 14:01
Still broken with version 11.20. I can't get the authorization header details to be picked up. I'm getting an error stating no auth headed.

Any fixes or steps to fix this issue please.
