### ISSUE TITLE
CircularJSON is  in maintenance only, flatted is its successor. Error while installing Newman

### ISSUE THREAD

**Issue by msbhalerao** [a85/POSTMan-Chrome-Extension#5981] opened 2019-02-25 17:37 UTC
I was trying to install the Newman for generating postman results reports.
I tried with cmd ` npm install -g newman ` and it has given me error as 
`npm WARN deprecated circular-json@0.5.5: CircularJSON is in maintenance only, flatted is its successor.`
`C:\Users\mbhalerao\AppData\Roaming\npm\newman ->`
`C:\Users\mbhalerao\AppData\Roaming\npm\node_modules\newman\bin\newman.js`
`+ newman@4.4.0`

I also tried to clear cache `npm cache clean --force`  but no luck. 

Thanks

**Comment by kunagpal** [comment] 2019-02-25 17:58
Duplicate of https://github.com/postmanlabs/newman/issues/1908

**Closed as completed by kunagpal** 2019-02-25 17:58 UTC
Labels: duplicate, newman
