### ISSUE TITLE
AWS Signature Mismatched Calculation

### ISSUE THREAD

**Issue by nwayve** [a85/POSTMan-Chrome-Extension#1663] opened 2016-01-14 22:10 UTC
When making requests to AWS resources using the `AWS Signature` authorization Access Key and Secret Key, this error message is returned from AWS:  

`{
  "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'GET\n/my/resource\nqParam=qValue\ncontent-type:application/x-www-form-urlencoded\nhost:xxxxxxxxxx.service.region.amazonaws.com\nx-amz-date:20160114T220540Z\n\ncontent-type;host;x-amz-date\ne3b_____________2b855'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20160114T220540Z\n20160114/region/service/aws4_request\na59c9_____________fc623f'\n"
}`

If I remove the query string from the request, the request goes through fine.

**Comment by abhijitkane** [comment] 2016-01-15 07:39
That's odd - this hasn't been reported earlier. Is the AWS region and Service Name set correctly? We're able to make requests to one of our services using the AWS helper.

**Comment by nwayve** [comment] 2016-01-15 15:41
That's the interesting thing, I don't need to set the `AWS Region` or `Service Name` fields.  I've tried having them set and not set, and the result is the same.  The only reason I thought about trying them without those fields is because in AWS' API Gateway console, select Stages, there's an Export tab with an option to export the JSON config to import the endpoints into Postman (which is super sweet BTW).  When that's imported in, it doesn't have any values added to the aforementioned fields.

A co-worker was trying it with one of his endpoints that didn't have a query string and was getting through.  That's when I realized the issue.  Tried it without the query string and it worked.

**Comment by sanmarco** [comment] 2016-01-15 17:34
This might be a different issue, but I'm having the same error when I use an environment variable for the x-amz-security-token header. If I set the value for the x-amz-security-token explicitly (without using a variable) in the header than the request succeeds. It looks as if the signature was built before replacing the variables.

**Comment by abhijitkane** [comment] 2016-01-15 18:08
@czardoz Any opinion here?

**Comment by czardoz** [comment] 2016-01-15 18:10
@sanmarco, does your request contain query parameters too?

**Comment by sanmarco** [comment] 2016-01-15 18:12
No it doesn't have query params

**Comment by czardoz** [comment] 2016-01-15 18:15
@sanmarco, can you ensure that your request does not contain the `x-amz-date` and `Authorization` headers before you click on send?

It can mess with the signature calculation :)

**Comment by sanmarco** [comment] 2016-01-15 18:17
Yes, I noticed that. I have to delete those two headers before every request. But it doesn't solve the issue.

**Comment by nwayve** [comment] 2016-01-15 18:18
I also ensure that I clear those headers before sending.

**Comment by sanmarco** [comment] 2016-01-15 18:25
So, to clarify, the problem I'm having is that I'm not able to use variables for those headers that are used in the signature. In my case they are: SignedHeaders=content-type;host;x-amz-date;x-amz-security-token;x-auth0-jwt. I would need a variable for the x-amz-security-token since it has an expiration.

**Comment by czardoz** [comment] 2016-01-15 18:25
Okay, I'll check this out further. Which AWS services are you trying to make requests to? (Will help me reproduce)

**Comment by nwayve** [comment] 2016-01-15 18:26
I'm specifically making requests to custom API Gateway endpoints (`execute-api` service).

**Comment by sanmarco** [comment] 2016-01-15 18:27
same here, thanks.

**Comment by czardoz** [comment] 2016-01-15 18:28
Cool, I'll update this thread after investigating a bit more.

**Comment by czardoz** [comment] 2016-01-19 08:05
I was able to reproduce this.. We'll fix it in the next version :+1:

**Comment by sanmarco** [comment] 2016-01-19 14:54
Awesome news! Thanks for the update.

**Comment by abhijitkane** [comment] 2016-01-26 08:25
This fix has been included in v3.2.13. @sanmarco can you confirm?

**Comment by nwayve** [comment] 2016-01-26 14:54
I just tried this in version 3.2.13 and it works with query string parameters now.  :+1:
Thanks @czardoz :smile:

**Comment by sanmarco** [comment] 2016-01-26 17:40
@abhijitkane I'm still having the same issue when using environmental variables in the header

**Comment by abhijitkane** [comment] 2016-01-26 18:01
@czardoz

**Comment by kams-mash** [comment] 2016-03-05 16:04
@abhijitkane, @czardoz - I'm seeing the same issue as @sanmarco (i.e. signature mismatch when using env. var in header). This started happening since 4.0.1 for me.

I'm using AWS Auth, and when I have "x-amz-security-token" header value as environment var then the request fails with signature mismatch error response from AWS, but if I substitute the environment var with the actual session token value, then it works.

**Comment by abhijitkane** [comment] 2016-03-06 10:23
@czardoz Will your pull-request fix this?

**Comment by czardoz** [comment] 2016-03-06 12:02
It should, unless it's some other issue

**Comment by czardoz** [comment] 2016-03-06 12:03
My fixes will ensure that environment variables are substituted, but some AWS services require special headers to be added etc. Those cases will require better handling.

**Comment by abhijitkane** [comment] 2016-04-26 11:12
@sanmarco @kams-mash Is this working in v4.1.3?

**Comment by kams-mash** [comment] 2016-04-26 11:59
This  is working now, thank you for the fix.

**Comment by bbronshteyn** [comment] 2016-08-02 21:59
I am seeing same issue pop up in 4.5.0. Funny thing if I generate code for cUrl or Shell cUrl the generated code has correct signature and requests go through.

**Comment by kabilanvk** [comment] 2016-08-04 20:18
I see the same issue 4.4.3 version. Here is my error message.
{
  "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/int/users\n\ncontent-length:66\ncontent-type:application/json\nhost:s5fzhotuo9.execute-api.us-east-1.amazonaws.com\nx-amz-date:20160804T201218Z\nx-api-key:bkayZOMvuy8aZOhIgxq94K9Oe7Y70Hw55\n\ncontent-length;content-type;host;x-amz-date;x-api-key\n11701599565568d8c0bdf7eb1a7638024ae2a9439451921de98b8448126b0700'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20160804T201218Z\n20160804/us-east-1/execute-api/aws4_request\n20cfc19399d778f4ba7476adb5f04c3c5d9d28dd2445e811647bec1667c6b68c'\n"
}

**Comment by dennisoverbeeke** [comment] 2016-08-17 09:42
I am having this issue while trying to sign a request to Cognito IDP... 

```
{
  "__type": "InvalidSignatureException",
  "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/\n\ncontent-length:1772\ncontent-type:application/x-amz-json-1.1\nhost:cognito-idp.eu-west-1.amazonaws.com\nx-amz-date:20160817T094057Z\nx-amz-target:AWSCognitoIdentityProviderService.AdminInitiateAuth,AWSCognitoIdentityProviderService.AdminInitiateAuth\n\ncontent-length;content-type;host;x-amz-date;x-amz-target\n5434932577f68e96dd23fd3147d2f59431e6138e62231044f4a7b48e09816cba'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20160817T094057Z\n20160817/eu-west-1/cognito-idp/aws4_request\n33afbf397e488ed140809ea88e601226df0aeeac6262d184c8167c39fd50b50c'\n"
}
```

My Authentication (AWS):
![image](https://cloud.githubusercontent.com/assets/16736635/17731892/aeb48d80-646f-11e6-8c88-423bfffd3989.png)

My Headers:
![image](https://cloud.githubusercontent.com/assets/16736635/17731931/d8d4a960-646f-11e6-98bc-21b619df0996.png)

Version 4.6.1

@czardoz : any idea what I am doing wrong?

**Comment by davidfeldi** [comment] 2016-08-21 13:22
@czardoz same here... version 4.6.2 still having this issue.

**Comment by sh1n0b1** [comment] 2016-08-26 00:39
I'm having the same issue. It appears to work under GET request. But it won't work for POST and PUT request. Please fix it asap.

**Comment by tikipatel** [comment] 2016-08-31 02:04
I'm having the same issue... I intercepted with Charles and I see that it's adding the security header twice -- 
![screen shot 2016-08-30 at 10 03 26 pm](https://cloud.githubusercontent.com/assets/1288767/18113427/c61afb38-6efd-11e6-8939-ba5636c7eb85.png)

Edit -- I am able to get around the issue by remove the extra header in the auth headers using breakpoints, but that's just a hinderance in development :(

**Comment by a85** [comment] 2016-09-15 23:19
@shamasis @czardoz What do we need to do to fix this issue?

**Comment by shamasis** [comment] 2016-09-16 06:10
@czardoz is already on it. 😊

**Comment by shamasis** [comment] 2016-09-16 06:10
The app needs a better way to stop adding saved header into the auth.

**Comment by shamasis** [comment] 2016-09-16 10:58
@tikipatel and rest :-),

the change being introduced to fix this will require you to now provide `session token` (one that generates `x-amz-security-token`) as part of the AWS auth helper UI and if you were previously providing it via headers that would not work.

@SamvelRaja - please add to app changelog as a minor breaking change.

**Comment by tikipatel** [comment] 2016-09-21 00:23
Great! @shamasis any insight as to release time for this change?

**Comment by dennisoverbeeke** [comment] 2016-09-28 06:30
When this will be fixed, will it be fixed in Newman automatically? I need support for AWS Sig4 helper in Postman AND Newman for our continuous integration & deployment: we use Postman/Newman to test our AWS API Gateway. We have moved towards Cognito Identity Pools for API Authentication & Authorization and need to sign all of our request with AWS Sig4 (with temporary IAM credentials).

I see that [4.8](https://github.com/postmanlabs/postman-app-support/milestone/10) is due 29th of September, but this issue is not tagged as fixed yet. Any more detailed insight on when this fix will be released?

If I can be of any assistance, please let me know

**Comment by SamvelRaja** [comment] 2016-09-28 06:50
@dennisoverbeeke  Yes it will be available for the Newman as well. We are working on as per the schedule, we will update this thread if any changes happen. Thanks for your valuable consideration.

**Comment by dennisoverbeeke** [comment] 2016-09-28 07:02
@SamvelRaja: thank you for your quick reply, good to hear. Does this mean that this fix will be released tomorrow?

**Comment by czardoz** [comment] 2016-09-28 08:22
@dennisoverbeeke Yes, that's is the plan, unless we hit any hiccups with testing :)

Newman will need to be released in order to support this, and we'll do the release along with the Postman App.

**Comment by dennisoverbeeke** [comment] 2016-09-28 08:36
@czardoz Perfect!

**Comment by dennisoverbeeke** [comment] 2016-10-03 07:35
@SamvelRaja , @czardoz Hi Guys, any news on progress / timelines?

**Comment by dennisoverbeeke** [comment] 2016-10-12 10:53
@SamvelRaja , @czardoz : Any updates?

**Comment by SamvelRaja** [comment] 2016-10-14 13:54
@dennisoverbeeke  Sorry for the delay in the release. The fix went in 4.8.0, can you check the same from your end.

**Comment by dennisoverbeeke** [comment] 2016-10-16 08:40
***\* PLEASE SCROLL DOWN TO UPDATE FIRST ****
***\* ISSUE SOLVED, BUT LEFT MY INFO FOR OTHER NOT TO MAKE THE SAME MISTAKE ****

@SamvelRaja Thanks for your update and the new v4.8.0 Postman (and v3.1.2 Nemman) release. I tried both new versions in my specific case and the update does not seem to have fixed my issue. I first tried the new Newman release in my CI/CD solution but it did not work. Because it is more difficult to debug there I switched to Postman for debugging.

Using the new v4.8.0 Postman I still have the same issue. When trying to call my AWS API Gateway which is secured with IAM credentials (that is why I need the Sigv4 authorization) I still have errors.

Authorization config (vars are correctly loaded):
![image](https://cloud.githubusercontent.com/assets/16736635/19416247/43cee834-938c-11e6-9119-524780db83aa.png)

My header after sending the POST:
![image](https://cloud.githubusercontent.com/assets/16736635/19416324/419e3a22-938e-11e6-93b5-c52662596c41.png)

Authorization header: 
AWS4-HMAC-SHA256 Credential=ASIAIWFE3XX7CS*****_/20161016/eu-central-1/execute-api/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-api-key, Signature=4b204f8408d2c6c362eefe9387b2df88bed7447e1dd39e5bea08a6**_*******

Error retrieving:
"message": "The security token included in the request is invalid."

Now comes the interesting part: when I use the generated cURL code from this exact call everything works fine!

generated cURL:
`curl -X GET -H "x-api-key: 3UkX1NRc5t310k5rrqBna6x3c5hoAJen9B******" -H "x-amz-security-token: AgoGb3JpZ2luE****" -H "Content-Type: application/x-www-form-urlencoded" -H "X-Amz-Date: 20161016T083150Z" -H "Authorization: AWS4-HMAC-SHA256 Credential=ASIAIWFE3XX7CS******/20161016/eu-central-1/execute-api/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-api-key, Signature=4b204f8408d2c6c362eefe9387b2df88bed7447e1dd39e5bea08a6b6bd******" -H "Cache-Control: no-cache" -H "Postman-Token: 93e74922-6357-d266-4819-440b8c395cf8" "https://*****.execute-api.eu-central-1.amazonaws.com/dev/info"`

Must be something different in Postman/Newman executing the request and the actual request from the generated cURL

If you need any additional info or want to do so debugging together, please contact me...

Appreciating your effort in fixing this bug!

---

UPDATE: did some additional debugging.

I just found out about the 'console' function in Postman and tried to do the request again:
![image](https://cloud.githubusercontent.com/assets/16736635/19417762/82e2dcfa-93b5-11e6-9759-8ab09f52e45d.png)

I think the problem is that Postman never includes the 'x-amz-security-token' header in the request? It is defined (see screenshot above) but the console does not show it.

This led me to the fact that I was an idiot and that I did not notice that the new solution in v4.8.0 required an additional parameter in the Authorization especially for this:
![image](https://cloud.githubusercontent.com/assets/16736635/19417786/f68e69b2-93b5-11e6-962f-a4a9e41c9582.png)

If I use it the correct way it al works fine :-)

Thanks guys, will test Newman little bit later <-- works as a charm as well!

**Comment by shamasis** [comment] 2016-10-16 18:35
👍🏼 waiting for your test using Newman before closing it.

**Comment by dennisoverbeeke** [comment] 2016-10-16 18:36
@shamasis : both Postman and Newman work! Case closed,... thanks again

**Comment by shamasis** [comment] 2016-10-16 18:55
That's good to hear. 😊

**Closed as completed by shamasis** 2016-10-16 18:55 UTC
Labels: product/runtime

**Comment by topside844** [comment] 2017-01-19 18:37
I was running into the same issue and found that Postman is not updating the 'Host' header value to match the host where the request was sent, and if that value is different, the signature calculation will fail. 

Simply deleting the 'Host' header and letting it auto-populate again when sending the next request fixed my issue.

For instance, if you select 'Service Name: s3' and send your request to 'BUCKETNAME.s3.amazonaws.com', the Host header is defaulting incorrectly to 's3.amazonaws.com'. By deleting the Host header from the request and resending, it auto-populates the Host header with the correct 'BUCKETNAME.s3.amazonaws.com' value which leads to the correct signature calculation.

**Comment by vinaygoel79** [comment] 2017-07-14 11:17
@nwayve @abhijitkane @sanmarco @czardoz @kams-mash @dennisoverbeeke @kabilanvk @kams-mash @shamasis @sh1n0b1 @SamvelRaja I am facing the same problem. 
I set:-"Access key:- xxxxxxxxxx
         Secrete key:-xxxxxxxxxx
         Aws region:- ap-south-1
         service name:- execute-api"
Can anyone me to solve this problem. Thanks in advance.

while **POST** i get this error
`{
    "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/dms/api/v1/filestore/file\n\ncontent-length:29940\ncontent-type:multipart/form-data\nhost:e7ffona9b4.execute-api.ap-south-1.amazonaws.com\nx-amz-date:20170714T111258Z\n\ncontent-length;content-type;host;x-amz-date\n15c77e9022d5c4e9de523e7279515d245695c76115ebabe7517119701f9ae963'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20170714T111258Z\n20170714/ap-south-1/execute-api/aws4_request\nb0e6151f24eb3a4aa5520da442bdafe7625a44ed7c15f3109eeb78eef038a6cd'\n"
}`

while **GET** i got this 
`
{
    "message": "No method found matching route api/v1/filestore/file for http method GET."
}
`

In the code I did something like this


`
    @RestController
    @RequestMapping(value = "/v1/filestore")
    public class FileUploadController {

	@Autowired
	private IFileStoreService fileStoreService;
	
	@CrossOrigin
    @ResponseBody
    @RequestMapping(value = "/file/{id}", method = RequestMethod.GET)`

and in application.properties i set
`server.contextPath=/api`

if i was wrong then please lead me the correct argument and help me to fix this issue
Thanks

**Comment by appsassociates-dev** [comment] 2017-08-02 15:48
#3232 known issue

**Comment by rcfrias** [comment] 2017-08-08 03:20
Having the same issue, any idea how to get the session token if using a login-less access?

**Comment by rcfrias** [comment] 2017-08-08 15:12
Ok, I have the right session now, still the same issue. Any Ideas?
Using Version 5.1.3 (5.1.3)

**Comment by ayushrawat18** [comment] 2018-07-07 07:22
I am facing the same issue on version - Version: 5.5.3.

**Comment by mr-fixit** [comment] 2018-08-22 21:46
I had the this error, in my case the error message from the server included

    <StringToSign>PUT
        application/octet-stream 1535007327
        /secureurl/foo/bar/baz/workaround.mp4
    </StringToSign>

I saw that the value of the Content-Type header was used when calculating the signature, so I tried various values for 'Content-Type' until I stumbled on "".  Yes, a empty string.  

curl does this by default.  Postman had to be told specifically to use "".  If I didn't specify it in Postman, then it used 'application/octet-stream'.   NSURLRequest (a macOS/iOS thing) also has to be told, otherwise a default value is injected.

I can see from above thread that the server can choose of what parameters go into the generation  of a pre-signed upload URL, so YMMV.

**Comment by alekseyl-aurea** [comment] 2018-10-04 09:03
found one possible solution:
Remove Send no cache and postman token headers from application settings
and change
Content-Type: application/x-www-form-urlencoded

And magic it works for me (s3 service)

**Comment by sashalinder** [comment] 2018-10-27 20:06
Hey,
using 6.4.4, trying to invoke custom API (execute-api) getting the same issue. 
tried alekseyl-aurea  workaround above, didn't solved it for me.

"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST"

Thanks

**Comment by olgunyldz** [comment] 2019-02-01 10:30
I'm also facing same problem while uploading file via Api Gateway. File is lesser than 10 mb. If file key name is **debug22019 -+(.txt** is not working, and if rename the bucket name to **debug22019 -(.txt** is working fine.

**Comment by jeffhall-wk** [comment] 2019-02-20 17:55
@alekseyl-aurea I removed Send no cache and postman token headers from app settings and now it seems to work. I'm not sure why, though. This worked *with* them 10 hours ago hahah. Also, I think its worth mentioning that I wasn't having this problem when I just hit the "Send" button in Postman, only when I generated the curl and ran it from command line. 

Anyway, Thanks!

**Comment by xai1983kbu** [comment] 2019-08-04 12:48
tried to follow instructions of that blog post https://blog.iron.io/amazon-sqs-simple-queue-service-overview-and-tutorial/ 
1 step - creating a queue by sending GET request 
GET https://sqs.us-east-1.amazonaws.com?Action=CreateQueue&DefaultVisibilityTimeout=0&QueueName=MainLine&Version=2012-11-05

but got an error message in response
```
<?xml version="1.0"?>
<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
    <Error>
        <Type>Sender</Type>
        <Code>SignatureDoesNotMatch</Code>
        <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'GET
...
```

then I've tried the same instructions in Insomnia (https://insomnia.rest/) and it works 
I hope this message will help recreate and fix this behavior in postman
