### ISSUE TITLE
import test run not worked

### ISSUE THREAD

**Issue by msreyad** [a85/POSTMan-Chrome-Extension#4896] opened 2018-07-26 13:26 UTC
**Describe the bug**
i try to import an already .json import test run, but i got an error pls check the file format

**To Reproduce**
1. go to runner
2. save any run result
3. remove it from the list
4. import the .json file again
5. i got an error

**Expected behavior**
test run imported

**App information (please complete the following information):**
 - Chrome App,
 - Postman Version  v6.2.1 
 - windows 10

**Comment by sivcan** [comment] 2018-07-27 06:01
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3574

You can follow the above-mentioned thread for updates.

**Closed as completed by sivcan** 2018-07-27 06:01 UTC
