### ISSUE TITLE
Importing Collection fails

### ISSUE THREAD

**Issue by msesun** [a85/POSTMan-Chrome-Extension#13339] opened 2024-12-17 06:38 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I can't import an existing collection into Postman and there's no errors or messages stating what is causing the error

### Steps To Reproduce

1. On the lefthand side, select `import`
2. Import a .json collection file
3. Error appears

### Screenshots or Videos

<img width="362" alt="Screenshot 2024-12-17 at 01 36 04" src="https://github.com/user-attachments/assets/00ce36b6-54e6-4db9-a820-5432cdb1186b" />

### Operating System

macOS

### Postman Version

11.22.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DannyDainton** [comment] 2024-12-17 09:27
Update:

We've been able to reproduce the issue for certain users type and are continuing to investigate further. More information to follow.

**Comment by guillaume-kizilian** [comment] 2024-12-17 10:21
Same here on windows since this morning. 
@msesun are you behind corporate proxy ? 
@postman-staff was there some domains or cors change today ?

**Comment by rivancic** [comment] 2024-12-17 10:42
Same here. 
With all the data in the cloud UX degrades daily.

**Comment by OzoneDavidP** [comment] 2024-12-17 10:49
+1  I am seeing this and it is likely related to body raw format

**Comment by bozicsara** [comment] 2024-12-17 10:50
+1

**Comment by bozicsara** [comment] 2024-12-17 10:50
+1

**Comment by JsOrange** [comment] 2024-12-17 11:00
+1

**Comment by Rahul-oz** [comment] 2024-12-17 11:01
+1

**Comment by Supriyaoz** [comment] 2024-12-17 11:03
+1

**Comment by OzoneRabiya** [comment] 2024-12-17 11:06
+1

**Comment by morrisond91** [comment] 2024-12-17 11:07
+1

**Comment by DannyDainton** [comment] 2024-12-17 11:07
I appreciate that this comment will not stop this from happening - If you're experiencing the same issue, you can let us know by adding an emoji to the original comment. Adding +1 just notifies everyone who is watching this issue. 🙏🏻

**Comment by VyraC6** [comment] 2024-12-17 11:21
+1 i have the same problem

**Comment by AyushOzone** [comment] 2024-12-17 11:21
+1 having same problem

**Comment by ektajatasra** [comment] 2024-12-17 11:26
If you are not able to directly import the collection on your postman then you can try to share the collection by creating a team workspace & invite the members who want the export of that particular collection.  Once the member receives the collection they can check out the invitation mail & check out the workspace.

I hope this helps you!!

**Comment by RAOdotSH** [comment] 2024-12-17 11:27
Is there any temporary workaround for this?
I got one, you cannot import new collections but you can restore the same collection if it is available in the trash.


Hope that help!

**Comment by DannyDainton** [comment] 2024-12-17 11:34
This appears to be impacting medium to large Collections and APIs - We're still investigating all the areas and services to find the root cause for this. Apologies for the inconvenience that this is causing you all 🙏🏻

**Comment by eslamkhalaf991** [comment] 2024-12-17 12:10
Force closing postman `cmd + q` and reopening it solves it for now

**Comment by DannyDainton** [comment] 2024-12-17 12:18
We have applied a fix for the imports - Would anyone be able to confirm this on their side, please?

**Comment by Rookxc** [comment] 2024-12-17 12:26
> We have applied a fix for the imports - Would anyone be able to confirm this on their side, please?

Works for me.

**Comment by DannyDainton** [comment] 2024-12-17 12:31
Appreciate you confirming @Rookxc ❤️

**Comment by Philip-Nwabuwa** [comment] 2024-12-17 12:34
> Appreciate you confirming @Rookxc ❤️

works for me too

**Comment by OzoneDavidP** [comment] 2024-12-17 12:38
It is working for me - thank you for the turnaround 🤙

**Comment by DannyDainton** [comment] 2024-12-17 12:39
As this seems to have resolved the issue, I'm going to close out this ticket. 

Appreciate all the patience shown here ❤️

**Closed as completed by DannyDainton** 2024-12-17 12:39 UTC
Labels: importer, collections, product/importers

**Comment by douglaschalegre** [comment] 2025-02-04 03:20
Hey @DannyDainton i'm still having this issue on macOS Desktop Platform Version: 11.31.0 (11.31.0)

The import error only seems to occur when using import setting "Naming requests" as Fallback, if i set to URL the import is successful
