### ISSUE TITLE
crashing on any put request where body is a binary file and authorisation is AWS signature

### ISSUE THREAD

**Issue by LouiseYau** [a85/POSTMan-Chrome-Extension#7508] opened 2019-10-21 22:02 UTC
**Describe the bug**
When a Put request is sent with a binary file as the request body, postman immediately crashes either before or just after response is received. (if response is reeived postman crashes about a second or less later not long enough to see any erorrs, however this happens for success responses too)

**To Reproduce**
Steps to reproduce the behaviour:
1. use put request with a request body as a binary file (eg a put request to an aws bucket or api accessed via aws api gateway)
2. for authorisation select aws signature and enter your accesskey, secretkey, aws region, service name and session token
3. attach a binary file as the body 
4. add any headers or parameters necessary for the call
4. click send

**Expected behavior**
success or error message received, file sent and postman dosen't crash 

**Screenshots**
No screenshots available as postman crashes before screenshots can be captured

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.9.0
 - OS: windows 7 enterprise

**Additional context**
note that this postman doesn't crash when aws signature auth not used

**Comment by vikiCoder** [comment] 2019-10-25 06:52
Hi @LouiseYau ,

Thanks for reporting the bug. We have identified the issue and we will be releasing the fix in the upcoming release of the Postman App.

For now, I am closing this issue as it is duplicate of the following issue: https://github.com/postmanlabs/postman-app-support/issues/7220

**Closed as completed by vikiCoder** 2019-10-25 06:52 UTC
Labels: bug, auth/aws, product/runtime
