### ISSUE TITLE
Variable dropdown in edit collection screen showing behid the screen

### ISSUE THREAD

**Issue by FCulig** [a85/POSTMan-Chrome-Extension#9410] opened 2021-01-08 14:01 UTC
**Describe the Issue**

On the edit collection  `Authorization` tab when starting to type variable into basic auth username or password, a dropdown of variables is shown behind the edit collection window.

**Screenshots or Videos**

![variable dropdown behind winow](https://user-images.githubusercontent.com/36075622/104023623-39ca5a00-51c2-11eb-9312-e83419986878.png)

**Environment Information**

 - Platform Type: Desktop app
 - Postman Version: 7.37.0-canary03
 - Operating System: Windows 10

**Comment by DannyDainton** [comment] 2021-01-08 14:06
Closing this as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/8819

**Closed as completed by DannyDainton** 2021-01-08 14:06 UTC
Labels: duplicate
