### ISSUE TITLE
Postman pre_request_scripts issue

### ISSUE THREAD

**Issue by BazzJiang** [a85/POSTMan-Chrome-Extension#7536] opened 2019-10-25 08:28 UTC
**Describe the bug**
In pre_request_scripts you can add those code,but the result is not as expected
```Javascript
let accessToken = pm.environment.get("accessToken");//accessToken is null
console.log(pm.environment.get("accessToken"));//print null
console.log(accessToken === null);//print false
```

**Comment by codenirvana** [comment] 2019-10-25 08:32
Probably its string "null".

**Comment by codenirvana** [comment] 2020-02-29 19:22
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-02-29 19:22 UTC
Labels: support
