### ISSUE TITLE
GET params toggles

### ISSUE THREAD

**Issue by chimit** [a85/POSTMan-Chrome-Extension#1637] opened 2015-12-31 04:23 UTC
Please, add toggles for GET params as well as toggles for body params in POST, PUT.

![postman 2015-12-31 12-22-30](https://cloud.githubusercontent.com/assets/839349/12061125/43ca4322-afb9-11e5-8f9c-1c97e62d2c4a.png)

**Comment by vivek201** [comment] 2017-03-15 04:09
Hi everyone. Any updates on this?

**Comment by IllyaMoskvin** [comment] 2017-04-06 22:59
Dupe of #785, I think.

**Comment by a85** [comment] 2017-06-25 23:21
Should be possible now in 5.0+

**Closed as completed** 2017-06-27 21:12 UTC
Labels: feature
