### ISSUE TITLE
Shared collections don't update on other devices / user accounts

### ISSUE THREAD

**Issue by webcoder-eu** [a85/POSTMan-Chrome-Extension#6309] opened 2019-04-16 11:22 UTC
**Describe the bug**

**To Reproduce**
1. Go to create new request in a shared collection
2. Clcik Sync (orange button in dark theme on Mac)
3. Check on another device / user account the same shared collection
4. The collection doesn't update until the native app is completely closed and reopened on both Mac and Windows platforms. Clicking Sync button doesn't refresh and new collections or changes aren't reflected.

**Expected behavior**
Sync button should refresh collections and show changes made by other users.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.0.7 Mac
 - OS: macOS High Sierra 10.13.3

**Additional context**

**Comment by sujayvenaik** [comment] 2019-04-16 11:30
Duplicate of #6239

**Closed as completed by sujayvenaik** 2019-04-16 11:30 UTC
