### ISSUE TITLE
Postman how to get request body with already substituted variables

### ISSUE THREAD

**Issue by mp222** [a85/POSTMan-Chrome-Extension#6222] opened 2019-04-03 08:38 UTC
Hi,

could you help me with one thing

I need to save request body (json with variables) to use it later in my prerequest script. Unfortunately when I display request data

console.log(request.data);

It looks for example like this:

{

"session": "{{session}}",

"playerid": "{{playerid}}",

"currency": "{{currencyCode}}",

"action":

{ "command": "com",

"parameters": {

"country": "{{countryCode}}"

} } }

Is there a possibility to get request body in Pre-req. with already substituted variables?

**Comment by codenirvana** [comment] 2019-04-03 09:08
Duplicate of #5043

Refer: https://github.com/postmanlabs/postman-app-support/issues/5043#issuecomment-414301254

**Closed as completed by codenirvana** 2019-04-03 09:08 UTC
