### ISSUE TITLE
Postman Updates are disabled but still updates are being downloaded and installed automatically

### ISSUE THREAD

**Issue by kumarvipin1983** [a85/POSTMan-Chrome-Extension#10149] opened 2021-07-24 08:43 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

While working on API testing, last week we noticed that there was a problem with version 8.8 that is once installed automatically. When we restarted postman it restarted with udpates installed automatically. we were in middle of testing and not expecting to install updates immediately. 
In our quick check, we found that we had disabled the setting -> Updates = false/off. Still updates are being automatically downloaded and installed -> asking for restart application with new updates. 

On restart, it has eaten my RAM that was round 8 GB and slow down my system. I was not willing to install updates without my consent but the problem was application was never looking at my updates=disabled setting and doing it updates and install without being asked. 

Thank You so much.  

### Describe the solution you'd like

If any version is introduced with error, we can reinstalled previous smooth working version but again it will auto update and install new updates force it to move new version. We should be fixing existing updates setting and allow user to ask like 
Download Updates only. 
Download & Install updates
No Download of Updates . 
This feature is not present in postman today. Kindly add it. 

### Describe alternatives you've considered

Any better solution is welcome by us.

**Comment by DannyDainton** [comment] 2021-07-24 08:48
Hey @kumarvipin1983

That setting only disables the Major version updates, the Minor and Patch version updates are still enabled.

**Comment by DannyDainton** [comment] 2021-07-24 08:59
Closing as this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/6999

**Closed as completed** 2021-07-24 08:59 UTC
Labels: feature, duplicate
