### ISSUE TITLE
duplicate tab not work

### ISSUE THREAD

**Issue by smile-magic** [a85/POSTMan-Chrome-Extension#9553] opened 2021-02-05 04:57 UTC
duplicate tab not work

Platform Type: Desktop App
Postman Version: 8.0.4
Operating System: macOS 11.2

**Comment by DannyDainton** [comment] 2021-02-05 06:22
Closing as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9493

**Closed as completed by DannyDainton** 2021-02-05 06:22 UTC
Labels: duplicate
