### ISSUE TITLE
Black / Tan Screen

### ISSUE THREAD

**Issue by LordDelacroix** [a85/POSTMan-Chrome-Extension#6469] opened 2019-05-10 13:44 UTC
This has been reported before and a fix published but the fix does not work for me.
v6.1.5, set the environment variable to disable gpu to true and restart the entire machine. Still get the black / tan screen.

Every new version lately just makes Postman worse.

**Comment by numaanashraf** [comment] 2019-05-10 15:55
@LordDelacroix We are sorry to hear that. Would it be possible to share the screenshots of Postman and provide the following details? Is this happening immediately after you launch the app or after using the app for a while?

 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. Window 10]

**Comment by m3dbedb** [comment] 2019-05-24 12:33
Postman Version: 7.1.1
OS: Windows 7 32 bit
Video card Intel HD graphics 2000
1. Open Postman with several little collections in workspace. 
2. Select first request from a collection
3. Wait 3-5 seconds until postman render new tab
4. hit ctrl+enter
5. Wait for response for 3-5 seconds
5. hit down arrow on keyboard
6. go to step 3
After 8-10 steps screen usually goes black

**Comment by numaanashraf** [comment] 2019-05-24 14:27
@m3dbedb We are tracking performance issues like these aggressively. If you can give us some data points on the sizes of requests/responses you were dealing with, number of collections in the workspace, open request tabs etc. or any other relevant details, it'll help us set up relevant benchmarks to test against. I'd like to emphasize that performance and a smooth experience is a top priority and your help would be great.

**Comment by m3dbedb** [comment] 2019-06-04 12:11
I process little requests/responses of about several bytes, number of collections in workspace is up to five. Opened tabs are 10 units. Note that the issue is cross-platform. I suppose @maxcr provided correct reason here: [https://github.com/postmanlabs/postman-app-support/issues/5288#issuecomment-426411371](url) 

> Its because of the electron version

**Comment by m3dbedb** [comment] 2019-06-14 07:46
The issue is reproduced in postman 7.2.0 under windows 7 32 bit

**Comment by m3dbedb** [comment] 2019-08-05 11:00
The issue is reproduced in postman 7.3.5 under windows 7 32 bit

**Comment by m3dbedb** [comment] 2019-10-09 09:46
The issue is reprodused in Postman 7.8.0 under windows 7 32 bit

**Comment by kamalaknn** [comment] 2019-11-11 06:05
Duplicate of #7078

**Closed as completed by kamalaknn** 2019-11-11 06:05 UTC
Labels: performance
