### ISSUE TITLE
Saved response are missing when using 'Save As'

### ISSUE THREAD

**Issue by SeameX** [a85/POSTMan-Chrome-Extension#2893] opened 2017-04-04 09:09 UTC
Version/App Information:
 1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Chrome 56
 3. OS details: win
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: recently

Steps to reproduce the problem:
      1. Go on an existing request
      2. send + save response
      3. save everything in another existing collection
      Expected: collection got a new get request + saved sample response 
      Actual state: collection got a new get request but without the saved sample response 

On 3. when i save the collection the ui is showing me the saved response when i click on another request and then back to the freshly saved the ui is not showing me the saved response anymore.

Best regards

Stefan

**Comment by numaanashraf** [comment] 2017-04-04 09:19
Hi @SeameX, thanks for reporting this. We were able to replicate this issue when saving a request with saved responses into another collection with the 'Save As' option. We'll include a fix in the coming releases.

**Comment by kamalaknn** [comment] 2018-07-19 09:19
Hi @SeameX 

We've identified the root cause of the issue. When a request is saved, the did not react to that immediately that it is now a saved request and that's why you are not being able to add examples to it.

We've identified the fix for this. We'll keep the thread updated on the status of this.

**Comment by numaanashraf** [comment] 2019-04-23 14:59
Fixed in Postman v7.0.8

**Closed as completed by numaanashraf** 2019-04-23 14:59 UTC
Labels: bug, tabs
