### ISSUE TITLE
Global Proxy triggers a connection error but collection runs fine when proxy is disabled

### ISSUE THREAD

**Issue by frcharbonneau** [a85/POSTMan-Chrome-Extension#6026] opened 2019-03-06 17:56 UTC
**Describe the bug**
Postman collection runs fine when I run without any proxy but throws the following error when custom proxy defined (and enabled) to localhost:8087.
Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8087

I've tried multiple solutions posted on other issues with no success:
1- I've tried setting an environment variable with the proxy values for both http and https;
2- I've tried creating a .bat launcher which resets and empties the variables before launching postman:
set HTTP_PROXY=
set http_proxy=
set HTTPS_PROXY=
set https_proxy=
start ----\AppData\Local\Postman\app-7.0.4\Postman.exe
3- I've tried with SSL certificates verification turned off and on

My issue seems to be similar to this one #5626 

**To Reproduce**
1. go to Settings --> Proxy
2. Disable Proxies
3. Test runs fine
4. go to Settings --> Proxy
5. Enable Global Proxy (see 1st screenshot)
6. Test fails to run with failed connection message (see 2nd screenshot)

**Expected behavior**
Expected behavior would have been to have the same result as when Proxy was disabled

**Screenshots**
![image](https://user-images.githubusercontent.com/48291876/53901968-3128fb80-400e-11e9-8473-8e89f221558d.png)
![image](https://user-images.githubusercontent.com/48291876/53901922-16568700-400e-11e9-89ca-a402363ac261.png)

**App information (please complete the following information):**
 - Native App
 - app-7.0.4
 - Windows 7

**Comment by shamasis** [comment] 2019-05-13 11:09
Possible duplicate of https://github.com/postmanlabs/postman-app-support/issues/5626. Closing here. Please let know if otherwise.

**Closed as completed by shamasis** 2019-05-13 11:09 UTC
Labels: bug, Proxy, duplicate, product/runtime
