### ISSUE TITLE
Full-screen windows

### ISSUE THREAD

**Issue by stlr00** [a85/POSTMan-Chrome-Extension#10816] opened 2022-04-02 15:30 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman app doesnt remember window expand settings on windows. After restart, app doesnt in expan window mode.

### Steps To Reproduce

1. Open app
2. Expand window
3. Close it
4. Open again

### Operating System

Windows

### Postman Version

9.15.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment] 2022-04-02 15:45
Closing as this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/6347

**Closed as completed** 2022-04-02 15:46 UTC
Labels: duplicate
