### ISSUE TITLE
Collections disappeared after upgrade

### ISSUE THREAD

**Issue by yaronn** [a85/POSTMan-Chrome-Extension#2234] opened 2016-08-08 13:12 UTC
I'm using Postman 0.8.4.8 as an Extension for Chrome 52.0.2743.116 on Mac 10.11.6. My entire collection has disappeared after upgrade to the mentioned Chrome version. Those collections contain history which is very hard to build from scratch... How can I bring it back?

EDIT: In addition to that Postman itself seems broken (cannot send requests)

**Comment by abhijitkane** [comment] 2016-08-09 09:59
Moving from 0.8 to 4.5 will not automatically migrate your collections. You'll need to manually move data (as described in https://www.getpostman.com/docs/migration).

What's the issue you're facing with the new app? Are there any errors you see?

**Comment by yaronn** [comment] 2016-08-09 10:14
thanks @abhijitkane! I cannot do the migration instructions since they assume I see the collection now and can export it, but at this point I already see nothing in the collections. 

In addition, currently when I type a url and click "send" nothing happens, not sure if related (still talking about the browser extension). However my focus now is to see again my collections.

**Comment by abhijitkane** [comment] 2016-08-09 10:18
What does the Chrome URL bar say when Postman is open? The official Postman extension is `chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm/index.html`.

**Comment by yaronn** [comment] 2016-08-09 10:24
it says:

chrome-extension://mkhojklkhkdaghjjfdnphfphiaiohkef/index.html

and help leads to this repository

**Comment by abhijitkane** [comment] 2016-08-09 10:25
That's an unauthorized clone of the app. (https://github.com/postmanlabs/postman-app-support/issues/2101#issuecomment-225519331)

Not sure what we can do to help out here. Closing this as a duplicate of #2101

**Closed as completed by abhijitkane** 2016-08-09 10:25 UTC
Labels: support
