### ISSUE TITLE
Mutual SSL fails

### ISSUE THREAD

**Issue by Golgo1** [a85/POSTMan-Chrome-Extension#7000] opened 2019-07-26 02:36 UTC
**Describe the bug**
Previously working MutualSSL requests fail after the 7.3.x update

**To Reproduce**
Add a certificate in the typical way
Ensure Certificate Verification is OFF
Attempt a request to an online resource that uses MutualSSL
Any request will fail

**Expected behavior**
When all certificates are properly configured, an SSL connection should be made successfully

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.3.4
 - OS: Windows 10

**Additional context**

**Comment by codenirvana** [comment] 2019-07-26 04:37
@Golgo1 Thanks for reporting this issue.
In Postman v7.3.x, we had upgraded the version of OpenSSL (from `1.0.2l ` to `1.1.0h`) which might have caused this issue.

To help us debug and triage this, is it possible to share more details or a scaled-down collection (if it's a public endpoint) which we can use to reproduce this issue?

**Comment by Golgo1** [comment] 2019-07-26 14:23
I will try to get you some more information.  I will need a bit of time as my current examples have sensitive endpoints.
In the meantime, some notes are 
-one-way SSL seems to work well
-The type of Client cert likely doesnt to matter.  cer/key, pfx both fail (havnt tried other formats)
-all my available test endpoints are on non-standard https port (non 443)  I can confirm these are NOT blocked by any network device
-All my test requests work in 7.2.2

I will try to gather more info

**Comment by Golgo1** [comment] 2019-08-07 18:05
I am unable to provide any useful examples as the targets and certificates cannot be posted.

Is there any public Postman resource I can send requests to in order to test MutualSSL connections?

**Comment by Golgo1** [comment] 2019-10-02 21:41
There have been a number of updates since this functional break.
Just updating the issue to point out that there has been no indication it is being addressed, and the problem appears to persist.

If assistance/examples is required, is there a public URL that requires 2-way SSL that I can test against?
I still cannot post my examples as they are quite sensitive. But they DO work in v6.x

**Comment by Mechanicalkeyboard** [comment] 2020-09-04 11:30
I was able to quickly test against https://server.cryptomix.com/secure/ with any generated key/crt pair. 

@Golgo1  Please let me know if you are able to test against something like this.

**Comment by Mechanicalkeyboard** [comment] 2020-09-11 15:04
Closing issue, please feel free to re-open if the issue is encountered again!

**Closed as completed by Mechanicalkeyboard** 2020-09-11 15:04 UTC
Labels: bug, regression, request-sending, product/runtime, SSL
