### ISSUE TITLE
Content-Type Headers changed inexplicably

### ISSUE THREAD

**Issue by Worldpay-Austin** [a85/POSTMan-Chrome-Extension#7358] opened 2019-09-19 17:28 UTC
After the latest update, all my payloads have had their Content-Type changed from text/xml to application/xml.

I certainly didn't change it and my application requires text/xml. When I select XML as the type of the Body, it gets set to application/xml.

Why this change and is there a way to reset where it will always set header to text/xml?

**Comment by jhendry-whispir** [comment] 2019-09-20 00:46
Same, 

I have vendor specific headers in Content-Type.

Steps to reproduce:
1. open a request
2. click on Headers tab
3. click on Body tab
4. click back to Headers tab

Content-Type has changed from:
`application/vnd.whispir.api-callback-v1+json`

to 
`application/json`

Editing the Content-Type to the correct value, saving, closing the request and reopening corrects the issue.

HTH

**Comment by codenirvana** [comment] 2019-09-22 08:12
@Worldpay-Austin @jhendry-whispir This issue of `Content-Type` header getting overridden for existing requests is already fixed in the latest version of the Postman app (v7.7.3).

For the newer requests which require `text/xml` you have to manually update the `Content-Type` header because by default it uses `application/xml` for XML request body (as `text/xml` is depricated).

**Closed as completed by codenirvana** 2019-09-22 08:12 UTC
