### ISSUE TITLE
New Integration Request - Azure DevOps Git integration

### ISSUE THREAD

**Issue by R-Lamberson** [a85/POSTMan-Chrome-Extension#10414] opened 2021-11-01 17:14 UTC
### Describe your current workflow

we use azure devops git repos as our primary code repositories

as part of the code storage we hold the api specifications in the repository in a folder structure as outline below

source
-- domain a 
---- version
------ api-spec 
-------- file name
-- domain b
---- version
------ api-spec 
-------- file name
-- domain c 
---- version
------ api-spec 
-------- file name
-- domain d 
---- version
------ api-spec 
-------- file name

### Describe your ideal workflow

would like to have the ability to integrate either the entire repository or individual api's to postman rather than having to import / export files into the postman workspace

### Describe alternatives you've considered

import/exporting the files manually

**Comment by shashankawasthi88** [comment] 2021-11-02 05:52
@R-Lamberson thanks for raising this request. We are tracking the Azure DevOps Git request [here](https://github.com/postmanlabs/postman-app-support/issues/10280). Please follow the thread and also comment if your repository is cloud-hosted or self-hosted.

**Comment by shashankawasthi88** [comment] 2021-11-02 05:52
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/10280

**Closed as completed by shashankawasthi88** 2021-11-02 05:52 UTC
Labels: feature, product/integrations
