### ISSUE TITLE
Problem to set metadata in grpc postman

### ISSUE THREAD

**Issue by MNouroozi** [a85/POSTMan-Chrome-Extension#11658] opened 2023-01-26 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

problem to set metadata in grpc post
Send header application/grpc-web

### Steps To Reproduce

hi
Does Postman support grpc+web method?
I send a parameter in the metadata section, but it applies the default metadata
![Screenshot 1401-11-04 at 14 21 25](https://user-images.githubusercontent.com/37396752/214273561-89ae687e-1112-43c8-892b-82e0b7740415.jpg)
kreya is supported and send request get response 
![Screenshot 1401-11-04 at 14 23 19](https://user-images.githubusercontent.com/37396752/214273752-259939b4-995b-47e0-8deb-23d466324ff7.jpg)
But I want to use postman, I don't know if it has such a feature or not. Thank you for your guidance

### Operating System

Mac os

### Postman Version

10.8.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by codenirvana** [comment] 2023-01-26 13:47
@MNouroozi Setting metadata won't work because the underlying transport is still native gRPC (HTTP/2).

Closing as duplicate of #10712, follow this thread for updates on gRPC Web support.

**Closed as completed by codenirvana** 2023-01-26 13:47 UTC
Labels: protocol/grpc, product/api-client
