### ISSUE TITLE
Default environment for each collection

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5694] opened 2018-12-27 10:00 UTC
**Is your feature request related to a problem? Please describe.**
Yes, so if I select a call from the collection (existing tab) it already has selected one of the possible environments for this collection - then the selection can't be changed (For example I configured local, stage & prod and defined local as default. So when I make a call to stage environment then opened another call in a new tab, and then back to the first - stage still selected as last used.)

**Describe the solution you'd like**
Default environment for every collection

**Comment by numaanashraf** [comment] 2018-12-28 11:04
@ash007-postman this is a bug report or a feature request? please follow the template https://github.com/postmanlabs/postman-app-support/issues/new/choose and provide the required information.

**Comment by moleksyuk** [comment] 2018-12-28 15:49
@numaanashraf this ticket was created based on contact by email.
I created it according to rules and it's a feature request.
I explained with more details here #5698

This ticket can be closed.

**Comment by numaanashraf** [comment] 2018-12-31 07:05
Duplicate of #5698

**Closed as completed by numaanashraf** 2018-12-31 07:05 UTC
