### ISSUE TITLE
Strip spaces while pasting bulk edit

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5113] opened 2018-08-30 02:57 UTC
When I used this feature before, I often copied the request directly in the browser, for example.
![image](https://user-images.githubusercontent.com/20716891/44826770-e97e7d00-ac42-11e8-93fd-bf73bb16b41d.png)
Then I will copy directly to form-data in postman,like this
![image](https://user-images.githubusercontent.com/20716891/44826873-1af74880-ac43-11e8-9a3b-5e743b6b4954.png)
![image](https://user-images.githubusercontent.com/20716891/44826884-2480b080-ac43-11e8-939f-329daf50141a.png)
Now the problem is that it used to be very good, but now, after copying directly, the space before the value of value will not be automatically removed. After copying in, the space before the value will be removed directly. Now it will not be removed directly? What is it?
![image](https://user-images.githubusercontent.com/20716891/44826967-86411a80-ac43-11e8-8b31-4f1fb6bbf88c.png)

**Comment by DannyDainton** [comment] 2020-08-25 08:50
Closing this a duplicate of #8963

**Closed as completed by DannyDainton** 2020-08-25 08:50 UTC
Labels: feature, configurations, bulk-edit
