### ISSUE TITLE
Multi language documentation

### ISSUE THREAD

**Issue by felipeplets** [a85/POSTMan-Chrome-Extension#5311] opened 2018-10-05 10:53 UTC
Hey guys, 

I have customers world wide and some are not so used to English. Mainly Spanish and Portuguese customers and I would like to have a native multi language support for documentation. 

Also another solution would be some integrations like with [localizejs.com](localizejs.com) or similar tools.

**Comment by VictorHOliveira** [comment] 2019-07-10 01:14
Yeah, I'm from Brazil and here we use Postman a lot, and o feel miss about the translate and more support in portuguese. Can I help with this?

**Comment by arlemi** [comment] 2020-01-17 16:51
Closing this issue since this is a duplicate of the following in the postman-docs repository: 
https://github.com/postmanlabs/postman-docs/issues/2057

We'll update on the advancement there.

**Closed as completed by arlemi** 2020-01-17 16:51 UTC
Labels: feature, product/documentation, i18n
