### ISSUE TITLE
Error saving new tab

### ISSUE THREAD

**Issue by gfigueroa** [a85/POSTMan-Chrome-Extension#4589] opened 2018-05-22 16:17 UTC
**Describe the bug**
Postman v6.1.2 cannot save new tab on Windows 10. An error occurs.

**To Reproduce**
1. Create new tab
2. Fill (or don't fill) request data
3. Click Save/Save As...
4. Error window appears saying "Something Went Wrong"

**Expected behavior**
Tab should be saved.

**App information (please complete the following information):**
 - Native App
 - v6.1.2
 - OS: Windows 10

**Comment by vkaegis** [comment] 2018-05-23 13:30
Hey @gfigueroa, thanks for writing in! I can't seem to reproduce this bug on v6.1.2. Can you attach a screenshot of your app state? This will help us identify the problem. Could you also check if your Sync icon is orange?

<img width="1001" alt="screenshot 2018-05-23 18 57 38" src="https://user-images.githubusercontent.com/6038010/40427486-7868d6a8-5ebb-11e8-9682-548d07f45faf.png">

**Comment by gfigueroa** [comment] 2018-05-24 16:33
Hi Vineet,
Thanks for your reply. The Sync icon is orange. I can save tabs with different names if they have been duplicated, but I cannot save new ones.
Below is a more detailed reproduction:
   
1. Click New Request
![image](https://user-images.githubusercontent.com/1941240/40892430-49f34cb2-6754-11e8-8570-89f8b2f81e3b.png)

2. Enter URL and other request information
![image](https://user-images.githubusercontent.com/1941240/40892439-68f2d59c-6754-11e8-82e6-8b0082a140c9.png)

3. Click Save
![image](https://user-images.githubusercontent.com/1941240/40892452-97fbf184-6754-11e8-9400-588b858e86e5.png)

4. Select Collection
![image](https://user-images.githubusercontent.com/1941240/40892462-afc77eb4-6754-11e8-9610-73bc529cdbdb.png)

5. Error message appears
![image](https://user-images.githubusercontent.com/1941240/40892467-bef210fc-6754-11e8-997f-f1243d3ec791.png)

6. Any subsequent attempts to click the Save button result in this window popping up immediately.

**Comment by vkaegis** [comment] 2018-05-25 21:29
Hey @gfigueroa, still unable to reproduce this. Some screenshots would really help here. Does the error appear when you click Save or when you select the collection in the Save dialogue?

**Comment by gfigueroa** [comment] 2018-05-28 01:02
Hi Vineet,
Did you not receive the screenshots attached directly to the instructions (as inline images) in the previous email? It appears first when you select the collection in the Save dialogue. Then it appears any time I click Save on that same tab.
Gerardo
    On Friday, May 25, 2018, 3:29:24 PM CST, Vineet Kumar <notifications@github.com> wrote:  
 
 
Hey @gfigueroa, still unable to reproduce this. Some screenshots would really help here. Does the error appear when you click Save or when you select the collection in the Save dialogue?

**Comment by vkaegis** [comment] 2018-05-30 21:58
@gfigueroa Can't find any screenshots here. Could you try posting them on Github instead of replying to the email thread?

**Comment by gfigueroa** [comment] 2018-06-03 23:39
@vkaegis I updated my comment above with the screenshots. Thanks!

**Comment by vkaegis** [comment] 2018-06-30 14:26
@gfigueroa Thanks for the screenshots, and apologies for the delay on this. @prashantagarwal could you take a look at this?

**Comment by prashantagarwal** [comment] 2018-07-01 16:05
@gfigueroa We have released a fix for this on our canary apps. Can you please verify it. You can download canary app from https://www.getpostman.com/canary

**Closed as completed** 2018-07-28 08:26 UTC
Labels: bug, pending-close
