### ISSUE TITLE
Postman Auth Issue / Not allowed to use the browser: Google Chrome (66.x)

### ISSUE THREAD

**Issue by bleadm** [a85/POSTMan-Chrome-Extension#7720] opened 2019-11-29 10:42 UTC
When I'm connecting to Postman App , I got  error to authenticate 

The message is :
Sorry, this web browser is not approved for use at our company.
Not allowed to use the browser: Google Chrome (66.x)

We are  using Zscaler Proxy and we have block OLD chrome Version.
I've try to create Global Variable to force the User-Agent String without success.

**To Reproduce**
1. Go to 'Zscaler Cloud Admin '
2. Click on 'Block ALL OLD Chrome Version'
3. Launch Postman
4. Clic Sign IN 
5. Error : Not allowed to use the browser: Google Chrome (66.x)

**Expected behavior**
Authentication to Postman is done with OLD Chrome version

**Screenshots**
Error Message 
![image](https://user-images.githubusercontent.com/58329041/69863030-0bc6d680-129c-11ea-8d51-077e9e3c95c6.png)

Print screen of Global Variable I've try 
![image](https://user-images.githubusercontent.com/58329041/69863099-43358300-129c-11ea-9a2d-8f4ef20e7175.png)

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [7.12.0 win32 10.0.17134 /x64]
 - OS: [Win10 1803 - 17134.1130]
- Chrome installed [ version 78.0.3904.108]

**Comment by numaanashraf** [comment] 2019-12-02 04:50
Thanks @bleadm. We are tracking this at #7700.

**Comment by numaanashraf** [comment] 2019-12-02 04:50
Duplicate of #7700

**Closed as completed by numaanashraf** 2019-12-02 04:50 UTC
