### ISSUE TITLE
Impossible to use definitions in json-schema

### ISSUE THREAD

**Issue by SParmentier** [a85/POSTMan-Chrome-Extension#8426] opened 2020-05-04 09:13 UTC
**Describe the bug**
Postman can't validate a json-schema with the 'definition' attribute defined
https://json-schema.org/understanding-json-schema/structuring.html

**To Reproduce**
Create a json-schema in the pre-request script

`
pm.globals.set("example-schema", {
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "definitions": {
    "test": {
      "$id": "#test",
      "type": "string",
    }
  }
});
`

Add the json-schema test  in the Tests section

`
pm.test("Check Schema", () => {
    pm.response.to.have.jsonSchema(pm.globals.get('example-schema'))
}) 
`

Contact any endpoint.

In the Test Results, I have this error

Check Schema | Error: schema is invalid: data.definitions['setPlan'] should be object,boolean.

**Expected behavior**
Postman should accept the json-schema and validate the payload received by the endpoint since it's only using definitions

**App information (please complete the following information):**
 - Native App
 - 7.23.0
 - macOS Catalina 10.15.4

**Additional context**
I tried with online validator with the same schema & payload and it's fine.
I also tried with the Ajv node lib (v 6.12.2) with the same schema & payload and it's fine.
Also, if I make a more complex schema with multiple definitions, the errors is multiplying too.

**Comment by atulbi** [comment] 2020-05-15 07:04
@SParmentier We tried reproducing this issue on our end using the following schema for our test with definitions, but were able to successfully validate the schema. 
**With the limited information at hand we are unable to reproduce this issue.** 
```
pm.globals.set("example-schema",` {
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "definitions": {
        "test": { "$id": "#test",  "type": "string" }
    },
    "properties": {
        "test": { "$ref": "#/definitions/test" }
    }
});
```
It would be helpful if you could provide us with a schema that is not working as expected or a collection that we can run to see the failure.

**Comment by Mechanicalkeyboard** [comment] 2020-09-14 14:55
Closing this issue for now, please feel free to re-open if this issue is still present.

**Closed as completed by Mechanicalkeyboard** 2020-09-14 14:55 UTC
Labels: bug, product/runtime
