### ISSUE TITLE
Javascript > XHR: Code Generation Not Passing in Body with Variables

### ISSUE THREAD

**Issue by StoicNZ** [a85/POSTMan-Chrome-Extension#3095] opened 2017-06-01 07:47 UTC
1. Postman Version: 4.11.0-canary02
 2. App (Chrome app or Mac app): Windows Native
 3. OS details: Win x64

The body isn't being generated, coming through as null. The URL is correctly capturing the current environment variables, but the body doesn't.

My request is a raw/Text type request.

![image](https://cloud.githubusercontent.com/assets/5607534/26669612/e02e6984-46f1-11e7-83b4-043eebef64f8.png)
![image](https://cloud.githubusercontent.com/assets/5607534/26669716/3be87b48-46f2-11e7-8f9f-79db10a76b3b.png)

**Expected**
```
var data = "api_key=XXX&api_secret=YYY&grant_type=client_credentials";

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "https://ZZZ:443/v1/oauth/token");
xhr.setRequestHeader("content-type", "application/x-www-form-urlencoded");
xhr.setRequestHeader("cache-control", "no-cache");

xhr.send(data);
```

**Actual**
```
var data = null;

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "https://ZZZ:443/v1/oauth/token");
xhr.setRequestHeader("content-type", "application/x-www-form-urlencoded");
xhr.setRequestHeader("cache-control", "no-cache");

xhr.send(data);
```

**Comment by numaanashraf** [comment] 2017-06-01 08:04
Thanks for reporting @StoicNZ. We are looking into this.

**Comment by vinitshahdeo** [comment] 2019-04-03 13:27
@StoicNZ Could you please check it now?

 I tried to reproduce this bug, the **raw body** is correctly capturing the **environment variables**.

<img width="1110" alt="Screenshot 2019-04-03 at 4 15 10 PM" src="https://user-images.githubusercontent.com/20594326/55473204-b44c6a00-562b-11e9-9949-cedfdbabb8d5.png">

<img width="723" alt="Screenshot 2019-04-03 at 4 16 12 PM" src="https://user-images.githubusercontent.com/20594326/55473335-16a56a80-562c-11e9-94b5-3af49908b1f0.png">

**Comment by numaanashraf** [comment] 2019-04-03 13:30
Closing as this issue seems to be resolved

**Closed as completed by numaanashraf** 2019-04-03 13:30 UTC
Labels: bug, code-generator
