### ISSUE TITLE
Support SOCKS proxy on Postman.app for Mac 

### ISSUE THREAD

**Issue by quantumrag** [a85/POSTMan-Chrome-Extension#7756] opened 2019-12-06 15:49 UTC
**Is your feature request related to a problem? Please describe.**
Postman Chrome app is able to support through browser SOCKS proxy (tunnelling). However, the desktop app only supports HTTP/HTTPS proxy. I am currently using SOCKS5 proxy addon on browser to access services on my remote server. 

**Describe the solution you'd like**
I want the Postman chrome app to support SOCKS proxy

**Describe alternatives you've considered**
Currenlty, I am using Postman chrome app + browser addon SwitchyOmega (supporting SOCKS proxy)

**Additional context**
I have my collections on Postman login and would like to have a Mac desktop app to support the same than going through browser.

**Comment by numaanashraf** [comment] 2019-12-09 06:25
Thanks for writing in @raghavendrabond. We are tracking this feature request at #1321. Do follow that thread for discussions and updates.

**Comment by numaanashraf** [comment] 2019-12-09 06:25
Duplicate of #1321

**Closed as completed by numaanashraf** 2019-12-09 06:25 UTC
