### ISSUE TITLE
Have a different empty state while searching on the sidebar

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#5168] opened 2018-09-12 09:31 UTC
When some text is entered in the sidebar search field, and there are no results, we display the same empty state message. We need to change the message to inform that the user is viewing a filtered list so that he/she doesn't think there are no collections.

![screen shot 2018-09-12 at 15 01 20 pm](https://user-images.githubusercontent.com/16399370/45416073-bacdc100-b69c-11e8-886d-e2e7199b8803.png)

**Comment by numaanashraf** [comment] 2018-09-12 09:48
Duplicate of #5041

**Closed as completed by numaanashraf** 2018-09-12 09:48 UTC
Labels: user-interface
