### ISSUE TITLE
tv4 error objects missing major information in native app and newman

### ISSUE THREAD

**Issue by kajdo** [a85/POSTMan-Chrome-Extension#3300] opened 2017-07-24 12:28 UTC
## App Details:

```
Postman for Windows
Version 5.0.2
win32 6.1.7601 / x64

npm newman --version
5.0.3

npm tv4 --version
5.0.3

Postman for Chrome
Version 5.0.2
win / x86-32
Chrome 58.0.3029.110

```

## Issue Report:
 1. I can't tell if this issue was there before - this was my first try to work with tv4
 2. Expected behaviour: the error object should carry the same information in **native app and in newman**, unfortunately it just carries 
```
- message, 
- name 
- type
```
efficient bugfixing after validating several hundred parameters would need the full error object (or at least the **dataPath and schemaPath**)
3. Screenshots (this img is from chrome app and it contains much more object data)
![image](https://user-images.githubusercontent.com/8735942/28522937-6849624a-707a-11e7-9d3a-a7c6dcd19771.png)
4. the comparison was done with exactly the same collection

you can reproduce this behaviour via below steps
- run a schema validation as test 
- console output the error.object
f.e see below script
```
tests["Response OK"] = responseCode.code === 200;
var responseData = JSON.parse(responseBody);
console.log(responseData);

tests["Valid Data"] = tv4.validate(responseData, schema);
var result = tv4.validateResult(responseData, schema);
console.log(JSON.stringify(result));
console.log(tv4.error);
```

**Comment by kamalaknn** [comment] 2017-07-25 11:12
@kajdo this could be because we use [`postman-sandbox`](https://github.com/postmanlabs/postman-sandbox) to execute our scripts in the Native apps and Newman.

We'll take a look at this.

**Comment by kajdo** [comment] 2017-07-26 12:42
its strange ... running it this way, i get the dataPath and schemaPath

`var responseData = JSON.parse(responseBody);
var result = tv4.validateMultiple(responseData, schema,false,true);
tests["JSON response complies to schema"] = result.valid;
//console.log(JSON.stringify(result));
result.errors.forEach(function(currentValue,index,array){
    console.log("#"+index+": "+currentValue.message+", dataPath: "+currentValue.dataPath+", shemaPath: "+currentValue.schemaPath);
});`

**Comment by blikblum** [comment] 2017-09-19 16:31
I can reproduce the issue with PostMan for windows 5.2 (newman also shows the same behavior)

**Comment by fefranca** [comment] 2018-01-05 16:20
This issue still persists in Postman client (macOS 10.12 / 10.13). Testing tv4 from source brings up both properties (dataPath and schemaPath). This would be really useful for debugging endpoint schema changes using Postman app / monitors.

**Comment by rsweetland** [comment] 2018-01-12 20:51
Issue persists for me, too (macOS 10.13 / Postman 5.5.0). It would be very helpful if this could be fixed.

*Update*: Could upgrading tv4 to latest version (1.3.0) fix the issue? Looks Postman Sandbox is [running 1.2.7](https://github.com/postmanlabs/postman-sandbox/blob/b79aa0e14ded0683e751f34d8ca0a76d05c0f556/package.json#L78)

**Comment by rsweetland** [comment] 2018-01-12 23:57
I found a workaround: 

Explicitly log `tv4.error.schemaPath`.
```javascript
tv4.validate(responseJson, taskSchema);
console.log(tv4.error.schemaPath);  // <-- data is there! 👍
```

```javascript

console.log(tv4.error); // <-- doesn't show schemaPath when you just log the object
 {
  "message": "Invalid type: null (expected integer)",
  "name": "ValidationError",
  "type": "Error"
}
```

**Comment by Coffee-Boyy** [comment] 2018-08-14 20:12
That workaround only seems to work for single validation. This is still an issue in Postman 6.2.4 (Windows 7)

Update:
Workaround for multiple validation:
```
const result = tv4.validateMultiple(jsonData, schema);
console.log(result.errors[0].schemaPath);
```

It seems that accessing it directly is the only thing that works for some reason

**Comment by codenirvana** [comment] 2019-02-04 09:16
Postman native apps starting from v6.7.1 and Newman v4.3.0+ adds support for [Ajv](https://github.com/epoberezkin/ajv) library.

Check if Ajv helps to debug schema validation errors. ([documentation](https://github.com/epoberezkin/ajv#validation-errors))
cc. @kajdo @ConnorChristie @rsweetland @fefranca

Refer:
```javascript
var Ajv = require('ajv'),
    ajv = new Ajv({logger: console}),
    schema = {
        "properties": {
            "alpha": {
                "type": "boolean"
            }
        }
    };

pm.test('Schema is valid', function() {
    var valid = ajv.validate(schema, {alpha: 123});
    console.log(ajv.errors);
    pm.expect(valid).to.be.false;
});
```

**Comment by codenirvana** [comment] 2019-02-20 06:48
Closing this since tv4 is deprecated in favor of Ajv.
Refer to the above example for debugging schema errors in Ajv.

**Closed as completed by codenirvana** 2019-02-20 06:48 UTC
Labels: bug

**Comment by GrzegorzPi** [comment] 2019-02-21 12:35
Postman v6.7.3

I have tiny validator inside snippets scripts using tv4. If it is now deprecated should be rewitten with Ajv.
