### ISSUE TITLE
AWS Signature authentication issue old vs new postman versions

### ISSUE THREAD

**Issue by elpaisa** [a85/POSTMan-Chrome-Extension#4186] opened 2018-02-14 01:09 UTC
Hi, i'm using the latest postman version to do an authenticated request to AWS, i'm using the provided authentication option, however, no matter what i do, it gets the following error:

`{
    "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'GET\n/state/state/state\n\ncontent-length:\ncontent-type:application/x-www-form-urlencoded\nhost:search-dasdsadasdas.us-east-1.es.amazonaws.com\nx-amz-date:20180214T005109Z\n\ncontent-length;content-type;host;x-amz-date\neSOME-CALCULATED-SIGNATURE-REMOVED-FOR-SECURITY'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20180214T005109Z\n20180214/us-east-1/es/aws4_request\nfSOME-CALCULATED-SIGNATURE-REMOVED-FOR-SECURITY'\n"
}`

## App Details:
```
Version 5.5.2 (5.5.2)
```
I decided to try the chrome version, with the same credentials and the same settings, and it got a a good response:

```
Postman for Chrome
Version 5.5.1
OS X / x86-64
Chrome 63.0.3239.132
```
Differences between curls generated:

For desktop version Version 5.5.2 (5.5.2)
`
curl -X GET \
  https://search-1234.us-east-1.es.amazonaws.com/_count \
  -H 'Authorization: AWS4-HMAC-SHA256 Credential=SOMECREDENTIAL/20180214/us-east-1/es/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=SOMESIGNATURE' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Host: search-1234.us-east-1.es.amazonaws.com' \
  -H 'Postman-Token: be91afb2-320c-a826-3584-fc2bbfa2d558' \
  -H 'X-Amz-Date: 20180214T005109Z'
`

For chrome version:

`
curl -X GET \
  https://search-1234.us-east-1.es.amazonaws.com/state/state/state \
  -H 'authorization: AWS4-HMAC-SHA256 Credential=SOMECREDENTIAL/20180214/us-east-1/es/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=SOMESIGNATURE' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'host: search-1234.us-east-1.es.amazonaws.com' \
  -H 'x-amz-date: 20180214T005611Z'
`

I tried the curl requests via terminal, and removed `content-length` from the desktop version curl, also renamed 'Authorization' to 'authorization' as the chrome version, but i get the same signature error, so for some reason the calculation of the signature is getting bad done, it might be some OS time issue, but i'm not sure, the request only works in the chrome version

**Comment by harryi3t** [comment] 2018-02-17 12:43
Thanks for reporting this issue. We will look into this and get back to you.

**Comment by garnold** [comment] 2018-02-19 21:33
@harryi3t [Can you look at this one too](https://github.com/postmanlabs/postman-app-support/issues/4151)? Similar issue...

**Comment by rolyv** [comment] 2018-07-16 14:57
👍 been seeing this too. I've had to fall back to the chrome app for AWS signed requests.

**Comment by KenEucker** [comment] 2018-08-27 22:46
I'm happy that I stumble across this issue, as I would never have guessed that my issue connecting to the domain that resulted in this error:

```The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been ... ```

Would have had to do with the postman app, and not something else. 

In my scenario, I am also using AWS API Gateway + CloudFront and the POSTs sent directly to the API Gateway URL were working. If I tried to use the CNAME attached to the CloudFront distribution, I would get the error above.

**Comment by red8888** [comment] 2018-09-24 15:37
This is still broken it seems

**Comment by alekseyl-aurea** [comment] 2018-10-04 08:35
Yep, experiencing same issue on 6.3.0 VS current Chrome %((((((

**Comment by alekseyl-aurea** [comment] 2018-10-04 08:57
found one possible solution: 
Remove Send no cache and postman token headers from application settings 
and change 
Content-Type: application/x-www-form-urlencoded 

And magic it works for me (s3 service)

**Comment by cwdcwd** [comment] 2018-10-23 19:34
6.4.4 on mac. Same issue. removing the no-cache and postman tokens didn't help for me with AWS API gateway

**Comment by govindrai** [comment] 2018-10-30 20:26
Also experiencing this same issue running 6.4.4

**Comment by kjozsa** [comment] 2018-10-31 07:57
broken on linux with 6.4.4 too.. that's a pretty bad joke for a commercial customer

**Comment by benschmi** [comment] 2018-11-13 10:13
Same issue in 6.5.2
Removing the no-cache and Postman tokens doesn't help.

**Comment by zacacollier** [comment] 2018-11-20 20:39
6.5.2 doesn't work for me on Linux either. Also tried removing the no-cache and postman headers to no avail. Guess I'll switch to Insomnia?

**Comment by daMichaelB** [comment] 2018-12-29 15:54
Also experiencing this issue running 6.6.1 and trying to invoke AWS Sagemaker endpoint.

**Comment by nhunghuynhthihong** [comment] 2019-01-09 06:45
Also met the same issue on `6.6.1`

**Comment by mjendza** [comment] 2019-01-09 13:19
Also I have problem with 6.6.1 version

**Comment by nhunghuynhthihong** [comment] 2019-01-16 07:11
I am able to workout like this:

In Authorization, after you click Preview Request, back to Headers tab and enable Authorization key and its value (or copy it to a new line)

**Comment by cyrfer** [comment] 2019-02-17 05:16
I had the same problem with 6.7.3 and found this thread.

I was able to work it out by:
1- remove use of environment var substitution for access/secret keys. paste keys directly into auth form.
2- click Preview Request once before Send.

**Comment by rameshnatesan** [comment] 2019-02-19 20:42
> I had the same problem with 6.7.3 and found this thread.
> 
> I was able to work it out by:
> 1- remove use of environment var substitution for access/secret keys. paste keys directly into auth form.
> 2- click Preview Request once before Send.

You are right, same thing here. If I use it as environment variables {{accesskey}} and {{secretkey}}, it is not working. If I hard code the keys, it works fine.

**Comment by rameshnatesan** [comment] 2019-02-20 18:10
this looks like a very critical/high priority/severity # 1 bug. please look into it :)

**Comment by kjozsa** [comment] 2019-02-20 20:02
this is a BLOCKER issue which is at least a year old, open, and forces commercial users like us to stay with historical versions like 5.5.3, which is stuffed with annoying notifications that we should update to the latest version which freakin' does not work. 

The whole story is a really bad joke, if you ask me.

**Comment by rameshnatesan** [comment] 2019-02-21 17:05
> this is a BLOCKER issue which is at least a year old, open, and forces commercial users like us to stay with historical versions like 5.5.3, which is stuffed with annoying notifications that we should update to the latest version which freakin' does not work.
> 
> The whole story is a really bad joke, if you ask me.

will this happen even when running the test using newman tool? I need to tried that way.

**Comment by kjozsa** [comment] 2019-02-21 20:28
I hope you excuse my ignorance but I think that someone is paid for testing this app, and I'm sure it's not me. In fact, we are even paying for this app to support its testing!

**Comment by rameshnatesan** [comment] 2019-02-25 19:33
I tried using environment variable names {{key1}} and {{key2}} for access key and secret key. It worked!!!


![aws4](https://user-images.githubusercontent.com/11393530/53363343-3d280580-390a-11e9-8161-9f3f435727d9.png)

**Comment by rameshnatesan** [comment] 2019-03-13 20:31
> I had the same problem with 6.7.3 and found this thread.
> 
> I was able to work it out by:
> 1- remove use of environment var substitution for access/secret keys. paste keys directly into auth form.
> 2- click Preview Request once before Send.

I tried using environment variable names {{key1}} and {{key2}} for access key and secret key. It worked!!!
it also worked when using names like {{secretkey}} and {{accesskey}} all lowercase

**Comment by joseSantacruz** [comment] 2019-03-27 16:57
Version 7.0.6 same issue

**Comment by caionaweb** [comment] 2019-04-09 00:32
7.0.7 same... 
I tried post into elasticsearch endpoint and received same quote.

**Comment by vikiCoder** [comment] 2019-04-26 08:29
We have fixed some issues related to AWS authentication in version 7.0.9. You can test it. And please inform in this thread whether your issue related to AWS authentication is solved or not.

**Comment by kjozsa** [comment] 2019-05-02 10:41
issue still exists in 7.0.9

**Comment by willkjackson** [comment] 2019-05-10 19:12
Having the same issue with 7.0.9, using postman environment vars or directly in the Auth tab...

**Comment by britt-k** [comment] 2019-08-29 15:09
Experiencing the same issue in version 7.3.5
After trying the suggestion of using environment variable names {{key1}} and {{key2}} for access key and secret key, it is now giving a different error saying that the security token included in the request is invalid.

**Comment by mikepalfrey** [comment] 2019-10-28 17:17
Looks like this is still an issue on 7.10.0 on macOS. Tried all the workarounds here but no luck. Bit disappointing as I thought this was a cool feature which would save me a fair bit of work!

**Comment by vikiCoder** [comment] 2019-12-06 13:09
Hi everyone 👋,

I tried to reproduce the issues regarding the signature mismatch mentioned in this thread but had no success 😞. I tried the Postman's AWS auth helper in S3 and Elastic Search services of AWS with different combinations of request body, path and query parameters. And all the requests worked just fine for me (in Postman App version v7.13.0).

We are closing this issue because there are many people talking about different problems not necessarily related to AWS auth without enough information for us to reproduce the issue. This issue was created more than a year ago and we have made many changes to AWS auth helper since. Please update your Postman App to the latest version (v7.13.0) and see whether you are still facing any issues with AWS auth. If you are still facing any issue with it, I suggest you to open a new issue with detailed information about your failing request. Please mention the following details if you are creating a new issue related to AWS auth:

1. Request URL
2. Query Params
3. Request body type (any one of none, form-data, x-www-form-urlencoded, raw, binary, GraphQL)
4. All the request headers that are being sent with the request
5. Screenshot of the failing request from Postman Console (expand all the sections of request in the console before taking a screenshot)
6. Which AWS service are you trying to use?
7. Are there any special characters in your URL/query param/body that should be percent-encoded before sending the request?
8. What response are you getting from AWS for the failing request?
9. In some cases, AWS also sends the `StringToSign` and `CanonicalRequest` in the response in case of signature mismatch. It would be good if you can show that as well.
10. Are you using any proxy for sending the request?
11. Are there any redirects happening for the sent request?

Note: Please include all of the above information while creating a new issue. Replace any sensitive data in your answers with `xxxx`.

**Closed as completed by vikiCoder** 2019-12-06 13:09 UTC
Labels: bug, Auth, product/runtime

**Comment by shawnwz** [comment] 2020-06-26 14:32
I am suffering this with both postman<latest> and postmancanary<latest>.
Request url is 
https://rr25iqfk26.execute-api.us-east-1.amazonaws.com/dev/?key=zhe.jpg&oper=get
both GET and POST method
no body for GET request.
It return 403 error code.
{
    "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/dev/\nkey=zhe.jpg&oper=get\nhost:rr25iqfk26.execute-api.us-east-1.amazonaws.com\nx-amz-date:20200626T141931Z\n\nhost;x-amz-date\n4df4ccb96895d292bfc67a73a47af41f88158fc60173b1d8018d55943c544cad'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20200626T141931Z\n20200626/us-east-1/execute-api/aws4_request\n09aac79c852fcf1727b25e6e483bb643140cc9c0de05f70fd9270995207f86b8'\n"
}


I am using API gateway -> aws lambda 
I don’t use proxy and no redirects happen.

**Comment by arlemi** [comment] 2020-06-30 09:51
@shawnwz I'd recommend reaching out to support on help@postman.com.
