### ISSUE TITLE
Omit redundant content-type header from generated cURL

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#8414] opened 2020-04-29 18:35 UTC
**Is your feature request related to a problem? Please describe.**
If content-type header is added manually, in addition to the one automatically generated by Postman, generated cURL includes two content-type headers.

**Describe the solution you'd like**
Only include manual content-type header in cURL, when it's present.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by shreys7** [comment] 2020-05-15 09:13
Duplicate of #8290

**Closed as completed by shreys7** 2020-05-15 09:13 UTC
Labels: code-generator, product/codegen
