### ISSUE TITLE
Weird character display (Elasticsearch query results)

### ISSUE THREAD

**Issue by turbokat** [a85/POSTMan-Chrome-Extension#2711] opened 2017-02-15 21:25 UTC
1. Postman Version: 4.10.0
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: Windows 7
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: recently, haven't tried before
 6. Expected behaviour: normal display
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): NA
 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/20780493/22995896/88df1a0c-f381-11e6-98de-cdaaacff2f2c.png)

Simply firing a query to elasticsearch returns results, but with the ids distorted as shown above. I checked this against other tools and by firing the query in the browser - works fine there. This appears to be a postman-specific issue. 

Any help would be appreciated. Thank you.

**Comment by hn3000** [comment] 2017-02-16 06:14
duplicate of #2710

**Comment by sdnts** [comment] 2017-02-16 08:01
@gdiwakar Is this happening for you on the latest version? (4.10.2)?

**Comment by hn3000** [comment] 2017-02-16 09:28
at that time it should have been impossible to have 4.10.2, because of #2713

**Closed as completed** 2017-02-19 11:31 UTC
