### ISSUE TITLE
Select & Execute requests from collection or folder

### ISSUE THREAD

**Issue by vgosai86** [a85/POSTMan-Chrome-Extension#5566] opened 2018-11-25 02:12 UTC
We can run requests from folder or collection in a runner. It'd good to have a GUI based option to not run all requests within folder/collection and have checkbox to select or unselect request. For ex. I want to run only failed requests. I know I can do it runner but due to dependency with other request I'd have to run other requests which are passed. So, It'll be good to have an checkbox where I can just select and run only selected.

**Comment by brock** [comment] 2019-03-08 15:29
I'd like to add a more explicit request here: being able to click a run icon on a folder like in collections.

The use case is a folder for logging into an application so I can test a new endpoint _before_ running the whole collection 

<img width="296" alt="run_folders" src="https://user-images.githubusercontent.com/654725/54037780-9141ae00-4184-11e9-87ca-a49afcb2c227.png">

**Comment by saswatds** [comment] 2019-05-21 19:43
Duplicate of #6360 #2392

Closing this issue to track the feature at a single place

**Closed as completed by saswatds** 2019-05-21 19:43 UTC
Labels: feature, collection-runner, product/runtime
