### ISSUE TITLE
Request throws Error: read ECONNRESET error

### ISSUE THREAD

**Issue by vkjain603** [a85/POSTMan-Chrome-Extension#10641] opened 2022-02-08 14:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

<img width="938" alt="image" src="https://user-images.githubusercontent.com/31352238/153007607-20d3b834-d7a5-4e18-8c92-9f4a3e3a055f.png">

I'm getting "Error: read ECONNRESET" error while hitting request.

Application is configured for certificate authentication.
Certificate is installed and added in settings-> certificate
ssl enabled in application
Application is configured to accept certificate by Changing SslFlag value in ApplicationHost.config
<img width="298" alt="image" src="https://user-images.githubusercontent.com/31352238/153008071-f172e213-0eb5-48fe-b928-a91c53af31de.png">

Application is initialized properly and working.

Please guid me if something is missing here.

### Steps To Reproduce

1

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

**Comment by jkdba** [comment] 2022-02-09 22:40
I have also identified this error, it happens on any type of request method and only every other request. 

The issue seems to be a combo of having the no-cache header enabled and a request url length over 64 characters.

Turning off the no-cache header option and testing again the issue goes away, or if you reduce the url character length to < 65 it also goes away.

In addition I tested against a kestrel and IIS express endpoint and found when the failure occurs it never makes it endpoint which make sense as the error typically client side.

running version:

## Environment Information

- Postman for Windows
- Version 9.13.1
- UI Version 9.13.0-prod194533-220207-0659
- Desktop Platform Version 9.13.0
- Architecture x64
- OS Platform win32 10.0.22000

**Comment by shubhbhargav** [comment] 2022-02-16 08:51
@jkdba @vkjain603 Can you please confirm that the same request is running via curl? Just trying to identify if it's an issue on the server application side or the Postman client side.

**Comment by jkdba** [comment] 2022-02-23 18:18
@shubhbhargav confirmed I am able to run the same request from curl and aspnet core http client no issue.

Also to note after the recent update, turning off the no-cache header work around no longer prevents the issues.

**Comment by shubhbhargav** [comment] 2022-02-24 08:20
@jkdba I see. Can you please share a screen recording of the issue and logs (ref: https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs)? This will help debug it further. You can share these with us at help@postman.com

**Comment by jkdba** [comment] 2022-03-21 20:50
@shubhbhargav  I updated to Postman 9.15.2 and I cannot reproduce the problem anymore.

**Comment by shubhbhargav** [comment] 2022-03-22 05:04
Thanks for the confirmation @jkdba. Closing this ticket as of now.

**Closed as completed by shubhbhargav** 2022-03-22 05:04 UTC
Labels: product/runtime

**Comment by sabir-atrule** [comment] 2023-08-16 12:10
When I host the project on iis it works fine but when i host it on plesk it give the error
 ( Could not get response Error: read ECONNRESET) 
web api in .net core 6 c#

**Comment by akhiljagtap** [comment] 2024-03-08 08:41
does postman is running on windows 32 bit
