### ISSUE TITLE
Postman Think Double Slash Are Link

### ISSUE THREAD

**Issue by iqb-dawn** [a85/POSTMan-Chrome-Extension#11307] opened 2022-09-29 17:47 UTC
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have recently hit Postman issue to think double slash are URL and show wrong value in pretty mode.

https://stackoverflow.com/questions/73897506/asp-net-core-5-response-json-and-input-json-encoding-issue

![image](https://user-images.githubusercontent.com/87642965/193104405-1be10af3-ff54-44cd-95fa-2a5edca8423d.png)

But if you go in Raw,

![image](https://user-images.githubusercontent.com/87642965/193104492-28815a64-a989-45cf-8a88-881340e5b08d.png)

The problem is that I copy pasted pretty value without realizing that it has been processed and changed by Postman. 

I am filing a bug as I thought lot of users will face the same issue.

### Steps To Reproduce

Any request that returns double slash like below,

```
{"str":"h24KFS69\\pucBJH3x2ov+MAj\\/JWq/UBt3EjhKGUtBM="}
```

### Screenshots or Videos

Screenshot attached above.

### Operating System

Windows

### Postman Version

9.31.13

### Postman Platform

Postman App

**Comment by DannyDainton** [comment] 2022-09-29 20:27
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/7004

**Closed as completed** 2022-09-29 20:27 UTC

**Comment by iqb-dawn** [comment] 2022-09-30 06:56
I dunno if they are same but if you see JSON response in Pretty and JSON response in Raw, they are different, means if someone copy from Pretty they are copying wrong value.
