### ISSUE TITLE
cURL code for AWS SigV4 generates incorrect signature when environment variable is used in the URL

### ISSUE THREAD

**Issue by ratpik** [a85/POSTMan-Chrome-Extension#8611] opened 2020-06-09 13:12 UTC
**Describe the bug**

Two similar requests with the only difference being one uses an environment variable in the URL and the other does not. When cURL code is generated for this, the request that uses the environment variable fails to authorize due to invalid AWS Signature.

**To Reproduce**
1. Create an AWS Auth request without using any environment variables
2. Generate cURL code and test it out. This works.
3. Replace the request URL with an environment variable whose value is set to the request URL used in Step 1
4. Generate cURL code and test it out. This fails.

**Expected behavior**
The generated code should work with environment variables

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.25.0]
 - OS: [e.g. macOS Cataline 10.15.2]

**Comment by sjaeger-lxo** [comment] 2022-04-01 09:47
This bug is still present and quite confusing. You cannot generate a curl snippet and use it or manually copy the Authorization header and use for another request.

I can confirm that when a env variable is used for SecretKey then the resulting signature string in the Authorization of the auto-generated headers seems to the be pre-calculated using the variable name and not its value. It is only the SecretKey. Using env vars for AccessKey is properly resolved.

**Comment by dhwaneetbhatt** [comment] 2023-02-09 05:40
@sjaeger-lxo I tested this in the latest version of Postman, and it works for me. I'd like to add the steps here for clarity.

1. Add a URL to request to AWS (I tested using Lambda Function URL) in the request bar
3. Add AccessKey to an environment (in current value)
4. Add SecretKey to an environment (in current value)
5. Choose AWS Signature as the auth type
6. Select the environment and add access key and secret key values from the environment
7. Try sending the request - it works
8. Generate cURL snippet - I verified that the signature in the request header is the same as the one in the cURL
9. Copy the cURL snippet and try it - it works

If you are doing anything different, I would love to know the steps, or would you please mention the version and OS of the Postman client you're using? Screenshots would also help.

**Comment by akshaydeo** [comment] 2023-02-15 07:42
@sjaeger-lxo As mentioned by @dhwaneetbhatt, we cannot reproduce this on the latest version of the Postman app. I am closing this issue for now, but feel free to re-open it if you are still facing this issue 🙇‍♂

**Closed as completed by akshaydeo** 2023-02-15 07:42 UTC
Labels: bug, product/codegen
