### ISSUE TITLE
Disable requests / Select what requests should run in runner 

### ISSUE THREAD

**Issue by pelmered** [a85/POSTMan-Chrome-Extension#1467] opened 2015-09-30 14:54 UTC
It would be nice to be able to select what requests you want to run in the collection. I usually don't want to run all the requests in my collection and it doesn't work so well to split up the the requests in multiple collections either.

**Comment by kurtfm** [comment] 2015-11-12 19:58
I agree.  Right now I am using folders to be able to selectively run blocks of tests. Still would be cool to be able to flag certain tests for disable.

**Comment by srbangre** [comment] 2016-01-21 18:52
+1

**Comment by vfedorin** [comment] 2018-05-21 14:45
+1

**Comment by Jai-Gogineni** [comment] 2018-09-10 11:21
Any progress on this please ?

Thanks !

**Comment by saswatds** [comment] 2019-05-21 19:47
Duplicate of #6360 #2392

Closing this issue to track the feature at a single place

**Closed as completed by saswatds** 2019-05-21 19:47 UTC
Labels: feature, collection-runner, product/runtime
