### ISSUE TITLE
Web Sockets Support (Socket.io)

### ISSUE THREAD

**Issue by Kaffiend** [a85/POSTMan-Chrome-Extension#3186] opened 2017-06-20 21:12 UTC
Would be nice if Postman had a way to test web sockets, like socket.io. Register listener events and send events to test the response. We use a combination of sockets and api calls in out applications and having that in one tool of which we already use would be fantastic! Perhaps in the form of a plugin?

**Comment by kamalaknn** [comment] 2017-06-21 09:16
Hey @Kaffiend 

Thanks for sending in your feedback. 

This would be nice to have. I am tagging this as a feature request. @a85 can clarify on the roadmap for this.

**Comment by akshay2604** [comment] 2017-11-07 14:10
Any updates on this?

**Comment by Kamikadze4GAME** [comment] 2018-03-05 12:25
I would be grateful! Please...

**Comment by claytonbez** [comment] 2018-06-13 07:15
For those looking for an interim solution until Postman has Socket.io support, here is a link to a Socket.io client tool on github. Works for me. [https://github.com/amritb/socketio-client-tool](https://github.com/amritb/socketio-client-tool) , it is open source so it might inspire a roadmap for this.

**Comment by asleepysamurai** [comment] 2019-03-07 08:48
I've run into this issue too, and I finally created my own barebones GUI for testing websockets. It's called Socket Wrench, it supports

- multiple concurrent connections to servers (with all responses and connections displayed in the same view),
- comprehensive message history to enable easy re-use of messages, and
- custom headers for the initial connection request.

It's available for Mac OS X, Windows and Linux and you can get it from [here](https://asleepysamurai.com/articles/socketwrench?ref=github/postman-app-support/issues/3186).

**Comment by a85** [comment] 2019-12-01 06:54
Closing as duplicate of #4009 as that has more upvotes.

**Closed as completed by a85** 2019-12-01 06:54 UTC
Labels: feature, streamed-responses, protocol/websocket

**Comment by shamasis** [comment] 2021-07-30 19:50
https://blog.postman.com/postman-now-supports-socket-io/ - yay! We have Socket.io support now!

**Comment by yarcowong** [comment] 2021-11-25 08:37
Hello, just want to know does postman support to choose different socket.io client version?
For I get
`Error: It seems you are trying to reach a Socket.IO server in v2.x with a v3.x client. Switch the client version from request settings.`
This error~

----

Oh, I found the settings~ But it is really hard to find those informations from google~
![image](https://user-images.githubusercontent.com/86391690/143407877-98e30c57-fecb-47de-9803-8f69c335fc46.png)

**Comment by codenirvana** [comment] 2021-11-25 08:45
@yarcowong Thanks for the feedback.

We'll improve the error message and possibly add a CTA to auto-switch the version and reconnect.

**Comment by yarcowong** [comment] 2021-11-29 01:44
@codenirvana And also any document on using it?
I know how to use raw websocket, but don't know how to use socket.io in postman (and cannot find the document anywhere). I mean for example:
![image](https://user-images.githubusercontent.com/86391690/143795921-836f6d2a-e6c0-4c2d-b841-ca9a314035d8.png)
This is what I send in chrome.
I don't know which one is right when using postman:
![image](https://user-images.githubusercontent.com/86391690/143796290-14715085-6d0a-42ec-a49b-345b728ac2e6.png)
When choose `socket.io` method not `Raw`. 
 Thank you~
