### ISSUE TITLE
Option for turning off save confirmation

### ISSUE THREAD

**Issue by mlambley** [a85/POSTMan-Chrome-Extension#3386] opened 2017-08-15 01:39 UTC
## App Details:
```
Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 60.0.3112.90
```

## Issue Report:
Previously I could close tabs without an extra button click. Now I must also click on "Don't Save". 

I would appreciate an option for "Don't ask me again", either on the dialog box itself or in the settings.

![postman save](https://user-images.githubusercontent.com/17264636/29298874-4b3f8aa4-81ae-11e7-97e6-c3e053659eb1.png)

**Comment by prashantagarwal** [comment] 2017-08-15 06:52
@mlambley Thanks for the suggestion. We will look into this and try to release this enhancement in upcoming versions.

**Comment by jamesyarrington** [comment] 2017-08-15 20:17
+1
My previous workaround was to right click a tab and select `Close All Tabs`, then hit spacebar for each popup.  This worked because `Don't Save` was selected by default.
I've now just noticed that `Save` is now the default selection, so my spacebar workaround no longer works.
I'm not looking forward to the next few weeks where I find all the changes that I did not mean to save!

**Comment by robolivable** [comment] 2017-08-16 19:53
It seems unnecessary for the "Do you want to save?" popup to be default behavior in the first place.

I would rather just have a little floppy disk button that takes me directly to the "Save request" prompt instead.

Edit:
Oh..
![screen shot 2017-08-16 at 3 57 35 pm](https://user-images.githubusercontent.com/7831876/29382790-c721803a-829b-11e7-9da0-f7a26131711c.png)

**Comment by njLT** [comment] 2017-08-17 04:09
+1
My coworkers and I really hate this dialog box

**Comment by bhawna2109** [comment] 2017-08-17 05:01
Hi everyone - sorry for the trouble 😓  . We understand how this can be annoying, and are actively working on some improvements there. Thanks so much for all the suggestions and patience - we'll post an update here once we push out a usability fix for this very soon :)

**Comment by mlambley** [comment] 2017-08-17 05:19
Thank you for your attention to this matter, Bhawna. I look forward to seeing the fix in the future.

**Comment by ronaldso55** [comment] 2017-08-30 21:02
Please fix this issue.  Why am I being asked if I want to save my unsaved changes?  This is about to drive me to use an alternative software.  Combining with the fact that it takes over 15 seconds when I turn on the application, POSTMAN is not going to the right direction.  I love what you guys did in the past.

**Comment by SamvelRaja** [comment] 2017-08-31 04:37
@ronaldso55 this seems odd. Can you provide us a screen cast of whats happening.. would be very useful to debug much faster.

**Comment by bhawna2109** [comment] 2017-08-31 12:04
@ronaldso55 Sorry to hear that. We are actively working on the improvements around this and it'll be fixed in the next version.

**Comment by djejaquino** [comment] 2017-08-31 16:50
@bhawna2109 Postman simplicity used to be its awesomeness. Thanks for looking into this.

**Comment by APrasser** [comment] 2017-09-26 06:49
100% agree with this feature request.

**Comment by johnnorton** [comment] 2017-10-04 21:38
+1

**Comment by bhawna2109** [comment] 2017-10-09 07:12
Hi guys, ability to force close all tabs is now supported in our latest version [(V 5.3.0)](https://www.getpostman.com/apps#changelog). 🎉 Clicking on the three dots next to the '+' icon brings up a dropdown with options to manage the tabs you're currently working with.

The last option in the dropdown - 'Force close all tabs' - will close all the tabs without prompting to save each time - 
![image](https://user-images.githubusercontent.com/14976346/31327774-eca078a2-acee-11e7-8a7d-52a290bef376.png)

Additionally, you can use CMD/CTRL + ALT + W shortcut to force close the currently active tab. Holding down the ALT key and clicking on the 'x' icon also closes a tab without bring up the save modal.

**Comment by djejaquino** [comment] 2017-10-10 14:02
@bhawna2109 First of all, thanks for implementing this.
But I have to say, that is not what we were expecting. 
A simple option to disable the save confirmation would be much simpler and effective.
Please, keep this issue open until it happens.

Thanks

**Comment by robolivable** [comment] 2017-11-16 19:00
Adding some noise to this thread as I'm still being pestered by these dialogs. Please fix soon, thanks.

**Comment by peeveeone** [comment] 2017-11-24 07:29
Would like see an option to disable the dialog all-together, I rarely want to close all tabs, just the ones I cannot reuse and are created by following links in my test cases.

**Comment by mlambley** [comment] 2018-01-04 06:24
Could this issue be given priority, perhaps even fixed in the next version? It is quite a significant inconvenience. Thank you.

**Comment by skyboyer** [comment] 2018-01-17 13:31
#2195 is about the same

**Comment by doschi** [comment] 2018-01-19 08:37
I would also appreciate that option.
The Dialog is quite annoying

**Comment by DedMorozzz** [comment] 2018-01-23 21:36
+1

**Comment by t-mdo** [comment] 2018-01-27 20:14
Hey guys. Still no news about that update ? It's been quite a while now.

**Comment by kyeotic** [comment] 2018-02-15 16:41
Still looking for an option to disable this prompt entirely. CMD+ALT is an awkward key combo to use for people with hands.

**Comment by iagolaguna** [comment] 2018-03-07 16:51
+1

Postman it grateful but, I really hate this dialog and I still waiting for "Don't ask again" issue.

[]'s

**Comment by nazarkryp** [comment] 2018-04-25 10:47
Remove please that "Do you want to save" feature. It's so annoying. Implement thing like Ctrl+Shift+T in case if someone accidentally closed tab, there is no need to ask me on each tab if i wanna save it

**Comment by Couragyn** [comment] 2018-04-26 23:52
+1 I hate that dialogue so much

**Comment by derAndi5** [comment] 2018-05-03 09:49
+1

**Comment by lxtzfr** [comment] 2018-05-17 22:11
This pop up is really annoying, it's wasting time.

**Comment by kikkauz** [comment] 2018-07-12 11:13
Yes please remove it 👍

**Comment by xuther** [comment] 2018-08-07 14:58
:+1:

**Comment by foxbaucia** [comment] 2018-08-10 06:36
Please, this might be Priority 1!
I constantly lose my saved request.

**Comment by bahatron** [comment] 2018-09-24 13:10
+1 to this

**Comment by kamalaknn** [comment] 2018-09-24 13:57
Hi,

Sorry for the delayed response.

We have been working on a refactor of out tabs implementation. We have been thinking about this as well.

We are planning to add a function to `Reopen recently closed tab`. This will make sure users do not lose valuable work when they accidentally close a tab. With that functionality in place we can allow users to skip the confirmation step when closing tabs.

We will be releasing these in the near term over the next couple of releases. 

Thanks for your patience and support 😄 

cc @vkaegis

**Comment by tangyouze** [comment] 2018-09-27 05:15
A workround use autohotkey is as follows, so I can hit ctrl-w to close tabs.

```

#IfWinActive, Postman
{
    ^w::
        Send ^!{w}
    return
}

```

**Comment by sujayvenaik** [comment] 2018-10-11 15:42
Hey, I would like to push an update here.
We have brought this feature to our short-term roadmap and would be coming out soon.

**Comment by mkrell** [comment] 2018-11-02 20:07
@sujayvenaik YESS! This popup is very annoying.

**Comment by a85** [comment] 2018-12-07 05:14
Closing as duplicate of #2195. This is shipping in the next version.

**Closed as completed by a85** 2018-12-07 05:15 UTC
Labels: feature, tabs
