### ISSUE TITLE
Postman proxy: "Something went wrong. And we are reporting a custom error message."

### ISSUE THREAD

**Issue by joeminicucci** [a85/POSTMan-Chrome-Extension#5889] opened 2019-02-06 19:13 UTC
I am trying to run the Postman built in proxy on the native OSX app to capture traffic from my browser. Currently, I am able to do so (the traffic shows up in Postman) however with every request made to my locally hosted web app, I receive an otherwise blank HTML response with the message:

`Something went wrong. And we are reporting a custom error message.
`

The web app has self-signed SSL cert, and I tried to both enable/disable the "SSL certificate verification setting".

The only current workaround is to use the deprecated Postman Chrome app / Interceptor, which works as expected, however is _non-optimal_. Please advise.

Environment:
Postman native Version 6.7.3 (6.7.3)
macOS High Sierra 10.13.6

**Comment by joeminicucci** [comment] 2019-02-11 16:35
https://i.gifer.com/qI.gif

**Comment by numaanashraf** [comment] 2019-02-18 15:05
@joeminicucci Could you provide the detailed logs? You can find these at `View > Developer > View logs`. "electronProxy" errors in the logs will help us triage and fix this issue fast.

**Comment by joeminicucci** [comment] 2019-02-21 18:47
@numaanashraf Thanks for the response. I will get that over early next week.

**Comment by joeminicucci** [comment] 2019-02-23 05:04
@numaanashraf I made 4 GET requests after starting with a clean log, and got the following results:
```
./main.log:[4215][1550898068989][main][error]["electronProxy - Error proxying https",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":443,"name":"Error","message":"connect ECONNREFUSED 127.0.0.1:443","stack":"Error: connect ECONNREFUSED 127.0.0.1:443\n    at Object.exports._errnoException (util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)"}]
./main.log:[4215][1550898071433][main][error]["electronProxy - Error proxying https",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":443,"name":"Error","message":"connect ECONNREFUSED 127.0.0.1:443","stack":"Error: connect ECONNREFUSED 127.0.0.1:443\n    at Object.exports._errnoException (util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)"}]
./main.log:[4215][1550898082627][main][error]["electronProxy - Error proxying https",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":443,"name":"Error","message":"connect ECONNREFUSED 127.0.0.1:443","stack":"Error: connect ECONNREFUSED 127.0.0.1:443\n    at Object.exports._errnoException (util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)"}]
./main.log:[4215][1550898087657][main][error]["electronProxy - Error proxying https",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":443,"name":"Error","message":"connect ECONNREFUSED 127.0.0.1:443","stack":"Error: connect ECONNREFUSED 127.0.0.1:443\n    at Object.exports._errnoException (util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)"}]
```

The web app is up and running, and as stated before over a self-signed SSL cert. Other sites seem to be working. I tried clones of the same app on several external AWS instances and received the same response. Any ideas?

**Comment by joeminicucci** [comment] 2019-03-15 20:22
Temporary solution: 
Use two proxies, i.e. first proxy to a reverse proxy agent such as Burp Suite and then upstream Burp's requests over to Postman's. Not optimal. Note that I can grab the requests this way however the response is still scrubbed with the original error code

**Comment by JanneckLange** [comment] 2019-05-14 13:03
I run into the same error with the newest version of Postman today. Error Log exact the same except the port (`"port":80`) for me

**Comment by ClaysonIO** [comment] 2019-05-15 15:52
I'm running into an identical issue, also on the native OSX app.

```
[572][1557935398098][main][error]["electronProxy - Error proxying http",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":80,"name":"Error","message":"connect ECONNREFUSED 127.0.0.1:80","stack":"Error: connect ECONNREFUSED 127.0.0.1:80\n    at Object.exports._errnoException (util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)"}]
[572][1557935398208][main][error]["electronProxy - Error proxying http",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":80,"name":"Error","message":"connect ECONNREFUSED 127.0.0.1:80","stack":"Error: connect ECONNREFUSED 127.0.0.1:80\n    at Object.exports._errnoException (util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)"}]
```

**Comment by codenirvana** [comment] 2019-09-18 19:04
Duplicate of #3661

**Comment by chughmayank** [comment] 2020-09-21 09:17
hey @joeminicucci  and @ClaysonIO , is this something you are still facing on the latest version of postman app?

**Comment by abhinaba-ghosh** [comment] 2022-04-27 11:47
Hey @joeminicucci 

I'm going to close out this issue for now but we can open it up again if you/other users are facing the same issue.

**Closed as completed by abhinaba-ghosh** 2022-04-27 11:47 UTC
Labels: Proxy, blocked/need-info, product/capture-proxy

**Comment by ghnzbd** [comment] 2024-05-14 02:41
Just modify the port number of the project. For example, the port number of tomcat。
