### ISSUE TITLE
Can't copy from textarea using right click -> copy 

### ISSUE THREAD

**Issue by boorac** [a85/POSTMan-Chrome-Extension#3760] opened 2017-11-09 13:36 UTC
## App Details:

```
Postman for Linux
Version 5.3.2
linux 4.4.0-98-generic / x64
```

## Issue Report:
 1. I encountered the bug as soon as the standalone app was installed.
 2. Expected behaviour:
I should be able to copy from text editors, a selection of any size using right click -> copy
 3. No console errors are reported
 
## Steps to reproduce
1. Enter a textarea
2. Select text using mouse
3. Right click --> Copy
4. The selection is not in the buffer

**Comment by deepakpathania-zz** [comment] 2017-11-10 17:30
Hey @boorac, I wasn't able to replicate this behaviour locally. Can you specify more clearly what you mean by the `textarea` here? The body tab of the builder or something else?

**Comment by vlorenzosoleri** [comment] 2017-11-11 22:03
@deepakpathania I have the same bug, also on the standalone app. 

App details:

```
Postman for Linux
Version 5.3.2
linux 4.9.0-4-amd64 / x64
```
To reproduce it:

1. Send a request that returns some JSON
2. Set the "Pretty" option ON on the Response Body section (I checked with Raw ON and the bug doesn't happen)
3. Try to copy part of the response body from the response text area with right-click. It won't work

**Comment by deepakpathania-zz** [comment] 2017-11-12 07:13
Hey @vlorenzosoleri, thanks for the steps, I was able to reproduce this locally. 
In the screenshot below, after choosing to copy the selected part, it doesn't work. 

![screenshot from 2017-11-12 12 34 46](https://user-images.githubusercontent.com/15071438/32696733-08013aa6-c7a6-11e7-98de-9b18c909e477.png)

Also, duplicate of #3691

**Comment by deepakpathania-zz** [comment] 2017-11-14 13:07
@madebysid Mind looking into this? Thanks.

**Comment by SamvelRaja** [comment] 2017-11-15 09:57
Tracking in #3691

**Closed as completed by SamvelRaja** 2017-11-15 09:57 UTC

**Comment by Przemek625** [comment] 2018-10-11 07:10
There is still this annoying problem.
