### ISSUE TITLE
Feature Request: Request/Response panes side-by-side rather than vertical split

### ISSUE THREAD

**Issue by worrel** [a85/POSTMan-Chrome-Extension#2130] opened 2016-06-16 15:19 UTC
i often have very long JSON requests & responses that are relatively narrow.  It would be easier to view them side by side rather than having the response follow the request body.  It would nice to have an option to specify horizontal or vertical split layout.

**Comment by bondarevpavel** [comment] 2016-09-16 12:00
WORKAROUND: In OS X I've just added style to _/Applications/Postman.app/Contents/Resources/app/js/requester.js_ file in _exports.push_:
`
.request-editor,
.response-viewer {
    width:50%;
    float:left;
} 
`

**Comment by johndkane** [comment] 2016-09-30 18:00
Issue #2345 mentions this feature is being worked on - it seems to be a duplicate of this issue.

**Comment by a85** [comment] 2016-10-12 22:19
Closing as duplicate of #2345. This is coming soon everyone with a tighter theme!

**Closed as completed by a85** 2016-10-12 22:19 UTC
