### ISSUE TITLE
optional activate window when application finish Launching

### ISSUE THREAD

**Issue by ionutale** [a85/POSTMan-Chrome-Extension#9050] opened 2020-09-12 15:01 UTC
90% of the time postman is a secondary application that i use.
It is very annoying  that while i do something, when postman finish launching it will just become focus and i it interrupts me from my work.

postman it is a great application, but it is not my only, main or most important application 

can i choose to open it and get back to it later?

---

imagine while you where doing research on chrome, and opening 5 tabs from google with `cmd+click` and when each page finish loading just become active and take focus.

annoying, right?

please consider adding this option into the preference

**Comment by agdgdh** [comment] 2020-09-12 17:50
I certainly force type appear ,question 10times same setup interfere oath 1time pass word master pass lose.
It's nonsense.

**Comment by ionutale** [comment] 2020-09-12 17:57
Can you elaborate?

Inviato da iPhone

**Comment by DannyDainton** [comment] 2020-09-14 11:57
Closing this as it's a duplicate of #6849

**Closed as completed by DannyDainton** 2020-09-14 11:57 UTC
Labels: duplicate, installation
