### ISSUE TITLE
export websocket collection

### ISSUE THREAD

**Issue by Balagopal-datascientist** [a85/POSTMan-Chrome-Extension#12098] opened 2023-06-12 06:43 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

export websocket collection

### Describe the solution you'd like

export websocket collection

**Comment by codenirvana** [comment] 2023-06-15 12:09
Duplicate of #11252

**Closed as completed by codenirvana** 2023-06-15 12:09 UTC
Labels: feature, protocol/websocket, product/api-client
