### ISSUE TITLE
Postman Test Breaks for mutliple async pm.SendRequest call

### ISSUE THREAD

**Issue by hari2anand** [a85/POSTMan-Chrome-Extension#6197] opened 2019-04-01 13:41 UTC
I tried to write a loop for testing all the hal links that were got in the response, but could see the Postman is not able to process or keep the test alive for all loop iterations, not sure is either because of any existing timeouts for each run, but I could clearly see the test in request is not completed as couldn't get the next steps done after awaiting the response

**To Reproduce**
(have attached a sample script)
1. Try to get a hal response with more- than 3 links
2. use the script shared /suggest any change to the script
3. Send Request

**Expected behavior**

**Screenshots**

script used:
var Test_request_response_whole = pm.response;
var Test_request_response = pm.response.json();
var ConsolidatedResponse=[];
var UserToken=pm.globals.get("user_token"); 
var postTest_request_schema= pm.variables.get("post_Test_request_schema");
main()
async function main(){
    try{
        if(Test_request_response.message.match(/^Test_request with*.*already exist$/))
        {
            console.log(Test_request_response.message+". Switching to Find Test_request for the User");
            postman.setNextRequest('GetTest_request-UserID');
        }}catch(err){
        pm.globals.set("Test_requestID",Test_request_response.resourceId)
        await runForHalLinks();
        console.log("FINISHED");
    }
}

async function runForHalLinks(){
    schema_test("PostTest_request", postTest_request_schema, Test_request_response_whole);
    for  (var link in Test_request_response._links) {
        console.log("Started Validation for :"+link);
        
        var callLink=Test_request_response._links[link].href;
        var callMethod=Test_request_response._links[link].type;
        var resourceName, schema;
        
        if (link == "self"){
            pm.globals.set(request.name+"_url", callLink);
            schema=pm.variables.get("post_Test_request_schema");
            resourceName="GetTest_request";
        }
        else{
            pm.globals.set(link+"_url", callLink);
            schema= pm.variables.get("get_"+link+"s_schema");
            resourceName="Get"+link;
        }
        let run_response = await sendRequest(callLink,'GET',null);
        await schema_test(resourceName, schema, run_response);
    }

}

async function schema_test(resource,schema,response)
{
    console.log("Schema Valiation For- "+resource)
    var testTitle = resource+" Response conforms to schema";
    await pm.test(resource+"-Schema_Validation", function(){tests[testTitle] = tv4.validate(response, schema);})
    
}

async function sendRequest(reqURL,reqMethod,reqBody,callback){
    var call = {
        async:false,
        url:reqURL,
        method: reqMethod,
        header: {
            "token":UserToken,
            "Content-Type":"application/json"
        },
        body:reqBody
    };
    return new Promise( (resolve) => {
        console.log("Send req")
            pm.sendRequest(call, (err, res) => {
                console.log("RECEIVED", err, res)
                 resolve(res.json());
            });
    });
}

**App information (please complete the following information):**
 - App Type:  Native App 
 - Postman Version : 7.0.7
 - OS: Windows 10

**Additional context**

**Comment by codenirvana** [comment] 2019-04-01 17:23
Duplicate of #4131

@hari2anand async await isn't supported yet. Follow the mentioned thread for updates.

**Closed as completed by codenirvana** 2019-04-01 17:23 UTC
