### ISSUE TITLE
postman crashed in collection runner with insert csv file that has numbers 

### ISSUE THREAD

**Issue by hanyghazal** [a85/POSTMan-Chrome-Extension#950] opened 2015-03-04 15:36 UTC
the versions from 2 days ago until now, it is a buggy versions and effect my work and west a lot of my time,

please let me know when these critical defects will solved, my work on postman are hold

**Comment by hanyghazal** [comment] 2015-03-04 15:39
also in json files that has number not strings between double quotes .

and send the  request twice

**Comment by abhijitkane** [comment] 2015-03-04 16:50
Apart from numbers in the CSV file, what other issues are you facing?

We'll push a fix for these soon.

**Comment by hanyghazal** [comment] 2015-03-04 16:58
Also in json files when the numbers in file. And also the updated that done in tests or in request URL and a collection runner is opened. The updates not come to the run. Must close the collection runner then open it again . I open issue for this but not remember the issue I'd.

Also the defect if environment variable

**Comment by jdfriedman** [comment] 2015-03-04 20:51
@abhijitkane I'm seeing this one too. Here's the scenario: I'm trying to update a value on a large number of records. My request looks something like this:

curl -X GET -H "X-Futuresimple-Token: TOKEN" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 5934c995-7490-ad55-d897-8a916be4da17" https://app.futuresimple.com/apis/sales/api/v1/deals/{{ID}}.json

and the CSV looks something like this:

ID
123
124
125
126
127
128

Here's a screencast of what happens: http://monosnap.com/file/mMQmp8T8sfty4CKRcWcmDVJvpIU4tl

**Comment by richardbrammer** [comment] 2015-03-04 22:56
I can confirm, that the collection runner does not start and just **hangs up, if the testdata JSON includes values that are not within double quotes** (e.g. booleans)

**The following JSON produces the misbehavior** (timeout, no error message):
> [{
>   "valid": true
> }]

When the Error occurs, the runner just stays like in this screenshot:
![screen shot 2015-03-04 at 23 51 59](https://cloud.githubusercontent.com/assets/3230012/6495350/7fa9ce7c-c2c9-11e4-9eb8-aa361a453cb6.png)


This JSON **does not** hang the collection runner up *(but my tests are failing because of the unexpected value)*:
> [{
>   "valid": "true"
> }]

**Comment by abhijitkane** [comment] 2015-03-05 06:48
This has been fixed in version 2.0.4 of the app.
@richardbrammer can you confirm?

**Comment by abhijitkane** [comment] 2015-03-05 06:49
@richardbrammer Can you check with v2.0.4 of the app?

**Comment by jdfriedman** [comment] 2015-03-05 07:25
@abhijitkane as far as I can tell, my use case has been fixed with 2.0.4. Richard can probably speak to loading JSON files.

**Comment by richardbrammer** [comment] 2015-03-05 09:23
I'm still on 2.0.2 (packaged app) on Mac OS. How do I get the update? Chrome store does not update the app automatically and I can't find an update button or similar.

If I delete the app and reinstall, do I lose my settings/collections/history?

**Comment by abhijitkane** [comment] 2015-03-05 09:32
Deleting the app will lead to the loss of your data.

To force the update, you can go to "chrome:/extensions", enable "Developer Mode", and click "Update extensions now". It'll take upto a minute after that.

**Comment by richardbrammer** [comment] 2015-03-05 09:43
**2.0.4 resolves the issue** for me.
Thanks for the help with the update.

**Closed** 2015-03-05 19:17 UTC
