### ISSUE TITLE
After using find and replace, the changes save in Postman, but will not export with the changes

### ISSUE THREAD

**Issue by akaczinski** [a85/POSTMan-Chrome-Extension#6820] opened 2019-07-01 19:42 UTC
**Describe the bug**
I have a collection in my shared workspace, which, if I were to share, would not help showcase this bug, for reasons soon to be explained.

The issue seems to have occurred after I performed a Find & Replace using the built-in Find feature in Postman. I searched for all uses of a certain variable in the request URLs of my tests, and replaced about half of the tests in my collection with the new one. After clicking replace, the changes appear saved in Postman. If I duplicate the collection, the changes appear saved, with the correct variable changes.

However, if I export the collection to json, the old variable is still in use. For some reason, when exporting, it is not exporting the changes performed by the Find feature.

I confirmed this by importing the json into another workspace, and, as expected by this bug, the old variable is present.

The API Docs generated by Postman also show the OLD variables, not the new ones that should be saved.

**To Reproduce** ( I have not attempted to reproduce but this is my theory on how to do so. I need to focus my time on fixing my tests because it's causing a very large and important test to fail. )
1. Create 77 requests, with a variable like {{companyId}} in the URL, all in one collection. Add half of the requests to three folders deep (e.g. Collection -> Folder 1 -> Folder 2 -> Folder 3 -> Request). Add the other half to a different three folders deep, same method.
2. Highlight companyId in one of the requests, right click, and click "Find"
3. Manually select half of the requests that appear in this page
4. Enter text into the "Replace With" field, such as premiumCompanyId
5. Click "Replace" with the 35 or so selected tests
6. Export the collection
7. Import the collection to a different workspace, or view the json and confirm the bug has occurred and the changes made by the Find and Replace are not saving when exported.
8. Confirm that, when a collection is duplicated, the new variable still appears, however, it is still not exporting.
9. Now, modify one of the variables that was changed via Find & Replace. Note that, when modified directly, and then saved, this request will correctly export data as expected.

**Expected behavior**
Postman should always export what the user sees.

**App information (please complete the following information):**
 - Native
 - v7.2.2
 - OS: Windows 10

**Additional context**
I have no idea if this is related to working with large files and Find & Replace but I assume it is. It is also possible this is due to some weird cross compatibility between PostmanCanary, as I've had to switch back to using regular Postman recently. I verified that this bug is still occurring with the same collection in PostmanCanary when exported.

**Comment by preethammavin** [comment] 2019-07-02 04:55
@akaczinski I am unable to reproduce this, can you let us know if the following so that we can debug better
1) When you view the docs by clicking on `View in Web` do you see the changes reflected there?
2) The collection you are exporting does the collection reflect the changes in the variable edits that you made

**Comment by akaczinski** [comment] 2019-07-02 21:01
> @akaczinski I am unable to reproduce this, can you let us know if the following so that we can debug better
> 
> 1. When you view the docs by clicking on `View in Web` do you see the changes reflected there?
> 2. The collection you are exporting does the collection reflect the changes in the variable edits that you made

1. View in Web does not show the changes made from Find & Replace
2. Exporting the collection does not show the edits made from Find & Replace, neither in the json nor if I import it back into Postman.

Let me know if I can provide any more info, I'd really like to see this fixed.

**Comment by akaczinski** [comment] 2019-07-03 03:10
This is also happening with an environment file I'm using now. It's a fairly large file, about 80kb, and some of the changes I'm making are fairly small. I didn't use the Find & Replace on my environment file, so I now believe that is unrelated. There's just something about Postman not exporting small changes to large files.

**Comment by preethammavin** [comment] 2019-07-03 05:14
@akaczinski if you are not able to see it on Web and when you export, most likely reason would be if
the edits were not saved to collection. 

Can you check the things for me
1) In the find and replace you are on the collection section of it when you are replacing. Not on the tab.

If this does not solve it can you write to us at help@getpostman.com with logs to so that we can take a closer look with reference to the github id

User logs can be found view -> developer -> user logs.

**Comment by preethammavin** [comment] 2019-08-20 08:01
Closing the issue for now, do feel free to reopen the issue if it persists.

**Closed as completed by preethammavin** 2019-08-20 08:01 UTC

**Comment by akaczinski** [comment] 2019-09-11 19:18
Hi, I'm so sorry I missed your message before, all I saw was that it was closed.

I am in fact still experiencing this issue, and it's been causing some pretty annoying bugs. I will re-open it under the same name/description. 
Thanks!

**Comment by xk0der** [comment] 2019-09-12 01:27
Re-opened by @akaczinski here: https://github.com/postmanlabs/postman-app-support/issues/7307
