### ISSUE TITLE
Selecting large form-data file crashes app 

### ISSUE THREAD

**Issue by billy-g** [a85/POSTMan-Chrome-Extension#1031] opened 2015-04-28 17:50 UTC
I have a 250 MB IPA file -- selecting it with the file picker consistently crashes the packaged app.

**Comment by senjaliya** [comment] 2015-05-08 23:33
having large sized response like ( audio/image ~ 2mb) also crashes the app.
- just another memory related issue

**Comment by abhijitkane** [comment] 2015-05-09 07:03
@senjaliya what version of Postman are you using?

**Comment by senjaliya** [comment] 2015-05-10 00:11
@abhijitkane 
Here is the version detail from settings tab.
Version 2.0.25 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by a85** [comment] 2016-01-10 11:42
Closing this as a duplicate of #555. Will be tracked there.

**Closed as completed by a85** 2016-01-10 11:42 UTC
Labels: bug
