### ISSUE TITLE
problem with event listening for socket.io

### ISSUE THREAD

**Issue by forsmajor10** [a85/POSTMan-Chrome-Extension#12995] opened 2024-07-07 18:18 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When adding an event in the events section to listen to, and enabling it, when I click connect the listening is automatically disabled, for a situation where I need to listen to a "welcome" event that comes to connect this creates some problems

### Steps To Reproduce

1. open event tab in socket.io
2. add event and switch on "listen"
3. click connect button
4. switch disables listening at this moment

### Operating System

Windows

### Postman Version

v11.2.34

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ronork** [comment] 2024-07-08 06:22
Hey @forsmajor10 , thank you for reporting the issue.
I was able to reproduce the issue and will provide an update once a fix has been implemented. 
cc: @parthverma1

**Comment by ronork** [comment] 2024-07-08 06:26
This issue is a duplicate of: https://github.com/postmanlabs/postman-app-support/issues/12899

**Closed as completed by ronork** 2024-07-08 06:26 UTC
Labels: bug, product/api-client
