### ISSUE TITLE
Postman after update to 6.3.1 freeze loading

### ISSUE THREAD

**Issue by siryur** [a85/POSTMan-Chrome-Extension#4605] opened 2018-05-26 15:49 UTC
**Description**
After initialization, through UI or console (does not matter, because no errors are shown on both), the postman goes in a forever loading loop.
I tried to find any errors but nothing is shown except for the "Show DevToll (in current view)"

**To Reproduce**
There is no specific step to reproduce, because I've only updated the postman to the newest version. 

**Expected behavior**
Postman to load and show UI normally.

**Screenshots**
<img width="1440" alt="screen shot 2018-05-26 at 16 41 27" src="https://user-images.githubusercontent.com/12106023/40578003-b5d4a74c-6104-11e8-90eb-13001ef5bfbf.png">

**App information:**
 - Native App
 - Postman Version: 6.1.3
 - OS: macOS High Sierra 10.12.6

**Comment by ghost** [comment] 2018-05-27 05:41
Yes, I've also met with the same problem——The UI will be in the state of loading for quite a long time (about 5~10 minutes) each time.  The UI is frozen:(

I'm running on the Win 8.1 SP1 (Simplified Chinese，x86).

Here's the screenshot after opening it, it still stays in frozen window....
![default](https://user-images.githubusercontent.com/6959154/40582887-cb3aa7c0-61b4-11e8-80c9-b4a11f71df60.png)

Reinstalled but no help

**Comment by ilyaskhametov** [comment] 2018-05-27 06:53
I experience the same problem after update. I also tried to reinstall Postman app, no luck. Have empty scree n with a spinner appearing each second near to the mouse pointer. Windows 8.1, Postman 6.3.1. Any help?
![image](https://user-images.githubusercontent.com/19661877/40583267-f67f7a76-61ac-11e8-8d18-391cbd4196e5.png)

**Comment by RandomDude777** [comment] 2018-05-27 19:49
Yep also getting this win 8.1

**Comment by Matriz88** [comment] 2018-05-28 10:32
Same here, on win 8.1

If I try to open directly from command line (as suggested [here](https://support.getpostman.com/hc/en-us/articles/115005901149-My-Postman-app-won-t-start)) I get a lot of these logs:

`[20260:0528/122727.995:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-000000A96CBEF290]RENDER WARNING: texture bound to texture unit 0 is not renderable.
 It maybe non-power-of-2 and have incompatible texture filtering.
[20260:0528/122728.000:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000000A96CBEF290]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIU
M: invalid mailbox name
[20260:0528/122728.000:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-000000A96CBEF290]RENDER WARNING: texture bound to texture unit 0 is not renderable.
 It maybe non-power-of-2 and have incompatible texture filtering.
[20260:0528/122728.000:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000000A96CBEF290]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIU
M: invalid mailbox name
[20260:0528/122728.000:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-000000A96CBEF290]RENDER WARNING: texture bound to texture unit 0 is not renderable.
 It maybe non-power-of-2 and have incompatible texture filtering.
[20260:0528/122728.000:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000000A96CBEF290]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIU
M: invalid mailbox name
[20260:0528/122728.000:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-000000A96CBEF290]RENDER WARNING: texture bound to texture unit 0 is not renderable.
 It maybe non-power-of-2 and have incompatible texture filtering.
[20260:0528/122728.001:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000000A96CBEF290]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIU
M: invalid mailbox name
[20260:0528/122728.001:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-000000A96CBEF290]RENDER WARNING: texture bound to texture unit 0 is not renderable.
 It maybe non-power-of-2 and have incompatible texture filtering.
[20260:0528/122728.001:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000000A96CBEF290]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIU
M: invalid mailbox name
[20260:0528/122728.024:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-000000A96CBEF290]RENDER WARNING: texture bound to texture unit 0 is not renderable.
 It maybe non-power-of-2 and have incompatible texture filtering.`

**Comment by jemerald** [comment] 2018-05-28 22:58
There is a work around discussed here, fixed my problem.
https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

**Comment by sivcan** [comment] 2018-05-29 04:32
@siryur @RandomDude777 @MaleDong @Matriz88 @ilyaskhametov 
The issue is related to Nvidia GPU's being used in some windows machines.
As mentioned by @jemerald, kindly follow this https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621 as mentioned by @harryi3t 
We've released this fix with the 6.1.3 version so you wouldn't be needing the canary build.

In short, 
Since you guys are already on 6.1.3, you've to make a new environment variable called `POSTMAN_DISABLE_GPU` and set it to true and it should work then.
Follow the steps in that comment and let us know if it works for you.

**Comment by ghost** [comment] 2018-05-29 06:34
@jemerald & @siryur ：
Thanks to both of you! I did what you told us and everything seems going well with me again, the speed is very very fast than expected!

**Comment by RandomDude777** [comment] 2018-05-29 07:44
@sivcan @jemerald @siryur: Much appreciate the fix guys! confirmed working.

**Comment by sivcan** [comment] 2018-05-29 11:27
@MaleDong - Haha yes, we've made some major performance improvements!

Cool, so I'll close this issue then.

**Comment by siryur** [comment] 2018-05-29 11:36
Well, that flag didn't do anything to my app... Things are running the same.
Although, using the PostmanCanary version resolved the thing without added the env var. Something happened here and I don't know what/why. 

Well, if you want more information please tell me because I need to install the Postman app again.

**Comment by MaleDong** [comment] 2018-05-31 06:43
@siryur ：
Since you're using now Mac……What I can do is to let you down a version of postman from the official download page.

**Comment by harryi3t** [comment] 2018-05-31 07:02
@siryur Your issue is different than others who have commented in this thread.
Others were having an issue with the GPU. Adding that flag just disables it.
Unfortunately, the GPU issue got mixed up with yours.

Since the original issue you posted is different, I am reopening this.
 - As of now, I don't know the cause of this issue. Did you jump between an old and the new version of Postman?
 - Do you have all the data synced? If yes, you can delete/move the directory where Postman keeps the data. __Warning: If you delete that directory any unsynced changed will be lost forever!__ 
```
mv ~/Library/Application\ Support/Postman ~/Library/Application\ Support/Postman.bk
```

**Comment by Eli-Goldberg** [comment] 2018-05-31 12:51
Same happens to me on Ubuntu when I tried 6.1.3,
it just doesn't work at all.
I can't find older versions of Postman so I can't use Postman at all now.

**Comment by ghost** [comment] 2018-06-01 09:45
@Eli-Goldberg & @siryur ：

Here's the list of all kinds of versions, you can uninstall the latest one and reinstall a new one for a temporary fix until the official fixed this, hope this helps!

【For Linux】
1）https://dl.pstmn.io/download/version/6.0.10/linux64
2）https://dl.pstmn.io/download/version/6.0.10/linux32

【For Windows】
1）https://dl.pstmn.io/download/version/6.0.10/windows64
2）https://dl.pstmn.io/download/version/6.0.10/windows32

【For Mac】
https://dl.pstmn.io/download/version/6.0.10/osx64

**Comment by siryur** [comment] 2018-06-01 11:00
Well, @Eli-Goldberg, I've solved my problem with the [Postman Canary version](https://www.getpostman.com/canary). It worked like a charm 👍 

As for the @harryi3t comment:
> As of now, I don't know the cause of this issue. Did you jump between an old and the new version of Postman?

I'm not 100% sure, but I think I went from a 6.1.X to the 6.1.3 version. I'm not sure which of the previous version was, but I think I was in some 6.1 version.

> Do you have all the data synced? If yes, you can delete/move the directory where Postman keeps the data. Warning: If you delete that directory any unsynced changed will be lost forever!

Yea, I've all my data synced (at least postman says it like that 😛 ).
I've deleted all my data previously and it had the same behavior. But I wasn't sure I've deleted that folder.
So, I tried it and it worked now.
Now, I'm not sure if it was me that didn't delete that folder or if it was something on server-side.

**Comment by harryi3t** [comment] 2018-06-01 15:24
@siryur Glad that it worked! Closing this issue now

**Closed as completed by harryi3t** 2018-06-01 15:24 UTC
Labels: bug

**Comment by thetestgame** [comment] 2018-08-07 13:42
Still having this issue on version 6.2.3.

**Comment by kamilwlf** [comment] 2018-10-16 07:42
I have this issue again

**Comment by blowsie** [comment] 2019-06-11 09:37
I still have this issue
