### ISSUE TITLE
Request URL copy and paste doesn't track cursor location accurately

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#9141] opened 2020-10-07 18:34 UTC
**Describe the bug**
Edit/replace characters events are not accurate nor inspire confidence. It's common that I need to replace the same postman request from localhost to some other url. With other apps whatever text shows selected can be overwritten and replaced. However, in postman it's a fight to have text land in the correct location, and hard to determine what its going to choose to do. Randomly I'll see the cursor flashing, and I'll attempt to remove some text but it's removing it from a different section of the url, so I move the cursor but it's still deleting from the same location.

**To Reproduce**
1. Go to a new request and fill out with a url
2. Select some of the text
3. Paste in replacement text

**Expected behavior**
Have state follow cursor and selection location for normal editing and replacing items.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/13228659/95372811-f4c81c00-0890-11eb-9fcd-3d27b931a626.gif)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.33.1
 - OS: macOS Catalina 10.15.7

**Additional context**

**Comment by pankajk07** [comment] 2020-10-08 15:47
@miguel-orange We were not able to reproduce the issue. Will you be able to share a more detailed video about the complete flow starting from the moment you opened a tab until this issue was encountered with dev-tools open (To open Dev tools go to View>Developer>Show Devtools (Current View)).

**Comment by pankajk07** [comment] 2020-10-14 09:23
@miguel-orange We will need more info to reproduce this issue as was requested in the previous comment. I'm closing the issue for now but we can reopen if we receive more information about the problem.

**Closed as completed by pankajk07** 2020-10-14 09:23 UTC
Labels: bug, need-more-info
