### ISSUE TITLE
Postman doesn't deal with 80Mb file downloading (GET request) 

### ISSUE THREAD

**Issue by Heloise-Chauvel** [a85/POSTMan-Chrome-Extension#2972] opened 2017-04-24 15:04 UTC
Overview:

The GET request works when I put it directly in the browser, but with Postman it hangs indefinitely and never download the file. I would like to use Postman for this in order to retrieve the responseTime of several files from several computers. I tried with 1Mb, 10Mb and 40Mb, it works. But for heavier files it doesn't.

Other weird behavior: when I try to send this GET request too many times, I can't send any other requests (GET, POST, PUT, etc...). I have to delete my Chrome profile and reinstall Postman to be able to send them again.

Thank you for help.

Version/App Information:

 1. Postman Version: Version 4.10.7
 2. App (Chrome app or Mac app): Postman for Chrome
 3. OS details: Windows 7 Entreprise
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: Dowload the file
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Yes

Steps to reproduce the problem:

- Write a GET request to download a file (more than 80 Mb, fo less it is working)

**Comment by numaanashraf** [comment] 2019-03-27 19:29
Duplicate of #4751

**Closed as completed by numaanashraf** 2019-03-27 19:29 UTC
Labels: bug, performance
