### ISSUE TITLE
toggle Copy and Paste in Response body so clicking links don't open new request tabs

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#7218] opened 2019-08-28 21:24 UTC
Writing on behalf of a user.

**Is your feature request related to a problem? Please describe.**

> I updated to the new version of Postman and now when I try to copy text, it opens it inside of a new tab. I've disabled all shortcuts, but it still does it. 
> It seems that when I click, drag to select the text, then let go, Postman thinks I want to open the text in a new tab. This new feature is creating additional clicks for us to do what we need.

**Describe the solution you'd like**
The ability to toggle off opening links in new request tabs. 

**Describe alternatives you've considered**
Opening up the response body in Preview tab but this just creates a wall of text which makes it hard to fish out needed links.

**Comment by kamalaknn** [comment] 2019-08-29 04:11
@stcalica This looks like a duplicate of #6984 

This is not intended behavior. We have marked it as a bug and are working on a fix for this. 

I'm closing this as a duplicate. Please follow the original thread for updates.

**Closed as completed by kamalaknn** 2019-08-29 04:11 UTC
