### ISSUE TITLE
Runner not running request sequentially

### ISSUE THREAD

**Issue by vividhsv** [a85/POSTMan-Chrome-Extension#1809] opened 2016-03-07 17:23 UTC
Upon selecting the collection to run on the runner, API Requests within the collection are not running sequentially in the order listed. My API requests are chained, that is response from the previous request is required for next request.

How can I have my tests run sequentially ?

**Comment by darrylkuhn** [comment] 2016-03-07 17:33
We're seeing the same thing on the latest version (4.0.1) on OSX

**Comment by abhijitkane** [comment] 2016-03-07 23:29
@vividhsv What version of Postman are you using? Also, do you have folders, or are all the requests within the collection itself?

**Comment by wheelspinner** [comment] 2016-03-08 22:23
I'm using Mac 4.0.4 and I see the same issue.  It happens if the requests are in the same folder or in separate folders.  I haven't tried removing all folders yet though.

**Comment by abhijitkane** [comment] 2016-03-09 09:34
@wheelspinner Can you share a sample collection that you're able to reproduce the issue with? Does the page at https://app.getpostman.com/dashboard/collections/private?expand=1 show the requests and folders in the correct order?

**Comment by wheelspinner** [comment] 2016-03-09 15:18
This one:  https://www.getpostman.com/collections/720200519aa0d061c89a

In the "02 Add Contacts" folder the 'getNewlyAddedContact' request appears
to be running too soon.

BTW - I had no issue before I updated postman (don't remember the previous
version) and I have no issue running this from newman 1.3.0.

**Comment by abhijitkane** [comment] 2016-03-10 00:56
@wheelspinner Does the issue persist if you import the link you pasted, choose 'Import as Copy', and run the new collection?

**Comment by adampopkiewicz** [comment] 2016-03-14 08:47
I had the same issue with 4.0.4, with 4.0.6 update it's fixed. that's on OSX, with both standalone client and chrome app.

what it was, it didn't preserve sorting from previous version, and because it seems popular with others as well that we use folders for features, we prepend numbers before names so they run in specific order (i.e. first tests without login, then login requests & tests, then tests with user). not sure now if issue was with just runner or did it also shown differently on collections view.

**Comment by adampopkiewicz** [comment] 2016-03-15 10:05
actually, problem still occurs, when saving collection from standalone OSX app, newman reads out sequence in wired way (like collection runner used to in previous 4.x versions, in 4.0.6 works fine)

workaround is to store collection from postman chrome app

**Comment by abhijitkane** [comment] 2016-03-15 13:05
@czardoz How does Newman order the requests in a collection with folders?
@adampopkiewicz Can you share the collection URL which runs differently in Newman?

**Comment by adampopkiewicz** [comment] 2016-03-15 13:26
@abhijitkane sure, I created these 2 collections with new setup:
abc: good one
https://www.getpostman.com/collections/c0468282a08869b7f667
bcd: bad one
https://www.getpostman.com/collections/5ee9968692c74fa4e434

abc was created originally with sequence of 01, 02, 03...
for bcd I copied each folder from abc and moved to bcd, this time in reverse order 03, 02, 01
when running with newman it seems that creation time or sequence in which they were added takes precedence over sort by name.

it happens with postman OSX native app, not exactly sure which version it is, I think it showed 4.0.6 when updating, but when looking @about screen, it says 4.0.5, but check for update shows "you're up to date! v.4.0.6 is the latest version".
saving to file with chrome app 4.0.6 also does that, now that I've checked.

newman with `abc`

> Summary:
> 
> ## Parent                    Pass Count   FailCount
> 
> Folder 01. auth                    0           0
> Folder 02. first                   0           1
> Folder 03. second                  0           1

newman with `bcd`

> ## Parent                    Pass Count   FailCount
> 
> Folder 03. second copy             0           1
> Folder 02. first copy              0           1
> Folder 01. auth copy               0           0

**Comment by ageorge2** [comment] 2016-03-22 19:47
We are also having the same problem with Win7, Postman 4.1.2.  The collection runner doesn't run in the order that we set.  If it fails the run and you try to do re-run it starts in weird places so have to keep opening and closing the collection runner.  We noticed the bug happens the moment it runs into a failed test.

**Comment by abhijitkane** [comment] 2016-03-22 21:19
@czardoz How does Newman order the requests in a collection with folders?
@ageorge2 Does this happen with a failed test (test result = false), or an error in the test script (referencing an invalid variable, for example)?

**Comment by ageorge2** [comment] 2016-03-22 23:40
@abhijitkane test result = false , however most of the falses are due to the runner not keeping the order properly and thus creating the error.  So there is 2 things happening.  1 running out of order, 2 dumping out of the runner when a test = false

**Comment by abhijitkane** [comment] 2016-03-22 23:51
@ageorge2 Does this collection run for you - https://www.getpostman.com/collections/391d6436163c8947ac73 (all tests should pass)?

**Comment by czardoz** [comment] 2016-03-23 05:16
@abhijitkane, Newman just picks up folders in the order they exist in the collection

**Comment by ageorge2** [comment] 2016-03-23 13:42
@abhijitkane - So not sure if an update/patch was done during the night but this morning the runner appears to be now functioning properly when it comes to run order.  However I am still running into test result = fail causing the runner to kick me out of run.  Your test collection was successful.  I retested other collection runs and ones that are 100% pass run in order and 0 test results = fail.  However a collection with a test result = fail is dumping me out of the run.  The failure is an expected fail but the run should continue.  Prior to the last update a failure did not kick you out.

**Comment by ageorge2** [comment] 2016-03-23 13:46
@abhijitkane I spoke to soon just found another weird instance.  I tried to run a new folder in my collection without closing the Collection Runner in between.  This caused the new run to go out of order and fail things out.  I then closed the collection runner window completely.  Reopened it and ran the exact same folder, the tests then ran in the proper order up until an expected failure and then booted me from the run.  To test I immediately hit Start Test again without closing and experienced the half run rather than starting from the beginning.  Close and reopen the runner and starts from the beginning.

**Comment by abhijitkane** [comment] 2016-03-23 15:34
@ageorge2 If you change the test in `r3` of my collection to `tests["correct reqIndex"] = globals.reqIndex == 4;`, do the requests not run in order? 
If they do, can you share a sample collection where the order gets messed up after a test failure?

**Comment by ageorge2** [comment] 2016-03-23 15:52
Today the errors are very inconsistent

I did the changes you suggested and the test fails as expected the runner also completes.  I unfortunately cannot share any of my collections due to privacy issues.  From what I can see the runner seems to Pause/Stop if it in counters 500 errors then when you click start test again it is actually picking up where it left off.

I suspect something has changed from yesterday to today because many of the issues I was running into have stopped.  I will continue to monitor and see if I can find a reliable reproducible process of any issue I do continue to see.

**Comment by yyoungs** [comment] 2016-05-23 15:38
I have also experienced the runner executing calls in a different order to the order set in Postman. I am using folders of tests on 4.2.1 win / x86-32 Chrome 50.0.2661.102.

I have experienced several times in the past.

After experiencing the issue I closed and reopened Postman and the runner. This resolved the issue. After doing some tests I suspect that the runner is taking the order of the tests in which they were added to the folder. Not the order they were subsequently changed to. So restarting is correcting any order sync problems.

**Comment by abhijitkane** [comment] 2016-06-14 09:05
@YoungYoungs We fixed one problem related to this in v4.3.2. Can you upgrade to this version and check?

**Closed as completed** 2016-09-09 05:06 UTC

**Comment by anit05** [comment] 2017-07-03 14:15
Hi 
I have version 5.0.2
But postman collection runner executing calls in different order
It was working fine a few days back.
I have not made any changes to my calls but however it does not work properly.

What can be the reason ?

**Comment by tg4774** [comment] 2018-04-20 10:17
I'm on version v6.0.10 and just encountered the same issue. 
Re-ordering within the collection didn't change anything. What worked however was to move the wrong placed call out of the collection and then back in.

**Comment by dzottola** [comment] 2018-12-27 12:55
Same issue +1

**Comment by MoghunterRoot** [comment] 2019-02-22 09:28
same problems +1

**Comment by sdping** [comment] 2019-03-22 03:42
I have the same issue ,it causes by import the collection with "Replace". Just delete the whole collection,then import again ,everything goes well.
