### ISSUE TITLE
Variables not properly resolving in Pre-Request Script

### ISSUE THREAD

**Issue by stramel** [a85/POSTMan-Chrome-Extension#4194] opened 2018-02-15 04:12 UTC
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```
Postman for Windows
Windows 10/x64
_Will get version tomorrow_

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Encountered recently
 2. Expected behaviour: Variable should fully resolve
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

set variables: 
- env: d
- tenant: foobar
- baseUrl: https://{{env}}-{{tenant}}.subdomain.com

Then in a pre-request make a request using

{{baseUrl}}/api/rest/endpoint

The url doesn't resolve completely making a request to 

 https://{{env}}-{{tenant}}.subdomain.com/api/rest/endpoint

**Comment by sivcan** [comment] 2018-02-15 08:42
Hi @stramel - Duplicate of issue : https://github.com/postmanlabs/postman-app-support/issues/3929

**Closed as completed by sivcan** 2018-02-15 08:42 UTC
