### ISSUE TITLE
Collection variable does not work

### ISSUE THREAD

**Issue by kjnz** [a85/POSTMan-Chrome-Extension#6943] opened 2019-07-18 07:20 UTC
**Describe the bug**
 Cannot use collection variables in requests.

**To Reproduce**

Here is a publicly available GET request URI to replicate this..
https://reqres.in/api/users/2
Collection variable HomeUrl = https://reqres.in

**Expected behavior**
The GET request should be successful.

**App information (please complete the following information):**
 - Postman Version [7.3.2]
 - OS: [ Windows 10]

**Additional context**

Postman errors out showing the variable as unresolved

This is the message on the postman console...
Error: Invalid URI "http:///%7B%7BHomeUrl%7D%7D/api/users/2"

**Comment by shamasis** [comment] 2019-07-18 20:22
Umm... I tried reproducing it. Was not able to. Here's the collection I created: https://www.getpostman.com/collections/43d3f29710364cbf6349

Also, attaching screenshot:
<img width="675" alt="Screenshot 2019-07-19 at 01 51 14" src="https://user-images.githubusercontent.com/232373/61489247-e1990a00-a9c7-11e9-97fe-1a0fc0892181.png">

Can you try sending me a collection where this is erroring out?

**Comment by preethammavin** [comment] 2019-07-26 02:25
@kjnz closing the issue as with the current information provided we are unable to reproduce the issue, feel free to reopen the issue with the above mentioned information so that we can sort it out for you.

**Closed as completed by preethammavin** 2019-07-26 02:25 UTC
