### ISSUE TITLE
Feature Request: Protect published documentation

### ISSUE THREAD

**Issue by skimmerle** [a85/POSTMan-Chrome-Extension#6410] opened 2019-05-02 21:08 UTC
we are publishing our collections on custom domains, but we want to protect them also with some authentication like basic auth. 

is this already possible?

**Comment by Jul13nT** [comment] 2019-05-15 15:50
I think this is a duplicate of #4365

**Comment by sankalp0o** [comment] 2019-05-16 09:45
Closing this a duplicate of #4365

**Closed as completed by sankalp0o** 2019-05-16 09:45 UTC
Labels: feature, product/documentation
