### ISSUE TITLE
Segment Param suffixed with extension not being replaced with value

### ISSUE THREAD

**Issue by excalq** [a85/POSTMan-Chrome-Extension#2556] opened 2016-12-14 23:26 UTC
Thank you for developing the excellent application that Postman is. We have some API routes that require a '.json' extension, proceeded by a resource id. This becomes a URL in the form `{{api_host}}/api/v2/clients/:custom_path/members/:resource.json`. 

`:resource` will be shown as a Param in the GUI as expected. The "Generate Code Snippets" preview parses the request URL correctly, but the actual URL that gets requested is `https://mydomain.com/api/v2/clients/my_custom_path/members/:resource.json` with :resource.json being the literal ending of the URL.

A workaround is to include ".json" with the value of :resource, and omit from the URL, but that's less ideal, especially given the discrepancy with the "Code" preview and the actual behavior.

Version/App Information:
 1. Postman Version: 4.9.1
 2. App (Chrome app or Mac app): Mac App
 3. OS details: Mac OS X El Capitan
 4. Is the Interceptor on and enabled in the app: Not sure what this is.
 5. Did you encounter this recently, or has this bug always been there: ?
 6. Expected behaviour: :resource should be replaced with the value of that param instead of sent literally.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:
1. Create a request with the final segment being suffixed with an extension (e.g. ".json')
2. Fill the Param variable with a value
3. View the  "Generate Code Snippets"  popup. It should format as intended.
4. Send the request. It will include the literal string ":resource.json"

**Comment by vegetableman** [comment] 2016-12-16 08:11
@excalq Thanks for reporting this issue 👍  and the detailed steps to reproduce the same. Will keep you posted in this thread.

**Comment by jknipp** [comment] 2017-02-02 00:17
I ran into this same issue and can confirm the workaround using

1. Postman Version: 4.9.3
2. App (Chrome app or Mac app): Mac App
3. OS details: Mac OS X Sierra

**Comment by mtwomey** [comment] 2017-08-03 01:44
I think this is due to #1420 yes?

**Comment by Kanmuri** [comment] 2017-11-13 03:58
Due to the notice of the Chrome Apps going away soon, I switched from the Chrome app (version 5.3.2) to the Windows native app (also version 5.3.2) last week.

I've never had this issue in the Chrome App, but I immediately ran into it in the Windows native app. I just checked the Chrome App again and I *still* don't have this issue there. It's extremely frustrating. :(

**Comment by Krizzzn** [comment] 2018-02-19 09:20
Issue is still persists. The URL Parser considers everything from the `:` until the next `/` as variable name. (ie: :Id.pdf), while it should only consider alpha-numerics.

On the other hand URLvariables can't  include a `.` in their name --> this means `:Id.pdf` is not a valid.

Version 5.5.3
win32 6.1.7601 / x64

**Comment by sdnts** [comment] 2018-03-20 13:47
Can you guys try using environment variables instead of path variables for this? They should work a lot more reliably.
Also, this is the same as #2427, so I'm closing this one. Please let me know if this is not the case, and I'll reopen.

**Closed as completed by sdnts** 2018-03-20 13:47 UTC
Labels: bug

**Comment by Kanmuri** [comment] 2018-03-31 18:34
From my understanding of how environment variables work, no this will not work for my use case.
The value does not vary per environment.
It does look like #2427 is the same issue, however, so I will comment on that ticket as well.
