### ISSUE TITLE
OAuth 2.0 token not added to Headers

### ISSUE THREAD

**Issue by asmeikal** [a85/POSTMan-Chrome-Extension#3608] opened 2017-10-09 10:00 UTC
## App Details:

```
Postman for Mac
Version 5.3.0
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
  - Bug showed up after updating to 5.3.0
 2. Expected behaviour:
  - After successfully obtaining an OAuth 2.0 token, and selecting "Request Headers" as "Add authorization data to" in the "Authorization" tab, I expect Postman to actually add the token to the headers.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
  - No info in the console.
 4. Screenshots (if applicable)
- ![screen shot 2017-10-09 at 11 55 28](https://user-images.githubusercontent.com/5817904/31333176-52780b82-ace9-11e7-9d25-1fa716096678.png)

To replicate the problem:
1. Obtain a new access token.
2. Select "Request Headers" as "Add authorization data to". Do not add the token manually to the Headers.
3. Send request.
4. The headers will not contain the Authorization field.

Additionally:
- When clicking "Preview Request" from the "Authorization" tab, a "Could not update authorization data" message shows up.
- If I manually add an "Authorization" field to the Headers, Postman says that "This is a duplicate header", and that it will be overwritten (which doesn't happen).

**Comment by kamalaknn** [comment] 2017-10-09 10:27
Hi @asmeikal thanks for reporting the issue.

We are having trouble reproducing this. It would be great if you could give us more detail.

1. Are you seeing the access token in the input box or is the input empty?
2. Are you seeing the same if you select `Add authorization data` to `Request URL`?
2. Could you try saving the request and sending it again?

**Comment by asmeikal** [comment] 2017-10-09 10:42
1. The token appears in the `Access Token` box, in the `Authorization` tab.
2. If I select `Request URL`, there still is no token in the request. Also, `Preview Request` gives the same error (`Could not update authorization data.`)
3. I tried, no change. I'll try to reinstall Postman and see if anything changes.

**Comment by asmeikal** [comment] 2017-10-09 11:12
Reinstalling Postman fixed the problem.

**Comment by kamalaknn** [comment] 2017-10-09 11:24
@asmeikal Good to hear.

We'll continue to investigate why the update was not working for you. 

I'll post updates to this thread.

**Comment by krmr** [comment] 2017-10-09 13:04
I am afraid that I am experiencing the same problem under Windows (Version 5.3.0, win 32 10.0.15063 / x64):

Steps:
1. Successfully request an OAuth2.0 token (grant type is 'Client Credentials', the token received has token_type 'Bearer')
2. In the request select the token to use
3. Click on 'Preview Request'

Result:
1. A message is shown 'Could not update authorization data'
2. There is no authorization header created

Unfortunately uninstalling and reinstalling postman did not resolve the problem for me.

**Comment by kamalaknn** [comment] 2017-10-09 13:10
@krmr 

Could you open `Manage Tokens` from the `Available Tokens` dropdown and select the token and share a screenshot?

You can mask the `Access Token` field.

**Comment by krmr** [comment] 2017-10-09 13:34
Sure, I had to take two screenshots as the token does not fit into the window as it has 876 characters.
![grafik](https://user-images.githubusercontent.com/3511772/31340685-3e722514-ad07-11e7-88ff-4a056375f521.png)
![grafik](https://user-images.githubusercontent.com/3511772/31340690-4245630e-ad07-11e7-99f9-1e95d15e9ea7.png)

**Comment by mhw** [comment] 2017-10-09 13:53
I'm seeing the same behaviour on macOS 10.12.6. I've tried uninstalling Postman and then reinstalling, but that's made no difference. I can see the access token value on the Authorisation tab, but it's not getting added to the request headers (as seen in the Postman console log).

**Comment by kamalaknn** [comment] 2017-10-09 14:03
Hi, 

We've identified the root cause for the issue and fixed it internally. We'll roll out a fix within a week. I'll update this thread as soon as the fix is out on Production.

You can find the download link to `5.2.1` here - https://www.getpostman.com/apps#changelog. This will unblock you to continue working. 

We're sorry for the trouble with the upgrade, we'll try to roll out the fix quickly.

**Comment by zwtan** [comment] 2017-10-09 15:27
@kamalaknn I'm facing similar issue where information is entered for Google OAuth 2.0 but console stated that "parameter not for this message: state". This happens when 5.3.0 update came in, not sure if anything added in the backend. I've tried downgrade to 5.2.1 but no avail 

<img width="1074" alt="screen shot 2017-10-09 at 11 24 02 pm" src="https://user-images.githubusercontent.com/8004516/31345761-5a450d00-ad49-11e7-8ac4-b669835dd17a.png">
<img width="1075" alt="screen shot 2017-10-09 at 11 24 07 pm" src="https://user-images.githubusercontent.com/8004516/31345762-5a74c6da-ad49-11e7-9573-14115327f11a.png">
<img width="478" alt="screen shot 2017-10-09 at 11 24 17 pm" src="https://user-images.githubusercontent.com/8004516/31345763-5a80e564-ad49-11e7-9188-c09cc4352949.png">

**Comment by kamalaknn** [comment] 2017-10-09 17:40
@zwtan What you are experiencing is a different issue. You can find more details on it in #2811

**Comment by zwtan** [comment] 2017-10-09 23:11
@kamalaknn thank for the redirect to the correct answer. tested and work, cheers!

**Comment by psimoneau22** [comment] 2017-10-11 16:26
just subscribing to this thread.  I have the same issue.  In addition, after upgrading, all of the settings that I previously had in my OAuth2 modal were wiped out and I had to go and re-enter all of that information.   I'm not sure if that will be fixed also, but it would be nice if upgrading in the future does not wipe out my settings.

**Comment by kamalaknn** [comment] 2017-10-11 18:40
@psimoneau22 we're sorry that we couldn't carry over the settings for OAuth 2 dialog after the update. We made several changes to internal workings of OAuth 2.0, and we couldn't do it while retaining existing data. Rest assured, this is a one-time event and subsequent updates will preserve the settings in the dialog.

As for the original issue, we've rolled out a fix for this in our Canary channel in 5.3.1-canary01.

Here are the Canary download links for all platforms,

macOS:
https://dl.pstmn.io/download/channel/canary/osx_64

windows:
https://dl.pstmn.io/download/channel/canary/windows_32
https://dl.pstmn.io/download/channel/canary/windows_64

linus:
https://dl.pstmn.io/download/channel/canary/linux_32
https://dl.pstmn.io/download/channel/canary/linux_64
It would be great if someone could confirm this is fixed.

**Comment by krmr** [comment] 2017-10-12 10:58
Thanks for the update @kamalaknn , I have just tried with the Canary version for windows 64 bit and it workes fine for me.

**Comment by varsitynetworks** [comment] 2017-10-12 17:03
Also having same problem with PM 5.3 using Mac OS 10.12.2

After obtaining access token, and clicking on "use token" (obscured in window, by the way), subsequent api calls all claim that authorization header is missing. Enclosed is a screen shot.

As can be seen, the token is there and "supposedly" being used. The request is a get and scope was correctly set on token request. 

![image](https://user-images.githubusercontent.com/3950480/31508925-9e9e08d4-af4d-11e7-80f9-dcd512c6a7ef.png)

**Comment by kamalaknn** [comment] 2017-10-12 17:24
@varsitynetworks We've rolled out a fix for this on the Canary channel. The download links are in the [comment above](https://github.com/postmanlabs/postman-app-support/issues/3608#issuecomment-335907768).

We'll push an update to the stable channel with this fix in a few days.

**Comment by DavydeVries** [comment] 2017-10-13 08:13
@kamalaknn Tested on macOS 10.13.1 bèta (17B25c) with Canary version and it works! Thank you a lot because we were struggling the last couple of days with this issue!

**Comment by gareth-a-jones** [comment] 2017-10-14 07:11
it works some of the time in the canary, but some of the time still just stops as previously.  very flaky.  Plus Doesn't give any sign that it refreshes automatically yet, so need to do that in a collection request, so need it to go into an environment variable, not a header, so the first request in the collection can be to run token refresh.

**Comment by kamalaknn** [comment] 2017-10-16 18:16
@garethj-msft we are more pushing fixes to OAuth 2.0 in Postman over the next couple of days. That should solve your issues with getting a token.

Also, you are right that Postman does not yet support refreshing the OAuth 2.0 tokens. We are working on possible ways to allow refreshing tokens. To begin with, we might start with giving you an option to manually refresh tokens.

**Comment by kamalaknn** [comment] 2017-10-18 10:29
@asmeikal @garethj-msft @DavydeVries @krmr @psimoneau22 we've pushed a fix for this in 5.3.1 version of Postman. Could you update your apps to the latest version and confirm this?

**Comment by dhoeric** [comment] 2017-10-18 10:38
@kamalaknn works well :)

Here are my steps:
1. `Get New Access Token` on Authorization tab
2. Add authorization data on either `Request URL`or `Request Header`, click `Preview Request`
3. Successfully send the request with access token 👍

**Comment by kamalaknn** [comment] 2017-10-18 10:54
@dhoeric great, you can actually skip `Preview Request`.

1. `Get New Access Token`
2. Follow the dialog to get a token
3. Select `Use Token` when you see the token details
4. Send the request

Closing this issue, feel free to leave a comment if something is off.

**Closed as completed by kamalaknn** 2017-10-18 10:54 UTC
Labels: bug, Auth

**Comment by jdinardo30** [comment] 2018-02-12 21:06
Hi all,

I wanted to mention that I'm seeing this exact issue in the latest version of postman.  I opened the issue here as it has sprung up again: #4140

**Comment by zonito** [comment] 2018-02-22 17:16
Getting the same issue. Followed the steps mentioned in @kamalaknn

**Comment by sivaserr** [comment] 2018-06-07 09:47
Thanks for the update @kamalaknn , I have just tried with the Canary version for windows 64 bit and it workes fine for me.

**Comment by nicodesh** [comment] 2018-07-05 15:21
Hi guys,

I'm experiencing the same issue. My token is valid, and I can see it in "Access token". If a create my own querystring param, it tells me "warning, your param access_token will be overrived by ours" but actually it's the only way to make it work. And if I click on "preview request", I've got the message "Could not update authorization data". I'm on Mac OS X with the latest version of Postman.

**Comment by JasonTheAdams** [comment] 2018-09-17 17:00
I'm completely blocked by this on MacOS. I've tested both the latest version of Postman as well as Postman Canary. I've tried setting the Token Bearer authorization for both the endpoint as well as the group. I cannot seem to get Postman to send the Authorization. I also turned on dev mode and checked the console — no output.

Please fix this issue. It seems like it's been around for a while and is a real show-stopper.

**Comment by JasonTheAdams** [comment] 2018-09-17 18:02
I wanted to report back that in my case Postman was working just fine. It was actually Apache that was causing me grief. Turns out — and I'm still not sure why — but it will strip out the Authorization header. To get it back I added the following to the .htaccess:
```apache
SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0
```
What this does is make `$_SERVER['REDIRECT_HTTP_AUTHORIZATION']` available (or whatever your server language equivalent is). That will then contain the value of the authorization header, not where you would otherwise expect.

It's strange, and I don't fully understand it, but I don't want Postman to be blamed for an apache quirk. It sure looks like the header isn't being sent, but it is.

Hope this helps someone else!

**Comment by bensonfungpostman** [comment] 2020-10-29 23:19
I am using version 7.35.  I got the same issue now....Please help.

**Comment by nostick** [comment] 2020-11-05 17:26
I'm having the same issue as @bensonfungpostman with the update 7.35

**Comment by vvs11** [comment] 2020-11-06 10:37
We are working on fixing this issue. Please go through #9056 We will post updates there
