### ISSUE TITLE
Connectivity Feature Request for Postman & DB

### ISSUE THREAD

**Issue by BhanuDash007** [a85/POSTMan-Chrome-Extension#5199] opened 2018-09-18 12:36 UTC
Hi , As part of Webservice testing and Automation we need the connectivity between DB and Services. Other tool provide that . If some thing can be done in it ASAP that make Postman more robust.

**Comment by numaanashraf** [comment] 2018-09-18 18:38
Related to #2185

**Comment by JoaoGFarias** [comment] 2018-10-22 18:36
I don't know if you can do it with Postman, but calling a shell script would be sufficient to leverage your favorite tool to run the DB scripts (A Python/Java script, e.g.).

**Comment by ghost** [comment] 2018-12-10 14:18
Hi,
Any update on this?

**Comment by a85** [comment] 2019-03-09 23:19
Closing as duplicate of other feature requests and there are no plans for Postman to support databases in the near future.

**Closed as completed by a85** 2019-03-09 23:19 UTC
Labels: feature
