### ISSUE TITLE
Error while importing cURL with --compressed option

### ISSUE THREAD

**Issue by Krittam** [a85/POSTMan-Chrome-Extension#5735] opened 2019-01-08 06:53 UTC
**Description**
When trying to import a new request from curl Postman says :: Error while importing Curl: TypeError: Invalid format for cURL.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Import'
2. Click on 'Paste Raw Text'
3. Paste the mentioned curl
4. Click on 'Import'
5. See error :: 'Error while importing Curl: TypeError: Invalid format for cURL.'

**Expected behavior**
I should see a new request tab with the curl parmaneters.

**Screenshots**
<img width="457" alt="screenshot 2019-01-08 at 12 02 30 pm" src="https://user-images.githubusercontent.com/20901558/50814538-0ee16d00-1340-11e9-812f-3b45849ccc8e.png">

**App information**
Postman Version 6.6.1 (6.6.1)
OS: macOS Mojave 10.14.2

**sample curl**
> curl -H 'app: android' -H 'did: c3f4e8faa35463df/Android/26/1/1.0' -H 'x-build: 1' -H 'utn: Ezqzt85Ap6_0:I0ft79g13WeBBaErhH3w=' -H 'cid: 853221600544e5187185016703f77a9d' -H 'Accept: application/json' -H 'net: 1/13/-1' -H 'Content-Type: application/json; charset=UTF-8' -H 'Host: stage.in' -H 'User-Agent: okhttp/3.11.0' --compressed 'http://stage.in/xyz'

**Comment by numaanashraf** [comment] 2019-01-08 07:24
@Krittam we do not support `--compressed` option at the moment. We have taken this up as a bug and would be fixing in the coming releases. As a workaround, you can remove the compressed option to import this cURL snippet.

**Comment by numaanashraf** [comment] 2019-01-16 16:59
Duplicate of #5424

**Closed as completed by numaanashraf** 2019-01-16 16:59 UTC
Labels: bug, importer, importer/curl

**Comment by JAELatDHI** [comment] 2021-06-15 07:35
Has --compressed been added since? I am having a similar issue.
