### ISSUE TITLE
win7下载点击安装后无法定位程序输入点y于动态链接库KERNET32.dll上。

### ISSUE THREAD

**Issue by liuwenwubin** [a85/POSTMan-Chrome-Extension#7047] opened 2019-08-02 11:04 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by shamasis** [comment] 2019-08-02 19:53
Google translate shows “After win7 download click install, you can't locate the program input point y on the dynamic link library KERNET32.dll.”

We need more information such as 
- app version, 
- OS version and if 32/64bit OS
- is there any antivirus software blocking it?

Try re downloading the app and install in a fresh machine and check to start eliminating the cause.

**Comment by liuwenwubin** [comment] 2019-08-03 00:48
1、win7系统版本64位，
2、下载也是64位操作系统，
![image](https://user-images.githubusercontent.com/20508528/62404947-6476b300-b5cb-11e9-9f78-5eb003bb0e1f.png)

**Comment by Itsusinn** [comment] 2020-03-28 10:13
use this用这个
 [https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot](url)
it maybe work这可能起作用

**Comment by Itsusinn** [comment] 2020-03-28 10:15
it can solve the problem "SetDefaultDllDirectories "
这个补丁可以解决"SetDefaultDllDirectories "的问题

**Comment by liuwenwubin** [comment] 2020-03-28 10:18
hello，thank you very much！I have solved this problem，It was a system problem！！！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"逸新"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月28日(星期六) 晚上6:15
收件人:&nbsp;"postmanlabs/postman-app-support"<postman-app-support@noreply.github.com&gt;;
抄送:&nbsp;"ㄣж鈊痛"<1172752173@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [postmanlabs/postman-app-support] win7下载点击安装后无法定位程序输入点y于动态链接库KERNET32.dll上。 (#7047)





 
it can solve the problem "SetDefaultDllDirectories "
 这个补丁可以解决"SetDefaultDllDirectories "的问题

**Comment by DannyDainton** [comment] 2020-08-25 11:53
@liuwenwubin I'm going to close this issue as it appears that you have solved the problem.

**Closed as completed by DannyDainton** 2020-08-25 11:53 UTC
Labels: bug
