### ISSUE TITLE
Postman crashes when certificate and private key mismatch

### ISSUE THREAD

**Issue by drkilikil** [a85/POSTMan-Chrome-Extension#5916] opened 2019-02-13 09:07 UTC
**Describe the bug**
Postman crashes when the certificate and the private key configured for client-certificate authentication do not form a valid public/private key pair.

**To Reproduce**
1. Open Settings
2. Add a client certificate
3. Choose a certificate file and a private key file that does not match
4. Send a request

**Expected behavior**
Show an error message instead of crashing.

**App information:**
 - Native App
 - Postman Version 6.7.3
 - Windows 7

**Comment by gitankitsingh** [comment] 2019-02-19 12:15
@drkilikil thank you for reporting this bug, we tried reproducing it locally but everything seems to work. would it be possible for you to provide any additional details that might help us reproduce it locally and investigate it further. 

 related to https://github.com/postmanlabs/postman-app-support/issues/5765

**Comment by benoitrolland** [comment] 2019-02-20 10:27
load an ssl url in chrome working with a certificate of your own or of your own company , 
extract it in a file (right click on lock/Certificate/Details/copyInFile) 
and load it in postman specifying the correct url. 
Configure a Get request on the url using postman.
Whether or not postman is configured to check ssl certificates, 
postman disapear as soon as you click on "Send"

**Comment by gitankitsingh** [comment] 2019-02-20 11:12
@benoitrolland by doing that you are essentially using the server's SSL certificate to send the request to the server, the behavior is still unexpected as the app shouldn't crash but you are expected to provide client certificates in postman app for any server which require SSL client authentication.

**Comment by drkilikil** [comment] 2019-02-21 12:52
@ankitsiam 
Thanks for your comment that was helpful. After a more thorough investigation, here is the result of my tests:
- No issue when proxy config is off. The Postman console shows:

> **Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch**
Client Certificate:
keyPath:"C:\test2.key"
pemPath:"C:\test1.cer"

- Postman crashes when sending a request through a proxy server.

**Comment by gitankitsingh** [comment] 2019-02-22 18:43
@drkilikil thank you for your reply, I was able to reproduce the issue with proxy settings on. we are looking into it and fix or any other update will be shared here.

**Comment by wklenk** [comment] 2019-02-25 10:17
For me, the reason for postman crash was that the certificates in cert file were in the wrong order. The certificate chain had 3 certificates, and the Root CA certificate was the first one in the file, followed be the intermediate CA certificate, followed by the actual client certificate. 
After I manually reversed the order (beginning with client certificate) by some cutting and pasting in the cert file, it finally worked.

**Comment by codenirvana** [comment] 2019-06-13 11:53
Fixed in Postman v7.2.0

**Closed as completed by codenirvana** 2019-06-13 11:53 UTC
Labels: bug, need-more-info, product/runtime
