### ISSUE TITLE
postman.setNextRequest('Request Name') does not execute in another folder under the same collection? 

### ISSUE THREAD

**Issue by 21anujashah** [a85/POSTMan-Chrome-Extension#7151] opened 2019-08-20 14:41 UTC
I have one collection of 400 APIs.
1. This collection has around 10 folders.
2. Each folder has also subfolders. 
3. I have one scenario that "Check events on the page. If the page has any event then execute the next request under the same folder else execute the next request from another folder".
4. I write below code in my tests script. It does not execute the next request. My collection executes all the request even though the application does not find any event on the page.

if (responseJSON.length !== 0) {
    tests["Schema Validation Success for events"] = tv4.validate(responseJSON, JSON.parse(pm.globals.get('eventSchema')));
    postman.setEnvironmentVariable("guid", responseJSON.content[0].guid);
    postman.setEnvironmentVariable("userID", responseJSON.content[0].userId);
    postman.setEnvironmentVariable("userID", responseJSON.content[0].userId);
    if (tv4.error) {
        console.log(tv4.error);
    }
}

if (responseJSON.length === 0) {
    postman.setNextRequest('Retrieve All workers'); // this is another request under different folder in colelction 
}

**Comment by codenirvana** [comment] 2019-08-21 06:46
`postman.setNextRequest` works irrespective of the executing request's folder or location provided the entire collection is getting executed.

But, it won't work if only a specific folder (say A) is executing which `setNextRequest` to a request in a different folder (say B).

Closing as duplicate of #2819

**Closed as completed by codenirvana** 2019-08-21 06:46 UTC
Labels: duplicate, product/runtime
