### ISSUE TITLE
Unable to delete folder created from duplicate

### ISSUE THREAD

**Issue by clemz25** [a85/POSTMan-Chrome-Extension#5636] opened 2018-12-11 14:31 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When trying to delete a folder that was created from duplicating a folder containing requests, it fails to delete. The duplicate folder contains requests to the same URI, but with different HTTP methods. 

**To Reproduce**
1. Go to a folder to be duplicated to another Collection
2. Click on the '...'  and select the "Duplicate" command
3. After the folder is created, click on the '...' for the folder Copy and select "Delete"
4. Confirm that you want to delete and click on "Delete"
5. The error returned: "Unable to delete this folder"

**Expected behavior**
I expect the folder to be deleted along with the requests contained within the folder.

**Screenshots**
Attached is a screenshots of the folders to delete and the error.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.5.3
 - OS: win32-10.0.17134 on x64

**Additional context**
When I duplicated the folders containing the requests, it did not completely make a copy of all of the requests contained with in the folder. For the duplicate folder, I was able to delete the requests that were shown. However, with the empty folder, it fails to delete the folder. I have attached a backup of the collections, as well.

[Backup.postman_dump - Copy.json.txt](https://github.com/postmanlabs/postman-app-support/files/2667940/Backup.postman_dump.-.Copy.json.txt)

![postman-empty folders](https://user-images.githubusercontent.com/34449625/49807097-45b76980-fd27-11e8-82e9-840d7faf62c5.PNG)
![postman-empty folders-error](https://user-images.githubusercontent.com/34449625/49807098-46500000-fd27-11e8-9f01-349dbf5fe958.PNG)

**Comment by DaniVSainz** [comment] 2018-12-18 17:46
I'm also running into this issue while using Postman v6.6.1

**Comment by joaosoft** [comment] 2019-01-09 14:16
i also have this issue

**Comment by ezenwankwogabriel** [comment] 2019-01-10 10:53
Same issue here

**Comment by MuntzMathias** [comment] 2019-01-15 08:27
Same issue here Version 6.7.1 OSX

**Comment by sujayvenaik** [comment] 2019-03-29 04:15
Hey @clemz25 @DaniVSainz @ezenwankwogabriel @MuntzMathias 
Can you update to the latest v7.x version of the desktop app and check whether this is still reproducible?

**Comment by kamalaknn** [comment] 2019-03-29 06:06
Also can you attach screenshots of any errors you see in devtools - `View -> Developer -> Show DevTools(Current view)`?

**Comment by clemz25** [comment] 2019-03-29 13:50
This is still reproducible.

**Comment by clemz25** [comment] 2019-03-29 13:52
Attached is the log

**Comment by kamalaknn** [comment] 2019-04-02 04:57
@clemz25 I'm not able to see the logs. Was there something wrong with the attachment?

**Comment by clemz25** [comment] 2019-04-02 13:42
I am resending the log file as an attachment. I have also copied the log to
the body of the email.



vendor-shared.js:124060 Initializing the global config
requester.js:2464 App updater event Object
requester.js:2464 App updater event Object
vendor-shared.js:48662 Could not find on EditorStore. Missing or invalid
parameter.
find @ vendor-shared.js:48662
vendor-shared.js:428301 entityId is undefined for workspace addCollection
vendor-shared.js:48662 Could not find on EditorStore. Missing or invalid
parameter.
find @ vendor-shared.js:48662
vendor-shared.js:33579 [mobx.array] Attempt to read an array index (0) that
is out of bounds (0). Please check length first. Out of bound indices will
not be tracked by MobX
get @ vendor-shared.js:33579
vendor-shared.js:33579 [mobx.array] Attempt to read an array index (0) that
is out of bounds (0). Please check length first. Out of bound indices will
not be tracked by MobX
get @ vendor-shared.js:33579
vendor-shared.js:48662 Could not find on CollectionStore. Missing or
invalid parameter.
find @ vendor-shared.js:48662
vendor-shared.js:147120 undefined
vendor-shared.js:147777 Error: request is not available in the root
subtree. 8c04ecd5-77dc-4d50-a98c-a62c9be051b2
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.childRef
(vendor-shared.js:147121)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.entity
(vendor-shared.js:147092)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __getChildEntities (vendor-shared.js:147075)
    at __traverse (vendor-shared.js:147002)
    at Object.prune (vendor-shared.js:146257)
    at Object.delete (vendor-shared.js:191065)
    at vendor-shared.js:49556
    at <anonymous>
vendor-shared.js:133025 Error in pipeline for deleting folder Error:
request is not available in the root subtree.
8c04ecd5-77dc-4d50-a98c-a62c9be051b2
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.childRef
(vendor-shared.js:147121)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.entity
(vendor-shared.js:147092)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __getChildEntities (vendor-shared.js:147075)
    at __traverse (vendor-shared.js:147002)
    at Object.prune (vendor-shared.js:146257)
    at Object.delete (vendor-shared.js:191065)
    at vendor-shared.js:49556
    at <anonymous>
console.error @ vendor-shared.js:133025
vendor-shared.js:147120 undefined
vendor-shared.js:147777 Error: request is not available in the root
subtree. 64b62183-03f1-451e-b7c5-e915708489fe
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.childRef
(vendor-shared.js:147121)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.entity
(vendor-shared.js:147092)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __getChildEntities (vendor-shared.js:147075)
    at __traverse (vendor-shared.js:147002)
    at Object.prune (vendor-shared.js:146257)
    at Object.delete (vendor-shared.js:191065)
    at vendor-shared.js:49556
    at <anonymous>
vendor-shared.js:133025 Error in pipeline for deleting folder Error:
request is not available in the root subtree.
64b62183-03f1-451e-b7c5-e915708489fe
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.childRef
(vendor-shared.js:147121)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.entity
(vendor-shared.js:147092)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __getChildEntities (vendor-shared.js:147075)
    at __traverse (vendor-shared.js:147002)
    at Object.prune (vendor-shared.js:146257)
    at Object.delete (vendor-shared.js:191065)
    at vendor-shared.js:49556
    at <anonymous>
console.error @ vendor-shared.js:133025
vendor-shared.js:147120 undefined
vendor-shared.js:147777 Error: request is not available in the root
subtree. 64b62183-03f1-451e-b7c5-e915708489fe
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.childRef
(vendor-shared.js:147121)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.entity
(vendor-shared.js:147092)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __getChildEntities (vendor-shared.js:147075)
    at __traverse (vendor-shared.js:147002)
    at Object.prune (vendor-shared.js:146257)
    at Object.delete (vendor-shared.js:191065)
    at vendor-shared.js:49556
    at <anonymous>
vendor-shared.js:133025 Error in pipeline for deleting folder Error:
request is not available in the root subtree.
64b62183-03f1-451e-b7c5-e915708489fe
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.childRef
(vendor-shared.js:147121)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.entity
(vendor-shared.js:147092)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __getChildEntities (vendor-shared.js:147075)
    at __traverse (vendor-shared.js:147002)
    at Object.prune (vendor-shared.js:146257)
    at Object.delete (vendor-shared.js:191065)
    at vendor-shared.js:49556
    at <anonymous>
console.error @ vendor-shared.js:133025
vendor-shared.js:147120 undefined
vendor-shared.js:147777 Error: request is not available in the root
subtree. 64b62183-03f1-451e-b7c5-e915708489fe
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.childRef
(vendor-shared.js:147121)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.entity
(vendor-shared.js:147092)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __getChildEntities (vendor-shared.js:147075)
    at __traverse (vendor-shared.js:147002)
    at Object.prune (vendor-shared.js:146257)
    at Object.delete (vendor-shared.js:191065)
    at vendor-shared.js:49556
    at <anonymous>
vendor-shared.js:133025 Error in pipeline for deleting folder Error:
request is not available in the root subtree.
64b62183-03f1-451e-b7c5-e915708489fe
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.childRef
(vendor-shared.js:147121)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.entity
(vendor-shared.js:147092)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __getChildEntities (vendor-shared.js:147075)
    at __traverse (vendor-shared.js:147002)
    at Object.prune (vendor-shared.js:146257)
    at Object.delete (vendor-shared.js:191065)
    at vendor-shared.js:49556
    at <anonymous>
console.error @ vendor-shared.js:133025
vendor-shared.js:147120 undefined
vendor-shared.js:147777 Error: request is not available in the root
subtree. f399d877-f0e6-4abb-b8b2-e0428e4e41d2
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.childRef
(vendor-shared.js:147121)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.entity
(vendor-shared.js:147092)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __getChildEntities (vendor-shared.js:147075)
    at __traverse (vendor-shared.js:147002)
    at Object.prune (vendor-shared.js:146257)
    at Object.delete (vendor-shared.js:191065)
    at vendor-shared.js:49556
    at <anonymous>
vendor-shared.js:133025 Error in pipeline for deleting folder Error:
request is not available in the root subtree.
f399d877-f0e6-4abb-b8b2-e0428e4e41d2
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.childRef
(vendor-shared.js:147121)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __WEBPACK_IMPORTED_MODULE_1_lodash___default.a.forEach.entity
(vendor-shared.js:147092)
    at arrayEach (vendor-shared.js:669)
    at Function.forEach (vendor-shared.js:9495)
    at __getChildEntities (vendor-shared.js:147075)
    at __traverse (vendor-shared.js:147002)
    at Object.prune (vendor-shared.js:146257)
    at Object.delete (vendor-shared.js:191065)
    at vendor-shared.js:49556
    at <anonymous>
console.error @ vendor-shared.js:133025

**Comment by kamalaknn** [comment] 2019-04-05 06:15
@clemz25 Thanks for the logs

This seems to be a duplicate of #5524

**Comment by numaanashraf** [comment] 2019-04-05 09:11
Duplicate of #5524

**Closed as completed by numaanashraf** 2019-04-05 09:11 UTC
Labels: bug, postman-data
