### ISSUE TITLE
No status code in Collection Runner

### ISSUE THREAD

**Issue by joaquinrios** [a85/POSTMan-Chrome-Extension#8936] opened 2020-08-13 18:11 UTC
**Describe the bug**
On Collection Runner, when checking the Run Results, there is no information about status code, time, or memory. When exporting the run to .json, the response code is also empty and time shows "0".

**To Reproduce**
1. Go to Runner
2. Start any run
3. Look at Run Results

**Expected behavior**
Up to version 7.27.1, there would be information to the right of each request (shown in screenshot). 

**Screenshots**
Run started in version 7.27.1:
![info](https://user-images.githubusercontent.com/30807767/90170943-5c1c9080-dd66-11ea-8144-603329971168.png)

Run started in version 7.30.1:
![noInfo](https://user-images.githubusercontent.com/30807767/90170985-70608d80-dd66-11ea-91ff-8b0258abe350.png)

**App information (please complete the following information):**
 - Native App
 - Version 7.30.1
 - OS: macOS Catalina v10.15.5 (also reproduced on Windows 10 Pro)

**Additional context**
None

**Comment by DannyDainton** [comment] 2020-08-13 20:08
Hey @joaquinrios 

I'm unable to reproduce this issue on the latest version.

![Screenshot 2020-08-13 at 21 07 09](https://user-images.githubusercontent.com/17089546/90181875-0917fd00-dda9-11ea-8b5e-a54df1c54737.png)

Are there are more details that you can provide about the request itself that might give us some clues? Are there any errors in the console? 

Was this an older run? Could you tell us the date from the recent run list, please?

**Comment by babenkovitaliy** [comment] 2020-08-18 20:45
I have the same bug. I can try to provide as much details as possible where I noticed this bug. Some of the information may be useless, but I will still provide it. 

My collection runner consists of two requests:
**Request 1**

- Type: POST
- URL contains an environment variable for the hostname (etc. www.google.com). Contains no parameters.
- Content-Type is application/json
- Contains body text.
- Contains pre-request script and tests.
- "Save responses" is checked.

**Request 2**

- Type: PUT
- URL contains an environment variable for the hostname (etc. www.google.com). Does contain one parameter.
- Content-Type is application/json
- Contains Authorization header with the value: bearer {{token}}
- Empty body text.
- Contains pre-request script, but no tests.
- "Save responses" is checked.

**Notes**

- I used the runner today, and ran it against a csv file. The first endpoint doesn't grab any data from the csv file. It completed successfully and returned 200 OK
- The second endpoint gets part of the URL replaced from a piece of data in the csv file. First time I ran the runner, this second endpoint timed out for about 60 seconds before returning a 500 error (I was actually able to see it). After closing postman and re-opening, I don't what specific 500 error it was.
- I tried re-running against the same csv file. This time, the second endpoint didn't return an error (it completed successfully). However, it did not display the response code (it would have been code: 200 OK)
- I tried closing collection runner window, closing the application and re-opening, checked for updates.

**Comment by DannyDainton** [comment] 2020-08-18 21:01
Hey @babenkovitaliy,

I appreciate you trying to explain your collection details with us, could you share the actual collection file instead?

This can either be via the public link or pasting the raw json from exporting the collection to your local machine. 

There might be other details in there that help us to understand what's going on.

Another thing you could try is the Runner in the latest version of the Canary app - this should be a different experience than what you're used to but hopefully might solve some of those issues you described.

https://www.postman.com/downloads/canary/

**Comment by babenkovitaliy** [comment] 2020-08-18 21:09
@DannyDainton Unfortunately, they are private endpoints, and I am not sure that I am allowed to provide them to anyone outside of my work.

What I can do, is find any public facing endpoints (I know Postman has a service called echo where I can test those endpoints). I can then try to recreate as much as I can where I can (hopefully) get the same issue to happen. If successful, I can then provide them to you.

**Comment by DannyDainton** [comment] 2020-08-30 06:29
Hey @babenkovitaliy 

Were you able to find another endpoint to recreate the issue or is this something you're still seeing in the latest version?

**Comment by DannyDainton** [comment] 2022-01-27 09:34
Closing this issue due to lack of information - If the issue can be reproduced on the latest version we can look to open it again.

**Closed as completed by DannyDainton** 2022-01-27 09:34 UTC
Labels: support, collection-runner, product/runtime
