### ISSUE TITLE
Shortcut to uncomment turns text into uppercase.

### ISSUE THREAD

**Issue by TiagoSantosDeveloper** [a85/POSTMan-Chrome-Extension#11709] opened 2023-02-08 11:57 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

To reproduce the bug:

In Body > Raw > JSON select all the code and comment it with the shortcut Ctrl + K + C.
Select all code and uncomment with Ctrl + K + U.
The result will uncomment the code but make the text uppercase.

### Steps To Reproduce

1. Open a new request tab
2. Select the Body tab
3. Select the `raw` type 
4. Select the JSON type
5. Insert a JSON code
6. Comment it with the shortcut Ctrl + K + C
7. Uncomment with Ctrl + K + U.

The result will uncomment the code but make the text uppercase.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/27559346/217523073-97d332c5-2964-4995-90b4-0f3948093da8.png)
![image](https://user-images.githubusercontent.com/27559346/217523146-b3ef4463-14e0-499f-b884-bc2f09516a97.png)
![image](https://user-images.githubusercontent.com/27559346/217523200-ff2c5956-2665-4037-996a-bd313d09196a.png)

### Operating System

Windows

### Postman Version

10.9.3

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Everything indicates that it is a conflict of shortcuts.

**Comment by DannyDainton** [comment] 2023-02-08 11:59
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9114

**Closed as completed by DannyDainton** 2023-02-08 11:59 UTC
Labels: duplicate
