### ISSUE TITLE
Data type handling environment vs. data variables

### ISSUE THREAD

**Issue by sareykaj** [a85/POSTMan-Chrome-Extension#3225] opened 2017-06-29 18:06 UTC
## App Details:
```
Postman for Mac
Version 5.0.0
OS X 16.6.0 / x64
```

## Issue Report:
I have just started using postman and I found that environment and global variables placed inside a json body are not resolved in the same way as data variables:
- string values from environment are wrapped in double quotes but from data file they are not
- null values from environment are resolved as null but from data file they are not resolved at all
- json values from environment are resolved as json but from data they appear as [Object ...]

For reproduction I have attached a collection with an environment and a json data file and additionally screenshots from the console to compare the differences

## Questions:
- Is this expected behaviour?
- Is there a way to work around this?

[Archiv.zip](https://github.com/postmanlabs/postman-app-support/files/1113091/Archiv.zip)
<img width="1305" alt="bildschirmfoto 2017-06-29 um 19 21 12" src="https://user-images.githubusercontent.com/3009927/27702967-30a7eb68-5d06-11e7-82de-20f4411ad098.png">
<img width="1305" alt="bildschirmfoto 2017-06-29 um 19 20 59" src="https://user-images.githubusercontent.com/3009927/27702968-30aa60aa-5d06-11e7-8e0c-bd4e213d2cc2.png">

**Comment by sareykaj** [comment] 2017-06-30 07:06
OK - today I took a closer look how the environment is actually persisted to json. All is in double quotes and the double quotes that should be part of the variable are escaped. So I copy and pasted the same representation to the data file and now its the same handling.

`
[
	{
		"stringField": "\"string\"",
		"numberField": "1000",
		"nullField": "null",
		"jsonField": "{id : 1, value : \"jsonValue\"}"
	}
]
`

**Comment by sdnts** [comment] 2017-06-30 09:54
Hi @sareykaj We'll definitely look into these inconsistencies so that workarounds aren't necessary. Will keep you updated on this thread.

**Comment by QAautomatedNI** [comment] 2017-09-08 15:12
Is there a known workaround for this?  Tried removing properties with null values from the data object.   Then created environment variables and set them to null in a pre-request script.  However, the request appears to be executing before the environment variables are set (issue 3480).

**Comment by ashishkumarjoshi-accolite** [comment] 2018-09-20 05:57
[samplePostmanScriptData.txt](https://github.com/postmanlabs/postman-app-support/files/2399819/samplePostmanScriptData.txt)

I am facing the same issue. Other than string variables, everything is getting parsed as Object. 

![postmanrunnerissue](https://user-images.githubusercontent.com/38347722/45798523-d1d96800-bcc7-11e8-9017-80765526e9dc.PNG)

escaping the curly braces "{ }" is not working. Can anyone suggest what can be done here.?

**Comment by ryannnnnn** [comment] 2019-02-01 01:14
I got around this for now by stringifying the object from iterationData and putting it into environment data with a different name name:

`pm.environment.set('myObject2', JSON.stringify(pm.iterationData.get('myObject')))`

**Comment by coditva** [comment] 2019-07-30 05:43
As can be verified by looking at the exported `.json` files, there are no inconsistencies between **environment** and **data** variables. This is the intended behaviour because data is to be imported as it is and not `JSON.stringify`-ed.

For the use case that is mentioned above, as @ryannnnnn said, the "correct" way to send the request would be to `JSON.stringify` the variable in the `pre-request` script and put it in the local, environment or global variable.
Or, as @sareykaj said, to use the stringified value in the `data.json` file itself.

Closing this issue because it is the intended behaviour. If you have any follow-up questions, feel free to send in a comment!

**Closed as completed by coditva** 2019-07-30 05:43 UTC
Labels: bug, variables, product/runtime
