### ISSUE TITLE
Custom snippets for test code

### ISSUE THREAD

**Issue by npadhya** [a85/POSTMan-Chrome-Extension#2593] opened 2016-12-26 08:42 UTC
Feature request

Currently, Postman's Test tab have the list of Code snippet that helps the beginner.
Can we have a way to add custom snippets so working with tests and helping the team become easier?

**Comment by kunagpal** [comment] 2016-12-29 11:11
Duplicate of #675

**Closed as completed** 2017-01-10 07:34 UTC
Labels: feature
