### ISSUE TITLE
Can't manage more than 8 presets headers

### ISSUE THREAD

**Issue by guilhermepaula** [a85/POSTMan-Chrome-Extension#4752] opened 2018-06-29 14:17 UTC
I have some headers presets configured and since some versions ago I can't manage them. The menu opens behind the window if has more than 8 presets.

I'm using the lastest version (6.1.4) and it occurs in macOS and Ubuntu. 

![screen shot 2018-06-29 at 11 04 11](https://user-images.githubusercontent.com/5208238/42097202-e652651e-7b8d-11e8-8836-d31742d86fa2.png)

**Comment by prashantagarwal** [comment] 2018-06-29 17:14
Duplicate of #4748

**Closed as completed by prashantagarwal** 2018-06-29 17:14 UTC
Labels: bug

**Comment by prashantagarwal** [comment] 2018-06-29 17:17
@guilhermepaula We have fixed this and released it on our canary apps for now. It will soon be available for the Postman app itself in next release. You can download canary apps from https://www.getpostman.com/canary
