### ISSUE TITLE
using Postman Proxy to Capture https requests 

### ISSUE THREAD

**Issue by zxning** [a85/POSTMan-Chrome-Extension#2207] opened 2016-07-28 08:26 UTC
I want to using Postman Proxy to Capture https requests from Android Devices, but ,according to the following:
http://blog.getpostman.com/2016/06/26/using-postman-proxy-to-capture-and-inspect-api-calls-from-ios-or-android-devices/

In Android Devices my app's request failed

**Comment by shamasis** [comment] 2016-08-01 22:25
Very little information for me to start with. :-/
1. are you on same wifi network on phone and computer?
2. can you ping your phone from computer and vice versa?
3. have you set correct ports in both device and postman app?

**Comment by zxning** [comment] 2016-08-28 10:18
1. the same wifi.MAC wifi 192.168.1.109,Phone wifi 192.168.1.107
2. yes
3. use the defaut  port  ：5555。

note:
the phone's http request can be captured by postman, and I can see them in the history

but https request  cannot be captured

**Comment by loveiset** [comment] 2016-12-26 03:57
ran into the same problem.
Did you have found the solutions?

**Comment by paperp** [comment] 2017-11-03 08:05
the same problem too.Anyone have solutions?

**Comment by skyboyer** [comment] 2017-12-07 10:20
I believe this one and #3013 are about the same

**Comment by a85** [comment] 2017-12-11 14:55
Closing this as duplicate of #3013

**Closed as completed by a85** 2017-12-11 14:55 UTC
Labels: support
