### ISSUE TITLE
Add new feature

### ISSUE THREAD

**Issue by BardinValentin** [a85/POSTMan-Chrome-Extension#9226] opened 2020-11-03 09:44 UTC
Hello
Please, consider adding functionality like drag and drop multiple requests from folder to folder and collection to collection
Now it is possible to drag and drop by one request

**Comment by DannyDainton** [comment] 2020-11-03 14:56
Closing this as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1066

**Closed as completed by DannyDainton** 2020-11-03 14:56 UTC
Labels: duplicate
