### ISSUE TITLE
Inconsistency within Postman's Import + related feature request

### ISSUE THREAD

**Issue by hlubovac** [a85/POSTMan-Chrome-Extension#3821] opened 2017-11-16 19:05 UTC
When I choose to import a swagger-json via the app's main "Import" button/dialog, all swagger-defined variables (`{variable-name-here}`) get transformed to this pattern: `:variable-name-here`.

It would be helpful if Postman-Import imported this using this pattern instead: `{{variable-name-here}}`.

It would also be helpful if a concept of variable-groups is introduced, importable into environments, and then - during import - those variables are automatically created as a new variable-group (maybe with blank values), so that we could later start to use imported request-entries much quicker. As it is now, this process is manual (unless I don't see something important), and when the imported collection is large, it translates to a lot of work.

I already tried changing `{variable-name-here}` within swagger file to `{{{variable-name-here}}}`, hoping that would somehow result in `{{:variable-name-here}}` (so that I could, as a shortcut, define a Postman-variable as `:variable-name-here` instead of `variable-name-here`), but the import spit out `:::variable-name-here` instead, so that was a disappointment also.

Thanks.
Hari

**Comment by hlubovac** [comment] 2017-11-16 19:23
Maybe even take this a little further and also provide JS templates for pre-request and test scripts. I know you cannot possibly know how to obtain a value from a response content of a request (so that it can be passed to another request as a variable, via test script, when these requests are set up to execute in chain), but if there is some nifty JS template already defined for me, with a function call taking xpath-like strings to locate values (there could be multiple) in json file (for example), where I could then just adjust that code/path and reorder request-definitions, then set them up to all execute in a row - then this app would be even "awesomer". 

In case you're looking for ideas :)

**Comment by abhijitkane** [comment] 2019-08-13 12:57
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/4598

**Closed as completed by abhijitkane** 2019-08-13 12:57 UTC
Labels: importer
