### ISSUE TITLE
postman 6.2.5 and 6.3.0 for windows hangs on launch

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#5159] opened 2018-09-10 06:18 UTC
**Bug description**
Postman hangs on screen with rotating travellers.

**To Reproduce**
1. Launch app

**Expected behavior**
App launches correctly and open my workspace

**Screenshot**
Applied

**App information (please complete the following information):**
 - App Type: Native App for windows 32
 - Postman Version 6.2.5 and 6.3.0 (Previous version launches successfully)
 - OS: Windows 7 32 bit

**Additional context**
Log data applied
![postman63log](https://user-images.githubusercontent.com/25632818/45279633-71357880-b4da-11e8-9335-865cce1c6ec7.png)
![postman](https://user-images.githubusercontent.com/25632818/45279634-71357880-b4da-11e8-984c-30f30f881d46.png)

**Comment by salimusta** [comment] 2018-09-10 23:05
I get the same thing, I was 6.0.3, the update was failing,

Deleted and downloaded the new 6.3.0. Now hanging ..... HELP !!!

Im on MacOS

**Comment by SamvelRaja** [comment] 2018-09-11 08:38
Related to https://github.com/postmanlabs/postman-app-support/issues/4897

**Comment by kamalaknn** [comment] 2018-09-11 08:45
@m3dbedb The original issue posted here is a duplicate of #4897 Can you try the workaround suggested in the parent thread?

**Closed as completed by kamalaknn** 2018-09-11 08:45 UTC
Labels: bug

**Comment by m3dbedb** [comment] 2018-09-13 09:36
Thank you, run from command line with --disable-gpu helped.

**Comment by m3dbedb** [comment] 2018-11-20 14:40
On version 6.5.2 it is still present on tab switching.
