### ISSUE TITLE
New Integration Request - Azure DevOps

### ISSUE THREAD

**Issue by AlthalusDGr8** [a85/POSTMan-Chrome-Extension#10306] opened 2021-09-20 07:44 UTC
### Describe your current workflow

Similar to the colleciton backup to GitLab and DropBox, it would be nice to have the option to have the abiilit to save to Azure DevOps

### Describe your ideal workflow

Ideally this backup is done automatically :)

### Describe alternatives you've considered

Backup is currently done with a manual export

**Comment by shashankawasthi88** [comment] 2021-09-20 11:20
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/10280

**Closed as completed by shashankawasthi88** 2021-09-20 11:20 UTC
Labels: feature, product/integrations
