### ISSUE TITLE
Can't move item in folder

### ISSUE THREAD

**Issue by HarryF514** [a85/POSTMan-Chrome-Extension#3349] opened 2017-08-04 20:57 UTC
## App Details:

```
Postman helps you develop APIs faster
Postman for Linux
Version 5.1.3
linux 3.16.0-4-amd64 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: previous version existed too.
 2. Expected behaviour: drag and move item in folder should move.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

xml.js:22 Requests not found in order

 4. Screenshots (if applicable)

1. create a collection
2. create a folder
3. create some items in the folder.
4. drag to change order of items.

**Comment by fuintis** [comment] 2017-08-08 03:13
Same issue on Windows 7 box. In previous version this bug existed but not always showed. In latest version of Postman, always shown.

**Comment by mslancashire** [comment] 2017-08-09 12:33
I have the same issue, can't move any item about within a folder.  I have been able to do this in previous versions.

`Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 59.0.3071.115`

Using Chrome developer tools I see an error pop in the console:
`Requests not found in order`

Comes from common.js line 127152.

**Comment by SamvelRaja** [comment] 2017-08-09 12:47
@mslancashire can you provide some more debug information?
What type of collection it is?
1. Imported
2. Shared (Owned)
3. Subscribed (Owned by someone else)
4. Not shared own collection

` I have been able to do this in previous versions.`
Do you have idea on which version of the app you could able to do it properly?

**Comment by Faz540** [comment] 2017-08-09 14:07
I've had this issue occur for me (Windows App/ Windows 10 64 bit)

**Example:**
I have an existing collection with a child folder in them.
I duplicate a request inside the child folder and it's moved to the bottom of the child folder.
If I attempt to move the duplicate request anywhere else in that child folder, it moves outside the child folder and is moved to the bottom of the parent folder (the collection folder).

This doesn't happen to me 100% of the time, but I've had it happen 4 times in the last 2 days.
I was able to move this request after closing/opening the app sometime later and seeing the usual sync conflict popup.

**Comment by mslancashire** [comment] 2017-08-09 14:25
Can't tell you the exact version but it was before the Sub Collection / Child Folder feature was added.  I use Postman for post deployment checks, the order they run in is important.  I remember arranging the order of the items about a week ago if that helps.

The collection is not an imported collection built and owned by myself.  It has been exported thou for use by the build server.

I use simply using standard Postman app in Chrome not the Pro version.

**Comment by Faz540** [comment] 2017-08-09 15:33
Just happened again!

I've managed to get around the issue for now by moving the older requests below the new request that cannot be moved. This only seems to occur with the newly created request...sync issue? I'm able to move the older requests without a problem.

I recreated this by following my example above.

**EDIT:**
By the time I wrote this comment, I was then able to move the newly created request where I wanted.

**Comment by HarryF514** [comment] 2017-08-09 21:19
I can't move old request in a folder neither.

**Comment by deinspanjer** [comment] 2017-08-10 16:04
I'm using Postman app Version 5.1.3 (5.1.3) on OSX 10.12.6 (16G29) and have hit the same issue.

I have a shared collection with 73 requests saved across 15 folders.  Trying to drag a request from the bottom position in a folder to the middle position in the same folder fails.

I am able to drag it into a different folder, and then back into the old folder.
After I do so, if I try to drag it to a different position in the folder, it pops *out* of the folder and into the root of the collection.
I am able to take it from there and put it back in the folder again.

When I try dragging entries in my `Postman Echo` collection's folders, it works fine.
I tried making a copy of the `Postman Echo` collection and sharing it, but dragging still works fine with the copy, so I suspect some sort of corruption maybe with the larger collection that is exhibiting the problem?

Interesting! I opened the dev console, and saw the following messages:
[-1502381328906.log.txt](https://github.com/postmanlabs/postman-app-support/files/1215560/-1502381328906.log.txt)
The save didn't appear to capture the file and line number of the error: `_reorderRootLevelRequests @ requester.js:222051`

I tried dragging a few items within a folder again and it worked, but then trying to drag it into the middle of the list failed.

At one point, I also saw the following error as a toast notification:
Response too large. The response body for "Show the Unassigned tree" cannot be synced. The maximum length for the response text is 100000 characters
Note that this was only during attempting the move of a request.  That example had previously been saved with no problem and it was not the item I was attempting to move.

I tried trimming down the response body in that big example and my re-ordering started working consistently.

**Comment by mslancashire** [comment] 2017-08-11 14:48
Don't know if this helps but I have a work around.

So for Folders that you can not change the order of requests by drag and dropping. Create a new Folder, move all your requests to the new Folder, drag and drop now works in the new folder.

Looking at the debugger when you move requests about in in the old folder and it fails to be moved a
`Requests not found in order` exception is thrown.

The cause of this comes from `collection.get('order')` returning `null` as the rest of the code in the `function _reorderRootLevelRequests(collectionId, sourceRequestId, destinationRequestId, position)` function fails to determine the new position of the item in the folder.

I thought I'd then see what happens in the function when moving items about successfully in the new folder. I added a break point to the start of that function and moved an item in the new folder the break point is not even hit.

No idea if this information is of any use but thought I'd post it anyway.

**Comment by a5ync** [comment] 2017-08-11 18:22
@harryyuanfeng @mslancashire I think I've found another workaround. If you create a duplicate of the directory You are trying to re-order, the clone will allow you to re-organize the collection. 
Then delete the original directory/subdirectory and rename the duplicate.

**Comment by HarryF514** [comment] 2017-08-14 14:12
@a5ync verified that it is a valid work around.

**Comment by mjkraner** [comment] 2017-08-14 20:01
This issue is SO frustrating, please fix soon!

**Comment by Faz540** [comment] 2017-08-18 08:11
Not sure if this is helpful, but I opened DevTools when the bug was occurring.
Whenever I attempted to move the request into the position I wanted, the issue occurred and it was moved to the bottom of the collection and the below error was displayed in DevTools:

![image](https://user-images.githubusercontent.com/9334128/29450051-0bc4e6fa-83f5-11e7-88f9-4bc38897e038.png)

It seems to fix itself after a couple of minutes, but it's very annoying.

**Comment by SamvelRaja** [comment] 2017-08-22 06:11
We pushed out *Canary app(5.2.0-canary02)* with fixes for reordering problem you all facing

Just download and install the app according to your os.
*NOTE:*  Backup the data in current app using Settings -> Data -> Export  for additional security.

https://dl.pstmn.io/download/channel/canary/osx_64
https://dl.pstmn.io/download/channel/canary/windows_32
https://dl.pstmn.io/download/channel/canary/windows_64
https://dl.pstmn.io/download/channel/canary/linux_32
https://dl.pstmn.io/download/channel/canary/linux_64

**Comment by SamvelRaja** [comment] 2017-08-22 06:11
Closing in favor of #3291

**Closed as completed by SamvelRaja** 2017-08-22 06:11 UTC
