### ISSUE TITLE
Body isn't removed from JSON when changing requests from PUT to GET

### ISSUE THREAD

**Issue by claireriley** [a85/POSTMan-Chrome-Extension#4963] opened 2018-08-03 23:19 UTC
**Describe the bug**
Body of request is not removed from JSON export when you change it from PUT to GET (after saving first as PUT). Does not appear to be in other conversions (checked PUT and PATCH - didn't happen). 

**To Reproduce**
1. Create a new PUT request with something in the body
2. Save it to a collection (any collection is fine)
3. Change the request method to GET
4. Save changes
5. Export or View in web - body is still there

**Expected behavior**
Body should be deleted along with everything else :(

**Screenshots**
<img width="370" alt="screen shot 2018-08-03 at 4 14 36 pm" src="https://user-images.githubusercontent.com/21180383/43669511-6da44698-9738-11e8-9602-96debdbf0f66.png">
<img width="442" alt="screen shot 2018-08-03 at 4 18 12 pm" src="https://user-images.githubusercontent.com/21180383/43669575-de03d110-9738-11e8-8ab9-48d22566e028.png">

**App information (please complete the following information):**
Mac App
Version 6.2.3
OS X 17.6.0 / x64

Also reported on Windows 6.2.3

**Comment by numaanashraf** [comment] 2018-08-04 05:28
Duplicate of #4502

**Closed as completed by numaanashraf** 2018-08-04 05:28 UTC
