### ISSUE TITLE
Can't open Postman

### ISSUE THREAD

**Issue by nivance** [a85/POSTMan-Chrome-Extension#5028] opened 2018-08-15 04:42 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Can't open the Window of Postman，

**To Reproduce**
1. Launch the Postman in Windwos
2. whirl and can't go to the next step

**Screenshots**
![](https://user-images.githubusercontent.com/3291404/44130840-09463c6c-a082-11e8-87cb-486e37885d24.jpg)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Winidows App]
 - Postman Version [e.g. 6.2.4]

**Comment by sivcan** [comment] 2018-08-15 05:44
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4703

**Closed as completed by sivcan** 2018-08-15 05:44 UTC
