### ISSUE TITLE
Keyboard shortcuts in other countries

### ISSUE THREAD

**Issue by sandorsasovits** [a85/POSTMan-Chrome-Extension#5649] opened 2018-12-14 11:51 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Hungarian language keyboard layout has the @ character on the "V" key. We can use it only by pressing AltGr + V. Which is a keyboard shortcut in Postman for the "Toggle Two-Pane View" functionality. It gets a bit more annoying every time I am typing some text in Postman and it does this toggling.

**To Reproduce**
1. Press AltGr+V roughly anywhere
3. See window horizontal/vertical flip, window appears/disapperas

**Expected behavior**
I press AltGr+V and nothing special happens OR keyboard shortcuts can be edit.

**Screenshots**
![ Image of hungarian keyboard ](https://notebookker.cdn.shoprenter.hu/custom/notebookker/image/cache/w1000h800wt1/Rakt%C3%A1r%20k%C3%A9pek/Billenty%C5%B1zetek/hp-6460b-magyar-billenty%C5%B1zet.jpg?lastmod=1543232164.1543263481)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] (idk what should i type here)
 - Postman Version 6.6.1 (latest, any version, doesnt matter)
 - OS: Win10x64pro

**Additional context**
Nothing, and thanks!

**Comment by sujayvenaik** [comment] 2018-12-17 05:25
Duplicate of #2096

**Closed as completed by sujayvenaik** 2018-12-17 05:25 UTC
