### ISSUE TITLE
JSON schema validation with ajv - it always fails if users add an Object.prototype function before the validation.

### ISSUE THREAD

**Issue by franksunnn** [a85/POSTMan-Chrome-Extension#8064] opened 2020-02-14 16:57 UTC
**Describe the bug**
In my test environment, I have to create some Object.prototype functions before the tests and makes test scripts benefit from those functions.
However, I've found once the functions exist, the JSON schema validation always fails.

**To Reproduce**
1. In Postman, take the official test - GET Request as an example. 
    Call the request GET https://postman-echo.com/get?test=123
2. Override the original test script by the following one
```
const ajv = new require('ajv')();

let response = pm.response.json(),
    schema_response = {
        "type": "object",
        "required": ["args", "headers", "url"],
        "properties": {
            "args": {"$ref":"#/args"},
            "headers": {"$ref":"#/headers"},
            "url": {"type": "string"}
        },
        "args": {
            "type": "object",
            "required": ["test"],
            "properties": {
                "test": {"type": "string"}
            }
        },
        "headers": {
            "type": "object",
            "required": ["x-forwarded-proto", "host", "accept", "accept-encoding", "cache-control", "cookie", "postman-token", "user-agent", "x-forwarded-port"],
            "properties": {
                "x-forwarded-proto": {"type": "string"},
                "host": {"type": "string"},
                "accept": {"type": "string"},
                "accept-encoding": {"type": "string"},
                "cache-control": {"type": "string"},
                "cookie": {"type": "string"},
                "postman-token": {"type": "string"},
                "user-agent": {"type": "string"},
                "x-forwarded-port": {"type": "string"},
            },
        }
    };

pm.test('validate schema', function(){
    pm.expect(ajv.validate(schema_response, response)).to.true;
})
```
3. Click Send button to run the test and you will see the test passes.
4. Repeat the step 2 but add an Object.prototype function before the test. Here's the code snippet:
```
Object.prototype.function1 = (query, variables) => ({
    query: query,
    variables: variables
});
const ajv = new require('ajv')();

let response = pm.response.json(),
    schema_response = {
        "type": "object",
        "required": ["args", "headers", "url"],
        "properties": {
            "args": {"$ref":"#/args"},
            "headers": {"$ref":"#/headers"},
            "url": {"type": "string"}
        },
        "args": {
            "type": "object",
            "required": ["test"],
            "properties": {
                "test": {"type": "string"}
            }
        },
        "headers": {
            "type": "object",
            "required": ["x-forwarded-proto", "host", "accept", "accept-encoding", "cache-control", "cookie", "postman-token", "user-agent", "x-forwarded-port"],
            "properties": {
                "x-forwarded-proto": {"type": "string"},
                "host": {"type": "string"},
                "accept": {"type": "string"},
                "accept-encoding": {"type": "string"},
                "cache-control": {"type": "string"},
                "cookie": {"type": "string"},
                "postman-token": {"type": "string"},
                "user-agent": {"type": "string"},
                "x-forwarded-port": {"type": "string"},
            },
        }
    };

pm.test('validate schema', function(){
    pm.expect(ajv.validate(schema_response, response)).to.true;
})
```
5. Click Send button to run the test and test failed.
6. See error
```
validate schema | Error: schema is invalid: data.properties['function1'] should be object,boolean
```

**Expected behavior**
I expect the JSON schema validation succeeds along with my pre-defined Object.prototype functions.

**Screenshots**
None

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : Version 7.16.0 (7.16.0)
 - OS: macOS Catalina Version 10.15.3

**Additional context**
Is the bug reproducible every time, or do you see it occasionally? - Yes

Did you first encounter it recently, or has it always been there? - I recently encountered it after I switched ajv.

**Comment by franksunnn** [comment] 2020-02-18 19:50
Updated:
I've found the deprecated schema validation lib tv4 encounters the same problem.
It'll error out too if we add Object.prototype before the test.

**Comment by vikiCoder** [comment] 2020-03-12 06:41
Hi @franksunnn,

I tried running the following script outside the Postman app in Node. It also gives the same error while validating. So it seems to be a problem with `ajv` not with the Postman app. Closing this issue because the problem is not related to the Postman app.

![image](https://user-images.githubusercontent.com/16588032/76494222-69052300-645a-11ea-8b1c-4e5857c0c1d5.png)

**Closed as completed by vikiCoder** 2020-03-12 06:41 UTC
Labels: bug, product/runtime
