### ISSUE TITLE
Prompt to set/update variables before sending a request

### ISSUE THREAD

**Issue by VaishnaviChallaPostman** [a85/POSTMan-Chrome-Extension#10448] opened 2021-11-18 15:26 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Let's say we are trying to run the function add(a,b) where a,b are inputs that have to be entered every single time. By using env variables - (a,b) are replaced by default with those values - we don’t get an opportunity (or the cue) to reset them before trying. 

### Describe the solution you'd like

A prompt to set/update variables (user inputs) before sending the request.

### Describe alternatives you've considered

One stop-gap solution is to leave the environment variables empty so that we end up defining these values every attempt.

### Additional Context

Already being tracked internally. Logged here for public tracking.

**Comment by DannyDainton** [comment] 2021-11-18 15:43
Closing as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/285

**Closed as completed by DannyDainton** 2021-11-18 15:43 UTC
Labels: feature, duplicate
