### ISSUE TITLE
Password Protected Private API Documentation 

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#7084] opened 2019-08-08 17:42 UTC
**Is your feature request related to a problem? Please describe.**
As a developer team, I would like to share our API docs with **_only_** our customers. 

**Describe the solution you'd like**
I would like to have a password-protected link to my documentation to help my customer base consume our API without making it public, and without adding every customer to my team.

**Describe alternatives you've considered**
Any way to make the documentation private to outside my team.

**Comment by Raja-Simha** [comment] 2019-08-09 05:14
Duplicate of #6681

**Closed as completed by Raja-Simha** 2019-08-09 05:14 UTC
Labels: feature, product/documentation

**Comment by MichaelPeter-Shockoe** [comment] 2019-10-10 21:09
@Raja-Simha I do not believe this is a duplicate of the issue you mentioned. That issue describes a use case where the documentation is still consumed only by logged in team members. The ask here is for limited public sharing outside of the team.

My team also has a strong use case for this. We work with a number of clients who would benefit from viewing our API documentation but do not merit a seat on our team as a developer.

Could this be reopened?

**Comment by rfonrouge** [comment] 2020-04-16 08:49
Same need here. We would like to publish the documentation to our customers, but the public link is very weak. Adding a password would make the link a bit less transferable.

**Comment by ariadnavaldivia** [comment] 2023-09-14 01:37
Yes, this is something very necessary please.
