### ISSUE TITLE
Postman Environment Variables are not being Sync properly

### ISSUE THREAD

**Issue by Siddhant125** [a85/POSTMan-Chrome-Extension#10958] opened 2022-05-30 12:15 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Update in Environment Variables are not being sync properly in our team.

Example:
Environment  variable on my desktop application:
![image](https://user-images.githubusercontent.com/44401619/170989243-729021ce-0e26-418a-9b9d-f24ac87b4fbd.png)

Same Environment Variable in Web application:
![image](https://user-images.githubusercontent.com/44401619/170989427-af87826c-507f-475c-be2a-d920baa5a6bd.png)

Same Environment Variable in my teammates desktop application, after clicking multiple times on sync button:
![image](https://user-images.githubusercontent.com/44401619/170991627-4e41e247-98a6-4a39-939b-50bdd077cfe7.png)

### Steps To Reproduce

1. Make a change in Environment Variable using Postman desktop application.
2. Sync the change to Postman Web Application.
3. Ask your teammate to check and confirm if the change in Environment variable is reflected in his postman desktop application.

### Operating System

Windows

### Postman Version

9.20.3

### Postman Platform

Postman Web

### Additional Context?

Version 9.19.3 on Desktop Application

**Comment by Siddhant125** [comment] 2022-05-30 12:20
Correct screenshot for my teammates desktop application
![image](https://user-images.githubusercontent.com/44401619/170991086-07306dcf-ceab-499b-9956-43f6d493754a.png)

**Comment by giridharvc7** [comment] 2022-05-30 12:47
@Siddhant125 did you press the `Save` button on the Global environment?

**Comment by Siddhant125** [comment] 2022-05-30 12:50
Yes, only then it was synced to web application. I first made the change on my desktop application, then synced that change with web application. After that when my teammate clicked on his sync button in desktop application, he cannot see the changes in Global Variables.

**Comment by giridharvc7** [comment] 2022-05-31 08:45
Just to be clear, are we referring to the button over here?
<img width="1016" alt="Screenshot 2022-05-31 at 2 15 33 PM" src="https://user-images.githubusercontent.com/1040583/171132240-a60d55f1-2d77-4a3b-aa4e-891db2017b54.png">

**Comment by Siddhant125** [comment] 2022-06-01 12:25
Let me try to reproduce the issue one more time, I will get back to you.

**Comment by Siddhant125** [comment] 2022-06-01 13:04
Ok, we have tried again and here are findings.

Test 1:
I update environment variable, current value in my Desktop application, clicked on Save and clicked on Sync.
![image](https://user-images.githubusercontent.com/44401619/171407627-d77b8a06-9f1e-4868-b909-c4dcccabd3c3.png)

The update was not reflected in Postman Web Application - Environment Variables.
![image](https://user-images.githubusercontent.com/44401619/171407779-62e1a7a7-4bf3-439a-a780-7d18349580c8.png)

Test 2:
I updated one variable from Postman Web Application, clicked on Save and then clicked on Sync.
Again the update was not reflected in desktop application.

Test 3:
I created a new environment variable in desktop application, clicked on save and clicked on Sync.
![image](https://user-images.githubusercontent.com/44401619/171408631-422cd046-c0a9-4fd2-aea5-cdfaafc076a3.png)

Refreshed the web page and then I can see the new variable was reflected in Web application.
![image](https://user-images.githubusercontent.com/44401619/171410732-01c08108-e31e-4250-91fc-4c91c8130482.png)

After this, I asked my teammate to check on his side and he also confirmed that we was able to see the new variable but he can't see any updates on the existing variables.
![image](https://user-images.githubusercontent.com/44401619/171410969-51cee132-f297-4f9f-8407-08e570fc6177.png)


Here is my understanding of the issue then.
It seems the sync is not working when we are updating the values in the existing variables. But it works when a new variable in created.

**Comment by giridharvc7** [comment] 2022-06-09 05:38
@Siddhant125 Thank you for the detailed explaination. Apologies for the delayed response. 

Can you confirm if the changes you make and save in the `Initial Value` of the environment variable is visible to your teammates and yourself? 

The `Current values` of the environment are local to you and your client. The current value is not synced to postman servers, so you might not be seeing these between desktop and web app - neither can your teammates see it.

**Comment by Siddhant125** [comment] 2022-06-09 06:58
Yes, the changes to Initial value are being synced properly.

**Comment by giridharvc7** [comment] 2022-06-14 17:59
This is an intended behavior, read more about it [here](https://learning.postman.com/docs/sending-requests/variables/#:~:text=Initial%20values%20are%20shared%20when,on%20local%20versus%20synced%20variables.)
Closing this ticket.

**Closed as completed by giridharvc7** 2022-06-14 17:59 UTC
Labels: bug, Environments, product/runtime
