### ISSUE TITLE
Sync is delayed or not working

### ISSUE THREAD

**Issue by johnnavarra** [a85/POSTMan-Chrome-Extension#1131] opened 2015-06-10 15:10 UTC
It seems that at all times, the sync will take the server settings rather than the local settings. I've lost so much in the past hour from the sync overwriting my local settings.

**Comment by abhijitkane** [comment] 2015-06-10 15:24
Did you sign out and sign in and see the local changes overwritten? Or was the app open and did the local changes get replaced with the server values?

**Comment by johnnavarra** [comment] 2015-06-10 15:45
The app was open and the local changes were replaced with the server
values. On app reload, I was prompted to re-sync and verify the values. I
selected the ones that were proper on local but the server asserted it's
values anyways.

On Wed, Jun 10, 2015 at 11:24 AM, Abhijit Kane notifications@github.com
wrote:

> Did you sign out and sign in and see the local changes overwritten? Or was
> the app open and did the local changes get replaced with the server values?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/a85/POSTMan-Chrome-Extension/issues/1131#issuecomment-110794496
> .

## 

AIM: obliviouslyaware
ICQ: 5147787
googletalk

**Comment by LexFrench** [comment] 2015-06-11 22:59
Yeah, I've been seeing this issue as well. Does Postman sync when changes are made to a collection or does it poll every few minutes to see if a change was made and then sync?

**Comment by abhijitkane** [comment] 2015-06-12 07:28
If the app is connected to the server, every change that you make is synced in real-time. Are there any specific properties (request url / collection name) etc for which you saw the conflict screen not work properly?

**Comment by gerob** [comment] 2015-06-12 14:25
I find the same issue when my system goes to sleep (OSX), when it wakes up it's no longer syncing and clicking sync will not reenable it. I have to close the program and reopen it to get it to sync again. I also have to be sure to export my collection before closing it so that I can reimport when Sync overwrites what I have done locally.

**Comment by abhijitkane** [comment] 2015-06-12 15:02
@gerob - Do you see a screen asking you to choose between local values and server values? Or are your local changes simply overwritten without any notification?

**Comment by gerob** [comment] 2015-06-12 17:41
@abhijitkane I am on the Team sync beta to clarify. I get no screen asking me about choosing between values. Just an overwrite. My version shows 3.0.0.30.

**Comment by brothhaar** [comment] 2015-07-13 21:14
I'm seeing the same thing. I make changes to my local collections and then they disappear shortly after. Pleeeeeease fix.

**Comment by abhijitkane** [comment] 2015-07-13 21:15
@brothhaar Can you send an email to help@getpostman.com with your Postman username?

**Closed as completed** 2015-08-20 06:33 UTC
Labels: bug

**Comment by soodyravi** [comment] 2016-06-17 18:10
Hi,
I logged out of postman and when I logged in all my collection were lost.
I noticed that the sync status is always offline.
When i logged in I see the connecting status but then it changes to offline within few mins.
Please help/advice

**Comment by saithis** [comment] 2017-11-16 13:21
I have the same issue. 

I was editing a collection (adding/modifying/renaming request) and suddenly a screen asking me to choose between local values and server values appeared. I chose the local values(they were pre-selected), clicked resync and it deleted all my edits. This happened about 4-6 times in the last 2 hours. I restarted postman several times in the hope it wouldn't happen again afterwards... 

I'm now exporting after every change and reimport after every sync-delete. It's a pain in the ass :/

**Comment by kondal99** [comment] 2017-11-30 06:22
I am having same issue, edited couple of collections and suddenly a screen popup, asking me to choose local/server values, I selected local values and clicked on resync.  It deleted all my edited collection. Postman always having sync issues.

**Comment by soroushchehresa** [comment] 2018-01-23 14:29
The problem is happening when use more than one account in postman! 

**steps to resolve this issue:**
1: sign out from all accounts
2: login to postman with one account
3: 👍  in sync

**note:**
if you don't want to sign out from your accounts, you can use google chrome postman app :)

**Comment by d4v1dst** [comment] 2018-03-21 16:05
Just ensure to backup your collections in your local, then you can import it again.
