### ISSUE TITLE
Postman 8.0.3, not loading all history

### ISSUE THREAD

**Issue by remcolam** [a85/POSTMan-Chrome-Extension#9513] opened 2021-02-01 08:36 UTC
Postman is not loading in the history, it is only loading a few days, and only once you scroll to the end, will it continue loading the next few days. 

When you search, it will not find any requests that have not yet been loaded. So trying to get to a request from a month ago, takes you several minutes of scrolling and then finally you can start searching for it. 

However, as soon as you restart postman, the history is empty again and the whole thing needs to be redone. 

**Environment Information**

 - Platform Type: Native desktop app & Postman on the web
 - Postman Version: 8.0.3
 - Operating System: Windows 10

**Comment by DannyDainton** [comment] 2021-02-01 08:43
Hey @remcolam

Could you provide a short recording of this issue please?

**Comment by remcolam** [comment] 2021-02-01 08:49
Here it is, very short, in a small screen, to stay under the 10 mb...

https://user-images.githubusercontent.com/11367055/106435109-bb846f00-6472-11eb-8a50-a5f6ce7ddb82.mp4

**Comment by DannyDainton** [comment] 2021-02-01 08:54
While this is loading, is the sync status still 'syncing' - You should be able to see this if you click/hover over the sync icon.

**Comment by remcolam** [comment] 2021-02-01 08:56
No, it is green.

![image](https://user-images.githubusercontent.com/11367055/106435888-b8d64980-6473-11eb-8d48-cb43c539f93b.png)

and the tooltip says:

![image](https://user-images.githubusercontent.com/11367055/106435925-c4297500-6473-11eb-8235-7a6abfa48dae.png)

**Comment by mccannt** [comment] 2021-04-12 23:45
Closing out this issue as its a duplicate of [9566](https://github.com/postmanlabs/postman-app-support/issues/9566)

**Closed as completed by mccannt** 2021-04-12 23:45 UTC
Labels: bug, history, product/runtime

**Comment by remcolam** [comment] 2021-04-13 04:06
Tss, this is not a duplicate, the other one is a duplicate, this one was earlier ;)

**Comment by Naif95** [comment] 2021-05-22 00:57
I have the same issue and it's very annoying for me as a developer working on many different projects.

**Comment by UjjualUSspericorn** [comment] 2022-01-25 10:25
Have they fixed this issue ?

**Comment by Naif95** [comment] 2022-01-25 10:56
No

**Comment by andersonb** [comment] 2023-08-25 14:24
it hasn't been fixed yet
