### ISSUE TITLE
feedback: Postman's designed to store its stuff in a hidden database...

### ISSUE THREAD

**Issue by ishepherd** [a85/POSTMan-Chrome-Extension#3910] opened 2017-12-05 21:11 UTC
## App Details:

```
Postman for Windows
Version 5.4.1
win32 6.1.7601 / x64
```

## Issue Report:

I read [this blog post on backup/sync of Postman collections](http://blog.getpostman.com/2017/03/10/backup-and-sync-your-postman-collections-on-github/) and got irritated because it's my main bugbear with Postman:

Couldn't it store its collections as normal directories?
Containing tests and environments as text files?
In my choice of location - ie a local git repo?

Then we don't need a GitHub sync feature - because we have Git! we also have diff, we have alternative editors, templating languages, etc. All of that could 'just work' if Postman wasn't locking up its stuff in a special database

**Comment by sdnts** [comment] 2017-12-06 11:21
@ishepherd Thanks for the feedback! We currently use IndexedDB to store all data. This dates back to when Postman was just a Chrome extension, so writing to files was not an option. However, this can be revisited for our native apps.
I can definitely appreciate your use case. We will look into this :)

**Comment by a85** [comment] 2017-12-11 13:05
There are other data types (test results, sessions, certificates, application state) that Postman stores and storing them in a git repository is not feasible - which means Postman now needs to maintain it's own data store as well as everything the filesystem has. For API collaboration, Git repositories then need to be accessible across several teams which means everybody needs to have access to these special repos. Contrary to popular perception, not everybody who uses APIs uses Git. Closing this as a duplicate of #3563 for now.

**Closed as completed by a85** 2017-12-11 13:06 UTC

**Comment by ishepherd** [comment] 2017-12-11 20:22
@a85 Beyond git, it would mean that Postman now plays in the whole wide universe of file-based tools. For example, I could `grep` my tests to see if a particular endpoint is covered.

Current situation feels like my tests belong to Postman instead of to me. I do get that while you were a Chrome extension you were stuck like that. But now spread your wings :)

**Comment by vikasInfo** [comment] 2018-05-28 06:39
![image](https://user-images.githubusercontent.com/38036767/40600636-d73fc5c6-626f-11e8-949a-fe4f63527d7b.png)

i am not able to select get or post method here.
