### ISSUE TITLE
Can't create a monitor configuration with a new user

### ISSUE THREAD

**Issue by thiagobxc** [a85/POSTMan-Chrome-Extension#8552] opened 2020-05-27 15:09 UTC
Postman returns a 500 while trying to create a new monitor configuration with a new user. I've added a new user to my team granted admin and developer roles and deleted the old user, all my monitors have been deleted and now I am not able to create a new test monitor 

**To Reproduce**
1. Go to 'manage roles'
2. Remove the current user
3. Add a new user and set the roles Developer and Admin
4. Go to team workspace > Monitor
5. Create a new monitor configuration

**Expected behavior**
The test monitors that were in place should not be deleted and the new user should be able to create a new monitor configuration.

**App information (please complete the following information):**
 - Postman Version 7.25.0 
 - OS: macOS Catalina 10.15.4

**Additional context**
I am trying to create the monitor using pre-existent collections and environments that belongs to the old user but was shared in the team workspace.

**Comment by Hayk-S** [comment] 2021-02-03 14:54
@thiagobxc  the issue is not reproducible for me, could you please confirm if this still exists or it is already resolved ?

**Comment by Hayk-S** [comment] 2021-02-05 00:31
Closing issue as it is not reproducible.

**Closed as completed by Hayk-S** 2021-02-05 00:31 UTC
Labels: bug, product/automation-testing
