### ISSUE TITLE
How can I pass specific version of TLS in my API calls through postman

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#2536] opened 2016-12-08 21:58 UTC
1. Postman Version: v4.9.1
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: always
 6. Expected behaviour: Be able to pass tls version with my api calls

**Comment by karolinanm** [comment] 2018-09-21 10:09
Hi, postman is a great tool but I currently can't use it without TLS support (sslv3 handshake failure)...do you have any idea, when you could implement this feature?

**Comment by saswatds** [comment] 2019-06-18 07:21
Duplicate of #5918

**Closed as completed by saswatds** 2019-06-18 07:21 UTC
Labels: feature, Certificate, product/runtime
