### ISSUE TITLE
Order collections and folders inside collection alphabetically

### ISSUE THREAD

**Issue by scascalesageinfoes** [a85/POSTMan-Chrome-Extension#10088] opened 2021-07-01 13:48 UTC
Hello
Any plans to automatic order collections alphabetically?
And another action button/option/menu to automatic order folders alphabetically inside a collection?
Thx

**Comment by appurva21** [comment] 2021-07-05 05:41
Duplicate of [#7341 ](https://github.com/postmanlabs/postman-app-support/issues/7341)

**Closed as completed by appurva21** 2021-07-05 05:41 UTC
Labels: duplicate
