### ISSUE TITLE
gRPC request tab crashes when trying to paste Bearer token the second time

### ISSUE THREAD

**Issue by hveiga** [a85/POSTMan-Chrome-Extension#10870] opened 2022-04-29 14:19 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When sending requests using the new grpc requests I normally need to paste a bearer token multiple times as those expire over time. First time it always works, however when I double click on the value to paste the new value, the tab crashes and gives me the `Something Went Wrong. Postman has encountered an error.`.

### Steps To Reproduce

1. Open a new gRPC Request
2. Go to Authorization tab, select type `Bearer Token`
3. Paste a value in `Token` field.
4. Go to Message tab, form your message. Invoke a request.
5. Go back to Authorization tab, double click to select the whole text in `Token` field to paste the new value.
6. Tab crashes.

### Operating System

macOS

### Postman Version

9.16.1

### Postman Platform

Postman App

**Comment by appurva21** [comment] 2022-04-29 14:46
Hey @hveiga!

Thanks for writing in and sorry that you are facing the issue. Could you please share:
1.  A screen recording of the above issue to help us reproduce it (I tried the above-mentioned steps, but couldn't reproduce it on our end)
2. Logs from `View -> Developer -> View Logs In Finder` to [help@postman.com](mailto:help@postman.com)?

**Comment by steverawlins-zebra** [comment] 2022-06-27 16:08
I am attempting to use gRPC requests and having problems.  Postman tells me it has "encountered an error" - but, please, what it is?  Tell me more.

https://user-images.githubusercontent.com/52328771/175985742-f8d48acb-5b63-4b8b-8b34-71b334b24599.mov

**Comment by steverawlins-zebra** [comment] 2022-06-27 16:09
Here are the Postman logs
[PostmanProblemLogs20220627.zip](https://github.com/postmanlabs/postman-app-support/files/8993606/PostmanProblemLogs20220627.zip)

**Comment by codenirvana** [comment] 2022-06-28 10:46
@steverawlins-zebra I am not able to reproduce this issue locally, can you try updating your app to the latest version and check if the issue persists?

**Comment by codenirvana** [comment] 2022-07-30 18:30
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2022-07-30 18:30 UTC
Labels: bug, need-more-info, protocol/grpc, product/api-client
