### ISSUE TITLE
The postman icon doesn't show on the windows taskbar. (Windows 10)

### ISSUE THREAD

**Issue by asmp3** [a85/POSTMan-Chrome-Extension#3107] opened 2017-06-02 12:18 UTC
1. Postman Version: 4.11.0
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: After the update.
 6. Expected behaviour: Postman icon should show on the windows taskbar.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by kamalaknn** [comment] 2017-06-02 12:26
@asmp3 Thanks for reporting this. We will look into this and update the thread.

**Comment by kamalaknn** [comment] 2017-06-08 06:52
Hey @asmp3,

I looked into this and traced it to the fix we made recently for #2816. 

It looks like after the update the older shortcut was still left in `c:\Users\<your username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc`. 

Unfortunately there is no way for us to detect and remove the shortcut there, which is used by Windows. That is why you are seeing the missing icon.

Deleting the shortcut in `GitHub, Inc` folder(`right click on Postman in Start Menu -> Open file location` for folder location) should fix this. 

Can you confirm this?

**Comment by asmp3** [comment] 2017-06-08 14:45
Hey @kamalaknn,

Yes deleting the shortcut in the Github, Inc folder has solved the issue.
Thank You!

**Comment by kamalaknn** [comment] 2017-06-08 14:59
@asmp3 Great! That's good to hear.

I am closing this issue then.

For anyone stumbling on this in future, 

1. Right click on `Postman` in Start menu and select `Open file location`. 
2. If the shortcut is inside `GitHub, Inc` folder
3. Make sure there is one shortcut inside `c:\Users\<your username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Postman`
4. Delete the shortcut in `c:\Users\<your username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc`

This should bring the icon back. Also any fresh installs should work cleanly.

**Closed as completed by kamalaknn** 2017-06-08 14:59 UTC

**Comment by Werror** [comment] 2017-08-17 15:42
Thanks for this post @kamalaknn!

**Comment by orryrotem-buildinglink** [comment] 2017-11-07 18:49
This fix applies to the Postman icon in the Start menu as well

**Comment by jaiswalDilip** [comment] 2018-07-19 11:43
I'm using windows 2016. Shortcut file directs me to this location C:\Users\Administrator\AppData\Local\Postman\Update.exe
I dont have _Github, Inc_ folder. Any help is appreciated.

**Comment by fayt81** [comment] 2018-07-20 11:01
I have no Github, Inc folder, but the icon is not displayed. Shortcut on desktop points to Update.exe as written by jaiswalDilip, and start menu shortcut points to c:\Users\<your username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Postman.
Thanks in advance for any advice.

**Comment by nsossonko** [comment] 2018-07-25 15:11
The original shortcut in the Postman folder may need updating as well. To do so, do the following:
1. Right-click on the shortcut and click "Properties"
2. Click "Change Icon..."
3. Click "Browse..." and go to "%LOCALAPPDATA%\Postman\"
4. Select "Update.exe"
5. The icon will now show, select it and click "OK"
6. If necessary, change the "Start in:" folder to "%LOCALAPPDATA%\Postman\"
7. Click "OK"

Note: %LOCALAPPDATA% refers to your local app data folder. Usually is is in "C:\Users\<username>\AppData\Local\".

**Comment by fayt81** [comment] 2018-07-26 07:00
Thank you, @nsossonko! This solved the issue!

**Comment by bogdandevlpr** [comment] 2018-08-08 09:00
For me it worked after I pinned and unpinned the icon in the taskbar

**Comment by DatChoob** [comment] 2018-08-15 18:47
@nsossonko  Perfect! worked for me

**Comment by chrisadipascual** [comment] 2019-07-12 06:33
Still happens in 2019, v7.3.2

**Comment by 95rajasekar** [comment] 2019-07-20 09:33
> For me it worked after I pinned and unpinned the icon in the taskbar
It worked for me following this

**Comment by kyouzzz** [comment] 2019-08-05 02:57
Right click the icon in task bar.
Right click program name "Postman".
Left click "property" and modify the icon

**Comment by richie86** [comment] 2019-08-07 04:50
I realize the problem is the shortcut created in windows, was referring to 
C:\Users\<username>\AppData\Local\Postman\app-<version> folder, in the event that we update the postman to a different version, the app shortcut no longer works. the "Start In" for the short cut point to C:\Users\<username>\AppData\Local\Postman\app-<version> folder as well, which caused the shortcut no longer valid as well.

**Comment by bugoutfr** [comment] 2019-08-24 10:41
I have the same issue here, and the icon is also wrong when the application is running and not pinned to the taskbar. This seems like a recurrent bug, not something that should be fixed manually with the aforementioned workarounds.

**Comment by ravishankarkota2017** [comment] 2019-09-05 15:34
> The original shortcut in the Postman folder may need updating as well. To do so, do the following:
> 
> 1. Right-click on the shortcut and click "Properties"
> 2. Click "Change Icon..."
> 3. Click "Browse..." and go to "%LOCALAPPDATA%\Postman"
> 4. Select "Update.exe"
> 5. The icon will now show, select it and click "OK"
> 6. If necessary, change the "Start in:" folder to "%LOCALAPPDATA%\Postman"
> 7. Click "OK"
> 
> Note: %LOCALAPPDATA% refers to your local app data folder. Usually is is in "C:\Users<username>\AppData\Local".

This worked for me and solved the issue, Time saver, Thanks a ton to  nsossonko.
Working Link : https://github.com/postmanlabs/postman-app-support/issues/3107#issuecomment-407789469

**Comment by tony-shannon** [comment] 2019-09-15 11:12
I fiddled with those instructions , needing tidy up the Postman properties: Target  & Start In references ...
![image](https://user-images.githubusercontent.com/939996/64920639-edc7fa80-d7b1-11e9-971f-fd46b6b90bbb.png)
... plus also add a new ICO file to the postman folder as well 
For those who need a postman ICO file I've zipped  down the one I added myself 
[postmanIcofile_zipped.zip](https://github.com/postmanlabs/postman-app-support/files/3613672/postmanIcofile_zipped.zip)

Shortcut appearance ok again working as needed now
