### ISSUE TITLE
Not able to Import Test Run throwing error "Could not import test run. Please check the format of the file."

### ISSUE THREAD

**Issue by amnoman** [a85/POSTMan-Chrome-Extension#3574] opened 2017-09-28 19:52 UTC
```
Postman for Windows
Version 5.2.1
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always been there
 2. Expected behaviour: Should able to import the test run which exported before.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Steps: 
1. Import the collection and environment
2. Run it from the runner
3. Click on Exports Results and save it
4. Click on New button
5. Delete the Recent Runs Practice before Import Test Run to avoid "The run you are trying to import already exists." error
![image](https://user-images.githubusercontent.com/28634757/30987228-e1ab285c-a45b-11e7-9507-171f05deee36.png)

6. Import Test Run which exported and saved before
7. check the pop up : 
![image](https://user-images.githubusercontent.com/28634757/30987278-06ec6310-a45c-11e7-80ac-5b0fd8ecb3eb.png)

"Could not import test run. Please check the format of the file."

[Could not import test run.zip](https://github.com/postmanlabs/postman-app-support/files/1342139/Could.not.import.test.run.zip)

**Comment by sivcan** [comment] 2018-03-20 13:31
Hi @amnoman - This has been fixed in the [latest version](https://www.getpostman.com/apps) - v6.0.10 of the native app.
Kindly update to the same.
Closing this.

**Comment by ChrisYarland-Price** [comment] 2018-03-22 09:04
This is not Fixed we are still encountering this problem.

**Comment by sivcan** [comment] 2018-03-22 09:21
@ChrisYarland-Price - You'll have to export the run from the updated version (6.0.10) and then try importing it.

Let me know if it works for you. :)

**Comment by sivcan** [comment] 2018-03-22 09:42
Sorry for the inconvenience caused because of this bug.

I have fixed your exported test run file.
You can diff check it and fix your old runs if you manually want to.

https://pastebin.com/wjanuurw

**Comment by ChrisYarland-Price** [comment] 2018-03-22 11:07
I have just tried this this morning from the newest version and it is definitely not working for me.

**Comment by sivcan** [comment] 2018-03-22 12:48
@ChrisYarland-Price - Can you share the exported test run with us through [mail](mailto:help@getpostman.com)
Feel free to redact any sensitive information by manually editing the file. 

Thanks

**Comment by sivcan** [comment] 2018-03-27 04:55
@ChrisYarland-Price - I saw that the export is still having a bug. 
Though I have been unable to reproduce it on the latest 6.0.10 version of the app.
But since you're definite that you've exported it using the latest app so I'll dig more into this.
I will update this thread once a fixed patch is released. 

Reopening this until a fix is released and confirmed that the bug no longer exists.

**Comment by ChrisYarland-Price** [comment] 2018-03-28 08:13
Thanks

**Comment by zhulingbiezhi** [comment] 2018-04-13 04:13
I also found that this problem cannot be imported into the test. Can you fix it on native app. Guys. Even the use of official examples does not useful.

**Comment by bokivaol** [comment] 2018-05-08 11:33
I also have a problem with this. My Postman v6.0.10.
I exported results with Postman v6.0.10 and imported it in Postman v6.0.10.

**Comment by sivcan** [comment] 2018-05-08 12:45
@bokivaol Can you share your collection that you're using in the collection runner with us on help@getpostman.com ? 

Feel free to redact any sensitive information.

**Comment by bokivaol** [comment] 2018-05-08 13:24
@sivcan What should I share collection or exported results of the collection?

**Comment by sivcan** [comment] 2018-05-09 10:39
@bokivaol Export the collection and share that, please. 
Not the exported run.

**Comment by dcsava** [comment] 2018-05-21 00:09
I can add that this is still an issue.  Postman v6.1.2 on Windows. I am reviewing the docs and got to the section describing this function I ran a simple request, exported the test run, deleted the history of the run and tried to import the just exported data and received the error described in this thread. 
By basic test I mean: New collection, new GET request

`https://postman-echo.com/get?foo1=bar1&foo2=bar2`

1 TEST:
```
pm.test("Status code is 200", function () {
    pm.response.to.have.status(200);
});
```
Thanks.

**Comment by ursandy72** [comment] 2018-06-19 14:30
I am also facing same issue. This issue is still there on postman v6.1.3

**Comment by andrew-maczero** [comment] 2018-09-24 23:54
This problem is still active on v6.3.0

**Comment by GregoryPellegrin** [comment] 2018-10-25 16:03
This problem is still active on 6.4.4

**Comment by Ocsidot** [comment] 2018-11-07 10:05
I confirm that this issue is still active. Could you please fix this?

Regards

**Comment by bickelk** [comment] 2018-12-07 21:55
I'm seeing this same problem in v6.5.3.

**Comment by andrew-smith-nz** [comment] 2018-12-13 20:28
Still occurring on v6.6.1.

**Comment by arun-chandran-c** [comment] 2018-12-31 13:21
Still got error "Could not import test run. Please check the format of the file." with v6.6.1. Does this issue got resolved ? any work around available.

**Comment by BrambleRamble** [comment] 2019-01-15 11:08
I can still reproduce this in v6.7.1.

**Comment by vpetrovic-cw** [comment] 2019-01-16 23:20
Me too. Postman 6.7.1, Ubuntu Linux 16.04.

**Comment by cruinh** [comment] 2019-01-22 15:13
I've also been seeing this repeatedly since I started using the Runner a few weeks ago.  I have yet to ever successfully import a test...

**Comment by vpetrovic-cw** [comment] 2019-02-05 00:46
There is an error in exported test results JSON. 
For example, in one of the requests I have 3 pm.test() functions in JS: 
- "Status code is 200"
- "Content-Type is present and of text/xml"
- "Version is: R3_1_136"

Also, as an example, let us mark this request as "0"; then, in **results.0.tests**, instead of
```
"tests": {
   "Status code is 200": true,
   "Content-Type is present and of text/xml": true,
   "Version is: R3_1_136": true
},
```
this is how it looks:
```
"tests": {
   "error": null,
   "name": "Status code is 200",
   "status": "pass",
   "Content-Type is present and of text/xml": true,
   "Version is: R3_1_136": true
},
```
which is incorrect. 
When I correct this manually, the import of test results back to Collection Runner works.

**Comment by GregoryPellegrin** [comment] 2019-02-05 19:06
hello vpetrovic-cw,
How did you correct the json manually ? what did you change ?

**Comment by GregoryPellegrin** [comment] 2019-02-05 19:10
ok guys, for all requests you have to change this 

"tests": {
	"error": null,
	"name": "test name",
	"status": "pass",
	"test name 1": true,
	"test name 2": true
},

for this

"tests": {
	"test name 1": true,
	"test name 2": true
},

and you will able to import your tests result into postman collection runner
you have to remove every "error", "name" and "status" tags into "tests"

I tried every possibility, just remove "error", just remove "error" and "name", etc... and the only way to import the tests results its by removing all 3 tags

**Comment by GregoryPellegrin** [comment] 2019-02-05 19:17
can someone post a regex for removing all of thoses tags and value easilly with notepad ?

**Comment by numaanashraf** [comment] 2019-04-01 06:59
We've rolled out a fix for this issue in Postman v7.0. Please update and let us know if you are still facing this issue.

**Closed as completed by numaanashraf** 2019-04-01 06:59 UTC
Labels: bug, collection-runner, regression

**Comment by nikhitakale** [comment] 2019-05-31 08:08
@numaanashraf Issues still re-producing in Postman v7.0.please refer the screenshot
![Screenshot from 2019-05-31 13-37-58](https://user-images.githubusercontent.com/11737260/58691305-2f6e9a00-83a9-11e9-855d-a07314316c7d.png)

**Comment by fjbranco** [comment] 2019-06-26 19:42
This problem is still active on 7.2.2
