### ISSUE TITLE
Request using pm.request.headers.add are no longer displayed in Monitor Test Results

### ISSUE THREAD

**Issue by eborey** [a85/POSTMan-Chrome-Extension#8559] opened 2020-05-28 16:06 UTC
**Describe the bug**
When a custom header is added to a request by using "pm.request.headers.add", the related monitor result panel (Test Result or Console Log) will no longer show that request, despite the request has been successfully run (or not). Everything is fine with "Run Collection".

**To Reproduce**
1. Create en new collection
2. Add a GET request to URL "https://postman-echo.com/get"
3. Add the following code to Pre-request Script
```
pm.request.headers.add({
    key: 'MyCustomHeaderName', 
    value: 'MyCustomHeaderValue' });
```
4. Run the request to check execution
5. Create a monitor for the collection
6. Run that monitor
7. Once finished, Click on "Test Results"
8. You will see "This run finished without results"
9. Click on "Console Log"
8. The request will not be displayed

**Expected behavior**
Test Results and Console Log must show all requests run. It used to work some weeks ago.

**App information (please complete the following information):**
 - App Type Chrome, Safari, Native App
 - Postman Version [e.g. 7.25.0]
 - OS: macOSCatalina 10.15.4

**Comment by cyrielle-hada** [comment] 2020-06-19 12:37
@eborey Thanks for flagging this! We were able to replicate the issue.

It seems like the request sequence occurs in a way that does not create logs in the expected sequence to populate test results. 

We're actively working on a solution and hope to have a fix in place soon, and we'll update you here once we have.

**Comment by cyrielle-hada** [comment] 2020-07-22 13:52
A fix has been deployed to production today. After testing, I confirm that the issue is resolved.

**Closed as completed by cyrielle-hada** 2020-07-22 13:52 UTC
Labels: bug, support, product/automation-testing

**Comment by sajitharnair** [comment] 2022-09-26 20:38
Dear All,
I am new to postman to K6 tool and while running the performance load testing I am getting the below error.
ERRO[0002] Error: pm.request.headers not supported

1. I have exported my collection from the postman.
2. I have exported the environments from postman.
3. Running the below command in powershell to generate the k6 script for the performance Load testing.
  postman-to-k6 collection.json -e environment.json -o k6-script.js
4. I ran the "k6 run k6-script.js" command to run the performance load testing.

At this stage I receive this error.

My collection is having these parameters in the json file. Please find as below.

"event": [
				{
					"listen": "prerequest",
					"script": {
						"type": "text/javascript",
						"exec": [
							"pm.request.headers.add({key: 'Content-Type', value: \"application/json\"});",
							"pm.request.headers.add({key: 'itsapp-so', value: \"{{header__itsapp-so}}\" });",
							"pm.request.headers.add({key: 'itsapp-lang', value: \"{{header__ITSAPP_LANG}}\" });",
							"pm.request.headers.add({key: 'itsapp-ver', value: \"{{header__itsapp-ver}}\" });",
							"pm.request.headers.add({key: 'itsapp-deviceid', value: \"{{header__itsapp-deviceid}}\" });",
							"pm.request.headers.add({key: 'itsapp-device', value: \"{{header__itsapp-device}}\" });"
						]
					}
				},

And my K6 script also has the method as below.

export default function() {
  group("Product *", function() {
    postman[Pre].push(() => {
      pm.request.headers.add({
        key: "Content-Type",
        value: "application/json"
      });
      pm.request.headers.add({
        key: "itsapp-so",
        value: "{{header__itsapp-so}}"
      });
      pm.request.headers.add({
        key: "itsapp-lang",
        value: "{{header__ITSAPP_LANG}}"
      });
      pm.request.headers.add({
        key: "itsapp-ver",
        value: "{{header__itsapp-ver}}"
      });
      pm.request.headers.add({
        key: "itsapp-deviceid",
        value: "{{header__itsapp-deviceid}}"
      });
      pm.request.headers.add({
        key: "itsapp-device",
        value: "{{header__itsapp-device}}"
      });
    });

I am not understanding what went wrong?

Any kind of help would be appreaciated.

Thanks in advance,
Sajitha
