### ISSUE TITLE
Not all request headers being sent

### ISSUE THREAD

**Issue by emssw** [a85/POSTMan-Chrome-Extension#6566] opened 2019-05-21 14:33 UTC
**Describe the bug**
Not all requested headers are being sent in the http request when clicking on SEND button

**To Reproduce**
1. Go to a request tab in the UI and create a request with multiple headers
2. Open the Postman console
3. Click the send button
4. Review the request in Postman console, compare headers

**Expected behavior**
All request headers be sent by Postman as requested by the user
**Screenshots**

![postman_headers_1](https://user-images.githubusercontent.com/31017043/58104681-2a446a80-7bb3-11e9-99bd-69ef6951ac28.png)

![postman_headers_2](https://user-images.githubusercontent.com/31017043/58104690-2f091e80-7bb3-11e9-941d-b5cf8a09f194.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]  Native
 - Postman Version [e.g. 7.0.0]  7.1.1
 - OS: [e.g. macOS High Sierra 10.13.2] Win 10

**Additional context**

**Comment by codenirvana** [comment] 2019-05-29 06:51
@emssw That's weird, can you try changing the request URL to `https://postman-echo.com/post` and check if all the headers are present in response's `headers` object?

I can only think of two scenarios which can lead to this issue:
1. The console is not showing request headers correctly.
> Confirm with the echo URL or server logs to check actual headers sent.

2. Usage of `pm.request.headers.*` API to mutate the request headers in pre-request scripts.
> Check folder and collection level pre-request script if that's the case.

**Comment by emssw** [comment] 2019-05-30 15:01
Can not find any pre-request Scripts, collection/folder/request. I have discovered that this does not occur when creating a new request and placing it into a new collection. This only occurs when importing older collections. The collections are approximately 2 years old. I have not found a way to move a request from one collection to another. Any suggestions?

**Comment by codenirvana** [comment] 2019-05-30 15:40
@emssw You can drag and drop requests from one collection to another.
But, importing an older collection should not have affected this.

**Comment by codenirvana** [comment] 2019-06-13 11:49
@emssw Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.
Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2019-06-13 11:49 UTC
Labels: bug, product/runtime
