### ISSUE TITLE
Signing in || Accepting invitations throws 500

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#7077] opened 2019-08-07 20:15 UTC
**Describe the bug**
Users that created their Postman accounts _prior_ to their organization moving to enterprise, and enabling SSO, are seeing a `500 Something went wrong` error when signing in to their account and/or accepting an invitation to join the team.

**To Reproduce**
1. Generate an invitation on an enterprise team w/ SSO 
2. Disable Google Auth as an authentication method
3. Invite a user that already has an account
4. See 500 error when they attempt to sign in

**Expected behavior**
Joining the team should work – if there are any errors, a more descriptive error message should populate.

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/62654728-10026900-b926-11e9-84f6-c0a20b0db130.png)
![image](https://user-images.githubusercontent.com/4734306/62654735-1264c300-b926-11e9-9aec-ced19fffa067.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version" 7.2+
 - OS: OSX & Windows 10

**Additional context**
[Filed by Postman]
Internal notes on specific teams provided

**Comment by anudeepmedicharla** [comment] 2019-08-08 06:52
Is Postman sign in disabled for this team? Is that the reason we're seeing an error?

**Comment by gdbhowmick** [comment] 2019-08-11 12:56
Is this error still reproducible?

**Comment by elssar** [comment] 2019-08-13 06:40
@chrisdeso is this still happening or was this a transient error? We haven't been able to reproduce it.

**Comment by chrisdeso** [comment] 2019-08-20 19:16
Checking on this @elssar

**Comment by elssar** [comment] 2019-10-09 09:10
Closing the ticket since we haven't been able to reproduce.

**Closed as completed by elssar** 2019-10-09 09:10 UTC
Labels: bug, product/login
