### ISSUE TITLE
Same POST request works in 7.0.9, but not 7.1.1

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6743] opened 2019-06-18 18:07 UTC
**[Reported by Postman Support, on behalf of original user]**

**Describe the bug**
When user sends the same POST request to upload an image, the requests succeeds in v7.0.9 of the native app, but returns an error message in v7.1.1.

Error message is as follows:
<img width="1200" alt="Screen Shot 2019-06-18 at 10 59 56 AM" src="https://user-images.githubusercontent.com/43283131/59707824-49391b00-91b8-11e9-82e4-4ebfeb8621e9.png">

Headers appear to be set correctly:
<img width="636" alt="Screen Shot 2019-06-18 at 11 07 40 AM" src="https://user-images.githubusercontent.com/43283131/59708304-56a2d500-91b9-11e9-9c9d-b63b04e1809e.png">

There is only one error in the network logs, which may or may not be relevant:
<img width="859" alt="59708328-64585a80-91b9-11e9-968b-35420e5d8e09" src="https://user-images.githubusercontent.com/43283131/60124419-6f256900-973e-11e9-8962-898d76b6aa30.png">

**To Reproduce**
Steps to reproduce the behavior (not reproduced outside of user's request):
1. Send request in v7.0.9 --- succeeds
2. Send same request in v7.1.1 --- error message

**Expected behavior**
Request is sent successfully

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: v7.1.1
 - OS: Windows

**Additional context**
See internal notes

**Comment by shamasis** [comment] 2020-03-10 14:57
@JP-from-Postman ... i know it has been a while, but can you help reproduce this? We have scratched our heads for a while around this. But now we either close this as not reproducible or do something soon. :-)

**Comment by codenirvana** [comment] 2020-05-29 20:27
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-05-29 20:27 UTC
Labels: bug, product/runtime, blocked/need-repro
