### ISSUE TITLE
Input from user

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#10611] opened 2022-01-27 14:28 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Is there any possibility to have a prompt for a value from an user? Imagine I have MFA in my authorization endpoint which needs to be enabled for the user for the methods I like to test, there is no way I can write a test for it then when there is no possiblity to ask for the OTP response from authenticator.

### Describe the solution you'd like

Using something like `myVar = prompt("OTP response:")` will assign entered value to `myVar` variable.

**Comment by DannyDainton** [comment] 2022-01-27 14:32
Closing as this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/285

**Closed as completed by DannyDainton** 2022-01-27 14:32 UTC
Labels: feature, duplicate
