### ISSUE TITLE
Remove search params from a request's URL (Docs)

### ISSUE THREAD

**Issue by phcoliveira** [a85/POSTMan-Chrome-Extension#5782] opened 2019-01-16 12:44 UTC
Hello there.

It makes sense to display the search params on a request's URL, while using Postman, because it makes clearer what the request will be.

But, in my opinion, it does not make any sense in displaying all of them in the documentation. If disabled, they still appear grayed out on private view, but not on the published website.

It is enough to have a table of path and search params right bellow the URL. It is very weird to see them all concatenated. For example, I have to have many endpoints for searching the same resource because some of the search parameters are mutually exclusive.

Presenting how the URL would look with a given search param can be done much more effectively on the saved examples. I could have many examples saved under only one endpoint, but, instead, I ended up having many endpoints with only one example bacause the search params would be all cluttered in the request's URL.

Also, I believe the documentation's responsibility is to describe how the API can be used, not how it was used. Therefore, please also remove the value from the params table. It seems to always be useless since it points to environment variables which should not be interpolated on a released publication.

>  Completely agree.This is a blocker for me currently as I want to show optional parameters in the documentation without having to 'check' the parameter which forces it into the URL.
-- @timkeeler

https://github.com/postmanlabs/postman-docs/issues/1470

**Comment by numaanashraf** [comment] 2019-01-16 15:25
Duplicate of #5784

**Closed as completed by numaanashraf** 2019-01-16 15:25 UTC
Labels: duplicate
