### ISSUE TITLE
New window should respect the current screen

### ISSUE THREAD

**Issue by deepakpathania-zz** [a85/POSTMan-Chrome-Extension#5327] opened 2018-10-09 05:34 UTC
Opening a new window of the app, say by switching account, does not open it in the same screen in which the current window is. The new window opens in the primary screen, which I have to then drag to the intended screen.

Ideally, I would like it to open in the same screen from which the intent to open the new window came.

**Comment by sivcan** [comment] 2018-10-09 05:51
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/5101

**Closed as completed by sivcan** 2018-10-09 05:51 UTC
