### ISSUE TITLE
In tab "Headers" border between DESCRIPTION and VALUE don't attached.

### ISSUE THREAD

**Issue by Pavezlo** [a85/POSTMan-Chrome-Extension#8969] opened 2020-08-25 05:26 UTC
**Describe the bug**
In tab "Headers" border between DESCRIPTION and VALUE don't attached.

**To Reproduce**
1. Create new GET;
2. Click on 'Headers'
3. Click border between Value and DESCRIPTION at the header level.
4. Slide border in the right.
5. Border main table don't move.

**Expected behavior**
I expected to see functionality like in other tabs.

**App information (please complete the following information):**
 - Native App
 - Postman Version v7.31.0
 - OS: Xiaomi Mi Notebook Pro 15,Windows 10, version 1903

![Postman 2020-08-25 08-04-23 (1)](https://user-images.githubusercontent.com/44898892/91125801-446cd280-e6ab-11ea-8b24-4a8e91085524.gif)

**Comment by DannyDainton** [comment] 2020-08-25 05:33
Duplicate of #8918

**Closed as completed** 2020-08-25 05:33 UTC
Labels: duplicate
