### ISSUE TITLE
Postman standalone app mac generates empty x-www-form-urlencoded fields values 

### ISSUE THREAD

**Issue by choosen** [a85/POSTMan-Chrome-Extension#4416] opened 2018-04-04 11:09 UTC
## App Details:
```
Postman standalone Mac
Version 6.0.10 (6.0.10)
macOS High Sierra 10.13.4
```

## Issue Report:
 1. Issue encountered recently, I did not see it before
 2. Expected behaviour:
  send fields with inputted values
 3. Console logs 
```
requester.js:299530 Initializing the global config
requester.js:362219 Initializing settings
requester.js:299814 Booting waterline models
requester.js:299880 Object "Successful ORM initialization"
requester.js:370427  ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs.
================================================================
requester.js:41967 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41967
requester.js:560528 Check that entitites shown here should only be personal entites
componentWillMount @ requester.js:560528
requester.js:41967 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41967
requester.js:41967 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41967
requester.js:41967 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41967
requester.js:363160 Uncaught TypeError: Cannot read property 'ownerDocument' of null
    at getScrollPosition (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:400512:66)
    at DraftEditor._focus (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:501789:34)
    at PluginEditor._this.(anonymous function) [as focus] (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:508477:56)
    at AutoSuggestInput.handleFocus (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:123599:46)
    at Object.invokeGuardedCallback (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:112537:5)
    at executeDispatch (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:112365:21)
    at Object.executeDispatchesInOrder (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:112385:7)
    at executeDispatchesAndRelease (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:79628:22)
    at executeDispatchesAndReleaseTopLevel (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:79639:10)
    at Array.forEach (native)
    at forEachAccumulated (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:133576:9)
    at Object.processEventQueue (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:79842:7)
    at runEventQueueInBatch (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:207775:18)
    at Object.handleTopLevel [as _handleTopLevel] (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:207786:5)
    at handleTopLevelImpl (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:210960:24)
    at Object.batchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:210875:14)
    at Object.batchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:43195:27)
    at dispatchEvent (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:211035:20)
    at HTMLDocument.wrapped (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:363156:29)
    at addPointToSelection (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:504411:13)
    at setDraftEditorSelection (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:504343:5)
    at DraftEditorLeaf._setSelection (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:502447:5)
    at DraftEditorLeaf.componentDidMount (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:502459:10)
    at CallbackQueue.notifyAll (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:133702:22)
    at ReactReconcileTransaction.close (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:211209:26)
    at ReactReconcileTransaction.closeAll (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:102067:25)
    at ReactReconcileTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:102014:16)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:102001:20)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:43187:32)
    at Object.flushBatchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:43270:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:102067:25)
    at ReactDefaultBatchingStrategyTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:102014:16)
    at Object.batchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:210877:26)
    at Object.enqueueUpdate (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:43298:22)
    at enqueueUpdate (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:113435:16)
    at Object.enqueueSetState (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:113620:5)
    at DraftEditor.ReactComponent.setState (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:111859:16)
    at DraftEditor._restoreEditorDOM (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:501845:10)
    at file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:505756:12
    at wrapped (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:363156:29)
requester.js:41967 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41967
mode-auto.js Failed to load resource: net::ERR_FILE_NOT_FOUND
mode-go.js Failed to load resource: net::ERR_FILE_NOT_FOUND
requester.js:541082 @todo Select in the sidebar
(anonymous) @ requester.js:541082
```
 4. Screenshots (if applicable)
cURL:
![obraz](https://user-images.githubusercontent.com/11080848/38303929-dd41d668-3807-11e8-99cd-bf547f95e778.png)
After switching to HTTP:
![obraz](https://user-images.githubusercontent.com/11080848/38304361-62be5f22-3809-11e8-9829-3cf8ddc4e5f7.png)
Defined fields:
![obraz](https://user-images.githubusercontent.com/11080848/38304114-8e494630-3808-11e8-810a-a2f96c2fe304.png)

* _Maybe I enabled/disabled first field to check if some error will occur in console_

To reproduce?
I opened new tab, did the same activities and works fine.
I saved old buggy-one tab, closed app, load it again - error occurs (so I can reproduce it on my machine)

**Comment by harryi3t** [comment] 2018-04-05 11:57
@choosen So the issue is not reproducible for newly opened tabs? Also, what happens if you close and re-open the same tab?

**Comment by choosen** [comment] 2018-04-05 15:03
@harryi3t This occurred once - I have this request (tab) saved. 
If I close all tabs, restart Postman and load this tab: the error occur again. 
I will create a vid

**Comment by choosen** [comment] 2018-04-05 15:06
@harryi3t If I change the content in Bulk Edit it starts to work.
http://recordit.co/u0vEb2FfKv

**Comment by numaanashraf** [comment] 2019-03-28 03:43
Thank you for your issue! With only the details that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you are still facing this issue.

**Closed as completed by numaanashraf** 2019-03-28 03:43 UTC
Labels: bug, code-generator
