### ISSUE TITLE
Authorization headers doesn't appear in the generated doc

### ISSUE THREAD

**Issue by remi-blaise** [a85/POSTMan-Chrome-Extension#7869] opened 2020-01-03 15:05 UTC
Good afternoon!

**Is your feature request related to a problem? Please describe.**
Like [this user](https://stackoverflow.com/questions/50940489/postman-collection-authorization-not-present-in-documentation-headers) on Stackoverflow, I have been surprised to see that Bearer token set in the Authorization tab doesn't appear in the doc. I am then forced not to use the tab and to manually repeat the token in the header tab of every HTTP request.

**Describe the solution you'd like**
I would like it to appear as an HTTP header.

**Describe alternatives you've considered**
I don't see alternatives, this is clearly the way to go for me.

**Additional context**
![image](https://user-images.githubusercontent.com/9931240/71730423-61b20f80-2e42-11ea-8697-1a9831a90f85.png)
Generate a little lock icon (but no HTTP header)

Thank you for your amazing work,

An (almost) happy user!

**Comment by Raja-Simha** [comment] 2020-02-06 19:04
Duplicate of #4244

**Closed as completed by Raja-Simha** 2020-02-06 19:04 UTC
Labels: feature, product/documentation
