### ISSUE TITLE
Error: Parse Error: Invalid header value char

### ISSUE THREAD

**Issue by bleghrib-CLGX** [a85/POSTMan-Chrome-Extension#11085] opened 2022-07-14 10:56 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

start happening after getting the last update of postman 9.24.2

### Steps To Reproduce

Create a post request and execute it, it happens for some requests only

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/59644486/178966676-5585f3d2-64dd-4830-a9c6-829efe7187b9.png)

### Operating System

Windows

### Postman Version

9.24.2

### Postman Platform

Postman App

**Comment by DannyDainton** [comment] 2022-07-18 08:51
Hey @bleghrib-CLGX 

We're going to be unable to create this issue on our side, given the information that you have provided. 

Can you update the issue and provide a repeatable set of steps, please? Without that, it's going to be difficult to see this happening.

The issue seems to relate to a header that's been provided for that specific request, do you have a copy or screenshot of these? If this was manually entered, ensure that there were not any extra characters placed into the fields.

**Comment by DannyDainton** [comment] 2022-07-21 09:38
Hey @bleghrib-CLGX 

I will close this issue for now as we don't have the required contextual information to reproduce this problem.

If you can provide a clear set of steps to reliably recreate this error, we can look at reopening this again.

**Closed as completed by DannyDainton** 2022-07-21 09:38 UTC
Labels: need-more-info, request-sending, product/runtime

**Comment by ferba24** [comment] 2022-11-08 02:36
I'm experiencing this issue as well so I'm willing to provide all the details you need @DannyDainton

**Comment by ferba24** [comment] 2022-11-12 00:32
@DannyDainton I'm experiencing the same issue as well. Several users too (https://github.com/postmanlabs/postman-app-support/issues/8747)

![image](https://user-images.githubusercontent.com/48895700/201447544-afe69524-4650-4671-9f3b-5c9af593531d.png)

The issue was gone (in fact, I removed the post I made here because the issue was gone but today it happened again).
I haven't been able to find out a way to reproduce this because it just came from nowhere (I haven't changed any settings). If you have any suggestions to troubleshoot this I'm willing to help you.

**Comment by ivanparramartinez** [comment] 2022-11-16 00:07
This is an issue that happens all the time with the desktop app (I use the Mac app)... If I use Postman on the web browser it doesn't happens. Why can be that?
![Captura de pantalla 2022-11-15 a la(s) 7 04 57 p  m](https://user-images.githubusercontent.com/16830391/202050988-74a7e10d-12ef-4e0e-a6d9-63b0b31660fb.png)
