### ISSUE TITLE
Importing example with body displays empty body when re-importing

### ISSUE THREAD

**Issue by yapily-gkatzioura** [a85/POSTMan-Chrome-Extension#5414] opened 2018-10-23 15:46 UTC
I create an example for one of the requests of my postman collection. Then I export the collection. By importing the collection again the body is empty.

**Steps to reproduce**
Create a collection
Create a POST request with a raw body.
Add an example with a raw body different from the original.
Export the collection.
Import the collection from the json file.

**Expected behaviour**
Example displays the example body

**Actual behaviour**
The example has an empty body.

**App information (please complete the following information):**
 - Postman Version: 6.4.4
 - OS: macOs High Sierra 10.13.6

**Comment by kamalaknn** [comment] 2018-10-24 08:30
Hi @yapily-gkatzioura 

Thanks for reporting this. We've identified the root cause of this in the example request having inconsistent data with `form` body and `raw` body.

We'll push out a fix for this in the next release.

**Closed as completed** 2019-02-03 07:51 UTC
Labels: regression

**Comment by jonathannah** [comment] 2019-04-22 05:07
I have version 7.0.7 and this is still a problem.  I spent hours building my postman collection, and export only to get an empty body.  To make matters worse, Postman also reset in memory so all of my work is lost.  I have tried multiple times to define and save, and always get empty code like below.

	"item": [
		{
			"name": "ping",
			"request": {
				"method": "GET",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": ""
				},
				"url": ""
			},
			"response": []
		},

**Comment by jonathannah** [comment] 2019-04-22 05:57
The problem is that edits made to a collection are not saved.  If you start with a clean collection and insert a request, it has a empty body.  If you edit, and then save, it still has an empty body.  If you hand-edit one request, and then open in Postman and make a copy, then edit, then save, the copy does not reflect the edits.  So it seems that request edits made in Postman can not be saved.

**Comment by sujayvenaik** [comment] 2019-04-22 06:25
Hey @jonathannah 
Request edits are allowed and if you are changing the body and saving data should be persisted.
I tried creating a collection, saving a request and then make some changes and saved again. My request got successfully saved.

Also, by hand edit do you mean that you export a collection, make changes to the collection JSON and then re-import?. I tried this as well and was successfully able to import the collection with my desired changes. 

Can you send a screen recording how exactly you are reaching this state?
Also, can you send us the logs from View -> Developer -> View Logs in Finder?

NOTE: When you export a collection postman picks the saved state of the data and not current unsaved changes in the tab for the requests belonging to that collection.

**Comment by jonathannah** [comment] 2019-04-22 14:39
I walked through the same steps as last night, and I can not reproduce,
which is more frustrating that losing my evening's work.

David
