### ISSUE TITLE
SSL certification verification turned to off no longer works

### ISSUE THREAD

**Issue by Sweathered** [a85/POSTMan-Chrome-Extension#5879] opened 2019-02-04 23:37 UTC
This seems to be a duplicate of this existing issue: https://github.com/postmanlabs/postman-app-support/issues/5819

You can delete this duplicate please.

**Describe the bug**
When trying to Get New Access Tokens from our internal enterprise developer gateway (https endpoint), it throws an error with the following stack trace:
```
"Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)"
```

**To Reproduce**
1. Go to postman preferences
1. Turn SSL Certificate Verification to "OFF"
1. Go to a new request
1. click on authorization tab
1. Click on Get New Access Token
1. Enter in an access token URL with "https" prefix
1. Click Request Token 
1. See error

**Expected behavior**
Since we have SSL certificate verification turned to off, the expected behavior is for the SSL cert to be ignored

**Screenshots**
![image](https://user-images.githubusercontent.com/5304285/52244494-7fc66700-28a3-11e9-9ca3-0578fe80bd40.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.7.3 
 - OS: macOS High Sierra 10.13.6 

**Additional context**

**Comment by numaanashraf** [comment] 2019-02-05 06:28
Duplicate of #5819. Please refer https://github.com/postmanlabs/postman-app-support/issues/5819#issuecomment-457625628 for clarification on this issue.

**Closed as completed by numaanashraf** 2019-02-05 06:28 UTC
Labels: duplicate
