### ISSUE TITLE
"Clear all" history does not works weel

### ISSUE THREAD

**Issue by efrenette11** [a85/POSTMan-Chrome-Extension#8451] opened 2020-05-08 11:30 UTC
**Describe the bug**
When I want to delete my history, here's what I see forever. I must cancel it because it is never ending

![image](https://user-images.githubusercontent.com/30326999/81401535-832b4c80-90fd-11ea-92fd-dbdfb0a2663c.png)

**To Reproduce**
1. Have some history
2. try to clear them all

**App information (please complete the following information):**
 - App Type = Native App
 - Postman Version Version 81.0.4044.129 (Official Build) (64-bit)
 - OS: macOS Mojave 10.14.6

**Comment by sachisahu** [comment] 2020-05-08 15:30
I want to work on it Please assign me this.

**Comment by efrenette11** [comment] 2020-05-08 18:33
I'm also not able to open the runner, nor the console ??? Tried to reinstall, same issue

**Comment by numaanashraf** [comment] 2020-05-08 19:24
Thanks for reporting this @efrenette11. We are tracking this at #6005 .

**Comment by numaanashraf** [comment] 2020-05-08 19:24
Duplicate of #6005

**Closed as completed by numaanashraf** 2020-05-08 19:24 UTC
