### ISSUE TITLE
Documentation Syntax highlighting for snippets written in markdown 

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7770] opened 2019-12-10 12:10 UTC
_Filed by Product Support_

**Is your feature request related to a problem? Please describe.**

For now, the code snippets written in markdown on the **left-hand side** of the documentation don’t have syntax highlighting. Documents have highlighted syntax on the right-hand column only - where code generation happens.

<img width="1680" alt="Screen Shot 2019-12-12 at 10 59 17" src="https://user-images.githubusercontent.com/47351631/70706817-9fea6200-1cce-11ea-8983-92788dd205ee.png">

Example of a code snippet on the left-hand side of a document. 

<img width="688" alt="Screen Shot 2019-12-09 at 11 56 40" src="https://user-images.githubusercontent.com/47351631/70528391-085a0780-1b46-11ea-84e6-f6849a8ff673.png">

**Describe the solution you'd like**

Highlight the syntax of these code snippets the same way it is highlighted when writing the collection's description in edit mode inside the App. 

![Pasted-image-Thu Dec 05 2019 095101 GMT+0100 (Central European Standard Time)](https://user-images.githubusercontent.com/47351631/70528344-e5c7ee80-1b45-11ea-8d8d-1fb0e1821daf.png)

**Comment by torkelrogstad** [comment] 2019-12-13 10:44
Thanks for filing this issue! We (Arcane Crypto) use Postman for our API documentation, and would really love this feature.

**Comment by Raja-Simha** [comment] 2020-02-07 23:18
Duplicate of #5052

**Closed as completed by Raja-Simha** 2020-02-07 23:18 UTC
Labels: feature, product/documentation
