### ISSUE TITLE
post json data with raw data in ubuntu19.04 can not edit json data easily

### ISSUE THREAD

**Issue by 0x2d3c** [a85/POSTMan-Chrome-Extension#7061] opened 2019-08-05 03:31 UTC
os: ubuntu19.04
when i use postman to post json data with raw, can not edit json data  easily! beacuse, i can not choose correctly index  to character which you want to edit

**Comment by wangjiancn** [comment] 2019-08-05 12:54
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37948697/62466115-1cba7c00-b7c3-11e9-9823-ef0482749bba.gif)
Postman7.3.6 in Ubuntu18.04LTS has this problem too.

**Comment by kamalaknn** [comment] 2020-05-25 16:48
Hey @0x2d3c @wangjiancn 

This looks like a duplicate of #2985, where the editor is not able to calculate the cursor positioning because the font used to render the text is not monospace.

Could you try the workaround suggested [here](https://github.com/postmanlabs/postman-app-support/issues/2985#issuecomment-583815252)?

I'm closing this issue as a duplicate please follow the original thread for updates.

**Closed as completed by kamalaknn** 2020-05-25 16:48 UTC
Labels: bug, user-interface, request-sending, product/runtime
