### ISSUE TITLE
Postman Interceptor Desktop Workflow needed

### ISSUE THREAD

**Issue by sosensible** [a85/POSTMan-Chrome-Extension#3874] opened 2017-11-29 13:37 UTC
OK, we understand Chrome Desktop will be going to no updates. But, what about the "Postman Inspector". Are we loosing those features? Will that be updated to work with the native desktop? Or how do we get that now?

**Comment by prashantagarwal** [comment] 2017-11-29 13:42
@sosensible Yes, That's definitely on our roadmap. We do realise how important this is for some user flows. We will keep you updated about this.

**Comment by Kamaros** [comment] 2017-11-29 23:29
+1. Around 90 developers at my workplace use Postman to debug and interact with our app, and it's very tedious to copy all the relevant authentication and tracking cookies to Postman by hand.

**Comment by CoeusCC** [comment] 2017-12-04 22:44
Whoa, I didn't realize I was giving up this feature when I transitioned to the Windows desktop app. Hope to get this feature back soon. Really could have used it today.

**Comment by liester** [comment] 2017-12-06 03:05
@CoeusCC You can still use the web app if you need it.  That is what I do for now.  If you save them to a collection you should be able to sync them to the desktop application afterwards.

**Comment by johngronberg-okta** [comment] 2017-12-11 18:45
@prashantagarwal is this the best issue to track for updates? Or where can we follow along? The interceptor flow is vital to a number of our postman collections.

**Comment by CoeusCC** [comment] 2018-02-08 16:19
I sorted it out with the proxy. I didn't realize it would be so easy because it's not as straightforward as the interceptor, but it is indeed possible by following the instructions here: [https://www.getpostman.com/docs/postman/sending_api_requests/capturing_http_requests](https://www.getpostman.com/docs/postman/sending_api_requests/capturing_http_requests).

I hope everyone who needs this functionality is able to figure out the new method. It's really quite good.

**Comment by sosensible** [comment] 2018-02-09 15:01
Seriously, isn't the chrome extension invalid moving forward? We are not
app only, right?

**Comment by liester** [comment] 2018-02-21 22:43
While what @CoeusCC said is true, I thought there still might be some confusion.  For those of us NOT using a mobile device the documentation for other devices, like windows, is linked at the bottom of that page. (https://www.howtogeek.com/tips/how-to-set-your-proxy-settings-in-windows-8.1/)

Because it wasn't making sense to me at first I'll attempt to explain my thoughts.  The Postman Desktop application, opposed to the chrome app, functions as a proxy server.  If you want your browser history to show up in Postman like you may have been used to with the Chrome App and Interceptor extension, you have to do a couple things:

1. Follow these instructions for setting up the proxy in the Postman App. - Step 1: Set up the proxy in Postman in https://www.getpostman.com/docs/postman/sending_api_requests/capturing_http_requests
2. Configure you device (mine is windows) to use a proxy server. https://www.howtogeek.com/tips/how-to-set-your-proxy-settings-in-windows-8.1/

What this ends up doing is routing all of your web traffic to the Postman Proxy.  Postman then forwards your request to the specified URL.  Specified URL responds, Postman proxy responds, browser gets the response.
NOTE: I haven't done much tinkering with it but this will upset many HTTPS sites so if someone else wants to tackle that issue and report back that would be awesome.

If I've incorrectly stated something, it isn't working, or there is a better way to accomplish this please let me know,

**Comment by vreelb** [comment] 2018-06-20 18:50
Is there any update on this? The proxy workaround given above isn't an acceptable solution for what I need to do.

**Comment by elgplayer** [comment] 2018-06-26 16:00
Ping. I also want an update if this will actually be happening or not. Chrome interceptor is so much better than the proxy.

**Comment by akun2014** [comment] 2018-06-28 07:43
Chrome interceptor is so useful. we need it!

**Comment by Sraw** [comment] 2018-07-16 06:23
So we lose the most important feature?
I just cannot understand at all.

**Comment by prashantagarwal** [comment] 2018-07-16 07:49
@Sraw No you won't lose anything. We are actively working on integrating it with our native apps. Things become little tricky with native apps due to security. But to assure you again, we will have interceptor for native apps.

**Comment by Sraw** [comment] 2018-07-16 08:32
I... I just hope so.

**Comment by n0v3xx** [comment] 2018-07-18 12:05
Guys can you speed up this problem? Over 8 months now and this feature is important.

**Comment by raymondpdurkin** [comment] 2018-08-31 12:07
I just had to switch back to the deprecated Chrome plugin. Debugging Postman is my key usage with .NET attach to w3wp.exe and without this feature I have to battle cookies and proxy settings at work.

Thanks in advance.

**Comment by Sraw** [comment] 2018-08-31 12:10
@raymondpdurkin Guy you are not the only one. Without this feature, Postman is just like broken.

**Comment by nikolaykolibarov** [comment] 2018-09-05 11:45
Still no alternative to Postman Interceptor for desktop Postman application?

**Comment by rickythefox** [comment] 2018-09-05 17:20
I especially miss being able to send requests that automatically include the current authentication cookies. Is there a work-around for this or do I have to copy the cookies manually?

**Comment by Guacam-Ole** [comment] 2018-09-11 15:18
We use SharePoint Authentication (OnPrem & O365). Sadly this does not work with standalone Postman. (at least not without time-consuming workarounds)
We had to switch to ARC with its Cookie-Extension, We really would prefer using Postman again as it has some features we miss in ARC.

**Comment by numaanashraf** [comment] 2018-09-18 13:51
Duplicate of #3874. Moving discussions to the original thread.

**Comment by rickythefox** [comment] 2018-09-18 14:09
Duplicate of itself?

**Comment by Sraw** [comment] 2018-09-18 14:13
Interesting.

**Comment by numaanashraf** [comment] 2018-09-18 14:23
@rickythefox @Sraw  Sorry folks. My bad. 🙏

**Comment by numaanashraf** [comment] 2018-09-18 14:25
Related to #1667

**Comment by ahdung** [comment] 2018-09-20 01:25
+1

**Comment by emizuki** [comment] 2018-10-06 07:57
Without Postman Interceptor, Postman is just another web debugging proxy, like Charles, Burp Suite, Fiddler... I think there is a lot of people not using Postman to develop API. Postman is the best web debugging proxy ever with Interceptor. Make your software different.

**Comment by elgplayer** [comment] 2018-10-06 15:03
I mainly use for scraping, as it is superb!

**Comment by Sraw** [comment] 2018-10-06 15:08
That's true. Without interceptor, there is no core difference between Postman and others.

For scraping? There are maaaannnnny other tools 1000x better than Postman. Postman definitely doesn't focus on scraping.

**Comment by elgplayer** [comment] 2018-10-07 12:05
What other tools can automatically capture get and post request, set the correct headers and cookies and instantly export the request to python code?

**Comment by raymondpdurkin** [comment] 2018-10-08 02:29
So much noise. Can we just agree that it's an important feature and can someone please link to the work item that's going to implement this? Postman team must have this on their plate as a showstopper right?

**Comment by cloudersjun** [comment] 2018-11-29 05:22
we need  this feature

**Comment by a85** [comment] 2018-12-07 05:15
Closing as duplicate of #1667 

No ETA yet but we'll have an announcement soon on the roadmap for this.

**Closed as completed by a85** 2018-12-07 05:15 UTC
Labels: feature, Interceptor

**Comment by fergardi** [comment] 2019-06-21 06:41
Any news?
