### ISSUE TITLE
Windows client cannot bypass proxy

### ISSUE THREAD

**Issue by neildocs** [a85/POSTMan-Chrome-Extension#4430] opened 2018-04-09 14:20 UTC
## App Details:

```
Postman for Windows
Version 6.0.10
Windows 10 / x64
```

## Issue Report:

I am working within a corporation network where internet access is proxy'd as most organizations. The postman for Chrome works fine.
But the windows client seems having issue with proxy. I chose to disable the proxy and **not** using system proxy either. But when I was trying to access a local URI such as [http://localhost:8080/xxx](http://localhost:8080/xxx), or [http://127.0.0.1:8080/xxx](http://127.0.0.1:8080/xxx), I got `504 gateway error` error which tells me the proxy server/gateway does not recognize the URI. 

This is an issue with **standalone windows client only**, the chrome extension works fine.

**Comment by godeater** [comment] 2018-04-13 14:45
I'm getting the same issue. Despite have the proxy settings in the app turned off - all requests I'm sending are still trying to go via the corporate proxy - meaning tests against internal services are now failing.

On more investigation - this appears to be because postman is picking up the values of http_proxy/https_proxy environment variables.

**Comment by daniel0x00** [comment] 2018-05-09 09:18
I think this is a clear bug. As @godeater suggested, Postman Windows client is picking up the http_proxy and https_proxy settings from the environment variables, even when clearly specifying to not use proxy in Postman settings. This also prevent us to work against internally-facing APIs that should not by proxy'd. As a work-around, delete the environment variables in Windows and it will work, but this is not a permanent solution, as removing those variables could break other local applications.

**Comment by harryi3t** [comment] 2018-06-29 12:28
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3942

**Closed as completed by harryi3t** 2018-06-29 12:28 UTC
Labels: bug
