### ISSUE TITLE
Postman crashes on start

### ISSUE THREAD

**Issue by rkpatnaik** [a85/POSTMan-Chrome-Extension#7464] opened 2019-10-11 11:30 UTC
**Describe the bug**
Whenever I am trying to open postman app, it crashes. It brings up the screen but closes instantaneously.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.8.0
 - OS: Windows 7 64-bit

**Additional context**
I tried to uninstall the app and re-install the same, but the issue still persists.

**Comment by Melodyn** [comment] 2019-10-12 03:54
+1

Ubuntu 18.04
Yesterday I received an update to version **7.8** and the application stopped running.
![Screen](https://user-images.githubusercontent.com/26752238/66694516-00542780-ecbd-11e9-9edb-89a116b91368.png)

Log:
```bash
$ ./Postman 
Not disabling GPU
Main~createDefaultWorkingDir - Default working dir creation already attempted
1570851777650 main info "Booting Postman 7.8.0, linux-5.0.0-29-generic on x64"
1570851777651 main info "EventBus~initialize - Success"
1570851777661 main info "UpdateHandler~init - Success"
1570851777664 main info "RuntimeExecutionService~initialized: Success"
1570851777666 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1570851777686 main info "PluginHost~bootHost: Booted - 1"
1570851778309 pluginHost info "Booting Plugin Host for Postman 7.8.0, linux-5.0.0-29-generic on x64"
1570851778312 pluginHost info "PluginsHost: Booted"
1570851778391 pluginHost info "not exist",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/melodyn/.config/Postman/plugins/postman.openApi/version.json","name":"Error","message":"ENOENT: no such file or directory, open '/home/melodyn/.config/Postman/plugins/postman.openApi/version.json'","stack":"Error: ENOENT: no such file or directory, open '/home/melodyn/.config/Postman/plugins/postman.openApi/version.json'"}
1570851778392 pluginHost info "PluginInstallationService~installOrUpdatePlugins Installing plugin",{"version":"0.0.10","pluginId":"postman.openApi","isInstalled":false}
1570851778393 pluginHost info "PluginInstallationService~installFromLocal",{"pluginZipPath":"/home/melodyn/Soft/Postman/app/resources/app/plugins/postman.openApi.zip","pluginsDir":"/home/melodyn/.config/Postman/plugins","currVersionDirPath":"/home/melodyn/.config/Postman/plugins/postman.openApi/0.0.10","tempDir":"/tmp","result":{"pluginId":"postman.openApi","version":"0.0.10","status":null}}
1570851778394 pluginHost info "PluginInstallationService~installFromLocal extracting"
1570851778395 pluginHost info "not exist",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/melodyn/.config/Postman/plugins/postman.sample/version.json","name":"Error","message":"ENOENT: no such file or directory, open '/home/melodyn/.config/Postman/plugins/postman.sample/version.json'","stack":"Error: ENOENT: no such file or directory, open '/home/melodyn/.config/Postman/plugins/postman.sample/version.json'"}
1570851778396 pluginHost info "PluginInstallationService~installOrUpdatePlugins Installing plugin",{"version":"0.0.1","pluginId":"postman.sample","isInstalled":false}
1570851778397 pluginHost info "PluginInstallationService~installFromLocal",{"pluginZipPath":"/home/melodyn/Soft/Postman/app/resources/app/plugins/postman.sample.zip","pluginsDir":"/home/melodyn/.config/Postman/plugins","currVersionDirPath":"/home/melodyn/.config/Postman/plugins/postman.sample/0.0.1","tempDir":"/tmp","result":{"pluginId":"postman.sample","version":"0.0.1","status":null}}
1570851778397 pluginHost info "PluginInstallationService~installFromLocal extracting"
1570851778408 pluginHost warn "PluginInstallationService~installFromLocal: Error while extracting plugin",{"name":"Error","message":"end of central directory record signature not found","stack":"Error: end of central directory record signature not found\n    at /home/melodyn/Soft/Postman/app/resources/app/node_modules/yauzl/index.js:187:14\n    at /home/melodyn/Soft/Postman/app/resources/app/node_modules/yauzl/index.js:631:5\n    at /home/melodyn/Soft/Postman/app/resources/app/node_modules/fd-slicer/index.js:32:7\n    at FSReqWrap.wrapper [as oncomplete] (fs.js:601:17)"}
1570851778410 pluginHost info "PluginInstallationService~installFromLocal Completed installing plugin",{"pluginId":"postman.openApi","version":"0.0.10","status":"failed","error":{}}
1570851778411 pluginHost warn "PluginInstallationService~installFromLocal: Error while extracting plugin",{"name":"Error","message":"end of central directory record signature not found","stack":"Error: end of central directory record signature not found\n    at /home/melodyn/Soft/Postman/app/resources/app/node_modules/yauzl/index.js:187:14\n    at /home/melodyn/Soft/Postman/app/resources/app/node_modules/yauzl/index.js:631:5\n    at /home/melodyn/Soft/Postman/app/resources/app/node_modules/fd-slicer/index.js:32:7\n    at FSReqWrap.wrapper [as oncomplete] (fs.js:601:17)"}
1570851778411 pluginHost info "PluginInstallationService~installFromLocal Completed installing plugin",{"pluginId":"postman.sample","version":"0.0.1","status":"failed","error":{}}
1570851778412 pluginHost info "PluginsHost~installOrUpdatePlugins: Synced all plugins",[{"pluginId":"postman.openApi","version":"0.0.10","status":"failed","error":{}},{"pluginId":"postman.sample","version":"0.0.1","status":"failed","error":{}}]
1570851779211 main info "Bootstrap-models~bootstrap - Success"
1570851780159 main info "window-manager~newSharedWindow: Shell loaded"
1570851782301 main info "Main~AppEvents - Received booted event for process shared"
1570851782307 main error "Main~AppEvents - Shared window boot failed",{"_e":{"message":"","name":"Error","stack":"Error\n    at getErrorWithStack (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:152242:12)\n    at new DexieError (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:152371:19)\n    at mapError (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:152401:14)\n    at handleRejection (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:152885:14)\n    at IDBOpenDBRequest.<anonymous> (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:156092:9)\n    at IDBOpenDBRequest.<anonymous> (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:153098:23)"},"_stack":"VersionError: The requested version (40) is less than the existing version (120).\n    at mapError (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:152401:14)\n    at handleRejection (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:152885:14)\n    at IDBOpenDBRequest.<anonymous> (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:156092:9)\n    at IDBOpenDBRequest.<anonymous> (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:153098:23)","inner":{"message":"The requested version (40) is less than the existing version (120).","name":"VersionError"},"message":"The requested version (40) is less than the existing version (120).","name":"VersionError","stack":"VersionError: The requested version (40) is less than the existing version (120).\n    at mapError (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:152401:14)\n    at handleRejection (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:152885:14)\n    at IDBOpenDBRequest.<anonymous> (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:156092:9)\n    at IDBOpenDBRequest.<anonymous> (file:///home/melodyn/Soft/Postman/app/resources/app/js/vendor-shared.js:153098:23)"}
Gtk-Message: 06:43:02.376: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by Warkdev** [comment] 2019-10-16 07:32
Hello,

I have the exact same problem. Wiping Postman data allows to get it back but the problem is re-occuring usually within the same day:

`{
	"_e": {
		"message": "",
		"name": "Error",
		"stack": "Error
		at getErrorWithStack (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152313:12)
		at new DexieError (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152442:19)
		at mapError (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152472:14)
		at handleRejection (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152956:14)
		at IDBOpenDBRequest.<anonymous> (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:156163:9)
		at IDBOpenDBRequest.<anonymous> (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:153169:23)"
	},
	"_stack": "VersionError: The requested version (40) is less than the existing version (120).
    at mapError (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152472:14)
	at handleRejection (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152956:14)
    at IDBOpenDBRequest.<anonymous> (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:156163:9)
    at IDBOpenDBRequest.<anonymous> (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:153169:23)",
	"inner": {
		"message": "The requested version (40) is less than the existing version (120).",
		"name": "VersionError"
	},
	"message": "The requested version (40) is less than the existing version (120).",
	"name": "VersionError",
	"stack": "VersionError: The requested version (40) is less than the existing version (120).
    at mapError (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152472:14)
    at handleRejection (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152956:14)
    at IDBOpenDBRequest.<anonymous> (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:156163:9)
	at IDBOpenDBRequest.<anonymous> (file:///C:/UserTemp/Apps/Postman/App/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:153169:23)"
}`

**Comment by pvgennip** [comment] 2019-10-16 12:34
Same here with new release Postman 7.9.0 desktop app on Mac OS Mojave 10.14.6. As soon as app is started: popup with: **Could not open Postman** Please contact help@getpostman.com OK.
Then it continues with Preparing your workspaces... but does nothing. Any option clicked from the application menu crashes the program.

**Comment by grimsa** [comment] 2019-10-17 13:12
Same here after upgrading to `Postman 7.9.0, win32-10.0.18362 on x64`

```
[1236][1571317656687][main][info]["Booting Postman 7.9.0, win32-10.0.18362 on x64"]
[1236][1571317656690][main][info]["EventBus~initialize - Success"]
[1236][1571317656693][main][info]["UpdateHandler~init - Success"]
[1236][1571317656694][main][info]["RuntimeExecutionService~initialized: Success"]
[1236][1571317656703][main][info]["PluginHost~bootHost: Booted - 1"]
[1236][1571317656836][main][info]["Bootstrap-models~bootstrap - Success"]
[1236][1571317657140][main][info]["window-manager~newSharedWindow: Shell loaded"]
[1236][1571317658335][main][info]["Main~AppEvents - Received booted event for process shared"]
[1236][1571317658335][main][error]["Main~AppEvents - Shared window boot failed",{"_e":{"message":"","name":"Error","stack":"Error\n    at getErrorWithStack (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152313:12)\n    at new DexieError (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152442:19)\n    at mapError (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152472:14)\n    at handleRejection (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152956:14)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:156163:9)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:153169:23)"},"_stack":"VersionError: The requested version (40) is less than the existing version (120).\n    at mapError (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152472:14)\n    at handleRejection (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152956:14)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:156163:9)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:153169:23)","inner":{"message":"The requested version (40) is less than the existing version (120).","name":"VersionError"},"message":"The requested version (40) is less than the existing version (120).","name":"VersionError","stack":"VersionError: The requested version (40) is less than the existing version (120).\n    at mapError (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152472:14)\n    at handleRejection (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:152956:14)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:156163:9)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Fel/AppData/Local/Postman/app-7.9.0/resources/app.asar/js/vendor-shared.js:153169:23)"}]

```

Uninstalling the app via Programs and Features and reinstalling after downloading latest installer from the official site did not help.

**Comment by netanelravid** [comment] 2019-10-24 06:59
same here
tried 7.9, 7.8, 7.7.3
all of them crashed

**Comment by dosse** [comment] 2019-10-25 18:38
Same for me with Postman 7.10.0 on Win64. Postman refuses to revert to previous version. How do you wipe Postman data?

**Comment by kamalaknn** [comment] 2019-11-04 08:21
This looks like a duplicate of #5373

I'm closing this issue for now. Please follow the original thread for updates.

**Closed as completed by kamalaknn** 2019-11-04 08:21 UTC
Labels: bug
