### ISSUE TITLE
Runner runs black screen just after user opens it

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6960] opened 2019-07-19 13:04 UTC
**The bug description**
Usually when postman windows goes black due to electron bug, runner windows either goes black untill you don't restart it (console stay working). Sinse postman 7.2.2 runner may start with already black and empty window.

**To Reproduce**
1. Run runner from collection side bar context menu
2. See error

**Expected behavior**
Runner is expected to became still black when Postman does.

**Screenshots**
![1907](https://user-images.githubusercontent.com/25632818/61537069-e51ba800-aa3e-11e9-8257-482496100137.jpg)

**App information:**
 - Native App
 - Postman 7.2.2
 - OS: windows 7 32 bit

**Comment by saswatds** [comment] 2020-02-12 07:40
We have pushed all of our performance fixed to the stable version 7.18.0. The runner should be snappier and not crash. Can you update to the latest version and check if this issue is fixed for you?

**Comment by saswatds** [comment] 2020-03-11 05:19
Closing the issue now as other users have reported then the issue is fixed for them.

**Closed as completed by saswatds** 2020-03-11 05:19 UTC
Labels: performance, collection-runner, product/runtime
