### ISSUE TITLE
Authorization Type: JWT Token

### ISSUE THREAD

**Issue by eschwartz** [a85/POSTMan-Chrome-Extension#7424] opened 2019-10-02 21:42 UTC
**Is your feature request related to a problem? Please describe.**

I have an API that accepts JWT tokens, which I would like to test against. Currently, I need to manually generate and encode my tokens, which is slow, and involves a lot of context-switching.

**Describe the solution you'd like**

I would like the _Authorizations_ panel to allow a new _Type_ called _JWT Token_. It would accept a JSON payload and a secret, and use that information to populate the `Authorization` header with an encoded value.
See for example https://jwt.io/

**Describe alternatives you've considered**

I am currently encoding the token and setting the `Authorization` header myself

**Comment by codenirvana** [comment] 2019-10-03 02:58
Duplicate of #5548

**Closed as completed by codenirvana** 2019-10-03 02:58 UTC
Labels: duplicate, product/runtime
