### ISSUE TITLE
Postman extension crashed when POST done for 1301447L of REST payload

### ISSUE THREAD

**Issue by abhisek193** [a85/POSTMan-Chrome-Extension#3771] opened 2017-11-10 08:13 UTC
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sdnts** [comment] 2017-11-14 15:23
@abhisek193 Can you provide a little more info about this? Steps to reproduce will help us get to the bottom of this faster.

**Comment by kamalaknn** [comment] 2018-07-05 08:10
I'm closing this as a duplicate of #4751 

We're tracking similar issues related to Postman handling large responses. Please follow the original thread for updates.

**Closed as completed by kamalaknn** 2018-07-05 08:10 UTC
Labels: bug
