### ISSUE TITLE
when i use csv file, the last data is changed

### ISSUE THREAD

**Issue by tester1234562020** [a85/POSTMan-Chrome-Extension#6203] opened 2019-04-02 02:59 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
![image](https://user-images.githubusercontent.com/44419851/55373005-5427cc00-5536-11e9-9d07-ca3bc1c33228.png)
![image](https://user-images.githubusercontent.com/44419851/55373023-60138e00-5536-11e9-9d23-12c9d54c7560.png)
![image](https://user-images.githubusercontent.com/44419851/55373024-6570d880-5536-11e9-87e4-1f38892d4921.png)
![image](https://user-images.githubusercontent.com/44419851/55373027-69045f80-5536-11e9-9981-e44ed9c6d7d5.png)

**Comment by shamasis** [comment] 2019-04-02 05:10
Open the CSV file in a text editor and check if it has a new line at the end of it. In fact, can you post the CSV file here?

**Comment by tester20183450** [comment] 2019-04-02 06:54
Now,it is ok. I dont konw why..

**Comment by tester20183450** [comment] 2019-04-02 07:20
hello,i dont know how to post here

**Comment by tester1234562020** [comment] 2019-04-02 07:22
[1.txt](https://github.com/postmanlabs/postman-app-support/files/3032741/1.txt)
i have post it , you need to change to csv

**Comment by shamasis** [comment] 2019-04-03 19:16
Close duplicate of two issues. Keeping reference and tracking in original issue:
https://github.com/postmanlabs/postman-app-support/issues/3427

**Closed as completed by shamasis** 2019-04-03 19:16 UTC
Labels: bug, duplicate, product/runtime
