### ISSUE TITLE
Automatically assign "Editor" role to members, once the owners exit the workspace

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6994] opened 2019-07-25 08:39 UTC
**Describe the bug**
When the owner of the collection exits the workspace, other members of the workspace cannot manage the collection if the owner hasn't assigned the editor roles to them. This blocks the team from working on the collection.

**To Reproduce**
1. Create a Collection on a Team workspace
2. Provide only "Viewer" roles to other members
3. Leave the Team workspace
4. Other members cannot manage that collection

**Expected behavior**
Automatically provide "Editor" role to members of the workspace, similar to the action when the user leaves the team.

**Screenshots**
<img width="911" alt="ManageRole" src="https://user-images.githubusercontent.com/47771757/61859236-5cd94f00-aee5-11e9-864d-1c191b0851de.png">

**App information:**
 - App Type - Native App
 - Postman Version - v7.3.4

**Additional context**
The other members will automatically get the "Editor" role when the owner of the collection who has previously left the workspace also leaves the team.

**Comment by sankalp0o** [comment] 2019-07-26 05:59
@Raj-postman that is the intended behaviour. People in other workspaces can access this collection, including the person who created it. This is why we can't infer that "...This blocks the team from working on the collection".

Related to this, we are working on the ability for users to request for access to a collection if they don't have it, that should take care of users who feel that they should have access but do not. I'm closing this issue, but feel free to reopen it in case this didn't address the user's concerns.

**Closed as completed by sankalp0o** 2019-07-26 05:59 UTC
