### ISSUE TITLE
"Something went wrong" screen on todays history deletion

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6444] opened 2019-05-08 15:34 UTC
**The bug description**
When I push on trash icon to delete todays request history postman displays message "something went wrong"

**To Reproduce**
1. Make several requests
2. Click on trash icon to delete todays history
3. See error "something went wrong"

**Expected behavior**
History is to be empty

**Screenshots**
Applied
![deletetodayhistory](https://user-images.githubusercontent.com/25632818/57387855-c5a30c00-71bf-11e9-93d2-6a932cc0bf14.jpg)
**App information:**
 - App Type: Native
 - Postman Version:7.0.9

 - OS: Windows 7 32 bit

**Comment by sujayvenaik** [comment] 2019-05-08 15:36
Duplicate of #6378

**Closed as completed by sujayvenaik** 2019-05-08 15:36 UTC
