### ISSUE TITLE
Do you have any plans for Chinese?

### ISSUE THREAD

**Issue by joesdu** [a85/POSTMan-Chrome-Extension#5055] opened 2018-08-21 02:09 UTC
Do you have any plans to support the language of other countries, such as Chinese.

**Comment by numaanashraf** [comment] 2018-08-21 08:30
@Dygood Yes we do. But we haven't taken this up yet and I don't have an ETA on when we'ld be supporting Chinese.

**Comment by a85** [comment] 2019-03-10 04:36
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/3126

**Closed as completed by a85** 2019-03-10 04:36 UTC
Labels: feature, i18n
