### ISSUE TITLE
Support for exporting current values

### ISSUE THREAD

**Issue by anirudhanagaraja** [a85/POSTMan-Chrome-Extension#7626] opened 2019-11-12 13:06 UTC
**Describe the bug**

The import of the postman environment will not take the values used previously also missing some variables.

**To Reproduce**
1. Create postman env .
2. export
3. Import the same in other postman
4. you can see the values are not present also missing some variables.

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by harryi3t** [comment] 2019-11-13 03:58
@anirudhanagaraja Can you share the exported file and some screenshots after importing the environment showing the bug?

**Comment by anirudhanagaraja** [comment] 2019-11-13 04:06
Nope sorry , cant share as it is COBC..

**Comment by harryi3t** [comment] 2019-11-13 04:11
@anirudhanagaraja Are you allowed to share dummy environments with random values? It would really help us debug the issue faster.

**Comment by anirudhanagaraja** [comment] 2019-11-13 04:29
Here are the things which can be used as reference.. But in this you can see the values of env has got changed . In some other cases even the variables went missing.

**Comment by anirudhanagaraja** [comment] 2019-11-13 04:33
[Reference.zip](https://github.com/postmanlabs/postman-app-support/files/3839439/Reference.zip)

All the required docs..
FYI
Before Export : Current and initial values are different.
Exported the file.
After Import : Current value is replaced with Initial value

**Comment by harryi3t** [comment] 2019-11-13 11:22
@anirudhanagaraja That is the expected behavior. Right now `current values` are not exported.

**Comment by codenirvana** [comment] 2019-11-14 05:40
Duplicate of #6728

**Closed as completed by codenirvana** 2019-11-14 05:40 UTC
Labels: variables, duplicate, product/runtime
