### ISSUE TITLE
Select All option in the contextual menu in Postman's body section is not working

### ISSUE THREAD

**Issue by Carlos-Contreras-DXC** [a85/POSTMan-Chrome-Extension#12593] opened 2024-01-22 22:18 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the Postman's body section, I select the **raw** option, then I select the **JSON** option, finally I add a large (almost 1,000 lines after beautifying it) data request (in JSON format). 

If I right click on that section and select the **Select All** option, nothing happens.

However, the Ctrl + A option is working fine.

### Steps To Reproduce

1. Open a new request tab
2. Select the **Body** tab
3. Select the **raw** type
4. Select the **JSON** option
5. Include some data request (in JSON format)
6. Right click on the text
7. Click on the **Select All** option

![image](https://github.com/postmanlabs/postman-app-support/assets/157425801/290e1a0c-9020-4708-8b86-83356b2d0743)

### Operating System

Windows

### Postman Version

10.22.1

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

By the way, I already tested all the other options available for the **raw** type (**Text**, **JavaScript**, **HTML** and **XML**), and the **Select All** option from the contextual menu is not working either.

I also tested with a much smaller data request (10 lines), but the option still is not working.

**Comment by satokenta940** [comment] 2024-03-18 05:55
Perhaps you can try [Apidog](https://apidog.com/), a friend of Postman.

**Comment by parthverma1** [comment] 2024-03-18 07:22
Hello,

Thank you for bringing this issue to our attention. We understand how inconvenient it can be when features don't work as expected.

We'll investigate this further on our end to determine the root cause of the issue. In the meantime, using the Ctrl + A shortcut should provide a workaround for selecting all the content in the body section.

We appreciate your patience and understanding as we work to resolve this issue promptly. If you have any additional information or further questions, please don't hesitate to let us know.

Thanks you again for bringing this to our attention.

**Comment by parthverma1** [comment] 2024-05-22 09:01
@Carlos-Contreras-DXC This is fixed in the latest version of the app.

**Closed as completed by parthverma1** 2024-05-22 09:01 UTC
