### ISSUE TITLE
could not open postman help@getpostman

### ISSUE THREAD

**Issue by Srb1996** [a85/POSTMan-Chrome-Extension#7296] opened 2019-09-10 11:26 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
![Screenshot (1)](https://user-images.githubusercontent.com/42827764/64609955-c2c55b80-d3eb-11e9-935d-56c546fc081a.png)

**Comment by numaanashraf** [comment] 2019-09-14 19:15
We are tracking this issue at #5591. Closing as duplicate of #5591.

**Closed as completed by numaanashraf** 2019-09-14 19:15 UTC
Labels: duplicate
