### ISSUE TITLE
Postman Monitor flatline across workspace

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#7281] opened 2019-09-06 18:18 UTC
Filing on behalf of the user. 

**Describe the bug**
Postman Monitor dashboard latency graph is showing a flatline across all collections in the workspace. 

The user shows data coming in from server with latency has data properly coming in from the server. The client is not properly displaying the graph. 

**To Reproduce**
1. Go to a monitor in a collection
2. Check the collections run without any issue and have latency
3. Monitor graph shows a flatline

**Comment by aaronbelanger** [comment] 2019-09-06 18:23
Thank you @stcalica!

**Comment by shivam-postman** [comment] 2019-09-09 09:57
Hello @aaronbelanger, we're looking into the issue. The graph shows a flat line if the currently selected region is different from the ones in which the monitor ran. Can you please verify that it's not the case? An easy way to ensure that is to make sure that the region selected in both the region selection drop-downs (the one above the graph and the one below it) is same and the test results show some response time for each request.

**Comment by aaronbelanger** [comment] 2019-09-09 11:33
@shivam-postman Our region selected (US Static IP) is the same as the one we run our tests in. Let me know if you need more details!

**Comment by cyrielle-hada** [comment] 2019-09-09 15:54
@stcalica looks like a duplicate of this issue: https://github.com/postmanlabs/postman-app-support/issues/5378.

**Comment by shivam-postman** [comment] 2019-09-12 06:29
Hi @aaronbelanger, the issue existed only for the static regions and has been fixed. The fixed version will be available in our next release.

**Comment by ash007-postman** [comment] 2019-10-30 03:08
@shivam-postman  Another user reported the same and more details can be in the attached info

**Comment by ArjunSingh-PM** [comment] 2019-11-14 12:49
Confirmed that this issue is fixed.

**Closed as completed by ArjunSingh-PM** 2019-11-14 12:49 UTC
Labels: bug, product/automation-testing
