### ISSUE TITLE
Duplicate tab should duplicate the request

### ISSUE THREAD

**Issue by ilam-natarajan** [a85/POSTMan-Chrome-Extension#9273] opened 2020-11-13 15:14 UTC
**Is your feature request related to a problem? Please describe.**
When I duplicate a tab, the same request reference is opened in duplicate tab. Any change in new tab causes conflict in the original tab. This causes frustration.

**Describe the solution you'd like**
When a tab is duplicated, it should also create duplicate request (similar to what happens when you right click on a request and duplicate). 

**Describe alternatives you've considered**
no alternatives

**Comment by DannyDainton** [comment] 2020-11-13 15:22
This is the intended behaviour of that `Duplicate Tab` action - The naming of that action suggests that it's doing something different though.

> Duplicating a tab does not mean creating a second request to the same endpoint—when you duplicate a tab any edits you make will affect the original request.

https://learning.postman.com/docs/getting-started/navigating-postman/#tabs

We currently have an open issue to take a look at this so I'm going to close this FR.

**Closed as completed by DannyDainton** 2020-11-13 15:22 UTC
