### ISSUE TITLE
Documentation: generated cURL doesn't escape $

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5878] opened 2019-02-04 23:25 UTC
**Issue:**
Generated cURL on docs site doesn't escape `$`. When a `$` appears at the beginning of (e.g.) a property name in a JSON request body, the actual key is lost when sending the request.

Request body (JSON):
`{"$example_key": 26}`

Generated cURL:
```
curl --location --request GET "https://postman-echo.com/get?test=123" \
  --header "Content-Type: application/json" \
  --data "{\"$example_key\": 26}"
```
From response body (postman-echo):
`"":26`

**Ideal solution:**
Wrap cURL argument strings in single quotes, as done in the Postman app. This works fine:
```
curl -X GET \
  'https://postman-echo.com/get?test=123' \
  -H 'Content-Type: application/json' \
  -d '{"$example_key": 26}'
```

Or, escape `$` characters.

**Comment by codenirvana** [comment] 2019-02-04 23:28
Duplicate of #5737

**Closed as completed** 2019-02-18 15:00 UTC
