### ISSUE TITLE
Add proxy exceptions or disable proxy for local urls

### ISSUE THREAD

**Issue by Kapcash** [a85/POSTMan-Chrome-Extension#6484] opened 2019-05-13 12:29 UTC
I often use a proxy when using postman. But when I debug local servers, I want to reach localhost easily, which isn't possible using the proxy. For the moment, I switch it on/off from the settings quite often when I want to reach urls unaccessible from the proxy.

Thus I would like to be able to set up some **exceptions for the proxy**. I want to configure a list of domain names that should not go through the proxy, as "localhost" or "http://localhost:8080/*, "http://www.google.com" for instance. Regex could be used here as well to except more specific urls.

Many proxy settings propose this feature (see the proxy setting on Mozilla Firefox), or at least a **checkbox to disable the proxy for local urls** (see the proxy settings from Windows 10).

**Comment by codenirvana** [comment] 2019-05-13 13:01
Duplicate of #6380
Refer: https://github.com/postmanlabs/postman-app-support/issues/6380#issuecomment-487504172

**Closed as completed by codenirvana** 2019-05-13 13:01 UTC
