### ISSUE TITLE
Auth login window is not ignoring certificate errors after disabling ssl certificate verification

### ISSUE THREAD

**Issue by mgohashi** [a85/POSTMan-Chrome-Extension#4371] opened 2018-03-22 12:57 UTC
Postman for Mac
Version 6.0.10
OS X 16.4.0 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: 
After installing the most recent version of Postman

 2. Expected behaviour: 
Show auth login page ignoring certificate errors

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

`Opening auth login window https://[url]/auth/realms/#####/protocol/openid-connect/auth?response_type=code&state=&client_id=3ab0b6ba&scope=user&redirect_uri=https%3A%2F%2Fopenidconnect.net%2Fcallback`

 4. Screenshots (if applicable)
   4.1. Install version 6.0.10 on MacOSX
   4.2. Install a OpenID Test server (such as: Keycloak) with an self signed certificate
   4.3. Configure a new OAuth 2.0 with authorization and token URL's to that server server
   4.4. Click on the Request Token button

And you will see an empty page.

**Comment by harryi3t** [comment] 2018-03-23 17:47
duplicate of https://github.com/postmanlabs/postman-app-support/issues/2918

**Closed as completed by harryi3t** 2018-03-23 17:47 UTC
