### ISSUE TITLE
All collections lost after app got blocked

### ISSUE THREAD

**Issue by iscarmario** [a85/POSTMan-Chrome-Extension#4476] opened 2018-04-19 14:55 UTC
## App Details:

```
Postman for Windows
Version 6.0.10
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
This issue happend just after postman got blocked and had to end the task from the windows task manager
 2. Expected behaviour:
All previously stored collections are available in the collections tab
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
N/A
 4. Screenshots (if applicable)
N/A

For some reason Postman got blocked. Then I've end the task from the task manager. After reopening the application the collections tab is empty.
I was never signed in so no config can be retrieved online.

Can you please give support on how to recover lost collections?

Thank you.

**Comment by kamalaknn** [comment] 2018-04-23 11:33
Hi @iscarmario 

Can you open your devtools(View -> Developer -> Sow DevTools (Current View)) and check if there are any errors?

Could you share more information on your exact steps that led to this? Also, when you say `blocked` could you explain what you mean by it?

**Comment by iscarmario** [comment] 2018-04-23 11:49
Hell @kamalaknn 

What I mean by blocked is "not responding", for which I had to end the task from the Windows Task Manager
Regarding the steps followed, it's not easy not reproduce exactly as it was: I was jumping between several windows, including postman. After having perform one request in postman just few seconds before, I came back to postman and it was not responding. I finished the task and relaunch postman. Once it the postman interface was loaded, I realized all previously existing collections were missing.

This is what I find in DEV:

`Initializing the global config
requester.js:360887 Initializing settings
requester.js:298482 Booting waterline models
requester.js:298548 Objectcollections: Objectdatastores: Objectinitialize: initialize(options, done)loadCollection: heyThatsDeprecated()registerModel: registerModel(wmd)teardown: teardown(done)__proto__: Object "Successful ORM initialization"
requester.js:369095  ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs.
================================================================
requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
requester.js:560264 Check that entitites shown here should only be personal entites
componentWillMount @ requester.js:560264
requester.js:368809 error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (requester.js:75398)
    at EventEmitter.108.EventEmitter.emit (common.js:17099)
    at _dispatch (common.js:24502)
    at EventEmitter.<anonymous> (common.js:24512)
    at emitTwo (events.js:106)
    at EventEmitter.emit (events.js:191)
8requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
mode-auto.js Failed to load resource: net::ERR_FILE_NOT_FOUND`

**Comment by kamalaknn** [comment] 2018-04-23 14:09
Hey @iscarmario 

The logs look fine. I'm having trouble identifying the root cause here. Can you check if the data is still intact in the local database?

1. Open `Application` tab in `DevTools`
2. Select `postman-app` in `indexedDB`
3. Look for `collections`, `folders` and `requests` tables

**Comment by iscarmario** [comment] 2018-04-27 08:40
Hi @kamalaknn 

All tables are completely empty currently

**Comment by numaanashraf** [comment] 2019-08-01 11:44
This seems to be an isolated case and we have shipped multiple fixes to prevent such issues in Postman v7.1.0 and above. Closing this issue for now. Please reopen if you are still facing this in the latest version of Postman.

**Closed as completed by numaanashraf** 2019-08-01 11:44 UTC
Labels: bug, postman-data
