### ISSUE TITLE
GraphQL Query Scheme doesn't work with Enum when it's required

### ISSUE THREAD

**Issue by Klaesy** [a85/POSTMan-Chrome-Extension#12746] opened 2024-03-28 09:02 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have two input fields to select a specific language from a Enum. Normally it will show a nice Select with all available options, however if the input is required the input field is turned into a regular text field. For Enums a text field won't work since it adds quotes around the input, which isn't allowed for Enums.

### Steps To Reproduce

Have an GraphQL endpoint with two Enum input fields, one being optional, and the other being required.
Select a value for both input fields.

### Operating System

Windows

### Postman Version

10.24.3

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by bfwg** [comment] 2024-06-29 00:10
Running into the same problem.

**Comment by EmilianoCervantesOfferUp** [comment] 2024-07-16 16:21
Same, doesn't make sense.

<img width="508" alt="Screenshot 2024-07-16 at 12 21 31" src="https://github.com/user-attachments/assets/3d202c67-a675-46ed-88f8-1d96b07681e2">

**Comment by barthansen** [comment] 2024-08-13 13:38
Same for me - input is enum and mandatory
it shows me a text input box and adds quotes in the request body

I run Postman  v11.2.0

Update: After changing this field to optional, postman showed the list as a dropdown - so this clearly is a bug in postman

**Comment by timhall** [comment] 2024-08-13 14:16
@SkippyTheMonkeyKeeper thanks for reporting this issue. It has been fixed in Postman 11.6.0 released on July 31st. @barthansen can you try upgrading Postman and see if you are still facing this issue?

**Closed as completed by timhall** 2024-08-13 14:16 UTC
Labels: protocol/graphql, product/api-client

**Comment by barthansen** [comment] 2024-08-14 13:15
@timhall 
Upgraded to latest version - confirm the issue is fixed
thnx a lot ;-)
