### ISSUE TITLE
Allow permanently hiding yellow banner (local work)

### ISSUE THREAD

**Issue by SynapseScribe** [a85/POSTMan-Chrome-Extension#9782] opened 2021-03-30 10:21 UTC
When not connected to a workspace / internet connection cut, a yellow banner is displayed: "Working locally in Scratch Pad. Switch to a Sorkspace". Every time I open the app, I have to close it and it keeps reappearing which is quite a nudge..

**Comment by johndanek** [comment] 2021-04-14 18:59
Agreed. I am fully aware that my Postman data only exists on my local machine- that is the way I choose to use it. There's a little burst of annoyance every time I open the app.

**Comment by debargharoy** [comment] 2021-06-15 18:40
I understand that it's not a priority from a functionality standpoint but given the damage, it's causing to user experience, is there an ETC for this? Not sure how many people are bothered by it, but as already said by @johndanek it's annoying to close the banner every time we start the app.

**Comment by d-schmidt** [comment] 2021-06-29 09:20
They want to lock in our data and then have us pay for it. I doubt they will remove this greedy banner. There is no reason for it to return every start.

**Comment by 3omar-mostafa** [comment] 2021-08-23 20:48
If you are interested, I've created a node app to patch Postman to remove this banner
Manual patching method is also included in the Readme if you are intersted about the methodology

You can have a look [Postman-Scratchpad-Banner-Fix](https://github.com/3omar-mostafa/Postman-Scratchpad-Banner-Fix)
I hope this can help you

**Comment by dmaltsiniotis** [comment] 2021-11-23 23:01
This is related to #9488, referencing here for whoever runs triage.

**Comment by DannyDainton** [comment] 2022-06-28 14:28
Duplicate of #9488

**Closed as completed by DannyDainton** 2022-06-28 14:28 UTC
Labels: user-interface
