### ISSUE TITLE
tv4 Validation does not console.log where my error is at 

### ISSUE THREAD

**Issue by evan-k-wright** [a85/POSTMan-Chrome-Extension#7527] opened 2019-10-24 15:13 UTC
Since the new Postman update, anytime I use **tv4.error.dataPath** and **tv.error.schemaPath**, the console no longer shows me where the error is at. 

How do I get the console to show me my errors and where they are at in the schema?

**Comment by evan-k-wright** [comment] 2019-10-24 15:14
Sorry I don't have a lot of information, screenshots, or steps to reproduce. Feel free to ask me questions for me clarification.

**Comment by xk0der** [comment] 2019-10-25 00:19
@evan-k-wright  Thanks for writing in here as well.
I'm putting the information I shared with you internally as a reference for others as well.

VT4 has been deprecated and it is recommended that you use [AJV](https://github.com/epoberezkin/ajv) for JSON schema validation.

*References:*
- GitHub Issue: https://github.com/postmanlabs/postman-app-support/issues/3199
- https://learning.getpostman.com/docs/postman/scripts/postman_sandbox

I'm leaving this open for our Devs to triage and qualify as well.

**Comment by codenirvana** [comment] 2019-10-25 06:52
Duplicate of #3300

@evan-k-wright tv4 is deprecated in favor of Ajv. Check https://github.com/postmanlabs/postman-app-support/issues/3300#issuecomment-460177101 for more details.

Ajv have great documentation around debugging the validation errors https://github.com/epoberezkin/ajv#validation-errors

**Closed as completed by codenirvana** 2019-10-25 06:52 UTC
Labels: support, duplicate, product/runtime

**Comment by evan-k-wright** [comment] 2019-10-25 14:08
Thank you @xk0der and @codenirvana! I really appreciate the quick responses and the information on the new software to use.
