### ISSUE TITLE
Requesting token OAuth 2 token, "Something went wrong"

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7828] opened 2019-12-19 22:18 UTC
**Describe the bug**
When attempting to generate an OAuth2 token using the authorization helper, the user's app shows the error "Something went wrong".

Logs display the following error:

> [12164][1576673260350][main][warn]["OAuth2TokenRequester~startTokenRequestFlow: Error while requesting token ",{"name":"Error","message":"Could not complete OAuth 2.0 token request","stack":"Error: Could not complete OAuth 2.0 token request\n    at Function.response (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\services\\OAuth2TokenRequester.js:381:26)\n    at PostmanCollectionRun.<anonymous> (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\runner\\extensions\\request.command.js:66:50)\n    at PostmanCollectionRun.<anonymous> (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\runner\\extensions\\request.command.js:87:21)\n    at apply (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\lodash\\lodash.js:475:27)\n    at C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\lodash\\lodash.js:9473:36\n    at C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\lodash\\lodash.js:4881:15\n    at Function.<anonymous> (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\lodash\\lodash.js:9472:7)\n    at apply (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\lodash\\lodash.js:476:27)\n    at Function.invokeMap (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\lodash\\lodash.js:6563:16)\n    at Instruction.<anonymous> (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\runner\\instruction.js:145:48)\n    at safeNext (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\runner\\extensions\\http-request.command.js:69:28)\n    at C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\runner\\extensions\\http-request.command.js:205:32\n    at onEnd (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:309:24)\n    at onComplete (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:343:21)\n    at Request._callback (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:468:13)\n    at Request.self.callback (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-request\\request.js:255:12)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:442:20)\n    at Request.<anonymous> (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-request\\request.js:1439:10)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:442:20)\n    at IncomingMessage.<anonymous> (C:\\Users\\User\\AppData\\Local\\Postman\\app-7.13.0\\resources\\app.asar\\node_modules\\postman-request\\request.js:1310:12)"}]
>

User's OAuth2 configuration is using Client Credentials. All fields are filled out, and CLIENT AUTHORIZATION is set to: `Send client credentials in body`

**To Reproduce**
Support unable to reproduce

**Expected behavior**
Token is generated successfully.

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: v7.14.0
 - OS: Windows 10

**Additional context**
Logs attached:
[logs (1).zip](https://github.com/postmanlabs/postman-app-support/files/3985859/logs.1.zip)

**Comment by codes-zain** [comment] 2020-01-09 10:01
I'm facing the same issue did you solve it ?

**Comment by jcherniak** [comment] 2020-01-10 19:22
I ran into this same issue, and it occurred because our OAuth endpoint was not working properly.  In our case, it was returning a 200, with a content of "null".

I would guess, based on this, the error appears to lie with error handling in the OAuth token calls in Postman.

@codes-zain Hit your OAuth endpoint manually and make sure it's working to spec to work around the issue.  Note: hitting it manually in Postman worked.  You can always take the token and use it in other Postman requests, until they fix their error handling.  If it IS working properly, then this might be caused by something else.

@vvs11 I am still getting this error as well when I go to delete the "tokens" created when we returned null.  When I click on the delete button, it crashes Postman.

Steps to reproduce, based on my usecase:

1. Make an endpoint that, when called returns: HTTP 200 and a content of "null".  I'm not sure what the Content-type was, but it would either be text/html or application/json.
2. Notice that crashes Postman when it's returned.
3. It will also create a "token", with the name specified in the OAuth token dialog.
4. Trying to view, or delete that invalid token also crashes Postman.

**Comment by JP-from-Postman** [comment] 2020-02-24 18:54
Another user reporting this on:
macOS Catalina Version 10.15.3
Postman Version 7.18.1

They're able to hit the auth endpoint manually using Postman, but using auth helper errors out. They're also encountering the behavior noted in [#8054](https://github.com/postmanlabs/postman-app-support/issues/8054)

**Comment by vikiCoder** [comment] 2020-03-16 07:40
Hi everyone,

We have fixed this issue with `Manage Tokens` dialog and the fix is out in the latest [Postman canary (7.21.0-canary01)](https://www.postman.com/downloads/canary). It will be fixed in the next version of the Postman app (v7.21) soon. Meanwhile, please check out the latest [Postman canary](https://www.postman.com/downloads/canary) and let us know if you are still facing the same issue in it.

**Comment by vikiCoder** [comment] 2020-03-23 13:46
The fix is out in the latest version of the Postman app (v7.21.0).

**Closed as completed by vikiCoder** 2020-03-23 13:46 UTC
Labels: bug, pending-close, OAuth2, product/runtime
