### ISSUE TITLE
Windows Desktop Proxy issues, Chrome app works fine

### ISSUE THREAD

**Issue by neon096** [a85/POSTMan-Chrome-Extension#3715] opened 2017-11-02 09:24 UTC
## App Details:
Postman for Windows
Version 5.3.2
win32 10.0.14393 / x64

This is the proxy settings

Global Proxy Configuration

ON
Specify a global proxy setting to act as an intermediary for requests sent to the server.Learn more about using a global proxy
Proxy Type
HTTP =  Y 
HTTPS = Y
Proxy Server xxx.xxx.xxx.xxx:1
Use System Proxy

ON

When sending a message through the Desktop app to our internal servers I get the following messages. However sending through the Chrome plugin it works fine. I have proxy settings in app set to use system settings and I've also tried to use the IP directly. However our proxies are setup using a remote JavaScript. 

OUTPUT

Enable this option to allow Postman to use the system's default proxy configurations.

Could not get any response
There was an error connecting to https://xxxxxxxxx.com/xxxx/xxxxx.aspx.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

**Comment by mbrasier** [comment] 2017-11-02 09:42
This is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/3692
caused by not supporting NTLM proxies before withdrawing the chrome app

**Comment by prashantagarwal** [comment] 2017-11-02 16:46
@neon096 I am closing this as duplicate of #3692

**Closed as completed by prashantagarwal** 2017-11-02 16:46 UTC
