### ISSUE TITLE
Unable to read Cyrillic symbols in response body

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6716] opened 2019-06-14 14:56 UTC
**Describe the bug**
The JSON response doesn't return Cyrillic symbols. It returns Unicode symbols instead. 
Content-Type of response is text/html; charset=UTF-8. 

**To Reproduce**
1. Go to either Version 7.1.1-canary08 or Postman version 7.2.0
2. Send a GET request to an endpoint that renders Cyrillic symbols (e.g. https://www.rambler.ru/location/current)
3. See only Unicode symbols
![reproduce](https://user-images.githubusercontent.com/47351631/59566036-5936ea80-9052-11e9-89fd-33bb6de6138c.jpg)

**App information (please complete the following information):**
Canary version (7.1.1-canary08)

See screenshots of the response internally.

**Comment by Vladislav4er** [comment] 2019-06-15 07:56
I reproduce this case using GET https://www.rambler.ru/location/current request. (watch attached file)
![reproduce](https://user-images.githubusercontent.com/30718334/59548729-23afd580-8f5c-11e9-8dc6-b94eaee540bb.jpg)

**Comment by kamalaknn** [comment] 2019-06-17 04:33
Hey @Vladislav4er 

Thanks for trying out the Canary channel and reporting this issue. Also thanks for sharing the endpoint. We are able to replicate this issue from our side. We will update this thread once the fix is ready.

**Comment by kamalaknn** [comment] 2019-06-26 08:16
@Vladislav4er 

We've pushed a fix for this on `7.3.0-canary04`. Can you update your app and confirm if this fixes your issue?

**Comment by kamalaknn** [comment] 2019-06-28 06:40
@Vladislav4er I've tested the endpoint you have shared and a few others. This issue is fixed on the latest version of Canary.

I'm closing this issue now since this behaviour is observable only on Canary channel and is fixed on Canary channel now. 

Please let us know if you are still seeing this.

Thanks.

**Closed as completed by kamalaknn** 2019-06-28 06:40 UTC
Labels: product/runtime
