### ISSUE TITLE
gRPC Call - Error: duplicate name 'MetaData' in Type Error

### ISSUE THREAD

**Issue by ferdgonz** [a85/POSTMan-Chrome-Extension#12932] opened 2024-06-11 19:41 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The following error occurs when attempting to make gRPC call in Postman after upgrading to v11 (previously on v10).

Error Message:
Could not invoke method
Error: duplicate name 'MetaData' in Type Error

### Steps To Reproduce

1. Add gRPC request under an existing collection.
2. Import proto.
3. Set url.
4. Select method to invoke.
5. Add any meta data key values.
6. Construct message.
7. Click "Invoke".

Call is not made and the error: "Could not invoke method" "Error: duplicate name 'MetaData' in Type Error" appears.

### Operating System

Windows

### Postman Version

11.1.14

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

This error does not occur in version 10.
All existing gRPC requests across many collections are throwing the same error without having changed any of the requests or collections.

**Comment by appurva21** [comment] 2024-06-12 05:13
Hey @ferdgonz! Could you please share a scaled-down proto to help us recreate this issue on our end and expedite the fix?

**Comment by ferdgonz** [comment] 2024-06-14 14:08
Thanks for asking for that, @appurva21. It seems the issue is when using map in the proto file. 
I attached two proto files (had to convert to txt to upload):
[demo.txt](https://github.com/user-attachments/files/15839127/demo.txt) - Works
[demo_2.txt](https://github.com/user-attachments/files/15839128/demo_2.txt) - This one has a map in the definition and throws the error in question.

**Comment by rosibaj** [comment] 2024-06-18 17:55
Also facing this; any resolution or workaround?

**Comment by ferdgonz** [comment] 2024-06-19 17:24
@rosibaj you can downgrade to v10 (10.24.26) for the moment. 
Just note that postman automatically updates you unless you turn it off. So make sure to turn it off when you downgrade.

**Comment by saurabhateveri** [comment] 2024-06-19 19:51
I am also facing this. How to downgrade? I can't find the old Windows version to download from the portal.

**Comment by ferdgonz** [comment] 2024-06-19 19:58
@saurabhateveri I don't see previous versions in their site but you can use chocolatey. https://community.chocolatey.org/packages/postman/10.24.16

**Comment by appurva21** [comment] 2024-06-20 06:00
Hey everyone! We have identified the root cause and are working on a fix. In the meantime, to unblock, I have disabled the recent changes that led to it. Re-opening the gRPC request tab should fix this for now.

**Comment by appurva21** [comment] 2024-08-14 13:57
Hey folks! We have rolled out a fix for this with the latest version of Postman (v11.8.0). Please restart the app to get the update.

**Closed as completed by appurva21** 2024-08-14 13:57 UTC
Labels: bug, platform/windows, protocol/grpc, product/api-client
