### ISSUE TITLE
System dark mode

### ISSUE THREAD

**Issue by imclint21** [a85/POSTMan-Chrome-Extension#10095] opened 2021-07-03 06:54 UTC
Hey,

Why you don't integrate system theme like many apps now, if system is in dark mode app switch to dark mode and so on

Thank you

**Comment by DannyDainton** [comment] 2021-07-05 10:34
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/8075

**Closed as completed by DannyDainton** 2021-07-05 10:34 UTC
Labels: duplicate
