### ISSUE TITLE
GraphQL Introspection

### ISSUE THREAD

**Issue by graphei** [a85/POSTMan-Chrome-Extension#10416] opened 2021-11-01 21:54 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

I have to also use Insomnia to get GraphQL Schema Documentation.

### Describe the solution you'd like

Add Introspection schema fetching.

**Comment by giridharvc7** [comment] 2022-01-10 19:23
Duplicate of #6719

**Closed as completed by giridharvc7** 2022-01-10 19:23 UTC
Labels: feature, product/runtime, protocol/graphql
