### ISSUE TITLE
Unable to SSO into Postman native application with iDP credentials

### ISSUE THREAD

**Issue by aamir-ahmed** [a85/POSTMan-Chrome-Extension#7001] opened 2019-07-26 07:11 UTC
**Describe the bug**
User see's a generic "Something went wrong" error when they try to log into the Postman native application with the iDP credentials for SSO

**To Reproduce**
1. Click on "Sign in here" next to "Enterprise user?" on the main login page
2. Enter the Team Domain and submit
3. Select the iDP Provider, enter your credentials and submit
4. See "Something went wrong" error 

**Expected behavior**
1. If you have not completed sign on using iDP credentials previously, you will be redirected to the main login page to link your Postman credentials to your iDP
2. If you have completed sign on using iDP credentials previously, you will be signed into the Postman native application.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - Native App
 - Postman 7.3.0 and Postman 7.3.4
 - OS: Both Windows and Mac

**Additional context**

**Comment by saurabhpatel2108** [comment] 2019-07-26 08:27
Adding to above, the issue only happens with the Postman Desktop App.
The SSO works fine over web(or when we access it from IDP over web)
[postman_logs.zip](https://github.com/postmanlabs/postman-app-support/files/3434871/postman_logs.zip)

**Comment by numaanashraf** [comment] 2019-07-26 12:53
Thanks for reporting this. This is a confirmed regression in Postman v7.3 apps and we are working towards getting this fixed on our stable channel as soon as possible. We have released a fix on our canary channel (https://www.getpostman.com/downloads/canary) and we advise teams which are impacted by this issue to use the Postman Canary apps till this issue is available on our stable channel.

Root cause summary:
Postman supports SSO login via an in-built browser that is shipped with the app. Typical SSO login involves multiple redirects and navigations during the course of the login flow and we monitor these navigations and redirects to detect a successful completion or failure in the login flow. In Postman v7.3, we had updated the internal browser we use, and it seems this browser is firing a navigation failure event during the course of the SSO flow, even though there are no actual failures. Postman interprets this as a login failure and stops the login flow. We have an interim fix ready which involves detecting and ignoring this erroneous failure event, and have released this to our canary apps and are doing further testing before releasing this fix to our stable user base.

Related issue:
https://github.com/electron/electron/issues/14004

**Comment by saurabhpatel2108** [comment] 2019-07-26 15:06
Adding Paul.

Paul,
Below is for your information.

Regards,
Saurabh

Sent from phone, please ignore typo errors.



From: Numaan Ashraf
Sent: Friday, July 26, 18:24
Subject: [EXT] Re: [postmanlabs/postman-app-support] Unable to SSO into Postman native application with iDP credentials (#7001)
To: postmanlabs/postman-app-support
Cc: Saurabh Patel, Comment


Thanks for reporting this. This is a confirmed regression in Postman v7.3 apps and we are working towards getting this fixed on our stable channel as soon as possible. We have released a fix on our canary channel (https://www.getpostman.com/downloads/canary<https://clicktime.symantec.com/3AoGc85i3Ns65q8DqZCWpwn7Vc?u=https%3A%2F%2Fwww.getpostman.com%2Fdownloads%2Fcanary>) and we advise teams which are impacted by this issue to use the Postman Canary apps till this issue is available on our stable channel.
Root cause summary:
Postman supports SSO login via an in-built browser that is shipped with the app. Typical SSO login involves multiple redirects and navigations during the course of the login flow and we monitor these navigations and redirects to detect a successful completion or failure in the login flow. In Postman v7.3, we had updated the internal browser we use, and it seems this browser is firing a navigation failure event during the course of the SSO flow, even though there are no actual failures. Postman interprets this as a login failure and stops the login flow. We have an interim fix ready which involves detecting and ignoring this erroneous failure event, and have released this to our canary apps and are doing further testing before releasing this fix to our stable user base.
Related issue:
electron/electron#14004<https://clicktime.symantec.com/3Rh3nHK7kiBZc4DvZy2vwoS7Vc?u=https%3A%2F%2Fgithub.com%2Felectron%2Felectron%2Fissues%2F14004>

**Comment by saurabhpatel2108** [comment] 2019-07-26 20:08
it seems using the canary also gives issues. The app hangs at the attached screenshot. Attaching logs as well
[logs.zip](https://github.com/postmanlabs/postman-app-support/files/3437263/logs.zip)
<img width="1281" alt="postman_canary" src="https://user-images.githubusercontent.com/53333947/61978554-28fa4880-b00f-11e9-8770-16e88c1cec01.png">

**Comment by harryi3t** [comment] 2019-08-01 05:48
@aamir-ahmed @saurabhpatel2108 
We have pushed a fix for this on the stable channel in the version v7.3.5
Please let us know if you are still facing the issue.

**Closed as completed by harryi3t** 2019-08-01 05:48 UTC
Labels: bug, product/login
