### ISSUE TITLE
Feature request: Collection Environment

### ISSUE THREAD

**Issue by GuryYu** [a85/POSTMan-Chrome-Extension#3907] opened 2017-12-05 10:41 UTC
In the case of a very large number of collections, each with its own distinct Environment, the existing Environment mechanism is particularly cumbersome to choose from. In the 5.4.1 release, a new Collection variable functionality was added. Extend this functionality to "Collection Environment." Provide a different Environment for each Collection, and quickly switch between them.

**Comment by prashantagarwal** [comment] 2017-12-05 13:53
@GuryYu Thanks for suggesting this feature.

**Comment by curtisgibby** [comment] 2017-12-05 16:53
Dupe of #213 (and therefore #3205)

**Comment by ericnewton76** [comment] 2018-01-07 01:04
Agreed.  I had suggested this a long time ago as well.

Its Collections that need specific Environments.  Usually my collections need one of several different baseUrls: dev/stage/production to run some smoke tests against.

Still hoping to see this feature soon.

**Comment by a85** [comment] 2018-02-28 20:04
Workspaces might help a bit here: https://www.getpostman.com/docs/postman/workspaces/intro_to_workspaces

**Comment by curtisgibby** [comment] 2018-03-01 19:51
Yes, Workspaces is exactly how I expected something like this to be implemented. Thanks for pointing out that it has now been released!

**Closed as completed** 2018-04-03 17:58 UTC
Labels: feature
