### ISSUE TITLE
Code Generation for Curl Command doesn't work in [Postman for Chrome Version 4.10.5 OS X / x86-64 Chrome 56.0.2924.87]

### ISSUE THREAD

**Issue by ravichauhan03** [a85/POSTMan-Chrome-Extension#2883] opened 2017-04-03 05:19 UTC
Below are the Postman plugin details :

Postman for Chrome
Version 4.10.5
OS X / x86-64
Chrome 56.0.2924.87

**Comment by SamvelRaja** [comment] 2017-04-03 06:09
@ravichauhan03 Could you provide me more specific information on the issue you are facing?

**Comment by ravichauhan03** [comment] 2017-04-03 06:37
@SamvelRaja : Please find the details inline:
Do any post call using postman, it gets successful if the details are correct. But when you convert that http call to a curl command and use that command instead for getting the response from shell, you will not get any response against that. 

Let me know in-case any other details are required. We have Authorization headers and some more header keys but cannot share that details.

**Comment by vegetableman** [comment] 2017-04-03 07:12
@ravichauhan03 Chiming in behalf of @SamvelRaja here. Could you share a screenshot or the generated cURL code with the private details redacted?, so that we could help you better, as we are not able to reproduce the issue.

**Comment by pdeak** [comment] 2017-04-04 08:24
I think I might be having the same issue as @ravichauhan03, so just adding my notes. Since 4.10.5 the cURL export -> import workflow seems to have completely broken. See screenshot of a basic post request:

https://i.imgur.com/7JwPVl6.png

After selecting Code -> cURL -> Copy to clipboard, and then re-importing it via Import -> Paste Raw Text, the request is completely broken. The URL is missing, and the payload is corrupted:

https://i.imgur.com/gaRMqYe.png

In prior versions, exporting and importing using cURL was a reliable way to pass requests around, and the imported requests were always exactly what was exported.

**Comment by barryku** [comment] 2017-04-04 19:53
I am also having issues with the curl command it generates.  The issue with mine is that postman ignores parameters with the same name, and simply takes the last one.  It was working for me last week that all parameters got appended properly, so I am guessing something got changes in the new version.  The rest API I use takes multi-values as multiple parameters with the same name.
![postman](https://cloud.githubusercontent.com/assets/438686/24675889/a2fa92fc-1935-11e7-9822-32dd22a1440a.png)

**Comment by ravichauhan03** [comment] 2017-04-06 04:23
Any update on this ??

**Comment by SamvelRaja** [comment] 2017-04-10 11:03
@ravichauhan03 @pdeak @barryku The issue has been fixed in our latest 4.10.7 update, can you guys check the same from your end. 
Closing this issue now. Feel free to create new or reopen the same issue if problem still persists.

**Closed as completed by SamvelRaja** 2017-04-10 11:03 UTC

**Comment by pdeak** [comment] 2017-04-10 12:24
Yes, looks good to me, thanks.
