### ISSUE TITLE
about font...

### ISSUE THREAD

**Issue by SaddestMoon** [a85/POSTMan-Chrome-Extension#4152] opened 2018-02-07 03:49 UTC
## App Details:
Version 5.4.1
win32 10.0.15063 / x64
```

## Issue Report:
emmmm .
does the postman can change it's font? 
sometimes,it's better to use monospaced fonts to edit code  and show/format the test results.

for example .
the test result in postman :
![image](https://user-images.githubusercontent.com/8498603/35897543-a680b2b6-0bfc-11e8-88e6-51075639ce4e.png)

in IDEA(use monospaced font)

![image](https://user-images.githubusercontent.com/8498603/35897462-480efd5a-0bfc-11e8-9221-b8ad02b4ab45.png)

**Comment by sivcan** [comment] 2018-03-16 20:39
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4142

**Closed as completed by sivcan** 2018-03-16 20:39 UTC
