### ISSUE TITLE
Persist state of OAUTH2 dialog fields along with retrieved token

### ISSUE THREAD

**Issue by gareth-a-jones** [a85/POSTMan-Chrome-Extension#3337] opened 2017-08-02 04:49 UTC
## App Details:
Postman for Windows
Version 5.1.0
win32 10.0.15063 / x64```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```


I'd like to be able to more easily manage a set of OAUTH2 token providers and resources.
Currently the OAUTH2 dialog only remembers the last used settings.
I'd like it to persist either a named list of auth presets or to persist the setting used when retrieving a token, so when coming back to that token, after refresh has expired, a new one can be regenerated using the previous preset values.

**Comment by sdnts** [comment] 2017-08-02 12:17
Hi @garethj-msft, I'm marking this as a feature request, thanks for this!

**Comment by gareth-a-jones** [comment] 2017-09-18 22:05
Seems like it and its compatriot should have the auth label too?

**Comment by var23rav** [comment] 2019-06-20 05:00
@madebysid  Any update on this feature.

**Comment by vikiCoder** [comment] 2019-07-31 08:04
Closing this as a duplicate of the following issue:
https://github.com/postmanlabs/postman-app-support/issues/4636

**Closed as completed by vikiCoder** 2019-07-31 08:04 UTC
Labels: feature, Auth, OAuth2, duplicate
