### ISSUE TITLE
Unable to update new email address, after logging out and in, the old email presist

### ISSUE THREAD

**Issue by Aaron1515** [a85/POSTMan-Chrome-Extension#8434] opened 2020-05-04 20:22 UTC
**Describe the bug**
Unable to update new email address.
![Screen_Shot_2020-05-04_at_1_14_29_PM](https://user-images.githubusercontent.com/15719821/81009792-216f9780-8e0a-11ea-85f2-6d046914e62a.png)

**To Reproduce**
1. Go to 'https://blue-shadow-4014.postman.co/settings/me'
2.Update email address.
3. Visit mailbox to verify the new email address.
4. Click on the verified email link
5. Logout of postman
6. Login to Postman.
7. Go back to 'https://blue-shadow-4014.postman.co/settings/me"
8. Old email still shows. the email didn't get updated.

**Expected behavior**
After going through all the steps, after logging out and logging back in. The new email address persist.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
![Screen_Shot_2020-05-04_at_1_14_29_PM](https://user-images.githubusercontent.com/15719821/81009811-29c7d280-8e0a-11ea-9fb6-c284604c5913.png)

**Additional context**

**Comment by preethammavin** [comment] 2020-05-10 09:45
@Aaron1515 The issue was a transient issue, which should be fixed now. Do let me know if it isn't so that we can take a deeper look.

**Closed as completed by preethammavin** 2020-05-10 09:45 UTC

**Comment by AnupKTarafder** [comment] 2022-11-23 16:50
I am facing this issue right now.
userid: cloudy-water-934240

**Comment by dimitris-zournatsidis** [comment] 2022-12-07 16:29
Same here... A toast message appears saying that the email is updated, but after a page refresh the email is still the old one

**Comment by pankajkumar005** [comment] 2022-12-08 17:24
@dimitris-zournatsidis @AnupKTarafder - Thanks for reporting the issue. 

We have a known bug, due to which the status is shown as a success even though the email update failed due to some validation failure. The fix for the bug will be available in upcoming versions.

Meanwhile, could you please raise a request [here](https://support.postman.com/hc/en-us/requests/new) or reach out to us directly at [help@postman.com](mailto:help@postman.com) with your account details, so that we may check the cause of email update failure? 
[In the request, please provide information about (1) Your current email and (2) The email you were trying to update to]
