### ISSUE TITLE
Proxies configurable per collection/folder/request

### ISSUE THREAD

**Issue by teunis90** [a85/POSTMan-Chrome-Extension#7285] opened 2019-09-09 09:11 UTC
**Is your feature request related to a problem? Please describe.**
I work for multiple projects, for some projects I have to use proxies because my own IP-address is not whitelisted. Therefore I have to keep switching my proxy settings.

**Describe the solution you'd like**
It would be handy if we could set proxy settings per collection/folder/request as we can do with pre-request scripts. The more specific setting would take precedence.

This would also allow overriding the use of a proxy (disabling).

**Describe alternatives you've considered**
In the current situation, it's often faster to copy the curl call from Postman and execute it on the proxy host via SSH. Unfortunately not all my colleagues have this option.

**Additional context**
This feature would be an alternative and more powerful implementation of:
- #3942 
- #6380
- #6484

**Comment by teunis90** [comment] 2019-09-09 16:41
The feature would be even more powerful when combined with #4760.

**Comment by codenirvana** [comment] 2019-09-18 08:27
@teunis90 Thanks for the feature request. I understand your issue with switching proxy settings every time.

To fix similar issues with core request sending flows we recently (v7.7) added new `Settings` tab for every request and soon adding support for Collection and Folder level settings/configurations as well.

We are currently working on fixing a few of the issues with proxies which you already mentioned and will take this up soon (no eta just yet).

Closing as duplicate of #4739

Please follow the above thread for more updates on this feature!

**Closed as completed by codenirvana** 2019-09-18 08:27 UTC
Labels: feature, Proxy, product/runtime

**Comment by teunis90** [comment] 2019-09-18 09:42
@codenirvana Thanks for your update. Totally missed #4739 in my research of existing issues.
