### ISSUE TITLE
Cmd+Enter unreliable on Mac app

### ISSUE THREAD

**Issue by Znarkus** [a85/POSTMan-Chrome-Extension#2075] opened 2016-05-20 08:05 UTC
Hi! Cmd+Enter on the Mac app doesn't work reliably. When it doesn't work it either resets the URL to previous URL, or sends double requests. Restarting the app temporarily resolves this issue.
1. Postman Version: 4.2.0
2. App (Chrome app or Mac app): Mac app
3. OS details: 10.11.5 (15F34)
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Last week
6. Expected behaviour:
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Nothing special
8. Screenshots (if applicable) -

**Comment by abhijitkane** [comment] 2016-05-20 08:06
Right. We'll be pushing a fix for this in the next release.
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/2074

**Closed as completed by abhijitkane** 2016-05-20 08:06 UTC
