### ISSUE TITLE
Forcing Postman to choose specific certificate

### ISSUE THREAD

**Issue by FredrikTamm** [a85/POSTMan-Chrome-Extension#1993] opened 2016-04-14 08:04 UTC
I have several client certificates installed and want to be able to choose the appropriate certificate for my specific api-request. Is there a way to do this? I am using the MacApp.

**Comment by abhijitkane** [comment] 2016-04-26 01:24
@FredrikTamm Not that we know of. We're looking at an easy way to manage certificates - will try and update this thread soon.

**Comment by FredrikTamm** [comment] 2016-08-24 07:40
Looks like the new release (I am on 4.6.2) allows me to add certificates under Preferences in the Postman app. But how do I choose which certificate to use with my request, or is there always a default certificate for each host? Is there any documentation where I can read about the changes in handling certificates?

**Comment by sdnts** [comment] 2016-08-24 07:51
When you add a certificate through the Preferences tab, it is registered to be used whenever a request to the specified domain (host) is made.

When you make a request to the said domain, Postman sends the certificate along with the request, if the server requires it. (This acts like the default certificate for that host).

Correct me if this is not your use case.

We'll try and add documentation around this as soon as possible.

**Comment by FredrikTamm** [comment] 2016-08-24 08:48
It doesn´t work for me, but not sure what is wrong as there is no error-handling other than a 403-response from the server.

**Comment by sdnts** [comment] 2016-08-24 08:52
Can you open up your Postman Console (View > Show Postman Console), resend the request and check if the certificate was actually sent? (You'll have to expand the request  you just made in the Console)

**Comment by FredrikTamm** [comment] 2016-08-24 08:57
No, it isn´t logged as sent.

**Comment by sdnts** [comment] 2016-08-27 05:33
I've been unable to reproduce this at our end.
I set up Node and NginX servers to request certificates from clients, and Postman sends the corresponding certificate correctly.
Could you send us an email at help@getpostman.com with details about your setup (with private fields redacted)? That would help us debug the issue and get you a solution.

**Comment by sdnts** [comment] 2017-01-03 12:24
@FredrikTamm Closing this. Feel free to reopen if this isn't resolved yet.

**Closed as completed by sdnts** 2017-01-03 12:24 UTC
