### ISSUE TITLE
你好，postman支持扩展java写的私有协议吗？

### ISSUE THREAD

**Issue by jianglgit** [a85/POSTMan-Chrome-Extension#7571] opened 2019-11-01 01:38 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kamalaknn** [comment] 2019-11-05 04:04
Duplicate of #7572

**Closed as completed by kamalaknn** 2019-11-05 04:04 UTC
