### ISSUE TITLE
Postman is changing the request method under the hood

### ISSUE THREAD

**Issue by shibasisp** [a85/POSTMan-Chrome-Extension#9695] opened 2021-03-08 06:10 UTC
**Describe the Issue**
Postman is changing the request method from PUT to GET under the hood for http request.

**Steps to Reproduce**

- I sent a request from postman as a PUT method. But it reached the server as a GET method.
- I replaced the http with https in the above case and it worked fine in postman.
- I extracted the curl from postman and hit it from terminal and worked fine in both the cases(http and https).
- I tried the same with insomnia, worked fine for both the cases.

**Version used**: 8.0.5
**OS**: Mac OS Catalina

**Comment by codenirvana** [comment] 2021-03-08 06:30
@shibasisp You can turn the `Follow original HTTP Method` request setting ON to redirect with the original HTTP method.

![Screenshot 2021-03-08 at 11 55 05 AM](https://user-images.githubusercontent.com/4865836/110283115-90f37c00-8005-11eb-8c5d-e8ea779a19e3.png)

Duplicate of #4001

**Closed as completed by codenirvana** 2021-03-08 06:30 UTC
