### ISSUE TITLE
Folder level pre-request scripts not showing up unless you click on the body

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#4893] opened 2018-07-26 12:07 UTC
**Describe the bug**
If you have added any pre-request script for the folder in a collection, it will not show up when you edit the folder, You need to click on the editor/body to view the script placed in there.

**To Reproduce**
1. Edit any folder which has the pre-request script saved init
2. Go to the Pre-rescript script tab & you notice it being blank

**Expected behavior**
The saved script should appear there.

**Screenshots**
<img width="1054" alt="screen shot 2018-07-26 at 5 31 38 pm" src="https://user-images.githubusercontent.com/40994626/43261333-ee6cfa30-90f9-11e8-8c18-5aacd6791733.png">

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version :  6.1.4]
 - OS: e.g. macOS High Sierra 10.13.4

**Comment by prashantagarwal** [comment] 2018-07-26 12:20
Duplicate of #4755

**Closed as completed by prashantagarwal** 2018-07-26 12:20 UTC
