### ISSUE TITLE
Global variables are not saved after Collection runner (Keep variable values is checked)

### ISSUE THREAD

**Issue by andrewVolodko** [a85/POSTMan-Chrome-Extension#8820] opened 2020-07-23 12:28 UTC
Global variables are not saved after Collection runner (Keep variable values is checked)

**Steps to reproduce the behavior**
1. Create any script in the Tests section of any request that sets global variable.
2. Run the request in the Collection runner.
3. Look at the Global variables list.

**Expected behavior**
Global variable from step 1 should be set in Globals.

**Actual behavior**
Global variable is NOT set if the request was launched from the Collection runner.

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - Version 7.29.0
 - OS - OS X 19.6.0 / x64, Mac OS Catalina (10.15.6)

**Comment by saswatds** [comment] 2020-07-23 13:18
Hi @andrewVolodko, I was able to reproduce this issue. Thanks a lot for reporting. We will get this fixed ASAP

**Comment by mohitranka** [comment] 2020-07-24 14:34
@andrewVolodko It has been fixed in the Postman app v 7.29.1 . Please update the app, and let us know if the issue persists.

**Closed as completed by mohitranka** 2020-07-24 14:34 UTC
Labels: bug, product/runtime

**Comment by robinhuang76** [comment] 2020-07-25 03:06
I updated to postman app v 7.29.1. The issue is still there. The global variables are not saved after collection runner.
