### ISSUE TITLE
Give Back The Vertical Scrollbar at the rightest side as ur .17 version

### ISSUE THREAD

**Issue by Garry14** [a85/POSTMan-Chrome-Extension#8952] opened 2020-08-20 06:57 UTC
**This useful scrollbar has been disappeared by you**
![Feedback POstman](https://user-images.githubusercontent.com/14907169/90726838-91882780-e2ec-11ea-8198-2fa12380c7e9.jpg)
So that when I need to see my response from my code, I need to scroll down the bottom part and I just have 1/4 of my screen to view it.. 
It makes me headache, I swear.! 

**This is your App v7.17 and there is scrollbar at the rightest of its side**
![Postman v17](https://user-images.githubusercontent.com/14907169/90726652-4241f700-e2ec-11ea-9bb8-8143d9f64e92.jpg)
This makes me easier when I need to see my preview response of my code with my entire screen b'coz I can scroll it down.. 
![Postman v17 2](https://user-images.githubusercontent.com/14907169/90727185-0e1b0600-e2ed-11ea-9a89-826f32065701.jpg)

Thanks before

**Comment by DannyDainton** [comment] 2020-08-20 08:33
Duplicate of #8789

**Closed as completed by DannyDainton** 2020-08-20 08:33 UTC
Labels: duplicate
