### ISSUE TITLE
Support validation of response against Swagger/OpenAPI spec

### ISSUE THREAD

**Issue by mattlock83** [a85/POSTMan-Chrome-Extension#6614] opened 2019-05-29 12:13 UTC
**Problem**
I want to validate that responses conform to the API swagger specification during my tests

**Proposed solution**
Integrate something like [swagger-model-validator](https://www.npmjs.com/package/swagger-model-validator) that let's you associate a swagger specification with a collection and validate a response against a swagger path and model

**Alternatives considered**
Currently I'm using a script that converts the swagger API specification to JsonSchema using [ytoj](https://www.npmjs.com/package/ytoj) then writes it to a collection variable in the collection file. I'm not very comfortable with having to modify the collection file outside of the Postman UI.

**Comment by vkaegis** [comment] 2019-06-03 08:18
@mattlock83 Thanks for writing in! This is something that is definitely in our sights. No ETA just yet, but will keep you updated.

**Comment by vdespa** [comment] 2019-11-01 08:53
It seems that currently there is no way to get the current schema (if one was defined) in the scripts.

**Comment by VicKetchup** [comment] 2019-11-18 14:53
A big +1 for this to be implemented. This is one of the most useful things Automation can do. 

Just like OP we are using a custom implementation for swagger 2.0 validations (loading external JS, obtaining swagger from our domain and specifying the definition in Pre-Request), however we are currently in discussions to move to OpenAPI 3, which our current setup doesn't support. 

I do want to add though, it would be great if multiple swaggers could be associated with one collection (we have new system relying on some info from calls from an old one, so their swaggers are separate) and ability to load swaggers from a domain using different Authentication methods.

**Comment by andrewshawcare** [comment] 2019-11-19 18:52
It would be great, in general, if you could access the API schema via `pm`, like:

```
pm.test("Response is a valid foo", () => {
  const responseJson = pm.response.json();
  const fooSchema = pm.schema.components.schemas.foo;
  pm.expect(tv4.validate(responseJson, fooSchema)).to.be.true;
});
```

**Comment by mennodehaas** [comment] 2019-12-04 15:01
For me, the OAS import functionality misses a lot of functionality.

1. The application assumes that the spec is finished on day 1. Whenever changes are performed, new collections have to be generated.
2. For testing purposes, it is not possible to validate agains an OAS spec (only json models).
3. It is not possible to see test coverage (which paths/response codes have been tested)

**Comment by iDiogenes** [comment] 2019-12-31 21:22
What @andrewshawcare is proposing is the real win. The schema as defined in the APIs tab should be directly accessible in the postman tests to ensure the schema is being followed. Once the schema has to be defined in multiple places maintenance becomes a real problem.

**Comment by sankalp0o** [comment] 2020-01-02 07:45
Thanks for the feedback everyone! We are currently working on validating sent (history) requests as well as collections against the schema defined in the API tab. I'll update this thread when we have it out in production. 

For us to design this better, what are the kind of issues you are looking to find from a validation like this? This will inform us on what to prioritise.

**Comment by VicKetchup** [comment] 2020-01-02 10:03
@sankalp0o Hopefully this will help with the design, we use https://www.jsonschemavalidator.net/ even after using tv4.validateMultiple results, as it is missing a crucial bit of information - path at which validation has failed.

**Comment by mennodehaas** [comment] 2020-01-02 11:52
I am using [Stoplight Studio](https://stoplight.io/studio/) to create the OAS and JSON models as writing the OAS by hand is cumbersome and error prone.

**Comment by vdespa** [comment] 2020-01-07 16:54
@VicKetchup consider using the ajv validator. tv4 is really not very good.

**Comment by VicKetchup** [comment] 2020-01-07 17:29
> @VicKetchup consider using the ajv validator. tv4 is really not very good.

Didn't realise this was added! Thanks for pointing this out :)

**Comment by sankalp0o** [comment] 2020-01-09 16:01
Hey @mattlock83 @VicKetchup @vdespa @andrewshawcare ! We just released a feature which does validation of collections and requests which are linked to a OAS3.0 spec through an "API". Will be updating this thread with a link to docs soon, but here are the rough steps which you can follow.

1. Create a new "API" in Postman
2. Add your OAS3 specs to the API version
3. Link your collection to the API. This can be done by going to the "Test" tab and adding a Test Suite and selecting your collection. Feel free to instead add the collection as an integration test or documentation or anything else. You can also add your mock servers and monitors in a similar way.
4. As soon as you add it, we'll try to validate the collection (all the requests and examples) against the spec. You'll be able to see the results against the collection name (in the Develop, Test and Observe tabs in the API).
5. If there are issues found, you'd be able to see the details.
6. Try running any request in this collection. When you do, you'll be notified (near the title of the request tab) if there are any mismatches found in the request/response and the spec.

Would love to hear if this can be useful to you or not. We're continuously improving the validation logic itself and any feedback there would be appreciated!

**Comment by andrewshawcare** [comment] 2020-01-09 20:21
This is great. Really appreciate the changes. I'm currently unable to see the actual validation messages, however. When I enter the following specification:

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "Sample API",
    "description": "Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.",
    "version": "0.1.9"
  },
  "servers": [
    {
      "url": "http://api.example.com/v1",
      "description": "Optional server description, e.g. Main (production) server"
    },
    {
      "url": "http://staging-api.example.com",
      "description": "Optional server description, e.g. Internal staging server for testing"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "summary": "Returns a list of users.",
        "description": "Optional extended description in CommonMark or HTML.",
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

I add an empty collection and see:

![Screen Shot 2020-01-09 at 3 16 22 PM](https://user-images.githubusercontent.com/54861/72101866-b0085800-32f3-11ea-96b8-aa58f8aeb494.png)

When I click on the, "View details" link, I see:

![Screen Shot 2020-01-09 at 3 16 44 PM](https://user-images.githubusercontent.com/54861/72101905-bf87a100-32f3-11ea-8d9b-6af5da608750.png)

**Comment by sankalp0o** [comment] 2020-01-11 04:04
@andrewshawcare An empty collection will give out issues. We will work on a better empty state. Try having an actual request in there to see the validation happening.

**Comment by m4nu56** [comment] 2020-01-29 22:12
@sankalp0o this sounds fantastic will try it tomorrow. Will it be runnable via Newman too ?

**Comment by sankalp0o** [comment] 2020-01-30 05:49
@m4nu56 Not as of yet. If it were, how would you want to use it?

**Comment by m4nu56** [comment] 2020-01-30 07:17
I followed your instructions to create the API but nothing seem to be happening. 
![Screenshot from 2020-01-30 08-12-47](https://user-images.githubusercontent.com/330472/73428017-59150200-4338-11ea-8548-ae9ea95d628f.png)
The collection I added as a Test Suite have the same endpoints as defined in the open api 3.0 spec I added to the Define tab: 
![Screenshot from 2020-01-30 08-14-15](https://user-images.githubusercontent.com/330472/73428093-882b7380-4338-11ea-8abd-a801ffe1ce01.png)

How should I "launch" the validation ? I tried running the collection directly but nothing appeared in the API section. 
I must be missing something but I don't see what. 

And to respond to your question yes I would be interested in being able to validate my endpoints by the openapi specs with newman. 
What I'm trying to achieve is to automate the validation of my endpoints based on the swagger doc generated by the api. To validate documentation it's not out of sync with implementation.

**Comment by arlemi** [comment] 2020-01-30 08:57
@m4nu56 The validation is done automatically and if any issues are found it'll show next to the collection in the `Develop` or `Test` tabs like this:
 ![https://user-images.githubusercontent.com/5029719/72075557-eb068d80-32eb-11ea-8845-96b1afa3ed8e.gif](https://user-images.githubusercontent.com/5029719/72075557-eb068d80-32eb-11ea-8845-96b1afa3ed8e.gif)

The full documentation for this feature is available here: https://learning.getpostman.com/docs/postman/design-and-develop-apis/validating-elements-against-schema/

Let us know if you have more questions!

**Comment by iDiogenes** [comment] 2020-02-07 18:45
@arlemi Thanks for this feature, you guys are heading in the right direction. I found what could be a bug, so please let me know how you would like me to proceed.

When using the OAS3 schema to generate a collection the values in the body don't match the example, rather they just say the "type". For example,



```json 
"post": {
        "tags": [
          "Users"
        ],
        "summary": "Create User",
        "description": "Allows for a new user to be created.",
        "operationId": "CreateUser",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUserRequest"
              },
              "example": {
                "data": {
                  "type": "users",
                  "attributes": {
                    "deploymentId": "{{deploymentId}}",
                    "firstName": "John",
                    "lastName": "Doe",
                    "email": "john.doe@soda.io"
                  }
                }
              }
            }
          },
          "required": true,
          "x-send-file-in-body": false
        }
```

In postman it yields the following in the Body for the request.

```json
{
    "data": {
        "type": "<string>",
        "attributes": {
            "deploymentId": "<string>",
            "firstName": "<string>",
            "lastName": "<string>",
            "email": "<string>"
        }
    }
}
```

**Comment by iDiogenes** [comment] 2020-02-07 21:37
@arlemi Another apparent bug is validation fails when doing a `GET` to `/`.  The error is `Unable to validate. No matching path found in schema`. If I change the path to be `/1` in the schema and the Postman collection the validation passes.

**Comment by arlemi** [comment] 2020-02-10 10:16
@iDiogenes Thanks for your feedback! We're tracking the first issue you've raised in #7397. I've raised the second one with our team, they're looking into it. :) 

@m4nu56 If you are still not seeing the validation, make sure to update your app to the latest version.

**Comment by VicKetchup** [comment] 2020-02-19 13:51
Using the steps provided, got the validation working, majority of the requests are being validating against wrong paths or can't find the path at all:
![image](https://user-images.githubusercontent.com/43671684/74840161-695c4380-531e-11ea-9f15-97b29172800e.png)
For the requests that correct path was found, the validation on response has no details on where the issue is (clicking on the text just closes the validation window):
![image](https://user-images.githubusercontent.com/43671684/74840278-9e689600-531e-11ea-90e1-4eab5cc39209.png)

Really glad to see that steps have been taken to get this added and hope that these issues will be ironed out soon :)

**Comment by iDiogenes** [comment] 2020-02-20 23:26
> @iDiogenes Thanks for your feedback! We're tracking the first issue you've raised in #7397. I've raised the second one with our team, they're looking into it. :)

@arlemi - thanks I will track the progress on the above. I also found what appears to be another issue. Please let me know if you guys are able to reproduce. In my request example and schema I have a bool, but it is saying it is only valid as a when I change the schema to be a string and not a bool even though I am returning t/f.

**Comment by ahmetgeymen** [comment] 2020-02-21 18:01
Even using the example value generated in on https://editor.swagger.io with the same spec on both postman and the online editor, postman warns me that the response is not validating against the API.

**Comment by iDiogenes** [comment] 2020-02-21 18:05
@ahmetgeymen - What example value are you talking about? Are you seeing the same issue with the bool or are you referring to something else?

**Comment by ahmetgeymen** [comment] 2020-02-24 08:42
@iDiogenes 
After reading the issue title and viewing the shared screenshots, I think I have the similar issue with the validation of Postman.

Here the example swagger ui generates over openapi spec (yaml)

```
{
  "directory": [
    {
      "section": "string",
      "contacts": [
        {
          "title": "string",
          "address": "string",
          "phones": [
            "string"
          ],
          "fax": "string",
          "email": "string",
          "website": "string"
        }
      ],
      "imageURL": "string"
    }
  ]
}
```

But even I copy the example exactly and use as collection request example in Postman, it didn't validate. May be this is connected with this issue #8098 

I think validator of the Postman runs on sample values of the collection examples. It doesn't run after response has been captured in my opinion. Thus it doesn't validate with dynamic variables if it expects integer values but only see **$randomInt** instead. (I might be wrong because I have validation issues with responses contain both $randomInt and arrays)

**Comment by VicKetchup** [comment] 2020-03-11 14:07
@sankalp0o Wanted to bring up the discussion of being able to run these validations as tests, which I also think would help with @m4nu56 's question:

> @sankalp0o this sounds fantastic will try it tomorrow. Will it be runnable via Newman too ?

Maybe some functions like pm.response.isValidAgainstSpec(), pm.response.getValidationErrors().

**Comment by andrewshawcare** [comment] 2020-03-11 18:51
Using it in tests is the thing I'd like the most, especially with Newman so I can use it in CI and have the build break if validations are failing.

**Comment by rishabh7g** [comment] 2020-04-04 09:45
Wonderful feature to validate schema. Is it possible to use this in jar or java code?

My scenario is, 
1. Given Swagger YAML file with 3.0
2. TestNg class, which will validate response body schema
       a. Send request using io.RestAssured api and get response 
       b. validate response body schema for given path and status

**Comment by sankalp0o** [comment] 2020-04-29 13:44
@ahmetgeymen you are correct, validations on a collection are run on the sample example stored in the collection. If you run individual requests in this collection though, the validation should run on the response received.

---

@VicKetchup we are both improving the matching algorithm as well as considering providing a way so that you can set them manually. I'll update you when these improvements are out.

---

@VicKetchup  @andrewshawcare @m4nu56 We are focusing on improving the validation results before exposing the results to other places like Newman. I'm very interested in how you see this working - 

1. We generate tests based on the OpenAPI spec and you run this collection in Newman.
2. We provide a way to reference the OpenAPI spec when a collection is run in Newman. Tests are generated on the fly when the collection is being run.

In the first approach, if the API changes, you would have to update the collection since older generated tests would break. In the second approach, tests would be dynamic but you'd need to always maintain a reference to the specification.

Based on your use case, which direction would you prefer? This would help us design a better experience.

**Comment by VicKetchup** [comment] 2020-04-29 14:10
@sankalp0o Definitely the second option for us, as that sounds similar to the way we implemented our checks. Maybe this part of our documentation will clarify our use case:
![image](https://user-images.githubusercontent.com/43671684/80605792-6f138b00-8a2b-11ea-88df-019b5667aac9.png)

**Comment by arlemi** [comment] 2020-08-12 09:30
I'm closing this issue as the original request was implemented. I've created a different one specific to being able to run the validation as a test, we'll be tracking it in #8920.

**Closed as completed by arlemi** 2020-08-12 09:30 UTC
Labels: feature, product/runtime
