### ISSUE TITLE
Endpoint returning images times out

### ISSUE THREAD

**Issue by g0rd** [a85/POSTMan-Chrome-Extension#5531] opened 2018-11-15 20:40 UTC
**Describe the bug**
We have an endpoint that returns an image and every time I run it it returns a socket timeout error. I am suspecting that postman is currently not capable of handling such requests. Hence, I am posting this in a feature request. 

If you think this is bug and you require more information I will be happy to share

**Comment by numaanashraf** [comment] 2018-11-16 19:41
@g0rd Is there a publicly accessible endpoint we could try to replicate this? if not, could you provide a screenshot of Postman Console (Menu > View > Show Postman Console) with this error?

**Comment by g0rd** [comment] 2018-11-19 15:23
![image](https://user-images.githubusercontent.com/8823811/48716330-1f4d5500-ebe5-11e8-9f89-2af3b1b7c7e5.png)
sorry for the late reply, here it is

**Comment by g0rd** [comment] 2018-11-21 21:40
@numaanashraf any movement on this?

**Comment by numaanashraf** [comment] 2018-12-05 10:03
@g0rd Postman support image responses. But it looks like the connection to server is timing out before we receive the response completely. Could you let me know which OS you are on? I can send you the steps to enable verbose logging in Postman's network stack, which might help us understand what is happening in this case.

**Comment by g0rd** [comment] 2018-12-05 18:19
I am on Windows 10 64 bit

**Comment by saswatds** [comment] 2019-05-27 05:37
Hey @g0rd, Can you confirm that this issue still persists in our latest version of App v7.1.1.
If it does can you also provide with some more details regarding the size and type of the image or an endpoint we can call from our endpoint to fetch that image.

Thanks.

**Comment by g0rd** [comment] 2019-06-12 23:31
I have stopped working on the project. Sorry cannot provide more info

**Comment by codenirvana** [comment] 2019-07-05 05:55
@g0rd Thanks for the reply.

We tried reproducing this issue but as mentioned in https://github.com/postmanlabs/postman-app-support/issues/5531#issuecomment-444429169  this looks like a server timeout or request is not completed within the specified timeout in `Request timeout` setting.

Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2019-07-05 05:55 UTC
Labels: bug, blocked/need-info, product/runtime
