### ISSUE TITLE
The order of the Test is not coming as correct in the Postman Test Result Tab

### ISSUE THREAD

**Issue by rakeshk1987** [a85/POSTMan-Chrome-Extension#4650] opened 2018-06-05 08:37 UTC
**Describe the bug**
The order of the Test is not coming as correct in the Postman Test Result Tab, Collection Runner and Newman Results. The Test that are written in the first line is displayed last in the Test Result Tab. 

Please refer the screenshot attached for more details.

**Screenshots**
Screenshot is attached

**App information (please complete the following information):**
Postman for Windows
Version 6.1.3
win32 6.1.7601 / x64

**Comment by rakeshk1987** [comment] 2018-06-05 08:50
Attaching the Screenshot here as I couldn't attach it in the Main thread.

![postmantest](https://user-images.githubusercontent.com/38182578/40965520-d7ac209a-68a5-11e8-9b33-fb5b3f3dba3b.png)

**Comment by sivcan** [comment] 2018-06-29 08:07
@rakeshk1987 The new format for writing tests is the one that you're using in the 2nd Test and 3rd Test and it's **recommended** that you use this format.

The old test format was writing it like so: `test['test name'] = boolean`
Which is still supported only to help people who're coming from the old versions of the postman app to migrate to the new versions.

The tests are always executed in the correct order no matter if you're writing `pm.test` or `tests['test name']` format. Just that all the tests that are there in the `test['test name']` format are intentionally displayed at the end.

So all `pm.test` will be displayed at the top and the remaining `test['test name']` tests will be displayed at the last.

To confirm this:
I wrote a small  script to console log the order. 
![image](https://user-images.githubusercontent.com/12631777/42080741-4503b898-7ba1-11e8-837e-8ce7bec9adba.png)

It's printed as: 1, 2, 3
![image](https://user-images.githubusercontent.com/12631777/42080751-4c62b1ca-7ba1-11e8-9c78-6731d5c05ccf.png)

I move the script number 1 in between 2 & 3
![image](https://user-images.githubusercontent.com/12631777/42080794-655ef7ba-7ba1-11e8-980d-127e4f958450.png)

You can see the execution order is now 2, 1, 3
![image](https://user-images.githubusercontent.com/12631777/42080798-683df9cc-7ba1-11e8-8eda-318b4e3107f9.png)

I hope this information helps you.

**Comment by sivcan** [comment] 2018-07-02 07:41
Closing this issue since it's an intended behavior.
Kindly use the `pm.test` format to write your tests if display order is necessary for you.

Thanks!

**Closed as completed by sivcan** 2018-07-02 07:41 UTC
Labels: bug
