### ISSUE TITLE
oauth2.0 helper: it is not possible to save the helper data to a collection like for oauth1.0

### ISSUE THREAD

**Issue by pollenflugkalender** [a85/POSTMan-Chrome-Extension#2433] opened 2016-10-26 11:09 UTC
1. Postman Version: 4.8.0
2. App (Chrome app or Mac app): Standalone
3. OS details: Windows 
4. Is the Interceptor on and enabled in the app: 
5. Did you encounter this recently, or has this bug always been there: always
6. Expected behaviour: The settings for the oauth2 helper can be exported to a collection like it works for the oauth1 helper. 
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

For oauth1 it is possible to save the helper data to the request:
![image](https://cloud.githubusercontent.com/assets/8361094/19723691/b838a906-9b7c-11e6-8a95-c5ba5bfc4ad4.png)

But for oauth2 there is no corresponding setting:

![image](https://cloud.githubusercontent.com/assets/8361094/19723734/e22accbc-9b7c-11e6-9173-5d3fcf01ea52.png)

I am not sure if this is a really bug or just a missing feature.
Nevertheless it would be great if this feature was available because we want to use Newman in conjunction with Postman.

**Comment by sdnts** [comment] 2016-10-27 11:17
@pollenflugkalender We indeed do not store OAuth2 details specifically right now. We're considering this, thanks for the request :)

**Comment by ricjohn** [comment] 2017-11-07 17:27
+1

**Comment by vikiCoder** [comment] 2019-07-30 07:47
Closing this issue as a duplicate of the following issue:
https://github.com/postmanlabs/postman-app-support/issues/5459

**Closed as completed by vikiCoder** 2019-07-30 07:47 UTC
Labels: feature, Auth, OAuth2, product/runtime

**Comment by flyingUnderTheRadar** [comment] 2019-09-23 22:11
Any word on this?

**Comment by b-hayes** [comment] 2019-11-27 05:06
I'd like this as well
