### ISSUE TITLE
Manage environment hangs up postman when try to edit variables

### ISSUE THREAD

**Issue by samuelj90** [a85/POSTMan-Chrome-Extension#9084] opened 2020-09-23 12:18 UTC
Environment variables editor in postman hangs up when the number of variables is high.

**Describe the bug**
When  postman is loaded with more than 100 environment variable the postman app will freeze when try to edit it with environment editor.

**To Reproduce**
1. Add more than 100 environment variables.
2 Try to edit the variables
3. Window will freeze.

**Expected behavior**
Its only a simple JSON editor in tables try to implement lazy loading or some thing like to improve performance and UX

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]  :  Native App
 - Postman Version [e.g. 6.0.1]                       :  PostmanCanary 7.27.0-canary04
 - OS: [e.g. macOS High Sierra 10.13.2]         :  Windows

**Comment by DannyDainton** [comment] 2020-09-23 13:02
Hey @samuelj90,

This is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/5827 and all updates around the issue will be posted there.

**Closed as completed by DannyDainton** 2020-09-23 13:02 UTC
Labels: duplicate
