### ISSUE TITLE
Feature Request:  View or Edit webhook integration details

### ISSUE THREAD

**Issue by clarkritchie** [a85/POSTMan-Chrome-Extension#8558] opened 2020-05-28 16:03 UTC
It would be really helpful to be able to either see the details of a configured webhook integration, or ideally to edit it.

For example, I have 2 web hooks configured below but am unsure of where exactly they are pointed, so my only option is to delete them and re-create them.

![image](https://user-images.githubusercontent.com/385550/83165032-d3c11480-a0c1-11ea-9081-8037c5b16274.png)

**Comment by Atishay4294** [comment] 2020-06-05 06:55
Hi @clarkritchie - We have this feature in our roadmap and we'll be going live in a few weeks.
We'll keep you posted on this when we have more updates.

**Comment by shashankawasthi88** [comment] 2020-10-30 09:45
@clarkritchie This feature should be available now. If you go to Workspace > Integrations > Webhook Integration, you should see the Integration in the _Added Integrations_ tab. If you are the creator of the Integration, you should be able to edit the Integration as well. Closing the ticket, please open it if the issue is not addressed.

**Closed as completed by shashankawasthi88** 2020-10-30 09:45 UTC
Labels: feature, product/integrations

**Comment by clarkritchie** [comment] 2020-10-30 14:18
Thank you @shashankawasthi88!  

Question:

> If you are the creator of the Integration, you should be able to edit the Integration as well.

So if I am away on holiday and a change needs to be made, my teammates cannot edit the integration?

**Comment by shashankawasthi88** [comment] 2020-10-30 14:49
@clarkritchie the Integrations details under the _Edit_ ambit may contain sensitive information, hence only the creator of the Integration can edit the Integration.

**Comment by clarkritchie** [comment] 2020-10-30 15:45
And if the creator resigns or otherwise leaves, can someone else delete it?

**Comment by shashankawasthi88** [comment] 2020-10-30 15:53
@clarkritchie Yes, Team Admin has the rights to delete the Integration.
