### ISSUE TITLE
Postman v.7.16.0 crashes when a run request in collection is interrupted by CANCEL button.

### ISSUE THREAD

**Issue by milititskiy** [a85/POSTMan-Chrome-Extension#7949] opened 2020-01-23 09:36 UTC
Initial Setup

**Create a collection (e.g: abc)**

1. Add 3 folders to the collection. 
2. Nest 3 folders with chaining requests to the lowest  folder.

**Steps to reproduce the behavior**

1. Go to created Collection.
2. Run request from the lowest folder in the ierarchy.
3. Press "Send" button.
4. Wait until Cancel  button appears near HTTP status line.
5. Press appeared Cancel button.
6. Postman crashes.

**Expected behavior**
postman should cancel request and not quit unexpectedly.

**App information**

- App Type:Native App
- Postman version: v.7.16.0
- OS: Windows 10 version 1709

**Comment by mccannt** [comment] 2020-01-28 17:55
@milititskiy I am trying to replicate this but not seeing the same behaviour. 
Is this the setup that you have?

![image](https://user-images.githubusercontent.com/14275144/73291074-57223600-41b4-11ea-8792-d685ecaa6eb9.png)

**Comment by milititskiy** [comment] 2020-01-29 08:00
@mccannt Yes,the structure is right. But the request is POST and inside pre-request and test tabs on every level there is also a GET/POST request written in code(pm.sendRequest()).It is a chain of mixture of get and Post requests.
It fails on the latest version of Postman, but works fine on 7.9.0 ( had to downgrade because of the issue).
I can also provide video of the issue if you will not be able to reproduce it.
I wolud like to note thet before the actual POST request  (as I said before) I am making a chain(written in code) it looks like this: GET -> GET-> POST->GET->GET->POST(its the actual POST that is located in Level 3 folder)->GET->GET all code is located in pre-request tabs on different levels of folders.

**Comment by mccannt** [comment] 2020-01-29 17:12
@milititskiy If you could provide a video clip of this that would be fantastic!

**Comment by milititskiy** [comment] 2020-01-30 09:00
@mccannt HI! I have uploaded the video to my google drive. Can you check it?

https://drive.google.com/file/d/1IDzAg20Fyt2r-lHK5XSBaxXvBtwJN5hd/view?usp=sharing

**Comment by mccannt** [comment] 2020-01-30 15:55
@milititskiy I am able to view it. Thank you so much for this, it will help us in replicating and debugging this issue.

**Comment by milititskiy** [comment] 2020-02-05 11:48
@mccannt UPD: updated to a Latest Postman version and it is still has this issue. Any luck on taming it up? Need any information on the collection that I am using? Its just really frusrating. Currently I am using Postman 7.9.0 and it works fine. Htere are no probles with cancelling the requests.

**Comment by mccannt** [comment] 2020-02-05 12:18
@milititskiy Thanks for the update on this. I understand that this is a frustrating issue for you.
We now have all the necessary information we need to replicate this and will be triaging this to understand the cause and a fix for it shortly.

I can not give a version or date that this will be fixed by until we discover the root cause. We will keep you updated.

**Comment by milititskiy** [comment] 2020-02-05 12:20
> @milititskiy Thanks for the update on this. I understand that this is a frustrating issue for you.
> We now have all the necessary information we need to replicate this and will be triaging this to understand the cause and a fix for it shortly.
> 
> I can not give a version or date that this will be fixed by until we discover the root cause. We will keep you updated.

Thanks for your quick response! And thank you for keeping work on on it! Will be waiting for the reply and will be happy to provide more information on this issue.

**Comment by timbochamp** [comment] 2022-04-28 02:34
Hi @milititskiy, sorry to have this fall off our radar! Are you still able to reproduce this on the latest v9.16.1 version? It doesn't look like that Google Drive link is accessible anymore to see the chaining you used. I tried a chain of pm.sendRequests like so

![Screen Shot 2022-04-27 at 11 32 25 PM](https://user-images.githubusercontent.com/4521134/165664796-faf4cec1-615a-42a2-aa94-35298cdd4153.png)

and cancelled them in a 100 iteration collection run, but wasn't able to get a crash, though the resources used by Postman did jump up a fair bit

**Closed as completed** 2022-05-05 13:30 UTC
Labels: product/runtime
