### ISSUE TITLE
postman form-data upload file issue after update v7.1.1 

### ISSUE THREAD

**Issue by susumaung** [a85/POSTMan-Chrome-Extension#6608] opened 2019-05-29 07:44 UTC
I upload file with form-data and the file was not uploaded to httprequest after updating to v7.1.1.
When I reinstall to v7.0.9 then can upload file successfully.

**Comment by saswatds** [comment] 2019-05-29 07:52
Hi @susumaung, can you give us some more information on how to reproduce this? It would be really helpful if you follow the issue creation guidelines as there could be a multitude of reasons why this could be happening. 

Recently we have changed how files work in form-data and binary, to know more you can refer these issues https://github.com/postmanlabs/postman-app-support/issues/4320#issuecomment-490749103

**Comment by susumaung** [comment] 2019-05-29 08:02
Hi @saswatds, 
I created web Api as below.
[HttpPost]
        public HttpResponseMessage FileUpload()
        {
            HttpResponseMessage result = null;
                var httpRequest = HttpContext.Current.Request;
                if (**httpRequest.Files.Count** > 0)
                {
                    return Request.CreateResponse(HttpStatusCode.OK);
                }
                else
                {
                    return Request.CreateResponse(HttpStatusCode.BadRequest);
                }
        }
After that, I try to upload file from postman [Post] method. In the body, choose form-data and select the file.
![image](https://user-images.githubusercontent.com/12973703/58539827-bb0dec80-822a-11e9-8dee-eb068375cc8d.png)

httpRequest.Files.Count is 1 at version v7.0.9 which means the file was uploaded successfully.
After updating to latest version v7.1.1 then httpRequest.Files.Count becomes 0 which means fail to upload.

**Comment by saswatds** [comment] 2019-05-29 08:39
Hi @susumaung, This is the issue with form-data empty key. More on this here https://github.com/postmanlabs/postman-app-support/issues/6537

We have applied the fix on our canary app. https://www.getpostman.com/downloads/canary or else you can use the temporary hack as I have suggested in the other issue

I will be closing this issue once you confirm that it is working.
Thanks.

**Comment by susumaung** [comment] 2019-05-29 09:04
Hi @saswatds,
Thank you for reply.
The problem is solved by using canary.

**Comment by codenirvana** [comment] 2019-05-29 09:47
@susumaung This will be fixed in our next stable release, follow the original issue thread for more updates.

Closing as duplicate of #6537

**Closed as completed by codenirvana** 2019-05-29 09:47 UTC
Labels: product/runtime
