### ISSUE TITLE
Long Running Requests Freeze the GUI////

### ISSUE THREAD

**Issue by natiki** [a85/POSTMan-Chrome-Extension#5877] opened 2019-02-04 05:36 UTC
- Postman Native Application 6.7.3 on Windows 10 Professional
- Put in a request that is connecting to a slow remote server. The GUI shows waiting with the white background 

![image](https://user-images.githubusercontent.com/4738140/52191956-59043280-289b-11e9-8705-816bbc94764a.png)

and then eventually changes to:

![image](https://user-images.githubusercontent.com/4738140/52191872-ea26d980-289a-11e9-86f8-78249a23f323.png)

The application itself is still responsive as I can close it using the window X, but it never redraws itself.

**Comment by numaanashraf** [comment] 2019-02-04 05:41
@natiki Is there a publicly accessible endpoint we can use to replicate this? Else, could you share more information regarding the request & response? 

Response size
Response headers
Are you using pre-request or test scripts?
- If yes, are you setting environment or variables in these scripts?

**Comment by natiki** [comment] 2019-02-04 05:44
* Unfortunately this is not a publicly accessible end point
* No pre-request scripts
* I will have to work out what the response size is using a different tool etc.

FWIW if I run the Postman Console at the same time it also goes grey as the main window at the same time. As that only shows the response headers I would not have expected this as it should be unaffected by response size.

**Comment by natiki** [comment] 2019-02-04 05:49
Hmmmm Response Body is in the Postman Console as well.... Perhaps the returned content is too big for the window. Any way to TURN OFF the body appearing in the Console window?

**Comment by numaanashraf** [comment] 2019-02-04 05:51
@natiki could you try sending the request via cURL?

**Comment by natiki** [comment] 2019-02-04 21:58
@numaanashraf Using cURL I can see the response come back no problem. The response is LARGE at 42MB so I am guessing this is what kills PostMan. AFAIK the response has not increased in size of late and Postman was working fine. It did upgrade itself automatically so this may be a regression.

Bottom line PM needs to handle large responses elegantly.

**Comment by numaanashraf** [comment] 2019-02-20 17:27
Thanks for the info @natiki. We are tracking this at a related issue #4751.

**Comment by numaanashraf** [comment] 2019-02-20 17:27
Duplicate of #4751

**Closed as completed by numaanashraf** 2019-02-20 17:27 UTC
Labels: bug, performance
