### ISSUE TITLE
Markdown not rendered inside tables

### ISSUE THREAD

**Issue by kszafran** [a85/POSTMan-Chrome-Extension#5662] opened 2018-12-18 13:52 UTC
**Describe the bug**
Markdown is not rendered inside tables. I have reported a similar bug before https://github.com/postmanlabs/postman-app-support/issues/5346, which has been fixed. This time Markdown is not rendered in _any table_.

**To Reproduce**
Import the following collection into Postman:
```
{
	"info": {
		"_postman_id": "f54f5fce-5f26-4203-97e9-49a0597bf99a",
		"name": "what's wrong",
		"description": "<table><tr><td>`Hello` _there_</td></tr></table>",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "with this folder",
			"item": [],
			"description": "<table><tr><td>`Hello` _there_</td></tr></table>"
		}
	]
}
```
View the documentation in web.

**Expected behavior**
Markdown should be rendered inside tables.
![48669559-100ad080-eb2d-11e8-996c-e65fc61a5d3f](https://user-images.githubusercontent.com/3056812/50158288-08794b80-02d4-11e9-9c83-c1a194793895.png)

**Screenshots**
<img width="669" alt="screen shot 2018-12-18 at 14 43 21" src="https://user-images.githubusercontent.com/3056812/50158257-f0a1c780-02d3-11e9-97c6-a158ec893b12.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.6.1
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome 70.0.3538.77

**Comment by kszafran** [comment] 2019-01-22 14:03
Any updates on this issue?

**Comment by godfrzero** [comment] 2019-04-09 05:19
I noticed that in the collection you've posted, the markdown is embedded within an HTML table (not a markdown table). In general, markdown does not support parsing of markdown content within an HTML block in a markdown document context. Refer https://spec.commonmark.org/0.29/#html-blocks for details. #5346 was actually caused by double-parsing of the markdown in certain cases, which is what led to the markdown within the table being incorrectly rendered.

Out of curiosity, is there a reason why you're not using a markdown table?

**Comment by kszafran** [comment] 2019-04-09 07:36
That's because I construct nested tables. I don't think it's possible with markdown itself.

**Comment by godfrzero** [comment] 2019-04-09 10:21
Yeah, nested tables aren't possible in markdown AFAIK either. With the markdown standard though, the only way that I can see to achieve what you're trying to achieve is to use HTML only within the table context.

**Comment by Raja-Simha** [comment] 2019-04-11 11:19
@kszafran We are closing this issue as the reported behavior is not a bug as explained by @godfrzero .

**Closed as completed by Raja-Simha** 2019-04-11 11:19 UTC
Labels: feature, product/documentation, product/dashboard
