### ISSUE TITLE
Generate Code Snippets does not show Authorization header

### ISSUE THREAD

**Issue by markbullock-mbo** [a85/POSTMan-Chrome-Extension#8561] opened 2020-05-29 03:11 UTC
**Describe the bug**
For a request with an Authorization header, Generate Code Snippets does not display the Authorization header.

**To Reproduce**
1. Click a request which has an Authorization header
2. Click on Code

Actual: the Authorization header does not appear
curl --location --request POST 'https://auth.mbodev.me/issue/oauth2/token' \
--header 'Content-Type: text/plain' \
--data-raw '{
  "username": "mbexternalservicesqa+verified@gmail.com",
  "password": "P@ssw0rd",
  "scope": "urn:mboframeworkapi",
  "grant_type": "password"
}'

**Expected behavior**
All headers should appear
curl --location --request POST 'https://auth.mbodev.me/issue/oauth2/token' \
--header 'Authorization: Basic XXXXXXXXXXXXX' \
--header 'Content-Type: text/plain' \
--data-raw '{
  "username": "mbexternalservicesqa+verified@gmail.com",
  "password": "P@ssw0rd",
  "scope": "urn:mboframeworkapi",
  "grant_type": "password"
}'

**Screenshots**
see attached images

**App information (please complete the following information):**
Postman for Windows
Version 7.25.0
win32 10.0.18362 / x64
Windows 10 Enterprise v1903 OS build 18362.836
![postmanRequest](https://user-images.githubusercontent.com/26971939/83216525-57105380-a11e-11ea-81db-2f8937f90842.png)
![postmanCodeSnippet](https://user-images.githubusercontent.com/26971939/83216534-5d063480-a11e-11ea-9d0f-bbc2efe4cf89.png)

**Comment by shreys7** [comment] 2020-05-29 05:37
Duplicate of #8550

**Closed as completed by shreys7** 2020-05-29 05:37 UTC
