### ISSUE TITLE
Get "Unable to verify the first certificate' despite adding client certificate to Settings > Certificates

### ISSUE THREAD

**Issue by ashwinnair2011** [a85/POSTMan-Chrome-Extension#11322] opened 2022-10-04 02:50 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm trying to run a GET request for a .net API I've created in a docker container. I've added my generated self signed dev certificate to, first, the CA certificates as a PEM and then the Client Certificates list as a pfx.

![image](https://user-images.githubusercontent.com/25140633/193722072-b8929754-9be3-4a6b-a8af-ab3b5557a5ec.png)

Regardless of what I do, I still get this error/warning. Disabling SSL certificate validation returns me a response with a warning. Here is what the warning looks like in the log

![image](https://user-images.githubusercontent.com/25140633/193722227-b0fa6c67-71bf-4a42-87b6-8e4b8b3129dd.png)

I get no errors or console warnings when I access it via a browser.
 
I have seen similar issues like this in Github which is where I got the idea of adding the certificate to the Settings but I can't seem to get beyond this

### Steps To Reproduce

1. Create self signed certificate for localhost
2. Add certificate to POSTman settings > Certificates
3. Make GET request call to https endpoint

### Operating System

Windows

### Postman Version

9.31.15

### Postman Platform

Postman App

**Comment by DannyDainton** [comment] 2022-10-04 03:47
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/6354

**Closed as completed** 2022-10-04 03:47 UTC

**Comment by Hendrik-Rummens** [comment] 2022-10-24 08:53
Have you found a solution yet? @DannyDainton
