### ISSUE TITLE
Adding a large file to form-data body causes postman to hang with black screen

### ISSUE THREAD

**Issue by zootyzoot** [a85/POSTMan-Chrome-Extension#5132] opened 2018-09-04 12:33 UTC
## App Details:

```
Postman for Windows
Version 6.2.5
win32 10.0.17134 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behaviour: postman should not hang

1. open postman
2. create a new request tab
3. set the method to POST
4. click on body tab
5. select form-data
6. click on the dropdown inside the key input line
7. select file 
8. click on choose files
9. select a very large file (mine was 3.7GB) --> postman kaput

**Comment by numaanashraf** [comment] 2018-09-04 12:54
@zootyzoot Thanks for reporting this. This seems related to another issue we are tracking. Closing this as a duplicate of #4375.

**Closed as completed by numaanashraf** 2018-09-04 12:54 UTC
