### ISSUE TITLE
Postman crashes after closing collection runner during the run process

### ISSUE THREAD

**Issue by tonyparkerov** [a85/POSTMan-Chrome-Extension#7439] opened 2019-10-05 13:43 UTC
**Describe the bug**
Postman crashes after closing collection runner during the run process. 

**Preconditions**
You have a collection with 1 ore more requests.

**To Reproduce**
1. Open collection runner
2. Set delay to 1200 ms for example
3. Click 'RUN TEST'
4. Close 'Collection runner' screen before the end of the run.

**Expected behavior**
Postman doesn't crash.

**Screenshots**
![crash](https://user-images.githubusercontent.com/14942194/66255651-e7b0b280-e78e-11e9-82cc-7153698c071e.gif)

**App information (please complete the following information):**
 - Desktop App
 - Postman v7.8.0
 - OS: Windows 10, 1903, x64

**Additional context**
Logs: `[17468][1570282270346][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"Error","message":"Object has been destroyed","stack":"Error: Object has been destroyed\n    at WebContents.send (C:\\Users\\Anton\\AppData\\Local\\Postman\\app-7.8.0\\resources\\electron.asar\\browser\\api\\web-contents.js:101:15)\n    at Function.io (C:\\Users\\Anton\\AppData\\Local\\Postman\\app-7.8.0\\resources\\app.asar\\services\\RuntimeBridge.js:191:16)\n    at Requester.emit (events.js:182:13)\n    at Requester.EventEmitter.emit (domain.js:442:20)\n    at onEnd (C:\\Users\\Anton\\AppData\\Local\\Postman\\app-7.8.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:305:22)\n    at onComplete (C:\\Users\\Anton\\AppData\\Local\\Postman\\app-7.8.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:342:21)\n    at Request._callback (C:\\Users\\Anton\\AppData\\Local\\Postman\\app-7.8.0\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:467:13)\n    at Request.self.callback (C:\\Users\\Anton\\AppData\\Local\\Postman\\app-7.8.0\\resources\\app.asar\\node_modules\\postman-request\\request.js:255:12)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:442:20)\n    at Request.<anonymous> (C:\\Users\\Anton\\AppData\\Local\\Postman\\app-7.8.0\\resources\\app.asar\\node_modules\\postman-request\\request.js:1439:10)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:442:20)\n    at Gunzip.<anonymous> (C:\\Users\\Anton\\AppData\\Local\\Postman\\app-7.8.0\\resources\\app.asar\\node_modules\\postman-request\\request.js:1310:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Gunzip.emit (events.js:187:15)\n    at Gunzip.EventEmitter.emit (domain.js:442:20)\n    at endReadableNT (_stream_readable.js:1090:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}]`

**Comment by saswatds** [comment] 2019-10-05 14:17
Closing this issue as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/5848

**Closed as completed by saswatds** 2019-10-05 14:17 UTC
