### ISSUE TITLE
Descriptions for Variables

### ISSUE THREAD

**Issue by swinster** [a85/POSTMan-Chrome-Extension#11914] opened 2023-04-12 13:25 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When sharing environment variables, only the initial value persists. This is fine if you want that initial value to be an example, but most of the time, you want to describe what the variable does and where it might be used (especially if you have hundreds of variables used in multiple requests). We, therefore, have to use the initial value as a description, which can be accidentally over written. 

### Describe the solution you'd like

As an additional field to a variable to allow for a description, as is the case header parameters.

### Describe alternatives you've considered

As mentioned above - use the initial value as a description field, but this sucks

### Additional context

![image](https://user-images.githubusercontent.com/8142964/231476247-2f94a6c9-092c-4cd5-b603-5b76831ececd.png)

**Comment by giridharvc7** [comment] 2023-04-17 10:21
Duplicate of #11303

**Closed as completed by giridharvc7** 2023-04-17 10:21 UTC
Labels: feature, variables, product/runtime

**Comment by swinster** [comment] 2023-04-17 10:52
Dmn it; I even searched for "Decriptions for Variables" on open and closed issues before I posted. 😮‍💨. Anyhow, thank you for linking.
