### ISSUE TITLE
Add "new request" option to collection/folder menu

### ISSUE THREAD

**Issue by CallumWatkins** [a85/POSTMan-Chrome-Extension#4115] opened 2018-01-26 19:40 UTC
## Feature Request
Ability to right click (or click 3 dots) on a collection/folder and add a new request.

I believe there are two ways of implementing this:
1. Open up the standard "save request" dialog, but where the collection/folder location has already been selected.
2. Or, a slightly more polished version would be an "add request to [collection/folder name]" dialog where the ability to select the location is completely removed.

This is an image of the current right click menu within which I am suggesting a "new request" option could be placed:
![currentmenu](https://user-images.githubusercontent.com/18353194/35456879-e8b9db80-02ce-11e8-9a0a-938fb5d56bba.png)

Adding this would massively improve the speed at which one could add a new request, especially within nested folders.

**Comment by prashantagarwal** [comment] 2018-02-08 13:09
@CallumWatkins Thanks for reporting this.

**Comment by sankalp0o** [comment] 2018-06-29 07:14
@CallumWatkins We're working on adding an "Add request" option to the context menu for collections as well as folders. This would be out soon in the next release of the Postman App.

**Comment by sivcan** [comment] 2018-08-06 07:53
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4177

**Closed as completed by sivcan** 2018-08-06 07:53 UTC
