### ISSUE TITLE
Copy existing curl command in plain text and paste "Paste Raw Text" -- it does not update the method

### ISSUE THREAD

**Issue by g-industrialist** [a85/POSTMan-Chrome-Extension#6427] opened 2019-05-07 01:55 UTC
**Describe the bug**
Copy existing curl command in plain text and paste "Paste Raw Text" -- it does not update the method

**To Reproduce**
1. Copy existing curl command , for example , curl --request GET .....
2. Click on 'Import' --> paste "Paste Raw Text"
3. The method does not update to "GET", it is still "POST"

**Expected behavior**
3. The method does not update to "GET", it is still "POST", it should be updated according to the curl command

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 7.0.9]
 - OS: [e.g. Windows 7]

**Comment by abhijitkane** [comment] 2019-06-04 18:10
@iseehk I'm unable to reproduce this. cURL requests always open in a new tab, so there's no change in any existing request. Can you share a sample curl command and the request it adds to a tab, where the methods don't match?

**Comment by alexnoise79** [comment] 2019-08-30 07:43
I got the same error, when paste a POST curl, the method in the window is not updated remains GET

**Comment by DannyDainton** [comment] 2020-06-29 11:12
Hey @alexnoise79 / @iseehk 

Is this still an issue for you in the latest version?

Would you be able to share the full curl command or post a short video/.gif showing the problem?

**Comment by alexnoise79** [comment] 2020-06-29 13:15
Hi, no not anymore

**Comment by DannyDainton** [comment] 2020-06-29 13:23
Closing this issue for now but it can be opened again, if the problem persists for others.

**Closed as completed** 2020-06-29 13:23 UTC
Labels: bug
