### ISSUE TITLE
Improvements in sharing of OAuth 2.0 token and token generation details

### ISSUE THREAD

**Issue by vikiCoder** [a85/POSTMan-Chrome-Extension#9056] opened 2020-09-14 13:02 UTC
Over the last few years, Postman has evolved to become an API Development Platform. The ability to build a request and inspect the response is one of the core features that we offer. Authentication is a fundamental part of an API and within this, OAuth 2.0 has emerged as one of the most used auth methods. We have made a few improvements to make the OAuth 2.0 experience better in a collaborative environment. In this post, we are going to elaborate on the problems we have tried to address in using OAuth 2.0 through Postman. 

### Easy access to OAuth token generation information:

We want to simplify working with multiple OAuth servers through Postman. You can now save the information required to generate an OAuth token with the request or collection and you won’t have to enter these details again when you’re generating a new token. This information will be sharable with the request/collection as well. 

![image](https://user-images.githubusercontent.com/16588032/93087632-75db2b80-f6b6-11ea-99b8-ad5575ccea46.png)
 
This is helpful if you have multiple requests using different OAuth servers or if you’re sharing a request with someone and they need the details to generate the token. 

**A word of caution:** OAuth token generation information can contain sensitive data. Like other authentication methods, we encourage you to use environment variables to mask this when sharing the request or collection.

### On-demand sharing of OAuth access token:

An OAuth token contains sensitive information and hence, it should be shared carefully. You can now optionally choose to share a token with the request or collection. All you have to do is sync the token. By default, we will not sync it. If you don’t sync the token, it will still be present in your local session and can be used by you in the app but it won’t be stored with the request on Postman cloud. 

![image](https://user-images.githubusercontent.com/16588032/93087657-81c6ed80-f6b6-11ea-8bdc-18da27251cb5.png)
 
Another important thing to note here is that you can still generate the token and use it even if you’re not the editor of the request/collection. You will have all the information needed to generate the token, you can create a new token and use it in your local session. Since you’re the viewer of the collection, you won’t be able to sync it on the Postman cloud. This will give you better access control in using tokens. 

![image](https://user-images.githubusercontent.com/16588032/93087691-8d1a1900-f6b6-11ea-8385-97a791344a62.png)

These changes are available in the [Postman Canary](https://www.postman.com/downloads/canary/). Please download the latest Postman Canary app and check it out. Feel free to provide your feedback here.

<details><summary><b>Issues affected by these changes:</b></summary>

* https://github.com/postmanlabs/postman-app-support/issues/4636
* https://github.com/postmanlabs/postman-app-support/issues/7537
* https://github.com/postmanlabs/postman-app-support/issues/5459
* https://github.com/postmanlabs/postman-app-support/issues/1507
</details>

**Comment by va-vessels** [comment] 2020-09-23 12:29
It's been GREAT!!  I already have four or five different collections to support effort with multiple partners.  Implicit, Code, Code w/PKCE and of course all with different client_id, client_secrets and redirect_uri settings.  I've had no issues.

Big THANKS again.

**Comment by shtrip** [comment] 2020-09-24 06:15
Very nice improvement!

I'm using a variable for the token name and the value is set by the active environment. When I'm getting a new access token the old token is also still kept. As far as I know in OAuth2 the old access and refresh token should be invalidated when you get a new token so I'm wondering why old tokens are kept. 

Wouldn't it be better to keep just one token per token name? That way you automatically have the active token, no need to manually select it and less clutter in the Manage access tokens window.

**Comment by CasperWSchmidt** [comment] 2020-11-03 12:30
How do I avoid syncing the username and password in a "Passwords credentials" flow? I think those should be opt-in just like the token.

**Comment by vvs11** [comment] 2020-11-03 12:54
@CasperWSchmidt  You can use environment variables to store that information and use the current value of environments to prevent sharing. We will keep working on making this solution better, but in the meantime, you can use environments.

**Comment by CasperWSchmidt** [comment] 2020-11-03 13:00
@vvs11 Thanks, but doesn't that bring the risk of sharing by mistake if hitting "Persist All"?

**Comment by CasperWSchmidt** [comment] 2020-11-03 13:05
Also, I've tried deleting a synced token in a team collection, Now I'm no longer able to use a newly generated token accessible from the "Available tokens" dropdown. Nothing happens when I select the token and sending the request gives 401 Not Authorized back.
If I open the "Manage tokens" and click "Use token" a small notification pops up in the lower right corner saying "Token added", but I don't see it anywhere and the request is still rejected with 401.

On another request I have tried just creating a new token (the old one is still synced) but I get 401 as well. Looking at the token clicking "code" it is the old one (expired this morning) that I retrieved just before updating Postman to 7.35.

I filed a ticket on that as well, but hope that someone can help me here so that other people with the same problem can benefit from it as well.

**Comment by TimmyAA** [comment] 2020-11-03 15:56
woke up to v7.35.0 this morning. OAuth2 is broken for me. 
I cannot choose "Available" token or paste in a token. It never gets set as an Authorization header.
I can work around this by copying/pasting using the Bearer Token type, but it's extra steps
At least allow the pasting of tokens, as my work involves using idtokens and need to copy/paste anyway.

**Comment by vvs11** [comment] 2020-11-03 19:19
@CasperWSchmidt @TimmyAA  I tried reproducing it but could not do so. Could you share a recording of this? It will help us understand the issue better

**Comment by TimmyAA** [comment] 2020-11-03 19:44
Thanks @vvs11 , here are some snips...

![image](https://user-images.githubusercontent.com/45183705/98032089-799b4c80-1de1-11eb-872b-5da4828c40e8.png)

Choose one of the dev's
![image](https://user-images.githubusercontent.com/45183705/98032222-afd8cc00-1de1-11eb-8349-51b63a4069c9.png)

No Authorization header...
![image](https://user-images.githubusercontent.com/45183705/98032327-d991f300-1de1-11eb-884f-6a67d79191e0.png)

Try pasting an idtoken
![image](https://user-images.githubusercontent.com/45183705/98032546-2a095080-1de2-11eb-87d1-3a1f685b4d65.png)

Still no Authorization header
![image](https://user-images.githubusercontent.com/45183705/98032625-44432e80-1de2-11eb-98be-5c220854dbf3.png)

Switch to Bearer token and paste idtoken
![image](https://user-images.githubusercontent.com/45183705/98032735-72c10980-1de2-11eb-8fc7-273991754db8.png)

Authorization token present
![image](https://user-images.githubusercontent.com/45183705/98032783-840a1600-1de2-11eb-89c9-606ac98bbcfd.png)

**Comment by CasperWSchmidt** [comment] 2020-11-03 19:47
Video of the problem here: https://streamable.com/yrxvrk

**Comment by randyramirez1** [comment] 2020-11-03 23:36
The new version is not working when using the OAuth 2.0 authorization.  It's not picking up the latest token in the Authorization header so it keeps on saying it's expired and not matching.

**Comment by randyramirez1** [comment] 2020-11-03 23:38
Same issue with TimmyAA.  This morning all my OAuth 2.0 are broken and can't make it work.  Keeps on getting the old token and not working as the older version where it picks up the latest token generated after clicking  "Use Token".  Trying to manually edit the Authorization and keeps on getting overriden by an old token.

**Comment by randyramirez1** [comment] 2020-11-03 23:49
Can we go back to the older version of Postman as this new version is no longer working properly.  Losing trust with Postman now so I'm using other API tester as it does not work anymore as it used to.

**Comment by rvillane** [comment] 2020-11-04 01:00
I also have the same issue with v7.35.0 and Mac and windows, OAuth 2.0 authentication is broken, however, the generation of OAuth tokens works fine, then as a workaround , you can generate the OAuth token, copy it and then switch to Bearer Authentication and paste the token value.  This will help to get you unblocked until the OAuth headers are set correctly.

**Comment by vvs11** [comment] 2020-11-04 04:50
Thanks everyone for reporting this. We are looking into this issue. Will post an update soon

**Comment by quixote911** [comment] 2020-11-05 11:31
Hi folks, we appreciate your feedback and patience.
Rest assured, our team is working on this issue as we speak. This is a bug in Postman v7.35.0 which we have now rolled back.
We are working on fixing this as soon as possible.

To mitigate any impact for now, please use [Postman v7.34.0](https://dl.pstmn.io/download/latest/osx) 🙂

**Comment by CasperWSchmidt** [comment] 2020-11-05 12:22
Please note that the link above is for MacOS, the link for Windows is [Postman v7.34.0](https://dl.pstmn.io/download/latest/windows)

For some reason it won't load after installation. It complains about me having a newer version on my system. How do I fix that problem? Complete uninstall and re-installing 7.34.0 again?

**Comment by vvs11** [comment] 2020-11-05 14:47
@CasperWSchmidt You can follow the steps mentioned here: https://support.postman.com/hc/en-us/articles/360025359014
Please check out 'Clean up local files and restart the app' and ‘Resolution steps to rename your Postman folder’ sections

**Comment by CasperWSchmidt** [comment] 2020-11-06 08:04
@vvs11 Thank you!

**Comment by AVHemonto** [comment] 2020-11-16 08:14
> Hi folks, we appreciate your feedback and patience.
> Rest assured, our team is working on this issue as we speak. This is a bug in Postman v7.35.0 which we have now rolled back.
> We are working on fixing this as soon as possible.
> 
> To mitigate any impact for now, please use [Postman v7.34.0](https://dl.pstmn.io/download/latest/osx) 🙂

Could you roll back the Mac version as well? I am having the same issues as @CasperWSchmidt :(

**Comment by AndersMalmgren** [comment] 2020-11-19 10:25
several weeks now, can we have this fixed please

**Comment by lilliank** [comment] 2020-11-20 23:18
https://dl.pstmn.io/download/latest/windows  was linked above saying that it was Postman v7.34.0, but it's still pointing to the bad version.  Can we get a link to 7.34.0 please?  And, any update on a fix?  

Thank you!

**Comment by mohitranka** [comment] 2020-11-21 05:33
@lilliank and others we have recently released 7.36.0 with bunch of fixes related to OAuth2. Please let us know if you continue to face any issues.

**Comment by CasperWSchmidt** [comment] 2020-11-23 08:31
It works for me! Hooray! 👍

**Comment by AndersMalmgren** [comment] 2020-11-23 10:43
Works here too!

**Comment by bhavnaberi** [comment] 2020-12-16 08:43
Can we automate the access token generation using Azure AD OAuth V2 implicit flow in postman/newman. We tried doing that but all our existing scripts fail as the popup to enter user credentials (username and password) comes up and it seems like it cannot be automated in newman without manual intervention. Can you help as all our existing automation is breaking

**Comment by mohitranka** [comment] 2021-02-22 05:06
@bhavnaberi We are working on making access token management easier for OAuth2. Closing this ticket, If you wish to track it separately, suggest opening an issue dedicated to this.

**Closed as completed by mohitranka** 2021-02-22 05:06 UTC
Labels: product/runtime

**Comment by khyejin1231** [comment] 2022-04-18 19:57
Hi everyone, I am experiencing this issue while generating a new access token. Everything works fine but I cannot find the new access token in the response. Any tips?

![image](https://user-images.githubusercontent.com/74085996/163868565-c36ae72b-469d-4e73-b083-f091358ab8d9.png)


Native app
Postman v9.15.10
Twitter

**Comment by dansykora** [comment] 2022-07-28 13:06
@khyejin1231 I'm having the same issue on version 9.26.2

**Comment by sandeep-singh-pstmn** [comment] 2023-06-15 07:36
@khyejin1231 and @dansykora Do you still have this problem? It can't be replicated on my end

https://github.com/postmanlabs/postman-app-support/assets/85243040/f0c22f93-d3f6-48df-bf54-a08b4d137cec
