### ISSUE TITLE
UI hides a part of content on Two Panes View on Mac

### ISSUE THREAD

**Issue by phunguyen19** [a85/POSTMan-Chrome-Extension#5466] opened 2018-11-01 03:33 UTC
**To Reproduce**
1. Switch to Single Pane View
2. Open new tab with POST method 
3. Pass a long content to body with format `raw` `application/json`, the content need to long enough to see the scrollbar on request body
4. Switch to Two Panes View
5. See error

**Expected behavior**
See the full content in Body Request Pane

**Screenshots**
![Postman Error](https://image.ibb.co/cT4oiL/postman-error-compressed.gif "Postman Error")
*The gif is not repeated, re-open it in a new tab to see the animation*

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version 6.4.4 (6.4.4)
 - OS: macOS Mojave 10.14

**Comment by sivcan** [comment] 2018-11-03 12:38
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/5430

**Closed as completed by sivcan** 2018-11-03 12:38 UTC
