### ISSUE TITLE
Basic Auth bug with unicode characters

### ISSUE THREAD

**Issue by grational** [a85/POSTMan-Chrome-Extension#5161] opened 2018-09-10 10:40 UTC
**Bug description**
I have noticed the postman app (my version is `6.3.0`) generates an incorrect basic authentication header when non ASCII characters are used.

**To reproduce**
1. Go to any request
2. Click on `Authorization tab`
3. Select TYPE `Basic Auth` in the left section
4. Fill the username with: `username`
5. Fill the password with: `ɐsʇɹouɓdɐssʍoɹp`
6. Click on the button `Preview Request`
7. Go on the `Headers` tab copy the string following `Basic` in the `VALUE` field of the `Authorization` header (for me it is `dXNlcm5hbWU6UHOHeW91U2RQc3ONb3lw`)

**Expected behavior**
The output must be the same of the following (linux shell) command, following the explanation how to build it [here](https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side):
```bash
echo -n 'username:ɐsʇɹouɓdɐssʍoɹp' | base64
dXNlcm5hbWU6yZBzyofJuW91yZNkyZBzc8qNb8m5cA==
```

**Countercheck**
```bash
# decode base64 output
echo -n dXNlcm5hbWU6yZBzyofJuW91yZNkyZBzc8qNb8m5cA== | base64 --decode
username:ɐsʇɹouɓdɐssʍoɹp

# decode postman v6.3.0 output
echo -n 'dXNlcm5hbWU6UHOHeW91U2RQc3ONb3lw' | base64 --decode
username:Ps�youSdPss�oyp
```

**App information**
 - App Type: `Native App`
 - Postman Version: `6.3.0`
 - OS: Ubuntu Xenial `16.04.5 LTS`

**Comment by Lysander** [comment] 2019-04-04 09:03
This bug is a duplicate of #4070 - although this is more generic.

Overall it's not about *unicode* but about the **encoding** that is used for generating the basic auth credentials.

Currently postman uses ISO-8859-1 as encoding; in #4070 there is the suggestion to change it to UTF-8. Imho that would not be a good solution!

I would apreciate it, if one could **choose** the encoding. This would be the best solution reagrding compatibility with older and newer webservices.

**Comment by shamasis** [comment] 2019-04-04 11:04
Curated the issue #4070 to include these details and closing this as duplicate.

**Closed as completed by shamasis** 2019-04-04 11:04 UTC
Labels: bug, encode-decode, duplicate
