### ISSUE TITLE
Auto activate response search input on clicking search icon

### ISSUE THREAD

**Issue by npadhya** [a85/POSTMan-Chrome-Extension#2594] opened 2016-12-26 08:49 UTC
Bug Fix | Feature request

Postman app has the response section where the response body is displayed, It also has a search functionality by clicking on a Search icon. But it's very annoying that upon clicking the search icon the search input box is not auto activated. So after clicking on the search icon, the user will have to click on the input to start typing the search string.

Can postman fix this, and auto-activate the search input

**Comment by a85** [comment] 2017-12-24 21:51
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1937

**Closed as completed by a85** 2017-12-24 21:51 UTC
Labels: Response-Section
