### ISSUE TITLE
Prompt for input on unknown environment variable

### ISSUE THREAD

**Issue by jgf5013** [a85/POSTMan-Chrome-Extension#4220] opened 2018-02-21 00:34 UTC
Intentional duplicate due to lack of follow-up on #285. Can we please get some input on that issue so that we at least know it's on the radar?

**Comment by a85** [comment] 2018-02-22 01:39
Closing as a duplicate of #285

**Comment by a85** [comment] 2018-02-22 01:40
Have responded in the thread.

**Closed as completed by a85** 2018-02-22 01:40 UTC
