### ISSUE TITLE
Body of a response with status code 204 contains strange characters

### ISSUE THREAD

**Issue by ykz89** [a85/POSTMan-Chrome-Extension#5420] opened 2018-10-24 09:57 UTC
**Describe the bug**
I created a route in Lumen which responds with status code 204 and no content.
When I send this request in Postman v6.4.4 however I receive a body 
```
 �


```
**Expected behavior**
An empty body

**Screenshots**
https://imgur.com/a/Ayjjusq

**App information (please complete the following information):**
 - Lumen Version 5.4
 - Postman Version 6.4.4
 - OS: Windows 10 Pro

**Additional context**
When I test the same request in PhpStorm it returns `<Response body is empty>`

**Comment by sujayvenaik** [comment] 2018-10-24 10:04
Hey @ykz89 
Can you confirm me that this was working in 6.3 version?

Also, can you send a screen recording of the complete flow you had, or send the response headers?

**Comment by ykz89** [comment] 2018-10-24 10:42
[These](https://imgur.com/a/eV5caNo) are the response headers.
I am unable to confirm if this was working in 6.3 since I only tried this is the latest version.

**Comment by shamasis** [comment] 2019-05-13 11:29
![image](https://user-images.githubusercontent.com/232373/57618242-81898000-75a0-11e9-9d47-70f15646fca4.png)

**Comment by codenirvana** [comment] 2019-08-14 06:37
@ykz89 The requesting server is responding with the response body (notice `content-length: 20` response header in the screenshot).

We have seen similar issues in the past where different clients (PhpStorm in your case) authoritatively override/trim the request body for 204 response.
However, Postman shows the exact response body sent from the server irrespective of the response status.

Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2019-08-14 06:37 UTC
Labels: bug, Response-Section, product/runtime
