### ISSUE TITLE
Cannot click and drag to highligh text when renaming request

### ISSUE THREAD

**Issue by IanCampbellCode** [a85/POSTMan-Chrome-Extension#5181] opened 2018-09-14 18:17 UTC
If you hold down the left mouse button to highlight text while renaming a request, the request moves instead of highlighting text.

Highlighting text does work as expected for renaming a collection.

1. Create a request.
2. Right click the request and click 'Rename'.
3. Attempt to highlight text by holding the left mouse button down and moving the mouse across the text.
4. Instead of highlighting text, the entire request moves.

Expected behavior:
The text should be highlighted instead of moving the request.

App information:
 - App Type: Native App
 - Postman Version:  6.2.5 
 - OS: macOS High Sierra 10.13.6

**Comment by dustinh123** [comment] 2018-10-10 21:18
I second this bug: Also occurs in Postman 6.4.2 on Windows 10.

**Comment by elephantchau** [comment] 2018-12-13 07:26
+1 IanCampbellCode
Postman v6.6.1 on windows 7 still able to reproduce the bug

**Comment by numaanashraf** [comment] 2019-04-04 14:09
Duplicate of #2940

**Closed as completed by numaanashraf** 2019-04-04 14:09 UTC
Labels: bug, user-interface
