### ISSUE TITLE
Postman Collection runner duplicates query paramaters

### ISSUE THREAD

**Issue by geraldbaeck** [a85/POSTMan-Chrome-Extension#3262] opened 2017-07-11 19:11 UTC
I have a similar problem as described in  issue #3141

PASSES manual post:

{{url}}/niu/image?imageUrl=https://some/path/to/image/cb5999d6de7c44deb8750f0ee9edd1a2.png&employeeID=0ba9916e-e305-4df6-b318-a671013118a1

FAILS This is the requestUrl when using the test runner:

{{url}}/niu/image?imageUrl=https://some/path/to/image/cb5999d6de7c44deb8750f0ee9edd1a2.png&employeeID=0ba9916e-e305-4df6-b318-a671013118a1?imageUrl=https://some/path/to/image/cb5999d6de7c44deb8750f0ee9edd1a2.png&employeeID=0ba9916e-e305-4df6-b318-a671013118a1

App Details:

Postman for Mac
Version 5.0.2
MacOS Sierra 10.12.5

**Comment by prashantagarwal** [comment] 2017-07-12 11:40
@geraldbaeck Hmm, I was unable to reproduce this. Can you try to reproduce this with `GET` request in Postman Echo collection. Just add these query parameters to the `GET` request and see if this happens again.

**Comment by geraldbaeck** [comment] 2017-07-13 13:26
sorry it was a POST request

**Comment by 7omasz** [comment] 2017-09-08 03:48
I have the same issue. `GET`/`POST` tests fail with duplicated parameters in collection runner and monitors unless I uncheck parameters, which then breaks the manual tests.

Postman for Mac
Version 5.2.0 (5.2.0)

**Comment by 7omasz** [comment] 2017-10-16 23:06
FWIW url encoding the parameters outside out postman resolves the issue.

**Comment by sdnts** [comment] 2017-10-18 08:59
Hi @7omasz, we've pushed out a fix for this with 5.3.0, can you try updating your app to see if this is still an issue?

**Comment by 7omasz** [comment] 2017-10-19 00:07
@madebysid I'm already on 5.3.0. Updated to 5.3.1. The issue persists.

**Comment by a85** [comment] 2017-12-11 14:48
Please let us know if it still persists in 5.5

**Closed as completed by a85** 2017-12-11 14:48 UTC
Labels: pending-close
