### ISSUE TITLE
After 6.2.3 update postman wont launch - error fetching user information stops any use of program

### ISSUE THREAD

**Issue by NeilCrerar** [a85/POSTMan-Chrome-Extension#4974] opened 2018-08-06 10:16 UTC
## App Details:

```
Postman for Windows
Version 6.2.3
Windows 10 / x64
```

## Issue Report:
Immediately following the autoamtic update to v6.2.3 widows postman app has stopped working and will not launch correctly.
Instead of getting to the main UI it gets stuck at the launch screen with the three circles and does not progress.
![image](https://user-images.githubusercontent.com/29798873/43711122-a41fccaa-9969-11e8-8577-58d0b871a222.png)
When view the DevTools > current View can see there is an error being reported for........
[1533550453634.log](https://github.com/postmanlabs/postman-app-support/files/2262104/1533550453634.log)
Downgraded to v6.1.4 and this issue goes away but immediately then forced to re-upgrade to v6.2.3 as no way to turn off the auto update to this version making is unusable.

**Comment by NeilCrerar** [comment] 2018-08-06 10:21
Resolved via:
  DevTools > Current View
  Application
  Clear Storage
  Clear site data

**Comment by kamalaknn** [comment] 2018-08-07 15:58
Hey @NeilCrerar

This seems to be a duplicate of #4897

**Closed as completed by kamalaknn** 2018-08-07 15:58 UTC
Labels: bug

**Comment by mailtoshrb** [comment] 2018-08-23 13:05
Immediately following the autoamtic update to v6.2.5 widows postman app has stopped working and will not launch correctly.
Instead of getting to the main UI it gets stuck at the launch screen with the three circles and does not progress.
![2018-08-23 14_00_26-window](https://user-images.githubusercontent.com/23381847/44526768-ed5b4e00-a6dc-11e8-8928-34491e16cbd8.png)

When view the DevTools > current View can see there is an error being reported 

![2018-08-23 14_01_29-window](https://user-images.githubusercontent.com/23381847/44526918-46c37d00-a6dd-11e8-83d0-eae9e0c383e5.png)


When view the DevTools > shared View can see there is an error being reported

![2018-08-23 14_02_45-window](https://user-images.githubusercontent.com/23381847/44526920-49be6d80-a6dd-11e8-91e2-e6b2043410f3.png)

Could some one Please let me know, how to resolve this issue.

I have Contacted your colleague and i have tried all her steps but still i have this issue

![2018-08-23 14_04_58-window](https://user-images.githubusercontent.com/23381847/44527008-8db17280-a6dd-11e8-819c-7722b160022e.png)


Note:When i go back to previous version which i had 5.1.2, its working fine
