### ISSUE TITLE
All requests hangs after update to 5.4 on lubuntu

### ISSUE THREAD

**Issue by wateva** [a85/POSTMan-Chrome-Extension#3889] opened 2017-12-01 10:54 UTC
## App Details:

```
Postman for Linux
Version 5.4.0
linux 4.4.0-57-generic / x64
```
## System Details:

```
user@PC:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

user@PC:~$ uname -a
Linux PC 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

## Issue Report:
After updating to 5.4 version of Postman app for Linux there are no requests which executing correctly. 
On previous versions similar problem occurred during using new pretty "Authorization" tab. It was avoided by manually adding the "Authorization" header and choosing "No Auth" option in "Type" field. But now requests don't works with any of that options (tried with "Inherit auth...", "No Auth" and "Basic Auth").
Judging Fiddler or Postman console no request coming from postman to proxy-server. In UI it looks like timeless loading with "Loading..." caption on request field and caption "Sending" on blue button.
Version 4.9.3 works good.

**Comment by SamvelRaja** [comment] 2017-12-01 11:02
@wateva We found the root cause of the issue and fixing the same, will be available in our canary channel very soon.

**Comment by kamalaknn** [comment] 2017-12-01 16:35
Hey @wateva 

We've rolled out a fix for this in our Canary channel. You can find the download link here - https://www.getpostman.com/canary

Could you try out the Canary build and let us know if this is fixed?

**Comment by wateva** [comment] 2017-12-01 17:00
Hi @SamvelRaja 
Yes, in that canary version all works fine, thanks)

**Comment by SamvelRaja** [comment] 2017-12-06 05:44
Patched up in 5.4.1 stable. Closing this.

**Closed as completed by SamvelRaja** 2017-12-06 05:44 UTC

**Comment by DaveWishesHe** [comment] 2017-12-07 10:08
An addendum to this - I continued to experience the described issue in v5.4.1 after copying the new install over the top of the old one (as I would normally do). 

To resolve, I completely removed the install and added the new one back in.

**Comment by SamvelRaja** [comment] 2017-12-07 10:15
@DaveWishesHe  can you provide me the OS version?

**Comment by DaveWishesHe** [comment] 2017-12-07 11:13
@SamvelRaja absolutely, same (almost) as original bug report

```
dave@dave-entroware:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

dave@dave-entroware:~$ uname -a
Linux dave-entroware 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Postman:

```
Version 5.4.1
linux 4.10.0-40-generic / x64
```
Resolved by removing and re-adding entire directory, but a bit weird. I was a bit behind on my updates too, if that makes a difference. Upgrade was from 5.3.0 to 5.4.1.

**Comment by SamvelRaja** [comment] 2017-12-07 12:15
@DaveWishesHe  Thanks :)
