### ISSUE TITLE
 x-www-form-encoded header doesn't detach/

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#3501] opened 2017-09-08 09:32 UTC
Under body section where the content type is set to form-data by default, if the developer clicks on x-www-form-encoded, it attaches a header of content type. The problem is when you switch to other content type like raw, form-data or binary, it never detaches/removes the header content  type x-www-form-encoded. It should be detached as soon as one switches from x-www-form-encoded to other.

Postman for Mac
Version 5.2.0
Ubuntu 16.04 / x64

**Comment by prashantagarwal** [comment] 2017-09-08 12:25
@thapliyalshivam Thanks for letting us know. Will get this fixed in upcoming release.

**Comment by ghost** [comment] 2017-09-08 12:39
Leaving this reopened for you people to close it when done.

**Comment by prashantagarwal** [comment] 2018-06-29 09:52
Duplicate of #2366

**Closed as completed by prashantagarwal** 2018-06-29 09:52 UTC
Labels: bug
