### ISSUE TITLE
Decimals get truncated from json response

### ISSUE THREAD

**Issue by piel1** [a85/POSTMan-Chrome-Extension#4624] opened 2018-05-30 18:17 UTC
**Describe the bug**
Trailing zeros get truncated from the response when using 'Pretty' mode in json requests.
For example , you will receive 12 instead of 12.00
If you switch to 'Raw' mode you will see the zeros

**To Reproduce**
Send a POST request through postman which expects a JSON response
In the 'Body' section, make sure the mode is set to 'Pretty' and the language to JSON.
Look at any number in the response

**Expected behavior**
The numbers should be kept as returned by the API, without truncating decimals.

For example if you expect:
`{
            "value": 11.00,
            "taxRate": 13.20
        }`

You will instead receive:
`{
            "value": 11,
            "taxRate": 13.2
        }`

**App information (please complete the following information):**
Postman for Windows
Version 6.1.3
win32 10.0.14393 / x64

**Additional context**
This is not a big issue for most cases and is in fact mathematically correct but it can cause confusion when trying to test the formatting of your API responses. For example, if you are writing a custom serializer in your service, you would like to see exactly how numbers are returned and do not expect the 'Pretty' mode to go so far as to modify their format.

**Comment by harryi3t** [comment] 2018-05-31 12:33
~As per the [RFC for JSON](https://tools.ietf.org/html/rfc8259#section-6), this is invalid~

This seems like a good candidate for an external plugin.

**Comment by piel1** [comment] 2018-05-31 12:54
My example is about **trailing** zeros but your quote mentions **leading** zeros.
Trailing: 23.00
Leading: 0023

`{ "value": 11.00, "taxRate": 13.20 }` is certainly a valid json

**Comment by harryi3t** [comment] 2018-06-01 13:19
@piel1 You are right, my bad. Updating the comment.

**Comment by philipstratford** [comment] 2018-08-03 15:26
I've wasted hours because of this today, debugging an API that returns currency values. Didn't occur to me that my API was returning the trailing zeroes but Postman was not displaying them. Sure enough, they're there in Raw mode.

**Comment by garychapman** [comment] 2018-11-16 05:43
Please fix this, I just wasted 2 hours because of this bug.

**Comment by WurstCommander** [comment] 2019-05-10 13:44
me too...

**Comment by bisatech369** [comment] 2019-07-08 04:16
I have wasted more than 2 hours trying to figure out the problem; please fix this bug.

**Comment by saswatds** [comment] 2019-07-08 04:23
Hi @ElectronicMoney we have updated the response viewer in our latest canary https://www.getpostman.com/downloads/canary to be more accurate with responses.
Can you confirm its working for you in canary? 

This should be out in our stable release soon.

Duplicate of #1465

**Closed as completed** 2019-08-19 09:48 UTC
Labels: feature, Plugin, configurations
