### ISSUE TITLE
Postman does not handle newlines in headers well

### ISSUE THREAD

**Issue by tz** [a85/POSTMan-Chrome-Extension#4485] opened 2018-04-23 21:38 UTC
**When a newline is included at the end of a header value, this automatically causes the request to fail with the unhelpful message "Could not get any response"**

## App Details:

```
Postman for Mac
Version 6.0.10
OS X 17.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Noticed it recently
 2. Expected behaviour: 
a) Postman should throw an error when a trailing newline has been included in a header, or it should send the request with the newline escaped, or it should strip the newline. 
b) If the value of the text field is "hello\n" (where \n is actually a newline), then when the caret is on the right side of the "o", pressing the right arrow key or the down arrow key should take the caret to the next line instead of tabbing to the "description" box.
c) The newline should appear in the "code" popup (the curl request). Its disappearance from the popup makes debugging this problem more difficult.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

## Steps to Reproduce
1) Create a new request
2) GET en.wikipedia.org/wiki/Water
3) Add a header "my-header" with value "hello"
4) Execute the GET, notice that the expected HTML page is returned
5) Now copy/past a newline character from a text editor at the end of "hello"
6) Observe that the "value" popup gets taller
7) Execute the GET
8) Postman says "could not get any response"

**Comment by Ncifra** [comment] 2018-05-15 12:28
I have actually noticed this anywhere in a header value. Input like this:

```
applicatio
n/json
```

**Comment by lrtanner** [comment] 2018-06-26 20:26
👍  on this. This is a serious issue

**Comment by kamalaknn** [comment] 2018-07-04 08:17
Hi everyone,

I'm leaving my thoughts here.

Newline is not a valid character in a header. That's the reason the request fails. Auto-escaping the header value or trimming it is not an ideal option. We do not want to change any input provided by the user.

However, I can understand that this is not a very ideal experience.

We are doing a couple of things to improve the experience here.

1. The actual failure is logged in the postman console as `Error: The header content contains invalid characters`. We can add this error message in the response view section.
2. Like you mentioned, we can add a UI warning next to the headers to highlight special characters

I'm also creating a bug to track the `code generator` removing trailing newline.

Thanks for the feedback.

**Comment by cypher0six** [comment] 2018-09-21 19:05
> Newline is not a valid character in a header

Are you saying that you cannot have HTTP Header field values that span multiple lines? Because if that is the case, then that is not really true. HTTP Headers can and do support the field value spanning multiple lines. The value on the new lines need to be preceded by a space or a tab, but it is supported. See RFC2616 Section 4.2 (https://tools.ietf.org/html/rfc2616#section-4.2).

Not that this feature request makes any sense, but Postman should support the HTTP spec to its fullest, which ought to include multi-line header field values.

**Comment by codenirvana** [comment] 2018-12-24 05:52
@cypher0six You are right but RFC2616 is obsoleted by RFC7230 which deprecates such behavior:

```
Historically, HTTP header field values could be extended over
multiple lines by preceding each extra line with at least one space
or horizontal tab (obs-fold).  This specification deprecates such
line folding except within the message/http media type
(Section 8.3.1).  A sender MUST NOT generate a message that includes
line folding (i.e., that has any field-value that contains a match to
the obs-fold rule) unless the message is intended for packaging
within the message/http media type.
```
https://tools.ietf.org/html/rfc7230#section-3.2.4

Also, newline in header content is an invalid character for NodeJS HTTP parser which we use to send the request. Reference: https://github.com/nodejs/node/blob/v10.14.2/lib/_http_outgoing.js#L460

**Comment by kylewhat** [comment] 2019-05-30 19:27
Can you have a ' convert \r & \n to new lines' setting for pasting in raw text?  This is a pretty annoying chrome issue that I come across daily.    I understand it's not really a bug in postman but it could be a feature in postman.

**Comment by codenirvana** [comment] 2019-08-21 06:10
Duplicate of #3835

**Comment by shamasis** [comment] 2019-09-18 22:33
Closing this as duplicate and concentrating to ensure the request sending error messages are put straight into the response failure area.

**Closed as completed by shamasis** 2019-09-18 22:33 UTC
Labels: bug, user-interface, duplicate, product/runtime
