### ISSUE TITLE
Request sending hangs forever

### ISSUE THREAD

**Issue by zoeker** [a85/POSTMan-Chrome-Extension#2559] opened 2016-12-15 11:05 UTC
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Windows 7 64-bit Service Pack 1
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Today for the first time, probably occurred after yesterday's update.
 6. Expected behaviour: Send request, receive response. Instead request sending hangs forever.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
requester.html:1 beforeunload is not available in packaged apps.
requester.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
tester_sandbox.html:1 unload is not available in packaged apps.
jQueryNoConflict.js:1 Uncaught SyntaxError: Invalid or unexpected token
init.js:1 Uncaught SyntaxError: Invalid or unexpected token

These are before running any requests. Trying to do so doesn't add anything to the log.
 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/1173345/21221661/f21db848-c2c6-11e6-81e6-7c177a13d366.png)
![image](https://cloud.githubusercontent.com/assets/1173345/21221666/f8efc972-c2c6-11e6-9055-a4ccc5f66e72.png)

It remains in this state forever.

I haven't done anything special, just trying to run normal SOAP requests the way I did yesterday. I've changed nothing in the project.

**Comment by zoeker** [comment] 2016-12-15 11:13
Okay, deleted the extension, installed it again, imported the project and the problem's gone.

**Comment by sdnts** [comment] 2016-12-19 15:01
@zoeker That's weird. Closing, but I'll keep an eye on this.

**Closed as completed** 2016-12-19 15:00 UTC
Labels: bug

**Comment by radoslavpetranov** [comment] 2017-05-03 15:16
I just had the same issue - everything was working fine yesterday and today Postman just magically stopped working (i.e. getting stuck in "Loading.." whatever requests I made - GET, POST, DELETE..). I reinstalled the extension and it works now.

**Comment by RajatGoyal** [comment] 2017-05-21 12:12
This keeps happening to me too, It suddenly stops working (chrome app) and works fine after reinstallation.

**Comment by jm2242** [comment] 2017-06-26 04:31
had the same problem - stopped working, reinstalled, started working.

**Comment by McGern** [comment] 2017-08-22 12:39
Exactly the same scenario for me. Came here, read the posts, reinstalled, it started working.

**Comment by sdnts** [comment] 2017-08-22 13:43
Are you guys using the interceptor? We saw a bug some time ago that caused the Interceptor's queue to misbehave, causing this. Updating the interceptor fixed the issue. Can you guys also force update all your Chrome extensions and see if the problem reoccurs? Reinstalling the app just clears this queue so it starts working again.

Also, can you guys try this on the native apps as well? While the interceptor does not work with the native apps, it has a dedicated cookie manager that should serve just as well. I'd recommend shifting anyway, since Chrome apps will be deprecated by Google later this year.

**Comment by jric** [comment] 2017-11-29 00:08
After installing the native app, I had to uninstall the chrome extension, and then these symptoms cleared for me.

**Comment by blairg23** [comment] 2017-12-04 21:08
Had to reinstall native app to resolve problems on native app.

**Comment by tennisoctocat** [comment] 2017-12-19 00:17
Same here-- Reinstalling fixes the problem. Thanks everyone for commenting that it works!

**Comment by adlaws** [comment] 2018-02-06 04:21
Again, same here - I had to actually _delete the application directory first_, then do a fresh install, rather than just a reinstall. My first attempt with a simple "reinstall over the top" didn't fix anything.

**Comment by anne-lydon** [comment] 2018-02-07 08:59
A restart seems to have done it for me. I'm using the native app on Mac.

**Comment by yubing24** [comment] 2018-02-13 05:26
Same problem. I am using the native app on Ubuntu. Restart didn't always help.

**Comment by hielfx** [comment] 2018-02-22 20:31
Removing the directory and installing it made the native app work again on ubuntu

**Comment by blairg23** [comment] 2018-02-24 23:39
Same for me, removing directory and reinstalling works for me.

**Comment by raducostea** [comment] 2018-03-02 09:09
For some reason Interceptor crashed. Opened chrome://extensions/ and reloaded the extension and everything was fine again.

**Comment by srinikitha09** [comment] 2018-04-03 09:07
I also have the same issue but only with few services, I mean the APIs that I have defined in my node application. Please kindly let me know, why do I have this problem?

**Comment by Zapnologica** [comment] 2018-05-21 17:45
I was using Interceptor, when I disabled this requests started working.

**Comment by tsasioglu** [comment] 2018-06-03 19:09
I had disabled interceptor in chrome but still had it enabled in postman and saw this behaviour.
Disabling it in postman was my fix.

**Comment by Ettery** [comment] 2018-07-30 08:17
I have also had this problem with the native app v.6.2.2.  Reboot didn't help I had to export my collections, uninstall, delete the app folder and re-install.  Back to normal.  Problem seemed to be triggered by a Postman update I installed.

**Comment by ScottBurfieldMills** [comment] 2018-07-31 03:49
I've also run into this issue after installing v.6.2.2. Reinstalling now to see if that fixes it.

edit: Reinstalling didn't help although I'm not confident it uninstalled properly because all of my data was still there when it installed again. What fixed it for me was logging out of my Postman account, which clears all of your data.

**Comment by kallen11** [comment] 2018-08-03 20:57
I ran into the same problem with the stand-alone 6.2.3 application.  I use Postman everyday and it stopped working today.  Attempts to reinstall it didn't help.  I fired up my old Chrome app version to continue my work.

If anybody wants to troubleshoot this issue, I currently have a broken standalone Postman along with a working Chrome App Postman.  - kallen@traust.com

**Comment by numaanashraf** [comment] 2018-08-04 07:01
@kallen11 Could you open the Postman Console (View > Show Postman Console), re-send the request and send us a redacted screenshot of the logs there?

**Comment by kallen11** [comment] 2018-08-04 18:28
There isn’t much to see.  I hit Send on a request that had been working a few days ago…

Postman says “Loading…”
[cid:image001.png@01D42BF6.B4D19410]


And then I went to see what was in the console….
[cid:image002.png@01D42BF6.B4D19410]


The day before it stopped working, I had closed a lot of the Postman request tabs.  Towards the end I did a force close (without saving).  Maybe that caused the problem.

I am currently able to successfully do a Get New Access Token for OAuth2.  But whenever I submit a Get/Post/Put, Postman just says “Loading…”.  I never see the request come across on the server side.

Thanks,
Ken

**Comment by jldanford** [comment] 2018-08-06 17:29
I'm experiencing the same issue with 6.2.3. OAuth works fine but the request hangs. I've tried using GET and POST on several endpoints, using OAuth 2.0 and no auth, same result. The console doesn't show anything - no traffic, no logging, nothing - during the request but does log the OAuth POST.

The problem started today, the first time I tried to use it. I've logged off/logged on, cleared old sessions, cleared cookies, and rebooted my system, but no change. I was successfully using Postman three days ago. I use it daily and have never had this problem

**Comment by MartinHsu** [comment] 2018-08-07 02:25
I encounter same issue as @jldanford  from 8/6 ,2018
Postman hang on request sending, no any log on Postman console. I have tried re-install but no work.

Postman version:  v6.2.3
OS: Windows 10 v1803

Please help, thank you

**Comment by lejewk** [comment] 2018-08-08 05:21
I also have same problem. version 6.2.3, window10

**Comment by Anwar-Ul-Haq** [comment] 2018-08-09 09:11
Having same issue for version 6.2.3 on  window10.
Tried re-installing few times but that did not help.

**Comment by Falx** [comment] 2018-08-09 09:16
same issue here!

**Comment by Anwar-Ul-Haq** [comment] 2018-08-09 15:23
@Falx bug reported

**Comment by gdlin** [comment] 2018-08-10 21:57
I'm having the same problem. I'm currently using Basic Authentication and that's it. The Get's response is a tiny json. Attaching captures of the console.

![screenshot from 2018-08-10 18-53-03](https://user-images.githubusercontent.com/1306672/43983107-439db0c2-9ccf-11e8-813d-79cdecd0bba4.png)
![screenshot from 2018-08-10 18-53-06](https://user-images.githubusercontent.com/1306672/43983110-46342ad2-9ccf-11e8-8847-2334abe3c9ce.png)

EDIT: Postman native app for linux version 6.2.3

**Comment by rahul-jain-7893** [comment] 2018-08-21 10:24
Before making request please check the server is accessible or not, by commanding telnet...
Example - In command prompt or terminal type --> telnet **IP Port**

**Comment by kEph13** [comment] 2018-09-13 18:03
I'm having the same issue - v6.3 Windows x64. Same behavior as the above screenshots

**Comment by kallen11** [comment] 2018-10-12 22:06
Possible Solution:  The issue might be related to the "No Environment" drop down at the top right of the Postman page.  I've occasionally had success by clicking on the field and/or re-selecting No Environment from the drop down.  The problem reappeared today, so I created a new environment (using the eyeball icon to the right of the environment dropdown).  I didn't include any environment variables.  It is just a dummy environment, but it solved the problem for me.

Hope this helps others....
Ken

**Comment by ghost** [comment] 2018-10-25 10:05
I have this issue with version 6.4.4, creating dummy environment didn't help...
Removing it and installing again fixed it. No need to change anything in ${HOME}/.config/Postman

**Comment by mturner** [comment] 2018-10-28 16:07
I too am having this problem, strangely it seems that when I post a json payload it fails, but when i remove the payload and simply post it works just fine.  Reinstalling has had no impact for me.  OSX 10.14 w/ Postman 6.4.4 osx app.  

I am intermittently getting data in the developer tools and have seen nothing meaningful to report around the hangs.

**Comment by drxw** [comment] 2018-10-28 19:03
I experienced this issue because I was not handling my POST request correctly.

Simple JSON post request to `/car` endpoint in Postman:
`{ "car": "honda", "year": 1992}`

My router:
```
router.post('/car', body-parser, (request, response) => {
   console.log(request.body);
}) 
```

I could see my request on my server console, but the SEND process would _hang_ on Postman.

If you made a trivial mistake like me, I fixed this by just sending a response within the router:
```
   console.log(request.body);
   response.send(request.body);
```

**Comment by breale1008** [comment] 2018-11-09 19:52
I am experiencing a similar issue, but it only occurs when I'm attempting to upload a file. Related endpoints that don't require file upload on the same server work just fine. Also, my coworkers don't experience any issues with the exact same request that hangs for me, so it's got to be something on my side.

As above, postman console doesn't have much of interest (displays a perpetual "Response Headers: Loading..." message). Any ideas? 

Edit: using native mac app, no interceptor. Also, I can hit the endpoint without a file attached to the request (and get the appropriate error response back) fwiw.
More edits: current version 6.5.2 (upgraded today from 6.4.something, which was also affected). Have tried reinstalling, restarting, no dice. I have never logged into postman (another poster mentioned logging out/in solved it). Let me know if you need more info :)

**Comment by mfarhat437** [comment] 2019-03-04 17:22
i am using the native app latest version and it was working good but suddenly the same problem appeared i tried to reinstall it but nothing changed an tried the environment variables for postman and still the problem....what can i do...please help

**Comment by taqvi** [comment] 2019-04-10 07:52
I solved this by just **Deleting all Cookies**. Same happens whether it is Postman or Insomnia. In Postman cookies are at top right corner below Send button and in Insomnia Cookies are in top left tab after Environment drop down. With this solution I'm up and running.

**Comment by m1m6** [comment] 2019-04-30 12:04
solved by re-enable the interceptor extension on chrome

**Comment by sidartdesai** [comment] 2020-03-06 12:32
Tried reinstalling 
Tried removing .config/postman folder
Restarted system
reinstalled postman

still postman app not working in Manjaro.
can anyone suggest a fix ?

but web extension on chrome works ... can someone explain this ?

**Comment by jamiladeveloper** [comment] 2020-05-13 13:13
For me the interceptor was running. I had to stop the interceptor.

**Comment by SairaBeg** [comment] 2021-04-13 22:12
I had this same issue, and shutting down, and starting up my computer fixed this

**Comment by Merati22** [comment] 2022-01-24 08:25
Same Problme!
Thre Only Solution that works for me was restarting computer..!

**Comment by shubhbhargav** [comment] 2022-01-28 10:44
@Merati22 Is this a recurring problem for you? If yes, can you please file a new ticket with some more details about the OS as well as any particular steps to reproduce the issue?

**Comment by cyrionp** [comment] 2023-01-02 07:35
I had same issue while I was using Visual Studio 2022 for Mac debugging. .NET Web Api exe should be terminated as it is running as a console. Then restarting the Web Api may fix this issue. It's worked for me.
