### ISSUE TITLE
Black Screen inside Postman while getting 35Mbytes file (was working before windows/software/drivers update)

### ISSUE THREAD

**Issue by IMAdvisorLB** [a85/POSTMan-Chrome-Extension#5288] opened 2018-10-02 09:33 UTC
**Describe the bug**
Postman was working normally until possibly a windows update happened.
Getting a large file (35Mbytes+) using GET and Send/Send and Download does not work anymore. It reaches the point where it is about to propose to save the file and it gives a black screen inside the Postman window.
Same thing is happening in PostmanCanary (though in Canary it is white/beige screen)
I tried to disable GPU and such with no success.
Small files work normal.

**To Reproduce**
1-Getting a large file (35Mbytes+) using GET (Send/Send and Download)
2-See black window right before the prompt to choose file name.

**Expected behavior**
Normally we should be able to save the json file.
(we are still able to get the json file using wget)

**Screenshots**
![image](https://user-images.githubusercontent.com/36759520/46340405-ff1a0480-c63d-11e8-8493-3dae6dfef1b3.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.3.0 and 6.4.0-1
 - OS: Windows 10 Pro Build 17134

**Additional context**
The problem is probably because of the update done by windows/other updated hardware/software related updates

**Hardware**
Laptop Lenovo Ideapad 320-15IKB Type 81BT
Intel Core i5-8250U 64bit 8GB RAM
Intel UHD Graphics 620
AMD Radeon 530

**Comment by maxcr** [comment] 2018-10-02 20:05
also happening to me. Its because of the electron version.

**Comment by jzabroski** [comment] 2018-12-03 21:19
@maxcr  How did you determine it was because of the Electron version?

**Comment by m3dbedb** [comment] 2019-03-06 06:10
The issue is actual for postman 7.0.4 under windows 7 32 bit

**Comment by m3dbedb** [comment] 2019-05-24 12:34
The issue is actual for postman 7.1.1 under windows 7 32 bit

**Comment by a85** [comment] 2019-06-12 19:21
We are making some fundamental improvements to Postman's response rendering including using the Monaco editor for better memory optimization and rendering speeds. You can try out these updates in the Canary channel here: https://www.getpostman.com/downloads/canary

<img width="1790" alt="Screenshot 2019-06-12 12 19 53" src="https://user-images.githubusercontent.com/653409/59379813-72ffc700-8d0c-11e9-9da4-5c9ce0492dc4.png">

You can test it out with an API that we have created on the Postman Echo service. Examples here: https://documenter.getpostman.com/view/55577/S1ZudWWm?version=latest

**Comment by shamasis** [comment] 2019-08-06 09:23
The ability to render large responses has landed in production. Closing this issue.

**Closed as completed by shamasis** 2019-08-06 09:23 UTC
Labels: bug, performance, product/runtime

**Comment by matthewcoxx** [comment] 2020-02-23 07:27
This seems to still be an issue in build 7.18.x. MacOS, full permissions. 

Download file size: 108MB json file.

Screen turns black.

What are the current limitations on download?

**Comment by ctunikuma** [comment] 2020-04-03 16:55
Yes I am running Version 7.21.2 (7.21.2) and came cross this issue today (trying to save a json file with size of 101MB).

**Comment by vikiCoder** [comment] 2020-04-04 08:16
Hi @ctunikuma, @matthewcoxx,

We are tracking this issue with large downloads here: https://github.com/postmanlabs/postman-app-support/issues/7871. Please follow https://github.com/postmanlabs/postman-app-support/issues/7871 for updates. The fix is on the way. I'll update the thread as soon as the fix is out.
