### ISSUE TITLE
[Bug] URL query param used for authorization defined at the collection level is automatically duplicated and inserted every time a new change for the request is saved

### ISSUE THREAD

**Issue by SonNg2k** [a85/POSTMan-Chrome-Extension#10130] opened 2021-07-17 08:56 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the Issue

1) I define an API key at the collection level in the 'Authorization' tab. This API key is then added to all requests within the collection as a query param `access_token` in the URL.

2) Everytime I make a change to any of the query params for a particular request inside the collection, the `access_token` defined at the collection level is automatically added  (even though there is already one `access_token` added by Postman in the first place)

Every time I save a change for a particular request, the same API key flowing from the collection is automatically duplicated and inserted by Postman. The best way to understand the bug is to see my GIF below.

### Steps To Reproduce

See the attached GIF

### Screenshots or Videos

![Steps to reproduce the bug](https://user-images.githubusercontent.com/29955043/126032606-b3c85489-e208-48fc-81df-e82ac5135306.gif)

### Environment Information

```markdown
- Operating System: macOS Big Sur 11.4 (20F71) - Intel Chip
- Platform Type: MacBook Pro (16-inch, 2019)
- Postman Version: 8.8.0
```

**Comment by timbochamp** [comment] 2021-07-17 15:11
Hi @SonXuanNguyen2k , thanks for the report! I think this is a duplicate of #10094 if you can follow the resolution there? I'll mark this as closed, but feel free to reopen if you feel your issue is different

**Closed as completed by timbochamp** 2021-07-17 15:11 UTC
