### ISSUE TITLE
Support groups in tabs (similar to chrome tab groups)

### ISSUE THREAD

**Issue by jagz-hbh** [a85/POSTMan-Chrome-Extension#10866] opened 2022-04-27 06:22 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Having tab groups will help out in preventing chaos when we have opened multiple tabs. Tab groups help with organization.

### Describe the solution you'd like

Having tab groups similar to google chrome.

**Comment by DannyDainton** [comment] 2022-04-27 10:50
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9615

**Closed as completed** 2022-04-27 10:51 UTC
Labels: feature, duplicate
