### ISSUE TITLE
OAuth 1.0 , no callback field.

### ISSUE THREAD

**Issue by amateusz** [a85/POSTMan-Chrome-Extension#2173] opened 2016-07-10 14:51 UTC
1. Postman Version:
2. Chrome app
3. OS..Win 10.. doesn't apply
4. Is the Interceptor on and enabled in the app: doesn't matter
5. Did you encounter this recently, or has this bug always been there:
6. Expected behaviour:
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

In "Authorization" tab:
The form for OAuth 1.0 is missing "oauth_callback" field. According to OAuth docs it is needed to get temporary credentials. ("Temporary Credentials Acquisition" section [http://oauth1.wp-api.org/docs/basics/Auth-Flow.html](url))

When added it manually, then it works.
Sorry if I'm wrong, I'm quite new to web-dev, but I think that that issue is indeed correct.

**Comment by tyteen4a03** [comment] 2016-07-27 08:40
+1

**Comment by tyteen4a03** [comment] 2016-07-27 08:42
Duplicate of #1240 and #283 (3 years ago!)

Can we get this added please?

**Comment by pabloviquez** [comment] 2016-10-10 19:07
Any update on this?

**Comment by a85** [comment] 2017-04-08 20:31
Closing as duplicate for now. We are working on an overhaul of auth systems.

**Closed as completed by a85** 2017-04-08 20:31 UTC
Labels: feature, Auth

**Comment by bradparks** [comment] 2018-07-25 11:53
Insomnia supports callback, and is an opensource cross platform REST client:

https://github.com/getinsomnia/insomnia
