### ISSUE TITLE
[feature request] Expand the "Select a collection or folder to save to:"

### ISSUE THREAD

**Issue by Pederytter** [a85/POSTMan-Chrome-Extension#3833] opened 2017-11-20 10:11 UTC
## App Details:
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64

After working with Postman the past few months and added hundreds saved of request inside different folders its beginning to get quite annoying with such a small "folder view" when you save a request. Also when you scroll there is times when you jump over a folder, so you have to use the scroll bar on the side to slowly find the right folder.

It doesn't expand on full view either, which were my first though where it could be implemented.

**Comment by prashantagarwal** [comment] 2017-11-20 12:05
Duplicate of #3620 . Closing it. will help us in better tracking this issue.

**Closed as completed by prashantagarwal** 2017-11-20 12:05 UTC
