### ISSUE TITLE
Environment Value not substituted for Key when used in token request "Token Name" field.

### ISSUE THREAD

**Issue by deanjott** [a85/POSTMan-Chrome-Extension#4279] opened 2018-03-05 15:45 UTC
## App Details:
Postman for Windows
Version 6.0.8
win32 10.0.16299 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
          Present in last few versions

 2. Expected behaviour:
          The Value for the substitution parameter should appear as the token name when available 
          tokens are listed

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

 4. Screenshots 
Using an Environment definition to set variables for OAuth2 token requests. Note in the example the Value is set to "PROD"
![image](https://user-images.githubusercontent.com/20361228/36983645-7f4ce8f2-2058-11e8-94d7-9b6f70344466.png)

When requesting the token, all substitution strings are orange so they are found in the template.
![image](https://user-images.githubusercontent.com/20361228/36983746-ca7b30a4-2058-11e8-82a7-14418c1487bc.png)

The Token is provided but has token name equal to the variable substitution Key and not it's Value
![image](https://user-images.githubusercontent.com/20361228/36983820-f9853ad4-2058-11e8-8adb-ba72b2fdbb03.png)

The list of available tokens does not reflect the Value of the Key used in the template
![image](https://user-images.githubusercontent.com/20361228/36983869-229baf8e-2059-11e8-8a66-0a3e25801a0b.png)

**Comment by harryi3t** [comment] 2018-03-06 10:38
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3525

**Closed as completed by harryi3t** 2018-03-06 10:38 UTC
