### ISSUE TITLE
什么时候加上国际化多语言i18n功能啊！

### ISSUE THREAD

**Issue by 15678871232** [a85/POSTMan-Chrome-Extension#9482] opened 2021-01-28 08:44 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DannyDainton** [comment] 2021-01-28 08:53
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9440

**Closed as completed** 2021-01-28 08:53 UTC
Labels: duplicate
