### ISSUE TITLE
How to make postman waiting for pre-request script to be finished before making request?

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#3480] opened 2017-09-04 03:11 UTC
## App Details:
```
Postman for Chrome
Version 5.2.0
win / x86-64
Chrome 60.0.3112.113
```

## Issue Report:
I'm making want to make request with Environment Variable in url. In pre-request script I'm calculating and setting value for my Environment Variable. Here is the code:
```
// Getting js file with script to calculate sha256 hex:
eval(postman.getGlobalVariable("module:sha256"));
// Calculating hex for '123':
var result_hash = sha256('123');
// Setting env. variable:
postman.setEnvironmentVariable("result_hash", result_hash);
```
Then I make request like "my_url/{{result_hash}}".

The **problem is** that the request is executed **before** then Environment Variable was set: *"my_url/"*
So as a result - it fails. But next consequent absolutely equal request will be successful:
*"my_url/a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"*

## Question:
How can I make postman waiting for Environment Variable to be filled (or equal to some value) before executing request?

**Comment by sdnts** [comment] 2017-09-04 12:23
Hi @sergeidyga This will be a problem with the Chrome apps. I'd suggest moving to our [native apps](https://getpostman.com/apps), which has better support for async actions like yours.

Additionally, the prerequest / test script sandbox includes CryptoJS, so you can use that as well. Please let me know if these do not solve your issue, and I'll reopen.

**Comment by brendankeane** [comment] 2017-09-06 21:50
I would still like to see this. I have the native app and I can see a pre-request script start, and while it is processing, the main postman request is made before the pre-request finishes.  Since I am calling a remote service, and parsing the response in the pre, it takes a couple hundred ms.  The main does not wait, and errors as the env variable is null due to the pre still processing.  If there is a way to fix that, please let me know.  If not, I would like to see this request put somewhere in the build pipeline.  thanks

**Comment by sdnts** [comment] 2017-09-07 06:17
@brendankeane The pre-request scripts do respect timers and async actions (only on Native apps, though), when a request is made using `pm.sendRequest`
Maybe we need to investigate this. Can you supply a pre-request script that behaves this way?

**Comment by ghost** [comment] 2017-09-07 06:20
> This will be a problem with the Chrome apps

The problem occurs also in native app. Checked for: 
Postman for Windows
Version 5.2.0
win32 10.0.10586 / x64

> test script sandbox includes CryptoJS

thx, it works faster

 But in other cases of long pre-request scripts (like @brendankeane  have mentioned) the issue is still actual. Need to make Postman waiting for all pre-request scripts to be done before making request.

**Comment by rygood** [comment] 2017-09-07 18:12
Yes, this seems to be a regression in 5.2.0. I and another developer on my team are having the same issue with the native app.

Postman for Mac
Version 5.2.0
Mac OS 10.12.6

**Comment by akutruff** [comment] 2017-10-02 16:07
Running into this issue as well with sendRequest async handler in pre-request.  It appears that the main request for the test starts executing before the pm.sendRequest() is completed.  Here's a simple example that gets a token and tries to set an environment variable.

```
pm.sendRequest({
    url: 'http://api.example.com/connect/token',
    method: 'POST',
    header: 'Content-Type:application/x-www-form-urlencoded',
    body: {
        mode: 'raw',
        raw: 'grant_type=password&client_id=client&client_secret=secret2017&username=bob&password=foo'
    }
}, function (err, res) {
  
    var response_json = res.json();
    var access_token = response_json.access_token;

    pm.environment.set('access_token', access_token);
    
    console.log(access_token);
});
` ``

**Comment by kamalaknn** [comment] 2017-10-05 08:51
@akutruff the main request will always wait for any asynchronous scripts to complete in the pre-request script.

Can you share a collection or a request where you are not seeing this?

**Comment by akutruff** [comment] 2017-10-05 12:45
@kamalaknn I'm having trouble reproducing this, but we switched our auth servers which return almost instantly.  It seems that this is an issue in other cases per @rygood.  The above example was the case where I was seeing async issues.  

Also, this blog post adds confusion to the issue:  
http://blog.getpostman.com/2017/10/03/send-asynchronous-requests-with-postmans-pm-api/ 

That post makes it sound like the expected behavior is to not have the request wait.  

If, ultimately, Postman is going to wait for all sendRequests to complete before moving on to the main request, that makes the most sense.  However, if there is presently an issue I'd like to know.

On that note, if the callback for a sendRequest also makes sendRequest will that also be assured to complete prior to the main request?  (I have not tried this use case, but it may be coming in the future.)

**Comment by kamalaknn** [comment] 2017-10-05 12:58
@akutruff Any asynchronous script in the `pre-request` script will wait to complete before the main request starts. This holds true for `sendRequest` in the callback of another async function as well. 

If you see that requests do not wait for the pre request scripts to complete, please report to us with a reproducible collection and we'll take a look.

**Comment by mailtogj** [comment] 2017-11-21 05:21
I am trying to create a dictionary object of the response json's using postman's pm api sendRequest.

Wrote a recursive function to get all the responses but the problem is the response dictionary object population happens way before even the response comes back.

Is there any way to wait the dictionary population before each of the respective response is received so as to capture the response within the dictionary object ?

```
var respDictionary  = {};

getResponses (listOfUrls);

console.log("respDictionary: ");
console.log(respDictionary);

function getResponses(urlList) {

    if (typeof urlList === 'string') {
        urlList = urlList.split(' ');
    }
    _url = urlList[0];

    var call = {
        url: _url ,
        method: 'GET',
        header: {
            "Authorization": `Bearer ${token}`,
            "Content-Type": "application/json"
        }
    };
    urlList.splice(0, 1);

    pm.sendRequest(
        call,
        function (err, res) {
        if (err) {
            console.log(err);
        } else {
            if (urlList.length === 0) {
                return;
            }
            try {
                respDictionary[_url] = res.json();
            } catch (e) {
                console.log(err);
            }
            getResponses(urlList);
        }
    });
    console.log(respDictionary);
}
```
Output is:
```

respDictionary:
Object:{}
//further, pm request responses are listed as they are received - not at all in order
```

**Comment by qpi** [comment] 2018-02-05 17:00
I have the same issue. If I click on "code" link to see the Postman's raw HTTP request, it shows me that the token is properly added to the URL, but I receive invalid token response from the API.
So I was curious and that's why I installed Fiddler to see what happens in the background and it showed me that the token was missing from the URL. :(

**Comment by fatihtekin** [comment] 2018-08-09 18:59
I had the same issue as @qpi because I forgot to set Authorization to `No Auth`

**Comment by numaanashraf** [comment] 2019-03-26 09:03
With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you are still facing this issue and have more information to help us debug this - we'll be happy to reopen the issue.

**Closed as completed by numaanashraf** 2019-03-26 09:03 UTC
Labels: bug

**Comment by n370** [comment] 2019-04-02 15:55
I'm seeing this issue when wrapping pm.sendRequest in a promise.

```
function request(options) {
    return new Promise(function(resolve, reject) {
        pm.sendRequest(options, function (err, response) {
            if (err) return reject(err);
            resolve(response);
        });
    });
}
```

**Comment by mrdulin** [comment] 2019-04-30 08:45
same issue.

**Comment by duffpl** [comment] 2019-09-30 11:40
Can confirm. Wrapping sendRequest in Promise and then setting environment variable on resolve doesn't work. I've got 2 promises in Promise.all().

**Comment by Lampei** [comment] 2020-10-30 20:34
@numaanashraf it looks like this needs to be reopened.  There is reproducible code posted on April 2, 2019.

**Comment by erhhung** [comment] 2021-06-08 21:21
In case anyone reads this looking for a solution, here are some functions and example code to work around this issue:

_Collection pre-request script:_
```js
// export common utility functions
pm.globals.set('util', String(() => ({

    // use the open interval hack to wait until async
    // operations are done before sending the request
    // in a pre-request script
    waitUntilDone(promise) {
        const wait = setInterval(() => {}, 300000);
        promise.finally(() => clearInterval(wait));
    },

    // promisified pm.sendRequest()
    sendRequest(req) {
        return new Promise(
            (resolve, reject) => pm.sendRequest(req, (err, res) => {
                if (!err && res.code / 100 < 4) return resolve(res);
                let message = `Request "${req.url||req}" failed (${res.code})`;
                if (err?.message) message += `: ${err.message}`;
                reject({message});
            }));
    },

    // load external library modules in order,
    // then return this[thisProp] or just this
    async loadModules(urls, thisProp=undefined) {
        const thisKeys = Object.keys(this);
        (await Promise.all(urls.map(this.sendRequest)))
            .forEach(res => eval(res.text()));

        const thisObj = _.omit(this, thisKeys);
        //console.log('KEYS: this', Object.keys(thisObj));
        return !thisProp && thisObj || thisObj[thisProp];
    },
})));
```

_Main request pre-request script:_
```js
// import common utility functions
const util = eval(pm.globals.get('util'))();

util.waitUntilDone((async () => {
    const {moment} = await util.loadModules([
        'https://momentjs.com/downloads/moment.min.js',
        'https://momentjs.com/downloads/moment-timezone-with-data.min.js',
    ]);
    const tsToDate = ts => {
        const date = new Date(ts * 1000);
        let   str  = moment(date).format('L hh:mm:ss');
        const tz   = moment.tz(date, moment.tz.guess());
        const dur  = moment.duration(date - new Date());
        return `${str} ${tz.zoneAbbr()} (${dur.humanize(true)})`;
    };
    pm.variables.set( 'issued_at', tsToDate(jwt.iat));
    pm.variables.set('expires_at', tsToDate(jwt.exp));
})());
```
