### ISSUE TITLE
Collection Runner: select which requests to run within the same folder

### ISSUE THREAD

**Issue by gekonwi** [a85/POSTMan-Chrome-Extension#5578] opened 2018-11-28 02:38 UTC
**Is your feature request related to a problem?**
We often need to run load tests, e.g. sending the same request 200 times and checking whether all 200 alerts reach the iOS app. We use the Collection Runner but we cannot run single requests, only collections / folders.

**Describe the solution you'd like**
In the Collection Runner, in the top section, where it says "choose a collection or folder", add checkboxes in front of each collection / folder entry. Only the selected elements will be run. In particular, this would allow to select the one request we want to run X times. Per default, everything is selected. Add buttons like "Select All" and "Unselect All".

**Describe alternatives you've considered**
We end up creating a sub-folder for each request so we can run this one-request folder X times in Collection Runner. It annoys all of us 100 times a day due to the extra nesting level, making the collection folder tree harder to read and requiring hundreds of extra-click to unfold those ugly one-request leaf folders.

**Comment by gekonwi** [comment] 2018-12-27 20:46
@numaanashraf - any updates on this?

**Comment by TonyTrupp** [comment] 2019-04-03 18:13
sounds like a similar request to this one: 
https://github.com/postmanlabs/postman-app-support/issues/5578

**Comment by saswatds** [comment] 2019-05-21 19:43
Duplicate of #6360 #2392

Closing this issue to track the feature at a single place

**Closed as completed by saswatds** 2019-05-21 19:43 UTC
Labels: feature, collection-runner, product/runtime
