### ISSUE TITLE
TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by LayMuiToh** [a85/POSTMan-Chrome-Extension#6802] opened 2019-06-28 12:15 UTC
**Describe the bug**

**To Reproduce**
Run the post request in postman
GET http://{{hostname}}:8086/cm/x/response?conversationId={{convoId}}
Click the send
The body return has the content array
[
    {
        "conversationId": "xxxxx",
        "event": "UI",
        "message": {
            "content": [
                {
                    "command": "navigation",
                    "namespace": "CT-InputTextField"
                },
                {
                    "command": "resultSet",
                    "data": {
                        "entity_type": "customer",
                        "hint": null,
                        "knowledge": [],
                        "title": "Please provide your customer name:"
                    }
                }
....

In my test section, I do a test assertion in the field on content array
let responseSchema = {
    "event": "UI",
    "message": {
        "content": [
            {
                "command": "navigation",
                "namespace": "ConversationTree-InputTextField"
            },
            {
                "command": "resultSet",
                "data": {
                    "entity_type": "customer",
                    "hint": null,
                    "knowledge": [],
                    "title": "Please provide your customer name:"
                }
            }
        ]
    },
    "target": "stella.lens"
}

pm.test('Check Customer Lookup InputTextField', () => {
    let jsonData = pm.response.json();
    pm.expect(jsonData.message.content[1].data.title).to.be.equal(responseSchema.message.content[1].data.title);

**Expected behavior**
it should PASS
**Screenshots**
but it gives an assertion Error
TypeError: Cannot read property 'content' of undefined

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] Native app
 - Postman Version [e.g. 6.0.1] 7.2.2
 - OS: [e.g. macOS High Sierra 10.13.2]10.14.5

**Additional context**

**Comment by bhargavkaranam** [comment] 2019-06-28 12:30
Hey @LayMuiToh,
Looks like your response is returning an array of objects and you're not accessing it correctly in your test script. Closing this issue as this is not a bug with Postman itself and we would recommend posting this question on https://community.getpostman.com instead.

**Closed as completed by bhargavkaranam** 2019-06-28 12:30 UTC
