### ISSUE TITLE
POSTMAN app itself (UI not just the Runner) appending = to variables in query params Mac App

### ISSUE THREAD

**Issue by mcs130** [a85/POSTMan-Chrome-Extension#4039] opened 2018-01-08 21:53 UTC
## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:  Issue was not there until latest 5.5.0 update was made.
 2. Expected behaviour: When setting query parameters based on Environment variables associated with a SELECTED Environment config file - it should just add the exact string without any mutations/additions
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable): NA

**STEPS:** 

A.  Create a operation in POSTMAN (a GET operation let's say) inside a Collection
B.  Set up the URL to use an environment variable like this: http://{{hostname}}/maypp/core/management/api/categories?{{params}}
C.  Select environment such that env variable {{params}} gets set to some appropriate name-value pair
**parmas**: dept=25&products=myproduct
D. Click the Code link on right to open "Generate Code Snippets" dialog and you see WHAT IS EXPECTED in the URL that "looks" correct
GET maypp/core/management/api/categories?dept=25&products=myproduct 
E.  Now Click the Send button to make the request and the call ends with an error thrown by application being tested because the URL has been corrupted w/ a trailing "=" sign...  VERIFIED intercepting the URL sent using a TCP/IP Monitor tool, you see it like this:
GET maypp/core/management/api/categories?dept=25&products=myproduct=  **// note how the equal sign is appended to the URL**  THIS is how the URL call is made to the server so the request is essentially broken and the intended parameter parsing fails.   

NOTE there was a SIMILAR issue reported here for Runner... https://github.com/postmanlabs/postman-app-support/issues/3181#issuecomment-347688672

now it's showing up in the POSTMAN app itself

**Comment by harryi3t** [comment] 2018-01-09 12:18
@mcs130 This is a known bug and the fix is already in progress.
You can expect this to work in the next version :)

Also, this is duplicate of https://github.com/postmanlabs/postman-app-support/issues/3991
please subscribe to the original issue for updates.

**Closed as completed by harryi3t** 2018-01-09 12:18 UTC
