### ISSUE TITLE
Search the variable in Environment quick look

### ISSUE THREAD

**Issue by rathodamol** [a85/POSTMan-Chrome-Extension#6562] opened 2019-05-21 09:31 UTC
Current situation: 

My environment quick look screen has got lots of variables and at times I have to scroll too much to go to the exact variable. 

Expected: A small search input box to search the variable name which will populate the results (Like Typaheads or something). It can increase the usability.

**Comment by m3dbedb** [comment] 2019-05-24 12:42
Also it would be good to be able to mark environment/global variables favourite to move them to top

**Comment by rathodamol** [comment] 2019-06-12 10:23
Hello @sujayvenaik  

Are you planning to do something on the above mentioned improvement?

**Comment by DannyDainton** [comment] 2020-08-10 06:26
Duplicate of #8530

**Closed as completed** 2020-08-10 06:26 UTC
Labels: feature, Environments, product/runtime
