### ISSUE TITLE
Double clicking the window title bar does not adjust to macOS window settings

### ISSUE THREAD

**Issue by TVke** [a85/POSTMan-Chrome-Extension#11482] opened 2022-11-24 11:07 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When double clicking on the title bar of the window, the screen scales to a smaller/bigger version.
As this behaviour is adjustable in the macOS Settings app, it should respond to it accordingly.

### Steps To Reproduce

Open the "Settings" app
Go to "Desktop and Dock"
Change the item "Double-click a window's title bar to" to "Minimize"

Open the "Postman" app
Double click the title bar

It resizes but does not minimize as expected.

### Operating System

macOS

### Postman Version

10.4.5

### Postman Platform

Postman App

**Comment by laaser-mself** [comment] 2023-09-01 18:12
This is a bug that I've previously reported as well and it's BLOODY ANNOYING.   Please fix it.   @jviotti   IT IS NOT A FEATURE.  IT *USED* to work properly and then it STOPPED working.  Please UNLABEL feature and LABEL BUG!!!!

**Comment by dsanders11** [comment] 2024-04-19 03:59
Duplicate of #11148.

**Closed as not planned by dsanders11** 2024-04-19 03:59 UTC
Labels: feature, platform/macOS, product/desktop-foundation, component/native-integration
