### ISSUE TITLE
Matching example responses with query parameters does not work in mocks

### ISSUE THREAD

**Issue by ssallmen** [a85/POSTMan-Chrome-Extension#10552] opened 2022-01-08 12:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Matching algorithm for mocks does not work for request query parameters as described in the documentation: https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/matching-algorithm/

It was said to be implemented in Oct'19 in a discussion (https://community.postman.com/t/mock-server-responses-matching-request-query-string-params/343) but it does not seem to work anymore, if it has ever worked like it should. It seems to work somehow only for one query parameter, but not at all if there are multiple query parameters.

Let’s assume I have two different example responses with exactly the same endpoint but with different values for two query parameters, and I send a request with fully matching URL (also query parameters matching one of the examples), I will always get the response from latest created example, not the one matching the query parameters.

### Steps To Reproduce

In these steps, you can use any endpoint you want, but always use the same, only query parameters differ.

1. Create a response example for query parameters `?param1=1&param2=2` for one request.
2. Create another example for query parameters `?param1=foo&param2=bar` (it does not matter if you create this for the same or different request in the collection)
3. Send a request with parameters `?params1=1&param2=2` to the mock-server url (the same endpoint, just different server name)

**Expected result:** Should get the response created in step 1 (with query parameters `?param1=1&param2=2`) because it fully matches the URL with exactly the same query parameters and their values.

**Actual result:** Will get the response created in step 2 (with query parameters `?param1=foo&param2=bar`), even when the query parameters are different and there would be an example with exactly matching query parameters available.

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.8.1
```

**Comment by grakhejapstmn** [comment] 2022-01-14 05:25
Hi, I tried to replicate the issue mentioned but the mock server seems to work fine even with multiple query parameters.
We would like some more information about the requests that you created in examples and the ones you sent.
Can you provide us the same at help@postman.com

**Comment by ssallmen** [comment] 2022-01-15 09:30
Actually I tried to replicate the issue from scratch with a new workspace and did not get the same issue either. But, then I went back to my earlier workspace and still got the same issue there. I started to wonder what could be different and noticed that I had used different kinds of query parameters, and the issue it not actually related to the number of query parameters but on what kind of query parameters I am using.

The API I am trying out, and also mocking, has some query parameters like arrays. Those parameter names have %5B%5D ([] in ascii) in their names. If I am using that hex-presentation of the characters in my request and response (even when I have only that one query parameter), then it does not work. But, if I use [] in the query parameter names in requests and example responses, it does work. You can replicate it like this when you have a collection with mock:

1. For that collection create a request with url and a problematic query parameter: `{{url}}/api/bug?array%5B%5D=1`
2. For the previous request, add an example response with url and the same problematic query parameter (`{{url}}/api/bug?array%5B%5D=1`) and some body like `"Response 1"`
3. Now, you can check that you get the first example response if you have your Mock's URL in variable `url`
4. For the same request, add another example response with the same endpoint but a bit different value for query parameter (for example `{{url}}/api/bug?array%5B%5D=2`) with some other body like `"Response 2"`
5. Now, if you send the original request with url `{{url}}/api/bug?array%5B%5D=1`, you may get the response body defined by the second example (`"Response 2"`), not the first example, which has fully matching endpoint and query parameters.
6. If you still get the response with body `"Response 1"`, try then with the url of the second example (`{{url}}/api/bug?array%5B%5D=2`), you should of course get then `"Response 2"` in the body, but you will still get `"Response 1"`. I am writing this, because I now also noticed that the outcome is different whether you duplicate the second example from the first one, or if you use "Add example" menu item to create your second example based on an already existing response. Of course importing the collection may then be another story, but it looks like it will always return the latest created mock response, if it is not duplicated from an already existing example.

I made you a [gist with an exported collection](https://gist.github.com/ssallmen/e0147838ac91425a64ffe9e1f42ea449), which can be easily used to replicate the issue. It has also similar request (endpoint `{{url}}/api/works`) with similar example responses but query parameters with `[]`, instead of `%5B%5D`. Just create a mock server based on that collection, and you will be able to find it out by variating the value of the only query parameter in both requests.

**Comment by Dhembla** [comment] 2022-01-28 06:25
Hey, @ssallmen Thank you so much for reaching out to us. We have released a fix for this issue yesterday and your mock server should work as expected by now. Please give it a try and let us know if the problem is resolved for you.

**Comment by ssallmen-pro** [comment] 2022-01-28 08:28
Thank you for the fix. I tested it and it seems to work now like it should. I mean, query parameters with for example %5B and %5D characters, and hopefully also any other characters presented like that, will give the same result as if I use the same characters as such ('[' and ']' in this case). Didn't do any regression testing though, but at least my case is not solved.

**Comment by ssallmen** [comment] 2022-01-28 08:32
Sorry, was logged in with my other account when writing the comment above. But, it works now, like my other account said above 😉 Thanks!

**Closed as completed** 2022-02-02 06:23 UTC
Labels: product/mocks
