### ISSUE TITLE
Scrolling left does not work on request tabs

### ISSUE THREAD

**Issue by philmagr** [a85/POSTMan-Chrome-Extension#6635] opened 2019-05-31 14:33 UTC
**Describe the bug**
When you have more tabs that can fit on the screen, you can't scroll to see them

**To Reproduce**
1. Open up more tabs than can fit on your screen
2. Hover over the tab bar and scroll the mouse wheel
3. Notice that the tabs happily scroll right, but you are unable to view tabs on the left side without closing some

**Expected behavior**
Tabs scroll

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: No idea. Where in the world are your version numbers?! Oh. The settings menu. Well there's another bug report... 
7.1.1
 - OS: Windows 10

**Additional context**
Related: https://github.com/postmanlabs/postman-app-support/issues/5350

**Comment by grojguy** [comment] 2019-06-04 22:29
I can confirmed exact same behavior, same conditions.  

And I agree with OP... app version is in a very non-standard location.  Not sure why this was done.  Standard location for Windows is typically Help -> About.

Version 7.1.1 (native)
win32 10.0.17134 / x64

**Comment by rocasyeh** [comment] 2019-06-13 02:52
This also happened on me.

Version 7.2.0
win32 10.0.16299 / x64

**Comment by fedorareis** [comment] 2019-06-17 20:21
Also happens on Mac (not surprising since it is an electron app). It however does work properly with side to side scrolling on my touchpad.

Version 7.2.0
macOS 10.14.5

**Comment by Simaky** [comment] 2019-06-20 11:54
Also happens on my Mac.

Version: 7.2.2 
macOS: 10.14.4

**Comment by ankurdengla** [comment] 2019-09-17 06:31
This issue is now fixed in Postman v7.7.2
Do let us know if the issue still persists.

**Closed as completed by ankurdengla** 2019-09-17 06:31 UTC
Labels: bug, tabs, user-interface, product/dsui
