### ISSUE TITLE
Collection Runner does not update cookies

### ISSUE THREAD

**Issue by andre-exads** [a85/POSTMan-Chrome-Extension#7288] opened 2019-09-09 10:46 UTC
**Description of the bug**
Headers set in the request, that are being sent when the individual request is sent using the main interface, are being ignored when the request is being sent by the Collection Runner causing the request to fail.

**To Reproduce**
1. Create any request into a new collection to a certain URL;
2. Create a POST request to the same URL with a different path, some form-data body variable and the following headers:
  a) Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  b) Referer: <the_previous_url>
  c) X-Requested-With: XMLHttpRequest
3. Run the collection with the console open

**Expected behavior**
The Request-Headers to contain the headers set

**Screenshots**
[standalone request run with console](https://github.com/breier/dev-tests/blob/master/Screenshot%20from%202019-09-09%2011-27-58.png)
[same request from collection runner with console](https://github.com/breier/dev-tests/blob/master/Screenshot%20from%202019-09-09%2011-30-44.png)

**App information:**
 - App Type: Native App
 - Postman Version: 7.6.0
 - OS: Linux 5.2.11-200.fc30.x86_64 (fedora 30)

**Comment by coditva** [comment] 2019-09-10 13:54
Hey @andre-exads, thanks for reaching out!

I tried sending a request in Postman with the information you provided but could not reproduce the issue.

I did observe from your screenshots that `200` was returned for the Request Editor but `404` was returned for the Runner. This could mean that the server redirected the request and this changed the `Referer` header. Could you verify if this is the  reason in your case?

**Comment by andre-exads** [comment] 2019-09-11 09:01
Hi @coditva , thanks for the reply.

Yes, if I try to send the request from standalone and I'm not logged in, I get the same 404 and I just checked that the headers change as well, so you're right there is a redirect.

It looks like the main cause is that the collection is not sending the cookie with PHPSESSID with this request.

The request, when standalone, and being run after the successful login request, sends that cookie and everything works.

But the collection might be ignoring the cookie being set, or not sending it for the type of request (IDK) even though it's NOT a cross domain request.

So this issue should probably be renamed to "Collection Runner not respecting cookies" !?!

**Comment by Duckbringer** [comment] 2019-09-11 11:27
It does seem to ignore some kind of cookies.. 
![image](https://user-images.githubusercontent.com/34427714/64693537-c3b3c700-d497-11e9-9523-7f81673746a6.png)

**Comment by coditva** [comment] 2019-09-19 08:45
@andre-exads @Duckbringer This is definitely an issue with the cookies.

The Runner is not ignoring the cookies, it concatenates all the cookies into one cookie. But the problem is that the Runner is not using the new cookies, but rather the one set when sending the standalone request in the Request Builder.

One workaround you can try in the meantime while we work on fixing this is that you can checkmark the `Run collection without using stored cookies` in the Runner:

![Screenshot 2019-09-19 at 14 13 54](https://user-images.githubusercontent.com/8445768/65228235-be81f800-dae7-11e9-8a6e-6382761ad3e3.png)

Updating the issue title for this bug.

**Comment by codenirvana** [comment] 2019-11-04 06:21
@andre-exads @Duckbringer This issue is fixed in the latest version of the Postman app `v7.10.0`.

**Closed as completed by codenirvana** 2019-11-04 06:21 UTC
Labels: bug, collection-runner, cookies, product/runtime
