### ISSUE TITLE
Stuck in Sign In Loop

### ISSUE THREAD

**Issue by joemonti** [a85/POSTMan-Chrome-Extension#3956] opened 2017-12-12 21:09 UTC
## App Details:

```
Postman for Linux (native)
Version 5.3.2 (same behavior after upgrading to 5.5.0) x64
Ubuntu 17.10 4.13.0-17-generic
```

## Issue Report:
Postman somehow got stuck unable to sign in. I typically Sign In with Google. When I sign in with Google, Postman goes to the orbiting loading screen and then returns to the Sign In screen. I also tried signing in to Postman with my email/password, but the same thing happens. I don't get a Sign In error, I just get sent back to the sign in screen. I tried signing in the same way under the Chrome App and that worked fine.

![screenshot from 2017-12-12 15-55-51](https://user-images.githubusercontent.com/764037/33908206-a3ca979a-df55-11e7-87e5-1260e2edd39e.png)
![screenshot from 2017-12-12 15-55-47](https://user-images.githubusercontent.com/764037/33908214-a89d3d2c-df55-11e7-9d7c-5e018959c051.png)

## Steps to Reproduce
This may have been what caused the issue
1. As a typical user does, I was not paying attention to what I was doing
2. I was debugging Authorizing a OAuth2 app and decided to try and clear cookies
3. Open Dev Tools
4. Go to Application Tab
5. Under Clear Storage, Clear site data
6. Close Postman
7. Now unable to signin

**Comment by joemonti** [comment] 2017-12-12 21:11
I also see this in the Chrome App, presumably from all of my login attempts.

![screenshot from 2017-12-12 16-10-46](https://user-images.githubusercontent.com/764037/33908627-123cabe0-df57-11e7-8a79-53da55520040.png)

**Comment by harryi3t** [comment] 2017-12-13 11:23
@joemonti Thank you for reporting this. I was able to reproduce this using your steps.
Marking this as a bug. We will look into this and update this thread.

**Comment by harryi3t** [comment] 2017-12-13 11:58
@joemonti 
While our developers are looking into this bug, may I suggest you a workaround?
You can delete (or rename) the folder where Postman stores all the configuration. 

__Warning: All data which is not synced will be lost! This should not be a problem if you were signed in before getting stuck in this issue.__

1. Quit Postman, if running.
2. Delete (or rename) the folder using the following commands
```shell
# To delete
rm -rf ~/.config/Postman

# instead of deleting, you can also rename the folder 
# (in case you want to revert back to it later)
mv ~/.config/Postman ~/.config/Postman-old
```
3. Start the app

You should be able to see the following screen 
![image](https://user-images.githubusercontent.com/5207331/33937388-4ba04fcc-e029-11e7-9dcc-b0e669393b67.png)

**Comment by joemonti** [comment] 2017-12-15 14:30
Thank you @harryi3t ! yes that did resolve the issue for me

**Comment by wtam** [comment] 2017-12-20 04:19
Same issue and I'm on Windows native client and where is the config file to delete?

**Comment by harryi3t** [comment] 2017-12-20 09:49
@wtam and to all new visitors facing this issue, here's the location of postman config directory across all platforms
```
MacOS: "~/Library/Application Support/Postman" 
Windows: "C:\Users\<user>\AppData\Roaming\Postman"
Linux: "~/.config/Postman"
```

**Comment by wtam** [comment] 2017-12-21 08:26
@harryi3t Thanks it work

**Comment by rdbasu** [comment] 2018-04-05 16:45
Any update on this issue?

**Comment by prashantagarwal** [comment] 2018-05-19 05:36
We have made several improvements to our Sign In / Sign Up flows. This ideally should not happen for Postman v6.1.0 onwards

**Closed as completed by prashantagarwal** 2018-05-19 05:36 UTC
Labels: bug, pending-close

**Comment by LisaBails** [comment] 2018-08-14 05:39
yeah still happening >_<

**Comment by MoragM** [comment] 2018-08-14 07:48
This has begun happening for me since yesterday. Unlike with the original post, I didn't even deliberately clear any site data. The workaround with the config file seems to have solved the problem.

**Comment by amaschas** [comment] 2018-12-20 17:33
I am also having this problem. Deleting the config files doesn't fix it. I just want to be able to use this app without signing into an account.

**Comment by LisaBails** [comment] 2018-12-21 08:20
what fixed it for me was downloading latest version

**Comment by h1lleh** [comment] 2019-03-27 10:14
Still a bug within Postman  over a year after first reported. 

I'm using the latest version of Postman (7.0.6); and had to blow away my postman file and recreate collections - by following the details here I was able to export ahead of time, but still - it's a pain to do. A colleague also has the exact same issue.

**Comment by kdehairy** [comment] 2019-03-27 14:19
I also still face this bug. Linux, postman v7.0.6.

I tried the workaround (rm -rf ~/.config/Postman). Still loops back to the login screen.

The only different case I can think of is that after providing my company's google email, I'm redirected (rightfully) to my company's SSO login page.

**Comment by amaschas** [comment] 2019-03-27 15:55
What if, and I'm just spitballing here, you didn't force users to log into an app that doesn't require login to function?

**Comment by a85** [comment] 2019-03-27 15:58
Postman doesn’t require a login to function.

**Comment by h1lleh** [comment] 2019-03-27 16:02
Correct: We're not forcing anyone to log in; Part of my login flow has a PCV which uses basic auth to get an access token. It's the PCV which loops (with any user, new or old that I create). So I can never get an access token through Postman when this bug arises. 

Deleting the Postman directory worked for me, and I can now get an access token, but surely this bug should be fixed over a year later.

**Comment by underhilllabs** [comment] 2019-08-28 14:07
@a85 true it doesn't require signing in. But if you don't sign in, it will delete all of your history and all of the sites that you have set up to test. I know this because it just happened to me.
