### ISSUE TITLE
Cookies in response are not reflecting under Manage Cookies

### ISSUE THREAD

**Issue by masterchop** [a85/POSTMan-Chrome-Extension#6021] opened 2019-03-06 01:33 UTC
**Describe the bug**
I am running a request through scripts in the Test section once i get the response headers which contain a Set-Cookie header, i use the output and build a cookie:

    console.log(response.headers.get('Set-Cookie'))
    var Cookie = require('postman-collection').Cookie,
    rawHeader = response.headers.get('Set-Cookie')
    myCookie = new Cookie(rawHeader);

The JSON output looks just fine:

console.log(myCookie.toJSON());

But if you look at the Cookie manager in the UI The cookie never gets created. The next request fails as the cookie is not longer available on the app, if i print the cookie content and go to Cookie manager and add the cookie manually everything works just fine.

**App information (please complete the following information):**
 - Postman Version [ v7.0.4 ]
 - OS: [Test on windows and linux]

**Comment by numaanashraf** [comment] 2019-03-06 07:25
@masterchop This is not supported at the moment. We'll consider this as a feature request. I've re-worded the issue title to reflect the same.

**Comment by numaanashraf** [comment] 2019-03-06 08:28
@masterchop My bad. We took a deeper look at this issue and cookies in response headers should be added to the cookie manager after the request completes. Is there a publicly assessible endpoint we can use to replicate this issue at our end?

**Comment by masterchop** [comment] 2019-03-06 14:01
I am afraid this is a work API and i can't share the information but very interested so if you need me to test anything please feel free to reach out to me to do all the necessary testing.

**Comment by codenirvana** [comment] 2019-04-10 11:42
@masterchop You don't have to manually set the cookie.
If `Set-Cookie` response header is set correctly, the cookie will be added automatically.

**Comment by masterchop** [comment] 2019-04-12 15:56
i think you dont understand what i am doing, the cookie is generated but after the reqeust is been done, and it has to be generated before as this a script that runs before the request. This is a bug as i am not able to create the cookie at run time to be use on the request.

**Comment by codenirvana** [comment] 2019-04-12 18:31
@masterchop If I understood you correctly, you are either trying to create a new cookie programmatically via script OR cookie is not set (in the cookie manger) even if `set-cookie` header is sent correctly (*Is this a normal request or `pm.sendRequest`?*).

**Comment by masterchop** [comment] 2019-04-13 05:30
I am collecting the cookie from the pm.request and try to place it on the cookie manager so the main request can use it but it get created after executing the main request. which fails due to missing cookie.

**Comment by shamasis** [comment] 2019-05-14 06:49
Hey, I was dropping into check whether one of the changes that we are working on would actually address this issue.

@codenirvana - can you confirm that the work we are doing on programmatic cookie access would allow creating new cookies from within sandbox and use in subsequent requests?

**Comment by codenirvana** [comment] 2019-05-14 07:27
> programmatic cookie access would allow creating new cookies from within sandbox and use in subsequent requests?

@shamasis Yes.

> I am collecting the cookie from the pm.request and try to place it on the cookie manager.

Possible duplicate of #5753.
@masterchop You don't have to programmatically add `pm.sendRequest` cookies, We've added support this on our Canary (version: 7.1.1-canary01) channel https://www.getpostman.com/canary

**Comment by codenirvana** [comment] 2019-05-16 19:48
@masterchop We've added support for this in the latest Postman App (v7.1.0).
Cookies set in `pm.sendRequest` will be stored automatically.

**Closed as completed by codenirvana** 2019-05-16 19:48 UTC
Labels: feature, support, cookies, product/runtime
