### ISSUE TITLE
Sync issue when duplicate the folders within a collection 

### ISSUE THREAD

**Issue by kondal99** [a85/POSTMan-Chrome-Extension#3914] opened 2017-12-06 11:08 UTC
Sync issue when duplicate the folders within a collection. duplicated folder is overriding with original folder requests values while syncing between local and server.

Steps:
1. Create a folder test1 with 10 requests.
2. Duplicate folder test1 and rename it to test2
3. update the folder test2 by adding or deleting some requests
4. wait until sync popup appears and select the sync with local values
5. The updated values in folder test2 will be lost and it overridden by folder1 values
## App Details:
Postman for Windows
Version 5.4.1
win32 6.1.7601 / x64

**Comment by sdnts** [comment] 2017-12-06 11:37
@kondal99 I'm unable to reproduce this. I created a new collection and tried this. Is this happening for all collections in your case? If not, would it be possible to send over a collection that does this? You can email it to help@getpostman.com if posting it here is not an option.

Ideally, the Sync popup should not be shown in the first place.

**Comment by kondal99** [comment] 2017-12-06 12:44
@madebysid, this is happening many times. 
The sync popup showing many times while updating more collections in folder. I will send my collections.

**Comment by a85** [comment] 2017-12-23 19:22
We have a big overhaul for the sync layer coming up. Closing this issue as an isolated case. Tracking sync related issues elsewhere in the tracker.

**Closed as completed by a85** 2017-12-23 19:23 UTC
Labels: sync
