### ISSUE TITLE
View Collection Variables from Environment Quick Look

### ISSUE THREAD

**Issue by a1dutch** [a85/POSTMan-Chrome-Extension#9839] opened 2021-04-14 09:07 UTC
**Is your feature request related to a problem? Please describe.**
Postman variables are scattered over different places, there is no unified place to view all variables.

**Describe the solution you'd like**
The environment quick look should add a new section that displays the collection variables for the currently selected requests collection.

**Comment by giridharvc7** [comment] 2021-04-20 07:20
Duplicate of #5846 
This is very similar to #5846, closing this to track it in a single place.

**Closed as completed by giridharvc7** 2021-04-20 07:20 UTC
Labels: feature, variables, user-interface, product/runtime
