### ISSUE TITLE
Unable to open Postman v8.7.0 in Mac OS

### ISSUE THREAD

**Issue by sathyarajagopal** [a85/POSTMan-Chrome-Extension#10097] opened 2021-07-04 16:43 UTC
**Describe the Issue**
Unable to install Postman in Mac.

**Steps to Reproduce**
1. Download v8.7.0 from https://dl.pstmn.io/download/latest/osx
2. Unzip and double click "Postman" to install
3. Following error is thrown:
_Postman can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information._

**Environment Information**'
 - Postman Version: 8.7.0
 - Operating System: Mac OS Catalina

**Comment by sathyarajagopal** [comment] 2021-07-04 16:57
I raised this because everytime I had to change the security preferences to enable Postman.

**Comment by jviotti** [comment] 2022-02-07 17:09
Hey @sathyarajagopal , are you still facing this problem?

**Comment by twitharshil** [comment] 2022-02-18 06:14
The postman `v8.7.0` and the latest versions are notarized. 

```sh 
$ spctl -a -vvv -t install Postman.app
Postman.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Postdot Technologies, Inc (H7H8Q7M5CK)
```

Closing this as a duplicate of this issue https://github.com/postmanlabs/postman-app-support/issues/6029

**Closed as completed by twitharshil** 2022-02-18 06:14 UTC
Labels: bug, platform/macOS, product/desktop-foundation, version/8, component/code-signing
