### ISSUE TITLE
"Run" collection with only folders doesn't do anything

### ISSUE THREAD

**Issue by keithfry** [a85/POSTMan-Chrome-Extension#10429] opened 2021-11-09 13:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I have a folder in a collection in my scratchpad that contains other folders of tests, like below (note that each "Test" folder contains requests):

All Tests/
   Test 1/
   Test 2/
   Test 3/

The Run button is shown in the test runner, but when clicked it doesn't do anything. The content will only run if there are ONLY request entities in them. ie a mix of folder and request also doesn't work. This pretty much breaks the entire benefit of an organized collection. 

### Steps To Reproduce

1. Create a Collection with a folder hierarchy of at least 2 folders deep.
2. At the bottom level create a couple of requests/tests
3. Try to Run the folder at the very top by selecting it and clicking the Run button. The button doesn't do anything.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/50087233/140934497-18e33922-7879-4972-b9de-832fe8984c43.png)

Sample hierarchy.

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

### Additional Context?

This is in scratch pad, haven't tried it in workspaces.

**Comment by malvikach** [comment] 2021-11-10 04:56
@keithfry I tried to replicate the issue on my end and it seems to be working fine on the scratchpad (see attached screenshot).

Please let me know if you saved your requests before trying the run button. 
Also, a screenshot/video will help me understand the issue better along with the information on OS, postman version, and the platform type(web or postman app).

![image](https://user-images.githubusercontent.com/89449769/141052319-5d11a2a7-ed53-48f3-944f-2a55d2073569.png)

**Comment by keithfry** [comment] 2021-11-10 13:07
I had to delete and re-import all my Collections after upgrading before the Run button would work correctly for the example above. Maybe it's an upgrade process issue?

**Comment by malvikach** [comment] 2021-11-11 08:49
@keithfry Glad to know that upgrading helped fix the issue. 

It could be a bug/issue with one of the previous versions. Do let me know if you could provide me with the previous version that you were on. (and your platform details) This will help us investigate this and identify the cause.

I will be closing this issue for now. Feel free to write to us if you face any other problems.

**Closed as completed by malvikach** 2021-11-11 08:49 UTC
Labels: collection-runner, product/runtime
