### ISSUE TITLE
GET that is 301 redirected fails

### ISSUE THREAD

**Issue by hairymonkeynuts** [a85/POSTMan-Chrome-Extension#8174] opened 2020-03-12 19:54 UTC
**Describe the bug**
When using postman to send a GET against an AWS ALB ~(or IIS)~ with redirection on the HTTP side (for HTTP to HTTPS redirection), ALB ~/IIS~ sends 301 with reference to HTTPS url. Postman chokes with "Could not get any response" error. POSTs and some other non-GET methods tried are not affected with IIS redirecting, but with AWS ALB redirecting Postman will not resend the headers.

**To Reproduce**
1. Create AWS ALB with two listeners, HTTP and HTTPS
2. On HTTP listener set default rule to redirect 301 to HTTPS with the original host and uri sent
3. Have "Hello World" site behind HTTPS
4. have Postman make a GET against HTTP  (ie. http://www.example.com/page)
5. see the error

**Expected behavior**
I would expect the GET to follow the redirect to HTTPS like POST does _OR_ throw an error stating it is not following the 301 (maybe same for 302?)

**Screenshots**
screenshots should not be necessary 

**App information (please complete the following information):**
 - App Type: any
 - Postman Version 7.2.0
 - OS: windows 10

**Additional context**
As an aside finding, we implemented a squid proxy to facilitate the mass work from home initiative with the coronavirus pandemic. In looking at the logs it seems postman is not using CONNECT with the proxy and just hitting directly _until_ it has an HTTPS in the URL for the GET call. Also, the HTTP GET receives the 301 and Postman attempts to send HTTPS but without CONNECT.

**Comment by hairymonkeynuts** [comment] 2020-03-12 20:11
I tried to wireshark Postman calling with the GET and it seems to get the redirect but does nothing with it.

**Comment by vikiCoder** [comment] 2020-03-16 05:56
Hi @hairymonkeynuts,

I tried to reproduce the problem by creating a local server that sends a 301 redirect to `https://postman-echo.com/get` on a GET request. The redirect seems to be working fine (below screenshot).

![image](https://user-images.githubusercontent.com/16588032/76726830-54859b00-6778-11ea-91cc-905a9432ccd6.png)

If possible, please share a screenshot of Postman console with all the requests expanded where you are facing the problem. And it would be great if you can share an endpoint with us for which you are facing the problem so that we can replicate the problem at our end.

**Comment by codenirvana** [comment] 2020-05-29 20:47
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-05-29 20:47 UTC
Labels: blocked/need-info, product/runtime
