### ISSUE TITLE
Save the Authorization data as part of saving the request

### ISSUE THREAD

**Issue by plaishwarya** [a85/POSTMan-Chrome-Extension#5165] opened 2018-09-10 20:42 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
I usually work in different environments which require different token generation mechanisms.
For Example:
My First Request:
1. Http POST request
2. Go to Authorization --> Select any --> Give the required urls, fields etc
3. Get the token and use it
4. Save the Request

My Second Request:
1. Http POST request
2. Go to Authorization --> Select different one than First Request--> Give the required urls, fields etc
3. Get the token and use it
4. Save the Request

Now if I try to go to my first (Saved )Request, I have to change the entire Authorization mechanism as it is not saved.

**Describe the solution you'd like**
1. When we save a request, the Authorization data and the token should be saved as part of the request
2. For example I should be able to save 2 requests with different authorization mechanisms and should be able to go to them without the hassle of changing the Authorization every time.

**Describe alternatives you've considered**
1. The only alternative currently available is to save the request and re-type / reselect all the authorization mechanisms for each and every request with different authorization techniques.

**Additional context**

**Comment by numaanashraf** [comment] 2018-09-11 18:31
Duplicate of #3903

**Closed as completed by numaanashraf** 2018-09-11 18:31 UTC
