### ISSUE TITLE
Clicking "New API" on the APIs tab caused Postman to become unresponsive for 15 min

### ISSUE THREAD

**Issue by ylanen-anu** [a85/POSTMan-Chrome-Extension#6800] opened 2019-06-28 08:21 UTC
**Describe the bug**
I clicked the + New API link on the APIs tab.
![image](https://user-images.githubusercontent.com/28052324/60328155-ff0d2200-998d-11e9-83e9-c8cf1abfd8ad.png)
After that, Postman became unresponsive, and I was not able to switch the workspace, it just said "loading..." for a long time (perhaps 15 min)
![image](https://user-images.githubusercontent.com/28052324/60328232-2532c200-998e-11e9-8452-6e4a60e41e75.png) 

**To Reproduce**
Already described above. All I did was click the button.

**Expected behavior**
Postman should not load that long and block using other features.

**Screenshots**
Already posted above.

**App information (please complete the following information):**
 - Native app, Mac
 - Postman version 7.2.2
 - OS: macOS Mojave, version 10.14.5

**Additional context**
n/a

**Comment by shivangibajpai12** [comment] 2019-07-15 05:24
Hey @anupulu , thank you for reporting this issue. We are unable to reproduce it . Could you confirm if you are still able to reproduce this behaviour consistently?

**Comment by sankalp0o** [comment] 2019-07-29 08:22
Hi @anupulu , did you face this again or was it only the one time? I'm thinking maybe your internet was slow at that time and that's why loading the workspace took too long (as is evident from your second screenshot).

I'm closing this for now, but if you're seeing this repeatedly, please let us know and we will fix this.

**Closed as completed by sankalp0o** 2019-07-29 08:22 UTC
Labels: performance
