### ISSUE TITLE
Feature request: Import/export of globals

### ISSUE THREAD

**Issue by xxldoctor** [a85/POSTMan-Chrome-Extension#2155] opened 2016-07-01 13:56 UTC
4.4.1
win / x86-32
Chrome 51.0.2704.84
Interceptor on
- export globals (Download as json)
- import it back through the import button in environments (1) or in main window (2)

expected: imported globals
actual (1): imported new empty environment
actual (2): Failed to import data: format not recognized

**Comment by abhijitkane** [comment] 2016-07-04 13:13
@xxldoctor Thanks for reporting this. We'll be pushing a fix in the next release.

**Comment by asookazian** [comment] 2016-07-05 19:20
I am reproducing, is there a workaround or ETA on the patch?  Also, shouldn't this be classified as a bug not a feature?  thx.

4.4.1
os x 10.11.4
chrome 51.0.2704.106 (64-bit)

exported globals (download as json: globals.postman_globals.json)
import globals

consistently getting "Failed to import data: format not recognized" when I drag/drop file from finder to the postman import window.  same results if I click choose files, etc.

**Comment by abhijitkane** [comment] 2016-07-06 12:59
@asookazian @xxldoctor This has been fixed in v4.4.2 of the app (Chrome only). Can you update (https://www.getpostman.com/docs/updating) and check?

**Comment by xxldoctor** [comment] 2016-07-06 14:00
Fixed partly. It works if I import globals through import buuton in main window. But if import through import button in "manage environments" window - it still create "new environment" (empty) instead of importing globals.

**Comment by asookazian** [comment] 2016-07-06 16:22
I was able to import as xxldoctor stated above.  However, in runner mode, one of my tests is failing due to the variable substitution for a path param in the endpoint URI is not happening.  In non-runner mode the path param is being substituted.  Using the same "no environment" as I am in the default (non-runner) mode.  Please advise.  Also, how can I import the global json file into a specific named environment rather than just the globals (no environment).  thx.

**Comment by asookazian** [comment] 2016-07-06 17:32
If I create a new environment and bulk edit as key/value pairs to add the global environment variables, save and then run the runner of the collection tests using the test envmt vs the no envmt (globals I presume), the error (not replacing the variable in the URI) is not reproducing and all my tests are passing.

**Comment by abhijitkane** [comment] 2016-07-07 10:04
@asookazian Globals and environments are different. You cannot import globals into an environment right now.

**Comment by Alexsey** [comment] 2017-06-12 12:04
Can't import globals through the "Import" window - error
```Failed to import data: Could not import: TypeError: Cannot read property 'id' of null```
File is like this
```
{
  "id": "94eb92bd-fcb9-ce88-14fa-41966de0b2ad",
  "name": "Postman Globals",
  "values": [
    {
      "enabled": true,
      "key": "user",
      "value": "1ddd2e4c-3705-4172-be2f-ad579b01c100",
      "type": "text"
    },
    {
      "enabled": true,
      "key": "site",
      "value": "http://abc.def.com:3333",
      "type": "text"
    }
  ],
  "_postman_variable_scope": "globals",
  "_postman_exported_at": "2017-06-12T11:45:10.984Z",
  "_postman_exported_using": "Postman/5.0.0"
}
```
And I already have some globals

**Comment by sdnts** [comment] 2017-06-12 12:08
@Alexsey I am able to import the JSON you attached on the 5.0.0 native and Chrome apps. What version of the app are you on?

**Comment by Alexsey** [comment] 2017-06-12 12:09
@madebysid OSX native V5.0

**Comment by Alexsey** [comment] 2017-06-12 12:13
Sorry, globals are actually imported. But also error balloon will pops up. First green balloon will pops up with the message that globals art imported and the red balloon pops up with an error

**Comment by sdnts** [comment] 2017-06-12 12:18
@Alexsey Ah I was able to replicate this. A `Raw text Import` works as expected. If you do an `Import by File`, this happens. I'm investigating what might be causing this.

**Comment by sdnts** [comment] 2017-06-12 12:34
I was able to find the problem. While the import does work, the behaviour you mentioned has been fixed and will be out with the next release :)

**Comment by Alexsey** [comment] 2017-06-12 12:39
Thanks :)

**Comment by Alexsey** [comment] 2017-07-20 12:22
@madebysid Now it's 5.0.2 and the bug is still there :(

**Comment by nbarel** [comment] 2017-07-26 07:52
@madebysid Same happens to me on Postman App for windows v5.1.2, when I import any environment file

![capture](https://user-images.githubusercontent.com/18085493/28610120-eb80678c-71ef-11e7-8f0d-1ead13209326.PNG)
 
to reproduce:
1. create a new environment
2. download it to external file
3. import the downloaded file

**Comment by nbarel** [comment] 2017-07-26 08:04
@madebysid Same happens to me on Postman App for windows v5.1.2, when I import any environment file

![capture](https://user-images.githubusercontent.com/18085493/28610768-2e733d60-71f2-11e7-9ab2-fa9bb836ae59.PNG)

to reproduce:

create a new environment
download it to external file
import the downloaded file

**Comment by anudeepmedicharla** [comment] 2018-07-17 09:17
@SamvelRaja Can this be closed now? I was not able to replicate the issue.

**Comment by SamvelRaja** [comment] 2018-07-18 04:13
Closing this as both the import via raw text and import via files had been fixed in the latest version of the app.

**Closed as completed by SamvelRaja** 2018-07-18 04:13 UTC
Labels: feature
