### ISSUE TITLE
Password protecting publish documentation

### ISSUE THREAD

**Issue by wywarren** [a85/POSTMan-Chrome-Extension#8485] opened 2020-05-14 20:00 UTC
More often than not we create APIs for 3rd party clients that do not wish for their documentation to be openly available on the web. Our clients may not all know or are willing to use Postman as much as we make an effort to bring them onboard. Once a documentation is published, they wish for only their designated members to view the documentation.

Our work around right now is to export the collection for them to import into their own environment, or to bake the documentation into HTML/PDF versions for them to view.

It is the case that companies make APIs for their own products internally but there are a bunch of development teams that are developing APIs for various clients that do not use Postman. There needs to be a way to allow them to securely view their documentation without providing them the full features of Postman if they're not part of the team.

**Comment by Raja-Simha** [comment] 2020-11-19 10:57
Duplicate of #6681

**Closed as completed by Raja-Simha** 2020-11-19 10:57 UTC
Labels: feature, product/documentation
