### ISSUE TITLE
Display fork label in collections list

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6540] opened 2019-05-17 16:04 UTC
The Postman API enables to return a list of collections `https://api.getpostman.com/collections` but in case a collection is forked, it doesn't specify which one is the original one and which one is the fork. 

This makes it difficult to differentiate them.

It would be nice if the fork label was displayed with the collection.

**Comment by sankalp0o** [comment] 2019-05-19 06:21
@vkaegis This issue is coming up everywhere. We've already solved it in 2-3 places but I feel we should look at this more holistically.

**Comment by Wotuu** [comment] 2019-10-24 15:38
What's the status on this? I'm running into this right now. This makes it unusable for automation.

**Comment by ankit-m** [comment] 2019-11-29 05:42
Duplicate of #7435

**Closed as completed by ankit-m** 2019-11-29 05:42 UTC
Labels: feature
