### ISSUE TITLE
added a "=" at the end of a request url raw when exporting a collection v2.1 to v2.1 

### ISSUE THREAD

**Issue by TAkbay** [a85/POSTMan-Chrome-Extension#4007] opened 2017-12-27 08:59 UTC
## App Details:

```
Postman for Windows
Version 5.5.0
win32 10.0.10586 / x64
```

## Issue Report:
 1. The bug is seen in the 2.1 Version.
 2. Expected behaviour: If you export an already existing Postman Collection in Version 2.1. again to Version 2.1. there should not be any changes in the url raw.

Steps to reproduce the problem:
1. Import a collection in version 2.1
2. Export it as a collection in version 2.1
3. The end of the url raw in a request has a "**=**".
It is automatically added when you export the collection 2.1 version to 2.1.

```
"request": {
...
...

    "url":{
        "raw": "http://urlExample/postman="
     ...
      }
}
```

**Comment by prashantagarwal** [comment] 2017-12-27 11:47
@Mina05 Thanks for reporting this we will investigate this and keep you updated.

**Comment by a85** [comment] 2017-12-28 19:59
@prashantagarwal Is this due to the transformer?

**Comment by kunagpal** [comment] 2017-12-29 08:46
@Mina05 I was unable to reproduce this with the following collection:
```js
{
        info: {
            schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
        },
        item: [
            {
                request: {
                    url: {
                        raw: 'http://urlExample/postman',
                        protocol: 'http',
                        host: ['urlExample'],
                        path: ['postman']
                    }
                }
            }
        ]
}
```

Could you share the complete collection that causes this behaviour? Feel free to redact sensitive details 😄

**Comment by TAkbay** [comment] 2018-01-05 11:39
@kunagpal I could make a small postman collection for you and I could reproduce the problem.
It only appears in URLs with "?wsdl" and placeholder like "{{PLACEHOLDER}}.
So it changes the url after the export from v2.1 to 2.1 to "?wsdl=" and "{{PLACEHOLDER}}="
Here the collection.json this should be sensitive enough 😄

```
{
	"info": {
		"name": "Test for equals bug in URL",
		"_postman_id": "0073fad5-20d8-5627-7a6e-c78bcedf6c24",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "01 wsdl test",
			"item": [
				{
					"name": "test url with wsdl",
					"event": [
						{
							"listen": "test",
							"script": {
								"type": "text/javascript",
								"exec": [
									"tests[\"Status code is 200: \" + responseCode.code] = responseCode.code === 200;"
								]
							}
						}
					],
					"request": {
						"method": "GET",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": ""
						},
						"url": {
							"raw": "http://some.url:8080/forPostman/?wsdl",
							"protocol": "http",
							"host": [
								"some",
								"url"
							],
							"port": "8080",
							"path": [
								"forPostman",
								""
							],
							"query": [
								{
									"key": "wsdl",
									"value": ""
								}
							]
						}
					},
					"response": []
				}
			]
		},
		{
			"name": "02 placeholder test",
			"item": [
				{
					"name": "test url with placeholder",
					"event": [
						{
							"listen": "test",
							"script": {
								"type": "text/javascript",
								"exec": [
									"tests[\"Status code is 200: \" + responseCode.code] = responseCode.code === 200;"
								]
							}
						}
					],
					"request": {
						"auth": {
							"type": "basic",
							"basic": [
								{
									"key": "username",
									"value": "{{user}}",
									"type": "string"
								},
								{
									"key": "password",
									"value": "{{password}}",
									"type": "string"
								},
								{
									"key": "saveHelperData",
									"value": true,
									"type": "boolean"
								},
								{
									"key": "showPassword",
									"value": false,
									"type": "boolean"
								}
							]
						},
						"method": "POST",
						"header": [
							{
								"key": "Content-Type",
								"value": "text/xml"
							},
							{
								"key": "Authorization",
								"value": "Basic U1NJX1dTX0VYRUM6SW5pdDEyMzQ="
							}
						],
						"body": {
							"mode": "raw",
							"raw":  "body with raw data"
						},
						"url": {
							"raw": "{{URL}}/{{URL_PATH}}?{{URL_PARAMS}}",
							"host": [
								"{{URL}}"
							],
							"path": [
								"{{URL_PATH}}"
							],
							"query": [
								{
									"key": "{{URL_PARAMS}}",
									"value": "",
									"equals": false
								}
							]
						}
					},
					"response": []
				}
			]
		}
	]
}
```

**Comment by harryi3t** [comment] 2018-01-09 12:16
@Mina05 This is a known bug and the fix is already in progress.
You can expect this to work in the next version :)

Also, this is duplicate of https://github.com/postmanlabs/postman-app-support/issues/3991
please subscribe to the original issue for updates.

**Closed as completed by harryi3t** 2018-01-09 12:16 UTC
