### ISSUE TITLE
The value of this.request.description is undefined

### ISSUE THREAD

**Issue by innovanik** [a85/POSTMan-Chrome-Extension#3286] opened 2017-07-19 04:47 UTC
## App Details:

```
Postman for Windows
Version 5.0.2
Windows 7 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 Same as previous version
 2. Expected behaviour:
it must be defined as the value of the description.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
N/A
 4. Screenshots (if applicable)
- Chrome App
![screenshot-postman_for_chrome](https://user-images.githubusercontent.com/10056281/28350917-5a55f78a-6c87-11e7-9f8a-6039bb61fa9e.jpg)

- Windows App
![screenshot-postman_for_windows](https://user-images.githubusercontent.com/10056281/28350918-5a5ec9fa-6c87-11e7-8948-50aa024d647f.jpg)

**Comment by prashantagarwal** [comment] 2017-07-19 07:47
@dopenik Thanks for reporting this. We were able to reproduce this and will release a fix for it soon.

**Comment by kamalaknn** [comment] 2018-07-18 09:24
Hey, 

In the native Postman Apps, you can use the `pm.info` object to get the name and description of the request. You can find an extensive documentation on the API included in `pm.*` in the scripts on native apps here - https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference

I'm closing this as this is not a bug and an expected behavior. I've provided a working alternative for this.

**Closed as completed by kamalaknn** 2018-07-18 09:24 UTC
Labels: bug
