### ISSUE TITLE
Ability to collapse sidebars

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#9633] opened 2021-02-18 15:54 UTC
Filing on behalf of user. 

**Is your feature request related to a problem? Please describe.**

>
> -          We don’t need feature like Server mock, API monitoring, and Environments, we would like an option to disable all those stuff, we just need a simple, very simple IDE to send API requests and see responses, that’s ALL we need.
> 
> 
> -          We don’t need those panels circled in red, see below image, can we disable/make them invisible?
> They just take space for nothing useful.

![image](https://user-images.githubusercontent.com/5624835/108383237-74121880-71be-11eb-8a13-4402016f28d9.png)

**Describe the solution you'd like**
Collapsing the sidebars might be a good solution for the user.

**Comment by DannyDainton** [comment] 2021-02-18 16:02
Closing as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9601

**Closed as completed by DannyDainton** 2021-02-18 16:02 UTC
Labels: duplicate
