### ISSUE TITLE
Postman GRPC  live streaming response 

### ISSUE THREAD

**Issue by 5olitude** [a85/POSTMan-Chrome-Extension#11047] opened 2022-06-29 08:05 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I want to get the live streaming response for individual clients ,but opening the duplicate  tabs in postman GRPC only serving response to one of the client who is connected first to the GRPC server .

### Steps To Reproduce

1. Open two request tabs 
2. localhost:40005 and use the message param as {id:1} in the other tab localhost:40005 and use the message param as same or {id:2}
3. Now invoke the first request from tab1 (works perfectly)
4. Now invoke the second request from tab2 (nothing is returned ) but the tab will be active  and no response at all

The same thing happened while i was live streaming the data from gin server SSE EVENT response

### Operating System

Linux 

### Postman Version

9.14.0

### Postman Platform

Postman App

**Comment by appurva21** [comment] 2022-06-29 08:25
Hey @5olitude! We are not able to reproduce this issue with the given steps on the latest version of the Postman app. Could please update your app and verify if the issue still persists? If yes, would it be possible to share a screen recording of the same to help us reproduce it on our end?

**Comment by DannyDainton** [comment] 2022-07-05 09:38
Hey @5olitude 

I'm going to close this issue for now as we've been unable to reproduce the problem, given the information you've provided.

If you can provide clear steps to reproduce the issue and a short recording of what you can, that will help the team investigate what's going on.

**Closed as completed by DannyDainton** 2022-07-05 09:38 UTC
Labels: protocol/grpc, product/api-client
