### ISSUE TITLE
Cannot view content of body tab when we select GraphQL in body

### ISSUE THREAD

**Issue by sebastiancretu** [a85/POSTMan-Chrome-Extension#8672] opened 2020-06-17 12:54 UTC
**Describe the bug**
When we create a new request and we select the body to be a GraphQL request, we will receive an error: Something Went Wrong
Postman has encountered an error. If this problem persists, contact us at help@postman.com

**To Reproduce**

1. open postman
2. click on new
3. select collection
4. set a name for the collection
5. click create
6. click on new
7. select request
8. set a name for the request
9. select the previously created request
10. click on save
11. if not already open the new created request, open it
12. click on Body
13. select GraphQL
14. see error

**Expected behavior**
I should be able to see the body and make modifications to it

**Screenshots**
![Screenshot 2020-06-17 at 15 49 13](https://user-images.githubusercontent.com/2368005/84900280-89282c00-b0b2-11ea-99ee-e716e502fb88.png)
![Screenshot 2020-06-17 at 15 58 34](https://user-images.githubusercontent.com/2368005/84900923-719d7300-b0b3-11ea-82bf-71ca992f8d15.png)

**App information (please complete the following information):**
 - Postman Version 7.26.0 (7.26.0)
 - OS: macOS Catalina version 10.15.4

**Comment by kamalaknn** [comment] 2020-06-17 13:26
Hey @sebastiancretu 

Thanks for reporting this. We have identified the cause for this and will be releasing a fix for this on the stable channel in the next release.

We have also pushed this fix on the [Canary](https://www.postman.com/downloads/canary/) channel already.

**Comment by sebastiancretu** [comment] 2020-06-17 13:27
Great. Thanks.

**Comment by pankajk07** [comment] 2020-06-18 09:56
Hey @sebastiancretu, we have released a fix as part of `v7.26.1` in the stable channel. Please update the app and try out the new version. Do let us know if you find any other issues.

**Closed as completed** 2020-06-18 10:16 UTC
Labels: bug
