### ISSUE TITLE
Tunneling socket could not be established  

### ISSUE THREAD

**Issue by mohansaid** [a85/POSTMan-Chrome-Extension#8892] opened 2020-08-06 07:07 UTC
Hi team ,
We are getting the following exception while accessing the postman application and unable to perform any methods (get/post/delete/put).

Error :Tunneling socket could not be established,Status code=407

**To Reproduce**
1. Launch postman application
2. Enter the endpoint URL and case header and click on Send
3. Scroll down to to Response body 

**Expected behavior**
Should be able to get the response without any error and status code should be 200 

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version : Postman-win64-7.29.1
 - OS: Windows 10 Enterprise

**Additional context**
All of sudden we got this and earlier it is working fine as expected.

**Comment by DannyDainton** [comment] 2020-08-06 07:10
Duplicate of #8783

**Closed as completed** 2020-08-06 07:11 UTC
