### ISSUE TITLE
Collection Runner does not return to the selected folder after running Collection then clicking on Collection Runner in top left of same window

### ISSUE THREAD

**Issue by dglanville** [a85/POSTMan-Chrome-Extension#7520] opened 2019-10-23 17:13 UTC
Collection Runner does not return to the selected folder after running Collection then clicking on Collection Runner in top left of same window

1. Open Postman 
2. Choose your Personal or Team in the upper middle
3. Click on the Runner button in the upper left of the main window
4. In the Choose a collection or folder browse to your collection (Mine is 3 folders deep)
5. Select an Environment
6. Leave all other settings at their default 
7. Click on blue Run button in the middle left
    - This will run through all selected requests (I have 28 selected which is all of them in this folder)
8. Once all requests have run, click on the Collection Runner tab in the upper left 

RESULT 
The Choose a collection or folder and Run Order area is as if I have only selected 1 folder deep and not 3. 

EXPECTED
For the Choose a collection or folder and Run Order areas to have my original folder selection.

App information
Postman v7.9.0 

My environment 
   macOS Mojave 10.14.6
   MacBook Pro (15-inch, 2019)
   Processor 2.6 GHz Intel Core i7
   Memory 32 GB 2400 MHz DDR4

Additional context
I can replicate this issue on each run of my Collection Runner.
This is the first time that I've seen this. I updated 1 or 2 days ago to the 7.9.0 version. I updated to my last version less than a month ago (I believe) which did not reflect this issue. 
I am part of a Team with 9 collections and growing with over 3000 requests but only work out of 1 Collection. I do not use any other program in conjunction with Postman, connects or intercepts Postman processes of any kind.

**Comment by appurva21** [comment] 2020-02-11 06:55
Hi @dglanville, we made have certain improvements in Collection  Runner during our last few releases. Can you please update to the latest version of the app and check if this issue still persists for you.

To get the latest version either you can update the existing app or can download a new app from [here](https://www.postman.com/downloads/)

**Comment by appurva21** [comment] 2020-02-17 12:15
Closing the issue as we are not able to reproduce it. Please feel free to reopen if the issue still persists.

**Closed as completed by appurva21** 2020-02-17 12:15 UTC
Labels: bug, collection-runner, product/runtime
