### ISSUE TITLE
啥时候来个多语言版（When is a multi - language version）

### ISSUE THREAD

**Issue by a354123417** [a85/POSTMan-Chrome-Extension#4614] opened 2018-05-29 15:26 UTC

**Comment by kamalaknn** [comment] 2018-05-30 12:30
Hi @a354123417 

Thanks for your feedback. I'm marking this as a feature request.

**Comment by a354123417** [comment] 2018-06-01 07:00
Thank you!

**Comment by a85** [comment] 2019-03-10 04:45
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/3126

**Closed as completed by a85** 2019-03-10 04:45 UTC
Labels: feature, i18n
