### ISSUE TITLE
Oauth 2 building invalid request for Authoriztion Code grant type

### ISSUE THREAD

**Issue by jjlambros** [a85/POSTMan-Chrome-Extension#2565] opened 2016-12-16 00:47 UTC
When using the Authorization tab, Type = OAuth 2.0 to get a new access token using the Authorization Code grant type - the request to exchange the code for a token (from the Postman callback URL to the Access Token URL) fails.  It includes the client is and secret in both an Authorization header and and body of the POST causing the code exchange to fail.

This is not allowed per RFC-6749 / 2.3 which states "The client MUST NOT use more than one authentication method in each request.".  The request is properly failed by our Ping Federate OAuth server with the message - {"error_description":"The client MUST NOT use more than one authentication method in each request.","error":"invalid_client"}.

Postman should omit the client_secret=xxx from the request body.  Leaving the client_id=xxx in the body is required for this grant type per RFC-6749 2.3.1 last paragraph.  Alternatively, Postman could omit the Basic Authorization header on the POST.

Perhaps some OAuth servers don't enforce the RFC, however Ping Federate does.

Version/App Information:

 1. Postman Version:  4.9.2
 2. App (Chrome app or Mac app): Mac
 3. OS details: OSX 10.11.6
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there:  Don't know
 6. Expected behaviour: client credentials either in header or body, but not both
 7. Console logs None
 8. Screenshots N/A

Steps to reproduce the problem:

1. Create any API call
2. In Authorization tab, choose type OAuth 2.0
3. Fill in all values and select Grant Type - Authorization Code
4. Click request Token
5. Complete and submit the OAuth credential page.
6. Observe error in OAuth server logs or Gateway logs

**Comment by SamvelRaja** [comment] 2016-12-19 15:05
@jjlambros Thanks for bringing this to our notice. We will keep updated this thread regarding the update from our end.

**Comment by harryi3t** [comment] 2017-09-11 12:43
duplicate of https://github.com/postmanlabs/postman-app-support/issues/2296
as a workaround follow the instructions as mentioned here https://github.com/postmanlabs/postman-app-support/issues/3357#issuecomment-322816409

**Closed as completed by harryi3t** 2017-09-11 12:43 UTC
Labels: bug, Auth
