### ISSUE TITLE
Set Content-Length header automatically when posting a binary file

### ISSUE THREAD

**Issue by poisa** [a85/POSTMan-Chrome-Extension#4064] opened 2018-01-12 23:50 UTC
It would be really handy if Postman set the Content-Length header automatically after you select a binary file. If this behaviour is not desired for everyone, it could be turned into an optional setting.

**Comment by thecuriousdev** [comment] 2018-01-15 11:53
@poisa thanks for suggesting this, We'll look into this and keep you posted here.

**Comment by Efaq** [comment] 2019-05-31 08:27
Hi all!

What is the status of this one?

I am using Postman 7.13.0 and, when sending pictures as binary files, together with Content-Type as application/octet-stream, Postman automatically sets the content-length header MOST OF THE TIME. Sometimes it misses it, quite randomly it seems, and in this case it sends content-length empty, instead of not sending it at all.

Is anyone else also experiencing this behavior?

**Comment by shamasis** [comment] 2019-06-30 18:17
Postman sends the content-length header for binary files all by itself. Need to reproduce under what scenarios is this missed. Still keeping this as a feature request so that we end up adding the configuration feature suggested.

**Comment by codenirvana** [comment] 2019-08-22 10:58
@poisa @Efaq `Content-Length` header is always set irrespective of the request body type.

Can you share more detail about the request, file, and the headers set which cause this issue?
Also, how are you debugging the headers sent for the request (Postman console or anything else)?

**Comment by poisa** [comment] 2019-08-22 16:03
@codenirvana Mind you that it has been over a year and a half since I first posted this. At the time I was using Postman literally every day for my work. Now I barely use it so I can't confirm if this bug is still present. 

In this case, what I was doing is creating a PUT request to upload a file to an Amazon S3 bucket. Just an empty request with the URL to the amazon endpoint, chose `Body > Binary` (and select a file), and the `Content-Length` field would not be sent. I could tell because AWS creates an empty S3 object when this header is missing. Adding the `Content-Length` header manually would make it work correctly.

**Comment by codenirvana** [comment] 2019-09-18 18:51
@poisa Thanks for the response, I assume it got fixed over time 😕.

Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists.

**Closed as completed by codenirvana** 2019-09-18 18:51 UTC
Labels: feature, Request, configurations, blocked/need-info, product/runtime, request-body-configuration

**Comment by Michael-LiK** [comment] 2020-05-06 16:14
i meet the same problem ,i use the postman to upload file with aws s3. I will get a empty file when i  put file without use content-length

**Comment by txwizard** [comment] 2023-07-07 18:57
I am running Postman Version 10.15.8, attempting to send binary data with a Content-Type declared as audio/mpeg, and my endpoint reports a Content-Length header value of zero.

**Comment by txwizard** [comment] 2023-07-08 04:52
I figured it out, and I think it's worth documenting.

The file length is reported as zero when a file is selected from a location other than the default directory and access to other directories is denied per the PostMan settings.
