### ISSUE TITLE
Global Variables are Not Found When Switching Workspaces

### ISSUE THREAD

**Issue by ScottCarr73** [a85/POSTMan-Chrome-Extension#9796] opened 2021-04-05 14:23 UTC
**Describe the Issue**
I have several Global variables that I have created for each Workspace.  If I open a workspace, and try to run one of the Requests, it gives me an error:  getaddrinfo ENOTFOUND {{defaulturl}}.  One thing I will note, is that in error, the defaulturl is called DefaultUrl in Globals.

The request has this:  **{{DefaultUrl}}/topics** in the url, but the error comes up with all lower case.

The Global variable exist in the Globals tab.  This issue also shows up for any Global variables we have.

The only way I have found to workaround this issue, is Delete the variable, add it back, with the same name and value, Save the tab, and then I can run my requests.  This only works in the current postman session, once I close and come back in, I have to Delete each of the variables, and re-add them, so I can work in that session.

This issue shows up in each workspace.  It seems that if we change ALL of the Global variables, then the Workspace is fine during that session.  If we switch Workspaces, we have to update the Global variables again.

My QA team has to follow these same steps, each time they want to run a qa test we have setup in Postman as well.  This is affecting our use of Postman, and making running requests pretty frustrating.

**Steps to Reproduce**
* Open Postman
* Select a Different Workspace
* Run a Request that uses a Global variable.  Example:  {{DefaultUrl}}/mytest

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/51333022/113583712-9dacc500-95ef-11eb-9c73-d64a883fc2f1.png)

**Environment Information**

 - Platform Type:  Linux, Windows, and Mac  (Different users in our organization have dealt with this issue)
 - Postman Version:  8.1.0  (we just upgraded to the latest version for this verification)
 - Operating System:  Manjaro Linux, Windows 10, and Mac Big Sur

**Comment by DannyDainton** [comment] 2021-04-05 19:15
Hey @ScottCarr73

Just to clarify, the title says Environment variables but the issue is describing Global variables - is that correct?

As you have described the different parts of the UI and the variables you can see when switching Workspaces, could you provide some example screenshots of these, please?

It's much easier for us to _see_ what happening with those attached to the issues.

Could you also confirm that all the variables are saved and the values are in the initial value section? Do you have variables of the same name under different scopes, in any of the Workspaces?

**Comment by ScottCarr73** [comment] 2021-04-07 02:07
> Just to clarify, the title says Environment variables but the issue is describing Global variables - is that correct?

Yes, it is Global variables that is having the issue.
> 
> As you have described the different parts of the UI and the variables you can see when switching Workspaces, could you provide some example screenshots of these, please?

Opening Postman, and running a request results in the error.  The Global variables are not resolved as part of the request.

> Could you also confirm that all the variables are saved and the values are in the initial value section? Do you have variables of the same name under different scopes, in any of the Workspaces?

All the Variables are saved, and the values are in the initial value section.

**Comment by DannyDainton** [comment] 2021-04-07 06:10
Thanks for that, could you also share some images, full app ones are better than zoomed in specific ones. Please mask any sensitive information being posting. 

Without seeing the issue in action, it's going to be tricky to see what's happening and replicate it fully.

**Comment by DaniSchenk** [comment] 2021-04-13 15:07
We're experiencing the exact same bug.

Sometimes, when switching Workspaces (both define globals), globals are not applied in requests and stay unresolved. In the UI they are shown correctly, but in the "Console" log of the executed request we find unresolved global variable names (e.g. in Request Headers: `custom-header-name: "{{global-header-value}}"` )

We found a workaround: clicking "Reset All" in the "Environments" - "Globals" tab restores expected behavior

To be clear: we're experiencing this bug over and over again. Using the workaround only restores expected behavior for some time.

OS: Windows 10, Postman: v8.2.2

**Comment by kepikoi** [comment] 2021-04-13 15:09
Experiencing the same issue. Global variables vanish when working with multiple PM environments. Working around this issue via the "Reset all" button in the Globals tab. This revives the variables in the current env.
@DannyDainton here's a quick screencap demonstrating the issue with two environments I just created on a whim
![pm](https://user-images.githubusercontent.com/12378498/114575852-e19c6b80-9c7a-11eb-9f13-e3e08c8b7c96.gif)

**Comment by ScottCarr73** [comment] 2021-04-13 20:15
@kepikoi @DaniSchenk Thanks.  Your workaround is a lot easier than mine.  ;-)  Thanks @kepikoi for the videos, I didn't have time to create them.  My team is still experiencing this error.

I have noticed that it shows up more, when you switch between multiple workspaces.

**Comment by timbochamp** [comment] 2021-04-15 13:51
I believe this is similar to #9729 with environment variables not resolving after workspace switching or on the initial load of an environment. I'm able to reproduce this global variable issue with {{DefaultUrl}} changing to {{defaulturl}} and not resolving on workspace switch periodically. I'm logging this as a separate bug for the team to investigate. Thanks for the report!

**Comment by Nmirontsev** [comment] 2021-05-21 20:52
@kepikoi , thank you for the workaround. It was a blocker for me.
@timbochamp , in my case all references to globals are not working. Specifically:
- requesting global variable from request body. I have a combination of environment and global variables in request body. Environment variables are fetched correctly, but globals are not.
- requesting global variable from test script. Console shows that variable is not defined, while it is shown in UI. As @kepikoi mentioned, using Reset All in globals editing UI resolves the issue.
Postman version: 8.5.1. I believe it started to happen to me after 8.3.0 release.

**Comment by Ashish-uzumaki** [comment] 2021-06-08 15:40
Hi @Nmirontsev @ScottCarr73 This Issue has been resolved in latest version ( v8.6.1 ) of [postman-app](https://www.postman.com/downloads/), and [postman-web](https://web.postman.co).

Do let us know if you face any issues!

**Closed as completed** 2021-06-08 16:16 UTC
Labels: bug, variables, product/runtime, workspaces
