### ISSUE TITLE
Postman Interceptor not working for sending cookies

### ISSUE THREAD

**Issue by gauravcanon** [a85/POSTMan-Chrome-Extension#3146] opened 2017-06-10 21:53 UTC
Postman Interceptor not working, I am trying to test API's which requires the user to be logged in. I am using interceptor for that. Enabled both in chrome and in App version. The user is not getting logged in into the system . 

But the same thing is working with **httprequestor** which is for Mozilla same API URL is working fine with cookies provided to **httprequestor** . 

What I am doing wrong I am not getting

## App Details:

Version 5.0.0 (5.0.0)

**Comment by numaanashraf** [comment] 2017-06-12 08:33
Hi @gauravcanon, could you let us know your Postman App and Interceptor versions and detail the steps you did to replicate this? We'll look into this.

**Comment by gauravcanon** [comment] 2017-06-26 06:21
Postman Application Version =  Postman 5.0.1
Postman inteceptor = Postman Interceptor 0.2.22

**Comment by alan-givati** [comment] 2017-07-19 15:21
Hi.  I'm experiencing the same issue on 5.1.0-canary02.
Postman Interceptor 0.2.23

**Comment by gauravcanon** [comment] 2017-07-19 15:33
@numaanashraf can you update on this

**Comment by sdnts** [comment] 2017-07-26 11:18
@gauravcanon I'm unable to reproduce this on v5.0.2 on Chrome.
The Interceptor is not available on the native apps. Can you make sure you're on the Chrome App?
Also, can you try this out on our [native apps](https://getpostman.com/apps)? These have inbuilt cookie handling and this shouldn't happen there.

**Comment by homerepope** [comment] 2017-08-07 01:00
@madebysid On the desktop app When i set Auto follow re-directs to false, it tells me I need to enable the Inteceptor?  Why is this the case if it is not part of the desktop app? (v5.1.3), I am constantly getting 302's on all my requests.  Thanks.
![screenshot](https://user-images.githubusercontent.com/10887296/29008790-982842d6-7aea-11e7-9b1f-e01362af1bae.png)

**Comment by gauravcanon** [comment] 2017-08-15 09:29
@homerepope un-install current postman, 
Go to chrome and find for extension Postman Interceptor, After installing in postman then click option **Postman chrome app** it will open postman application which is compatible with Postman Interceptor. Your problem can be solved with this. 
<img width="202" alt="screenshot 2017-08-15 11 25 40" src="https://user-images.githubusercontent.com/897747/29310127-d70a2f1e-81ac-11e7-9e07-6d7fcb8685ad.png">

**Comment by gauravcanon** [comment] 2017-08-15 10:06
I am using this version of the postman, I am on Mac OS X version 10.12.6 (16G29).
<img width="777" alt="screenshot 2017-08-15 11 43 26" src="https://user-images.githubusercontent.com/897747/29310752-55f5eb4a-81af-11e7-8dc4-fbec873b3bc8.png">
<img width="336" alt="screenshot 2017-08-15 11 44 53" src="https://user-images.githubusercontent.com/897747/29310753-56758b5c-81af-11e7-89dc-66405f4e6d9a.png">

_Previously I was not able to send cookies. But somehow I upgrade my system . with new installation I am able to see cookies are getting send in postman but two different versions._ 

I logged into my website, I get cookies, But the problem is what cookies I get on the website is not same as what postman app is getting from chrome.

**This is my Website cookies from Inspect manager  :** 
<img width="1043" alt="website" src="https://user-images.githubusercontent.com/897747/29311329-cee40828-81b1-11e7-82ac-6bd45ce6cfe3.png">

**This is my postman cookies. Currently, we are not using cookies so it is a success .**
<img width="1135" alt="postman" src="https://user-images.githubusercontent.com/897747/29311394-232123da-81b2-11e7-8bde-413a250b2844.png">

Same cookies working with **Httprequestor** on **Mozilla**

<img width="1200" alt="httprequtor" src="https://user-images.githubusercontent.com/897747/29311950-cf72cd22-81b3-11e7-9aef-89e97b88f398.png">

<img width="540" alt="mozilla" src="https://user-images.githubusercontent.com/897747/29311955-d2e534a4-81b3-11e7-9023-4ee19c385c26.png">

**Comment by gauravcanon** [comment] 2017-08-25 10:21
@numaanashraf @madebysid Any update on this issue?

**Comment by sdnts** [comment] 2017-08-28 09:59
@homerepope That looks like an erroneous alert, that shouldn't be there, we'll get that fixed.
 
@gauravcanon Do you have Interceptor capture enabled? Try turning that off. Currently, when the Interceptor is ON from the app, the request is made through Chrome, so all cookie attaching is done by Chrome, which means that two versions of the same cookie is very weird. Can you head over to `chrome://settings/content/cookies?search=cookie` and make sure the cookie you're trying to send is the same? I think there might be a rogue cookie in there.

**Comment by gauravcanon** [comment] 2017-09-06 08:01
@madebysid Interceptor Capture is on from Application. But using this I found new problem  `chrome://settings/content/cookies?search=cookie` there are two cookies are getting created. 
**domain.com** & **www.domain.com**. _Postman is cookies_ and _domain.com_ cookies are same but _www.domain.com_ cookies don't match.

**Comment by abhijitkane** [comment] 2019-07-01 13:26
Everyone - we’re finally ready to launch a beta for the Interceptor integration for the native Postman apps!

The Interceptor is a very useful part of the Postman workflow - making API calls in the context of the browser’s session is a common use case. Any use-case which requires you to login to the browser (effectively setting a cookie) and performing API calls from Postman was cumbersome at best. This is the first problem we’ve tried to address. The request capturing workflow is on its way too.

Details on getting started can be found at https://community.getpostman.com/t/interceptor-integration-for-postman-native-apps/5290.

**Comment by abhijitkane** [comment] 2019-07-05 09:50
Closing this. There are multiple issues mentioned here. The latest versions of Postman (7.2.2+) support cookie syncing via the Interceptor extension.

**Closed as completed by abhijitkane** 2019-07-05 09:50 UTC
Labels: bug, Interceptor

**Comment by unlox775** [comment] 2021-05-19 20:22
You guys totally suck.  Your doc's show how to configure cookie sending, but not how to actually USE the intercepted cookies.  You list how to install the Chrome extension, check the box in Postman app.  Great.  My indicator light is green.

If what I was wanting is for a F-ing indicator light to look pretty a green, then yes, you totally showed me all I needed.  But... NO I actually wanted to run a request, WITH the cookies I have intercepted from the browser!!!!!!!!!  NO. DOCS. AT. ALL. about how to actually use the cookies!!!

I go to a request in Postman and I see:
1. Under Headers. I can set a "cookie" key, to set the cookies myself.  Setting, or unsetting this has no effect.
2. There is a blue "Cookies" link, which opens up a modal called "Manage Cookies".  It is all blank.  So I think, "Oh, maybe I need to type in the domain name, who's cookies I want to scrape from my Chrome browser".  So I type in a domain name.  Nothing.  Freaking, it is now letting me to the same F-ing thing, manually type my own cookies.  NO indication of ANYTHING syncing down from the Chrome interceptor

My interceptor is running perfectly for intercepting requests, they show up in the handy "History" button on the left.  WHY is there nothing like this for cookies!!!!  WHY is there no "End-to-End" set of docs like:
1.  Here's how to configure the extension, app, check the box to intercept cookies (All the F-ing docs you have)
2. See in here ________________ where you can now see the cookies you were intercepting from Chrome, Now showing in Postman app
3. In a request you are setting, instructions of how to load some/all the cookies you intecepted, to add to your request.  Something here explaining how Not to use the Headers 'cookie' value, or if you do, whether it will override or merge with the cookies you have intercepted
4. After you have submitted, showing the cookies that actually got sent.  Maybe show "Hey look, (in the browser), the cookies are the same that you just sent from your request!"

After hours of trying to read your SH-- docs, I have given up.  I have tried 50+ different combinations of settings, requests and domains, and no matter what I do, after running the request, I look in the console (request headers), and NO cookies have been sent (at least nothing related to cookies brought over from my browser)

Please fix your SH--!!

**Comment by shashankawasthi88** [comment] 2021-05-24 06:18
@unlox775 while we look at the documentation gap, please follow this [tutorial](https://www.youtube.com/watch?v=Swjims0aOl4) explaining the step-by-step process of capturing cookie works.

**Comment by lzeee** [comment] 2021-06-29 09:46
> You guys totally suck. Your doc's show how to configure cookie sending, but not how to actually USE the intercepted cookies. You list how to install the Chrome extension, check the box in Postman app. Great. My indicator light is green.
> 
> If what I was wanting is for a F-ing indicator light to look pretty a green, then yes, you totally showed me all I needed. But... NO I actually wanted to run a request, WITH the cookies I have intercepted from the browser!!!!!!!!! NO. DOCS. AT. ALL. about how to actually use the cookies!!!
> 
> I go to a request in Postman and I see:
> 
> 1. Under Headers. I can set a "cookie" key, to set the cookies myself.  Setting, or unsetting this has no effect.
> 2. There is a blue "Cookies" link, which opens up a modal called "Manage Cookies".  It is all blank.  So I think, "Oh, maybe I need to type in the domain name, who's cookies I want to scrape from my Chrome browser".  So I type in a domain name.  Nothing.  Freaking, it is now letting me to the same F-ing thing, manually type my own cookies.  NO indication of ANYTHING syncing down from the Chrome interceptor
> 
> My interceptor is running perfectly for intercepting requests, they show up in the handy "History" button on the left. WHY is there nothing like this for cookies!!!! WHY is there no "End-to-End" set of docs like:
> 
> 1. Here's how to configure the extension, app, check the box to intercept cookies (All the F-ing docs you have)
> 2. See in here ________________ where you can now see the cookies you were intercepting from Chrome, Now showing in Postman app
> 3. In a request you are setting, instructions of how to load some/all the cookies you intecepted, to add to your request.  Something here explaining how Not to use the Headers 'cookie' value, or if you do, whether it will override or merge with the cookies you have intercepted
> 4. After you have submitted, showing the cookies that actually got sent.  Maybe show "Hey look, (in the browser), the cookies are the same that you just sent from your request!"
> 
> After hours of trying to read your SH-- docs, I have given up. I have tried 50+ different combinations of settings, requests and domains, and no matter what I do, after running the request, I look in the console (request headers), and NO cookies have been sent (at least nothing related to cookies brought over from my browser)
> 
> Please fix your SH--!!


I have the same problem. The chrome extention and postman seem to be working properly, but they are not.

**Comment by mirceade** [comment] 2021-11-16 11:16
Yes, same issue, this is junk.
