### ISSUE TITLE
Socks5 System Proxy not working with Postman Mac App

### ISSUE THREAD

**Issue by splagemann** [a85/POSTMan-Chrome-Extension#2480] opened 2016-11-21 08:14 UTC
1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Mac app
 3. OS details: Mac OS Sierra 10.12.1
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Can't say
 6. Expected behaviour: System Proxy should work
 7. Console logs:

```
GET https://api.somehost.dev/somepath                                      08:58:53.032

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND socks5127.0.0.1 socks5127.0.0.1:1080

Proxy:
    proxy:"http://SOCKS5127.0.0.1:1080"
    tunnel:true
```

8. Steps to reproduce:
- Configure Socks5 Proxy on `localhost:1080`
- Configure Proxy with this `proxy.pac` script:
```
function FindProxyForURL(url, host) {
    PROXY = "SOCKS5 127.0.0.1:1080"

    if (shExpMatch(host,"(api|anotherapi|somesubdomain).somehost.dev")) {
        return PROXY;
    }

    // Everything else directly!
    return "DIRECT";
}
```
- Try to connect with Postman Mac App

**Comment by vegetableman** [comment] 2016-11-21 10:20
@splagemann Thanks for reporting this issue 👍 . Closing it, as it's a duplicate of #1321. It's part of the roadmap and you could subscribe to that issue to stay tuned.

**Closed as completed by vegetableman** 2016-11-21 10:20 UTC
