### ISSUE TITLE
Merging PR no longer triggers a backup in custom github domain (integration)

### ISSUE THREAD

**Issue by frdesnous** [a85/POSTMan-Chrome-Extension#11119] opened 2022-07-27 09:12 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi, 
we have integrations set up to back up our collections in a github custom domain.
We noticed recently that when merging PR into a collection, the back up run is not longer triggered.
Backup run is triggered only when doing a change directly in the collection.
This used to work fine. Is it a know issue?

### Steps To Reproduce

1. create a custom domain backup integration 
2. create a fork of your collection
3. do a small change in the new fork
4. create a PR and merge it
5. go to integration run log

### Operating System

Windows

### Postman Version

Version 9.25.2

### Postman Platform

Postman App

**Comment by Atishay4294** [comment] 2022-07-27 13:34
Hi @frdesnous
Thank you for reaching out.

I understand that this is not the expected behavior as merging collection PRs should trigger the backup integration. This seems to be due to some recent changes and we are able to replicate the issue.

We'll update this thread after addressing the same :)

**Comment by Atishay4294** [comment] 2022-08-11 17:44
Hi @frdesnous 
This issue should be fixed now :)

Please confirm.

**Comment by Atishay4294** [comment] 2022-08-19 07:36
Closing the issue, feel free to reopen if you run into problems again.

**Closed as completed by Atishay4294** 2022-08-19 07:36 UTC
Labels: bug, product/integrations
