### ISSUE TITLE
New request example does not inherit parent request body type

### ISSUE THREAD

**Issue by AlesBudna** [a85/POSTMan-Chrome-Extension#11139] opened 2022-08-02 14:46 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

"Add example" on HTTP collection's request copies body of parent request but does not inherit its body type (e.g., JSON). Basic text is always applied and user needs to switch it then. 

### Steps To Reproduce

1. Right click on collection's request.
2. Choose "Add example" in selection list.
3. Show new request example contents.
4. Click on "Body" tab of request example and see the contents in plain text.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/12699220/182402210-2b5fb03f-9d62-4038-8fc9-dec31797586c.png)

### Operating System

Windows 10 Pro

### Postman Version

9.26.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment] 2022-08-02 14:57
Closing as a duplicate of #8482

**Closed as completed by DannyDainton** 2022-08-02 14:57 UTC
Labels: examples, duplicate
