### ISSUE TITLE
Run requests in Postman Desktop app and Postman runner using same data file 

### ISSUE THREAD

**Issue by raghav19** [a85/POSTMan-Chrome-Extension#6307] opened 2019-04-16 09:50 UTC
**Describe the bug**
I have written test scripts in postman for automation which i want to use it with multiple data sets for which runner gives me the capability to use the data file like a json or csv.
However now that i use the data from the json file, i have many cases where i need to run only certain requests in my worflow manually through the console. By console , i mean the desktop app of Postman where we quickly run requests using SEND button. In this case i cannot make use of the test scripts developed for automation purposes as they look out for the data [json] file

**Expected behavior**
Want to use the same data file for my console runs as well as runner runs using newman

**Screenshots**

**App information (please complete the following information):**
 - Native App
 - Postman Version [e.g. 7.0.8]
 - OS: Windows 10

**Additional context**
Alternatives Tried:
Pick any 1 data from the set and use it in environment and run the request using the postman environment in the console

**Comment by vikiCoder** [comment] 2019-05-21 18:50
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/6275.

**Closed as completed by vikiCoder** 2019-05-21 18:50 UTC
Labels: feature, data-file, product/runtime
