### ISSUE TITLE
aws sigv4 support: missing aws_session_token and unwanted content-type on get requests

### ISSUE THREAD

**Issue by mcleane** [a85/POSTMan-Chrome-Extension#2907] opened 2017-04-06 10:44 UTC
Hi,

Using postman, trying to test an api hosted on an aws api gateway that requires an aws v4 signature for authentication with federated credentials.

For a request, on the Authentication tab I can add the access and secret key but there is no where to add the session token. Session Tokens need to be sent in addition to Access and Secret Keys when using federated authentication.

As a work around I can add an environment variable to the header X-Amz-Security-Token, however when you click on update request, the environment variable is replaced with the actual session token, so when you try to run the request again the session token never gets update, its stays at the first value.

In addition when a GET request is created, an unwanted Content-Type header of application/x-www-form-urlencoded is automatically added to the request even though no Content-Type header is set nor any content in the body. This additional header breaks my api as its deemed an unsupported media type.

Version/App Information:

 1. Postman Version:  4.10.5
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: OSX 10.11.6
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour:
1. Postman AWS Authentication should provide the ability to enter an AWS Security Token for V4 Sig.

2. Postman should not add a Content-Type header of application/x-www-form-urlencoded when the body is empty and request is of type GET.

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
No option to supply an AWS Session Token
<img width="1057" alt="missing security token" src="https://cloud.githubusercontent.com/assets/11022388/24749975/761db9ec-1b08-11e7-9f59-0eb988187b90.png">

Below shows the headers before and after clicking on update request. After request is updated session token changes from a variable to hard coded value and there is an additional content-type header even though its a GET request.
<img width="1055" alt="headers" src="https://cloud.githubusercontent.com/assets/11022388/24749976/77dc624c-1b08-11e7-90ca-b487d23cbda2.png">

Steps to reproduce the problem:
1. Create New Request
2. Set method as GET
3. Enter an aws api gateway endpoint
4. Click on Authentication and select AWS Signature
5. Enter appropriate values, with the Service Type as execute-api
There is no where to add an AWS Security Token
6. Click on headers tab and add X-Amz-Security-Token that references an environment variable eg {{aws_security_token}}
7. Back on authentication tab, click on Update Request
8. Go back to headers tab
The X-Amz-Security-Token header is now hardcoded, and there is an unwanted Content-Type header set to application/x-www-form-urlencoded.

**Comment by kamalaknn** [comment] 2017-09-11 12:25
@mcleane can you try out our native apps `5.2.0` and let us know if you are still having issues? You can find the download link for your platform [here](https://www.getpostman.com/apps).

**Comment by ek-akqa** [comment] 2017-09-25 18:21
@kamalakhn I could not reproduce a similar issue in the macOS native app. The latter lacks the interceptor though, so I really hope the Chrome app will get its fix soon.

**Comment by kamalaknn** [comment] 2017-09-25 18:28
@ek-akqa in the long term the native app is a better solution to bet on because Google has announced plans to deprecate support for Chrom apps. 

Could you elaborate on your workflow with the interceptor that is blocking you from migrating to the native apps, so that we could try to support it?

**Comment by ek-akqa** [comment] 2017-09-26 08:01
hey, @kamalaknn, thanks for the support, but essentially, please ignore my reply above as I found the option to disable redirects in the native app, and it doesn't actually require the use of the interceptor! So all's working for me now in the native app. Thank you!

**Comment by kamalaknn** [comment] 2017-09-26 08:03
@ek-akqa Great! 

I am closing this issue as this feature is supported in the latest version of our Native apps.

**Closed as completed by kamalaknn** 2017-09-26 08:03 UTC

**Comment by solariswu** [comment] 2018-01-04 01:38
Find the issue of 

when a GET request is created, an unwanted Content-Type header of application/x-www-form-urlencoded is automatically added to the request even though no Content-Type header is set nor any content in the body. This additional header breaks my api as its deemed an unsupported media type.

in native Mac OSX postman 5.5.0
