### ISSUE TITLE
Custom domain not released when underlying collection is deleted

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6421] opened 2019-05-06 12:55 UTC
**Describe the bug**
When a custom domain is in use, deleting the underlying collection doesn't free it up for use with a different collection.

**To Reproduce**
1. Add a custom domain
2. Publish a collection using that domain
3. Delete the published collection
4. See that you're unable to associate another collection with the custom domain

**Expected behavior**
When deleting a collection that's associated with a custom domain, the domain should be free be pointed to a different collection.

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/57226253-3c7bb180-6fd4-11e9-81b4-23e20bceaf2d.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.0.8

**Additional context**
[Filed by Postman]

**Comment by eprothro** [comment] 2019-06-24 17:59
We are trying to use the revision control features in a new product's workflow and this issue is biting us.

1. fork (development)
2. publish fork with custom domain
3. merge + delete fork
4. re-fork
5. I can't associate the new fork's documentation with the custom domain

```
Someone else on your team has already published a documentation with this domain. Ask them to unpublish their documentation before publishing yours.
```

But I cannot as the collection is deleted.

Due to #5056, I don't see another way to view or un-publish the phantom collection.

**Comment by eprothro** [comment] 2019-06-24 18:06
Workaround: delete and re-add the custom domain.

**Comment by Cazaimi** [comment] 2019-08-26 03:54
@eprothro , thanks for posting this use case! Really interesting to see collection forks being published to custom domains. Another, simpler workaround is:

1. The current system will dissociate the custom domain from the collection once it realizes that the underlying collection is deleted. 
2. For that to happen, simply hit your custom domain/published docs URL. For example, My published doc URL can be `https://documenter.getpostman.com/view/153432/324342` -> `https://my.domain.com`
3. Once your domain/Docs URL is hit, the system, will dissociate `my.domain.com` from `documenter.getpostman.com/view/153432/324342`, and you can then use the said domain to publish another collection, _within 10 minutes_.

This way, you wouldn't have to re-add custom domains. :)

We're working to make this system more fluid for the user, so that you don't have to perform step-2 at all, and `my.domain.com` gets dissociated as soon as you delete the collection. 

cc @godfrzero

**Comment by Cazaimi** [comment] 2019-08-26 03:59
@Raja-Simha , This thread can serve as documentation for this particular case, and it's not a bug as it can be solved by the steps mentioned above. Can be marked as closed.

**Comment by mjang** [comment] 2019-08-30 18:11
> @Raja-Simha , This thread can serve as documentation for this particular case, and it's not a bug as it can be solved by the steps mentioned above. Can be marked as closed.

So you're saying that the procedure listed here is part of official Postman documentation?

**Comment by Cazaimi** [comment] 2019-09-03 04:51
@mjang, I wouldn't call it a documentation on how to deal with this issue, rather a temporary workaround that lets you unblock your flow and _eliminates any impediment._

> @eprothro , thanks for posting this use case! Really interesting to see collection forks being 
> ...
> ...
> ...
> We're working to make this system more fluid for the user, so that you don't have to perform step-2 at all, and `my.domain.com` gets dissociated as soon as you delete the collection.
> 
> cc @godfrzero

**Comment by DannyDainton** [comment] 2020-09-05 09:14
Hey @Cazaimi,

Are we able to close this out or convert from a bug to a feature request?

**Closed as completed** 2022-07-21 10:03 UTC
Labels: bug, product/documentation
