### ISSUE TITLE
Binary file download broken

### ISSUE THREAD

**Issue by jimonthebarn** [a85/POSTMan-Chrome-Extension#2903] opened 2017-04-05 21:08 UTC
It seems the binary file download using "send and download"is broken.

Steps to reproduce:
Just enter a link to a file (e.g. http://ipv4.download.thinkbroadband.com/5MB.zip) and issue a get request using the "send and download"button. It will download a file which ends up being almost twice as big. The file will be corrupted as well.

 1. Postman Version:
Postman for Windows
Version 4.10.5
win32 10.0.15031 / x64

 3. OS details:
Windows 10 Version 1607 Build 15031.0

 4. Is the Interceptor on and enabled in the app:
disabled

 5. Did you encounter this recently, or has this bug always been there:
I cant tell the exact version since it is not working anymore. It still works in the chrome extension though.

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

GET
http://ipv4.download.thinkbroadband.com/5MB.zip
11:06:04.644
Request Headers:
cache-control:"no-cache"
Postman-Token:"073e3e64-1868-4555-bf21-cd4aeca306de"
User-Agent:"PostmanRuntime/3.0.11-hotfix.2"
Accept:"*/*"
Host:"ipv4.download.thinkbroadband.com"
accept-encoding:"gzip, deflate"
Response Headers:
server:"nginx"
date:"Wed, 05 Apr 2017 21:05:09 GMT"
content-type:"application/zip"
content-length:"5242880"
last-modified:"Mon, 02 Jun 2008 15:30:42 GMT"
connection:"keep-alive"
etag:""48441222-500000""
access-control-allow-origin:"*"
accept-ranges:"bytes"

**Comment by Skinner927** [comment] 2017-04-06 19:50
From thinkbroadband.com

> These files are made of random data, and although listed as zip files, will appear to be corrupt if you try and open them.

However, I too am experiencing this issue. Here's a test file that will actually extract: http://www.colorado.edu/conflict/peace/download/peace.zip but will fail with Postman.

**Comment by jkweb3** [comment] 2017-04-07 15:04
I too am experiencing this with PDF files from my system. Worked in previous versions of Postman for Windows as far as I know up until 4.10.5. Interestingly it works in Postman for Chrome 4.10.5.

**Comment by numaanashraf** [comment] 2017-04-07 21:47
@jimonthebarn, @Skinner927, @jkweb3 This is addressed in `v4.10.6` that is out for Postman native apps now. Could you update and let us know if the issue is resolved?

**Comment by jkweb3** [comment] 2017-04-07 23:00
I can confirm that I got 4.10.6 today and it has been fixed. Thanks!

**Closed as completed** 2017-04-07 23:43 UTC
