### ISSUE TITLE
Javascript - Fetch code snippet should not set body for GET requests

### ISSUE THREAD

**Issue by klivian** [a85/POSTMan-Chrome-Extension#10427] opened 2021-11-08 21:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Generating a code snippet with Javascript - Fetch against a GET request sets the body of the request as an empty string, whereas Fetch requires it to not be set.

### Steps To Reproduce

Create or select an HTTP GET request
Generate a code snippet for JavaScript - Fetch
See the body tag is set

When running this code, I get the error
`error TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.`

Removing the line that sets body: raw removes this error and renders the correct output to the console

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/71658347/140819395-899b2265-bdb3-4631-a096-198582591a49.png)

### Environment Information

```markdown
- Operating System: Windows
- Platform Type: Native App
- Postman Version: 9.1.3
```

### Additional Context?

See : https://github.com/github/fetch/issues/402

**Comment by DannyDainton** [comment] 2022-03-18 11:06
Hey @klivian 

Can you confirm if this is still an issue for you, please?

I'm unable to reproduce this in the latest version of the platform.

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/17089546/158991889-cf4249d7-25ce-4ffd-985e-b66d8fd8e74c.png">

The only way that I would see the `raw` variable on the code snippet is if I'd selected that option in the body:

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/17089546/158992248-80bf8990-f490-41b7-b68d-2e1139b91f8e.png">

**Comment by klivian** [comment] 2022-03-18 11:12
Thanks @DannyDainton - can confirm that switching from "raw" to "none" in the body options (radio buttons) solves this issue for cases where the body should be empty. If not, it provides empty-string as input

**Comment by DannyDainton** [comment] 2022-03-18 11:15
Good to hear, I'm going to close this issue. The default is set to `none` when creating a new request by opening a tab.

**Closed as completed by DannyDainton** 2022-03-18 11:15 UTC
Labels: need-more-info, product/codegen
