### ISSUE TITLE
Chosen Files in formdata posts are not saved

### ISSUE THREAD

**Issue by fcheadle** [a85/POSTMan-Chrome-Extension#4953] opened 2018-08-02 16:53 UTC
**Description**
If you have a POST request saved as part of a collection,
With a body of type "FormData",
When you choose a file to post,
Then export the collection,
The postman_collection.json file will not contain the source of the file chosen,
And an attempt to run it via Newman will throw a "Not Found" error

**To Reproduce**
1. Create a new and empty collection
2. Create a POST request to any endpoint
3. Set the Body of the request to be formdata
4. Set the key to some value and use the dropdown to set the type to "File"
5. Click the "Choose Files" button and select a file.
6. Save the request to your new collection
7. Export your new collection as postman 2.1 file.
 
**Expected behavior**
I expected that the source of the file would have been exported to the JSON. It is not, and now whenever I need to edit a large collection, I have to use a diff tool to figure out where to paste back in my file sources

**Screenshots**
<img width="636" alt="bug001" src="https://user-images.githubusercontent.com/3935323/43598387-cc7dc61e-9641-11e8-8cd3-34dcece6cc19.png">
<img width="435" alt="bug002" src="https://user-images.githubusercontent.com/3935323/43598396-d1c93356-9641-11e8-8182-a2119c4416dd.png">

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.2.3
 - OS: Windows 10

**Additional context**
Below is the collection v2.1 that I exported when I was writing up these steps to reproduce. Since I cannot upload the json file here, I have pasted it in entirety:

`{
	"info": {
		"_postman_id": "1070081c-6e3b-47f2-a877-30f40592c781",
		"name": "Proof of Not Saving Files",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"_postman_id": "2655ed05-40e1-40a8-9eb2-fd799699c623",
			"name": "Upload a Photo",
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "Authorization",
						"value": "Bearer {{token}}"
					}
				],
				"body": {
					"mode": "formdata",
					"formdata": [
						{
							"key": "file",
							"type": "file"
						}
					]
				},
				"url": {
					"raw": "{{api}}images/organization/{{dynamicOrgKey}}",
					"host": [
						"{{api}}images"
					],
					"path": [
						"organization",
						"{{dynamicOrgKey}}"
					]
				}
			},
			"response": []
		}
	]
}`

**Comment by numaanashraf** [comment] 2018-08-03 07:51
Duplicate of #4320

**Closed as completed by numaanashraf** 2018-08-03 07:51 UTC
