### ISSUE TITLE
Sharing collection between workspaces does not share values for collection variables

### ISSUE THREAD

**Issue by stvrdinic** [a85/POSTMan-Chrome-Extension#8093] opened 2020-02-21 09:03 UTC
When sharing a collection between workspaces, and the collection at hand has it's own collection variables (keys and values), for newly created/shared collection in the new workspace values for the collection variables are blank.

Steps to reproduce:
1. create a workspace X with a collection
2. define variable keys and values for the collection
3. create another workspace Y
4. share collection from the step 1 to the new workspace Y
5. check the collection variables for the shared collection in the workspace Y (variable values were blank for me even though they existe/ed in the workspace X).

Issue noticed on a app version  v7.18.1.

**Comment by stvrdinic** [comment] 2020-02-21 09:09
Forgot to mention: both workspaces are personal/private

**Comment by sankalp0o** [comment] 2020-02-24 11:22
Hey @stvrdinic 
This shouldn't be happening. Let us look into this.

**Comment by sankalp0o** [comment] 2020-02-24 11:29
@stvrdinic we are unable to reproduce this. Are you seeing this behavior consistently using the steps you've mentioned?

**Comment by stvrdinic** [comment] 2020-02-24 13:37
I think I just figured out what happened: in the shared collection variables didn't have definied "Initial" values but just the "Current value". 

Sharing that collection doesn't copy values from the "Current value" column if "Initial value" is not defined. Please confirm this is expected :)

**Comment by sankalp0o** [comment] 2020-03-01 13:31
Yes, you are correct. "Current value" itself isn't synced and hence would not be the same in different workspaces.
I'm closing this issue but if you think there can an improvement made here based on your work-flow, please do reply back and we'd be happy to reopen this!

**Closed as completed by sankalp0o** 2020-03-01 13:31 UTC
