### ISSUE TITLE
GRPC Reflection not working

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [a85/POSTMan-Chrome-Extension#13001] opened 2024-07-10 20:35 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

GRPC reflection is not working with the error message "Details: 1 CANCELLED: Call Cancelled" almost instantaneously after clicking "Retry":
<img width="803" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/5585339/8c004108-1a77-410f-b963-86b241f01942">

Using `grpcurl bla.ticket.edenred.net:8081 list` works:
<img width="583" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/5585339/aa67eb9b-03e5-4b42-b39c-25309e9afc7f">

### Steps To Reproduce

1. Open new request
2. Try GRPC Reflection

### Operating System

macOS

### Postman Version

11.3.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by parthverma1** [comment] 2024-07-10 23:07
This issue is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/12997

**Closed as completed by parthverma1** 2024-07-10 23:07 UTC

**Comment by ronork** [comment] 2024-07-12 06:33
Hey, @Leonardo-Ferreira   thank you for reporting the issue. 
We have resolved this issue in the latest release of the Postman app (v11.3.2). Please update your app to verify if everything is now working correctly.
