### ISSUE TITLE
Does not properly work with dd() from Laravel

### ISSUE THREAD

**Issue by yurii-github** [a85/POSTMan-Chrome-Extension#10043] opened 2021-06-17 14:11 UTC
- Platform Type: desktop
 - Postman Version: v8.6.2
 - Operating System: linux
- Laravel Framework: 8.32.1

When run dd in Laravel preview does not show detailed debug data, data exists when you click on raw tab

## Reproduce

1. run simple dd in Laravel controller
```
public function __invoke(Request $request) {  dd(Collection::make(['a','b','c'])); }
```
2. see in response
![image](https://user-images.githubusercontent.com/1162656/122411450-70847780-cf8d-11eb-8a22-37fa1cde78b8.png)

![image](https://user-images.githubusercontent.com/1162656/122411654-9742ae00-cf8d-11eb-9f2f-90d44de5309b.png)

# Conclusion

If I copy response into html file and run it, I see that output is hidden behind JS toggle
![image](https://user-images.githubusercontent.com/1162656/122412657-6d3dbb80-cf8e-11eb-9c56-858c8dbe802d.png)

but preview does not allow me to toggle

**Comment by leandrohago** [comment] 2022-02-23 03:17
This is happening because [Postman](https://www.postman.com/) disables _**javaScript**_ in **Preview** tab.
There's a opened issue for that https://github.com/postmanlabs/postman-app-support/issues/2646.
And I found this in [community page](https://community.postman.com/t/javascript-not-enabled/19277)

If anybody knows a workaround for that please post here.

**Comment by DannyDainton** [comment] 2022-05-05 11:07
Closing as duplicate of #2646

**Closed as completed by DannyDainton** 2022-05-05 11:07 UTC
Labels: product/runtime
