### ISSUE TITLE
Cannot login google 500

### ISSUE THREAD

**Issue by adardesign** [a85/POSTMan-Chrome-Extension#7305] opened 2019-09-11 17:48 UTC
Trying to log in
via regular username password, and via google.

**To Reproduce**
1. Go to https://identity.getpostman.com/login

**Expected behavior**

**Screenshots**
![error](https://user-images.githubusercontent.com/23543/64721509-a46a6900-d49a-11e9-9ce6-4ade0b073258.png)

**App information :**
 - Chrome App, Native App]
 - Postman Version 7.6.0 (7.6.0)
 - OS: macOS High Sierra 10.13.2

**Comment by godfrzero** [comment] 2019-09-22 23:39
@adardesign The issue description states that the issue is occurring in both the Chrome & Native apps. It'd be useful if you could post screenshots of both in this case. In addition, could you let us know:

1. When you started to see this issue
2. If you or your team enabled additional authentication methods before this error started to appear

**Comment by elssar** [comment] 2019-10-01 00:44
@adardesign are you still having trouble signing in to Postman?
We have not been able to reproduce this, so closing the ticket. Please reopen if you are still can't signin.

**Closed as completed by elssar** 2019-10-01 00:44 UTC
Labels: bug, product/login
