### ISSUE TITLE
Postman Collection Runner Stops Test Run If Any Request Has Empty Url

### ISSUE THREAD

**Issue by mariotee** [a85/POSTMan-Chrome-Extension#7778] opened 2019-12-11 18:21 UTC
**Describe the bug**
When a request in a collection has an empty URL, then not all tests run in Collection runner 

**To Reproduce**
1. Create New Collection
2. Create a Request in Collection with Tests
3. Create a Request with empty URL
4. Create another Request in Collection with Tests
5. Run Collection Runner
6. See Collection Runner output only shows tests for request in Step 2

**Expected behavior**
I am expecting every test to run, but the collection stops when it hits the empty request. This is easy to find when there are only 3 requests like in the repro steps, but when someone has hundreds of requests (and the empty request was made by accident), then this is harder to find than it should be.
The DevTools only says that a "request url is empty", but it does not say which one.

**Screenshots**
![image](https://user-images.githubusercontent.com/23297151/70648437-a7e3cc80-1c10-11ea-9dc6-5e28510f1526.png)
**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]:    _Windows x64 Desktop App_
 - Postman Version [e.g. 7.0.0]:  _v7.13.0_
 - OS: [e.g. macOS High Sierra 10.13.2]: _Windows 10 x64_

**Additional context**

**Comment by saswatds** [comment] 2020-02-12 02:32
Closing this issue as its a duplicate of https://github.com/postmanlabs/postman-app-support/issues/3845

**Closed as completed by saswatds** 2020-02-12 02:32 UTC
Labels: product/runtime
