### ISSUE TITLE
Anchor # become null when postman editor changed to markdown editor

### ISSUE THREAD

**Issue by jonathankyong** [a85/POSTMan-Chrome-Extension#12195] opened 2023-07-28 02:55 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

the link of anchor to internal documentation (#label-heading) always converted to **null** whenever we change the editor type from postman editor to markdown editor.

### Steps To Reproduce

1. open View Documentation for the Request (or create a new Request or a Folder ).
2. create some Header 1, ex : Label Heading in that folder
3. create another new Folder or Request and edit the description
4. edit the description using postman editor (put value with #label-heading or in markdown editor use the anchor to the Label Heading with following command [Label Heading](#label-heading)
5. test it, it works,
6. but try to edit again, by default the editor is Postman editor, try to change to markdown editor, then it will be null.
So, i think this is a bug

### Screenshots or Videos

n.a

### Operating System

Mac OS

### Postman Version

WEB

### Postman Platform

Postman Web

### User Account Type

Signed In User

https://github.com/postmanlabs/postman-app-support/assets/21050919/e7acea4c-aec0-4635-9592-b956e34387b4

**Comment by ishan-ks** [comment] 2023-07-28 14:08
Hi @jonathankyong,

Thanks for reaching out.

If possible, could you please share a screen recording of this issue as we're unable to reproduce it?

**Comment by jonathankyong** [comment] 2023-07-31 03:09
> Hi @jonathankyong,
> 
> Thanks for reaching out.
> 
> If possible, could you please share a screen recording of this issue as we're unable to reproduce it?

Hi Ishan, thanks for the straightforward reply. I just attach the video in my first post,. Thanks ya... we wait for the support.

**Comment by ekansh-001** [comment] 2023-10-11 07:32
Hello @jonathankyong,

This issue is being fixed, I am not able to reproduce this on the latest release.
Request you to please check this once 🙇
Let us know in case you need any other help from our side.

**Comment by ekansh-001** [comment] 2023-10-30 06:59
Hello @jonathankyong ,

Since the issue has already been resolved, I am closing off the issue.
Please feel free to open up the other issue on the board if you face any other problem 🙇

**Closed as completed by ekansh-001** 2023-10-30 06:59 UTC
Labels: bug, product/documentation, collections
