### ISSUE TITLE
Content-Length calculation error when some key not selected in body

### ISSUE THREAD

**Issue by juewuer** [a85/POSTMan-Chrome-Extension#5492] opened 2018-11-07 09:22 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I use POST method, body select x-www-form-urlencoded, i make 3 key and values, and only select two, but Content-Length should be the two key length, but now it is three total, although the not selected not contained in the body filed

**To Reproduce**

**Expected behavior**
I use wireshark to capture the packet sent, and found that the post request have a tag: "TCP segment of reassembled PDU"

**Screenshots**

**App information (please complete the following information):**
 - App Type Postman for Windows
 - Postman Version 6.4.4
 - OS: win32 10.0.17134 / x64

**Additional context**

**Comment by vikiCoder** [comment] 2019-05-16 13:27
Hi @juewuer 

I am unable to reproduce this issue in the latest version(v7.1.0) of postman desktop app. I created local echo server and checked content-length header received in the server when only 2 of 3 x-www-form-urlencoded params are selected. Below is the screenshot of the same. 

<img width="1124" alt="Screenshot 2019-05-16 at 6 46 54 PM" src="https://user-images.githubusercontent.com/16588032/57857270-6622ad00-780c-11e9-8004-b7ce5ec8500b.png">

Can you please confirm whether this is still happening to you or not in the latest version of the app?

**Comment by codenirvana** [comment] 2019-05-16 16:54
Closing this issue as we can’t replicate this and we haven’t seen other users facing similar issues.

**Closed as completed by codenirvana** 2019-05-16 16:54 UTC
Labels: bug, request-sending, product/runtime
