### ISSUE TITLE
File type parameters don't save their values.

### ISSUE THREAD

**Issue by AliSepehri** [a85/POSTMan-Chrome-Extension#1629] opened 2015-12-28 06:04 UTC
The parameters with file type don't save their values and this cause problems in test `Runner`.

![post](https://cloud.githubusercontent.com/assets/7887290/12014606/c9c7239a-ad44-11e5-8321-a20c83aad689.png)

**Comment by abhijitkane** [comment] 2015-12-29 17:28
This is currently a restriction of the Chrome app platform. We cannot save references to files. We're working on a native app where we'll be able to overcome this.

**Comment by abhijitkane** [comment] 2015-12-29 17:29
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1113

**Closed as completed by abhijitkane** 2015-12-29 17:29 UTC
Labels: platform/chrome
