### ISSUE TITLE
Postman giving 400 Bad Request (syntax error) 7.28.0 version, it was working fine in previous version

### ISSUE THREAD

**Issue by MuraliKrishna4550** [a85/POSTMan-Chrome-Extension#8768] opened 2020-07-13 18:53 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by mccannt** [comment] 2020-07-13 23:04
@MuraliKrishna4550 You are going to have to give more information than this. 
Can you please give us more details? Console Logs would be helpful so we can get an idea of what may be happening.

**Comment by gintohewoo** [comment] 2020-07-14 21:12
I am having the same problem.

Any POST request to any service running on any port on localhost never hits the service.  It immediately errors out with a 400 Bad Request.  I have included as much information as is relevant to the problem, the same request made of a valid hostname elsewhere works without issue.

![image](https://user-images.githubusercontent.com/1831468/87476813-0339cb00-c5f5-11ea-899b-217aed6be498.png)

MacOS 10.15.5
Postman 7.28.0 (Native App)

I recently updated Postman on a reboot and ever since I have experienced this problem, I have no issues reaching valid hostnames, it is just when I attempt to hit localhost that it nearly immediately gives a 400 and I do not see the request hit the locally running service that is being developed.

**Comment by codenirvana** [comment] 2020-07-15 04:01
@gintohewoo The request does reach your locally running service that's why it's returning a 404 response.
Can you share what's the request URL like? or, share steps that we can use to reproduce this issue locally?

Did you disable the `Host` request header? I see it's missing from the attached console screenshot.

**Comment by gintohewoo** [comment] 2020-07-15 14:18
I am not sure how to disable the HOST request header.  

I believe the host is missing because this request is going to localhost.  I do see the host header entry when I hit the services running at a valid hostname, so perhaps this is the issue.

**Comment by codenirvana** [comment] 2020-07-16 03:01
@gintohewoo `Host` header is attached to every request sent unless it's disabled explicitly. Refer to the following screenshot and check if the `Host` field is disabled/unchecked.

![Screenshot 2020-07-16 at 8 27 36 AM](https://user-images.githubusercontent.com/4865836/87621520-9599b600-c73e-11ea-89d4-4deaa138f955.png)

**Comment by gintohewoo** [comment] 2020-07-16 13:19
Everything looks as it should on my end.

**Comment by gintohewoo** [comment] 2020-07-16 13:26
I have simply rolled back to an earlier version and things appear to be working now.  Thank you for your assistance but I had to get this deployed by end of week this week, sorry I could not be of more help.

**Comment by hostaur** [comment] 2020-07-16 21:48
![image](https://user-images.githubusercontent.com/44832881/87726207-8e999480-c78c-11ea-8a59-a2cedd721a76.png)

**Comment by hostaur** [comment] 2020-07-16 21:49
file -> settings 
https://github.com/postmanlabs/postman-app-support/issues/8154

**Comment by codenirvana** [comment] 2020-07-17 03:09
@hostaur Note that this setting is deprecated and will be removed in the future.

Can you share what's the issue you are facing and got the need of turning this OFF?

**Comment by codenirvana** [comment] 2020-07-21 12:06
Closing as per https://github.com/postmanlabs/postman-app-support/issues/8791#issuecomment-661813107

**Closed as completed by codenirvana** 2020-07-21 12:06 UTC
Labels: support, need-more-info

**Comment by mnxumalo** [comment] 2022-02-24 15:12
I'm facing the same issue in Version 9.14.0 after the update. Where can I get the previous version of postman?

**Comment by jitusinghdagar** [comment] 2022-05-03 18:21
![Screenshot (76)](https://user-images.githubusercontent.com/77379465/166517530-a2c19586-738c-4fbd-b639-2ab1338c1cb2.png)

**Comment by jitusinghdagar** [comment] 2022-05-03 18:21
where is the problem reply as sson as possible urgent

**Comment by aboli-chavan** [comment] 2023-06-07 15:21
Enable all headers. Then it works. 
![image](https://github.com/postmanlabs/postman-app-support/assets/57430055/c2d2238d-f956-49ed-a34f-454aca0fcfa3)
