### ISSUE TITLE
Authorization OAuth2.0 Type with grant type "Authorization Code" missing "resource" argument in /token POST

### ISSUE THREAD

**Issue by barrettlee** [a85/POSTMan-Chrome-Extension#4051] opened 2018-01-10 16:02 UTC
## App Details:
```
Postman for Windows
Version 5.5.0
win32 6.1.7601 / x64
```

#### 1. Did you encounter this recently, or has this bug always been there:
*Encountered recently but only recently tried the authorization OAuth2 feature*
#### 2. Expected behaviour:
*Receive bearer token from **Azure** using Auth code flow*
#### 3. Console logs 
POSTing to  `https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/token`
``` POST /xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/token
content-type: application/x-www-form-urlencoded
authorization: Basic <code>
user-agent: PostmanRuntime/7.1.1
accept: */*
host: login.microsoftonline.com
accept-encoding: gzip, deflate
content-length: 835
grant_type=authorization_codecode=AQABAAIA<Redacted>8SShqa-SAAredirect_uri=https://myserver.com/XYZclient_id=88888888-aaaa-aaaa-aaaa-888888888888
HTTP/1.1 400
status: 400
cache-control: no-cache, no-store
pragma: no-cache
content-type: application/json; charset=utf-8
expires: -1
server: Microsoft-IIS/8.5
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-ms-request-id: d23da98c-0faf-439d-b014-c97b98472801
p3p: CP="DSP CUR OTPi IND OTRi ONL FIN"
set-cookie: esctx=AQAB<Redacted>PcgAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly,x-ms-gateway-slice=007; path=/; secure; HttpOnly,stsservicecookie=ests; path=/; secure; HttpOnly
x-powered-by: ASP.NET
date: Wed, 10 Jan 2018 14:33:10 GMT
content-length: 404
{"error":"invalid_resource","error_description":"AADSTS50001: Resource identifier is not provided.\r\nTrace ID: d23da98c-0faf-439d-b014-c97b98472800\r\nCorrelation ID: 6bf33aa7-d45f-4e93-a3b4-93e3080e31d8\r\nTimestamp: 2018-01-10 14:33:11Z","error_codes":[50001],"timestamp":"2018-01-10 14:33:11Z","trace_id":"d23da98c-0faf-439d-b014-c97b98472800","correlation_id":"6bf33aa7-d45f-4e93-a3b4-93e3080e31d8"} 
```
#### 4. Actual result:
Authorization code was received from GET /oauth2/authorize request but POST /oauth2/token failed due to missing body parameter (Resource identifier)
I validated this with manual testing so I know my parameters are correct

#### 5. Steps to reproduce 
In the authorization tab, choose type OAuth 2.0
Click "Get New Access Token"
Choose Grant Type "Authorization Code"
Enter Callback URL, Auth URL, Access Token URL, and Client ID
**Note: State and Scope are optional.  Client Secret is not required in authorize code flow**
Click "Request Token"

#### Suggested fix
Add an optional entry field for Resource and pass in the POST /token request as a body parameter
ie resource=xxxxxxxxxxxxx
You should also pass the Resource key and value as a URL parameter in the GET /authorize request

**Comment by sivcan** [comment] 2018-01-11 12:24
Hi @barrettlee, 
Resource is not part of OAuth2 Spec. For more details refer the following : 
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/2523#issuecomment-331790634

**Closed as completed by sivcan** 2018-01-11 12:24 UTC
Labels: Auth

**Comment by barrettlee** [comment] 2018-01-11 13:56
Thanks. I will use the workaround mentioned in the other ticket.
You should consider adding custom fields for body parameters like this to add flexibility.
