### ISSUE TITLE
Optional Query Parameters are not being displayed in the docs

### ISSUE THREAD

**Issue by DLTKMonBlaza** [a85/POSTMan-Chrome-Extension#8707] opened 2020-06-24 11:14 UTC
**Describe the bug**
When adding optional query parameters (unchecked) from a list of query parameters, the unchecked (optional) query parameter only appears in the View in Web view but not in the published API documentation.

**To Reproduce**
1. Go to an existing endpoint.
2. Add optional and required query parameters.
3. Uncheck the box for the optional query parameter.
4. Publish the documentation. The resulting documentation would not display the optional query parameter as grayed out unlike when viewing in web (unpublished).

**Expected behavior**
The resulting documentation for the endpoint displays the optional query parameter as grayed out under Params along with the required query parameter.

**Screenshots**

**App information (please complete the following information):**
 - Chrome
 - Postman Version v7.27.0
 - OS: Windows 10 Enterprise 10.0.16299 Build 16299

**Additional context**
None.

**Comment by Raja-Simha** [comment] 2020-11-19 10:12
Duplicate of #7301

**Closed as completed by Raja-Simha** 2020-11-19 10:12 UTC
Labels: feature, product/documentation
