### ISSUE TITLE
Backspace deletes an item in the sidebar (collections, folders, requests) and this is not documented and preferable

### ISSUE THREAD

**Issue by vhrsh** [a85/POSTMan-Chrome-Extension#8718] opened 2020-06-29 11:54 UTC
**Is your feature request related to a problem? Please describe.**
I created a big collection with all my requisite requests and custom code. When trying to rename the collection (ctrl + e), i pressed backspace with the assumption that the name would be changed. However, it gave a prompt for the collection to be deleted. Due to the speed at which i use, i inadvertently pressed enter and lost it.

Now, i was able to come across the same thing and this is when i understand that Backspace was the culprit. This is not a documented shortcut for deleting something. I would suggest, the better option is to remove this issue.

**Describe the solution you'd like**
Remove Backspace button ability to delete a collection.

**Describe alternatives you've considered**
Delete Button is provided and working as advertised.

**Additional context**

**Comment by DannyDainton** [comment] 2020-06-30 08:44
Hey @vhrsh 

I'm unable to reproduce this delete action using a backspace while editing - Are you able to reproduce this every time? 

If you could get a recording of this happening it will help out in reproducing this on our side.

Could you also share the environment (App version, OS information) details, please?

**Comment by vhrsh** [comment] 2020-06-30 16:31
> Hey @vhrsh
> 
> I'm unable to reproduce this delete action using a backslash - Are you able to reproduce this every time?
> 
> If you could get a recording of this happening it will help out in reproducing this on our side.
> 
> Could you also share the environment (App version, OS information) details, please?

Hi Danny,
I am not sure if i can repeat it on demand. However, i feel one of the reason a refresh or something on the postman window due to which the module being clicked, needs to be activated again. But again, Backspace doing the work of the Delete button is not documented as well. So, either it is to be documented, or preferably, the action disabled.

I am on 7.27.1 and Windows 10.

**Comment by DannyDainton** [comment] 2020-06-30 16:44
It's something that I can't recreate on my Win 10 machine when editing the name of a Collection.

The only keyboard `Delete` action is when not in the edit mode, pressing delete key will show the Delete modal which needs a further user action to delete the collection.

The shortcut key can be seen on the `...` collection menu:

![Screenshot 2020-06-30 at 17 36 49](https://user-images.githubusercontent.com/17089546/86152747-8b4daa00-baf8-11ea-84ef-d967e06407df.png)

It's also listed in the keyboard shortcuts:

![Screenshot 2020-06-30 at 17 38 58](https://user-images.githubusercontent.com/17089546/86152902-c51eb080-baf8-11ea-8774-bf350f37815b.png)

In the event of accidental deletion the collection, depending on the size, is recoverable from the Trash - You can see that using `https://go.postman.co/me/trash`.

**Comment by vhrsh** [comment] 2020-06-30 16:57
> It's something that I can't recreate on my Win 10 machine when editing the name of a Collection.
> 
> The only keyboard `Delete` action is when not in the edit mode, pressing delete key will show the Delete modal which needs a further user action to delete the collection.
> 
> The shortcut key can be seen on the `...` collection menu:
> 
> ![Screenshot 2020-06-30 at 17 36 49](https://user-images.githubusercontent.com/17089546/86152747-8b4daa00-baf8-11ea-84ef-d967e06407df.png)
> 
> It's also listed in the keyboard shortcuts:
> 
> ![Screenshot 2020-06-30 at 17 38 58](https://user-images.githubusercontent.com/17089546/86152902-c51eb080-baf8-11ea-8774-bf350f37815b.png)
> 
> In the event of accidental deletion the collection, depending on the size, is recoverable from the Trash - You can see that using `https://go.postman.co/me/trash`.

Awesome. I am able to replicate the issue and it seems a bad one.. One moment.. Getting a video up for you..
Meantime, you can try this:
1. Select a collection
2. Press F2 to rename
3. pick some text towards the front of the collection name (when selecting this, the mouse has to be super precise, if it goes out even a bit, it goes to collection selection mode)
4. Press Backspace

I could do this right now before responding. I am trying to do it again but with very little luck

**Comment by vhrsh** [comment] 2020-06-30 17:00
The selection with the mouse and the swift nature of people using the backspace button to clear text is the problem. I am not sure if this will be looked at. It looks like a clear UX Issue. When i am selecting the text, if i go out of bounds, it does not register it

**Comment by vhrsh** [comment] 2020-06-30 17:01
Moreover, If you select the collection and press backspace, it should not do anything. The backspace is the not the intended shortcut for any postman action anyways.

**Comment by DannyDainton** [comment] 2022-04-29 16:53
I'm going to close this issue - I'm unable to reproduce it on the latest version. If the select is selected, the backspace is a shortcut to delete the element. This will always display a confirmation modal before anything is deleted.

**Closed as completed by DannyDainton** 2022-04-29 16:53 UTC
Labels: support
