### ISSUE TITLE
HTTP Redirect is not supported?

### ISSUE THREAD

**Issue by Wuaner** [a85/POSTMan-Chrome-Extension#2068] opened 2016-05-17 12:28 UTC
I am using the latest Postman for Chrome.

When I send a PUT request to a URI that update specific resource and return a redirect URL, the response that I got was always 

> 405 Request method 'PUT' not supported

rather than the redirected page that I expected.

Is I do something wrong, or HTTP Redirect is not supported by Postman?

Thanks for this awesome tool.
Bests.

**Comment by abhijitkane** [comment] 2016-05-17 15:26
@Wuaner 

```
This is now possible with version 0.2.9 of the Interceptor and version 1.0.11 of the Postman Packaged app.

Interceptor - https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en

You need to enable the Interceptor in Postman, go to the Settings modal and disable automatic redirection.
```

Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/319

**Closed as completed by abhijitkane** 2016-05-17 15:26 UTC

**Comment by Wuaner** [comment] 2016-05-17 15:44
Hi, @abhijitkane,

Thanks for prompt response.

I already install Interceptor you mentioned. 
After I disable "Automatically follow redirects" on Settings, the page that I redirected to was not show up, But HTTP code became `302 Found`(although `Request method 'PUT' not supported` is still show up on my server log). 
Is this the right behavior?

Bests.
