### ISSUE TITLE
Collection runner goes black after selecting Collection

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7053] opened 2019-08-03 00:31 UTC
**Describe the bug**
After selecting a Collection, the Runner window goes black, and stays that way even after closing it and opening a new Runner window.

**To Reproduce**
(note: support not able to reproduce. maybe be specific to this user/team/etc)
1. Open Collection Runner window
2. Select Collection
3. See Runner window turn solid black
4. Close window and re-open
5. See same behavior

**Screenshots**
See internal notes

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.3.5
 - OS: MacOS High Sierra version 10.13.6

**Additional context**
See internal notes for logs

**Comment by xk0der** [comment] 2019-08-19 23:31
Another user has reported a similar issue. The internal ticket has been linked with this GitHub issue.
Logs are available as well.

*This is one of the errors I saw in the logs:*
```[785][1542331716101][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"Error","message":"Object has been destroyed","stack":"Error: Object has been destroyed\n    at WebContents.send (/Applications/Postman.app/Contents/Resources/electron.asar/browser/api/web-contents.js:97:15)\n    at done (/Applications/Postman.app/Contents/Resources/app/services/RuntimeBridge.js:315:16)\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/backpack/index.js:56:34\n    at PostmanCollectionRun.<anonymous> (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/runner/run.js:166:26)\n    at ontimeout (timers.js:469:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:264:5)"}]```

*Screenshot:*
![Screen Shot 2019-08-16 at 2 35 31 PM](https://user-images.githubusercontent.com/21366/63306231-dfff9080-c33d-11e9-8a88-b32695caf7ce.png)

*Setup Details:*
* MacBook Pro
* Mojave 10.14.1
* Postman 7.5.0

**Comment by saswatds** [comment] 2019-10-03 10:45
Closing this issue as it's a duplicate of #4128. I will be using the said issue as the master issue for the black-screen/memory problem in Collection Runner

**Closed as completed by saswatds** 2019-10-03 10:45 UTC
Labels: bug, product/runtime
