### ISSUE TITLE
Add support for defining proxy information per collection

### ISSUE THREAD

**Issue by frank-adler** [a85/POSTMan-Chrome-Extension#7030] opened 2019-07-31 15:20 UTC
Some of our test stages are available through a proxy only. This proxy requires authentication.

It would be nice if the proxy can be configured per collection, as there are many services we do not need a proxy.

**Comment by codenirvana** [comment] 2019-08-10 16:36
Duplicate of #4739

**Closed as completed by codenirvana** 2019-08-10 16:36 UTC
Labels: feature, product/runtime
