### ISSUE TITLE
Table cell in Query Params is editable when not in focus

### ISSUE THREAD

**Issue by pankajk07** [a85/POSTMan-Chrome-Extension#8264] opened 2020-03-31 16:11 UTC
**Describe the bug**
The table cell in Query params is editable even when the cell is not focused. This is reproducible only when some of the rows are selected in the in query params section.

**To Reproduce**

1.  Select a few rows in Query Params section by click and drag functionality
2. Click on any of the cell from the rows selected in Step 1
3. Notice the cell is not focused but is editable.

**Expected behavior**
The selected cell should be focused and editable when clicked.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Version 7.21.1 (7.21.1)
 - OS: macOS Catalina 10.15.3]

**Comment by vvs11** [comment] 2020-11-24 10:34
@pankajk07 Since this is not reproducible anymore, closing this issue

**Closed as completed by vvs11** 2020-11-24 10:34 UTC
Labels: bug, product/runtime
