### ISSUE TITLE
[Feature Request] Link with editor

### ISSUE THREAD

**Issue by yeikel** [a85/POSTMan-Chrome-Extension#6315] opened 2019-04-17 15:03 UTC
**Is your feature request related to a problem? Please describe.**
In Eclipse and similar IDEs , we have a feature called "link with editor"[1] that navigates to the current source file selected. I would like to have this feature in Postman. 

[1] https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-18.htm

**Describe the solution you'd like**
We should have a button next to "New Collections" called "Link with editor" that navigates to the active request.

**Comment by numaanashraf** [comment] 2019-04-17 19:31
Related to #6303

**Comment by yeikel** [comment] 2019-04-18 01:09
Unless I am missing something it seems to be the same suggestion. Feel free to close it

**Comment by a85** [comment] 2019-12-01 07:29
Closing as duplicate of #6303

**Closed as completed by a85** 2019-12-01 07:29 UTC
Labels: feature, user-interface
