### ISSUE TITLE
"Close Other Tabs" option not responding

### ISSUE THREAD

**Issue by michael-schantin** [a85/POSTMan-Chrome-Extension#11247] opened 2022-09-07 12:42 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Similar to issue 11123 which was closed as done I still encounter the same problem. Sometimes after executing a query, the option _Close Other Tabs_ no longer works. Restarting Postman fixes this.

### Steps To Reproduce

Open multiple requests
Right click on tab
Click on "Close Other Tabs"
Nothing happens.

### Operating System

macOS

### Postman Version

9.30.4

### Postman Platform

Postman App

**Comment by DannyDainton** [comment] 2022-09-09 13:52
Hey @michael-schantin 

Is this still an issue for you? Not sure which option you mean by `Close Other Tabs`. 

Can you share a short video of the behaviour you're seeing, please?

**Comment by michael-schantin** [comment] 2022-09-14 05:11
The issue persists. How to reproduce:

- Right-click a request tab
- Choose **Close Other Tabs**

<img width="427" alt="CloseOtherTabs" src="https://user-images.githubusercontent.com/34416401/190064729-53fab03d-2bcf-4ec2-9b92-0d300f567666.png">

**Comment by DannyDainton** [comment] 2022-10-18 10:35
Hey @michael-schantin 

I've been unable to reproduce this on the latest version of the app.

![Close_Tabs](https://user-images.githubusercontent.com/17089546/196407447-52e62555-e239-417b-826c-86200868ad92.gif)

Could you try selecting this option and trying again, please?

<img width="470" alt="image" src="https://user-images.githubusercontent.com/17089546/196407731-4e7ebdfe-b2e1-47e1-8a06-788749e04122.png">

**Comment by DannyDainton** [comment] 2022-10-24 15:58
Closing this as we've been unable to replicate the behaviour in the latest version.

If you can send a short video showing the behaviour that you're seeing, we can look at reopening it again.

**Closed as completed by DannyDainton** 2022-10-24 15:58 UTC
Labels: tabs, need-more-info, product/runtime
