### ISSUE TITLE
Client certificate issue with certificate signed by an intermediary CA

### ISSUE THREAD

**Issue by EasyMilos** [a85/POSTMan-Chrome-Extension#4627] opened 2018-05-31 12:51 UTC
**Describe the bug**
When using valid client certificate (provided as chained PEM certificate and private key in settings for domain under test) issued by valid intermediate root CA (present in supplied bundled CRT certificate and in both root CA stores) to access SSL endpoint protected by SSL and client certificate authentication, error "UNABLE_TO_VERIFY_LEAF_SIGNATURE" is received instead of expected HTTP response.

**To Reproduce**
1. Prepare all certificates: "Root CA", "Intermediate Root CA" issued by "Root CA", client certificate issued by "Intermediate Root CA", web site's SSL certificate
2. Ensure all certificates are valid and without errors, added to all appropriate certificate stores (on both client and server in certificate stores where needed) and that web site under test is secured with valid SSL certificate and with mandatory Client Certificate authentication and that requests to the endpoint under test from Chrome and Firefox browsers can go without any issues (that all certificates are accepted without exceptions and errors).
2. Open Postman 6.1.3 for Windows
3. Set bundled (client + issuing CA + issuer's parent root CA) client certificate (PEM format) and private key in "Settings > Certificates"  for the web site (endpoint) under test.
4. Make request to the web site under test
5. Error "UNABLE_TO_VERIFY_LEAF_SIGNATURE" is seen in Postman Console and no HTTP connection is established.

**Expected behavior**
Request to the web site under test goes through and expected response is received (meaning TLS handshake was successful and HTTP connection was established regardless of the server's HTTP response).

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.1.3
 - Windows 10 Professional (with all current updates installed)

**Additional context**
Site under test was using self signed SSL for "localhost" certificate auto generated by Visual Studio (IIS Express) which was present in Computer's Personal and User's Trusted Root CA certificates store. Postman was able to receive answers without any problems from the same SSL secured endpoint when client certificate authentication was not turned on.

When option in settings "SSL certificate verification" is turned off, requests (with client certificate authentication that is verified on the server) goes through fine, but that is due to the fact that any "validation" is turned off. The root cause for this issue probably can not be the same as other currently opened issues related to client certificate authentication problems (like #2874,  #3251, #3290).

Issuing the same request from Chrome and Firefox browser (with configuring client certificate in Firefox and adding localhost SSL certificate in Trusted Publishers) works as expected and without any issue.

All requests were tested with all proxies turned off (in both browsers and Postman) and with using default system configured proxy (which technically in this case would be none) and results were the same.

All certificates (client and all chained parent CAs and web site) are inspected through MMC (in all required stores), as the ones supplied to Postman and appears as valid and not marked with any issues.

This issue in particular seems to be related to the fact that client certificate is issued by intermediary root CA (root CA issued by another root CA) and that Postman (or underlining engine) for whatever reason does not properly resolves/validates CA chain (even though CA chain is properly supplied in bundled client certificate and is valid and in all relevant secure stores). Root cause might be the same as described here https://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature/48563954#48563954

**Comment by harryi3t** [comment] 2018-06-29 10:49
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3290

**Closed as completed by harryi3t** 2018-06-29 10:49 UTC
Labels: bug

**Comment by EasyMilos** [comment] 2018-06-29 13:29
Not sure if this is relevant to this particular issue or not, but it is found that CRL was not configured properly for the "Intermediate Root CA", and Powershell's Test-Certificate cmdlet was giving warning CERT_TRUST_REVOCATION_UNKNOWN for it, even though all other applications accepted it as valid. Given this new finding, it might not be "duplicate" of the the "UNABLE_TO_GET_ISSUER_CERT_LOCALLY" issue as in the case #3290, where CA cert was definitely not present in appropriate stores or chained in the initial certificate properly (thus couldn't be verified by postman).

**Comment by EasyMilos** [comment] 2018-07-02 08:50
Strangely, this does not happen for anything, but "localhost" (similar to #4726), but this happens only with client certificate. Tested with the same kind of CA certificates that were not hitting "localhost" website was properly working from postman with "SSL certificate verification" turned on.

**Comment by harryi3t** [comment] 2018-07-02 10:03
@EasyMilos Can you try with 127.0.0.1 instead of localhost?

**Comment by EasyMilos** [comment] 2018-07-02 10:44
Not really, because SSL certificate is tied to name, not IP.
