### ISSUE TITLE
Impossible to select the TEXT while renaming

### ISSUE THREAD

**Issue by nikitasius** [a85/POSTMan-Chrome-Extension#5218] opened 2018-09-20 14:45 UTC
**Describe the bug**
You cannot select text while renaming records (details in short video)

**To Reproduce**
Select a record, click `rename`, try to select the text, you can't.

**Expected behavior**
Allow to select the text with mouse :rofl: 

**Screenshots**
* Video: [Screencast 2018-09-20 16:41:53.mp4.zip](https://github.com/postmanlabs/postman-app-support/files/2401764/Screencast.2018-09-20.16.41.53.mp4.zip)

**App information (please complete the following information):**
 - native app
 - Postman v6.3.0
 - OS: Linux pentagon 4.9.0-0.bpo.5-amd64 #1 SMP Debian 4.9.65-3+deb9u2~bpo8+1 (2017-01-05) x86_64 GNU/Linux

**Comment by numaanashraf** [comment] 2019-04-04 14:09
Duplicate of #2940

**Closed as completed by numaanashraf** 2019-04-04 14:09 UTC
Labels: bug, user-interface
