### ISSUE TITLE
Need to have different amount of delay between two requests in a collection 

### ISSUE THREAD

**Issue by sarfaraz49** [a85/POSTMan-Chrome-Extension#1401] opened 2015-09-02 09:59 UTC
Right now we have a common delay option in the collection runner. We can not have different amount of delay if there are more than two requests in the collection. It would be useful if there is an option to have different amount of delays between two requests in a collection.

**Comment by shamasis** [comment] 2016-12-27 22:52
duplicate of https://github.com/postmanlabs/postman-app-support/issues/1038

**Closed as completed** 2016-12-27 22:52 UTC
Labels: feature, collection-runner
