### ISSUE TITLE
connection error and console with "pm.syncManager.forceConnect is not a function"

### ISSUE THREAD

**Issue by vollyimnetz** [a85/POSTMan-Chrome-Extension#9516] opened 2021-02-01 14:19 UTC
**Describe the Issue**

After upgrading to Postman 8 (Windows App) i had several problems. My old collections were lost (could only recover them cause i found that _%AppData%\Roaming\Postman_ had serveral backup files of the data from before the upgrade). 

Since then, Postman shows the "Connection Error" icon. The "Retry connection" seems to have no effect.

When i try to open an saved request, the tab where the Request normally renders, stays empty. If i click on the "+" for new Request all worked as expected.

Saved collections and requests are synced from web to the local installation but not the other way.

I tried reinstall severall times, also with deleting all data from %appdata%/roaming and %appdata%/local.

When i open the Developer Console i see the following error are logged, once i try to click "Retry connection".
```
Uncaught TypeError: pm.syncManager.forceConnect is not a function
    at SyncStatusContainer.handleForceConnect (requester.js:60889)
    at Button.handleClick (vendor-shared.js:416717)
    at Object.ba (vendor-shared.js:196)
    at ja (vendor-shared.js:196)
    at ka (vendor-shared.js:196)
    at oa (vendor-shared.js:197)
    at lc (vendor-shared.js:234)
    at jc (vendor-shared.js:233)
    at mc (vendor-shared.js:234)
    at sc (vendor-shared.js:238)
    at Ia (vendor-shared.js:469)
    at Ma (vendor-shared.js:201)
    at Rc (vendor-shared.js:252)
    at id (vendor-shared.js:251)
    at push.exports.unstable_runWithPriority (vendor-shared.js:512)
    at cg (vendor-shared.js:304)
    at Ga (vendor-shared.js:469)
    at gd (vendor-shared.js:250)
    at HTMLDocument.sentryWrapped (vendor-shared.js:906427)
handleForceConnect @ requester.js:60889
handleClick @ vendor-shared.js:416717
ba @ vendor-shared.js:196
ja @ vendor-shared.js:196
ka @ vendor-shared.js:196
oa @ vendor-shared.js:197
lc @ vendor-shared.js:234
jc @ vendor-shared.js:233
mc @ vendor-shared.js:234
sc @ vendor-shared.js:238
Ia @ vendor-shared.js:469
Ma @ vendor-shared.js:201
Rc @ vendor-shared.js:252
id @ vendor-shared.js:251
push.exports.unstable_runWithPriority @ vendor-shared.js:512
cg @ vendor-shared.js:304
Ga @ vendor-shared.js:469
gd @ vendor-shared.js:250
sentryWrapped @ vendor-shared.js:906427
```

**Environment Information**

 - Native Desktop App (i think ... its the electron based one)
 - Postman Version: 8.0.3
 - Operating System: Windows Home 64

**Comment by DannyDainton** [comment] 2021-02-01 14:22
Please send all of the log files to help@postman.com. 

It will help us to investigate the root cause of the problem. 

You can find the logs at `View -> Developer -> View logs in Finder/Explorer.`

Similar issues have been raised on the repository and to try and keep the flow of information in a central place, I'm going to close this issue and kindly ask that you follow the thread, on the issue below, for more information. 

https://github.com/postmanlabs/postman-app-support/issues/9481

**Closed as completed by DannyDainton** 2021-02-01 14:22 UTC
Labels: duplicate
