### ISSUE TITLE
No way to go back to workspace view from documentation

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#6375] opened 2019-04-27 05:23 UTC
**Describe the bug**
On dashboard, if a user wants to go back to the workspace view `/workspaces/:id` from collection documentation (/collections/:id), they have to open the workspace switcher and find the active workspace. There is no back to workspace button.

**Expected behavior**
Have some way to go back to workspace view.

**Comment by DannyDainton** [comment] 2022-07-12 11:14
Hey @akshay-kulkarni-03 

Are we able to close this out now?

**Comment by akshay-kulkarni-03** [comment] 2022-07-14 07:44
@ankit-m thanks for reporting this! I was unable to reproduce this. I tried the below steps:

- Opened the workspace overview
- Clicked on a collection which also opened documentation for the collection
- Clicked on back browser button and I went back to the workspace overview page.

Can you let us know if you're still facing the issue? If yes, what are the steps you tried so we can try to reproduce it at our end.

**Comment by akshay-kulkarni-03** [comment] 2022-09-22 08:16
@ankit-m closing this issue since we haven't heard back from you! Feel free to re-open if issue persists.

**Closed as completed by akshay-kulkarni-03** 2022-09-22 08:16 UTC
Labels: bug, product/collaboration, workspaces
