### ISSUE TITLE
Cursor flickering and jumping for auto generated headers key & value

### ISSUE THREAD

**Issue by jainsamyak** [a85/POSTMan-Chrome-Extension#9275] opened 2020-11-16 08:08 UTC
**Describe the bug**
When you have an auto-generated header in the "headers" tab, and you try to click through the key or value, the cursor starts jumping and rotating in a loop at the points you click  from there on. It doesn't stop until you manually switch to another tab or quit the app.
Introduced in most recent version 7.35.0.

**To Reproduce**
1. Go to 'Headers' tab in a request
2. Click on any value for an auto-generated header, and then try and click somewhere else.
3. Notice the cursor starts jumping through a loop at every point you click.

**Screenshots**
![image](https://user-images.githubusercontent.com/33225811/99226564-fbdb3600-280f-11eb-8298-fb6fc5b653f9.png)
![PostmanJump](https://user-images.githubusercontent.com/33225811/99227241-f8947a00-2810-11eb-887e-0ea0ec810488.gif)

**App information (please complete the following information):**
 - App Type: Windows Native
 - Postman Version 7.35.0
 - OS: Windows 10 (20H2)

**Comment by DannyDainton** [comment] 2020-11-16 08:28
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9251

**Closed as completed** 2020-11-16 08:29 UTC
Labels: user-interface, duplicate, product/runtime
