### ISSUE TITLE
why just the last blank can be null?

### ISSUE THREAD

**Issue by tester1234562020** [a85/POSTMan-Chrome-Extension#6220] opened 2019-04-03 08:17 UTC
![image](https://user-images.githubusercontent.com/44419851/55463534-dcd46400-562b-11e9-801c-e8433511ea6f.png)
[data-.txt](https://github.com/postmanlabs/postman-app-support/files/3037551/data-.txt)

**Comment by WendallHersh** [comment] 2019-04-03 12:40
https://community.getpostman.com/t/hello-how-to-write-null-in-csv-for-used-in-postmans-tests/4805

There are a few workaround posted in the above linked community post.

**Comment by shamasis** [comment] 2019-04-03 19:17
Close duplicate of two issues. Keeping reference and tracking in original issue:
https://github.com/postmanlabs/postman-app-support/issues/3427 
https://github.com/postmanlabs/postman-app-support/issues/6203

**Closed as completed** 2019-04-03 19:17 UTC
Labels: bug, duplicate, product/runtime
