### ISSUE TITLE
Multiple Selection and Movement of Http Requests within a Folder in a Collection

### ISSUE THREAD

**Issue by rakshitjain25** [a85/POSTMan-Chrome-Extension#9019] opened 2020-09-03 04:59 UTC
Problem Statement : Need to Move Http Requets to a new Folder from Multiple Existing Folders within a Collection.

For example, I have a Collection named C1 having 3 Folders named F1,F2 and F3. With Each folder having 5 Http requests each..

Now, I have a requirement to collate the selected Http Requests into a New Folder named F4 within C1. Lets 2 requests from F1,3 Requests from F2 and 1 Request from F3.

Currently, We need to copy from one folder and paste into another which seems to be tedious task when there is a need to move multiple requests from one folder to another.

So, can we have a feature wherein a user a select multiple http requests from a folder and Copy or move(by dragging) to Destination folder within same collection.

Thanks
Rakshit Jain
Contact No : +91-8588918484
Email Address : jain.raksh25@gmail.com

**Comment by DannyDainton** [comment] 2020-09-03 05:45
Closing this as it's a duplicate of #1066

**Closed as completed** 2020-09-03 05:46 UTC
Labels: user-interface, duplicate, product/runtime
