### ISSUE TITLE
Not open on Mac 10.13.6

### ISSUE THREAD

**Issue by jmajr** [a85/POSTMan-Chrome-Extension#6357] opened 2019-04-24 18:08 UTC
The app don't open

Process:               Postman [674]
Path:                  /Applications/Postman.app/Contents/MacOS/Postman
Identifier:            com.postmanlabs.mac
Version:               7.0.9 (7.0.9)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Postman [674]
User ID:               503

Date/Time:             2019-04-24 14:57:22.430 -0300
OS Version:            Mac OS X 10.13.6 (17G6030)
Report Version:        12
Anonymous UUID:        E37F4759-3134-0FC9-ADA5-B100E30CC475

Time Awake Since Boot: 710 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Postman.app/Contents/MacOS/Postman
  Reason: no suitable image found.  Did find:
	/Applications/Postman.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/Postman.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10c317000 -        0x10c317ff7 +com.postmanlabs.mac (7.0.9 - 7.0.9) <897843B4-87CB-378B-91BA-E535C0BF6F5E> /Applications/Postman.app/Contents/MacOS/Postman
       0x119f1f000 -        0x119f69acf  dyld (551.5) <30B355CB-35BA-3112-AA76-4E46CD45F699> /usr/lib/dyld

Model: iMac11,1, BootROM 61.0.0.0.0, 4 processors, Intel Core i7, 2,8 GHz, 12 GB, SMC 1.54f36
Graphics: ATI Radeon HD 4850, ATI Radeon HD 4850, PCIe
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353637334648302D4346382020
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353637334648302D4346382020
Memory Module: BANK 0/DIMM1, 4 GB, DDR3, 1067 MHz, 0x0000, -
Memory Module: BANK 1/DIMM1, 4 GB, DDR3, 1067 MHz, 0x0000, 0x202020202020202020202020202020202020
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x8F), Atheros 9280: 4.0.74.0-P2P
Bluetooth: Version 6.0.7f12, 3 services, 18 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: ST31000528ASQ, 1 TB
Serial ATA Device: OPTIARC DVD RW AD-5680H
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Expansion
USB Device: 2.4G Keyboard Mouse
USB Device: Internal Memory Card Reader
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB Keyboard
USB Device: IR Receiver
USB Device: Built-in iSight
Thunderbolt Bus:

**Comment by ankurdengla** [comment] 2019-04-25 10:55
@jmajr Did you get Postman 7.0.9 by updating an older version of the app or did you download the archive from the website? 
Also, if you downloaded the archive, this problem could have been caused because of using a third party app to unzip the file.
I suggest using the default mac Archive Utility to unzip the archive and reinstall the app. Do let us know if the problem still persists.

**Comment by jmajr** [comment] 2019-04-25 12:42
Hi @ankurdengla1996 

It worked. It really was what it said, I used the Archive Utility and it worked normally.

Thank you.

**Comment by numaanashraf** [comment] 2019-04-29 09:52
@jmajr Glad to hear the issue is resolved. Closing this.

**Closed as completed by numaanashraf** 2019-04-29 09:52 UTC

**Comment by JP-from-Postman** [comment] 2019-05-24 23:35
@numaanashraf Another report of this, user attempted using Archive Utility and others and was unsuccessful. Can you assist? Internal notes added.

**Comment by satishsoni777** [comment] 2020-12-24 18:37
Hi, for me its not working. my postman keep on crashing, can please some help me.?
@ankurdengla
