### ISSUE TITLE
Bug: Data binding for null values not working using Collection Runner

### ISSUE THREAD

**Issue by liam-hitchcock-dev** [a85/POSTMan-Chrome-Extension#4277] opened 2018-03-05 07:03 UTC
I am having some trouble using the collection runner as I currently am doing some csv data binding to a collection that I have.

I sometimes need to pass null as a value into the request but when I look at the collection runner results the request body serializes the null as '{{value}}' instead of 'null'. In the csv its just an empty string.

I have run the collection using Newman and it works fine using that so I am wondering whether its a collection runner issue.

Could you please assist me and let me know if this is a bug or a feature?

Thanks,

## App Details:
```
Postman for Windows
Version 6.0.8
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: I have encountered this recently while running collection runner and Newman for the same collection
 2. Expected behaviour: Collection runner should serialize empty csv string as null - however its currently serializing it as {{value}} instead (whereas if I run the same collection in Newman with data binding then the empty csv gets serialized correctly as null.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Dont have any...
 4. Screenshots (if applicable)
![csv entries](https://user-images.githubusercontent.com/33255357/36961244-173b5244-2053-11e8-82fa-8e558cedf9da.png)
![postman preview of csv showing null](https://user-images.githubusercontent.com/33255357/36961247-17991636-2053-11e8-82cd-cff640231a61.png)
![error_request body property not showing as null](https://user-images.githubusercontent.com/33255357/36961249-17d784a2-2053-11e8-8153-32d34aebb31b.png)

**Steps to reproduce:**
1) create csv with null entries 
2) reference property in postman request eg: `"propertyName": "{{ref_value}} "`
3) open collection runner and add csv data file choose collection and run
4) null entry not serialized to null in the collection runner request body

**Comment by harryi3t** [comment] 2018-03-06 11:36
@hitcl08 Thanks for reporting this issue.

> Could you please assist me and let me know if this is a bug or a feature?

😀 It's a bug

We are looking into this. I will update the thread once the fix is released.

**Comment by sivcan** [comment] 2018-08-01 10:00
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/2861

**Closed as completed by sivcan** 2018-08-01 10:00 UTC
Labels: bug

**Comment by sibande** [comment] 2018-09-13 06:30
Hello @sivcan, I'm having this problem and was trying to find the duplicate issue, but your comment is self-referencing this issue.

**Comment by sivcan** [comment] 2018-09-14 11:12
Hey, @sibande thanks for pointing out. I've updated the comment with the correct issue ticket.
