### ISSUE TITLE
[Feature] let user change shortcut keys

### ISSUE THREAD

**Issue by lukasoppermann** [a85/POSTMan-Chrome-Extension#2055] opened 2016-05-10 09:31 UTC
Hey, 

I think it would be very helpful if a user could change the keys for shortcuts, as some people might use other features more often than others. 

If you would make the keys customisable in the **Settings > Shortcut** it would be a huge improvement.

**Comment by a85** [comment] 2017-05-13 02:50
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/2096

**Closed as completed by a85** 2017-05-13 02:50 UTC
Labels: feature
