### ISSUE TITLE
Azure DevOps Git integration

### ISSUE THREAD

**Issue by R-Lamberson** [a85/POSTMan-Chrome-Extension#9302] opened 2020-11-20 22:21 UTC
**Describe your current workflow**
Currently we used Postman collections stored in our git repositories in Azure DevOps.  Requires manual syncing of files to local file system and then importing and exporting the postman collections into the tool.   Very inefficient and leads to errors across the team (dev, qa, ops)

**Describe your ideal workflow**
Direct integration with Azure DevOps git repositories.   Including the ability to target multiple specific paths for locations of postman files

Example file structure
Project 1
- App
- Test
-- Postman Collection.json
Project 2
- App
- Test
-- Postman Collection2.json
Project 3
- etc...

**Comment by Jmuddiman666** [comment] 2020-12-15 14:51
Is there an ETA for when this might get integrated?

**Comment by jotsarup** [comment] 2020-12-16 09:07
@Jmuddiman666 We are planning to support Azure Repos soon. Will let you know as soon as we have concrete deadlines.

**Comment by abhijitkane** [comment] 2021-07-13 06:08
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9131

**Closed as completed** 2021-07-13 06:08 UTC
Labels: feature, product/integrations
