### ISSUE TITLE
Feature Request - Please allow sub-folders within folders

### ISSUE THREAD

**Issue by jmihalich** [a85/POSTMan-Chrome-Extension#1522] opened 2015-10-22 15:38 UTC
I have a ton of rest requests that i have created.  it is nice to have the collection, and then folders underneath the collection.  But i really need support for folders within folders to be able to keep all my stuff organized and clean.

My current typical layout looks like this:

Application1 (Collection)
==>Prod (Folder)
======>request1 (Rest Request)
======>request2 (Rest Request)
      ...
===>QA (Folder)
======>request1 (Rest Request)
======>request2 (Rest Request)
      ...

What i really need is this:

Application1 (Collection)
===>Prod (Folder)
======>service1 (Folder)
=========>test1 (Folder)
============>request1 (Rest Request)
============>request2 (Rest Request)
======>service2 (Folder)
===========>test1 (Folder)
==============>request1 (Rest Request)
...

Thanks,
Joe

**Comment by felipeplets** [comment] 2015-10-22 16:10
Doesn't environment variables solve your problem? I manage the different
environments for prod/test/dev using it.

**Comment by a85** [comment] 2015-10-22 16:11
Agree with @felipeplets. Environments are built for this exact purpose - letting you switch between prod/qa etc without having to duplicate requests.

**Comment by PetrusKiendys** [comment] 2016-11-15 17:10
While "Environments" solve the case for various deployment envs it doesn't help when you want to organize your requests in a fine-grained manner.
I have requests that currently squeeze in under `Operations > Various > [request]` when I really want something more like `Operations > Various > [network] > [node] > ([stack]) > [application] > [API section]`

This is supposed to be implemented according to: http://blog.getpostman.com/2015/06/05/travelogue-of-postman-collection-format-v2/
Any status update on this? Is it possible to have multi-level folders in the native app?

**Comment by withoutclass** [comment] 2017-03-08 16:27
Agree with @PetrusKiendys.  Say I have 2 collections with sub folders already, but I want to merge these two collections into a single collection while keeping them separated in their own sub folder.  This is currently impossible but would be a great feature.

**Comment by mmckillion-r7** [comment] 2017-03-09 14:42
I would also like to bump this I posted on twitter also. I currently test my API in folders via newman with a structure like this:

-API Tests (Collection)
---Feature One (Folder)
---Feature Two (Folder)
---Feature Three (Folder)

However there are alot of tests in each folder that are dependant on each other some with 40+ requests. I would like to be able to have folders like this:

-API Tests (Collection)
---Feature One (Folder)
------Feature One Create (Sub-Folder)
------Feature One Read (Sub-Folder)
------Feature One Update (Sub-Folder)
------Feature One Delete (Sub-Folder)
---Feature Two (Folder)
------Feature Two Read (Sub-Folder)
------Feature Two Update (Sub-Folder)
------Feature Two Delete (Sub-Folder)
---Feature Three (Folder)
------Feature Three Create (Sub-Folder)
------Feature Three Read (Sub-Folder)
------Feature Three Update (Sub-Folder)
------Feature Three Delete (Sub-Folder)

I use newman in my jenkins environment and need the tests all to be in the same collection and currently it looks a bit messy!

I love the application and the company I work for are in talks about enterprise edition, I already bought pro for myself!

**Comment by sdnts** [comment] 2017-03-17 13:18
Guys, this is being actively worked upon! While I don't have an exact ETA right now, this will hit production very soon :D

**Comment by jonaslundholm** [comment] 2017-05-24 10:25
What's the status on this? Would be really neat to group requests that are supposed to succeed / fail and even group by expected status codes.

**Comment by a85** [comment] 2017-06-27 23:12
This is available in Postman Canary. Coming soon to production apps. Closing this as duplicate of #907

**Closed as completed by a85** 2017-06-27 23:12 UTC
Labels: feature
