### ISSUE TITLE
Undefined=undefined in code generated request body

### ISSUE THREAD

**Issue by thamerla** [a85/POSTMan-Chrome-Extension#5809] opened 2019-01-23 01:32 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Postman adds undefined=undefined to request body.

**To Reproduce**
1. Create a new request
2. Choose POST
3. Set url
4. Set body parameters with urlencoded key=value
5. See code. It throws random undefined=undefined for no reason.

**Expected behavior**
Seeing query parameters.

**Screenshots**

**App information (please complete the following information):**
 - App Type Simple request
 - Postman Version newest
 - OS: Windows

**Additional context**
Built-ins work without any problem.

**Comment by thamerla** [comment] 2019-01-23 01:34
Also would like to point out that editing existing body parameters causes the same problem.

**Comment by thamerla** [comment] 2019-01-29 14:58
@sujayvenaik any chance to fix it?

**Comment by chucklu** [comment] 2019-02-22 07:49
Encounter the same problem
```
POST /WayBill_GetDetail HTTP/1.1
Host: hdgateway.zto.com
Content-Type: application/x-www-form-urlencoded
cache-control: no-cache
Postman-Token: f6ffc331-fcae-484f-bf5f-3006e4fb9692
billCode=542430453744undefined=undefined
```

**Comment by kerednai** [comment] 2019-03-05 20:14
I get the same issue on 7.0.4 as reported in #5921 

curl -X POST \
  https://1.1.1.1:8443/v1/auth/identitytoken \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Postman-Token: ac1c6d06-3dae-4d62-b1db-7dbc7f94b95c' \
  -H 'cache-control: no-cache' \
  -H 'charset: UTF-8' \
  -d 'grant_type=password&username=admin&password123=password&scope=openid&undefined='

**Comment by sujayvenaik** [comment] 2019-03-12 08:48
Hey @kerednai @chucklu @nonyy 
We have identified the cause for this and are testing it internally. Would be coming out soon.

**Comment by ghost** [comment] 2019-03-13 01:19
h7lost

**Comment by chucklu** [comment] 2019-03-13 06:53
@sujayvenaik  Thanks

**Comment by tbolon** [comment] 2019-04-15 15:20
Please also note that if you submit multiple parameters, the "&" separator is not included between name-value pairs in the "HTTP" format.

**Comment by VShingala** [comment] 2019-04-29 08:03
Hey @kerednai @chucklu @nonyy @tbolon

I followed same steps to reproduce issue. And here's what I got on HTTP and cURL. Can you confirm if problem still exists or not?

In HTTP:
```
POST /post HTTP/1.1
Host: postman-echo.com
Content-Type: application/x-www-form-urlencoded
User-Agent: PostmanRuntime/7.11.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 426a51f8-d16c-4bef-a883-94636d1a2628,2c36a4e6-0ad6-439a-92eb-f44c29eed77b
Host: postman-echo.com
cookie: sails.sid=s%3AuCA6U9XBvmmvD0oXv21DghksJn6_8CvD.ISqk7aGtkJ9q7VPLAHv25shxMuY%2FW0kgpjPMrlHYoog
accept-encoding: gzip, deflate
content-length: 9
Connection: keep-alive
cache-control: no-cache

grant_type=password&username=admin&password123=password&scope=openid&key_1=value_1&key_2=value_2
```

In cURL
```
curl -X POST \
  https://postman-echo.com/post \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Host: postman-echo.com' \
  -H 'Postman-Token: 426a51f8-d16c-4bef-a883-94636d1a2628,9ba95cd7-1af7-4459-8e28-7882d6217096' \
  -H 'User-Agent: PostmanRuntime/7.11.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 9' \
  -H 'cookie: sails.sid=s%3AuCA6U9XBvmmvD0oXv21DghksJn6_8CvD.ISqk7aGtkJ9q7VPLAHv25shxMuY%2FW0kgpjPMrlHYoog' \
  -b sails.sid=s%3AuCA6U9XBvmmvD0oXv21DghksJn6_8CvD.ISqk7aGtkJ9q7VPLAHv25shxMuY%2FW0kgpjPMrlHYoog \
  -d 'grant_type=password&username=admin&password123=password&scope=openid&key_1=value_1&key_2=value_2'
```

Tested On Version 7.0.9
win32 10.0.17763 / x64

**Comment by chucklu** [comment] 2019-04-29 08:38
@VShingala  I  am trying to upgrade the software, but failed. Could you help me with https://github.com/postmanlabs/postman-app-support/issues/6381

**Comment by chucklu** [comment] 2019-04-29 08:56
@VShingala  With version 7.0.9, I find the parameter was lost.
The get request url is https://hdgateway.zto.com/WayBill_GetDetail?billCode=75132077503374
![image](https://user-images.githubusercontent.com/3004057/56885566-5599d500-6a9f-11e9-84f0-1baf41a19589.png)

Previously I got
```none
POST /WayBill_GetDetail HTTP/1.1
Host: hdgateway.zto.com
Content-Type: application/x-www-form-urlencoded
cache-control: no-cache
Postman-Token: f6ffc331-fcae-484f-bf5f-3006e4fb9692
billCode=542430453744undefined=undefined
```
Currently I got
```none
GET /WayBill_GetDetail?billCode=75132077503374 HTTP/1.1
Host: hdgateway.zto.com
Accept: text/html
cache-control: no-cache
Postman-Token: 799c7309-942a-4dae-bbbc-73db1a14ed50

```

**Comment by VShingala** [comment] 2019-04-29 09:22
@chucklu You haven't included `urlencoded` body in you request. And Previously you were using POST with `urlencoded` body. While in "Currently I got", you are using GET.

Using POST request with `urlencoded` body you should be able to get below code snippet.

```
POST /WayBill_GetDetail HTTP/1.1
Host: hdgateway.zto.com
Content-Type: application/x-www-form-urlencoded
cache-control: no-cache
Postman-Token: ade352bd-92c6-4bf9-8c8b-8d81a3888abe

billCode=75132077503374
```

**Comment by chucklu** [comment] 2019-04-29 10:32
@VShingala  I find the new generated with duplicate section Host and cache-control
And the postman-token looks weird, you provide two token id?
```none
POST /WayBill_GetDetail HTTP/1.1
Host: hdgateway.zto.com
Accept: text/html
Content-Type: application/x-www-form-urlencoded
User-Agent: PostmanRuntime/7.11.0
Cache-Control: no-cache
Postman-Token: 34995de5-4499-492a-ac7f-c49079e8ff79,05cb441d-a80a-4549-86bb-b694758790a5
Host: hdgateway.zto.com
accept-encoding: gzip, deflate
content-length: 23
Connection: keep-alive
cache-control: no-cache

billCode=75132077503374
```
![image](https://user-images.githubusercontent.com/3004057/56890752-ef1bb380-6aac-11e9-9ef3-48ee1d680342.png)

**Comment by abhijitkane** [comment] 2019-06-18 14:11
@nonyy @chucklu 
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

**Comment by chucklu** [comment] 2019-06-19 01:52
@abhijitkane   The previous problem was resolved in version 7.2.1

> I find the new generated with duplicate section Host and cache-control
> And the postman-token looks weird, you provide two token id?

I also tried with the powershell code, the logisticsRecord property lost content
```
{
  "result": {
    "prescriptionStatus": 5,
    "logisticsRecord": [
      " ",
      "  ",
      "   "
    ],
    "billPrescription": "1天17小时",
    "billCode": "75132077503374"
  },
  "message": "快递信息查询成功",
  "status": true,
  "statusCode": null
}
```

**Comment by chucklu** [comment] 2019-06-19 01:55
By the way the problem was resolved only in Experimental Codegen mode.

**Comment by abhijitkane** [comment] 2019-06-24 06:50
@chucklu The experimental mode will soon be made the default. Can you file a separate issue for the `logisticsRecord` bug you mentioned with details of what request you're trying to generate code for?

**Closed as completed by abhijitkane** 2019-06-24 06:50 UTC
Labels: bug, code-generator

**Comment by chucklu** [comment] 2019-06-24 09:35
@abhijitkane  I have create another issue https://github.com/postmanlabs/postman-app-support/issues/6775
