### ISSUE TITLE
Suggestions on export

### ISSUE THREAD

**Issue by blackhumors** [a85/POSTMan-Chrome-Extension#9003] opened 2020-08-31 08:41 UTC
When I want to export requests in a folder of the collection, it is currently not supported.Currently only requests in one collection can be exported. Can you support it?

**Comment by DannyDainton** [comment] 2020-09-01 06:32
Hey @blackhumors

Would you be able to expand on this information please and describe your usecase.

Who would be the people receiving the folder of requests? 

The Collection is the exported unit and you can decide what's contained with that. The format and structure on that Collection file allows other to easier import that into thier own instance of Postman or run these in a CI/CD environment using Newman.

**Comment by blackhumors** [comment] 2020-09-01 06:45
I am a server-side developer. When passing the exported informations with front-end developers, different developers only need the requests in one folder. At this time, I can only delete the redundant ones manually.

**Comment by SabriH10** [comment] 2020-09-02 15:30
Hi @blackhumors ,

Instead of deleting the redundant ones manually, you could create a new collection, then create a duplicate of the sub-folder you want to export, drop it into the newly created collection and export that collection instead.

**Comment by SabriH10** [comment] 2020-09-04 18:28
Hey @blackhumors,

Just wanted to check-in - Hopefully, the information shared in my previous response helps for your use case.

**Comment by postman-kenji** [comment] 2022-06-28 16:18
Closing this issue for now given age and response time. @SabriH10  please feel free to reopen this if you are still encountering this issue and the solution provided does not work. Thanks!

**Closed as completed by postman-kenji** 2022-06-28 16:18 UTC
Labels: feature, support
