### ISSUE TITLE
Basic Auth not encoding username when set via environment variable

### ISSUE THREAD

**Issue by kurt-friedrich** [a85/POSTMan-Chrome-Extension#8777] opened 2020-07-14 19:00 UTC
Basic Auth `Username` is not being encoded into `Authorization` header when set via an environment variable. The env var value is "linked" and appears correctly when you hover over the variable reference, but the `Authorization` header value is always `Basic Og==` (base64 encoding of `:`).

**To Reproduce**
1. Go to 'Authorization'
2. Click on 'Type' and select 'Basic Auth'
3. Add a previously-set environment variable to the 'Username' field (e.g. `{{MY_VARIABLE}}`)
4. Go to 'Headers'
5. See that `Authorization` header value is `Basic Og==`

**Expected behavior**
The `Username` value should be encoded and assigned to the `Authorization` header

**App information (please complete the following information):**
 - Native App
 - 7.28.0
 - macOS Catalina 10.15.5

**Additional context**
When the `Username` is set directly, it is encoded and correctly assigned to the `Authorization` header.

**Comment by DannyDainton** [comment] 2020-07-15 07:02
Hey @kurt-friedrich 

Just trying to reproduce the issue that you're seeing and it's not happening the same way for me.

If I add an environment variable into the `Username` field, it's showing that in the Live Header preview.

<img width="721" alt="Screenshot 2020-07-15 at 07 44 16" src="https://user-images.githubusercontent.com/17089546/87513904-57829080-c671-11ea-83fa-a03bb2f671c8.png">

<img width="668" alt="Screenshot 2020-07-15 at 07 44 27" src="https://user-images.githubusercontent.com/17089546/87513892-518caf80-c671-11ea-8d5f-6bd98afdb771.png">

The only time that I get something similar, is when I have the Auth helper selected and I leave the fields blank.

<img width="734" alt="Screenshot 2020-07-15 at 07 43 42" src="https://user-images.githubusercontent.com/17089546/87513620-ea6efb00-c670-11ea-918a-2fc2359122a5.png">

<img width="679" alt="Screenshot 2020-07-15 at 07 43 54" src="https://user-images.githubusercontent.com/17089546/87513651-f5c22680-c670-11ea-8289-062b4a2a9999.png">

Would you be able to provide some screenshots or even better a short gif/video of the issue so we can see what's happening on your end?

**Comment by kurt-friedrich** [comment] 2020-07-15 15:01
@DannyDainton Seems like we are experiencing different behavior for the same actions. Here are my screenshots:

<img width="982" alt="Screen Shot 2020-07-15 at 10 57 53 AM" src="https://user-images.githubusercontent.com/17503641/87561329-848f6d00-c68a-11ea-94af-c1b0a4d1c708.png">

<img width="988" alt="Screen Shot 2020-07-15 at 10 58 14 AM" src="https://user-images.githubusercontent.com/17503641/87561342-8bb67b00-c68a-11ea-9f99-a06e7096d2fc.png">

**Comment by DannyDainton** [comment] 2020-07-15 15:31
I'm looking into this a bit more and I can see this happening on _some_ occasions but trying to establish the pattern. 🤔 

Is this only happening for you when you don't set the `Current` value?

**Comment by mohitranka** [comment] 2020-07-15 16:09
@appurva21 Can you help triage this?

**Comment by kurt-friedrich** [comment] 2020-07-15 16:21
I am able to get a properly encoded `Authorization` header when I set `Current` value, but only when it is set _before_ I select 'Basic Auth'.

It almost seems like there are a couple issues at play - one related to encoding the `Initial` value (which is never happening), and another related to _updating_ the header when the env var value is changed.

Here are some patterns I observed in a few minutes of testing. Step 10 of the "Bad" path is where things get especially interesting.

**Good**
1. Go to 'Authorization'
2. Click on 'Type' and select 'No Auth'
3. Set `Current` value for env var
4. Go to 'Authorization'
5. Click on 'Type' and select 'Basic Auth'
6. Add env var to the `Username` field
7. See that `Authorization` header value is correctly encoded

**Bad**
1. Go to 'Authorization'
2. Click on 'Type' and select 'No Auth'
3. Set only `Initial` value for env var
4. Go to 'Authorization'
5. Click on 'Type' and select 'Basic Auth'
6. Add env var to the `Username` field
7. See that `Authorization` header value is incorrectly encoded (`Basic Og==`)
8. Set `Current` value for env var
9. See that `Authorization` header value has _not_ updated and is still incorrectly encoded (`Basic Og==`)
10. Manually add a second / duplicate `Authorization` header (with or without value)
11. See that Postman-generated `Authorization` header value has now updated and is correctly encoded for `Current` value
12. Remove `Current` value from env var
13. See that Postman-generated `Authorization` header value has _not_ updated and is still encoded for deleted `Current` value
14. _Uncheck_ or _delete_ manually created `Authorization` header
13. See that Postman-generated `Authorization` header value has updated back to incorrect encoding for `Initial` value (`Basic Og==`)

**Comment by appurva21** [comment] 2020-07-16 10:03
Hey @kurt-friedrich !! Thanks for writing in and providing such detailed steps to reproduce the issue.

So regarding the flow where correct header value is not showing up when you don't set the `current value` of the variable is because whenever you use a variable in the request it gets resolved to its `current value`. 
Since in your case, you have only specified the `initial value` (I am assuming you must have deleted the value from the current value column to unset it, which is resulting in an empty string being set for it), the `Authorization` header value correctly updates to `Basic Og==` as the `username` variable is getting resolved to an empty string (it's current value), similar to the case when you don't set anything in the username field.

Now about the preview not getting updated, it has already been reported [here](https://github.com/postmanlabs/postman-app-support/issues/8617) and we will soon be shipping out a fix for this. You can follow the thread [here](https://github.com/postmanlabs/postman-app-support/issues/8617) for the latest updates.

**Comment by kurt-friedrich** [comment] 2020-07-16 14:31
Thanks @appurva21 🙂 I'm still a bit confused, because the documentation seems to imply otherwise.

From the "Using Variables" docs:

> When you create or edit a variable, you can enter both an initial and a current value. You can choose to leave the current value empty, in which case it will default to the initial value.

https://learning.postman.com/docs/sending-requests/variables/

Is this incorrect? Or am I misinterpreting it?

**Comment by appurva21** [comment] 2020-07-16 15:34
@kurt-friedrich We copy the initial value to current value only while creating a new variable from the UI, to aid new users of this feature and avoid the common errors due to current value being left blank.

@SueSmith Let us update our docs to reflect the same more clearly.

**Comment by kurt-friedrich** [comment] 2020-07-16 16:09
@appurva21 Awesome, thanks for clarifying 🙏

**Closed as completed** 2020-07-17 06:05 UTC
Labels: product/runtime
