### ISSUE TITLE
Postman 5.3 keeps deleting mode-auto.js 

### ISSUE THREAD

**Issue by sdknintex** [a85/POSTMan-Chrome-Extension#3638] opened 2017-10-16 01:41 UTC
## App Details:
Postman for Windows
Version 5.3.0
win32 10.0.14393 / x64

## Issue Report:
Postman regularly says it can't find _/AppData/Local/Postman/app-5.3.0/resources/app.asar/html/mode-auto.js_. I have been unable to track down exactly when this occurs, although it reliably has occurred by the start of each day, after system has hibernated for several hours.

This prevents me getting new OAuth2.0 tokens unless I uninstall/reinstall the app. When I go to get a token, I press "Request token", it takes me through the approval process with the third-party service, and then just shows the "request token" screen, not the final "use token" screen. Reinstalling the app reliably removes the error message (below) and fixes this.

There is no process on the system I am aware of that would be modifying the file, nor have I had file-deletion issues with any other apps. It is always the same resource that can't be found.

 1. Did you encounter this recently, or has this bug always been there:
Since I updated to 5.3. 

 2. Expected behaviour:
Installed components to remain installed.

 3. Console logs file:///C:/Users/username/AppData/Local/Postman/app-5.3.0/resources/app.asar/html/mode-auto.js net::ERR_FILE_NOT_FOUND

Evidently this is not a widespread issue, or you'd have had many more issue reports on it by now. There is an easy workaround (just reinstall postman every morning), I'm largely submitting this as an FYI.

**Comment by kamalaknn** [comment] 2017-10-16 18:23
@sdknintex This might not be related to the missing `mode-auto.js`.

We've identified the root cause and have fixed it internally. We'll be rolling out the fix in the next couple of days. Until then reloading the app should do the trick for you(`View -> Reload`).

We are tracking this in #3616. I am closing this issue, you can subscribe to the root issue for updates on release.

**Closed as completed by kamalaknn** 2017-10-16 18:23 UTC

**Comment by jooleeanh** [comment] 2017-12-21 09:23
My computer froze, I hard-rebooted it, and Postman gave me the following error:

![image](https://user-images.githubusercontent.com/9873597/34249102-bbbc2848-e638-11e7-99f5-01054f8d81f3.png)
Neither `View > Reload` nor restarting the app worked.
I don't use OAuth2.0 tokens so I don't think it's related to #3616.

## App Details:
```
Postman for Mac
Version 5.5.0
OS X 10.12.6 
```
