### ISSUE TITLE
As a postman flow user, I want block is able to export the whole data

### ISSUE THREAD

**Issue by wangfeifan945** [a85/POSTMan-Chrome-Extension#11969] opened 2023-04-28 15:22 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

not about problem but for a new feature

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/37173694/235186284-49045cc2-d374-4244-9ccc-63d989958e27.png)
For example, with block = "Output", it can show the value in multiple formats. Or JSON or text or other formats.
But as a user, sometimes I want to copy the output as backup or other purposes.

But existing version postman flow not support this feature, so I have to print the data as log and then copy the whole log.
So here is tricky that only be able to export whole log, but not some.

This led to that I must clean the log again. 
It tooks my much time and hope team is able to support export data.

Or provide copy all 
Or export data out like csv,excel,txt etc.

Same time, i want to confirm does postman support cloud file.
Now cloud is widly used, if the postman support file export to cloud like onedrive,box, will very benefit for user 

### Additional context

![image](https://user-images.githubusercontent.com/37173694/235186284-49045cc2-d374-4244-9ccc-63d989958e27.png)
For example, with block = "Output", it can show the value in multiple formats. Or JSON or text or other formats.
But as a user, sometimes I want to copy the output as backup or other purposes.

But existing version postman flow not support this feature, so I have to print the data as log and then copy the whole log.
So here is tricky that only be able to export whole log, but not some.

This led to that I have to clean the log again.

**Comment by SterlingChin** [comment] 2023-07-19 22:16
Thank you for feature request! We'll look into this for future development.

**Comment by rabbah** [comment] 2023-11-02 16:25
Duplicate of #11974 - we're working on this.

**Closed as completed by rabbah** 2023-11-02 16:25 UTC
Labels: feature, Flows
