### ISSUE TITLE
slashes

### ISSUE THREAD

**Issue by chenjianeng0201** [a85/POSTMan-Chrome-Extension#6900] opened 2019-07-11 07:10 UTC
![image](https://user-images.githubusercontent.com/42136057/61029608-ff75d600-a3ed-11e9-9f08-d881f71cc02e.png)

**Comment by kamalaknn** [comment] 2019-07-12 03:52
Hi @chenjianeng0201 

Thanks for reporting this. This looks like a duplicate of #6899.

I'm closing this. Please follow the original issue for updates.

**Closed as completed by kamalaknn** 2019-07-12 03:52 UTC
Labels: bug, response-rendering
