### ISSUE TITLE
Collection runner modifying large numbers

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#8771] opened 2020-07-13 20:48 UTC
**Describe the bug**
For CSVs, numbers over 16 digits are being rounded/modified when used in the Collection Runner. See example below:

| raw value | value used in request |
| --------- | ----------- |
| 5720687706200772658.153 | 5720687706200773000 |
| 5720687706200772658.15 | 5720687706200773000 |
| 5720687706200772658.1 | 5720687706200773000 |
| 5720687706200772658 | 5720687706200773000 |
| 572068770620077265 | 572068770620077250 |
| 57206877062007726 | 57206877062007730 |
| 5720687706200772 | 5720687706200772 |
| 572068770620077 | 572068770620077 |
| 57206877062007 | 57206877062007 |

Workaround is to wrap value in quotes in CSV:
"5720687706200772658"

**To Reproduce**
1. Create a CSV containing at least one number with >16 digits.
2. Try to use CSV in collection runner
3. Check Postman console to see that values used in requests are modified from their original value.

**Expected behavior**
Numbers in requests are used exactly as represented in the data source.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.28.0
 - OS: MacOS

**Additional context**

**Comment by bcole** [comment] 2020-08-04 16:28
+1 on this - we ran into the same issue last night (nasty one to debug, too, with large data collections).

I just wanted to add, it doesn't always have to be a value with decimal places.  We had a number `13563577887054669` which for whatever reason was adjusted to `13563577887054668`.  Must just be a precision bug in how Postman is storing number values.

**Comment by vikiCoder** [comment] 2021-01-08 09:12
Closing this as duplicate of https://github.com/postmanlabs/postman-app-support/issues/6746

**Closed as completed by vikiCoder** 2021-01-08 09:12 UTC
Labels: product/runtime
