### ISSUE TITLE
Importer: parameters/schema/reference "not found in the api spec"

### ISSUE THREAD

**Issue by cfritschi** [a85/POSTMan-Chrome-Extension#7769] opened 2019-12-10 11:02 UTC
**Describe the bug**
Importing the following yaml example ends in corrupted get/parameters.

**To Reproduce**
1. Go to Postman base app
2. Click on 'Import'
3. Choose file -> petstore.yaml
4. Open the imported collection
5. Open the Request "pets Get By Source" 
6. See parameter section

**Expected behavior**
The parameters should be created as in the yaml defined (also the reference)

**Screenshots**
![image](https://user-images.githubusercontent.com/15942557/70524020-96cd8980-1b44-11ea-8b0c-52208435fa2c.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.13.0]
 - OS: [Windows-10 v1909]

**Additional context**
see petstore.yaml
[petstore.zip](https://github.com/postmanlabs/postman-app-support/files/3944497/petstore.zip)

**Comment by cfritschi** [comment] 2019-12-10 11:03
![image](https://user-images.githubusercontent.com/15942557/70524275-1b200c80-1b45-11ea-98c8-dcaf8acc751b.png)

**Comment by abhijitkane** [comment] 2019-12-31 05:29
@cfritschi I'm unable to reproduce this with version 7.14 of the app. Can you confirm?

**Comment by VShingala** [comment] 2022-02-23 18:09
@cfritschi Closing this as this is supported with current import/generation flow. Feel free to reopen the issue if you face any further problems.

**Closed as completed by VShingala** 2022-02-23 18:09 UTC
Labels: bug, product/api-design
