### ISSUE TITLE
The app is not displaying anithing

### ISSUE THREAD

**Issue by danteay** [a85/POSTMan-Chrome-Extension#6855] opened 2019-07-04 00:49 UTC
**Describe the bug**
I've reinstalled the Postman app but is totally transparent, and don't show anything of the front app. Its running and present in desktop but it shows nothing.

**To Reproduce**
* OS:
* Package: Postman for Linux x64

1. Install by extracting the tar file into */usr/local/apps* folder
2. Make a link from */usr/local/apps/Postman/Postman* to */usr/local/bin/postman*
3 execute in console to see execution logs

**Expected behavior**
The complete app has to be displayed as not transparent at all.

**Screenshots**
![Captura de pantalla de 2019-07-03 19-38-06](https://user-images.githubusercontent.com/9085902/60632287-71d12f80-9dca-11e9-8953-da5c52fb6285.png)

![Captura de pantalla de 2019-07-03 19-45-39](https://user-images.githubusercontent.com/9085902/60632433-29664180-9dcb-11e9-91ba-ce01c057faee.png)

**App information (please complete the following information):**
 - App Type *Native Linux app*
 - Postman Version *7.2.2*
 - OS: *elementary OS 5 Juno*

**Comment by preethammavin** [comment] 2019-07-05 18:32
@danteay were you by any chance using multiple monitors? if so can you check if connecting to the other monitor and relaunching the app opens up in that monitor as we are unable to reproduce this on our end.

**Comment by danteay** [comment] 2019-07-06 04:47
@preethammavin as you can see in the first image, the interface is present but completely transparent, also in the image there is a pointer (arround the middle left of the image) that is possible to see a collection name, so the app is not in other monitor or something. the application is present in current desktop, but I've try it by connecting other monitor and the app still in the same error.

**Comment by harryi3t** [comment] 2019-07-08 04:52
@danteay Can you give a try to our [canary build](https://getpostman.com/downloads/canary) which has an updated underlying platform?

**Comment by danteay** [comment] 2019-07-08 14:12
@harryi3t sure, letme try it and I'll give you my comments

**Comment by danteay** [comment] 2019-07-08 20:58
@harryi3t Canary works fine

![Captura de pantalla de 2019-06-27 16-27-42](https://user-images.githubusercontent.com/9085902/60842238-4028e180-a199-11e9-8408-02ca8dc7b38d.png)

**Comment by danteay** [comment] 2019-07-08 20:59
@harryi3t Canary woks fine

![Captura de pantalla de 2019-07-08 15-57-30](https://user-images.githubusercontent.com/9085902/60842281-5df64680-a199-11e9-8d88-498441a174da.png)

**Comment by danteay** [comment] 2019-07-08 21:23
@harryi3t sorry bro, same error, after close an reopen the app still the error in canary

**Comment by DannyDainton** [comment] 2022-04-28 16:39
Hey @danteay 

This looks like an issue with an earlier version of the platform - I'm going to close this out but if you're still having issues with the latest version we can reopen and investigate further.

**Closed as completed by DannyDainton** 2022-04-28 16:39 UTC
Labels: product/client-foundation
