### ISSUE TITLE
Can not save all Collections values

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#8904] opened 2020-08-09 15:47 UTC
When I try to export collections there won't any saving mechanisms for values I put in to collections. It works in individual requests but cant save all of them.

![postman_collection](https://user-images.githubusercontent.com/12722674/89736216-b84f8e00-daa2-11ea-880f-d6e4175c2b87.png)

1. when I press ctrl+s. It saves one request but not another requests values

![postman_values](https://user-images.githubusercontent.com/12722674/89736219-ba195180-daa2-11ea-8582-bb76b49eea01.png)

2. The values I want to save is URL, Param keys and so forth

**Comment by codenirvana** [comment] 2020-08-09 16:00
Duplicate of #3466

**Closed as completed by codenirvana** 2020-08-09 16:00 UTC
Labels: duplicate
