### ISSUE TITLE
Environment variable not set inside .then

### ISSUE THREAD

**Issue by santhosh2512** [a85/POSTMan-Chrome-Extension#9567] opened 2021-02-08 06:09 UTC
In prerequest script:

```
sendGetRequest(finalrequest)
            .then((data) => {
                console.log("data from  postRequest ", data)
                var key = 'OAuth ' + btoa(JSON.stringify(data));
                pm.environment.set('OAuth', key);
                console.log("OAuth: ",  pm.environment.get('OAuth'));
            })
```

In the above example, it is printing the console.log but when I check the environment variable file the variable 'OAuth' does not exist. Because of this, I am not able to pass this variable value required for the API request header.

**Comment by DannyDainton** [comment] 2021-02-08 11:53
Hey @santhosh2512 

Could you please complete the rest of the issue template to include the app version and more context around the custom `sendGetRequest` function that you have written, please? 

---

**Describe the Issue**

> A high-level summary or description of the problem that you're facing.

**Steps to Reproduce**

> A list of steps that can be followed to recreate the issue.


**Screenshots or Videos**

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 


**Environment Information**

 - Platform Type: [e.g. Native Desktop App, Postman On The Web, Web Dashboard]
 - Postman Version:
 - Operating System:

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by codenirvana** [comment] 2021-02-15 08:29
@santhosh2512 This is a known issue, script execution doesn't wait for all the promises to resolve. Some workarounds are already mentioned in #4131.

Closing as duplicate of #4131

**Closed as completed by codenirvana** 2021-02-15 08:29 UTC
Labels: support
