### ISSUE TITLE
Beautify doesn't work if environment variable notation is used within request body.

### ISSUE THREAD

**Issue by akj009** [a85/POSTMan-Chrome-Extension#7795] opened 2019-12-13 11:32 UTC
**Describe the bug**
In POST request with raw JSON body, if I use environment variable and then try to beautify the body (just for inspecting other parameters), it doesn't work. To get it to work, I have to remove the environment variables, then click on beautify and then add them back.

**To Reproduce**
1. Create a POST request.
2. Go to 'Body' tab.
3. Select body type as raw and content type as JSON
4. Add request body with environment variables.
5. Click on beautify link to format JSON.

**Expected behavior**
The json request body should get formatted properly

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : 7.13.0 (7.13.0)
 - OS: macOS Mojave 10.14.6

**Comment by kamalaknn** [comment] 2019-12-17 05:11
@akj009 Thanks for reporting this issue. 

This looks like a duplicate of #6133. I'm closing this issue. Please follow the original issue for updates.

**Closed as completed by kamalaknn** 2019-12-17 05:11 UTC
Labels: bug, code-editor
