### ISSUE TITLE
Postman hangs on sending any request when globals are missing

### ISSUE THREAD

**Issue by lawnboyy** [a85/POSTMan-Chrome-Extension#4985] opened 2018-08-07 13:44 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Clicking send on any request does not send the request. The send button changes to "Sending..." and the area at the bottom says "Loading...", but nothing happens regardless of how long I wait. If I pull up the developer tools, no network requests are made and the following error appears in the console:

Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at child.send (requester.js:14528)
    at <anonymous>
send @ requester.js:14528

**To Reproduce**
1. Enter a URL for a GET request (doesn't matter if it's valid or not, you should get a 404 if it's not)
2. Click on 'Send'
3. Wait until Heat Death of the Universe for request to complete
4. Give up and use Fiddler

**Expected behavior**
I expect the request to complete.

**Screenshots**
![console_error](https://user-images.githubusercontent.com/8755968/43779249-85460d44-9a1d-11e8-9ad3-b7505444afbe.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.2.3
 - OS: Windows 10

**Comment by kamalaknn** [comment] 2018-08-07 14:52
Hey @lawnboyy 

Thanks for the report. From your report I was able to identify code flow that was causing this issue. I could see that you do not have global variables in the storage. That is causing the request sending flow to error out because it is assuming a global variables scope to always be present.

There are two parts to this issue. 

1. The request sending flow should be tolerant to failures in other systems. **We are pushing a fix in the next version to make sure request flows work even if there are failures in globals creation**.
2. A global variable scope should always be created for your workspace as soon as you join a workspace or login for the first time. But like all systems this is not accurate because a network is involved to pull the globals from sync servers. We do have a fail safe for this that should detect and correct such inconsistencies when you restart the app.

You can try restarting the app. Wait for syncing to finish. This would pull missing entities. Then give it a try.

We are working on the fix from our side as well.

PS: I'm guessing you are signed in with your account on Postman. If my assumption is wrong let me know, so I can suggest alternatives.

Thanks

**Comment by lawnboyy** [comment] 2018-08-07 14:59
Hey @kamalaknn 

Thanks for the quick reply. I am signed in on Postman with my Google account. I have tried restarting the application and I've even uninstalled and reinstalled it. But I continue to get the error. This seems to have started when our corporate network changed. How do I access/configure the global variables?

**Comment by kamalaknn** [comment] 2018-08-07 15:10
Hey @lawnboyy 

Can you restart the app open the shared process logs with `View -> Developer -> Show DevTools (Shared)` and share any errors you see?

It will help me identify the cause for why globals are missing.

Also can you give me a description of what the state of your app is, how many workspaces do you see, collections, the sync indicator etc.

**Comment by lawnboyy** [comment] 2018-08-07 15:15
Here are the shared process logs:

![image](https://user-images.githubusercontent.com/8755968/43784912-db82918e-9a2a-11e8-88de-ebd53147ff81.png)

**Comment by lawnboyy** [comment] 2018-08-07 15:16
![image](https://user-images.githubusercontent.com/8755968/43784927-e23794de-9a2a-11e8-886a-a8fb84e10473.png)

**Comment by lawnboyy** [comment] 2018-08-07 15:17
Here is my application. I've never really set up workspaces. Let me know if there is something specific you'd like to see.

![image](https://user-images.githubusercontent.com/8755968/43785049-21a0a098-9a2b-11e8-8a60-52cef370d425.png)

**Comment by kamalaknn** [comment] 2018-08-07 15:28
Hey looks like you have sync disabled. Can you open `Settings -> Sync` and check?

**Comment by lawnboyy** [comment] 2018-08-07 15:33
Yes, it was disabled. I enabled it and it seems to be working again. Thanks a lot for your help!

**Comment by kamalaknn** [comment] 2018-08-07 15:50
Glad that it worked.

**Comment by kamalaknn** [comment] 2018-08-09 13:41
@lawnboyy We've pushed a fix in `6.2.4` that will make sure the system continues to work with sending requests when there are failures with setting up globals.

**Closed as completed** 2018-08-09 13:41 UTC
Labels: regression

**Comment by NitinSaxenait** [comment] 2022-04-11 16:20
Hi @kamalaknn my postman is getting hang while sending the request. Can you please the issue
![Screenshot from 2022-04-11 21-40-51](https://user-images.githubusercontent.com/77061053/162785682-ba5bd653-3794-45b2-97a5-ef1ef55e0821.png)
