### ISSUE TITLE
Allow customization of bearer token

### ISSUE THREAD

**Issue by washeck** [a85/POSTMan-Chrome-Extension#4727] opened 2018-06-22 12:17 UTC
I need to work with application which uses authorization with a bearer token but the value of Authorization header is not "Bearer ..." but "Token ...".

Postman "Bearer Token" would be perfect for my needs but it has hardcoded the string "Bearer " added before the token value. I think it should be possible to customize the whole header as not all APIs respect the bearer convention. Or it would make sense to add yet another authentication type which allows full customization of headers.

I know there workarounds (adding the header to all requests or using collection-wide pre-request script) but it would be cleaner to have it solved in authorization.

**Comment by darron1217** [comment] 2018-06-23 07:28
It seems duplicate of #4044

**Comment by kevcam4891** [comment] 2019-10-25 13:46
This is becoming a critical reason I can't use Postman for work with AWS. Cognito doesn't want "Bearer" text in the Authorization header. I understand I could just add a custom "Authorization" header, but then I can't easily use Oauth2 support in Postman.

This should be a very simple enhancement that will have significant benefit for those using services that don't need the "Bearer" string, or need something else in its place.

**Comment by kevcam4891** [comment] 2020-01-30 13:41
@vvs11 Any update on this? Do you see this as a potentially easy challenge to solve? Just need to be able to remove "Bearer" from authorization header, at the very least.

**Comment by mohitranka** [comment] 2020-06-22 15:55
This has been released in the lastest Postman app V7.27. Please upgrade and give it a go!

**Closed as completed by mohitranka** 2020-06-22 15:55 UTC
Labels: feature, Auth, Plugin, product/runtime

**Comment by AllenEllis** [comment] 2021-01-31 17:34
Hi, how exactly was this implemented? I'm trying to use Postman with an API that expects the keyword `Token` instead of `Bearer`. As of Postman App version 8.0.3 I see no way to customize this, and [the documentation](https://learning.postman.com/docs/sending-requests/authorization/#bearer-token) indicates it is still not possible:

> Postman will append the token value to the text "Bearer " in the required format to the request Authorization header as follows:

**Comment by jorgv** [comment] 2021-02-09 14:24
> Hi, how exactly was this implemented? I'm trying to use Postman with an API that expects the keyword `Token` instead of `Bearer`. As of Postman App version 8.0.3 I see no way to customize this, and [the documentation](https://learning.postman.com/docs/sending-requests/authorization/#bearer-token) indicates it is still not possible:
> 
> > Postman will append the token value to the text "Bearer " in the required format to the request Authorization header as follows:

You can now use API Key option and then use "token" or any other prefix
![image](https://user-images.githubusercontent.com/32174909/107377010-cc745680-6aea-11eb-94e5-39d7483401e0.png)

That will work the same as the bearer but with any prefix you want to use.
