### ISSUE TITLE
Call to localhost:8000 "Could not get any response"

### ISSUE THREAD

**Issue by cpiggott** [a85/POSTMan-Chrome-Extension#2214] opened 2016-08-01 19:10 UTC
I recently updated the Postman Mac application to 4.5.0 and I'm currently having issues getting a response from localhost. 

I have tried multiple ports and restarted everything that I thought could be an issue(Postman, local Apache, server, etc.) I don't believe it is an issue with my server or apache. I can reach the localhost with Postman by using [ngrok](https://ngrok.com/) to POST/GET the URL that is tunneled to my localhost.

Not sure what the issue is, console isn't logging any errors either.

Version/App Information:
1. Postman Version: 4.5.0
2. App (Chrome app or Mac app): Chrome app
3. OS details: OS x 15.0.0 x64
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Latest update
6. Expected behaviour: 200 OK
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Nothing
8. Screenshots (if applicable)

Steps to reproduce the problem: Make a POST/GET request to localhost:xxxx while running a LAMP stack in development mode.

**Comment by abhijitkane** [comment] 2016-08-01 19:12
@cpiggott Can you check also check the Postman console (View -> Show Postman Console) for any errors?
Also, are you able to make requests to non-localhost endpoints? (`GET http://echo.getpostman.com/get`)

**Comment by cpiggott** [comment] 2016-08-01 19:24
@abhijitkane I am able to connect to `http://echo.getpostman.com/get` and any other site, it's only happening with localhost.

Error: connect ECONNREFUSED 127.0.0.1:8080 is getting logged.

**Comment by abhijitkane** [comment] 2016-08-01 19:46
@cpiggott Can you try adding these two headers in the Postman UI:

```
Accept: */*
Accept-language: en-US,en;q=0.8
```

**Comment by cpiggott** [comment] 2016-08-01 19:47
@abhijitkane Tested with the errors, still getting the same error.

**Comment by cpiggott** [comment] 2016-08-01 19:51
@abhijitkane I ran a NodeJS server on port 9000 and I'm getting the expected response from it.

It may be something to do with Laravel, but I ran it this morning before updating and had no problem with my Laravel test server.

**Comment by abhijitkane** [comment] 2016-08-01 19:57
Are there any error/debug logs printed by your laravel server?

**Comment by cpiggott** [comment] 2016-08-01 20:08
Nothing error/debug is being logged. 

I can reach localhost:8080 from Chrome, but not Postman.

**Comment by czardoz** [comment] 2016-08-01 20:12
@cpiggott Hope you don't mind me jumping in! 
Does it also happen if you use `127.0.0.1` instead of `localhost`? Surprisingly, the error shown is a "ECONNREFUSED" which means that Postman could not even connect to the server.

**Comment by knarz** [comment] 2016-08-02 16:09
I think I'm hitting a similar (the same?) problem.

After upgrading to `4.5.0` from `4.4.3` postman seems to be unable to talk to one of the daemons that I have running locally whereas a simple `curl` still works as expected. After downgrading to the previous version I can talk to the daemon in question normally again.

Response headers from the daemon that does _not_ work with `4.5.0`

```
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 3021
< Connection: close
```

Response headers from a daemon that does work with `4.5.0`

```
< HTTP/1.1 200 OK
< Date: Tue, 02 Aug 2016 16:00:11 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 26
```

**Comment by cpiggott** [comment] 2016-08-02 17:38
@czardoz If I hit 127.0.0.1 I get a 200 OK. 

If I try and hit 127.0.0.1:8080 I get the same response.

**Comment by capicue** [comment] 2016-08-02 21:53
I ran into this issue as well. It seems that Postman converts localhost to 127.0.0.1 before making the request. I happened to be serving a Rails app with Puma that was not listening on 127.0.0.1, only [::1]. They have since fixed this in Puma (https://github.com/puma/puma/issues/782), but it seems like this will at first look like a Postman issue whenever a server disregards ipv4. 

My symptoms were as follows:

## In a browser:
- http://localhost:3000 works (due to having "::1 localhost" in my /etc/hosts file)
- http://127.0.0.1:3000 does not work
- http://[::1]:3000 works

## In Postman:
- http://localhost:3000 **does not work** (because it's getting converted to 127.0.0.1)
- http://127.0.0.1:3000 does not work
- http://[::1]:3000 works

**Comment by jpletner** [comment] 2016-08-04 16:34
Same issue here. Works with http://[::1]:3000. Thank you @capicue!!!

**Comment by shamasis** [comment] 2016-08-05 20:08
Issue is fixed in 4.5.1 release. If I get one confirmation, I can close this issue. Let me know.

**Comment by knarz** [comment] 2016-08-06 18:47
Doesn't seem to fix it for me.

**Comment by czardoz** [comment] 2016-08-06 19:03
@knarz can you tell us a few more details?
1. What framework do you use? 
2. How do you start the server?
3. What happens when, instead of localhost you use one of these values?
   1. `127.0.0.1`: example: `http://127.0.0.1:8080/my/url`
   2. "::1" , example: `http://[::1]:8080/my/url`
4. Contents of your `/etc/hosts` file. (Feel free to leave out sensitive entries, I'm mostly interested in the `localhost` entries :)

**Comment by knarz** [comment] 2016-08-06 19:41
Sure.
1. The daemon that I cannot contact with the new version is written in Java, not sure which framework. As stated before, a simple `curl` works just fine, as does version `4.4.3`.
2. `java -jar server.jar`.
3. Neither of those make the request succeed.

```
127.0.0.1 localhost
::1       localhost 
```

**Comment by cpiggott** [comment] 2016-08-08 20:44
Update to 4.5.1 fixed the issue for me.

**Comment by ywang-clarify** [comment] 2016-08-18 17:42
I'm seeing this problem in the Windows app version 4.6.1.
Requests to http://localhost:3000/stuff fail with no response.
Requests to http://127.0.0.1:3000/stuff works fine.

The Chrome app (version 4.6.0) works fine with http://localhost:3000/stuff

**Comment by rahulsivalenka** [comment] 2016-12-04 06:40
This issue exists in the latest Chrome app Postman 4.9.0.

http://localhost:3100/test fails
http://127.0.0.1:3100/test works

**Comment by devjamie** [comment] 2017-02-08 21:01
I'm having this issue too 4.9.3

**Comment by airs0urce** [comment] 2017-02-10 21:16
This is what I see in console when get that error:
https://dl.dropboxusercontent.com/u/1875424/Screen%20Shot%202017-02-11%20at%2012.08.10%20AM.png

I have same error when I send request from node.js application written by me. 
I suppose Postman uses node.js too.
In my app I have a little more debug information, and I see "HPE_INVALID_CONSTANT":

> "message":"Error: Parse Error","cause":{"bytesParsed":278,"code":"HPE_INVALID_CONSTANT"

which means there is issue with parsing response. May be something wrong with response headers for example. I had this issue before and it was because server was returning wrong value in "Content-length" header, for example, Content-length: 10, but real length of body is 5. PHP will handle this case without issues, but node.js don't ignore it and throw HPE_INVALID_CONSTANT and "Parse Error". 
As solution to handle errors like these (and if I'm right about Postman written with node.js, as I didn't check it) it makes sense to replace http parser by this one:
https://www.npmjs.com/package/http-parser-js

And I think it should let Postman work even with http servers that return invalid headers.

**Comment by Chobicus** [comment] 2017-02-12 06:58
Postman's response is confusing.
I was getting no response because I had one of the header names with quotes. 
Postman would respond with:

> Could not get any response

The console output is:

> Error:
Header name must be a valid HTTP Token [""Invheader""]

**Comment by sdnts** [comment] 2017-02-13 07:21
The native Postman apps do run on a NodeJS sandbox, so that could be a possibility.
@Chobicus @airs0urce Is this misbehaviour only observed with `localhost` and not `127.0.0.1`?

**Comment by airs0urce** [comment] 2017-02-13 11:10
@madebysid It's not only on localhost. As I got an API (private), and saw there is "Parse Error" when I implemented that API in node.js. Then I decided to test it in Postman and saw same error. I also tried "Rested" HTTP client for macOS, and it returned response without issues. So, issue happens only in node.js and error message is "Parse Error".
This module solves the issue: https://www.npmjs.com/package/http-parser-js 
I suppose something wrong with HTTP response format and node.js can't eat everything. 
But when I try to reproduce for example wrong Content-length on local machine, Postman and node.js works good, issue happens only for certain servers. May be because there is proxying of http requests and that proxy change something more, not only Content-length. It's hard to tell why error appears.

**Comment by blarzHernandez** [comment] 2017-02-22 22:33
http://localhost:3100/dishes fails
http://127.0.0.1:3100/dishes works good

**Comment by tokidoki11** [comment] 2017-06-18 13:10
I'm facing the same problem as well. 
In my case adding Header x-access-token

if I remove the header, it works fine

**Comment by agolendukhin** [comment] 2017-06-26 13:04
firewall can block 8000 port also, e.g. antivirus's one.

**Comment by chemalopezp** [comment] 2017-07-26 17:58
Using Postman 5.1.2, localhost doesn't work when the url is provided via a environment variable.

I have a {{domain}} environment variable to select easily which system to test ({{domain}} = http://url.system.com)
Works fine with every system, also ngrok urls, but there's no way to use it with localhost.
I tried defining the variable with:
http://127.0.0.1:8081
http://localhost:8081
http://[::1]:8081

I always get this error:
Could not get any response
There was an error connecting to %7B%7Bdomain%7D%7D/...

Unlike with other environments, in this case domain appears in red ('Unresolved variable') even if it is defined, as they are for the other environments, which seems to be related more than postman not able to notice the domain variable rather than connection issues.
<img width="974" alt="screen shot 2017-07-26 at 10 54 49" src="https://user-images.githubusercontent.com/15825354/28635897-230931e2-71f1-11e7-85fd-965f3f0a977b.png">

Right now I have to use ngrok to test my localhost... which expression should be accepted by Postman?

**Comment by ms-OrionCox** [comment] 2017-09-22 17:32
Turn off SSL Certificate Verification in Settings>General

**Comment by magasea** [comment] 2017-10-01 23:16
close your interceptor

**Comment by caddac** [comment] 2017-11-07 22:16
I was having this same issue on Mac postman 5.3.2, turns out I had an incorrect header, I had this error in the console: `Error: Header name must be a valid HTTP Token`. Seems like that error should be displayed to the user?

**Comment by lvian** [comment] 2017-11-28 16:40
Was having the same problem using the Windows App accessing a linux server running on vagrant.

Had to ditch the windows app and use the browser version, working like a charm now.

**Comment by a85** [comment] 2017-12-11 14:49
Closing this issue as there might be multiple reasons for this request to not work. Does not seem to be a particular problem with the postman-runtime.

**Closed as completed by a85** 2017-12-11 14:49 UTC

**Comment by Rylai-Zihang** [comment] 2018-01-10 08:03
How about error"Error: socket hang up" in console view of postman?
I've tried to turn off SSL but not work.
I visited by IP.
My backend is OK.

**Comment by haraujo83** [comment] 2018-04-04 11:49
hi. i'm having the same problem... 
when i use a different port, it show error "Could not get any response"
my postman version is the newest (6.0.10 - windows)
the chrome app version it works fine for me

**Comment by BobGerman** [comment] 2018-04-11 00:25
Turning off SSL certificate validation worked for me (debugging w/VS2017 ASP.NET Core 2.0)

**Comment by ShabbirGithub** [comment] 2018-05-10 16:17
I had envronment variables 'http_proxy' and 'https_proxy' that were preventing me to get to localhost. Removing the environment variables did the trick.

**Comment by seabamirum** [comment] 2018-05-10 18:36
I have SSL certificate validation off, but it still didn't work. Changing localhost to [::1] (whatever that means) fixed it.

**Comment by baibhavtripathi** [comment] 2019-04-04 06:14
I was having this same issue on Mac postman, Version 7.0.7 (7.0.7). 

'/'  at the end in requests, did the job for me.

**Comment by haugstve** [comment] 2019-11-27 10:45
I tested today using netcat on mac:
`nc -lk localhost 3000`

In chrome, requests are printed when I write 
`localhost:3000`
`http://[::1]:3000/`

Postman only works when using
`[::1]:3000`
when writing 
`localhost:3000`
I get errors (not the same for all requests even if they are identical). Once it actually worked(not able to reproduce). I think the different errors and results might be correlated with chrome doing requests at the same time but my understanding of this is rudamentary. 

The two errors are
`Error: write EPIPE`
`Error: connect ECONNREFUSED 127.0.0.1:3000`

**Comment by yogiiiii26** [comment] 2020-03-13 14:56
When I'm trying to use POST operation through local host server. It is not connecting to the server and showing the following error : There was an error connecting to http://localhost:4500/api/user/signup

Can someone please help here?

![image](https://user-images.githubusercontent.com/61676728/76632236-e4ed9100-6568-11ea-922a-d9159346bfa7.png)

**Comment by airs0urce** [comment] 2020-03-13 15:13
@yogiiiii26 So, when you open this URL in browser it works?
http://localhost:4500/api/user/signup

but when you request it in Postman it doesn't?
May be you blocked network for Postman in firewall settings.

**Comment by yogiiiii26** [comment] 2020-03-13 15:34
Hi @airs0urce thanks for the suggestion but after doing this also the error is still the same.

**Comment by Gitanjali86** [comment] 2021-05-11 18:36
Hi ! Can I have solution for this localhost issue plssss?
I am able to access via chrome browser but not via Postman.
https://localhost:8080/
I am using V8.4.0

**Comment by krishna066** [comment] 2022-07-04 07:34
postman is not able to connect to localhost:3000.
disabled SSH and proxy in settings, but no luck.
It's loading continuously, not even showing any error.

Postman version:9.23.3
System used: Mac

**Comment by shubhbhargav** [comment] 2022-07-06 19:04
@krishna066 Are you able to access the above url via any other method? I am assuming that you are using the desktop version of Postman (not web). Let me know if that's not the case.

@Gitanjali86 Can you please share a screen recording of the issue? It will help us debug the issue further.

**Comment by krishna066** [comment] 2022-07-07 07:19
Hi @shubhbhargav, I'm using the desktop version and my issue got fixed after I downgraded the node version in my machine.

Thank You.
