### ISSUE TITLE
PR merge shows resolve conflicts before but none are shown in the UI

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#9780] opened 2021-03-30 06:41 UTC
Filed on behalf of user.

We have a PR and the Postman tool is saying we have a conflict that must be solved before merging. However, we can't see any conflicts (check screenshot attached) and the merge button is blocked. if we try to pull changes we get "Resolve the active conflicts in the diff"

**Comment by Davi-DeGanne** [comment] 2021-04-01 18:13
This has been pretty disastrous for our team, we have 5+ "feature branch" forks that we can't merge into the main test collection at all, for no apparent reason; the entire "pull request" feature has been rendered non-functional.

![postman merge failure](https://user-images.githubusercontent.com/10736422/113336272-62ef1800-92e3-11eb-8d19-9eaf853218d4.png)

**Comment by ShukujiNeel13** [comment] 2022-06-22 08:59
Had a similar issue, in my case this is due to manually changing the Variables in the original and fork.
---

**Postman client / app Details:**
Version: 9.21.3
UI Version: 9.21.3-ui-220609-0642
Desktop Platform Version: 9.19.0 (9.19.0)

**OS Details:**
macOS Catalina
10.15.7
---

This blocker happens when trying to creating the PR in the fork where it shows the conflict, and asks to pull the changes from the original 
A status message shows on top which says something like: 
`The original was updated since last... please pull the changes before...`

A screenshot of the conflict showing in the app attached below.

From what can be seen in the screenshot the names of the variables have become jumbled up somewhere - perhaps in the synced version and are not getting updated even after making the manual changes.

Even though I ensured that in the fork, the variables order and names matches that of the source collection,
but still this conflict still remains.

---

Since below workaround has already solved my problem, 
I am curious if the: "Clear Cache and Reload" option under "Help"  solves this issue.
In case this works for anyone, do update us.

#### A workaround

👍 This helped in my case, since I wanted to merge a few additions from single fork into the original collection.
👎 May not be so easy or work for complex situations like the one in comment above ☝️ 

**Steps for the workaround:**
1. Export the fork and the original collections to file (for backup)
2. Duplicated the fork
3. Deleted the fork (and the original collection, if you may)
4. Treat duplicate of the fork as the new original collection5. 
---

#### Reflecting how this issue could have happened:
🤔
I believe this could have happened due to **following journey of steps:**
(Assume that I pressed save after every step)

1. Forked from original collection
2. Made changes in the fork.
3. Changed the variable names and / or order in the original collection
4. In the fork, Try to merge / create pull request, found out there is conflict in variables
5. In the fork, change the variable names and / or order to match that of the original collection (hoping manual update will resolve the conflict)
6. In the fork, try to merge / create pull request again, this conflict keeps showing up and never goes away (even after closing the application, system shutdown and future use) 😞 
---

The screenshot:
<img width="1262" alt="Postman merge conflict due to Variables" src="https://user-images.githubusercontent.com/17528652/174988806-eecd2051-697b-426c-b9b4-6a2de97a20f9.png">

**Comment by ankitjaggi** [comment] 2022-06-24 05:40
Hey @ShukujiNeel13! Would it be possible for you to share the involved collection or the Pull Request IDs with us over an email to [help@postman.com](mailto:help@postman.com)? This will help us in better debugging the issue.

**Comment by ShukujiNeel13** [comment] 2022-06-24 11:47
Unfortunately I had already applied the workaround and deleted the affected
collection.
If you review my comment again you may be able to reproduce the issue with
the steps I mentioned.

**Comment by ankitjaggi** [comment] 2022-11-10 09:01
Closing this issue for now. Feel free to create a new issue if the issue persists.

**Closed as completed by ankitjaggi** 2022-11-10 09:01 UTC
Labels: bug, product/version-control
