### ISSUE TITLE
19-bit Long type digital precision lost

### ISSUE THREAD

**Issue by Mr-LiuDC** [a85/POSTMan-Chrome-Extension#7623] opened 2019-11-12 10:54 UTC
**Describe the bug**
Here is a problem that seems to exist in all JavaScript libraries. My ID is a 19-bit Long number generated by the Snowflake algorithm. When I click on the Beauty button, it also loses precision when it beautifies my Json.

**To Reproduce**
1. Open Postman and send a request，POST or PUT.
2. The parameter is row body like below：
```
{
    "startTime": 1571714270409,
    "userId": 1192715994825625600,
    "assessmentProcessId": 1194137245683023872,
    "assessmentDataDetails": [
        {
            "assessmentId": 1191185031834370048,
            "dataType": [
                "questionnaire"
            ],"questionnairePostData": [
                {
                    "questionnaireId": 1191185031880507392,
                    "tag": {
                        "squatOnTheWallCount": "115"
                    }
                }
            ],
            "heartRates": [
              
            ]
        }
    ]
}
```
3. When I click the beauty button，the row body has changed, Looking at assessmentProcessId and assessmentId，it lost precision.
```
{
    "startTime": 1571714270409,
    "userId": 1192715994825625600,
    "assessmentProcessId": 1194137245683024000,
    "assessmentDataDetails": [
        {
            "assessmentId": 1191185031834370000,
            "dataType": [
                "questionnaire"
            ],
            "questionnairePostData": [
                {
                    "questionnaireId": 1191185031880507400,
                    "tag": {
                        "squatOnTheWallCount": "115"
                    }
                }
            ],
            "heartRates": []
        }
    ]
}
```

**Expected behavior**
Expect digital precision not to be lost.

**App information (please complete the following information):**
 - Postman Version 7.11.0 win32 10.0.16299 / x64
 - OS: Windows 10 Professional

**Comment by shamasis** [comment] 2019-11-16 18:09
Yep. That’s right. We currently need to parse the JSON to beautify and underlying limitations of number precision gets in the way here. 

We are working towards solving this. cc @kamalaknn @postmanlabs/runtime

**Comment by codenirvana** [comment] 2019-11-19 05:37
Duplicate of #5658

**Closed as completed by codenirvana** 2019-11-19 05:37 UTC
Labels: bug, response-rendering, product/runtime
