### ISSUE TITLE
Incorrect Response in VS Code Extension vs Postman App

### ISSUE THREAD

**Issue by ritvij-saxena** [a85/POSTMan-Chrome-Extension#13302] opened 2024-11-28 23:21 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I created a Flask API project that was designed to update the points for a user each time a request was made. On each request, the points for a specific user (`user123`) were incremented by a fixed value. The updated points were then returned in the response. The database used here is in-memory in nature (python dictionaries.). This project was made for learning purposes, local development only.  In the Postman app, the points value increased as expected (e.g., `17`, `34`, `51`). However, when using the VS Code extension, the response always returned `17`, despite the server-side update being logged correctly.  (Please see the screenshots)

### Steps To Reproduce

1. Download this zip [Q1.zip](https://github.com/user-attachments/files/17952817/Q1.zip)

2. Run the flask app with command `python3 main.py`
3. Trying making a `POST` request to url `http://127.0.0.1:5000/api/validate-receipt` on both VSCode and Postman app.

### Screenshots or Videos

Postman VSCode Extension(v1.5.0): <img width="1030" alt="Screenshot 2024-11-28 at 6 03 31 PM" src="https://github.com/user-attachments/assets/250f74fb-2470-4a37-bb4e-d9fc39095379">

<img width="1034" alt="Screenshot 2024-11-28 at 6 20 01 PM" src="https://github.com/user-attachments/assets/c755e0ef-a0bc-4491-bd6b-25f2c650b68e">

Postman App (v 11.18.0):
<img width="1130" alt="Screenshot 2024-11-28 at 6 03 50 PM" src="https://github.com/user-attachments/assets/3c55f0f3-a018-498c-ae66-3275ad533987">

<img width="287" alt="Screenshot 2024-11-28 at 6 19 41 PM" src="https://github.com/user-attachments/assets/730ed70a-7d36-4990-a1eb-6fc911e958c1">

### Operating System

macOS

### Postman Version

11.18.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by amaldinesh7** [comment] 2024-11-29 06:22
Duplicate of #13230

**Closed as completed by amaldinesh7** 2024-11-29 06:22 UTC
Labels: bug, vscode
