### ISSUE TITLE
UI input control for Query params works the wrong way with partial text selection or partial remove

### ISSUE THREAD

**Issue by asartem** [a85/POSTMan-Chrome-Extension#8018] opened 2020-02-07 16:13 UTC
**Describe the bug**
When I try to select the part of the value\name in QuryParams input control, it stops to select the text and starts to drow a mouse "Select Many" square. Or it can even don't select the text if the focus was not set on this control with an additional click. Or can remove all text instead of a selected part

**To Reproduce**
1. Go to  Request
2. Add some text value, for example, "ThisIsALongText" to QueryParams input control (name or value)
3. Focus on some other control
4. Make standard quick edit actions: 
 4.1 Mouse hover on text to select part "Long"
 4.2  Click and hold LMB to select 
 4.3 Move mouse. Maybe leave input control holding LMB.
 4.4. Thumb off the LMB to let the mouse select text.
5. Additional: Click Delete keyboard button to remove

**Expected behaviour**
The text "Long" selected and then removed

**Actual**
The focus was lost, text not selected, not removed

**Screenshots**
![Capture](https://user-images.githubusercontent.com/3481430/74045467-a53bf400-4981-11ea-9f15-d20719fa6980.PNG)

**App information (please complete the following information):**
 -  Native Desktop App
 - Postman Version  7.17.0
 - Windows 8.1 with latest updates

**Additional context**
This input control almost not tested and doesn't work correctly with basic text editing like the partial selection, partial remove\edit or little bit advanced scenarios like the focus is on the different elements and so on. I'm sure that you'll find more cases with bugs when you'll test it.

**Comment by kamalaknn** [comment] 2020-02-11 02:23
Hey @asartem 

This looks like a duplicate of #5078. I'm closing this issue. Please follow the original thread for updates. Do let us know if you have additional info.

**Closed as completed by kamalaknn** 2020-02-11 02:24 UTC
Labels: bug, data-editor
