### ISSUE TITLE
Error while importing: format not recognized

### ISSUE THREAD

**Issue by christianbaumann** [a85/POSTMan-Chrome-Extension#4588] opened 2018-05-22 14:02 UTC
**Describe the bug**
Importing files via the IMPORT-function fails, even with the provided examples from https://www.getpostman.com/docs/v6/postman/collection_runs/working_with_data_files

**To Reproduce**
1. Click the import button
2. Select your data file (eg. the one downloaded from the [postman tutorial](https://www.getpostman.com/docs/v6/postman/collection_runs/working_with_data_files): [58702574.csv](https://s3.amazonaws.com/postman-static-getpostman-com/postman-docs/58702574.csv)
3. Click Import

**Expected behavior**
The file should be imported.

**Actual behaviour**
I get an error message: "Error while importing: format not recognized"

**App information (please complete the following information):**
 - Native app
 - Postman Version 6.0.10
 - OS: Windows 8

**Comment by vkaegis** [comment] 2018-05-23 13:32
@christianbaumann Thanks for reporting this! I could reproduce this on my end, we'll take a look and update this thread.

**Comment by harryi3t** [comment] 2018-05-23 13:40
@christianbaumann Data files are not supposed to be imported but instead are used when running a collection.
![image](https://user-images.githubusercontent.com/5207331/40427973-d65ea2c8-5ebc-11e8-896f-a066ab76f6ba.png)

We will update our docs to remove this confusion

**Comment by yavgel** [comment] 2018-06-22 09:51
The issue still exists!!!!
Version 6.1.3 (6.1.3) - the latest one on for Mac OS
@harryi3t - Why did you close it?
at least update you `docs`.

**Comment by Anupam2303** [comment] 2018-06-24 15:03
Yes Issue still exist on mc os

**Comment by vkaegis** [comment] 2018-06-30 13:57
@yavgel @Anupam2303 Apologies for the confusion here. As @harryi3t mentioned, the CSV file was meant to be selected in the Runner, and not imported in Postman using the Import button. This seems to be a misdirection in our documentation, so reopening this until that is fixed.

**Comment by dhirajmobikwik** [comment] 2018-10-04 16:07
@vkaegis, the issue is still reproducible. I am still unable to import the file from import option in native Postman app.

**Comment by harryi3t** [comment] 2018-10-04 18:24
We have updated our docs to reflect this information. 
@dhirajmobikwik As mentioned in docs page, csv files are **not supposed to be imported**.
<img width="817" alt="working_with_data_files" src="https://user-images.githubusercontent.com/5207331/46494570-d017b480-c830-11e8-83bd-f385f6b63b1c.png">

**Closed as completed by harryi3t** 2018-10-04 18:24 UTC
Labels: bug, postman-docs
