### ISSUE TITLE
Cookie option (link/button) not available in my postman app

### ISSUE THREAD

**Issue by rajiv3444** [a85/POSTMan-Chrome-Extension#3307] opened 2017-07-25 06:55 UTC
## Cookie option is not available in my postman:

Cookie option is not available in my postman. Hence I am unable to use this option to deal with cookie.

**Comment by kamalaknn** [comment] 2017-07-25 07:06
Hey @rajiv3444,

The Cookie management options are only available on the native applications. Could you verify if you are on the Native applications or the Chrome App?

The "How can I tell if I’m on the Postman Chrome app or Postman native app?" section in [this blog](http://blog.getpostman.com/2017/03/14/going-native/) will help you identify your app. 

If you want to use Cookie management options you can switch to the native apps. The download links are also available on the same blog.

I'm closing this as this is not a bug with the Postman App itself. Feel free to continue discussion here.

Thanks.

**Closed as completed** 2017-07-25 07:07 UTC

**Comment by rajiv3444** [comment] 2017-07-26 11:41
Hi @kamalaknn 
Thank you for your quick response.
Yes, I could see the cookie option available on native app.

Thanks
