### ISSUE TITLE
Manage Environments window needs to be able to be re-sized

### ISSUE THREAD

**Issue by thetreythomas** [a85/POSTMan-Chrome-Extension#5891] opened 2019-02-07 00:47 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem, just a "Quality of Life" improvement to Postman.

This is somewhat related to #3493.

**Describe the solution you'd like**
#3493 asks for the ability to move the Manage Environments window.

To add to this, the modals should not only be movable, but able to be re-sized.

For this one particular environment, I am testing API calls against 20 hard drives. The current view can only show the title bar, and then 10 variables. It would be nice to change the size to see as much as I can.

**Describe alternatives you've considered**
There aren't any.

Native App
Postman v6.7.3
Windows 10

**Comment by numaanashraf** [comment] 2019-02-07 05:57
Thanks for the suggestion @thetreythomas. We are tracking this at #3493. Please follow that thread for updates.

**Comment by numaanashraf** [comment] 2019-02-07 05:57
Duplicate of #3493

**Closed as completed by numaanashraf** 2019-02-07 05:57 UTC
Labels: duplicate
