### ISSUE TITLE
Postman crashes on large data POST to REST Service.

### ISSUE THREAD

**Issue by ethai** [a85/POSTMan-Chrome-Extension#2479] opened 2016-11-20 09:03 UTC
1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Win7
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Encountered this recently due to first time usage of such huge POST of data.
 6. Expected behaviour:  POST to REST service was successful, however, I would get an alert of the app crashing with a balloon asking to restart.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

POST request with an extra large dataset. In my case I was POST to elasticsearch using the bulk API with ball park guestimate probably 9 mb worth of data in the body.  

I can readily reproduce so please let me know how to go about collecting any debug logs you may need.

**Comment by sdnts** [comment] 2016-11-22 09:08
@ethai Could you try out your endpoint with our native apps? The native apps run on top of Postman Runtime, which can handle large file uploads a lot easier.
You can download our native apps, based on your platform, [here](https://getpostman.com/apps)

**Comment by ethai** [comment] 2016-11-24 06:46
@madebysid , i tried teh native app now although it's not crashing on me the POST never seems to complete so all i'm left with is Loading....Cancel Request option.

**Comment by ethai** [comment] 2016-11-24 07:01
i can see from the postman console log that the requests is actually successful and that it shows completion time of 28secs with 200 OK yet the Builder screen is still stuck on Loading...Cancel Request.  here's a screenshot
![native-postman-output-large-requests](https://cloud.githubusercontent.com/assets/6053873/20589353/c73cb414-b1d0-11e6-9179-fa6842cf6302.JPG)

**Comment by vegetableman** [comment] 2016-11-24 07:12
@ethai Thanks for sharing the screenshot 👍 . Could you also share a screenshot of the devtools on the native app (`View -> Show Devtools` or `Cmd  + Alt + I`), for us to check if there are any errors?

**Comment by ethai** [comment] 2016-11-24 07:24
yup as you expected some error shown

![storage-error](https://cloud.githubusercontent.com/assets/6053873/20589834/e7194e2a-b1d3-11e6-9a79-2fc3f712c26d.JPG)

**Comment by ethai** [comment] 2016-11-24 07:24
![fullerror](https://cloud.githubusercontent.com/assets/6053873/20589862/09611fe4-b1d4-11e6-811a-09f7ef406b5f.JPG)

**Comment by vegetableman** [comment] 2016-11-24 08:17
@ethai Thanks for sharing the screenshot. The fix will be out in the upcoming release (which will be out in a few days). 

The issue is due to storing the request data from the api call on the app `localstorage`. As a workaround, until the next release, could you run this code on the devtools console `pm.settings.setSetting('lastRequest', null)`  which would clear out the request made.

Thanks ^_^.

**Comment by ethai** [comment] 2016-11-26 00:51
I tried that temporary workaround, but doesn't appear to do anything.  I'll await for the next build to try.

**Comment by sdnts** [comment] 2016-12-02 14:03
@ethai We just released a new version (4.9). Can you update and see if large files are still causing issues for you?

**Comment by ethai** [comment] 2016-12-02 14:27
let me give it a try and get back to you.

**Comment by ethai** [comment] 2016-12-02 15:38
@madebysid , are you alluding to the native app or the chrome ext to retest with?

**Comment by ethai** [comment] 2016-12-02 15:41
@madebysid , disregarding updating native app and testing now.

**Comment by ethai** [comment] 2016-12-02 22:02
@madebysid , certainly 4.9 has addressed the initial problem but now the issue is once such large request has been completed the entire UI is unresponsive and basically crashes.  The only thing i can do is kill the process from task manager.

**Comment by vegetableman** [comment] 2016-12-03 05:14
@ethai Thanks for updating to 4.9 👍 . The initial issue has been fixed for both the apps. Could you clarify whether the crash happens before the response is displayed or after?

**Comment by ethai** [comment] 2016-12-03 05:16
@vegetableman , the crash / unresponsiveness happens after the response is displayed.  It's readily reproducible as i've tried it repeatedly with having to kill via task manager every time.

**Comment by elmojo** [comment] 2017-01-23 17:39
I can also confirm the crash/unresponsiveness for a large response.  It seems to occur if the returned data is over ~15MB.

The data will display but shortly afterward the window goes white and becomes unresponsive.  I then have to close the application.

**Comment by valamelkor** [comment] 2017-09-13 10:07
Same issue here. Postman hangs up with responses over 15mb

**Comment by obenshaindw** [comment] 2017-09-14 20:42
I am having a similar issue posting a 38 MB CSV file (88298 lines) as raw data. Postman readily returns a response from the service; however the application then crashes and becomes unresponsive. 

I thought this might have to do with the postman Sync feature so I disabled it. Then copy/pasted my 38MB of text, saved, and ran my request.  With the Sync feature disabled, it works as expected.

**Comment by saswatds** [comment] 2019-07-03 16:01
Hello everyone, we are tracking this issue here https://github.com/postmanlabs/postman-app-support/issues/4751
As stated in one of the comments https://github.com/postmanlabs/postman-app-support/issues/4751#issuecomment-501420752 we have pushed a lot of performance fixes to our canary app. 

Will be closing this issue as Duplicate and would want everyone to follow https://github.com/postmanlabs/postman-app-support/issues/4751

**Closed as completed by saswatds** 2019-07-03 16:01 UTC
Labels: bug, performance, product/runtime
