### ISSUE TITLE
there is no change feature for shortcuts

### ISSUE THREAD

**Issue by Vladinho10** [a85/POSTMan-Chrome-Extension#6274] opened 2019-04-11 05:44 UTC
I use Postman 7.0.7
Please add feature ! It's too necessary shortcut edit-ability .
![postman](https://user-images.githubusercontent.com/33626746/55933527-a8216780-5c3e-11e9-8d29-7a95e7d3b173.png)

**Comment by numaanashraf** [comment] 2019-04-11 15:01
Duplicate of #2096

**Closed as completed by numaanashraf** 2019-04-11 15:01 UTC
