### ISSUE TITLE
Postman incorrectly read the values in CSV file (modified the value)

### ISSUE THREAD

**Issue by j-c17** [a85/POSTMan-Chrome-Extension#9073] opened 2020-09-18 05:37 UTC
**Describe the bug**
Postman can read my csv file but incorrectly read the value (the value is modified by Postman).

**To Reproduce**
1. Prepare csv file as described in https://blog.postman.com/looping-through-a-data-file-in-the-postman-collection-runner/
2. Click Runner -- Collection Runner window will appear
3. Choose the request that we want to run
4. In Data : Select File , click the button and select the csv file that we want to use 
5. Click Preview --- We can see the csv data read by Postman is somehow modified (the second column , the last 3 digit, Postman read it as "000" , instead of "620").  Open the csv file using notepad++ and compare it with Postman's preview (snapshot provided below).
6. Run the runner. I can see Postman is feeding the request with wrong data (with the last 3 digits "000" , instead of "620")

**Expected behavior**
Postman should read the value in csv file as it is and do not modify the value.

**Screenshots**
![Postman Issue](https://user-images.githubusercontent.com/28582666/93559986-1f7f2d00-f9d5-11ea-92d4-48dbd051a925.jpg)

**App information (please complete the following information):**
 - Postman for Windows
 - Postman v7.32.0 
 - OS: Windows 10 

**Additional context**

**Comment by DannyDainton** [comment] 2020-09-18 05:47
Hey @j-c17

This might help to understand why that number gets converted:

https://github.com/postmanlabs/postman-app-support/issues/9065

**Comment by vikiCoder** [comment] 2020-09-21 12:45
Closing this as a duplicate of this feature request: https://github.com/postmanlabs/postman-app-support/issues/6746

See this comment for a possible workaround: https://github.com/postmanlabs/postman-app-support/issues/6798#issuecomment-506642247

**Closed as completed by vikiCoder** 2020-09-21 12:45 UTC
Labels: data-file/csv, product/runtime
