### ISSUE TITLE
Terminal Console as a pane and not an external window

### ISSUE THREAD

**Issue by agiguere** [a85/POSTMan-Chrome-Extension#5272] opened 2018-09-27 21:32 UTC
If would be nice to have the terminal console for logs as a pane and not as an external windows to avoid back and forth between the 2 windows

thanks

**Comment by sivcan** [comment] 2018-09-28 10:11
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3700

**Closed as completed by sivcan** 2018-09-28 10:11 UTC
