### ISSUE TITLE
OAuth 2 implicit grant flow ends in error

### ISSUE THREAD

**Issue by santhoshanna** [a85/POSTMan-Chrome-Extension#4775] opened 2018-07-04 15:10 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When initiating OAuth2 implicit grant flow, a pop-up comes up from Azure AD to enter email id, once done entering, it results in an error. The console also shows "Error" & "Unsupported response type"

**To Reproduce**
1. Go to  AUthorization tab in a request and select OAuth 2.0 as type
2. Enter all the details as seen below
![image](https://user-images.githubusercontent.com/9366313/42284329-d8cf8ea2-7f71-11e8-8447-5454bc34f829.png)
3. See error
![image](https://user-images.githubusercontent.com/9366313/42284431-18cf9eca-7f72-11e8-9af1-e893b94bfee3.png)
![image](https://user-images.githubusercontent.com/9366313/42284453-2d264a22-7f72-11e8-96f2-85f2160927b9.png)
![image](https://user-images.githubusercontent.com/9366313/42284472-380a5e60-7f72-11e8-8613-dd85f47763ac.png)

**Expected behavior**
The OAuth2.0 implicit grant flow should complete successfully

**Screenshots**
It has been attached above

**App information (please complete the following information):**
 - Postman Version - 6.1.4
 - Windows 7

**Comment by harryi3t** [comment] 2018-07-04 15:20
@santhoshanna Can you also check the dev console (view -> developer -> Show devTools (current view)) for any errors and post it here?
Also, try changing the dropdown `client authentication` to header instead of body.

**Comment by santhoshanna** [comment] 2018-07-04 17:08
@harryi3t 
![image](https://user-images.githubusercontent.com/9366313/42288965-ac0a0eae-7f82-11e8-805e-7ac4de193662.png)
attached is the dev console capture with "client authentication" set to "send as basic auth header" as adviced

**Comment by harryi3t** [comment] 2018-08-01 09:32
@santhoshanna From the logs, it looks like the server does not support the `Implicit` grant type.


![42288965-ac0a0eae-7f82-11e8-805e-7ac4de193662 png 1917x420 2018-08-01 15-01-36](https://user-images.githubusercontent.com/5207331/43513599-cf02d7fe-959b-11e8-8aec-036cbe5ea35e.png)

Can you confirm this (check the docs for the relevant auth provider)?

**Comment by harryi3t** [comment] 2019-01-11 12:45
@santhoshanna Closing this since it looks like the issue is with the Oauth2 provider itself and that it does not support implicit grant type.
Feel free to re-open if that is not the case.

**Closed as completed by harryi3t** 2019-01-11 12:45 UTC
Labels: support, OAuth2

**Comment by ansaryansu** [comment] 2019-06-03 12:36
Enable "oauth2AllowImplicitFlow" in the client application manifest.

**Comment by javolek** [comment] 2019-07-10 14:17
> @santhoshanna Closing this since it looks like the issue is with the Oauth2 provider itself and that it does not support implicit grant type.
> Feel free to re-open if that is not the case.

OpenID Connect defines also `id_token` as response type for an implict flow. Could it be also supported?

**Comment by Burnett01** [comment] 2019-12-20 23:32
Can confirm. OpenID Connect defines an id_token as a response type for implicit flows. I can't use Postmans Access-Token feature because it uses a hardcoded response_type. Having an option to override this would be good.

**Comment by jackielii** [comment] 2020-01-24 12:39
OIDC defines that in the implicit grant, for response_type, if token is specified, either id_token or code must be specified: https://openid.net/specs/openid-connect-core-1_0.html#Authentication

![image](https://user-images.githubusercontent.com/360983/73069787-91cf5a00-3ea6-11ea-895d-798719ebca70.png)

**Comment by JCPuerto** [comment] 2020-05-11 22:49
Hi @Burnett01, do you know if there's another thread for the hardcoded response_type problem? Thank you!

**Comment by albertoVieiraNeto** [comment] 2022-03-05 10:23
will postman ever fix this? oidc/implicit is a pretty standard login flow.

**Comment by itpropro** [comment] 2023-12-05 22:21
@harryi3t the bug that postman uses `token` instead of `id_token` exists for over 3 years, any timeline on a fix? Overwriting the parameter in the advanced section does unfortunately not work...
