### ISSUE TITLE
Suggest a way to add external javascript libraries which is not supported by Postman 

### ISSUE THREAD

**Issue by LalithVigneshS** [a85/POSTMan-Chrome-Extension#6148] opened 2019-03-25 13:13 UTC
1.For example i am trying to use the "Twilio" library in my code. But i dont know how to proceed further.

2.Suggest me a workaround to solve this.

**Comment by codenirvana** [comment] 2019-03-25 14:25
Closing as duplicate of #1180

**Closed as completed by codenirvana** 2019-03-25 14:25 UTC
