### ISSUE TITLE
If header name is incorrect in single REST call and then corrected, an error will still be thrown when running collection

### ISSUE THREAD

**Issue by roslowry** [a85/POSTMan-Chrome-Extension#7957] opened 2020-01-24 18:13 UTC
*****PREFACE******
I believe the below details should be sufficient for replicating and resolving this bug. I will not be closely following this thread, as I have found that restarting Postman solves the problem at hand, though you are welcome to reach out to me if you want. 

**Describe the bug**

If header name is incorrect in single REST call and then corrected, the request will succeed. However, if the user runs the parent collection of that single REST call, the same "invalid name" error will occur. This issue no longer occurs when restarting Postman. 

**To Reproduce**
1. Create a draft request of any kind 
2. Add headers for 'X-Client-DN' and X-Issuer-DN' 
2a. Add corresponding values for these fields, but make sure one of them has a duplicative comma (if you are unfamiliar with these headers, I believe they are Citrix fields and more information my be available here or elsewhere on Google (https://support.citrix.com/article/CTX123075). 

An example value for X-Client-DN could be something like the following (I needed to redact the original one): C=US,CN=User_A,L=Orlando,O=Testing Group,OU=Somewhere,ST=FL
An example value for X-Issuer-DN could be something like the following (again, I redacted the original I used): CN=Company A, OU=MyProject, O=Awesome Company\, Inc., L=Orlando, ST=Florida, C=US

3. Remove the backslash for "Awesome Company\,Inc" noted in the "X-Issuer-DN" example part 2a above
4. Send a request, and see it fail (a Java/Apache server will  note "Invalid Name: xxx"
5. Add the backslash back into the request (see it run correctly when trying the request again)
6. Run the entire parent collection. The same "Invalid Name" error will occur for the original request. 

**Expected behavior**
After correcting an incorrectly named header, such as X-Issuer-DN, the request should successfully run both at the individual request level (which happens) and at the collection level (which does not happen)

**App information (please complete the following information):**
 - App Type: Locally installed version of Postman
 - Postman Version: 7.16.0
 - OS: macOs

**Comment by shamasis** [comment] 2020-03-22 19:29
This could be because changes are not reflected while one runner window is still open. Thanks for reporting.

**Comment by vikiCoder** [comment] 2020-04-16 14:14
Hi @roslowry,

I tried to reproduce your problem but had no success. When I updated the header of a request and retried the request in the runner, it sent the updated header as expected. Although one thing to note here is that while sending a request from the runner, it sends the saved version of that request, not the unsaved changes to that request in request editor. So it could be happening to you because you might have forgotten to save the changes to request before sending it. Please let us know if it is still happening to you.

**Comment by codenirvana** [comment] 2020-05-29 20:48
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-05-29 20:48 UTC
Labels: bug, collection-runner, blocked/need-info, product/runtime
