### ISSUE TITLE
Missing icon app

### ISSUE THREAD

**Issue by Gustana** [a85/POSTMan-Chrome-Extension#4921] opened 2018-07-30 14:12 UTC
Describe the bug
After i open postman, the icon on the taskbar is missing, its like '.txt' icon

To Reproduce
1. Open postman app
2. See the icon of postman app

Expected behavior
The icon on the task bar shouldn't like '.txt' icon

Screenshots
![screenshot_1](https://user-images.githubusercontent.com/23212456/43402480-686a6888-9445-11e8-9eee-0550ad8ba1fc.png)

App information
 - Postman Version 6.2.2
 - OS: Windows 10 Home

**Comment by SamvelRaja** [comment] 2018-07-31 08:43
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4814

**Closed as completed by SamvelRaja** 2018-07-31 08:43 UTC
