### ISSUE TITLE
Exception Report: Could not write content: JsonObject

### ISSUE THREAD

**Issue by mikezang** [a85/POSTMan-Chrome-Extension#8700] opened 2020-06-23 08:36 UTC
**Describe the bug**
When I response Microsoft Graph API result as below:
..
IEventCollectionPage eventPage = graphClient.users(email).events().buildRequest(requestOptions).select("subject,body,bodyPreview,organizer,attendees,start,end,location").get();
List<Event> eventList = eventPage.getCurrentPage(); .
return eventList;
...
I got error message:
HTTPステータス 500 - Internal Server Error
Type Exception Report

メッセージ Could not write content: JsonObject (through reference chain: jp.co.smfl.nile.models.ApiResult["data"]->java.util.UnmodifiableRandomAccessList[0]->com.microsoft.graph.models.extensions.Event["rawObject"]->com.google.gson.JsonObject["asString"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: JsonObject (through reference chain: jp.co.smfl.nile.models.ApiResult["data"]->java.util.UnmodifiableRandomAccessList[0]->com.microsoft.graph.models.extensions.Event["rawObject"]->com.google.gson.JsonObject["asString"])

説明 The server encountered an unexpected condition that prevented it from fulfilling the request.

例外

org.springframework.http.converter.HttpMessageNotWritableException: Could not write content: JsonObject (through reference chain: jp.co.smfl.nile.models.ApiResult["data"]->java.util.UnmodifiableRandomAccessList[0]->com.microsoft.graph.models.extensions.Event["rawObject"]->com.google.gson.JsonObject["asString"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: JsonObject (through reference chain: jp.co.smfl.nile.models.ApiResult["data"]->java.util.UnmodifiableRandomAccessList[0]->com.microsoft.graph.models.extensions.Event["rawObject"]->com.google.gson.JsonObject["asString"])
	org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:276)
	org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:100)
	org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:222)
	org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:153)
	org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:165)
	org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	jp.co.smfl.ng.managers.spi.DefaultMaintenanceManagerFilter.doFilter(DefaultMaintenanceManagerFilter.java:41)
	jp.co.smfl.ng.securities.TwoFactorAuthenticationFilter.doFilter(TwoFactorAuthenticationFilter.java:164)
	jp.co.smfl.ng.securities.FormAuthenticationFilter.doFilter(FormAuthenticationFilter.java:280)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
原因

com.fasterxml.jackson.databind.JsonMappingException: JsonObject (through reference chain: jp.co.smfl.nile.models.ApiResult["data"]->java.util.UnmodifiableRandomAccessList[0]->com.microsoft.graph.models.extensions.Event["rawObject"]->com.google.gson.JsonObject["asString"])
	com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:199)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:683)
	com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1387)
	com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:889)
	org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:269)
	org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:100)
	org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:222)
	org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:153)
	org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:165)
	org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	jp.co.smfl.ng.managers.spi.DefaultMaintenanceManagerFilter.doFilter(DefaultMaintenanceManagerFilter.java:41)
	jp.co.smfl.ng.securities.TwoFactorAuthenticationFilter.doFilter(TwoFactorAuthenticationFilter.java:164)
	jp.co.smfl.ng.securities.FormAuthenticationFilter.doFilter(FormAuthenticationFilter.java:280)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
原因

java.lang.UnsupportedOperationException: JsonObject
	com.google.gson.JsonElement.getAsString(JsonElement.java:192)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
	com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:654)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1387)
	com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:889)
	org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:269)
	org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:100)
	org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:222)
	org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:153)
	org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:165)
	org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	jp.co.smfl.ng.managers.spi.DefaultMaintenanceManagerFilter.doFilter(DefaultMaintenanceManagerFilter.java:41)
	jp.co.smfl.ng.securities.TwoFactorAuthenticationFilter.doFilter(TwoFactorAuthenticationFilter.java:164)
	jp.co.smfl.ng.securities.FormAuthenticationFilter.doFilter(FormAuthenticationFilter.java:280)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
注意 原因のすべてのスタックトレースは、のログに記録されています

Apache Tomcat/7.0.96

**Expected behavior**
A Json result should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1030268/85380525-fdae0f80-b577-11ea-8ada-fca2f42bd10e.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.26.1]
 - OS: [Windows7]

**Additional context**

**Comment by mccannt** [comment] 2020-06-23 23:05
@mikezang Can you give us some more information on this issue?
How can we replicate this? What steps are you doing?

**Comment by mikezang** [comment] 2020-06-24 01:14
To replicate this issue, you need to use Microsoft Graph SDK by gradle as below:
>
     repositories {
        jcenter()
    }
    dependencies {
        compile 'com.microsoft.azure:msal4j:1.6.1'
        compile 'com.microsoft.graph:microsoft-graph:1.8.0'
        compile 'org.slf4j:slf4j-nop:1.8.0-beta4'
    }

Then you need to use https://portal.azure.com/ to register a app to get tenant id, client id and client secret, and use Java code as below to replicate this issue.
The problem is `List<Event> eventList = eventPage.getCurrentPage();`, here evevntPage is `IEventCollectionPage`, not only this interface, all interface `I*CollectionPage` have the same issue, their `getCurrentPage()` return a relevant List, and POSTMAN won't pass those list to JSON format.
> 	
    @RequestMapping(value = "/events", method = RequestMethod.GET)
	@ResponseBody
	public List<Event> getUserEventList(HttpServletRequest request) {
		try {
			final String accessToken = getAccessToken();
			
            DefaultLogger logger = new DefaultLogger();
            logger.setLoggingLevel(LoggerLevel.ERROR);
	            
            SimpleAuthProvider authProvider = new SimpleAuthProvider(accessToken);
			IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider(authProvider).logger(logger).buildClient();
			
            LinkedList<Option> requestOptions = new LinkedList<Option>();
    		requestOptions.add(new HeaderOption("Prefer", "outlook.timezone=\"Tokyo Standard Time\""));
            String email = "zhengrong.zang@gmail.com";

       		IEventCollectionPage eventPage = graphClient.users(email).events().buildRequest(requestOptions).select("subject,body,bodyPreview,organizer,attendees,start,end,location").get();
		    List<Event> eventList = eventPage.getCurrentPage();
		} catch (Exception e) {
			e.printStackTrace();
		}

		return eventList;
	}

	public String getAccessToken() {
	    final String authority = "https://login.microsoftonline.com/");
		final String tenantId = "Your APP tenant id");
		final String clientId = "Your APP client id");
		final String clientSecret = "Your APP client secret");
		final String scope = "https://graph.microsoft.com/.default");
		final String[] scopes = scope.split(",");
        String accessToken = null;
        
        try {
            // Build the MSAL application object with app ID and authority
            app = ConfidentialClientApplication.builder(clientId, ClientCredentialFactory.createFromSecret(clientSecret)).authority(authority + tenantId + "/").build();
            ClientCredentialParameters clientCredentialParameters = ClientCredentialParameters.builder(scopeSet).build();

            // Request a token, passing the requested permission scopes
            IAuthenticationResult result = app.acquireToken(clientCredentialParameters).exceptionally(ex -> {
                System.out.println("Unable to authenticate - " + ex.getMessage());
                return null;
            }).join();

            accessToken = result.accessToken();
        }
        catch (Exception e) {
        	e.printStackTrace();
        }

		return accessToken; 
	}

	public class SimpleAuthProvider implements IAuthenticationProvider {
	    private String accessToken = null;
	    public SimpleAuthProvider(String accessToken) {
	        this.accessToken = accessToken;
	    }

	    @Override
	    public void authenticateRequest(IHttpRequest request) {
	        // Add the access token in the Authorization header
	        request.addHeader("Authorization", "Bearer " + accessToken);
	    }
	}

**Comment by xk0der** [comment] 2020-06-24 02:16
Hey @mikezang pardon me, but I was unable to understand the issue with respect to the use of Postman.

- Are you facing issues with any code generated via Postman?
- Is the API endpoint failing in Postman but working otherwise (say via the Browser or cURL)?

If you have screenshots or a video recording showing where in Postman things are failing, that would be useful!

**Comment by mikezang** [comment] 2020-06-24 03:25
@xk0der I use postman to request my API that use Microsfot Graph SDK API, the REST API will return `List<com.microsoft.graph.models.extensions.Event>`, 
this Event class has 'rawObject' item that can't be convert to JSON format, you can refer this error message

> 

> com.microsoft.graph.models.extensions.Event["rawObject"]->com.google.gson.JsonObject["asString"]); nested exception is
com.fasterxml.jackson.databind.JsonMappingException: JsonObject (through reference chain: com.microsoft.graph.models.extensions.Event["rawObject"]->com.google.gson.JsonObject["asString"])

this issue is that `com.microsoft.graph.models.extensions.Event["rawObject"] is failed when convert to JSON by com.google.gson.JsonObject["asString"])`

You can check screenshot as below, I GET my API by postman, then API to get event list with Micorosft Graph SDK, you can check log on console, that is no any problems until return that list, at last, you will see the error message in postman.
I hope those information can help you.

Call my API from postman
![image](https://user-images.githubusercontent.com/1030268/85494774-503d0980-b614-11ea-8d54-29eba97cb01f.png)

Call into my API
![image](https://user-images.githubusercontent.com/1030268/85494889-811d3e80-b614-11ea-8088-94b3fcf24917.png)

My API will return event list
![image](https://user-images.githubusercontent.com/1030268/85495196-09034880-b615-11ea-914c-39f8f0e89dcf.png)

The response in postman
![image](https://user-images.githubusercontent.com/1030268/85495291-30f2ac00-b615-11ea-81b6-88fe4eb84d3f.png)

**Comment by mikezang** [comment] 2020-06-24 03:40
@xk0der `com.microsoft.graph.models.extensions.Event.rawObject` is `com.google.gson.JsonObject`, but postman used `com.fasterxml.jackson.databind.ObjectWriter.writeValue` to parse and convert it, I think this is reason for this issue.

**Comment by xk0der** [comment] 2020-06-24 04:17
Hey @mikezang appreciate you providing more information. It's useful.

**From what I see the issue is with the code you have and not with Postman.**
[HTTP 500](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500) indicates Internal Server Error.

Postman app (or for that matter any API Client, or even a browser) do not know which language interfaces and classes you are using at the server. 

The errors you are seeing are server-side errors, you will have to debug your code to understand why it's failing and these would likely need to be fixed in your server code.

To aid you to troubleshoot from the Postman side, you can check the data being sent by Postman using the Postman Console (View > Show Postman Console). Refer to Graph SDK's documentation to validate if you are sending the request in the right format.

**The problem you are facing is with the Java Spring framework** 
And more specifically with the Java library you are using to parse JSON : https://springframework.guru/processing-json-jackson/
I'm not a Java SpringBoot expert, but the issue seems to be around serialization and deserialization of the data.

I would suggest your try out StackOverflow or other programming related forums to get help on this issue.
Maybe try Microsoft's forums as well.

Here are some quick results from a search I did for the exception you are getting that should help you:
* **Similar to the exception you got:** https://stackoverflow.com/questions/44565206/com-fasterxml-jackson-databind-jsonmappingexception-due-to-new-maven-entries 
* **Jackosn JSON library documentation:** https://github.com/FasterXML/jackson-docs
* **Another Similar issue to yours:** https://stackoverflow.com/questions/61169128/could-not-write-json-jsonobject-nested-exception-is-com-fasterxml-jackson-data

Hope this makes sense and was useful. Let me know if there are still confusions 👍

**Comment by xk0der** [comment] 2020-06-24 22:50
Since this is a Spring Boot issue, and not related to Postman, closing this ticket.

**Closed as completed by xk0der** 2020-06-24 22:50 UTC
Labels: support
