### ISSUE TITLE
Postman crashing if result size is more than 40k

### ISSUE THREAD

**Issue by fadk089** [a85/POSTMan-Chrome-Extension#5913] opened 2019-02-12 18:08 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

**To Reproduce**
1. Hit any endpoint which returns more than 40k result set
2. Wait for result and try to click again on send 
3. See error

**App information (please complete the following information):**
 Version 6.7.3 (6.7.3) for Mac
**Additional context**

**Comment by numaanashraf** [comment] 2019-02-18 12:24
Thanks for reporting this @fadk089. We are tracking this at #4751. Please follow that issue for updates.

**Comment by numaanashraf** [comment] 2019-02-18 12:24
Duplicate of #4751

**Closed as completed by numaanashraf** 2019-02-18 12:24 UTC
Labels: duplicate
