### ISSUE TITLE
Data File Import - Collection Runner - Incorrect Import

### ISSUE THREAD

**Issue by ashishkpathak** [a85/POSTMan-Chrome-Extension#5994] opened 2019-02-27 23:51 UTC
**Describe the bug**
While importing data (CSV file) for collection runner, the data is incorrectly imported if the first column data has a leading zero.
Example: The following CSV file, when imported 
MSISDN,CONTACT_ID
0405153828,2 
0405177895,3
0482018572,5

Would drop the leading Zero of '0405153828' and make it '405153828'

**To Reproduce**
1. Go to Collection Runner.
2. Click on 'Data.. Select File'
3. Import the CSV file with sample data mentioned above.
4. Click the 'Preview'
5. Notice the missing leading zeros.

**Expected behavior**
The imported data should have the leading zero in the data.

**Screenshots**
Refer to attached screenshots.

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.7.3
 - OS: macOS High Sierra 10.13.6
<img width="1280" alt="missing leading zero" src="https://user-images.githubusercontent.com/10985629/53531228-c3c92680-3b46-11e9-8049-3f144a532e37.png">
![collectionrunnerfailure](https://user-images.githubusercontent.com/10985629/53531235-c6c41700-3b46-11e9-82a1-7da9d5688dc5.png)

**Comment by numaanashraf** [comment] 2019-02-28 08:22
@ashishkpathak We are tracking this at #2734

**Comment by numaanashraf** [comment] 2019-02-28 08:22
Duplicate of #2734

**Closed as completed by numaanashraf** 2019-02-28 08:22 UTC
Labels: duplicate
