### ISSUE TITLE
form-data type="file" isnt saved properly in collections

### ISSUE THREAD

**Issue by zvaehn** [a85/POSTMan-Chrome-Extension#1040] opened 2015-05-04 05:47 UTC
the key keeps but the chosen file disappears and you have to select it over and over again after switching back from another saved request.

**Comment by abhijitkane** [comment] 2015-07-20 11:31
The current Chrome app platform prevents us from saving a handle to the file with the request.

**Comment by abhijitkane** [comment] 2015-12-29 17:40
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/1113

**Closed as completed** 2016-08-01 22:51 UTC
Labels: platform/chrome, collection-v2
