### ISSUE TITLE
Previous request in the preview tab is displaying under body preview

### ISSUE THREAD

**Issue by ramyaduttuluri** [a85/POSTMan-Chrome-Extension#5371] opened 2018-10-16 14:31 UTC
Postman for Windows
Version 6.4.2
Windows 10
https://user-images.githubusercontent.com/9086020/47023746-36b5a000-d158-11e8-91c8-539e3ec8eb7f.png

**Comment by sujayvenaik** [comment] 2018-10-18 05:21
Hey @ramyaduttuluri 
This may be the case if you sent another request in the same tab previously and was on the preview tab at the end before sending another request.

If you sent one request and was on preview tab before sending another request in the same tab, so the next response that you receive by default will have the preview tab selected.

**Comment by sujayvenaik** [comment] 2018-10-18 06:33
Duplicate of #5368

**Closed as completed by sujayvenaik** 2018-10-18 06:33 UTC
Labels: bug
