### ISSUE TITLE
Add Collection import support for RAML 1.0

### ISSUE THREAD

**Issue by satwise** [a85/POSTMan-Chrome-Extension#3057] opened 2017-05-22 21:55 UTC
Although RAML 0.8 import is currently supported, our company has fully migrated to RAML 1.0 to take advantage of it's powerful capabilities.

Generating a Collection from RAML 1.0 will save our Dev team valuable time, as they must manually create these collections now. The import would eliminate rework and allow development activity to replace the current manual documentation effort.

**Comment by SamvelRaja** [comment] 2017-05-23 08:03
Thanks for bringing this to our notice. We shall keep you updated on this thread when we start taking this up.

**Comment by mhGLEIF** [comment] 2017-05-23 15:16
Thanks @SamvelRaja - I also just upgraded to RAML 1.0 because this is now the supported version e.g. in API Workbench; RAML2HTML... so it just makes sense for Postman to use it.

**Comment by a85** [comment] 2017-06-27 23:41
Closing as a duplicate. We will look into this soon after introducing multi-level folders.

**Closed as completed by a85** 2017-06-27 23:41 UTC
Labels: feature

**Comment by Tzaphkiel** [comment] 2017-12-20 10:12
Which issue is duplicating this one?

 I also would like to see RAML 1.0 supported especially in the "Tests" tab in postman with response code validation, schema validation, etc. i.e.: basic checks extracted from the definition of the API in RAML v1.0 with types

**Comment by satwise** [comment] 2017-12-21 05:20
I couldn't agree more it would be so useful to be able import the RAML
available on our MuleSoft's Exchange API portals, which have fully
documented data type descriptions and examples fully defined. Not it's an
extra step to manually create a Postman collection after the RAML is
defined, which we don't have the Dev Cycles for.

Ed Jankauskas

**Comment by craigstjean-wf** [comment] 2019-01-10 15:32
@a85 what is this a duplicate of?  As others have mentioned, this would be very valuable for MuleSoft developers (such as me).  Thank you!
