### ISSUE TITLE
Version 5.4.0: After update one of my HTTP GET call is hanging

### ISSUE THREAD

**Issue by mohitkhanna** [a85/POSTMan-Chrome-Extension#3891] opened 2017-12-01 14:48 UTC
## App Details:
```
Postman for Mac
Version 5.4.0
OS X 15.6.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Until the upgrade this specific API call was working all fine. My API server which hosts multiple APIs is up and running. POST, DELETE calls work all fine. Only this specific GET call gets stuck at Sending.... status. Other GET calls (different API endpoints) are working.

The same API works from the command line (curl) from the same system. Restarting Postman also did not work.

 2. Expected behaviour:
GET call should have reached the API backend server.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

Postman console shows nothing for this call. For rest of the API calls logs are being shown as expected.

 4. Screenshots (if applicable)

Screenshots attached.
<img width="1503" alt="screen shot 2017-12-01 at 20 15 48" src="https://user-images.githubusercontent.com/681244/33487832-972ea3b6-d6d4-11e7-8c06-2782bbba5971.png">
<img width="1513" alt="screen shot 2017-12-01 at 20 16 21" src="https://user-images.githubusercontent.com/681244/33487833-9903eee4-d6d4-11e7-810d-7a64ddf49685.png">

**Comment by kamalaknn** [comment] 2017-12-01 16:32
Hi @mohitkhanna 

This is a duplicate of #3889. Closing this. Please follow the parent thread for updates.

**Closed as completed by kamalaknn** 2017-12-01 16:32 UTC
