### ISSUE TITLE
Postman 8.0.3, not multi tab option available

### ISSUE THREAD

**Issue by rbailen** [a85/POSTMan-Chrome-Extension#9514] opened 2021-02-01 11:44 UTC
Hi guys, 

Is it possible to open more than one tab at the same time without doing any change in the resource?

The button "Open in new Tab" is not working.

**Comment by DannyDainton** [comment] 2021-02-01 11:55
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9493

**Closed as completed by DannyDainton** 2021-02-01 11:55 UTC
Labels: duplicate
