### ISSUE TITLE
Interceptor missing from Mac Postman

### ISSUE THREAD

**Issue by bhimvu** [a85/POSTMan-Chrome-Extension#2872] opened 2017-03-31 01:08 UTC
1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Mac app (thick client)
 3. OS details: OS X 16.5.0 / x64
 4. Is the Interceptor on and enabled in the app: the icon is missing
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: There should be an icon to enable the Interceptor, but it doesn't seem to be present.
 7. Console logs: (see below)
 8. Screenshots (if applicable)
<img width="1403" alt="postman mac no interceptor" src="https://cloud.githubusercontent.com/assets/26556094/24532206/7ba75c5a-1573-11e7-8968-0cdf7cb16ad2.png">

LOGS:
 ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs. 

================================================================
🌏 sync service connectivity initiated
socket replaying queued commands
🌏 connected to sync service.
🐶 watchdog checking connection health
Failed to load resource: net::ERR_FILE_NOT_FOUND
🐶 watchdog checking connection health
You are not a member of a team
You are not a member of a team
🐶 watchdog checking connection health

**Comment by ravi-cloudknox** [comment] 2017-04-28 22:10
Same here.

**Comment by yingw787** [comment] 2017-11-29 15:26
Same here.

**Comment by a85** [comment] 2017-12-24 21:40
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1667

**Closed as completed by a85** 2017-12-24 21:40 UTC
Labels: feature
