### ISSUE TITLE
Long intergers are truncated (converts to a floating point notation) without any warning

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#4908] opened 2018-07-27 14:21 UTC
**Describe the bug**
While testing API, if the response of the API call contains a long integer, it is getting converted into a floating point notation in pretty view but the same works in raw view.

**Steps to reproduce the behavior:**
Call an API that gives you a long integer in the response or create a mock server with a long integer in the response body - you will notice a number being converted into floating point notation in the pretty view, Please see the screenshot below
<img width="973" alt="screen shot 2018-07-27 at 7 46 25 pm" src="https://user-images.githubusercontent.com/40994626/43326184-cf39a42e-91d5-11e8-80ee-a1ba9676c1b7.png">

But the same works fine in raw view.
<img width="953" alt="screen shot 2018-07-27 at 7 48 41 pm" src="https://user-images.githubusercontent.com/40994626/43326310-1fd78dce-91d6-11e8-9395-96186cbe223c.png">

**App information (please complete the following information):**
App Type: Native App
Postman Version: 6.1.4]
OS: e.g. macOS High Sierra 10.13.4

**Comment by harryi3t** [comment] 2018-07-28 04:35
@Ramyasri1212 Thanks for reporting this issue.
The specification for JSON in [rfc 7159](https://tools.ietf.org/html/rfc7159#section-6) says:
> A number is represented in base 10 using
   decimal digits.  It contains an integer component that may be
   prefixed with an optional minus sign, which **may be followed by a
   fraction part and/or an exponent part.**

So having an exponenet part is valid.

Also, it talks about the largest number that should be supported by the implementations
>  Note that when such software is used, numbers that are integers and
   are in the range [-(2\*\*53)+1, (2\*\*53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.

The value comes out to be `-9007199254740991 to 9007199254740991`

In the raw mode it's just text so it's not truncated.
I would suggest considering sending large numbers as strings instead (If modifiying the server code is possible at all)

**Comment by kamalaknn** [comment] 2019-07-30 09:31
This issue should be fixed in the latest version of Postman.

Starting from Postman 7.3 we have changed the response pretty view rendering logic. 

In previous versions, we would convert the response into a Javascript object and format the Javascript object. This has led to multiple issues caused by the constraints of the Javascript language.

In the newer version of Postman, we have switched to a formatting method that prettifies the response directly without converting it into a Javascript object. This would make sure there is no change in the response view when displayed.

**Closed as completed by kamalaknn** 2019-07-30 09:31 UTC
Labels: bug, request-sending

**Comment by yoimnik** [comment] 2019-08-26 18:40
@kamalaknn 
https://github.com/postmanlabs/postman-app-support/issues/7197

**Comment by sidharthjs** [comment] 2019-12-20 12:37
This issue is seen again in the postman version `7.14.0`. OS: `Mac OS - High Sierra 10.13.1`

<img width="364" alt="Screen Shot 2019-12-20 at 6 02 32 PM" src="https://user-images.githubusercontent.com/17313998/71255086-fac92c80-2352-11ea-8dff-c65a1a8775e3.png">

@yoimnik @kamalaknn
