### ISSUE TITLE
Update failed message when app is launched manually while updating

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5580] opened 2018-11-28 18:46 UTC
**Describe the bug**
Updating from 5.2 to 5.3 in-app fails with the following warning:
<img width="480" alt="screen shot 2018-11-28 at 10 23 33 am" src="https://user-images.githubusercontent.com/43283131/49173564-f3bf1e80-f2f8-11e8-8305-c2bf02c8fe99.png">

DevTools logs and Postman/logs/ files attached. The relevant error in the logs appears to be:

`
vendor-shared.js:119189 Error in update flow: {"message":"Could not get code signature for running application","name":"Error","stack":"Error: Could not get code signature for running application\n    at DarwinUpdater.downloadUpdate (/Applications/Postman.app/Contents/Resources/app/node_modules/@postman-app/updater/lib/AbstractUpdater.js:175:26)\n    at downloadUpdate (/Applications/Postman.app/Contents/Resources/app/services/UpdaterHandler.js:195:25)\n    at EventEmitter.pm.eventBus.channel.subscribe (/Applications/Postman.app/Contents/Resources/app/services/UpdaterHandler.js:74:13)\n    at emitOne (events.js:115:13)\n    at EventEmitter.emit (events.js:210:7)\n    at _dispatch (/Applications/Postman.app/Contents/Resources/app/common/_event-bus.js:180:14)\n    at EventEmitter.<anonymous> (/Applications/Postman.app/Contents/Resources/app/common/_event-bus.js:196:11)\n    at emitThree (events.js:135:13)\n    at EventEmitter.emit (events.js:216:7)\n    at WebContents.<anonymous> (/Applications/Postman.app/Contents/Resources/electron.asar/browser/api/web-contents.js:266:13)\n    at emitTwo (events.js:125:13)\n    at WebContents.emit (events.js:213:7)"}
`

**App information:**
 - _App Type:_ Native App
 - _Postman Version:_ 6.5.2
 - _OS:_ macOS High Sierra 10.13.6

**Log Files:**
[failed_update_devtools.log](https://github.com/postmanlabs/postman-app-support/files/2626155/failed_update_devtools.log)
[logs_from_folder.zip](https://github.com/postmanlabs/postman-app-support/files/2626186/logs_from_folder.zip)

**Comment by SamvelRaja** [comment] 2018-12-03 09:13
@JP-from-Postman  This issue will happen when you tried to open the app while it is in the updating phase.
This should be resolved when you restart the app, kindly confirm the same. 
Keeping this open to funnel people who face the same issue.

**Comment by akaustav** [comment] 2020-01-25 15:22
A similar behavior seems to occur in Microsoft Windows 10 when updating to Postman version 7.16.1
(win32 10.0.18363 / x64).

## Pre-requisites
* Microsoft Windows 10
* Have a version of Postman native application installed which is NOT the latest version.
* Keep **Automatically download major updates** turned on under **Settings** > **Update**.

## Steps to reproduce
1. Launch the older version app.
1. The desktop app will start checking if any updates are available.
1. An orange notification dot appears on top of the Settings (🔧) icon indicating that an update is available.
1. The Settings menu contains an extra option - **Update available, download now** - to download the update manually.
1. The application starts downloading the update in the background without any visual indicators.
1. Click on the **Settings** (🔧) > **Update available, download now**.
1. The application fails to download the update - displaying a similar kind of dialog box [shown in the description of this issue](https://github.com/postmanlabs/postman-app-support/issues/5580#issue-385407402).
1. The notification dot on top of the Settings (🔧) icon changes from **orange** to **red** color.
1. After the download is complete in the background, the application displays a dialog box stating - "An update has been downloaded. Restart the application to install the update."

## Actual Behavior
The application states that it failed to update - when, in fact, it is downloading the same update in the background without any apparent visual indicators that it is doing so.

## Expected Behavior
The application should indicate that an update is currently being downloaded in the background. If that download fails, then an option to manually retry or download the application should be presented to the user.

**Comment by morrison147** [comment] 2021-01-21 14:32
I'm having issue upgrading Postman x64 on a Windows 2012 R2 RDS server from version 6.7.4 to version 7.36.1. Attached are screenshots of the update error message, the DevTools errors, and the squirrel setup log.

[updateFailedMsg.zip](https://github.com/postmanlabs/postman-app-support/files/5849945/updateFailedMsg.zip)

**Comment by twitharshil** [comment] 2022-02-23 05:48
Hey @JP-from-Postman, 

The issue originally reported seems to be coming from an unsupported version of the postman. This issue only happens when the application is not code-signed and it tries to get updates. In your scenario, it could be the local builds that you are trying out. Closing this ticket as all the latest versions of the postman application are code signed & notarized properly :)

**Closed as completed by twitharshil** 2022-02-23 05:48 UTC
Labels: bug, platform/macOS, product/desktop-foundation, component/auto-updates, version/6

**Comment by twitharshil** [comment] 2022-02-23 05:51
Hey @akaustav @morrison147 

The issue reported seems to be a different one than the original issue for which the ticket was opened. You create separate ticket if you are still facing the same issue. Thanks!

**Comment by akaustav** [comment] 2022-02-23 08:10
> Hey @akaustav @morrison147
> 
> The issue reported seems to be a different one than the original issue for which the ticket was opened. You create separate ticket if you are still facing the same issue. Thanks!

Hi @twitharshil - Thanks for taking the time to look at this issue that I had opened over 2 years ago. You are probably right about the issue mismatching the original issue - I don't recall actually verifying the logs in the developer console to confirm if my reported issue exactly matched the original issue - sorry about that.

As far as I recall, I have not seen the issue that I described above occur for quite some time now. Maybe it got fixed by another defect / enhancement since I reported the issue? I can assure you that I was not using any local builds of Postman, and was (and always have been) using the officially published version of Postman. I will be sure to re-test and open a separate issue in this GitHub repository if my problem still persists.

Ameet
