### ISSUE TITLE
How to use a custom HTTP Method?

### ISSUE THREAD

**Issue by cyborgx37** [a85/POSTMan-Chrome-Extension#2403] opened 2016-10-11 23:48 UTC
I'm attempting to test an OData 3.0 service that uses the "MERGE" method (this standard predated PATCH). I don't see "MERGE" as an option and can't find a way to either add it to the list or enter a custom method.

Is this possible? If not, please consider adding a simple "Other" with a popup (or something) to use a custom method.

4.7.2
OS X / x86-64
Chrome 53.0.2785.143

**Comment by vegetableman** [comment] 2016-10-12 06:01
@cyborgx37 Thanks for posting this issue 👍  . We are looking in to it and will get back to you.

**Comment by a85** [comment] 2016-12-08 15:19
Closing as duplicate of #166

**Closed as completed by a85** 2016-12-08 15:19 UTC
Labels: feature
