### ISSUE TITLE
File | Import does nothing

### ISSUE THREAD

**Issue by Brilbroeder** [a85/POSTMan-Chrome-Extension#9536] opened 2021-02-03 09:56 UTC
File | Import a first time works fine
I import a swagger file by pointing to a url. Works fine.
File | Import second time, does nothing

Closing postman, opening postman.
File | Import works fine again for only one import.

**Comment by DannyDainton** [comment] 2021-02-03 10:01
Closing as this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9520

**Closed as completed by DannyDainton** 2021-02-03 10:01 UTC
Labels: duplicate
