### ISSUE TITLE
How to send a base64 image to Postman?

### ISSUE THREAD

**Issue by AndriiHavrylyak** [a85/POSTMan-Chrome-Extension#5678] opened 2018-12-20 10:29 UTC
You need to request an API with an image encoded in base64. I would like to assign the "Фото1
1
![1](https://user-images.githubusercontent.com/38010614/50279616-e0fcbd00-0452-11e9-8910-0bd04fdfe020.jpg)
" time to base64 via the Get-request, but there is an error!

**Comment by numaanashraf** [comment] 2018-12-24 12:06
Duplicate of #5685

**Closed as completed by numaanashraf** 2018-12-24 12:06 UTC
