### ISSUE TITLE
2nd instance of Postman Chrome (Windows) app hangs on startup

### ISSUE THREAD

**Issue by 808codist** [a85/POSTMan-Chrome-Extension#2828] opened 2017-03-20 22:50 UTC
1. Postman Version:4.10.3
 2. App (Chrome app or Mac app):Chrome App
 3. OS details:Windows 10
 4. Is the Interceptor on and enabled in the app:I don't know
 5. Did you encounter this recently, or has this bug always been there:I don't know
 6. Expected behaviour:2nd window starts up OR notification that Postman is already running.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Could not load DB Event
Notification System not initialized
'FileError is deprecated and will be removed in M54, around October 2016. Please use the 'name' or 'message' attributes of the error rather than 'code'. See https://www.chromestatus.com/features/6687420359639040 for more details.
Error: INVALID_STATE_ERR

 8. Screenshots (if applicable)

1. Start Postman Chrome App
2. Start another Postman Chrome App
3. Observe 2nd Postman window remains in "startup" mode

**Comment by vegetableman** [comment] 2017-03-21 07:50
@808codist Could you share a vid/gif showing the steps to reproduce the issue?. We are not able to recreate it.

**Comment by 808codist** [comment] 2017-03-22 01:32
see mp4 w/in attached zip

[2017-03-21_15-22-13.zip](https://github.com/postmanlabs/postman-app-support/files/860122/2017-03-21_15-22-13.zip)

**Comment by schellem** [comment] 2017-03-22 15:05
I see the same results with 4.10.3 on Win 8.1, the second instance sits on the solar system waiting image.

**Comment by vegetableman** [comment] 2017-03-23 07:15
Ah.. yes, the issue is reproducible for the native app. will keep you guys posted ^_^.

**Comment by SamvelRaja** [comment] 2017-09-06 09:49
Duplicate of #/2177

**Closed as completed by SamvelRaja** 2017-09-06 09:49 UTC
Labels: bug, platform/windows
