### ISSUE TITLE
Run all endpoints till selected

### ISSUE THREAD

**Issue by blackandred** [a85/POSTMan-Chrome-Extension#5486] opened 2018-11-06 10:36 UTC
Hi,

I have a feature request, I think it is a nice idea when working with bigger collections. Could potentially save a lot of time.

Given you are on the main view, you browse the list of endpoints.
When you right click on the endpoint you have options such as "Open in new window, duplicate, rename, (...)".
If there would be such feature you could select "Run all endpoints to this moment" - that could run all endpoints one-by-one and stop after that one we selected.

**Comment by sivcan** [comment] 2018-11-06 11:37
Hi @blackandred, you might want to look into [pm.setNextRequest](https://www.getpostman.com/docs/v6/postman/collection_runs/building_workflows)

You can basically just run the collection and in the scripts you can define with if statements and basically stop the execution.
You can build really complex workflows around this.

There are multiple issues on github and [Postman Community](https://community.getpostman.com) such as https://github.com/postmanlabs/postman-app-support/issues/4996 in which I have explained how to use this feature.

There's also a suggestion on improvements in this feature here: https://community.getpostman.com/t/improve-postman-setnextrequest/258

I would still mark yours as a feature request but you should be able to quickly set up your workflows with SNR and a few environment variables.

Let me know in case you need further help using SNR. :)

**Comment by saswatds** [comment] 2019-05-21 19:44
Duplicate of #6360 #2392

Closing this issue to track the feature at a single place

**Closed as completed by saswatds** 2019-05-21 19:44 UTC
Labels: feature, collection-runner, product/runtime
