### ISSUE TITLE
Postman failing to respond

### ISSUE THREAD

**Issue by anirudhanagaraja** [a85/POSTMan-Chrome-Extension#7627] opened 2019-11-12 13:09 UTC
**Describe the bug**
When you use the postman for many requests, it wont respond correctly.

**To Reproduce**
1. Use postman and try to hit many requests.
2. It fails responding .

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by kamalaknn** [comment] 2019-11-13 11:12
@anirudhanagaraja Closing this as a duplicate of #7624 

Could you provide the following details on the **original thread**?

1. The version of Postman app you are using
2. Size of response for each of the request
3. Number of tabs you have open

**Closed as completed by kamalaknn** 2019-11-13 11:12 UTC
