### ISSUE TITLE
Iteration number when selected in collection runner highlights different iteration number

### ISSUE THREAD

**Issue by srinivasskc** [a85/POSTMan-Chrome-Extension#8834] opened 2020-07-25 16:09 UTC
**Describe the bug**
After running the collection to run for 10 iterations, when i click on Iteration number 4. It is highlighting Iteration number 3 from the list.

**To Reproduce**
1. Go to 'Postman'
2. Click on 'Collection -> Runner'
3. If the collection is to run 10 iterations, Click 
3. Scroll down to right and click on Iteration number: 4
4. I see it highlights the iteration number: 3

**Expected behavior**
when Iteration number 4 is selected, it should highlight iteration number 3

**Screenshots**
![image](https://user-images.githubusercontent.com/26836928/88460891-34e84700-cebd-11ea-8bf3-6c42f6dd43b7.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [v7.29.1]
 - OS: [Windows 10 64-Bit]

**Comment by saswatds** [comment] 2020-07-26 07:18
Hi @srinivasskc, I was not able to reproduce this bug. Can you help us with a gif or recording that show this behaviour happening?

**Comment by srinivasskc** [comment] 2020-07-26 08:22
Hi @saswatds @vvs11,
Below is the gif recording on this behavior.

![PostmanRunnerIteration](https://user-images.githubusercontent.com/26836928/88474856-44f93880-cf48-11ea-95ea-aefd2d8db61d.gif)


https://drive.google.com/file/d/1C-QjyNV_pG2oqq8ZRmXOI-e7DEZ4vTiF/view?usp=sharing

**Comment by srinivasskc** [comment] 2020-08-02 07:42
Any additional info required from my end?

**Comment by mccannt** [comment] 2020-08-28 22:55
@srinivasskc Thanks for this. We are making improvements in the Runner and will follow up when we have more to share.

**Comment by timbochamp** [comment] 2021-01-18 19:42
@srinivasskc This should now be fixed this issue in the latest Postman Canary application (v8.0.0-canary09), as well as in Postman for Web. Can you please try it out and confirm if it's fixed for you?

**Comment by timbochamp** [comment] 2021-01-27 16:25
I'm going to close this out but please feel free to reopen again if you encounter this different iteration number highlighting in our Postman Version 8.0.2 app or on Postman for Web.

**Closed as completed by timbochamp** 2021-01-27 16:25 UTC
Labels: bug, collection-runner, product/runtime
