### ISSUE TITLE
something went wront message when typing text in tests tab

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#7810] opened 2019-12-17 05:55 UTC
**To Reproduce**
1. open a collection
2. click on a request
3. open a tests tab with some code

**Expected behavior**
It is supposed to work, but the text bacame unawailable untill you open new instance on postman

**App information (please complete the following information):**
 - App Type Native
 - Postman Version 7.13.0 win32
 - OS: windows 7 pro

**Additional context**
The issue wasn't seen before.

**Comment by vvs11** [comment] 2019-12-19 09:24
Hi @m3dbedb, Thanks for writing in
Could you give us more info about the issue you're facing? e.g. what were you doing when you hit this state?
Also, are you still seeing it?

**Comment by harryi3t** [comment] 2019-12-19 11:18
@m3dbedb Can you share a screen recording showing the issue? That would help us identify and fix the issue faster.

**Comment by codenirvana** [comment] 2019-12-19 12:34
Duplicate of #7759

**Closed as completed by codenirvana** 2019-12-19 12:34 UTC
Labels: product/runtime
