### ISSUE TITLE
Postman code snippet - Python code fails to run when header values contains " (double quotes)

### ISSUE THREAD

**Issue by vivekpatel111** [a85/POSTMan-Chrome-Extension#6701] opened 2019-06-12 07:23 UTC
**Describe the bug**
Python code fails to run when header values contains " (double quotes)

**To Reproduce**
1. Add any request header with value containing " (double quotes)
![image](https://user-images.githubusercontent.com/8190653/59331045-9593df00-8d10-11e9-8c16-ea1eaf66ae92.png)

1. Click on code and select Python language (select any option in python sub-menu)
![image](https://user-images.githubusercontent.com/8190653/59331122-beb46f80-8d10-11e9-936d-d1ab2fed49df.png)

**Expected behavior**
- Generated code should ran as is and should give same result as Postman.
- Header value should be escaped properly while generating code snippet.

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : 7.1.1 (7.1.1)
 - OS: macOS Mojave 10.14.5

**Comment by pdewitt** [comment] 2019-10-22 09:02
For me the generated code works when you replace the "," by "." in the parameter on line 3. This gives a valid host.

Also on line 11 the URL on the host ("undefined") has to start with "/". If there is a second part on it ("undefined/something") the parts are separated by a ",". This should be replaced  by "/".

**Comment by gabrielsroka** [comment] 2019-11-01 16:28
@pdewitt 

yes, i came to report the same thing. eg, Postman says
``` python
import http.client

conn = http.client.HTTPConnection("org,oktapreview,com")
# ...
conn.request("GET", "api,v1,users,me")
```

but I needed
``` python
import http.client

conn = http.client.HTTPSConnection("org.oktapreview.com")
# ...
conn.request("GET", "/api/v1/users/me")
```

so:
change `HTTP` to `HTTPS`
on line 3, change `,` to `.`
on line 5, change `,` to `/` (and add leading `/`

**Comment by gabrielsroka** [comment] 2019-11-01 16:36
seems to be fixed: https://github.com/postmanlabs/postman-app-support/issues/4133

![image](https://user-images.githubusercontent.com/14354736/68040225-1c7b3100-fc8b-11e9-844d-22542910f163.png)

**Comment by DannyDainton** [comment] 2020-06-29 12:05
Closing this issue as it has now been resolved.

Please feel free to reopen with the steps to reproduce if the issue persists.

**Closed as completed by DannyDainton** 2020-06-29 12:05 UTC
Labels: bug, code-generator
