### ISSUE TITLE
URL path variables are not replaced if followed by a dot

### ISSUE THREAD

**Issue by fireattack** [a85/POSTMan-Chrome-Extension#8302] opened 2020-04-09 04:04 UTC
**Describe the bug**

When path parameter is immediately followed by a dot, the character afterwords are considered as part of the path parameter. And there is no way to split the two.

Example: `https://example.com/api/:id.json`

**To Reproduce**
1. Create a new request tab.
2. Paste in the above link
3. Check path parameter part.

**Expected behavior**
The key should "id", not "id.json".

**Screenshots**

![image](https://user-images.githubusercontent.com/4130991/78856666-f5205100-79ec-11ea-803b-c5e79f427594.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.22.1
 - OS: Win7x64

**Additional context**
The bug was firstly reported at #4423 and later redirected to #2427. Both of these two issues are closed despite the bug is still present in newest version. I think relying on closed issue(s) for discussion of an existing bug not the right way to do it, so I open this new ticket to reflect the fact that the bug still exists.

**Comment by whyvez** [comment] 2020-05-25 20:13
It would be nice to be able to do something like: `https://example.com/api/:id.:format` which would map to two path params of `id` and `format`.

**Comment by jayarjo** [comment] 2020-06-12 11:45
How many times this bug has to be reopened?

**Comment by dzmitry-kankalovich** [comment] 2021-06-10 21:49
I just really wish someone at Postman would spend some time on, you know, covering their fix with unit tests. Because it's broken again.

**Comment by fireattack** [comment] 2021-06-10 22:09
It indeed is weird this hasn't be fixed. I encounter this issue semi-frequently when using Postman. I'd guess others would find so too.

**Comment by coditva** [comment] 2022-06-30 09:33
Hey everyone, this issue has been fixed and is now available in v9.23 onwards. 🎉
Please [update the app](https://www.postman.com/downloads/) and let us know how it goes. 🙂

**Comment by shubhbhargav** [comment] 2022-07-06 18:51
Re-opening the issue due to a bug where the variable is not getting resolved when the request is sent: https://github.com/postmanlabs/postman-app-support/issues/2805#issuecomment-1172148346

**Comment by coditva** [comment] 2022-07-13 05:52
Update: The bug has been identified. The issue is fixed and will be rolled out with v9.25 release in the next few days.

**Comment by coditva** [comment] 2022-07-21 05:38
Update: The fix is now available in v9.25.x onwards. Closing the ticket; please re-open if facing any issues. 🙂

**Closed as completed by coditva** 2022-07-21 05:38 UTC
Labels: bug, request-sending, product/runtime
