### ISSUE TITLE
The URL text box in two pane mode is too short

### ISSUE THREAD

**Issue by mchaitanyababu** [a85/POSTMan-Chrome-Extension#4837] opened 2018-07-17 04:52 UTC
## App Details:

```
Postman for Windows
Version 6.2.0-canary04
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: It has been there already
 2. Expected behaviour: It must be long enough to show the URL
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): NA
 4. Screenshots (if applicable)
![capture](https://user-images.githubusercontent.com/19500653/42797109-dffe7c14-894a-11e8-996b-9f698d0028a6.PNG)

Enter into two pane mode. The URL box is too short to see at least the reasonably long URL fully.

**Comment by mchaitanyababu** [comment] 2018-07-17 04:53
We can make the URL box common to both request and response boxes below

**Comment by SamvelRaja** [comment] 2018-07-17 04:55
Duplicate of #2716

**Closed as completed by SamvelRaja** 2018-07-17 04:55 UTC
