### ISSUE TITLE
Clear all cookies using script

### ISSUE THREAD

**Issue by vgosai86** [a85/POSTMan-Chrome-Extension#5563] opened 2018-11-25 01:43 UTC
**Problem statement**
I have a use-case where I have to login for different users. without clearing cookies, it'll fail. Currently, I have been doing it manually clearing all cookies but using this way I can not run in a runner. 

**Describe the solution you'd like**
Need a way to clear all cookies via pre/post request scripts.

**Comment by matt-ball** [comment] 2018-11-26 18:41
Dependent on the complexity of what you need to do, you could set the [Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie) header manually:

Pre-request Script:
![image](https://user-images.githubusercontent.com/8490181/49034618-57b1dd80-f167-11e8-8bc0-b8ae00729b9c.png)

Headers + result:
![image](https://user-images.githubusercontent.com/8490181/49035092-a3b15200-f168-11e8-8c8a-e917af1de300.png)

[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/d9b24e221d27901e5a51)

**Comment by vgosai86** [comment] 2018-12-03 03:00
I am doing similar way but postman is adding cookie set by first user to all rest of the calls automatically which will invalidate the 2nd user attempt to login. That is why I have to clear cookies in order get successful response.

**Comment by numaanashraf** [comment] 2018-12-03 12:54
Duplicate of #3312

**Closed as completed by numaanashraf** 2018-12-03 12:54 UTC
