### ISSUE TITLE
Postman crashes when a run collection is interrupted by STOP

### ISSUE THREAD

**Issue by roshansukur** [a85/POSTMan-Chrome-Extension#7877] opened 2020-01-06 21:06 UTC
Postman crashes when a RUN collection is interrupted by STOP

**Initial Setup**
1. Create a collection (e.g: abc)
2. Add 2 folders to the collection. ( Folder 1 & Folder 2)
3. Add 5 api's to each folder in the collection.

**Steps to reproduce the behavior**
1. Go to collection abc
2. select option RUN
3. In the Collection Runner, provide Iteration count as 15
4. Select data file as "text/csv" options
5. Select & Run only 2 apis from Folder 2.
6. Once the api execution is in progress, after 2 hits, Click Stop. 
7. postman App crashes.

**Expected behavior**
postman should stop and not quit unexpectedly.

**App information**
 - App Type: Native App
 - Postman Version: v7.14.0
 - OS: Windows 10

**Comment by saswatds** [comment] 2020-02-12 02:44
Closing this issue as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/5848

**Closed as completed by saswatds** 2020-02-12 02:44 UTC
Labels: bug, product/runtime
