### ISSUE TITLE
Application crashes frequently

### ISSUE THREAD

**Issue by lucas937** [a85/POSTMan-Chrome-Extension#7139] opened 2019-08-19 10:46 UTC
The Postman application frequently fails when making requests. Sometimes the app needs to be closed and reopened, other times the (not responding) text is shown in the text bar of the application. I couple of times the application has presented a black screen - for this the application needs to be restarted 

Added screenshot of blacked out application:
![postman crash](https://user-images.githubusercontent.com/48093059/63259635-3f4a9b80-c27f-11e9-99dd-0058520cb6dd.png)

To Reproduce
1. Open Postman
2. Send a request - my request are quite large sometimes. (10-25mb) 
3. Application crashes with black screen. 

Expected behavior:
No application crash 

App information:
 - Native Postman application 
 - Postman Version v7.5.0  
 - OS: Windows 10 

Additional context:
Noticed that larger requests that take over 10+ seconds fail or make the app unresponsive. (

**Comment by numaanashraf** [comment] 2019-08-22 10:12
@lucas937 Thanks for reporting this. We are tracking this at a related issue - #4230.

**Comment by numaanashraf** [comment] 2019-08-22 10:12
Duplicate of #4230

**Closed as completed by numaanashraf** 2019-08-22 10:12 UTC
Labels: duplicate
