### ISSUE TITLE
How to have multiple headers using multipart/mixed request ?

### ISSUE THREAD

**Issue by JulienErdogan** [a85/POSTMan-Chrome-Extension#7407] opened 2019-09-30 09:39 UTC
Hey guys, 

I'm using Postman to connect to my Tableau API and I have an issue using the API to post a file.
The API is used to send a file AND send a JSON request in the same request. Both parts need to have a specific Content-Disposition in the header but I don't know how to do it.

I've tried everything and searched every possible solution but I'm still stuck with an internal server error 500, clearly indicating that the request is badly formed. Plus, in the console I can clearly see that only one header is sent.

I want to have a request looking like this : [https://help.tableau.com/v2018.3/api/rest_api/en-us/REST/rest_api_ref.htm#publish_workbook](https://help.tableau.com/v2018.3/api/rest_api/en-us/REST/rest_api_ref.htm#publish_workbook)
(See **Publishing a file in the request body**)

Is it possible using Postman ? 

Thanks in advance,
Julien 

Request to send (example is in XML but it also supports JSON): 

--boundary-string
Content-Disposition: name="request_payload"
Content-Type: text/xml

<tsRequest>
  <workbook name="workbook-name" showTabs="show-tabs-flag" >
    <connections>
    <connection serverAddress="server-address" serverPort="port-number">
    <connectionCredentials name="connection-username" password="connection-password"
          embed="embed-flag" />
    </connection>
    </connections>
    <project id="project-id"/>
  </workbook>
</tsRequest>
--boundary-string
Content-Disposition: name="tableau_workbook"; filename="workbook-file-name"
Content-Type: application/octet-stream

content-of-workbook-file
--boundary-string--

**Comment by codenirvana** [comment] 2019-09-30 10:17
Duplicate of #6933

**Closed as completed by codenirvana** 2019-09-30 10:17 UTC
Labels: duplicate, product/runtime
