### ISSUE TITLE
List public documentations in a single view for a team

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#7600] opened 2019-11-07 11:46 UTC
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to view all publicly hosted documentation(s) by a team in a single view. The only way to find out now is to find the sign of a globe on the collections, as it indicates that collection is published. Below is a screenshot for reference:
<img width="1328" alt="public documentations" src="https://user-images.githubusercontent.com/12132423/68386262-ae020b80-0181-11ea-937c-eb78f1050499.png">

Users, especially admins of teams would like a view where there is a single list of all publicly hosted docs.

**Describe the solution you'd like**
A solution (either in the app/ web dashboard/ or both) which will help users of a team clearly see a list of publicly hosted Postman documentation.

**Comment by Raja-Simha** [comment] 2020-11-24 14:51
Duplicate of #5056

**Closed as completed by Raja-Simha** 2020-11-24 14:51 UTC
Labels: feature, product/documentation, product/api-network, enterprise
