### ISSUE TITLE
Add multiple files to request body in Postman interface

### ISSUE THREAD

**Issue by dheerajbhaskar** [a85/POSTMan-Chrome-Extension#2465] opened 2016-11-12 13:02 UTC
1. Postman Version:
4.8.3
win32 10.0.14393 / x64
 2. App (Chrome app or Mac app):
Windows native app
 3. OS details:
win 10 64 bit
 4. Is the Interceptor on and enabled in the app:
yes 
 5. Did you encounter this recently, or has this bug always been there:
encountered recently (needed to do this only now)
 6. Expected behaviour:
Show "Choose Files" instead of "Choose File"
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
https://gist.github.com/dheerajbhaskar/25ed549b697f32f5625eaa25dc53027d
 8. Screenshots (if applicable)

http://imgur.com/a/ejLmY

## Steps to reproduce the problem:
1. Use this request: https://www.getpostman.com/collections/68c4fd1377e3e98ad5e2
2. Change the file path to execute the request

**Comment by dheerajbhaskar** [comment] 2016-11-12 13:31
I see that this is only a limitation in the windows native app. There is a "choose files" (plural) in the chrome app

Can you please confirm that it's setting the `multipart/form-data` as contet type? because I'm not able to debug the actual request that is made since there is no debugger in the chrome app

**Comment by a85** [comment] 2017-06-27 23:30
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1104

**Comment by a85** [comment] 2017-06-27 23:31
Will be tracking that issue. We have a data editor now built to support this but need to get some other issues sorted.

**Closed as completed by a85** 2017-06-27 23:31 UTC
Labels: feature
