### ISSUE TITLE
Unable to Manage Roles

### ISSUE THREAD

**Issue by vanithathadvai** [a85/POSTMan-Chrome-Extension#8711] opened 2020-06-26 02:34 UTC
**Describe the bug**
After upgrading to  v7.27.0 I am unable to Manage Roles or Share the newly created collection.
I am an admin and Unable to share the collection manage roles on the collection created by me

**To Reproduce**
1. Go to Postman Workspace
2. Click on Create Collection
3. Add few Requests
4. Then Click on manage Roles
5. Error is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/67449095/85814458-fc294680-b733-11ea-84bf-1e8a2294bb32.png)

**App information (please complete the following information):**

 - Postman Version v7.27.0
 - OS:Windows 10 
- Browser Chrome

**Comment by sankalp0o** [comment] 2020-06-26 08:28
Hey @vanithathadvai 
There could be a few reasons why this happens. We are looking into improving the error state here. However to help us identify the root cause, could you please write to us at help@getpostman.com with information about collection id?

**Comment by kartikjain26** [comment] 2020-06-26 08:57
@vanithathadvai Did you open the share collection/ manage roles modal just after adding the collection or waited for sometime before performing those operations ?
Also, is this problem persisting even now ?

**Comment by vanithathadvai** [comment] 2020-06-26 11:07
I created a collection..added few sub folders and requests and then I want
to give another user permission to edit that collection. At that time I am
getting errors.

I am admin and I am unable to perform these manage roles on older
collection which I created earlier, This is the new collection which I
created after upgrade

**Comment by mccannt** [comment] 2020-07-22 13:00
Resolved in v7.29.0

**Closed as completed by mccannt** 2020-07-22 13:00 UTC
Labels: bug, version-control, product/runtime
