### ISSUE TITLE
Pre-request script problem

### ISSUE THREAD

**Issue by raysefo** [a85/POSTMan-Chrome-Extension#5569] opened 2018-11-26 05:50 UTC
Hello,
I am using v6.5.2. I am trying to send body-raw-json request.

Here is my sample json body:
{
    "referenceId": "700078925111",
    "productCode": "001002461285",
    "quantity": "1",
    "version": "V1",
    "signature": {{Signature}},
    "applicationCode": "52e7cf966b724749a7c4efadc3727ed7"
}
In my pre-request script I have this script;
var ApplicationCode = request.data["applicationCode"];
var Version=request.data["version"];
var ReferenceId=request.data["referenceId"];
var ProductCode=request.data["productCode"];
var Quantity=request.data["quantity"];
var SecretKey="e56067172e61";
var hashText = ApplicationCode+ProductCode+Quantity+ReferenceId+Version+SecretKey;
var encryption = CryptoJS.MD5(hashText).toString();
postman.setEnvironmentVariable("Signature", encryption);

In my python code I am checking the request as follows and getting request was not JSON.
if request.is_json:
...
else:
return jsonify(status="Request was not JSON")

Am I getting the Signature variable wrong?

**Comment by sivcan** [comment] 2018-11-27 05:40
Duplicate of  https://community.getpostman.com/t/raw-json-body-how-to-add-variable/3396/2

**Closed as completed by sivcan** 2018-11-27 05:40 UTC
