### ISSUE TITLE
Disable alt+shift shortcut

### ISSUE THREAD

**Issue by ozahorulia** [a85/POSTMan-Chrome-Extension#6255] opened 2019-04-09 13:40 UTC
I'm using Linux Mint 19.1 and Postman 7.0.7.
I have a system-wide shortcut for changing keyboard layot (alt+shift). All other software works fine wwith that. But when I'm trying to change layout while in postman, it selects "file" from the top bar menu. Is it possible to disable this shortcut? I don't find it tn the settings -> shortcuts menu.

**Comment by Tvde1** [comment] 2019-04-10 09:34
I am using v7.0.7 and alt + shift does not do anything.

**Comment by numaanashraf** [comment] 2019-04-11 04:53
Duplicate of #2096

**Closed as completed by numaanashraf** 2019-04-11 04:53 UTC

**Comment by sematgt** [comment] 2021-10-09 16:47
Its not a duplicate.

I disabled all shortcuts in Postman and still have focus on top bar menu on Alt.

Ubuntu 20 here
