### ISSUE TITLE
Generated cURL code appends &undefined=

### ISSUE THREAD

**Issue by kvor** [a85/POSTMan-Chrome-Extension#5921] opened 2019-02-13 18:02 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
After  firing a rest call, generated cURL code appends string: **&undefined=**.

However, if we generate code before firing call then snippet is generated correctly.

**To Reproduce**
1. Go to 'Request'
2. Click on 'Code'
3. See wrong generated code

**Expected behavior**
We expect to see only x-www-form-urlencoded params withhout  **&undefined=**  appended.

**Screenshots**
After firing call, snippet includes  **&undefined=**
<img width="710" alt="screenshot 2019-02-13 at 18 46 37" src="https://user-images.githubusercontent.com/5127910/52732753-3ff93100-2fc1-11e9-8c4b-5e1e3082163e.png">

Before firing call, generated snippet is correct
<img width="711" alt="screenshot 2019-02-13 at 18 59 56" src="https://user-images.githubusercontent.com/5127910/52732954-ca419500-2fc1-11e9-8013-8836ff66de7f.png">

**App information (please complete the following information):**
 -  Native App
 - Postman Version 6.7.3
 - OS:  macOS Mojave 10.14.3

**Comment by numaanashraf** [comment] 2019-02-18 13:10
Thanks for reporting this. We are tracking this at #5809. Please follow that issue for updates.

**Comment by numaanashraf** [comment] 2019-02-18 13:10
Duplicate of #5809

**Closed as completed by numaanashraf** 2019-02-18 13:10 UTC
Labels: duplicate
