### ISSUE TITLE
[Bug] - Using .toString() on a boolean value passes in Postman, but fails in the Runner

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3428] opened 2017-08-22 11:10 UTC
Windows Client, x64. Windows 10.

A true/false value is returned in the response and I'm asserting this value against an environment variable that is also "true" or "false".
Since Postman saves all Env Variables as strings I'm converting the bool in the response to a string and then performing the assertion.

tests["Boolean Value Test"] = path.to.boolean.toString() == environment.boolean;

This test passes fine in Postman, but fails in the runner.

**EDIT:**
If I modify the above test to the below, this will fail in Postman but pass in the runner.
tests["Boolean Value Test"] = path.to.boolean == environment.boolean;

I know this is passing because it's not checking the type, but it's just weird that I'm getting two different results from the Runner and Postman itself.

**Comment by sdnts** [comment] 2017-08-23 08:40
Hi @Faz540 I'm unable to see this.

I set up a little server that sends me back the response:
```
{
    "value": "test",
    "isCorrect": true
}
```
isCorrect here is a boolean.

My test script looks like:
```
var jsonData = pm.response.json();
console.log('Response', typeof jsonData.isCorrect) // Outputs boolean
console.log('Env', typeof environment.test) // Outputs string

tests["Boolean Value Test"] = jsonData.isCorrect.toString() == environment.test;
```

This test passes in the main app as well as the runner. I see your test script, can you post what your server sends back? It doesn't have to be real data, just something you see this with so I can replicate on my end.

**Comment by Faz540** [comment] 2017-08-23 08:56
Response is returning:
`{
	"onSale": true
}`

I then save that value as an Environment Variable called "available" which has a value "true" as it's now a string.

If I hit the endpoint again and assert the boolean returned in the response against the environment variable saved in the main app, the below test fails:

```
var response = JSON.parse(responseBody);
tests["On Sale = " + environment.available] = response.onSale == environment.onSale;
```

**Comment by sdnts** [comment] 2017-08-23 09:29
@Faz540 Did you remove the `toString()` call? From what you said, it looks like you're doing what I did in my example. Can you try using my code and see if that works?

The `==` will not work since `true != "true"` in JS

**Comment by Faz540** [comment] 2017-08-23 09:43
Hi, yes I removed it for the example as that test will fail in the main app but pass in the Runner.

Whereas, if I use the test below:
```
var response = JSON.parse(responseBody);
tests["On Sale = " + environment.available] = response.onSale.toString() == environment.onSale;
```

This will pass in the main app but fail in the runner
![image](https://user-images.githubusercontent.com/9334128/29609569-8bf340c6-87ef-11e7-8b31-01bac09fb599.png)

A section of the response returned.
![image](https://user-images.githubusercontent.com/9334128/29609588-97357512-87ef-11e7-9fd1-8ef06a706b21.png)

And to answer the above, I thought true == "true" would pass I'm not testing the type, just the value. I know true === "true" would definitely fail as they're not the same type.

**Comment by sdnts** [comment] 2017-08-23 11:55
@Faz540, I changed my server to return `{ "onSale": true }`

I also have an environment variable called `available`, whose value is set to true (not from the UI, via `postman.setEnvironmentVariable('available', response.onSale)`

My test script, like yours, looks like:
```
var response = JSON.parse(responseBody);
tests["On Sale = " + environment.available] = response.onSale.toString() == environment.available;
```
I changed the variable names here, but the gist should be the same. This passes on both the main app and the runner.

Is your environment variable called `available` or `onSale`? Can you check your scripts once?
Also, are you supplying an environment when starting the run in the Runner?

**Comment by Faz540** [comment] 2017-08-23 12:57
@madebysid messaged you on Slack to show you the API response

**Comment by sdnts** [comment] 2017-08-23 13:29
Isolated this as an issue with `pm.environment.set`. Using postman.setEnvironmentVariable instead when setting the variable should solve this.
A fix for this will be out with the next release.

**Comment by abhijitkane** [comment] 2017-09-11 11:16
@Faz540 This has been fixed in 5.2.0.

**Comment by Faz540** [comment] 2017-10-13 08:04
I'm able to reproduce this on windows client 5.3.0
`
{
	 "isRestricted": false
}
`
Given I have the above response in an endpoint. 
I hit the GET request and save the value as a postman variable.
`
var response = JSON.parse(responseBody);
postman.setEnvironmentVariable("myBoolean", response.isRestricted);
`

I duplicate the endpoint but this time I'm asserting that the value returned in the response matches my postman variable.

`
tests["Is Restricted = SAVED VALUE"] = response.isRestricted.toString() == environment.myBoolean;
`
This passes in Postman, but in the runner this will fail.

If I get rid of the .toString() the opposite will happen. 
`
tests["Is Restricted = SAVED VALUE"] = response.isRestricted == environment.myBoolean;
`
The above will fail in Postman but pass in the runner.

Now, if I add the below code
`
    console.log(typeof environment.myBoolean);
    console.log(typeof response.isRestricted.toString());
`

When the test is ran in Postman, console outputs:
![image](https://user-images.githubusercontent.com/9334128/31535837-7b3edefc-aff4-11e7-9635-010322d3f44c.png)
When the test in ran in the Runner, console outputs:
![image](https://user-images.githubusercontent.com/9334128/31535847-86628a72-aff4-11e7-8a7b-1895913e7bb2.png)

Hopefully this now gives you enough information.

**Comment by Faz540** [comment] 2017-10-17 13:08
@madebysid Can this isssue be re-opened or shall I create a new ticket?

**Comment by sivcan** [comment] 2018-08-14 08:22
@Faz540 This issue is not reproducible on the latest version of Postman i.e 6.2.4 as of now.
As per your comment https://github.com/postmanlabs/postman-app-support/issues/3428#issuecomment-336380713

Here's a collection to test this:
https://www.getpostman.com/collections/6ef32b8a715d7aa98079

Note: Incase you're testing the above mentioned collection then you'll be needing to setup the environment too.

The test is passing in both requester and runner with correct type of variables being printed in console.

Irrespective of using `pm.environment.set` or `postman.setEnvironmentVariable` api's, both are working fine.

Can you test it out and let me know?

**Comment by sivcan** [comment] 2018-08-20 07:36
I'll be closing this issue, let me know if you're still able to reproduce this.

Thanks.

**Closed as completed by sivcan** 2018-08-20 07:36 UTC
Labels: bug

**Comment by rwuttke-dxc** [comment] 2020-02-24 04:26
I know this is closed @sivcan, but I have been able to reproduce this in

Postman v 7.18.1 and pure Newman 4.5.7

And have just added this code in

const switchOn = pm.environment.get('FeatureSwitchTest');
    if (switchOn === true || switchOn === 'true') {

This works nicely in both envs.
