### ISSUE TITLE
Postman v7.0.9 crashes when deleting daily requests

### ISSUE THREAD

**Issue by Crypt32** [a85/POSTMan-Chrome-Extension#6479] opened 2019-05-12 11:47 UTC
**Describe the bug**
When deleting daily request group (in request history pane), the app crashes. Actually, history for selected day is deleted, but error page is shown.

**To Reproduce**
1. Open Postman, make one or more request to generate items in hostory
2. on Request History pane, navigate to day group header
3. when trash icon appears, press it
![Untitled](https://user-images.githubusercontent.com/6384119/57581755-b32d1900-74c4-11e9-8c5d-08b0416fd359.png)

**Expected behavior**
App should not crash

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.0.9
 - OS: Windows 10

**Additional context**

**Comment by sujayvenaik** [comment] 2019-05-13 08:50
Duplicate of #6378

**Closed as completed by sujayvenaik** 2019-05-13 08:50 UTC
