### ISSUE TITLE
URL path variables are not replaced if followed by a dot

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#4423] opened 2018-04-06 14:56 UTC
## App Details:

```
Postman for Windows
Version 6.0.10
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Always

 2. Expected behaviour:
URL parameter is replaced

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
GET
https://example.com/api.ashx/v2/threaddata/:threadId.json
```

 4. Screenshots (if applicable)

Enter the URL `https://example.com/api.ashx/v2/threaddata/:threadId.json`
Set the threadId parameter to 1234
Click Send
Observe that URL parameter is not replaced

I would expect there to be some way of wrapping the parameter name.
I tried using `{{threadId}}`, `:{threadId}`, `:threadId:` and `{:threadId}` but none of these worked.

**Comment by harryi3t** [comment] 2018-06-29 12:41
@errorx666 Will it be possible for you to use environment, global or collection variables instead of path variables? That is the more recommended way of using variables.

**Comment by ghost** [comment] 2018-06-29 17:59
It would be very inconvenient to do so, as `threadId` would need to change frequently (each request).

I'm working with a platform (Telligent Community Server) that uses this URL format for all of its APIs: `.json` suffix for a JSON response, `.xml` suffix for an XML response.

**Comment by kamalaknn** [comment] 2018-07-02 06:16
Hi @errorx666 

We could see two parts to this issue.

1. The variable in URL `https://example.com/api.ashx/v2/threaddata/:threadId.json` is not replaced. We will look into this. But since there is no proper specification on this format of templating there could be more of these scenarios that aren't defined how it should behave.
2. The alternative is to use the `{{variable}}` syntax. To use them you have to define the variable in environment, collection or globals. We are trying to improve the experience working with environments with [sessions](https://community.getpostman.com/t/sessions-in-postman/1925) and other improvements. Please have a look.

Thanks.

**Comment by ghost** [comment] 2018-07-02 15:25
These are possible workarounds.  It feels less "correct" to me to change globals or the environment in order to pass a parameter to a single query.
Further, this scales extremely poorly.  I'm going to end up with a global variable for each possible query parameter across all queries, and each variable will only be applicable to a few queries.

**Comment by shamasis** [comment] 2018-07-04 13:31
@errorx666 - there is a bug that the path variable with trailing `.` - however there are two issues:

1. The path variable name is free-form (i.e. there is a start identifier, but no end-identifier)
2. There is no definite way to isolate the variable name from URL without making some assumptions.

I suggest we set some assumptions and for anything else recommend using double braces standard that is everywhere else in Postman.

**Comment by numaanashraf** [comment] 2018-07-12 12:38
@errorx666 This seems related to #2427. I'm closing this and let's continue this discussion on the original issue.

**Closed as completed by numaanashraf** 2018-07-12 12:38 UTC
Labels: bug

**Comment by agaonkar-cleo** [comment] 2019-09-26 11:42
Do we have a solution for this problem? I am also facing the same problem.

**Comment by SzymonDukla** [comment] 2019-10-02 11:55
Same here, apparently it was fixed in 7.2.0 but now is again broken

**Comment by codenirvana** [comment] 2019-10-02 12:57
@agaonkar-cleo @SzymonDukla Can you share steps to reproduce this issue?

Not reproducable in v7.8.0:

<img width="942" alt="Screenshot 2019-10-02 at 6 24 48 PM" src="https://user-images.githubusercontent.com/4865836/66045799-0e2dde00-e542-11e9-9d98-0f4c79e822fe.png">

**Comment by ghost** [comment] 2019-10-03 11:59
@codenirvana I can see the issue in your screenshot.  The path variable name should be `get`, not `get.json`, and the URL should end in `.json`

**Comment by jayarjo** [comment] 2020-06-12 11:42
This issue is still actual

**Comment by Lechus** [comment] 2020-11-13 14:26
This issue is still actual

**Comment by jjercx** [comment] 2021-09-08 22:58
Yes, can this be reopened?
