### ISSUE TITLE
Importing using curl does not implement method (gives default GET)

### ISSUE THREAD

**Issue by yiiness** [a85/POSTMan-Chrome-Extension#6790] opened 2019-06-26 16:48 UTC
**Describe the bug**
Importing using curl does not implement method (gives default GET)

**To Reproduce**
Importing using curl raw string copied from chrome request

**App information (please complete the following information):**
- Native app
- v7.2.2 have bug
- v6.7.4 and v7.2.0 have not bug
- OS: win7x64

**Comment by abhijitkane** [comment] 2019-06-27 06:59
@yiiness I'm not able to reproduce this. Importing `curl -X POST http://google.com` creates a POST request.

Can you paste the raw curl string you're trying to import?

**Comment by preethammavin** [comment] 2019-07-03 05:56
@yiiness closing the issue for now, as it is not reproducible at our end  and with the information we have we are unable to address it. Do feel free to reopen the issue with the requested information so that we can address it.

**Closed as completed by preethammavin** 2019-07-03 05:56 UTC

**Comment by goffreder** [comment] 2019-07-31 08:39
I'm having the same issue though, I'm copying as cURL from Chromium, and pasting into Postman as raw text. It looks like Postman ignores the fact that having the `-d` or `--data` flag set implies a POST request, as per cURL documentation.

I'm using Postman v7.3.4, issue was present also on v7.3.2. v6.7.3 works fine though.

I'll paste here a reproducible example as soon as I can.
