### ISSUE TITLE
How do I use environment variable for a simple string search test in Postman?

### ISSUE THREAD

**Issue by bigbigmike** [a85/POSTMan-Chrome-Extension#3139] opened 2017-06-08 16:12 UTC
## App Details:

```
Version 4.11.0
```

## Issue Report:

...
Hello.  I am struggling to reference an environment variable string value in my postman tests.  I have looked through the test documentation and other threads but unable to find a working solution.  

I have a json response that includes names of jar files in the result.
```
  "result" : [ {
    "jarFile" : "Test1.jar",
    "fileSize" : "633437",
    "description" : "Test File 1",
    "type" : "Application Component",
    "platform" : "windows,solaris,linux"
  }, {
    "jarFile" : "Test2.jar",
    "fileSize" : "1528213022",
    "description" : "Manager",
    "type" : "mgsrv",
    "platform" : "windows"
  }, {
    "jarFile" : "Test3.jar",
    "fileSize" : "14504949",
    "description" : "Tools and Utilities",
    "type" : "apiserver",
    "platform" : "windows,solaris,linux"
  }
```

If I use this test snippet with the exact string, I am able to find the string,  
`tests["Body matches string"] = responseBody.has("Test2.jar");`

However; i am trying to use an environment variable for the jar file name and the tests do not work. 
Some of the attempts are as follows.  Environment variable name is "compName".

```
tests["Body matches string"] = responseBody.has`(('<compName>'));`

var jsonData = JSON.parse(responseBody);
tests["Contents"] = environment.compName == jsonData.jarFile;
```

**Comment by kamalaknn** [comment] 2017-06-09 05:54
Hi @bigbigmike ,

You can use `postman.getEnvironmentVariable()` to get the value of an environment variable.

This snippet should serve as a guideline for what you are trying to achieve.

```js
var jsonData = JSON.parse(responseBody),
      compName = postman.getEnvironmentVariable('compName'),
      matchingFile = _.find(jsonData.result, { jarFile: compName });

tests["Body matches string"] = !_.isEmpty(matchingFile);
```

Pro tip: You can also use `console.log` in scripts and see them in the Postman Console(`View -> Show Postman Console`).

Hope this helps. 

I am closing this issues as it is not a bug with the Postman app itself.

Thanks.

**Closed as completed by kamalaknn** 2017-06-09 05:54 UTC

**Comment by bigbigmike** [comment] 2017-06-21 20:02
Thank you for the example.  This works perfectly.
