### ISSUE TITLE
default selected tab in a request

### ISSUE THREAD

**Issue by charlitos85** [a85/POSTMan-Chrome-Extension#8890] opened 2020-08-05 21:36 UTC
**Is your feature request related to a problem? Please describe.**
Every time I open a request from a collection is selected the params tab, so need to select the body tab.

**Describe the solution you'd like**
Give the possibility to define in the settings of postman what tab I will want to be selected every time a request is open.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by codenirvana** [comment] 2020-08-06 05:53
Duplicate of #2086

**Closed as completed by codenirvana** 2020-08-06 05:53 UTC
Labels: feature, duplicate, product/runtime
