### ISSUE TITLE
JSON request body not working with PHP service

### ISSUE THREAD

**Issue by alvarotrigo** [a85/POSTMan-Chrome-Extension#4325] opened 2018-03-12 22:39 UTC
## App Details:

```
Version 5.5.2
OS X / x86-64
Chrome 64.0.3282.186
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:

I always found it crazy trying to send JSON data to PHP. Never managed to find the way. It sounds pretty basic and simple but... just can't get to do it when using PHP.

 2. Expected behaviour:

```php
array('name' => 'demo')
```

Obtained result:
```php
array();
```

 4. Screenshots (if applicable)

![screen shot 2018-03-12 at 23 36 12](https://user-images.githubusercontent.com/1706326/37313138-3237fcf4-264e-11e8-9ab3-4614270a6a86.png)
![screen shot 2018-03-12 at 23 35 53](https://user-images.githubusercontent.com/1706326/37313145-364b839c-264e-11e8-911e-085f6732c7cb.png)

**Steps to reproduce it:**

Open postman
Write a url
Select POST method.
Go to "body" tab
Select raw
Paste {"name":"demo"}
Select JSON (Application/JSON)
Click Send

On the PHP side, post to this file:
```php
<?php
print_r($_REQUEST);
```

**Comment by alvarotrigo** [comment] 2018-03-12 22:40
I've also tried using a php file like this with same results:

```php
<?php
$data = json_decode(file_get_contents('php://input'), true);
print_r($data);
```

I found plenty of people asking for this same problem on stackoverflow, but none of the comments helped me.

**Comment by harryi3t** [comment] 2018-06-29 13:00
This does not seem to be a bug on Postman side. Postman is correcting sending the data and has no control over how the server is parsing it.

**Comment by georgeholt** [comment] 2018-07-26 14:50
@harryi3t I don't think so because I've had this issue with Postman for ages. I have never been able to get one of these requests to work in Postman. You could be right, but then why are so many people having issues with this? Are there limitations or rules to using the raw json posting features that we aren't aware of?

I've created a test page using AJAX to post the request I'd like to make to my server and that works perfectly fine, but the moment I try it in Postman it doesn't.
It's as if Postman clears the post data before making the request to the server because if I dump the request data on the server side I get nothing back if I make the request through Postman!

Out of interest this is the script I'm using to send the AJAX request:

```js
const $requestForm = document.getElementById('requestForm');
const $requestJson = document.getElementById('requestJson');

$requestForm.addEventListener('submit', function(e) {
    e.preventDefault();

    const xhr = new XMLHttpRequest();

    xhr.open('POST', $requestForm.action, true);
    xhr.setRequestHeader('Content-Type', 'application/json')
    xhr.onload = function() {
        console.dir(xhr);
    };
    xhr.send(JSON.stringify($requestJson.value));
});
```

And the server simply dies with the request body:

```php
die(file_get_contents('php://input'));
```

Works using the AJAX script, doesn't using Postman.

**Comment by zinczinc** [comment] 2018-08-17 17:04
I have the same issue. Posting the following does not work. I tried several times in vain. The value is always null server-side:

    {
	    "userDetails": [
		    { "Name": "Von", "Qty": 25 },
		    { "Name": "Peter", "Qty": 15 }
		    ]
    }

I wonder why @harryi3t closed this, while the issue is real. I would have expected him to support his closing by some example of how and where it works.

**Comment by numaanashraf** [comment] 2018-08-17 17:42
@zinczinc @georgeholt We are having trouble replicating this at our end and based on our tests, Postman's sends the correct request to the service. We'll post a detailed account of how we ran these tests. In the meantime, could you share the PHP version you are using?

**Comment by numaanashraf** [comment] 2018-08-17 17:45
@zinczinc @georgeholt @alvarotrigo I've reopened this and have modified the title to better reflect the actual issue.

**Comment by abhijitkane** [comment] 2019-01-07 14:50
Acc. to http://php.net/manual/en/reserved.variables.post.php, $_REQUEST and $_POST are only for multipart-form / urlencoded POST bodies.

I'm using Slim v2 locally, and the following controller definition successfully returned the decoded JSON:
```
$app->post('/posttest', function () use ($app) {
    print_r(json_decode(file_get_contents("php://input")));
});
```

In Postman:
<img width="838" alt="screen shot 2019-01-07 at 20 19 45" src="https://user-images.githubusercontent.com/681190/50774499-9c2dae80-12b9-11e9-854e-54b4f9c2c965.png">

@alvarotrigo Is `file_get_contents("php://input")` not working for you?

**Comment by numaanashraf** [comment] 2019-02-03 08:06
We are closing this due to inactivity. Do let us know if you are still facing this issue.

**Closed as completed by numaanashraf** 2019-02-03 08:06 UTC
Labels: support

**Comment by ghaith4** [comment] 2019-10-29 16:49
just change http:// to https:// and it'll work for you, post request requires https

**Comment by ricardocosta43** [comment] 2023-04-28 17:54
> basta alterar http:// para https:// e funcionará para você, a permissão de postagem requer https


Really localhost doesn't work for some reason
