### ISSUE TITLE
Create UIDs for requests, so that they can be referred to outside of display name

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5986] opened 2019-02-26 01:01 UTC
**ISSUE:**
`pm.setNextRequest()` requires the target request's name to work. However, if the request name is changed for any reason the string must be updated in all Test / Pre-request scripts where it is used.

**PROPOSED SOLUTION**
By having UIDs for all requests, request names could be changed as needed while not affecting any Sandbox scripts that rely on them.

Seems like these could be:
a) Procedurally generated upon request creation
b) User-defined (as needed)
c) a + b (requests all have a UID generated, but this can be changed)

**CURRENT WORKAROUNDS**
1. Use find and replace to update script contents with new request names (manual, potentially hazardous if not done carefully)
2. Store the request name in a Global or Environment variable, and have scripts get the actual request name from there. (safer, but more manual to set up and update)

**Comment by numaanashraf** [comment] 2019-02-26 15:47
Duplicate of #5908

**Closed as completed by numaanashraf** 2019-02-26 15:47 UTC
Labels: duplicate
