### ISSUE TITLE
vscode extension reload data error

### ISSUE THREAD

**Issue by muhammedfurkan** [a85/POSTMan-Chrome-Extension#12585] opened 2024-01-15 04:55 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when I login to my postman account my collection doesnt load.

### Steps To Reproduce

```
(2024-01-15T04:50:30.543Z) [info] [extension] Extension activation started: 1705294230539
(2024-01-15T04:50:30.562Z) [info] [extension] Extension activation completed: 1705294230562
(2024-01-15T04:50:30.562Z) [info] [extension] Extension activation took 23ms
(2024-01-15T04:50:32.922Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2024-01-15T04:50:32.922Z) [info] [extension:htmlProvider] get sidebar HTML
(2024-01-15T04:50:32.925Z) [info] [extension:workspaceContext] Found the record in the cache
(2024-01-15T04:50:41.652Z) [info] [extension:secretManager] Removing the account data
(2024-01-15T04:50:41.655Z) [info] [extension:globalStateManager] clearing storage
(2024-01-15T04:50:41.659Z) [info] [extension:sidebar:manager] setting the view to login app
(2024-01-15T04:50:41.659Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"login"}
(2024-01-15T04:50:43.196Z) [info] [extension:sidebar:manager] set login state to busy
(2024-01-15T04:50:43.197Z) [info] [extension:auth] Starting the login flow
(2024-01-15T04:52:13.666Z) [info] [extension:auth] Handing the URL redirect to VSCode
(2024-01-15T04:52:13.666Z) [info] [extension:auth:client] finalising the auth handover
(2024-01-15T04:52:15.576Z) [info] [extension:auth] The sign in flow has finished successfully
(2024-01-15T04:52:16.419Z) [info] [extension:sidebar:manager] setting the view to sidebar app
(2024-01-15T04:52:16.419Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2024-01-15T04:52:16.419Z) [info] [extension:htmlProvider] get sidebar HTML
(2024-01-15T04:52:16.423Z) [info] [extension:workspaceContext:networkClient] fetch recent workspaces: {"baseUrl":"https://bifrost-extension-https-global.gw.postman.com/ws/proxy"}
(2024-01-15T04:52:25.667Z) [error] [extension:sidebar:manager:history-sidebar] Error: Failed to get history items: {"stack":"\n    in $t\n    in p\n    in div\n    in styled.div\n    in a\n    in f\n    in qt\n    in Suspense\n    in Ke\n    in Suspense\n    in div\n    in styled.div\n    in div\n    in styled.div\n    in nav\n    in styled.nav\n    in k\n    in Er\n    in st\n    in lt\n    in At\n    in Ot\n    in Pt\n    in h\n    in l\n    in Xe\n    in le\n    in ee\n    in ne\n    in ft\n    in o\n    in a\n    in f\n    in StrictMode","appId":"history-sidebar","errorElementId":"history-sidebar"}
```

### Operating System

macOS

### Postman Version

0.17.0

### Postman Platform

Other

### User Account Type

Signed In User

### Additional Context?

```
(2024-01-15T04:50:30.543Z) [info] [extension] Extension activation started: 1705294230539
(2024-01-15T04:50:30.562Z) [info] [extension] Extension activation completed: 1705294230562
(2024-01-15T04:50:30.562Z) [info] [extension] Extension activation took 23ms
(2024-01-15T04:50:32.922Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2024-01-15T04:50:32.922Z) [info] [extension:htmlProvider] get sidebar HTML
(2024-01-15T04:50:32.925Z) [info] [extension:workspaceContext] Found the record in the cache
(2024-01-15T04:50:41.652Z) [info] [extension:secretManager] Removing the account data
(2024-01-15T04:50:41.655Z) [info] [extension:globalStateManager] clearing storage
(2024-01-15T04:50:41.659Z) [info] [extension:sidebar:manager] setting the view to login app
(2024-01-15T04:50:41.659Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"login"}
(2024-01-15T04:50:43.196Z) [info] [extension:sidebar:manager] set login state to busy
(2024-01-15T04:50:43.197Z) [info] [extension:auth] Starting the login flow
(2024-01-15T04:52:13.666Z) [info] [extension:auth] Handing the URL redirect to VSCode
(2024-01-15T04:52:13.666Z) [info] [extension:auth:client] finalising the auth handover
(2024-01-15T04:52:15.576Z) [info] [extension:auth] The sign in flow has finished successfully
(2024-01-15T04:52:16.419Z) [info] [extension:sidebar:manager] setting the view to sidebar app
(2024-01-15T04:52:16.419Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2024-01-15T04:52:16.419Z) [info] [extension:htmlProvider] get sidebar HTML
(2024-01-15T04:52:16.423Z) [info] [extension:workspaceContext:networkClient] fetch recent workspaces: {"baseUrl":"https://bifrost-extension-https-global.gw.postman.com/ws/proxy"}
(2024-01-15T04:52:25.667Z) [error] [extension:sidebar:manager:history-sidebar] Error: Failed to get history items: {"stack":"\n    in $t\n    in p\n    in div\n    in styled.div\n    in a\n    in f\n    in qt\n    in Suspense\n    in Ke\n    in Suspense\n    in div\n    in styled.div\n    in div\n    in styled.div\n    in nav\n    in styled.nav\n    in k\n    in Er\n    in st\n    in lt\n    in At\n    in Ot\n    in Pt\n    in h\n    in l\n    in Xe\n    in le\n    in ee\n    in ne\n    in ft\n    in o\n    in a\n    in f\n    in StrictMode","appId":"history-sidebar","errorElementId":"history-sidebar"}

```

**Comment by pankajk07** [comment] 2024-02-09 06:09
Hi @muhammedfurkan can you please also share a screen recording for the same as it would help us debug the issue?

**Comment by muhammedfurkan** [comment] 2024-02-09 06:17
> Hi @muhammedfurkan can you please also share a screen recording for the same as it would help us debug the issue?


https://github.com/postmanlabs/postman-app-support/assets/9547040/03a139dd-f7bb-40b3-af70-4970027e650a

**Comment by pankajk07** [comment] 2024-08-06 08:05
Closing this as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/12254

**Closed as completed by pankajk07** 2024-08-06 08:05 UTC
Labels: bug, duplicate, product/ide-platform, vscode
