### ISSUE TITLE
How I can configre the destination Directory

### ISSUE THREAD

**Issue by Kirchmayer** [a85/POSTMan-Chrome-Extension#4141] opened 2018-02-02 06:05 UTC
We will install Postman on lots of PC´s with different user.

So we will install Postman on Windows in the Directory C:\Program Files (x86) but we can´t configure this.

How can we made it ?

**Comment by Anton-V-K** [comment] 2018-02-02 10:08
Same as #3019

**Comment by sdnts** [comment] 2018-02-26 13:08
@Kirchmayer As @Anton-V-K said, we've been looking into MSI packages for Windows app distribution. When that comes in, you should be able to select a destination for app data. I'm closing this as duplicate of #3019, please follow that thread for updates :)

**Closed as completed by sdnts** 2018-02-26 13:08 UTC

**Comment by number005** [comment] 2019-06-14 10:08
Why is this closed? I can still not decide where to install to?
