### ISSUE TITLE
Upload file support in GraphQL 

### ISSUE THREAD

**Issue by bipinct** [a85/POSTMan-Chrome-Extension#8156] opened 2020-03-07 11:18 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sankalp0o** [comment] 2020-03-09 06:26
@bipin000 can you elaborate on the problem you're facing?

**Comment by numaanashraf** [comment] 2020-03-11 06:17
@bipin000 We are tracking this at #7072

**Comment by numaanashraf** [comment] 2020-03-11 06:17
Duplicate of #7072

**Closed as completed by numaanashraf** 2020-03-11 06:17 UTC
Labels: duplicate
