### ISSUE TITLE
S3 SignatureDoesNotMatch if port number present in URL

### ISSUE THREAD

**Issue by JumpyKitten** [a85/POSTMan-Chrome-Extension#3391] opened 2017-08-16 00:47 UTC
## App Details:
Postman for Linux
Version 5.1.3
linux 4.10.0-32-generic / x64

## Issue Report:
When I send this request to AWS it succeeds:
http://mybucket.s3.amazonaws.com/Hello.txt
By just adding the port number, it fails with SignatureDoesNotMatch:
http://mybucket.s3.amazonaws.com:80/Hello.txt

This make Postman unusable with S3-compatible service that does not use the default port number.

**Comment by harryi3t** [comment] 2017-08-16 07:21
Hi @JumpyKitten 
I tried to repro this.
I have created a bucket on AWS and uploaded an image with public read access
But I am able to see the image using both URLs from Postman
```
http://s3.amazonaws.com/test-github-issue-3391/postman_icon.png
http://s3.amazonaws.com:80/test-github-issue-3391/postman_icon.png
```

![image](https://user-images.githubusercontent.com/5207331/29351776-c9c70798-8281-11e7-93c3-1df38b76737e.png)

Could you try these on your end? It will help us to narrow down the issue.

**Comment by JumpyKitten** [comment] 2017-08-16 17:09
You used "No Auth" for anonymous access. I am using "AWS Signature" which causes Postman to generate S3 Signature V4. Also, you used path-style access, while I use virtual hosted-style access.

**Comment by JumpyKitten** [comment] 2017-08-16 17:37
Here are screenshots:
![image](https://user-images.githubusercontent.com/13560014/29376735-65b40534-826e-11e7-8bc2-5ce3080185b5.png)
![image](https://user-images.githubusercontent.com/13560014/29376745-6be7e010-826e-11e7-97c0-cfc4518b8a8d.png)

Note that since request header X-Amz-Content-Sha256 is required, I have to add it manually for a zero-byte body, which is "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855". (It would have been nice if Postman will automatically add it. But that's another story.)

**Comment by harryi3t** [comment] 2017-08-18 08:14
@JumpyKitten Oh right, this would happen only for signed request.
I have reproduced this bug. 

This happens because `aws` is taking port as part of host
![image](https://user-images.githubusercontent.com/5207331/29449930-4cfd560a-841a-11e7-844e-91c9eb678c3c.png)
And the npm module we are using, [aws4](https://www.npmjs.com/package/aws4) mentions that the parameters are supposed to be `http.request` compatible
![image](https://user-images.githubusercontent.com/5207331/29449966-79ec158e-841a-11e7-9baa-9ad7d49deb1a.png)
And the docs for http.request mentions that 
```
```


We are working on a fix and release a fix in upcoming releases.

**Comment by harryi3t** [comment] 2017-08-18 08:49
@JumpyKitten Oh right, this would happen only for signed request.
I have reproduced this bug. 

We are working on a fix and would release a fix in the upcoming release. Will keep you posted.

### What was the issue
This happens because `aws` is taking port as part of host
![image](https://user-images.githubusercontent.com/5207331/29449930-4cfd560a-841a-11e7-844e-91c9eb678c3c.png)

And the npm module we are using, [aws4](https://www.npmjs.com/package/aws4) mentions that the parameters are supposed to be `http.request` compatible
```js
// given an options object you could pass to http.request 
var opts = {host: 'sqs.us-east-1.amazonaws.com', path: '/?Action=ListQueues'}
```

And the [docs for http.request](https://nodejs.org/api/http.html#http_http_request_options_callback) mentions that 
```
host <string> A domain name or IP address of the server to issue the request to. Defaults to localhost
```
So from our end port was not being included and aws was expecting it.

**Comment by harryi3t** [comment] 2017-08-18 08:55
~Closing this since this is a duplicate issue of https://github.com/postmanlabs/postman-app-support/issues/2566~

~Will post the updates on the original issue.~
Sorry, that issue is a different one.

**Closed as completed by harryi3t** 2017-08-18 08:55 UTC
Labels: bug, Auth

**Comment by harryi3t** [comment] 2017-09-04 10:20
In Postman 5.2.0 this is fixed.
Please re-open if still facing the issue
