### ISSUE TITLE
Cookie not being set when set-cookie header is returned (Mac App v4.5.0)

### ISSUE THREAD

**Issue by DCRichards** [a85/POSTMan-Chrome-Extension#2258] opened 2016-08-13 12:09 UTC
1. Postman Version: 4.5.0 (4.5.0)
2. App (Chrome app or Mac app): Mac app
3. OS details: Mac OSX 10.11.5
4. Is the Interceptor on and enabled in the app: N/A (Mac app)
5. Did you encounter this recently, or has this bug always been there: Recent but not tried before
6. Expected behaviour: Cookie should be set and visible in _Manage Cookies_
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): No relevant content in the logs as the request is otherwise successful
8. Screenshots (if applicable)

Steps to reproduce the problem:
1. Make a request where the `Set-Cookie` header is returned by the request
2. On successful request the headers show the set-cookie header as follows:
   
   `set-cookie →<cookie-name>=<data>; Domain=localhost; Path=/; Expires=Sat, 20 Aug 2016 10:41:38 GMT; HttpOnly`
3. Check the Cookies tab and see 'No cookies were returned from the server' and check _Manage Cookies_ to see nothing in the list either.

Note that setting the cookie **manually** in _Manage cookies_ successfully sets the cookie and the cookie is then shown in the Cookies tab in subsequent requests, so the cookie data itself is valid. Making calls to the same API with the **Chrome App** does not appear to suffer from this issue.

**Comment by abhijitkane** [comment] 2016-08-13 12:15
@DCRichards  Can you change the `localhost` to `127.0.0.1`? There's a problem with the underlying cookie layer that prevents cookies from being set on localhost. If there's still an issue, we'll be pushing an update today that solves other cookie-related issues too.

**Comment by shamasis** [comment] 2016-08-13 18:49
This should be resolved now - v4.6. Closing. Please reopen if otherwise.

**Comment by kavare** [comment] 2017-04-07 10:08
After updating to `4.10.5` recently this issue happens again. The cookie is not being set even `set-cookie` header presents. 

I am on a MacOS and not using `localhost` (using my local domain name assign to `127.0.0.1`

**Comment by numaanashraf** [comment] 2017-04-07 21:44
Hi @kavare, this is addressed in `v4.10.6` that is out for Postman native apps now. Could you update and let us know if the issue is resolved?

**Closed as completed** 2017-04-08 16:24 UTC

**Comment by kerembaydogan** [comment] 2017-04-14 08:48
Same issue here.
Mac Native App - Version 4.10.7 (4.10.7).  (Full uninstall/reinstall)

**Comment by kamalaknn** [comment] 2017-04-14 09:31
Hi @kerembaydogan, can you attach a screenshot of the Postman Console (View -> Show Postman Console) with the response headers or copy paste the `set-cookie` header where you see this?

This will help us narrow down the issue. We haven't been seeing this in all the requests.

**Comment by kerembaydogan** [comment] 2017-04-17 07:30
Hi @kamalaknn here is the screenshot. Please let me know if you need additional detail.

<img width="957" alt="screenshot at apr 17 10-27-16" src="https://cloud.githubusercontent.com/assets/3845600/25082334/c6eeaa54-2358-11e7-9291-7e5c673fea18.png">

**Comment by kdvlr** [comment] 2017-05-26 21:37
I have the same problem on Windows and Chrome as well. I cannot see the cookie. It does show in the console though. 

Version Info: 
Postman for Chrome
Version 4.10.7
win / x86-64
Chrome 58.0.3029.110

![image](https://cloud.githubusercontent.com/assets/19178546/26513519/885375d4-4231-11e7-8232-14e589ed20a0.png)
