### ISSUE TITLE
Unable to use conditional statements with pm.* API

### ISSUE THREAD

**Issue by guestz0r** [a85/POSTMan-Chrome-Extension#3686] opened 2017-10-27 14:21 UTC
## App Details:
Postman for Mac
Version 5.3.1
OS X 16.7.0 / x64

## Issue Report:
Hello, I have originally asked my question here:
https://stackoverflow.com/questions/46929974/how-to-use-conditional-statement-with-postmans-new-pm-api

I'm having problem with fully moving my test scripts to pm.* API as I cannot get a conditional statement to work. Here is an example of my old test script and the new one:

Old:
```
if(tests["Status code is 200"] = responseCode.code === 200) {

var token = postman.getResponseHeader("Authorization"); 
postman.setEnvironmentVariable("JWT Token", token.substr(7)); 

tests["Body is empty"] = responseBody.length === 0; 
}
```

And here's a new one:
```
if(pm.test("Status code is 200", function() {pm.expect(pm.response.code).to.equal(200);
})){

var token = pm.response.headers.get("Authorization");
pm.environment.set("JWT Token", token.substr(7));

pm.test("Response body is empty ", function () {
    pm.expect(pm.response.text().length).to.equal(0);
});
}
```

In the new script, if I change to.equal() to 300 so the first test fails, it won't matter as the next test will be run anyway and the variable will be created.

I tried to debug this by using
`console.log(pm.test("Status code is 200", function() {pm.expect(pm.response.code).to.equal(300)}));`

but an empty object is returned instead of true/false.

Can this actually be done with pm.* API? If not, then this would greatly diminish the value of it as I'd like to perform some tests only when other pass.

Cheers!

**Comment by kamalaknn** [comment] 2017-10-30 07:36
@guestz0r you are seeing this because `pm.test` does not return the result of the test. This is because you can have multiple assertions in one `pm.test` and those are executed asynchronously.

That said, the `pm.test` is a much more powerful API and you should be able to do a lot more with this.

To give an example, this would be the equivalent of your code example with the new `pm.test`
```
pm.test("Status code is 200", function() {
  pm.expect(pm.response.code).to.equal(200);
});


(pm.response.code === 200 ? pm.test : pm.test.skip)('Body is empty', function () {
    var token = pm.response.headers.get("Authorization");
    pm.environment.set("JWT Token", token.substr(7));

    pm.test("Response body is empty ", function () {
        pm.expect(pm.response.text().length).to.equal(0);
    });
});
```

I'm closing this issue as this is not a bug with the app itself. Feel free to continue discussion on this ticket.

**Closed as completed by kamalaknn** 2017-10-30 07:36 UTC
Labels: code-generator

**Comment by guestz0r** [comment] 2017-10-30 10:16
Thank you for the detailed answer, @kamalaknn, this helps a lot
