### ISSUE TITLE
Postman icon not displaying in taskbar

### ISSUE THREAD

**Issue by amurad** [a85/POSTMan-Chrome-Extension#3372] opened 2017-08-10 22:49 UTC
## App Details:

```
Postman for Windows
Version 5.1.3
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
For quite some time
 2. Expected behaviour:
Postman icon should be displayed in taskbar instead of generic document icon.

 3. Console logs:
No message in console.log

 4. Screenshots (if applicable)
On Desktop
![image](https://user-images.githubusercontent.com/2021240/29195348-a66fbff2-7df3-11e7-8218-1f2b770e300c.png)

On Taskbar
![image](https://user-images.githubusercontent.com/2021240/29195379-d25dfd22-7df3-11e7-8b82-9f915853e228.png)

Launch postman

**Comment by prashantagarwal** [comment] 2017-08-15 06:24
@amurad this issue is a duplicate of #3107 .We have suggested a way to fix this in that issue.

**Closed as completed by prashantagarwal** 2017-08-15 06:24 UTC
