### ISSUE TITLE
Standalone apps do not work with some URIs, but the Chrome application does.

### ISSUE THREAD

**Issue by PhilipSharman** [a85/POSTMan-Chrome-Extension#2402] opened 2016-10-11 17:45 UTC
Version/App Information:
1. Postman Versions:
   - Chrome:     4.7.2, OS X / x86-64, Chrome 53.0.2785.143
   - Macintosh:  Version 4.7.2 (4.7.2)
   - Windows:    4.7.2, win32 6.1.7601 / x64
2. App (Chrome app or Mac app): 
   - Chrome app
   - Macintosh standalone app
   - Windows standalone app
3. OS details:
   - Macintosh:      OS X, 10.11.6
   - Windows:        Windows 7
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: For a few weeks or more.
6. Expected behaviour: The standalone apps should behave the same way as the Chrome app.

**Details**
I'm testing an API and I notice some URIs behave correctly in Postman when launched from Chrome but not in the Macintosh standalone Postman application or the Windows standalone Postman application.

For example, this is what I get from the Chrome application:
![postman_chrome](https://cloud.githubusercontent.com/assets/209361/19281399/5b4414a0-8fa7-11e6-881c-8fa72d14f556.png)

But this is what I get from the standalone Macintosh application:
![postman-standalone](https://cloud.githubusercontent.com/assets/209361/19281445/94e7a97e-8fa7-11e6-8ce8-a67eb5f1105e.png)

I get the same error from the standalone Windows application.

Interestingly, if I use the "Code" button to generate a cURL command from the standalone Macintosh app and run it in the Macintosh Terminal, that _does_ work.

(When I get the error response, the xoauth_problem header says "signature_invalid", but if I use the same nonce and timestamp in the Chrome application and the standalone application, the oauth_signature is identical.  And it is identical to the signature I get from the SoapUI testing tool. So I don't think the problem is actually with the OAuth signature itself.)

Most URIs in the API work correctly, but the ones that do not always show the same behavior.  (I can't see any common pattern in which URIs work correctly versus which ones don't.)

This API uses two-legged OAuth 1 authentication.  I don't know if that has anything to do with it.

Thanks.

**Comment by vegetableman** [comment] 2016-10-12 05:11
@PhilipSharman `400` error occurs if the request being sent is malformed in some way. Could you open up the Postman Console (`View -> Show Postman Console`) on either of the native app (Windows/Mac), hit Send and verify the request headers being sent?. 
An easier way to detect the issue, would be to compare the request headers being sent from the chrome app by opening up the devtools (https://www.getpostman.com/docs/errors) versus the native app.

**Comment by PhilipSharman** [comment] 2016-10-13 18:48
Here are the request headers from the standalone app:

```
cache-control:"no-cache"
Postman-Token:"b595a084-fa49-44e7-83f4-cea622ff5084"
Authorization:"OAuth oauth_consumer_key="2f9260ec-84ec-4638-8ca6-5e5abc21afb4",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1476383988",oauth_nonce="O13UKwZfwVR",oauth_version="1.0",oauth_signature="y9FVqirf1yaH%2FF7bOBuxXqcgA44%3D""
User-Agent:"PostmanRuntime/2.5.2"
Accept:"*/*"
Host:"accounts-dev.autodesk.com"
cookie:"ASP.NET_SessionId=bnetb5ifb2ngmkjdxsc2e3ui"
accept-encoding:"gzip, deflate"
```

And here are the headers from the Chrome app:

```
GET /api/tenants/v1/tenant/name/TestTenant004 HTTP/1.1
Host: accounts-dev.autodesk.com
Connection: keep-alive
Authorization: OAuth oauth_consumer_key="2f9260ec-84ec-4638-8ca6-5e5abc21afb4",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1476384201",oauth_nonce="u87E4W",oauth_version="1.0",oauth_signature="DOQbIdBB7J1jGXcXBFauQGoRav0%3D"
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Postman-Token: ec95a8e5-b154-1c17-c0c1-56bb2be06b87
Accept: */*
DNT: 1
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
Cookie: out=X9PHJ4PWKYLN
```

I don't see any obvious differences between them.

By the way, I did enter another issue, https://github.com/postmanlabs/postman-app-support/issues/2405, that concerned another instance of authentication differing between the Chrome app and the standalone apps.  I don't know if that affects this issue too.  (That issue arose from differences in URL-encoding, so it probably doesn't affect this directly, but it did point out that the Chrome app was handling authentication slightly differently from the standalone apps.)

Thanks for looking into this.

**Comment by vegetableman** [comment] 2016-10-20 00:38
@PhilipSharman Thanks for sharing more info on it 👍 . We have been trying to reproduce this issue, is it possible for you to share the mentioned endpoint or any public endpoint with a similar issue for us to test out?. 
Also, you could reach out to me on the slack community (which I noticed you already are part of) to discuss more about it.

**Comment by PhilipSharman** [comment] 2016-10-25 18:22
Thanks Vignesh.  I’ll see if I can get you access.
   Philip.

**Comment by vegetableman** [comment] 2016-12-05 06:23
@PhilipSharman Could you update to the latest version `4.9`? and check if the issue still exists?

**Comment by PhilipSharman** [comment] 2016-12-09 21:38
Unfortunately, the issue is still there.

However, I do have some more information that may help identify the issue.

Here is a URL that shows differences between the Chrome app and the standalone app, and which does not require any permissions to use: https://example.com/api/accounts/v1/user/2RNNRAHHN333.

I find that SopaUI and the Chrome Postman application generate the same signature, but that the Postman standalone app differs.

Details:

a) SoapUI (version 5.3.0):

	curl --include --request GET \
	--header "Authorization: OAuth oauth_signature=\"hDLaEneS9dp%2B3IrD8teX9jF81m0%3D\", 
	oauth_version=\"1.0\", oauth_nonce=\"2057139879\", oauth_signature_method=\"HMAC-SHA1\",
	 oauth_consumer_key=\"REDACTED\", oauth_token=\"\", oauth_timestamp=\"1481311032\"" \
	https://example.com/api/accounts/v1/user/2RNNRAHHN333

	oauth_nonce =              2057139879
	oauth_timestamp =          1481311032
	oauth_signature =          hDLaEneS9dp%2B3IrD8teX9jF81m0%3D


b) Postman Chrome Application (version 4.9.0):

	curl -X GET -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: OAuth
	oauth_consumer_key=\"REDACTED\",oauth_signature_method=\"HMAC-SHA1\",
	oauth_timestamp=\"1481311032\",oauth_nonce=\"2057139879\",oauth_version=\"1.0\",oauth_signature=\"
	hDLaEneS9dp% 2B3IrD8teX9jF81m0%3D\"" -H "Cache-Control: no-cache" -H "Postman-Token:
	ee5b5345-da8f-ccd7-8ed8-bd774d0ce5ce" https://example.com/api/accounts/v1/user/2RNNRAHHN333

	oauth_nonce =              2057139879
	oauth_timestamp =          1481311032
	oauth_signature =          hDLaEneS9dp%2B3IrD8teX9jF81m0%3D


c) Postman Standalone Application (version 4.9.1):

	curl -X GET -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: OAuth
	oauth_consumer_key=\"REDACTED\",oauth_signature_method=\"HMAC-SHA1\",
	oauth_timestamp=\"1481311032\",oauth_nonce=\"2057139879\",oauth_version=\"1.0\",oauth_signature=\"
	xwn9rHcL28f6mr7YrdaRg8erxAg%3D\"" -H "Cache-Control: no-cache" -H "Postman-Token:
	f0dd2ecb-9c58-508c-38c5-1c09cbc9457b" https://example.com/api/accounts/v1/user/2RNNRAHHN333

	oauth_nonce =              2057139879
	oauth_timestamp =          1481311032
	oauth_signature =          xwn9rHcL28f6mr7YrdaRg8erxAg%3D


(This is using OAuth 1.0 authentication for all cases.)

---

Interestingly, I find that with this url, https://www.example.com/something, both the Chrome application and the standalone application generate the _same_ signature.  I'm not sure why the more complex URL causes a difference.

Thanks for looking into this.

Regards,
   Philip.

**Comment by tekoyaki** [comment] 2017-01-05 16:18
Also getting similar problem with Chrome version not being able to access an endpoint but the standalone does. Using v4.92 on Chrome and v4.9.3 on standalone.

Generated code snippet is the same other than the postman token.

Standalone (success):

> Request Headers:
> cache-control:"no-cache"
> Postman-Token:"b0e54db2-f2d7-4513-8b86-5341702bbf49"
> Content-Type:"multipart/form-data; boundary=--------------------------573781571615466076866621"
> Authorization:"Token token='###'"
> User-Agent:"PostmanRuntime/3.0.9"
> Accept:"*/*"
> Host:"www.example.com"
> cookie:"###"
> accept-encoding:"gzip, deflate"
> content-length:185530

Chrome (400 Bad Request):

> Request Headers:
> POST /api/endpoint.json HTTP/1.1
> Host: www.example.com
> Connection: keep-alive
> Content-Length: 28953
> Authorization: Token token='###'
> Postman-Token: ba4e0385-5ca3-f4f3-fada-9e0c7845d2e3
> Cache-Control: no-cache
> Origin: null
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
> Content-Type: application/vnd.api+json
> Accept: */*
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en-US,en;q=0.8
> Cookie: ###

> Response Headers:
> HTTP/1.1 400 Bad Request
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Methods: GET, PUT, POST, PATCH, DELETE, OPTIONS, HEAD
> Access-Control-Allow-Origin: null
> Access-Control-Max-Age: 1728000
> Content-Type: application/vnd.api+json; charset=utf-8
> Date: Thu, 05 Jan 2017 00:43:44 GMT
> Server: nginx
> Vary: Origin
> X-Request-Id: c438147b-7ad8-4581-b20a-d078c4434f4d
> X-Runtime: 0.021094
> Content-Length: 36
> Connection: keep-alive

**Comment by freeart** [comment] 2017-07-03 06:50
I found the different in "charset=UTF-8" which can be a cause of all issues

**Comment by bobwirka** [comment] 2018-07-17 19:14
Doing a simple POST operation. Identical body, auth, and url for both the app and Chrome.

In my instance, the application fails with "Could not get any response", while the Chrome version works.

Also, the 'cURL' version generated by both seem to be identical, and both work.

Web version:
curl -X POST \
  http://192.168.1.176/cgi-bin/xml-cgi \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/xml' \
  -H 'postman-token: 63f4869a-03bc-6325-c6a4-4584db8dd5c9' \
  -d ` '<rdom fcn="rpc" doc="chnData"><unit>0</unit></rdom>'`
  
App version:
curl -X POST \
  http://192.168.1.176/cgi-bin/xml-cgi \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/xml' \
  -H 'Postman-Token: 096abbd9-e1d3-442b-9232-3de2c515616d' \
 -d ` '<rdom fcn="rpc" doc="chnData"><unit>0</unit></rdom>'`

**Comment by a85** [comment] 2019-05-05 19:01
Everyone, closing this issue as there is a large surface area of places where things might differ from the Chrome app and the Desktop apps. We are tracking these individual differences elsewhere. The app is on 7.0+ now and lots of things have changed since the issue was filed.

**Closed as completed by a85** 2019-05-05 19:01 UTC
Labels: bug, request-sending
