### ISSUE TITLE
Postman crashes on launch

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6689] opened 2019-06-10 17:27 UTC
**Describe the bug**
Postman crashes on launch on Windows 10. 
Postman was running fine for months and just recently stopped launching. 

**To Reproduce**
Try opening the app from the desktop

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version 7.1.1
 - OS Windows 10

**Additional context**
What has been done and didn't help
- Clearing the cache doesn't help.
- Disabling GPU
- Uninstalling/Reinstalling

Note: screencast and logs are accessible internally.

**Comment by numaanashraf** [comment] 2019-06-11 12:26
Relevant error from logs
```
[34304][1559925761460][main][error]["Bootstrap-models~bootstrap -Failed",{"name":"Error","message":"More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss","stack":"Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss\n    at Persistence.treatRawData (<location>\\app-7.1.1\\resources\\app.asar\\node_modules\\nedb\\lib\\persistence.js:242:11)\n    at <location>\\app-7.1.1\\resources\\app.asar\\node_modules\\nedb\\lib\\persistence.js:281:38\n    at tryToString (fs.js:513:3)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)"}]
[34304][1559925761477][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read property 'collections' of undefined","stack":"TypeError: Cannot read property 'collections' of undefined\n    at bootstrapModels (<location>\\app-7.1.1\\resources\\app.asar\\main.js:162:27)\n    at <location>\\app-7.1.1\\resources\\app.asar\\bootstrap-models.js:34:14\n    at <location>\\app-7.1.1\\resources\\app.asar\\node_modules\\waterline\\lib\\waterline.js:918:25\n    at <location>\\app-7.1.1\\resources\\app.asar\\node_modules\\waterline\\lib\\waterline.js:719:25\n    at <location>\\app-7.1.1\\resources\\app.asar\\node_modules\\waterline\\node_modules\\async\\dist\\async.js:952:25\n    at iteratorCallback (<location>\\app-7.1.1\\resources\\app.asar\\node_modules\\waterline\\node_modules\\async\\dist\\async.js:995:17)\n    at <location>\\app-7.1.1\\resources\\app.asar\\node_modules\\waterline\\node_modules\\async\\dist\\async.js:847:20\n    at <location>\\app-7.1.1\\resources\\app.asar\\node_modules\\async\\lib\\async.js:52:16\n    at done (<location>\\app-7.1.1\\resources\\app.asar\\node_modules\\async\\lib\\async.js:241:17)\n    at <location>\\app-7.1.1\\resources\\app.asar\\node_modules\\async\\lib\\async.js:44:16\n    at <location>\\app-7.1.1\\resources\\app.asar\\common\\adapters\\waterline-shared-nedb.js:320:29\n    at newArguments.(anonymous function) (<location>\\app-7.1.1\\resources\\app.asar\\node_modules\\nedb\\lib\\executor.js:29:17)\n    at <location>\\app-7.1.1\\resources\\app.asar\\node_modules\\nedb\\lib\\persistence.js:305:26\n    at <location>\\app-7.1.1\\resources\\app.asar\\node_modules\\nedb\\lib\\persistence.js:283:22\n    at tryToString (fs.js:513:3)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)"}]
```

**Comment by arcdev** [comment] 2019-06-25 16:36
Seems to be the same as #6296

**Comment by numaanashraf** [comment] 2019-08-01 10:32
This seems related to #6296 as @arcdev suggested and we'll be using #6296 to track this going forward.

**Comment by numaanashraf** [comment] 2019-08-01 10:33
Duplicate of #6296

**Closed as completed by numaanashraf** 2019-08-01 10:33 UTC
Labels: bug, launch
