### ISSUE TITLE
When you click the Send button again 'too fast' the 'Time:' value can be reported too low

### ISSUE THREAD

**Issue by HenkPoley** [a85/POSTMan-Chrome-Extension#7768] opened 2019-12-10 08:44 UTC
**Describe the bug**
Click Send twice quickly. First click it says (for this Vagrant-PHP7-MariaDB backend) normal values of 150ms. Second click load time may be < 12ms.

There is probably some odd juggling with timestamps or querying of the system-time going on.

**Expected behavior**
Our backend does the same work. Time shouldn't change (very much). It won't improve > x10.

**App information (please complete the following information):**
* Postman for Windows
* Version 7.13.0
* win32 10.0.18363 / x64

**Comment by codenirvana** [comment] 2019-12-10 10:22
Duplicate of #6073

@HenkPoley This is because of the persisted connection as mentioned in https://github.com/postmanlabs/postman-app-support/issues/6073#issuecomment-473038673

Try sending the request using `Connection: close` header and you will see similar response time for every request.

**Closed as completed by codenirvana** 2019-12-10 10:22 UTC
Labels: support, duplicate, request-sending

**Comment by HenkPoley** [comment] 2019-12-10 10:40
That would be a nice theory. So I added under the 'Headers' tab, a Key 'Connection', with Value 'close'. But the randomly fast behaviour is still there.

Maybe the header needs to be set up elsewhere in Postman?

Edit: the response headers also switches from `Connection: keep-alive` to `Connection: close`. So at least nginx seems to think it needs to act differently.
