### ISSUE TITLE
Postman capitalizing "charset" header

### ISSUE THREAD

**Issue by akshaygoyal** [a85/POSTMan-Chrome-Extension#7904] opened 2020-01-13 13:23 UTC
**Describe the bug**
"charset" header is getting capitalised while sending the request via postman. Whereas with curl it is sent as it is. I found it while testing an API where header validation was case sensitive. 

**To Reproduce**
Just pass charset in lower case in your api and print the headers.
Check it with curl and see the difference

![image](https://user-images.githubusercontent.com/7792454/72259025-c96d1500-360f-11ea-9b98-353e6f440cd6.png)

 - Postman Version 5.5.4
 - OS: macOS Mojave 10.14.6

Feel free to close this if this is an expected behaviour.

**Comment by codenirvana** [comment] 2020-01-13 13:42
@akshaygoyal Looks like you are using a very old version of the Postman app.
Check if updating to the latest version fixes the issue.
https://www.getpostman.com/downloads

**Comment by codenirvana** [comment] 2020-02-29 19:21
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-02-29 19:21 UTC
