### ISSUE TITLE
OAuth 2 Request Authorization Code not working

### ISSUE THREAD

**Issue by BrianP6** [a85/POSTMan-Chrome-Extension#7032] opened 2019-07-31 23:08 UTC
Postman for Windows version 7.3.4
OS: Windows 10

Target system: WordPress 5.2.2 website running WP_Oauth_Server PRO with a LetsEncrypt certificate.

## Issue
Clicking on "Get New Access Token" launches the pop up window to login to the server application. After entering credentials the user is logged in on the target system but the Postman pop up window returns to the login screen. The process does not complete and return with the access token.

## Chrome App Test
If I switch over to the old chrome app (version 5.5.4) using the same credentials, the access token is returned successfully. Copying and pasting that access token into the native Postman app allows requests to be made correctly.

## Browser Test
Opening a browser window and entering:
{{AUTH_URL}}?response_type=code&state=&client_id={{CLIENT_ID}}&scope=read&redirect_uri=https://www.getpostman.com/oauth2/callback
Then a login page appears and after successfully logging in the URL changes to:
https://app.getpostman.com/oauth2/callback?code=m2mkehnnzrledlv3tkngtdp3ejjlnxf4cjwbrum7&state=

## Screenshot
![Get_Access_Token](https://user-images.githubusercontent.com/45318522/62253993-8c112400-b3ef-11e9-8eb6-f26d23f6d098.png)

Many thanks,
Brian.

**Comment by ankurdengla** [comment] 2019-08-01 11:16
Hey @BrianP6 @andutta ! Thanks for bringing this issue to our notice. Could you please try your use-case with this custom canary build which has extra logging so as to enable us to understand the issue better?

Link to custom build - https://drive.google.com/open?id=1-Clx1jDPY_M1oJxsJV3TJ6fhT_4hP-Vn

Please share all the logs available in View->Developer->View Logs in Explorer/Finder/File Manager with us at help@getpostman.com with subject as "Logs for Github issue 7032" .

**PS** - This custom build is made for this specific use-case and won't receive any future updates.

**Comment by chrisdeso** [comment] 2019-08-05 18:53
Thanks for sending the logs in @BrianP6!

@ankurdengla1996 – We've added the info internally

**Comment by ankurdengla** [comment] 2019-08-07 10:09
Hey @BrianP6! We went through the logs we received from you and noticed that the callback url you are using is `https://callbackurl` and it has an extra space at the end of it which is then encoded as `%20` and sent as part of the callback url. To unblock yourself quickly, could you try removing the extra space at the end of the callback url ?
Do let us know if this solves your issue.

**Comment by ankurdengla** [comment] 2019-08-09 13:27
**UPDATE:** We are also tracking the issue mentioned in https://github.com/postmanlabs/postman-app-support/issues/6895 by @toreskobba where the OAuth2 "Request Token" flow hangs on a white screen after login. We were able to reproduce the issue at our end and are working on a fix for it. This is an issue with the custom protocol being used in your callback url.

@toreskobba A quick workaround to unblock your workflow would be to change the callback url to something with `http` or `https` protocol. For example - `https://www.getpostman.com/oauth2/callback`

**Comment by BeingSujeetK** [comment] 2019-08-12 08:53
Hi @ankurdengla1996 , please find the details below.
- callback url that you are using to obtain the access token
it's an app specific custom url

- Last version where the flow was working
not sure about this, since i had enabled auto update and wasn't keeping track of versions. But pretty sure that it was working about a month back for the same callback url.

**Comment by ankurdengla** [comment] 2019-08-12 08:57
@BeingSujeetK Thanks for getting back to us. We are working on a fix for the issue. Meanwhile, you can try the workaround mentioned above. https://github.com/postmanlabs/postman-app-support/issues/7032#issuecomment-519918500

**Comment by BeingSujeetK** [comment] 2019-08-12 08:57
Is there a stable version for this feature where the OAuth2.0 Authorization Code flow is working perfectly?

**Comment by BeingSujeetK** [comment] 2019-08-12 08:59
Hi @ankurdengla1996 , I don't have the flexibility to change the redirect url due to operational reasons.

**Comment by BrambleRamble** [comment] 2019-08-13 16:28
I've been affected for a while by the variant of this problem where the OAuth generation dialog ends up showing a blank white page, instead of getting a token. This started happening after automatic upgrade a few weeks ago. My current version is 7.5.0 on Windows. Several other people on my team are similarly affected, including Mac users.

Is there any extra information that we can provide to help progress this issue please?

**Comment by ankurdengla** [comment] 2019-08-14 06:00
@BrambleRamble Could you confirm if you're using a custom protocol for the callback URL?

**Comment by BrambleRamble** [comment] 2019-08-14 08:57
> @BrambleRamble Could you confirm if you're using a custom protocol for the callback URL?

@ankurdengla1996 Yes, we are.

**Comment by andutta** [comment] 2019-08-14 15:28
@ankurdengla1996 You mentioned in one of your previous comments that you were able to reproduce the issue of "hung white screen when requesting token". Do you know when can I get a patch for it?

Appreciate all the help on this.

**Comment by ankurdengla** [comment] 2019-08-19 11:55
@toreskobba @BeingSujeetK @BrambleRamble @andutta The fix for the OAuth 2.0 issue is out on our latest canary build (PostmanCanary 7.6.0-canary03) which can be downloaded from - https://www.getpostman.com/downloads/canary

Do let us know if it solves your issue.

**Comment by jounii** [comment] 2019-08-20 08:07
The canary version fixed our white screen issue. We have "urn:" prefixed callback urls.

**Comment by BrambleRamble** [comment] 2019-08-20 08:29
@ankurdengla1996 I'm able to generate tokens successfully using the canary version. I don't get the white screen that I was seeing before.
Edit: I can confirm this for Windows & Mac.

**Comment by BeingSujeetK** [comment] 2019-08-21 08:39
Hi @ankurdengla1996 , I'm able to generate the token using auth code grant successfully on below setup.
Version 7.6.0-canary03
win32 10.0.17763 / x64

Thanks for the prompt resolution!

**Comment by ankurdengla** [comment] 2019-08-30 08:15
A fix for this has been released on Postman 7.6.0

**Closed as completed by ankurdengla** 2019-08-30 08:15 UTC
Labels: bug, product/runtime

**Comment by GlennIM** [comment] 2020-03-23 14:40
When clicking the "Request Token" button, the "Connect To Pinterest" dialog appears to grant access, then when I click the OK button in that dialog I get the following error message...

`{"status": "failure", "code": 12, "data": "path: /oauth/\nparams:<dict_itemiterator object at 0x7fad8ef24050>\nAuthError(code=500, message='dial tcp 127.0.0.1:22000: connect: connection refused')", "message": "Something went wrong on our end. Sorry about that.", "endpoint_name": "oauth_connect"}`

What is the work around for this?

**Comment by yamgarcia** [comment] 2024-11-18 19:35
This issue persists to this day. 
My scenario is different but, I suggest working on something that would help the troubleshooting (a simple error message instead of a blank screen would help).
Comparing to Insomnia, I do get an error with a code.
