### ISSUE TITLE
<title>Use of Global environment variables in Postman flows 

### ISSUE THREAD

**Issue by sepdoce90** [a85/POSTMan-Chrome-Extension#11923] opened 2023-04-14 09:25 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Strangely I can use Global environment variables in test mode, but in live testing flow it's not possible to use the global environment variables. How can that be ? And what about adding payload data in the start block from the triggered webhook. Add connection between flows. Creating sub-flows inside a flow. Adding Websocket function inside flows as well to capture and use data inside.  

### Describe the solution you'd like

Strangely I can use Global environment variables in test mode, but in live testing flow it's not possible to use the global environment variables. How can that be ? And what about adding payload data in the start block from the triggered webhook. Add connection between flows. Creating sub-flows inside a flow. Adding Websocket function inside flows as well to capture and use data inside.  

### Describe alternatives you've considered

I really like flows in Postman, I have tried other platforms but nothing comes close to this easy visual workflow with low-code. But if you just add the functionality to integrate all functions with Postman and Postman flows, then it would be perfect !

**Comment by sepdoce90** [comment] 2023-04-14 09:30
Just a thought ! I like the new flow integration examples, like the stock marked dashboard. Why not add this as a front end. It seems like you want add similar functions like other platforms, to create back and front-end.

**Comment by rabbah** [comment] 2024-04-18 13:57
@sepdoce90 can you clarify what you mean by add this as a front-end?

**Comment by rabbah** [comment] 2024-04-18 13:58
This is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/12109.

**Closed as completed** 2024-04-20 02:34 UTC
Labels: feature, Flows
