### ISSUE TITLE
Auth Helper – Basic Auth not encoding non-ASCII characters correctly

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#4838] opened 2018-07-17 05:15 UTC
**Describe the bug**
When on-ASCII characters are used for basic auth, the url encoded auth header is incorrect.

**To Reproduce**
1. Set username to `user` and password to `password`. The generated Auth header has value: Basic dXNlcjpwYXNzd29yZA== (decodes successfully) 
2. Set username to `user` and password to `passÅword`. The generated Auth header has value: Basic dXNlcjpwYXNzxXdvcmQ= 

**Screenshots**
`user / password`
![user / password](https://i.imgur.com/cyiDi5Y.png)

`user/passÅword`
![user/passÅword](https://i.imgur.com/LwudffK.png)

**App information (please complete the following information):**
 - **Postman Version**: 6.1.3

**Comment by kamalaknn** [comment] 2018-07-17 08:43
Hey @chrisdeso 

I tried to replicate this, and I noticed that the encoded header is infact encoded per the input provided. When you use `user:password` you get the header `Basic dXNlcjpwYXNzd29yZA==` and when you use `user:passÅword` you get the header `Basic dXNlcjpwYXNzxXdvcmQ=`, which is different from the previous combination as it should be.

I've also tested this by encoding the combination directly and it seems to match the one that Postman generates.

So I'm confused here, are you expecting these two combination to result in the same header?

**Comment by kamalaknn** [comment] 2018-07-18 19:48
`password` and `passÅword` are different characters and should be encoded differently. I think this is not a bug with Postman and behaves as it is expected to. I'm closing this issue now.

Feel free to reopen if I've missed anything here.

**Closed as completed by kamalaknn** 2018-07-18 19:48 UTC
Labels: support
