### ISSUE TITLE
Runner: Data load from CSV doesn't seem to work with nested elements

### ISSUE THREAD

**Issue by pjohnkeane** [a85/POSTMan-Chrome-Extension#1976] opened 2016-04-07 16:27 UTC
I'm working with a few API calls that use nested elements in their bodies -- i.e. in this sort of shape:

```
{ 
  "parent" : [
    {
      child : "{{PARAM}}"
    }
  ]
}
```

These can be processed fine by specifying the data to use on a case-by-case basis when running via Postman, but I get failures when executing via Runner from a CSV data file when it hits one of these requests (typically returning **422 Unprocessable Entity**).

I can appreciate that this sort of data shape assumes the possibility of multiple child elements, which is incompatible with a flat CSV file in principle, but the nature of these tests means that the data needs to be specified anyway, so multiple child elements would be named uniquely in both the request and in the data file.

**Comment by pjohnkeane** [comment] 2016-04-07 16:28
Previously also noted by someone else in the comments on [Using CSV and JSON data files in the Postman Collection Runner](http://blog.getpostman.com/2014/10/28/using-csv-and-json-files-in-the-postman-collection-runner/#comment-2398413656)

**Comment by vikiCoder** [comment] 2019-06-13 13:05
Duplicate issue: https://github.com/postmanlabs/postman-app-support/issues/6098

**Comment by codenirvana** [comment] 2019-06-17 22:15
Closing as duplicate of #6098

**Closed as completed by codenirvana** 2019-06-17 22:15 UTC
Labels: feature, collection-runner, data-file/csv, duplicate, data-file, product/runtime
