### ISSUE TITLE
Collection Runner in a separate window

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#9661] opened 2021-02-25 10:30 UTC
On behalf of a user:

**Is your feature request related to a problem? Please describe.**
In the latest v8 version, test runs in the same window making it difficult for the users in terms of debugging. Earlier there was a possibility to toggle between fail test and actual test with the help of a separate window.

**Describe the solution you'd like**
It would be great to have a Runner opened in a  separate window for debugging like previous versions:

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ritwijsinha** [comment] 2021-02-25 11:08
We still have the option to see the all/failed/passed tests in Runner, it's just that the view is different now.

V7:
![image](https://user-images.githubusercontent.com/19693841/109144920-d30bfa80-7787-11eb-8a7b-2c64d862d2de.png)
![image](https://user-images.githubusercontent.com/19693841/109144938-d7381800-7787-11eb-9c56-fa707cd2ea5d.png)
![image](https://user-images.githubusercontent.com/19693841/109144948-da330880-7787-11eb-967b-c65c35c64459.png)


V8:
![image](https://user-images.githubusercontent.com/19693841/109144972-e3bc7080-7787-11eb-953d-669d21161f16.png)
![image](https://user-images.githubusercontent.com/19693841/109144985-e919bb00-7787-11eb-87e7-60b30e01984b.png)
![image](https://user-images.githubusercontent.com/19693841/109145002-ed45d880-7787-11eb-897c-7bd9eea6aa23.png)

**Comment by knottronix** [comment] 2021-02-25 11:33
Hi guys, I am the user who reported this issue. I think this below best explains what the issue is and how it could easily work a lot better and save a huge amount of mental cross-referencing between windows or tabs:

It really would be useful to be able to link from a failed test back to the request and test code that failed. 
At the moment I have to take a note of which test (in a big collection) failed in the test run window – I take down the name of the request and which collection folder it’s in. 
Then I switch to the collection window, scroll down the folders to find the right folder, then expand, then find which request failed (sometimes locating by name AND POSITION as there are requests with the same name at different places in the folder).
Then I open the request and then open the test tab. I look at the test code and then go back and forth between the original collection run window to check the response (from test run) vs the test code.
 
This is arduous. Having to cross refernce between screens in the same app is crazy,
 
I would love a feature the linked the failed test back to the request – open the request that failed the test, by default on the test code tab.
Also, it would be amazing if the response data from the failed collection run test could be shown in the request response window – then I can look at the failed response code and test code vertically next to each other on the screen – bliss!

**Comment by knottronix** [comment] 2021-02-25 11:34
In fact, this was not logged correctly - I will log this a new feature request.

**Comment by knottronix** [comment] 2021-02-25 11:39
Done- here it is https://github.com/postmanlabs/postman-app-support/issues/9662

**Comment by saswatds** [comment] 2021-02-25 13:07
Hey @knottronixm, thanks for reaching out. Your feature request is exactly in line with what we intend to do in the next iteration. Having the Runner in a different window was one of the major hindrances in term of integration with the rest of the postman ecosystem. Our first step was to get the runner into a tab within the main window, now as that's done in the V8 version of the app, over the next few iterations we will link the elements in the runner to open the relevant request, folders, etc.  

Closing this issue and tracking #9662 instead.

**Closed as completed by saswatds** 2021-02-25 13:07 UTC
