### ISSUE TITLE
Submitting NULL into POST body using IF statement fails to hit ELSE statement.

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2970] opened 2017-04-21 13:48 UTC
**1. Postman Version:**
Version 4.10.7
 **2. App (Chrome app or Mac app):**
58.0.3029.81 (64-bit)
 **3. OS details:**
win32 6.1.7601 / x64
 **4. Is the Interceptor on and enabled in the app:**
N/A
 **5. Did you encounter this recently, or has this bug always been there:**
Recent
 **6. Expected Outcome:**
POST Submission takes null value within variable name

**7. Abstract**
I'm having an absolute nightmare trying to pass a null value into a variable within my POST body.
Whenever the CSV file contains a value for the field it updates without an issue. It completely fails however when I attempt to submit it as null:

**8. Replication Steps:**
Given I have if statement in Pre-Script setup of:

if(data.Title !== "undefined" && data.Title!==null ) 
postman.setEnvironmentVariable("title", data.Title);
}else
{
postman.setEnvironmentVariable("title", "");
}

_**OR**_

if( data.Title != "undefined" || data.Title !== null || data.Title !== undefined || data.Title != "null" ){
postman.setEnvironmentVariable("title", data.Title);
}
else{
postman.setEnvironmentVariable("title", null);
}
**9. Actual Result**

When I submit using CSV data title: "Mr"
Then I can see Request body contains Title: Mr,

______________________________________________________

When I submit using CSV data title: "",
Then I can see Request body contains Title: {{title}},

**Comment by punchdrunkdetective** [comment] 2018-01-05 20:49
I think my issue is related to this bug. 

I am parsing a csv file with empty fields. I can actually log out the data object's properties in the pre-request script of postman, and postman seems to be correctly parsing ,,, into four nulls in my form json body. But when I capture what data is sent in the post itself, I see {{varirableName}} inside the body  instead of null. 

Is there any update on this issue? 
I am running postman 5.5.0

**Comment by jlchavis0844** [comment] 2018-06-09 05:52
The issue with postman seems to be not handling  empty spaces in a CSV file. For instance:
Sending -
"myItem1": "{{i1}}",
"myItem2": "{{i2}}",
"myItem3": "{{i3}}",

With CSV of -
i1,i2,i3
Item1,,Item3
 
Will result in-
"myItem1": "Item1",
"myItem2": "{{i2}}",
"myItem3": "Item3",

You must use a text text qualifier of " .

"i1","i2","i3"
"Item1","","Item3"

will translate to -
"myItem1": "Item1",
"myItem2": "Item2",
"myItem3": "Item3",

**Comment by digital-q** [comment] 2018-11-27 20:14
Looks like this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2861

Check out a workaround for this issue at: https://github.com/postmanlabs/postman-app-support/issues/2861#issuecomment-443241417

**Comment by psharma-intacct** [comment] 2019-03-28 20:33
I am still running into this issue! when can we expect a solution to this?

**Comment by digital-q** [comment] 2019-03-29 15:45
> I am still running into this issue! when can we expect a solution to this?

@psharma-intacct If you follow the steps at https://github.com/postmanlabs/postman-app-support/issues/2861#issuecomment-443241417 you'll have a complete workaround to this issue.

**Comment by vikiCoder** [comment] 2019-06-12 08:16
Hi everyone,

I would like to inform that we have made some changes related to CSV file parsing under the hoods in the Postman App. This issue is fixed as part of those changes, Postman App now treats null values as empty string while parsing CSV file (same as Newman). It is available on the [latest canary](https://www.getpostman.com/downloads/canary) version (Version 7.1.1-canary07) of the app. You can check out [canary](https://www.getpostman.com/downloads/canary) and let us know if you are still facing this issue in it.

However, for the users who don't want this behavior or want to have more control over parsing, we are planning to provide options related to CSV file parsing behavior in our long term roadmap. Suggestions are always welcome regarding what options you would like to have when we add them.

**Comment by vikiCoder** [comment] 2019-06-19 05:15
The fix that I mentioned in my previous comment is out in [latest Postman App](https://www.getpostman.com/downloads/) (v7.2.1) as well.

**Closed as completed** 2019-06-19 06:42 UTC
Labels: bug, collection-runner, data-file/csv, product/runtime
