### ISSUE TITLE
Cannot get response for POST request in 7.0.9 version

### ISSUE THREAD

**Issue by makhaer** [a85/POSTMan-Chrome-Extension#6341] opened 2019-04-23 07:03 UTC
**Describe the bug**
I am using windows 10 64 bit. Just upgraded from version 7.0.7 to 7.0.9. After that my request is not getting response which was totally OK in version 7.0.7.

Requested server is totally fine and works in 7.0.7 still.

request detail :
method : POST
param : wsdl
header : Content-type : text/xml
Body : raw with xml content

**To Reproduce**
1. Create or import a request as mentioned above.
2. Click on 'Send'
3. Wait for response

**Expected behavior**
Response will arrive from server.

**Actual behavior**
Response does not arrive and timeout occurs.

**Screenshots**

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [7.0.9]
 - OS: [Windows 10 64 bit

]

**Additional context**

**Comment by codenirvana** [comment] 2019-04-23 07:38
@makhaer Since you closed the issue, I assume its fixed.
What caused this issue? Because of the v7.0.9 upgrade?

**Comment by makhaer** [comment] 2019-04-23 07:49
@codenirvana  > Sorry I did not want to close it. May be closed accidentally. Issue is still here. I want to reopen. Now I have installed older version 7.0.7.

Upgrading from 7.0.7 to 7.0.9 caused. I think in new version problem exists still.

**Comment by codenirvana** [comment] 2019-04-23 08:03
@makhaer To debug the issue with 7.0.9, can you try:
1. For sanity, is `POST` request at `https://postman-echo.com/post` working fine?
2. What's the error message in `Postman Console` for the errored request?
3. What are the Response Headers received in 7.0.7?
4. Check SSL and Proxy settings in App (both the versions)

**Comment by JdKock** [comment] 2019-04-23 13:41
I normally download the file and extract if over the old version, like now over 7.0.7
I solved this issue by delete the Postman directory of version 7.0.7 and do a clean install of Postman version 7.0.9

**Comment by makhaer** [comment] 2019-04-24 03:27
> @makhaer To debug the issue with 7.0.9, can you try:
> 
> 1. For sanity, is `POST` request at `https://postman-echo.com/post` working fine?
> 2. What's the error message in `Postman Console` for the errored request?
> 3. What are the Response Headers received in 7.0.7?
> 4. Check SSL and Proxy settings in App (both the versions)

**Comment by makhaer** [comment] 2019-04-24 03:31
Sorry I closed again accidentally.
1. For sanity, is POST request at https://postman-echo.com/post working fine?
It works fine.
2. What's the error message in Postman Console for the errored request?
Error: connect ETIMEDOUT 
3. What are the Response Headers received in 7.0.7?
I don't have the header. 
4. Check SSL and Proxy settings in App (both the versions)
Same in both.

**Comment by makhaer** [comment] 2019-04-24 04:02
> I normally download the file and extract if over the old version, like now over 7.0.7
> I solved this issue by delete the Postman directory of version 7.0.7 and do a clean install of Postman version 7.0.9

I reinstalled 7.0.7 . This version is working.

**Comment by Kapcash** [comment] 2019-04-24 08:56
I have the same issue with v7.0.9 using a proxy. In 7.0.7 everything works fine.
Since the new "Authentication Proxy" feature, none of my requests reach the urls. Even if I add the configurations for authentication or not.

**Comment by makhaer** [comment] 2019-04-24 09:09
> I have the same issue with v7.0.9 using a proxy. In 7.0.7 everything works fine.
> Since the new "Authentication Proxy" feature, none of my requests reach the urls. Even if I add the configurations for authentication or not.

Thanks for sharing. I forgot to share I am also using proxy. Same request using proxy works in 7.0.7 but not in 7.0.9.

**Comment by codenirvana** [comment] 2019-04-24 09:55
@Kapcash @makhaer Isn't same Proxy Configuration (with auth OFF) working fine?

**Comment by Kapcash** [comment] 2019-04-24 09:58
No, even with auth off it doesn't work. I've tried a bunch of proxy settings combinations but none of them are working (system proxy on/off, empty auth on/off, filled auth on/off). Seems like the entire proxy system is broken.

**Comment by codenirvana** [comment] 2019-04-24 10:09
@Kapcash Not able to reproduce this, working fine for me (Proxy with and without auth).

Is it happening for every request sent or any particular endpoint?
Are you also facing this issue on Windows or on a different OS?

@makhaer @Kapcash Can you check if clean installing v7.0.9 fixes this issue as suggested by @JdKock https://github.com/postmanlabs/postman-app-support/issues/6341#issuecomment-485807523?

**Comment by Kapcash** [comment] 2019-04-24 12:06
It happens for all requests involved with the proxy.
Requests that don't require the proxy are good.

I've tried a clean install of v7.0.9 on Windows, still facing the issue.

**Comment by codenirvana** [comment] 2019-04-24 13:33
@Kapcash What's the error message in `Postman Console` for the failed requests?

Is there any way I can reproduce this? I tried using `mitmproxy` and its working fine with that.
Can you debug the request on the proxy server or test with `mitmproxy` to test if that fails too?

**Comment by makhaer** [comment] 2019-04-25 00:29
> @Kapcash Not able to reproduce this, working fine for me (Proxy with and without auth).
> 
> Is it happening for every request sent or any particular endpoint?
> Are you also facing this issue on Windows or on a different OS?
> 
> @makhaer @Kapcash Can you check if clean installing v7.0.9 fixes this issue as suggested by @JdKock [#6341 (comment)](https://github.com/postmanlabs/postman-app-support/issues/6341#issuecomment-485807523)?

My server endpoint needs to use proxy to reach. So, I cannot test without proxy. But post-man echo request worked for me. Even I installed 7.0.9 fresh. It did not work.
I am not sure if @JdKock is using proxy.

**Comment by Featurum** [comment] 2019-05-02 19:53
I ran into this problem on macos after update 7.0.9

**Comment by Kapcash** [comment] 2019-05-13 11:55
Some news about the bug:
* I've tested reaching localhost with the proxy on v7.0.9. I'm not supposed to reach it with the proxy but I do. It was not possible for me on v7.0.7 (the proxy answers that it is not a reachable url)
So it looks like weather the proxy is enabled or not, it behaves as if it is not even configured.
* Using mitmproxy, it seems to work. At least, requests are logged from the mitmproxy interface.

If that may help, the proxy's ip is configured in my Window's host file.

Sadly, I cannot configure the proxy myself nor ask for any informations about it.

**Comment by codenirvana** [comment] 2019-05-13 12:14
@Kapcash Possible duplicate of #6364

**Comment by codenirvana** [comment] 2019-05-20 14:03
@Kapcash This is fixed in the latest version of the Postman App (v7.1.1).

Closing as duplicate of #6364

**Closed as completed by codenirvana** 2019-05-20 14:03 UTC
Labels: bug, Proxy, product/runtime
