### ISSUE TITLE
Does PostMan support Collection Runner for gRPC APIs 

### ISSUE THREAD

**Issue by tissac** [a85/POSTMan-Chrome-Extension#12617] opened 2024-02-02 17:33 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Testing gRPC API at scale is what I am looking for,  I could not see the collection runner for gRPC APIs,   

### Describe the solution you'd like

Functionality on Par with REST APIs while using Postman is what I am looking for.

**Comment by appurva21** [comment] 2024-02-05 05:57
Hey @tissac! Thanks for the feature request. It would be really helpful if you could share more details on your use case [here](https://github.com/postmanlabs/postman-app-support/issues/11583). 

----
Duplicate of #11583

**Closed as completed by appurva21** 2024-02-05 05:57 UTC
Labels: feature, protocol/grpc, product/api-client
