### ISSUE TITLE
Postman: 407 proxy authentication required

### ISSUE THREAD

**Issue by fm555** [a85/POSTMan-Chrome-Extension#6208] opened 2019-04-02 08:51 UTC
I have issues when using Postman at my office with proxy.
I am trying to send a GET request to the following link:

http://postman-echo.com/get

But I am getting "407 Proxy Authentication Required".

I have followed the following instructions to configure Postman to work through a proxy in:

https://support.getpostman.com/hc/en-us/articles/360008893713-How-do-I-configure-Postman-to-work-through-a-proxy-

My proxy is correctly configures, but Postman does not work. 
I have tried with "No Auth" and "Basic Auth", and both without logging in and logging with my Postman account, but it does not work so far.
I am using the Settings-> Use System Proxy option turned ON.

Any suggestions on how can I solve this issue?
Let me know if you need more information.

I am using: 

Postman for Windows
Version 7.0.7
win32 10.0.14393 / x64

**Comment by codenirvana** [comment] 2019-04-02 11:39
Duplicate of #3566

@fm555 We recently added support for Proxy Authentication (Basic Auth) in our Canary channel https://www.getpostman.com/canary

You can try it out and follow the mentioned thread for updates. Refer: https://github.com/postmanlabs/postman-app-support/issues/3566#issuecomment-477780835

**Closed as completed by codenirvana** 2019-04-02 11:39 UTC
Labels: Proxy

**Comment by fm555** [comment] 2019-04-02 13:01
@codenirvana 

Proxy issue solved using Postman Canary.
Thank you so much @codenirvana !

**Comment by diman82** [comment] 2019-06-18 09:26
I'm facing the same issue, even though I'm accessing in internal server API (proxy should not be hit), and also have [px](https://github.com/genotrance/px) configured.
Installed Canary build, but same behavior.

** Eventually, I had a redirect to another hostname, and seems Postman (and curl as well) doesn't know how to deal with this).
