### ISSUE TITLE
Setting environment variable inside a javascript method in a collection script doesn't work

### ISSUE THREAD

**Issue by muku** [a85/POSTMan-Chrome-Extension#4617] opened 2018-05-30 03:21 UTC
I am setting an environment variable inside a function in my collection's pre-request script like this:

`String.prototype.collectionFunction = function(){`
    `console.log("executing collection function on: " + this);`
    `pm.environment.set("var1",this);`
   `console.log("Getting var1 in collection: " + pm.environment.get("var1"));
`}`

Then inside a request I execute the function like this:

`"1".collectionFunction();`
`console.log("Getting var1 in request: " + pm.environment.get("var1"));`

The console log is like this:

executing collection function on: 1
Getting var1 in collection: 1
Getting var1 in request: undefined

What am I missing? If I change environment to global, it works. But I don't want to set a global variable.

**Comment by sivcan** [comment] 2018-05-30 11:11
@muku I was unable to reproduce this.
Couple of questions:
1. What version of postman are you using? Can you make sure you're on the latest version (v6.1.3 as of now) 
2. Have you selected the environment from the dropdown? 
For eg: 
![image](https://user-images.githubusercontent.com/12631777/40716921-2d8236d0-6428-11e8-91f3-9ca68ff39603.png)

**Comment by muku** [comment] 2018-05-30 11:39
I'm using the latest desktop version for windows. I've also selected my environment. I've added some code on my initial description. It's pretty simple, give it a try and you will reproduce the problem.

**Comment by kamalaknn** [comment] 2018-05-30 12:26
Hi @muku 

I tried to reproduce this with the following seetup. I was able to get it working.

<img width="678" alt="screen shot 2018-05-30 at 5 47 28 pm" src="https://user-images.githubusercontent.com/8401064/40719673-e37ba8b4-6431-11e8-9bb4-7f9259520fc4.png">

![screen shot 2018-05-30 at 5 47 40 pm](https://user-images.githubusercontent.com/8401064/40719963-d179337e-6432-11e8-92b7-6c72a542774e.png)

Am I missing something?

**Comment by muku** [comment] 2018-05-30 12:53
From the above screenshot I take that the js function is defined in the pre-request script of the request. Try to define it in the pre-request script of the collection. And then use the function in the pre-request script of a request.

**Comment by kamalaknn** [comment] 2018-05-30 13:17
@muku 

I've got the problem here. All the scripts in a postman are executed in a sandboxed environment.

The sandbox environment is initialized everytime a script is executed in it. That's why the prototype mutations are not preserved across the scripts. This is also a way we can ensure that malicious scripts that change the prototype are contained in the script and do not affect any other scripts.

If you need this behavior you might have to initialize the prototype functions in all your scripts. You can look at the `Tip #5 reuse code` on http://blog.getpostman.com/2017/07/28/api-testing-tips-from-a-postman-professional/ to help reuse your code.

**Comment by kamalaknn** [comment] 2018-05-30 13:17
I'm closing this as this is not a bug with Postman App itself.

Thanks

**Closed as completed by kamalaknn** 2018-05-30 13:17 UTC
Labels: pending-close

**Comment by muku** [comment] 2018-05-30 14:34
So if I want to reuse a function in all my scripts I need to define it in every script? This is not very productive and it will bloat around 1000 requests with about 30 lines of code that my functions take.

I don't quite get your previous message. As I said in my first post, using this "hack" I can set global variables from inside the js functions in the prototype but I can't set the environment variables. Can you explain me why this is happening and how it is related to the sandbox environment? To me it still looks like a bug.
