### ISSUE TITLE
Nested JSON string not formatting correctly 

### ISSUE THREAD

**Issue by Thwar** [a85/POSTMan-Chrome-Extension#4420] opened 2018-04-05 19:19 UTC
## App Details:
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Always
 2. Expected behaviour:
Should show string as JSON object
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/11199179/38386945-655d7174-38e4-11e8-8a17-ff92d10e21ad.png)

I am passing an object class from an asp project. The value of "InputData" and "InputTranslationResult" are supposed to be JSON strings, but they aren't formatted correctly in postman, is there something I am missing? What is the right string format for postman to show the JSON correctly in the app?

Thanks!

**Comment by kamalaknn** [comment] 2018-04-09 10:34
Hi @Thwar 

From a quick look at your screenshot I could see that the `InputData` and `InputTranslationData` are actual strings. Hence they are formatted as a single string.

If these are part of the same JSON object they must be used without a wrapping `"` quote to prevent them from being treated as a string.

For example,
```json
{
  "Input": "{ \"key\": \"value\" }"
}
```
is different from
```json
{
  "Input": { "key": "value" }
}
```
'Input' is treated as a JSON value in second example, whereas it is treated as a string value in the first example(Note how I had to escape `"` in first example because it is treated as a string.)

Here's an example of a JSON response - http://json.org/example.html

I'm closing this issue as this is not a bug with the Postman App itself. 

Thanks

**Closed as completed by kamalaknn** 2018-04-09 10:34 UTC
