### ISSUE TITLE
POSTMAN Sync does not work.

### ISSUE THREAD

**Issue by syedqadeer** [a85/POSTMan-Chrome-Extension#9397] opened 2021-01-04 14:59 UTC
Hi All,

The postman sync does not work, all the time I am getting the "RED" sync button. When I click on it nothing is synced online.

![image](https://user-images.githubusercontent.com/5575310/103548204-7cd0b880-4eb6-11eb-8307-3764c75dc435.png)

When I signed out, I lost all my work and there is no way to recover it. Please help me with this sync issue.

**Comment by CainDS** [comment] 2021-02-01 16:29
I'm getting the same issue and so is everyone in my team, we've tried updating, downgrading, uninstalling and clearing postman files but nothing works. When looking at the logs I get the following:

`["CloudProxyManager~init: Error while reading proxy configuration from user data - ",{"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\Users\\USER\\AppData\\Roaming\\Postman\\Postman_Config\\proxy","name":"Error","message":"ENOENT: no such file or directory

Which I then thought was a proxy issue, but upon setting the proxy within Postman and restarting the issue is still present.

**Comment by mbopp** [comment] 2021-02-04 15:50
I would be incredibly grateful for a workaround or anything that would allow me to use the app as I am experiencing the same issue. I was able to recover my collections from a backup, but am still unable to use the app. Logs describe the same 'proxy' issue detailed above.

**Comment by syedqadeer** [comment] 2021-02-16 07:44
There is an update and i am not even able to update to the latest version.

![image](https://user-images.githubusercontent.com/5575310/108032659-df83ab00-7043-11eb-8dfe-cc60472f6f35.png)


I am afraid, if download the latest version and install it, I might loose the history again which I cannot afford.

**Comment by nk-gears** [comment] 2021-03-19 09:21
Please let us know how to get the past history. I have been using more than 2 years, looks like i lost all the history now and its not syncing..

**Comment by syedsanahassan** [comment] 2021-04-29 19:09
I have lost my entire history too, please let us know what's the way to recover old history

**Comment by syedqadeer** [comment] 2021-05-31 12:12
Great news,

Updated to latest version beliving that i will be able to use the sync and maintain the history.

But UNFORTUNATELY, the issue didnt fix and lost all the history once again

Not only that, the collections that are stored only are not even rendering

![image](https://user-images.githubusercontent.com/5575310/120191403-8f131080-c222-11eb-8640-66d0094e1894.png)

Screwed up beautifully

**Comment by CoronaFiredancer** [comment] 2021-06-09 08:30
Want to bump this, I have the same issue, unable to upgrade, red sync button doing nothing

**Comment by nk-gears** [comment] 2021-06-15 13:08
> Please let us know how to get the past history. I have been using more than 2 years, looks like i lost all the history now and its not syncing..

Now it's stuck in "Preparing your workspace" for the last few days, going for ever. 
![image](https://user-images.githubusercontent.com/897323/122058060-e0b5c080-ce08-11eb-9679-3f21140a0a87.png)

**Comment by syedqadeer** [comment] 2021-06-15 17:54
Here is what i did.

1. Logout from Existing account ( Note that you will loose all your history )
2. Login with another account
3. VOILA!!! Sync started to work!!

I hope it will keep syncing my data

**Comment by giridharvc7** [comment] 2023-01-19 11:45
@syedqadeer We've made some significant changes to our syncing systems when you are signed in. Please let us know if you still face trouble like this. I'm closing this bug for now.

**Closed as completed by giridharvc7** 2023-01-19 11:45 UTC
Labels: bug, sync, product/runtime
