### ISSUE TITLE
Chinese filename use form-data upload, flask request.files.filename have wrong value

### ISSUE THREAD

**Issue by UranusLin** [a85/POSTMan-Chrome-Extension#9088] opened 2020-09-24 15:17 UTC
**Describe the bug**
use form-data upload Chinese filename file and flask use request.files to get file and files.filename to get the filename, the filename will append " in the string.

**To Reproduce**
1. POST API, Body use form-data and select Chinese filename file 
2. flask use request.files get file and files.filename to get the filename
3. filename have "

<img width="673" alt="截圖 2020-09-24 下午11 07 57" src="https://user-images.githubusercontent.com/5743898/94164809-1520cf80-febc-11ea-8fa0-156949800147.png">
<img width="702" alt="截圖 2020-09-24 下午11 11 29" src="https://user-images.githubusercontent.com/5743898/94164828-19e58380-febc-11ea-9b31-c9122ac20378.png">

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type : Postman for Mac
 - Postman Version: 7.33.1
 - OS:  macOS Catalina 10.15.4（19E287

**Additional context**

**Comment by DannyDainton** [comment] 2020-09-25 10:00
Closing this issue as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/8537

**Closed as completed by DannyDainton** 2020-09-25 10:00 UTC
