### ISSUE TITLE
Variable within variables are not populating when request is sent through pm.sendRequest

### ISSUE THREAD

**Issue by spdkb** [a85/POSTMan-Chrome-Extension#6747] opened 2019-06-19 07:38 UTC
Variable within variables are not populating when request is sent through pm.sendRequest.

1. Create an Global variable of:
key = BaseUrl
value = https://www.microsoft.com:{{PortNumber}}
2. Create environment variable of:
key = PortNumber
value = 1234
Select this environment in Postman

3. In the pre-request script, add:

pm.sendRequest({ method: 'GET',
  url: pm.globals.get("BaseUrl"),
  headers: 
   { 'Postman-Token': '8b7bd3d4-aaa9-414d-8a8f-ea4f0186297d',
     'cache-control': 'no-cache',
     '': '' } }, function (err, response) {
    console.log(response.json());
});

4. Send the request
Note, it will output https://www.microsoft.com:{{PortNumber}}

**Expected output**
https://www.microsoft.com:1234

 - App Type - Native App
 - Postman Version [7.2.1]
 - OS: Windows 10

**Comment by codenirvana** [comment] 2019-06-19 07:53
@spoloju `pm.globals.get` don't resolve nested variables.
We are tracking this feature request here: #5691

There's a workaround for this, Refer: https://github.com/postmanlabs/postman-app-support/issues/6078#issuecomment-479408141

Closing as duplicate of #5691 & #5767

**Closed as completed by codenirvana** 2019-06-19 07:53 UTC
Labels: duplicate, product/runtime

**Comment by spdkb** [comment] 2019-07-03 06:08
@codenirvana - Workaround which you mentioned is not working as per my requirement.  Please let me know if you have any other workarounds to resolve nested variables.

**Comment by codenirvana** [comment] 2019-09-02 10:51
@spoloju Refer https://github.com/postmanlabs/postman-app-support/issues/2922#issuecomment-527101679 for `pm.variables.replaceIn`.

**Comment by spdkb** [comment] 2019-09-03 00:02
Hi, does same method works in Newman or do we need update Newman ??

**Comment by codenirvana** [comment] 2019-09-03 02:59
@spoloju Yes, update Newman to latest (`v4.5.4`).
