### ISSUE TITLE
Undo list isn't cleared if a different request opens in the same tab

### ISSUE THREAD

**Issue by nickm8** [a85/POSTMan-Chrome-Extension#4367] opened 2018-03-22 05:23 UTC
## App Details:
```
Postman for Windows
Version 6.0.9
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Recent
 2. Expected behavior:
Undo list is cleared after swapping to a new request
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
No Logs for this function

~~~
## Replications Steps
1. Ensure you have "Always open requests in new tab" disabled (default setting)
2. Create a collection with two requests (type doesn't matter)
3. Enter any text in Tests sections of both requests and save
4. Close all open requests
5. Open the first request in the collection and open the tests tab
6. Open the second request (this should open in the same tab)
7. Click into the Tests box and press Ctrl + Z (Edit - Undo from the top menu doesn't work)

*Actual Result*
The data from the test section of the first request is put into the test section of the second request.
This could cause all data in the test section to be overwritten by mistake.

*Expected Result*
The Undo list is cleared as you have opened a new request

**Comment by callmeaatrey** [comment] 2018-03-23 13:14
@nickm8 so i was able to reproduce the issue. It seems that the undo stack is not getting reset when you switch between requests. Thanks for bringing this into our attention. We'll look into this and will prioritise this in future releases.

**Comment by sujayvenaik** [comment] 2019-01-13 05:36
Hey @nickm8 
I just tried this out on the latest version 6.7.1 and it seems to be working.
I'm closing this issue. Please let us know if you're still seeing this issue.

**Closed as completed by sujayvenaik** 2019-01-13 05:36 UTC
Labels: bug, user-interface, code-editor
