### ISSUE TITLE
Error ‘something went wrong’ upon Sign in (native app)

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6163] opened 2019-03-27 10:56 UTC
**Describe the bug**
It is not possible to sign into the native app, an error message says: `‘Something went wrong, please try again later’`.

**To Reproduce**
1. Open Postman native app (version 5.5.4)
2. Enter credentials and hit Sign in
3. See error below

![55070870-141ca100-507f-11e9-8038-fb9594da4580](https://user-images.githubusercontent.com/47351631/55071027-71185700-507f-11e9-881e-3b6b51b0374b.png)

**Expected behavior**
Sign into the native without any error. 

**App information (please complete the following information):**
 - App Type: Native App 
 - Postman Version 5.5.4
- OS: Windows

**Additional context**
The credentials are right 
No internet connexion issue
Can log in to the Chrome app successfully 
Clearing local app cache didn’t solve the issue

**Comment by numaanashraf** [comment] 2019-03-28 04:59
@cyrielle-hada This seems to be a really old version of Postman and we would need more information to reproduce this issue.

**Comment by harryi3t** [comment] 2019-04-09 09:19
@cyrielle-hada Are you still facing the issue on the latest version of Postman?

**Comment by numaanashraf** [comment] 2019-04-22 09:52
@cyrielle-hada We are unable to reproduce this issue. Closing for now. Feel free to re-open if the issue still persists.

**Closed as completed by numaanashraf** 2019-04-22 09:52 UTC
