### ISSUE TITLE
Ability to use node mssql in Pre-request scripts

### ISSUE THREAD

**Issue by timothyconnolly5** [a85/POSTMan-Chrome-Extension#5917] opened 2019-02-13 09:25 UTC
It is frustrating that we cannot use node mssql in Pre-request scripts to automate population of environment/global variables.
e.g.:

Get Customer
GET: https://{{baseUrl}}:{{port}}/customers/{{customerid}}

var sql = require('mssql');
var config = {
  user: 'DB_USER',
  password: 'DB_PASSWORD',
  server: 'DB_SERVER',
  database:'DB_NAME'
};
sql.connect(config, function(err) {
   if (err) console.log(err);
   var request = new sql.Request();
   request.query('select TOP 1 CustomerID from Customers', function (err, result) {
	  if (err) console.log(err);
	  console.log(result.recordset);
	  postman.setGlobalVariable('customerid', result.recordset[0].CustomerID);
   });
});

This results in:
There was an error in evaluating the Pre-request Script:  Error: Cannot find module 'mssql'

If we could use mssql, we could automate a lot of data retrieval for complex functional testing which we currently have to do manually.

We have considered loading external scripts, but do not have a solution on how to successfully do this.

**Comment by numaanashraf** [comment] 2019-02-18 12:19
Thanks for the feedback @timothyconnolly5. We are tracking this at a similar issue (#1180). Please follow that thread for updates.

**Comment by numaanashraf** [comment] 2019-02-18 12:19
Duplicate of #1180

**Closed as completed by numaanashraf** 2019-02-18 12:19 UTC
Labels: duplicate
