### ISSUE TITLE
Issues in rendering font colours in the Visualise tab for dark mode

### ISSUE THREAD

**Issue by correaswebert** [a85/POSTMan-Chrome-Extension#9797] opened 2021-04-05 18:52 UTC
**Describe the Issue**

When using dark mode, and checking out the visualise tab, the font colours are not contrasting.

**Steps to Reproduce**

Use dark mode, and check out a collection that supports visualisation. I am referring to the *Student expert* program.

**Screenshots or Videos**

![postman-dark-mode](https://user-images.githubusercontent.com/40336924/113612505-90362000-966d-11eb-915b-5ef120be98e1.png)
![postman-light-mode](https://user-images.githubusercontent.com/40336924/113612729-d3908e80-966d-11eb-8784-9051cc4a4bd7.png)

**Environment Information**

 - Platform Type: Linux
 - Postman Version: 8.1.0
 - Operating System: Ubuntu 20.04

**Additional Context**

*N/A*

**Comment by DannyDainton** [comment] 2021-04-05 19:09
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9505

**Closed as completed** 2021-04-05 19:09 UTC
Labels: duplicate
