### ISSUE TITLE
where is the public shared collections explorer?

### ISSUE THREAD

**Issue by andreinitescu** [a85/POSTMan-Chrome-Extension#1495] opened 2015-10-10 10:24 UTC
I remember Postman had a way to explore public shared collections.
It can be very useful when you want to test out some APIs from popular services and someone already created a Postman collection for the service.
Is that still available?
Thanks!

**Comment by forksofpower** [comment] 2017-04-19 07:33
+1

**Comment by wardhanster** [comment] 2017-05-18 16:54
+1

**Comment by a85** [comment] 2017-06-27 23:15
We have restarted work on this. Closing this as a duplicate of #720

**Comment by a85** [comment] 2017-12-11 12:29
This is available as the Postman API Network in versions 5.5+

**Closed as completed by a85** 2017-12-11 12:29 UTC
Labels: feature
