### ISSUE TITLE
Feature Request - Assign and setup headers in prequest script

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#2291] opened 2016-08-24 18:37 UTC
**Description:**
Pass the headers as an array in the environment variables and then set the headers on the go using pre request script. This is useful when there is a new header introduced and now you have to individually add this header to all requests.
If we have the ability to just pass headers as a list and then parse that list and assign headers to all requests in the pre request script that will ease this a lot

**Version/App Information:**
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Chrome
3. OS details: Windows 7 Professional
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Its not supported from the beggining
6. Expected behaviour: Support setting headers from pre request scripts. Not only the value but the headers themselve

**Steps to reproduce the problem:**
1. Have an environment variable set as:
myHeaders - Header1:value , Header2:value , Header3:value
1. From pre request script do something like:
   var headers = environment.myHeaders.split(",");
   for (var i = 0; i < headers.length ; i++){
   givenHeader = headers[i].split(":");
   postman.setHeaderKey(giveHeader[0]);
   postman.setHeaderValue(giveHeader[1]);
   }
2. This sets all the headers and their values before the request starts

**Comment by tariqghalib** [comment] 2016-08-24 19:21
Also, we could have something similar to what we have for setting variables(postman.setGlobalVariable) as:
postman.setGlobalHeaders (type , key, value) or
request.setHeaders (type, key, value)

**Comment by shamasis** [comment] 2016-12-27 22:43
@a85 pm-api could allow mutating request from an SDK request instance passed to pre-request script.

**Comment by a85** [comment] 2017-02-04 01:20
@shamasis Yeah for sure. pm-api should allow customizing the request as much as possible.

**Comment by codenirvana** [comment] 2019-06-27 08:21
Request mutation via pre-request script is supported in the latest Postman app, Refer https://github.com/postmanlabs/postman-app-support/issues/4631#issuecomment-477766260 for more details.

Closing as duplicate of #4631

**Closed as completed by codenirvana** 2019-06-27 08:21 UTC
Labels: feature, collection-v2, product/runtime
