### ISSUE TITLE
Postman windows native application Postman-win64-7.6.0-Setup  installer failed

### ISSUE THREAD

**Issue by steven7mwesigwa** [a85/POSTMan-Chrome-Extension#7323] opened 2019-09-16 09:08 UTC
**Screenshots**
![postmn-error](https://user-images.githubusercontent.com/24929438/64946017-9f326300-d87a-11e9-962b-c4a32de6b832.PNG)

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : Postman-win64-7.6.0-Setup
 - OS: Windows

**Comment by harryi3t** [comment] 2019-11-03 18:30
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/6707
@steven7mwesigwa I am closing this issue, please subscribe to the original issue for future updates. Also, if you could share some more information about the issue, that would help.

**Closed as completed by harryi3t** 2019-11-03 18:30 UTC
Labels: bug
