### ISSUE TITLE
Unchecked query parameters doesn't appear on the published API documentation but does on "View in web"

### ISSUE THREAD

**Issue by nabihnadhif** [a85/POSTMan-Chrome-Extension#7554] opened 2019-10-29 10:51 UTC
**Describe the bug**
Unchecked query parameters are displayed when we view documentation via "View in web", but not on published documentation.
We use unchecked parameters to tell API users that the parameters are optional.

**Screenshots**
View in Web
<img width="652" alt="Screenshot 2019-10-29 at 11 56 29" src="https://user-images.githubusercontent.com/601134/67761726-2bbc6d80-fa44-11e9-9bab-8e4e3c0078ee.png">

Published documentation
<img width="589" alt="Screenshot 2019-10-29 at 11 59 19" src="https://user-images.githubusercontent.com/601134/67761744-337c1200-fa44-11e9-94b2-1dadaa8a50a5.png">

**Comment by Raja-Simha** [comment] 2020-11-19 10:12
Duplicate of #7301

**Closed as completed** 2020-11-19 10:12 UTC
Labels: feature, product/documentation
