### ISSUE TITLE
BUG: Postman API endpoint to PUT Update Collection is not working

### ISSUE THREAD

**Issue by geoffturk** [a85/POSTMan-Chrome-Extension#8712] opened 2020-06-26 09:40 UTC
**Describe the bug**
The `PUT https://api.getpostman.com/collections/:collectionID` endpoint is not working [as documented](https://documenter.getpostman.com/view/631643/JsLs/?version=latest#aa3701e8-7f99-b421-7d74-0d571b051f3c).

**To Reproduce**
1. [Get a single collection](https://documenter.getpostman.com/view/631643/JsLs/?version=latest#647806d5-492a-eded-1df6-6529b5dc685c) and make some changes to it
2. [Put the updated collection](https://documenter.getpostman.com/view/631643/JsLs/?version=latest#aa3701e8-7f99-b421-7d74-0d571b051f3c)
3. Get the collection again. None of the changes are shown.

**Expected behavior**
I am expecting to see the changes I made reflected when I get the collection again in step 3. This is not happening. 

Also, the `uid` parameter that is returned in the response **is exactly the same** as the `id` parameter.

![image](https://user-images.githubusercontent.com/32190662/85843071-ef8f0780-b7a0-11ea-8b1c-40e6ad37722d.png)

![image](https://user-images.githubusercontent.com/32190662/85843612-b0ad8180-b7a1-11ea-8883-e0109d6cbfb8.png)

According to the documentation, these should be different.

![image](https://user-images.githubusercontent.com/32190662/85843110-0170aa80-b7a1-11ea-8148-7ce53d775c27.png)

![image](https://user-images.githubusercontent.com/32190662/85843142-0df50300-b7a1-11ea-86e7-724e1aca57ea.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.27.0
 - OS: macOSX 10.13.6

**Additional context**
The fact that the `uid` is exactly the same as the `id` and does not have the extra characters at the beginning of it as shown in the documentation leads me to conclude that there is an issue with your API.

**Comment by geoffturk** [comment] 2020-07-06 14:27
@Raja-Simha @ankitjaggi If you need more information or want me to test something else from my side, please let me know. AFAICT, the API endpoint is not working as documented.

**Comment by ash007-postman** [comment] 2020-07-08 09:57
@mohitranka Can you please check and advise.

**Comment by mohitranka** [comment] 2020-07-15 11:11
@geoffturk I tried it now, and could not reproduce the issue ( the changes were reflected). Could you share the standalone collection of the requests that you are making (`GET`, `PUT`), and list the changes you are introducing after `GET`-ing the collection?

**Comment by geoffturk** [comment] 2020-07-17 17:17
@mohitranka I have sent the two files (the original and the one with the changes I am trying to introduce) to Asha through the support.postman.com messaging system.  I also sent her two video links explaining what my issue still is so you can see what happens to the JSON file after I submit my PUT with the changes. It's made some unusual modifications to the URL structure in the JSON file after the PUT was processed (GETting the collection again showed unusual results, which you can see in the second video).

**Comment by mohitranka** [comment] 2020-07-20 10:52
@saswatds could you please triage this issue? I'll share the files with you.

**Comment by mohitranka** [comment] 2020-08-17 14:56
@geoffturk We are not able to reproduce the issue.

The diff of the attached files are about the variables. When you upload the data via Postman, the environment variables get resolved to their values, giving the impression that upload is not working.

Please let me know if that is the case.

**Comment by mohitranka** [comment] 2020-08-25 18:42
Closing the issue, with the assumption that variable resolution was the issue. @geoffturk please re-open this, if that is not the case.

**Closed as completed by mohitranka** 2020-08-25 18:42 UTC
Labels: bug, product/runtime

**Comment by geoffturk** [comment] 2020-09-11 09:25
@mohitranka That was the case. Selecting "No Environment" sorted the issue for me.
