### ISSUE TITLE
Postman and OAuth tokens

### ISSUE THREAD

**Issue by kappaj2** [a85/POSTMan-Chrome-Extension#10143] opened 2021-07-23 06:00 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Yes - we need to be able to select id_token or access_token when talking to AWS API Gateway when using OAuth authorizers.
PLEASE!!!

### Describe the solution you'd like

A simple check box/radio button to select which one of the two you would want to use.

### Describe alternatives you've considered

Use something else than Postman... will be a big shame as it does all we can ask, bar this one small option. This is preventing us from using Postman to run automated testing against AWS APIGateway endpoints.

### Additional context

So many people have asked for this. Why is such a small change with such a bit impact not considered?

**Comment by DannyDainton** [comment] 2021-07-23 06:19
Hey @kappaj2

Could you provide a link to the issues you have noticed where people have asked for this feature, please?

**Comment by kappaj2** [comment] 2021-07-23 07:04
Good morning.
Sure - here are 4 that I could find quickly...
https://github.com/postmanlabs/postman-app-support/issues/1854
https://github.com/postmanlabs/postman-app-support/issues/6987
https://github.com/postmanlabs/postman-app-support/issues/1464
https://github.com/postmanlabs/postman-app-support/issues/492

**Comment by DannyDainton** [comment] 2021-07-23 07:13
Closing this as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/8231

**Closed as completed** 2021-07-23 07:14 UTC
Labels: feature, duplicate

**Comment by kappaj2** [comment] 2021-07-23 07:52
Comment: The other stories/issue are not getting any traction. So this is closed, just another paper in the wind?
