### ISSUE TITLE
Global Proxy Configuration not working in Postman 7.0.9

### ISSUE THREAD

**Issue by nikitha12** [a85/POSTMan-Chrome-Extension#6462] opened 2019-05-10 06:34 UTC
**Describe the bug**
Updated  postman to version 7.0.9. After which I am not able to hit API with Proxy. 
I have turned off 'SSL certificate verification' in Settings > General. 
Able to hit API which don't require proxy.

**To Reproduce**
1. Download Postman 7.0.9
2.Settings>Proxy 
3.Set Global Proxy Setting with a Proxy 
4.Switch off Proxy Auth 
5. Hit an API which requires the Proxy you have set 

**Expected behavior**
Could not get any response
There was an error connecting to {{URL}}.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

**Screenshots**
Proxy Configuration 
![image](https://user-images.githubusercontent.com/36627122/57506942-eb90f380-731a-11e9-8330-c15a26b16098.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g.7.0.9]
 - OS: [e.g. macOS Sierra 10.12.6]

**Additional context**
I downgraded to version 7.0.7 and its working.

**Comment by codenirvana** [comment] 2019-05-10 07:32
@nikitha12 What's the request URL? Does it contain a port? Like `127.0.0.1:9090` etc.

Probably  duplicate of #6364

**Comment by nikitha12** [comment] 2019-05-20 04:42
Yes. Its contains a Port.
Its same bug as in #6364

**Comment by codenirvana** [comment] 2019-05-20 14:04
@nikitha12 This is fixed in the latest version of the Postman App (v7.1.1).

Closing as duplicate of #6364

**Closed as completed by codenirvana** 2019-05-20 14:04 UTC
Labels: bug, Proxy, product/runtime
