### ISSUE TITLE
Enhancement request regarding accessibility and usability to clearly distinguish resolved variable colors.

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#10245] opened 2021-08-24 07:00 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

 At the moment, it's somewhat uneasy to differentiate resolved & unresolved variables in Dark mode.

Un-resolved:
![image](https://user-images.githubusercontent.com/47771757/130571311-7cb87cc1-bf68-4ec0-81fd-10b8477eaa6d.png)

Resolved:
![image](https://user-images.githubusercontent.com/47771757/130571336-9a4825b2-58f9-4f16-a7df-a6edc55e68b5.png)

### Describe the solution you'd like

 Provide an alternative color for resolved variables in Dark mode.

### Describe alternatives you've considered

 Switching to the light mode.

### Additional context

_Filed by Product Support_

**Comment by timbochamp** [comment] 2021-08-24 14:50
I think this is a duplicate of #10028 but feel free to reopen if not!

**Comment by malvikach** [comment] 2022-02-14 12:07
@timbochamp this is a separate issue, I am reopening the ticket to track the same. 
Update: We have started working on this.

**Comment by malvikach** [comment] 2022-03-14 09:27
The changes for this have been released in Postman 9.14.12. Please read about it more [here](https://blog.postman.com/identify-unresolved-variables-easily/) or on our [learning center](https://learning.postman.com/docs/sending-requests/variables/#fixing-unresolved-variables).

**Closed as completed by malvikach** 2022-03-14 09:27 UTC
Labels: feature, variables, product/runtime
