### ISSUE TITLE
Unable to View collection on Web dashboard

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#7400] opened 2019-09-27 07:15 UTC
**Describe the bug**
After importing a ~6000 line long OAS yaml file. The application hangs and displays a black window. However, after reopening the Postman app, the collection was present in the collection tab and clicking on the "View in Web" redirects to error - page doesn't exist.

**To Reproduce**
1. Import the yaml file
2. Application hangs
3. Quit and reopen the application to see the imported collection
4. Expand the collection and click on "View on Web"

**Expected behavior**
Be able to view this collection on web

**Screenshots**
<img width="822" alt="Screen Shot 2019-09-27 at 12 07 25 PM" src="https://user-images.githubusercontent.com/47771757/65749359-90be3400-e123-11e9-8ed7-151b9e58ad6f.png">

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.8
 - OS: Windows

**Comment by ankit-m** [comment] 2019-09-27 10:13
@Raj-postman can you ensure that the collection was synced? (Is the sync icon on top right orange?) Also, do you see the collection listed under the `Collections` in the dashboard?

**Comment by godfrzero** [comment] 2019-09-27 10:22
Based on the information we have, this is most probably caused by or related to https://github.com/postmanlabs/postman-app-support/issues/7037

**Comment by Raj-postman** [comment] 2019-10-01 05:48
@ankit-m This looks like more of #7037 issue. Once the file is uploaded then the window turns black. After restarting the application, the collection appears on the app but the same collection isn't synced to the web dashboard. The sync icon is orange as soon as the app is restarted but after checking the collection from Web dashboard the icon keeps spinning (blue).

In addition, once I import the provided file(yaml) which is of size 136KB and when the same file is exported, then its size becomes 236MB.

**Comment by ankit-m** [comment] 2019-11-25 09:13
Duplicate of #7037

**Closed as completed by ankit-m** 2019-11-25 09:13 UTC
Labels: version-control, blocked/need-info
