### ISSUE TITLE
VS Code extension - no option to move requests or drag & drop

### ISSUE THREAD

**Issue by NandoZee** [a85/POSTMan-Chrome-Extension#12598] opened 2024-01-24 22:33 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I'd say so, a basic & necessary functionality is missing.

### Describe the solution you'd like

Enable drag & drop, or at least add a "Move" option to the context menu.

### Describe alternatives you've considered

Desktop Postman is unusable for me because the new version (January 2024) hangs my System process in Windows and renders my mouse unusable, but that's a different problem altogether.

**Comment by pankajk07** [comment] 2024-08-06 08:11
Closing this issue as this is the duplicate of https://github.com/postmanlabs/postman-app-support/issues/12475

**Closed as completed by pankajk07** 2024-08-06 08:11 UTC
Labels: feature, product/ide-platform, vscode
