### ISSUE TITLE
WSDL support - elementFormDefault=qualified and attributeFormDefault=qualified not honoured

### ISSUE THREAD

**Issue by rrobb** [a85/POSTMan-Chrome-Extension#11768] opened 2023-02-27 14:56 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am having issues with XML generated from an imported WSDL that contains `elementFormDefault` and `attributeFormDefault` attributes, both set to `"qualified"`. 
The generated XML does not reflect these attributes; neither the elements nor their attributes receive a prefix. The resulting SOAP request is not accepted by Workday, returning a 500 response. I can fix this and make a successful request by manually adding the prefixes:
### Generated partial XML:
```xml
<soap:Body>
    <Get_Workers_Request xmlns="urn:com.workday/bsvc" wd:version="v39.0">
        <Request_References Skip_Non_Existing_Instances="true" Ignore_Invalid_References="true">
            <Worker_Reference Descriptor="string">
                <ID type="Employee_ID">{{employee_id}}</ID>
            </Worker_Reference>
        </Request_References>
    </Get_Workers_Request>
</soap:Body>
```
### 'Fixed' partial XML:
```xml
<soap:Body>
    <bsvc:Get_Workers_Request xmlns:bsvc="urn:com.workday/bsvc" bsvc:version="v39.0">
        <bsvc:Request_References bsvc:Skip_Non_Existing_Instances="true" bsvc:Ignore_Invalid_References="true">
            <bsvc:Worker_Reference bsvc:Descriptor="string">
                <bsvc:ID bsvc:type="Employee_ID">{{employee_id}}</bsvc:ID>
            </bsvc:Worker_Reference>
        </bsvc:Request_References>
    </bsvc:Get_Workers_Request>
</soap:Body>
```
### Partial WSDL:
`elementFormDefault` and `attributeFormDefault` found on line 4
```xml
1 <wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wd-wsdl="urn:com.workday/bsvc/Human_Resources" xmlns:wd="urn:com.workday/bsvc" xmlns:nyw="urn:com.netyourwork/aod" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapbind="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:httpbind="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mimebind="http://schemas.xmlsoap.org/wsdl/mime/" name="Human_Resources" targetNamespace="urn:com.workday/bsvc/Human_Resources">
2     <wsdl:documentation>The Human Resources Web Service contains operations that expose Workday Human Capital Management Business Services data, including Employee, Contingent Worker and Organization information. This Web Service can be used for integration with enterprise systems including corporate directories, data analysis tools, email or other provisioning sub-systems, or any other systems needing Worker and/or Organization data.</wsdl:documentation>
3     <wsdl:types>
4         <xsd:schema elementFormDefault="qualified" attributeFormDefault="qualified" targetNamespace="urn:com.workday/bsvc">
5         --- truncated ---
```
A [w3schools](https://www.w3schools.com/xml/el_schema.asp) article that describes the expected behaviour:
> attributeFormDefault: "qualified" indicates that attributes from the target namespace must be qualified with the namespace prefix

> elementFormDefault: "qualified" indicates that elements from the target namespace must be qualified with the namespace prefix

### Steps To Reproduce

1. Import the WSDL: Click 'import', then 'link' and import this [wsdl file](https://wd3-impl-services1.workday.com/ccx/service/bmo/Human_Resources/v39.0?wsdl) and click 'import' again to start the process.
2. In the newly created service, select any request, for example `Get_Workers`
3. Examining the request body will show that none of the element attributes (except `version`) have a prefix even though the WSDL contains `elementFormDefault="qualified" attributeFormDefault="qualified"`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <Get_Workers_Request xmlns="urn:com.workday/bsvc" wd:version="v39.0">
      <Request_References Skip_Non_Existing_Instances="true" Ignore_Invalid_References="true">
        <Worker_Reference Descriptor="string">
          <ID type="string"/>
        </Worker_Reference>
      </Request_References>
      --- truncated ---
    </Get_Workers_Request>
  </soap:Body>
</soap:Envelope>
```

### Operating System

Mac OS

### Postman Version

10.10.5

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by akshaydeo** [comment] 2023-02-28 05:02
@rrobb, thanks for reporting this issue. We are looking into it. I will keep this ticket updated as we push out the fix.

**Comment by VShingala** [comment] 2023-04-18 11:33
@rrobb We needed a bit of information regarding this issue. In the mentioned file, `wd` is mentioned as a namespace prefix for URI `urn:com.workday/bsvc` which is the `targetNamespace` for mentioned `schema`.

In this case, would be having `wd` prefix in SOAP envelop body before each element attributes works? or `bsvc` as namespace is needed?

**Comment by rrobb** [comment] 2023-04-18 18:04
Hi @VShingala , and thanks! 
That should be fine I think, below request using the `wd` prefix for both elements and attributes gives me a valid 200 response. Does that answer your question?

```xml
<soapenv:Envelope xmlns:wd="urn:com.workday/bsvc" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header>
        <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            <wsse:UsernameToken wsu:Id="UsernameToken">
                <wsse:Username>{{username}}</wsse:Username>
                <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">{{password}}</wsse:Password>
            </wsse:UsernameToken>
        </wsse:Security>
    </soapenv:Header>
    <soapenv:Body>
        <wd:Get_Workers_Request wd:version="v37.1">
            <wd:Response_Filter>
                <wd:Page>1</wd:Page>
                <!--Optional:-->
                <wd:Count>1</wd:Count>
            </wd:Response_Filter>
        </wd:Get_Workers_Request>
    </soapenv:Body>
</soapenv:Envelope>
```

**Comment by VShingala** [comment] 2023-04-19 07:38
@rrobb Thanks for the quick response! Yes, it does answer my question. We'll inform here once we do have a fix for this issue.

**Comment by rrobb** [comment] 2023-04-19 07:46
Thanks @VShingala ! Looking forward to using this in Postman!

**Comment by VShingala** [comment] 2023-06-22 13:24
@rrobb We wanted a bit of feedback regarding the fix we're working. I've provided the collection that gets generated after the fix we've worked upon below. Could you import this file and give it a try and let us know if it works as intended and any further feedback?

[collection.txt](https://github.com/postmanlabs/postman-app-support/files/11834373/collection.txt)

**Comment by rrobb** [comment] 2023-06-27 12:41
Hi @VShingala , sorry for the delayed response. This works, here's a request and a partial response. I had to add a soap header but did not need to touch the xml itself in any way:

```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
{{SOAPHeader}}
  <soap:Body>
    <wd:Get_Locations_Request xmlns:wd="urn:com.workday/bsvc" wd:version="v39.0">
      <wd:Request_Criteria>
      </wd:Request_Criteria>
      <wd:Response_Filter>
        <wd:Page>1</wd:Page>
        <wd:Count>100</wd:Count>
      </wd:Response_Filter>
      <wd:Response_Group>
        <wd:Include_Reference>true</wd:Include_Reference>
        <wd:Include_Location_Data>true</wd:Include_Location_Data>
      </wd:Response_Group>
    </wd:Get_Locations_Request>
  </soap:Body>
</soap:Envelope>
```

```xml
<?xml version='1.0' encoding='UTF-8'?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
    <env:Body>
        <wd:Get_Locations_Response xmlns:wd="urn:com.workday/bsvc" wd:version="v39.0">
            <wd:Response_Filter>
                <wd:Page>1</wd:Page>
                <wd:Count>100</wd:Count>
            </wd:Response_Filter>
            <wd:Response_Group>
                <wd:Include_Reference>1</wd:Include_Reference>
                <wd:Include_Location_Data>1</wd:Include_Location_Data>
            </wd:Response_Group>
            <wd:Response_Results>
                <wd:Total_Results>227</wd:Total_Results>
                <wd:Total_Pages>3</wd:Total_Pages>
                <wd:Page_Results>100</wd:Page_Results>
                <wd:Page>1</wd:Page>
            </wd:Response_Results>
            <wd:Response_Data>
                <wd:Location>
                    <wd:Location_Reference>
                        <wd:ID wd:type="WID">83d424edebf44b10a31ca67a095cb46f</wd:ID>
                        <wd:ID wd:type="Location_ID">Kuala_Lumpur_site</wd:ID>
                    </wd:Location_Reference>
                    <wd:Location_Data>
                        <wd:Location_ID>Kuala_Lumpur_site</wd:Location_ID>
                        <wd:Location_Name>Kuala Lumpur</wd:Location_Name>
                        <wd:Location_Usage_Reference>
--SNIP--
```

**Comment by VShingala** [comment] 2023-06-27 13:25
@rrobb Thanks for getting back! We've worked upon the fix for this and this fix will be available on Postman app release coming up next month (~15th July). i.e. With Postman App version v10.16.

**Comment by VShingala** [comment] 2024-07-11 17:13
Closing the issue since this has been fixed! Here's request body that we now generate for mentioned example which contains prefix based on mentioned props `attributeFormDefault` and `elementFormDefault`.

<img width="1230" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/16756296/3c343c36-dc26-4202-ba99-9cb4d39f963c">

**Closed as completed by VShingala** 2024-07-11 17:13 UTC
Labels: bug, product/importers
