### ISSUE TITLE
sub-variable is not replaced with getEnvironmentVariable()

### ISSUE THREAD

**Issue by iredmail** [a85/POSTMan-Chrome-Extension#2434] opened 2016-10-26 11:35 UTC
1. Postman Version: 4.7,2 & 4.8.0
2. App (Chrome app or Mac app): Mac app
3. OS details: macOS 10.12
4. Did you encounter this recently, or has this bug always been there: ALWAYS

Steps to reproduce the problem:

In environment, define two vars:

```
a: 1,2,3
b: 4,5,6,{{a}}
```

In tests, write code like below:

```
console.log(postman.getEnvironmentVariable("b"));
```

It logs`4,5,6,{{a}}]`, but expected value is: `4,5,6,1,2,3`.

**Comment by sdnts** [comment] 2016-10-26 12:21
@iredmail Thanks for reporting this. We'll get on a fix and will let you know when it is released.

**Comment by iredmail** [comment] 2016-10-26 12:22
Does postman team offer nightly build?

**Comment by sdnts** [comment] 2016-10-26 12:30
@iredmail Not as of now.

On second thought, the function `postman.getEnvironmentVariable` returns you back the _value_ of the variable, but it does not _resolve_ the variable, which is the correct behaviour. We will look into adding a function to the pre-request script / test sandbox that allows you to resolve variables.

For now, can you use some sort of regular-expression based loop to recursively resolve your variable?

**Comment by iredmail** [comment] 2016-10-26 12:32
> For now, can you use some sort of regular-expression based loop to recursively resolve your variable?

I have no idea how to do this in my tests. It's better done by Postman: if it detects sub-variable in value, recursively resolve the variable.

**Comment by sdnts** [comment] 2016-10-27 12:02
@iredmail I agree. We're thinking of adding a function to the sandbox that resolves variables. Will keep you updated.

**Comment by skyboyer** [comment] 2017-04-07 21:51
```javascript
function replaceVariable(str) {
 var areValidVarsFound;
 do {
   str = str.replace(/\{{2}(\w+)\}{2}/g, 
      function (possibleVariableName) {
          var variableValue =
             _.chain[(data && data[possibleVariableName]),
              postman.getEnvironmentVariable(possibleVariableName),
              postman.getGlobalVariable(possibleVariableName)].
              filter(_.isString).
              first().
              value();

          if (_.isUndefined(variableValue)) {
             return '{{' + possibleVariableName + '}}'; // at least I tried :'(
          } else {
             areValidVarsFound = true;
             return variableValue;
          }
      }
   );
 } while(areValidVarsFound); // value just injected may also contain variables... 
 return str;
}
```

**Comment by rmorrise** [comment] 2019-01-31 20:57
Any update on this?

**Comment by JP-from-Postman** [comment] 2019-04-23 17:28
Would be great to add this for the current pm.____.get methods:

pm.variables.get()
pm.environment.get()
pm.globals.get()

**Comment by codenirvana** [comment] 2019-04-23 17:52
Duplicate of #5767

A workaround for this:
```javascript
pm.environment.set("a", "1,2,3");
pm.environment.set("b", "4,5,6,{{a}}");

const {Property} = require('postman-collection');

let resolved = Property.replaceSubstitutions(pm.environment.get("b"), pm.variables.toObject());

console.log(resolved);
```

**Closed as completed by codenirvana** 2019-04-23 17:52 UTC
Labels: feature, variables
