### ISSUE TITLE
Monitor Dashboard Response Time 

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#7005] opened 2019-07-26 19:07 UTC
Filed by Support on behalf of the original user. 

**Describe the bug**
Monitor dashboard Test may be running be checking against the total time of request with Pre-request and Test script rather than Response Time. 

**To Reproduce**
Unable to reproduce by Support. 

User's test script: 
```
pm.test("Response time is less than 3000ms", function () { 
    pm.expect(pm.response.responseTime).to.be.below(3000); 
}); 
```
Runs in Monitor Dashboard and test will pass even when response time is above 3000ms.

**Expected behavior**
Expect to tests to fail when using `responseTime` attribute in `pm` object is higher than given threshold in Test script. 

**Screenshots**
![TimeResponseIsWrong](https://user-images.githubusercontent.com/5624835/61974663-f06d5700-af9b-11e9-9b0f-eb4edbec6d1d.png)

**App information (please complete the following information):**
 - Monitor Dashboard 

**Additional context**
There might be some inflation being added to the response time shown in the monitor dashboard and when the Test script is using it for testing.

**Comment by codenirvana** [comment] 2019-08-20 13:50
@stcalica Not able to reproduce this issue.
The screenshot doesn't help either, the assertion message can be different than actually `.to.be.below(3000)`.

Note: `pm.response.responseTime` is just the request-response time (not influenced by script execution time).

Also, by "monitor dashboard" do you/user means collection runner?

**Comment by stcalica** [comment] 2019-08-20 18:06
@codenirvana User expressed this only happened in Monitor runs, not when running from app manually.

**Comment by godfrzero** [comment] 2019-12-26 07:16
@stcalica Would it be possible for the user to share this part of the collection with us? If it's not possible to share the entire request, just the test script should be enough (I'm assuming that the test script in the ticket is not the complete script).

**Comment by shivam-postman** [comment] 2020-02-03 08:26
@stcalica, any updates from the user?

**Comment by ArjunSingh-PM** [comment] 2020-02-14 10:21
Closing this issue as this is not reproducible and there has not been an update on this issue for an extended period.

@stcalica Please reopen this issue if you have additional information that is requested here

**Closed as completed by ArjunSingh-PM** 2020-02-14 10:21 UTC
Labels: bug, product/automation-testing, blocked/need-info
