### ISSUE TITLE
Extraneous newlines in formatting of XML response

### ISSUE THREAD

**Issue by BrakTalk** [a85/POSTMan-Chrome-Extension#1910] opened 2016-03-22 16:51 UTC
Not sure if this is a config issue on my end but the formatting of the XML responses requires an unnecessary/extra step in our workflows.

![image](https://cloud.githubusercontent.com/assets/646062/13959976/b8a532c0-f02c-11e5-82cb-dd8cf1287aa7.png)

**Comment by abhijitkane** [comment] 2016-03-22 17:58
@BrakTalk Didn't realise this was the same issue as the twitter thread. In the Mac app, you can open the console with Cmd+Option+I.

Also, can you paste the raw response (from the raw tab) here? Probably an issue with our XML formatter.

**Comment by BrakTalk** [comment] 2016-03-22 18:01
This is Win32.  Due to sensitive nature of data, I am unable to post the response.  Is there a public test API you would suggest and see if it's reproducible there?

**Comment by abhijitkane** [comment] 2016-03-25 10:18
Can you include the raw body part that corresponds to the section shared in your first screenshot?

**Comment by BrakTalk** [comment] 2016-04-12 18:42
So, I wouldn't have to provide a complete block?  Just a part of it?

**Comment by abhijitkane** [comment] 2016-04-12 21:28
No, just enough so we can reproduce the problem.

**Comment by lasselehtinen** [comment] 2016-04-14 08:37
I have the same issue. I have nothing confidential in the XML, so i've [provided a gist here](https://gist.github.com/lasselehtinen/87e9c79228b03a4624f430ea9c6da659) for the raw output.

![image](https://cloud.githubusercontent.com/assets/1290186/14522019/3e90dc94-0235-11e6-8246-defc4156fd90.png)

![image](https://cloud.githubusercontent.com/assets/1290186/14522024/42d7a1c0-0235-11e6-851a-7eee0ede9657.png)

**Comment by abhijitkane** [comment] 2016-04-26 13:14
Thanks @lasselehtinen. Our parser seems to be detecting an extra newline after certain closing tags. We'll push a fix in the next release.

**Comment by abhijitkane** [comment] 2016-05-16 09:38
@BrakTalk @lasselehtinen Can you confirm this fixed in the latest version of the app?

**Comment by lasselehtinen** [comment] 2016-05-16 19:05
@abhijitkane Fix confirmed on my end. XML looks good as it can get.

**Closed as completed** 2016-05-16 19:06 UTC
