### ISSUE TITLE
API stops responding on custom domain

### ISSUE THREAD

**Issue by jifka** [a85/POSTMan-Chrome-Extension#5589] opened 2018-11-29 19:28 UTC
**Describe the bug**
We have an API published on Postman using a custom domain. So our API documentation can be seen at restapi.mycompany.com (not the real address, but the subdomain is the same).

Occasionally, we check the API docs and we get a 404 error coming from the Postman server. This is not a 404 from the browser, and not a DNS issue because we're getting to the Postman server and seeing a Postman 404 error page.

We check the API configuration and it says that it's published. 
We check the custom domain and it's correct.

We then unpublish and republish in Postman and it starts responding again. No other changes are made. Then a few weeks/months go by and our API is down again.  We have no idea what's precipitating this as we're not making changes to the API itself.

**Comment by godfrzero** [comment] 2018-11-30 03:18
Are you publishing using an environment? What's the error message displayed on the 404 page?

**Comment by jifka** [comment] 2018-11-30 03:24
I'm not sure I understand the first question. I'm using the Postman web-based Dashboard and publishing a Collection within a Workspace. From the Publish screen I'm using a custom URL.

As for the 404 message, it's the page you get on Postman when your API isn't published. It's the same page you get when you hit an invalid URL like this:  https://www.getpostman.com/foobar/

Every time this happens, I go back to the collection and hit "Publish" and it says it's already published. I take it offline and re-publish it and it works again...until the next time.

**Comment by godfrzero** [comment] 2018-11-30 03:34
A published documentation can be a collection, or a collection + environment combo. If you have an environment published as well, and the environment is deleted or removed from the team, the public documentation will display a 404 since it can't find one of the published elements. This is something that can be fixed by "republishing" since a new environment or no environment will be used.

If a custom domain is being used, and revalidation of the custom domain fails, that can also trigger a 404. 

Let me know if there were any changes to the collection/environment prior to the 404 showing up. If not, I'll dig around and see if there's an issue with the custom domain association.

**Comment by jifka** [comment] 2018-11-30 04:24
Ah, I do have environments set up in the workspace, but do not believe any of them were deleted or removed form the team.

**Comment by Raja-Simha** [comment] 2019-04-09 04:44
Hi @jifka , could you please check if this issue is still persistent. Thanks,

**Comment by Raja-Simha** [comment] 2019-04-16 04:53
Hi @jifka, we are closing this issue as we are unable to proceed further without additional information on reproducing the issue. Please do reopen if you find that the issue is still persistent. Thanks,

**Closed as completed by Raja-Simha** 2019-04-16 04:53 UTC
Labels: bug, product/documentation
