### ISSUE TITLE
Clicking Retry after modifying a Test doesn't run the scripts with the modifications

### ISSUE THREAD

**Issue by Quietbeat** [a85/POSTMan-Chrome-Extension#7799] opened 2019-12-13 15:59 UTC
**Is your feature request related to a problem? Please describe.**
Ye, related to a Bug I created: #7780

My Collection has 4 Collection variables and numerous API requests. Each Request has a parameterized URL along with 7 Tests and a test data file. If I start the Collection runner, modify a Test then click Retry in the Collection Runner, it will use the Collection Variable default values instead of the data from the test data file. I start the Collection runner, modify a Test then click on the Collection Runner tab then click "Run ", then it'll correctly use the test data.

**Describe the solution you'd like**
When using a data file and the Retry button is clicked, 1) the CR will always use the data file and 2) the iteration count will reset.

**Describe alternatives you've considered**
I've wasted my time going back to CR to manually reset everything and reattach the file.

**Additional context**

**Comment by appurva21** [comment] 2020-02-11 10:05
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/7780

**Closed as completed by appurva21** 2020-02-11 10:05 UTC
Labels: collection-runner, duplicate, product/runtime
