### ISSUE TITLE
Duplicating Environments doesn't keep nested environment variables

### ISSUE THREAD

**Issue by S33G** [a85/POSTMan-Chrome-Extension#7718] opened 2019-11-28 15:53 UTC
I noticed a small thing when duplicating environments which I wasn't sure the behavior was expected or not.

**Describe the bug**
When duplicating an environment, I expect values to still contain dynamic child variables.

**To Reproduce**
1. Create a new environment
2. Create 2 variables inside said environment (e.g. `baseUrl` & `version`)
3. Make the value of these variables as follows: `baseUrl = foo.bar/{{version}}` `version = v1`
4. Duplicate the environment
5. Notice that `foo.bar/v1` is now a static variable with no dynamic version number

**Expected behavior**
I expect the child variables to still exist in duplicated environment

**Screenshots**
Can provide screenshots if needed

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.10.0 linux 5.0.0-36-generic / x64
 - OS: Ubuntu 18.04

Cheers!

**Comment by shamasis** [comment] 2020-03-10 15:27
How are you duplicating the environment? Clicking the duplicate button on the listing row? If so, I could not reproduce this. I am using latest app version though.

**Comment by mohitranka** [comment] 2020-07-06 07:31
Closing the issue as we cannot reproduce it at our end. @charj please comment if it still happens for you.

**Closed as completed by mohitranka** 2020-07-06 07:31 UTC
Labels: bug, product/runtime
