### ISSUE TITLE
Request to remove right hand code snippet inside documentation page

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6171] opened 2019-03-28 06:44 UTC
**Is your feature request related to a problem? Please describe.**

I need to better understand the right-hand code snippet and to find out if there is a way to remove it.  It literally is taking up 1/2 of the viewable area and is 100% useless.  No programmer that I've ever worked with has ever used those code samples and it totally jacks up the documentation by scrunching everything down into a narrow column. Please remove it or tell me how I might be able to remove it so our partners don't have to deal with it.

**Describe the solution you'd like**
Remove the code snippet or there should be an option to hide it
![Hide documentation](https://user-images.githubusercontent.com/41741228/55146455-a188ef80-516a-11e9-812f-fe1fb0098df0.jpg)

**Comment by Raja-Simha** [comment] 2019-03-28 09:09
@ash007-postman can you please add the images sent by the user. Thanks,

**Comment by Raja-Simha** [comment] 2019-07-23 14:41
Duplicate of #5263

**Closed as completed by Raja-Simha** 2019-07-23 14:41 UTC
Labels: feature, product/documentation
