### ISSUE TITLE
Team admin unable to manage a workspace - delete option is greyed out

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7382] opened 2019-09-24 20:57 UTC
**Describe the bug**
Team admin is unable to manage a team workspace as no role shows up against their name.
Delete option is greyed out.

*Context:*
The users that were showing up as admin in these workspaces are no longer with organization and have been removed from the team.
Team admin want's to reclaim these workspaces and delete after exporting out any data within the workspaces.

**To Reproduce**
I was unable to reproduce this behaviour.
Check out the screenshots describing what the user sees.

**Expected behaviour**
Team admin should be able to delete teams, apart from other admin related actions.

**Screenshots**
*No Role Dropdown is shown*
![image](https://user-images.githubusercontent.com/21366/65549217-341b1780-df71-11e9-9a66-5e71bdc43cc1.png)

*The option to delete the team is greyed out*
![image](https://user-images.githubusercontent.com/21366/65549266-4c8b3200-df71-11e9-8159-431ecf5567d4.png)

**App information (please complete the following information):**
 - App Type: Postman Native
 - Postman Version 7.7.3

**Additional context**
Logged by Postman on behalf of a user.
More details provided internally.

**Comment by sankalp0o** [comment] 2019-09-25 08:53
Thanks for reporting this Amit! This looks like a bug because all members of a workspace should have some role on the workspace. I'd also like to highlight a couple of other points that I noticed.

> Team admin should be able to delete teams,...
Deleting teams is a very distinct action and has nothing to do with deleting workspaces (which is what you're trying to do, as I gather from the screenshot).

> Team admin want's to reclaim these workspaces...
The fact that this person is a "Team Admin" has no bearing on the actions on a workspace. In Postman world, team admins are support accounts. They have control over team members etc, but very little control over the data in the team. Technically, they'd need the "Developer" role to be able to even see the workspace, which itself has no special privilege in team workspaces.

I'll keep you updated on the progress on the bug.

**Comment by sankalp0o** [comment] 2019-09-25 08:57
Meanwhile, if all the other Workspace Admins are removed from the team (user #3 and user#4 in your screenshot), the whole team will get Workspace Admin role. That'll enable you to manage the workspace and reset roles.

**Comment by akaczinski** [comment] 2019-09-27 17:01
Experiencing a similar issue, cannot delete workspace from app or online portal.

**Comment by Millais** [comment] 2019-09-30 15:11
Similar/duplicate of #6102

**Comment by sankalp0o** [comment] 2019-10-17 03:50
@xk0der We've updated the messaging so that users don't see the "No dropdown" state and are informed that they have a role that is inherited from the Team's role on the workspace.

I know this doesn't solve the root problem that admins are not able to delete workspaces. We will track that on #6102 (which is a feature request since this is expected behaviour) and keep everyone updated on how and when we solve it. Please feel free to leave comments in case you have some inputs.

**Closed as completed by sankalp0o** 2019-10-17 03:50 UTC
Labels: bug
