### ISSUE TITLE
When editing a collection, authorization variables are behind the collection popover

### ISSUE THREAD

**Issue by Hrafnkellos** [a85/POSTMan-Chrome-Extension#9398] opened 2021-01-04 16:08 UTC
**Describe the Issue**
The intellisens autocomplete helper is located in a layer behind the popover so its hard to use properly.
![image](https://user-images.githubusercontent.com/2863090/103554471-e6e16180-4ea6-11eb-9810-d9da26957985.png)

**Steps to Reproduce**
Try to create a variable and using it in the authorization tab of a collection.

**Comment by DannyDainton** [comment] 2021-01-05 09:55
Closing this as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/8819 but on a different modal.

**Closed as completed by DannyDainton** 2021-01-05 09:55 UTC
Labels: duplicate
