### ISSUE TITLE
Allow Postman app's top window bar to adjust for "Dark mode"

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5294] opened 2018-10-02 23:29 UTC
The current light-grey window bar at the top of the Postman app contrasts pretty sharply in macOS Mojave's "Dark mode" (and against the apps "Dark" theme).

Would be nice to allow the window bar color to suit "Dark mode/theme" viewing.

**Comment by tyrann0us** [comment] 2018-12-13 09:38
And maybe Postman should automatically use the Dark Theme if macOS's Dark Mode is active?

**Comment by LunaticoCR** [comment] 2019-03-22 15:18
I'd love to see Postman in Dark Mode. With more and more apps introducing dark mode, and with macOS Majave introducing it at a system wide level, now every time I open Postman my eyes hurt a bit because they're used to all the other dark apps.
Is this being considered?

**Comment by preethammavin** [comment] 2019-03-22 15:25
@LunaticoCR We do have a dark theme, in the setting page of the app under theme.

**Comment by LunaticoCR** [comment] 2019-03-22 17:14
Ah thanks for for pointing that out @preethammavin ! It looks great!

**Comment by diegogsann** [comment] 2019-04-13 19:08
have any prevision to implemented this feature?

**Comment by Hackmodford** [comment] 2019-06-04 17:39
+1

**Comment by martinburyak** [comment] 2019-07-22 11:37
+1

**Comment by KaminKevCrew** [comment] 2019-08-01 17:50
+1

**Comment by Hossman333** [comment] 2019-08-14 14:16
iTerm has done a great job with this. Something like this would be way nice 
![image](https://user-images.githubusercontent.com/2993997/63028298-cb1d8b80-be6b-11e9-9f05-f3088e121513.png)

**Comment by GrzegorzWidla** [comment] 2019-10-02 06:26
> 
> 
> And maybe Postman should automatically use the Dark Theme if macOS's Dark Mode is active?

And on Windows 10 too!

**Comment by blackcater** [comment] 2019-10-10 07:46
Any update?

**Comment by Hossman333** [comment] 2019-10-17 21:12
Hoping this becomes a priority soon!

**Comment by Kozaar89** [comment] 2020-03-04 12:59
+1

**Comment by aleksspeaker** [comment] 2020-03-27 07:41
Yea, I'm switching dark/light back and forth twice a day.
All my other apps do that on their own.

Pleeeeeeeeeeease 🙏 🙏 🙏

**Comment by tm1819** [comment] 2020-04-15 19:21
it can be fixed with the dark theme plus this and restarting the app:
defaults write com.postmanlabs.mac NSRequiresAquaSystemAppearance 0

**Comment by harryi3t** [comment] 2020-04-16 13:54
Hi, 
We've pushed an update on our early access canary channel that should resolve this issue. Do try it out and let us know

You can get the canary app from https://www.getpostman.com/downloads/canary

**Comment by Hackmodford** [comment] 2020-04-16 18:50
Looks good to me. I would also recommend having an option to switch between light/dark theme based on OS preference.

**Comment by twitharshil** [comment] 2020-05-21 16:19
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/5302

**Closed as completed by twitharshil** 2020-05-21 16:19 UTC
Labels: feature, user-interface
