### ISSUE TITLE
Not able to launch postman app 6.5.2 Windows 8

### ISSUE THREAD

**Issue by jagathjanani95** [a85/POSTMan-Chrome-Extension#5517] opened 2018-11-12 06:36 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by kamalaknn** [comment] 2018-11-12 06:42
Hi @jagathjanani95 

Can you give us some details to help us debug this issue?

Can you send a screenshot of the error you are seeing? Can you also send the logs from `View -> Developer -> View Logs in Explorer`?

Also which version were you on before updating Postman?

**Comment by jagathjanani95** [comment] 2018-11-12 06:51
Hi,
 
Please find the below screenshots.
 
Previous version used is 5.5.3 for which am getting the below error and also am not able to find any logs.
 
Error Screenshot for version 5.5.3 
 

 
Error Screenshot for version 6.5.2 
 
 


Regards,Janani M
-----Original Message-----From: "Kamalakannan" <notifications@github.com>Sent: Monday, 12 November, 2018 12:12pmTo: "postmanlabs/postman-app-support" <postman-app-support@noreply.github.com>Cc: "jagathjanani95" <jagathjanani_manoharan@thbs.com>, "Mention" <mention@noreply.github.com>Subject: Re: [postmanlabs/postman-app-support] Not able to launch postman app. PFB error.To Reproduce Steps to reproduce the behavior: 1) Open App 2)See error Postman Version: 6.5.2 OS:Windows 8 (#5517)

Hi @jagathjanani95
Can you give us some details to help us debug this issue?
Can you send a screenshot of the error you are seeing? Can you also send the logs from View -> Developer -> View Logs in Explorer?
Also which version were you on before updating Postman?
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
******* DISCLAIMER: This email and any files transmitted with it are privileged and confidential information and intended solely for the use of the individual or entity to which they are addressed. If you are not the intended recipient, please notify the sender by e-mail and delete the original message. Further, you are not to copy, disclose, or distribute this e-mail or its contents to any other person and any such actions are unlawful. This e-mail may contain viruses. Torry Harris Business Solutions has taken every reasonable precaution to minimize this risk, but is not liable for any damage you may sustain as a result of any virus in this e-mail.  The recipient should check this email and any attachments for the presence of viruses. THBS reserves the right to monitor and review the content of all messages sent to or from this e-mail address********


******* DISCLAIMER: This email and any files transmitted with it are privileged and confidential information and intended solely for the use of the individual or entity to which they are addressed. If you are not the intended recipient, please notify the sender by e-mail and delete the original message. Further, you are not to copy, disclose, or distribute this e-mail or its contents to any other person and any such actions are unlawful. This e-mail may contain viruses. Torry Harris Business Solutions has taken every reasonable precaution to minimize this risk, but is not liable for any damage you may sustain as a result of any virus in this e-mail.  The recipient should check this email and any attachments for the presence of viruses. THBS reserves the right to monitor and review the content of all messages sent to or from this e-mail address.********

**Comment by jagathjanani95** [comment] 2018-11-12 06:52
-----Original Message-----From: "jagathjanani_manoharan@thbs.com" <jagathjanani_manoharan@thbs.com>Sent: Monday, 12 November, 2018 12:21pmTo: "postmanlabs/postman-app-support" <reply@reply.github.com>Cc: "postmanlabs/postman-app-support" <postman-app-support@noreply.github.com>, "Mention" <mention@noreply.github.com>Subject: Re: [postmanlabs/postman-app-support] Not able to launch postman app. PFB error.To Reproduce Steps to reproduce the behavior: 1) Open App 2)See error Postman Version: 6.5.2 OS:Windows 8 (#5517)

Hi,
 
Please find the below screenshots.
 
Previous version used is 5.5.3 for which am getting the below error and also am not able to find any logs.
 
Error Screenshot for version 5.5.3 
 

 
Error Screenshot for version 6.5.2
 
 

Regards,Janani M
-----Original Message-----From: "Kamalakannan" <notifications@github.com>Sent: Monday, 12 November, 2018 12:12pmTo: "postmanlabs/postman-app-support" <postman-app-support@noreply.github.com>Cc: "jagathjanani95" <jagathjanani_manoharan@thbs.com>, "Mention" <mention@noreply.github.com>Subject: Re: [postmanlabs/postman-app-support] Not able to launch postman app. PFB error.To Reproduce Steps to reproduce the behavior: 1) Open App 2)See error Postman Version: 6.5.2 OS:Windows 8 (#5517)

Hi @jagathjanani95
Can you give us some details to help us debug this issue?
Can you send a screenshot of the error you are seeing? Can you also send the logs from View -> Developer -> View Logs in Explorer?
Also which version were you on before updating Postman?
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

******* DISCLAIMER: This email and any files transmitted with it are privileged and confidential information and intended solely for the use of the individual or entity to which they are addressed. If you are not the intended recipient, please notify the sender by e-mail and delete the original message. Further, you are not to copy, disclose, or distribute this e-mail or its contents to any other person and any such actions are unlawful. This e-mail may contain viruses. Torry Harris Business Solutions has taken every reasonable precaution to minimize this risk, but is not liable for any damage you may sustain as a result of any virus in this e-mail. The recipient should check this email and any attachments for the presence of viruses. THBS reserves the right to monitor and review the content of all messages sent to or from this e-mail address*************** DISCLAIMER: This email and any files transmitted with it are privileged and confidential information and intended solely for the use of the individual or entity to which they are addressed. If you are not the intended recipient, please notify the sender by e-mail and delete the original message. Further, you are not to copy, disclose, or distribute this e-mail or its contents to any other person and any such actions are unlawful. This e-mail may contain viruses. Torry Harris Business Solutions has taken every reasonable precaution to minimize this risk, but is not liable for any damage you may sustain as a result of any virus in this e-mail.  The recipient should check this email and any attachments for the presence of viruses. THBS reserves the right to monitor and review the content of all messages sent to or from this e-mail address********


******* DISCLAIMER: This email and any files transmitted with it are privileged and confidential information and intended solely for the use of the individual or entity to which they are addressed. If you are not the intended recipient, please notify the sender by e-mail and delete the original message. Further, you are not to copy, disclose, or distribute this e-mail or its contents to any other person and any such actions are unlawful. This e-mail may contain viruses. Torry Harris Business Solutions has taken every reasonable precaution to minimize this risk, but is not liable for any damage you may sustain as a result of any virus in this e-mail.  The recipient should check this email and any attachments for the presence of viruses. THBS reserves the right to monitor and review the content of all messages sent to or from this e-mail address.********

**Comment by SamvelRaja** [comment] 2018-11-12 07:32
Hi @jagathjanani95 

Could you zip and send the logs from `C:/Users/[USERNAME]/AppData/Roaming/Postman/logs` folder?

Also, the screenshots are not attached to your previous comment.

**Comment by jagathjanani95** [comment] 2018-11-12 08:04
![5 5 3](https://user-images.githubusercontent.com/44961505/48334042-540a5b00-e67f-11e8-990d-941acf0d2493.JPG)
![6 5 2](https://user-images.githubusercontent.com/44961505/48334050-5b316900-e67f-11e8-81a0-33b7d0919827.JPG)

**Comment by jagathjanani95** [comment] 2018-11-12 08:04
Attached the screenshots.

**Comment by jagathjanani95** [comment] 2018-11-12 08:44
Hi,
 
Attached the screenshots.
 
Regards,
Janani


-----Original Message-----

**Comment by SamvelRaja** [comment] 2018-11-12 08:49
@jagathjanani95 can you kindly zip and send the logs from C:/Users/[USERNAME]/AppData/Roaming/Postman/logs folder? to help[at]getpostman[dot]com
?

**Comment by jagathjanani95** [comment] 2018-11-12 08:51
PFA. [logs.zip](https://github.com/postmanlabs/postman-app-support/files/2571182/logs.zip)

**Comment by jagathjanani95** [comment] 2018-11-12 08:54
[main.log](https://github.com/postmanlabs/postman-app-support/files/2571204/main.log)
[renderer-shared.log](https://github.com/postmanlabs/postman-app-support/files/2571205/renderer-shared.log)
[renderer-shell.log](https://github.com/postmanlabs/postman-app-support/files/2571206/renderer-shell.log)

**Comment by DjGimli** [comment] 2018-11-12 12:41
**App Details**
Native App
Version 6.4.4
Operating System: High Sierra (10.13.3)

My app isn't crashing, but is failing to load. When i open the app it gets to the loading page in the screenshot below but then does not go any further.
![image](https://user-images.githubusercontent.com/19625866/48347777-30431700-e677-11e8-880b-fd41ad2404df.png)

Checking the log files in `/Postman/logs` the only error message i could see was in the renderer-requester logs:
> Dexie specification of currently installed DB version is missing

All logs attached for review
[logs.zip](https://github.com/postmanlabs/postman-app-support/files/2571904/logs.zip)

Im pretty sure it was fine until i installed the latest updates.

**Comment by Psypher9** [comment] 2018-11-15 23:01
I had this problem just today after updating to 6.5.2 yesterday. In my particular case I use a pinned Start menu shortcut so I looked at the Properties for that shortcut. It was still pointing to the `6.4.2` version at:
`<the_rest_of_the_path>\Postman\app-6.4.2\Postman.exe`

So I updated the shortcut path to:
`<the_rest_of_the_path>\Postman\app-6.5.2\Postman.exe`

This made it so that I could launch Postman correctly on the first try.

**Comment by numaanashraf** [comment] 2019-04-05 09:28
Duplicate of #5591

**Closed as completed by numaanashraf** 2019-04-05 09:28 UTC
Labels: bug, updates
