### ISSUE TITLE
[UBUNTU] Postman requires system restart to start

### ISSUE THREAD

**Issue by rami-dabain** [a85/POSTMan-Chrome-Extension#8232] opened 2020-03-24 10:03 UTC
**Describe the bug**
When closing and opening postman multiple times on ubuntu (5.3.0-40-generic), at some point, postman will not start

**To Reproduce**
1. Open postman.
2. Update a call, without saving it, nor syncing it
3. Close postman
4. repeat with some interval (5-10 minutes) until postman will not start

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
can't send a screenshot, no window is even launched

**App information (please complete the following information):**
 - App Type :Native App
 - Postman Version (not sure)
 - OS: Ubuntu 19.10

**Additional context**
---

**Comment by kamalaknn** [comment] 2020-03-24 17:21
@rami-dabain Can you forward the logs from `View -> Developer -> View logs in Explorer` to `help@postman.com` so we can take a closer look at this issue?

**Comment by harryi3t** [comment] 2020-03-25 05:29
@rami-dabain It looks like while closing the app sometimes the processes are not cleaned up properly.
We are tracking this issue here https://github.com/postmanlabs/postman-app-support/issues/8205

We are trying to find the root cause of this. Until this issue is fixed you can use the workaround (mentioned in the original ticket too) to kill all the processes by running `killall Postman`

**Closed as completed by harryi3t** 2020-03-25 05:29 UTC
Labels: bug

**Comment by ranu1993** [comment] 2023-09-04 07:48
post
![kai-2023-09-04-13-17-34](https://github.com/postmanlabs/postman-app-support/assets/84901738/ba95ee4f-dadc-4435-a1a1-aa5a273823bc)

Unable to open can anyone help me?

I tried all possible steps
