### ISSUE TITLE
The 'this temporary header' tooltip obstructs the actual value

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5191] opened 2018-09-17 05:40 UTC
**Describe the bug**
When sending a request with an auth helper, and auto-generated Authorization header is added. While hovering over the header value, the 'This header has been generated' tooltip blocks part of the value, and there's no way to read the entire string.

**To Reproduce**
1. Send a request with the OAuth1 helper enabled
2. Go to the headers tab
3. Hover over the auto-generated header's value

**Expected behavior**
The tooltip should:
1. open away from the cursor
2. vanish after some time, OR
3. only open when you hover over the header name, not the value.

**Screenshots**
<img width="725" alt="screen shot 2018-09-17 at 11 07 13" src="https://user-images.githubusercontent.com/681190/45607463-4d3dde00-ba6a-11e8-8c72-b617fb50fe05.png">

**App information (please complete the following information):**
Postman for Mac
Version 6.3.1-beta180908-2332
OS X 17.3.0 / x64

**Comment by numaanashraf** [comment] 2019-01-09 14:23
Duplicate of #4894

**Closed as completed by numaanashraf** 2019-01-09 14:23 UTC
Labels: duplicate
