### ISSUE TITLE
add cookie button doesn't work win 10

### ISSUE THREAD

**Issue by playwolf719** [a85/POSTMan-Chrome-Extension#8129] opened 2020-03-03 04:51 UTC
**Describe the bug**
add cookie button doesn't work

**To Reproduce**
1. Click on 'cookies'
2. Add  domain name
3.  click "add cookie", no textarea show up

**Expected behavior**
add cookie textarea show up

**App information (please complete the following information):**
 - Postman v7.19.1
 - win 10 64bit

**Comment by codenirvana** [comment] 2020-03-03 04:58
@playwolf719 Can you share the screen recording/gif for this issue?
Not able to reproduce this on Windows 10.

**Comment by playwolf719** [comment] 2020-03-03 05:55
![image](https://user-images.githubusercontent.com/6240382/75746949-af6dca00-5d56-11ea-85bb-c677b8896952.png)

**Comment by playwolf719** [comment] 2020-03-03 05:57
![image](https://im.ezgif.com/tmp/ezgif-1-38bd6d471de0.gif)
@codenirvana

**Comment by codenirvana** [comment] 2020-03-03 06:40
@playwolf719 That's because of the invalid hostname as the protocol `https://` is included.
This is a known issue and is being tracked here: #7603

For now, you can just drop the protocol and add a valid domain name (`google.com` in this case) to fix this issue.

Closing as duplicate of #7603

**Closed as completed by codenirvana** 2020-03-03 06:40 UTC
Labels: cookies, duplicate, product/runtime

**Comment by playwolf719** [comment] 2020-03-03 08:17
It works now. Thx a lot!
