### ISSUE TITLE
Simultaneous headers content-length and transfer-encoding leads to ParseError

### ISSUE THREAD

**Issue by sbiemont** [a85/POSTMan-Chrome-Extension#7466] opened 2019-10-11 15:33 UTC
**bug**
When both headers `content-length` and `transfer-encoding` are present, postman raises a `ParseError` and prints the message "Could not get any response".

**example**
`transfer-encoding: chunked`
`content-length: 250`

It's not coherent to have these 2 headers in a response (but they can be present).
If so, the `content-length` could be used first, without checking the `transfer-encoding`.
Or postman could raise a specific error. (?)

**Comment by vvs11** [comment] 2019-10-14 07:50
Hi @sbiemont, Thanks for writing in!
I tried sending a POST request with both the headers and its working for me. 
Could you provide us with exact steps and screenshots of what you're trying to do?

**Comment by sbiemont** [comment] 2019-10-14 12:26
Hi @vvs11 !

More info:
* I'm using a bearer token, in a GET request (it responses a 404 but the result is the same with a 200, I just have a lot more headers in the 200).
* The root and the token are in variables.
* Version: `Postman-linux-x64-7.9.0` on Ubuntu

All present headers in the response:
* `transfer-encoding: chunked`
* `Content-Type: application/json; charset=utf-8`
* `Content-Length: 78`
* `ETag: W/"4e-7EW8chmGrXO/dCnsUFYeNLttAp8"`

I changed the settings as suggested in the postman error page (see screenshot) without any effect.

What postman prints ('Params' tab contains data but nothing is checked, and note that the message `There was an error connecting to .` is incomplete (the address is missing since postman 7.8.0)):
![postman](https://user-images.githubusercontent.com/30431242/66750377-968a7800-ee8c-11e9-81e0-de382239f816.png)

What RESTer prints (firefox extension):
![rester](https://user-images.githubusercontent.com/30431242/66750383-99856880-ee8c-11e9-95ee-09302b71bc46.png)

**Comment by verhyppo** [comment] 2020-09-09 12:00
Morning @codenirvana, 
There are no updates on this issue?

**Comment by Mechanicalkeyboard** [comment] 2020-09-15 17:46
@verhyppo @sbiemont  After reproducing this, I am seeing an error returned that is more descriptive. 

Closing this issue. If the behaviour seen in the most recent version is not up to your expectations, please re-open. 
![Screen Shot 2020-09-15 at 2 44 35 PM](https://user-images.githubusercontent.com/9625128/93245824-44b83500-f762-11ea-9550-6bb6090d51d6.png)

**Closed as completed by Mechanicalkeyboard** 2020-09-15 17:46 UTC
Labels: bug, product/runtime

**Comment by MesaSantiago96** [comment] 2021-02-03 14:55
> @verhyppo @sbiemont After reproducing this, I am seeing an error returned that is more descriptive.
> 
> Closing this issue. If the behaviour seen in the most recent version is not up to your expectations, please re-open.
> ![Screen Shot 2020-09-15 at 2 44 35 PM](https://user-images.githubusercontent.com/9625128/93245824-44b83500-f762-11ea-9550-6bb6090d51d6.png)

I revive this issue because I can't find a solution to my problem.
That error you posted appears directly to me: Parse Error: The response headers can’t include “Content-Length” with chunked encoding.
And I understood that the description of the problem is very explanatory, but I can't understand what that means.
So my question is, what should I correct so that this error stops appearing, or at least, what should I look at to avoid it.

**Comment by sbiemont** [comment] 2021-05-24 08:47
Hi @MesaSantiago96 

The new release of postman is very coherent and the response is now clear : both headers `transfer-encoding` and `content-length`, by definition, cannot be used at the same time.

The one and only solution is to have a consistent set of header with `transfer-encoding` **or** `content-length` (but not both).

An example of an answer on the same problem : [chunked-encoding-and-content-length-header](https://stackoverflow.com/questions/3304126/chunked-encoding-and-content-length-header)
