### ISSUE TITLE
Enhancement: Change Environment on Tab Change

### ISSUE THREAD

**Issue by baldemarch** [a85/POSTMan-Chrome-Extension#2183] opened 2016-07-20 15:57 UTC
When working with different API Endpoints, you may need to use different Environments for each endpoint.

It would be very useful to change to the environment on which the tab was saved to. That way you can optimize the use of different collections, tests etc.

Thanks!

**Comment by nathan-alden-sr** [comment] 2016-07-21 16:08
It would be nice to have an Environment "override" per endpoint. If it's not specified, then the global setting would be used. Good suggestion!

**Comment by a85** [comment] 2017-12-23 19:08
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1256

**Closed as completed by a85** 2017-12-23 19:08 UTC
Labels: Environments
