### ISSUE TITLE
Collection Runner when opened from collection does not default the Collection folder.

### ISSUE THREAD

**Issue by built-by-vjallada** [a85/POSTMan-Chrome-Extension#4028] opened 2018-01-05 08:24 UTC
## App Details:
Postman for Windows
Version 5.5.0
win32 6.1.7600 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently. This feature was working fine during the earlier postman versions.

Steps to Reproduce:
1. Open the Postman application.
2. On the Collection Folder Click on ">" and then click on [Run]
3. Check that the Runner is opened successfully.
4. Check that the "Choose collection or folder" is empty.

Expected behavior: "Choose collection or folder" is populated with the Collection Folder selected in Step 2.

**Comment by numaanashraf** [comment] 2018-01-05 12:42
@sekhar-selenium Thanks for writing in. We are looking into this.

**Comment by polydoreplasden** [comment] 2018-01-09 09:50
Hi, this looks like the same issue previously reported under https://github.com/postmanlabs/postman-app-support/issues/3916

**Comment by built-by-vjallada** [comment] 2018-01-11 05:02
There are couple of other observations made:

1. When ever the collections in the application are less such as 4 or 5 collections, I see that on clicking on RUN button for the collection, it takes me to the runner page where the Collection as well as the Environment are pre-populated.

2. When ever the collections in the application are more than 10 (on my application I got 23 collection folders), when I click on the RUN button for the collection, the application takes me to the Runner page, but with out the collection or the environment populated.

For the above observation, I'm using the same application version (v5.5.0) and on Windows Platform.

This might be the reason where some people are not able to reproduce this issue even when they are using the same version of application.

Hope this might help to debug further.

Thanks, 
Vijay.

**Comment by harryi3t** [comment] 2018-02-17 09:56
Duplicate of issue https://github.com/postmanlabs/postman-app-support/issues/3887
Closing this in favour of the original issue
Also, this has been fixed and will be available in the next release 🎉

**Closed as completed by harryi3t** 2018-02-17 09:56 UTC
Labels: platform/windows
