### ISSUE TITLE
utf-8 is not supported

### ISSUE THREAD

**Issue by mhamri** [a85/POSTMan-Chrome-Extension#3688] opened 2017-10-29 16:31 UTC
## App Details:
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64
```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: yes, I just setuped the stand alone postman application and encounter this issue, on chrome it works fine
 2. Expected behavior: i am sending this "http://localhost:50610/س/" and at server side i'm receiving "3" instead of "س"
or "سلام" is converted to "3D'E"
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Not applicable, i'm using stand alone 
 4. Screenshots (if applicable)
Bellow picture is for `http://localhost:50610/سلام`
![image](https://user-images.githubusercontent.com/8991783/32145829-9c4780be-bd09-11e7-91c4-da0e9dbaa77f.png)

**Comment by prashantagarwal** [comment] 2017-11-02 15:54
@mhamri Can you update to the latest Postman app version and see if it is still happening for you.
Also can you provide me with a screenshot of Postman Console after sending this request.

**Comment by mhamri** [comment] 2017-11-08 15:00
when i check for the update it say that i have the latest version
![image](https://user-images.githubusercontent.com/8991783/32555723-81761b66-c4d8-11e7-8ea4-98072a0ab56c.png)

but the problem still is there

**Comment by DerAlex23** [comment] 2018-01-29 10:44
I run into the same issue with german umlauts.
OS: Windows 10 Pro (64 Bit)
Postman: 5.5.2 (up to date)

I try to access a REST-API. The url looks like http://localhost/users/XXXXXX (where X is the username).
Sending in postman a request like http://localhost/users/fööbär results encoding error and returns something like this as username: f??b?r (where ? are non printable invalid chars).

**Comment by Ponant** [comment] 2019-04-11 08:35
http://faß.de will lead postman to `Critical error: no domain selected! ` The Unicode right click feature does as bad job because it should punycode instead.

**Comment by codenirvana** [comment] 2019-05-13 10:01
Duplicate of #3778

**Closed as completed by codenirvana** 2019-05-13 10:01 UTC
Labels: bug, encode-decode, product/runtime

**Comment by shamasis** [comment] 2019-06-17 15:45
Noting this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/4555
