### ISSUE TITLE
New Postman not working on Windows

### ISSUE THREAD

**Issue by eduardoHoefel** [a85/POSTMan-Chrome-Extension#5663] opened 2018-12-18 15:14 UTC
**Describe the bug**
Just opened Postman today and found out that there is a new native app. Installed it, sent a local GET request and received:

![image](https://user-images.githubusercontent.com/8729915/50163995-bf6fca00-02c8-11e9-92e0-cbe816856ef2.png)

Tried the same request using Google Chrome and got the correct response.
Tried the same request on the old app and got the correct response.
Tried it again using the new app on Linux and got the correct response.

**App information:**
 - Native App
 - Postman 6.6.1
 - OS: Windows 7

**Comment by numaanashraf** [comment] 2018-12-19 15:32
@eduardoHoefel That's strange. Could you share a publicly accessible endpoint we can use to replicate this?

**Comment by eduardoHoefel** [comment] 2018-12-19 16:03
I can't because the issue was just tested at my office and I cannot share an endpoint here.

I can inform you that the api was hosted at localhost, port 3000, and that I am behind a proxy server, although I don't think that is as issue since the server is local

**Comment by shamasis** [comment] 2019-05-13 11:02
It has been quite a while since this issue was reported. Since then a number of improvements were done to Postman Proxy settings. Can you try them and check? Try using "System Proxy" instead of setting proxy in Postman App.

Otherwise: this could be a case where Postman is not respecting proxy exclusion for localhost

**Comment by eduardoHoefel** [comment] 2019-05-15 18:15
I tried again and the result was the same. The return is different when requested using chrome or the old postman extension.

My system proxy settings is set to use an automatic configuration script. I could not find a similar option in postman settings, nor to set exceptions to the global proxy

**Comment by codenirvana** [comment] 2019-08-14 07:38
@eduardoHoefel Can you share a scaled-down collection which we can use to reproduce this issue?

More information about the request behavior will be helpful for us to debug this issue.

**Comment by saswatds** [comment] 2019-09-17 13:22
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by saswatds** 2019-09-17 13:22 UTC
Labels: bug, Proxy, request-sending, blocked/need-info, product/runtime
