### ISSUE TITLE
Experiencing an issue with Variables set in Pre-test scripts

### ISSUE THREAD

**Issue by AshraafElkholy** [a85/POSTMan-Chrome-Extension#7696] opened 2019-11-25 23:27 UTC
Updated to Release 7.12.0 
Currently experiencing an issue with Variables set in Pre-test scripts
values not reflecting before the request sent, it gets updated after request is sent, hence resulting in setting it in the next request in collection

I found old bug explains what i am experiencing
https://github.com/postmanlabs/postman-app-support/issues/6144

**Comment by radupopabac** [comment] 2020-03-02 22:08
+1

**Comment by orShapira** [comment] 2020-03-04 16:36
+1

**Comment by codenirvana** [comment] 2020-03-04 16:43
@AshraafElkholy @radupopabac @orShapira Can you share a scaled-down collection (or steps) which we can use to reproduce this issue?

**Comment by orShapira** [comment] 2020-03-08 08:11
look like it something with the await vs. callback working differently
calling pm.enviroment.set working fine inside a callback but nothing happen after await

`const main = async () => {
  pm.environment.set("posts", []); // <=== work fine
  await new Promise((resolve, reject) => { 
    pm.sendRequest({ url: `${pm.environment.get('api-prod')}/configurations/`, method: 'GET'}, (err, res) => { 
      pm.environment.set("configurations", res.json()); // <=== work fine
      err 
        ? reject() 
        : resolve();
    });
  }); 
  pm.environment.set("projectId", "123"); // <=== not working
}`

**Comment by orShapira** [comment] 2020-03-08 08:16
look like it something with the await vs. callback working differently
calling pm.enviroment.set working fine inside a callback but nothing happens after await


```
const main = async () => {
  pm.environment.set("posts", []); // <<<<======= working fine
  await new Promise((resolve, reject) => { 
    pm.sendRequest({ url: pm.environment.get('api-prod') + "/configurations/", method: 'GET'}, (err, res) => { 
      pm.environment.set("configurations", res.json()); // <<<<======= working fine
      err 
        ? reject() 
        : resolve();
    });
  }); 
  pm.environment.set("projectId", "123"); // <<<<======= not working
}
```

**Comment by codenirvana** [comment] 2020-03-19 21:02
@orShapira Postman scripts don't support promises or async/await well and we are tracking this feature request here: https://github.com/postmanlabs/postman-app-support/issues/4131

However, as a workaround, you can just add 1-2 sec timeout (`setTimeout(()=>{}, 2000)`) at the end of the script to force the postman-sandbox to wait for the script execution to complete.

Closing as duplicate of #4131

**Closed as completed by codenirvana** 2020-03-19 21:02 UTC
Labels: bug, blocked/need-info, product/runtime
