### ISSUE TITLE
cannot copy the console of the previous and next page

### ISSUE THREAD

**Issue by Melcome7** [a85/POSTMan-Chrome-Extension#9225] opened 2020-11-03 01:37 UTC
for details, I made an attachment of the bug, that I can only copy the console content of the current view, cannot copy the content of previous and next page, fix the bug?
![image](https://user-images.githubusercontent.com/11468955/97936935-1fd25c80-1db8-11eb-9d35-9ddcb6bc5a7b.png)

**Comment by DannyDainton** [comment] 2020-11-03 06:40
Closing as this is a duplicate of #8785

**Comment by DannyDainton** [comment] 2020-11-03 06:41
Closing as this is a duplicate of #8757

**Closed as completed** 2020-11-03 06:41 UTC
Labels: duplicate
