### ISSUE TITLE
Proxy system setting including exceptions

### ISSUE THREAD

**Issue by naclma** [a85/POSTMan-Chrome-Extension#7279] opened 2019-09-06 12:26 UTC
Hello,
I am still unable to use postman because I am behind a proxy and postman doesn't use the system proxy exceptions and I can't set exception in the setting either.

It is working within the chrome app which is deprecated since a long time, because the app is using chrome's proxy setting including the exceptions.

![postman01](https://user-images.githubusercontent.com/49639244/64428067-10bc2580-d0b3-11e9-91cb-2a714bfb9c34.png)

**Expected behavior**
The native app is using the systems proxy exceptions just as the postman chrome app does.

**Comment by shamasis** [comment] 2019-09-06 16:59
Hey... we intend to add this. But this is not high up on our roadmap yet.

**Comment by naclma** [comment] 2019-09-06 20:21
Hey,
what can I do to put it high up on your roadmap :p

**Comment by codenirvana** [comment] 2019-09-19 00:19
@naclma We are currently working on adding support for this feature which will allow you to bypass proxy settings for the given domains.

Please follow #6380 for more updates and its availability in our canary or production channel.

Closing as duplicate of #6380

**Closed as completed by codenirvana** 2019-09-19 00:19 UTC
Labels: feature, Proxy, product/runtime
