### ISSUE TITLE
Adding a cookie adds a '.' (period) before the domain property

### ISSUE THREAD

**Issue by marnixhoh** [a85/POSTMan-Chrome-Extension#8270] opened 2020-04-01 13:24 UTC
Adding a cookie manually causes a '.' (period) to be added before the domain property of the cookie.

E.g:
    Cookie=value; Path=/; Domain=api.localhost; Expires=Thu, 01 Apr 2021 13:18:08 GMT;
becomes:
    Cookie=value; Path=/; Domain=.api.localhost; Expires=Thu, 01 Apr 2021 13:18:08 GMT;

When a cookie is set through a received 'set-cookie' header, the domain property is set correctly without the period. However, when the cookie is simply opened in the editor and then 'Saved', the '.' period is inserted.

As a result, when a response includes a "set-cookie" header with a time in the past to remove the cookie above, it won't work, because the domain properties do not match.

- Postman version: Version 7.21.1 (7.21.1)
- OS: MacOS Catalina (10.15.3)

**Comment by coditva** [comment] 2020-04-03 07:59
Duplicate of #7901.

The leading dot signifies that the cookie will be used for subdomains as well.

Having `Domain=api.localhost` means that the cookie name will be used for every subdomain of `api.localhost`.
Whereas, with `Cookie=value; Path=/;` makes the cookie HostOnly and will only be used for the requesting hostname.

Remove the domain part from the string and the cookie becomes `hostOnly` (not sent for subdomains) and the leading dot is also gets removed.

Hope that helps! :)

**Closed as completed by coditva** 2020-04-03 07:59 UTC
Labels: cookies, product/runtime
