### ISSUE TITLE
Postman to code headers case

### ISSUE THREAD

**Issue by 5yx** [a85/POSTMan-Chrome-Extension#2681] opened 2017-02-07 08:59 UTC
Version/App Information:
 1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome 55.0.2883.87
 3. OS details: win / x86-64
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: seems like always
 6. Expected behavior: right headers

when converting Postman requests to code, it sets http headers to _lowercase_ style, which makes the request fail sometimes when preformed from code..

HTTP RFC 7230 states: "Each header field consists of a **case-insensitive** field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace."

best regards

**Comment by efenderbosch** [comment] 2017-02-16 21:21
Also experiencing this using:

Postman for Chrome
Version 4.10.2
OS X / x86-64
Chrome 56.0.2924.87

**Comment by tsmgeek** [comment] 2017-03-29 14:52
Same on 4.10.3.
Does not happen if you pass params though URL.

**Comment by Blue-Dog-Archolite** [comment] 2017-06-28 21:50
![postman_044](https://user-images.githubusercontent.com/53378/27662067-9a7a8228-5c19-11e7-9883-2c421d9efa6c.png)
![selection_045](https://user-images.githubusercontent.com/53378/27662076-9e2074c8-5c19-11e7-9909-430f81077092.png)

Same on Linux `Version 5.0.1`

**Comment by wysow** [comment] 2017-08-29 10:41
Experiencing exactly this on an API which firewall is only accepting headers with exact syntax like `Authorization` and not `authorization`, Postman should not convert headers keys to lowercase in my opinion...

**Comment by sdnts** [comment] 2017-08-29 10:44
Can you guys try this on the [native apps](https://getpostman.com/apps) and check if this is an issue there as well?

**Comment by wysow** [comment] 2017-08-29 11:24
@madebysid I'm already using Mac native app version 5.1.3 so yes this issue is also there.

**Comment by sdnts** [comment] 2017-08-29 12:04
@wysow Looks like this is only the case for the generated code, and not actual requests sent through the app. Regardless, this is still a bug and I'm marking it as such.

**Comment by wysow** [comment] 2017-08-29 12:11
@madebysid How do you explain that same request made by Postman app and by curl (after rewriting the headers in the right way) is not getting the same response then?

**Comment by wysow** [comment] 2017-08-29 12:52
@madebysid nevermind... , I found the answer on my side, the firewall needed some "real life" values for some specific headers, all working now...

**Comment by Blue-Dog-Archolite** [comment] 2017-08-29 17:58
@madebysid I am using the Native app.

**Comment by rianwouters** [comment] 2017-09-14 08:42
Same problem here.
Quite surprised that a bug as impactful as this one persists so long in a tool like this....
I will try to find a fix.

**Comment by wysow** [comment] 2017-09-15 06:32
@rianwouters requests sent through the app are using headers as you set them so all working, only exported code is affected by this, what is exactly the problem your facing?

**Comment by rianwouters** [comment] 2017-09-15 13:11
@wysow I deleted my comment. We found out that the problem is not in postman. Sorry for bothering you, we just concluded too fast the we were facing the issue described above.

**Comment by wysow** [comment] 2017-09-15 14:56
@rianwouters sure no problem! Have fun with Postman!

**Closed as completed** 2017-12-23 02:04 UTC

**Comment by efenderbosch** [comment] 2017-12-23 21:36
Was this ever fixed?

**Comment by a85** [comment] 2017-12-24 22:22
Yep. Fixed in the latest release.

**Comment by dressjo** [comment] 2018-01-15 14:10
Tested with latest  Postman v5.6.0-canary01 build. Postman still converts header keys to lowercase.

**Comment by efenderbosch** [comment] 2018-01-16 14:55
Works correctly for me w/ 5.5.0. Here's a captured request w/ mixed case header.

https://hookbin.com/bin/Ezgzd5Mm/6b73fdb1

**Comment by dressjo** [comment] 2018-01-19 09:34
@efenderbosch, maybe i have misunderstood. But I am using Postman v5.6.0-canary01 on windows. I have attached screenshot of the request header definition in Postman and the actual sent request from 
postman log. As you can see "AuthToken" is converted to lowercase "authtoken".

![postman_request_header](https://user-images.githubusercontent.com/961610/35144064-b5a9d112-fd03-11e7-8562-75649b4b23f2.PNG)

Actual request sent from postman console

`content-type:"application/json"
authtoken:"test"
cache-control:"no-cache"
postman-token:"3191861c-1268-4b4a-bd68-d3c7f7af811f"
user-agent:"PostmanRuntime/7.1.1"
accept:"*/*"
host:"localhost:8080"
accept-encoding:"gzip, deflate"
content-length:142`

**Comment by efenderbosch** [comment] 2018-01-19 15:52
Must be a regression from 5.5 to 5.6 because I have a mixed case header name "HEADER-header" that worked correctly.

**Comment by vinogradoff** [comment] 2018-01-26 16:15
doesn't work for me in 5.5.2

just put like Content-Type Header and try

```
console.log(request.headers["Content-Type"]); // undefined
console.log(request.headers["content-type"]); // correct
```

it is actually another bug, just linking here:
#4113
