### ISSUE TITLE
Feature Request: Secure environment variables

### ISSUE THREAD

**Issue by gesslinger** [a85/POSTMan-Chrome-Extension#4777] opened 2018-07-04 15:39 UTC
Another cool feature for postman's environment variables: 
- add a checkbox for "secure" environment variables (e.g. for credentials) 
- encrypt these values in the internal storage 
- these variables should be only marked with ****** 
- when exporting an environment, these variables should be also hidden

**Comment by jkewley** [comment] 2018-07-04 19:51
Dupe of #824

**Closed as completed** 2018-07-05 05:56 UTC
Labels: feature
