### ISSUE TITLE
Collection & Request order is broken by 6.0.9

### ISSUE THREAD

**Issue by glenpike** [a85/POSTMan-Chrome-Extension#4321] opened 2018-03-12 14:01 UTC
## App Details:
```
Postman for Mac
Version 6.0.9
OS X 15.6.0 / x64
```

## Issue Report:
Exporting a collection doesn't seem to preserve folder or request order.
 1. Issue with 6.0.9
 2. Expected behaviour:  Exporting the collection in the order I see it in Postman.

Upgraded Postman
Exported collection for running Newman tests.
First time, I discovered the folders were completely out of order.
(Originally I named all my folders "01. Foo", "02. Bar", "03. Baz", etc.)
I trashed 6.0.9, installed 6.0.8 and the order of my folders then appeared screwed in Postman.
I fixed the order of the folders, but the order of the requests inside these were completely screwed - no apparent order, e.g. alpha / numeric, just chaos - this reflects the exported JSON.

Rolled back to 6.0.8 again and it's the same in Postman.

Unfortunately, this means the sync has now happened and my files are completely screwed.

I've only lost a morning's work from the last commit, but this is a _serious_ issue which needs addressing urgently I feel.

**Comment by ghost** [comment] 2018-03-14 07:20
I have experienced the same bug

Postman for Windows
Version 6.0.9
win32 6.1.7601 / x64

The issue does not affect all my collections

The issue first occurs when you use the collection runner. If you export, then the incorrect order seen in the collection runner appears in the export

The issue is critical. It destroys the functionality of collections in which order is significant

**Comment by ghost** [comment] 2018-03-14 07:23
It further occurs to me that the destruction of the order may occur whenthe collection is updated, and this would explain why collections which I have not edited can be exported with the order preserved

**Comment by ghost** [comment] 2018-03-24 03:53
This is still present in 6.0.10

I have now seen the behaviour occur in the sync process as follows.

1. I opened Postman 6.0.10 on laptop A whilst connected to my Postman account
2. I hand sorted the collection according to alphabetic order of the request names
3. I opened Postman 6.0.9 on laptop B whilst connected to my Postman account
4. Postman performed an upgrade to 6.0.10
5. I noted that the collection order was lost

I have exports at both points

Other possibly contributing factors:

* On laptop A, I exported and reimported the collection to store in a Git repository

**Comment by ghost** [comment] 2018-03-28 07:24
**Results of further experimentation**

Given two instances of Postman one on laptop A and one on laptop B, I was able to unscramble a collection by signing out and then signing back in again as follows.

1. Observe that collection is scrambled on laptop A and laptop B
2. Sign out on laptop B
3. Sign back in on laptop B
4. Observe that collection is no longer scrambled on laptop B
5. Force a sync on laptop A
6. Observe no change in the order of the collection
7. Sign out on laptop A
8. Sign back in on laptop A
9. Observe that collection is no longer scrambled on laptop B

**Analysis**

This *suggests* the following.

*  The problem is with the representation in the running app: although the request order was scrambled on two Postman instances for 4 days, it was still possible to retrieve the correct order from the copy on the server
* The incorrect ordering is suffered by the
  * Collection pane displaying the collection,
  * Collection runner
  * Collection exporter

However, it is unclear whether the incorrect ordering is possibly seen by the sync algorithm and propagated between instances, or whether the two instances simply replicated the same fault

**Comment by sdnts** [comment] 2018-04-19 12:03
Is this still happening? We've made some changes to make sure this doesn't. Please let me know if this is resolved!

**Comment by fschai89** [comment] 2018-04-23 05:05
@madebysid yes still happen, everytime I sync, the order of the requests inside collection get mess up. I need to reorder them manual, but no use, everytime sync between 2 pc get mess up anyway. Is there a function that sort requests?

**Comment by glenpike** [comment] 2018-04-24 17:18
@madebysid: yes this is happening for me too.  When my Linux version (6.0.10) syncs, it often breaks the collection order and I have to delete and re-import.

**Comment by brianbellon** [comment] 2018-05-31 16:31
I am seeing this issue as of yesterday as well now.  Seemed to be related to a Windows Postman update I got, but then after reading the above comment, it's probably something else.  I tried the logout and login suggestion above, and afterwards my Folders that were out of order seemed to line up correctly again, but all my sub-calls under the folders were still in the wrong order - so my tests are still messed up, just deeper down.  My issue started doing the same thing I've done multiple times: rather than working on an existing collection that is current working correctly, I usually highlight the collection and do a Ctrl+D to duplicate it and then rename it to show that I'm working on it.  I don't remember if I was prompted to update Postman before or after this Duplicate process.  But immediately afterwards, in my new "test update" collection, I couldn't drag items under a folder to reorder calls that I needed.  They would just bounce back down to their original location.  After trying for 5+ minutes, I left for the day.  The next morning items appeared to be allowed to move around again as they always have in the past.  It wasn't until editing items for a few hours that I noticed that the order of my calls and folders was all messed up.  So they were probably that way from right after my duplicate - since some of the folders and their contents I'd never touched during my update.  I think the duplicate function may have been the culprit because I still have the original collection my list and all the folders and calls are in the correct order.

**Comment by brianbellon** [comment] 2018-05-31 16:42
One more update - I did the logout and login just before leaving yesterday with the result I talked about - folders fixed but the calls under them still messed up.  I didn't logout again overnight - but now that I'm checking them this morning, everything appears to be in the correct order again except on folder with 2 calls that I just manually changed.  It's like the sync may have fixed things? Although very slowly...

**Comment by connorsadlervelo** [comment] 2018-06-05 20:33
Just happened to me on Mac OS
Collection ended up in a random order so I have to dump my work and revert to the version from git
Is there a fix/workaround for this please?

**Comment by fschai89** [comment] 2018-06-06 05:02
Can we have sort request function? Cannot cope with this problem, extremely slowing down our work. Thanks.

**Comment by SamvelRaja** [comment] 2018-06-29 12:22
@fschai89  @glenpike @syntegritysolutions @brianbellon  Requesting you guys to send a mail to help[at]getpostman[dot]com with the screenshot of the re-ordered collection from your registered email id. 

This will help us is getting closer look at the issue.

Also, we recommend people facing this issue to contact us directly through help[at]getpostman[dot]com to help faster.

**Comment by brianbellon** [comment] 2018-06-29 13:18
I'll have to apologize for not getting screen shots when I saw the issue before.  If it ever happens again, I'll be sure to do so.  Thanks for looking into this.

**Comment by glenpike** [comment] 2018-08-09 15:57
Hi, I am still getting this when I swap between Mac OS at work and Ubuntu at home.  I will try again with latest versions, but was happening with recent ones the other day.

**Comment by a85** [comment] 2018-12-07 05:21
We have made several improvements to Sync since this issue was reported. Closing this for now.

**Closed as completed by a85** 2018-12-07 05:21 UTC
Labels: bug, sync

**Comment by olgaivanovaplutora** [comment] 2019-02-04 05:09
I experience the same issue now. 
**Preconditions:**
Having two POSTMAN instances at work and at home logged in under the same work account. 
Both instances have never been online together, only one after another. 
Created a collection with groups of requests on one instance (create new requests and change order).
Modified a collection on another instance (create new requests and change order).
**Steps:**
step1. On one of instances, change the order for any of requests in your collection by drag and drop.
step2. Using Runner, execute your collection.
**Actual result:**
step1. Order of all requests gets messed up after this action.
step2. Requests are being run in a messed up order, but not the one visible in POSTMAN collection.
**Expected result:**
step1. Order should stay the same.
step2. Runner should execute requests in the same order as shown in POSTMAN collection.
**Note:**
Another use case is when you log in to POSTMAN from PC 2 , make changes to the same collection, and save them. Next time you open it from the PC 1 you will get all requests in messed up order.
**Workaround:**
Save your collections and make a backup every time before you want to work with them from PC 2. Then come back to PC 1, delete all collections from your POSTMAN and use the backup ones.

**Comment by ShohruxYusupov** [comment] 2019-04-17 13:58
@a85 the issue is still actual. I've two PCs. MacOS(work) and Windows(home). Every time when i open postman on homePC after workPC(or on workPC after homePC), order is messed up.

**Comment by xaviergm** [comment] 2020-11-12 14:16
I am also suffering from this right now. Sometimes, for no apparent reason, the order of the requests in the collection (104 requests at the moment) gets scrambled.

- Postman for Windows
- Version 7.35.0
- win32 10.0.18363 / x64
