### ISSUE TITLE
"KEY_VALUES_MISMATCH" error when using .pfx certificate

### ISSUE THREAD

**Issue by TheNestea** [a85/POSTMan-Chrome-Extension#6878] opened 2019-07-09 09:14 UTC
**AR**: Can't send requests to https with .pfx certificate

**To Reproduce**
1. Go to Settings > Certificate
2. Click on ”Add Certificate”
3. Fill “Host” field with host, like “mmm-nn.ru” and port with ”8080”
4. Click “Choose File” in PFX file field and select .pfx file
5. Enter “Passphrase” of .pfx certificate
6. Click “Add” button
7. Send any request to this host

“Could not get any response” message is displayed.
Postman Console — Error: KEY_VALUES_MISMATCH

**Expected behavior**
Successful request with some readable response

**Screenshots**
![1](https://user-images.githubusercontent.com/28944777/60875648-5a22fc80-a24b-11e9-9490-2474f3c9e308.png)
![2](https://user-images.githubusercontent.com/28944777/60875649-5abb9300-a24b-11e9-90b1-586c001f4d72.png)
![3](https://user-images.githubusercontent.com/28944777/60875650-5abb9300-a24b-11e9-960e-bd7e5e6c0056.png)

**App information (please complete the following information):**
 - Native App
 - Postman app Version 7.3.0 (7.3.0)
 - OS: macOS Mojave 10.14.5

**Additional context**
Last week using this certificate was successful, maybe I used postman 7.2.0. 
This cert is correct, I use it in mobile android app to connect to host.

**Comment by FunksMaName** [comment] 2019-07-09 16:54
I can confirm that I am getting the the same error, on windows client v7.3.2, which is not listed on your website release notes. I have a valid PFX file setup as a client certificate for mutual authentication. This worked 2 hours ago until the upgrade.

**Comment by codenirvana** [comment] 2019-07-09 19:02
@TheNestea @FunksMaName Thanks for reporting this issue.

This looks like a side effect of OpenSSL upgrade from `1.0.2l` to `1.1.0` during the Electron upgrade in v7.3.

Until we verify this can you please check if one of the following fixes this issue:
1. Re-configure the client certificate configuration (remove existing and add again)
2. Remove the passphrase from pfx and try again

**Steps to remove passphrase:**
1. Export to a temporary certificate
```console
$ openssl pkcs12 -in your-protected-crt.pfx -nodes -out temp.pfx
<enter password>
```
2. Genearte a new pfx without passphrase
```console
$ openssl pkcs12 -export -in temp.pfx  -out unprotected.pfx
press [return] twice for no password

$ rm temp.pfx # delete temporary certificate
```

Also, It would we great if you can share local certificates/steps which we can use to reproduce this issue at our end.

**Comment by TheNestea** [comment] 2019-07-10 07:14
> 2. Remove the passphrase from pfx and try again

Only this helps, Thx

**Comment by codenirvana** [comment] 2019-07-23 14:27
@TheNestea @FunksMaName Can you update your app and confirm if this issue is fixed in the latest version of the Postman app `v7.3.4`?

**Comment by FunksMaName** [comment] 2019-07-24 16:18
Thanks @codenirvana, I can confirm that this now assigns the configured client certificate as expected in version 7.3.4 

![postman](https://user-images.githubusercontent.com/2690060/61810335-f72e8980-ae36-11e9-92c1-1f3a84369043.PNG)

**Closed as completed** 2019-07-25 05:30 UTC
Labels: bug, Certificate, client-certificates, product/runtime
