### ISSUE TITLE
The Postman cannot send the attachments ( .wav ) 

### ISSUE THREAD

**Issue by DenysZvarychDEEP** [a85/POSTMan-Chrome-Extension#9636] opened 2021-02-19 09:49 UTC
**Describe the Issue**
* The Postman cannot send the attachments ( .wav ). `File: undefined.`

**Pre-conditions:**
 
1. Open Postman App.
2. Create your own account.
3. Sign in.
4. Open Postman settings
5. On the General tab activate "Allow reading files outside working directory"

**Steps to Reproduce**

1. Create the [ POST ] request which includes in the Body -> form-data: file (required) with the file extension .wav (audio)
2. Send the request

**Actual result:**

- In the Console -> Request Body : `file: undefined`

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/79307980/108487150-9b90e000-72a7-11eb-90aa-f3209fa25854.png)

**Environment Information**

 - Platform Type: desktop app
 - Postman Version: Version 8.0.6 win32 10.0.15063 / x64
 - Operating System: Windows 10 Pro. System type: 64-bit Operating System, x64-based processor

**Additional Context**

- This bug does not always appear but in most cases. To fix this I completely reinstall the Postman app (and even this action didn't always help). However, due to Newman, this error does not exist.

**Comment by DannyDainton** [comment] 2021-02-19 17:51
Hey @DenysZvarychDEEP 

I've tried to recreate the issue locally and using a .wav file but I'm unable to see the same behaviour.

<img width="1634" alt="Screenshot 2021-02-19 at 17 47 24" src="https://user-images.githubusercontent.com/17089546/108541686-aa44ba80-72da-11eb-8d1a-36ffb5f77911.png">

Are there any other contextual information that could result in this happening?

**Comment by aielloaldo** [comment] 2021-03-30 08:10
I've also this problem with the new version of Postman (8.x). Instead with the older version (7.x) the same collection works.
The message is "This file isn't in your working directory. Teammates you share this request with won't be able to use this file. To make collaboration easier you can setup your working directory in Settings" and in the request data the file is undefined.

I tried on Windows and OSX and both have the same issue only with new Postman version

**Comment by shamasis** [comment] 2021-03-30 08:17
> I've also this problem with the new version of Postman (8.x). Instead with the older version (7.x) the same collection works.
> 
> The message is "This file isn't in your working directory. Teammates you share this request with won't be able to use this file. To make collaboration easier you can setup your working directory in Settings" and in the request data the file is undefined.
> 
> 
> 
> I tried on Windows and OSX and both have the same issue only with new Postman version

You may have checked this already, but have you checked the status of the working directory settings in your 8.x installation. https://support.postman.com/hc/en-us/articles/360023574653-Storage-of-file-Working-Directory-in-reference-for-collections

**Comment by aielloaldo** [comment] 2021-03-30 08:22
@shamasis 
Yes, the collection and the settings are the same and the working directory is fine. In Postman 7 it works, in Postman 8 don't.

![Screenshot 2021-03-30 at 10 23 25](https://user-images.githubusercontent.com/54989749/112957815-1ae4bf80-9142-11eb-8350-5b0cd596abd1.png)

**Comment by apoorvgupta03** [comment] 2023-06-13 12:16
Hey @DenysZvarychDEEP  and @aielloaldo, We tried reproducing it but couldn't, can you please confirm if you are still facing this issue, you can also update the Postman App for feature improvements and rich UI.

**Comment by apoorvgupta03** [comment] 2023-06-26 04:53
We're closing the ticket as we couldn't reproduce the reported issue at this time on MacOS or WindowsOS. 
We sincerely encourage you to reopen the ticket if you encounter the problem again or if you have any further details that could assist us in resolving it

**Closed as completed by apoorvgupta03** 2023-06-26 04:53 UTC
Labels: bug, product/runtime
