### ISSUE TITLE
$randomInt dynamic variable appears to be 0-1000 not 1-1000 as documented

### ISSUE THREAD

**Issue by bradthurber** [a85/POSTMan-Chrome-Extension#10168] opened 2021-07-28 21:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

A request using $randomint today resulted a value of 0 (zero). Docs say it should be 1-1000.

### Steps To Reproduce

Use $randomInt in a request
Submit a bunch of requests until you get one that has a randomInt value of 0

### Environment Information

```markdown
- Operating System: Windows
- Platform Type: Desktop
- Postman Version: 8.9.1
```

**Comment by neilstudd** [comment] 2021-07-30 12:52
Thanks for reporting this, @bradthurber. I've confirmed using a pre-request script that, in its current form, `$randomInt` seems to be returning values from 0-999:

```
numbers = [];

for (i = 1; i < 10000; i++) {
    numbers.push(pm.variables.replaceIn('{{$randomInt}}'));
}

numbers.sort();
console.log("Numbers range from " + numbers[0] + " to " + numbers[numbers.length -1]);
```

...which outputs `Numbers range from 0 to 999`.

I'm unclear whether this is a behavioural regression or a documentation issue, but will get this investigated further.

**Comment by bradthurber** [comment] 2021-07-30 19:14
Hi @neilstudd - Thank you for reviewing this and taking the time to make a pre-request script to confirm the behavior!

I was certain that I saw $randomInt return 1000 the other day. It looks like .sort does an alpha sort by default instead of a numeric sort unless a "compare" function is provided such as `numbers.sort(function(a, b){return a-b});`. 

This then outputs `Numbers range from 0 to 1000`.

**Comment by neilstudd** [comment] 2021-07-30 19:43
Ah - thanks for spotting my script oversight! 

I've checked the underlying faker libraries, and when asking for a random number up to `x`, it does indeed use `0-x` as the range. So I'm fairly confident that this is a long-standing documentation issue rather than anything that's changed, but I'll confirm with the relevant people.

**Comment by neilstudd** [comment] 2021-08-04 06:42
The [public documentation for dynamic variables](https://learning.postman.com/docs/writing-scripts/script-references/variables-list/) has now been updated to reflect the actual behaviour - there was a similar problem with the stated range for `$randomPrice` which I have fixed at the same time.

@coditva Could you please close this issue when you get a chance? I haven't got GitHub Issues powers yet 🙏

**Comment by coditva** [comment] 2021-08-04 09:53
@neilstudd Thanks for the documentation update! I found that this issue is also present in the variables' descriptions. Will close this one out after updating it there.

**Comment by coditva** [comment] 2021-09-01 13:53
@bradthurber This has been fixed in the latest version of Postman. :tada:

**Closed as completed by coditva** 2021-09-01 13:53 UTC
Labels: bug, product/runtime, dynamic-variables
