### ISSUE TITLE
Featurerequest : allow multi-select to dragdrop requests

### ISSUE THREAD

**Issue by Brilbroeder** [a85/POSTMan-Chrome-Extension#9469] opened 2021-01-27 11:09 UTC
When moving request from one folder to another, it has to be done one by one.
It would be nice to hold shift down, select multiple and than dragdrop the selected ones.

If possible in combination with the copy/dragdrop ;-)

**Comment by entimaniac** [comment] 2021-04-14 15:14
I'd also like to see this feature. I'll often have multiple requests in a row like create object1, create object2, create object3 ... to setup a certain state in my application and so that I can properly test. This sort of setup might happen multiple times for different scenarios so I need to duplicate the requests. Selecting and copying whole blocks of requests would make things so much easier. 

Another use case is I sometimes copy whole collections because its basically the same setup but I'll need to delete a lot of the existing requests that aren't needed. Its a hassle to delete 30 requests one at a time.

**Comment by Greeley** [comment] 2022-03-25 19:05
I'd like to see this feature as well. Along with the use cases provided above, opening multiple requests into the workspace at the same time would be quite helpful.

**Comment by shubhbhargav** [comment] 2022-05-02 04:25
Closing this as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1066

**Closed as completed by shubhbhargav** 2022-05-02 04:25 UTC
Labels: feature, user-interface
