### ISSUE TITLE
JSON to Table view

### ISSUE THREAD

**Issue by ezequias** [a85/POSTMan-Chrome-Extension#5018] opened 2018-08-13 11:18 UTC
Hi eveyone

Have you any plan to integrate Postman Client to http://json2table.com/# tool?

I miss the json to table(html) in a way I could make easy import to [HighChartsCloud](https://cloud.highcharts.com) and increase my productivity.

**Comment by a85** [comment] 2019-03-10 03:54
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/519. We haven't gotten around to this yet but hopefully soon with our new plug-in system

**Closed as completed by a85** 2019-03-10 03:54 UTC
Labels: feature, data-editor
