### ISSUE TITLE
Documentation not showing the Authorization Key name

### ISSUE THREAD

**Issue by eqnet** [a85/POSTMan-Chrome-Extension#8839] opened 2020-07-27 15:11 UTC
**Describe the bug**
Authorization API Key
Key <key>

This should reflect the Key name in the Authorization tab.

**To Reproduce**
1, Setup Request level Authorization.
2. Create Documentation

**Expected behavior**
Display the Key name in the Authorization tab.  i.e. X-API-Key

**Screenshots**
![image](https://user-images.githubusercontent.com/3315009/88558519-8c082c00-d023-11ea-8ad3-c9608c5eed0c.png)

**App information (please complete the following information):**
 Native App
 Postman v7.29.1
 Windows 10

**Additional context**

**Comment by Raja-Simha** [comment] 2020-08-03 19:14
Duplicate of #8861

**Closed as completed by Raja-Simha** 2020-08-03 19:14 UTC
Labels: bug, product/documentation
