### ISSUE TITLE
Cannot create new Team Workspaces

### ISSUE THREAD

**Issue by Diuda** [a85/POSTMan-Chrome-Extension#6945] opened 2019-07-18 12:51 UTC
**Describe the bug**
If a user leaves a team through Postman dashboard he cannot create Team Workspace unless he logs out and login again. Error is thrown for every team workspace related task such as creating team workspace and inviting users to workspace.

**To Reproduce**
Steps to reproduce the behaviors:
1. Open Postman App. Create a team workspace.
2. Click on profile option in **Manage Accounts**.
3. Dashboard is opened in Chrome. Go to **Your Team** and leave the team.
4. Go to Postman App again. Try to create a team workspace.
5. Error pops up saying **Something went wrong while creating this workspace**.
6. Error comes up if user tries to invite another user.

**Expected behavior**
User should be able to create a new team workspace after leaving the existing team.

**Screenshots**

**Error while creating new team workspace after leaving current team**
<img width="346" alt="Screenshot 2019-07-18 at 5 50 56 PM" src="https://user-images.githubusercontent.com/12708871/61457707-8a267a00-a986-11e9-84db-d560d653d1f2.png">

**Error while inviting users after leaving current team**
<img width="508" alt="Screenshot 2019-07-18 at 5 39 18 PM" src="https://user-images.githubusercontent.com/12708871/61457810-bd690900-a986-11e9-87ed-05ca2d123653.png">

**DevTools Console**
![Screenshot 2019-07-18 at 5 40 46 PM](https://user-images.githubusercontent.com/12708871/61457883-e6899980-a986-11e9-8bdf-e179ed6c8cec.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.3.3
 - OS: macOS OS X 18.6.0 / x64

**Additional context**
DevTools Console shows **Bad Request** with status code `400`.
Works fine if user logs out and logs in again.

**Comment by sankalp0o** [comment] 2020-01-16 04:28
Hi @Diuda , thanks for reporting this! The issue is fixed in the latest Postman app, please let us know if you still face the same problem.

**Comment by Diuda** [comment] 2020-01-16 07:46
@sankalp0o This is still happening I think. I'm not able to create a workspace after I leave the team. 
![teamleave](https://user-images.githubusercontent.com/12708871/72503710-6b843b80-3862-11ea-957d-05b0a4cb1907.gif)

**Comment by sankalp0o** [comment] 2020-01-18 07:04
Hey @Diuda , thanks for letting us know. We are looking into why it's not resolved for you. Will keep you updated!

**Comment by Diuda** [comment] 2020-01-31 06:25
@sankalp0o You can close this issue. I tried this recently and the issue seems to be fixed.

**Closed as completed** 2020-01-31 18:06 UTC
Labels: bug
