### ISSUE TITLE
Removing user the Team workspace shows that the "User not found", but pop-up says "Removed User"

### ISSUE THREAD

**Issue by Pricilla09** [a85/POSTMan-Chrome-Extension#10858] opened 2022-04-21 11:52 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When we try to remove a user from the Team Workspace, the displayed information is not coherent. It is displayed as "User not found", but the pop-up says "Removed User", which is a bit contradictory. 

### Steps To Reproduce

1. Create a new Team workspace
2. Add few members to it
3. Try to remove the users from the team workspace

### Screenshots or Videos

<img width="960" alt="Snag_59b16985" src="https://user-images.githubusercontent.com/71498483/164451700-bcdeb144-9d8c-4792-a8ea-5d3386ee1d50.png">

### Operating System

Windows

### Postman Version

9.15.11

### Postman Platform

Postman App

### Additional Context?

Using the the professional monthly plan of Postman

**Comment by DannyDainton** [comment] 2022-04-28 11:52
Hey @Pricilla09 👋🏻 

Would you be able to clarify the steps you're taking and the area of the platform that you were in when this occurred? 

You mention adding and removing members from a _Team Workspace_ but the image shows members being removed from a Team, which is something different.

**Comment by ramji367** [comment] 2022-05-02 20:43
@ArjunSingh-PM - FYI, I ran into this same issue a couple of weeks ago.

**Comment by Pricilla09** [comment] 2022-05-08 03:19
Hi @DannyDainton, Adding the team members is not an issue. Once added, if I am trying to remove them, there are two different messages on the screen. 

I am using a Team workspace with a limit of 15 members - Professional plan (Monthly)

**Comment by DannyDainton** [comment] 2022-05-08 06:13
The screenshot shown looks like the one from the _Manage team_ area. Are you removing them from a Team and not the Team Workspace?

Removing members from a Team **Workspace**, from the Workspace Settings tab, is a different action that wouldn't lead to this page.

Can you add a short recording of this behaviour, if you're still seeing this please.

**Comment by akshay-kulkarni-03** [comment] 2022-07-05 10:01
@Pricilla09 would you be able to share the recording for this issue? As @DannyDainton mentioned removing members from team & from workspace are different actions.

**Comment by DannyDainton** [comment] 2022-07-06 12:57
I'm going to close this issue for now. If we receive a recording of the behaviour and reliable steps to reproduce, we can take a close look and investigate this issue further.

**Closed as completed by DannyDainton** 2022-07-06 12:57 UTC
Labels: bug, need-more-info, workspaces
