### ISSUE TITLE
Base64 wrong data with cyrillic chars

### ISSUE THREAD

**Issue by akavato** [a85/POSTMan-Chrome-Extension#4384] opened 2018-03-26 14:08 UTC
## App Details:

```
Postman for Windows
Version 6.0.10
win32 6.1.7601 / x64
```

## Issue Report:
 1. Constant problem
 2. Basic auth encodes wrong data, if login contains cyrillic chars

**Comment by harryi3t** [comment] 2018-06-29 19:00
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4070

**Closed as completed by harryi3t** 2018-06-29 19:00 UTC
Labels: bug, encode-decode
