### ISSUE TITLE
CSV File as an iteration Data is appended with "\r" for the last record value.

### ISSUE THREAD

**Issue by built-by-vjallada** [a85/POSTMan-Chrome-Extension#4352] opened 2018-03-19 03:53 UTC
## App Details:

```
Postman for Windows
Version 6.0.10
win32 6.1.7600 / x64
```

## Issue Report:

Open the Collection Runner.
For the Data, browse the CSV file.
Check that the Data File type is auto selected to "text/csv".
Click on [Preview] button.
Check that the last record is appended by "\r"

Attached the screenshot.

Screenshot:
![image](https://user-images.githubusercontent.com/22824009/37577211-d6498796-2b84-11e8-82f1-1b938a342274.png)

**Comment by sivcan** [comment] 2018-03-19 12:31
Hi @sekhar-selenium - Thanks for reporting this.
I'll look into it and get back to you.

**Comment by sivcan** [comment] 2018-03-20 12:35
Hi @sekhar-selenium - I tried to reproduce this error but couldn't.
The editor that you're using is probably adding this escape character.
![image](https://user-images.githubusercontent.com/12631777/37654709-1668aa3e-2c69-11e8-8bd4-c0b163cf1f6d.png)

Can you try it with multiple CSV files ? 
Or is this just specific to this one ?

Can you try another editor to generate this file?

**Comment by Rob-DeRosia** [comment] 2018-04-10 18:48
I am able to reproduce this using Notepad++ and adding a blank line at the end of the file. After removing the blank line, the preview window no longer shows the "/r".

**Comment by sivcan** [comment] 2018-04-11 06:18
That's what was mentioned in this https://github.com/postmanlabs/postman-app-support/issues/4352#issuecomment-374581610, that the data file that is being uploaded has an escape character that has been added in the end of the file by the editor that is being used.

I am closing this issue since it's not an issue with the app itself.

**Closed as completed by sivcan** 2018-04-11 06:18 UTC

**Comment by jsclark** [comment] 2018-06-20 19:04
I would request that this be reopened.

This bug occurs when the last row in the CSV ends with a windows line-break (CR-LF).  If I change it to a unix line-break (LF), it's fine, or if there's no line-break for the last row it's fine.

I would argue that a csv that ends with a line-break is perfectly valid, and should be supported.
e.g.
```
testname,CLIENT\r\n
line1,Acme\r\n
line2,USAF\r\n
```

Furthermore, this is the default format that Excel 2016 saves CSVs in, so it really ought to be supported.

**Comment by Kittzus** [comment] 2019-06-04 12:55
I'd like to bump this to be re-opened as well. This is a real pain when working in Windows environments and seems like an arbitrary distinction to make to allow Unix line-breaks on the final line to be parsed correctly but not Windows line-breaks.

**Comment by dpearce-aconex** [comment] 2019-06-14 04:24
Me too.

**Comment by vikiCoder** [comment] 2019-06-18 05:48
Hi,

We've fixed this problem. The fix is available on the [latest canary](https://www.getpostman.com/downloads/canary) version (Version 7.1.1-canary07) of the app. You can checkout [canary](https://www.getpostman.com/downloads/canary) and let us know if you are still facing this issue in it.
