### ISSUE TITLE
4.1.2 - Send and Download creates empty/invalid files

### ISSUE THREAD

**Issue by tredston** [a85/POSTMan-Chrome-Extension#1905] opened 2016-03-22 12:48 UTC
Hi,

We've encountered a couple of bugs in the new versions of Postman. These previously worked in 3.2.20 but are not working in 4.0.1 and 4.1.2.

**Bug 1:** When trying to retrieve a zip first time with "Send and Download" the result is 0 bytes.

Steps to reproduce:
0. Open a new tab
1. GET https://github.com/postmanlabs/postman-app-support/archive/support.zip
2. "Send and Download"
3. Save the file (eg response.zip) 
4. Notice it's 0 bytes

**Bug 2:** When trying to retrieve a zip with "Send and Download", after first "Send"ing, the result is an invalid zip.

Steps to reproduce:
0. Open a new tab
1. GET https://github.com/postmanlabs/postman-app-support/archive/support.zip
2. "Send" (and see a zip like body in the response)
3. "Send and Download"
4. Save the file (eg response.zip) 
5. Notice it's not 0 bytes and attempt to unzip it.

Thanks

**Comment by abhijitkane** [comment] 2016-03-22 18:24
@tredston Got it. We've fixed this, and will push the fix out in the next release. Thanks for reporting this.

**Comment by dangerman** [comment] 2016-03-22 19:02
@abhijitkane Glad to hear it's fixed :+1: 

I noticed that it isn't specific to zip files (in 4.1.2 I've reproduced Bug 2 with .xlsx files), so perhaps we should update the issue title?

**Comment by tojagrut** [comment] 2016-03-25 15:37
@abhijitkane  may I know when can I expect this release?  I need this fix to proceed.

**Comment by zvercheto** [comment] 2016-03-30 06:39
@abhijitkane I also hit this issue. When will the fix be available?

**Comment by abhijitkane** [comment] 2016-03-30 07:49
@zvercheto @tojagrut We'll be pushing a fix for this today.

**Comment by zvercheto** [comment] 2016-03-31 07:55
@abhijitkane Has the fix been pushed and how can I get it?

**Comment by abhijitkane** [comment] 2016-03-31 11:58
@tojagrut @zvercheto We just released the Chrome app - you can update by going to `chrome://extensions, enable 'Developer Mode', click Update extensions now`

**Closed as completed** 2016-04-26 02:50 UTC

**Comment by cristianmuntianu** [comment] 2016-05-31 06:20
Hello,

We are still experiencing this problem on postman 4.2.2.
Would you kindly review this issue and check if it's actually fixed?

The bug/error occurs when downloading archived database dump files from S3 using Api calls.

I ruled out the error from our api call since i've tried countless times to reproduce the bug using cURL calls and worked perfectly.
The file is around 200 MB in size. 

Have not tested/seen scenarios where a file having 1GB or more to have this issue.

Regards,
Cristian Muntianu
Technical Support Engineer 
[Mambu Tech](http://www.mambu.com/)
