### ISSUE TITLE
Changing from Post body x-www-form-urlencoded to form-data does not change header Content-Type

### ISSUE THREAD

**Issue by evanchan** [a85/POSTMan-Chrome-Extension#2366] opened 2016-09-29 12:06 UTC
In Mac app v4.7.2
If I select a request as POST with body x-www-urlencoded, Header `Content-Type: application/x-www-form-urlencoded` is automatically added. However, if I change the post body from x-www-urlencoded to form-data. The header `Content-Type: application/x-www-form-urlencoded` remain unchanged. The request will be sent using the wrong header `application/x-www-form-urlencoded` rather than `multipart/form-data`

**Comment by vegetableman** [comment] 2016-09-29 12:57
@evanchan Detecting `Content-Type` for `form-data` could lead to inaccurate results, as form-data supports multiple media types. One plausible fix could be clearing out the value  `application/x-www-form-urlencoded` from the header in case of `form-data` selection. Let me know if that will help.

**Comment by reinaldomoreira** [comment] 2017-05-19 14:17
getting the same problem yet.

**Comment by KMayne** [comment] 2017-07-26 08:44
+1 Spent a few hours debugging my app when this was the cause :disappointed:

**Comment by leaanthony** [comment] 2017-07-27 00:34
+1 as above. Wasted at least an hour on this thinking it was poor 3rd party parsing libraries only to accidentally discover that the x-www-form-urlencoded header was still present :angry:

**Comment by yeomann** [comment] 2018-06-19 08:42
+1 same problem in Mac version see the screenshot pls. I selected the content type from body tab.
<img width="842" alt="screen shot 2018-06-19 at 11 41 28" src="https://user-images.githubusercontent.com/5970751/41586553-bc244bf2-73b5-11e8-9252-6f714e52f13b.png">

**Comment by vkaegis** [comment] 2018-07-04 07:43
Hey guys, thanks for all the feedback. We've noticed some discrepancies around the header being added automatically, will be rolling out fixes in the coming versions. That said, we'll also be exploring ways in which you can control this behavior so that you can decide when and where you'd want the header to be added. Stay tuned for updates!

**Comment by ryanharmaning** [comment] 2018-10-24 15:33
Any further update on this? We also spent a couple hours debugging our app to find this was the issue. We have a manual work-around, but it prevents us from automating a test suite for our particular scenario.

Currently running  Postman 6.4.4 Mac (High Sierra)

**Comment by alucic** [comment] 2019-03-22 01:30
This issue is consuming a lot of debugging time for past 2 years, @vkaegis any updates on it?

**Comment by vkaegis** [comment] 2019-03-22 10:05
@alucic No ETA just yet, but this is on our roadmap.

**Comment by shamasis** [comment] 2019-04-29 20:31
Hey, we are planning to take this up in near term. The way we are thinking of doing this is stop auto adding the header in UI and instead if no specific content-type header is added in UI then and only then automatically add this as temporary in-flight headers.

**Comment by codenirvana** [comment] 2020-03-10 22:57
This is fixed in the latest version of the Postman app.

Postman will no longer force add/update the `Content-Type` header.
The default `Content-Type` header will be added (if not present already) only at the time of request sending based on the selected request body mode.

**Closed as completed by codenirvana** 2020-03-10 22:57 UTC
Labels: bug, Content-Type, product/runtime, request-body-configuration

**Comment by sciamano89** [comment] 2021-09-03 19:05
Hi, I'm having an issue with the test collection generated by the API tool. My requests' bodies are declared with a `$ref` to a component that has its `content` set to `application/x-www-form-urlencoded`. The problem is that each endpoint in the generated Test collection does not default its body to the `application/x-www-form-urlencoded` type, so the `example`s I have created are not present. The only workaround for this is if I manually switch the body type, save, then re-validate the test suite, review the errors, and accept the changes needed. Am I missing something? Thanks
