### ISSUE TITLE
Right click tab, show in collection panel

### ISSUE THREAD

**Issue by CyberMew** [a85/POSTMan-Chrome-Extension#8881] opened 2020-08-04 01:22 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Find out where does my tab come from. I have unchanged tab and I have no idea is it a brand new tab, or is does it come from collection. not being able to see the original vs the change is already a PITA. at least if i know it's from the collection, i can discard my changes.
**Describe alternatives you've considered**
there is none.
**Additional context**
see context above. do it like vscode, Reveal in Side Bar (in this case, Collections)

**Comment by codenirvana** [comment] 2020-08-04 04:35
@CyberMew If the collection sidebar is open, it does highlight the selected request in the tab.

![Screen Recording 2020-08-04 at 9 59 10 AM](https://user-images.githubusercontent.com/4865836/89253223-a8b2ee00-d639-11ea-84f3-2dcc167333e6.gif)

Can you share more details about the problem you are facing?

**Comment by codenirvana** [comment] 2020-08-04 13:32
Duplicate of #8486

**Closed as completed by codenirvana** 2020-08-04 13:32 UTC
Labels: tabs, user-interface, need-more-info, product/runtime
