### ISSUE TITLE
an old cookie header continues to be injected even after I close postman

### ISSUE THREAD

**Issue by bseib** [a85/POSTMan-Chrome-Extension#1425] opened 2015-09-05 15:13 UTC
I have an application that issues a cookie that is used as a token for subsequent calls. In Postman, I set this cookie header for those subsequent calls to do my testing. One of my tests is for an invalid payload of the cookie, which is easy to create by simply adding a space character in the cookie header.

Here is a screenshot of how I set the cookie in the header, using the "bad" cookie:

![postman-bug-screenshot1](https://cloud.githubusercontent.com/assets/1313561/9699726/2db93354-53bb-11e5-85ad-6172c3da95a1.PNG)

Okay, everything is fine, tests failed properly, etc. (Although I did have to go to Chrome > More tools > Extensions and enable the postman interceptor, which I had disabled a while back.)

I quit postman. I disable the postman interceptor extension.

---

Now, fast forward a few hours, and I am interacting with the _real_ website that I had been testing earlier with Postman.

Strangely, things are not working correctly, and I narrow it down to the real site being unhappy with the cookie it is receiving. My server logs are reporting that the test cookie from earlier is showing up. Look at the following log line.

![postman-bug-screenshot2](https://cloud.githubusercontent.com/assets/1313561/9699767/24c30922-53bc-11e5-95c4-f24c2e19b4a2.PNG)

There it is, extra space character and all.

Okay, fine. Maybe chrome really does have the wrong cookie and it really is sending this to the server.

Nope.

I went into Chrome Dev Tools and removed all cookies associated with my domain. Then I visited my site again to be issued a brand new cookie. I looked in Dev Tools to find my newly issued cookie, and yep, there's a fresh, valid cookie:

![postman-bug-screenshot3](https://cloud.githubusercontent.com/assets/1313561/9699793/b68607a6-53bc-11e5-92de-0cb1b3780df7.PNG)

That cookie starting with `3ebb68` is a newly minted cookie. But what does my server see when I visit? It sees the old `96ed66` cookie, the one used hours ago in Postman:

![postman-bug-screenshot4](https://cloud.githubusercontent.com/assets/1313561/9699822/631f56fc-53bd-11e5-92d1-d49cf1bbabb6.PNG)

I don't understand how chrome can still be sending this cookie, even after I disabled the Postman Interceptor extension. But the evidence is clear. The _only_ place that `96ed66` cookie ever existed is in my Postman test. Something happened to pollute Chrome's notion of what headers to send to the server, and perhaps needs to clean up when shutting down the extension, or when the individual test is done executing.

**Comment by abhijitkane** [comment] 2015-09-05 19:11
Can you try reproducing this with http://dump.getpostman.com/?

You can use Postman to send a GET request to `http://dump.getpostman.com/cookies/set?name=postman` (with the interceptor enabled) to set a cookie. Visit http://dump.getpostman.com/cookies in your browser to see a list of cookies saved. Go to DevTools, delete the `name` cookie, and visit http://dump.getpostman.com/cookies. The `name` cookie should disappear from the response. 
Visit `http://dump.getpostman.com/cookies/set?name=new_postman`, and then go to `/cookies`. You should see the new value for name.

This is the flow I tried, and the behaviour I saw. Are you seeing a different behaviour for the same flow?

**Comment by bseib** [comment] 2015-09-05 23:16
Using `dump.getpostman.com`, I recreated the flow of events, but could not reproduce the problem. Here's a record of what I did:

Before starting up postman or anything, I pulled up the dump.getpostman.com site to have a look at what its default state looks like:

![screen1](https://cloud.githubusercontent.com/assets/1313561/9701585/cccb653c-53fe-11e5-8b94-6fcfa994ffc8.PNG)

![screen2](https://cloud.githubusercontent.com/assets/1313561/9701586/d11e95aa-53fe-11e5-9e64-0be208b31987.PNG)
No cookies here.

![screen3](https://cloud.githubusercontent.com/assets/1313561/9701587/d39587a8-53fe-11e5-85d1-da14ee2e9197.PNG)
No cookies here either.

---

Fire up Postman. Let's invoke a GET request with a manually constructed cookie header.

![screen5](https://cloud.githubusercontent.com/assets/1313561/9701591/d8150f06-53fe-11e5-973c-c1c08d853139.PNG)

Send the request.

![screen4](https://cloud.githubusercontent.com/assets/1313561/9701589/d5f20f76-53fe-11e5-805c-2d61356048fe.PNG)

Whoops, it spins like this forever.... Oh yeah. I gotta turn on my postman interceptor extension.
![screen4 5](https://cloud.githubusercontent.com/assets/1313561/9701619/a2750620-53ff-11e5-964b-8958c8b84d33.PNG)

Ok, now restart postman.

(Yeah, this is _exactly_ the sequence of events that happened to me when I saw this problem. )

Now send that GET request with the manual cookie header set:

![screen6](https://cloud.githubusercontent.com/assets/1313561/9701592/d9fd3b4a-53fe-11e5-81ba-d4b855b749b7.PNG)

Yay! The respons JSON even echoed back the manually set cookie that I sent.

And my cookie even thinks it is a cookie:
![screen7](https://cloud.githubusercontent.com/assets/1313561/9701593/dc5b84a0-53fe-11e5-9152-8952988a2633.PNG)

So that means Chrome must have the same cookie. Visit dump.getpostman.com/get to see what it thinks we have for cookies:
![screen8](https://cloud.githubusercontent.com/assets/1313561/9701594/de6269c6-53fe-11e5-93dd-4d02d8f9c966.PNG)

Okay, good. The usx cookie is there.

Now quit postman and disable the Interceptor extension.
![screen9](https://cloud.githubusercontent.com/assets/1313561/9701596/e0bd25f8-53fe-11e5-83ba-f65949f31111.PNG)

Is our cookie still in chrome being presented as expected?
![screen10](https://cloud.githubusercontent.com/assets/1313561/9701597/e3173708-53fe-11e5-9048-5d98fb74a249.PNG)

Yes. It's still being presented.

---

Okay, now let's have the server set a new cookie value for the same cookie. Visit http://dump.getpostman.com/cookies/set?usx=foobar

That request did indeed set the new value to the cookie:

![screen11](https://cloud.githubusercontent.com/assets/1313561/9701598/e6b4d8d4-53fe-11e5-8b27-f5e72a72a354.PNG)

And here's the moment where I saw the "old" cookie being sent. Do another GET of any kind, and see what cookie is being presented to the server.

![screen12](https://cloud.githubusercontent.com/assets/1313561/9701600/e8f77282-53fe-11e5-8b15-aefa2d06ce1c.PNG)

We correctly got the "foobar" cookie rather than the purported '96ed66' cookie. Bummer.

---

One more thing to try. Delete the cookie from Chrome. Let's go find it:
![screen13](https://cloud.githubusercontent.com/assets/1313561/9701680/296b7c3e-5402-11e5-986e-25ed59bb4c35.PNG)

Then delete it:
![screen13 5](https://cloud.githubusercontent.com/assets/1313561/9701681/303fde74-5402-11e5-80ac-8f55383749fd.PNG)

And do the GET request again:
![screen14](https://cloud.githubusercontent.com/assets/1313561/9701682/382e8f04-5402-11e5-867c-bf9c89c51118.PNG)

No cookies. Looks correct.

**Comment by bseib** [comment] 2015-09-05 23:29
After I opened this issue, I thought I would try restarting Chrome to see if that cleared things up. I saw that Chrome's hamburger menu was green, meaning an update was ready. I performed the chrome update and restarted chrome.

At this moment, my problem had gone away. When I would browse to my live site where I had been getting cookie errors, the server was receiving the correct cookie now.

So I think my above test case is the right procedure to reproduce things. But unfortunately, I had disturbed the crime scene.

---

I would like to make a general observation about Chrome updates from the past. As a developer, I hate closing down chrome. I inevitably end up with a dozen or so windows or tabs that I am actively using, and when Chrome comes along and suggested that I update, I tend to put it off until the indicator turns yellow or red.

In the past I have had the experience of chrome "behaving badly" when an update is pending. More than once I remember seeing all DNS resolution fail, only within Chrome, and not on the rest of my machine. Installing the update and restarting Chrome would fix the problem.

---

The pending Chrome update is the only confounding factor here that I can identify. Closing this issue is appropriate. The next time I have a pending Chrome update, I'll try to reproduce the problem again.

**Comment by bseib** [comment] 2015-09-05 23:34
I want to record one other observation, for when I try to reproduce this next time:

When I visited my live site and witnessed the "old cookie" show up on the server, that old cookie did _not_ show up on _all_ URLs. Only a select few REST calls were receiving the old cookie and logging an error. There were likely the same REST urls that I had been testing from Postman.

**Comment by abhijitkane** [comment] 2015-09-06 10:17
The Interceptor uses Chrome's cookie API - https://developer.chrome.com/extensions/cookies to set cookies when you include the 'Cookie' header, setting the URL, name, and value.

Closing this for now. Feel free to reopen if you see the issue, and thanks for the detailed report. Should help a lot if the issue is seen again.

**Closed as completed by abhijitkane** 2015-09-06 10:17 UTC
Labels: bug, support

**Comment by Hubbitus** [comment] 2016-07-20 09:49
I saw similar issue.
Additional cookie sent when I discover site even with postman and postman interceptor was deleted from chromium. That cookie indeed was set in one of my debug session.
Then I check and delete **all** cookies for the site from dev tools resources tab.
But it still listed if I look at them on [chrome://settings/cookies](chrome://settings/cookies). Found answer at http://stackoverflow.com/questions/28305273/how-to-delete-session-cookie-in-postman! Only delete there solve my problem.

**Comment by ApeksIT** [comment] 2018-01-18 11:27
I think I got the same issue with the latest version. When I've been logged in using Basic Auth and then removed the cookies and use new/other credentials, somehow the old credentials are used to log in with a new request.

Also when after changing to No Auth, I can still send a successful request, because the old info is used

Postman v5.5.0
