### ISSUE TITLE
Missing settings for deletion confirmations

### ISSUE THREAD

**Issue by nikitasius** [a85/POSTMan-Chrome-Extension#5348] opened 2018-10-11 15:02 UTC
**Describe the bug**
When you want to delete, app ask you to confim it. There are **no option to disable it**.

**To Reproduce**
Try to delete any example.

**Expected behavior**
Settings where you can choose "autoconfirm" or "do not ask confirmations for deletions"

**Screenshots**
![image](https://user-images.githubusercontent.com/3670331/46813488-144a0e00-cd77-11e8-89e0-293835a11201.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.4.2
 - OS: Linux pentagon 4.9.0-0.bpo.5-amd64 #1 SMP Debian 4.9.65-3+deb9u2~bpo8+1 (2017-01-05) x86_64 GNU/Linux

**Additional context**
Thats annoying, when you can't manage this.

**Comment by sujayvenaik** [comment] 2018-10-11 15:38
Duplicate of #3386

**Closed as completed by sujayvenaik** 2018-10-11 15:38 UTC
