### ISSUE TITLE
Where did request count go?

### ISSUE THREAD

**Issue by HenrikHolmIT** [a85/POSTMan-Chrome-Extension#9757] opened 2021-03-23 12:58 UTC
In previous version there was a count of underlying requests on the Collections. This is now gone with version 8.0.7

I'd need those counts back.

There are no alternatives. I need just them back.

No need for screenshot. They are gone. I need them back.

**Comment by DannyDainton** [comment] 2021-03-23 13:00
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9754

**Closed as completed by DannyDainton** 2021-03-23 13:00 UTC
Labels: duplicate
