### ISSUE TITLE
4.5.0 could not get reponse when using self-signed SSL certificates with client certificate

### ISSUE THREAD

**Issue by binderclip** [a85/POSTMan-Chrome-Extension#2217] opened 2016-08-02 06:38 UTC
1. Postman Version: 4.5.0
2. App (Chrome app or Mac app): Map app
3. OS details: 10.11.6
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there: Always, after upgraded to 4.5.0
6. Expected behaviour: Could trust self-signed SSL certificates. (Just turning off "SSL certificate verification" the nginx would say "No required SSL certificate was sent")
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Console: `Error:
   SSL Error: SELF_SIGNED_CERT_IN_CHAIN`
8. Screenshots (if applicable)

**Comment by abhijitkane** [comment] 2016-08-02 07:45
@binderclip Can you attach a screenshot of the console too?

**Comment by binderclip** [comment] 2016-08-02 09:00
@abhijitkane 

![console_ss](https://cloud.githubusercontent.com/assets/8187479/17322878/552c8e8c-58d2-11e6-995a-41c3b170a57d.png)

![dev_tool_ss](https://cloud.githubusercontent.com/assets/8187479/17322885/5a648620-58d2-11e6-8cd2-ae4668831812.png)

![app_ss](https://cloud.githubusercontent.com/assets/8187479/17322916/5f922652-58d2-11e6-9417-31d458e0379a.png)

**Comment by czardoz** [comment] 2016-08-02 09:09
@binderclip Have you set SSL verification to off in your settings?

**Comment by binderclip** [comment] 2016-08-02 09:33
@czardoz No, if I set SSL verification to off, response could be got but the client cert would not be sent. Response is:

![no-ssl-cer-sent](https://cloud.githubusercontent.com/assets/8187479/17323830/340dec42-58d6-11e6-80ba-eea1aa452bc6.png)

There is a client certificate verification in the server. Chrome's prompt is:

![ssl](https://cloud.githubusercontent.com/assets/8187479/17323937/a7210d5e-58d6-11e6-967e-2830288b3ab3.png)

So I couldn't just set SSL verification to off.

Old versions like Chrome app 4.4.3 and Map app 4.3.0 are OK with this.

**Comment by ctorresmx** [comment] 2016-08-02 19:04
👍 I am having this issue as well after upgrading to 4.5.0, apparently the SSL client certificate is no longer being sent in the request. I am using the Mac App

**Comment by tdurden82** [comment] 2016-08-02 19:08
I am also having the same issue with Mac App after upgrading to 4.5.0
With or without SSL Cert verification enabled.
Client cert was working in the previous version and the client cert is verified as working through other means.

**Comment by shamasis** [comment] 2016-08-02 20:24
We are actively working on this.

**Comment by bhonnegowda** [comment] 2016-08-03 20:10
downgraded to 4.4.3 temporarily.

**Comment by grace-spitzer-wong** [comment] 2016-08-04 11:22
@shamasis any update on how this is going? Can't work without Postman.

**Comment by shamasis** [comment] 2016-08-04 11:25
@Grace-W 
- we have determined the behaviour of Chrome on OSX, WIndows and Linux (this took a while)
- we are in the process of mimicking that behaviour (as close as possible) for upcoming release - hopefully in a few days. that should unblock everyone.
- post that, we would look into how this certificate management workflow can be made better and more integrated with the app.

**Comment by grace-spitzer-wong** [comment] 2016-08-04 11:26
@shamasis Thanks - do you think it will be fixed by Monday next week or is that too optimistic?

**Comment by czardoz** [comment] 2016-08-04 12:08
@Grace-W we definitely plan to fix this before Monday :)

Also, you should be able to use the Chrome app in the meantime: https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop

**Comment by grace-spitzer-wong** [comment] 2016-08-04 13:04
@czardoz Thanks for getting back to me- I have tried to use the extension but for some reason it only lets me launch the app?

**Comment by shamasis** [comment] 2016-08-05 19:27
Hey - try out 4.5.1+ to get the client certificate feature.

**Comment by tdurden82** [comment] 2016-08-05 20:26
@shamasis I've added a host/cert/key in Preferences->Certificate but it doesn't appear to be sending the client cert to the server. Do I need to make any other changes to enable the cert?

**Comment by binderclip** [comment] 2016-08-09 13:19
@shamasis Hi, I tried out 4.5.1 and add the client cert/key but it still doesn't work.

Also, the console error message is still `Error:
SSL Error: SELF_SIGNED_CERT_IN_CHAIN`, so if the question is `SSL certificate verification`? Maybe I could send the client cert but don't verify the server cert?

(I would go to learn more about HTTPS, try to build my own HTTPS server and make some tests.)

**Comment by czardoz** [comment] 2016-08-09 13:39
@binderclip you should do two things:
1. Turn off SSL verification
2. Add your client certificate in Settings > Certificates

**Comment by binderclip** [comment] 2016-08-09 14:49
@czardoz I have tried this, failed.
It seems after turning off SSL verification, the client cert won't be used? Or if my setting is wrong?

These are my setting and request:

![cert](https://cloud.githubusercontent.com/assets/8187479/17520642/0e63c3ba-5e83-11e6-96c9-74f04e303175.png)

![cert-set](https://cloud.githubusercontent.com/assets/8187479/17520659/163c6808-5e83-11e6-8239-23c33527d542.png)

![request](https://cloud.githubusercontent.com/assets/8187479/17520669/1c1926f8-5e83-11e6-8186-af35b6432890.png)

---

Using curl is OK (this is on Linux, OS X version curl doesn't support PEM cert):

```
curl -v https://clip.dev.xiachufang.com/ec/chat/api/search_goods.json\?q\=火龙果 --cert ~/temp/p12/path.crt.pem --cert-type PEM --key ~/temp/p12/path.key.pem -k
```

**Comment by tdurden82** [comment] 2016-08-09 15:02
I can confirm the behavior. I've tried with and without the verification enabled.

**Comment by sloppypointless** [comment] 2016-08-09 20:33
Windows Desktop App on 4.5.1 - Broken

**Comment by shamasis** [comment] 2016-08-10 06:50
@sloppypointless - you mean you're still seeing download modal instead of response in Windows app? What's the content type header returned?

**Comment by sloppypointless** [comment] 2016-08-10 12:17
@shamasis  Content-Type →application/json;charset=UTF-8

{
  "error": "invalid_request",
  "error_description": "proper client ssl certificate was not presented"
}

**Comment by shamasis** [comment] 2016-08-10 20:32
have you provided your SSL certificate in the settings dialog box?

**Comment by sloppypointless** [comment] 2016-08-11 15:10
@shamasis Yes.  Under Certificates I added the clients host domain ex: asdf1234.com (also tried asdf1234, api.asdf1234.com) then I used the OpenSSL to convert the pem file to a crt file and key file.  I then selected those newly generated files without a password to eliminate the passphrase need while testing.    

I am currently using 4.4.3 since I have the pfx installed on my current desktop.  If I am doing something wrong in the settings | certificates its because there is literally zero documentation I can find on what the expected selections would be in those fields.

**Comment by shamasis** [comment] 2016-08-12 07:39
@numaanashraf @czardoz any update on this?

**Comment by shamasis** [comment] 2016-08-12 07:40
@sloppypointless i agree that documentation is scanty on this. this was a last minute feature we had to urgently roll out to unblock users. I will ask someone to attend the documentation ASAP.

**Comment by shamasis** [comment] 2016-08-18 21:05
@sloppypointless we added more information regarding certificates in postman console. can you now try using latest 4.6.2 app and let us know whether you see that your certificate was picked up accurately and what error is displayed?

**Comment by sloppypointless** [comment] 2016-08-18 21:29
@shamasis So I have been using the Chrome app since it doesn't have the issue and the 4.6.0 update took out 4.4.3 (which i couldn't figure out how to get back).  I did try the newest version of the desktop application 4.6.2.  I turned off self signed and restarted the application and then removed the existing certificate entries and re-added them back.

Could not get any response
There was an error connecting to https://api.domainhere.com/auth/oauth/v2/token?grant_type=client_credentials.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Client certificates are required for this server:
Fix this by adding client certificates in Settings > Certificates
Request timeout:
Change request timeout in Settings > General

**Comment by shamasis** [comment] 2016-08-18 23:30
Great. Open the Postman Console and expanding your request. That would show the exact error. Maybe it's an issue with the certificate file format, read permissions and what not. Chrome works because at one point of time you had added the certificate, right? Anything changed in those files?

We really want to solve your issue, but have very little to go on and debug the cause. That's why we added more error messages in Postman Console for you To verify and let us know what's going on. If it helps, I am available on our community slack channel to chat with you and get this solved.

**Comment by shamasis** [comment] 2016-08-18 23:33
Also, if client side SSL is working for some, please provide a confirmation here so that we know that the feature is at least working for someone other than us. 😊

**Comment by sloppypointless** [comment] 2016-08-19 12:59
@shamasis So I never knew that the console existed until you prompted me to get the output.  Upon finding it I got this returned to me.

Error:error:0906D06C:PEM routines:PEM_read_bio:no start line

I googled the error and found most people put the CRT and KEY in the PEM file.  I copied the key file and pasted below the certificate data already in the PEM file.  I saved the data and pointed both the CRT and KEY records to the new PEM file.  This resolved the issue.  

I believe the issue was 100% on me since I had to convert a x.509 to a PFX to import into my personal certificate store.  I then used OpenSSL to convert to a PEM and from PEM to CRT and KEY.  In looking at the data inside of the CRT file I generated it contained binary data for some reason and not the actual certificate text.

**Comment by shamasis** [comment] 2016-08-19 14:14
I am glad it's resolved. Moral for us - console needs more visibility.

**Comment by sloppypointless** [comment] 2016-08-19 15:07
@shamasis Would it make sense to parse the CRT and KEY file to validate it contains -----CERTIFICATE----- text when selecting a file?  That at least would alert an end user to the fact my CRT or KEY file isn't actually a CRT or KEY file.

**Comment by tdurden82** [comment] 2016-08-19 15:28
I can also confirm that client certs are working for me too. Thanks!

**Comment by shamasis** [comment] 2016-08-19 18:23
Thank you all. This has been keeping us up all night. Now we can take a breather and add more validations to check the certificate file. Actually, there's too many variants and we don't want to get in the way of any of them. Will do something about showing more warnings though.

**Comment by bukkeamarnath** [comment] 2016-09-23 15:47
![postman](https://cloud.githubusercontent.com/assets/22398040/18792255/b9f5a6da-8183-11e6-86dc-7cd128df8295.jpg)
Hi

I am using postman for windows v 4.7.2 - i dont see the client certificate tab in the settings. Please see attached.

**Comment by SamvelRaja** [comment] 2016-09-27 03:58
@bukkeamarnath the one which you are showing us is the chrome app.
We do have our native app for windows which you can download it from [here](https://www.getpostman.com/apps). the certificate can be provided only in the native app not through the chrome app.

**Comment by skumarcse** [comment] 2016-10-28 15:49
I am using **Postman Windows NativeApp 4.8.1**. I have configured CRT & KEY(encrypted) with Passphrase under **Settings --> Certificates** as Client Certificates. Does not work. Is this issue still open at postman native app ? I tried both _ON/OFF_ of **Settings --> General --> SSL certificate verfication**.
PS: This works in Chrome - Postman extension with PFX.

**Comment by sdnts** [comment] 2016-10-28 16:12
@skumarcse PFX format isn't supported yet, we're working on it :)
Could you try a CRT format?

**Comment by skumarcse** [comment] 2016-10-30 13:26
@madebysid I did not say I used PFX format in Postman NativeApp v 4.8.1, instead I said i used CRT and KEY(encrypted) with Passphrase in Postman Windows NativeApp 4.8.1. though i used CRT & KEY, still Postman NativeApp, it do have problem of consume the certificate.

**Comment by sdnts** [comment] 2016-10-31 08:56
@skumarcse Ah, I assumed you were using PFX because you said PFX works for you in Chrome. Can you try opening up the Postman Console (Cmd/Ctrl + Alt + C), resend the request and check if the certificate was actually sent with the request?

**Comment by skumarcse** [comment] 2016-11-01 13:08
@madebysid , thanks !! I see following in Postman Console, looks like the certificate(CRT) is file passed thru pempath. but i see tunneling socket could not be established. not sure what else need to configure in Postman NativeApp for Windows.

**_Error:_**
**tunneling socket could not be established, statusCode=407**
Client Certificate:
pemPath:_"C:\cert.crt"_
keyPath:""
Proxy:
proxy:"http://xx.xxx.xxx.xx:8080"
tunnel:true
Request Headers:
cache-control:"no-cache"
Postman-Token:"3f3fdcf2-a959-4d0b-834f-1628874d1c0d"

**Comment by sdnts** [comment] 2016-11-01 13:57
@skumarcse That looks like something went wrong server-side, could you check your server?

**Comment by skumarcse** [comment] 2016-11-01 19:22
@madebysid well, that same collection works in Postman Chrome Extension where Chrome browser configured with PFX. why not on Postman NativeApp ?

**Comment by cjbiggs** [comment] 2016-11-01 22:28
I have a similar issue as @skumarcse I am using Postman NativeApp 4.8.1.  It works through Postman Chrome Extension.

**Comment by sdnts** [comment] 2016-11-03 06:52
@skumarcse @cjbiggs That's weird. We're looking into what could be causing this. Will let you know here when we find something. Thanks for reporting this.

**Comment by skumarcse** [comment] 2016-11-04 13:30
@madebysid thanks !! I think this should be fixed before fully rolling into nativeApp from Chrome Extension..

**Comment by StevenMapes** [comment] 2016-11-20 17:15
May I ask how you even get the Client Certificate option? I'm running 4.8.3 and there is no tab under settings even with client certificate only General | Themes | Shortcuts | Data | Add-ons | Sync | About

**Comment by sdnts** [comment] 2016-11-22 07:21
@StevenMapes I think you're on the Chrome App. The Chrome app relies on Chrome to supply us a certificate. I'd suggest switching to our native apps, which have certificate support in the Settings screen.

**Comment by StevenMapes** [comment] 2016-11-22 08:55
@madebysid, I'm using the latest Windows 10 Deskstop App and not the chrome app. If I install the chrome extension it just recognises the Win10 app is installed as well as launches that anyway.

**Comment by sdnts** [comment] 2016-11-22 09:06
Hm, that's weird. Could you attach a screenshot of your Settings screen here?

**Comment by StevenMapes** [comment] 2016-11-22 13:00
Sure.
Here's the desktop app
and here is the application running, open on settings showing the About
tab. You'll notice the missing menus

​

**Comment by sdnts** [comment] 2016-11-23 07:25
@StevenMapes I can't see the screenshot, I think it wasn't attached properly.

**Comment by StevenMapes** [comment] 2016-11-25 09:17
@madebysid, strange Okay here they are again, the first shows the application that I use, the second shows the launched application on the about settings menu  
![postman1](https://cloud.githubusercontent.com/assets/2013210/20620072/c278625a-b2ef-11e6-9e97-f35a6eba0c3e.PNG)
![postman2](https://cloud.githubusercontent.com/assets/2013210/20620073/c27a2b58-b2ef-11e6-93ab-78525b04423e.PNG)

**Comment by sdnts** [comment] 2016-11-25 09:57
@StevenMapes From the screenshot, it looks like you are using the Chrome App, not the native app. (I can see the Chrome version + the Interceptor icon), so in that case, certificates are not under our control.

I think Windows suggests the Chrome App in your case because you use it more often?

**Closed as completed** 2016-11-25 10:44 UTC
Labels: product/documentation
