### ISSUE TITLE
In my computer this app is not open even one time. it continuously  showing a black screen.

### ISSUE THREAD

**Issue by SorbAggarwal** [a85/POSTMan-Chrome-Extension#5940] opened 2019-02-19 06:23 UTC

**Comment by numaanashraf** [comment] 2019-02-19 09:06
@SorbAggarwal Could you verify whether you are impacted by the related issue #4594 and try the workaround detailed at https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621?

**Comment by SorbAggarwal** [comment] 2019-02-22 05:05
yeah it's the same situation I'm dealing with

**Comment by numaanashraf** [comment] 2019-02-22 06:22
@SorbAggarwal Did the workaround work for you?

**Comment by SorbAggarwal** [comment] 2019-02-22 07:34
what are they?

**Comment by SorbAggarwal** [comment] 2019-02-22 07:41
Okay,
it starts working now when I follow the instruction given by you.

Thanks, man for your support.

**Comment by numaanashraf** [comment] 2019-02-24 15:49
@SorbAggarwal Glad to hear that. I'm closing this as a duplicate of the related issue.

Duplicate of #4594

**Closed as completed by numaanashraf** 2019-02-24 15:49 UTC
Labels: duplicate
