### ISSUE TITLE
Postman OAuth Popup keeps poppig back up after successful login. error with code -3 in logs

### ISSUE THREAD

**Issue by markmcgookin** [a85/POSTMan-Chrome-Extension#8543] opened 2020-05-26 11:36 UTC
**Describe the bug**
I am running a local instance of IdentityServer4 for a dev version of our Identity Provider. (I have this on two other laptops, both the exact same code, and version of postman, both work fine). On a new laptop, when type in a valid username and password into the auth popup, it simply just closes and reopens with the fields left blank.

I'm on Mac OS 19.4.0 and Postman 7.25.0

Checking the logs I see this:

```
[1934][1590492422109][main][info]["OAuth2WindowManager~onHeadersReceived: Got response details for","https://localhost:5005"]
[1934][1590492422110][main][info]["OAuth2WindowManager~onHeadersReceived: Redirection request to","https://localhost:5005"]
[1934][1590492422110][main][info]["OAuth2WindowManager~startLoginWith - Received redirect on auth login window"]
[1934][1590492422112][main][info]["OAuth2WindowManager~onBeforeRedirect:","https://localhost:5005"]
[1934][1590492422112][main][info]["OAuth2WindowManager~startLoginWith - Received redirect on auth login window"]
[1934][1590492422116][main][info]["OAuth2WindowManager~onHeadersReceived: Got response details for","https://localhost:5005"]
[1934][1590492422117][main][info]["OAuth2WindowManager~startLoginWith - Received redirect on auth login window"]
[1934][1590492422124][main][info]["OAuth2WindowManager~did-navigate:","https://localhost:5005"]
[1934][1590492422124][main][info]["OAuth2WindowManager~startLoginWith - Received redirect on auth login window"]
[1934][1590492436368][main][info]["OAuth2WindowManager~onHeadersReceived: Got response details for","https://localhost:5005"]
[1934][1590492436369][main][info]["OAuth2WindowManager~onHeadersReceived: Redirection request to","INVALID URL"]
[1934][1590492436369][main][info]["OAuth2WindowManager~startLoginWith - Received redirect on auth login window"]
[1934][1590492436371][main][info]["OAuth2WindowManager~onBeforeRedirect:","https://localhost:5005"]
[1934][1590492436372][main][info]["OAuth2WindowManager~startLoginWith - Received redirect on auth login window"]
[1934][1590492436375][main][info]["OAuth2WindowManager~onHeadersReceived: Got response details for","https://localhost:5005"]
[1934][1590492436375][main][info]["OAuth2WindowManager~onHeadersReceived: Redirection request to","https://localhost:5005"]
[1934][1590492436375][main][info]["OAuth2WindowManager~startLoginWith - Received redirect on auth login window"]
[1934][1590492436377][main][info]["OAuth2WindowManager~onBeforeRedirect:","https://localhost:5005"]
[1934][1590492436378][main][info]["OAuth2WindowManager~startLoginWith - Received redirect on auth login window"]
[1934][1590492436381][main][info]["OAuth2WindowManager~onHeadersReceived: Got response details for","https://localhost:5005"]
[1934][1590492436382][main][info]["OAuth2WindowManager~startLoginWith - Received redirect on auth login window"]
[1934][1590492436609][main][info]["OAuth2WindowManager~did-navigate:","https://localhost:5005"]
[1934][1590492436609][main][info]["OAuth2WindowManager~startLoginWith - Received redirect on auth login window"]
[1934][1590492436612][main][info]["OAuth2WindowManager~did-fail-load: Error with code ",-3,"","https://localhost:5005"]
[1934][1590492436612][main][info]["OAuth2WindowManager~startLoginWith - Received redirect on auth login window"]
```

I'm not sure what error with code -3 means... but that might be the cause. I am using swagger to authenticate to the same provider on my local machine and it's fine, and able to auth with local versions of the API so the auth server is working and producing valid tokens.

I just cleared out the logs and changed the redirect url in our identityserver and in postman as I was seeing 

`URL did not match the registered callbackURL, so skipping`

But the settings are the exact same as another laptop using the same credentials, and the same version of postman. I've tried both a local redirect url like https://localhost and the original postman one (https://www.getpostman.com/oauth2/callback) (which the other laptop is configured to use) and updated them both in postman and the identity provider 

I've got the SSL validation off, but that didn't make a difference.

![image](https://user-images.githubusercontent.com/1053345/82896113-4a88d100-9f4d-11ea-9fa9-ecc853974cf7.png)

Usually this just works and I get a valid auth token. The exact same code and auth are working on another laptop sitting right beside me.

**Comment by vikiCoder** [comment] 2020-05-27 06:21
Hi @markmcgookin,

Can you please post a screen recording of the issue so we can understand clearly what is happening? 

And I would suggest you to try the new `Authorize using browser` option to unblock you while we investigate the issue. See [this comment](https://github.com/postmanlabs/postman-app-support/issues/8059#issuecomment-626274349) for more details about the option.

**Comment by markmcgookin** [comment] 2020-05-27 07:48
> Hi @markmcgookin,
> 
> Can you please post a screen recording of the issue so we can understand clearly what is happening?
> 
> And I would suggest you to try the new `Authorize using browser` option to unblock you while we investigate the issue. See [this comment](https://github.com/postmanlabs/postman-app-support/issues/8059#issuecomment-626274349) for more details about the option.

Hey ... yeah, here you go, sorry for the delay, had to generate some new ids to hide some stuff (nothing sensitive there, but can't be too careful.) also had to figure out how to blur some logos etc. and upload this! [Here is a video](https://youtu.be/yL8T70MGElU) showing me typing in a username and password in regular postman, and the popup just comes right back. Then into canary on the right, same exact settings, same username and password, same url, it just generates the token as expected.

**Comment by mohitranka** [comment] 2020-06-23 09:46
Hi @markmcgookin , If it is not too much trouble, can you please upgrade to the latest stable version of the application and confirm if the issue still exists?

**Comment by mohitranka** [comment] 2020-07-13 06:44
Closing the issue as we were not able to reproduce it locally. @markmcgookin, if the issue still exists in the latest version of the application, feel free to reopen the issue.

**Closed as completed by mohitranka** 2020-07-13 06:44 UTC
Labels: bug, Auth, OAuth2, product/runtime
