### ISSUE TITLE
Switching environments by collection item.

### ISSUE THREAD

**Issue by bayramucuncu** [a85/POSTMan-Chrome-Extension#8202] opened 2020-03-20 09:29 UTC
**My feature request is about switching between environments?**
I have created multiple Envionments and Collection folders on my postman. But these are does not related. So when I wanted to test a request from another collection, I can forget change the Environment. So i think, something is going wrong. But environment change forgotten.

**My advice**
When a user clicked a link in a collection for send request, the environment should automatically change to related environment. (I could not find a solution using google searches.)

**Comment by vvs11** [comment] 2020-03-21 11:14
Hi @bayramucuncu, this looks a very valid feature request. Could you let us know how you organize your environments and collections so that we can design a better solution for you?

**Comment by bayramucuncu** [comment] 2020-03-22 10:52
@vvs11 How can I let you know my env. and collections?

**Comment by vvs11** [comment] 2020-03-30 14:51
@bayramucuncu I am interested in knowing how you organize requests in collections and how do you use environments in your workflow

**Comment by vvs11** [comment] 2020-03-30 14:52
Duplicate of #6622

**Comment by giridharvc7** [comment] 2021-04-14 08:11
Also a duplicate of #1256. Closing this to track it in a single place

**Closed as completed by giridharvc7** 2021-04-14 08:11 UTC
Labels: feature, Environments, product/runtime
