### ISSUE TITLE
clear  history error

### ISSUE THREAD

**Issue by Daiqiangdeveloper** [a85/POSTMan-Chrome-Extension#6440] opened 2019-05-08 03:13 UTC
**Describe the bug**
![dedddd](https://user-images.githubusercontent.com/19928030/57346730-4511ea80-7182-11e9-94be-9f8dc14072f4.png)

**To Reproduce**
Steps to reproduce the b
![dedddd](https://user-images.githubusercontent.com/19928030/57346206-40e4cd80-7180-11e9-8d93-e5182f91ba68.png)
ehavior:
1. Go to 'History'
2. Click on arbitratry day cache
3. Click on 'delete'
What the fuck error, so stupid, hamper my work, fuck

**Expected behavior**
clear history http request cache

**Screenshots**
...

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment] 2019-05-08 03:29
Duplicate of #6378

**Closed as completed by numaanashraf** 2019-05-08 03:29 UTC
