### ISSUE TITLE
Configured client cert not attached to requests

### ISSUE THREAD

**Issue by chris-jansson** [a85/POSTMan-Chrome-Extension#7368] opened 2019-09-20 14:06 UTC
# Description
This is similar to [#3434](https://github.com/postmanlabs/postman-app-support/issues/3434), but I have to specify the port since I'm not using 443.

I'm calling an internal API that requires client authentication, so I've added my client cert to Postman. The cert and key files are in .crt and .key format, based on the Postman [docs](https://learning.getpostman.com/docs/postman/sending_api_requests/certificates/).

# Steps to Reproduce
1. Add client certificate details in Settings window
2. Send request
3. View console logs
4. See that certificate was not sent

# Expected Behavior
I expect Postman to attach my client cert to the request

# Screenshots
![image](https://user-images.githubusercontent.com/30248918/65333113-803b1600-db85-11e9-9677-e961502f6e9b.png)
![image](https://user-images.githubusercontent.com/30248918/65333153-91842280-db85-11e9-9983-6df3eae364ce.png)
![image](https://user-images.githubusercontent.com/30248918/65333164-93e67c80-db85-11e9-8e38-b7e17fddd482.png)

# App information
 - Native app
 - Postman 7.7.2
 - macOS Mojave 10.14.5]

**Comment by xxxxpenny** [comment] 2019-11-06 03:37
yes，I hava some problm, I use port 443, it works, but if port is not 443, it does not work.

**Comment by vikiCoder** [comment] 2020-03-17 12:08
Hi @chris-jansson, @xxxxpenny 

I tried to reproduce the problem with a local https server running on port 3000. It seems to be working fine for me. See the below screen recording in which I add a client certificate for `https://localhost:3000` and then send a request to `https://localhost:3000/foo` which sends the certificate as expected and gets the 200 response. After that, I remove the client certificate and send the same request again (which fails because the certificate was removed).

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/16588032/76854595-6436d980-6875-11ea-906f-7aa9cf0abb7f.gif)

Please update to the latest Postman app (v7.20.1) and see if it is happening for you or not. If the problem is still there, please share some more info about the server/endpoint you are trying to hit and a scaled-down version of your collection so that we can reproduce it at our end.

**Comment by chris-jansson** [comment] 2020-03-23 13:29
@vikiCoder thanks for looking into it. I think the issue is network connectivity, not Postman. I'm happy to close, unless you are still resolving @xxxxpenny 's issue

**Comment by saswatds** [comment] 2020-03-26 10:52
I will be closing this now. 
@xxxxpenny if you are still facing the issue, it would be more helpful if you could create a new issue with steps to reproduce and a detailed explanation of the issue for us to understand the problem better.

**Closed as completed by saswatds** 2020-03-26 10:52 UTC
Labels: bug, client-certificates, product/runtime, blocked/need-repro
