### ISSUE TITLE
Postman does not show compressed size after gzip compression

### ISSUE THREAD

**Issue by vaibhavpacharya** [a85/POSTMan-Chrome-Extension#8871] opened 2020-08-01 19:30 UTC
**Describe the bug**
After enabling compression, postman does not display compressed json size. Looks like it unzips the response automatically.
Able to see compressed json size in insomnia 
**To Reproduce**
1. Add compression module in express app. 
const compression = require("compression");
app.use(compression({ threshold: 0 }));
**Expected behavior**
I should be able to see the compressed size in response after adding the above module. 
**Screenshots**
## insomnia_without_compression

![insomnia_without_compression](https://user-images.githubusercontent.com/16417441/89109009-4caa5880-d3f2-11ea-8eb2-77138f8b813f.jpg)
## postman_without_compression

<img width="836" alt="postman_without_compression" src="https://user-images.githubusercontent.com/16417441/89109001-36040180-d3f2-11ea-8c9a-cde5d0c87fa9.png">

## postman_with_compression

<img width="838" alt="postman_with_compression" src="https://user-images.githubusercontent.com/16417441/89109025-6481dc80-d3f2-11ea-9283-c86e049e2d21.png">

## insomnia_with_compression

![insomnia_with_compression](https://user-images.githubusercontent.com/16417441/89109038-7a8f9d00-d3f2-11ea-92c0-4efa37db168f.jpg)

**Additional context**
1. postman without compression - 1.75kb
2. Insomnia without compression - 1.65kb
3. postman with compression - 1.8kb
4. insomnia with compression - 790 bytes

**Comment by mohitranka** [comment] 2020-08-03 17:55
Duplicate of Show #7596

**Comment by mohitranka** [comment] 2020-08-03 17:55
Duplicate of Show #7596

**Comment by mohitranka** [comment] 2020-08-03 17:56
Duplicate of #7596

**Closed as completed** 2020-08-03 17:56 UTC
Labels: feature, product/runtime
