### ISSUE TITLE
Can't change request type.

### ISSUE THREAD

**Issue by forwebtrash1** [a85/POSTMan-Chrome-Extension#1080] opened 2015-05-28 11:06 UTC
After 3.0.4 update i can't change request type(verb). It just doesn't change from drop-down list.

**Comment by abhijitkane** [comment] 2015-05-28 11:11
Are you using Windows?

**Comment by forwebtrash1** [comment] 2015-05-28 11:20
OS: Windows 8.1
Chrome: 43.0.2357.81 m

**Comment by abhijitkane** [comment] 2015-05-28 11:21
Can you try executing the following statement in your DevTools console and see if it resolves the issue:
`$(".request-method-dropdown").css('z-index','990');`
One user suggested this fix, though we're not able to reproduce it on Windows or OSX.
If it works, let me know and we'll push an update ASAP.

**Comment by forwebtrash1** [comment] 2015-05-28 11:28
Looks like it fix the problem. At least i can really select another verb from dropdown list.

**Comment by ywilkof** [comment] 2015-06-01 14:47
I experience the same problem with Ubuntu 15.04
Chrome: 42.0.2311.135 (64-bit)

**Comment by abhijitkane** [comment] 2015-06-01 16:45
@ywilkof Have you tried the `$(".request-method-dropdown").css('z-index','990');` fix? We'll be pushing this in the next release.

**Comment by KE-Cbu** [comment] 2015-06-03 10:30
I experience the same problem win Win8 and Chrome 43.0.2357.81 m
The Javascript Command line resolved it, Please push it :)

**Comment by sp72** [comment] 2015-06-03 16:46
@abhijitkane How to run your command `$(".request-method-dropdown").css('z-index','990');` in the packaged app ? Thanks.

Chrome 43.0.2357.81 (64-bit) on Ubuntu 14.04

**Comment by abhijitkane** [comment] 2015-06-03 16:47
You can enable DevTools (http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/), go to the console tab, and execute the statement.

**Comment by sp72** [comment] 2015-06-03 16:50
@abhijitkane Many thanks, it works perfectly.

**Comment by kdelmonte** [comment] 2015-06-08 15:35
I am having the same issue on the packaged app.

**Comment by redwebs** [comment] 2015-06-11 21:44
I'm using Windows 8.1 and had the same problem.  The $(".request-method-dropdown").css('z-index','990'); command worked for me.

**Comment by dpweberza** [comment] 2015-06-17 12:40
When will this be fixed???

**Comment by redwebs** [comment] 2015-06-17 16:57
The fix works, but you have to do it every time your system is rebooted.  Quite a hassle.  Is there a way in Postman to check for the update?

**Comment by KE-Cbu** [comment] 2015-06-18 06:43
I uninstalled and reinstalled and it works

**Comment by a85** [comment] 2015-06-30 00:41
This should be fixed in the latest Postman version. 3.0.0.10+

**Closed as completed by a85** 2015-06-30 00:41 UTC
Labels: bug
