### ISSUE TITLE
Postman won't connect to cloud behind proxy on Linux

### ISSUE THREAD

**Issue by aapablaza** [a85/POSTMan-Chrome-Extension#6978] opened 2019-07-22 21:55 UTC
**Description**
Postman connect to cloud behind proxy in Ubuntu. 

**Affected**
-Postman Cloud connection
-APIs Beta ("No internet connection")

**To Reproduce**
1. Must be behind a proxy network 
2. On Ubuntu or similar (should happen on Linux Mint too)
2. Install Postman by either snap, apt-get or by tar.
3. Configure global environment proxy variables by edit the /etc/environment and configure the network proxy settings. 
4. Open Postman and try to login to cloud or to APIs.

**Expected behavior**
Should connect to postman cloud or APIs. Instead it won't connect, so you can't download Collections, environments, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/13614842/61667591-62962100-aca8-11e9-94b0-45c694bc7ded.png)
![image](https://user-images.githubusercontent.com/13614842/61667614-6de94c80-aca8-11e9-8058-224ad4bc9583.png)

**App information:**
 - App Type: desktop
 - Postman Version: 7.2.0
 - OS: tested on Ubuntu 18.04 and 19.04

**Additional context**
- Network proxy settings filled
- Global enviroments set on /etc/environment :
```
https_proxy=http://XXX.XXX.XXX.XXX:PPPP/
http_proxy=http://XXX.XXX.XXX.XXX:PPPP/
all_proxy=socks://XXX.XXX.XXX.XXX:PPPP/
ftp_proxy=http://XXX.XXX.XXX.XXX:PPPP/
no_proxy=localhost,127.0.0.0/8,::1,others1,others2
```

**Comment by aapablaza** [comment] 2019-07-30 17:06
Also, if proxy settings are set on env variables (/etc/environment), both the "no_proxy" env variable and the Postman built in proxy settings, won't work. 
I mean, **if http_proxy is set on env variables, Postman will ALWAYS use it**, despite the fact there is a no_proxy env variable, plus Postman's "Use System Proxy" disabled (as shown in the image).

![image](https://user-images.githubusercontent.com/13614842/62149891-c46b1200-b2ca-11e9-9362-e77fd8d3ff69.png)

**Comment by numaanashraf** [comment] 2019-08-02 08:51
@aapablaza We are tracking this at #3450. If your proxy doesn't need authentication, could you try launching Postman with these flags?
```
./Postman --proxy-server=address:port
```

**Comment by numaanashraf** [comment] 2019-08-02 08:51
Duplicate of #3450

**Closed as completed by numaanashraf** 2019-08-02 08:51 UTC
