### ISSUE TITLE
Postman not detecting automatically the data file type and iterations when a data file is selected from collection runner

### ISSUE THREAD

**Issue by mahi8321** [a85/POSTMan-Chrome-Extension#7121] opened 2019-08-15 13:18 UTC
**Describe the bug**
When running tests from collection runner and select a data file the type is not auto detecting the format and the number of iterations as well

**To Reproduce**
1. Go to Collection Runner
2. Click on select file for Data and select a csv file

**Expected behavior**
After select a csv file the data file type format should come and it should be auto selected to text/csv but this is not happening and also the Iterations also need to be updated to a number.
![Data File](https://user-images.githubusercontent.com/21227209/63097218-66dbf400-bf5f-11e9-9bb7-15dcb24ac00c.PNG)

**Screenshots**

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.5.0
 - Windows Server 2016 - 

**Additional context**

**Comment by ritwijsinha** [comment] 2019-08-19 08:53
Duplicate of #7008

**Closed as completed** 2019-08-19 08:53 UTC
Labels: bug, collection-runner, data-file, product/runtime
