### ISSUE TITLE
Headers with names like 'X-Date' are silently dropped if User-Agent and Accept-Encoding headers are included in the same request

### ISSUE THREAD

**Issue by schmod** [a85/POSTMan-Chrome-Extension#2329] opened 2016-09-15 21:38 UTC
Hi,

So, I've got a rather strange issue.

If I make a request from Postman that includes a HTTP header named `X-Date`, **this header is silently dropped from the request if `User-Agent` and `Accept-Encoding` headers are also included in the same request.**

Including other standard headers like `Cookie` or `Cache-Control` do not seem to trigger this behavior.  Similarly, `User-Agent` _and_ `Accept-Encoding` do not trigger this issue on their own -- the `X-Date` header is only dropped when **both** `User-Agent` and `Accept-Encoding` headers are included in the same request.

This same behavior occurs if the header is named `X-Dat` or `X-Datee`.  Other permutations such as `X-Da`, `X-Dateee`, and `X-Late` are _not_ affected.

This problem only appears when the Interceptor is enabled. 

I've observed this behavior on my own HTTP server, and have replicated it on [httpbin's header-repeater tool](https://httpbin.org/headers).

---

The Chrome App console shows nothing strange (cropped to redact my Postman Sync access token):
![console](https://cloud.githubusercontent.com/assets/1102667/18567831/e92fef2c-7b67-11e6-9683-a5424bf33dda.png)

The Interceptor's Network Inspector clearly shows that the `X-Date` header was not included in the request:
![network inspector](https://cloud.githubusercontent.com/assets/1102667/18567830/e92fd2d0-7b67-11e6-80bb-4c0c6922da6a.png)

cURL works fine:
![curl](https://cloud.githubusercontent.com/assets/1102667/18567829/e92f4716-7b67-11e6-992c-5728d6a6529f.png)

GIFs are cool, right?
![movie](https://cloud.githubusercontent.com/assets/1102667/18568013/f2d27aee-7b68-11e6-903c-91d173e50bf7.gif)

---

Postman 4.7.1
OS X / x86-64
Chrome 53.0.2785.116

---

Thank you in advance!

**Comment by shamasis** [comment] 2016-09-17 06:47
Aha. Let me do some digging and get back to you.

**Comment by shamasis** [comment] 2016-10-30 16:13
Can you try this in native client? Seems to me that this is a restriction ok chrome platform.

**Comment by shamasis** [comment] 2016-11-16 06:36
Hi,

Any update on this? I was not able to reproduce this without more information. Closing it. Please feel free to reopen if you're still facing the issue.

**Closed as completed by shamasis** 2016-11-16 06:36 UTC
