### ISSUE TITLE
App shows splash screen but never actually opens

### ISSUE THREAD

**Issue by manoadamro** [a85/POSTMan-Chrome-Extension#4984] opened 2018-08-07 12:45 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I run the app, I get the splash screen, that goes, then nothing.

The Icon is in my launcher and has a dot below it as if it is running, but the window is not on any of my monitors or desktops. (I have checked all of the virtual desktops on all my monitors)

I have tried:
- right click -> hide/show but it does nothing
- re-running it (several times)
- re installing (twice)

**To Reproduce**
Start the app on OSX

**Expected behavior**
I would have expected to see the GUI

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: Version 6.0.10 (6.0.10)
- MacOS 10.12.6 (16G1510)
   2.2 GHz Intel Core i7
   16 GB 1600 MHz DDR3

**Additional context**
I can't really show it with screen shots, but I have a screen recording if you need that

**Comment by thecuriousdev** [comment] 2018-08-07 13:16
Hey @manoadamro thanks for reporting this. Please help me with some additional information,
1. Are you opening the app for the first time?
2. Is the Postman window is visible in mission control view?
3. Please share the console logs, ( you can open the console from the menu, View -> Developer -> Show DevTools Shared, and Show DevTools Current View)

**Comment by victorcunya** [comment] 2018-08-07 15:49
![image](https://user-images.githubusercontent.com/5834885/43786953-7e5f48ee-9a2f-11e8-94d8-a04ad033afff.png)

**Comment by kamalaknn** [comment] 2018-08-07 15:59
Hey @victorcunya This seems to be duplicate of #4897

Can you try the workaround suggested in the parent thread?

**Comment by victorcunya** [comment] 2018-08-07 16:10
Yes, I resolved it by Clear Storage - Clear Data.
Thanks @kamalaknn

**Comment by manoadamro** [comment] 2018-08-07 17:20
@thecuriousdev Since this was closed before I had a chance to answer your questions, I'll keep an eye on that parent thread for updates. (although I'm not sure it is a duplicate, since the solutions posted there didn't help).
I have a backup so I'm in no rush

**Comment by kamalaknn** [comment] 2018-08-29 10:59
Hey @manoadamro 

It looks like your issue is not the same as @victorcunya which was a duplicate of #4897].

I'm reopening this issue. Can you attach the error logs that you see, so we can investigate?

**Closed as completed** 2018-08-31 14:18 UTC
