### ISSUE TITLE
Uncomment shortcut also uppercase everything

### ISSUE THREAD

**Issue by nelsonprsousa** [a85/POSTMan-Chrome-Extension#10305] opened 2021-09-18 01:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Ctrl + K -> Comment selected lines
Ctrl + K + U -> Uncomment selected line BUT also uppercase everything's selected.

### Steps To Reproduce

1. Select some piece of code that you want to comment
2. Ctrl + K to comment
3. Ctrl + K + U to uncomment (+ uppercase everything)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/8364345/133867673-ed941cfd-0dd4-4ef6-825d-3c7b6565d61e.png)
![image](https://user-images.githubusercontent.com/8364345/133867681-86c06b45-c79b-4d32-87b6-2d72c34a483b.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.0.2
```

**Comment by timbochamp** [comment] 2021-09-20 00:17
Duplicate of #9114

**Closed as completed by timbochamp** 2021-09-20 00:17 UTC
