### ISSUE TITLE
Variables used for Basic Auth's username/password fields don't get replaced

### ISSUE THREAD

**Issue by trevordunn** [a85/POSTMan-Chrome-Extension#11243] opened 2022-09-06 18:17 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using variables for Basic Auth in requests or collection Authorization settings, they don't get replaced with the variable's value, but get used as the literal username/password.

### Steps To Reproduce

1. Create a new collection and add `username` and `password` variables to it. Give them values of `foo` and `bar` (for example).
2. Go to the collection's Authorization tab, select "Basic Auth" and add `{{username}}` and `{{password}}` for their respective fields. They should highlight orange, which implies that they're going to get replaced with the variable values.
3. Create a new request and check out any of the code snippets (e.g. cURL). Notice that the Authorization Basic token outputted is the base 64 version of `{{username}}:{{password}}` instead of `foo:bar`.

If it's expected that variables can't be used and replaced in the Basic Auth username/password fields, then I would expect them not to get highlighted orange.

### Operating System

macOS

### Postman Version

9.30.3

### Postman Platform

Postman App

**Comment by DannyDainton** [comment] 2022-09-06 18:31
Hey @trevordunn

Can you provide some visual examples of what you're seeing in the UI, please?

It make it easier for us to _see_ what's in front of you and investigate any issues.

**Comment by trevordunn** [comment] 2022-09-06 19:51
Sure. The steps are pretty simple, but here's a screen recording:
https://user-images.githubusercontent.com/1427463/188725809-05e2c216-7b2e-45ef-824b-960d905dab83.mov

**Comment by DannyDainton** [comment] 2022-09-06 21:28
Appreciate you creating that, might be simple but we might notice different things when seeing it. 

As none of those things (Collection/Request) are saved, what happens when you save them?

**Comment by DannyDainton** [comment] 2022-09-06 21:31
This actually looks like a duplicate of an open issue

https://github.com/postmanlabs/postman-app-support/issues/10734

**Comment by trevordunn** [comment] 2022-09-06 21:34
Saving doesn't change anything. The bug still persists.

**Comment by trevordunn** [comment] 2022-09-06 21:34
And yeah, looks like it is a duplicate of #10734

**Comment by DannyDainton** [comment] 2022-09-06 21:38
I'm going to close this one and track everything over there to keep the information in a single place.

Thanks for reporting!!

**Closed as completed** 2022-09-06 21:38 UTC
