### ISSUE TITLE
The window app auto installs to C drive

### ISSUE THREAD

**Issue by akash-shrestha** [a85/POSTMan-Chrome-Extension#9002] opened 2020-08-31 05:10 UTC
When i install the postman app in windows machine. It auto installs to my C drive

**Comment by DannyDainton** [comment] 2020-08-31 07:03
Hey @akash-shrestha 

In order for us to take a look at this, we will need more details about your environment and. the version of Postman.

How are are you installing the version on your machine, via our downloads option on the website, via the update option in the app, a 3rd party package manager, etc?

Could you also provide some screenshots of what you're currently seeing, please?

**Comment by jviotti** [comment] 2022-01-19 16:24
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/10458

**Closed as completed by jviotti** 2022-01-19 16:24 UTC
Labels: feature, platform/windows, product/desktop-foundation, component/installers
