### ISSUE TITLE
Turning interceptor on breaks collection runner

### ISSUE THREAD

**Issue by rayjezek** [a85/POSTMan-Chrome-Extension#1092] opened 2015-05-29 21:10 UTC
Version 3.0.0.5 (packaged) 

If I turn interceptor ON I can step through each request in my collection manually and it works fine. If you try and use the collection runner  on this same collection it just hangs forever. :-1:  To verify this, I just turned Interceptor off and the collection runner works.  

However, in order for my tests/requests to work I need interceptor turned on and working with the collection runner.

**Comment by abhijitkane** [comment] 2015-05-30 05:38
@rayjezek We're not able to reproduce this. Can you check if you're seeing any errors in the collection runner's console? (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ - Right click in the collection runner > Inspect element > Console).

If there's no error, can you try running a simple collection with 1 request in the collection runner with the interceptor enabled?

**Comment by rayjezek** [comment] 2015-05-30 13:34
When I start the runner I get these errors/messages in the console. I get these exact same messages if interceptor is on or off. 

(error) Uncaught ReferenceError: postman_ga_tracking_id is not defined
Initialized ThemeManager
Open latest DB
Initialize interceptor
(error) unload is not available in packaged apps.

When I run the collection it just hangs with this message in the console:
Sending request message d3066f92-16ca-257e-9669-616e1aa5abb4

When I run the runner with interceptor turned off I never see a "sending request" message and it works.

I made a brand new collection and put one rest POST request in it and it did the same thing. It also happens on my mac and my windows machine.

Chrome version is 43.0.2357.81 (64-bit)

**Comment by CWftw** [comment] 2015-06-03 19:30
I am having the same issue. I am not able to run any collections with the interceptor on. Same errors in the console, same version of Chrome.

**Comment by ecozoic** [comment] 2015-06-19 17:16
Same problem here. W/ Interceptor turned on all my requests hang forever. Every once in a while a request will go through (usually first couple requests after I restart my machine) and then they all hang. Using 3.0 postman w/ latest version of Interceptor

**Comment by CWftw** [comment] 2015-06-19 19:06
@johnnn-mitchell I was recommended to uninstall Postman and install the latest version from the Chrome Web Store (3.0.0.6) which fixes the issue for me.

**Comment by abhijitkane** [comment] 2015-07-16 09:25
@johnnn-mitchell @rayjezek Can you confirm this fixed in v3.0.4?

**Comment by ecozoic** [comment] 2015-07-16 13:44
Yes I updated/re-installed, restarted my PC and everything is working fine
for me. Thanks!

**Comment by rayjezek** [comment] 2015-07-16 16:01
yep works like a charm now!
thanks!

**Closed as completed** 2015-07-16 16:32 UTC
Labels: bug
