### ISSUE TITLE
Runner: Collection and Environment are deselected. 

### ISSUE THREAD

**Issue by cebor** [a85/POSTMan-Chrome-Extension#3887] opened 2017-12-01 09:59 UTC
## App Details:

```
Postman for Mac
Version 5.4.0 (5.4.0)
macOS High Sierra
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
      since 5.3
 2. Expected behaviour: 
      If i click the "RUN" Button in a collection menu, then the collection and the current active environment should be selected in the runner. 
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
<img width="467" alt="screen shot 2017-12-01 at 10 58 09" src="https://user-images.githubusercontent.com/1576120/33477618-918a377a-d686-11e7-9529-a5eef95b18ba.png">

**Comment by sdnts** [comment] 2017-12-01 12:22
Hi @cebor, I'm unable to reproduce this. Just to confirm, this is the `Run` button you're referring to, correct?
<img width="413" alt="screenshot 2017-12-01 17 51 53" src="https://user-images.githubusercontent.com/7689783/33482703-56b9e0c0-d6c0-11e7-9277-06a83dd6f314.png">

**Comment by cebor** [comment] 2017-12-01 13:03
@madebysid yes, my looks little bit different, but i think its the same.

<img width="897" alt="screen shot 2017-12-01 at 13 51 34" src="https://user-images.githubusercontent.com/1576120/33483914-6da4a362-d6a0-11e7-809f-75ccb968d1a6.png">

**Comment by cebor** [comment] 2017-12-01 13:13
Have this issue on 3 machines (osx / windows 7)

On Windows the collection is selected but the environment not.

**Comment by mstaalesen** [comment] 2017-12-06 09:27
Linux: Environment is set, Click on the ">" on the collection, choose 'Run' from the dialog that appears. Runner is started: Environment (inside the runner) is reset to "No Environment".

Postman-Linux version: 5.4.1

**Comment by cebor** [comment] 2017-12-10 21:25
Issue still in `5.5.0`

**Comment by miguelhughes** [comment] 2017-12-15 18:31
I also have this on postman 5.5.0
macOS sierra 10.13.2
Chrome 63.0.3239.84
Neither environment nor collection are selected when pressing the "run" button

Updated chrome to 63.0.3239.108, and relaunched postman and chrome: same behaviour

**Comment by polydoreplasden** [comment] 2018-01-09 09:57
We are seeing this issue also, previously reported under https://github.com/postmanlabs/postman-app-support/issues/3916

**Comment by mtoothman** [comment] 2018-01-19 16:38
FWIW, same issue with
Version 5.5.0 (5.5.0)
macOS 10.13.2 (High Sierra, not Sierra as reported above)
Neither environment nor collection are selected when pressing the "run" button

**Comment by harryi3t** [comment] 2018-02-17 10:00
Update:
This has been fixed internally and should be available in the next release 🎉

**Comment by sivcan** [comment] 2018-03-16 20:00
This has been fixed in our latest postman release. [Download Postman 6](https://www.getpostman.com/apps)
Kindly check and if you're still experiencing the same issue then feel free to reopen this.

**Closed as completed by sivcan** 2018-03-16 20:00 UTC
