### ISSUE TITLE
Feature request: Add Fetch API to the list of generated js code

### ISSUE THREAD

**Issue by melnikaite** [a85/POSTMan-Chrome-Extension#3695] opened 2017-10-30 09:03 UTC
Fetch API documentation https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by prashantagarwal** [comment] 2017-10-30 10:19
@melnikaite closing this as duplicate of #2724

**Closed as completed by prashantagarwal** 2017-10-30 10:19 UTC
