### ISSUE TITLE
Make requests to re-attach to last used environment when selected

### ISSUE THREAD

**Issue by onacit** [a85/POSTMan-Chrome-Extension#6622] opened 2019-05-30 08:33 UTC
I defined many collections for each remote services and related environments for them.

When I change from Collection[A]/Request[A] to Collection[B]/Request[B],
the environment stays and I have to change it.

Is it possible to make each request re-attache to the related/last environment used?

**Comment by shamasis** [comment] 2019-05-31 07:26
Yes. We have plans to improve this workflow. There has been some rounds of discussions. But nothing finalised yet. Stay tuned and I will update here when something comes up.

**Comment by giridharvc7** [comment] 2021-04-14 08:11
Duplicate of #1256. 
Closing this to track it in a single place

**Closed as completed by giridharvc7** 2021-04-14 08:11 UTC
Labels: feature, product/runtime
