### ISSUE TITLE
Black screen appearing while trying to open Canary version

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#7737] opened 2019-12-04 10:19 UTC
**Describe the bug**
Getting black screen while trying to open Postman Canary

**To Reproduce**
After clicking on the Postman Canary app, the app is showing a black screen

**Expected behavior**
Postman Canary should open

**Screenshots**
<img width="924" alt="Screenshot 2019-12-04 at 3 43 24 PM" src="https://user-images.githubusercontent.com/41741228/70133805-d875b480-16ac-11ea-8ae2-1829d43535d2.png">

**App information (please complete the following information):**
 - App Type [Canary]
 - Postman Version [7.13]
 - OS: [Windows]

**Comment by kamalaknn** [comment] 2019-12-04 11:19
Duplicate of #7078

**Closed as completed by kamalaknn** 2019-12-04 11:19 UTC
