### ISSUE TITLE
Request exists in App but not in Sync

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#6145] opened 2019-03-25 08:42 UTC
**Describe the bug**
I have a collection which has three requests, R1, R2, R3. R1 does not exist on sync because I cannot see it on the web.

**To Reproduce**
This needs to be done while the app is actively syncing:

1. Create new collection
2. Click on the context menu for the collection in the sidebar, add a request
3. Open the new request R1, add a URL, and save it
4. Wait for syncing to complete
5. Duplicate the request to create R2
6. Click on "View in web" in the flyout for this collection
7. Only R2 shows up on the web
8. Head back to the app, and open the console to see requests to Sync
9. Open R1, edit something, and save it to trigger an update to Sync
10. App sends request to Sync, gets an error: 

```
message: "We could not find the request you are looking for"
name: "instanceNotFoundError"
```

**Expected behavior**
All requests within the collection should show up on the web as well, once syncing is complete.

**App information (please complete the following information):**
Postman for Mac
Version 7.0.6
OS X 18.2.0 / x64

**Comment by sankalp0o** [comment] 2019-07-30 08:06
@godfrzero Closing this as the team is not able to reproduce this. Please reopen if you are able to still see this.

**Closed as completed by sankalp0o** 2019-07-30 08:06 UTC
Labels: bug, sync
