### ISSUE TITLE
Support chinese and other feature requests

### ISSUE THREAD

**Issue by xujialiang** [a85/POSTMan-Chrome-Extension#1936] opened 2016-03-26 10:54 UTC
1.Environments should auto switch by collections.
2.If I Share a collection,the environment should be shared automatically.
3.Not Support Chinese?My Login Name can't be display correct.
4.Runner , not all the api I want to run, I think I could choose what apis to run, without create a new collection.
5.I want to group my Collections.
6.When I switch from x-www-form-urlencoded to form-data, it should copy key-value....
7.I want to set environment when did finish call api, but i can only write code in Tests... Can you add a tab Called End-request Script Or After-request Script? or Other name....
8.enviroment preview's layout is terrible....I can't find my key clearly.
9.I like postman!!!!!!

**Comment by a85** [comment] 2016-04-02 08:29
Replies below:
1. Environment auto switching: This is a tricky issue. We don't want coupling between environments and collections but in some cases this is desirable.
2. Again. Same issue. Coupling creates problems.
3. Chinese: We'll fix this. Must be a problem with unicode support.
4. Runner: You can chose either a folder or a collection. We are working on flows to improve this.
5. Grouping collections: Collection is supposed to be the base unit. Collection sorting/ordering will be available in the product soon.
6. Copying key-value pairs: You can use the bulk data editor to transfer values.
7. This is coming as a post-request script soon.
8. Environment preview is getting an overhaul. Will be out soon. :)

**Comment by a85** [comment] 2016-04-02 08:29
For 9. Thank you! :D

**Comment by a85** [comment] 2019-03-10 04:36
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/3126

**Closed as completed by a85** 2019-03-10 04:36 UTC
Labels: feature, i18n
