### ISSUE TITLE
Black Window on Startup

### ISSUE THREAD

**Issue by szahn** [a85/POSTMan-Chrome-Extension#4703] opened 2018-06-14 17:38 UTC
Get black window on application startup. App just hangs. Opening Dev Tools also provides a black windows.

![postman_2018-06-14_10-35-08](https://user-images.githubusercontent.com/271732/41428400-dcc5287c-6fbe-11e8-8be9-6565257ca130.png)
![postman_2018-06-14_10-34-50](https://user-images.githubusercontent.com/271732/41428401-dce329d0-6fbe-11e8-8cf3-462731998261.png)

Tried uninstalling and reinstalled, same problem.

**Comment by sivcan** [comment] 2018-06-15 05:27
@szahn Can you head over to this URL and try the solution provided here:

1. https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates
2. Scroll down to **Troubleshooting Postman Updates**

The latest version of Postman App as of now is **v.6.1.3**

**Comment by szahn** [comment] 2018-06-15 17:33
Setting the "POSTMAN_DISABLE_GPU" environment flag to true did the trick, but it's more of a temporary workaround than a solution. I'd prefer to have GPU acceleration enabled.

**Comment by sivcan** [comment] 2018-06-18 08:49
@szahn Postman native app is built on top of electron and that is based on chromium.
The issue lies with chromium and the support for your GPU.

The issue is not with the Postman app itself hence I'll be closing this ticket.

**Closed as completed by sivcan** 2018-06-18 08:49 UTC

**Comment by DewaldDeJager** [comment] 2018-07-12 13:44
@sivcan I am experiencing this issue in 6.1.4 on Linux 4.14.53-1-MANJARO / x64. It happens intermittently but I can reproduce consistently on some screens such as the login screen (When clicking in an input field).

I have tried using the `POSTMAN_DISABLE_GPU` environment variable and the `--disable-gpu` flag. I have also tested other Electron apps and they work fine. It is just Postman.

Any suggestions on what else I can try?

**Comment by DewaldDeJager** [comment] 2018-07-13 05:22
Another observation: It only happens when the window loses focus.

**Comment by SauceCode84** [comment] 2018-07-30 05:00
@DewaldDeJager 
I'm having the same issue, also on Manjaro. Have you found any sort of solution or perhaps a workaround?

**Comment by DewaldDeJager** [comment] 2018-08-02 06:08
@SauceCode84 I installed the canary version from the AUR and it solved the issue. Not sure what it was.

**Comment by sahalsaad** [comment] 2018-08-09 04:05
I facing the same issue in **manjaro**.
POSTMAN_DISABLE_GPU=true still doesn't fix the problem. 

1. Start postman
2. Go to pre-request script tab
3. Change to another window
4. Come back to postman = black screen

Update:
Fixed by using [postman-bin](https://aur.archlinux.org/packages/postman-bin/).
Problem only happen in [postman](https://aur.archlinux.org/packages/postman/)

**Comment by jvalecillos** [comment] 2018-08-16 10:02
Same issue, still present but slightly different. You can reproduce if I go to **Import -> Paste Raw Text** and then focus on the text area.

Adding `POSTMAN_DISABLE_GPU` environment variable makes no difference.

I have applied the solution suggested by @sahalsaad in Archlinux.

**Comment by AnteroGasalho** [comment] 2018-09-23 14:48
I've installed the 6.3.0 version and I had the same problem "black window".
I create the variable and apparently it works!

**Comment by LaikaFusion** [comment] 2018-10-24 20:32
I can confirm that postman-bin works as @sahalsaad said. I am also on Manjaro (4.14.78-1-MANJARO)

**Comment by lukaszflorczak** [comment] 2018-11-13 11:52
Hi! I have black screen for some time too. I currently have 6.5.2 version. The black screen appears about 2 minutes after the start. I tried `POSTMAN_DISABLE_GPU` but it doesn't work. When the black screen appears, in the terminal is this info:

<img width="1052" alt="zrzut ekranu 2018-11-13 o 12 41 41" src="https://user-images.githubusercontent.com/1818979/48411761-d14ad400-e742-11e8-9048-f01197f9da26.png">

EDIT: I use Mac OS Mojave (10.14).

**Comment by sylann** [comment] 2018-11-22 13:07
I just installed postman (6.5.2) on linux Manjaro and I have the black screen systematically when I try to sign in with google.
It also appears randomly after a tab switch or after about a minute running, but it really is a bit random.
