### ISSUE TITLE
Headers preset list is going up

### ISSUE THREAD

**Issue by jpmo22** [a85/POSTMan-Chrome-Extension#4652] opened 2018-06-05 17:14 UTC
**Describe the bug**
The headers preset list is going up when there are too many presets. I have more than 50 defined.

**To Reproduce**
1. Go to 'Headers' tab
2. Click on 'Presets' dropdown
3. See unwanted behavior

**Expected behavior**
The list should go down and have a scrollbar.

**Screenshots**
![postman-bug-presets](https://user-images.githubusercontent.com/2581941/40991464-3cfb46a0-68ca-11e8-8719-b2d736322789.gif)

**App information (please complete the following information):**
 - Native App
 - Postman for Windows Version 6.1.3
 - OS: win32 10.0.16299 / x64

**Additional context**
If you don't have enough presets defined the bug cannot be seeing.

**Comment by sivcan** [comment] 2018-06-07 08:49
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4649

**Closed as completed by sivcan** 2018-06-07 08:49 UTC
