### ISSUE TITLE
Run same request with new iteration data using setNextRequest

### ISSUE THREAD

**Issue by raghav19** [a85/POSTMan-Chrome-Extension#5196] opened 2018-09-18 01:42 UTC
One of my usecase is that I have to run a specific request in a loop for all the data provided as CSV or JSON and then run the other request in the same folder.

As of by using setNextRequest to the same POST request, it runs for the same iteration data again and not the new data in the json. 

Is there a way to achieve it or what feature is coming up to handle this?

**Comment by sivcan** [comment] 2018-09-18 07:46
I'll close this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/4996, since it's already tagged with a feature request.

**Closed as completed by sivcan** 2018-09-18 07:46 UTC
