### ISSUE TITLE
Postman error:13000077:PKCS8 routines:OPENSSL_internal:UNKNOWN_ALGORITHM

### ISSUE THREAD

**Issue by sothri** [a85/POSTMan-Chrome-Extension#8692] opened 2020-06-22 07:19 UTC
**Describe the bug**
I have used postman for a while. Abruptly it started giving error. I googled to find any previous case and solution. There was no luck. So I am posting the error, wishing to get some help.

Could not send request
Error: error:13000077:PKCS8 routines:OPENSSL_internal:UNKNOWN_ALGORITHM

I did not change any settings which were working.

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment] 2020-06-22 07:22
@sothri It’d be great if you could share this endpoint and request with us at help@postman.com with any additional details like client certificates, if applicable.

**Comment by birnbuazn** [comment] 2020-06-25 14:18
Having the same issue since updating. My endpoint is internal, but if it is of any help: this endpoint requires a (self-signed) client-certificate

**Comment by jviotti** [comment] 2022-01-19 16:17
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/8598

**Closed as completed by jviotti** 2022-01-19 16:17 UTC
Labels: bug, platform/macOS, product/desktop-foundation, version/7, component/boringssl
