### ISSUE TITLE
Add publish capability to API

### ISSUE THREAD

**Issue by vostersc** [a85/POSTMan-Chrome-Extension#3992] opened 2017-12-19 17:09 UTC
Right now I can save my documentation to the postman platform via a POST request. But if I want to publish the docs I can only do so via the manual online interface. It would be great if there was a way to publish via the API!

I'd also appreciate the implementation of a custom css sheet for docs. I am excited that it is on your [roadmap](https://trello.com/c/F8NLGock/13-custom-css-for-docs)!

**Comment by rockywarren-vertex** [comment] 2020-07-25 17:33
This is preventing us from switching to Postman for documentation. We update all of our documentation in our OpenAPI spec. We want a completely automated flow from those spec updates to the docs being updated so we can add it to our CI process. We can use https://github.com/postmanlabs/openapi-to-postman and the Update Collections API to get the collection updated, but still need to manually sign in to publish the docs.

**Comment by Raja-Simha** [comment] 2020-12-14 06:43
Duplicate of #7833

**Closed as completed** 2020-12-14 06:43 UTC
Labels: feature, product/documentation, product/postman-api
