### ISSUE TITLE
Cannot convert schema generated by Hasura to any kind of collection or test, etc.

### ISSUE THREAD

**Issue by seanaguinaga** [a85/POSTMan-Chrome-Extension#8895] opened 2020-08-06 15:07 UTC
The schema.graphql file generated by Hasura is not correctly converted.

This is unfortunate because it blocks an incredibly powerful service from being easily integrated with Postman.

See screenshot for message and attached schema file.

<img width="790" alt="Screen Shot 2020-08-06 at 8 04 02 AM" src="https://user-images.githubusercontent.com/15254340/89548331-bdb78a80-d7bb-11ea-9d97-6f120e680373.png">

[schema.graphql.zip](https://github.com/postmanlabs/postman-app-support/files/5035752/schema.graphql.zip)

**Comment by DannyDainton** [comment] 2020-08-06 15:19
Duplicate of #8863

**Closed as completed by DannyDainton** 2020-08-06 15:19 UTC
