### ISSUE TITLE
Code Snippet indentation settings are inconsistent

### ISSUE THREAD

**Issue by sbettwieser** [a85/POSTMan-Chrome-Extension#11963] opened 2023-04-26 20:41 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Changing the indentation type from "space" to "tab" causes the indentation count setting to change both tab size and number of tabs for several languages (tested JS & Python options so far).

### Steps To Reproduce

1. Open or create a request
2. Open the Code Snippet sidebar
3. Select a JavaScript code option
4. Click the cog to edit the language options
5. Set indentation type to "Tab"
6. Set indentation count to any number
7. Observe that both number of tabs and the tab size (in spaces) have changed to the indentation count

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/110856576/234696567-225c3845-d22e-4ba9-ac2e-90c522e989a4.png)
![image](https://user-images.githubusercontent.com/110856576/234696881-51de085d-c601-445f-865a-4d24ad086367.png)

### Operating System

Windows

### Postman Version

10.13.4

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by VShingala** [comment] 2024-09-27 04:58
@sbettwieser Thanks for reporting the issue! But isn't this expected behaviour? i.e. Changing the indentation settings (type and count) also does change the indentation in generated snippet correctly. i.e. In your example 4 Tabs are indented wherever indentation is needed.

Could you explain more on what exactly the issue is or what's the expected behaviour you were looking for?

**Comment by sbettwieser** [comment] 2024-09-27 15:43
@VShingala Hello, it's been a while since I made this post. I thought I had added more screenshot examples back then, so here you go:

Snippet Settings:
Indentation count: 4
Indentation type: tab
Result: Indentation is 4 tabs of size 4
![image](https://github.com/user-attachments/assets/b5959cd9-9bac-49bb-8eb6-bf7f24cd39d7)

Snippet Settings:
Indentation count: 2
Indentation type: tab
Result: Indentation is 2 tabs of size 2
![image](https://github.com/user-attachments/assets/e7740299-9ab9-4356-8507-3732627efa26)

The script editor works correctly (in my opinion): changing indentation count while using tabs only changes the tab size. It is just the code snippets that are acting weird, changing both.

**Comment by VShingala** [comment] 2024-09-30 06:17
@sbettwieser Thanks for the explanation! It makes sense. Code Snippets seems to also add actual 4 tabs on top of editor making the tab indentation of 4 space. We'll work on fix for this and inform here once it's fixed.

**Comment by aman-v-singh** [comment] 2024-10-07 10:10
This issue will be fixed in the `11.16` version of the Postman App.

**Comment by VShingala** [comment] 2024-10-16 14:01
@sbettwieser This issue has been addressed with latest version of app v11.17. We'll close this issue for now, feel free to reopen it in case if you face any further problems with the fix.

**Closed as completed by VShingala** 2024-10-16 14:01 UTC
Labels: bug, product/codegen
