### ISSUE TITLE
Custom certificates are not trusted even if the root certificate has been installed on Windows

### ISSUE THREAD

**Issue by Fonger** [a85/POSTMan-Chrome-Extension#5088] opened 2018-08-24 08:22 UTC
**Describe the bug**
Custom root certificates installed on the OS root are not trusted by Postman native app

**To Reproduce**
1. Create a custom CA and sign a certificate for the api server. And installed it to the OS root certificate.
2. Use Chrome/IE/Firefox to check the certificate is trusted and valid
3. Use postman, request `GET` and the following message appears:
```
Could not get any response
There was an error connecting to https://xxxxx.com/api/data
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
...
```
4. Go to `Settings` -> `General` -> `SSL Verification` and change it to off
5. Postman successfully get the result.
6. Restart postman doesn't help.

**Expected behavior**
The custom SSL certificate should be trusted once installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5862369/44574155-2f5ac180-a7bb-11e8-868e-8f1d6a5ccc39.png)
![image](https://user-images.githubusercontent.com/5862369/44574184-400b3780-a7bb-11e8-9ee8-729d12dd17aa.png)
![image](https://user-images.githubusercontent.com/5862369/44574267-721c9980-a7bb-11e8-8bae-cb1062f19c8d.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.2.5
 - Windows 10 Enterprise Version 1803 Build 17134.228 x64

**Additional context**

I'm also using Postman 4.2.2 on macOS with the same custom certificate and root certificate installed into Keychain. It works when `SSL certificate verification` is on.

**Comment by numaanashraf** [comment] 2018-08-24 08:52
Duplicate of #3290

**Closed as completed by numaanashraf** 2018-08-24 08:52 UTC
