### ISSUE TITLE
Archived Items in Free Team Account can't be deleted Part 3

### ISSUE THREAD

**Issue by n0v3xx** [a85/POSTMan-Chrome-Extension#6056] opened 2019-03-12 13:08 UTC
Its detailed described here:

https://github.com/postmanlabs/postman-app-support/issues/6054

https://github.com/postmanlabs/postman-app-support/issues/5457

And if you now close the ticket again without a reasonable solution then I switch completely to Insomnia Http Client. Rarely seen such an ignorant development team.

**Comment by numaanashraf** [comment] 2019-03-12 13:47
@n0v3xx We have responded to the original ticket at https://github.com/postmanlabs/postman-app-support/issues/5457#issuecomment-445124182. Feel free to continue this discussion on the original thread as duplicate issues violate the guidelines and will be closed.

You can find the guidelines for reporting issues at https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues

**Comment by numaanashraf** [comment] 2019-03-12 13:48
Duplicate of #5457

**Closed as completed by numaanashraf** 2019-03-12 13:47 UTC
Labels: duplicate

**Comment by n0v3xx** [comment] 2019-03-13 14:28
@numaanashraf nice joke. The original ticket is closed and you dont respond to closed ticket. But ok enjoy your commercial money making feature. I switch to insomnia

**Comment by andersonllda** [comment] 2019-03-20 14:04
The best way is stop to using postman.... that's unbelievable that a simple delete feature cant be done.
If i buy the premium how much things they will not be able to do?
I don´t want this risk.

**Comment by sanderhouttekier** [comment] 2019-04-16 11:37
I understand the problem is partly because they want more premium accounts but can we maybe get a warning when importing a collection or something?
as I had a workspace active which I share with friends, and by accidentally leaving it active while i imported something i wanted in my personal space, now just blocked the entire team as it archives everything. 

I get that you want people to upgrade, but some kind of measure to not put us with our backs against he wall would be nice. either a delete or a warning on import or whatever. anything will help make us a calculated move instead of accidentally blocking an entire team.

**Comment by preethammavin** [comment] 2019-04-16 12:36
@saelfaer We provide a buffer time before we archive and also inform the user of the said warnings in the app, also we are looking the time that user accidentally imports experience. We definitely dont want the user to accidentally to archive the collection.

**Comment by sanderhouttekier** [comment] 2019-04-16 12:51
@preethammavin  i'm sorry but that is not really what I experienced just now
I opened the app, clicked import and choose a collection
next thing I saw was "Some collections were archived because you’ve reached the shared requests limits. Learn more" and the popup showing I reached the monthly sharing limit.

no warning, no way to return, I just had the wrong workspace selected and therefor it archived the 2 collections in that workspace.

**Comment by andersonllda** [comment] 2019-04-16 22:48
> @preethammavin i'm sorry but that is not really what I experienced just now
> I opened the app, clicked import and choose a collection
> next thing I saw was "Some collections were archived because you’ve reached the shared requests limits. Learn more" and the popup showing I reached the monthly sharing limit.
> 
> no warning, no way to return, I just had the wrong workspace selected and therefor it archived the 2 collections in that workspace.

Well man, same here... 
I just give up about PostMan, they just don't listen the comunity.... there are others options, its sad because PostMan is a nice tool i almost buy a premium but i'm afraid about this suport, just take a look in other threads.

**Comment by einSelbst** [comment] 2020-09-26 02:28
> no warning, no way to return, I just had the wrong workspace selected and therefor it archived the 2 collections in that workspace.

Exactly this.

**Comment by benknight** [comment] 2020-12-16 08:06
I have to pile on here and agree that this is very anti-user. It's an inconvenience that "conveniently" nudges free plan users to upgrade. Instead of being able to clean up their workspace and delete the archived collections, they have to deal with these warnings until the end of time. There is a backfire effect here because this sort of friction makes me more unlikely to ever pay for the product.
