### ISSUE TITLE
"Clear All" option in the Manage Cookies modal

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#5250] opened 2018-09-26 05:26 UTC
**Describe the bug**
There is no way to clear all cookies.

**To Reproduce**
1. Click on the `Cookies` link below the URL bar
2. Look around the Manage Cookies modal
3. Realize that you have 99 cookies but no way to clear them

**Expected behavior**
A button somewhere which would allow me to clear *all* cookies.

**App information (please complete the following information):**
Postman for Mac
Version 6.3.0
OS X 18.0.0 / x64

**Comment by kkapell** [comment] 2019-02-05 20:50
This would be very useful. I would add to this request the ability to clear one, multiple, or all cookies programaticly using something in the Pre-Request Script or similar.

**Comment by shamasis** [comment] 2019-03-28 16:06
> This would be very useful. I would add to this request the ability to clear one, multiple, or all cookies programaticly using something in the Pre-Request Script or similar.

@kkapell - indeed it would be useful. Your particular request is being tracked at https://github.com/postmanlabs/postman-app-support/issues/1228#issuecomment-477649059

**Comment by codenirvana** [comment] 2019-04-09 10:06
Duplicate of #5215

**Closed as completed by codenirvana** 2019-04-09 10:06 UTC
Labels: feature, cookies
