### ISSUE TITLE
Pdf Download

### ISSUE THREAD

**Issue by rajmantechnology** [a85/POSTMan-Chrome-Extension#5393] opened 2018-10-20 09:38 UTC
Hello,

When i hit the below code in postman then we get the error. I want to download pdf with data. 
var request = require("request");

var options = { method: 'GET',
  url: 'https://api.fortnox.se/3/invoices/31/preview',
  headers: 
   { 'Postman-Token': 'aa8f701d-e4e0-40fa-836d-a623f8072281',
     'cache-control': 'no-cache',
     'Content-Type': 'application/json',
     'Client-Secret': 'Mz9Yy3QY9I',
     'Access-Token': '' } };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});

%PDF-1.4
%����
3 0 obj
<</Length 1438/Filter/FlateDecode>>stream
x��Y�r�6��+�Ɍ3S�xXڭ�h���IM���STB�n>�_�/p~!�^<H��N�xti���}��T�,��&k��g���xU|*҂�Gk�JPSH#13�װ�).�?�����`�������/���!`~�Ц���$���l?݅���O(���幷���~��Ē��l(Z��0�h��8zR]��]�x����!1�Jy?�fX(�D9&	R���*V"�όvX��Z[�"�f"6����׹�����-�;����um�a%6&�&d�s#�X����,��u�l\���V�ꬫ��l8����RL=���f��zۿ����u=�LRH	9@jL��|zݞ�g+q�u�G�z�����/���������So<����̈p�Km14�> ��
��`��޽����v�^loVMs��=0`�2!�H��Ѧ;���z���$�>��|�Ϋ��d��p#ޏdO��P�栞�75T���
Ύ��u8����a���l����]�g����.%�2�$Ʊ̱M&Nn��>��
�I�.�8�q�E��P�,��/��:�،���3�{>{4
��Ps��RKl���B��A�z�����(^��#*¸�fB�T�)b@�m�ё�ܟyȉԄ]S/D����}�v�����ԲN��.�
�c_8��>��j91�@��P2ۻ�-������I���
ـ�v~^�X)lB�m/��0*�q�J�|I;^|�V�ۊ�����0��|L
X �ba�
������R� xc�:^�DBEq�&b���������C���� S��
��D����\�������`x  ��(���d>a�c�����	Y/"�4�2��|�B@O��+I�r+襘xŰ$K�ե�S�
����`�m�>���[Ty�<R��r"�(N�����8�fB�ˑ��8��hÎ������CN�&욘z!eꅔ�������|E�p�����\����=������f=��2�Q��8�(\��g�p6�6�/��寺�����i�9��������x�D'���g����5׶h�P��uٲhD��x���医y2W{8�ɀ�ؕ2G;'�r��}�ä]�,�P����)��J��l������̛ӧ�q��P\��C�TH�<Uf���A��<����L�b�Z8X��H�nO,<�@j����:uAذo�NDf�&\��������2������1_�=�=]+����3%��QµR��5��7��c?�.��>ߴy8F��²o�>�A@�3��W�m�X|�dLkD�@F.QK����^��ٍ+@j�kOf1���Mc((޷�T��ԗ@7��~��N_�����쩑1{���(��𢻨�ն�W�v;�����yJ����)֫�����?~�x>���l
endstream
endobj
5 0 obj
<</Group<</Type/Group/CS/DeviceRGB/S/Transparency>>/Parent 4 0 R/Contents 3 0 R/Type/Page/Resources<</ProcSet [/PDF /Text /ImageB /ImageC /ImageI]/ColorSpace<</CS/DeviceRGB>>/Font<</F1 1 0 R/F2 2 0 R>>>>/TrimBox[0 0 595.29 841.89]/MediaBox[0 0 595.29 841.89]/BleedBox[0 0 595.29 841.89]>>
endobj
1 0 obj
<</BaseFont/Helvetica-Bold/Type/Font/Encoding/WinAnsiEncoding/Subtype/Type1>>
endobj
2 0 obj
<</BaseFont/Helvetica/Type/Font/Encoding/WinAnsiEncoding/Subtype/Type1>>
endobj
4 0 obj
<</ITXT(2.1.6)/Type/Pages/Count 1/Kids[5 0 R]>>
endobj
6 0 obj
<</Type/Catalog/Lang(en)/Pages 4 0 R>>
endobj
7 0 obj
<</Creator(RealObjects PDFreactor\(R\) 4.0.4491.1, Serial No: 2401, Licensed for: Fortnox AB)/Producer(RealObjects PDFreactor\(R\) 4.0.4491.1, Serial No: 2401, Licensed for: Fortnox AB using iText 2.1.6 by 1T3XT)/Title()/ModDate(D:20181020113559+02'00')/CreationDate(D:20181020113559+02'00')>>
endobj
xref
0 8
0000000000 65535 f 
0000001825 00000 n 
0000001918 00000 n 
0000000015 00000 n 
0000002006 00000 n 
0000001521 00000 n 
0000002069 00000 n 
0000002123 00000 n 
trailer
<</Root 6 0 R/ID [<8c3b521390019cd1e88e9dd68d4edf9d><5e72180379649d349a8e6c9f0d1f063d>]/Info 7 0 R/Size 8>>
startxref
2432
%%EOF

**Comment by sujayvenaik** [comment] 2018-10-22 06:07
Duplicate of #5359

**Comment by sujayvenaik** [comment] 2018-10-22 06:08
Duplicate of #5359

**Closed as completed by sujayvenaik** 2018-10-22 06:07 UTC
Labels: duplicate

**Comment by rajmantechnology** [comment] 2018-10-23 11:36
Hello,


We are using this code to download the pdf file but we are getting problem.
i want when i hit this route then pdf file will download.
But when i hit this api in postman and click on the download button then
pdf file download. So i wnat to download the pdf file with data.

router.get('/demo',function (req,res){
async function getinvoicelist(){

 var chunks = [];
 var options = { method: 'GET',
 url: 'https://api.fortnox.se/3/invoices/31/preview',

request(options, function (error, response, body) {

  console.log(body);

});

Image :1







Please check to solve this problem/
