### ISSUE TITLE
Use checkboxes in the Params section of the URL

### ISSUE THREAD

**Issue by vivek201** [a85/POSTMan-Chrome-Extension#2792] opened 2017-03-09 06:21 UTC
1. Postman Version: Postman for Windows 4.10.3
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows

Feature Request
==
It would be really great if there were checkboxes in the params section just like in the headers sections. Check this [screenshot](http://prntscr.com/ehq6ch)

**Comment by sdnts** [comment] 2017-03-09 12:02
Closing as duplicate of #2519. This is on our radar :)

**Closed as completed by sdnts** 2017-03-09 12:02 UTC
Labels: feature
