### ISSUE TITLE
Ability to add new Code Snippets via template files

### ISSUE THREAD

**Issue by russianryebread** [a85/POSTMan-Chrome-Extension#2569] opened 2016-12-17 18:49 UTC
It would be helpful to have the ability to create templates for the code generator feature.  Sometimes I use projects, such as PHP GuzzleHttp, that are not natively supported by Postman's code generator.  It would be nice to write a custom template file in something template language like Handlebars:

```handlebars
<?php

$client = new GuzzleHttp\Client();
{{#if body}}
  $body = '{{body}}';
{{/if}}
$res = $client->request('{{requestType}}', '{{requestURL}}', [
    'cache-control' => 'no-cache',
    {{#each headers}}
        '{{header.key}}' => '{{header.value}}',
    {{/each}}
]{{#if body}}, $body{{/if}});

echo $res->getBody();

```

**Comment by a85** [comment] 2017-06-27 23:37
@russianryebread Closing as a duplicate of #675. Will be tracking there.

**Closed as completed by a85** 2017-06-27 23:37 UTC
Labels: feature, code-generator
