### ISSUE TITLE
"loosing" should be "losing" in dialogue

### ISSUE THREAD

**Issue by EvilJordan** [a85/POSTMan-Chrome-Extension#5362] opened 2018-10-15 17:52 UTC
![screen shot 2018-10-15 at 1 50 32 pm](https://user-images.githubusercontent.com/1364262/46968579-8f663980-d081-11e8-8935-1d4d0aec406c.png)

**Comment by sujayvenaik** [comment] 2018-10-16 02:23
Duplicate of #5325

**Closed as completed by sujayvenaik** 2018-10-16 02:23 UTC
