### ISSUE TITLE
Import a collection with a tab open - tab doesn't refresh

### ISSUE THREAD

**Issue by connorsadlervelo** [a85/POSTMan-Chrome-Extension#4737] opened 2018-06-27 09:31 UTC
**Describe the bug**
When you import a collection and have a tab open with a request from that collection, the contents of the tab are not updated to show the request you just imported

**To Reproduce**
1. Create a collection with a request and a test script saying "// hello world"
2. Export the collection to a .json file
3. Open the request in postman so you now have a tab open and can see your test script
4. Change the .json file on the disk so the test script says "// hello world version 2" - this simulates a colleague changing the script and you pulling their changes from git
5. Import the .json file into Postman
6. You can still see the old version of the script on your open tab

**Expected behavior**
Either the tab should close or refresh with the newly imported information
I do not know what I'd expect to happen if the tab has unsaved changes.

**App information:**
 - App Type Mac Native
 - Postman Version 6.1.3
 - OS: macOS Sierra 10.12.6

**Comment by SamvelRaja** [comment] 2018-06-27 15:37
@connorsadlervelo  We hope that this is the intended behavior we expect. 
When you mentioned the word import, this means the whole collection and request are been replaced with the new set of requests. But the request which was opened in the tab was the snapshot of the older request you opened.

Kindly let me know if am missing any edge case you have in your mind.

I am closing this now. Feel free to re-open it.

**Closed as completed by SamvelRaja** 2018-06-27 15:37 UTC

**Comment by connorsadlervelo** [comment] 2018-06-27 15:45
I understand what import means and what it does.
That is odd behaviour IMHO, but if you're happy with it then I'll leave it with you.
