### ISSUE TITLE
Implement the concept of a postman project

### ISSUE THREAD

**Issue by singhrajivk** [a85/POSTMan-Chrome-Extension#2389] opened 2016-10-06 16:26 UTC
This is a new feature request in the context of the standalone app  (not the chrome extension).

I have different projects I switch between. To do this currently I do the following:
1. dump the state to a file.
2. clean out all the collections, environments, and globals by deleting them.
3. load a previous state dump corresponding to the new project.

I would be nice to have the concept of a postman project which will allow load, save, and save as of all the state directly to a project file. The project file can be saved and checked into version control with the corresponding code base, as needed.

Thanks.

**Comment by a85** [comment] 2016-11-12 12:46
Closing as duplicate of #2277

**Closed as completed by a85** 2016-11-12 12:46 UTC
Labels: feature
