### ISSUE TITLE
Mutual TLS authentication not working on Windows 10 "socket hangup", 6.7.4 and 7.9.0

### ISSUE THREAD

**Issue by tgulick** [a85/POSTMan-Chrome-Extension#7524] opened 2019-10-24 13:39 UTC
**Describe the bug**
Using a request and client cert/key that work on MacOS and Linux versions of Postman app on Windows 10 results in a connection timeout. Postman console shows the cause to be a "socket hangup". Have tried both 6.7.4 and 7.9.0 on Windows 10 and both show the same behavior. 

Using tcpdump on the target shows the cert that the client sends is either missing (0 length) or corrupted and the target returns an SSL alert "bad certificate" and that's it.

Capture file attached. SSL exchange starts at packet #577

100% repeatable.

**To Reproduce**

**Expected behavior**
Mutual TLS authentication should succeed and a secure channel be established and 

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 -  Native App
 - Postman Version: seen in both 6.7.4 and 7.9.0
 - OS: Windows 10

**Additional context**
Add any other context about the problem here
[bug.zip](https://github.com/postmanlabs/postman-app-support/files/3767787/bug.zip)

**Comment by codenirvana** [comment] 2020-03-12 07:53
Duplicate of #7000

**Closed as completed by codenirvana** 2020-03-12 07:53 UTC
Labels: bug, request-sending, tls, product/runtime

**Comment by tgulick** [comment] 2020-03-12 14:46
this was a Windows 10 specific bug and didn't work with any version of Postman we had. Looks different than https://github.com/postmanlabs/postman-app-support/issues/7000.

**Comment by codenirvana** [comment] 2020-03-12 19:26
@tgulick Can you please share the steps to reproduce this particular issue?
Steps to generate the certs and with the local server configuration which fails.

That will help us reproduce this issue locally and triage this better.

**Comment by tgulick** [comment] 2020-03-12 19:49
Hi,
I no longer have a company-provided Windows 10 machine to test on. I will have to install Postman on a private machine and see if problem still exists. If it does, I will provide you a cert/key pair and a public URL for you to duplicate it.

**Comment by tgulick** [comment] 2020-03-13 14:15
I loaded 7.20 on my own Windows 10 machine and tried it out and it works now. OK to close this.
