### ISSUE TITLE
Dealing with older API's

### ISSUE THREAD

**Issue by amh2013** [a85/POSTMan-Chrome-Extension#5024] opened 2018-08-14 08:09 UTC
I am working with some older API's and at point point during testing the API will return HTML page which uses javascript to redirect (mainly happens in some payment gateways).

As far as I can tell there is no way to handle such response and you can't copy and past anything in the browser as it will simply not work.
Would be nice to have a webview type panel where you can execute the javascript in the page, or allow an option (unless i'm missing it somewhere) to switch this on in Preview pane.

**Comment by numaanashraf** [comment] 2019-01-22 09:29
Duplicate of #2646

**Closed as completed by numaanashraf** 2019-01-22 09:29 UTC
Labels: feature, duplicate
