### ISSUE TITLE
Copy url to clipboard options

### ISSUE THREAD

**Issue by MuhamedVrajolli** [a85/POSTMan-Chrome-Extension#8948] opened 2020-08-18 09:10 UTC
When copying an url of a request that has environment attributes for example:
```
{{base-url}}/candidates/groups
```
for example `base-url` in this case has the value `http://localhost:8080`.

It would be useful to have an option to copy it as raw or to copy with environment attributes parsed.
When copied as raw, it copies it like this:
```
{{base-url}}/candidates/groups
```
and when copied with environment attributes parsed, it copies it like this:
```
http://localhost:8080/candidates/groups
```

**Comment by DannyDainton** [comment] 2020-08-18 09:47
Duplicate of #3234

**Closed as completed by DannyDainton** 2020-08-18 09:47 UTC
Labels: duplicate
