### ISSUE TITLE
cURL Request Provided By Published Docs Not Functional With No Workaround

### ISSUE THREAD

**Issue by staticvoidmaine** [a85/POSTMan-Chrome-Extension#3282] opened 2017-07-17 20:08 UTC
## App Details:
documenter.getpostman.com

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behaviour: published documentation should provide an immediately usable cURL request
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Not Applicable
 4. Screenshots (if applicable)

## Steps to Reproduce
1. Publish documentation for an API call where query parameter names look something like `foo[bar]`
2. Visit documentation and copy/paste provided cURL request into terminal
4. See that the url is not url encoded and no -g flag is provided
5. User must intervene and modify the copied curl command with the -g flag.

edit: I restructured my issue to simplify after more testing.

Here is a description of a problem with the only workaround I could think of:

I created an example request where I manually url encoded the request so that I could leave the actual request in the collection unaltered. Then, when I refreshed the documentation page, I found that the example cURL request had 3 distinct sections:
1. The query parameters I url encoded in the proper order, but **url decoded**
2. The query parameters that needed no modification
3. The query parameters I url encoded in the proper order and **url encoded** like I set them in the request example within postman.

We do not want to or plan to remove `foo[bar]` style query parameters from our API as they are central to some of the flexibility we offer, but we really love where you're headed with your documenter and hope that you will help us out.

Thanks,

Rylan

**Comment by rylancates** [comment] 2017-07-17 20:35
This is an issue when the documentation is for external customers.

The URLs need to be human-readable in the actual written documentation, so URL encoding is undesirable at that point.

Conversely, when the user clicks the 'Copy to Clipboard' button, the expectation is, "Now I'm going to paste this into my terminal and hit enter and it will just work."

**Comment by rylancates** [comment] 2017-07-17 22:17
I poked around a little more and have some more info on this issue.

I looked further into your API documentation documentation (rolls off the tongue ;) ) and found the example request/response functionality. This looked promising at first glance. So, I rigged up some request examples.

The request I was testing accepts two different query parameter schemes.

The first is a single query parameter with no problematic characters in the name like so: `foo=Some value here`. The example request/response for this scheme is properly url encoded and works as expected in cURL.

The next query param scheme breaks the single query parameter down into specific fields. This looks like: `foo[bar]=chunk one&foo[buzz]=chunk two`. While the documentation page doesn't automatically url encode query parameter names along with the query parameter values, I figured I would build off my prior success and manually url encode the query parameter names despite that being a tedious workaround. But to my chagrin, my url encoding efforts didn't pan out as it appears the query parameter names are url decoded before display on the documentation page. Then, when the cURL command is copied and pasted into a terminal, the parameters are still in the url decoded state (not that I expected otherwise at that point).

**Comment by rylancates** [comment] 2017-07-18 18:32
I restructured my issue request to simplify after more testing.

Here is a description of a problem with the only workaround I could think of:

I created an example request where I manually url encoded the request. Then, when I refreshed the documentation page, I found that the example curl request had 3 distinct sections:
1. The query parameters I url encoded in the proper order, but **url decoded**
2. The query parameters that needed no modification
3. The query parameters I url encoded in the proper order and **url encoded** like I set them in the request example within postman.

**Comment by prashantagarwal** [comment] 2017-07-19 07:05
@rylancates Thanks for reporting this. We are looking into this issue and will get back to you with the fix.

**Comment by Cazaimi** [comment] 2019-07-23 08:08
@staticvoidmaine , I reproduced the situation that you mentioned, with the request having query params like `foo[bar]`. As can be seen in the screenshot below, the query params are correctly encoded in the `cURL` request:

![Screenshot 2019-07-23 at 1 35 25 PM](https://user-images.githubusercontent.com/13660453/61694268-c2df9e00-ad4e-11e9-9061-3078ad09cc58.png)

On directly pasting this request in the MacOS terminal, there aren't any syntax errors reported:

![Screenshot 2019-07-23 at 1 37 25 PM](https://user-images.githubusercontent.com/13660453/61694425-0934fd00-ad4f-11e9-9297-936f97225057.png)

Please feel free to contact us for any further queries. 

@Raja-Simha, this can be marked as closed.

**Closed as completed** 2019-11-30 23:14 UTC
Labels: bug, product/documentation, code-generator
