### ISSUE TITLE
form-data files with spaces in filenames are left out of requests

### ISSUE THREAD

**Issue by synotna** [a85/POSTMan-Chrome-Extension#1908] opened 2016-03-22 15:22 UTC
form-data files with spaces in filenames are left out of requests

![chrome_2016-03-22_16-21-41](https://cloud.githubusercontent.com/assets/3313126/13956770/401e7438-f04a-11e5-93cf-ba21624a4328.png)

The same request without spaces in the filename works

**Comment by abhijitkane** [comment] 2016-03-22 15:26
@synotna What version of Postman are you on? I'm not able to reproduce this. Can you try changing the URL to https://echo.getpostman.com/post? 
<img width="697" alt="screen shot 2016-03-22 at 20 54 58" src="https://cloud.githubusercontent.com/assets/681190/13956890/78a22194-f070-11e5-9780-f4c003f8e4e1.png">

**Comment by synotna** [comment] 2016-03-22 15:44
Strange, I can confirm the same behaviour on https://echo.getpostman.com/post

I also tested the behaviour with another client (Advanced REST client) on both https://echo.getpostman.com/post & the other API: it has identical behaviour on https://echo.getpostman.com/post & it works fine on the other API (I tested before opening this ticket, is why I believed the bug lay in postman)

Now we are not sure where the bug is!

**Comment by abhijitkane** [comment] 2016-03-22 18:05
In Advanced Rest Client, you should be able to right click and open DevTools (Inspect element).
In Postman, http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

Can you compare the 2 requests (Network tab), and see if there's any difference there?

**Comment by synotna** [comment] 2016-03-23 13:51
I did that, then noticed that I no longer had the same behaviour: and realised when testing with https://echo.getpostman.com/post I was turning off the interceptor without thinking!

With interceptor turned on, the file is left out of the request

![chrome_2016-03-23_14-50-22](https://cloud.githubusercontent.com/assets/3313126/13987188/a2252f7a-f106-11e5-83ed-46f6533b8671.png)

**Comment by abhijitkane** [comment] 2016-03-23 13:52
@synotna If you toggle the Interceptor, you'll need to delete the row with the file and re-select it. The file is read in a slightly different way if it has to be sent through the Interceptor.

**Comment by synotna** [comment] 2016-03-23 13:53
No, that's not the issue

I have removed the row, re-added it, re-selected, does not work

If I pick a file without spaces again, it works

If I pick the file with spaces again, it doesn't work

**Comment by abhijitkane** [comment] 2016-03-23 14:00
@synotna Got it. We'll be pushing a fix for this in the next release.

**Comment by synotna** [comment] 2016-03-23 14:12
Awesome, thanks for the great assistance in debugging!

**Comment by jeremymills** [comment] 2016-03-25 22:21
this will also close #1874

**Comment by abhijitkane** [comment] 2016-04-26 13:28
@synotna Can you confirm this fixed in 4.1.3?

**Closed as completed** 2016-05-16 09:43 UTC
