### ISSUE TITLE
Opened tabs are not saved on exit

### ISSUE THREAD

**Issue by DanielPetatCes** [a85/POSTMan-Chrome-Extension#3662] opened 2017-10-24 06:52 UTC
## App Details:
```
Postman for Windows
Version 5.3.1
win32 10.0.15063 / x64
```

## Issue Report:
Hello,
when I leave some tabs / requests open, close the app and start it again, it always starts with only one "New tab".
So after every restart, I have to re-establish my workspace.
The collections are saved and loaded correctly.

A few versions ago (I think before updating to version 5.3.0 or 5.3.1) it saved all the tabs that were open on exit, and restored them after starting it again.

Steps to reproduce:
- Open a tab with any request
- Close postman
- Open it again -> The tab is gone

I already re-installed Postman, deleting all the files in the local and roaming AppData.

Best regards
Daniel

**Comment by SamvelRaja** [comment] 2017-10-24 06:53
It's a regression introduced in 5.3.1, we are tracking it here. 
Closing it as the duplicate of #3650

**Closed as completed by SamvelRaja** 2017-10-24 06:53 UTC

**Comment by deepakpathania-zz** [comment] 2017-10-24 15:55
@SamvelRaja You referenced the wrong issue, I guess. 3653 is about the smaller font size for Chinese in tabs, you probably meant 3650.
