### ISSUE TITLE
Black Screen when response payload is 14 meg. 

### ISSUE THREAD

**Issue by spgit2014** [a85/POSTMan-Chrome-Extension#8072] opened 2020-02-17 05:49 UTC
**Describe the bug**
Using both Postman and PostmanCanary 7.18. Anytime the payload is around 14 Megs the screen goes black and you cannot further use pm without restarting.

**To Reproduce**
execute GET or POST request that returns ~14Meg response payload
Once the response is rendering, BLACK-O

**Expected behavior**
The response payload can be reviewed, searched etc.

**Screenshots**
It's a Black-Screen

**App information (please complete the following information):**
 - Asp.Net Core 2.2 Web API
 - 7.18 in Postman and PostmanCanary
 - OS: Windows 10 Pro

**Additional context**

**Comment by matthewcoxx** [comment] 2020-02-23 07:29
Duplicate of #https://github.com/postmanlabs/postman-app-support/issues/5288 , same issue, but 108MB file.

**Comment by Jgerardopine** [comment] 2020-03-03 15:05
I am having the same problem with .zip above 16MB. I have tried in different places and same thing, with Canary as well, both in Linux(ubutnu 18) and Windows 10.

**Comment by kamalaknn** [comment] 2022-05-05 05:06
@Jgerardopine @matthewcoxx Could you confirm if you are still seeing the crashes on the latest version of Postman?

**Comment by postman-kenji** [comment] 2022-06-28 15:59
Closing due to age of issue and response time. Please feel free to reopen this if you are encountering this issue in the latest version of Postman, thanks!

**Closed as completed by postman-kenji** 2022-06-28 15:59 UTC
Labels: bug, performance, product/runtime
