### ISSUE TITLE
Set-Cookie response header won't set cookie in Postman App

### ISSUE THREAD

**Issue by ma-schmidt-de** [a85/POSTMan-Chrome-Extension#4611] opened 2018-05-29 09:34 UTC
Hi guys,

I just encountered the issue cookies are not set automatically via `Set-Cookie` response header anymore. I was using this intensively for the last months but seams to be broken after I updated to the latest Postman App version.

## App Details:
```
Postman for Mac
Version 6.1.3
OS X 17.5.0 / x64
```

### Steps to reproduce
1. Send request to domain `example.com`
2. Receive response that includes a `Set-Cookies` header like:
`Set-Cookie → TEST=someValue; Path=/; Max-Age=3600.0; HttpOnly; Secure`
3. Open Cookie menu via `Cookies` link and check for new cookies for the `example.com`

### Expected behaviour
- New cookie `TEST` is set for domain `example.com`

### Actual behaviour
- No cookie set

## Hint
Setting cookies via `Set-Cookie` response header is a documented feature:
https://www.getpostman.com/docs/v6/postman/sending_api_requests/cookies

----
![cookie-documentation](https://user-images.githubusercontent.com/19306046/40650575-e94ae556-6333-11e8-9d52-7bfc025bf3be.png)
----

Please let me know if you need further details regarding the actual requests and response.

Cheers,
Matthias

**Comment by harryi3t** [comment] 2018-05-29 12:26
duplicate of https://github.com/postmanlabs/postman-app-support/issues/4581

**Closed as completed by harryi3t** 2018-05-29 12:26 UTC
