### ISSUE TITLE
Get New Access Token not using variable value for Token Name

### ISSUE THREAD

**Issue by yetibob** [a85/POSTMan-Chrome-Extension#3837] opened 2017-11-20 18:44 UTC
## App Details:
```
Postman for Mac
Version 5.3.2
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behaviour: Expect token name to use value of postman variable
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/5046928/33035391-ed069ae4-cdf8-11e7-86a6-6d588d434873.png)

![image](https://user-images.githubusercontent.com/5046928/33035402-f64b4ec4-cdf8-11e7-9919-d1d16d5ee051.png)

1) Set a variable in your environment
2) Open authorization tab
3) Choose OAUTH 2.0 (Only one I have tried with) and select "Get New Access Token"
4) Use variable in Token Name field
5) Fill in the rest of the fields accordingly
6) Click Request Token
7) A token is created with the name "{{somethingHere}}" instead of the value stored in `{{somethingHere}} `

**Comment by kamalaknn** [comment] 2017-11-21 10:28
Hey @Robocrypt,

This is a duplicate of #3525. In summary, we don't support variables in token names yet. We'll be working on improving oauth 2.0 token flows to add more information about tokens. However we can't give an ETA for it yet. Please follow the original issue for updates.

**Closed as completed by kamalaknn** 2017-11-21 10:28 UTC
