### ISSUE TITLE
Add software repositories for Linux distros

### ISSUE THREAD

**Issue by luispabon** [a85/POSTMan-Chrome-Extension#2616] opened 2017-01-09 11:35 UTC
As per title; keeping Postman update is a major chore as it requires manual installation instead of integrating with my distro's (Ubuntu) software repositories.

**Comment by sdnts** [comment] 2017-01-10 10:44
@luispabon This is on our roadmap. Although there isn't an ETA right now, I'll keep you updated here.

**Comment by saschazar21** [comment] 2017-03-30 09:55
I understand that Postman for Linux is still in beta... 
However, it would be nice to also have automated builds for different Linux distros, while you're not present in the different software repositories, so that people can install Postman at least manually and have it integrated in their system's applications...
Would it be possible to also publish a .deb or a .rpm release in Postman's next release?

[electron-builder](https://www.npmjs.com/package/electron-builder) has nearly out-of-the-box support for that...

**Comment by kevlawz** [comment] 2018-01-20 07:20
Maintaining packages can be time consuming for a small start-up. Better to look into Snap or Flatpak. One Flatpak probably resolves the issue for 99.9% of the people requesting the Enhancement.

**Comment by DanielRamosAcosta** [comment] 2018-03-01 20:52
Duplicate of #2931

**Comment by SamvelRaja** [comment] 2018-03-21 08:01
Closing this as we are actively tracking in #2931

**Closed as completed by SamvelRaja** 2018-03-21 08:01 UTC
