### ISSUE TITLE
Add longer time limits for monitoring runs

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#4834] opened 2018-07-16 20:14 UTC
**Describe the solution you'd like**
Some users would benefit from being able to run larger collections, and test suites.

**Describe alternatives you've considered**
Allowing monitors to have a longer time limit – currently [five (5) minutes](https://www.getpostman.com/docs/v6/postman/monitors/intro_monitors) – will allow larger collections and test suites to be run on monitors

**Comment by sulmanbashir** [comment] 2019-05-31 11:55
Hi,

I meet this issue by running collections who exceed always 5 min. Can you tell me when this fix will be released ?

Thanks,
Sulman

**Comment by sankalp0o** [comment] 2019-06-06 09:25
Duplicate of #3171 , closing this.

**Closed as completed by sankalp0o** 2019-06-06 09:25 UTC
Labels: feature, product/automation-testing
