### ISSUE TITLE
Incorrect request listing in web monitor test results view

### ISSUE THREAD

**Issue by umeshp7** [a85/POSTMan-Chrome-Extension#7102] opened 2019-08-13 10:34 UTC
The postman requests are not what are shown in the UI. Requests made from within the scripts are shown.
Expected: 
<img width="1190" alt="Screenshot 2019-08-13 at 4 00 11 PM" src="https://user-images.githubusercontent.com/31915995/62935006-9c5bd280-bde3-11e9-9d08-725aeffa8103.png">

The "Syncing with JIRA" method and request url changes with every monitor run.
<img width="1236" alt="Screenshot 2019-08-13 at 4 00 21 PM" src="https://user-images.githubusercontent.com/31915995/62935067-bc8b9180-bde3-11e9-99bd-fc5321e9bc0c.png">

<img width="1244" alt="Screenshot 2019-08-13 at 4 00 32 PM" src="https://user-images.githubusercontent.com/31915995/62935080-c44b3600-bde3-11e9-8d25-0d52aa2315d5.png">

**Comment by godfrzero** [comment] 2019-08-13 11:42
Possible duplicate of https://github.com/postmanlabs/postman-app-support/issues/6850

**Closed as completed** 2019-08-13 11:53 UTC
Labels: bug, product/automation-testing
