### ISSUE TITLE
Transferring a collection leads to broken public documentation

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#4988] opened 2018-08-08 08:12 UTC
**Describe the bug**
If a collection is transferred to another user (for example, when a user is removed from the team) causes the public documentation to stop working. Visiting the public documentation displays an error page.

**To Reproduce**
1. Be in a team with a user who has published documentation
2. Remove that user from the team, and while doing so, transfer their collections to another user
3. Access the public documentation once the transfer is complete

**Expected behavior**
Existing public documentation should remain functional.

**App information (please complete the following information):**
 - App Type: Irrelevant
 - Postman Version: Irrelevant
 - OS: Irrelevant

**Comment by ankitjaggi** [comment] 2018-08-09 08:42
We have found the issue on our end. We will release a fix for this soon and keep this issue updated on the same.

**Comment by ankitjaggi** [comment] 2018-09-11 10:09
@godfrzero This has been fixed now, right?

**Comment by preethammavin** [comment] 2019-03-04 23:25
@godfrzero can you confirm if the issue is solved in the current version.

**Comment by preethammavin** [comment] 2019-03-26 03:48
Closing due to inactivity

**Closed as completed** 2019-03-26 03:47 UTC
Labels: bug, product/documentation, product/dashboard
