### ISSUE TITLE
Postman app doesn't handle login with google account if 2 factor authentication is enabled

### ISSUE THREAD

**Issue by amahlaka** [a85/POSTMan-Chrome-Extension#3098] opened 2017-06-01 14:06 UTC
1. Postman Version: 4.11
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 10 Pro
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Unknown
 6. Expected behaviour: Log in with google account 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): TBD
 8. Screenshots (if applicable)

Steps to reproduce the problem:
Click> Sign in with Google
Enter google account email and password
Click Login in
Expected result: if account has 2fa enabled, wait for user to complete the challenge ( code, securite key etc) and log in after that
What Happens: The 2 Factor authentication window opens and immediately closes, causing the login to fail, resulting in error on top of the window: Failed to login

**Comment by numaanashraf** [comment] 2017-06-01 14:14
@amahlaka Thanks for reporting. We are looking into this.

**Comment by curtiscook** [comment] 2017-06-08 18:20
I'm running into this on mac chrome as well. Postman throws a "could not login" error and prematurely closes the 2FA window

**Comment by ai7** [comment] 2017-06-09 21:00
Running into this issue too. Postman prematurely closes the 2FA window.

**Comment by kissgyorgy** [comment] 2018-01-29 19:16
On Linux it says "You can only use your Security Keys with Google Chrome."

**Comment by thecuriousdev** [comment] 2018-05-21 06:15
Hey All, Can you try updating your app to the latest version (6.1.2+), And please let us know if you are still facing this issue.

**Comment by kissgyorgy** [comment] 2018-05-28 17:46
Same for me with 6.1.3 "You can only use your Security Keys with Google Chrome"

**Comment by calebmathis** [comment] 2018-06-14 18:03
MacOS High Sierra
Postman 6.1.3
"You can only use your Security Keys with Google Chrome"
"Try Another Way", clicks, security key is the only option!?!

**Comment by calebmathis** [comment] 2018-06-14 21:35
OK, my bad. Just needed to add another 2-factor method (like my phone) through my google account settings first. Then I can use it :)

**Comment by SamvelRaja** [comment] 2018-06-29 13:37
Duplicate of #3697

**Closed as completed by SamvelRaja** 2018-06-29 13:37 UTC
Labels: bug
