### ISSUE TITLE
Postman crashes on large response size (>50MB)

### ISSUE THREAD

**Issue by Yuvashkenazi** [a85/POSTMan-Chrome-Extension#9739] opened 2021-03-16 19:28 UTC
**Describe the Issue**
I changed the Max response size from the default 50MB to 0 because I was expecting a large response (stress testing my DB). When I send the POST request to my DB the app shows 200ok in the first ~5 seconds, but then Postman crashes.

**Steps to Reproduce**
1. Settings>General>Max response size in MB set to 0.
2. Make a request with a large response size.
3. App crashes.

**Environment Information**

 - Platform Type: Desktop
 - Postman Version: v8.0.7
 - Operating System: Windows 10 Pro 64-bit

**Comment by ICCTest** [comment] 2021-08-10 09:04
I have same problem as Yuval. I tried both Postman App and Postman Web.  :)

**Comment by Arthi93** [comment] 2021-12-13 12:24
Even with response smaller tham 50MB, but above 40MB, it just loads infinitely and request never ends. If i test it in any other app - it works.

**Comment by kamalaknn** [comment] 2022-04-28 09:36
Hey @Yuvashkenazi @ICCTest @Arthi93 

Could you share a sample collection/request that is causing Postman to crash? And, could you confirm if you are still seeing this issue on the latest version of Postman 9.16.1?

I have been testing the latest version of Postman with a large response size with `https://postman-echo.com/bytes/60/mb` and I am not able to reproduce the crash.

**Comment by ICCTest** [comment] 2022-04-28 11:07
Hi!

Yes I still see the crash!

BR,
ICCTest

Från: Kamalakannan ***@***.***>
Skickat: den 28 april 2022 11:37
Till: postmanlabs/postman-app-support ***@***.***>
Kopia: Naser Khodabin ***@***.***>; Mention ***@***.***>
Ämne: Re: [postmanlabs/postman-app-support] Postman crashes on large response size (>50MB) (#9739)


Hey @Yuvashkenazi [github.com]<https://urldefense.com/v3/__https:/github.com/Yuvashkenazi__;!!D7T54aRJsb59!DGVbphLt9j6AeZonzOlj1VA7egCLh4RvzRHPX3W22HVrHve8WXPS4XEZRCFoG_7x22lzIA6ENovK4cZMVQuEWNdwa8FRSQM5Vc9mMopFgg$> @ICCTest [github.com]<https://urldefense.com/v3/__https:/github.com/ICCTest__;!!D7T54aRJsb59!DGVbphLt9j6AeZonzOlj1VA7egCLh4RvzRHPX3W22HVrHve8WXPS4XEZRCFoG_7x22lzIA6ENovK4cZMVQuEWNdwa8FRSQM5Vc-EB27Sqw$> @Arthi93 [github.com]<https://urldefense.com/v3/__https:/github.com/Arthi93__;!!D7T54aRJsb59!DGVbphLt9j6AeZonzOlj1VA7egCLh4RvzRHPX3W22HVrHve8WXPS4XEZRCFoG_7x22lzIA6ENovK4cZMVQuEWNdwa8FRSQM5Vc9w5MRwQg$>

Could you share a sample collection/request that is causing Postman to crash? And, could you confirm if you are still seeing this issue on the latest version of Postman 9.16.1?

I have been testing the latest version of Postman with a large response size with https://postman-echo.com/bytes/60/mb [postman-echo.com]<https://urldefense.com/v3/__https:/postman-echo.com/bytes/60/mb__;!!D7T54aRJsb59!DGVbphLt9j6AeZonzOlj1VA7egCLh4RvzRHPX3W22HVrHve8WXPS4XEZRCFoG_7x22lzIA6ENovK4cZMVQuEWNdwa8FRSQM5Vc9LWbrJEA$> and I am not able to reproduce the crash.

**Comment by kamalaknn** [comment] 2022-04-28 12:40
@ICCTest 

1. Would it be possible to share an API that we can use to replicate the issue?
2. Could you share the logs from `View -> Developer -> View Logs In Finder` to `help@postman.com`?

**Comment by Yuvashkenazi** [comment] 2022-04-29 18:27
Sorry @kamalaknn, since making this post I have switched jobs and no longer have access to the database that was causing this issue.

**Comment by shubhbhargav** [comment] 2022-10-10 18:53
Closing off the issue for now. We will re-open it in-case anyone else comes across this.

**Closed as completed by shubhbhargav** 2022-10-10 18:53 UTC
Labels: bug, performance, product/runtime

**Comment by Deeptimullur1** [comment] 2023-04-06 09:06
Hi, I am still facing the issue, When I try to upload the file of size >400MB then postman is crashing.  
can you reopen the issue.
