### ISSUE TITLE
Removing a user from a team removes their shared environments without warning

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4807] opened 2018-07-11 06:10 UTC
**Describe the bug**
When removing a user from a team, I see a modal window asking me to transfer their shared collections to someone else. However, environments belonging to the user are removed from team workspaces, and there's no warning that this will happen.

**To Reproduce**
1. Remove a user with shared environments from a team

**Expected behavior**
Either a warning stating that shared environments will be removed, or transferring the environments along with the collection.

**App information (please complete the following information):**
 - Web dashboard

**Comment by ankit-m** [comment] 2018-12-12 01:42
The copy has been changed to warn the user about environments being removed.

**Comment by jkewley** [comment] 2019-03-19 15:01
> The copy has been changed to warn the user about environments being removed.

But that's not a solution, and the verbiage is generic. If environments are created directly in a team workspace by a user who is being removed from the team, those environments are gone forever unless a manual export for each environment is performed before the user is removed. The workflow to remove a team member only warns that "So and So is sharing ## collections" and doesn't provide details on which ones they are, or which environments will be lost.

Speaking from experience here, you guys need a better solution to team management. App-allowed activities can result in data loss for the team because the app doesn't make data retention a top priority. Pro and Enterprise editions are going to be used by organizations which won't tolerate data loss.

**Comment by sankalp0o** [comment] 2019-03-19 17:53
Hi @jkewley, thanks for your inputs! We're indeed working hard towards making team and data management better.
We've recently released a new version of the app in which the concept of an "owner" is done away with. What this means is that all environments shared with the team remain with the team even if the user who created it leaves (or is removed). This is the expected behaviour from app version v7.0 onwards. Do take a look at moving your team to the newer version.
I'm closing this issue for now but feel free to open it again or create a new one for any other feedback you might have. Have a great day!

**Closed as completed by sankalp0o** 2019-03-19 17:53 UTC
Labels: feature, product/dashboard

**Comment by jkewley** [comment] 2019-03-19 18:06
@sankalp0o I see that there are [additional roles defined in the new release](https://blog.getpostman.com/2019/03/11/streamline-access-control-with-extended-roles-permissions/), but can you point me to documentation which shows how sharing and syncing have been changed by this new design? That's a fairly substantial update which changes core application usage and I'd like to read about the new approach.

**Comment by jkewley** [comment] 2019-03-19 21:49
@sankalp0o looking at the interface post-upgrade to 7 I see that collections created directly in PM still have an owner, so I assume they''ll go away if I'm removed from the team.

![StillOwned](https://user-images.githubusercontent.com/1148930/54644153-0cea0780-4a6f-11e9-8344-3ce502aa8ed1.PNG)

Can you clarify that this fix only applies to environments? Are you planning to apply the same fix to collections, mocks and monitors?
