### ISSUE TITLE
Environment variables not working since updating to v 10.20.7

### ISSUE THREAD

**Issue by gpokvytyte** [a85/POSTMan-Chrome-Extension#12525] opened 2023-12-05 13:27 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

All of my tests are using environment variables in a way of setting it and getting it for further tests. These have stopped working since the new release - even your own suggested function in documentation remained the same (as has my code in test scripts) however the variables simply do not get set - no error is shown and the variable is not taken from env variables to run in test.

### Steps To Reproduce

1. Select environment to run tests on
2. in test scripts  use pm.environment.get("env_variable") function in test
3. the error shown in console is that the value of variable is undefined.

Same happens when attempting to use pm.environment.set function - no variable is created.

### Operating System

Linux

### Postman Version

10.20.7

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by vedkribhu** [comment] 2023-12-05 13:52
@gpokvytyte thank you for reporting the issue. I am not able to reproduce this issue on my end. Can you help me with some video recording of the issue or some screenshots?

**Comment by mkh71** [comment] 2023-12-28 07:10
[Recording 2023-12-28 130716.zip](https://github.com/postmanlabs/postman-app-support/files/13784098/Recording.2023-12-28.130716.zip)
After login/Reg the environment variable(token) is not changing. Have a look for variable token in env, login response and test in video. 
~TIA

**Comment by vedkribhu** [comment] 2023-12-28 08:02
@gpokvytyte when you set a variable through scripts it is set as the "current value" of that variable and not the initial value. Current value will be used for resolving your variables in request sending. For more details on initial values vs current values in postman you can refer to this small video: https://www.youtube.com/watch?v=I6vClap0ajU&ab_channel=Postman.

**Closed as completed** 2024-01-08 03:11 UTC
Labels: Environments, product/runtime, blocked/need-repro
