### ISSUE TITLE
Export collection version to filesystem fails

### ISSUE THREAD

**Issue by bmckinle** [a85/POSTMan-Chrome-Extension#10415] opened 2021-11-01 19:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Previous related issue closed.  

Export collection appears broken in 9.1.3. This is not fixed, apparently. Collection ... -> Export gives choice of export v2 or v2.1 (recommended). Selecting 2.1, as I've always done for over a year now, no longer results in a pop-up to select an output file name. Nothing happens, which means I cannot update my newman json test scripts. Is this fixed yet or how can I work around it?

### Steps To Reproduce

1. Select a collection ...
2. Export gives choice of export v2 or v2.1 (recommended).
3. Expecting the usual pop-up to select an output file name. 
4. Nothing happens, so not able to run newman tests in pipeline automation.

Surely, I am not the only one experiencing blocked pipeline newman test updating capability via this very important export capability.   Is there a patch, fix or something to get around the issue?

### Screenshots or Videos

none

### Environment Information

```markdown
- Operating System: Mac Catalina
- Platform Type: Native App
- Postman Version:  9.1.3
```

### Additional Context?

This was working very recently but not certain which version it stopped working in.  Very odd observation.  I rebooted my mac for an independent reason and this problem resolved.  There is definitely an issue pop-up not showing up on mac catalina, at least in some circumstances.  Should not have to reboot to fix--perhaps on a Windows box. ;)

**Comment by timbochamp** [comment] 2021-11-01 19:48
Thanks for reporting, @bmckinle ! I'm not able to reproduce this after upgrading to v9.1.3 on Catalina v10.15.7 with the file path to save window opening up when exporting a collection.

This sounds similar to #9750 with loss of functionality after upgrading. I'll log a bug and we'll investigate. 

If this happens again, could you please send your logs to help@postman.com as per https://support.postman.com/hc/en-us/articles/360025298633-How-to-share-logs-with-Postman-for-debugging-issue ?

**Comment by bmckinle** [comment] 2021-11-02 00:07
Sure

**Comment by timbochamp** [comment] 2022-02-17 19:29
We're going to close this as of version 9.13.0 being unable to reproduce. Please feel free to reopen this at the same time if the issue occurs again!

**Closed as completed by timbochamp** 2022-02-17 19:29 UTC
Labels: bug, product/runtime, export
