### ISSUE TITLE
APIs could not get response from Postman whereas it works with SOAP UI?

### ISSUE THREAD

**Issue by 03rohit** [a85/POSTMan-Chrome-Extension#7502] opened 2019-10-18 20:19 UTC
We have standard APIs for Oracle ERP. When I try to test APIs using the postman I am getting an error "Could not get any response" whereas with the same API URL, the same system, same parameters I tried with SOAP UI. It works absolutely fine. 
Also when we tested the API with postman on my colleague's machine it works.
 
The screenshot of the API with error
![API Postman Error](https://user-images.githubusercontent.com/56702059/67124960-56433680-f1b9-11e9-9504-d135b4f47868.JPG)

![image](https://user-images.githubusercontent.com/56702059/67124983-6c50f700-f1b9-11e9-81e3-d676e6445b10.png)

I check the discussion forum and applied all the solutions 

1. Disable all firewalls on windows.
2. Disable SSL Certificate
![image](https://user-images.githubusercontent.com/56702059/67125136-b4701980-f1b9-11e9-88a1-793c29959eda.png)

3. Validate the Proxy Server Settings
![image](https://user-images.githubusercontent.com/56702059/67125201-dd90aa00-f1b9-11e9-88ca-16c45f828172.png)

4.  Review request timeout
![image](https://user-images.githubusercontent.com/56702059/67125240-f8631e80-f1b9-11e9-93b2-bd1b6f9c0af2.png)

5. Review the environment variables on "View Advance setting on Windows"

6. Uninstall and install postman.

None of the solutions works. I tried many APIs none of them works with the postman whereas all of them work with SOAP UI. I am using SOAP UI as a workaround but I really wanted to know what's wrong with my system ?? Am I missing any setting ??

**Comment by shamasis** [comment] 2019-10-19 20:01
Can you hit send and check immediately if any error comes up on Postman Console.

**Comment by 03rohit** [comment] 2019-10-20 16:09
Not sure exactly what you are requesting. I run the API by clicking on send button and in response i get the error. I downloaded the response file may be that helps.

[response.zip](https://github.com/postmanlabs/postman-app-support/files/3748045/response.zip)

**Comment by codenirvana** [comment] 2020-03-10 22:23
@03rohit What's the error message in the [Postman Console](https://learning.postman.com/docs/postman/sending-api-requests/debugging-and-logs/#for-the-native-app-for-mac--windows--linux)?

**Comment by codenirvana** [comment] 2020-05-29 20:52
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Comment by crelinae** [comment] 2020-06-02 16:19
I'm facing a very similar issue where identical REST POST query on SoapUI is working, but on Postman my service is responding with the default message.

I say identical, and that's as far as I can see all settings and the query itself is the same.

Not sure how much I can share of the logs or other data as this is work-related, but please ask the good questions to pinpoint the problem. I have no Postman error messages, as I'm assuming our endpoint is resolving the queries but not responding to Postman for some reason.

**Comment by vvs11** [comment] 2020-06-02 18:35
reopening the issue

**Comment by Mechanicalkeyboard** [comment] 2020-09-03 21:31
Happy to try to help here, if you can collect the console logs of one of the requests which is failing following the guide: 
[Here](https://learning.postman.com/docs/sending-requests/troubleshooting-api-requests/#:~:text=Clear%20the%20list.-,Accessing%20console%20logs,see%20the%20app%20debug%20logs.)
Along with a sample request, we can investigate further.

**Closed as completed** 2020-09-11 15:06 UTC
Labels: bug, blocked/need-info, product/runtime, debugging

**Comment by SomosTropa** [comment] 2020-10-08 23:52
I m facing the same problem, but the other way round. its working in postman, but not in SoapUI. 👎

**Comment by fede-2110** [comment] 2020-10-08 23:58
I am facing the same problem but the other way round. Its working in Postman but not in Soap UI
