### ISSUE TITLE
Retrying a Collection Run with Iteration Data

### ISSUE THREAD

**Issue by jameshd** [a85/POSTMan-Chrome-Extension#5241] opened 2018-09-25 10:23 UTC
**Describe the bug**
Clicking Retry in collection runner when initial run used iteration data, forgets all knowledge of the iteration data used. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a simple request that has a call to console.log(data.YOUR_VAR_HERE)
2. Open Collection Runner and Postman Console.
3. Run your collection with a CSV of iteration data containing YOUR_VAR_HERE
4. First run, will log your iteration data.
5. After run completes, hit the blue retry button, data.YOUR_VAR_HERE will be null. Like iteration data has been forgotten. 

**Expected behaviour**
Iteration file should be remembered and collection run retry should use exactly the same data file and config as the initial attempt. 

**App information (please complete the following information):**
 - App Type Native
 - Postman Version 6.3
 - OS: OSX - 10.13.6

**Additional context**
There were two requests in my collection I was using. Both shared the iteration data. Each request works first time as if setting up a new collection run. Hitting retry is when problem occurs.

p.s. You have a typo in your Issue template on the word Behaviour :)

**Comment by sivcan** [comment] 2018-09-25 10:37
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4824
You can refer to this comment for more information https://github.com/postmanlabs/postman-app-support/issues/4824#issuecomment-409548624

**Closed as completed by sivcan** 2018-09-25 10:37 UTC

**Comment by jameshd** [comment] 2018-09-25 10:45
Ah thanks! I did look but didn't spot that one - makes sense. Cheers
