### ISSUE TITLE
UUID for Variables change every API request to a Collection

### ISSUE THREAD

**Issue by johnwyles** [a85/POSTMan-Chrome-Extension#9885] opened 2021-04-28 16:41 UTC
**Describe the Issue**
UUID for Variables change every API request to a Collection
Further discussion found here: https://community.postman.com/t/why-does-the-uuid-for-variables-change-every-api-request-to-a-collection/22954/5

**Steps to Reproduce**
# FIRST RUN (1)
```shell
curl --location -g --request GET 'https://api.getpostman.com/collections/abcd-abcd-dddd-42ac-ab61-abcd' --header 'X-Api-Key: PMAK-abcd-abcd' | jq
```

## RESULTS (1)
```json
...
"variable": [
      {
        "id": "29217a0f-36d2-4ca8-8a2e-ae67afd42118",
        "key": "authToken",
        "value": ""
      },
```

# SECOND RUN (2)
```shell
curl --location -g --request GET 'https://api.getpostman.com/collections/abcd-abcd-dddd-42ac-ab61-abcd' --header 'X-Api-Key: PMAK-abcd-abcd' | jq
```

## RESULTS (2)
```json
...
 "variable": [
      {
        "id": "f76e64ac-962c-41b3-a339-0138e2a61e43",
        "key": "authToken",
        "value": ""
      },
```

**Screenshots or Videos**

**Environment Information**

 - Platform Type: cURL to Postman API
 - Postman Version: N/A
 - Operating System: Linux

**Additional Context**
The UUID for the variables change every single request to the API for a Collection (and it may be other types of requests: Environments) which create differences when saving the results to source control despite there being no changes made in the Collections, Globals, or Envrionment Variable settings.

**Comment by johnwyles** [comment] 2021-05-10 15:49
This seems like a pretty serious bug if you are not able to consistently provide the Collection (or Environment) consistently per each request and that there will always be a DIFF and that the Variables you wish to reference will never be able to referenced again in subsequent requests. Seems like a much higher priority bug to have not had attention drawn to it.

**Comment by amilbeck** [comment] 2022-04-06 17:46
Any chance we can get an update from the team on this? 

I have been running into this problem lately as well. I asked a question about it on the community forum and there has been no response. This causes a lot of unnecessary toil when trying to merge branches that have been backed up through the "Connect to Repository" feature and/or the "Backup a Collection" integration. Every single time there are merge conflicts around these ids and as the collection grows, so do the number of conflicts that need to be resolved. It also makes PR diffs hard to read as there are a ton of these changes that occurred automagically and are not actually relevant to the PR itself. We have been migrating our collections from postman to bitbucket repos and this has been the most frustrating issue in that process.

**Comment by nickwinsor** [comment] 2023-07-23 01:04
+1 I'm seeing this too. I have the backup to GitHub integration setup as well so this is causing a new push to the repo on each run. 

<img width="657" alt="qe-notifications_-_The_RealReal_-_1_new_item_-_Slack" src="https://github.com/postmanlabs/postman-app-support/assets/10407964/363e1962-ff2e-478e-a611-a8551effbae4">

**Comment by riya-saini** [comment] 2023-09-19 12:09
@johnwyles This ID was being re-generated due to an internal bug while we do not maintain it in our servers for variables. This should be fixed and no diff should be visible now for your workflow. Can you please check and let us know?

**Comment by RichFlickstein** [comment] 2023-09-29 22:26
I tested this and confirmed the issue is fixed.

Example 
{"collection":{"info":{"_postman_id":"<UUID>"
{"collection":{"info":{"_postman_id":"<UUID>"
I replaced my UUIDs above but in my results, the actual values are the same, confirming the fix

**Comment by johnwyles** [comment] 2024-02-29 03:21
@riya-saini @RichFlickstein 👍🏻 does confirm this indeed does fix the issue so this can be closed if you needed confirmation.

**Comment by riya-saini** [comment] 2024-03-07 13:42
@johnwyles closing this. Issue is fixed.

**Closed as completed by riya-saini** 2024-03-07 13:42 UTC
Labels: bug, collections, product/runtime
