### ISSUE TITLE
Collection Runner: Using "Retry" doesn't re-attach data files

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5069] opened 2018-08-22 23:58 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes I'll need to repeat a collection run because of internet connectivity issues, attaching the wrong environment, etc. When using the `Retry` action to rerun the collection, the collection runs without the previously-attached data file.

**Describe the solution you'd like**
Ideally, the file should be reattached to the new run. 

**Describe alternatives you've considered**
Having a way to attach data files in the collection run summary window would be great. Without it, there are a few extra clicks needed.

**Additional context**
![image](https://user-images.githubusercontent.com/4734306/44497085-33a4a480-a62c-11e8-8420-49d79d17548c.png)

**Comment by sivcan** [comment] 2018-08-23 07:19
Hey @chrisdeso, this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/4824

**Closed as completed by sivcan** 2018-08-23 07:19 UTC
