### ISSUE TITLE
Postman Runner not showing values for URL that are populated from CSV file

### ISSUE THREAD

**Issue by nsenthilnath** [a85/POSTMan-Chrome-Extension#8229] opened 2020-03-23 16:53 UTC
**Describe the bug**
I use postman runner to fill in values for the URL host since I need to send the same request to multiple hosts. I use a csv data file to populate the endpoint host via the Runner. With an earlier version of postman, In the runner it used to show the URL values populated. Now with the latest revisions of Postman it just shows the variable in the URL portion of the iteration.

**To Reproduce**
1. Open postman
2. Click on Runner
3. Select a collection that has request URL values that are filled from a data file.
4. Click on run and when you see the iterations scrolling past, you would just see the endpoint URL as eg: https://{{serverport}} for each of the iterations instead of the actual value for each iteration.

**Expected behavior**
Each iteration should show the value picked from the data file..

**Screenshots**

**App information (please complete the following information):**
 - Postman Version 7.21.0

**Additional context**
It used to work on prior version of postman but I do not recollect the version number.

**Comment by saswatds** [comment] 2020-03-24 05:06
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/8166

**Closed as completed by saswatds** 2020-03-24 05:06 UTC
