### ISSUE TITLE
tests: to.be vs to.not.be ambiguity 

### ISSUE THREAD

**Issue by p00j4** [a85/POSTMan-Chrome-Extension#4710] opened 2018-06-15 12:17 UTC
**Describe the bug**
pm.response.to.be  vs  pm.response.to.not.be
are ambigous, getting the same results for some tests, and works fine for other cases. 

**To Reproduce**
mock an api which returns  500 with response:
```json
{
    "title": "Request not processible",
    "code": "500"
}
```

**Try tests:**
1.  pm.test("test error", function () {
     pm.response.to.not.have.status(200);
     pm.response.to.**not**.have.jsonBody('title');
});

2. pm.test("test error", function () {
     pm.response.to.not.have.status(200);
     pm.response.to.have.jsonBody('title');
     pm.response.to.be.clientError(); // THIS SHOULD PASS for 4xx but it fails with `expected response code to not be 4XX`
});

it returns: ```// AssertionError: expected { Object (title, description, ...) } in response to not contain property 'title'```
irrespective there is `not` there or not. 

Have followed [this](https://www.getpostman.com/docs/v6/postman/scripts/test_examples) and [this](https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference) and couldn't figure what should be the right way of testing.
<img width="750" alt="image" src="https://user-images.githubusercontent.com/6470509/41467428-1d4e9e90-70c4-11e8-88ac-df3838f8a5e3.png">

**Expected behavior**
In this case, one with **not**  should fail and other should pass.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [Version 6.1.3]
 - OS: [macOS High Sierra 10.13]

**Comment by harryi3t** [comment] 2018-06-18 13:06
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3592

**Closed as completed by harryi3t** 2018-06-18 13:06 UTC
