### ISSUE TITLE
Documentation: Order of saved examples doesn't match Collection

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#8140] opened 2020-03-03 23:02 UTC
**Is your feature request related to a problem? Please describe.**
The ordering of examples on generated documentation pages doesn't match what's in the app.

I have a user-submitted Collection with 6 example responses. In the app, they appear in the following order.

200
400
401
403
404
500

On the internal view for the generated documentation page, they appear in the following order:

400
401
200
404
403
500

**Describe the solution you'd like**
Documentation page should show examples in the same order they are represented in the app.

Ideally, this should be paired with support for re-ordering examples as noted in: https://github.com/postmanlabs/postman-app-support/issues/1070

**Describe alternatives you've considered**

**Additional context**

**Comment by Raja-Simha** [comment] 2020-03-04 06:44
Duplicate of #1070

**Comment by JP-from-Postman** [comment] 2020-03-06 21:32
@Raja-Simha I think this issue may be separate from #1070. #1070 refers to re-ordering examples, this issue notes that there is a disparity between the order shown in the app, and what is shown on a documentation page. Can we re-open?

**Comment by Raja-Simha** [comment] 2020-03-09 08:13
These two issues result from the same underlying limitation. We will be fixing both of these together. I will re-open just in case.

**Comment by godfrzero** [comment] 2020-03-09 08:28
@JP-from-Postman Is the order of examples returned in the Postman API incorrect as well? If so, this is a syncing issue and is not limited to documentation.

**Comment by JP-from-Postman** [comment] 2020-03-09 17:20
@godfrzero just tried pulling this collection via the Postman API and the example order is jumbled in the response too. Is that what you were referring to?

**Comment by godfrzero** [comment] 2020-03-09 19:58
Yep, the ordering in the Postman API response should match that in the documentation, but not match the one in the app. If that's the case, that means the data was incorrectly synced.

**Comment by JP-from-Postman** [comment] 2020-03-09 22:45
@godfrzero OK, so the API response _does_ match what is on the docs page. They are both different from what is shown in the app though.

**Comment by sony-mathew** [comment] 2024-09-02 19:24
Hey @JP-from-Postman 
We've been continuously improving our documentation to better serve you. Regarding your issue, this is no longer reproducible with the latest versions of the app. (Please note that there might a 2 minute caching on the published documentation, do try to refresh the page after changing the order after 2 minutes if you don't see the changes reflected immediately)

We hope this resolves your issue. If you have any further concerns or questions, please feel free to reopen this discussion. We're here to help and support you.

**Closed as completed by sony-mathew** 2024-09-02 19:24 UTC
Labels: feature, product/documentation
