### ISSUE TITLE
Code view not including Headers for curl (and probably others)

### ISSUE THREAD

**Issue by bberliner** [a85/POSTMan-Chrome-Extension#8597] opened 2020-06-06 00:52 UTC
**Describe the bug**
With Version 7.25.0, the "Code" view (whether using "New Code Generation Mode" or not) will not include all of the Headers you have enabled for your request, if the request already exists.

**To Reproduce**
1. Find an *existing* request that includes some pre-selected Headers
2. Press the "Code" button to see the curl command (I've only tested with curl).
3. Notice that the request does not contain all of your Headers

**Expected behavior**
It used to include all the `--header` values correctly in the curl command.

**Screenshots**
This is for an Okta request (not that it matters)...
![Screen Shot 2020-06-05 at 5 49 01 PM](https://user-images.githubusercontent.com/1403561/83932032-e2a86680-a754-11ea-89e2-d9dcf7f01da1.png)
![Screen Shot 2020-06-05 at 5 49 46 PM](https://user-images.githubusercontent.com/1403561/83932044-f6ec6380-a754-11ea-8359-60bb34971bd9.png)

**App information (please complete the following information):**
 - MacOS Postman App
 - Postman Version 7.25.0
 - OS: macOS Catalina 10.15.5

**Additional context**
If you de-select the Header in the Postman Edit window and reselect it, it will then be included in the `Code` preview. But, I have lots of headers in all my requests, so this is not a useful workaround.

**Comment by shreys7** [comment] 2020-06-06 09:25
duplicate of #8550

**Closed as completed by shreys7** 2020-06-06 09:25 UTC
