### ISSUE TITLE
Support authentication prompts in OAuth 2.0 access token flow

### ISSUE THREAD

**Issue by skeletozaure** [a85/POSTMan-Chrome-Extension#5888] opened 2019-02-06 16:39 UTC
**Describe the bug**
I cannot retrieve an oauth 2.0 access token using a custom callback URL

**To Reproduce**

1. Create a new request
2. Go to tab 'Authorization'
3. Set type to 'OAuth 2.0'
4. Click 'Get New Access Token'
5. Specify settings to obtain a token from Azure AD. Select Grant Type 'Authorization Code'. Specify the Callback URL according to the setting in your AAD App (in my case https://arcelormittal.onmicrosoft.com/MicrosoftGraphClient).
6. When i click "Request Token" a page is opened where i can enter my Professional Azure Account, then a message says that i'm going to be redirected to the connexion page of my Organization.  I end up with a blank popup screen with title 'Connectez-vous à votre compte'. No access token is obtained.

**Expected behavior**
I go to my login screen. After logging in, I return to Postman and have obtained an access token.

**App information (please complete the following information):**

* App Type: Windows native
* Postman Version: 6.7.3
* OS: Windows 7 Pro x64

**Comment by harryi3t** [comment] 2019-03-28 08:23
This looks like a duplicate of #4246

@skeletozaure I think this might be happening because the page requires a basic/NTLM authentication which normally shows a prompt in a web browser to allow the user to enter the username and password.
Since Postman is built on top of Electron and Electron does not support these prompts you see a blank page.
You can confirm this by trying to open the same URL in your browser. You can get hold of this URL by opening the Postman app from a terminal and then follow the normal steps in your Postman app. After you click on `Request Token` when the Oauth2 windows appear, looks for a URL in the terminal. Just copy the URL and open in your web browser (please use incognito mode).

It would look something like this
![harryi3t_Harendras-MacBook-Pro____work_postman_postman-app__zsh__and_Obtain_OAuth_2_0_access_token_with_custom_callback_URL_from_Azure_·_Issue__5888_·_postmanlabs_postman-app-support](https://user-images.githubusercontent.com/5207331/55141316-2ae6f480-5160-11e9-9196-b3344f1ea865.png)

Continue with the authentication in the browser, if any stage you see a prompt that would confirm the assumption.
For reference, you see this [gif posted by another user](https://github.com/postmanlabs/postman-app-support/issues/4246#issuecomment-369261507) facing the same issue 
![oauth-2-azure-issue](https://user-images.githubusercontent.com/2364632/36793969-f3334dd2-1c6c-11e8-9f09-b64ca864498a.gif)

**Comment by vikiCoder** [comment] 2020-05-10 05:27
Hi,

We've added an option in OAuth2 that allows you to authenticate using your system's default browser while generating OAuth 2.0 token. That should solve the problem. Check out [my comment](https://github.com/postmanlabs/postman-app-support/issues/7700#issuecomment-626273229) on a [similar issue](https://github.com/postmanlabs/postman-app-support/issues/7700) for more details. Feel free to reopen the issue if the problem still persists.

**Closed as completed by vikiCoder** 2020-05-10 05:27 UTC
Labels: bug, OAuth2, product/runtime
