### ISSUE TITLE
Can't send request if environment variable is used in request path

### ISSUE THREAD

**Issue by ilyanikolov** [a85/POSTMan-Chrome-Extension#5117] opened 2018-08-30 11:24 UTC
**Describe the bug**
Can't send request if environment variable is used in request path

**To Reproduce**
1. Create environment variable, for example "host: https://google.com";
2. Create new request, with url {{host}}
3. Try to execute request;

**Expected behavior**
Request should be send successful :)

**Screenshots**
![image](https://user-images.githubusercontent.com/14236313/44848394-45ef9580-ac5f-11e8-8695-fee7dc7e4a52.png)
![image](https://user-images.githubusercontent.com/14236313/44848413-50119400-ac5f-11e8-9a06-19600f131a4f.png)
![image](https://user-images.githubusercontent.com/14236313/44848453-77686100-ac5f-11e8-9427-e2e176bf161f.png)

**App information (please complete the following information):**
 - Native app
 - Postman Version 6.2.5
 - OS: Linux (linux 4.15.0-32-generic / x64)

**Additional context**
If I use url not variable in request path everything works fine;

**Comment by Discipe** [comment] 2018-08-30 12:34
Hm... Environment variable in URI works for me, but i get "Could not get any response" error if header key or value is an Environment variable (in my case, variable is nested "Key": "SomeValue-{{info}}"). 

That problem showed up after 2.6.4(?) -> 2.6.5 upgrade. In previous version everything worked (I think it was 2.6.4, but I may be mistaken here).

Looks like issue #5039 and probably caused by update.

**Comment by harryi3t** [comment] 2018-08-30 13:36
@ilyanikolov This seems like similar to the issue https://github.com/postmanlabs/postman-app-support/issues/5039 reported earlier 

Could you run through the [instructions](https://github.com/postmanlabs/postman-app-support/issues/5039#issuecomment-415727976) as mentioned in that issue and share the output?

Closing this issue in favor of the original issue.

**Closed as completed by harryi3t** 2018-08-30 13:36 UTC
