### ISSUE TITLE
Double // in route causes POST and PUT to be sent as GET

### ISSUE THREAD

**Issue by jengwood** [a85/POSTMan-Chrome-Extension#5599] opened 2018-11-30 23:56 UTC
The double "//" in the first part of the route below causes all requests to be sent as a GET. Technically, the URL is invalid, but the request should not go through as a GET

POST //[]/[] HTTP/1.1
Host: api-public-stage.[].com

This request from the HTPP code gets sent as a GET through Postman. When looking at the cURL code, it gets converted correctly into only one "/" in the route.

 - App Type: Native App
 - Postman Version: Version 6.5.3

**Comment by numaanashraf** [comment] 2018-12-03 09:33
@jengwood This looks like a duplicate of #4114. As of now, Postman changes POST & PUT to GET while following a redirect. We are working on giving more control of this behavior to our users.

**Closed as completed by numaanashraf** 2018-12-03 09:33 UTC
