### ISSUE TITLE
Test case names in Collection Runner Run Summary showing wrong failed tests

### ISSUE THREAD

**Issue by FCulig** [a85/POSTMan-Chrome-Extension#8971] opened 2020-08-25 11:54 UTC
When I run my tests using Collection Runner, Run Results shows me tests that failed and this is correct. But when I click on Run Summary it shows wrong tests failing and red crosses and green checkmarks are also wrong.

**To Reproduce**
1. Run tests using the collection runner
2. After runner is finished compare test names in Run Results and Run Summary

**Expected behavior**
Tests names should not be diffferent.

**Screenshots**
Tests in Run Results
![1st](https://user-images.githubusercontent.com/36075622/91171092-35e9df80-e6da-11ea-92b2-cd25adab8278.png)
Tests in Run Summary
![2nd](https://user-images.githubusercontent.com/36075622/91171096-36827600-e6da-11ea-999e-7755d9b80e34.png)

 I removed the request name because it had sensitive information. I triple checked that I'm not looking at the wrong request.

**App information (please complete the following information):**
 - Postman Version Postman v7.31.0
 - OS: Windows 10 Enterprise version 1909 build 18363.592

**Additional context**
I have started noticing this bug after update to 7.31.0

**Comment by DannyDainton** [comment] 2020-08-25 12:51
Hey @FCulig

It's a little difficult to see what's happening due to the reduced size of the images - are you able to expand those but still mask the sensitive details.

Are all the requests in the Builder saved, this might be impacting what you're seeing? Unsaved changes are not reflected in the Runner and could cause some unexpected behaviour. 

Have you confirmed that it's the right Summary for that run?

**Comment by FCulig** [comment] 2020-08-27 07:36
Here are screenshots of the whole collection runner window:

(Some test results changed because we are actively developing the API)

![Run summary](https://user-images.githubusercontent.com/36075622/91411205-4ae48100-e848-11ea-8cbf-228c36ea2ca9.png)
![Run results](https://user-images.githubusercontent.com/36075622/91411208-4c15ae00-e848-11ea-822a-519ceb548abe.png)

I tried replicating bug with other collections, duplicating this collection and could not replicate it.

**Comment by coditva** [comment] 2020-08-27 07:57
Hey @FCulig, thanks for the info! I could reproduce the issue. Seems like the failing tests are getting mixed up in the summary view with the passing tests. I've marked this as a bug and will post all updates for this on this thread.

**Comment by timbochamp** [comment] 2021-01-18 19:50
@FCulig This should now be fixed this issue in the latest Postman Canary application (v8.0.0-canary09), as well as in Postman for Web. Can you please try it out and confirm if it's fixed for you?

**Comment by timbochamp** [comment] 2021-01-27 16:23
I'm going to close this out but please feel free to reopen again if you encounter wrong failed tests in the run summary view in the Postman Version 8.0.2 app or on Postman for Web.

**Closed as completed by timbochamp** 2021-01-27 16:23 UTC
Labels: bug, collection-runner, product/runtime

**Comment by Mark0l** [comment] 2023-04-19 12:35
The bug is present again. Tests marked as failed are one position below the actual failed tests.

**Comment by timbochamp** [comment] 2023-04-19 13:01
> The bug is present again. Tests marked as failed are one position below the actual failed tests.

@Mark0l could you please raise a new issue for this with the Bug Report template filled with the relevant information? The version you're using, recording showing the type of run results you're seeing as malformed, and other information would be useful to help unravel this
