### ISSUE TITLE
Could not login via Google 

### ISSUE THREAD

**Issue by akadatsky** [a85/POSTMan-Chrome-Extension#7798] opened 2019-12-13 15:43 UTC
Could not login by using Google with reason "This browser or app may not be secure".
I have the latest Postman v7.13.0  installed on Linux.
And actually I can't use the app because I don't have other login option and can't skip it.

![Screenshot from 2019-12-13 17-39-55](https://user-images.githubusercontent.com/2796990/70812126-af050900-1dcf-11ea-904b-8a511ed015c8.png)

**Comment by rbudnar** [comment] 2019-12-13 19:49
I've got the same issue as well using the app on Windows 10.

**Comment by xscheck** [comment] 2019-12-15 04:25
Another data point if it matters: I am getting same error on Mac OS X (Catalina 10.15.1). Postman v7.13.0.

**Comment by harryi3t** [comment] 2019-12-16 04:40
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/7700

**Closed as completed by harryi3t** 2019-12-16 04:40 UTC
