### ISSUE TITLE
Add the possibilities to set custom headers for auth request

### ISSUE THREAD

**Issue by tychota** [a85/POSTMan-Chrome-Extension#4774] opened 2018-07-04 13:46 UTC
**Is your feature request related to a problem? Please describe.**

I have an *oAuth2* api with *password* grant.
This api expect the header `x-client` to be set (see the redacted curl request under this)

```
curl 'https://my.domain/oauth/access_token/' 
  -H 'Referer: http://localhost:3000/' 
  -H 'Origin: http://localhost:3000' 
  -H 'X-Client: blurp.blop.fr_FR' 
  --data-binary '{
    "blackbox":null,
    "grant_type":"password",
    "password":"**********",
    "username":"********@*******.fr"
}' 
  --compressed
```

=> 😵I struggled setting this  `X-Client: blurp.blop.fr_FR` headers.

**Describe the solution you'd like**

I would like to have the possibility to set up custom headers for the auth request.

<img width="618" alt="untitled" src="https://user-images.githubusercontent.com/13785185/42280426-069d20ae-7fa1-11e8-8a32-cf0403684df0.png">

**Describe alternatives you've considered**

Having the pre request scripts able to set headers, also for auth requests.

![image](https://user-images.githubusercontent.com/13785185/42280548-543c4740-7fa1-11e8-931b-fb9a11782173.png)

**Additional context**

My postman version : 6.1.4

**Comment by numaanashraf** [comment] 2018-07-04 15:33
Thanks for the feature suggestion @tychota.

**Comment by harryi3t** [comment] 2018-07-05 06:07
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/2523

**Closed as completed by harryi3t** 2018-07-05 06:07 UTC
Labels: feature

**Comment by tychota** [comment] 2018-07-05 06:59
@numaanashraf  is it something i can contribute with the open source directories or that ui part is closed source ?

**Comment by numaanashraf** [comment] 2018-07-05 07:04
@tychota Postman's core request sending library is open-sourced and we invite contributions there. But the OAuth2.0 flow is implemented outside of this library (As it depends on user interaction) and it is closed source.

**Comment by tychota** [comment] 2018-07-05 07:15
All clear.
Lets wait then.

**Comment by tychota** [comment] 2018-07-05 09:30
I posted a work around in https://github.com/postmanlabs/postman-app-support/issues/2523#issuecomment-402662519.

Basically it is using Charles proxy rewrite rules to add the headers while waiting for the feature to be implemented.
The above comments document my workaround with images so should be easy to follow (max 5 min) and hopefully save people coming to this issue some times.
