### ISSUE TITLE
API Docs cannot be loaded

### ISSUE THREAD

**Issue by danurahadi** [a85/POSTMan-Chrome-Extension#9370] opened 2020-12-16 05:59 UTC
My public API Docs cannot be loaded properly. Always loading with `Just a moment...` text. 

**Steps to reproduce**

 - Create a team workspace (I use team plan for now)
 - Create a collection & some requests inside
 - Publish Docs

**Error on browser console**

`content.js:48 Uncaught (in promise) TypeError: this.engines is not iterable
    at E.updateSocialMedia (content.js:48)
    at new E (content.js:48)
    at Function.start (content.js:48)
    at Function.main (content.js:48)`
    
**Environment Information**
  - OS Windows 10 latest version
  - Google Chrome latest version    
    
    
This error happens frequently in some of my collections. I hope you can follow up this issue soon.
Thanks for your attention.

Regards, Argi

**Comment by ranchanarajasekaran** [comment] 2020-12-21 10:14
@danurahadi Thank you for reporting this issue .
Can you please share the url of the public docs ?

**Comment by danurahadi** [comment] 2020-12-31 09:03
@ranchanarajasekaran this is my API Docs :
https://documenter.getpostman.com/view/982160/SW7W6Vmy?version=latest

Maybe there is some unstable code on postman app, because sometimes the docs can be loaded properly, but sometimes not and return that errors above.

Thanks for your reply.

**Comment by godfrzero** [comment] 2021-01-04 06:48
@danurahadi Does this error ever show up in incognito as well (with extensions disabled?).

**Comment by danurahadi** [comment] 2021-01-07 07:52
@godfrzero yes, i've tried that and the API Docs cannot be loaded.
sorry for my slow response

**Comment by godfrzero** [comment] 2021-01-07 12:24
Got it, thanks for letting me know @danurahadi. The reason I asked is because the error mentioned in the original description isn't coming from code we're shipping. We've also been unable to reproduce the issue with the API docs link. `content.js` is a file commonly present in Chrome extensions (https://developer.chrome.com/docs/extensions/mv2/content_scripts/).

Does this error show up in other browsers as well? If so, we may have to move this conversation to help@postman.com.

**Comment by danurahadi** [comment] 2021-01-08 08:22
@godfrzero Yes, the error also show up on Firefox & Edge. Other members in my team also got this error on their browser, Chrome & Firefox. I don't know if that error is caused by some browser extensions or not. 

I just wanna reporting that sometimes the API Docs can be loaded properly, and sometimes not. Also, the performances of the API Docs is too slow.

Thanks for your reply

Regards, Argi

**Comment by godfrzero** [comment] 2021-01-18 05:04
@danurahadi We haven't been able to reproduce the problematic behavior on any environments. Would you mind shooting us an email at help@postman.com so we can take a closer look?

**Comment by danurahadi** [comment] 2021-01-19 05:14
@godfrzero okay, we can move this issue to help@postman.com. thanks so much for your support.

**Comment by Raja-Simha** [comment] 2021-04-15 11:33
@danurahadi is this issue resolved through our support channel? If not you can re-open this issue. I am closing this for now.

**Closed as completed by Raja-Simha** 2021-04-15 11:33 UTC
Labels: bug, product/documentation
