### ISSUE TITLE
Run whole subfolder or selection within the builder view using sidebar

### ISSUE THREAD

**Issue by cen1** [a85/POSTMan-Chrome-Extension#4568] opened 2018-05-17 08:47 UTC
**A clear and concise description of what the problem is.**
A lot of times I have a subfolder with **prep calls** such as auth and some other stuff that sets global variables which are then used across further integration tests.

Manually running these calls one by one is tedious, especially if I am switching environments and they need to be re-run or if I need to rerun due to changes on the backend.

**Describe the solution you'd like**
Scenario 1: Right click on subfolder->Run all requests.

Scenario 2: select requests (select+shift or ctrl+select) and run selected requests.

**Describe alternatives you've considered**
Using the Runner (Scenario 1).

**Comment by numaanashraf** [comment] 2018-05-17 08:55
@cen1 Have you tried running the folder via the Collection Runner? https://www.getpostman.com/docs/v6/api_testing_and_collection_runner/running_collections

**Comment by cen1** [comment] 2018-05-17 09:48
Yes, I know about the runner and persisting the variables but it seems inconvenient. It's a seperate window which I need to have set up, then I need another runner window when running automated tests etc. I also have to switch environments in main and runner window, it's not synchronous.

I'd expand my idea even further, instead of running whole folder, to run a **selection** of requests, eg: select+shift or ctrl+select to highlight the wanted requests, then run them with single action.

**Comment by numaanashraf** [comment] 2018-05-17 10:22
Thanks for the feature suggestion @cen1.

**Comment by vkaegis** [comment] 2018-07-03 07:22
#4705

**Comment by saswatds** [comment] 2019-05-21 19:45
Duplicate of #6360 #2392

Closing this issue to track the feature at a single place

**Comment by shamasis** [comment] 2019-06-03 20:14
@cen1 - I’ve tweaked the title of the issue to better reflect the use case and reopened the issue.

**Comment by giridharvc7** [comment] 2021-04-13 20:11
You can now drag drop a subfolder into the collection runner, let us know if this solves your problem @cen1

**Closed as completed by giridharvc7** 2021-04-13 20:11 UTC
Labels: feature, collection-runner, product/runtime
