### ISSUE TITLE
POST is missing body and content-length

### ISSUE THREAD

**Issue by frankvandebergh** [a85/POSTMan-Chrome-Extension#3780] opened 2017-11-11 19:20 UTC
## App Details:

```
Postman for Mac
Version 5.3.2
10.13.1
OS X 10.13.1 / x64
```

## Issue Report:
 1. I'm trying to perform oauth token request to Azure AD. A post request with body as x-www-form-urlencoded containing 3 parameters.

The result is 400 because of missing grant_type parameter in the body. 
Console logs show that the body is not sent and content-length header is empty. 

 2. Console logs :

> 
>
>POST /99f28ad2-fd43-4ff1-b12c-9792c9ec06b8/oauth2/token
>cache-control: no-cache
> postman-token: 0d8e116e-ffc9-4743-bc33-fc4a4a0b2828
content-type: application/x-www-form-urlencoded
user-agent: PostmanRuntime/6.4.1
accept: */*
host: login.microsoftonline.com
cookie: esctx=AQABAAAAAABHh4kmS_aKT5XrjzxRAtHzlFjxDXVhx93vAOMy2_zth95cFuTeFOsM4NRrxfenZDxXNYuPdW1NpFK25OcAfbIekbMFhUlaUAssI52Ewi2eihGCxPwNGdEzopWqCp5ZN9gN35J4jzQ7zXZ00Msi_wo02yu_Yqj7-JOlBybMPPg-IZA7l5WwcN49K0uZY-zUZmggAA; x-ms-gateway-slice=004; stsservicecookie=ests
accept-encoding: gzip, deflate
content-length:

**Comment by sdnts** [comment] 2017-11-15 05:36
@frankvandebergh Are you using the in-built authorization methods to make this request or are you generating this body on your own?

**Comment by hoffepoffe** [comment] 2017-11-23 14:38
I'm having the same problem. POSTs with body (application/x-www-form-urlencoded) are sent without the body and content-length: 0. Postman captured an AJAX request from Chrome, and then I resent it with Postman. I can see in Wireshark that Chrome sends the full request with body (also shows up in Postman), but when I send the POST again in Postman, I can see in Wireshark that it's sent without the body and content-length: 0.

Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64

**Comment by brianalbrecht** [comment] 2017-11-30 06:29
I have the same issue.  I captured a request from chrome and I observe the following behaviors:

1.  When I send the captured POST request with x-www-form-urlencoded, no body is sent. (I also verified with wireshark)
2.  I cannot change the URL.  Even if I change it to POST to https://requestb.in/xxxx it still sends to the original URL.

My requests did not use authorization at all.

Postman for Mac
Version 5.3.2
macOS High Sierra (10.13.1)

**Comment by rkgrep** [comment] 2018-01-18 15:26
+1. Same issue. Content-Length is not set.
Postman for Mac
Version 5.5.0

**Comment by walfud** [comment] 2018-01-23 06:13
I send a GET request with form data in url(localhost:3000/api/num?price=0). No Content-Length be filled in header. 
Postman for Windows
Version 5.5.0

**Comment by amtsing** [comment] 2018-02-06 03:25
This issue can be worked around by using "Bulk Edit".

**Comment by harryi3t** [comment] 2018-08-01 13:35
@frankvandebergh @amtsing @rkgrep @hoffepoffe @brianalbrecht 
Is this still happening in the latest version of Postman? Can anyone please test this and let us know?

**Comment by saifuddinrangwala** [comment] 2018-08-28 15:43
Encountering the same issue.  Content-Length header is missing in the request. Due to this server will drop the connection. The same request and payload works fine with curl. Only difference is that Content-Length is missing in case of postman.

**Comment by harryi3t** [comment] 2018-08-30 12:09
@saifuddinrangwala What version of Postman are you using?

**Comment by shamasis** [comment] 2018-09-19 15:07
Note: 

The original issue was around missing grant type "The result is 400 because of missing grant_type parameter in the body." Down the line, additional similar issue has been added - which has not been linked to a common cause.

We would need more details to replicate the issue, since for POST methods in general cases, the content length was sent reliably. We should discuss what are the specific scenario where this fails.

**Comment by bcatalin** [comment] 2018-10-13 10:42
I have the same issue. Backend is express. I am using the latest version 6.4.2

**Comment by codenirvana** [comment] 2019-02-21 05:44
@bcatalin We are not able to reproduce this issue. Can you share more info like request body type, method etc? If possible share a sample express server where you are facing this issue.

**Comment by shamasis** [comment] 2019-06-17 18:05
This issue has become difficult to triage. Original issue was around oAuth1 and subsequent issues are filed on the issue title and not as per description.

I suggest that we retry sending request ensuring that content length and content-type headers in the request is not set or set appropriately before sending request. For form-data and other types, content length is auto calculated and content-type i auto set. Refer to "temporary headers" section we added in v7.0 that shows what got auto-added.

**Comment by abhijitkane** [comment] 2019-06-17 18:09
@bcatalin @saifuddinrangwala  We can split this into two possible issues:

1. Postman not capturing the request correctly: This will need detailed information on how the request is being captured - using either the proxy or interceptor, and the Postman version
2. The content-length not being sent: Postman doesn't re-compute the content-length if it has been explicitly set by the user, or is present in the captured request. We'll need the exact captured request in order to debug this.

@frankvandebergh - If you're still able to reproduce this in v7.x of Postman, I'd suggest filing a new issue.

Closing this for now.

**Closed as completed by abhijitkane** 2019-06-17 18:09 UTC
Labels: bug, product/ops

**Comment by YanivHaramati** [comment] 2021-03-25 18:24
Still an issue with postman 8.0.7 as of 2021.03.25

**Comment by acevos01** [comment] 2021-09-29 17:59
this issue is still happening with v9.0.3 as of 2021.09.29. What I did was close the browser and postman. Opening them again and doing the same requests worked. Hope it helps
