### ISSUE TITLE
I am Trying to set time out to zero but automatically it changes to 300 or something unable to set timeout to zero

### ISSUE THREAD

**Issue by Nasirkhan-259** [a85/POSTMan-Chrome-Extension#8670] opened 2020-06-17 07:10 UTC
I am trying to set timeout to zero but sometimes the settings window not showing, or i am unable to set time out to zero, strange behaviour 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40949696/84867364-7d2d7180-b094-11ea-966c-f196f5385adf.gif)
Some strange behaviour

**Comment by cyrielle-hada** [comment] 2020-06-19 16:47
@Nasirkhan-259 I was able to reproduce the issue. I then quitted the app and reopened it, and I don't seem able to replicate again ever since. Would you try that and see if this helps?

**Comment by Mechanicalkeyboard** [comment] 2020-09-11 15:08
This looks like it was resolved in a previous release. If the issue is experienced again, please re-open! Thank you

**Closed as completed by Mechanicalkeyboard** 2020-09-11 15:08 UTC
Labels: bug, product/runtime
