### ISSUE TITLE
Documentation confusing when it comes to variable scopes for local variables

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#4052] opened 2018-01-10 20:44 UTC
First of all, what is a local variable anyway? The [documentation](https://www.getpostman.com/docs/postman/environments_and_globals/variables) refers to them, but no example is given. So my understanding is that a local variable is a variable that I defined inside a pre-request or tests section, like:

`var foo = "bar";`

The documentation gets more confusing after you read this:

> The following scopes are available to you:
> 
> Global
> Collection
> Environment
> Local
> Data

It seems that you cannot access local variables by using the Postman API or the request builder.

If this is the case, why does **scope** play any role?  When can you override a global or environment variable with a local one?

Thanks for clarifying.

**Comment by sivcan** [comment] 2018-01-11 13:09
Hi @vdespa. 
Variables are simply used in Postman the way you actually use them in a programming language.

Let's look at an example : 
Suppose you want to hit the 2-3 domains with a simple get request as : 
**url-to-be-hit/get?test=params-to-be-added**

The way we'll be using it in the request builder is  : 
**{{domain-url}}/get?test={{params}}** 

Now, for domain-url's you can set them as **environment variables** and all other requests under the environment will be able to use that variable.
<img width="366" alt="env" src="https://user-images.githubusercontent.com/12631777/34826231-ca5de890-f6fb-11e7-84d3-5d5858eeb843.png">

You can 'edit' this and set the domain-url as per your need. 
Also, you can easily add params and check what you need and what you don't need. 
Now you can also, use variables inside params. 
<img width="1608" alt="testvars" src="https://user-images.githubusercontent.com/12631777/34826417-73b4a302-f6fc-11e7-9066-c7cd6fe5068c.png">


Now if you run the request, postman will resolve the variables and hit the correct url. 
You can change the domain-url multiple times or using scripts. (pm.global / pm.environment) depending on the variables scope. 
You can also use scripts to manipulate variables.

Scopes: 
- Environment variables can be accessed with the corresponding environment template. 
- Collection variables can be accessed from a request within the collection. 
- Global variables can be accessed broadly regardless of the selected environment.
- Data Variables - If you've used the Collection Runner then it allows you to import a data file and then use the values from the data file inside HTTP requests and scripts. To use them inside Postman, follow the same syntax as environment or global variables. 

Local : Variables that you'll be defining in the scripts and using them will be local to those requests. 
They also exist during the execution of the a complete collection run. They're pretty complex to be explained here but I am sure the documentation will cover the more technical details around this in the future.

Global variables will not be overwritten with local variables. 

Hope this clarifies your issue.
Let me know if you need more information.

**Comment by vdespa** [comment] 2018-01-11 16:27
Thanks for your long response.

I still consider the documentation confusing, as it puts the local variables in the same "bucket" as the rest of the variables.

**Comment by sivcan** [comment] 2018-01-11 17:41
@vdespa - No problem. 
We'll look over the same and see what we can change to make it even more easier to understand.
I'll be closing this issue now. 
If you feel that there's still anything that's not clear then feel free to reach out.

**Closed as completed by sivcan** 2018-01-11 17:41 UTC
Labels: support, product/documentation

**Comment by mistaecko** [comment] 2018-03-22 10:27
The documentation is still confusing. No mention of `pm.variables.set(key, value)` which my guess is what the "local" scope refers to.

**Comment by vdespa** [comment] 2018-03-27 08:53
@mistaecko of course it is still confusing 😕

**Comment by verglor** [comment] 2018-04-25 06:40
@vdespa There actually is a local scope API:
`pm.variables.set` - is setting local scope variable
`pm.variables.get` - is getting local scope variable or closest scope variable if not set locally

Quite confusing - I agree.

**Comment by vdespa** [comment] 2018-05-06 10:40
@verglor Indeed your are right. I have missed that.

Thanks for pointing that out.

**Comment by BorysFursov** [comment] 2018-05-16 11:42
@vdespa Also I noticed that Local VariableScope doesn't keep it's condition! It is clear again when next request starts

**Comment by p00j4** [comment] 2018-07-18 14:41
@sivcan  having a confusion, how can we define and reuse a collection level variable using the script (pass between requests)? 

**Use case:** In a collection, I have multiple requests and want to pass variable value updated from one request to another. Don't want to set in environment variable because they(my variables) are always changing and they are many. 

Tried with,  pm.variables.set(key, value) but
- As it's scope is only within the same request and hence not useful to get in another request (its scope is lost)
- also I couldn't figure the usecase for **pm.variables** because within the same request, could go directly with javascript variable.  **Edit**: oh Yes, this one is fine, this can be useful in passing to the same request building from per-request script if any. 

Now only query is, which way can use Collection level variables can be created using the postman scripts on the fly? 
The [doc](https://www.getpostman.com/docs/v6/postman/environments_and_globals/variables) here talks about per-defining the collection level variables which is not useful in above case

**Comment by sivcan** [comment] 2018-07-19 07:25
@p00j4 Collection variables cannot be updated through the scripts.
The only way is to use environment variables/globals.

However, since you've mentioned that your variables keep changing frequently and I suppose you don't want to update them with dirty data, I think the **sessions** in postman might fit your use-case well.
You can read the public RFC here: https://community.getpostman.com/t/sessions-in-postman/1925

**Comment by tparikka** [comment] 2018-12-12 18:58
I landed here because the documentation at https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#variable-scopes is still very confusing. Lack of concrete examples of what these scopes mean, particularly local, is in my opinion a major shortcoming in that section of the docs.

**Comment by sivcan** [comment] 2018-12-12 22:56
Hi @tparikka, we're working around improving our docs and as you can see here https://github.com/postmanlabs/postman-docs/issues/1442, the issue is already open.
You follow the thread for updates regarding the variables docs. 

Thanks!

**Comment by vdespa** [comment] 2019-03-07 05:09
I decided to write an article on this topic: https://medium.com/@vdespa/demystifying-postman-variables-how-and-when-to-use-different-variable-scopes-66ad8dc11200

I hope this helps somebody.

**Comment by willpoorman** [comment] 2019-04-25 18:30
That actually did help clear up a decent amount of my confusion @vdespa. Though it looks like you can actually override Collection variables in scripts, at least in the pre-request script.

Today I set the variable {{port}} in my collection  to a default value and in a pre-request script i used `pm.variables.set('port', 'ANOTHER')` then ran the request. I checked the request it generated and it shows that it used the value ANOTHER rather than the default one set it in the collection

**Comment by willpoorman** [comment] 2019-04-25 18:33
I have a gripe about the fact that local variables don't have a way to set them via in UI element like the Global, Collection, and Environment variables do. If there was a tab in the request for setting a variable specific for that request rather than our only option being to set it in the pre-request script, that would be nice. Especially since setting them in the pre-request script doesn't allow for the UI to pick up on what the value will be set to, so when you hover over the variable where you're using it, it doesn't show you what the value will be set to when it runs, which is something the UI can do if it was set from any of the other variable types.
