### ISSUE TITLE
Postman runner does not run the entire collection

### ISSUE THREAD

**Issue by ankr11** [a85/POSTMan-Chrome-Extension#3157] opened 2017-06-13 21:47 UTC
We have a collection with folders which contain our API tests. However, only a portion of the tests are running every now and then. So, out of 115 requests, only 15 are being executed. Sometime only 38 out 115, other time (rare) the whole 115 will run.

Multiple users experiencing this.

![screen shot 2017-06-13 at 2 46 14 pm](https://user-images.githubusercontent.com/29413987/27140905-91841d76-50db-11e7-9571-9855e5609020.png)

## App Details:
```
Postman for Mac
Version 5.0
OS X 16.4.0 / x64
```

**Comment by kamalaknn** [comment] 2017-06-14 06:34
Hey @ankr11 

Thanks for reporting this. We are seeing this too. 

We'll roll out a fix for this in the next version. I'll update this thread once the fix is out.

Thanks.

**Comment by kamalaknn** [comment] 2017-06-14 11:43
Hey @ankr11 

Could you export a collection where you are seeing this and send it to `help@getpostman.com`? It will help us narrow down the issue.

Thanks.

**Comment by a85** [comment] 2017-06-14 15:16
@ankr11 The number of requests in your collection can be different than the number of tests within them. Are you treating each request as a single test? If yes, you should have one test in the sandbox in each of them.

**Comment by ankr11** [comment] 2017-06-14 15:23
Hi @kamalaknn,

Thank you for a reply, but unfortunately I won't be able to export a collection and provide it to you. The collections are being used as an API tests for the company I am working for, so that would be a security breach and violation of the NDA I am under.

**Comment by ankr11** [comment] 2017-06-14 15:32
@a85 I do treat each request as single test. However, I'm not sure I understand what do you mean by having a one test in the sandbox. Do you mean one test per collection? The way I structured it, is by having one collection, containing folders with requests in them.

**Comment by a85** [comment] 2017-06-14 15:33
@ankr11 Your collections need to have one test in each request's test script. Explained in docs here: https://www.getpostman.com/docs/postman/scripts/test_scripts

**Closed as completed** 2017-06-28 20:17 UTC
Labels: bug

**Comment by VigneshwariSrinivasan** [comment] 2019-11-04 04:52
Hi,
Is this issue fixed.Because iam facing a similar issue.
I cant able to find any updates on this issue.

**Comment by ChrisCooney** [comment] 2020-03-20 13:29
I'm presently experiencing the exact same thing!

**Comment by tsimms** [comment] 2020-07-01 14:19
I'm seeing it also.

**Comment by arlemi** [comment] 2020-07-08 14:41
I wasn't able to replicate that issue, please provide us with a way to reproduce the issue (collection export for example) or a video showing it happen, this will help us investigate. 

Did you double check that all folders/requests were checked when running the collection ?
