### ISSUE TITLE
no response when i add a http header key like  x-mmm-sign

### ISSUE THREAD

**Issue by tiptok** [a85/POSTMan-Chrome-Extension#7406] opened 2019-09-30 08:03 UTC
**Describe the bug**
no response when i add a http header key like  x-mmm-sign:1234546

**Screenshots**
native app
![image](https://user-images.githubusercontent.com/16175379/65859122-0fbca200-e39a-11e9-9ea1-57eb5511268b.png)

![image](https://user-images.githubusercontent.com/16175379/65859175-29f68000-e39a-11e9-9ba8-83dea28596c5.png)

on chrome app  this problem does not occur
 
![image](https://user-images.githubusercontent.com/16175379/65859542-041dab00-e39b-11e9-9bc2-1b61a2820677.png)

**App information (please complete the following information):**
 - Native App
 - Postman v7.8.0-canary02
 - OS: win10

**Comment by codenirvana** [comment] 2019-09-30 10:08
@tiptok Looks like the problem is not with header name like `x-mmm-sign` but the header value which has a newline (notice `...` in the header value field).

I hope removing the newline will fix your issue.

Closing as duplicate of #3835

**Closed as completed by codenirvana** 2019-09-30 10:08 UTC
Labels: duplicate, product/runtime
