### ISSUE TITLE
Pre-request Script shows blank, even if the Script is written

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#4866] opened 2018-07-23 11:22 UTC
**Describe the bug**
I have a collection of 20-21 requests in a post man collection and each request has its own pre-request script and each request is with in a folder. if i try to open a pre-request script tab from the "..." option by clicking edit, the pre-request script tab is empty. and clicking on the middle of the screen, shows the populated script.

**To Reproduce**
1. create a folders and inside them create sub-folders and inside them create a request
2. Populate pre-request script tab with random code for each sub-folders. (code is at least 30-40 lines).
3. save and close the pre-request script tab.
4. click on the "..." menu for the sub-folder
5. click on the edit option.
6. click on the pre-request tab.
7. You will see an empty tab, even though you populated the pre-request script in 2.
8. Now click in the middle of the screen, you would see the code appear.

**Expected behavior**
Code should appear, before clicking in the middle of the screen.

**App information (please complete the following information):**
 -  Native app 
 - Version 6.1.4
 - OSX high sierra 10.13.6

**Comment by prashantagarwal** [comment] 2018-07-23 11:31
Duplicate of #4755

**Closed as completed by prashantagarwal** 2018-07-23 11:31 UTC
