### ISSUE TITLE
Self-signed certificate breaks OAuth2 authorization in standalone Postman app

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#3996] opened 2017-12-20 10:39 UTC
## App Details:

```
Postman for Linux
Version 5.5.0
linux 4.9.0-4-amd64 / x64
```

## Issue Report:

We use self-signed certificates for development purpose. These certificates break the OAuth2 authorization in the standalone Postman app: Requesting a new OAuth2 token opens a new window, but the window is empty. Disabling SSL certificate verification (Settings > General) or adding an client certificate (Settings > Certificates) does not affect OAuth2 authorization. The legacy Postman Chrome Extension works fine as it allows to add an exception for the self-signed certificate.

We would expect that the standalone Postman app respects the certificate settings (SSL certificate verification and client certificates) also for the OAuth2 authorization.

**Comment by sivcan** [comment] 2017-12-20 13:51
@hodjo - Thanks for reporting this. We'll look into this.

**Comment by lucamaf** [comment] 2018-02-12 12:31
same here

**Comment by andutta** [comment] 2018-02-12 17:41
Facing the same issue, any resolution ?

**Comment by zihotki** [comment] 2018-02-14 10:47
Duplicate of [https://github.com/postmanlabs/postman-app-support/issues/2918](https://github.com/postmanlabs/postman-app-support/issues/2918 )

**Comment by sivcan** [comment] 2018-02-15 07:44
Closing duplicate issue.

**Closed as completed by sivcan** 2018-02-15 07:44 UTC
Labels: feature, Auth
