### ISSUE TITLE
Clicking Retry after modifying a Test doesn't run the scripts with the modifications

### ISSUE THREAD

**Issue by Quietbeat** [a85/POSTMan-Chrome-Extension#7780] opened 2019-12-11 20:01 UTC
**Describe the bug**
My Collection has 4 Collection variables and numerous API requests. Each Request has a parameterized URL along with 7 Tests and a test data file. If I start the Collection runner, modify a Test then click Retry in the Collection Runner, it will use the Collection Variable default values instead of the data from the test data file. I start the Collection runner, modify a Test then click on the Collection Runner tab then click "Run <Collection Name>", then it'll correctly use the test data.

**To Reproduce**
1. Open the Collection Runner (CR) and click "Run <collection>
2. When the test is done, go back to the editor and modify a Test then click Save
3. Go back to CR and click Retry

**Expected behavior**
The CR uses the test data values

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.13.0
 - OS: Windows 10 Build 17763

** Notes
There are times when I have to go back to the CR tab and click Run twice in order to get Postman to use the test data file instead of the Collection variable default values.

**Comment by ASStroh** [comment] 2019-12-13 02:06
1. You need to back out (click the Collection Runner tab - top-left corner) between runs if you are using a data file. The iteration count will not reset unless you reset the runner - i.e. if you have a file containing 5 iterations-worth of data, and you run through each of those iterations, clicking "Retry" will begin with the data in the (non-existent) 6th iteration of the data file.

2. Ensure you've saved your changes between collection runs. If you don't save your changes, they will not be included in a subsequent collection run.

**Comment by mccannt** [comment] 2020-01-21 15:59
@Quietbeat Can you verify if this is still an issue in the latest version of the application?

**Comment by Quietbeat** [comment] 2020-01-21 18:46
Yes this is an issue, you need to allow users to 'reset the runner' without backing out (it's not intuitive that you have to do this and a waste of time).

**Comment by saswatds** [comment] 2020-02-11 09:49
@Quietbeat I am using the `7.18.0` and was not able to reproduce this issue following the steps you have provided.
Here is a video attached showing the steps I took.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8796447/74226773-3218e180-4ce3-11ea-9db7-54e51c64647c.gif)
Also not sure what you meant when you say `test data values`. The runner always uses the latest state of the collection when retrying, this should never happen.

**Comment by appurva21** [comment] 2020-02-17 12:23
Hi @Quietbeat,
I am closing the issue as we are not able to reproduce it on the latest version of the app (`v.7.18.0`). Please feel free to reopen if the issue still persists or if you can provide us with some more info which will help us in reproducing this issue.

Thanks.

**Closed as completed by appurva21** 2020-02-17 12:23 UTC
Labels: bug, product/runtime
