### ISSUE TITLE
Make graphql queries have autocomplete 

### ISSUE THREAD

**Issue by trailerzone** [a85/POSTMan-Chrome-Extension#10132] opened 2021-07-19 00:26 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

It is not related to a problem, more so efficiency. 

### Describe the solution you'd like

If devolopers are able to use autocomplete they can build better queries using postman without having to manually go to the graphql interface. it seems small but I am already using postman to test my API. It would be nice to use it to test queries as well, part of that testing would be easier if postman had graphql autocomplete on fields available.

### Describe alternatives you've considered

Alternatives would be just using postman for REST and leaving graphql queries up to the graphql interface

**Comment by DannyDainton** [comment] 2021-07-19 11:29
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/6719

This issue mentions the request to have autocomplete/introspection for GraphQL.

**Closed as completed by DannyDainton** 2021-07-19 11:29 UTC
Labels: feature, duplicate, protocol/graphql
