### ISSUE TITLE
Unable to Merge Forked Collection to Master

### ISSUE THREAD

**Issue by DivyaMoryani** [a85/POSTMan-Chrome-Extension#9645] opened 2021-02-22 07:23 UTC
Steps to Reproduce: 
1. Collection with APIs.
2. Fork the Collection. 
3. Add/Modify the collection APIs.
4. Merge the Forked to the destination ->Unable to merge -> Something went wrong with the server error is displayed
![image](https://user-images.githubusercontent.com/65155227/108675517-dc942900-7521-11eb-909f-7da0d8e41940.png)

**Comment by DivyaMoryani** [comment] 2021-02-22 07:24
![image](https://user-images.githubusercontent.com/65155227/108675620-04838c80-7522-11eb-9bc6-a80677e63e8c.png)

**Comment by DivyaMoryani** [comment] 2021-02-22 07:30
And I lost all the data i was working on since morning :( , tried sign-out , sign-in

**Comment by DannyDainton** [comment] 2021-02-22 08:23
Hey @DivyaMoryani

Could you expand on the information about the Collections you're using, please? 

- Are there Collections that you created yourself?
- Was this a fork from a Team Collection?
- Were there any sync connection issues before trying to merge?

Adding a recording of the issue being reproduced will also help us to investigate what is going on here.

**Comment by DivyaMoryani** [comment] 2021-02-22 10:59
Are there Collections that you created yourself? - No , by another team member.
Was this a fork from a Team Collection? - No, But i tried forking from Teams Workspace also- I get the same error. 
Were there any sync connection issues before trying to merge? - No. but forking took a while. 

Tried uploading the video, it always > 10 MB :(

**Comment by ankit-m** [comment] 2021-03-04 14:14
@DivyaMoryani apologies for the late response here. Would like to get some more information which will help use resolve this issue

1. ID of the source collection
2. ID of the forked collection
3. Video recording of the error

If you cannot upload these here, feel free to email it to us at help@postman.com

**Comment by prabhat-awasthi-3697** [comment] 2021-03-24 07:29
Hey @DivyaMoryani 

Can you confirm if the issue is resolved for you now ?

**Comment by mccannt** [comment] 2021-04-08 22:38
Closing this issue for now. If you are still experiencing this @DivyaMoryani please let us know.

**Closed as completed by mccannt** 2021-04-08 22:38 UTC
Labels: bug, product/version-control
