### ISSUE TITLE
Setup for Windows Only Install to system partition

### ISSUE THREAD

**Issue by lishu** [a85/POSTMan-Chrome-Extension#4480] opened 2018-04-23 02:47 UTC
## App Details:
```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

## Issue Report:
 1. The Setup does not have the installation folder option, I do not want the tool software to use my system partition

**Comment by sivcan** [comment] 2018-04-23 06:59
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3897
Kindly follow the original thread for further updates.

**Closed as completed by sivcan** 2018-04-23 06:59 UTC
