### ISSUE TITLE
Postman keeps saying You seem to be offline. Data in this workspace might not be up to date.

### ISSUE THREAD

**Issue by KarlaDiaz199** [a85/POSTMan-Chrome-Extension#9477] opened 2021-01-27 20:45 UTC
Postman website and desktop app says I do not have a connection but by other apps are working. It does not allow me to upload my collections- it says I have 9 but only 5 are displayed and if I refresh the page or restart the app the collections are not shown
<img width="1680" alt="Screen Shot 2021-01-27 at 2 45 29 PM" src="https://user-images.githubusercontent.com/69685740/106051642-53b6d880-60ae-11eb-9c52-c7e5aca6dc17.png">

**Comment by DannyDainton** [comment] 2021-01-30 19:54
Please send all of the log files to help@postman.com. 

It will help us to investigate the root cause of the problem. 

You can find the logs at `View -> Developer -> View logs in Finder/Explorer.`

Similar issues have been raised on the repository and to try and keep the flow of information in a central place, I'm going to close this issue and kindly ask that you follow the thread, on the issue below, for more information. 

https://github.com/postmanlabs/postman-app-support/issues/9481

**Closed as completed** 2021-01-30 19:54 UTC
Labels: ws-connect-errors
