### ISSUE TITLE
Problem with Sync

### ISSUE THREAD

**Issue by marcosgugs** [a85/POSTMan-Chrome-Extension#1011] opened 2015-04-15 19:12 UTC
Hi, sorry for my bad english.

I'm having problems syncing.
When I open the Postman, he begins to synchronize and gives this message.

![captura de tela 2015-04-15 as 16 03 16](https://cloud.githubusercontent.com/assets/191966/7167276/1f503052-e38a-11e4-94ce-559d707f025b.png)

As requested, I made the "logout", he erased all my data, and log in again, the message kept popping up and the data was not synchronized.

What should I do?

**Comment by abhijitkane** [comment] 2015-04-15 19:21
We're facing heavy traffic on our servers right now. There's data in your account - that won't be deleted. You can try again in a few minutes.

**Comment by marcosgugs** [comment] 2015-04-15 19:26
Ok, I understand!
But, I have this problem about 2 or 3 weeks.
I will wait and try again later, as requested.
Thank you.

**Comment by abhijitkane** [comment] 2015-04-15 19:45
We're looking into this. I'll update this thread ASAP.

**Comment by marcosgugs** [comment] 2015-04-15 19:46
No problems!

Thanks man!

**Comment by sobtiankit** [comment] 2015-04-16 04:37
Hi Marco

Can you try now? The sync should work. I'll close this thread once you confirm.

**Comment by marcosgugs** [comment] 2015-04-16 12:29
Hi @sobtiankit @abhijitkane 

It's work!!! :)

Thank you guys!

**Comment by sobtiankit** [comment] 2015-04-16 12:36
Happy to help :)

**Comment by marcosgugs** [comment] 2015-04-16 13:16
Hi guys! 

Bad news! 

The problem is back =/

When I try Sync in my office, he gives the same message.

![captura de tela 2015-04-16 as 10 13 36](https://cloud.githubusercontent.com/assets/191966/7181478/6ba2f74a-e421-11e4-8a75-884c0f50c9eb.png)

**Comment by abhijitkane** [comment] 2015-04-16 15:26
Were you ever able to Sync from office? It might be a firewall issue that prevents WebSocket connections from being made.

We didn't find any errors in our server logs. Let me know if you're unable to Sync from your home network.

**Comment by ratpik** [comment] 2015-07-15 07:40
![postmansyncerror](https://cloud.githubusercontent.com/assets/210420/8693154/8be752c2-2af2-11e5-9f0c-fc8795dde308.png)

I have similar issues. Happens almost every time I need to share a collection. So the only other option is to download, email and ask others to import the collection. It has worked earlier at times, so it is not a firewall issue but mostly the connections just timing out.

**Comment by marcosgugs** [comment] 2015-07-15 13:31
+1

**Comment by Kaveendra** [comment] 2015-07-23 23:57
Same problem. Sync does not work. I have also tried re-installing the app but no luck.

**Comment by Kaveendra** [comment] 2015-07-24 00:04
No joy, Sync does not work and I am stuck with no collections to work on :(

![untitled](https://cloud.githubusercontent.com/assets/13475842/8864928/1215db94-31eb-11e5-8e3e-6263c0079f0a.png)
![untitled2](https://cloud.githubusercontent.com/assets/13475842/8864929/1218ce08-31eb-11e5-8ad2-2fda84528afa.png)

**Comment by a85** [comment] 2015-07-24 00:05
@Kaveendra Sorry about the issue. Seems to be working for me. Might be an account specific issue. The team is looking into it.

**Comment by marcosgugs** [comment] 2015-07-24 00:07
still I continue with this problem

Em quinta-feira, 23 de julho de 2015, Abhinav Asthana <
notifications@github.com> escreveu:

**Comment by Kaveendra** [comment] 2015-07-24 00:11
Thanks Abhinav. By the way wonderful product, if you iron out the minor issues..

**Comment by Kaveendra** [comment] 2015-07-24 00:44
@a85 Can your team fix this for me within the hour, or is it complicated?

**Comment by sobtiankit** [comment] 2015-07-24 01:30
@Kaveendra can you try once now?

**Comment by Kaveendra** [comment] 2015-07-24 01:32
It was on Syncing and Connecting status in terns, but nothing happening. Restarted the app now but still the same

**Comment by Kaveendra** [comment] 2015-07-24 01:34
by the way, I can see heaps of packet loss on wireshark!!

**Comment by sobtiankit** [comment] 2015-07-24 01:38
Hmmm, I am unable to reproduce this on any of my accounts. I have, however, just alleviated some server load. 

Sorry to ask again but in the last 5 minutes did you log out and back in? or just reopened the app? Sometimes that helps.

**Comment by Kaveendra** [comment] 2015-07-24 01:39
not in last five minutes, but in last 30 minutes I have logged several times. Let me do that now again.

**Comment by Kaveendra** [comment] 2015-07-24 01:48
@sobtiankit  Connecting and Syncing in tern, for so many times. Then the red warning and goes back to offline.

**Comment by sobtiankit** [comment] 2015-07-24 01:50
Can you send me your email id? I'll get back to you in 5.

**Comment by Kaveendra** [comment] 2015-07-24 01:51
kaveendrav@gmail.com

**Comment by Kaveendra** [comment] 2015-07-24 01:56
One more thing I have noticed. When it goes back to offline, clicking the icon wont turn syncing back on! Seems like it prefers to stay offline until restart.

**Comment by sobtiankit** [comment] 2015-07-24 02:15
Please check your email, while I investigate this further.

**Comment by Kaveendra** [comment] 2015-07-24 02:30
Thanks, I can get back to work now :+1:  
This is another error message..

![untitled3](https://cloud.githubusercontent.com/assets/13475842/8866425/a97ba3ba-31ff-11e5-8423-1c0612664c5d.png)

**Comment by Sergeo17** [comment] 2015-09-15 15:33
Hi I have been getting the "There was a problem logging in to Sync. Please restart the app without logging out" error message.  I have been getting this for a few weeks now and not sure how to get my sync to work.

**Comment by abhijitkane** [comment] 2015-09-15 15:34
@Sergeo17 What's the username/email you use to sign in to Postman? Can you send us an email at help@getpostman.com?

**Closed as completed** 2015-10-31 06:02 UTC

**Comment by gsrinu78** [comment] 2016-02-17 01:20
Hi i am facing issues in connecting to postman server. can you please advise what would be the issue.

![image](https://cloud.githubusercontent.com/assets/17283451/13096887/d3d8199e-d570-11e5-967e-c5bcef17309e.png)

**Comment by sobtiankit** [comment] 2016-02-17 02:34
@gsrinu78 Can you please email help@getpostman.com with your App version number and user id? You can find this under Settings > About.

**Comment by chiragpurohit71085** [comment] 2016-05-19 04:26
Hi

I am facing account synching issue. Event I tried login/logout but some of the apis are not synching at all.

Regards,

**Comment by abhijitkane** [comment] 2016-05-19 04:35
@chiragpurohit71085 Can you please email help@getpostman.com with your App version number and user id? You can find this under Settings > About. Also, is the data visible at https://app.getpostman.com/dashboard/collections/private?expand=1?

**Comment by Scottwg11** [comment] 2016-11-09 16:35
I'm seeing something similar. it will sync some of my APIs but not all. Logging off and then back on does nothing.

**Comment by sdnts** [comment] 2016-11-10 07:18
@Scottwg11 Can you see all your collections at https://app.getpostman.com/dashboard/collections/private?expand=1 ? If yes, and Sync does not bring back all your collections, can you email us at help@getpostman.com?

**Comment by Scottwg11** [comment] 2016-11-10 14:23
I figured it out. I jumped the gun a little by posting here instead of looking into it a little more. When doing a "get" for the apps I needed to increase the limit so that I could see them all. By adding "?limit=200" to the end of the command I was able to list them all.

Thanks for the reply.
