### ISSUE TITLE
Setting a environment variable to undefined makes the variable disappear

### ISSUE THREAD

**Issue by devdavidkarlsson** [a85/POSTMan-Chrome-Extension#4429] opened 2018-04-09 08:00 UTC
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 16.4.0 / x64
```

## Issue Report:
 Setting a variable to something that is undefined makes the variable disappear from the list of env variables.

I would expect the variable to stay in the list but with an undefined or empty value.

Is this the expected behaviour.

**Reproduce:**
for jsonData = 
```
[
    {
        "id": "3f067157-7646-42b9-8886-091a51c57d59",
        "username": "user1",
        "notificationPreference": "",
        "phoneNumber": "4129621300",
        "roles": [],
        "groups": []
    },
    {
        "id": "a75a0bbc-23b8-418a-b70d-f3578733c832",
        "username": "service-account-userservice",
        "email": "service-account-olt@placeholder.org",
        "roles": [],
        "groups": []
    }
]
```
**and in the Test tab:**
```
//Correct parsing:

pm.test("set variable with userId from results", function () {
    var jsonData = pm.response.json();
    pm.environment.set("userId", jsonData[0].id);
   
});

//This one just removes the variable userId, so it is abit tricky to understand why the first time it happens, i.e. the id variable of jsonData is undefined.
pm.test("set variable with userId from results", function () {
    var jsonData = pm.response.json();
    pm.environment.set("userId", jsonData.id);
   
});
```

**Comment by kamalaknn** [comment] 2018-06-29 12:00
Duplicate of #3868

**Closed as completed by kamalaknn** 2018-06-29 12:00 UTC
Labels: bug
