### ISSUE TITLE
Fixing the problem with importing from swagger

### ISSUE THREAD

**Issue by Gone4Codin** [a85/POSTMan-Chrome-Extension#6642] opened 2019-06-03 12:11 UTC
**Is your feature request related to a problem? Please describe.**
This feature request is related to 2 other open issues (#2857 and #4499). 
The problem of Postman not importing correctly the body parameters from a request of a json file from Swagger is still present. I would not insist in this problem if I only had a few requests to change but I have, at least, 600 requests with a body.
  
**Describe the solution you'd like**
I would love to have that issue resolved

**Describe alternatives you've considered**
The only alternative is to change the request manually inside Postman Desktop

**Comment by abhijitkane** [comment] 2019-06-10 06:36
@Gone4Codin We're working on a fix, and hope to release this soon. Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/6666

**Closed as completed by abhijitkane** 2019-06-10 06:36 UTC
