### ISSUE TITLE
Windows: un-comment shortcut converts text to all caps

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#9301] opened 2020-11-20 18:39 UTC
**Describe the bug**
In the Windows desktop app, pressing the un-comment shortcut (`ctrl + k + u`) in the script editor un-comments the selected text, but also converts it to all caps. This behavior does not occur on Mac.

**To Reproduce**
1. On a Windows computer, open script editor in Postman desktop app
2. Enter some text, and select it
3. Press `ctrl + k + c` to comment the code out
4. Press `ctrl + k + u` to un-comment code
5. See that code has been converted to all caps

**Expected behavior**
Code is uncommented; capitalization is unchanged.

**App information (please complete the following information):**
 - App Type: Desktop App
 - Postman Version: 7.36
 - OS: Windows 10

**Comment by DannyDainton** [comment] 2020-11-20 18:44
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9114

**Comment by DannyDainton** [comment] 2020-11-20 18:45
I'm going to close this one @JP-from-Postman, as we have a big raised for this one already.

**Closed as completed** 2020-11-20 18:46 UTC
Labels: duplicate

**Comment by fedegomez78** [comment] 2021-09-04 15:56
I noticed this still has the same behavior on v8.12.0
App Type: Desktop App
Postman Version: v8.12.0
OS: Windows 10

**Comment by hammad1-byte** [comment] 2023-01-26 08:57
This behavior still exists. 
![image](https://user-images.githubusercontent.com/116883589/214795257-685259b4-06e4-4081-9527-eebe52d75334.png)
![image](https://user-images.githubusercontent.com/116883589/214795489-acbadd49-976d-41e5-9a91-49ee7a7c6614.png)
