### ISSUE TITLE
Blank screen with new install of Postman 6.2.3

### ISSUE THREAD

**Issue by Robin-West** [a85/POSTMan-Chrome-Extension#4962] opened 2018-08-03 21:07 UTC
**Describe the bug**
The form/screen shows just the top menu and the rest of the form is black, tan, or white.  If I close the form, sometimes another copy pops up but it is also blank. 

**To Reproduce**
1. Download and install Postman x64 for Windows 
2. After install and anytime the program is run, the screen in blank.

**Expected behavior**
The Postman app loads

**Screenshots**
![image](https://user-images.githubusercontent.com/5223636/43665599-5b6632f4-9736-11e8-9be5-d72cd3557206.png)
![image](https://user-images.githubusercontent.com/5223636/43665613-695cecf4-9736-11e8-9ba9-7af547eefa60.png)

**App information (please complete the following information):**
 - App Type - Windows PC
 - Postman Version 6.2.3
 - OS: Windows 7 Professional x64

**Additional context**
I looked through past issue like this(it seems to come up often in Postman) but I couldn't find any applicable solutions.  I ran from the command line and got the following errors:

C:\Users\xxx\AppData\Local\Postman\app-6.2.3>Postman.exe

C:\Users\xxx\AppData\Local\Postman\app-6.2.3>
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App updater event { name: 'checkForElectronVersionUpdated',
  namespace: 'appUpdate' }
App events bus { name: 'booted', namespace: 'requester' }
[1168:0803/154842.772:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.773:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[1168:0803/154842.774:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.775:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[1168:0803/154842.775:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.776:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[1168:0803/154842.776:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.777:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[1168:0803/154842.779:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.780:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[1168:0803/154842.781:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.782:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[1168:0803/154842.787:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.787:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[1168:0803/154842.788:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.789:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[1168:0803/154842.790:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.791:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[1168:0803/154842.791:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.792:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[1168:0803/154842.793:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.793:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[1168:0803/154842.794:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-000
0000004B9DD80]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[1168:0803/154842.795:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000
000004B9DD80]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
[15236:0803/155507.621:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-00
00000004B9B4D0]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIU
M: invalid mailbox name
[15236:0803/155507.622:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-000
0000004B9B4D0]RENDER WARNING: texture bound to texture unit 0 is not renderable.
 It maybe non-power-of-2 and have incompatible texture filtering.
[15236:0803/155507.624:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-00
00000004B9B4D0]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIU
M: invalid mailbox name
[15236:0803/155507.625:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-000
0000004B9B4D0]RENDER WARNING: texture bound to texture unit 0 is not renderable.
 It maybe non-power-of-2 and have incompatible texture filtering.

It continues on with these errors for another few pages.

Thanks

**Comment by sivcan** [comment] 2018-08-03 22:48
@Robin-West Try this: https://github.com/postmanlabs/postman-app-support/issues/4703#issuecomment-397517447

**Comment by numaanashraf** [comment] 2018-08-04 05:27
Duplicate of #4703

**Closed as completed by numaanashraf** 2018-08-04 05:27 UTC
Labels: bug
