### ISSUE TITLE
I Can't open Runner

### ISSUE THREAD

**Issue by xujialiang** [a85/POSTMan-Chrome-Extension#2562] opened 2016-12-15 15:22 UTC
1. Postman Version:  4.9.2 
 2. App (Chrome app or Mac app):Mac app
 3. OS details:10.12.1 (16B2657)
 4. Is the Interceptor on and enabled in the app:where is the interceptor?
 5. Did you encounter this recently, or has this bug always been there:YES
 6. Expected behaviour:Open Runner
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):nothing
 8. Screenshots (if applicable)

<img width="723" alt="wx20161215-232152 2x" src="https://cloud.githubusercontent.com/assets/1549351/21229664/5b0a9bc2-c31d-11e6-8f46-3a9b1f0cbfe3.png">

**Comment by vegetableman** [comment] 2016-12-16 07:40
@xujialiang The interceptor is part of the chrome app. As for the runner, the issue is fixed internally and will be part of the next release. Thanks for reporting 👍 .

**Comment by sdnts** [comment] 2016-12-20 14:44
@xujialiang Can you try updating to the latest version (4.9.3) and see if your issue is resolved?

**Closed as completed** 2016-12-21 11:02 UTC
Labels: pending-close
