### ISSUE TITLE
Not tests present on Monitor

### ISSUE THREAD

**Issue by drorwb** [a85/POSTMan-Chrome-Extension#9316] opened 2020-11-25 10:04 UTC
**Describe the bug**

I create a collection with a few requests and test. When I run the collection locally its working and all the tests passed. 

When I upload the collection as a monitor I get for each one of the requests this message: 

```
"This request does not have any tests".
```

**Steps To Reproduce**

1. Create monitor from web/app
2. Run 

**Screenshots**
Monitor:
![image](https://user-images.githubusercontent.com/45896398/100216772-5ca6f480-2f1b-11eb-9826-556e5e3d5c7b.png)
Collection Runner:
![image](https://user-images.githubusercontent.com/45896398/100217506-359cf280-2f1c-11eb-9131-0411461cae44.png)

**App information:**
 - App Type: Native App
 - Postman Version 7.36.0
 - OS: win32 10.0.19041 / x64

**Comment by DannyDainton** [comment] 2020-11-25 10:19
@drorwb 

I've updated your questions so that it follows the template - Could you please add steps to reproduce, any additional information and screenshots to the issue, please?

By providing this information, we will be better placed to help resolve the issue that you're facing.

**Comment by drorwb** [comment] 2020-11-25 10:46
Fixed. 
Second bug i have with postman in two days.
The app crash a lot and works really slowly

**Comment by DannyDainton** [comment] 2020-11-25 11:03
- What are the 8 errors on the Monitor Run? 
- Is the Collection using global variables when run successfully in the runner?
- Is an `Environment` file used in the Monitor Run?
- Does the Monitor show the tests if you delete and recreate it?

**Comment by ArjunSingh-PM** [comment] 2021-01-14 04:11
@drorwb Are you still experiencing any issues with tests in Monitors?

**Comment by DannyDainton** [comment] 2021-02-20 16:02
As it's been several months since the last response, I'm going to close this issue for now.

We can reopen if the problem still persists in the latest version.

**Closed as completed by DannyDainton** 2021-02-20 16:02 UTC
Labels: Tests, product/automation-testing
