### ISSUE TITLE
Exported Results can't be imported

### ISSUE THREAD

**Issue by bokivaol** [a85/POSTMan-Chrome-Extension#4537] opened 2018-05-08 09:30 UTC
![screenshot_1](https://user-images.githubusercontent.com/9623813/39749301-9f3cd8fc-52b2-11e8-9cd6-24c56f1865f8.png)

Problem is when I run collection and after that when I export results, those results can't be imported.

**Actual State**: Export results from Postman Collection Runner can not be imported again. I receive an error: "Could not import test run. Please check the format of the file."
**Expected result**: Exported results must be imported without any problem.

**Steps to reproduce**:
1. Open Postman
2. Click on Runner button
3. Choose and Run some collection which you already have
4. After running is finished hover the mouse over received result
5. On the right side of the result click on down pointing arrow (Export results) to Export results.
![download](https://user-images.githubusercontent.com/9623813/39749507-248dbf80-52b3-11e8-93a0-2fefa4fb933b.png)
6. After exporting in Runner click on "Import Test Run" button.
7. Choose and import exported collection .json file.

**App-information**:
- Windows 10
- Postman v6.0.10

**Comment by sivcan** [comment] 2018-05-08 10:21
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3574

**Closed as completed by sivcan** 2018-05-08 10:21 UTC
