### ISSUE TITLE
New param with key and description but empty value causes description not to save

### ISSUE THREAD

**Issue by asheroto** [a85/POSTMan-Chrome-Extension#11160] opened 2022-08-08 17:39 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In a request, in params, on a new key, if you enter the key and a description but nothing in value, then save it, the description disappears

### Steps To Reproduce

This only occurs on a NEW parameter in a request, one that does not exist already.

- Type something in the key field
- Skip the value field
- Type something in the description field
- Save it

Soon after the description disappears.

### Operating System

Windows

### Postman Version

9.27.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment] 2022-08-09 08:36
Hey @asheroto 

I've been unable to reproduce this on the latest version of the app - Could you record a quick video showing the behaviour you're seeing, please?

**Comment by DannyDainton** [comment] 2022-08-11 09:30
Hey @asheroto 

Could you provide the recording of the disappearing description, please?

**Comment by asheroto** [comment] 2022-08-11 11:16
Hello,

It did some testing and found that it only occurs if there are some params that are unchecked above the variable that you add...

https://user-images.githubusercontent.com/49938263/184121662-7ed7d4b4-4921-4297-a0ae-be703ff7c6d3.mp4

**Comment by DannyDainton** [comment] 2022-08-11 11:59
Thank you, that video helped to narrow down the issue. I'm now able to recreate it locally.

Appreciate you investigating that deeper and posting the video.

**Comment by asheroto** [comment] 2022-08-11 12:00
Glad I was able to help! 😊

**Comment by Dhembla** [comment] 2023-03-20 14:12
Hey @asheroto, 
Sorry for the trouble that you have to go through because of this issue. We have released a fix for this as part of our latest release V10.12. Please check it out and let us know if there is any feedback. Thanks for your patience!

**Closed as completed by Dhembla** 2023-03-20 14:12 UTC
Labels: bug, product/runtime, key/value editor
