### ISSUE TITLE
Secure / Gated access to published docs

### ISSUE THREAD

**Issue by 5p3c7r3** [a85/POSTMan-Chrome-Extension#3188] opened 2017-06-21 00:03 UTC
We would like to host our internal APIs inside of our developer portal. We would include the docs in our portal by proxying a url over to your published documentation. It would be great if that was made secure like an API request so that we could then open up the docs to our development team using SSO with our own corporate accounts.

**Comment by kamalaknn** [comment] 2017-06-21 11:19
Hey @caoimhghin 

This appears to be a duplicate of #3142.

I am closing this issue. Feel free to continue discussion in the linked issue.

**Closed as completed by kamalaknn** 2017-06-21 11:19 UTC
