### ISSUE TITLE
A 204 No Content does not update the Preview tab

### ISSUE THREAD

**Issue by leightonthomas** [a85/POSTMan-Chrome-Extension#5400] opened 2018-10-22 11:38 UTC
**Describe the bug**
If you've already made a request that had a preview then it won't update when making another request that results in an empty response (204 No Content) 

**To Reproduce**
1. Make a request to an endpoint that has a preview-able response
2. Click on the "Preview" tab in the Response section
3. Make another request to an endpoint that returns 204 with no content
4. See that the preview tab has not updated

**Expected behavior**
The preview tab should be empty on the 204 request.

**Screenshots**
![screen shot 2018-10-22 at 12 27 14](https://user-images.githubusercontent.com/14091070/47290396-335a6280-d5f7-11e8-963b-485423d41a2e.png)
The 204 response

![screen shot 2018-10-22 at 12 27 18](https://user-images.githubusercontent.com/14091070/47290397-335a6280-d5f7-11e8-99f9-c1ba8ff9f7d9.png)
The preview tab not showing correct information

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.4.4
 - OS: macOS High Sierra 10.13.4

**Additional context**
N/A

**Comment by kamalaknn** [comment] 2018-10-22 12:58
Hey, thanks for reporting this. 

We have identified this and have a fix ready for this internally. We will push it out as part of the next release.

I'm closing this issue because this is a duplicate of #2950 You can follow the original thread for updates.

Thanks

**Closed as completed by kamalaknn** 2018-10-22 12:58 UTC
