### ISSUE TITLE
New Integration Request - Azure DevOps Repos

### ISSUE THREAD

**Issue by sim1986** [a85/POSTMan-Chrome-Extension#10087] opened 2021-07-01 09:05 UTC
**Describe your current workflow**
We write our tests in postman and manually move them into our Azure DevOps repos

**Describe your ideal workflow**
Postman connects to Azure DevOps repo of choice on a branch of choice. From postman changes in tests can be committed to the branch

**Describe alternatives you've considered**
Use a webhook to call a workflow tool to commit the code to the Azure DevOps repo. This is too impractical

**Comment by abhijitkane** [comment] 2021-07-13 06:09
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9131

**Closed as completed by abhijitkane** 2021-07-13 06:09 UTC
Labels: feature, product/integrations
