### ISSUE TITLE
Getting blank vaalue in environment  json file after downloading from postman

### ISSUE THREAD

**Issue by Piyush1317** [a85/POSTMan-Chrome-Extension#7322] opened 2019-09-16 06:55 UTC
1.Create Env var and enter the valu into.
2. Download the environment json file from option,
3.Store the json file in your system,
4. Open environment json file and check the value .
5. No value is coming, all value asre blank.
Like this:
"values": [
		{
			"key": "uname",
			"value": "",
			"description": "",
			"enabled": true
		},
		{
			"key": "pwd",
			"value": "",
			"description": "",
			"enabled": true
		},
		{
			"key": "Url",
			"value": "",
			"description": "",
			"enabled": true
		},
		{
			"key": "Total val",
			"value": "",
			"enabled": true
		},
		{

**Comment by preethammavin** [comment] 2019-09-20 17:30
@Piyush1317 which version of the app are you using, also can you check if you have values in the initial value or the current value. If the values are only in the current values they are not exported with the environment as they meant to be used only in that session. If you want to export that value as well, click on persist all and export the environment post that

**Comment by vvs11** [comment] 2020-03-13 05:53
@Piyush1317 Please let us know if you're still facing this issue after trying the solution suggested above?

**Comment by codenirvana** [comment] 2020-05-29 20:46
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-05-29 20:46 UTC
Labels: blocked/need-info, product/runtime
