### ISSUE TITLE
Postman Mac App corrupts and shows incorrect JSON if floating point #'s are used

### ISSUE THREAD

**Issue by sjmcdowall** [a85/POSTMan-Chrome-Extension#2447] opened 2016-11-01 17:40 UTC
1. Postman Version: 4.8.1
 2. App (Chrome app or Mac app): Mac App
 3. OS details: os Sierra
 4. Is the Interceptor on and enabled in the app: No idea
 5. Did you encounter this recently, or has this bug always been there: not sure .. 
 6. Expected behaviour: Show proper floating point #'s not truncated to 0.000
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Here is the curl output of the request:  
```
{"total":1,"data":[{"adjust":[{"name":""},{"name":""}],"axisOrder":"XYZ","contGrp":[{"contexts":[]},{"contexts":[]}],"custUse":[],"fct":"","fctArgs":[],"id":"e738ee33-19b7-4270-bbf6-4d00e13bcd9b","idCZStart":"bde5015a-16aa-412c-a1ca-d572717bf86d","idLot":"UNKNOWNLOT","idSublot":"UNKNOWNSUBLOT","idUser":"hutner","instanceName":"FunctionalVB_VM1","patGrp":[{"patterns":["ti245_func_VMD.PAT"]},{"patterns":[]}],"pinGrp":[],"setups":[{"algoName":"Linear","mode":"X Shmoo","pName":["Open"],"pType":"Edge","rgFrom":[0],"rgStps":20,"rgStpsz":[2.75e-8],"rgTo":[5.5e-7],"shTname":[],"shTtype":[],"specUnit":"Time","stepName":"X_Shmoo_Vps"},{"algoName":"Linear","mode":"Y Shmoo","pName":["Vps"],"pType":"Level","rgFrom":[3.38],"rgStps":20,"rgStpsz":[0.011],"rgTo":[3.6],"shTname":[],"shTtype":[],"specUnit":"Volt","stepName":"Axis_1"}],"siteCnt":2,"testCell":"Tester123","timeStamp":"2016-10-10T15:00:53.993Z","tstMeth":"Reburst"}],"limit":25,"skip":0}
```

Notice the X Shmoo entry has rgStpsz of 2.75e-8  and rgTo is 5.5e-7

Here is the Postman App output for the request

```
{
  "total": 1,
  "data": [
    {
      "adjust": [
        {
          "name": ""
        },
        {
          "name": ""
        }
      ],
      "axisOrder": "XYZ",
      "contGrp": [
        {
          "contexts": []
        },
        {
          "contexts": []
        }
      ],
      "custUse": [],
      "fct": "",
      "fctArgs": [],
      "id": "e738ee33-19b7-4270-bbf6-4d00e13bcd9b",
      "idCZStart": "bde5015a-16aa-412c-a1ca-d572717bf86d",
      "idLot": "UNKNOWNLOT",
      "idSublot": "UNKNOWNSUBLOT",
      "idUser": "hutner",
      "instanceName": "FunctionalVB_VM1",
      "patGrp": [
        {
          "patterns": [
            "ti245_func_VMD.PAT"
          ]
        },
        {
          "patterns": []
        }
      ],
      "pinGrp": [],
      "setups": [
        {
          "algoName": "Linear",
          "mode": "X Shmoo",
          "pName": [
            "Open"
          ],
          "pType": "Edge",
          "rgFrom": [
            0
          ],
          "rgStps": 20,
          "rgStpsz": [
            0.00000
          ],
          "rgTo": [
            0.0000
          ],
          "shTname": [],
          "shTtype": [],
          "specUnit": "Time",
          "stepName": "X_Shmoo_Vps"
        },
        {
          "algoName": "Linear",
          "mode": "Y Shmoo",
          "pName": [
            "Vps"
          ],
          "pType": "Level",
          "rgFrom": [
            3.38
          ],
          "rgStps": 20,
          "rgStpsz": [
            0.011
          ],
          "rgTo": [
            3.6
          ],
          "shTname": [],
          "shTtype": [],
          "specUnit": "Volt",
          "stepName": "Axis_1"
        }
      ],
      "siteCnt": 2,
      "testCell": "Tester123",
      "timeStamp": "2016-10-10T15:00:53.993Z",
      "tstMeth": "Reburst"
    }
  ],
  "limit": 25,
  "skip": 0
}
```

The rgTo is now 0.0000 and the rgStpSz is 0.00000

This has driven me nuts for the last 3 days trying to track down the issue in my service.  :(

**Comment by sdnts** [comment] 2016-11-02 10:19
@sjmcdowall Thanks for reporting this. I'm looking into this. Will let you know here.

**Comment by sjmcdowall** [comment] 2016-11-02 13:14
Great -- let me know how I can help.  Obviously it's easy for me to reproduce :)

**Comment by sdnts** [comment] 2016-11-07 11:45
Hey @sjmcdowall I did some poking around, and it looks like this is happening when you do a `JSON.parse` on the response (I'm assuming you do). JSON.parse has a precision limit, and your numbers surpass it, so it is forced to round it down.
If you look at the raw response, do you see your numbers correctly?

When we render the pretty output, we do a JSON.parse too, so that's where you are losing precision. There isn't much we can do here, since this looks like a limitation of JSON.parse itself.

You could return your numbers as strings, which might solve your issue.

Let me know if removing JSON.parse solves the issue for you.

**Comment by sjmcdowall** [comment] 2016-11-07 13:26
@madebysid -- No, I don't think that is correct .. the numbers in the raw JSON (as posted above) are certainly not beyond the precision:

"rgStpsz":[2.75e-8],
"rgTo":[5.5e-7]

That is only 3 or 4 decimals of precision ... 

And in my program when we do a json.parse() of the thing, it represents just fine -- the ONLY time it doesn't look right is when POSTMAN is showing the output ..

**Comment by sdnts** [comment] 2016-11-07 13:39
Hmm. You're right in saying JSON.parse will handle your numbers, I just verified. Your issue stems from something else in that case.

I made a little Node server that returns me the JSON you posted above, and for me the numbers are correct, at least in the raw section (the tab next to Pretty in Postman). What about your raw view? Do you see your numbers represented correctly there?

**Comment by sjmcdowall** [comment] 2016-11-07 13:44
Yes -- the RAW view shows the numbers perfectly fine.  It's just the Pretty view that -- isn't so pretty. :)

**Comment by sjmcdowall** [comment] 2016-11-14 21:31
Any updates on this?  It’s a bit annoying ..

**Comment by sdnts** [comment] 2016-11-15 06:59
@sjmcdowall This is fixed internally, and we'll be rolling out a fix with the next release.

**Comment by unruthless** [comment] 2017-02-15 19:05
Has the fix been rolled out yet? I have just run into this same problem. 

```
Postman for Chrome
Version 4.10.0
OS X / x86-64
Chrome 56.0.2924.87
```

JSON response to call made with httpie running in iTerm:
<img width="292" alt="screen shot 2017-02-15 at 11 07 28 am" src="https://cloud.githubusercontent.com/assets/142906/22990773/0ec62222-f36f-11e6-80b1-2e9bdcf6a74e.png">

JSON response to identical call made with Postman, pretty printed:
<img width="282" alt="screen shot 2017-02-15 at 10 59 47 am" src="https://cloud.githubusercontent.com/assets/142906/22990439/0d1cd8d6-f36e-11e6-8654-6deea5f44002.png">

The raw response in Postman matches httpie.

**Comment by sdnts** [comment] 2017-02-15 19:07
@unruthless Chrome apps take some time to reflect the updated package, it should be up in a couple of hours at the latest.

**Comment by unruthless** [comment] 2017-02-15 19:11
@madebysid Cool, thanks! Can you point me at the commit that fixed this issue?

**Comment by sdnts** [comment] 2017-02-16 11:11
@unruthless Unfortunately, the Postman apps (chrome or native) aren't open source, so I cannot do that right now. This, however, should be fixed now (you may have to force update extensions in Chrome). Can you verify and let me know? :)

**Comment by jstell** [comment] 2017-02-16 22:01
Still seems to be an issue in: 

> Postman for Chrome
> Version 4.10.0
> linux / x86-64
> Chrome 56.0.2924.87

Text view is 

` "val": 0.089331540527343739,`

Whereas Pretty JSON is:

`"val": {
    "s": 1,
    "e": -2,
    "c": [
      8,
      9,
      3,
      3,
      1,
      5,
      4,
      0,
      5,
      2,
      7,
      3,
      4,
      3,
      7,
      3,
      9
    ]
  },`

**Comment by sdnts** [comment] 2017-02-17 01:53
@jstell That was a regression on our part, sorry about that. Force updating all extensions should get you 4.10.2, which works as expected.

**Comment by jstell** [comment] 2017-02-17 03:48
@madebysid  Pretty JSON is correct  in 4.10.2.
`"val": 0.089331540527343739,`
 Thanks!

**Closed as completed** 2017-02-17 03:50 UTC
Labels: bug, pending-close

**Comment by plexus77** [comment] 2018-02-05 23:20
Still seems to be an issue.

> Postman osx app v 5.5.2

The RAW view is

`"productid":7400373566520315078253202846060260341474445857883,`

The PRETTY view is

`"productid": 7.400373566520315078253202846060260341474445857883e+48,`

**Comment by anilmujagic** [comment] 2019-03-16 11:53
In Postman 7.0.4 on macOS 10.13.6:
RAW: `"total":0.0000002`
PRETTY: `"total": 2e-7`
