### ISSUE TITLE
URL Encoding does not work anymore

### ISSUE THREAD

**Issue by Jakartoine** [a85/POSTMan-Chrome-Extension#9554] opened 2021-02-05 09:07 UTC
**Describe the Issue**

> With the new version of Postman (8.x), the "URL Encode automatically" has been moved from a global setting to a specific one onto each request in collections (no documentation on it by the way). Even if this setting is activated, URLs are still not encoded and cause a 400 Bad request.

**Steps to Reproduce**

> Create a request.
> Open the settings tab on this request and check the "URL Encode automatically" option.
> Send your request.
> A 400 Bad request is produced.

**Screenshots or Videos**

> 
![image](https://user-images.githubusercontent.com/27675999/107012916-f4d21d00-6799-11eb-8f67-ea1d131b7788.png)

**Environment Information**

 - Platform Type: Native Desktop App (MacOS or Windows)
 - Postman Version: 8.0.4
 - Operating System: MacOS 10.15.7

**Comment by DannyDainton** [comment] 2021-02-05 10:30
Hey @Jakartoine 

Are you able to provide an image of the Console log for the request with it enabled and disabled?

When I run the requests - I see it encoding the URL:

![image](https://user-images.githubusercontent.com/17089546/107021976-b68a2d00-679c-11eb-83cc-492ec5136321.png)

The 400 Error code is returned from the server and not really something that's going to happen on any request, as mentioned in the steps. Just trying to get a bit more context for the issue. :D

**Comment by kooper100** [comment] 2021-02-05 16:40
Hi! I'm having a similar issue with encoding '%' in my get parameters now.
If I replace '%' with '%25' manually in the url then it works.

First three queries are with 'Encode URL automatically' enable, next two are with it off, and the last is me manually entering '%25'

![example](https://user-images.githubusercontent.com/10172265/107061761-8cd60380-67a6-11eb-831d-d3edd96f7dce.jpg)

**Comment by Jakartoine** [comment] 2021-02-05 17:47
Hey @DannyDainton,

You are right, I probably did not give enough information about the issue.

It seems the encoding is working but not as before with this new version.

The value part of a query parameter is not well encoded and you can already notice it in your sample.
Braces should be encoded as before, without that, some APIs are not able to decode it perfectly and it causes
some bad request errors (which is quite specific to the backend side).

**Comment by minakshi-goel** [comment] 2021-02-12 15:23
Hello, 
I am having similar issue where I see % characters at the end of URL and so the response is always 404. i guess the characters represent new line.  I have "Encode URL automatically" setting enabled. I am on windows 10, postman 8.0.4
I expect postman to ignore/trim those characters and process the request. when you have 100s of requests already running, passed in earlier versions, correcting every single request to delete newline makes no sense with new version. 


![newline char at he end of url](https://user-images.githubusercontent.com/63124739/107786263-46872400-6d13-11eb-8312-e1fbf87455b9.png)

**Comment by VLEESDOEKJE** [comment] 2021-02-18 14:34
I can confirm that { and } are not encoded.
![image](https://user-images.githubusercontent.com/12599327/108372127-c70bc000-71fe-11eb-91ba-9ed0a9cfc293.png)

**Comment by codenirvana** [comment] 2021-02-22 04:37
This is a duplicate of #8808.

@Jakartoine `{`, `}`, and `:` are not reserved characters that require automatic encoding, refer https://github.com/postmanlabs/postman-app-support/issues/8154#issuecomment-783070482 for more details.

**Comment by mccannt** [comment] 2021-04-08 22:28
This should be working as expected as per the note above. 
Closing this issue. Please reopen if this is an issue for some still, with as much detail as possible.

**Closed as completed by mccannt** 2021-04-08 22:28 UTC
Labels: pending-close, encode-decode, product/runtime

**Comment by wombat86** [comment] 2023-03-07 11:02
Still relevant for me. The percent symbol is not encoded if it is present in the original parameter value while "Encode URL Automatically" is turned on. It seems that percent sign is simply ignored: when I replace `%` with `%25` in the original value with the auto encoding turned on, it works fine. However, I don't think it's a proper behaviour. Percent sign should be treated as a special character only when "auto encoding" is turned off.

**Comment by joggl71xpt** [comment] 2023-05-09 17:22
ISO Date Time like '2023-05-09T06:40:00+00:00' are also not encoded...

**Comment by edpeng** [comment] 2023-12-14 04:33
> Still relevant for me. The percent symbol is not encoded if it is present in the original parameter value while "Encode URL Automatically" is turned on. It seems that percent sign is simply ignored: when I replace `%` with `%25` in the original value with the auto encoding turned on, it works fine. However, I don't think it's a proper behaviour. Percent sign should be treated as a special character only when "auto encoding" is turned off.

as a workaround add this to the Pre-request Script:

`pm.request.url=encodeURI(pm.variables.replaceIn(pm.request.url));`

**Comment by jason1004** [comment] 2024-03-30 06:34
> ISO Date Time like '2023-05-09T06:40:00+00:00' are also not encoded...

how to solve it？

**Comment by zakhar-huzenko** [comment] 2025-02-04 14:14
> how to solve it？

The next workaround works for me:

Add Pre-request Script `pm.request.url.query = encodeURIComponent(pm.request.url.query);`

**Comment by zakhar-huzenko** [comment] 2025-02-04 14:29
> how to solve it？

The next Pre-request script works for me:
`pm.request.url.query.all().forEach(param => param.value = encodeURIComponent(param.value));`
