### ISSUE TITLE
Monitors running multiple times

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#5322] opened 2018-10-08 11:14 UTC
**Describe the bug**
Sometimes monitors run twice or get duplicated.

**To Reproduce**
Not sure what causes this behavior, as some days none of the monitors get duplicated. First time occurrence seems to be on September 26th.
This may be caused by Slack Integration, as in majority of cases the duplicate run is only shown there, however in some cases it also may be visible in the monitor run history (today 3 monitors were duplicated in Slack, however only 2 monitors show the duplication in run history). 
One thing in common for the requests that show up duplicate on the monitor as well as Slack, is that the first request took longer than than usual.

**Expected behavior**
The monitors should only run once.

**Screenshots**
![image](https://user-images.githubusercontent.com/43671684/46605190-970d6780-caf0-11e8-8532-ee0ccb4b546d.png)

**App information (please complete the following information):**
-Dashboard
-Slack

**Comment by godfrzero** [comment] 2018-10-08 14:49
Thanks for letting us know! Could you shoot us an email at help@getpostman.com with the monitor ID? I'll have to do some digging to get to the bottom of this.

**Comment by godfrzero** [comment] 2018-10-15 23:54
FYI, I'll be pushing an update which should fix this issue in a couple days.

**Comment by godfrzero** [comment] 2018-10-26 04:29
The fix was pushed out, but it was causing some performance issues. I've rolled it back for now, and I'm working on something else I can push out to address this issue. I'll update here once it's ready to go with an ETA.

**Comment by thesilvanator** [comment] 2019-01-08 15:33
Any update regarding the ETA?

**Comment by alexcuevag** [comment] 2019-01-25 14:57
We are experiencing the same issue in our company. Any update on this will be appreciated. Thank you.

**Comment by vpavlushkov** [comment] 2019-02-18 10:17
Facing this issue as well 😞

**Comment by YuduDu** [comment] 2019-02-19 18:19
Facing the same issue as well, please help to prioritize and share some updates. Thanks so much!

**Comment by agoloahmedelsayed** [comment] 2019-02-20 14:03
Facing the same issue here. Please prioritize. We can not trust any automated periodic workflows now because of this bug, and eventually we will be compelled to find an alternative.

**Comment by vpavlushkov** [comment] 2019-02-20 14:11
@godfrzero Could you please shed some light why is that so difficult to fix this issue and what in your fix could possibly cause performance degradation that you mention above? I would rather expect a simple script to be added to a VM image / Docker container that would manipulate with `crontab` and I honestly fail to see why fixing it takes that long. 😞

**Comment by godfrzero** [comment] 2019-03-01 04:20
We had pushed out a fix for this on the 21st, and we've confirmed over the last week or so that duplicate runs are no longer a systemic issue.

The duplication issue was being caused by increased load on the storage layer due to other reasons (which we had to address first, before tackling this problem. This was also why the earlier fix had to be reverted.). The root cause was a bug deep within the application itself, and aggravated by load. The root cause and storage issues have both been addressed as of the 21st.

I'm leaving this ticket open for a few more days and I'll close it if there are still no reports of duplicate runs.

**Comment by godfrzero** [comment] 2019-03-25 05:15
We've received a report of duplicate runs which seems to be legitimate, so re-opening this for now. Once I've tracked down the root cause for the report and verified that it's not a systemic issue, I'll close this ticket. If it turns out to be a systemic issue, I'll post an update here and push out a fix.

**Comment by JP-from-Postman** [comment] 2019-03-25 19:33
@godfrzero Just linked a user report. Not sure if it's the same one you mentioned.

**Comment by godfrzero** [comment] 2019-03-28 04:14
We've isolated the root cause for the reported duplicate runs and a fix is already up on beta. It's much more difficult to trigger duplicate runs via this RC so it has a much lower impact than before. I'll post again once the fix is up in production.

**Comment by godfrzero** [comment] 2019-04-09 02:09
An update has been pushed to address this RC, and I'm keeping an eye on affected monitors.

**Closed as completed by godfrzero** 2019-04-09 02:09 UTC
Labels: bug, product/dashboard
