### ISSUE TITLE
High CPU after an update is discovered

### ISSUE THREAD

**Issue by ipatalas** [a85/POSTMan-Chrome-Extension#9911] opened 2021-05-06 08:31 UTC
**Describe the Issue**
For at least 3-4 last versions I have an issue that whenever Postman detects there is a new update available CPU jumps to a constant ~10% and it never drops unless I restart Postman.
I use Postman almost daily so I never close it - it's a long living app - I just keep it minimized.
The moment new update gets available it also steals focus. Even though it was minimized it very often pops up in the foreground and steals focus from whatever I was just doing. 
Apart from that CPU goes crazy and 10% doesn't seem like a lot for new CPUs but.. I wouldn't notice that if not the CPU fan in my laptop which goes crazy even when I'm not doing any CPU intensive work at the moment.
Just updated to 8.3.1 but the release notes aren't very verbose. 
If that happens again I can post some additional info. If you can tell me what to check when that happens please let me know.
I'm willing to help because this is driving me nuts.

**Steps to Reproduce**
1. Run Postman for Windows
2. Wait until there is an update available (can take few days/weeks depending on the schedule)
3. Check your CPU usage before you make the update

**Screenshots or Videos**

**Environment Information**

 - Platform Type: Postman for Windows
 - Postman Version: 8.3.0 and few older versions as well
 - Operating System: Windows 10 2004 (Build 19041.928)

**Additional Context**

**Comment by ipatalas** [comment] 2021-05-14 09:38
And... it happened again (8.3.1 -> 8.4.0):
![image](https://user-images.githubusercontent.com/2623329/118252131-bb9bfe00-b4a8-11eb-8628-9c933d9a14d4.png)

![image](https://user-images.githubusercontent.com/2623329/118252111-b5a61d00-b4a8-11eb-9fcb-6e00edc92155.png)

Need to update and restart as this will never get idle again.

I can't find anything in the Release notes so I guess it's not been addressed yet?

**Comment by ipatalas** [comment] 2021-06-01 09:27
And the same happened today before upgrading to 8.5.1.

**Comment by ipatalas** [comment] 2021-06-08 09:24
And today again when upgrading to 8.6.1.

**Comment by ipatalas** [comment] 2021-06-15 19:59
Same problem today with another update. 
Moreover today I was able to observe the same behavior on my teammate's machine so I'm definitely not alone with this problem.

**Comment by frozenice** [comment] 2021-09-02 10:23
I noticed the CPU load (also 9%) after keeping Postman open for a long period multiple times, too. But I never checked if it had to do with pending updates. Today I saw the CPU load again and went to check the Postman version in the app, et voilà there was an update pending.

**Comment by DartMen** [comment] 2022-01-17 16:40
I suspect ''they'' have embedded a crypto miner which kicks in when idle

**Comment by jviotti** [comment] 2022-01-19 16:28
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9787

**Closed as completed by jviotti** 2022-01-19 16:28 UTC
Labels: performance, platform/windows, product/desktop-foundation, version/8, component/auto-updates
