### ISSUE TITLE
Adding a file to a post request affects 2 requests

### ISSUE THREAD

**Issue by janAtcontinia** [a85/POSTMan-Chrome-Extension#4202] opened 2018-02-16 08:29 UTC
V5.5.3 for Windows 10

I added a post request that posts a csv file.
Content-type: [{"key":"Content-Type","value":"application/x-www-form-urlencoded","description":"","enabled":true}]
In form-data, Body I add a File

then I duplicate the request and change the server.
Now I have 2 requests

When I add a File in one of the requests:
1) A red dot that indicates that the request have been changed does not appear
2) The file is changed in both my 2 requests. I would expect to be able to send different files since this is 2 different requests (eventhough it was duplicated)

**Comment by harryi3t** [comment] 2018-02-16 09:33
@janAtcontinia 
1. The file is not saved with the request. So when you re-open the request, you would have to select a file again.
2. If you do not close the tab-1 and duplicate the request, and the change the file in tab-2 then it should not affect the file in tab-1.

I have tested this on my end and this is working fine
[Link to video](https://drive.google.com/file/d/1QGoNcJmihRz_Y99rblr0vZR2AJfjOkJb/view?usp=sharing)

Are you doing something different than this?

**Comment by janAtcontinia** [comment] 2018-02-16 09:52
I closed Postman and re-opened it, and now it works as expected. The 2 requests are disconnected.

Then I tried again
Before:
[cid:image006.jpg@01D3A714.405C1F40]

[cid:image007.jpg@01D3A714.405C1F40]
With best regards

Now changing in one of the requests:
[cid:image008.jpg@01D3A714.405C1F40]

[cid:image009.jpg@01D3A714.405C1F40]



Jan Nielsen
Software developer

E-mail: jni@continia.com

Continia Software A/S
Stigsborgvej 60
DK-9400 Nr. Sundby Denmark Tlf.: +45 8230 5000
Direkte: 63357705

[cid:image010.png@01D3A714.405C1F40]
Check out our websites: English | German | Danish | Swedish | Norwegian | Dutch | Spanish | French
Product & Price Catalogs – Euro – Language: English | German | Dutch (NL) | Dutch (BE) | Spanish
Product & Price Catalogs – Other currencies: USD I CAD | GBP | DKK | SEK | NOK I NZD I AUD
[cid:image005.gif@01D2C32A.7A308A90]

Fra: Harendra Singh [mailto:notifications@github.com]
Sendt: 16. februar 2018 10:34
Til: postmanlabs/postman-app-support <postman-app-support@noreply.github.com>
Cc: Jan Nielsen <JNI@continia.com>; Mention <mention@noreply.github.com>
Emne: Re: [postmanlabs/postman-app-support] Adding a file to a post request affects 2 requests (#4202)


@janAtcontinia<https://github.com/janatcontinia>

  1.  The file is not saved with the request. So when you re-open the request, you would have to select a file again.
  2.  If you do not close the tab-1 and duplicate the request, and the change the file in tab-2 then it should not affect the file in tab-1.

I have tested this on my end and this is working fine
Link to video<https://drive.google.com/file/d/1QGoNcJmihRz_Y99rblr0vZR2AJfjOkJb/view?usp=sharing>

Are you doing something different than this?

**Comment by harryi3t** [comment] 2018-02-16 12:04
@janAtcontinia The images were not uploaded. If you prefer you can mail them also at harendra[at]getpostman.com

**Comment by janAtcontinia** [comment] 2018-02-22 07:36
Did you get the images? I mailed them to you right away

**Comment by harryi3t** [comment] 2018-02-22 10:16
@janAtcontinia Yes. I have reproduced this. Marking this a bug.
![bug-confirmed-low](https://user-images.githubusercontent.com/5207331/36532398-a521290a-17e6-11e8-8cc4-91e9804141f3.gif)

**Comment by sdnts** [comment] 2018-03-21 08:35
Hi @janAtcontinia, we fixed this in the latest version (6.0.10). Can you update and check?

I'm closing this, but will reopen if you still see it.

**Comment by janAtcontinia** [comment] 2018-03-21 08:47
Hi Siddhant
I have had problems with uploading pictures to github, so you get them in a mail instead.

I can reproduce the problem

[cid:image008.jpg@01D3C0F9.9A1B0C90]


[cid:image009.jpg@01D3C0F9.9A1B0C90]


[cid:image010.jpg@01D3C0F9.9A1B0C90]


Changing:
[cid:image011.jpg@01D3C0F9.9A1B0C90]


Also affects the original:
[cid:image012.jpg@01D3C0F9.9A1B0C90]


I can see that you use a Mac. I use windows 10.



With best regards

Jan Nielsen
Software developer

E-mail: jni@continia.com

Continia Software A/S
Stigsborgvej 60
DK-9400 Nr. Sundby Denmark Tlf.: +45 8230 5000
Direkte: 63357705

[cid:image013.png@01D3C0F9.9A1B0C90]
Check out our websites: English | German | Danish | Swedish | Norwegian | Dutch | Spanish | French
Product & Price Catalogs – Euro – Language: English | German | Dutch (NL) | Dutch (BE) | Spanish
Product & Price Catalogs – Other currencies: USD I CAD | GBP | DKK | SEK | NOK I NZD I AUD
[cid:image005.gif@01D2C32A.7A308A90]

Fra: Siddhant Sinha <notifications@github.com>
Sendt: 21. marts 2018 09:36
Til: postmanlabs/postman-app-support <postman-app-support@noreply.github.com>
Cc: Jan Nielsen <JNI@continia.com>; Mention <mention@noreply.github.com>
Emne: Re: [postmanlabs/postman-app-support] Adding a file to a post request affects 2 requests (#4202)


Hi @janAtcontinia<https://github.com/janatcontinia>, we fixed this in the latest version (6.0.10). Can you update and check?

I'm closing this, but will reopen if you still see it.

**Comment by harryi3t** [comment] 2018-03-21 14:03
@janAtcontinia Please send the images to `help@getpostman.com`

**Comment by sujayvenaik** [comment] 2018-07-04 08:09
Hey @janAtcontinia 
i just tried it out once again,
But this seems to be fine on our latest app.

You can get a latest copy from https://www.getpostman.com/apps

**Closed as completed by sujayvenaik** 2018-07-04 08:09 UTC
Labels: bug
