### ISSUE TITLE
Curl imports with --data-row will not import the body

### ISSUE THREAD

**Issue by ptolemys** [a85/POSTMan-Chrome-Extension#7983] opened 2020-02-03 09:10 UTC
**Curl imports with --data-row will not import the body**

- Curl imports with body specified using -d will get imported successfully
- Curl imports with body specified using --data-row will get imported **without the body**

**To Reproduce**
1. Go to 'Import > Paste Raw Text'
2. Paste a sample curl which contains body specified with --data-row, for example : 
    
    curl --location --request POST 'https://postman-echo.com/post' \
    --data-raw 'This is expected to be sent back as part of response body.'

3. Click on 'Import'
4. Check that body has not been imported.

**Expected behavior**
Curls with body specified using --data-row should get completely imported **including body**.

**Screenshots**
25 seconds screen recording : https://imgur.com/a/X2zMqRh

**App information**
 - App Type [Native App]
 - Postman Version [Version 7.17.0]
 - OS: [macOS 10.15.2]

**Additional context**
On exporting a curl using Code > cURL (from drop down), the default export gets -d body 
but if Settings > General > New Code Generation Mode is turned ON, the body exports are done with --data-row body which are not back-importable to Postman itself.

**Comment by ptolemys** [comment] 2020-02-11 11:58
@shamasis Can someone in Team Postman have a look on this, I would be happy to assist in case help is required for replication.

Thank you.

**Comment by tiaraju** [comment] 2020-02-20 20:55
That's also happening to me. For quite a long time actually.
Any news?

**Comment by tiaraju** [comment] 2020-02-20 20:56
Also reported in #7895

**Comment by shreys7** [comment] 2020-03-05 06:43
@ptolemys Thanks for reporting this issue. We are soon going to release a fix for this. Will keep you updated here.

**Comment by umeshp7** [comment] 2020-03-05 10:36
Duplicate of: https://github.com/postmanlabs/postman-app-support/issues/7895

**Closed as completed by umeshp7** 2020-03-05 10:36 UTC
Labels: bug, importer

**Comment by JaswantBB** [comment] 2021-01-08 14:46
Again facing same issue

**Comment by kasumiru** [comment] 2021-03-01 11:48
the bug is stiil here in chrome Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by umeshp7** [comment] 2021-03-01 12:23
Hey @kasumiru! 
Are you using the Chrome App? We have actually deprecated the Chrome app version of Postman. 
Although we have recently launched Postman on the Web - Here you can experience the latest Postman app with all the recent features directly on any web browser. 

You can download the latest version of the native Postman apps or try out the Web version here: https://www.postman.com/downloads 

Do try this out in one of the latest apps and let us know if you are still facing this.

**Comment by umeshp7** [comment] 2021-03-01 12:26
Hey @JaswantBB, I tried this on the latest version and I couldn't reproduce this. Could you share your Postman App version?
