### ISSUE TITLE
Sorting Folders and APIs under a collection

### ISSUE THREAD

**Issue by SharmaHarsh7** [a85/POSTMan-Chrome-Extension#3306] opened 2017-07-25 05:11 UTC
Hi,

I would like to request a new basic but useful feature.

It would be appreciated if you can add functionality to Sort API Folders and APIs under them.

It is very helpful if we are dealing with large number of APIs and need to find one.

Currently, we have to check each api to find some.

Many Thanks,
Harsh

**Comment by kamalaknn** [comment] 2017-07-25 07:13
Het @SharmaHarsh7, this looks like a duplicate of #3089. I'm closing this. Please follow the parent thread for updates.

**Closed as completed by kamalaknn** 2017-07-25 07:13 UTC

**Comment by sdnts** [comment] 2017-07-25 07:14
On a side node @SharmaHarsh7, if you're looking for a request, you should be able to use the search bar at the top of the sidebar.

**Comment by SharmaHarsh7** [comment] 2017-07-25 07:18
Yes, The search bar is there at the top, but sometimes we need to search under a specific collection or a folder and this is when the sorting is required.

Because multiple collections might have same request and that can cause issues ...

**Comment by chiragpurohit71085** [comment] 2018-01-17 16:04
hI @madebysid 

is there any way to sort api by names in postman? I know api order is important etc, but we are creating api as per controller names, so sorting by api name is sort of must for us. 

Also if that is not directly possible is there any other way to do that? ( sorting by drag and drop is not possible) like creating new collection and exporting etc... Please help me.

**Comment by chiragpurohit71085** [comment] 2018-01-19 06:15
Also there is way to drag and drop multiple requests?

**Comment by SharmaHarsh7** [comment] 2018-01-19 06:26
@chiragpurohit71085, Agree with you.

Also it would be more better idea if we have can open one project API at a time.

Currently postman shows all the Collections in the left sidebar, which is completely useless if we are working on a single application.

There is no way in the app to remove/hide/filter unnecessary  collections from the left sidebar.

Sorting, Collection Filtration etc. are some major UI issues which needs to be address.

**Comment by robertpiska** [comment] 2018-10-25 12:43
> Het @SharmaHarsh7, this looks like a duplicate of #3089. I'm closing this. Please follow the parent thread for updates.

Hi @kamalaknn, you have marked all the sorting requests as duplicate of another request and no one is done
