### ISSUE TITLE
New Integration Request - Azure Repos

### ISSUE THREAD

**Issue by ewoody** [a85/POSTMan-Chrome-Extension#9940] opened 2021-05-16 20:20 UTC
**Describe your current workflow**
Support Azure Repos as good as Github

**Describe your ideal workflow**
We are using Azure repos as version control of the postman json file, and we want to sync between repos and postman collection.

**Comment by abhijitkane** [comment] 2021-07-13 06:09
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9131

**Closed as completed by abhijitkane** 2021-07-13 06:09 UTC
Labels: feature, product/integrations
