### ISSUE TITLE
Parse multi keys from json Object 

### ISSUE THREAD

**Issue by nenro** [a85/POSTMan-Chrome-Extension#3241] opened 2017-07-06 09:29 UTC
HI all,

is there a way to parse specific values into an environment variable?
for example, for the response below i want to have an environment variable which will be according to the following logic [name1 value];[name2 value];[name3 value....] so it will be like that: saving the world,artificial intelligence,cyborg........

{
    "id": 87101,
    "keywords": [
        {
            "id": 83,
            "name": "saving the world"
        },
        {
            "id": 310,
            "name": "artificial intelligence"
        },
        {
            "id": 679,
            "name": "cyborg"
        },
        {
            "id": 1373,
            "name": "killer robot"
        },
        {
            "id": 2964,
            "name": "future"
        },
        {
            "id": 4379,
            "name": "time travel"
        },
        {
            "id": 4565,
            "name": "dystopia"
        },
        {
            "id": 9663,
            "name": "sequel"
        },
        {
            "id": 161151,
            "name": "fiction"
        },
        {
            "id": 179431,
            "name": "duringcreditsstinger"
        },
        {
            "id": 209714,
            "name": "3d"
        }
    ]
}

thanks 
nen

**Comment by kamalaknn** [comment] 2017-07-06 10:46
Hey @nenro,

The following script should help you. You can use this in the "Tests" script.

```
var responseJson = JSON.parse(responseBody);
var joinedValues = _.map(responseJson.keywords, function (keyword) { return keyword.name; }).join(',');

postman.setEnvironmentVariable('envVariable', joinedValues)
```

I am closing this issue as this is not a bug with the Postman App itself.

**Closed as completed by kamalaknn** 2017-07-06 10:46 UTC

**Comment by nenro** [comment] 2017-07-06 11:36
thanks !!!
