### ISSUE TITLE
Swagger Import from API Gateway only works for old chrome extension app

### ISSUE THREAD

**Issue by petermoser** [a85/POSTMan-Chrome-Extension#4414] opened 2018-04-03 18:50 UTC
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
just encountered it today
 2. Expected behaviour:
import from swagger file should show request names (it works in the chrome extension)
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/5367107/38269319-048c7b20-3735-11e8-9bc5-0d6cc7caf1bf.png)

Export postman swagger file in aws API gateway.
Import into chrome extension -> works, request names are displayed
Import into Postman for Mac -> request names are not displayed

**Comment by harryi3t** [comment] 2018-04-05 12:17
@petermoser Please send a minimal collection that can reproduce this to help[at]getpostman.com with the issue number in the subject. This will help us debug this faster. 
Also, please do remove any sensitive information in it.

**Comment by centur** [comment] 2018-04-16 03:32
This issue looks similar to #4458 . I have simple reproduction there.

**Comment by prashantagarwal** [comment] 2018-05-19 05:55
Closing as duplicate of #4458

**Closed as completed by prashantagarwal** 2018-05-19 05:55 UTC
