### ISSUE TITLE
unable to save post (see image)

### ISSUE THREAD

**Issue by jb08** [a85/POSTMan-Chrome-Extension#2717] opened 2017-02-16 20:59 UTC
1. Postman Version: 4.10.0 (4.10.0)
 2. App (Chrome app or Mac app): Mapp app
 3. OS details: 10.11.6 (15G1108)
 4. Is the Interceptor on and enabled in the app: ?
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour: be able to save
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

How do I save this (bug-  missing submit button)? 
![screen shot 2017-02-16 at 2 56 33 pm](https://cloud.githubusercontent.com/assets/8146460/23040843/6c4c2ce0-f458-11e6-998e-a224b71ce85c.png)

**Comment by sdnts** [comment] 2017-02-17 02:17
@jb08 We're aware of this. This is caused when you're zoomed in. We're working on a fix for this. You can also use the shortcut `Cmd/Ctrl+Enter` to save your request. 
Closing this as duplicate of https://github.com/postmanlabs/postman-app-support/issues/2354
Will let you know when the fix is released, which should be soon.

**Closed as completed by sdnts** 2017-02-17 02:17 UTC
