### ISSUE TITLE
Application crashes frequently 

### ISSUE THREAD

**Issue by sujitblues** [a85/POSTMan-Chrome-Extension#4520] opened 2018-05-03 04:48 UTC
Application crashes frequently when i am opening multiple tab and send the request.
I am using postman app version postman  v6.0.10 on windows machine.
please see the attached screen for reference :
![post-add](https://user-images.githubusercontent.com/37321410/39560369-236dd53c-4ebb-11e8-8013-35a8f0c5c67b.png)
Need any more detail ,let me know
Thanks,
Sujit

**Comment by prashantagarwal** [comment] 2018-05-03 12:23
@sujitblues What kind of app crash you are experiencing. Is Postman closing abruptly, or something else. Can you please add a screenshot if possible.

**Comment by sujitblues** [comment] 2018-05-03 13:15
Postman closing abruptly.

Thanks,
Sujit

**Comment by sujitblues** [comment] 2018-05-16 05:25
Please see the log screenshot
![app crash](https://user-images.githubusercontent.com/37321410/40098164-af09b0a2-58f7-11e8-8425-a4ebf5358ea4.png)

**Comment by prashantagarwal** [comment] 2018-07-31 18:06
@sujitblues Can you update to the latest Postman app and see if the issue still persists.

**Comment by numaanashraf** [comment] 2019-07-30 09:32
We are unable to reproduce this issue and we have made major changes & improvements since this issue was created. Please update to the latest version of the app and create a new issue if you are still facing this issue.

**Closed as completed by numaanashraf** 2019-07-30 09:32 UTC
Labels: bug
