### ISSUE TITLE
<title>Reuseable Library for JS

### ISSUE THREAD

**Issue by siddh78** [a85/POSTMan-Chrome-Extension#10559] opened 2022-01-11 19:14 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

The feature is not related to a Problem in the product. But during my use, I have noticed I need to repeat 80% of code in multiple collection [8 - 12 at this point]. It will be great if we can put it as a common library.

### Describe the solution you'd like

A Seperate section to define library script and reuse it in multiple collection / request.

### Describe alternatives you've considered

None - as per my understanding.

**Comment by giridharvc7** [comment] 2022-01-12 07:19
Duplicate of #1180

**Closed as completed by giridharvc7** 2022-01-12 07:19 UTC
Labels: feature
