### ISSUE TITLE
Hard crash when making a request with empty scheme as part of the URL

### ISSUE THREAD

**Issue by mblufkin** [a85/POSTMan-Chrome-Extension#6664] opened 2019-06-05 21:17 UTC
**Describe the bug**
There's a hard crash whenever a call is made with an empty unresolved variable as part of the protocol.
**HARD CRASH** - `GET {{X}}://www.google.com`
**HARD CRASH** - `GET http{{X}}://www.google.com`
**HARD CRASH** - `GET {{X}}http://www.google.com`

It seems to be specifically before the `://`.

**To Reproduce**
1. Make a request with a variable name that doesn't exist prior to the `://` in the URL

**Expected behavior**
An error of some sort.

**App information (please complete the following information):**
Postman for Windows
Version 7.1.1
win32 10.0.17134 / x64

**Comment by codenirvana** [comment] 2019-06-07 07:45
@mblufkin Thanks for reporting this, we've already fixed this in our internal library and will be fixed in our next stable release.

Closing as duplicate of #6533

**Closed as completed by codenirvana** 2019-06-07 07:45 UTC
Labels: duplicate, product/runtime
