### ISSUE TITLE
show errors line numbers for `test` and `pre-request` in the console

### ISSUE THREAD

**Issue by ebookerd1** [a85/POSTMan-Chrome-Extension#7684] opened 2019-11-20 17:13 UTC
Sometimes I make mistakes in my code that cause failures that have nothing to do with the failure in a step. it would be nice to be able to know what line number something is failing so I can debug quicker.

**Comment by codenirvana** [comment] 2021-05-06 14:07
Duplicate of #3803

**Closed as completed by codenirvana** 2021-05-06 14:07 UTC
Labels: feature, product/runtime
