### ISSUE TITLE
Postman app not updating response body when returning image/svg+xml

### ISSUE THREAD

**Issue by randomev** [a85/POSTMan-Chrome-Extension#10490] opened 2021-12-10 10:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

1) Postman app does not update body preview when returned type is image/svg+xml; charset=utf-8 when called multiple times.

2) Also button-bar ["Pretty" "Raw" "Preview" "Visualize" [Dropdown for type v] is missing.

So I'm unable to view raw body either, there is no button for that in the UI.

Server I'm calling is running on local machine and I can verify with normal browser that server is returning different response for each different request with different request parameters as expected.

This was working with previous versions of Postman, unfortunately I don't know how to check what versions I had before
updating to 9.4.0. With previous versions I was able to modify request parameters and see the changed svg immediately as expected.

As if there is some caching going on inside Postman.

### Steps To Reproduce

I made an mimimum viable server with python3 to reproduce this easily. It outputs timestamp as text element
so that we have an SVG-reply that definitely will always be different when called with even slight pause between
calls.

1) Copy following example server to server.py:

-------
```
# Python 3 server example
from http.server import BaseHTTPRequestHandler, HTTPServer
import time

hostName = "localhost"
serverPort = 8080

class MyServer(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "image/svg+xml")
        self.end_headers()
        self.wfile.write(bytes("<svg version='1.1' xmlns='http://www.w3.org/2000/svg'>", "utf-8"))
        self.wfile.write(bytes("<g><text x='10' y='20' font-family='Verdana' font-size='10'>%s</text></g>" % time.time(), "utf-8"))
        self.wfile.write(bytes("<g><rect x='10' y='20' width='20' height='20'/></g>", "utf-8"))
        self.wfile.write(bytes("</svg>", "utf-8"))

if __name__ == "__main__":
    webServer = HTTPServer((hostName, serverPort), MyServer)
    print("Server started http://%s:%s" % (hostName, serverPort))

    try:
        webServer.serve_forever()
    except KeyboardInterrupt:
        pass

    webServer.server_close()
    print("Server stopped.")
```
-------

2) start server with 
python3 server.py

3) make postman app GET request to http://localhost:8080/

Expected behaviour is that timestamp always changes. With above server, it changes sometimes and sometimes not. If I make 5 requests with 1-2 second pause between requests, it will sometimes update to show new timestamp and
sometimes same timestamp stays there. With our normal server it will always return the first svg and not updating at all.
 
4) If tested with normal browser with url http://localhost:8080/ then timestamp is always seen to be changing.

Also when debugging, I can see from above example server output that
request is made at 

127.0.0.1 - - [10/Dec/2021 12:31:50] "GET / HTTP/1.1" 200 -

Also I can see that response headers timestamp at Postman response "Headers"-panel is updated to 

Fri, 10 Dec 2021 10:31:50 GMT

So these 2 match. But timestamp in the response Body - preview still shows

1639132304.597855

that corresponds to 10. Dec 2021, klo 12.31.44.597 GMT+02:00

So the timestamp shown in body preview is 12:31:44 but request is made and received by Postman at 12:31:50.
So clearly body preview panel is not updating it's content as expected.

### Screenshots or Videos

Button bar  ["Pretty" "Raw" "Preview" "Visualize" [Dropdown for type v] is missing:

<img width="777" alt="button-bar-missing" src="https://user-images.githubusercontent.com/541276/145558790-ecc879b7-d4aa-4808-9a59-cde3c20417ee.png">

### Environment Information

```markdown
- Operating System: OS X 12.0.1
- Platform Type: Native App
- Postman Version: 9.4.0
```

**Comment by nopeless** [comment] 2021-12-20 20:17
I'm having same issue

**Comment by shubhbhargav** [comment] 2021-12-26 10:17
@randomev @nopeless  Thanks for raising the concern. I've verified that the response in-fact changes with the repeated calls but the timestamp doesn't in the rendered response..

Let us look into this further and get back to you shortly. In-case this is blocking for you, please feel free to reach out to us at help@postman.com. We can help figure out the older versions of the app which didn't have this issue to unblock you for the short-term.

**Comment by nopeless** [comment] 2021-12-26 10:47
@shubhbhargav any comments about the button bar for "raw view"?

I was specifically having issues with that
ended up using curl to an output file as a temporary fix

**Comment by shubhbhargav** [comment] 2021-12-26 11:01
@nopeless We will look into that as well. :) In order to unblock you, let me share a quick trick that you can use.

Steps:
1. Add the following code in the `Tests`:
```
console.log(String.fromCharCode(...pm.response.stream));
```
2. Open `Postman Console` on the left bottom of your screen
3. Save the request and click the `Send` button
4. You should be able to see the raw data from the response in the console

**Comment by shubhbhargav** [comment] 2021-12-28 06:03
@nopeless @randomev We've identified the issue at our end which was causing the response to be not updated at times. We will be releasing a fix soon. We will update this thread once done.

Regarding the `Raw` and other tabs in the response section, that is by design since viewing the binary data is not helpful for the users in our opinion. Let us know if you feel that there is additional use-case that we are missing.

**Comment by nopeless** [comment] 2021-12-28 07:03
Glad that it will be fixed. But I think the raw button should be there

> @nopeless @randomev We've identified the issue at our end which was causing the response to be not updated at times. We will be releasing a fix soon. We will update this thread once done.
> 
> Regarding the `Raw` and other tabs in the response section, that is by design since viewing the binary data is not helpful for the users in our opinion. Let us know if you feel that there is additional use-case that we are missing.

@shubhbhargav 

I need it to see if svg data is properly generated though

Could it at least be an option? "show RAW button on svg responses"

**Comment by shubhbhargav** [comment] 2021-12-29 04:52
@nopeless We will look into it and let you know. Thanks for the feedback. :)

To be on the same page, you are referring to the binary data in `RAW` button right?

**Comment by nopeless** [comment] 2021-12-29 05:00
> @nopeless We will look into it and let you know. Thanks for the feedback. :)
> 
> To be on the same page, you are referring to the binary data in `RAW` button right?

I'm referring to the text output (isn't that what the RAW button does in html responses?)

**Comment by shubhbhargav** [comment] 2021-12-29 05:01
> I'm referring to the text output (isn't that what the RAW button does in html responses?)

Correct but it's in-fact HTML (or textual representation of the same), not binary. We will look into the same for binary as well.

**Comment by nopeless** [comment] 2021-12-29 07:02
ok, then I need the HTML output for SVG responses @shubhbhargav . Is this possible?

**Comment by coditva** [comment] 2022-01-21 06:31
@randomev @nopeless This is now fixed on the latest Postman app.

@nopeless As for the issue of not being able to see raw response for SVG, I've created a feature request to track it: https://github.com/postmanlabs/postman-app-support/issues/10594. Please feel free to add anything that I might have missed.

Closing this ticket for now. Please feel free to re-open in case of any queries.

**Closed as completed by coditva** 2022-01-21 06:31 UTC
Labels: bug, Response-Section, product/runtime
