### ISSUE TITLE
LinkedIn V2-API + 2.0.0 protocol: can successfully perform request with curl, but postman fails

### ISSUE THREAD

**Issue by Theemuts** [a85/POSTMan-Chrome-Extension#5752] opened 2019-01-09 14:55 UTC
**Describe the bug**
The LinkedIn V2-API in combination with the 2.0.0 protocol cannot make successful requests to the ugcPosts-endpoints; the response has status 500 with the message that contains a Java ClassCastException.  I I make the same request using curl, everything works as expected.

Unfortunately, in order to reproduce this error yourself, you will need a valid authorization token which I cannot provide in this bug report.

**To Reproduce**
- Create a new GET-request to https://api.linkedin.com/v2/ugcPosts?q=authors&authors=List(urn%3Ali%3Aorganization%3A{ID})
- Set two headers, "Authorization: Bearer {TOKEN}" and "X-Restli-Protocol-Version: 2.0.0"
- Make the request

**Expected behavior**
The same results as calling `curl -H Authorization: Bearer {TOKEN}" -H "X-Restli-Protocol-Version: 2.0.0" https://api.linkedin.com/v2/ugcPosts?q=authors&authors=List(urn%3Ali%3Aorganization%3A{ID}) 

**Screenshots**
Curl:
![image](https://user-images.githubusercontent.com/11926636/50906663-dfa52b80-1425-11e9-8dd9-7f0451d97d00.png)

Postman:
![image](https://user-images.githubusercontent.com/11926636/50906791-2eeb5c00-1426-11e9-91f8-a386f88cce24.png)

**App information (please complete the following information):**
 - App Type: Free linux app
 - Postman Version: 6.6.1
 - OS: Ubuntu 16.04

**Comment by vikiCoder** [comment] 2019-08-06 08:39
Hi @Theemuts,

Is this issue still reproducible in the latest version of Postman native app (v7.3.5)? If it is then we need more information regarding the issue to debug. Can you please share a scaled-down version of your collection with one request for which you are facing the issue?

**Comment by Theemuts** [comment] 2019-08-06 11:05
Thank you for your reply, but I won't be able to. I've changed jobs since and no longer have access to these APIs or any of the software I've written there.

**Comment by jro619** [comment] 2019-08-10 20:15
@vikiCoder thanks for offering to help with this! I can step in to assist as my company is still using the LinkedIn API and ran into this same issue with Postman and the new LinkedIn Protocol.

I put together a very simple example of searching for ad accounts. It seems to me the issue is that Postman is encoding parentheses in the URL. However, LinkedIn requires those parentheses to be unencoded with their 2.0.0 query protocol.

To compare, here's the successful curl command:
```
curl -X GET \
  'https://api.linkedin.com/v2/adAccountsV2?q=search&search=(status:(values:List(ACTIVE)))' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Authorization: Bearer <access_token>'
```

And the curl command being generated by Postman:
```
curl -X GET \
  'https://api.linkedin.com/v2/adAccountsV2?q=search&search=%28status:%28values:List%28ACTIVE%29%29%29' \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer <access_token>' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: lidc="b=TB88:g=1861:u=359:i=1565466943:t=1565551897:s=AQExF3RbjIKI3oMBPNdnOcK0Ldvd5uiR"' \
  -H 'Host: api.linkedin.com' \
  -H 'User-Agent: PostmanRuntime/7.15.2' \
  -H 'X-Restli-Protocol-Version: 2.0.0'
```

Here's a link to the scaled-down collection: https://www.getpostman.com/collections/7fa0e6311bc70e85e705. Note that to successfully retrieve data you'll need an access token for a LinkedIn user with access to a LinkedIn Business Account.

Here's the documentation to the new LinkedIn 2.0.0 protocol: https://developer.linkedin.com/docs/guide/v2/concepts/protocol-version.

And the API documentation: https://docs.microsoft.com/en-us/linkedin/marketing/integrations/ads/account-structure/create-and-manage-accounts.

I'm running Postman native 7.3.6.

**Comment by codenirvana** [comment] 2020-03-10 19:26
This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.

Feel free to leave your feedback at #8154 or reopen this thread if the issue persists.

**Closed as completed by codenirvana** 2020-03-10 19:26 UTC
Labels: bug, support, request-sending, product/runtime
