### ISSUE TITLE
OAuth 2.0 authorization type does not encode client id and secret in basic Authorization header

### ISSUE THREAD

**Issue by hmoratopcs** [a85/POSTMan-Chrome-Extension#7378] opened 2019-09-24 11:16 UTC
According to the OAuth 2.0 standard (https://tools.ietf.org/html/rfc6749#section-2.3.1), client id and seceret in the Authorization header must be encoded:

> 2.3.1.  Client Password
> 
>    Clients in possession of a client password MAY use the HTTP Basic
>    authentication scheme as defined in [RFC2617] to authenticate with
>    the authorization server.  **The client identifier is encoded using the
>    "application/x-www-form-urlencoded" encoding algorithm per
>    Appendix B, and the encoded value is used as the username; the client
>    password is encoded using the same algorithm and used as the
>    password.**  The authorization server MUST support the HTTP Basic
>    authentication scheme for authenticating clients that were issued a
>    client password.
> 

I can't use Postman with IdentityServer with a client secret containing for example a "+" character. Postman doesn't encode it and the server correctly decodes it as a space. Another example is "secret%26", it is decoded by the server as "secret&".

**To Reproduce**
1. Go to Authorization tab.
2. Click on "Get New Access Token".
2. Set Grant Type to "Client Credentials" (for example).
3. Set the Token URL.
3. Set the Client ID.
4. Set a Client Secret containing a "+".
5. The login fails.

**Expected behavior**
"+" must be encoded as "%2B", "%26" must be encoded as "%2526", etc. as the standard requires.

**App information**
 - App Type: Native App (Postman for Windows)
 - Postman Version: 7.7.3
 - OS: Windows 10 (win32 10.0.18362 / x64)

**Comment by vikiCoder** [comment] 2019-09-25 17:45
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/7138

See this comment for a temporary workaround: https://github.com/postmanlabs/postman-app-support/issues/7138#issuecomment-535128160

**Closed as completed by vikiCoder** 2019-09-25 17:45 UTC
Labels: product/runtime
