### ISSUE TITLE
Cookie `Max-Age` is not accounted for while representing the expiry of newly added cookies

### ISSUE THREAD

**Issue by tswysy** [a85/POSTMan-Chrome-Extension#7738] opened 2019-12-04 11:50 UTC
**Describe the bug**
I set a cookie with an expiration date. But after the cookie is saved, it shows "Never expires". Usually, this bug is always with the last cookie.

**To Reproduce**
1. Send a request to a service that sets a valid cookie. For example,  the cookie is set to be invalid after 24 hours.
2. Confirm that the cookie is saved, and then check the Expires of the cookie. It shows Never.
3. Send a request to another service and set another different cookie with a valid date.
4. Check the expire of the two cookies, the first one can be right and the last one can be wrong.

**Expected behavior**
It should show the right expire date.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.
The admin_session in the two images is the same cookie.
![image](https://user-images.githubusercontent.com/36076474/70139896-79289c00-16ce-11ea-8f38-9ba7783f54a3.png)
![image](https://user-images.githubusercontent.com/36076474/70139968-a9703a80-16ce-11ea-85cb-ea53345813c9.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [v7.12.0]
 - OS: [windows10 professional 18362.418 ]

**Comment by codenirvana** [comment] 2019-12-04 12:15
@tswysy I am not able to reproduce this issue locally, can you share a scaled-down collection which we can use to reproduce this issue?

Or, can you share a Node.js server like this https://github.com/postmanlabs/postman-app-support/issues/6807#issuecomment-507507349 which can help?

**Comment by tswysy** [comment] 2019-12-05 01:36
> @tswysy I am not able to reproduce this issue locally, can you share a scaled-down collection which we can use to reproduce this issue?
> 
> Or, can you share a Node.js server like this [#6807 (comment)](https://github.com/postmanlabs/postman-app-support/issues/6807#issuecomment-507507349) which can help?

**First you can see my simple example which is written with Golang**
```
package main

import (
	"github.com/gin-gonic/gin"
	"log"
	"strings"
)

func main() {
	r := gin.Default()
	r.GET("/cookie1",setFirstCookie)
	r.GET("/cookie2",setSecondCookie)
	if err := r.Run(":80"); err != nil {
		log.Fatal(err.Error())
	}
}

func setFirstCookie(c *gin.Context){
	c.SetCookie("cookie1","value1",3600 * 24,"/",strings.Split(c.Request.Host, ":")[0],false,false )
}

func setSecondCookie(c *gin.Context){
	c.SetCookie("cookie2","value2",3600 * 24,"/",strings.Split(c.Request.Host, ":")[0],false,false )
}
```
**Then Reproduce The Bug**
1. Send a request to {{ip}}/cookie1, and you can get a cookie saved within postman, but it shows Never Expires.
![111](https://user-images.githubusercontent.com/36076474/70195995-40c2a580-1742-11ea-816b-f7f37afb047f.jpg)
2. Repeat the first step to request {{ip}}/cookie2, you can find that there are two cookies within postman. Cookie1 now shows the right expire date but cookie2 is wrong.
![222](https://user-images.githubusercontent.com/36076474/70196009-491ae080-1742-11ea-8597-17c911906645.jpg)
3. Repeat the first step again, you can find that cookie2 shows the right expire date but cookie1 is wrong again.
![333](https://user-images.githubusercontent.com/36076474/70196019-4e782b00-1742-11ea-94d5-c97a112efe3a.jpg)

**Finally, I think it's clear now**

**Comment by codenirvana** [comment] 2019-12-05 05:30
@tswysy Thanks for the sample server. I can confirm the reported issue i.e, `Max-Age` is not accounted for while representing (view only) the expiry of newly added cookies.
However, the cookies are stored correctly into the store (that's why previously added cookies have the correct expiry set).

Thanks for reporting this issue, will update once this issue is fixed in our production or canary channel.

**Comment by codenirvana** [comment] 2020-03-12 04:58
@tswysy This is fixed in the latest version of the Postman app. 🎉

**Closed as completed by codenirvana** 2020-03-12 04:58 UTC
Labels: cookies, product/runtime
