### ISSUE TITLE
Selecting body parameter, copying and pasting doesn't work properly

### ISSUE THREAD

**Issue by chimit** [a85/POSTMan-Chrome-Extension#3093] opened 2017-06-01 04:34 UTC
1. Postman Version: 4.11.0 (4.11.0)
 2. App (Chrome app or Mac app): Mac app
 3. OS details: macOS Sierra 10.12.5 (16F73)
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: don't know
 6. Expected behavior: parameter should by copied
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

### Steps to reproduce the problem:

1. Select one body parameter with its value using mouse
2. Press Commad+C
3. Switch to another request tab
4. Put cursor into "New key" field
5. Press Command+V

![1](https://cloud.githubusercontent.com/assets/839349/26664624/85fde93e-46c5-11e7-8896-c6648c0ef778.png)

After that, you will see the copied parameter like if you create it manually, but it doesn't really work. It's not sent to the server. I spent a lot of time to realize that the problem is in the Postman, not in my code.

The only way to fix it is to create each parameter manually without copy/paste.

P.S. Few versions ago you added this mouse selection feature into the Postman, but I as for me it's not very convenient because now it's harder to select value or key names using mouse. It always turns into selection rectangle.

**Comment by SamvelRaja** [comment] 2017-06-01 05:53
Thanks for bringing this to our notice, we will let you know the progress in the same thread.

**Comment by Heydiddly** [comment] 2017-07-19 13:54
So _that's_ the problem! Spent a long time trying to figure out why my parameters copied from working requests were never being picked up!

**Comment by a85** [comment] 2017-12-11 15:44
Seems to be fixed in 5.5

**Closed as completed by a85** 2017-12-11 15:44 UTC

**Comment by akaars** [comment] 2018-02-05 13:17
Exactly the same behavior still reproducible in Postman v5.5.2 and Kubuntu 17.10 (started on 17.04, didn't notice the Postman version).
Should I open a new issue about it or may be you'll prefer to reopen this one?

PS
Nevermind, someone already reported it:
https://github.com/postmanlabs/postman-app-support/issues/4108
