### ISSUE TITLE
Socks proxy support

### ISSUE THREAD

**Issue by sgaree** [a85/POSTMan-Chrome-Extension#3728] opened 2017-11-03 15:58 UTC
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64
```

## Issue Report:
 Neither global proxy setting in native app or via system proxy settings appears to honor SOCKS proxy config.

e.g. Global setting: "socks5://localhost" gets changed to simple "localhost" and does not use the local (SSH tunneled) SOCKS5 server.

System proxy set to socks, localhost, 1234 works for browsers (IE, FF), but postman fails.

![image](https://user-images.githubusercontent.com/5863082/32383242-7a335546-c085-11e7-9f74-4f8600caba73.png)

Use case is accessing appliances in a DMZ network
ssh -D 1234 <some_host_that_is_a_firewall_to_a_DMZ>

Postman should be able to use the SOCKS5 proxy.

**Comment by SamvelRaja** [comment] 2017-11-06 13:03
Closing this as it is the duplicate of #1321

**Closed as completed by SamvelRaja** 2017-11-06 13:03 UTC
