### ISSUE TITLE
auto-set of headers can be switch on/off while changing the body type.

### ISSUE THREAD

**Issue by pawanbana** [a85/POSTMan-Chrome-Extension#6182] opened 2019-03-29 10:27 UTC
first select the x-www-urlencoded. 
after  changing the body type from x-www-urlencoded to raw, none, form-data, binary. the header still remains. there should be a option so auto-set header can be switch on/off.

![Screenshot from 2019-03-29 15-49-06](https://user-images.githubusercontent.com/31897605/55226255-8d142800-523a-11e9-9e90-8627f7088c75.png)
![Screenshot from 2019-03-29 15-48-53](https://user-images.githubusercontent.com/31897605/55226256-8dacbe80-523a-11e9-993c-2a77f663b5f9.png)
![Screenshot from 2019-03-29 15-48-28](https://user-images.githubusercontent.com/31897605/55226259-8eddeb80-523a-11e9-8ce7-0aab45d7cfae.png)

**Comment by saswatds** [comment] 2019-06-18 08:33
Duplicate of #2366

**Closed as completed by saswatds** 2019-06-18 08:33 UTC
Labels: feature, request-sending, product/runtime
