### ISSUE TITLE
Newman flags all visualizations as errors

### ISSUE THREAD

**Issue by thomasazdon** [a85/POSTMan-Chrome-Extension#7692] opened 2019-11-21 18:23 UTC
We use newman command line to run against all of our postman collections prior to distributing to clients.  Our QA team relies on error reporting to determine pass / fail of the tests.  All requests with visualizations throw errors.

**Describe the solution you'd like**
We would like a way to either exempt visualizations from the testing - or have the visualizations tested.

**Describe alternatives you've considered**
The alternative we are considering is writing code so that prior to testing all visualization code is removed from the collections and then re-added once the testing is complete.  This requires hand testing of all visualizations. At the moment we have collections in excess of thousands of requests and have built hundreds of visualizations since the feature was released.

**Comment by vikiCoder** [comment] 2020-03-11 09:06
Hi @thomasazdon,

I am not sure what do you mean by Newman throwing error for requests with visualizations 🤔. I created a collection with one request having visualization and a test to check status code 200. Running that collection with newman seems to be working fine for me without any errors.

Here is my collection: https://www.getpostman.com/collections/e06a76487db821550b23
Screenshot of collection run using Newman:
![image](https://user-images.githubusercontent.com/16588032/76399673-09007500-63a5-11ea-8017-15da59f3aece.png)

As you can see, the request is running without any errors/test fails. If I am not understanding your problem correctly, can you please share a scaled-down version of your collection with single request which fails in Newman? It would help me get a clear picture of your issue and reproduce it on my end.

**Comment by codenirvana** [comment] 2020-05-29 20:50
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-05-29 20:50 UTC
Labels: blocked/need-info, product/runtime
