### ISSUE TITLE
Postman "Start Proxy" recorder not saving requests to a collection in the right order its saving randomly

### ISSUE THREAD

**Issue by Monesh-engagedly** [a85/POSTMan-Chrome-Extension#12602] opened 2024-01-29 10:32 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After a recent update to version 10.20 a new "start proxy" function is available.
Using it the requests are visible on postman at runtime in the proper order, but saving them to a collection the order is not maintained.

### Steps To Reproduce

Record a browser session and save the requests to a collection with version above  10.20

### Operating System

macOS

### Postman Version

10.20.0

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by VShingala** [comment] 2024-01-29 12:23
@Monesh-engagedly Thanks for reporting the issue. Currently, the requests saved in the collection are not in any particular order but are grouped by one of 2 option mentioned in below screen.

![image](https://github.com/postmanlabs/postman-app-support/assets/16756296/3ba78dff-8e20-4d6b-9c8f-577c1f9e8d50)

We also wanted to get idea around the expectation of order. Were you looking these requests to be ordered based on time when captured or something else?

**Comment by Monesh-engagedly** [comment] 2024-01-29 12:36
Yes, @VShingala Order needs to be based on the time. Because when we order through Domain name Api wont be work in order login should happen and other api's will work when we order through Domain name it will be alphabetically its getting saved. so all the request will fail due to that

So need a feature to be based on time it will help a lot

**Comment by VShingala** [comment] 2024-01-29 12:39
@Monesh-engagedly Makes sense! We'll keep this thread updated with any future development.

**Comment by VShingala** [comment] 2024-02-13 11:59
@Monesh-engagedly I'm closing this as it's duplicate of https://github.com/postmanlabs/postman-app-support/issues/12511. I'll post further update there.

**Closed as completed by VShingala** 2024-02-13 11:59 UTC
Labels: feature, product/capture-proxy
