### ISSUE TITLE
Client very slow with a large collection expanded

### ISSUE THREAD

**Issue by Jothay** [a85/POSTMan-Chrome-Extension#3952] opened 2017-12-12 01:05 UTC
## App Details:
```
Postman for Windows
Version 5.4.1
win32 10.0.15063 / x64
```
## Issue Report:
**1. Did you encounter this recently, or has this bug always been there:**
Ever since I first loaded a large collection a while ago. The deprecated chrome extension/app and the current windows application both have this same issue.
**2. Expected behaviour:**
Opening Postman, navigating with the collection expanded, filtering, etc. should all perform within a reasonable timeframe instead of several minutes for it to "catch up" or possibly lock up and not return to functional/responsive.
**3. Console logs:**
No data found
**4. Screenshots (if applicable)**
None
## Repro Steps:
1. Import a large collection (several thousand endpoints)
2. Expand the collection in the side-bar.
3. All activities are now slowed including:
* Scrolling
* Filtering
* Interacting with the tabs and entering data into their fields
4. Collapse the collection
5. All activities are back to normal performance

I can provide our collection (privately) which has 10,223 endpoints in it for testing.

**Comment by sdnts** [comment] 2017-12-12 12:13
@Jothay We're aware of performance issues, and are actively working to get these fixed. Your collection should help immensely after we're done to ensure the problem is actually fixed. I will let you know here when this happens so you can send forward your collection to our support email. Thanks for reporting this.

**Comment by kamalaknn** [comment] 2018-04-13 08:59
Hi @Jothay 

This should be fixed in our latest version of Postman. Could you update your app and verify if you're still seeing performance issues?

I'm closing this issue, please report to us if the issue persists.

Thanks!

**Closed as completed by kamalaknn** 2018-04-13 08:59 UTC
Labels: performance

**Comment by Jothay** [comment] 2018-04-18 23:52
@kamalaknn I have loaded in our endpoints again (10,356 requests according to the folder in the sidebar) and it's still significantly slow with the folder expanded. This is with v6.0.10 and the client says there are no updates.

**Comment by kamalaknn** [comment] 2018-04-19 07:24
Hi @Jothay 

We have made several improvements to our view in the recent releases. We've seen that this has improved the performance with thousands of requests spread across collections, folders, and workspaces. This is the case for a lot of our users.

In your case, you have a huge number of requests all in the same collection and I'm guessing, the same level as well. I'm afraid this is an extreme case where our views breakdown or become very slow. 

We suggest you organize your requests into smaller collections and folders. That would help you to work faster.

We do understand there would be reasons for you to organize it this way. We would like to hear more about this. Could you send an email to `help@getpostman.com` so we can set up a call to talk more about this?

Thanks
