### ISSUE TITLE
Multi-language suggestion 

### ISSUE THREAD

**Issue by misaya** [a85/POSTMan-Chrome-Extension#3755] opened 2017-11-09 06:01 UTC
If support the language packages, we will get better feelings

**Comment by prashantagarwal** [comment] 2017-11-09 08:41
@yemadu Thanks for the suggestion.

**Comment by hjkl950217** [comment] 2018-11-24 05:45
Also hope to support zh-cn

**Comment by arlemi** [comment] 2020-01-17 16:54
Closing this since it is a duplicate of #3126.

Please add your input on which language you'd like to see added in the other issue so it's easier for us to track. :)

**Closed as completed by arlemi** 2020-01-17 16:54 UTC
Labels: feature, i18n
