### ISSUE TITLE
Local proxy settings

### ISSUE THREAD

**Issue by szyb** [a85/POSTMan-Chrome-Extension#4045] opened 2018-01-10 09:30 UTC
This problem occurs in standalone windows version. 
I have local proxy installed and all traffic goes through this proxy. Proxy is configured in Windows proxy settings. I'm trying to sent GET request to http localhost service. In Windows proxy settings I set "Do not use proxy for local connections" (which is most likely not taken into account)
Proxy settings in Postman are set to "Use system Proxy"

The error is: Could not get any response
Moreover when I use Postman for Chrome then everything works fine.

## App Details:
Postman for Windows
Version 5.5.0
win32 10.0.16299 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Always
 2. Expected behaviour:
Response from localhost service
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
None for now
 4. Screenshots (if applicable)

**Comment by SamvelRaja** [comment] 2018-01-10 12:56
Can you share us the screenshot of the postmanconsole?
view -> show postman console, this will give us much information to debug thing faster.

**Comment by szyb** [comment] 2018-01-10 13:02
Sure, here you go. "Invalid protocol 127.0.0.1" it says...
![postman](https://user-images.githubusercontent.com/1598139/34774233-d055e542-f60e-11e7-86ac-6c32d190eef1.png)

**Comment by harryi3t** [comment] 2018-01-10 13:31
@szyb Just add protocol to your windows proxy settings

It should be `http://127.0.0.1` instead of `127.0.0.1`

**Comment by harryi3t** [comment] 2018-01-10 13:34
Possible duplicate of https://github.com/postmanlabs/postman-app-support/issues/3667

**Comment by harryi3t** [comment] 2018-01-10 14:10
@szyb 

Since you have selected "Do no use proxy for local addresses", the request should not go through the proxy.

But there is an exception to this, if there is an environment variable is set up for proxy (http_proxy, https_proxy, HTTP_PROXY or HTTPS_PROXY) then Postman will use that.

Also, in that case, we expect the protocol to be present. This error is seen when you have an environment variable like
```
http_proxy=127.0.0.1
```

If this is the case, can you try changing it to
```
http_proxy=http://127.0.0.1
```

If not, please share a screenshot of your proxy configuration.

**Comment by szyb** [comment] 2018-01-10 14:33
@harryi3t 
Yes, I have http_proxy setup. Changing it to "http://127.0.0.1" haven't solved my problem due to my configuration (explained below). I just cannot use proxy to local connections - it just don't work in my case. When I remove this environment variable then it works fine. But I would like to have it defined. 

My configuration is:
I have local proxy (port 4480) which don't requires authentication (available only from localhost). Local proxy uses Non-ICP cascading and it just connects to my corporate proxy server which requires NTLM authentication, however my local proxy is already setup with valid user name and password.
Now I just need to setup my windows proxy to use only local proxy server and I don't need to provide username/password in every application uses internet connection.

As you can see (if I explained it well) the http_proxy variable is the reason why postman doesn't work in my case (for local services). Is there any option to ignore this variable in postman?

**Comment by harryi3t** [comment] 2018-01-10 15:02
This is a known issue/feature request (a setting to disable proxy for env vars also)
For now, there are 3 workarounds

1. You can remove the `http_proxy` env variable. Other non-terminal apps should continue to work using the proxy from operating system.
2. If the above is not possible, then you can also set another env var `NO_PROXY` to the URL(s) that you wish should not go through the proxy
3. You can also create a `.bat` file which un-sets the `http_proxy` variable and opens Postman app
```
set HTTP_PROXY=
set http_proxy=
set HTTPS_PROXY=
set https_proxy=
start Postman.exe
```

**Comment by szyb** [comment] 2018-01-11 07:08
@harryi3t
I will go with 3rd option.
Thank you for your support

**Comment by marcelocesards** [comment] 2018-04-26 21:14
3rd option works to me:

set HTTP_PROXY=
set http_proxy=
set HTTPS_PROXY=
set https_proxy=
P:\Users\myUser\AppData\Local\Postman\Update.exe --processStart "Postman.exe"

**Comment by marcelocesards** [comment] 2018-04-26 21:15
set HTTP_PROXY=
set http_proxy=
set HTTPS_PROXY=
set https_proxy=
P:\Users\myUser\AppData\Local\Postman\Update.exe --processStart "Postman.exe"

**Comment by harryi3t** [comment] 2018-06-29 12:27
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3942

**Closed as completed by harryi3t** 2018-06-29 12:27 UTC
Labels: bug, Proxy

**Comment by ronnac** [comment] 2019-06-11 15:03
In my case, what helped was:
setx http_proxy ""
setx https_proxy ""
