### ISSUE TITLE
UTF-8 Content-Type problem

### ISSUE THREAD

**Issue by newmangreen** [a85/POSTMan-Chrome-Extension#7575] opened 2019-11-04 06:58 UTC
When posting a json string to the server, turkish characters are mingled when reading on server.

At postman, header is:
Content-Type: application/json; charset=UTF-8
JSON is pasted to Body as "raw".

Sent data on Postman: 	"name": "REST işçğüö",
Received data on server: "name": "REST iÅŸÃ§ÄŸÃ¼Ã¶",

At server, request character encoding is set to UTF-8, but no chance.

Postman version: v7.10.0

**Comment by codenirvana** [comment] 2019-11-22 05:55
@newmangreen I am not able to reproduce this issue using `postman-echo`.

![Screenshot 2019-11-22 at 11 20 51 AM](https://user-images.githubusercontent.com/4865836/69401140-3f44b680-0d1a-11ea-804c-07d4f4435ac0.png)

Can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by codenirvana** [comment] 2019-12-12 03:44
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2019-12-12 03:44 UTC
Labels: encode-decode, need-more-info, request-sending, blocked/need-info, product/runtime

**Comment by newmangreen** [comment] 2020-01-13 06:53
OK, fixed the problem. 
For sharing for those having similar problem:
In Servlet,  I had set as request.setCharacterEncoding("UTF-8").
But when reading with request.getInputStream() that is not enough, we have to convert incoming string to "UTF-8" again.
