### ISSUE TITLE
Generate Code Snippet in cURL doesn't escape single quotes in URL

### ISSUE THREAD

**Issue by david-vermeer** [a85/POSTMan-Chrome-Extension#8756] opened 2020-07-10 09:36 UTC
**Describe the bug**
The single quotes in a URL (that are not part of the query string) are not escaped that results into: when exporting the URL in cURL and importing cURL the single quotes are missing.

**To Reproduce**
1. Create a new request e.g. "GET http://mydomain.com/resource('key')"
2. Go to 'Generate Code Snippets'
3. Select language 'cURL'
4. Generated code for cURL is "curl --location --request GET 'http://mydomain.com/resource('key')'"

**Expected behavior**
The single quotes are escaped, otherwise after importing the cURL the single quotes are missing.
1. Create a new request e.g. "GET http://mydomain.com/resource('key')"
2. Go to 'Generate Code Snippets'
3. Select language 'cURL'
4. Generated code for cURL is "curl --location --request GET 'http://mydomain.com/resource(\''key\'')'"

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.27.1
 - OS: Windows 10

**Comment by umeshp7** [comment] 2020-07-11 00:55
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/8674

**Closed as completed by umeshp7** 2020-07-11 00:55 UTC
Labels: product/codegen
