### ISSUE TITLE
Collection Runner not running a test for some endpoints

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#5806] opened 2019-01-22 17:29 UTC
**Describe the bug**
We have swagger validation implemented into our collection. The functions and all the code is in the Collection Tests and after using a tool to produce JSON Schema a tv4 check is run.
Everything works fine when running the endpoints manually, using postman and even Monitors, however during a run with the Runner two endpoints do not run the test (one currently fails other succeeds).
Checked this on other machines as well and experiencing the same issue.

**Expected behavior**
The test should be run for all endpoints in the Collection Runner.

**Screenshots**
First endpoint that doesn't run the test in the runner:
**Manual**:
![image](https://user-images.githubusercontent.com/43671684/51553441-c7dc9700-1e6a-11e9-9aa1-2b5cb2742a50.png)

**Monitor**:
![image](https://user-images.githubusercontent.com/43671684/51553413-b4c9c700-1e6a-11e9-95ef-3771427236bc.png)

**Newman**:
![image](https://user-images.githubusercontent.com/43671684/51553351-864bec00-1e6a-11e9-9232-da33178044ca.png)

**Runner**:
![image](https://user-images.githubusercontent.com/43671684/51553473-da56d080-1e6a-11e9-9a60-21f842c89f8e.png)

----------------------------------------------------------------
Second endpoint that doesn't run the test in the runner:
**Manual**:
![image](https://user-images.githubusercontent.com/43671684/51553599-286bd400-1e6b-11e9-9b8b-4300eec8290e.png)

**Monitor**:
![image](https://user-images.githubusercontent.com/43671684/51553611-2efa4b80-1e6b-11e9-96ac-49c93fb347aa.png)

**Newman**:
![image](https://user-images.githubusercontent.com/43671684/51553561-11c57d00-1e6b-11e9-8e48-1c3b2b7c81f0.png)

**Runner**:
![image](https://user-images.githubusercontent.com/43671684/51553580-1b4ee500-1e6b-11e9-89e6-1923d80fc109.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.7.1
 - OS: macOS Mojave 10.14.2

**Comment by numaanashraf** [comment] 2019-02-03 06:36
@VicKetchup Could you share the full test script that includes the specific test you are facing issues with?

**Comment by VicKetchup** [comment] 2019-02-04 10:17
Hi @numaanashraf,

The full test script (on collection level) is nearly 600 lines and also relies on external library to be loaded on pre-request. I could share the code if you want, however I think it would make more sense to share the collection ID for you to explore. 
Please tell me how would you like to proceed.

**Comment by codenirvana** [comment] 2019-07-03 21:03
@VicKetchup Can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by VicKetchup** [comment] 2019-07-04 09:56
@codenirvana Don't think I could, as there is no guarantee that I will be able to reproduce this. The collection had ~15 more requests at the time (more now) and only those two calls had the issue. We also have another collection is ~50 requests and that issue wasn't spotted there. Could I send you collection/monitor info/ids through email for you to investigate.

**Comment by VicKetchup** [comment] 2019-07-10 09:06
@codenirvana Tried to replicate the issue using the collection shared in https://github.com/postmanlabs/postman-app-support/issues/6850 and the issue seems to be present there as well, as the monitor had the swagger check while the runner didn't for the first request! Please try and use that collection :)

**Comment by codenirvana** [comment] 2019-11-18 10:22
@VicKetchup I am trying to reproduce the issue using the shared collection but not sure what's the exact problem is. 😕 

Can you point me where exactly (which request) the tests are not executed?

**Comment by VicKetchup** [comment] 2019-11-18 10:56
Hi @codenirvana,

I've just tried and it is the very first request in that collection, running manually the second test (swagger validation) was done, however through Collection runner it was not: 
![image](https://user-images.githubusercontent.com/43671684/69046917-f0cdaa00-09f1-11ea-9ba3-096d7a4f92d8.png)

**Comment by codenirvana** [comment] 2019-11-18 12:21
@VicKetchup looks like the script/tests are getting executed but the assertions are not getting listed in the Runner UI.
Thanks for reporting this issue, will let you know once this issue is fixed.

**Comment by saswatds** [comment] 2020-02-12 07:45
Hi @VicKetchup this issue has been fixed in the latest version of the app `7.18.0`. You can update to the latest version to see it working. Closing this issue for now. Feel free to reopen this issue if you find otherwise.

**Closed as completed by saswatds** 2020-02-12 07:45 UTC
Labels: bug, collection-runner, product/runtime
