### ISSUE TITLE
Unable to send files in postman post request

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#6534] opened 2019-05-17 09:10 UTC
When I select the image in postman form-data it is given warning as This file resides outside the working directory and no file is sent in the request

**Comment by saswatds** [comment] 2019-05-17 09:20
Hi @Yajan 
Recently we have updated how file references work with postman. Can you give us more details according to our issues guidelines? 

If you are on v7.1.0 of our app, you can check these to comments to understand how it works 

- https://github.com/postmanlabs/postman-app-support/issues/6516#issuecomment-492930576
- https://github.com/postmanlabs/postman-app-support/issues/4320#issuecomment-490749103

Thanks

**Comment by BCsRock** [comment] 2019-05-17 14:07
We found an issue related with the new update. 
When selecting files outside of `working directory` somehow Postman messes up the command to send the files. This happens only from today, not the days before.

Sometimes, postman generates the correct file references and sometimes it is adding too many slashes. And it really seems random.

I try to explain below.

Files *outside* of Working Directy

When clicking on `Code` with multiple files

Found:
```
curl -X PUT \
  http://localhost:5200/api/command \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: localhost:5200' \
  -H 'Postman-Token: 4af54d5b-94ae-46be-819e-82cd5d8eba57,8434d1f4-fe7c-4e68-aa49-fdb1e2b0f856' \
  -H 'User-Agent: PostmanRuntime/7.13.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 1260' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F publicFiles=@///C:/Users/Documents/Veterinaer_Bericht_01.txt \
  -F publicFiles=@//C:/Users/Documents/Veterinaer_Bericht_02.txt \
  -F 'publicText=Text' \
  -F 'references=["f3a3a224-3dda-46b8-8769-13d2319e0700", "c75a1443-a2bc-44b6-9d9e-c76b6fe2f08a"]' \
  -F publicFiles=@/C:/Users/Documents/README.adoc
```

Note the number of slashes after `publicFiles=@` is always different. 

As a result, only the file `Readme.adoc` was sent correctly. the other files have been skipped,

Expected:

```
curl -X PUT \
  http://localhost:5200/api/command \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: localhost:5200' \
  -H 'Postman-Token: 4af54d5b-94ae-46be-819e-82cd5d8eba57,8434d1f4-fe7c-4e68-aa49-fdb1e2b0f856' \
  -H 'User-Agent: PostmanRuntime/7.13.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 1260' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F publicFiles=@/C:/Users/Documents/Veterinaer_Bericht_01.txt \
  -F publicFiles=@/C:/Users/Documents/Veterinaer_Bericht_02.txt \
  -F 'publicText=I have nothing to hide' \
  -F 'references=["f3a3a224-3dda-46b8-8769-13d2319e0700", "c75a1443-a2bc-44b6-9d9e-c76b6fe2f08a"]' \
  -F publicFiles=@/C:/Users/Documents/README.adoc
```

Note the number of `/` after `publicFiles=@` are only one. The sending works correctly. 

When using files *inside *`working directory` the reference uses only an `@` and is always correct

```
curl -X PUT \
  http://localhost:5200/api/command \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: localhost:5200' \
  -H 'Postman-Token: 6cffe984-4216-43a8-9b36-aacc74f1ea5f,69c46ebb-c370-4d2a-bfa3-4f5a506d8fb3' \
  -H 'User-Agent: PostmanRuntime/7.13.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 873' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F 'publicFiles=@Labo1 - Kopie.txt' \
  -F publicFiles=@Labo1.txt \
  -F 'publicText=I have nothing to hide' \
  -F 'references=["8f7620a4-8704-48cf-98c8-c9b5ac28897b", "c75a1443-a2bc-44b6-9d9e-c76b6fe2f08a"]' \
  -F 'publicFiles=@Labo1 - Kopie (2).txt'
```

**Comment by saswatds** [comment] 2019-05-17 15:10
@BCsRock Yes this is a bug which we are tracking in this issue. More on this in this issue https://github.com/postmanlabs/postman-app-support/issues/6516#issuecomment-493217647

**Comment by nilanjanray** [comment] 2019-05-18 05:18
@saswatds : Can you gives us an idea when the latest will be published with fix? and what's alternative approach/work-around  to continue in the same version?

**Comment by saswatds** [comment] 2019-05-18 08:12
Hi @nilanjanray this issue is specific to absolute paths in windows. What you can do is use the working-directory and keep your files there. Selecting files in working directory use relative-paths and they should work fine.  As of the timeline for the next patch, we are expecting it to go out early next week. 

Hope this helps

**Comment by saswatds** [comment] 2019-05-20 15:16
Hi @Yajan @BCsRock @nilanjanray The patch has been released as part of Postman App v7.1.1
I will be closing this issue as I am tracking this issue here #6516.

If you are still facing this issue feel free to comment on the above-mentioned issue.

Thanks

**Closed as completed by saswatds** 2019-05-20 15:16 UTC
Labels: product/runtime

**Comment by dahernandez** [comment] 2019-05-30 15:25
@nilanjanray go to settings find your working directory root and put your files there.

**Comment by NDTChan** [comment] 2019-06-19 10:02
> @nilanjanray go to settings find your working directory root and put your files there.

Thanks dude

**Comment by khanimranraza** [comment] 2021-09-10 12:57
> 
> 
> @nilanjanray go to settings find your working directory root and put your files there.

still the issue is not solved
