### ISSUE TITLE
New native Postman app - 401 unauthorized

### ISSUE THREAD

**Issue by Fabriciuz** [a85/POSTMan-Chrome-Extension#3926] opened 2017-12-07 09:15 UTC
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Been there since the new native app, worked fine in Chrome app
 2. Expected behaviour: Authorization via Windows AD, like the Chrome app
 3. Console log:
```
GET /VF.LoraService/api/crm/HentAktiveKunder
cache-control: no-cache
postman-token: 404fdfeb-6266-4c0b-afe9-8d8469ad7103
user-agent: PostmanRuntime/6.4.1
accept: */*
host: tst-iis01
accept-encoding: gzip, deflate
HTTP/1.1 401
status: 401
cache-control: private
content-type: text/html
server: Microsoft-IIS/10.0
x-aspnet-version: 4.0.30319
www-authenticate: Negotiate
x-powered-by: ASP.NET
date: Thu, 07 Dec 2017 09:10:32 GMT
content-length: 1293
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
 <html xmlns="http://www.w3.org/1999/xhtml">
 <head>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
 <title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
 <style type="text/css">
 <!--
 body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
 fieldset{padding:0 15px 10px 15px;} 
 h1{font-size:2.4em;margin:0;color:#FFF;}
 h2{font-size:1.7em;margin:0;color:#CC0000;} 
 h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
 #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
 background-color:#555555;}
 #content{margin:0 0 0 2%;position:relative;}
 .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
 -->
 </style>
 </head>
 <body>
 <div id="header"><h1>Server Error</h1></div>
 <div id="content">
 <div class="content-container"><fieldset>
 <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
 <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
 </div>
 </body>
 </html>
```

 4. Screenshots (if applicable)

Steps to reproduce the problem:
Call a web service that assumes that the user is logged in via Windows AD

**Comment by harryi3t** [comment] 2017-12-11 05:08
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/2240
Please upvote and/or subscribe to the original issue for updates.

**Closed as completed by harryi3t** 2017-12-11 05:08 UTC
Labels: feature, Auth
