### ISSUE TITLE
Feature request: Collection - View the "Body"  instead of "Auth" by default

### ISSUE THREAD

**Issue by yishayn** [a85/POSTMan-Chrome-Extension#3389] opened 2017-08-15 18:08 UTC
First, I have to say that I love using Postman!. Thank you!
In any case, I would like to ask you for the following.

**Problem Description**
-----------------------
I have a collection of ~50 POST API requests.
And this collection is duplicated 10 times for different environments.
Each time, I selected an API POST request from the relevant collection,
and I only need to EDIT the values of the request parameters (i.e. User ID).
Currently, each time I select an item from my collection,
by default, it will display the "Auth" window.
So, each time,  I need to select the message "**Body**" Tab instead.
and it is very annoying :-)

**Possible Solution**:
1. when I save API request by clicking  SAVE , it should remember the window state.
i.e. It was on "body" and in JSON format.

2) An easier solution would be to add in the Postman setting, a way to configure the postman to display the Request "Body" by default.

Thank you!

**Comment by kamalaknn** [comment] 2017-08-16 03:52
Hey @yishayn 

Thanks for sending in your feedback. We'll take a look at this. Chears!

**Comment by alahosky** [comment] 2017-10-12 08:39
Agree this is very, very annoying.

When you think about it, for saved items in Collections:
- Authorization: you probably edit once and never again
- Headers: same
- Body: I'm constantly changing values in here

So Body should just be the 1st (and default) tab, as it is by far the most used.
thanks!

**Comment by davidpastrana** [comment] 2017-10-31 13:18
I agree with that, would be very helpful for Mac Postman app.
I have to constantly go to the Body tab as is the most used for everyone.
Therefore, I would like to avoid the default tab of Authorisation.

Thanks,
David

**Comment by a85** [comment] 2017-12-24 21:43
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2086

**Closed as completed by a85** 2017-12-24 21:43 UTC
Labels: feature, user-interface
