### ISSUE TITLE
"Error: socket hang up" while sending request

### ISSUE THREAD

**Issue by markozxuu** [a85/POSTMan-Chrome-Extension#3713] opened 2017-11-02 06:25 UTC
**Postman for Mac**
**Version 5.3.2**

<img width="1280" alt="screen shot 2017-11-02 at 00 14 23" src="https://user-images.githubusercontent.com/16585386/32312582-2eaec83e-bf64-11e7-9836-313d6213b576.png">

**Comment by numaanashraf** [comment] 2017-11-02 06:55
@MAPESO Are you facing the same issue when you request GET `https://postman-echo.com/get`? `socket hang up` error is usually caused by the server closing the connection or timing out.

**Comment by markozxuu** [comment] 2017-11-02 07:18
@numaanashraf 
<img width="1280" alt="screen shot 2017-11-02 at 01 17 03" src="https://user-images.githubusercontent.com/16585386/32314071-9c968024-bf6b-11e7-97b6-1aa3f0f96ded.png">

**Closed as completed** 2017-11-03 11:35 UTC
Labels: support

**Comment by karandtu** [comment] 2019-01-16 19:49
could anybody assist me in resolving this issue . 
Please check the screenshot.
![image](https://user-images.githubusercontent.com/19607478/51274737-8c872780-1995-11e9-87a9-62ddb0713749.png)

**Comment by karandtu** [comment] 2019-01-16 19:50
![image](https://user-images.githubusercontent.com/19607478/51274794-b5a7b800-1995-11e9-83cd-3226fb0a7270.png)

**Comment by vladyslovestepanov** [comment] 2020-04-14 10:59
> @MAPESO Are you facing the same issue when you request GET `https://postman-echo.com/get`? `socket hang up` error is usually caused by the server closing the connection or timing out.

@numaanashraf Could you please verify that I get this error because of the problem on the server side but not because of Postman (I can successfully get a response to any other host, including  GET https://postman-echo.com/get)
![image](https://user-images.githubusercontent.com/52454096/79217531-aee94880-7e57-11ea-930c-d53822eeccde.png)

**App information (please complete the following information):**
Postman for Windows
Version 7.22.1
win32 10.0.18362 / x64
![image](https://user-images.githubusercontent.com/52454096/79217753-0be4fe80-7e58-11ea-861c-d701bcf5f07c.png)
