### ISSUE TITLE
Header Content-Length no longer set correctly (not visible in Postman Console)

### ISSUE THREAD

**Issue by calebrepkes** [a85/POSTMan-Chrome-Extension#3751] opened 2017-11-08 15:20 UTC
## App Details:

```
Postman for Mac
Version 5.3.2
OS X 16.7.0 / x64
```

## Issue Report:

1. On certain network environments, the Header Content-Length is not send properly. Or either I dont see it back in the Console, as that its send. I have this issue, since at my client we changed our Proxy settings. In the old settings, it still works. But with the new one it doesnt. 

Though when I hard code the Content-Length field with a value, then my request succeeds. 

2. Expect my Post call to a website, either via RAW or "application/x-www-form-urlencoded" to succeed properly. To give me back a 200 status result call. Right now Postman gives me the following error: Error: socket hang up. 

3. Im unable to figure out what extra logging I need to share.

4. No applicable. 

## Steps to reproduce the problem:
1. Perform a POST call to a certain website, which is only accessible from within my client. Enter values to call website/ 
2. Gives error

3. Try performing POST call to certain website with header Content-Length:48 plus a value, that mimics exact request, then it works. 

4. Based on stackoverflow suggestions, I tried calculating the Request object size, from the pre-request. 
var rdata = request.data;
console.log(rdata);
var lengthRQ = JSON.stringify(rdata).length;
console.log(lengthRQ);
var requestLength = lengthRQ;
pm.environment.set("contentLength", requestLength);

But that doesnt take in to account any variables that I might be using in my request. So the actual body that is send, is of a different length then the one I calculate over.

**Comment by calebrepkes** [comment] 2017-11-08 16:41
Im on the slack channel, I think that would work a bit faster.

**Comment by prashantagarwal** [comment] 2017-11-09 08:56
@calebrepkes We will investigate this and reach out to you incase we need some more input.

**Comment by BrainStone** [comment] 2017-11-09 21:43
For me the Content-Length header isn't set at all. I've set a raw body in a post request. Content-Type header is updated correctly.

**Comment by calebrepkes** [comment] 2017-12-29 10:28
Hey @prashantagarwal @harryi3t any updates? :-)

**Comment by harryi3t** [comment] 2018-01-01 17:50
@calebrepkes I was not able to reproduce it. 
I tried all formats (form-data, x-www-form-urlencoded, raw & binary)

![postman_console](https://user-images.githubusercontent.com/5207331/34469620-6a1a494c-ef49-11e7-89c2-6becb42a51fc.jpg)

Please share the screenshot of your postman console

**Comment by BrainStone** [comment] 2018-01-01 19:09
@harryi3t this is was I get:
![Screenshot](https://puu.sh/yS9Ds/7f651810de.png)

I created a fresh request, added the content and set the type. `Content-Length` is not set.

**Comment by BrainStone** [comment] 2018-01-02 00:15
Note I use the Windows version

**Comment by harryi3t** [comment] 2018-01-02 06:19
@BrainStone Thanks for your input. 
I see that the request was not successful (connection was refused). When I tried this (hitting to an invalid endpoint), I could also not see the `content-length` header in the console.
But when I intercepted the same request using a proxy in between, I found that it was actually set.

![menubar_and_postman_console_and_mitmproxy_-p_8079_--setheader___q_x-proxy_mitm___python3_6_](https://user-images.githubusercontent.com/5207331/34475456-4774cd0e-efb2-11e7-9dac-62a1eed20e4f.jpg)

Also when the request is successful, I can always see the header in the console too.

I think it might be an issue with just the UI logic and that the header is *always sent* correctly.
To confirm this, could you try any other valid endpoint like `https://postman-echo.com/post` or `http://httpbin.org/post`?

**Comment by BrainStone** [comment] 2018-01-02 16:40
Indeed, It seems to be working when the requests suceeds. Though I definately have had issues with it even though the request itself was working. I mean the application I was working on was crashing because of the missing header. Though admideiately I sent a request before the server was online. And once it was the `content-length` header was definately missing. (Causing my server to crash)

Screenshots:
![https://puu.sh/ySKkC/23ea974f4e.png](https://puu.sh/ySKkC/23ea974f4e.png)
![https://puu.sh/ySKmX/bb8ea0cc1a.png](https://puu.sh/ySKmX/bb8ea0cc1a.png)
![https://puu.sh/ySKoU/7a8c33ce75.png](https://puu.sh/ySKoU/7a8c33ce75.png)

**Comment by harryi3t** [comment] 2018-07-23 10:09
Since the bug is in the console UI, I am closing this. 
If the issue stills persist even on successful requests, please reopen this.

**Closed as completed by harryi3t** 2018-07-23 10:09 UTC
Labels: bug

**Comment by harryi3t** [comment] 2018-07-23 12:42
I have created a separate issue for postman console here https://github.com/postmanlabs/postman-app-support/issues/4867
