### ISSUE TITLE
Workspace deleted when user role is deleted and re-added

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6280] opened 2019-04-12 06:24 UTC
**Describe the bug**
While testing the permissions and roles with a co-worker, I removed my "user" role. Postman app was open, then I re-added the user role and all of a sudden the TEAM workspace is completely gone including the activity.

**To Reproduce**
1. Go to collections in the Team workspace
2. Click on Manage role
3. Remove yourself from the collection and Save
4. Add yourself back to the User role (Editor)
5. Team Workspace deleted

**Expected behavior**
Collections and Team Workspace should stay intact.

**Screenshots**
![delete user role](https://user-images.githubusercontent.com/47771757/56016109-decbb080-5d18-11e9-8b50-e371b408dab2.png)

**App information:**
 - App Type - Native App
 - Postman Version - 6.3.0

**Additional context**
I removed myself from the "user" role and as I was the owner of the collection it got removed from the team workspace, is what I suspect.

**Comment by sivcan** [comment] 2019-04-12 06:35
Hi @Kurmavathar,
We were unable to reproduce this issue.


Couple of questions: 
1. Are you able to reproduce this reliably with other team workspaces too?

2. Which team workspace got deleted? (Did it have the name as _Team Workspace_ or some other team workspace that you had created got deleted?)

3. Also, the app version that you've shared is wrong, can you please verify and update it?
It must be v7.x
To check the app version go to Settings > About 

4. Can you check the web dashboard and see if the team workspace shows up there? https://go.postman.co

**Comment by knifesk** [comment] 2019-04-13 00:57
I was the original user that had the issue. I'll elaborate a bit better to see if you can reproduce the error.. Although I'm not sure if it's an error, it scared the crap out of me haha

The real description of the issue was:
Collections disappeared from the TEAM workspace after removing and adding back the "user" role to myself. I AM the owner of the Collection

- Open webpage (team.postman.co) 
- Go to Team (top-right) -> Manage
- Manage Roles
- Remove the collection's owner's `user` role (leave admin and billing)
- Navigate to collections to check that there's no collections (due to lack of permissions)
- Manage roles, add user role again. 
- Collections still missing.

How to fix:
- Go to: https://go.postman.co/team/elements?type=collection 
- Click on the "share" button of the collections that were on the team's workspace
- Add it back to the desired workspace.
- Fixed.

I hope it leads you to fix the issue. 

What I was trying to do? I was testing if I could still access the collection's docs (web version) without the "user"role because one of the team members only needs that. She never changes the requests and I needed to include one more person to the team.. After checking I couldn't access the collection without the role I ended up buying one more slot

**Comment by preethammavin** [comment] 2019-04-13 08:37
@knifesk I understand the issue 

When developer role is removed for the user we unassign the roles for the specific workspace
When the role is reassigned again we do not restore all the roles he already had 

But the said user should still have access to all team workspaces, it would take about a minute to restore permissions which might lead you to believe the Team Workspace was deleted.

We do not unshare collection.

**Comment by knifesk** [comment] 2019-04-13 08:41
I had access to the team workspace, but the collection seems to be unlinked
from the workspace. Workspace was fine, collection was fine... but when you
tried to access the collection you got an error saying that collection
wasn't assigned to any workspace

I actually took me a minute to fix it, but in the meantime had to ask for
help as I assumed that everything was gone and if I kept messing around I
would destroy my chances of getting something back....

**Comment by preethammavin** [comment] 2019-04-13 09:44
@knifesk I understand the concern, one question did you have to join the team workspace again?

**Comment by knifesk** [comment] 2019-04-13 15:27
I have team 3 workspaces, when I regained the "user" role I had to click
"join" on the 3 of them... When I did that I hoped to see the collections
again and right after that I realized that something went terribly wrong

**Comment by preethammavin** [comment] 2019-04-15 04:29
@knifesk Got it, I understand the issue better now. But this was one of the expected behaviour of the older version of the app. When you removed the user role, we remove the collection from the team context for the collection shared from that user. So when you added the user back, the collection could be shared again in the team context.

This behaviour has been changed in the latest version of Postman, with 7.x we introduced RBAC where a collection created/shared in the team remains with the team when the user role or the user is removed. The issue you mentioned would not happen in the said scenario. Hope this answers your question, will close the thread for now. Do let me know if this doesnt clarify the scenario :).

**Closed as completed by preethammavin** 2019-04-15 04:29 UTC
