### ISSUE TITLE
Setting up CORS headers for mock server

### ISSUE THREAD

**Issue by tudorgeorgescu** [a85/POSTMan-Chrome-Extension#4603] opened 2018-05-25 19:56 UTC
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 14.5.0 / x64
```

I am trying to setup a mock server to be able to test my Single page app also without the API server running, but the browser fails to pass the CORS checks, although I created a mock for the OPTIONS call and included all Access-Control-Allow-* headers in the Example for the mock. 
When checking the actual response the browser gets, I can see that the Headers were not sent as I set them (ex. Access-Control-Allow-Origin still responds with *, instead of the origin I set in postman, and which is actually returned if I call the mocked API via Postman)

**Comment by hamecodedVia** [comment] 2018-05-31 12:45
having the same problem. 
![image](https://user-images.githubusercontent.com/36043932/40782958-a069a3d8-64e9-11e8-934c-61ef846196f4.png)

**Comment by ratpik** [comment] 2018-06-13 14:48
@tudorgeorgescu @hamecodedVia - CORS support is enabled by default for all mock servers. You do need to add a OPTIONS request in your collection to enable CORS. The mock server automatically adds the `Access-Control-Allow-Origin: *` to the preflight request.

If you do specify a header for the `Access-Control-Allow-Origin: yourdomain.com` in your saved example, then the cross-origin call that you make should have an origin set in the request that matches `yourdomain.com`.

**Comment by tudorgeorgescu** [comment] 2018-06-26 16:45
well, the wildcard (*) is not allowed by Chrome... so the pre-flight check
fails

**Comment by tudorgeorgescu** [comment] 2018-06-26 16:57
@atpik that's the problem it "should" set the domain to the one you write in the
example (like yourdomain.com), but it actually always sends (*), so the browser will reject it

**Comment by preethammavin** [comment] 2018-06-27 10:25
@tudorgeorgescu Thats odd, can you give us a screenshot of the error so that we can look into it?

**Comment by tudorgeorgescu** [comment] 2018-08-29 19:59
Here it is.
I set the Access-Control-Allow-Origin but the mock still responds with *
![postman cors](https://user-images.githubusercontent.com/24169443/44812120-b3a3af00-abd6-11e8-8eb2-61400f0506e3.png)

**Comment by tudorgeorgescu** [comment] 2018-08-29 20:08
@hamecodedVia did you manage to solve it? I still couldn't set it up ...

**Comment by hamecodedVia** [comment] 2018-08-30 08:38
no

**Comment by ratpik** [comment] 2018-08-30 16:35
@hamecodedVia @tudorgeorgescu - Currently Mock Server will always return * in the `Access-Control-Allow-Origin` header even when you have specified your own custom domain in the example. We will be releasing a patch with a fix for this soon.

**Comment by tudorgeorgescu** [comment] 2018-08-30 18:48
Sounds great. Looking forward to this!
Any rough ETA?

**Comment by ratpik** [comment] 2018-09-03 08:00
@hamecodedVia @tudorgeorgescu - I tried reproducing this behavior in the latest version of Postman Mock Servers but I am unable to reproduce it. I am getting the `Access-Control-Allow-Origin` to be the domain that I have set in my saved example (Screenshot attached below). Can you verify that you do not have multiple saved examples in your collection that match the same request?

<img width="1059" alt="screen shot 2018-09-03 at 1 26 26 pm" src="https://user-images.githubusercontent.com/210420/44974413-3765ee80-af7d-11e8-848e-c8819fb99630.png">

<img width="1059" alt="screen shot 2018-09-03 at 1 26 13 pm" src="https://user-images.githubusercontent.com/210420/44974422-3d5bcf80-af7d-11e8-90bc-fbe24e8238a8.png">

**Closed as completed** 2019-03-06 18:44 UTC
Labels: bug, product/mocks

**Comment by ratpik** [comment] 2019-03-25 11:48
To enable CORS for all users of Postman Mocks, we detect if the incoming request is a preflight request by relying on the request method and the `Access-Control-Request-Method` header and reply with a response that has `Access-Control-Allow-Origin: *` header without looking at the saved examples. Most users of Postman Mock's do not explicitly save an example with the `OPTIONS` method and expect the mocks to work out of the box with CORS.

**Comment by hungvhau** [comment] 2019-09-06 15:02
Was the end of this conversation is that the Access-Control-Allow-Origin will always respond with a * and we cannot override this header with a Mock?

It seems like I am able to override this header when calling it from Postman.

The problem is when we view the website from a browser the header Access-Control-Allow-Origin: * is returned... which Chrome and Firefox blocks... 

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://????.mock.pstmn.io/v1/test’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’)`

**Comment by aasen** [comment] 2020-02-20 08:26
> To enable CORS for all users of Postman Mocks, we detect if the incoming request is a preflight request by relying on the request method and the `Access-Control-Request-Method` header and reply with a response that has `Access-Control-Allow-Origin: *` header without looking at the saved examples. Most users of Postman Mock's do not explicitly save an example with the `OPTIONS` method and expect the mocks to work out of the box with CORS.

Does this means that it isn't possible to mock preflight requests? It seems like I can't override any headers, and that saved examples aren't looked that at all. Which means that I can't use mock server for recreating and fixing errors regarding this.

**Comment by gaurav5430** [comment] 2020-07-25 21:32
To add to the conversation.

I have mocked a POST request and a OPTIONS request, for both of which I have examples pointing ACCESS-CONTROL-ALLOW-ORIGIN header to the correct domain, but from the browser I still get the header value as *

So, assuming this is expected behaviour and the original issue hasn't been fixed?

**Comment by rdazvd** [comment] 2021-03-29 20:49
Excuse me if I'm wrong, but from my understanding it seems like this issue hasn't been fixed. Inside the Postman app, I can successfully override the value of `Access-Control-Allow-Origin` in the response header when mocking a PUT request. But when issuing the same request to the same mocked end-point from the browser, just like @gaurav5430, I get `*` as the value for this header in the dynamically generated OPTIONS request (I tried up-to-date versions of Chrome and Firefox).

**Comment by noztea** [comment] 2021-12-06 16:19
Still have the same problem. Postman is returning a good allow origin, but chrome still return `*`

**Comment by bb100d** [comment] 2022-08-02 17:34
This problem still exists. Please add the ability to mock the OPTIONS in browsers.

Browsers are including `access-control-request-method` in the header, and this appears to be getting intercepted by Postman and not allowing the request to hit the mocked OPTIONS

**Comment by Haayzeed** [comment] 2023-11-24 03:06
Set `Access-Control-Allow-Credentials` to `true`. This works for me
