### ISSUE TITLE
Postman modifies the content of the request body through the pre-request. 

### ISSUE THREAD

**Issue by yewanji** [a85/POSTMan-Chrome-Extension#11154] opened 2022-08-05 07:28 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

A lot of times, what we send to the background needs to be encrypted, so I came up with a pre-request, where you encrypt the body of the request before you send it to the background
![image](https://user-images.githubusercontent.com/42515433/183024407-d46dc437-272b-4c42-8d72-5f883a97513c.png)
![image](https://user-images.githubusercontent.com/42515433/183024649-68a5cbc6-f073-41e1-8146-2849642a7f38.png)

### Steps To Reproduce

  Chorus

### Operating System

WINDOW

### Postman Version

 7.36.6

### Postman Platform

Postman App

**Comment by DannyDainton** [comment] 2022-08-05 09:10
Hey @yewanji 

Can you update the issue with a clear set of steps to reproduce this problem, please?

I can see that you have mentioned you're using 7.36.6 - Is this still an issue you're facing in the latest version of the platform?

**Comment by DannyDainton** [comment] 2022-08-11 09:31
Closing this out due to a lack of information - If you're able to provide the updated details, we can look at reopening the request again.

**Closed as completed by DannyDainton** 2022-08-11 09:31 UTC
Labels: need-more-info, request-body-format
