### ISSUE TITLE
Exeuting examples

### ISSUE THREAD

**Issue by marczahn** [a85/POSTMan-Chrome-Extension#5525] opened 2018-11-13 13:14 UTC
Hi,

this is a feature request/wish:

#### From my point of view it would be nice if I would be able to execute examples as well as the actual request config.

I stored my requests with some sample parameters which I then use on demand. This means that I sometimes need to remove or add parameters - depending on what I need at this moment which is a little annoying with the time.

**Comment by numaanashraf** [comment] 2018-11-13 23:49
Duplicate of #3694

**Closed as completed by numaanashraf** 2018-11-13 23:49 UTC
