### ISSUE TITLE
Postman 6.5.2 still hanging with GPU issue

### ISSUE THREAD

**Issue by beirtipol** [a85/POSTMan-Chrome-Extension#5536] opened 2018-11-16 11:10 UTC
Downloaded the latest version today and Postman wouldn't start up. Process explorer showed that it was crunching through CPU and RAM but the app itself was hanging with a blank screen. I followed the thread on https://github.com/postmanlabs/postman-app-support/issues/4578 and added the environment variable POSTMAN_DISABLE_GPU=true and restarted Postman and it seems to work now.

Raising a new issue because the one referenced above has been closed.

Running on
Windows 7
Dual Xeon E5-2620
48GB Ram
Dual Nvidia Geforce GT 610

**Comment by numaanashraf** [comment] 2018-11-16 19:38
Duplicate of #4594

**Closed as completed by numaanashraf** 2018-11-16 19:38 UTC
