### ISSUE TITLE
False-positives for link highlighting if `/` included in the response

### ISSUE THREAD

**Issue by Dentrax** [a85/POSTMan-Chrome-Extension#8893] opened 2020-08-06 09:02 UTC
**Describe the bug**
False-positive link highlighting.

**To Reproduce**
1. Create a bare-minimum mock response: `"test": "foo/bar/ baz"`
2. Send
3. Scroll down to `test` field
4. See the false-positive _Follow-Link_ popup on the `/bar/`.

**Expected behavior**
It shouldn't recognize this syntax as link.

**Screenshots**
<img width="374" alt="Screen Shot 2020-08-06 at 11 54 22" src="https://user-images.githubusercontent.com/16493751/89512507-02531e00-d7dc-11ea-9371-cae52cfbe7c3.png">

**App information (please complete the following information):**
 - App Type: _Native App_
 - Postman Version: _7.29.0_
 - OS: _macOS High Sierra 10.15.3_

**Comment by codenirvana** [comment] 2020-08-06 10:46
Duplicate of #7004

**Closed as completed by codenirvana** 2020-08-06 10:46 UTC
Labels: duplicate
