### ISSUE TITLE
Required and optional parameters

### ISSUE THREAD

**Issue by danni-popova** [a85/POSTMan-Chrome-Extension#7580] opened 2019-11-05 10:38 UTC
**Is your feature request related to a problem? Please describe.**
When documenting a request, there is no way of stating whether a request param is optional or required other than specifying that in the description.
Validating all the required params for the specific request are filled in would also be very helpful with a warning when trying to send the request without the required values.

**Describe the solution you'd like**
Either use the checkboxes next to the request params to identify whether a parameter is optional or required or have another designated check box that would also allow you to validate those params have values before being able to send the request. 

**Describe alternatives you've considered**
In Swagger docs, you are able to specify when a request param is required. 

![image](https://user-images.githubusercontent.com/43949046/68200750-65e3bd00-ffb8-11e9-81b7-232e0400ef82.png)

**Additional context**

**Comment by Raja-Simha** [comment] 2020-02-08 00:19
Duplicate of #7890

**Closed as completed** 2020-02-08 00:20 UTC
Labels: feature, product/documentation
