### ISSUE TITLE
when using - "duplicate tab"  - it no longer duplicate the URL and headers

### ISSUE THREAD

**Issue by drormik** [a85/POSTMan-Chrome-Extension#9539] opened 2021-02-03 17:48 UTC
**Describe the Issue**

> when using -right-click with mouse on a current tab and choosing   "duplicate tab"  option - the new tab doesnt copy over headers and URL  of the original tab

**Steps to Reproduce**

> A list of steps that can be followed to recreate the issue.

1. do a GET request and enter a URL and some headers
2. right click on the current tab and hit "duplicate"
a new tab will be added ,  But the headers and URL fields are blank in the new tab

**Environment Information**

 - Platform Type: [e.g. Native Desktop App, Postman On The Web, Web Dashboard]   Native Desktop App Windows 
 - Postman Version: Version 8.0.4
 - Operating System:  windows x64 bit

**Comment by DannyDainton** [comment] 2021-02-04 09:52
Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9493

**Closed as completed by DannyDainton** 2021-02-04 09:52 UTC
Labels: duplicate
