### ISSUE TITLE
postman crash after each POST or GET

### ISSUE THREAD

**Issue by scholid** [a85/POSTMan-Chrome-Extension#7292] opened 2019-09-10 01:10 UTC
**Describe the bug**
when POST to API, it successfully make a call since my server script is executed but POSTMAN is crashed and close the app before i get my response. I re-install the application, problem is solve momentarily and it start to crash again.

**To Reproduce**
1. Go to 'collections'
2. select any 'POST' API
3. click on 'SEND'
3. POSTMAN app close itself

**Expected behavior**
I expected to see the response from the API call

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.6.0] win32 6.3.9600 / x64
 - OS: [windows 8.1]

**Additional context**

**Comment by d199** [comment] 2019-09-10 04:23
Exact same problem

**Comment by codenirvana** [comment] 2019-09-10 19:40
@scholid That will be tricky to debug. Can you share more detail about the request?
App version, is it using pre-request or test scripts, etc?

Also, what's the average response size for your requests?

**Comment by CharlieReitzel** [comment] 2019-09-11 18:45
On Windows 10, instead of crashing, it starts getting connection timeouts for every request (GET, POST).  But, now that you mention it, it seems to be ok until the 1st POST.

**Comment by scholid** [comment] 2019-09-11 21:35
> @scholid That will be tricky to debug. Can you share more detail about the request?
> App version, is it using pre-request or test scripts, etc?
> 
> Also, what's the average response size for your requests?

App version 7.6.0
using reqular POST with environment setup
The response should be just a simple xml, no more than 10 lines,

all POST crash the POSTMAN
some GET crashing and other GET is ok => i can not isolate the problem with GET

**Comment by shamasis** [comment] 2019-09-15 22:29
All that is needed to debug this is a shareable collection with a public endpoint or a simple server code that can create this endpoint locally. Right now it’s near impossible to reproduce. But we are still trying. If sharing over public issue tracker isn’t feasible, please reach out to help@getpostman.com and we can try reproduce this.

**Comment by codenirvana** [comment] 2020-03-10 23:26
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-03-10 23:26 UTC
Labels: bug, need-more-info, product/runtime

**Comment by apporto** [comment] 2020-06-09 18:03
Exact same problem on Linux Mint 18.2

**Comment by arlemi** [comment] 2020-06-10 09:42
@apporto Please open a new issue with as many details as possible so we can reproduce the issue. If you can't share the details of the request on a public tracker then please reach out directly to our support on `help@postman.com`.

**Comment by tushar-accenture** [comment] 2021-01-12 09:36
Facing the same problem in MacOS Catalina
