### ISSUE TITLE
 Postman waits endlessly when he receives a 102 statuscode.

### ISSUE THREAD

**Issue by anderjoy** [a85/POSTMan-Chrome-Extension#8076] opened 2020-02-18 01:04 UTC
**Describe the bug**
When the server responds with a 102 code (processing), the postman waits infinitely.

If a timeout time is set, the postman decrees a timeout after that time, but does not process statuscode 102.

**To Reproduce**
Just call an API that returns 102.

**Screenshots**
![image](https://user-images.githubusercontent.com/6249874/74695001-204aa900-51d1-11ea-900c-2b8df5ccac7a.png)

![image](https://user-images.githubusercontent.com/6249874/74695010-30628880-51d1-11ea-9ca5-7888eac5e634.png)

**App information (please complete the following information):**
 - App Type: .net core 3.1
 - Postman Version: 7.18.1
 - OS: Windows 10

**Comment by mantoshelis** [comment] 2020-02-18 19:45
Same for me on Arch Linux.

**Comment by coditva** [comment] 2020-03-05 06:13
Hey, according to the RFC (https://tools.ietf.org/html/rfc2518#section-10.1), status code of `102` is sent specifically to ask the client to wait for a response.

> Methods can potentially take a long period of time to process,
   especially methods that support the Depth header.  In such cases the
   client may time-out the connection while waiting for a response.  To
   prevent this the server may return a 102 (Processing) status code to
   indicate to the client that the server is still processing the
   method.

When request timeout option in Postman is not set, we wait for the response because we know that the server is "Processing". This is the expected behaviour.

When timeout option is set, we know that the intention is to not wait for response endlessly and we timeout the request.

Closing this issue as it is the expected behaviour. @anderjoy Do let me know if you have any other doubts.

**Closed as completed by coditva** 2020-03-05 06:13 UTC
Labels: product/runtime

**Comment by anderjoy** [comment] 2020-03-05 15:36
> Hey, according to the RFC (https://tools.ietf.org/html/rfc2518#section-10.1), status code of `102` is sent specifically to ask the client to wait for a response.
> 
> > Methods can potentially take a long period of time to process,
> > especially methods that support the Depth header.  In such cases the
> > client may time-out the connection while waiting for a response.  To
> > prevent this the server may return a 102 (Processing) status code to
> > indicate to the client that the server is still processing the
> > method.
> 
> When request timeout option in Postman is not set, we wait for the response because we know that the server is "Processing". This is the expected behaviour.
> 
> When timeout option is set, we know that the intention is to not wait for response endlessly and we timeout the request.
> 
> Closing this issue as it is the expected behaviour. @anderjoy Do let me know if you have any other doubts.

Hello...

Thanks for answering.

Since the server has already responded with this code, how do you suggest that it responds again with another status code?

For the server this request has already been completed, there is nothing in the pipeline.

We use this code to notify the customer that the request is still processing, that they should wait a few seconds and try again. In our understanding, this code helps to avoid problems in the "retry pattern" since the verb "post" is not idempotent.

I did the test with another test application, and the result was different from Postman, in it, when receiving 102 status code the application does not "freeze" and shows the correct response code: 102 Processing.

**Comment by kevinswiber** [comment] 2020-03-05 17:31
> Since the server has already responded with this code, how do you suggest that it responds again with another status code?
> 
> For the server this request has already been completed, there is nothing in the pipeline.

Hi, @anderjoy.  HTTP clients that understand `102 Processing` should leave the connection open.  This is essentially a keep-alive ping to inform the client that the request has 1) been received and 2) is actually being handled by the server.

> We use this code to notify the customer that the request is still processing, that they should wait a few seconds and try again. In our understanding, this code helps to avoid problems in the "retry pattern" since the verb "post" is not idempotent.

Consider perhaps returning a [`202 Accepted`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202) response on the initial request.  This can help model a job pattern in API design.  In the 202 response, it's sometimes common to include a `Location` header that points to a resource that will return a status update for the job (e.g., received, processing, complete).  If attempting to notify the client that the request has already been received on subsequent, identical calls, consider returning a `400 Bad Request` with details in the representation that explain the request has already been received.

> I did the test with another test application, and the result was different from Postman, in it, when receiving 102 status code the application does not "freeze" and shows the correct response code: 102 Processing.

Not all HTTP clients understand `102 Processing`.  It has, for all intents and purposes, been deprecated at this point.  HTTP clients that don't understand 1xx response status codes will typically ignore it and close the connection after receiving the response.

Postman's behavior here models exactly what's expected in an HTTP client that actually supports 102, IMHO.

**Comment by debuglevel** [comment] 2021-01-09 21:00
I would suggest to show the user a notice about what you described, @kevinswiber.
e.g. `Server sent 102 Processing... waiting for request to finish`
