### ISSUE TITLE
Getting 'Error: connect ECONNREFUSED' while sending the request from Postman and same is working in another machine

### ISSUE THREAD

**Issue by mohank1986** [a85/POSTMan-Chrome-Extension#4494] opened 2018-04-26 01:57 UTC
## App Details:

Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
Console Log:

Error: connect ECONNREFUSED 10.39.145.155:1006
Request Headers:
x-application:"sample_app"
x-profileid:"test_profileid"
x-channel:"sample_channel"
x-requestcorrelationid:"23e4567-testing_requestCorrelationId"
x-requestdatetime:"2017-09-07T15:30:00-05:00"
cache-control:"no-cache"
postman-token:"e16f20e8-2d6f-492e-bc20-c5bae350e512"

**Comment by sdnts** [comment] 2018-04-26 12:31
Hi @mohank1986, you seem to be on a pretty old version of Postman. Can you update to the latest (6.0.10 as of now) and see of the problem persists?
Moreover, can you list some differences in both those machines (network-wise, proxies, firewalls etc.) that might help us debug this?

**Comment by mohank1986** [comment] 2018-04-26 23:50
Hi Team,

I have installed the latest build(6.0.10) and found the same issue again.

**Comment by mohank1986** [comment] 2018-05-02 06:43
Hi Team,

Any update on the above ticket. Same request is working in another machine without changing any proxy settings. We are sending the request behind firewall and tried using both Global Proxy Config and Use System Proxy settings.

With Global Proxy Settings --> We are getting Gateway Timeout
With Use System Proxy settings --> We are getting 'Could not get any response' error

**Comment by codenirvana** [comment] 2019-05-13 12:15
@mohank1986 Looks like an issue with proxy setup. Also, try setting "SSL verification" to off.

**Comment by codenirvana** [comment] 2019-08-14 07:40
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2019-08-14 07:40 UTC
Labels: bug, request-sending, blocked/need-info, product/runtime

**Comment by hoasaritasa** [comment] 2020-07-21 04:52
Got the same issue today. My colleague (next to me) use exactly the same config, no proxy setting, in the same LAN network, and only I got the "Error: connect ECONNREFUSED"
