### ISSUE TITLE
Collection variables are not present in auto complete dropdown or highlighted

### ISSUE THREAD

**Issue by YemSalat** [a85/POSTMan-Chrome-Extension#2336] opened 2016-09-21 10:05 UTC
1. Postman Version: 
2. App (Chrome app or Mac app): Chrome app
3. OS details: OSX
4. Is the Interceptor on and enabled in the app: na
5. Did you encounter this recently, or has this bug always been there: not sure
6. Expected behaviour:

I am trying to import a collection with some variables pre-set in it.
Here is the part of my .postman_collection that does that:

```
{
  "variable": [
    {
      "id": "hostUrl",
      "name": "hostUrl",
      "value": "__TEST__",
      "type": "string"
    }
  ]
...
```

And then in the url I have: `{{ hostUrl }}/foo/bar`

But when I submit the request in postman - it does not render the variable value - instead it encodes the curly brackets and spaces: `http://%7B%7B%20hostUrl%20%7D%7D/foo/bar`

Any idea what might be wrong here?

PS I am using postman collection v2 format

**Comment by abhijitkane** [comment] 2016-09-21 10:06
@YemSalat The V2 format supports variables, but support for this feature isn't available in the app yet.
For now, you'll need to create an environment with these variables.

**Comment by YemSalat** [comment] 2016-09-21 10:09
I see, thanks for the explanation @abhijitkane!
Do you by any chance know if there is any planned roadmap for adding this feature?

**Comment by Christoph-Harms** [comment] 2017-01-23 16:17
Any update on this? Trying to export API-information from an existing project to postman v2 format, this feature would really help. Thanks in advance!

**Comment by sdnts** [comment] 2017-01-26 05:39
@Christoph-Harms While there isn't a concrete ETA I can provide right now, rest assured, this is under development :D

**Comment by gaieges** [comment] 2017-03-08 22:05
Just started to get involved in postman, huge fan so far.  

I have this same problem as well though. Is there an update as to where this stands?  

Seems as though when I update a collection via the API I can submit a collection with the following format:

```
{
  "collection": {
  	"variables": [
      {
        "enabled": true,
        "key": "prefix",
        "value": "/v1/dir",
        "type": "text"
      },
      {
        "enabled": true,
        "key": "port",
        "value": "443",
        "type": "text"
      }
    ],
  	"info": {
  		"name": "mycollection",
  		"_postman_id": "a32123c3-10d1-2564-6998-466d2c123d6",
  		"description": "",
  		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
  	},
  	"item": [
  		...
  	]
  }
}
```

But when I request the object back from the API it basically wiped out all the variables from that clause.  Is that expected given this issue?

**Comment by sdnts** [comment] 2017-03-20 13:07
@gaieges The Pro API does not support collection variables (yet). We're actively working on making this possible. Will let you know here when we have an update.

**Comment by chhorz** [comment] 2017-10-13 06:33
Hey there,
its a while since the last update on this issue. Is there any update in the meantime?
This would be a very helpful feature.

**Comment by Ocsidot** [comment] 2017-12-07 09:29
Hello,
Normally, the collection variable feature should be in the current release.
I can add variables in the collection, it's good, but I can't use these variables in any request or in tests.
Is there something wrong ?

Thanks

**Comment by kamalaknn** [comment] 2017-12-07 09:32
@Ocsidot Thats odd. Could you elaborate on how you're setting and using the collection variables?

Maybe a screenshot of the app or the exported collection will help us narrow it down.

**Comment by Ocsidot** [comment] 2017-12-07 10:35
@kamalaknn Here are some screenshots

![2017-12-07 11_31_05-postman](https://user-images.githubusercontent.com/6094145/33710967-9274e21e-db42-11e7-983f-a0c300fa01e7.png)
![2017-12-07 11_32_32-postman](https://user-images.githubusercontent.com/6094145/33710975-9595bd2e-db42-11e7-8b2d-7e437829200b.png)

And I don't know how to call this collection variable inside a test script ??
Thanks for your help

**Comment by kamalaknn** [comment] 2017-12-07 10:49
@Ocsidot 

Can you make sure you've saved the collection after adding the variables and the request into this collection?

You should be able to use the collection variables in scripts with `pm.variables.get('testVar')`.

If you're not able to see this working could you export the collection and share it with us?

**Comment by Ocsidot** [comment] 2017-12-07 14:22
@kamalaknn , thank you, now it works in test and pre-request scripts :+1: 

I can use the variable in request but the auto completion and the  preview does not work.

**Comment by kamalaknn** [comment] 2017-12-07 14:32
Great! Closing this issue then.

We'll work on improving this in the next few releases where we'll work on auto-completion and preview.

**Comment by dasjestyr** [comment] 2017-12-18 18:12
This actually still does not work for me. I set the value in the collection and it shows up as "unresolved" in the test URI

![collectionvariable](https://user-images.githubusercontent.com/3200529/34120865-50075c36-e3e4-11e7-8814-e536022cbe40.png)
![unresolved](https://user-images.githubusercontent.com/3200529/34120871-540f42d0-e3e4-11e7-8965-585354cc21db.png)

**Comment by mhmacleod** [comment] 2017-12-22 04:13
Same here. Any reply on this?

**Comment by kamalaknn** [comment] 2017-12-22 06:21
@mhmacleod @dasjestyr Collection variables are available for use within the request. We are working on adding support for collection variables in the auto complete and variable highlighting in the next couple of releases.

You should still be able to use the variable.

**Comment by dasjestyr** [comment] 2017-12-23 21:38
@kamalaknn I'm not sure what that means. Are you saying that despite the unresolved warning, it should still work when I hit send? Because when I do that, it doesn't fill the value and I get a request error.

**Comment by WORMSS** [comment] 2018-01-02 15:46
@dasjestyr I can confirm that the variable "looks" like it is in red and therefor not working.. But a collection variables does in fact work in the URL.
```
Postman for Windows
Version 5.5.0
win32 10.0.10240 / x64
```

**Comment by Ghedeon** [comment] 2018-02-04 17:14
Can confirm, same issue in `v5.5.2`, the variable works, just not being recognized. Can't believe it was opened in 2016 :)

**Comment by ghost** [comment] 2018-02-06 16:12
Collection variables are not recognized or working for me.

> Postman for Windows
Version 5.5.2
win32 10.0.16299 / x64

**Comment by ybayk** [comment] 2018-02-09 02:44
I can confirm that collection vars do NOT actually work at all.
req1 test script:
pm.variables.set("foo", "bar");
req2 url:  http://example.com/{{foo}} is NOT substituted with http://example.com/bar but stays unresolved and called like http://example.com/%7B%7Bfoo%7B%7B

Version 5.5.2 (5.5.2)

**Comment by ghost** [comment] 2018-02-12 12:30
Day 509, the collection variables are still not being autocompleted during the request edition in the 5.5.2 version. Also, Postman complains about those variables, saying they're unresolved.

No answers, only hope.

Edit: Actually, they do work, but the program only complains about them as unresolved.

**Comment by piyushkantm** [comment] 2018-02-14 08:38
Still unable to work with the collection variables..

**Comment by WORMSS** [comment] 2018-02-14 08:41
@piyushkantm you can still work with them.. They just don't show up in auto complete and they look invalid if you type them manually.. But when you run them, they work. It is purely a visual thing.

**Comment by dasjestyr** [comment] 2018-02-16 16:03
If they're not working, I'd suspect that it is because your test hasn't yet been saved to the collection that holds the variable. For example, if you add the variable to MyCollection, then your test has to be saved there before it'll resolve. The UI will still show it as unresolved, but when you execute the test, it will work.

**Comment by mcfarljw** [comment] 2018-02-22 00:18
Yes, the do still work although they don't show up in autocomplete and are highlighted red as if in error. I now know that I can still use them, but only after I stumbled upon this issue. For about a month though I thought collection variables were broken just because they turned red and instead opted for switching between global environment configurations.

Cosmetic the fix may be but it's a useful feature that many users might not understand they can use given the current bug.

**Comment by patricktaylorstarbucks** [comment] 2018-02-26 21:38
this bug is causing significant problems with out ability to share and support postman collections. Add my vote to increasing priority to fix please.

**Comment by prashantagarwal** [comment] 2018-02-26 21:56
@patricktaylorstarbucks We have released the fix in the latest release which is slowly being rolled out. By the time you can test this out on our canary app https://www.getpostman.com/canary

**Comment by WORMSS** [comment] 2018-03-02 08:38
I can confirm that postman v6.0.8 has this fixed on stable

**Closed as completed** 2018-03-02 09:54 UTC
Labels: collection-v2, pending-close

**Comment by patricktaylorstarbucks** [comment] 2018-03-02 18:10
Thank you, I have confirmed that both Global and Environment variables set in a collection’s pre request script now highlight and autocomplete as I expect.

**Comment by dudewad** [comment] 2018-04-10 16:43
6.0.10
I can also confirm this is fixed. Severe drop in blood pressure. All is right with the world. Good job Postman crew.

**Comment by otter-chazzs** [comment] 2018-10-02 18:44
these do not seem to work at all. how does one access the collection variable in the body of a request?  i have tried the {{var}} notation there is nothing. 

i created a collection, added a variable.  i then created a request, saved it to the collection. then i tried to access the variable in the body of the request with the {{var}} notation and nothing gets subbed in.  that i can tell.  

how/can someone look at the actual GENERATED body that gets sent?

**Comment by fahu** [comment] 2018-10-13 09:41
In case somebody comes across this issue when having troubles to use collection variables when creating a new request:
**You need to save the request to the belonging collection before you can use it!**
