### ISSUE TITLE
Data collection import still removes leading zeros sometimes

### ISSUE THREAD

**Issue by JaredPage** [a85/POSTMan-Chrome-Extension#5125] opened 2018-09-03 08:46 UTC
**Bug Description**
I am experiencing an error with the Data function in the Postman Runner. I have an MS Excel document which I export a CSV from. I then import this CSV into the Data field in the Runner for my collection. This seemed to be working fine initially until I noticed some oddities. I eventually discovered that leading zero's from the numbers in my CSV file were being stripped from the imported CSV. The CSV file has the leading zero's, but the import process doesn't recognize them.

My current work around is to use a random [csv to json](https://www.csvjson.com/csv2json) site to convert my CSV file to a JSON file (which then works perfectly).

I have submitted this here instead of the Newman one because I cannot actually reproduce this with Newman.

**Steps to Reproduce**
1. Open a text editor and save the following CSV data as `test.csv`
```bash
example,data,moredata
0795184662,0002332693,001234456
```
2. Open Postman
3. Open the Runner's panel by clicking 'Runner' up the top
4. For the Data section, click 'Select File'
5. Choose the `test.csv` you saved earlier in step 1.
6. Once returned to the Runner's panel, verify that the file has been loaded. 
7. Click preview. 
8. Notice that the leading zero's for the first two columns have been stripped, but the last column has not.

**Expected behavior**
I expect that the _other_ columns would also be quoted and not lose their leading zero's, just like the last column.

**Screenshots**
![editor](https://user-images.githubusercontent.com/7892646/44976746-79a52500-afa9-11e8-8c85-e37410173cad.png)
![postman](https://user-images.githubusercontent.com/7892646/44976751-7dd14280-afa9-11e8-86e8-ff834a0978c5.png)

**App information:**
 - Native App
 - Postman Version 6.2.5
 - Windows 10 64-bit

**Additional context**
I found other bugs around (like [this one](https://github.com/postmanlabs/newman/issues/1346) and [this one](https://github.com/postmanlabs/postman-app-support/issues/2734)) that seem to indicate the problem was fixed in Newman v4.0.0. However, I am obviously still experiencing this bug.....potentially, is the latest version of postman not using this version of Newman ?

**Comment by sivcan** [comment] 2018-09-04 07:48
Yeah, as you mentioned this issue is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2734

Follow https://github.com/postmanlabs/postman-app-support/issues/2734 for further updates on the issue.

We'll be updating the thread once we have an update for this.

**Closed as completed by sivcan** 2018-09-04 07:48 UTC
