### ISSUE TITLE
Environment variable auto completion or suggestions are no more showing

### ISSUE THREAD

**Issue by Padmahas** [a85/POSTMan-Chrome-Extension#9948] opened 2021-05-19 10:05 UTC
**Describe the Issue**
While reusing Environment variable, after pressing double flower brackets, {{ and as soon as, partial name of Global environment variable is typed, list of available environment variables, matching the word, used to be shown previously. But in recent days, it is not happening, after one of the update (Not sure from which update, it's not working).

**Steps to Reproduce**
1. Click on "Eye" symbol on top right corner, which says "Environment quick look" in the tool tip.
2. Click "Edit" option.
3. Add a Global variable name and it's value in "Initial value" and "Current value" fields.
4. Come back to Postman request tab.
5. In the URL text box, start typing {{[ONE_OF_THE_GLOBAL_VARIABLE_NAME]}}. Eg: {{ProductionURL}} in my case.
6. The expected behavior is, as soon as "{{Prod" is typed, the matching variables should be shown for selection. But it will not show.

**Environment Information**

 - Platform Type: Windows
 - Postman Version: 8.4.0
 - Operating System: Windows 8.1

Thank you.

**Comment by DannyDainton** [comment] 2021-05-19 10:11
Hey @Padmahas 

Would you be able to share a quick recording of what you're seeing, please?

Can you also inside that you have saved the global variable after entering it, there shouldn't be an orange dot on the `Globals` tab.

**Comment by VaishnaviChallaPostman** [comment] 2021-05-19 10:34
Hey @Padmahas 👋 

Just to confirm, are you adding the variables in between or at the beginning of the URL?

If it is the case, currently suggestions won't show up if added in-between or at the beginning of any text. The reason is that the entire string after '{{' is considered as search text for suggestions. It doesn’t mean that you cannot add variables at the beginning/in-between text. But the suggestions won't show up at the moment. 
Our team is working on resolving this. Existing GH issue - https://github.com/postmanlabs/postman-app-support/issues/5067 

Screen-record of the expected behaviour at the moment : https://www.loom.com/share/f5c940eb193c4774a375b78ffc87b3dd (I tried adding variable at the end, middle, and beginning respectively )

Please let us know if this is not the case, and you are seeing something unexpected.

**Comment by Padmahas** [comment] 2021-05-19 16:11
> Hey @Padmahas
> 
> Would you be able to share a quick recording of what you're seeing, please?
> 
> Can you also inside that you have saved the global variable after entering it, there shouldn't be an orange dot on the `Globals` tab.

Hey @DannyDainton ,
I was intended to tell "Global variable" instead of "Environment variable". Apologies on that part.
Regarding video, it is similar as @VaishnaviChallaPostman has shared, the only difference is, the suggestions are being shown when typed in the end of  URL. But in my case, the suggestions are not being shown when I am typing in the beginning of the URL.

If you still need a video, I'll do it and post it here.

Regarding orange dot, I'm not sure, where and when it will show. (I can only see orange dots in the right side of each Request tab). But I can't see similar dot in the Global variable section.
![image](https://user-images.githubusercontent.com/11802323/118847087-01aef280-b8eb-11eb-98a7-356095cc1a9c.png)

**Comment by Padmahas** [comment] 2021-05-19 16:28
> Hey @Padmahas 
> 
> Just to confirm, are you adding the variables in between or at the beginning of the URL?
> 
> If it is the case, currently suggestions won't show up if added in-between or at the beginning of any text. The reason is that the entire string after '{{' is considered as search text for suggestions. It doesn’t mean that you cannot add variables at the beginning/in-between text. But the suggestions won't show up at the moment.
> Our team is working on resolving this. Existing GH issue - #5067
> 
> Screen-record of the expected behaviour at the moment : https://www.loom.com/share/f5c940eb193c4774a375b78ffc87b3dd (I tried adding variable at the end, middle, and beginning respectively )
> 
> Please let us know if this is not the case, and you are seeing something unexpected.

Hello @VaishnaviChallaPostman ,

You got me right, it is the similar issue. But in the given video, the person is able to get suggestions when the variable is typed in the end of URL, which even I'm able to get it. But the suggestions are not showing when it is typed in the beginning of the URL.

![image](https://user-images.githubusercontent.com/11802323/118849075-02e11f00-b8ed-11eb-8c7b-708be884b392.png)

The reason I raised this bug is, it was working in previous versions, with a bit of different behavior.
Assume you have a URL like.
**`{{localhostProjA}}/controllername/apiname`**
**Previously.**
1. If you already had the remaining part of URL in the tab, like
`/controllername/apiname`
2. And if you had typed `{{local` and a **SPACE bar**, immediately after pressing SPACE bar, suggestions would have shown. Like,
`{{local` SPACE_BAR`/controllername/apiname`

But Currently,
If nothing is there in the URL then only the suggestions will show in the beginning OR even if there is some text, if variable is typed in the end of URL, then it will show. But not when some text already present and even if you try to type in the beginning, suggestions will not show.

**Comment by VaishnaviChallaPostman** [comment] 2021-05-25 08:08
Hey @Padmahas 
Sorry for the delay in my reply. 
Yes, exactly 💯  That is what I have tried to convey. Really appreciate your explanation in detail. 
Our engineers are working to resolve this behaviour. 
Any updates on this will be posted to #5067  - Please make sure to subscribe to #5067, so that you won't miss any any updates. 
(Closing this out as this is a duplicate of #5067, will tag you on that thread 😃 )

**Closed as completed by VaishnaviChallaPostman** 2021-05-25 08:08 UTC
Labels: variables
