### ISSUE TITLE
auto dark mode depending on system preference

### ISSUE THREAD

**Issue by danjob** [a85/POSTMan-Chrome-Extension#9730] opened 2021-03-15 18:43 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to go to the config to set dark mode manually.

**Describe the solution you'd like**
An option to activate dark mode automatically depending on the system preference.

**Describe alternatives you've considered**
Maybe add this option under the menu that exists already.

<br>

<img width="708" alt="Bildschirmfoto 2021-03-15 um 13 36 56" src="https://user-images.githubusercontent.com/12426218/111204348-0924e900-8594-11eb-8589-f11045e0934e.png">

**Comment by DannyDainton** [comment] 2021-03-15 21:31
Closing this one out as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/8075

**Closed as completed** 2021-03-15 21:31 UTC
Labels: duplicate
