### ISSUE TITLE
Documentation: adjust truncation for tables

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6112] opened 2019-03-20 21:47 UTC
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
For content on a docs page (parameters, headers, body, etc) that contains many items, the list / table is truncated to fit within a maximum length, and requires clicking to expand to the full list.

**Describe the solution you'd like**
Allow truncation to be configurable. Examples:
- Never truncate content (expand all, by default)
- Set the length at which content is truncated

**Describe alternatives you've considered**
None

**Additional context**

**Comment by dacardona** [comment] 2019-03-20 22:33
Another alternative could be to show a scrollbar

**Comment by Raja-Simha** [comment] 2019-07-22 14:08
Duplicate of #5789. Closing this one.

**Closed as completed by Raja-Simha** 2019-07-22 14:08 UTC
Labels: feature, product/documentation
