### ISSUE TITLE
Error on Request Token OAuth2.0

### ISSUE THREAD

**Issue by LucasZuzarte** [a85/POSTMan-Chrome-Extension#7526] opened 2019-10-24 14:53 UTC
**Describe the bug**

After setting the data and clicking on "Request Token" Postman shows an error message "Could not complete OAuth 2.0 login. Check Postman Console for more details."

**To Reproduce**
1. Go to Authorization on a request
2. Select type OAuth 2.0
3. Click "Get New Access Token"
4. Fill in requested information
5. Click on Request Token
6. See error

**Expected behavior**
Postman should open the browser and get the authentication code

**Comment by LucasZuzarte** [comment] 2019-10-24 15:00
Postman version: Version 7.10.0

**Comment by codenirvana** [comment] 2019-10-25 08:58
@LucasZuzarte what's the error message in the console?

**Comment by LucasZuzarte** [comment] 2019-10-25 12:10
@codenirvana there is no message on the postman console.

**Comment by shamasis** [comment] 2020-03-11 21:15
Is there any doc of the service or URL we can use to test this flow? Right now it is too generic for us to tap into the cause.

**Comment by dramkler** [comment] 2020-07-24 23:31
Hi,
I have same issue with when I Click "Get New Access Token”.
This is the message on the console:

![Schermata 2020-07-25 alle 01 25 08](https://user-images.githubusercontent.com/9319944/88442832-3f033a80-ce16-11ea-803b-d7628524e2a8.jpg)

I think is correlated with this issues  #8825 when I post another img.

* App Type [Native App]
* Postman Version [7.29.0/1]
* OS: [macOs Mojave 10.14.6]

Thx.

**Comment by Mechanicalkeyboard** [comment] 2020-09-12 13:23
Issue #8825 has been resolved with version 7.30.0. Closing this issue.

If there is another issue present here, and it is still reproducible, please re-open and we will investigate! 

Thank you

**Closed as completed by Mechanicalkeyboard** 2020-09-12 13:23 UTC
Labels: bug, OAuth2, blocked/need-info, product/runtime
