### ISSUE TITLE
Content-Type boundary header for multipart/form-data is incorrect when digest authentication is used

### ISSUE THREAD

**Issue by flakey-bit** [a85/POSTMan-Chrome-Extension#6140] opened 2019-03-24 00:17 UTC
When digest authentication is used in combination with a multipart/form-data file upload, Postman does not correctly surround the multipart data with the boundary. Refer to [RFC2046](https://tools.ietf.org/html/rfc2046)

**To Reproduce**
1. Create a POST request w/ Authentication: digest, credentials supplied. Do not specify a "Content-Type" header explicitly. 
2. Change the body type to 'form-data', add key named "file" of type "file". Pick a local file to upload.
3. Enable request capturing in Fiddler or similar
4. Invoke request

**Expected behavior**
* The multipart data should be surrounded by a boundary
* The Content-Type header should specify a boundary (name)
* The two boundary names (wrapping the content & in the content-type header) should be the same

**Observed behavior**
The multipart data is surrounded by a different boundary to that in the content-type header

**Screenshots**
![1](https://user-images.githubusercontent.com/4413825/54872977-d28abc80-4e18-11e9-8666-99650c7a66cf.png)

![image](https://user-images.githubusercontent.com/4413825/54873210-55ae1180-4e1d-11e9-9bb0-4eca017055c4.png)

![2](https://user-images.githubusercontent.com/4413825/54873216-7fffcf00-4e1d-11e9-8dc2-818b5e91466d.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version 7.0.6
 - OS: Windows 10 Pro

**Additional context**
See [https://github.com/flakey-bit/DotNetDigestAuth/issues/2](url) for additional info.

**Comment by shamasis** [comment] 2019-06-17 17:24
Well... this would be very very odd and super low-level bug. So, I had a second look. I created a simple request with two text files in form-date and sent a POST request to http://postman-echo.com/post. Captured it using WireShark... and did not find this issue. Screenshot attached.

I even tried hard-coding a content-type in UI and set a boundary in it ... like ` multipart/form-data; boundary=--------------------------899579491390198298378346` ... it still did not allow me to break the boundary concept.

The only way I could break Postman is when I forcibly provided both content-type with boundary and content-length. But, under that circumstance, the entire HTTP Post broke and file did not get uploaded at all.

<img width="1031" alt="Screenshot 2019-06-17 at 22 36 32" src="https://user-images.githubusercontent.com/232373/59623813-ce89e480-9152-11e9-9cff-607326a7034f.png">

@flakey-bit, what am I missing? I need help to reproduce it.

**Comment by flakey-bit** [comment] 2019-06-17 20:49
Hi @shamasis

As per the ticket description, the bug manifests when an HTTP DIGEST Authorization header is present in the request (i.e. digest authorization credentials were added to the request in Postman). I can't see an Authorization header in your captured request which makes me think you missed this step. Take a look at my screenshots from the bug description.

**Comment by codenirvana** [comment] 2019-06-17 21:31
@flakey-bit Not able to reproduce with Digest auth as well.
<img width="1423" alt="Screenshot 2019-06-18 at 2 56 26 AM" src="https://user-images.githubusercontent.com/4865836/59638017-d9557100-9174-11e9-9f60-c67b949e25ad.png">

Is there any public endpoint which we can use to reproduce this issue?

**Comment by flakey-bit** [comment] 2019-06-17 21:41
Hi,

Not currently. I'll try and sort one out later today.

**Comment by flakey-bit** [comment] 2019-06-18 12:49
Hi 

@codenirvana @shamasis 

There is a test site up at http://eddie-digest-auth-test.azurewebsites.net/ 

If you hit that page in a browser, it will serve a simple form from which you can upload a file. I don't think it matters hugely what you upload.

![image](https://user-images.githubusercontent.com/4413825/59682684-0c9e0b80-921a-11e9-97ac-122642895433.png)

Submitting the form will POST to the same URL - if successful, it will serve the contents of the file back to you. Note that GET request does not require authorization however the POST request does (needs digest authentication). 

The credentials to use are 

Username: eddie
Password: starwars123

When I capture the requests through Fiddler, I see the following:

- When making the request via Chrome, I get a boundary such as `----WebKitFormBoundary3OUI6pI7CpGb4lfp` used consistently in both the initial request (401 challenge, no authorization header) and in the subsequent request (200 OK, authorization header present)
- When making the request via PostMan, the first request (401 challenge) uses a boundary such as `--------------------------234543481170520967227158` consistently however the subsequent request (authorization header present) uses the same boundary (`--------------------------234543481170520967227158`) again in the header, but a different boundary (`----------------------------664768466834213191890969`) around the multipart content.

Please let me know if you need further info.

**Comment by codenirvana** [comment] 2019-06-19 07:36
@flakey-bit Thanks for providing the testing endpoint.
We are able to reproduce the issue and will fix this as soon as possible.

**Comment by flakey-bit** [comment] 2019-06-19 07:38
Do you need me to leave the test endpoint up or can I get rid of it?

**Comment by codenirvana** [comment] 2019-06-19 07:40
@flakey-bit We identified the issue in our low-level request sending library.
You can remove the testing endpoint now.

**Comment by codenirvana** [comment] 2019-06-26 09:17
@flakey-bit We've pushed a fix for this on our [canary channel](https://www.getpostman.com/downloads/canary) `v7.3.0-canary04`.

Let me know if the issue persists?

**Comment by codenirvana** [comment] 2019-07-23 10:03
Fixed in Postman v7.3.4.

**Closed as completed by codenirvana** 2019-07-23 10:03 UTC
Labels: bug, Auth, request-sending, product/runtime

**Comment by nmfzone** [comment] 2023-03-28 01:35
Hey, this issue is coming back in latest postman release for Mac. I tried it in Chrome, it works fine (correctly sent `boundary=----WebKitFormBoundaryajIZxBpduIEsHOHd`), but when via Postman for Mac, it sents `boundary=--------------------------449517874985316538344793`.

App Type: Native
Postman Version: v10.12.8
OS: MacOs Mojave

**Comment by shivangi-2001** [comment] 2024-03-28 07:44
Follow. these article that worked for me and many more:
https://medium.com/@meetwithIT/error-multipart-boundary-not-found-8090c8609b09
