### ISSUE TITLE
Collaborator can remove collection from Workspace

### ISSUE THREAD

**Issue by InnaXITE** [a85/POSTMan-Chrome-Extension#7153] opened 2019-08-20 15:38 UTC
**Describe the bug**
Collaborator can remove collection from Workspace

**To Reproduce**
1. Create a workspace with collaborators with Postman Pro
2. Create a collection with 1 API call and share it with your team
3. Somebody from team with Collaborator and Viewer permissions gets shared collections and then removes that collection from workspace (Delete function is disabled)
4. Collection is removed and can't be restored

**Expected behavior**
This option - Remove from Workspace - should be greyed out.

**App information (please complete the following information):**
 - Postman Desktop
 - Postman Version 7.5.0
 - OS: macOS 10.14.3

**Additional context**
Collection permissions are hard coded and can't be changed so this is sort of a hole when collaborator can easily remove data once and forever.

**Comment by sankalp0o** [comment] 2019-08-21 06:03
@InnaXITE This is the intended behaviour, as you can also see on [our docs](https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/roles_and_permissions/#workspace-roles). Collections that are removed form a workspace can be added back, hence we allow this action to Collaborators. 

That being said, I'd love to hear your use case and the problem you face because of this. We're looking for feedback that could help us make workspace roles more useful.

**Comment by arlemi** [comment] 2020-06-03 08:49
Closing this issue as we didn't get any clarification on the use case.

**Closed as completed by arlemi** 2020-06-03 08:49 UTC
Labels: feature, Roles and Permissions
