### ISSUE TITLE
Requests setup with Authorization do not indicate so in the documentation

### ISSUE THREAD

**Issue by MarkusAnthony** [a85/POSTMan-Chrome-Extension#7674] opened 2019-11-19 18:31 UTC
This is very similar to a previous post but this is at the request level.

For my request I setup authorization type to be "Bearer Token" but I do not see any indication in the web view documentation for this specific request.

1. Go to a collection in the app
2. Click on a specific request
4. Click on Authorization Tab
5. For Type choose "Bearer Token"
6. For Token put an environment variable such as {{token}}
7. Click Save
8. Click on Sync button
9. View your collection documentation in the web view
10. Scroll to the request that you created
11. Look for any indication that the request requires a bearer token

I would expect the request example to include this information in the example just as it does so if I manually enter it on the header tab. 

For example:

--header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJtcmlzc21hbm5AbnV2b2RpYS5jb20iLCJ0cmFja0lkIjoiMjVkYWZmNDctOTdiNC00MzexampleN2MtMDNjZDQyYmIzMTNhIiwiYXV0aG9yaXphdGlvbnMiOltdLCJpYXQiOjE1NjI3MDM4MDMsImlzcyI6Ikdlc3RhbHQgRGlhZ25vc3RpY3MifQ.83QLbcmPSAHnKy5vCy_nWAFcj9nHHPeNBPPG4GctICM"

App information (please complete the following information):

App Type: latest app
Postman Version: Postman v7.11.0
OS: windows 10
Additional context

This is really problematic as the coders don't have any idea that a bearer token used. Nor do they have any indication if it is used for all or some requests.

**Comment by Raja-Simha** [comment] 2019-11-20 18:05
@MarkusAnthony as replied to your previous request, this falls into showing more auth info in the documentation. Marking this as a duplicate. 
Duplicate of #7673

**Closed as completed by Raja-Simha** 2019-11-20 18:05 UTC
Labels: feature, product/documentation
