### ISSUE TITLE
Request attempts to parse body as JSON even though Content-Type is application/x-mpegURL

### ISSUE THREAD

**Issue by ryanshores** [a85/POSTMan-Chrome-Extension#5993] opened 2019-02-27 22:20 UTC
**Describe the bug**
Request attempts to parse body as JSON even though Content-Type is application/x-mpegURL. The request always shows a JSON parsing error in the console, even when the test is empty.

**To Reproduce**
1. New request that will receive Cntent-Type -> application/x-mpegURL
2. Send the test

**Expected behavior**
Should not try and parse the data as JSON unless it is JSON, or I attempt to call pm.response.json().

**Screenshots**
![postman_hlfe4svwdh](https://user-images.githubusercontent.com/23423297/53527041-6c29ad00-3aab-11e9-9747-0d6a7224b0e1.png)
![postman_ala09etwjd](https://user-images.githubusercontent.com/23423297/53527042-6c29ad00-3aab-11e9-9d7a-762277d9bfd2.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 6.7.4]
 - OS: [Windows 10]

**Comment by sujayvenaik** [comment] 2019-03-25 05:50
Hey @ryanshores 
Can you help us with a public URL using which we can replicate this issue?

Ideally, we do not render these types and give the user an option to directly download the content.

**Comment by saswatds** [comment] 2019-09-17 13:45
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by saswatds** 2019-09-17 13:45 UTC
Labels: bug, response-rendering, product/runtime
