### ISSUE TITLE
Test script shows error when there are no test scripts

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#7154] opened 2019-08-20 21:02 UTC
**Describe the bug**
User will run a request with no test scripts but will get this error in the Test section of response: 
`script: Error: sandbox: execution interrupted, bridge disconnecting.`

**To Reproduce**
User is trying to call an endpoint that returns a ~25MB JSON file with nested objects. 
Formatter may be trying to format the large response and failing on multiple nested components. 
Tried to test with: https://postman-echo.com/bytes/25/mb?type=json
But the JSON file returned is a simple JSON object with not many nested objects. 

Unable to ask for specific API and response as it is proprietary software. 

**Expected behavior**
Expect the error: 
`script: Error: sandbox: execution interrupted, bridge disconnecting.`
to not show up when there are no test scripts in the request, collection, or folder. 

**Screenshots**
![Postman_After_Request2](https://user-images.githubusercontent.com/5624835/63384035-e0565680-c352-11e9-9145-a255adc91377.jpg)

**App information (please complete the following information):**
 - App Type Native 
 - Postman Version 7.5.0
 - OS:  MAC OSX

**Comment by codenirvana** [comment] 2019-08-21 06:53
@stcalica Possibly the folder or collection-level scripts are getting executed.

Also, this particular error message means either:
1. A synchronous script executing for more than 30 sec. (say infinite `for` loop)
2. Using test script with large response payload (possibly in this case).

**Comment by stcalica** [comment] 2019-08-21 17:28
@codenirvana  Have checked with user and they have no test scripts in Collections or Folder or Request. 

They have run Newman on the collection and received a JS Heap memory issue. Working on getting a log from them right now.

**Comment by ritman-us** [comment] 2019-08-22 14:19
Here are the logs from newman:

→ accounts - CP1 
GET http://xx.xx.xx.xx:xxx/api/v1.0/xxxx/views/accounts [200 OK, 23.03MB, 2.5s]

<--- Last few GCs --->

[23532:0x2f2aad0] 69272 ms: Mark-sweep 1397.5 (1411.9) -> 1397.5 (1411.9) MB, 631.9 / 0.0 ms allocation failure GC in old space requested 
[23532:0x2f2aad0] 69974 ms: Mark-sweep 1397.5 (1411.9) -> 1397.5 (1410.9) MB, 632.3 / 0.0 ms last resort GC in old space requested 
[23532:0x2f2aad0] 70681 ms: Mark-sweep 1397.5 (1410.9) -> 1397.5 (1410.9) MB, 706.6 / 0.0 ms last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x462f9625891 <JSObject> 
1: keys(this=0x462f9604809 <JSFunction Object (sfi = 0x2b77a9e09cf9)>,0xd30cf0543f1 <JSArray[24145099]>) 
2: revive [/usr/lib/node_modules/newman/node_modules/flatted/cjs/index.js:78] [bytecode=0x183c7f72b0d9 offset=28](this=0x154e06e8c2f1 <JSGlobal Object>,input=0x2b77a9e4edf9 <JSArray[219]>,parsed=0x1028fb2028e9 <Set map = 0x25f976704829>,output=0xd30cf0543f1 <JSArray[24145099]>,$=0x1aee...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 
1: node::Abort() [node] 
2: 0x8cd14c [node] 
3: v8::Utils::ReportOOMFailure(char const*, bool) [node] 
4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node] 
5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node] 
6: v8::internal::Factory::NewStringFromOneByte(v8::internal::Vector<unsigned char const>, v8::internal::PretenureFlag) [node] 
7: v8::internal::Factory::NumberToString(v8::internal::Handle<v8::internal::Object>, bool) [node] 
8: v8::internal::Factory::Uint32ToString(unsigned int) [node] 
9: 0xd9a698 [node] 
10: v8::internal::FastKeyAccumulator::GetKeysFast(v8::internal::GetKeysConversion) [node] 
11: v8::internal::KeyAccumulator::GetKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::KeyCollectionMode, v8::internal::PropertyFilter, v8::internal::GetKeysConversion, bool) [node] 
12: v8::internal::Runtime_ObjectKeys(int, v8::internal::Object**, v8::internal::Isolate*) [node] 
13: 0x22901e5042fd 
Aborted

**Comment by codenirvana** [comment] 2019-08-22 22:18
@ritman-us Thanks for sharing the logs. I can confirm this is because of the large response payload transmitting to script execution sandbox.

This should not happen if you have no test scripts defined.
Please confirm is the collection used for Newman execution have a `script` property defined or not. Something like this:
```json
{
    "listen": "test",
    "script": {
        "exec": []
    }
}
```

**Comment by ritman-us** [comment] 2019-09-03 15:37
for the particular request following is the script property
 "name": "accounts - CP1",
                        "event": [
                                {
                                        "listen": "test",
                                        "script": {
                                                "id": "a274c5b4-eb6e-458f-9051-b2f51ae1a5ee",
                                                "exec": [
                                                        ""
                                                ],
                                                "type": "text/javascript"
                                        }
                                }
                        ],

**Comment by ritman-us** [comment] 2019-09-09 15:46
Any update ?

**Comment by ritman-us** [comment] 2019-09-17 14:53
Any suggestions or a fix for the issue above would be helpful ... as of now we cannot use postman with large data sets being returned.

**Comment by codenirvana** [comment] 2019-09-17 15:10
@ritman-us Can you try removing the `event` property completely and check if that fixes your issue?

**Comment by codenirvana** [comment] 2020-03-10 19:00
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed as completed by codenirvana** 2020-03-10 19:00 UTC
Labels: bug, pending-close, blocked/need-info
