### ISSUE TITLE
Reorder Collection Versions

### ISSUE THREAD

**Issue by ypolishetty** [a85/POSTMan-Chrome-Extension#7371] opened 2019-09-06 17:05 UTC
While publishing my collection with multiple versions, right now I'm not able to reorder it. Is there any way to reorder my versions at the time of publishing my collection?

**Comment by Raja-Simha** [comment] 2020-02-12 08:09
@ypolishetty could you let me know why and how you would like to re-order your versions? Just trying to understand why the current functionality doesn't fit your use-case.

**Comment by ypolishetty** [comment] 2020-02-13 16:07
@Raja-Simha My original requirement is to rename "CURRENT" to "CURRENT - SP7". As thats not allowed, I created a new Version with the same name and when published, that one doesn't come up as the default when I open my published documentation. Someone has to manually go and change the version for it to load.

**Comment by Raja-Simha** [comment] 2020-11-20 17:50
Duplicate of #7979

**Closed as completed by Raja-Simha** 2020-11-20 17:50 UTC
Labels: feature, product/documentation
