### ISSUE TITLE
Oauth2 authorization form not working when using identical information to previous version

### ISSUE THREAD

**Issue by jbrinkle** [a85/POSTMan-Chrome-Extension#3604] opened 2017-10-07 07:25 UTC
## App Details:

```
Postman for Windows x64
Version 5.3.0
win32 10.0.14393 / x64
```

#### 10/27 Update:
No longer throwing errors, and don't know about other ID providers, but the one being used (Okta) for some reason causes redirect-with-auth-code step to instead redirect back to login page. But only for versions 5.3.1+. Previous version 5.2.1 still works flawlessly.

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there
    * Attempting to get an access token using Oauth2.0 Authorization pane
    * In version 5.3.0 I'm now getting errors where as in 5.2.1 I did not
    * Grant type = authorization code
    * Callback URL = https://www.getpostman.com/oauth2/callback (hardcoded in 5.2.1; had to be manually entered in 5.3.0 because default path caused auth server to return a 400 with message "The 'redirect_uri' parameter must be an absolute URI that is whitelisted")
    * State = state (not available in 5.2.1)
 2. Expected behaviour:
    * I expected to be able to get an access token that I could use in my postman requests. So far I'm unable to accomplish this task in version 5.3.0. Identical behavior and data used in version 5.2.1 works fine. 
 3. Actual behavior:
    * "Error getting access token. See console for error" toast pops up.
    * The postman console shows nothing at all 
    * Dev tools shows that my POST to the token endpoint of the auth server is coming back as a 403
    * Form data:
        * grant_type:authorization_code
        * code:FFlTBNKwYoMmiuquAms4
        * state:state
        * client_id: <correct value>
        * redirect_uri:https://www.getpostman.com/oauth2/callback
        * client_secret: <correct value>
 4. Screenshots (if applicable)

#### Repro steps
1. Open a new tab, and click the authorization subtab
2. Click "Get new access token"
3. Fill out form and submit

**Comment by harryi3t** [comment] 2017-10-07 07:50
Thank you for reporting this. 

Please note that the console mentioned in the toast is not the `postman console` but the `devTools console`.
Could you provide me with that error details? (Menu -> View -> Show devTools)


### Sample error
![image](https://user-images.githubusercontent.com/5207331/31305941-e8f632e2-ab62-11e7-9b36-fa40f5f01081.png)

**Comment by harryi3t** [comment] 2017-10-07 09:27
@jbrinkle Could you try changing the `Client Authentication` drop-down field to `Send as basic auth header`

![image](https://user-images.githubusercontent.com/5207331/31306496-2f6998d4-ab6f-11e7-9008-9db15dbf38f6.png)

Earlier we were sending the credentials in the body and the header. But this was not RFC compliant and many users were complaining.
So we made this configurable. 

I think your server requires the credential to be in the header.
So, just updating the drop-down should solve the issue.
If not, please share the error as mentioned in the comment above.

**Comment by jbrinkle** [comment] 2017-10-08 14:48
I tried both ways and it failed both times.

Send as header
common.js:154441 POST
https://vivint.oktapreview.com/oauth2/ausc2qa98kEkjuPKE0h7/v1/token 403
(Forbidden)send @ common.js:154441ajax @ common.js:153922requestToken @
xml.js:22(anonymous function) @ xml.js:22onBrowserLoginCallback @
xml.js:22wrapper @ common.js:28347handleInternalMessage @
common.js:155368handleElectronMessage @ common.js:155394(anonymous
function) @ common.js:155327emitTwo @ events.js:106emit @ events.js:191
xml.js:22 OAuth-2 Error while requesting the access token Object
{readyState: 4, responseText: "", status: 403, statusText:
"Forbidden"}error @ xml.js:22fire @ common.js:148453fireWith @
common.js:148583done @ common.js:154025(anonymous function) @
common.js:154389

Send in body
common.js:154441 POST
https://vivint.oktapreview.com/oauth2/ausc2qa98kEkjuPKE0h7/v1/token 403
(Forbidden)send @ common.js:154441ajax @ common.js:153922requestToken @
xml.js:22(anonymous function) @ xml.js:22onBrowserLoginCallback @
xml.js:22wrapper @ common.js:28347handleInternalMessage @
common.js:155368handleElectronMessage @ common.js:155394(anonymous
function) @ common.js:155327emitTwo @ events.js:106emit @ events.js:191
xml.js:22 OAuth-2 Error while requesting the access token Object
{readyState: 4, responseText: "", status: 403, statusText:
"Forbidden"}error @ xml.js:22fire @ common.js:148453fireWith @
common.js:148583done @ common.js:154025(anonymous function) @
common.js:154389

Looks like a standard 403 which is confusing because I can still
authenticate fine using the old version with all the same info.

**Comment by jbrinkle** [comment] 2017-10-08 14:48
P.S. Thanks for the fast follow up and suggestion. Happy to help any way I
can.

**Comment by devjack** [comment] 2017-10-09 04:48
Hi folks,
I've just reproduced this with my colleagues. It appears that the `client_secret ` param is not being POST'ed for the second leg of OAuth. I successfully see `grant_type`, `code`, `client_id` and `redirect_uri` but not `client_secret`.

This field is definitely configured in the UI/dialog for Oauth but is not included in the POST payload when attempting to exchange the access code for an access token.
Cheers!

**Comment by kamalaknn** [comment] 2017-10-09 07:34
Hi @devjack,

While trying to reproduce this, we found that `client_secret` is actually being sent with the request. Since you are not seeing the same behavior this should be specific to one of your configuration options or the OAuth provider.

Could you share a screenshot of the `Get new access token` dialog with the values filled so we can investigate it? 

Also, could you open `Developer Tools` (`View -> Show DevTools`) and send a screenshot of the `Network` tab for the token request, with request headers and request body sections expanded?

It should look like this

![developer_tools_-_file____applications_postman_app_contents_resources_app_html_requester_html_and_postman](https://user-images.githubusercontent.com/5207331/31327799-1e7207f6-acef-11e7-8f37-e022ea8fa8fb.png)
![developer_tools_-_file____applications_postman_app_contents_resources_app_html_requester_html_and_postman](https://user-images.githubusercontent.com/5207331/31327818-38814d32-acef-11e7-8e99-4d11d2ab4813.png)

You can blackout your sensitive information like `client_id` and `client_secret`

Thanks.

**Comment by harryi3t** [comment] 2017-10-09 13:28
@jbrinkle We have confirmed the bug and have this fixed internally. We will be releasing a fix soon in the next version of Postman.

__We have also identified that this bug is specific to the authentication provider, in this case, `okta`.__

@devjack The `client_secret` parameter will not be part of the token request body if you have `Send as basic auth header` selected for `Client Authentication`. It will be sent as an encoded authorization header.
You can try selecting `Send client credentials in body` which will send the `client_secret` in the request body instead of in the header.
If it does not work, could you share the auth provider with us so we can confirm if this is the same issue as above?

**Comment by jbrinkle** [comment] 2017-10-09 15:52
Thanks for fixing. Is Okta doing something "wrong" or is it just an
implementation difference? Okta might be interested in knowing of the issue.

**Comment by ian-weatherhogg-refractiv** [comment] 2017-10-10 21:26
I have the same problem and guessed the same - missing client_secret.
I've tried Send client credentials in body but it doesn't help - probably because the auth header isn't present.

**Comment by kamalaknn** [comment] 2017-10-11 18:36
We've rolled out a fix for this in our Canary channel in 5.3.1-canary01.

Here are the Canary download links for all platforms,
```
macOS:
https://dl.pstmn.io/download/channel/canary/osx_64

windows:
https://dl.pstmn.io/download/channel/canary/windows_32
https://dl.pstmn.io/download/channel/canary/windows_64

linus:
https://dl.pstmn.io/download/channel/canary/linux_32
https://dl.pstmn.io/download/channel/canary/linux_64
```

It would be great if someone could confirm this is fixed.

**Comment by jbrinkle** [comment] 2017-10-11 19:01
I just tried it.

It now works with Okta authorization server IF
* I set client authentication to be sent in the body
* I manually and explicitly set callback url to
https://www.getpostman.com/oauth2/callback even though the little help icon
says leaving the field blank uses the default URL (did the default URL
change? Is this a separate bug?)

Thanks for the fix.

**Comment by kamalaknn** [comment] 2017-10-11 19:27
@jbrinkle client authentication as Basic Auth headers does not work with Okta because Okta considers `client_id` in request body as a [duplicate credential](https://developer.okta.com/docs/api/resources/oauth2.html#token-authentication-methods). However, the RFC mandates us to send `client_id` in the body for all token requests. We cannot ignore this because there might be other providers who mandate `client_id` being present. [ref](https://tools.ietf.org/html/rfc6749#section-4.1.3)

As for point 2, we've allowed users to enter any callback url they have registered with their application. The `default url` in the help text is an empty URL aimed to help new applications, which might not be ideal for users migrating to this version. We'll revisit the help text. Thanks for pointing it out.

**Comment by Dismissile** [comment] 2017-10-12 15:52
Seems Postman 5.3.0 also doesn't like id_token for OpenID. I get a token back in the response (inspected with the Console) but Postman shows Access token undefined. In the old version it wouldn't automatically copy the token to the Authorization header (since it was expecting access_token) but I could at least copy it manually. Now I don't see it in the dialog.

New version:
![image](https://user-images.githubusercontent.com/10454182/31505582-da4674f6-af3a-11e7-9fe4-a86c9376390f.png)

Old version:
![image](https://user-images.githubusercontent.com/10454182/31505826-6960394c-af3b-11e7-865c-b66b36b72172.png)

**Comment by kamalaknn** [comment] 2017-10-12 16:41
Hi @Dismissile,

Could you try out our Canary Apps and see if this is fixed? You can find the download links [here](https://github.com/postmanlabs/postman-app-support/issues/3604#issuecomment-335906596).

If not, please share the details of the provider so we can identify and fix this.

**Comment by Dismissile** [comment] 2017-10-12 18:12
This build fixed the issue!

Travis Ellis
Solution Consultant
Mobile: 402.415.6398
Deliveron Consulting Services
[cid:image009.png@01D1E822.C4FFDE10]<http://www.deliveron.com/>

[cid:image016.png@01CF0620.0729E520]<https://www.facebook.com/deliveron>

[cid:image017.png@01CF0620.0729E520]<https://twitter.com/deliveron>

[cid:image018.png@01CF0620.0729E520]<http://www.linkedin.com/company/deliveron-consulting-services>

**Comment by nicksloan** [comment] 2017-10-12 18:17
@kamalaknn Many OAuth2 server implementations are (and should) be picky about matching the client with a registered callback URL. The feature of shepherding the authorization code for users is very useful, but it is completely useless if you don't tell us what callback URL to use with our client.

**Comment by Dismissile** [comment] 2017-10-12 18:27
@kamalaknn That did not fix the issue. I posted a comment on another issue that this build did fix, but the dialog still shows undefined when the auth server only returns an id_token.

**Comment by nicksloan** [comment] 2017-10-13 11:08
I just wanted to update based on my comment above so that it may clarify things for some users.

It appears that Postman is now grabbing the authorization code directly from the URL, rather than requiring that it be sent to a particular server. It can do this because it is serving as the user agent for the OAuth2 flow. It seems that you can use any valid URL, and the URL may not even need to be resolvable. I haven't tested that though.

It is still important to know and whitelist the URL with the OAuth2 server in advance in most cases, but perhaps the example.com placeholder IS the actual URL that Postman is sending? Additional documentation in that area would be helpful.

**Comment by harryi3t** [comment] 2017-10-13 11:58
@nicksloan 

> It appears that Postman is now grabbing the authorization code directly from the URL, rather than requiring that it be sent to a particular server. It can do this because it is serving as the user agent for the OAuth2 flow. It seems that you can use any valid URL, and the URL may not even need to be resolvable

Correct!

> It is still important to know and whitelist the URL with the OAuth2 server in advance in most cases, 

Yes, if you have registered your application with one or more callbacks, you MUST use one of them. Otherwise, you can put anything. We will use a default empty URL if not provided.

> perhaps the example.com placeholder IS the actual URL that Postman is sending

No, it's not an actual URL. 

> Additional documentation in that area would be helpful.

It's work in progress and will be updated soon.

**Comment by nicksloan** [comment] 2017-10-13 12:23
@harryi3t So what is the default URL that you send if the user doesn't supply one?

One more question: does the callback URL ever get loaded by postman, or does it simply cut the process after receiving the 302 response? Would it work with an authorization server that uses JavaScript location.href (or, hell, even a hyperlink) to send the user to the callback URL? Technically, I think both are valid in OAuth2.

If the callback URL is never actually loaded, there really is no reason the example.com URL wouldn't work… and it has the added benefit of definitely going nowhere.

**Comment by harryi3t** [comment] 2017-10-13 12:57
@nicksloan 
We will use `/` as default callback URL

> Would it work with an authorization server that uses JavaScript location.href (or, hell, even a hyperlink) to send the user to the callback URL

We are listening for the [electron events](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#class-webcontents) for any redirects or any navigation change. Please let us know if it's not working for some specific auth providers.

> does the callback URL ever get loaded by postman, or does it simply cut the process after receiving the 302 response

In most cases, the callback URL won't be hit. But if for some reason the event did not fire before the redirect then we will actually hit the endpoint.

> If the callback URL is never actually loaded, there really is no reason the example.com URL wouldn't work

As I mentioned above, anything would work if the server is not validating it. It does not even need to be an URL. So yes, `example.com` would work for some servers.

If you have more questions, I am more than happy to answer them all. 
You can directly reach out to me on our Slack community channel.
https://www.getpostman.com/slack-invite

**Comment by kamalaknn** [comment] 2017-10-13 15:59
@Dismissile  We've identified why the token responses without `access_tokens` do not show the response in the token details.

We have a fix ready for this and will push it out in the next release in a few days.

**Comment by nicksloan** [comment] 2017-10-15 14:27
@harryi3t One more thing to note, and then I'll get out of your hair. You have been super helpful.

I would recommend changing the default callback URL. "/" is unlikely to be a valid value for any OAuth2 provider (as it would imply redirecting to a URL on the provider's own server), and probably isn't something that the user can register with most providers. If that is the case, then it seems less helpful to supply a default at all… it would be better to just require that the user supply one, and perhaps link them to a docs page with some of the information that has come out of this discussion. An alternative would be to use an actual safe URL, such as http://localhost/. Users can probably register that with most providers, yet it still protects the authorization code from being sent somewhere inappropriate.

**Comment by kamalaknn** [comment] 2017-10-18 10:17
@jbrinkle @devjack @ian-weatherhogg-refractiv @Dismissile 

The fix for this has been rolled out in `5.3.1`. Could you update your Postman app to the latest version and verify that this works?

**Comment by CosminTS** [comment] 2017-10-19 08:50
> The client_secret parameter will not be part of the token request body if you have Send as basic auth header selected for Client Authentication. It will be sent as an encoded authorization header.
You can try selecting Send client credentials in body which will send the client_secret in the request body instead of in the header.

@harryi3t 

After reading the above comment I resolved one of my problems, now I'm encountering a problem with the State parameter in **version 5.3.1**. Our authentication OAuth2 has the State parameter required, but Postman is not sending the parameter even if I insert one. What can I do to send the State parameter? In the previous versions, it was not needed to insert one.

Thanks!

![first screen](https://user-images.githubusercontent.com/23333208/31762301-790eb1ce-b4c3-11e7-9511-3d8fa7289779.JPG)
![console](https://user-images.githubusercontent.com/23333208/31762398-b79c25a2-b4c3-11e7-8829-12986654d4aa.JPG)

**Comment by kamalaknn** [comment] 2017-10-19 09:25
@CosminTS Postman sends the `state` in the `Authorization Request`, that opens the `Auth URL` on a window. `state` parameter is not sent in the `Access Token Request` as it is mandated by the [spec](https://tools.ietf.org/html/rfc6749#section-4.1.3).

Does your server expect the `state` parameter to be present in the `Access Token Request`?

**Comment by jbrinkle** [comment] 2017-10-27 22:11
I don't know if Okta changed something but current status:
5.2.1 - still works
5.3.1 - **doesn't work anymore**. When it comes time to respond with a redirect with the auth code, it redirects back to the login page instead
5.3.2 - **doesn't work**

I'm uploading two files containing fiddler traces (https://www.telerik.com/download/fiddler). My desktop is running 5.2.1 and it works perfectly. The laptop is running 5.3.2 (I've also uninstalled and rolled back to 5.3.1 and get identical behavior). I'm using identical tenants, client id's, usernames, and passwords. If you just look at laptop-5.3.2 trace, you might think Okta is being stupid. But it doesn't have any problems with postman 5.2.1. Both traces have pretty much identical first requests to the widget that prompts for username and password so I don't know where it goes wrong from there.

[desktop-5.2.1.saz.zip](https://github.com/postmanlabs/postman-app-support/files/1423575/desktop-5.2.1.saz.zip)
[laptop-5.3.2.saz.zip](https://github.com/postmanlabs/postman-app-support/files/1423576/laptop-5.3.2.saz.zip)

As a side note: getting chrome developer tools to show up in the popup window that is handling the oauth2 flow doesn't seem to work in 5.3.1+ either. So these fiddler traces might be the best I can get you...

**Comment by fosple** [comment] 2017-11-23 11:38
Same problem here. Sometimes it works but sometimes the OAuth 2.0 Pop-up just shows a empty white page. 

However, I can't send you a bug report because the developer tools are not working in that window and the whole OAuth 2.0 communication is happening over HTTPS...

**Comment by fosple** [comment] 2018-01-03 11:37
Any update? @harryi3t

**Comment by fosple** [comment] 2018-01-04 10:59
I also made a video of the behaviour:
https://www.dropbox.com/s/opx18ppq8qnv2jr/20180104_Postman_bug.mov?dl=0

According to the title of the OAuth Popup the second request is not even triggered anymore. The title of the page stays "Postman OAuth 2.0".

Im using Version 5.5.0 (5.5.0) Standalone on MacOS.

**Comment by lphuberdeau** [comment] 2018-03-06 22:41
This may be related, but I've seen this through our reverse proxy logs while investigating this issue:

```
2018/03/06 22:33:54 [error] 16#16: *885 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: internal-name, request: "POST /auth/oauth2/authorize?response_type=code&state=test&client_id=strip&scope=read_only&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback HTTP/1.1", upstream: "http://127.0.0.1:5003/auth/oauth2/authorize?response_type=code&state=test&client_id=strip&scope=read_only&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback", host: "api.example.com", referrer: "https://api.example.com/auth/oauth2/authorize?response_type=code&state=test&client_id=strip&scope=read_only&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback"
```

The process works perfectly when testing with google's oauth 2.0 playground so it does not seem like the issue is on our side. My guess would be that PostMan does not read the response or response body.

**Comment by harryi3t** [comment] 2018-03-07 09:12
@jbrinkle can you update to latest Postman version and see if this issue still persists?

If still the issue is not resolved, can you help me with reproducing the issue? I have created an account on okta and tested this. Maybe the configuration of the app I created is different.

**Comment by lphuberdeau** [comment] 2018-03-07 14:55
Tested with 6.0.9, issue persists.

If the credentials are wrong, a response is provided immediately, but if a redirect is issued, it waits until the web server eventually times out.

**Comment by harryi3t** [comment] 2018-03-07 19:22
@lphuberdeau Can you help me reproduce this? Is the auth provider that you are using publicly accessible?

**Comment by lphuberdeau** [comment] 2018-03-08 22:43
After more a lot of tuning, we finally got it to work.

**Comment by harryi3t** [comment] 2018-03-09 06:07
@lphuberdeau Could you shed some light on what was the issue for you how did you get it to work?
Was there a issue with the auth provider or with Postman?

**Comment by lphuberdeau** [comment] 2018-03-09 13:38
Ultimately, the final issue was on our end.

However, several issues made the debugging harder than it had to be. None of the debugging consoles provided any information. The developer console did not show any activity in the network panel. The authentication window is completely locked down, preventing inspection of the provider's state.

It also seems like there is no way to accept a self-signed certificate, which we use for development environments. This forced much longer testing cycles by going through the build / deploy cycles.

**Comment by harryi3t** [comment] 2018-03-09 16:21
@jbrinkle Closing this issue. Let me know if you are still having issues. You can also mail me your auth-provider endpoint details. I can test it out for you. In most cases it is usually the auth-providers's issue to be not spec-complaint. But if it is issue on our end we will get it fixed ASAP.

**Closed as completed by harryi3t** 2018-03-09 16:21 UTC
Labels: Auth

**Comment by jbrinkle** [comment] 2018-03-09 23:14
Appears to be working for me. Thanks for following up. 👍

**Comment by cjaoude** [comment] 2018-07-20 15:23
for anyone trying to call the LinkedIn API, this resolves the `missing 'client_secret'` error after the Auth url response...

> You can try selecting `Send client credentials in body` which will send the `client_secret` in the request body instead of in the header.

Then use the `Bearer Token` authorization option when making API calls.
