### ISSUE TITLE
Can't capture requests in mac native app because I can't start a proxy server.

### ISSUE THREAD

**Issue by heathgr** [a85/POSTMan-Chrome-Extension#2764] opened 2017-02-27 22:31 UTC
Version/App Information:

 1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Mac app
 3. OS details: OS X 10.11.6
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: It has always been there.
 6. Expected behaviour: I'd expect a proxy server to start, and to get a notification that it has started as described in this documentation: https://www.getpostman.com/docs/capture_native
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

xml.js:22 Uncaught Error Uncaught ReferenceError: mode is not defined file:///Applications/Postman.app/Contents/Resources/app/js/common.js 4312 8 ReferenceError: mode is not defined(…)

 8. Screenshots (if applicable)

<img width="420" alt="postman_screenshot" src="https://cloud.githubusercontent.com/assets/7666356/23382811/de61b880-fd00-11e6-9000-0ec6613bd28a.png">

I'm trying to start a proxy server.  Here is what I'm doing:

1. I click on the satellite dish icon.
2. I click on connect.
3. The errors described above appear in the console.  Nothing else happens.

**Comment by SamvelRaja** [comment] 2017-02-28 05:15
Hey @heathgr the issue had been identified before, we are in track of it. You could continue working in our canary app which can be downloaded from [here](https://dl.pstmn.io/download/channel/canary/osx_64).

Duplicate of #2727

**Comment by heathgr** [comment] 2017-02-28 07:04
The canary app works like a charm.  Thanks for you help @SamvelRaja.

**Comment by SamvelRaja** [comment] 2017-03-03 05:07
@heathgr the fix has been rolledout in our 4.10.3 app. kindly update and verify the same 😄

**Closed as completed** 2017-03-03 13:39 UTC
Labels: bug, pending-close

**Comment by heathgr** [comment] 2017-03-03 17:32
Yep, it's working great!
