### ISSUE TITLE
Mystery grey dot character breaking request body

### ISSUE THREAD

**Issue by matthewmb** [a85/POSTMan-Chrome-Extension#6458] opened 2019-05-10 02:28 UTC
**Describe the bug**
A mystery grey dot character appeared within my JSON request body. This caused the body to be submitted as a string enclosed in double quotes, rather than JSON. I'm guessing this some sort of character encoding issue.

The grey dot was hardly visible and I wasn't aware that it was there (I thought it was either dust on my screen, or part of the visual code cues), so I had difficulty in troubleshooting why my request wasn't working.

**To Reproduce**
1. Import mystery grey dot collection into Postman: [Mystery grey dot.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/3164651/Mystery.grey.dot.postman_collection.json.zip)
2. Open postman console
3. Check request for weird grey dot, and observe the grey dot in the body. Submit request and observe body is submitted in double quotes
4. Check request for for no weird grey dot, submit request and observe body is submitted as expected

**Expected behavior**
If there are any unexpected/unknown characters like this, they are either more visible, or a warning is displayed

**Screenshots**
![mystery grey dot](https://user-images.githubusercontent.com/29061406/57498469-53e1d400-731f-11e9-9af0-f4dfd87d2bb8.png)

**App information (please complete the following information):**
 - App Type: Native 
 - Postman Version: 7.0.9
 - OS: Win 10 Pro 1803

**Comment by shamasis** [comment] 2019-05-10 05:01
Ah ... we do need to solve this together Watson! I do see the mystery dot. Further inspecting the json I discovered this character: “} ï»¿\r\n}”. The culprit has been lurking behind the closing brace as an extra character. I have a hunch that it got copied over while pasting data from some other source. The dot simply represented a white-space equivalent fharacter.

**Comment by matthewmb** [comment] 2019-05-10 05:43
I agree, it was probably from copy/pasting an external source. It would be useful if this dot was more visible, I didn't notice it existed for a long time.

**Comment by shamasis** [comment] 2019-05-14 07:02
Yeah. I agree. I can hardly see this dot when in a general monitor. High end phones and monitors with better colour reproduction is working just fine. 

@vkaegis - can you keep a track of this?

Closing the issue for now - since I know for a fact that there’s a bigger epic somewhere that tracks colour related issues. @vkaegis please add to your list.

**Closed as completed by shamasis** 2019-05-14 07:02 UTC
