### ISSUE TITLE
goes endless loop when specific environment param is passed

### ISSUE THREAD

**Issue by maheshjajadabbc** [a85/POSTMan-Chrome-Extension#1671] opened 2016-01-20 12:14 UTC
Steps:
1. Try to GET the request in the following format from postman; which is especially having an environment variable with a colon (:)
https://abc.{{env:}}.def.com/
2. Click on Send

**Actual Result:**
Loading.... message is shown in postman forver.
The request goes in an endless loop

_Customer Impact:_
User may wait to get the request finished.
One may not have any idea what to do next

**Expected Result:**
It should throw some 403 like errors, so that user can modify the request & pass on the correct request within time

_Work around_
When the endless loop occurred, one can click on 'Restet this tab' button

**Screenshot**
![2016_01_20_12_13_03_postman](https://cloud.githubusercontent.com/assets/10502322/12448643/5932746c-bf6f-11e5-84e8-f00372adf531.png)

**Comment by abhijitkane** [comment] 2016-01-20 16:41
@maheshjajadabbc I'm not able to reproduce this. Also, you'll need to set the XHR timeout (Settings>General) to 10000 or 20000s. The default setting of 0 will never time out.

Also, do you have an environment variable with the name `env:`?

**Comment by maheshjajadabbc** [comment] 2016-01-20 17:03
I have set the XHR timeout to a non-zero value. the problem is still happening. But yes you are right, this is happening for the variable which is not being set. I have set a variable called 'env', but not 'env:'.

Anyways this is not bothering me at all. I am not getting stucked with this issue anyway. This was just raised for your knowledge. You can ignore it.

**Comment by abhijitkane** [comment] 2016-01-20 17:07
Ah..managed to reproduce the issue with a non-zero timeout. Will add a fix for this in the next release. Chrome treats a URL with "http://{{" in a weird manner. Thanks for pointing this out.

**Comment by maheshjajadabbc** [comment] 2016-01-20 17:27
Yeah. Good to hear that you have managed to reporduce it. Thanks.

**Comment by abhijitkane** [comment] 2016-01-26 08:20
Fixed with v3.2.13.

**Closed as completed by abhijitkane** 2016-01-26 08:20 UTC
Labels: bug

**Comment by maheshjajadabbc** [comment] 2016-01-26 10:50
thanks Abhijit.
