### ISSUE TITLE
Postman Application on Windows 10  throws Parse: Parse Error -Reopened

### ISSUE THREAD

**Issue by Pr1Smiley** [a85/POSTMan-Chrome-Extension#2750] opened 2017-02-23 23:05 UTC
1. Postman Version:
Postman for Windows
Version 4.10.2
win32 10.0.14393 / x64
 2. App (Chrome app or Mac app):
Windows Application
 3. OS details:
Windows 10 Professional
 4. Is the Interceptor on and enabled in the app:
No
 5. Did you encounter this recently, or has this bug always been there:

 6. Expected behaviour:
Return result
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/25694929/23283040/89a7c240-f9e9-11e6-9df8-801d6806eac6.png)

![image](https://cloud.githubusercontent.com/assets/25694929/23283057/ab4bb9f6-f9e9-11e6-8022-8a44d08d3c8d.png)

tested rest interface via  postman application results in a parse error
tested the same with postman for chrome resulted in good response
removed authorization, tested with multiple  headers results  are the same

thanks

**Comment by vegetableman** [comment] 2017-02-27 12:37
@Pr1Smiley Thanks for posting this issue 👍 . Could you share screenshots of the `Postman Console` (Native app) and devtools (Chrome app) for the request?. To access those tools, you could refer: https://www.getpostman.com/docs/errors

**Comment by SamvelRaja** [comment] 2017-09-06 12:31
Since there is no activity in this issue, we are closing this now, feel free to reopen it if needed.

**Comment by trajano** [comment] 2017-10-17 18:28
I have the same issue but I can only use Postman Console rather than the Chrome App since I am not allowed to install extensions on Chrome.

I am also on Windows 10, but on my home computer (also Windows 10 but more current) it works correctly.

I notice is if I send in the `Authorization: Bearer token` header.

**Comment by trajano** [comment] 2017-10-17 18:28
![image](https://user-images.githubusercontent.com/110627/31682244-828e4bba-b347-11e7-9a7d-878631bf3b8f.png)

**Comment by sdnts** [comment] 2017-10-18 07:12
@trajano Do you think this has something to do with the response you're expecting? If possible, could you share a sample response you're expecting? Just the structure (you can replace sensitive information with dummy data) will be useful.

Also, which version of the app are you on?

**Comment by trajano** [comment] 2017-10-18 09:09
I think we can merge this with #3511

**Comment by Pr1Smiley** [comment] 2017-11-07 03:23
![0a8345e5-ea92-4db9-8c27-af7e60520a59](https://user-images.githubusercontent.com/25694929/32475670-aa440a4a-c338-11e7-81b2-ddf36685046f.GIF)

**Comment by Pr1Smiley** [comment] 2017-11-07 03:24
Sorry for the late response, had a few releases I had to get out

**Comment by Pr1Smiley** [comment] 2017-11-07 04:36
![image](https://user-images.githubusercontent.com/25694929/32477331-e61c3c2c-c342-11e7-94d3-ad9e1ddafc3b.png)

![image](https://user-images.githubusercontent.com/25694929/32477342-f7c1ba42-c342-11e7-8400-c0bff47f41cd.png)
![image](https://user-images.githubusercontent.com/25694929/32477348-083dff3e-c343-11e7-80c0-6a2f9cb39df3.png)

**Comment by trajano** [comment] 2017-11-07 04:40
What do you get if you use `curl`?

**Comment by Pr1Smiley** [comment] 2017-11-07 04:52
Have not tried it yet

**Comment by Pr1Smiley** [comment] 2017-11-07 05:02
hello,

Checked in fiddler works ok

![image](https://user-images.githubusercontent.com/25694929/32477821-9a245382-c346-11e7-9e7c-9eda9af57251.png)

**Comment by Pr1Smiley** [comment] 2017-11-07 05:13
Curl works also

**Comment by trajano** [comment] 2017-11-07 11:20
What's the output of `curl -v`? specifically looking at the resulting header part.

**Comment by VictorBadea** [comment] 2017-11-16 11:19
I also have this issue... it seems to be caused by when I manually add an Authorization token to the header.

EDIT: as in, if I remove that token... the call goes through and the server responds with a missing authorization response.

**Comment by claudio-incomedia** [comment] 2018-01-08 11:51
Same problem here. I simply get a Parse Error with no explanation about it.
Curl and chrome browser work fine.

**Comment by trajano** [comment] 2018-01-08 16:20
@claudio-incomedia post the output of `curl -v` pls

**Comment by claudio-incomedia** [comment] 2018-01-09 07:12
Here you go. It happens only with POST so I added "--data" to curl.

`curl -v --data "{ \"type\": \"import\", \"input\": { \"path\": \"E:\\\\yotis.iwzip\" }` `}"http://192.168.0.88:1024/operation` 
`*   Trying 192.168.0.88...` 
`* Connected to 192.168.0.88 (192.168.0.88) port 1024 (#0)` 
`> POST /operation HTTP/1.1` 
`> Host: 192.168.0.88:1024` 
`> User-Agent: curl/7.47.0` 
`> Accept: */*` 
`> Content-Length: 60` 
`> Content-Type: application/x-www-form-urlencoded` 
`> ` 
`* upload completely sent off: 60 out of 60 bytes` 
`< HTTP/1.1 200 OK` 
`< Date: Tue, 09 Jan 2018 07:09:16 GMT` 
`< Server: ICM HTTP Adapter` 
`< Accept-Ranges: none` 
`< Connection: close` 
`< Content-Length: 123` 
`< ` 
`* Closing connection 0` 
`{"id":0,"type":"import","status":"waiting","progress":0,"log":[],"error":"","input":` `{"path":"E:\\yotis.iwzip"},"output":{}}`

Thanks

**Comment by franjo2016** [comment] 2018-01-25 22:54
I started getting same issue on latest postman (5.5.2) after importing a collection from a file. Everything else worked ok, but the imported ones kept giving "parse error" and "no response". Very annoying. Exact same collection imported in chrome app worked just fine.

**Comment by Pr1Smiley** [comment] 2018-02-13 21:02
Any reason why this thread was closed with no resolution? 

Thanks

On 2018-01-25 16:54, Franjo Markovic wrote:

> I started getting same issue on latest postman (5.5.2) after importing a collection from a file. Everything else worked ok, but the imported ones kept giving "parse error" and "no response". Very annoying. Exact same collection imported in chrome app worked just fine. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/postmanlabs/postman-app-support/issues/2750#issuecomment-360628078
[2]

**Comment by trajano** [comment] 2018-02-13 23:06
#3511

**Comment by SubhaRaju** [comment] 2018-08-07 08:16
Same issue exists for me.Could some one help me on this

**Closed as completed** 2018-08-07 09:53 UTC
Labels: bug

**Comment by Pr1Smiley** [comment] 2018-08-15 14:31
Closed again without no resolution?

**Comment by adrianknight89** [comment] 2018-11-21 15:41
I'm getting this issue all of a sudden.

**Comment by Pr1Smiley** [comment] 2019-03-13 19:58
Still No resolution

**Comment by matejdro** [comment] 2019-04-20 08:36
Same issue here with same symptoms than @VictorBadea . Request works without token (returns 401), but does not work when adding token.

* Windows Postman does NOT work
* Chrome postman works (but it is deprecated)
* Fiddler works
* curl works

**Comment by Pr1Smiley** [comment] 2019-04-20 13:54
This issue has been going on for the past 3years and still no resolution? Postman team should look into fixing this bug in your software instead of just closing the complaints hoping no one will reopen again. Smh

**Comment by matejdro** [comment] 2019-04-21 07:19
I think it was closed because it was duplicate. #3511 is the main issue now.
