### ISSUE TITLE
When I save example for request, the data from request is wiped or changed.

### ISSUE THREAD

**Issue by erudenko** [a85/POSTMan-Chrome-Extension#12263] opened 2023-08-24 03:54 UTC
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have recorded a vide about the issue.

The short description is:
When I save example for request, the data from request is wiped or changed. URL of request is changed and the value is got from previous reques, body is missing, custom headers is missing.

Tests and pre-script are wiped as well.

https://github.com/postmanlabs/postman-app-support/assets/463313/a3880226-df17-40f4-b5ee-3fba8a807937

### Steps To Reproduce

1. Create request
2. Fill URL, headers, tests
3. run script
4. create example from script

### Screenshots or Videos

https://cln.sh/YKMFmw9V

### Operating System

MacOS

### Postman Version

10.17.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by kartikjain26** [comment] 2023-08-24 06:46
@erudenko Thanks for reporting the issue. We'll look into this and keep the thread updated for the fix.

**Comment by kartikjain26** [comment] 2023-08-29 06:08
@erudenko Hey, we have released the fix for this on Postman web (10.17.3) and Desktop app. Could you try the web or update your app and give it a go.

**Comment by kartikjain26** [comment] 2023-08-31 07:14
@erudenko Could you confirm if the issue is resolved for you ?

**Comment by kartikjain26** [comment] 2023-09-06 10:07
Closing this issue as it is resolved on production desktop and web apps now.

**Closed as completed by kartikjain26** 2023-09-06 10:07 UTC
Labels: bug, collections
