### ISSUE TITLE
Documenter collections showing error in Safari

### ISSUE THREAD

**Issue by traylewin** [a85/POSTMan-Chrome-Extension#7884] opened 2020-01-08 02:49 UTC
**Describe the bug**
When using Safari and visiting a doucmentor page, instead of seeing the Postman Collection, there is only this error = "Could not load examples for this collection"

**To Reproduce**
1. Go to https://documenter.getpostman.com/view/3606954/S1TR3ewq?version=latest
2. See error

**Expected behavior**
Should see the collection

**App information (please complete the following information):**
 - Safari Version 13.0.4 (14608.4.9.1.4)
 - OS: macOS Mojave 10.14.6 (18G103)

**Comment by Cazaimi** [comment] 2020-01-09 13:11
@traylewin, tried hitting the public documentation link with Safari, but could not reproduce this issue. Is this happening only for a particular language? If so, could you post that information here? Thanks!

@Raja-Simha , could you tag this issue to `product/documentation`?

**Comment by eborey** [comment] 2020-01-17 19:50
It may help. I recently had the same issue with my collection. I was accessing the doc. with Safari from a pinned tab. We found that the issue was only within the pinned tab (maybe some cache problem or bad URL). Just unpin it and pin it again.

**Comment by DannyDainton** [comment] 2022-06-27 11:09
Unable to replace this issue on the Safari with the latest version - Going to close this issue for not but if you can recreate this in the latest version we can look to reopen it again.

**Closed as completed by DannyDainton** 2022-06-27 11:09 UTC
Labels: product/documentation, blocked/need-info
