### ISSUE TITLE
All request bodies have been deleted upon accepting a merge request

### ISSUE THREAD

**Issue by Wotuu** [a85/POSTMan-Chrome-Extension#8099] opened 2020-02-24 15:19 UTC
**Describe the bug**
Today we were using Postman as normal. After someone having created a Branch, doing their changes, and merging their changes back into the main branch, all bodies for ALL REQUESTS have been deleted. They could not be restored. We have to use a backup and manually copy over all bodies for over 600+ requests in order to continue with our work.

**To Reproduce**
What happened was:
1. Main Collection
2. Branch from Main Collection
3. Merge Branch into Main Collection
4. Main Collection lost every request body

**Expected behavior**
Not to get data deleted when performing a merge.

**Screenshots**
Not applicable

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.19.0
 - OS: Windows 10 18362.592

**Additional context**
I've tolerated a lot of bugs and issues but this issue is unacceptable. Our company pays a lot of money to use Postman, this cannot happen. This hurt my faith in the product. Who tells when it happens again and we again have to invest hours to get all data back?

If you want UUIDs of the Collections I'll be happy to supply them so you can investigate where this went wrong.

**Comment by ankit-m** [comment] 2020-02-25 08:16
Hi @Wotuu,

I have created a ticket on our internal tracker to investigate this issue. It would be great if you could provide the following details over email (help@postman.com)

1. Collection UUID (Open the collection on the web via `View in web` option and you will find the ID in the URL `../collections/<uuid>/..`)
2. What changes were made in the forked collection?
3. Were there any conflicts while merging?

**Comment by Wotuu** [comment] 2020-02-25 10:37
Hi Ankit,

I have sent the requested information along with a full overview of the resulting merge request to help@postman.com. Please let me know either here or by e-mail if you need more information. Thank you.

**Comment by ankit-m** [comment] 2020-02-26 11:23
We have been able to identify the root cause and are in the process of deploying a fix.

**Comment by Wotuu** [comment] 2020-03-06 10:12
Hi Ankit,

As discussed you may not have deployed the fix yet, but I just want to let you know we've just had the issue pop up again. In case you did deploy the fix it was not effective. I will be in contact with support to resolve the issue; the Restore function (Collection -> Changelog) does not seem to be functioning properly unfortunately.

**Comment by ash007-postman** [comment] 2020-03-06 11:43
@ankit-m Can you please take a look at it, more info can be found at Zendesk.

**Comment by Wotuu** [comment] 2020-03-09 14:15
Thank you for the communication of the past few days, good to hear this was taken seriously and the damage was restored skillfully 👍 . As for me this issue can be closed, but I'll leave that up to you guys to close it when you have fully resolved the issue internally.

**Comment by Raj-postman** [comment] 2020-03-12 11:44
@ankit-m Similar issue reported, after merging the forked collection although it shows as a successful merge - the request bodies are completely empty.

Re-merging the forked collection seemed to have fixed the issue in this case.

**Comment by VicKetchup** [comment] 2020-03-16 12:08
@Raj-postman got something similar on our end. When merging collection it is reporting that a POST request has been modified, however doesn't specify what the change is. If this is merged, the request body gets removed in the parent collection. Doing repeated merge shows that the body is now being added and adds it to the parent collection as well.
@ankit-m could share the details for our collections if this would help.

**Comment by ankit-m** [comment] 2020-03-16 12:50
@VicKetchup can you email us the collection details at help@postman.com?

**Comment by VicKetchup** [comment] 2020-03-16 14:49
@ankit-m Email sent, hope it helps :)

**Comment by ankitjaggi** [comment] 2020-03-26 05:55
The underlying problem has been identified and fixed for all affected users. If you're still facing issues with bodies disappearing, try restoring the collection to an older change or contact us at help@getpostman.com. Existing forks should not be causing any issues anymore.

**Closed as completed by ankitjaggi** 2020-03-26 05:55 UTC
Labels: bug, version-control
