### ISSUE TITLE
Postman API (api.getpostman.com) returning UnknownHostException

### ISSUE THREAD

**Issue by andmill** [a85/POSTMan-Chrome-Extension#4982] opened 2018-08-07 09:20 UTC
## App Details:
Postman for Windows
Version 6.2.2
win32 10.0.17134 / x64

## Issue Report:
1. Did you encounter this recently, or has this bug always been there:
Encountered every night over the weekend (Fri, Sat, Sun, and Mon) and once previously a couple of weeks ago. Jenkins HTTP request unable to connect to the Postman API to download collections (api.getpostman.com).

2. Expected behaviour:
Latest collection downloaded from the Postman API endpoint GET https://api.getpostman.com/collections/<uuid>. Jenkins jobs are scheduled to build at around midnight and run API tests using newman in the following workflow:
•	Download latest postman collection and save to Jenkins workspace
•	Download latest postman environment and save to Jenkins workspace
•	Run a collection/subfolder using newman

3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

Output from Jenkins console:

Building in workspace C:\Program Files\Jenkins1\workspace\Pay_Scalability_Postman_Sanity_Payments
HttpMethod: GET
URL: https://api.getpostman.com/collections/<uuid>
X-Api-Key: *****
Sending request to url: https://api.getpostman.com/collections/<uuid>
Treating UnknownHostException(api.getpostman.com) as 404 Not Found

4. Screenshots (if applicable)
N/A

5. Steps to reproduce the problem
Run the above request in the middle of the night to download the latest collection; api.getpostman.com returns UnknownHostException.
NOTE:
This same step has been working for a couple of months and has worked this morning when I built the Jenkins job manually today when I got into work.

**Comment by ankitjaggi** [comment] 2018-08-09 08:41
Hey @andmill! Is this something that you're still facing, or was it an intermittent issue at that time?

**Comment by andmill** [comment] 2018-08-09 09:50
Hi @ankitjaggi, in my test runs over the weekend, this was seen Friday, Saturday, Sunday and Monday nights. I have not seen the issue during the day or on Tuesday/Wednesday night into today.

**Comment by deepakpathania-zz** [comment] 2018-12-11 06:28
Couldn't reproduce. Closing this for now, please let us know if the issue still persists and we'd be happy to dig deeper.

**Closed as completed by deepakpathania-zz** 2018-12-11 06:28 UTC
Labels: bug, product/postman-api
