### ISSUE TITLE
PostMan issue in chrome

### ISSUE THREAD

**Issue by shahidsabadia** [a85/POSTMan-Chrome-Extension#2114] opened 2016-06-08 15:42 UTC
Postman crashes as soon as its starts by clicking the extension in chrome. I tried to install again after uninstalling but same issue persist.

I see in chrome console that error occurred at: requester.js:112 Uncaught TypeError: Cannot assign to read only property 'indexedDB' of object '#<Window>'

Please include the following:
1. Postman Version: 0.8.4.8
2. App (Chrome app or Mac app): Chrome Extension
3. OS details: Win 7 64 bit
4. Is the Interceptor on and enabled in the app: NA
5. Did you encounter this recently, or has this bug always been there: Recently,Since 2 days
6. Expected behaviour:
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   ![untitled](https://cloud.githubusercontent.com/assets/19795617/15900620/bae72b82-2dbd-11e6-94f1-8efdd230238f.jpg)

Some guidelines: 
1. Please file Newman-related issues at https://github.com/postmanlabs/newman/issues
2. If it’s a Cloud-related issue, or you want to include personal information like your username / collection names, mail us at help@getpostman.com
3. If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://getpostman.com/docs.

**Comment by abhijitkane** [comment] 2016-06-09 09:44
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/2101

**Closed as completed by abhijitkane** 2016-06-09 09:44 UTC
