### ISSUE TITLE
UI Inconsistent when using '&' in query parameters

### ISSUE THREAD

**Issue by lemvigh** [a85/POSTMan-Chrome-Extension#7813] opened 2019-12-17 12:40 UTC
I have a simple get request for a search API. In the Query Params section I have:
key="q" and value="&"
In the URL part of the UI it renders the resulting URL as:
[BaseURL]/search?q=%26
![image](https://user-images.githubusercontent.com/4123075/70996134-736d8600-20d2-11ea-94de-8d1b476f93c4.png)

From this it looks like it has encoded the "&". When I press Send it seems like it is sending the "&" not the encoded "%26". I don't know what is intended, but I think the UI at least is confusing. I would have expected the encoded value to be send when it is shown in the URL.

**Comment by codenirvana** [comment] 2019-12-17 13:33
@lemvigh You are right, the encoded value should be sent.
We are working on this right now and will let you know when the fix is available in our canary or production channel.

Closing as duplicate of #7758, please subscribe to the original issue thread.

**Closed as completed by codenirvana** 2019-12-17 13:33 UTC
Labels: encode-decode, duplicate, product/runtime

**Comment by vikiCoder** [comment] 2020-03-09 09:14
Hi, this is fixed in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). You can see more details about the fix at #8154
