### ISSUE TITLE
Alphabetize Variables?

### ISSUE THREAD

**Issue by donrolling** [a85/POSTMan-Chrome-Extension#9844] opened 2021-04-15 20:55 UTC
**Is your feature request related to a problem? Please describe.**
Yes. The problem is that I often find it difficult to locate a specific variable in an environment.

**Describe the solution you'd like**
I would like either for the variables to be alphabetized, or to have an option to alphabetize them. It is hard to locate specific variables otherwise.

**Describe alternatives you've considered**
Exporting the variables to JSON, converting them to CSV, sorting them in Excel, converting back to JSON and reimporting them. Seems like a pain though.

**Additional context**
![image](https://user-images.githubusercontent.com/1778167/114937063-e855ea80-9e02-11eb-9199-4cda3ef9f5bc.png)

**Comment by giridharvc7** [comment] 2021-04-20 07:14
Duplicate of #982 
Tracking it there!

**Closed as completed by giridharvc7** 2021-04-20 07:14 UTC
Labels: feature, variables, organizing-environments, user-interface, product/runtime
