### ISSUE TITLE
Adding support for automatically tracking active tab item in sidebar

### ISSUE THREAD

**Issue by imtrobin** [a85/POSTMan-Chrome-Extension#8437] opened 2020-05-05 05:17 UTC
Hi, it's easy to get lost where the tab is in the Collections when they are many of them . Are you able to implement to highlight the the collection when we are focused on the tab. This is similar to "Track Active Item in Solution Explorer" in visual studio

**Comment by kamalaknn** [comment] 2020-05-17 03:53
Duplicate of #7099

**Closed as completed by kamalaknn** 2020-05-17 03:53 UTC
Labels: feature, tabs
