### ISSUE TITLE
Incorrect steps to update Snap package

### ISSUE THREAD

**Issue by katarsenina** [a85/POSTMan-Chrome-Extension#6601] opened 2019-05-27 15:44 UTC
**Describe the bug**
No Update button if go by steps in message:
_Your team updated to Postman v7.0. To keep your collections and workspaces in sync with your team, you must also update to v7.0 by going to Icon setting > Settings > Update._

**To Reproduce**
1. Open Postman and read the notification
2. Go to 'Settings icon(top right corner) -> Setting -> Update'
3. Find  'Update' button.

**Expected behavior**
There is `Update` button in Settings pop up window.

**Screenshots**
![DeepinScreenshot_select-area_20190527183115](https://user-images.githubusercontent.com/37741916/58429593-14511100-80af-11e9-8aa9-8448b77d4abb.png)

**App information (please complete the following information):**
- Postman for Linux
- Version 6.7.1
- linux 4.18.0-20-generic / x64

**Additional context**

**Comment by numaanashraf** [comment] 2019-05-27 16:36
@katarsenina It looks like you are using a Snap variant of Postman for Linux, which need to be updated via the command line. Please follow the instructions here to update - https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/migrating_to_v7/#updating-app-to-postman-v7-after-migration.

Let's keep this issue open till we improve our messaging for Snap updates.

**Comment by kamalaknn** [comment] 2019-08-01 11:02
This is a duplicate of #6449

I'm closing this as a duplicate, please follow the parent thread for updates.

**Closed as completed by kamalaknn** 2019-08-01 11:02 UTC
Labels: bug
