### ISSUE TITLE
Will postman consider internationalization in the future? For example, simplified Chinese

### ISSUE THREAD

**Issue by TOP-LH** [a85/POSTMan-Chrome-Extension#9967] opened 2021-05-24 01:38 UTC
Will postman consider internationalization in the future? For example, simplified Chinese

**Comment by DannyDainton** [comment] 2021-05-24 10:37
I'm going to close this as this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/3126

**Closed as completed by DannyDainton** 2021-05-24 10:37 UTC
Labels: duplicate
