### ISSUE TITLE
Closing a newly openend window exits postman

### ISSUE THREAD

**Issue by midrissi** [a85/POSTMan-Chrome-Extension#3664] opened 2017-10-24 15:05 UTC
## App Details:

```
Postman for Windows
Version 5.3.1
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:

**Encounter recently**

 2. Expected behaviour:

Closing a newly openend window should not exit postman.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

**No errors**

 4. Screenshots (if applicable)

**No screenshots**

1. Open new postman window (Ctrl+Shift+N)
2. Close any postman window
3. Postman exits

**Comment by deepakpathania-zz** [comment] 2017-10-24 16:13
@midrissi Could not reproduce this on the Linux app. Might be specific to the windows app. 
@madebysid Please check.

**Comment by prashantagarwal** [comment] 2017-10-25 06:55
@midrissi We are already tracking this issue here #3222. Closing this as duplicate issue.

**Closed as completed by prashantagarwal** 2017-10-25 06:55 UTC
