### ISSUE TITLE
Request to improve the in-app "warning messages" when leaving the team

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#6825] opened 2019-07-02 03:10 UTC
Hi Team, 

The fact is that the shared collections and the archived collections are associated with the team and If someone by mistake or deliberately exit from the team they will end up losing their data. So, it is important to enhance the in-app flow and make it clear enough for the user to act accordingly. 

Currently, when a member attempts to exit from the team, he gets the following warning:
![image](https://user-images.githubusercontent.com/40994626/60479218-a0ec8180-9ca2-11e9-8968-061366c95123.png)
Similarly, for the last member of a team:
![image](https://user-images.githubusercontent.com/40994626/60479259-c7122180-9ca2-11e9-9898-322330cb2c9a.png)

Either of these warning messages gives clarity on "**what happens to the data after leaving the team**" 

So here are a few suggestions for creating a better user experience.

1. The selected default button for the above action should be **Cancel**, not **Proceed**. 
2. Should be explicit that all Data associated with the team in both Personal and Team workspaces will be deleted and not recoverable. 
3. Upon clicking on Proceed, ask for a second confirmation which says “**Delete My Team and All the Data in Personal and Team Workspaces**”.
4. There should also be a link included in the above description to “**Export Postman Data”**

**Comment by preethammavin** [comment] 2019-07-02 04:42
@Ramya-From-Postman there seems to be confusion here, there is no data deleted when a user leaves the team. When a user leaves the team the shared collections remain with the team as shared collections are team entities, the collections created by the user which are not shared with the team remain with the user. 

We will improve the second part where the communication of what happens to the team when the last person leaves the team looks like.

**Comment by Ramya-From-Postman** [comment] 2019-07-02 05:04
@preethammavin you are right. Explicitly mentioning **When a user leaves the team, the shared collections remain with the team as they are the team entities**" will help users who want to create a copy/duplicate of **their collection** that was shared with the team before they exit.

**Comment by Kenblair1226** [comment] 2019-07-03 09:20
I think it's reasonable to warn the user that the shared collection will not be accessible anymore even it's the user himself/herself shared.

**Comment by sankalp0o** [comment] 2019-07-05 13:50
Thanks @Kenblair1226 , we'll look at improving the communication!

**Comment by cyrielle-hada** [comment] 2019-07-05 14:07
Duplicate of [6751](https://github.com/postmanlabs/postman-app-support/issues/6751)

**Comment by sankalp0o** [comment] 2019-07-08 00:16
Closing this in favor of #6751

**Closed as completed by sankalp0o** 2019-07-08 00:16 UTC
Labels: feature, user-interface, Roles and Permissions
