### ISSUE TITLE
Tests don't have directory path information in the runner

### ISSUE THREAD

**Issue by KyryloKuchuk** [a85/POSTMan-Chrome-Extension#9464] opened 2021-01-26 10:43 UTC
Environments:
Postman for Windows
Version 8.0.2

Preconditions:
- Create a collection with three directories inside
Steps to reproduce:
- Run collection in the runner
- Move focus to any test to display a tooltip with the full request's directory path.

Expected result:
Tooltip displayed as in previous 7.x.x version

Actual result:
Tooltip doesn't display.
![image](https://user-images.githubusercontent.com/45817511/105835128-b4211980-5fcb-11eb-97fc-352aa5feca04.png)

**Comment by mccannt** [comment] 2021-01-26 13:59
Thanks for the report @KyryloKuchuk we are looking into the cause of this.

**Comment by ManiacDC** [comment] 2021-01-27 19:57
Thanks @mccannt . Noticed this as well and this functionality is pretty important for us.

**Comment by vdcardenas** [comment] 2021-01-29 12:47
Yeah, I came to report this too. In collections with thousands of requests, this functionality is essential to identify the failed test.
Getting back to functionality would be great news.

**Comment by mccannt** [comment] 2021-04-13 00:08
This should now be fixed in recent versions of the application. 
Closing out this issue, if you are still experiencing issues please reach out.

**Closed as completed by mccannt** 2021-04-13 00:08 UTC
Labels: bug, collection-runner, product/runtime
