### ISSUE TITLE
Environment variable in query param only shows two curly braces but not var

### ISSUE THREAD

**Issue by etabackman** [a85/POSTMan-Chrome-Extension#7316] opened 2019-09-13 13:16 UTC
**Describe the bug**
Sometimes, an environment var in the query params get chopped off in the key value editor so that it only shows two curly braces but not the var.

**To Reproduce**
- Create a request with a query param as shown in the screenshot.
- Open the Params tab.
- The value is corrupted.
- The request sent does not include the proper query param.

**Expected behavior**
Expected value to be what I entered.

**Screenshots**
![Screen Shot 2019-09-13 at 16 08 01](https://user-images.githubusercontent.com/8046643/64865102-3f9d4300-d641-11e9-9c95-aa37ca16ea30.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.6.0
 - OS: macOS Mojave 10.14.5

**Comment by codenirvana** [comment] 2019-09-18 08:14
Duplicate of #5779

@etabackman Its a known issue with variables containing `#` and you can find more detail about what it's not supported here: https://github.com/postmanlabs/postman-app-support/issues/5779#issuecomment-465018548

**Closed as completed by codenirvana** 2019-09-18 08:14 UTC
Labels: bug, variables, data-editor, duplicate, request-sending, product/runtime

**Comment by shamasis** [comment] 2020-03-09 12:40
This should not be resolved. More details at #8154 @etabackman
